import type { PracticeTask, GrammarConceptId, ErrorCategory } from "./learning-model";

const choice = (id: string, prompt: string, options: string[], answer: number, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "choice", prompt, options, answer: options[answer], evidence, feedback, conceptId, errorType, ...extra });
const range = (id: string, prompt: string, answer: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "range", prompt, options: [], answer, evidence: answer, feedback, conceptId, errorType, ...extra });
const link = (id: string, prompt: string, pairs: Array<[string, string]>, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "link", prompt, links: pairs.map(([source, target]) => ({ source, target })), options: [...new Set(pairs.map(([, target]) => target))], answer: JSON.stringify(pairs.map(([, target]) => target)), evidence, feedback, conceptId, errorType, ...extra });
const order = (id: string, prompt: string, blocks: string[], distractors: string[], evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "order", prompt, options: [...blocks, ...distractors], answer: JSON.stringify(blocks), evidence, feedback, conceptId, errorType, ...extra });

export const passage2000P2Practice:Record<string,PracticeTask[]>={
"p2-s1":[order("being-subject","拼出完整主系表。",["Being a man","has always been","dangerous"],[],"Being a man has always been dangerous","Being a man整体作主语；has been是完成时系动词，dangerous为表语。","nonfinite-subject","subject",{hintWords:["Being","has","been","dangerous"]})],
"p2-s2":[link("ratio-scopes","将三个数字或比例接回各自的统计范围。",[["105 males / 100 females","出生时男女比"],["near balance","成年时的比例"],["twice as many women as men","70岁群体内男女数量比较"]],"among 70-year-olds there are twice as many women as men","twice比较70岁群体的数量，不比较寿命长度；ratio承接出生比例。","comparison-scope","attachment",{hintWords:["born","maturity","twice","among","for every","drops to near balance","at the age of maturity","twice as many women as men"],mapRevealsAnswer:true}),choice("born-role","born与are在第一分句中是什么关系？",["are是存在句谓语；born后置修饰males","are born共同构成紧邻的被动谓语","born是另一个过去时谓语"],0,"There are about 105 males born","存在句的实际主语是males，born说明出生的男性；不能跨过名词把are born机械连成被动。","nonfinite-participle","predicate",{hintWords:["There","are","born"]})],
"p2-s3":[choice("progressive-passive","is being changed同时表达哪两点？",["现在正在发生、主语是被改变者","过去已经完成、主语主动改变别人","未来可能发生、施事已明确"],0,"is being changed","is承担现在时，being changed组成进行中的被动；改变者未出现。","passive-voice","predicate",{hintWords:["is","being","changed"]})],
"p2-s4":[choice("do-substitute","girls do中的do替代什么？",["survive","change","search for a mate"],0,"boy babies survive almost as well as girls do","do避免重复survive；almost仍保留接近，并非完全相等。","comparison-scope","reference",{hintWords:["do","as","almost","almost as well as"]})],
"p2-s5":[range("means-boundary","划出means的完整宾语从句，保留嵌套修饰。","that, for the first time, there will be an excess of boys in those crucial years when they are searching for a mate","when从句属于years的修饰，外层that内容一直到mate。","clause-object","clause-boundary",{hintWords:["that","when","means"],leaksToTaskIds:["years-reference"]}),link("years-reference","匹配这句话的指代和内部修饰。",[["This","男婴存活率接近女婴的变化"],["when they are searching for a mate","修饰years"],["they","boys"]],"in those crucial years when they are searching for a mate","when限定寻找配偶的年龄段；This承接上句变化，不指后面的某一个男孩。","reference-pronoun","reference",{hintWords:["This","when","they","years","searching for a mate"],mapRevealsAnswer:true})],
"p2-s6":[order("chance-passive","保留主语中心及被动谓语，修饰语留在池中。",["another chance","has been removed"],["More important","for natural selection"],"another chance for natural selection has been removed","chance是被移除者，natural selection在for短语中说明机会属于谁。","subject-head","subject",{hintWords:["chance","has","been","removed"]})],
"p2-s7":[link("survival-event","分清限定谓语、非谓语执行者与代词。",[["depended","全句限定谓语"],["a baby","surviving的逻辑主语"],["its","回指baby"]],"the chance of a baby (particularly a boy baby) surviving depended on its weight","of后是baby surviving这件事，括号只突出男婴；不能让chance成为存活者。","nonfinite-subject","subject",{hintWords:["surviving","depended","its","of","the chance of a baby (particularly a boy baby) surviving","depended on"],mapRevealsAnswer:true})],
"p2-s8":[choice("weight-deviation","A kilogram too light or too heavy应怎样理解？",["比适宜体重轻或重一公斤的情形","总共体重只有一公斤的婴儿","所有男婴都比女婴轻一公斤"],0,"A kilogram too light or too heavy","kilogram给偏差幅度；原文没有给适宜体重具体值，almost certain也保留几乎的程度。","comparison-scope","translation",{hintWords:["kilogram","too","light","heavy","too light or too heavy"],mapRevealsAnswer:true})],
"p2-s9":[choice("it-difference","it makes almost no difference中的it接回什么？",["体重过轻或过重的偏差","婴儿的性别完全相同","自然选择的某位代理人"],0,"Today it makes almost no difference","it概括上一句情形；almost no difference表示几乎不影响存活，不是从来没有体重差异。","reference-pronoun","reference",{hintWords:["it","difference","almost","makes almost no difference"],mapRevealsAnswer:true})],
"p2-s10":[link("cause-agent","把原因、程度和因素义区分开。",[["Since","引出原因"],["much of the variation","差异中很大一部分"],["agent of evolution","发挥进化筛选作用的因素"]],"Since much of the variation is due to genes, one more agent of evolution has gone","Since译由于，不给起始时间；many/much不能换成全部，agent不是人。","lexical-context","attachment",{hintWords:["Since","much","agent","genes","is due to","agent of evolution"],mapRevealsAnswer:true})],
"p2-s11":[link("colon-explanation","匹配冒号后的两项及其作用。",[["stay alive","保持存活，alive为表语"],["have fewer children","留下更少后代，children为宾语"],["冒号后的并列结构","解释another way的具体内容"]],"stay alive, but have fewer children","生存与繁殖都关系到自然选择；这里用祈使形式说明进化意义的损失。","basic-svc","attachment",{hintWords:["stay","alive","have","fewer","stay alive","have fewer children"]})],
"p2-s12":[choice("fertility-degree","Few people are as fertile as in the past保留哪个意思？",["很少有人达到过去那样的生育水平","所有人都彻底丧失生育能力","土地都比过去更肥沃"],0,"Few people are as fertile as in the past","Few有否定倾向但不是零；people决定fertile谈人的生育。","lexical-context","vocabulary",{hintWords:["Few","fertile","past","as fertile as"]})],
"p2-s13":[choice("exception-scope","哪些限制使‘无人有15个孩子’不成立？",["Except给例外，very few仍允许少数存在","some表示所有群体","15是全部女性的合计人数"],0,"Except in some religious communities, very few women have 15 children","某些宗教群体在概括之外；极少也不等于完全没有。","comparison-scope","option-logic",{hintWords:["Except","some","few","except in","very few women"],mapRevealsAnswer:true})],
"p2-s14":[order("number-agreement","拼出主系表，时间、of和like修饰留在池中。",["the number","has become","average"],["Nowadays","of births","like the age of death"],"the number of births, like the age of death, has become average","中心number是单数；like短语不是并列主语，所以has并不与births或death一致。","subject-head","subject",{hintWords:["number","like","has","average","the number of","like the age of death","become average"]})],
"p2-s15":[choice("roughly-most","哪种改写准确保留本句限制？",["大多数人的后代数量大致一样","每个人的孩子数精确相等","无人有任何后代"],0,"Most of us have roughly the same number of offspring","Most限制人数范围，roughly限制精确程度，两项都不能丢。","comparison-scope","translation",{hintWords:["Most","roughly","same","roughly the same number of offspring"],mapRevealsAnswer:true})],
"p2-s16":[link("two-subjects","把远距离主谓与不定式内部角色对应起来。",[["differences / the opportunity","have diminished的两个并列主语"],["natural selection","to take advantage的逻辑主语"],["it","人与人存在差异这一情况"]],"differences between people and the opportunity for natural selection to take advantage of it have diminished","and并列differences与opportunity；for说明不定式执行者，it保留原文单数指代形式。","nonfinite-infinitive","subject",{hintWords:["differences","opportunity","for","it","diminished"],mapRevealsAnswer:true})],
"p2-s17":[choice("what-subject","what除了连接宾语从句，还在内部做什么？",["作is happening的主语","作shows的主语","没有句法成分，直接换that即可"],0,"what is happening","从句没有另一个主语，what本身表示正在发生的事情。","clause-object","subject",{hintWords:["what","happening"]})],
"p2-s18":[link("wealth-poverty","将两项社会处境与各自人群匹配。",[["wealth","大城市的少数人"],["poverty","其余部落民族"]],"wealth for a few in the great cities and poverty for the remaining tribal peoples","wealth与poverty是offers的并列宾语；这句话明确保留贫富差别。","basic-svo","attachment",{hintWords:["wealth","few","poverty","tribal","peoples"],mapRevealsAnswer:true})],
"p2-s19":[link("power-comparison","匹配数字、范围和比较基准。",[["80%","自然选择效力的损失比例"],["upper-middle-class India","数字所适用的中上阶层"],["the tribes","对照的部落群体"]],"natural selection has lost 80% of its power in upper-middle-class India compared to the tribes","80%修饰power，不是人口；数字只明确给中上阶层相对部落的损失，不推出贫富群体都归零。","comparison-scope","option-logic",{hintWords:["power","upper-middle","class","compared","tribes","compared to"],mapRevealsAnswer:true,leaksToTasks:[{sentenceId:"p2-map",taskId:"india-percent"}]}),link("absolute-explanation","区分破折号解释与主句骨架。",[["The grand mediocrity of today","主句主语"],["everyone","being的逻辑主语"],["means","主句限定谓语"]],"everyone being the same in survival and number of offspring","everyone being是独立主格解释；being不与means争夺主句谓语位置。","nonfinite-participle","predicate",{hintWords:["everyone","being","means","mediocrity"]})],
"p2-s20":[range("semicolon-boundary","只划出means后的宾语从句。","that evolution is over","分号后the biological Utopia另起主谓，不属于that从句。","clause-object","clause-boundary",{hintWords:["that","means","over","evolution is over"]})],
"p2-s21":[choice("little-change","little physical change表示什么程度？",["身体变化很少","身体完全没有任何变化","身体变化极大"],0,"little physical change","little修饰不可数change，倾向于很少，不能加强成绝对零。","comparison-scope","option-logic",{hintWords:["little","physical","change"],mapRevealsAnswer:true})],
"p2-s22":[choice("other-species","No other species中的other以谁为比较基准？",["人类","只有男婴","机器这个物种"],0,"No other species fills so many places in nature","文章讨论人类，other排除人类以外的物种；places说自然环境中的位置。","reference-pronoun","reference",{hintWords:["other","species","places"],mapRevealsAnswer:true})],
"p2-s23":[order("lives-bodies","保留两组对照主谓，时间留在池中；不补入省略词。",["our lives","have been transformed","but our bodies","have not"],["in the past 100, 000 years","even the past 100 years"],"our lives have been transformed but our bodies have not","后半省略been transformed；省略理解可以补足，原文主干和作答仍只用实际词。","passive-voice","predicate",{hintWords:["lives","bodies","transformed","not","have been transformed"],mapRevealsAnswer:true})],
"p2-s24":[link("two-did","将主句与原因从句中不同角色对应起来。",[["did not evolve中的did","过去时否定助动词"],["did it中的did","替代完成适应功能的实义动词"],["it","进化本可承担的适应功能"]],"We did not evolve, because machines and society did it for us","技术与社会替人完成适应，不是说机器作为生物进行了进化。","finite-predicate","reference",{hintWords:["did","it","because","did it for us"],mapRevealsAnswer:true})],
"p2-s25":[link("phrase-quotation","区分名词修饰和引语比较。",[["ignorant of evolution","修饰those的形容词短语"],["as a savage looks at a ship","带主谓的比较从句"],["as at something wholly beyond his comprehension","省去重复看待动作的比较补足"]],"to describe those ignorant of evolution","those指人，ignorant为形容词；第一处as有主谓，第二处省略重复部分，理解时恢复但不补入原文。","modifier-prepositional","attachment",{hintWords:["those","ignorant","as","looks","comprehension","ignorant of","look at an organic being as a savage looks at a ship","beyond his comprehension"]}),choice("they-source","引语中的they指哪一类人？",["those ignorant of evolution","Darwin及所有后代","船上的所有人"],0,"those ignorant of evolution: they","冒号把they接回those；这段比喻引自Darwin，不与作者未来预测混为一谈。","reference-pronoun","reference",{hintWords:["they","those"],mapRevealsAnswer:true})],
"p2-s26":[link("way-modifiers","把层叠修饰接回它说明的对象。",[["of life","限定way的领域"],["beyond comprehension","说明这种生活方式难以理解"],["for its ugliness","说明为何难以理解"]],"a 20th century way of life beyond comprehension for its ugliness","for给难以理解的原因，its指生活方式；不是说记忆行为使生活变丑。","modifier-prepositional","attachment",{hintWords:["beyond","for","its","ugliness","way of life","beyond comprehension"],mapRevealsAnswer:true})],
"p2-s27":[range("concession-scope","划出however引出的完整让步从句。","however amazed our descendants may be at how far from Utopia we were","让步内容包括at后的内层how从句；逗号后they will look才是主句。","negation-contrast","clause-boundary",{hintWords:["however","amazed","how","were","however amazed our descendants may be at"],leaksToTaskIds:["two-levels"]}),link("two-levels","将两层从句和外层结论的主语配对。",[["our descendants","may be的主语"],["we","were的主语"],["they","will look的主语，回指后代"]],"however amazed our descendants may be at how far from Utopia we were, they will look just like us","how far...作内层前置表语；后代惊讶于生活状态，不改变外貌像我们的主句结论。","clause-object","subject",{hintWords:["descendants","we","they","were","look","look just like"],mapRevealsAnswer:true})]
};
