import type { SentenceWordContext } from "./contextual-vocabulary";
import type { WordKnowledge } from "./knowledge-base";
type ReviewedContext=SentenceWordContext&{partOfSpeech:string;contextualMeaning:string;use:string;pattern?:string};
const w=(partOfSpeech:string,contextualMeaning:string,use:string,pattern?:string):ReviewedContext=>({partOfSpeech,contextualMeaning,use,pattern,preferredCollocations:[]});
export const passage2000P2Contexts:Record<string,Record<string,ReviewedContext>>={
"p2-s1":{being:w("gerund（be的动名词）","是；作为","Being a man整体作主语，a man是动名词内部表语；不是正在被的被动助动词。","Being + 表语作主语"),man:w("n.","男性","a man说明作为男性的身份；dangerous由后文男性存活率解释。"),have:w("aux.（has）","完成时助动词","has与been组成现在完成时，不表示拥有。"),be:w("linking v.（been）","是","been连接dangerous表语。")},
"p2-s2":{be:w("v.（are）","有；存在","两处there are引出后置存在对象males与women。"),male:w("n.（复数males）","男性","为存在句的后置实际主语，born后置修饰。"),female:w("n.（复数females）","女性","for every 100 females给出生性别比例基准。"),for:w("prep.","每……对应","for every 100 females表示每100名女性对应的男性数。"),but:w("conj.","但是","由出生时男性偏多转向成年时接近均衡。"),this:w("det.","这个","this ratio回指出生时105比100的男女比例。"),drop:w("v.（drops）","下降","主语为ratio，to引出接近平衡的终点。"),to:w("prep.","到","drops to near balance中给变化终点。"),near:w("adj.","接近的","near balance表示接近平衡的状态，不能删掉接近这一限制。"),balance:w("n.","平衡","作to的宾语，指男女比例的平衡。"),at:w("prep.","在","at the age of maturity限定比例接近平衡的年龄阶段。"),age:w("n.","年龄","age of maturity为成熟年龄，不是时代。"),of:w("prep.","……的","of maturity限定年龄阶段。"),as:w("adv./比较连接词","和……一样","twice as many women as men比较同一70岁群体内的男女数量。","倍数 + as many + 复数名词 + as"),man:w("n.（复数men）","男性","as men给70岁群体内女性数量的比较对象。"),twice:w("adv.","两倍","twice限制人数比，不表示寿命或两次事件。"),many:w("det.","多的","as many women比较女性数量，women为可数复数。")},
"p2-s3":{but:w("conj.","但是","由前句的男性死亡规律转向它正在改变。"),great:w("adj.","普遍重大的","加强universal的概括色彩，并不是赞美死亡。"),universal:w("n.","普遍规律","作主语中心，of male mortality说明其领域。"),of:w("prep.","关于……的","限定男性死亡率这一领域的规律。"),male:w("adj.","男性的","前置修饰mortality。"),be:w("aux.（is）","现在时助动词","is与being changed组成现在进行时被动。"),being:w("participle（be的现在分词）","被动结构中的be形式","接changed，在is being changed中构成进行中的被动；不作主语。"),change:w("past participle（changed）","改变","过去分词与is being构成被动，规律是被改变者。")},
"p2-s4":{now:w("adv.","如今","时间相对于文中过去男性存活较差的情况。"),as:w("adv./conj.","和……一样","as well as比较存活状况；后一as引出girls do比较从句。"),well:w("adv.","好地","修饰survive，as well as在本句为程度比较，不是以及。"),do:w("代动词","代替survive","girls do避免重复survive，说明女婴存活的比较基准。"),almost:w("adv.","几乎","修饰as well as，保留接近而非完全相等。")},
"p2-s5":{this:w("pron.","这（男婴存活改善）","概括上句男婴存活率接近女婴这一变化。"),mean:w("v.（第三人称单数means）","意味着","that从句是宾语内容，提出择偶年龄男孩过剩的推论。","mean that + 内容从句"),that:w("conj.","引导内容，无独立词义","引出means宾语，范围包括嵌套when从句。"),for:w("prep.","表示首次时间；引出寻找对象","for the first time表首次；searching for a mate中的for引出寻找对象。"),time:w("n.","次","for the first time为第一次，不是倍数。"),will:w("modal v.","将","will be预测将存在的男孩过剩，不是已经完成的结果。"),be:w("v./aux.","存在；进行时助动词","will be为存在句；are searching中的are为进行时助动词，两处作用不同。"),excess:w("n.","过剩","an excess of boys为后置实际主语，of限定过量对象。"),of:w("prep.","……的","of boys给出过剩的群体。"),in:w("prep.","在","in those crucial years限定会出现过剩的年龄。"),those:w("det.","那些","限定crucial years，后面的when进一步说明是哪一年龄段。"),when:w("relative adv.","在……的时候","引出修饰years的定语从句；不是主句means的时间状语。"),they:w("pron.","他们（男孩）","回指boys，作are searching的主语。"),mate:w("n.","配偶","for a mate给出寻找对象，不是动词交配。")},
"p2-s6":{more:w("adv.","更","修饰important，构成句首评价，不是更多数量。"),another:w("det.","又一个","限定chance，添加一个被消除的自然选择机会。"),chance:w("n.","机会","中心主语，for natural selection说明哪种机制的机会。"),for:w("prep.","供……的","for natural selection后置修饰chance。"),have:w("aux.（has）","完成时助动词","has been removed强调机会已消除。"),be:w("aux.（been）","被动助动词","been与removed组成完成时中的被动。")},
"p2-s7":{fifty:w("numeral","五十","Fifty years ago以文章写作时为参照，不按读者今天重算。"),chance:w("n.","可能性","of后接baby surviving这件事，整个名词短语为depended的主语。"),of:w("prep.","……的","后接a baby surviving动名词复合结构，说明存活的可能性。"),survive:w("gerund（surviving）","存活","of后的非谓语中心，baby是逻辑主语；主句谓语另为depended。"),depend:w("v.（过去式depended）","取决于","depended on其后的weight说明决定婴儿存活的因素。","depend on + 决定因素"),on:w("prep.","取决于的对象","与depended搭配，引出其依赖因素its weight。"),its:w("possessive det.","它的（婴儿的）","回指a baby，限定weight。"),weight:w("n.","体重","on的宾语，是影响婴儿存活的因素，不是动词称重。")},
"p2-s8":{light:w("adj.","轻的","too light为体重过轻，与too heavy并列。"),mean:w("v.（过去式meant）","意味着","接almost certain death名词宾语，承接五十年前的情形。"),almost:w("adv.","几乎","修饰certain，不直接将death变成差不多的死亡。"),too:w("adv.","过于","分别限制light与heavy，表示超出适宜范围。")},
"p2-s9":{it:w("pron.","这种体重偏差","回指前句过轻或过重的情形，不是形式主语。"),make:w("v.（makes）","产生；造成","与difference构成表示有无影响的搭配，difference为宾语。","make (almost) no difference"),difference:w("n.","影响","在make no difference中指影响，不是说实际体重差异不存在。"),no:w("det.","没有","限定difference，前有almost保留几乎。")},
"p2-s10":{since:w("conj.","由于","引出基因相关这一原因，不是自某时以来。"),much:w("pron.","很大一部分","much of the variation作从句主语，不能加强成all。"),of:w("prep.","……中的；……的","much of限定差异中的数量；agent of evolution说明哪一过程的因素。"),variation:w("n.","差异","承接体重差异；不是抽象的任何变化都由基因决定。"),be:w("linking v.（is）","是","连接due to genes这一原因性质表语。"),due:w("adj.","由……引起的","due to genes作表语，to后接原因名词，不是预定做某事。"),to:w("prep.","由于的原因对象","due to后引出genes。"),one:w("numeral","一个","one more agent中限定新增的一个因素。"),more:w("det.","又一；再一","one more agent表示又一个因素，而非比较级形容词的程度。"),have:w("aux.（has）","完成时助动词","has gone表示因素已不再起作用。"),go:w("v.（过去分词gone）","消失；不复存在","agent has gone在此说筛选因素失去作用，不是前往某地。")},
"p2-s11":{be:w("v.（is）","有；存在","There is引出another way。"),another:w("det.","另一种","新增生育差异这一维度的way。"),way:w("n.","方式","to commit...后置说明方式内容，冒号后进一步解释。"),to:w("infinitive marker","不定式标记","引出修饰way的不定式，commit用原形。"),but:w("conj.","但","对照保持存活与后代更少。"),have:w("v.","生育；有","have fewer children是与stay并列的祈使形式，children为宾语。"),fewer:w("comparative det.","更少的","修饰可数复数children，不是不可数数量。")},
"p2-s12":{few:w("det.","很少的","Few people具有否定倾向，但不等于无人。"),person:w("n.（复数people）","人们","people是people are的主语。"),be:w("linking v.（are）","是","连接fertile的生育程度表语。"),as:w("adv./比较连接词","和……一样","as fertile as对照过去的生育水平，后一as接省略结构。"),fertile:w("adj.","生育力强的；多产的","形容people的生育水平，不是土地肥沃。"),in:w("prep.","在","in the past给过去的比较基准。"),past:w("n.","过去","in the past中为名词，前有定冠词the。")},
"p2-s13":{in:w("prep.","在……中","给出some religious communities这一例外群体。"),few:w("det.","极少的","very few women仍允许少数女性生育15个孩子，并非零。"),have:w("v.","生育；有","have后直接接15 children，不是完成时助动词。"),very:w("adv.","极其","加强few的少量程度。")},
"p2-s14":{number:w("n.","数量","the number为主语中心，控制单数has。"),of:w("prep.","……的","of births说明生育的数量，of death说明死亡的年龄。"),birth:w("n.（复数births）","生育；出生事件","of births修饰number；与age of death构成类比，不与death并列作主语。"),like:w("prep.","像……一样","插入like the age of death作比较，非并列连词。"),age:w("n.","年龄","the age of death指死亡年龄。"),death:w("n.","死亡","of death限定age。"),have:w("aux.（has）","完成时助动词","has become与主语number一致，不由births决定。"),become:w("linking v.（过去分词）","变得","has become接average表语，构成完成时系表结构。"),average:w("adj.","平均的；趋同的","average作表语，下句用大多数人的后代数量大致相同解释。")},
"p2-s15":{most:w("pron.","大多数","Most of us中Most为主语中心，不构成形容词最高级。"),of:w("prep.","……中的；……的","Most of us给人群范围；number of offspring给计数对象。"),have:w("v.","有；拥有","have直接接后代数量宾语，是实义动词。"),same:w("adj.","相同的","修饰number，roughly使相同性为大致而非精确。"),number:w("n.","数量","与of offspring连用，为have的宾语中心。")},
"p2-s16":{again:w("adv.","同样；又一次","将生育差异趋同带来的机会减少与第一段呼应。"),difference:w("n.（复数differences）","差异","between people后置修饰，与opportunity并列作have diminished的主语。"),between:w("prep.","在……之间","后面直接接复数people，不能把后面的and opportunity误作between的第二对象。","between + 复数名词"),person:w("n.（复数people）","人们","在between中说明人的差异，不是与opportunity并列主语。"),and:w("conj.","和","连接differences与the opportunity两个主语，不连接people与opportunity。"),for:w("不定式逻辑主语标记","标出动作执行者","for natural selection to take advantage...中natural selection执行不定式动作。","for + 逻辑主语 + to do"),to:w("infinitive marker","不定式标记","to take advantage作opportunity的后置说明。"),take:w("v.","利用搭配中的动作词","take advantage of作为整体表示利用；take自身不是接管。","take advantage of + 对象"),of:w("prep.","利用的对象接口","在take advantage of it中引出被利用的差异情形。"),it:w("pron.","这种差异情形","原文单数概括人与人存在差异这一情况；中文可说明所指，不擅改them。"),have:w("aux.","完成时助动词","与diminished组成完成时，对应两个并列主语。")},
"p2-s17":{what:w("融合关系代词","所……的事情","what引出shows宾语，同时作is happening主语，不能直接换that。"),be:w("aux.（is）","进行时助动词","is happening为现在进行时。")},
"p2-s18":{country:w("n.","国家","The country回指上句India。"),offer:w("v.（offers）","提供；呈现","wealth和poverty为并列宾语，用提供的表达呈现两群体的处境。"),for:w("prep.","对……而言","分别引出享有wealth和处于poverty的人群。"),few:w("pron.","少数一些人","a few中保留冠词a，肯定少数人存在，不是否定性的few。"),in:w("prep.","在","in the great cities限定少数富裕者所在地点。"),great:w("adj.","大的","修饰cities，意为大城市。"),and:w("conj.","和；而","连接wealth...与poverty...两个并列宾语。"),remain:w("participial adj.（remaining）","其余的","前置修饰tribal peoples，非句子的限定谓语。"),people:w("n.（复数peoples）","各民族","peoples指多个部落民族，区别people作为person复数时的人们。")},
"p2-s19":{of:w("prep.","……的；……中的","of today限定当今，number of offspring限定计数对象，80% of its power限定被损失的力量份额。"),today:w("n.","如今；当今","of today中作介词宾语，限定mediocrity。"),being:w("participle（非谓语系动词）","是；处于","everyone是being的逻辑主语，the same是表语；整个独立主格在破折号内解释mediocrity。"),same:w("adj.","相同的","作being的表语；in给出存活和后代数量两项相同维度。"),in:w("prep.","在……方面；在……群体中","第一处限定survival与number维度；第二处限定印度中上阶层中的效力。"),survival:w("n.","存活","与number of offspring并列，为相同状态的比较维度。"),and:w("conj.","和","连接survival与number of offspring两个维度。"),number:w("n.","数量","of offspring限定后代数，与survival并列。"),mean:w("v.（第三人称单数means）","意味着","主语为mediocrity，宾语为整个that从句；不是名词手段。"),that:w("conj.","引导内容，无独立词义","引出means的宾语从句，并不在从句中充当主语。"),have:w("aux.（has）","完成时助动词","has lost指出效力损失已经发生。"),its:w("possessive det.","它的（自然选择的）","限定power，不指人口的力量。"),power:w("n.","效力；作用能力","80%衡量自然选择效力的损失，不是population人口。"),class:w("n.（复合定语组成）","阶层","与upper-middle组成中上阶层限定，不是classify的动词。"),to:w("prep.","比较的对象接口","compared to the tribes中引出对照群体。"),compare:w("past participle（compared）","比较","compared to the tribes作比较状语，无独立时态。")},
"p2-s20":{for:w("prep.","对……而言","For us标记作者与读者视角，不是替某人完成动作。"),this:w("pron.","这（前述趋同变化）","概括存活和生育差异缩小、自然选择机会减少。"),mean:w("v.（第三人称单数means）","意味着","that evolution is over为完整宾语；分号后另起主谓。"),that:w("conj.","引导内容，无独立词义","means的宾语从句到over为止。"),be:w("linking v.（is）","是；处于","连接over表语，表示结束状态。"),over:w("表语性副词","结束的","is over中作表语，既不是介词关于，也不是在上方。"),have:w("aux.（has）","完成时助动词","has arrived表达乌托邦已到来的形象判断。")},
"p2-s21":{it:w("pron.","这一过程","概括前述生存和生育趋同，不是形式主语或Utopia这个地点。"),have:w("aux.（has）","完成时助动词","has involved表示这一过程至今包含的变化。"),little:w("det.","很少的","限制不可数physical change，不等于绝对零。"),change:w("n.","变化","作involved的宾语，是不可数名词，不是changed被动分词。")},
"p2-s22":{no:w("det.","没有任何","限定other species，保留人类为隐含比较对象。"),other:w("det.","其他的","other species排除人类以外的物种；other也可接这里的单数species。"),place:w("n.（复数places）","位置；环境","指自然界中人类占据的生态位置。"),in:w("prep.","在……中","in nature限定自然界这一领域。"),nature:w("n.","自然界","不是性格本性或人性。")},
"p2-s23":{but:w("conj.","但是","句首But转入身体变化；句中but对照lives与bodies。"),in:w("prep.","在……期间","引出过去十万年，破折号内缩短为一百年的观察尺度。"),past:w("adj.","过去的","前置限定两个时间数量，不是介词经过。"),our:w("possessive det.","我们的（人类的）","分别限定lives和bodies，比较同一群体的生活与身体。"),have:w("aux.","完成时助动词","第一处have been transformed为完成时被动；末尾have not省略been transformed。"),be:w("aux.（been）","被动助动词","与transformed构成完成时中的被动。"),not:w("adv.","没有","否定身体发生同样变化；后面省略been transformed。")},
"p2-s24":{do:w("aux./代动词（did）","过去时助动词；做","主句did帮助构成not evolve；从句did it是实义代动词加宾语，指完成适应功能。"),not:w("adv.","没有","否定We evolve，不否定机器和社会的作用。"),because:w("conj.","因为","引出机器和社会替人完成适应的原因从句。"),it:w("pron.","这种适应功能","承接进化本可完成的适应环境功能，作did宾语。"),for:w("prep.","替；为","for us指出适应功能的受益者。")},
"p2-s25":{have:w("v.（过去式had）","有","直接接a phrase宾语，不是完成时助动词。"),to:w("infinitive marker","不定式标记","to describe解释phrase的用途。"),those:w("pron.","那些人","ignorant of evolution在后修饰those，不需在原文补造who are。"),of:w("prep.","不了解的对象接口","ignorant of evolution中引出未知领域evolution。"),they:w("pron.","他们（不懂进化者）","引语主语，回指those ignorant of evolution。"),look:w("v.","看待；观看","look/looks均与at接观看对象，两处as引出比较；不是本句把A当作B的look at A as B。"),at:w("prep.","观看的对象接口","三处at分别接organic being、ship、something；末处省略重复的看待动作。"),being:w("n.","生物；存在物","an organic being是名词短语，being不是be的动名词或被动助动词。"),as:w("比较连接词","如同","第一as引出a savage looks at a ship完整比较；第二as at省略重复的看待动作。"),savage:w("n.","蛮族人（原引语称谓）","a savage为比较从句的主语，此处不是形容词修饰ship。"),ship:w("n.","船","at的宾语，是比喻中的被看待对象。"),beyond:w("prep.","超出","wholly beyond his comprehension后置说明something无法理解。"),his:w("possessive det.","他的（看船者的）","限定comprehension，回指a savage。")},
"p2-s26":{no:w("det.","没有","No doubt整体作句子评注，表达作者肯定语气。"),will:w("modal v.","将","will remember表示将来回顾生活方式。"),remember:w("v.","记住；记得","主语是we，宾语为20世纪生活方式；不把主语换成后代。"),way:w("n.","方式","way of life整体指生活方式，后有beyond comprehension修饰。"),of:w("prep.","……的","of life限定way。"),beyond:w("prep.","超出","beyond comprehension后置说明生活方式难以理解。"),for:w("prep.","因为","for its ugliness解释为何超出理解，给出原因。"),its:w("possessive det.","它的（生活方式的）","限定ugliness，所指为way of life。"),ugliness:w("n.","丑陋","for其引出令人难以理解的原因。")},
"p2-s27":{but:w("conj.","但是","以生活评价和身体相似的反差回扣文章主题。"),however:w("程度词及让步连接词","无论多么","修饰amazed并引出让步从句，不是单独的然而。"),amaze:w("participial adj.（amazed）","感到惊讶的","前置作may be的表语，at后给惊讶对象；不是主动使别人惊讶。"),our:w("possessive det.","我们的","限定descendants，表示作者这一代的后人。"),may:w("modal v.","可能","在however让步内设想后代可能的惊讶程度。"),be:w("linking v.（be/were）","是；处于","may be连接前置amazed；were连接前置how far from Utopia。两处均为系动词。"),at:w("prep.","对……","amazed at后接how内容从句，说明惊讶什么。"),how:w("程度疑问副词","多么","how far from Utopia we were作at的宾语，how修饰far，保持we were陈述语序。"),from:w("prep.","离","far from Utopia中引出距离的参照，表示远离理想状态。"),far:w("adv.","遥远地","how far说明离Utopia的程度，整个结构前置作were表语。"),they:w("pron.","他们（后代）","回指our descendants，作外层主句主语。"),will:w("modal v.","将","引出作者关于后代外貌的预测。"),look:w("linking v.","看起来","look接just like us表语，表示外貌相似，不是观看我们。"),like:w("prep.","像","just like us在look后作表语。")},
"question-15-prompt":{what:w("interrogative pron.","什么","作used to be的疑问主语，询问过去的危险是什么。"),use:w("过去惯常结构（used to）","过去常常","used to be表示过去的状态，不表示被使用。","used to + 动词原形"),to:w("infinitive marker","不定式标记","used to be整体表达过去曾是。"),be:w("linking v.","是","used to be接the danger表语。"),in:w("prep.","在……身份中","in being a man限定危险所处的身份。"),being:w("gerund","是；作为","being a man为in的宾语，指作为男性。"),man:w("n.","男性","a man在being后说明身份。"),according:w("复合介词组成","根据","according to the first paragraph限定信息来源。"),first:w("ordinal adj.","第一的","限定paragraph，而非for the first time首次。"),paragraph:w("n.","段落","the first paragraph把查找范围限定第一段。")},
"question-15-option-A":{lack:w("n.","缺乏","A lack为名词中心，of mates说明缺少对象。"),of:w("prep.","……的","of mates补足lack，说明缺配偶。"),mate:w("n.（复数mates）","配偶","of mates的名词宾语。")},
"question-15-option-B":{fierce:w("adj.","激烈的","前置修饰competition，描述竞争强度。"),competition:w("n.","竞争","本项名词中心，fierce说明其激烈程度。")},
"question-15-option-C":{low:w("comparative adj.（lower）","更低的","比较级修饰survival rate，不能译成最低。"),survival:w("n.（名词修饰语）","存活","前置限定rate，是存活的比率。"),rate:w("n.","比率","survival rate整体指存活率；lower限定其高低。")},
"question-15-option-D":{defective:w("adj.","有缺陷的","前置修饰gene，额外提出基因有缺陷的性质。"),gene:w("n.","基因","单数名词中心，受defective限定。")},
"question-16-prompt":{what:w("interrogative pron.","什么","前置为illustrate的宾语，问例证说明什么。"),do:w("aux.（does）","疑问助动词","does承担现在时，后面的illustrate保持原形。"),example:w("n.","例子","the example of India作主语，非举例动词。"),of:w("prep.","……的","of India说明以印度为例。"),illustrate:w("v.","说明；阐明","主语为example，前置what为宾语；问实例与论点关系。")},
"question-16-option-A":{wealthy:w("adj.","富裕的","前置修饰people；本项提出富人与穷人的生育数量比较。"),person:w("n.（复数people）","人们","分别由Wealthy与poor限定，构成比较两组。"),to:w("infinitive marker","不定式标记","tend to have表示倾向生育某数量孩子。"),have:w("v.","生育；有","直接接fewer children作宾语。"),than:w("比较连接词","比","引出poor people这一比较人群，省略重复的生育数量。"),poor:w("adj.","贫穷的","前置修饰people，不是作品质量差。")},
"question-16-option-B":{work:w("v.（works）","起作用","主语为natural selection，hardly限制作用程度。"),among:w("prep.","在……中","限定the rich and the poor这两类人群。"),rich:w("名词化形容词","富人","the rich表示富裕的人们，与the poor并列。"),poor:w("名词化形容词","穷人","the poor表示贫穷的人们，不是poor修饰省略不了解的商品。"),the:w("art.","使形容词指一类人","the rich与the poor均用the加形容词指人群。"),hardly:w("adv.","几乎不","hardly works保留近似否定，不是努力工作，也非精确统计为零。")},
"question-16-option-C":{class:w("n.（复合修饰组成）","阶层","middle class限定population的人群，不是动词归类。"),population:w("n.","人口","主语中心，数字在本项衡量人口规模。"),be:w("linking v.（is）","是","接80% smaller...的比较表语。"),small:w("comparative adj.（smaller）","更少的","描述population规模，比that of the tribes少。"),than:w("比较连接词","比","引出that of the tribes作为人口比较基准。"),that:w("pron.","那一人口","代替population，of the tribes限定其所属。"),of:w("prep.","……的","of the tribes说明部落的人口。")},
"question-16-option-D":{be:w("linking v.（is）","是","连接one of the countries表语。"),one:w("pron.","一个","one of...表示若干国家中的一个。"),of:w("prep.","……之中的","one of the countries限定部分与整体关系。"),country:w("n.（复数countries）","国家","with a very high birth rate后置修饰countries。"),with:w("prep.","具有","引出国家所具有的高出生率。"),birth:w("n.（名词修饰语）","出生","birth rate是出生率，不是存活率。"),rate:w("n.","比率","与birth组成出生率，very high限定数值高。")},
"question-17-prompt":{that:w("conj.","引导内容，无独立词义","argues后的宾语从句内容为身体已停止进化，末尾because等待原因选项。"),our:w("possessive det.","我们的（人类的）","限定bodies，非美国企业。"),have:w("aux.","完成时助动词","have stopped表已经停止。"),stop:w("v.（过去分词stopped）","停止","have stopped为完成时，evolving是stop的动名词宾语。","stop doing sth"),evolve:w("gerund（evolving）","进化","作stopped的宾语，不是与be组成现在进行时。"),because:w("conj.","因为","题目末尾的原因接口，完整原因由实际选项补入。")},
"question-17-option-A":{have:w("aux.（has）","完成时助动词","has been improved表达已改善的结果。"),be:w("aux.（been）","被动助动词","been接improved，life是被改善者。"),improve:w("past participle（improved）","改善","与has been组成完成时被动，不是独立过去时。"),by:w("prep.","由；因","引出technological advance这一造成改善的因素。"),advance:w("n.","进步","technological修饰advance，整体为by的宾语。")},
"question-17-option-B":{number:w("n.","数量","the number为单数中心，has由它控制，非由babies控制。"),of:w("prep.","……的","of female babies限定计数对象。"),female:w("adj.","女性的","前置修饰babies，组成女婴，不是独立名词女性。"),have:w("aux.（has）","完成时助动词","与been declining构成现在完成进行时。"),be:w("aux.（been）","进行时助动词的过去分词","后接declining构成进行状态，不是被动。"),decline:w("present participle（declining）","下降","与has been组成持续至今的变化，不是industrial decline的名词。")},
"question-17-option-C":{our:w("possessive det.","我们的（人类的）","限定species，将人类作为一个物种。"),have:w("aux.（has）","完成时助动词","has reached表示已到达。"),reach:w("past participle（reached）","到达；达到","直接接the highest stage作宾语，不需要介词to。"),highest:w("superlative adj.","最高的","修饰stage，断言最高阶段而非一般较高水平。"),stage:w("n.","阶段","作reached宾语中心，of evolution限定进化阶段。"),of:w("prep.","……的","of evolution说明哪一过程的阶段。")},
"question-17-option-D":{difference:w("n.","差别","between wealth and poverty修饰difference，整体主语单数。"),between:w("prep.","在……之间","此处为between wealth and poverty，两项名词平行。"),be:w("aux.（is）","进行时助动词","is disappearing表示差别正在消失。"),wealth:w("n.","富裕；财富","与poverty为between的两个比较对象。"),poverty:w("n.","贫困","与wealth构成贫富比较，不是自然选择的效力。")},
"question-18-prompt":{which:w("interrogative pron.","哪一个","Which of the following作主语，问下列选项中哪一项。"),of:w("prep.","……之中的","限定Which选择的范围。"),follow:w("名词化分词（following）","下列内容","the following指随后列出的真实选项，不是正在跟随的动作。"),will:w("modal v.（would）","会；将是","would在提问中委婉询问最适合标题，不按过去将来叙事解释。"),be:w("linking v.","是","与would接the best title作表语。"),best:w("superlative adj.","最佳的","修饰title，询问最合适概括全文的标题。"),for:w("prep.","用于；适合","for the passage限定标题对应本文。")},
"question-18-option-A":{sex:w("n.（名词修饰语）","性别","与Ratio组合为性别比例，不是动词。"),ratio:w("n.（名词修饰语）","比率","Sex Ratio限定Changes所变化的对象。"),change:w("n.（复数Changes）","变化","标题中心名词，前有Sex Ratio修饰，不是第三人称单数动词。"),in:w("prep.","在……中","in Human Evolution限定变化所在领域。"),human:w("adj.","人类的","修饰Evolution，限定进化对象。")},
"question-18-option-B":{way:w("n.（复数Ways）","方法","标题名词中心，of Continuing...说明做什么的方法。"),of:w("prep.","……的","后接Continuing动名词短语作Ways的说明。"),continue:w("gerund（Continuing）","继续","of后的动名词，接Man’s Evolution作宾语。"),man:w("n.（所有格Man’s）","人类","此处泛指人类，所有格限定Evolution，不限男性。")},
"question-18-option-C":{evolutionary:w("adj.","进化的","修饰Future，限定未来的演化方面。"),future:w("n.","未来","标题名词中心，受Evolutionary和of Nature限定。"),of:w("prep.","……的","of Nature说明谁的未来。"),nature:w("n.","自然界","指整个自然界，而非人的本性。")},
"question-18-option-D":{human:w("adj.","人类的","前置限定Evolution。"),go:w("present participle（Going）","走；发展","Going Nowhere后置修饰Human Evolution，标题没有be，不构成完整进行时。"),nowhere:w("adv.","无处；没有进展","修饰Going，在本标题中比喻进化没有进展，不是地理定位。")}
};

// 同一原形在明确列出的来源中具有相同义项；仅共享已核对的角色。
const additional:Record<string,Record<string,ReviewedContext>>={
"p2-s2":{about:w("adv.","大约","修饰105这一数值，不是关于某个主题。"),there:w("存在句引导词","有（存在句占位）","两次there都引出存在句，分别讨论出生男性与70岁女性数量。")},
"p2-s4":{survive:w("v.","存活","限定谓语，比较男婴与女婴存活情况。")},
"p2-s5":{year:w("n.（复数years）","年龄段；年","crucial years指寻找配偶的关键年龄。")},
"p2-s7":{ago:w("adv.","……以前","Fifty years ago以文章写作时为时间参照。")},
"p2-s10":{agent:w("n.","作用因素","agent of evolution指产生筛选作用的因素，不指人。")},
"p2-s11":{stay:w("linking v.","保持","stay alive为系表，alive描述状态。")},
"p2-s15":{we:w("pron.（宾格us）","我们","Most of us限定多数人所在整体；us为介词of宾语。")},
"p2-s20":{we:w("pron.（宾格us）","我们","For us给作者与读者的评价视角。")},
"p2-s21":{physical:w("adj.","身体的","限定change，是身体层面的变化。")},
"p2-s22":{so:w("adv.","如此","加强many的数量程度，非因此的连词。"),many:w("det.","多的","修饰可数复数places，so强调数量之多。")},
"p2-s23":{life:w("n.（复数lives）","生活","与bodies对照，指生活方式及条件。"),body:w("n.（复数bodies）","身体","our bodies与our lives对照，have not后省略被动内容。")},
"p2-s24":{we:w("pron.（We/us）","我们","We为未进化者，us为for的宾语，两处都指文中人类群体。"),evolve:w("v.（原形）","进化","在did not后保持原形，不带过去式或分词词尾。"),society:w("n.","社会","与machines并列为适应功能的承担者，不指社团组织。")},
"p2-s25":{organic:w("adj.","有机体的；生物的","修饰being，将其限定为生物，不是有机食品标签。")},
"p2-s26":{we:w("pron.","我们","作will remember的主语，作者设想我们的将来回顾。"),life:w("n.","生活","of life修饰way，组成生活方式。"),doubt:w("n.","怀疑","No doubt为评注短语，表达肯定语气；doubt不是本句动词。"),comprehension:w("n.","理解","beyond comprehension后置修饰生活方式，说明超出一般人的理解。")},
"p2-s27":{we:w("pron.（we/us）","我们","we作were主语，us作like宾语，都指作者这一代；与descendants区分。"),just:w("adv.","正好；完全","在just like us中加强相似程度。")},
"question-15-prompt":{danger:w("n.","危险","题干询问作为男性过去面临何种危险，名词中心位于be表语中。")},
"question-16-option-C":{middle:w("adj.（复合修饰组成）","中等的；中产的","middle class整体限定population，不是地点中间。")},
"question-16-option-D":{high:w("adj.","高的","very high修饰birth rate，描述出生率数值高。")},
"question-17-prompt":{body:w("n.（复数bodies）","身体","our bodies作have stopped的主语。")},
"question-17-option-A":{life:w("n.","生活","作完成时被动主语，是被技术进步改善的对象。")},
"question-17-option-B":{baby:w("n.（复数babies）","婴儿","female修饰babies，两词组成女婴。")},
"question-17-option-C":{species:w("n.（单数）","物种","our species指人类这个物种，故谓语用has。")},
"question-18-prompt":{title:w("n.","标题","best title作be表语，要求概括本文。"),passage:w("n.","文章","the passage指完整阅读文章。")}
};
for(const[sourceId,words]of Object.entries(additional))Object.assign(passage2000P2Contexts[sourceId]??={},words);
const collocations:Record<string,Record<string,string[]>>={
"p2-s2":{for:["for every"],drop:["drops to near balance"],age:["at the age of maturity"],as:["twice as many women as men"]},
"p2-s4":{well:["almost as well as"],as:["almost as well as"]},
"p2-s5":{time:["for the first time"],excess:["an excess of"]},
"p2-s7":{chance:["the chance of a baby (particularly a boy baby) surviving"],depend:["depended on"]},
"p2-s8":{light:["too light or too heavy"],almost:["almost certain death"]},
"p2-s9":{make:["makes almost no difference"],difference:["makes almost no difference"]},
"p2-s10":{due:["is due to"],agent:["agent of evolution"]},
"p2-s11":{stay:["stay alive"],have:["have fewer children"]},
"p2-s12":{fertile:["as fertile as"]},
"p2-s14":{number:["the number of"],like:["like the age of death"],average:["become average"]},
"p2-s16":{take:["take advantage of"]},
"p2-s19":{compare:["compared to"],same:["the same in"]},
"p2-s20":{over:["evolution is over"]},
"p2-s25":{look:["look at an organic being as a savage looks at a ship"],beyond:["beyond his comprehension"]},
"p2-s26":{way:["way of life"],beyond:["beyond comprehension"]},
"p2-s27":{amaze:["however amazed our descendants may be at"],look:["look just like"]},
"question-15-prompt":{use:["used to be"]},"question-16-option-A":{have:["have fewer children"]},"question-16-option-B":{rich:["the rich and the poor"],poor:["the rich and the poor"]},"question-17-option-A":{advance:["technological advance"]},"question-18-option-D":{go:["Going Nowhere"],nowhere:["Going Nowhere"]}
};
for(const[sourceId,words]of Object.entries(collocations))for(const[head,phrases]of Object.entries(words))passage2000P2Contexts[sourceId][head].preferredCollocations=phrases;

export function getPassage2000P2WordKnowledge(headword:string,sourceId?:string):WordKnowledge|undefined{
 const context=sourceId?passage2000P2Contexts[sourceId]?.[headword]:undefined;
 if(!context)return undefined;
 return {grammarRole:headword === "mean" ? "第三人称单数谓语；本句后接宾语内容从句" : context.partOfSpeech??"本句词语",grammarSummary:context.use,structures:context.pattern?[{pattern:context.pattern,meaning:context.contextualMeaning??"",rule:context.use??""}]:[]};
}
