import type { QuestionReasoning } from "./article-teaching";
const ids = (...ns: number[]) => ns.map(n=>`p1-s${n}`);
const e = (id: string,n: number,quote: string,role: string,strength: "直接证据"|"上下文推断"|"全文概括" = "直接证据") => ({id,sentenceId:`p1-s${n}`,quote,role,strength});
export const passage2000P1Reasoning: Record<number,QuestionReasoning> = {
  11: { questionType: "细节原因题", scope: "paragraph", restatement: "美国战后领先地位的外部条件是什么？", keyInstruction: "because要求原因；比较对象、劳动力规模与技术水平必须分别核对。",
    locationPolicy: {revision:1,paths:[{id:"war-damage",label:"战争破坏竞争者经济的直接证据",groups:[ids(4)],supportingSentenceIds:ids(1,2,3),maxSentences:4}]},
    evidence:[e("effortless",1,"long and effortless success","A的相反措辞"),e("market",2,"a market eight times larger than any competitor","B的比较对象"),e("scale",2,"giving its industries unparalleled economies of scale","D偷换优势来源"),e("skill",3,"its workers the most skilled","技术水平而非人数"),e("war",4,"whose economies the war had destroyed","C的直接依据")],
    paraphrases:[{evidenceIds:["war"],meaning:"whose回指欧洲和亚洲人；战争破坏其经济，使潜在竞争者受损。",optionText:"the war had destroyed the economies of most potential competitors",relation:"同义转换",limit:"依据欧亚经济受损的历史对照；不推成全球每一个竞争者都被彻底消灭。"}],
    options:{A:{judgment:"排除",errorType:"与原文相反",evidenceIds:["effortless"],reasoning:"painstaking强调艰辛努力，与本段effortless的轻易成功相反。"},B:{judgment:"排除",errorType:"偷换对象",evidenceIds:["market"],reasoning:"原文与竞争者市场比较；before偷换为美国自己此前市场。"},C:{judgment:"选入",evidenceIds:["war"],reasoning:"把whose economies的前置宾语还原，即战争摧毁欧亚潜在竞争者经济，正是本项。"},D:{judgment:"排除",errorType:"偷换对象",evidenceIds:["scale","skill"],reasoning:"规模优势属于市场和由此产生的规模经济，劳动力被赞扬的是熟练程度，未说人数无可比拟。"}},transfer:"比较题保留than之后的对象；相同数字或形容词不能掩盖主语被换掉。" },
  12: {questionType:"细节表现题",scope:"paragraph",restatement:"哪一行业事实体现80年代美国经济优势减退？",keyInstruction:"主语the American与选项行业名词连读；事实已发生、仅处于危境和当时预测不能互换。",
    locationPolicy:{revision:1,paths:[{id:"foreign-cars",label:"外国汽车进入本土市场的直接改写",groups:[ids(11)],supportingSentenceIds:ids(9,10,12,13),maxSentences:4},{id:"compare-industries",label:"逐项核对电视、汽车、机床和半导体",groups:[ids(9,10),ids(11),ids(12),ids(13)],supportingSentenceIds:ids(8),maxSentences:5}]},
    evidence:[e("tv-one",9,"only one American television maker left, Zenith","电视厂商衰减"),e("tv-none",10,"Now there is none","补充电视厂商结果"),e("cars",11,"Foreign-made cars and textiles were sweeping into the domestic market","D的市场份额推断"),e("ropes",12,"was on the ropes","C的程度边界"),e("looks",13,"it looked as though","判断而非确认"),e("future",13,"was going to be the next casualty","B的时间边界")],
    paraphrases:[{evidenceIds:["cars"],meaning:"外国汽车涌入美国国内市场，意味着美国汽车业失去部分本土份额。",optionText:"auto industry had lost part of its domestic market",relation:"同义转换",limit:"只到部分市场损失，不推出美国车全部消失，也不增加竞争的具体百分比。"}],
    options:{A:{judgment:"排除",errorType:"偷换对象",evidenceIds:["tv-one","tv-none"],reasoning:"原文说厂商从一家到没有美国所有的厂商，并未陈述退守国内市场。"},B:{judgment:"排除",errorType:"时间错位",evidenceIds:["looks","future"],reasoning:"当时似乎将受损，被换成已经被外国企业接管；还添加未证实的收购方式。"},C:{judgment:"排除",errorType:"过度绝对",evidenceIds:["ropes"],reasoning:"危境不等于已经崩溃；suicidal actions也没有原文依据。"},D:{judgment:"选入",evidenceIds:["cars"],reasoning:"外国车进入本土市场与美国车失去部分本土市场构成同一竞争结果的两面。"}},transfer:"把时态、推测语气和程度词一起保留，避免将可能的风险读成已发生的事实。"},
  13: {questionType:"跨段推断题",scope:"whole-passage",restatement:"竞争、反省与复苏的过程支持哪种有限推断？",keyInstruction:"may contribute只主张可能有助；不能扩大成普遍人性、必需的国际合作或无条件的成功保证。",
    locationPolicy:{revision:1,paths:[{id:"pressure-response-growth",label:"竞争压力→反省或调查→随后增长",groups:[ids(8,11,18),ids(15,17),ids(20)],supportingSentenceIds:ids(1,7,14,16,19,22),maxSentences:6}]},
    evidence:[e("conditional",1,"if properly handled, it may become a driving force","D删去的条件"),e("pressure",8,"in the face of foreign competition","竞争压力"),e("reflection",15,"stopped taking prosperity for granted","反省的转变"),e("inquiries",17,"one inquiry after another into the causes of America's industrial decline","寻找原因的行动"),e("growth",20,"five years of solid growth","后来的经济改进"),e("pride",22,"Self-doubt has yielded to blind pride","A所泛化的特定社会现象")],
    paraphrases:[{evidenceIds:["pressure","reflection","inquiries","growth"],meaning:"竞争带来的危机促使反省和调查，随后出现改进，可以作竞争可能有助发展的有限推断。",optionText:"Intense competition may contribute to economic progress",relation:"同义转换",limit:"属于文章过程支持的推断，非证明竞争是复苏唯一原因；may不能删掉。"}],
    options:{A:{judgment:"排除",errorType:"范围扩大",evidenceIds:["pride"],reasoning:"美国在特定阶段的心理变化不能自动证明所有人共有的本性。"},B:{judgment:"选入",evidenceIds:["pressure","reflection","inquiries","growth"],reasoning:"竞争压力后出现反省、调查和改进，支持may contribute的有限因果。"},C:{judgment:"排除",errorType:"无中生有",evidenceIds:["pressure"],reasoning:"原文是foreign competition；国际合作和depends on的必需依赖均无证据。"},D:{judgment:"排除",errorType:"范围扩大",evidenceIds:["conditional"],reasoning:"首句强调成功既可能是包袱，也只有处理得当才可能成为动力；本项只把成功历史与进步相连，遗漏核心条件和双重作用。"}},transfer:"推断题连接分散证据，结论强度不能超过原文；过程关联不自动变成单一确定原因。"},
  14: {questionType:"作者观点归属题",scope:"paragraph",restatement:"作者隐含赞同哪一种复苏解释？",keyInstruction:"The author限定观点来源；把obvious causes与blind pride连读，再与三段直接或间接引语区分。",
    locationPolicy:{revision:1,paths:[{id:"author-evaluation",label:"明显经济原因加作者对盲目自豪的评价",groups:[ids(21),ids(22)],supportingSentenceIds:ids(20,23,24,25),maxSentences:5}]},
    evidence:[e("cycle",21,"such obvious causes as a devalued dollar or the turning of the business cycle","作者将周期变化列作明显原因"),e("few",21,"Few Americans attribute this solely","美国人的归因态度及solely限制"),e("blind",22,"blind pride","作者批评性用词"),e("structure",23,"has changed its structure","B来自Cavanaugh"),e("cavanaugh",23,"according to Richard Cavanaugh","标明来源"),e("proud",24,"It makes me proud to be an American","Moore自豪"),e("golden",25,"a golden age of business management in the United States","C来自Sahlman的预测")],
    paraphrases:[{evidenceIds:["cycle","blind"],meaning:"作者称经济周期为明显原因，并与美国人的盲目自豪保持距离；A最符合这一隐含解释。",optionText:"turning of the business cycle",relation:"同义转换",limit:"不据此断言周期是唯一原因，也不声称作者证明重组或管理毫无作用。"}],
    options:{A:{judgment:"选入",evidenceIds:["cycle","blind"],reasoning:"周期变化明确位于obvious causes中，配合下一句的批评比引语中的自我表扬更能体现作者态度。"},B:{judgment:"排除",errorType:"观点归属错误",evidenceIds:["structure","cavanaugh","blind"],reasoning:"结构改变是Cavanaugh的话；来源明确，不能换成作者的首选解释。"},C:{judgment:"排除",errorType:"观点归属错误",evidenceIds:["proud","golden","blind"],reasoning:"生产率和管理黄金时代由两位被引者肯定，不是作者在本题中的态度。"},D:{judgment:"排除",errorType:"无中生有",evidenceIds:["cavanaugh","golden"],reasoning:"哈佛等教育机构仅标明被引者身份，未提出教育成功导致复苏。"}},transfer:"先标清谁在说话，再判断态度；提到某观点与作者赞同它不是同一层次。"},
};
