import type { BeginnerSyntaxComponent, BeginnerClauseDetail, SentenceAnalysis, SyntaxVisualRole } from "./data";
import { withReviewedSyntax } from "./reviewed-syntax";
import { passage2000P2Reading } from "./2000-passage-2-reading";
import { passage2000P2Practice } from "./2000-passage-2-practice";
const c=(text:string,form:string,fn:string,modifies:string,explanation:string,children?:BeginnerSyntaxComponent[]):BeginnerSyntaxComponent=>({text,form,function:fn,modifies,explanation,children});
type Piece={component:BeginnerSyntaxComponent;color:SyntaxVisualRole;chinese:string};
const p=(color:SyntaxVisualRole,chinese:string,...args:Parameters<typeof c>):Piece=>({color,chinese,component:c(...args)});
const cl=(text:string,type:string,marker:string,role:string,subject:string,predicate:string,details:Array<[string,string]>,translationOrder:string):BeginnerClauseDetail=>({text,type,marker,role,subject,predicate,predicateDetails:details.map(([fn,text])=>({function:fn,text})),translationOrder});
type Teaching={pieces:Piece[];clauses?:BeginnerClauseDetail[];trunk:string;notes?:string[];natural?:string};
const teaching:Record<number,Teaching>={
1:{trunk:"Being a man has always been dangerous.",pieces:[p("subject","作为男性","Being a man","动名词短语","主语","has been","Being带表语a man，整个短语指作为男性这一身份。",[c("a man","名词短语","动名词内的表语","Being","说明身份，不是being的宾语。")]),p("predicate","一直是","has always been","现在完成时系动词","谓语","Being a man","always插入has与been之间，表示一贯如此。"),p("complement","危险的","dangerous","形容词","表语","been","后文用较低存活率解释这种危险。")],natural:"作为男性一直是件危险的事。"},
2:{trunk:"There are about 105 males born, but this ratio drops to near balance, and there are twice as many women as men.",pieces:[p("subject","有（存在句占位）","There","存在句引导词","形式主语","are","不指那里。"),p("predicate","出生","are","存在句动词","谓语","about 105 males born","存在句谓语，born在后面修饰males。"),p("subject","大约105名男性","about 105 males born","名词短语及分词修饰","后置实际主语","are","about限制数字精度，born后置说明出生的男性。",[c("born","过去分词","后置定语","males","不是另一个有时态的谓语。")]),p("modifier","每对应100名女性","for every 100 females","比例介词短语","比例基准状语","105 males","for every表示每……对应，不能把105看成死亡人数。"),p("connector","但是","but","并列连词","转折连接语","出生与成年比例","将偏高男婴数量转向成年均衡。"),p("subject","这个比例","this ratio","名词短语","主语","drops","回指出生时105比100的男女性别比。"),p("predicate","下降","drops","现在时动词","谓语","ratio","表示比例变化。"),p("complement","至接近平衡","to near balance","介词短语","变化终点补足语","drops","near保留接近，而非完全均等。"),p("modifier","在成年时","at the age of maturity","时间介词短语","时间状语","drops","maturity指成熟或成年阶段。"),p("connector","而且","and","并列连词","递进连接语","第三个年龄阶段","另起第三分句。"),p("modifier","在70岁的人中","among 70-year-olds","介词短语","统计范围状语","there are","不是说寿命长达另一性的两倍。"),p("subject","有（存在句占位）","there","存在句引导词","形式主语","are","不充当人数。"),p("predicate","有","are","存在句动词","谓语","women","与女性数量呼应。"),p("subject","为男性两倍的女性","twice as many women as men","含倍数比较的名词短语","后置实际主语","are","twice限制数量比较，比较对象men也限于70岁人群。",[c("as men","比较补足短语","比较基准","as many women","省略重复的数量内容，没有另造原文未出现的限定谓语。")])]},
3:{trunk:"the great universal is being changed.",pieces:[p("connector","但是","But","转折连词","篇章转折","旧死亡规律与新变化","承上转向变化。"),p("subject","男性死亡率这一普遍规律","the great universal of male mortality","名词短语","主语","is being changed","universal此处作名词，of说明规律所属领域。",[c("of male mortality","介词短语","后置定语","universal","mortality指死亡率或死亡现象。")]),p("predicate","正在被改变","is being changed","现在进行时被动","谓语","universal","is给现在时；being changed给进行中的被动，没有明说改变者。")],natural:"但是，男性死亡率的这一普遍规律正在改变。"},
4:{trunk:"boy babies survive almost as well as girls do.",pieces:[p("modifier","如今","Now","时间副词","时间状语","survive","相对于文章所谈的过去。"),p("subject","男婴","boy babies","名词短语","主语","survive","boy修饰babies。"),p("predicate","存活","survive","现在时动词","谓语","boy babies","这里不及物，well不是宾语。"),p("modifier","几乎像女婴那样好","almost as well as girls do","比较结构及比较从句","程度状语","survive","almost限制相等程度，do代替survive。",[c("as girls do","as比较从句","比较状语从句","as well","girls是主语，do避免重复survive。")])],clauses:[cl("as girls do","比较状语从句","as","给出男婴存活情况的比较对象","girls","do（代替survive）",[],"先译男婴存活，再译几乎与女婴一样好。")]},
5:{trunk:"This means that there will be an excess of boys.",pieces:[p("subject","这","This","指示代词","主语","means","概括男婴存活率接近女婴这一变化。"),p("predicate","意味着","means","现在时及物动词","谓语","This","接整个that内容。"),p("object","首次在寻找配偶的关键年龄段会有男孩过剩","that, for the first time, there will be an excess of boys in those crucial years when they are searching for a mate","含嵌套定语从句的that内容从句","宾语从句","means","外层包括完整when修饰，不能在years处截断。",[c("for the first time","介词短语","从句时间状语","will be","说明首次出现。"),c("there","存在句引导词","从句形式主语","will be","真正存在对象在后面。"),c("will be","将来存在句动词","从句谓语","an excess of boys","是预测，不是已经发生的统计。"),c("an excess of boys","名词短语","从句后置实际主语","will be","excess为超过需求的数量。"),c("in those crucial years when they are searching for a mate","介词短语","从句时间状语","will be","限定过剩显现的年龄。",[c("when they are searching for a mate","关系从句","限制性定语从句","years","they指男孩，when在从句中作时间状语。")])])],clauses:[cl("that, for the first time, there will be an excess of boys in those crucial years when they are searching for a mate","宾语从句","that","means的完整内容","there；后置实际主语an excess of boys","will be",[],"先交代寻找配偶的年龄，再说男孩首次过剩。"),cl("when they are searching for a mate","限制性定语从句","when","限定years是哪一段年龄","they（boys）","are searching",[["寻找对象补足语","for a mate"]],"译成寻找配偶的那些关键年龄。")],notes:["This译为‘这’时，具体所指由上句男婴存活率提高补足；不把预测改写为已发生结果。"]},
6:{trunk:"another chance has been removed.",pieces:[p("modifier","更重要的是","More important","形容词比较级评注","句子评注状语","整个后续判断","不与chance组成名词短语。"),p("subject","自然选择的又一次机会","another chance for natural selection","名词短语","主语","has been removed","chance是中心，被移除的是机会。",[c("for natural selection","介词短语","后置定语","chance","说明自然选择发挥作用的机会。")]),p("predicate","已被消除了","has been removed","现在完成时被动","谓语","chance","been标被动，has表示已造成结果。")]},
7:{trunk:"the chance depended on its weight.",pieces:[p("modifier","五十年前","Fifty years ago","时间名词短语","时间状语","depended","以文章写作时间为参照，不按今天重新计算。"),p("subject","婴儿（尤其男婴）存活的机会","the chance of a baby (particularly a boy baby) surviving","名词短语及动名词复合结构","主语","depended","中心是chance；of后不是chance自己存活。",[c("of a baby (particularly a boy baby) surviving","介词短语","后置定语","chance","of后接一件事：婴儿活下来。",[c("a baby","名词短语","动名词逻辑主语","surviving","真正执行存活动作。"),c("particularly a boy baby","插入名词短语","同位补充","a baby","特别突出男婴，不改变主句谓语。"),c("surviving","现在分词形式的动名词","介词宾语内的非谓语中心","a baby","自身无独立时态，与baby一起构成of的宾语。")])]),p("predicate","取决于","depended","过去式动词","谓语","the chance","限定谓语只有depended，不是surviving。"),p("complement","它的体重","on its weight","介词短语","依赖对象补足语","depended","its回指婴儿，不能说机会有重量。")],notes:["中文将of后的事件前置为‘婴儿存活的’，英语仍保持原顺序。"]},
8:{trunk:"A kilogram too light or too heavy meant almost certain death.",pieces:[p("subject","体重轻或重一公斤的情形","A kilogram too light or too heavy","表示体重偏差的名词化片段","主语","meant","整体指体重偏差，而不是婴儿总共重一公斤。",[c("A kilogram","度量名词短语","差额程度限定","too light or too heavy","一公斤衡量相对适宜体重的偏差。"),c("too light or too heavy","并列形容词结构","偏差状态说明","名词化的体重情形","or连接过轻与过重。")]),p("predicate","意味着","meant","过去式及物动词","谓语","体重偏差情形","承接五十年前的历史情况。"),p("object","几乎必然死亡","almost certain death","名词短语","宾语","meant","almost修饰certain，不将几乎误成绝对百分之百。")],natural:"体重过轻或过重一公斤，几乎就意味着死亡。",notes:["‘体重’和‘相对适宜值’承上补出，是解释量差而非在原文新增婴儿体重数值。"]},
9:{trunk:"it makes almost no difference.",pieces:[p("modifier","如今","Today","时间副词","时间状语","makes","与五十年前相对照。"),p("subject","这种体重偏差","it","代词","主语","makes","概括上一句的轻重偏差。"),p("predicate","产生","makes","现在时及物动词","谓语","it","与difference构成表示影响的搭配。"),p("object","几乎没有影响","almost no difference","名词短语","宾语","makes","almost no为几乎没有，不是绝对不存在差异。")],natural:"如今，这种体重偏差几乎没有影响。"},
10:{trunk:"one more agent has gone.",pieces:[p("modifier","由于这种差异很大一部分是基因造成的","Since much of the variation is due to genes","Since原因从句","原因状语从句","has gone","说明失去体重筛选为何意味着失去进化因素。",[c("much of the variation","数量代词短语","从句主语","is","much保留很多部分，不是all。"),c("is","系动词","从句谓语","much","后接原因性质的表语。"),c("due to genes","形容词性短语","从句表语","is","due to说明由基因引起。")]),p("subject","又一个进化因素","one more agent of evolution","名词短语","主语","has gone","agent指发挥作用的因素，不指代理人。",[c("of evolution","介词短语","后置定语","agent","说明进化过程中的因素。")]),p("predicate","已经消失了","has gone","现在完成时","谓语","agent","gone表示不再起作用，不是到某地旅行。")],clauses:[cl("Since much of the variation is due to genes","原因状语从句","Since","解释失去体重筛选的进化意义","much of the variation","is",[["表语","due to genes"]],"先译由于许多体重差异源自基因，再译进化又失去一个作用因素。")],natural:"由于这种差异很大一部分源自基因，进化又失去了一个作用因素。"},
11:{trunk:"There is another way: stay alive, but have fewer children.",pieces:[p("subject","有（存在句占位）","There","存在句引导词","形式主语","is","后置对象为another way。"),p("predicate","有","is","存在句动词","谓语","another way","单数与way一致。"),p("subject","另一种在进化意义上自毁的方式","another way to commit evolutionary suicide","名词短语及不定式","后置实际主语","is","冒号后的内容具体解释way。",[c("to commit evolutionary suicide","不定式短语","后置定语","way","说明什么样的方式；suicide是进化上的比喻。")]),p("predicate","保持","stay","祈使式系动词","谓语","隐含的人们","冒号内主语省略，stay接状态。"),p("complement","活着","alive","形容词","表语","stay","不作宾语。"),p("connector","但","but","并列连词","转折连接语","存活与后代少","两项共同解释进化机会的减少。"),p("predicate","生育","have","祈使式实义动词","谓语","隐含的人们","与stay并列，不是完成时助动词。"),p("object","更少的孩子","fewer children","名词短语","宾语","have","fewer比较数量减少。")],notes:["祈使形式用于说明一种现象，不把作者比喻译成对读者的生活命令。"]},
12:{trunk:"Few people are as fertile as in the past.",pieces:[p("subject","很少有人","Few people","名词短语","主语","are","Few具有否定倾向，但不等于无人。"),p("predicate","是","are","系动词","谓语","people","不是被动。"),p("complement","像过去那样能生育的","as fertile as in the past","形容词比较结构","表语","are","fertile用于人，谈生育程度；as in the past省略重复内容。",[c("as in the past","省略的比较补足结构","比较基准","as fertile","比较现在与过去的生育水平，没有在原文补出people were。")])]},
13:{trunk:"very few women have 15 children.",pieces:[p("modifier","除了某些宗教群体之外","Except in some religious communities","例外介词结构","例外范围状语","整句数量概括","some限制例外，不是所有宗教群体。"),p("subject","极少有女性","very few women","名词短语","主语","have","very修饰few，强调人数极少。"),p("predicate","生育","have","实义动词","谓语","women","此处不是完成时。"),p("object","15个孩子","15 children","数词名词短语","宾语","have","指每名女性生育的孩子，不是整个群体人数。")],natural:"除了某些宗教群体之外，极少有女性生育15个孩子。"},
14:{trunk:"the number has become average.",pieces:[p("modifier","如今","Nowadays","时间副词","时间状语","has become","指文章当前。"),p("subject","生育数量","the number of births","名词短语","主语","has become","中心number为单数；下句解释每人的子女数趋同。",[c("of births","介词短语","后置定语","number","说明生育次数这一数量。")]),p("modifier","像死亡年龄一样","like the age of death","插入比较短语","比较状语","has become average","like不是and，不构成第二个并列主语。"),p("predicate","已经变得","has become","现在完成时系动词","谓语","the number","has与单数number一致。"),p("complement","趋于平均","average","形容词","表语","become","指个体间趋于一致，非给定具体全国平均数。")],natural:"如今，生育数量像死亡年龄一样，已经趋于平均。"},
15:{trunk:"Most of us have roughly the same number of offspring.",pieces:[p("subject","我们中的大多数","Most of us","部分数量短语","主语","have","Most是中心，of us限定范围。"),p("predicate","拥有","have","实义动词","谓语","Most","不是助动词。"),p("object","大致相同数量的后代","roughly the same number of offspring","名词短语","宾语","have","roughly限定相同的精度；offspring单复数同形。",[c("of offspring","介词短语","后置定语","number","数量所计算的是后代。")])],natural:"我们大多数人的子女数量大致相同。"},
16:{trunk:"differences and the opportunity have diminished.",pieces:[p("modifier","同样","Again","衔接副词","篇章衔接状语","机会再次减少这一判断","把生育趋同与第一段存活趋同相接。"),p("subject","人与人之间的差异以及自然选择利用这种差异的机会","differences between people and the opportunity for natural selection to take advantage of it","并列名词短语","主语","have diminished","and连接differences与opportunity，故谓语用have。",[c("differences between people","名词短语","并列主语第一项","have diminished","between people限定人的差异。"),c("the opportunity for natural selection to take advantage of it","名词短语及带逻辑主语的不定式","并列主语第二项","have diminished","不是people与opportunity并列。",[c("for natural selection to take advantage of it","不定式复合结构","后置定语","opportunity","for标出to take advantage的执行者。",[c("natural selection","名词短语","不定式逻辑主语","to take advantage","是利用差异的机制。"),c("it","代词","介词of的宾语","take advantage of","原文单数概括存在差异这一情况，不擅改them。")])])]),p("predicate","都已减少","have diminished","现在完成时","谓语","differences and opportunity","diminish这里不及物，后面无需另找宾语。")],notes:["it保留原文单数；中文按语义回指补出‘这种差异’，不修订原卷代词。"]},
17:{trunk:"India shows what is happening.",pieces:[p("subject","印度","India","地名","主语","shows","以国家情况举例。"),p("predicate","展示了","shows","现在时动词","谓语","India","后接内容。"),p("object","正在发生的事","what is happening","what内容从句","宾语从句","shows","what同时连接并充当从句主语。",[c("what","融合关系代词","从句主语","is happening","意为所发生的事情，不是无成分的that。"),c("is happening","现在进行时","从句谓语","what","happen不及物，不接宾语。")])],clauses:[cl("what is happening","宾语从句","what","shows的内容","what","is happening",[],"将what译为正在发生的事情。")]},
18:{trunk:"The country offers wealth and poverty.",pieces:[p("subject","这个国家","The country","名词短语","主语","offers","回指印度。"),p("predicate","呈现","offers","现在时及物动词","谓语","The country","用给予的说法呈现两种社会处境。"),p("object","大城市少数人的富裕与其余部落民族的贫困","wealth for a few in the great cities and poverty for the remaining tribal peoples","并列名词短语及介词修饰","宾语","offers","wealth与poverty平行，贫富差异并未消失。",[c("wealth for a few in the great cities","名词短语","并列宾语第一项","offers","a few为一些少数人；in the great cities限定这些人。"),c("poverty for the remaining tribal peoples","名词短语","并列宾语第二项","offers","peoples指多个民族群体，不是人的普通复数。")])],natural:"在印度，大城市中的少数人富裕，而其余部落民族则贫困。"},
19:{trunk:"The grand mediocrity means that natural selection has lost 80% of its power.",pieces:[p("subject","如今这种普遍的平庸趋同","The grand mediocrity of today","名词短语","主语","means","mediocrity在本文指生存与后代数趋于平均。"),p("modifier","即人人的存活和后代数量都一样","everyone being the same in survival and number of offspring","独立主格结构","插入解释","The grand mediocrity","everyone是being的自有逻辑主语，说明主语具体内容。",[c("everyone","代词","独立主格逻辑主语","being","不是means的第二个限定主语。"),c("being","非谓语系动词","独立主格非谓语中心","everyone","无独立时态。"),c("the same","形容词性结构","独立主格内表语","being","相同的维度在后面。"),c("in survival and number of offspring","介词短语","比较维度状语","the same","survival与number平行，offspring只修饰number。")]),p("predicate","意味着","means","现在时及物动词","谓语","mediocrity","主语和谓语之间插入破折号解释。"),p("object","与部落群体相比，自然选择在印度中上阶层已失去80%的效力","that natural selection has lost 80% of its power in upper-middle-class India compared to the tribes","that内容从句","宾语从句","means","比较和阶层范围都在that内容内。",[c("natural selection","名词短语","从句主语","has lost","失去力量的是机制，不是人口。"),c("has lost","现在完成时","从句谓语","natural selection","说明作用已减弱。"),c("80% of its power","数量名词短语","从句宾语","has lost","百分比属于效力的损失，its回指自然选择。"),c("in upper-middle-class India","介词短语","从句适用范围状语","has lost","具体数字只适用于印度中上阶层。"),c("compared to the tribes","过去分词短语","比较状语","中上阶层的自然选择效力","以部落群体的自然选择效力为基准。")])],clauses:[cl("that natural selection has lost 80% of its power in upper-middle-class India compared to the tribes","宾语从句","that","means的判断内容","natural selection","has lost",[["宾语","80% of its power"]],"先给与部落相比的基准，再说印度中上阶层中的效力损失。")],notes:["原文80%说效力而非人口；不补成贫富两个群体都完全没有自然选择。"]},
20:{trunk:"this means that evolution is over; the biological Utopia has arrived.",pieces:[p("modifier","对我们来说","For us","介词短语","视角状语","this means","保留作者及其读者的视角。"),p("subject","这","this","指示代词","主语","means","概括前面存活和生育趋同。"),p("predicate","意味着","means","现在时动词","谓语","this","作者在文中的推论。"),p("object","进化结束了","that evolution is over","that内容从句","宾语从句","means","that内容到over结束。",[c("evolution","名词","从句主语","is","不是主句this。"),c("is","系动词","从句谓语","evolution","连接结束状态。"),c("over","表语性副词","从句表语","is","表示结束，不表示在上方。")]),p("subject","生物学乌托邦","the biological Utopia","名词短语","主语","has arrived","分号后另起独立主谓。"),p("predicate","已到来","has arrived","现在完成时","谓语","Utopia","对前述推论作形象评价。")],clauses:[cl("that evolution is over","宾语从句","that","means的内容","evolution","is",[["表语","over"]],"译为这意味着进化结束了；分号后另译乌托邦到来。")],natural:"对我们来说，这意味着进化已经结束，生物学乌托邦已经到来。",notes:["这是文中作者的推论；翻译不额外加入‘似乎’，篇章层再辨别其论述范围。"]},
21:{trunk:"it has involved little physical change.",pieces:[p("modifier","奇怪的是","Strangely","句子副词","句子评注状语","整句变化判断","表示作者感到出人意料。"),p("subject","这一过程","it","代词","主语","has involved","承接前述生存与生育趋同过程。"),p("predicate","包含了","has involved","现在完成时","谓语","it","不是被动。"),p("object","很少的身体变化","little physical change","名词短语","宾语","has involved","little限制不可数change，不能读成大量或完全没有。")]},
22:{trunk:"No other species fills so many places.",pieces:[p("subject","没有其他物种","No other species","名词短语","主语","fills","other隐含以人类为比较对象；species单复数同形，此处单数。"),p("predicate","占据","fills","现在时动词","谓语","species","不是填空题中的填入。"),p("object","如此多的位置","so many places","名词短语","宾语","fills","many限定可数places。"),p("modifier","在自然界中","in nature","介词短语","领域状语","fills so many places","位置指自然环境中的生态位置。")]},
23:{trunk:"our lives have been transformed but our bodies have not.",pieces:[p("connector","但是","But","连词","篇章转折","人类占据环境与身体变化","转向长时期身体变化有限。"),p("modifier","在过去十万年，甚至过去一百年里","in the past 100, 000 years—even the past 100 years","时间介词短语及插入强调","时间状语","have been transformed","even缩短观察时间以突出生活变化之快，两个时间不相加。"),p("subject","我们的生活","our lives","名词短语","主语","have been transformed","lives是life复数。"),p("predicate","已经被改变","have been transformed","现在完成时被动","谓语","our lives","保留完成与被动。"),p("connector","但","but","并列连词","转折连接语","生活与身体","区别句首But的篇章衔接。"),p("subject","我们的身体","our bodies","名词短语","主语","have not","与lives作同一时段对比。"),p("predicate","却没有（同样改变）","have not","否定完成时省略结构","谓语","our bodies","省略been transformed，not不得丢掉。")],notes:["理解have not时补出been transformed；中文补‘同样改变’，英文主干保留实际省略。"]},
24:{trunk:"We did not evolve.",pieces:[p("subject","我们","We","代词","主语","did not evolve","作者与人类观察对象。"),p("predicate","并没有进化","did not evolve","一般过去时否定","谓语","We","did在主句是助动词，evolve用原形。"),p("modifier","因为机器和社会替我们完成了这种适应","because machines and society did it for us","because原因从句","原因状语从句","did not evolve","从句did是实义代动词，it指进化本来承担的适应功能。",[c("machines and society","并列名词","从句主语","did","是技术与社会，不是身体。"),c("did","过去式实义代动词","从句谓语","machines and society","相当于完成相关适应功能，不是省略it的助动词。"),c("it","代词","从句宾语","did","语义上承接适应环境的功能。"),c("for us","介词短语","受益者状语","did","替我们完成。")])],clauses:[cl("because machines and society did it for us","原因状语从句","because","说明为何无需身体进化","machines and society","did",[["宾语","it"]],"先译机器与社会替我们承担适应，再联系身体未改变的判断。")],notes:["it译为‘这种适应’是结合生活已改变、身体未改变的对照解释其功能，不说机器本身发生生物进化。"]},
25:{trunk:"Darwin had a phrase; they look at an organic being as a savage looks at a ship.",pieces:[p("subject","达尔文","Darwin","人名","主语","had","被引用说法的来源。"),p("predicate","有","had","过去式实义动词","谓语","Darwin","不是完成时助动词。"),p("object","一种说法，用来描述那些不懂进化的人","a phrase to describe those ignorant of evolution","名词短语及不定式","宾语","had","不定式解释phrase的用途；those是人。",[c("to describe those ignorant of evolution","不定式短语","后置定语","phrase","说明用这句话描述什么人。",[c("those ignorant of evolution","代词及形容词后置修饰","不定式宾语","describe","ignorant of evolution修饰those；原文没有who are。")])]),p("subject","他们","they","代词","主语","look","指那些不理解进化的人。"),p("predicate","看待","look","现在时动词","谓语","they","引语里的行为。"),p("complement","一个生物","at an organic being","介词短语","观看对象补足语","look","being此处名词，不是动名词系动词。"),p("modifier","如同一个蛮族人看待一艘船","as a savage looks at a ship","as比较从句","比较状语从句","look at an organic being","第一处as引出有主谓的比较。",[c("a savage","名词短语","从句主语","looks","原引语中的人群称谓。"),c("looks","现在时动词","从句谓语","a savage","与主句look比较。"),c("at a ship","介词短语","从句观看对象补足语","looks","ship是被看待对象。")]),p("modifier","如同看待完全超出他理解的东西","as at something wholly beyond his comprehension","省略的比较补足短语","补充比较说明","looks at a ship","重复的主语和look被省去，保留实际出现的as at结构。",[c("wholly beyond his comprehension","程度副词及介词短语","后置定语","something","his指看船者，wholly限定超出理解的程度。")])],clauses:[cl("as a savage looks at a ship","比较状语从句","as","比较两种看待未知事物的方式","a savage","looks",[["观看对象补足语","at a ship"]],"先译看待生物，再接如同看待船，末尾补出视作无法理解之物。")],notes:["第二处as保留省略形式；可在中文补出看待，不把隐含的he looks写回英文。"]},
26:{trunk:"we will remember a 20th century way of life.",pieces:[p("modifier","无疑","No doubt","名词性评注短语","句子评注状语","will remember","表达作者的肯定语气。"),p("subject","我们","we","代词","主语","will remember","不擅自改成句中尚未出现的后代。"),p("predicate","将记住","will remember","将来表达","谓语","we","是将来回顾而非已有记忆。"),p("object","一种因丑陋而令人难以理解的20世纪生活方式","a 20th century way of life beyond comprehension for its ugliness","名词短语及层叠修饰","宾语","remember","中心way，beyond说明这种生活方式令人难以理解。",[c("of life","介词短语","后置定语","way","way of life整体为生活方式。"),c("beyond comprehension for its ugliness","介词短语及原因修饰","后置定语","way of life","for说明因何难以理解。",[c("for its ugliness","介词短语","原因状语","beyond comprehension","its指这种生活方式，丑陋造成难以理解。")])])],natural:"无疑，我们会记住一种20世纪的生活方式，它因其丑陋而令人难以理解。"},
27:{trunk:"they will look just like us.",pieces:[p("connector","但是","But","转折连词","篇章转折","生活评价与身体不变","回到身体进化主题。"),p("modifier","无论我们的后代多么惊讶于我们曾离乌托邦那么远","however amazed our descendants may be at how far from Utopia we were","含嵌套内容从句的让步从句","让步状语从句","they will look","however修饰前置amazed，后面仍按主语与系动词顺序。",[c("however amazed","程度词及前置形容词","从句前置表语","may be","无论多么惊讶。"),c("our descendants","名词短语","从句主语","may be","惊讶者是后代。"),c("may be","情态动词及系动词","从句谓语","our descendants","不是amaze的被动动作。"),c("at how far from Utopia we were","介词短语及内容从句","形容词补足语","amazed","说明惊讶的内容。",[c("how far from Utopia we were","嵌入疑问内容从句","介词宾语从句","at","how far...前置，we仍为主语。",[c("how far from Utopia","程度结构","前置表语","were","说明离理想状态的距离。"),c("we","代词","内层从句主语","were","指作者这一代的人。"),c("were","过去式系动词","内层从句谓语","we","后代回看作者时代。")])])]),p("subject","他们","they","代词","主语","will look","回指our descendants。"),p("predicate","将看起来","will look","将来表达及系动词","谓语","they","look接外貌状态，不是观看。"),p("complement","和我们一样","just like us","介词短语及程度限定","表语","look","just加强相像，呼应身体几乎没有变化。")],clauses:[cl("however amazed our descendants may be at how far from Utopia we were","让步状语从句","however","即便后代非常惊讶也不改变主句结论","our descendants","may be",[["前置表语","however amazed"]],"先译无论后代对我们离理想多远有多惊讶，再译外貌仍像我们。"),cl("how far from Utopia we were","介词宾语从句","how","作at的宾语，说明惊讶内容","we","were",[["前置表语","how far from Utopia"]],"译为我们曾离乌托邦多么遥远。")],notes:["they明确为后代，we/us为作者这一代；后代视角下were所述是此前的生活状态。"]}
};
export function reviewPassage2000P2(sentence:SentenceAnalysis):SentenceAnalysis{
 const spec=teaching[sentence.number];
 const reviewed=withReviewedSyntax({...sentence,trunk:spec.trunk,natural:spec.natural??sentence.natural,beginnerSyntax:{components:spec.pieces.map(p=>p.component),clauses:spec.clauses??[],reading:passage2000P2Reading[sentence.id]}},spec.pieces.map(p=>p.color));
 return {...reviewed,practice:passage2000P2Practice[sentence.id],translationAlignment:reviewed.chunks.map((chunk,i)=>({english:chunk.text,chinese:spec.pieces[i].chinese})),translationNotes:spec.notes};
}
