import type { SentenceWordContext } from "./contextual-vocabulary";
import type { WordKnowledge } from "./knowledge-base";
type ReviewedContext = SentenceWordContext & { pattern?: string };
const w = (partOfSpeech: string, contextualMeaning: string, use: string, pattern?: string): ReviewedContext => ({ partOfSpeech, contextualMeaning, use, pattern });
// 只共享相同用法；发生词性、指代或结构变化时逐来源另写。来源ID不借用题目兼容定位句。
export const passage2000P1Contexts: Record<string, Record<string, ReviewedContext>> = {
  "p1-s1": {
    long:w("adj.","长久的","与effortless并列修饰success，描述成功持续很久，不是long before的副词。"),
    of:w("prep.","……的","of long and effortless success补足history，说明这段经历的内容。"),
    be:w("linking v.","是；成为","can be后接a dreadful handicap作表语，不是被动。","can be + 名词表语"),
    but:w("conj.","但是","连接成功成为障碍与可能转为动力的两个判断。"),
    can:w("modal v.","可能；会","can be表示可能具有的作用，不是许可。"), may:w("modal v.","可能","may become保留成功转成动力的不确定性，且受if条件限制。"),
    it:w("pron.","它（成功经历）","回指a history of long and effortless success；不是形式主语。"),
    handicap:w("n.","障碍；不利条件","作be后的名词表语，将既有成功比作发展的包袱。"),
    force:w("n.","力量；动力","driving force整体指推动力量；force不是强迫某人做事的动词。"),
  },
  "p1-s2": {
    just:w("adv.","正是","修饰such，强调美国进入的正是前述那样的辉煌时期。"),such:w("det.","这样的","such a glowing period回指前句的成功状态；不是such as举例。"),
    of:w("prep.","……的","the end of the Second World War中限定结束的事件；economies of scale中限定节约来自规模扩大。"),
    it:w("pron.","它（美国）","主句it had中的it回指时间从句the United States，不是形式主语。"),
    have:w("v.（过去式had）","拥有","had直接接a market作宾语，没有构成过去完成时。","have + 名词宾语"),
    time:w("n.（复数times）","倍","eight times修饰larger的比较程度，不是次数或时段。"),
    large:w("adj.（比较级larger）","更大的","比较市场规模；than any competitor借竞争者指其市场。"),
    than:w("比较连接词","比","引出竞争者的市场，不表示美国此前的市场。"),
    its:w("possessive det.","它的（美国的）","限定industries，受益者是美国工业。"),
    industry:w("n.（复数）","各工业部门；行业","its industries是giving的间接宾语，经济规模好处由这些工业获得。"),
    economy:w("n.（复数）","节约；经济效益","economies of scale整体指规模经济，不能沿用后文各国国民经济的义项。","economies of scale"),
    world:w("n.（专名组成）","世界","Second World War是第二次世界大战的专名，World不处于所有格。"),
  },
  "p1-s3": {
    its:w("possessive det.","它的（美国的）","两处分别限定scientists和workers，都回指美国。"),
    be:w("linking v.（were）","是","前半句连接scientists和best；后半句重复的were省略。","主语 + were + 表语"),
    most:w("adv.","最","most与skilled组成形容词最高级，不限定工人的数量。"),
    skilled:w("adj.","技术娴熟的","the most skilled作第二分句表语；此处省略系动词were，不能说已经出现的workers被省略。"),
  },
  "p1-s4": {
    american:w("n.（复数Americans）","美国人","与America并列作主语，不是修饰名词的形容词。"),
    be:w("linking v.（were）","是；处于","连接主语与prosperous，后面没有过去分词，不是被动。"),
    european:w("n.（复数）","欧洲人","与Asians并列，受whose关系从句限定。"),asian:w("n.（复数）","亚洲人","与Europeans并列作为whose的先行对象。"),
    of:w("prep.","……的","of the Europeans and Asians说明谁的想象；不能把dreams说成战争的梦想。"),
    economy:w("n.（复数）","经济","whose economies是被战争摧毁的各方经济，不是规模经济中的节约。"),
    have:w("aux.（had）","完成时助动词","had destroyed表破坏早于战后繁荣；had不译拥有。","had + 过去分词"),
    whose:w("关系限定词","其……的","whose限定economies；整个whose economies作had destroyed的前置宾语，主语是the war。","whose + 名词 + 主语 + 谓语"),
  },
  "p1-s5": {
    it:w("形式主语","主语占位，不指具体名词","后面的that从句才给出被评价为inevitable的内容。","It is + 形容词 + that从句"),
    be:w("linking v.（was）","是","was连接inevitable，不是should have中的助动词。"),
    that:w("conj.","引导主语内容，无独立词义","that从句为后置真正主语，包含内部as从句；that不作从句主语。"),
    this:w("det.","这种","限定primacy，接回战后美国的优势地位。"),
    have:w("aux.","完成式助动词","should have narrowed中构成完成式，不表示拥有。"),
    as:w("conj.","随着","引出other countries grew richer，说明别国富裕与美国优势缩小同步发生。"),
    grow:w("linking v.（grew）","逐渐变得","grew接richer表语；与下一段growing competition的分词修饰不同。","grow + 形容词"),
    rich:w("adj.（比较级richer）","更富裕的","作grew的表语；形容国家越来越富裕，不是矿产丰富。"),
  },
  "p1-s6": {
    just:w("adv.","恰好；同样","加强as inevitably，把本句必然痛苦与前句必然失势并置。"),
    as:w("adv.（比较作用）","同样地","as修饰inevitably，承接上一句inevitable，不在这里引导有主谓的从句。"),
    retreat:w("n.","退却；退离","主语中心，不是命令撤退的动词。"),
    from:w("prep.","从……","限定retreat，说明退出优势地位的起点。"),
    predominance:w("n.","优势地位","from predominance是retreat的起点，不将loss误配from。"),
    prove:w("linking v.（proved）","结果显得；证明是","后接painful作表语，没有直接宾语。","prove + 形容词"),
  },
  "p1-s7": {
    by:w("prep.","到……为止","By the mid-1980s给had found的过去截止点，不引出施事。"),
    american:w("n.（复数）","美国人","作had found的主语，也就是themselves所指的人。"),
    have:w("aux.（had）","完成时助动词","had found以80年代中期为回顾点；不译拥有。"),
    find:w("v.（过去分词found）","发现","find oneself + 状态整体表示发现自己处于某状态；‘自己’不属于find的单词义。","find oneself + 状态补足语"),
    themselves:w("reflexive pron.","他们自己（美国人）","反身代词与Americans同指，at a loss补足其处境。"),
    at:w("prep.","处于（习语成分）","at a loss整体表示困惑，作themselves的宾补；不是价格比率。"),
    loss:w("n.（习语成分）","迷失；无措","在at a loss中表达无措状态，与题干loss of predominance的丧失不同。"),
    their:w("possessive det.","他们的（美国人的）","限定industrial competitiveness。"),
    fade:w("现在分词作定语","逐渐减弱的","fading修饰competitiveness，句子的限定谓语仍是had found。"),
  },
  "p1-s8": {
    some:w("det.","一些","限定industries，既未说所有行业，也不表示某一人的财产。"),
    american:w("adj.","美国的","修饰industries，不是名词美国人。"),industry:w("n.（复数）","行业；产业","Some限定多个具体产业，作并列谓语主语。"),
    such:w("举例结构成分","例如（与as连用）","such as consumer electronics举industries的实例。"),as:w("举例结构成分","例如（与such连用）","as后是名词consumer electronics，没有从句主谓。"),
    have:w("aux.（had）","完成时助动词","had统领并列shrunk和vanished，两项都在过去完成时内。"),
    in:w("prep.（复合介词组成）","在……面前","in the face of整体表示面对某种压力或挑战。"),
    face:w("n.（习语成分）","面前","in the face of中不用动词面对；整组表达面对外国竞争。"),
    of:w("prep.（复合介词组成）","引出所面对对象","in the face of后面接foreign competition。"),
  },
  "p1-s9": {
    by:w("prep.","到……为止","By 1987限定剩余厂商数量的截止时间。"),
    be:w("v.（存在句was）","有；存在","there was后置实际主语为one maker，left是其修饰语。"),
    only:w("adv.","仅仅","限制数量one，不表示仅限某种方式。"),
    american:w("adj.","美国的","修饰television maker，厂商的国家归属。"),
    leave:w("过去分词作定语left","剩下的","修饰maker，限定谓语为was；不是主句‘离开了’。"),
    zenith:w("proper n.","Zenith公司","电视制造商专名，同位解释最后一家厂商，不取普通名词顶峰义。"),
  },
  "p1-s10": {
    now:w("adv.","如今（文中当前）","回到作者写作时的情况，不等于读者今天。"),
    be:w("v./aux.","is表存在；was构成被动","同句is用于there is none；was与bought构成被动，须按所在片段区分。","there is none / was bought"),
    by:w("prep.","由","was bought by引出收购者LG Electronics，与By 1987时间义不同。"),
    electronics:w("专名组成","电子（公司名称组成）","LG Electronics是公司名，不能沿用consumer electronics作为行业的讲解。"),
    in:w("prep.","在","in July交代收购月份，原文没有给出年份。"),
    zenith:w("proper n.","Zenith公司","被收购的电视制造商名称，不是普通名词‘顶峰’。"),
  },
  "p1-s11": {
    be:w("aux.（were）","进行时助动词","were sweeping为过去进行时，不是系表或被动。","was/were + 现在分词"),
    into:w("prep.","进入","sweeping into引出产品涌入的方向，美国国内市场。"),
    textile:w("n.（复数）","纺织品","与cars并列作主语，不是形容词纺织业的。"),
    domestic:w("adj.","国内的","以美国为叙述中心，不作家庭的解释。"),market:w("n.","市场","into后为进入对象，非动词营销。"),
  },
  "p1-s12": {
    be:w("linking v.（was）","处于","后接on the ropes作表语，不是was doing。"),
    industry:w("n.","工业；行业","machine-tool限定为机床制造领域。"),
    on:w("prep.（习语组成）","处于（围绳边的比喻）","on the ropes整体表示濒于失败的困境，不按回顾的look back on解释。"),
    rope:w("n.（复数，习语成分）","围绳","on the ropes源自拳击，整体比喻危境；rope单词义不直接等于行业崩溃。"),
  },
  "p1-s13": {
    for:w("prep.","持续","For a while限定一段时间。","for + 时间段"),
    while:w("n.","一段时间","a while是For的名词宾语；不是第20句表示对比的连词。","for a while"),
    it:w("情境代词","形势如此（情境占位）","it looked as though概括当时看起来的形势，不指机床或半导体某一个名词。"),
    look:w("linking v.（looked）","看起来","接as though表语从句，不是look back on回顾。","look as though + 从句"),
    as:w("从句连接结构成分","仿佛（与though连用）","as though整体引出looked的表语内容。"),
    make:w("名词化-ing形式making","制造","the making of semiconductors作从句主语中心，不是make me proud的使役动词。","the making of + 产品"),
    of:w("prep.","……的","making of引出制造对象，heart of限定核心所属范围；两处都嵌在名词结构内。"),
    which:w("relative pron.","关系代词，指半导体","第一处作invented的宾语，第二处作sat的主语；两处都指semiconductors。","which + 主语 + 谓语 / which + 谓语"),
    have:w("aux.（had）","完成时助动词","had invented说明发明早于当时产业前景的判断。"),
    sit:w("v.（过去式sat）","处于；位于","sat at the heart of比喻半导体位于计算机时代核心。","sit at the heart of + 领域"),
    at:w("prep.","在","at the heart of指出核心位置，不表价格比率。"),
    go:w("将来表达组成going","将要（be going to组成）","was going to be表示过去看来即将成为，不用go on a diet的进入节食状态义。"),
    to:w("不定式标记","引出动词原形be","was going to be中的to后接系动词be，非方向介词。"),
    be:w("aux./linking v.","was组成将来表达；be是成为","was going to be中was承担过去时，be接the next casualty作表语；两处作用要分开。"),
    semiconductor:w("n.（复数）","半导体","of后作制造对象，两处which的共同先行词。"),
  },
  "p1-s14": {
    all:w("pron.","所有的一切","All of this整体作主语，概括前段衰退事例。"),
    of:w("prep.","……中的全部；……的","All of this限定概括范围；crisis of confidence说明危机发生于信心领域。"),
    this:w("pron.","这些情况","回指前段工业竞争力受损的整体情况。"),
    cause:w("v.（过去式caused）","导致","直接接a crisis of confidence作宾语，不能用causes的名词原因义。"),
  },
  "p1-s15": {
    american:w("n.（复数）","美国人","停止把繁荣视为当然的人。"),
    stop:w("v.（过去式stopped）","停止；不再","后接taking作宾语，stop doing与stop to do不同。","stop doing"),
    take:w("动名词taking","视为（固定结构中的动词）","take A for granted整体是把A视为当然；这里不取接管义。","take A for granted"),
    for:w("prep.（固定结构组成）","引出被认定的状态","for granted配合taking说明对prosperity的看法。"),
  },
  "p1-s16": {
    they:w("pron.","他们（美国人）","外层They began的主体，和上一句Americans衔接。"),
    to:w("不定式标记","引出动词原形","两处分别为began to believe和begin to fall，都补足开始的行为。"),
    that:w("conj.","引出所相信内容","两个that从句并列受believe支配，that本身不作从句成分。"),
    their:w("possessive det.","他们的（美国人的）","分别限定经营方式way与收入incomes。"),
    of:w("prep.","……的","of doing business说明way的具体内容，doing是介词宾语。"),
    do:w("动名词doing","从事；做","doing business指从事经营，do为实义动词，不是疑问助动词。"),
    business:w("不可数名词","经营活动；生意","doing business是从事经营，与businesses指多家企业不同。"),
    be:w("aux.（was）","进行时助动词","was failing描述经营方式当时正在失效。"),
    will:w("modal v.（would）","将会（过去视角）","在过去的believe视角下预测收入会下跌，不是意愿。"),
    as:w("固定副词短语成分","也（与well连用）","as well修饰收入下降这项附加变化，没有第二个as，不套as well as。"),
    well:w("固定副词短语成分","也（as well组成）","as well放句末表示也，不是健康、井或as well as结构。","as well"),
  },
  "p1-s17": {
    after:w("prep.","一个接一个地（结构组成）","one inquiry after another把调查连成连续发生的事件，不特指二战结束后。"),
    into:w("prep.","针对；关于","inquiry into引出调查对象，不表产品涌入方向。","an inquiry into + 问题"),
    cause:w("n.（复数causes）","原因","the causes of America's industrial decline是调查对象中的原因名词，不是caused的谓语。"),
    of:w("prep.","……的","causes of引出需要解释的工业衰退。"),
  },
  "p1-s18": {
    their:w("possessive det.","它们的（那些调查的）","findings属于上一句接连进行的调查，不指美国人的身体。"),
    be:w("aux.（were）","被动形式助动词","were filled with表达发现中充满某些内容。"),
    from:w("prep.","来自","from overseas后置修饰competition，说明竞争来源。"),
    grow:w("现在分词作定语growing","不断增强的","修饰competition，不是grew richer里的系动词谓语。"),
    with:w("prep.","充满……（搭配成分）","be filled with中的with引出内容warnings，而非伴随人物。"),
  },
  "p1-s19": {
    how:w("感叹副词","多么","修饰变化程度，感叹句不倒装，不能按疑问词怎样追问。"),
    thing:w("n.（复数）","情况；形势","things概括经济与社会心态，不是具体物品清单。"),
    have:w("aux.","完成时助动词","have changed强调截至文中当前已有的变化。"),
    change:w("v.（过去分词）","改变；变化","things have changed中不及物，没有宾语；不是changed structure的及物用法。"),
  },
  "p1-s20": {
    in:w("prep.","在","In 1995给文中观察点，非在某种方式中。"),
    look:w("v.","看；回看（搭配中的动作）","look back on整体表示回顾，on后接回顾对象。","look back on + 经历"),
    on:w("prep.","关于；引出回顾对象","look back on five years...的对象是五年增长，不是回顾持续五年。"),
    of:w("prep.","……的","five years of solid growth说明这五年经历怎样的增长。"),
    while:w("conj.","而；然而","对照美国稳健增长与日本持续困境，不取a while的一段时间义。"),
    have:w("aux.（has）","完成时助动词","has been struggling构成现在完成进行时，以文章1995年当前为参照。"),
    be:w("aux.（been）","进行时助动词的过去分词","has要求been的过去分词形式，been与struggling构成进行部分。","has/have been doing"),
  },
  "p1-s21": {
    few:w("det.","很少的","限定Americans数量，和solely合起来不表示无人承认这些原因。"),
    american:w("n.（复数）","美国人","作attribute的主语，不是美国工业的形容词。"),
    this:w("pron.","这一变化（经济复苏）","作attribute宾语，回指上句美国增长。"),
    to:w("prep.","归于（搭配成分）","attribute A to B的B为原因；不是接动词的不定式。"),
    as:w("举例结构成分","例如","与such呼应，后接两个名词性原因，没有独立从句谓语。"),
    cause:w("n.（复数）","原因","obvious causes是to的宾语，非动词引起。"),
    of:w("prep.","……的","the turning of the business cycle说明哪个周期在转变。"),
    business:w("名词作定语","商业；经济活动","business cycle整体是商业周期，不是多家企业。"),
    devalue:w("过去分词作定语devalued","已贬值的","修饰dollar，不是本句谓语发出贬值动作。"),
  },
  "p1-s22": {
    have:w("aux.（has）","完成时助动词","has yielded以文中当前为终点，旧心态已让位。"),
    to:w("prep.","向；给（让位结构成分）","yield to引出替代原有心态的新状态blind pride，方向不能反转。"),
    pride:w("n.","自豪；自负","to的宾语，blind使之带批评性，不能按动词以……为傲讲解。"),
  },
  "p1-s23": {
    american:w("adj.","美国的","修饰industry，是国家归属。"), industry:w("不可数名词","工业","泛指美国工业，共用三个has结构，不是勤奋。"),
    have:w("aux.（has）","完成时助动词","三处has分别接changed、gone、learnt，共用industry为主语。"),
    change:w("v.（过去分词）","改变","has changed直接接its structure作宾语，区别于things have changed的不及物变化。"),
    its:w("possessive det.","它的（美国工业的）","限定structure，不指说话者的学院。"),
    structure:w("n.","结构","changed的宾语，是工业结构，不作重组的动词。"),
    on:w("prep.（固定搭配组成）","处于（节食状态）","go on a diet比喻工业瘦身，不是look back on。"),
    to:w("不定式标记／介词","to be为不定式；according to表来源","同句有两种to：learnt to be接动作，according to Richard接人物，不能共判为一种。"),
    be:w("linking v.","变得；是","to be后接more quick-witted表语，不构成被动。"),
    more:w("adv.","更","修饰形容词quick-witted的程度，不表示更多数量。","more + 形容词"),
    executive:w("adj.","执行的；行政的","修饰dean，单词义不包含后面的院长。"),
    of:w("prep.","……的","dean of说明任职学院；School of Government说明学院领域。"),
  },
  "p1-s24": {
    it:w("形式主语","主语占位，无实指","真正主语为just to see how...，proud to be说明me的状态。","It makes somebody + 形容词 + to do"),
    make:w("v.（makes）","使；使得","makes接me作宾语、proud作宾补；不是半导体making的制造义。","make + 宾语 + 形容词"),
    to:w("不定式标记","引出动词原形","to be补足proud，to see为后置真正主语；两处层级不同。"),
    be:w("linking v./aux.","be为系动词；are组成进行时","to be an American说明身份；are improving是how从句的现在进行时，不能混读。"),
    american:w("n.","美国人","an American作be的表语，不是修饰industry的形容词。"),
    just:w("adv.","仅仅；只要","just限定to see，强调看到这种改进本身便使Moore自豪。"),
    how:w("内容从句引导词","怎样","引出see的宾语内容，内部保持陈述词序；不是第19句的感叹修饰。"),
    business:w("n.（复数businesses）","企业","our businesses为how从句主语，不是doing business的抽象经营活动。"),
    improve:w("v.（现在分词）","提高；改进","are improving接their productivity宾语，指企业提升生产率。"),
    their:w("possessive det.","它们的（企业的）","限定productivity，回指our businesses。"),
    of:w("prep.","来自；属于","of the Cato Institute限定Moore的机构归属。"),
    in:w("prep.","在","in Washington, DC限定智库所在地，不是Moore讲话发生地的明确报道。"),
    institute:w("n.（专名组成）","研究所；机构","Cato Institute是机构，后面的think-tank同位说明它。"),
  },
  "p1-s25": {
    of:w("prep.","……的；所属的","of the Harvard Business School限定Sahlman机构；age of business management说明黄金时代的领域。"),
    business:w("名词作定语","商业；企业经营","在Business School中限定学校领域，在business management中限定管理对象；两处都不是复数企业。"),
    believe:w("v.（believes）","相信；认为","这里只接一个that内容从句，不能沿用第16句两个并列that的解释。"),
    that:w("conj.","引导相信的内容","不作从句主语；从句主语是people。"),
    person:w("n.（复数people）","人们","泛指将来回望这段时期的人。"),
    will:w("modal v.","将会","预测未来如何回看当前时期，不表示人的意愿。"),
    look:w("v.","回看（搭配中的动作）","look back on this period as...表示回顾并给出评价。"),
    on:w("prep.","引出回顾对象","on this period给出回看的时期，as再补评价。"),
    as:w("prep.","作为；看作","引出对this period的评价名词golden age，不是时间从句。"),
    this:w("det.","这一","限定period，指当前谈到的经济复苏时期。"),
    in:w("prep.","在","in the United States限定企业管理的地域。"),
  },
  "question-11-prompt": {
    achieve:w("v.（过去式achieved）","取得","achieved接its predominance，过去式而非缺助动词的过去分词。"),
    its:w("possessive det.","它的（美国的）","限定predominance，指题干The U.S.。"),
    predominance:w("n.","主导地位","achieved的宾语中心，本句谈取得优势，不是retreat from优势退却。"),
    world:w("n.（专名组成）","世界","World War II中的组成词，不是the world's best所有格。"),
    after:w("prep.","在……之后","后接World War II，不是含主谓的从句。"),
  },
  "question-11-option-A": {
    it:w("pron.","它（美国）","承接题干The U.S.，不是成功经历，也不是形式主语。"),
    have:w("aux.（had）","完成时助动词","had made表示先前已作出努力，后接过去分词made。"),
    make:w("v.（过去分词made）","作出；付出","make efforts整体表示努力，不取制造半导体或使某人自豪的结构。","make efforts towards a goal"),
    efforts:w("n.（复数）","努力","painstaking修饰efforts；本项泛指美国为目标付出的努力，不限定科学家和技术人员。"),
    towards:w("prep.","朝着；为了","引出努力所朝向的目标。"),
    this:w("det.","这一","this goal回指取得经济主导地位的目标。"),
  },
  "question-11-option-B": {
    its:w("possessive det.","它的（美国的）","限定domestic market。"),
    be:w("linking v.（was）","是","was连接market和larger比较结构，不是被动。"),
    time:w("n.（复数times）","倍","eight times限定市场比较的倍数。"),
    large:w("adj.（比较级larger）","更大的","比较的是现在所说市场与以前市场，不得把before改成竞争者。"),
    than:w("比较连接词","比","than before把时间上的以前作为比较基准。"),
    before:w("adv.","以前","独立用在than后，不接名词，也不引完整从句。"),
  },
  "question-11-option-C": {
    have:w("aux.（had）","完成时助动词","had destroyed表示战争破坏早于题干美国取得优势。"),
    economy:w("n.（复数）","经济","各潜在竞争者的经济是destroyed的宾语，不是规模经济的节约。"),
    of:w("prep.","……的","说明这些经济属于哪些竞争者。"),
    most:w("det.","大多数的","限定potential competitors的数量，不是the most skilled的最高级程度。"),
    competitor:w("n.（复数）","竞争者","本项指潜在对手本身，不在any competitor的市场借代比较内。"),
  },
  "question-11-option-D": {
    unparalleled:w("adj.","无可比拟的","本项修饰size，描述劳动力规模，不是正文economies of scale的修饰对象。"),
    of:w("prep.","……的","of its workforce说明size属于劳动力规模。"),
    its:w("possessive det.","它的（美国的）","两处分别限定workforce和economy。"),
    have:w("aux.（had）","完成时助动词","had given是过去完成时，不是拥有某物。"),
    give:w("v.（过去分词given）","给予；带来","given接an impetus，to引接受推动的经济；不是正文giving结果状语。","give an impetus to something"),
    to:w("prep.","向；给","引出impetus所作用的经济，不是不定式。"),
    economy:w("n.","经济","its economy指美国经济整体，不是节约。"),
  },
  "question-12-prompt": {
    loss:w("n.","丧失","of U.S. predominance说明失去的是美国优势，不能用at a loss无措义。","the loss of + 事物"),
    of:w("prep.","……的","引出所失去的主导地位。"),
    economy:w("n.","经济","world economy为全球经济领域。"),
    world:w("名词作定语","世界","限定economy的范围，不是所有格。"),
    in:w("prep.","在；体现于","in the world economy给领域，in the 1980s给时间，in the fact给表现依据，各自附着不同。"),
    be:w("aux.（is）","被动助动词","is manifested为现在时被动，不是过去时。"),
    that:w("conj.","引出事实内容","that接在fact后给同位内容，待选项补足，不作从句主语。","the fact that + 从句"),
    american:w("adj.","美国的","须与选项行业名称连读，不指一个美国人。"),
  },
  "question-12-option-A": {
    industry:w("n.","行业","TV限定电视制造行业；与题干the American衔接。"),
    have:w("aux.（had）","完成时助动词","had withdrawn为过去完成时主动，行业是退却者。"),
    to:w("prep.","到；退回到","withdrawn to引出撤回的终点，不是不定式。"),
    its:w("possessive det.","它的（该国电视业的）","限定domestic market，在题干美国范围内。"),
  },
  "question-12-option-B": {
    semiconductor:w("名词作定语","半导体","修饰industry，非正文making of semiconductors的复数宾语。"),
    industry:w("n.","行业","半导体行业是被接管对象。"),
    have:w("aux.（had）","完成时助动词","had been taken over是过去完成时被动，声称事件已发生。"),
    be:w("aux.（过去分词been）","被动助动词","been与taken构成被动，had要求been的完成形式。"),
    take:w("v.（过去分词taken）","接管（与over连用）","take over的被动形式，不是take for granted的视为当然。","be taken over by somebody"),
    over:w("短语动词小品词","接管结构成分","与taken组成take over，没有独立的关于义，也不是at a loss over。"),
    by:w("prep.","由","引出本项所称的接管方foreign enterprises。"),
    foreign:w("adj.","外国的","修饰enterprises，不直接修饰competition。"),
  },
  "question-12-option-C": {
    industry:w("n.","行业","machine-tool限定机床行业。"),
    have:w("aux.（had）","完成时助动词","had collapsed为过去完成时，声称已经崩溃。"),
    after:w("prep.","在……之后","后接suicidal actions，说明本项声称的事件先后，不是战后时间。"),
  },
  "question-12-option-D": {
    industry:w("n.","行业","auto限定汽车行业。"),
    have:w("aux.（had）","完成时助动词","had lost说明过去已经丧失部分份额。"),
    of:w("prep.","……中的","part of说明所丧失部分属于哪个整体。"),
    its:w("possessive det.","它的（美国汽车业的）","限定domestic market，不指外国的本土市场。"),
    part:w("n.","一部分","限定损失范围，不能译成整个市场。"),
  },
  "question-13-prompt": {
    be:w("aux.","被动助动词","can be inferred中的be与过去分词构成被动。"),
    from:w("prep.","根据；从……中","引出推断依据the passage，不是竞争来源或撤退起点。"),
  },
  "question-13-option-A": {
    it:w("形式主语","主语占位，无实指","后置to shift...才是真正内容，不回指前句。"),
    be:w("linking v.（is）","是","连接human nature名词表语。"),
    human:w("adj.","人的；人类的","修饰nature，概括整个人类，不是某位美国人。"),
    nature:w("n.","本性","human nature为人性，不取自然界义。"),
    to:w("不定式标记","引出shift","to shift整组作后置真正主语。"),
    shift:w("v.","转变；摇摆","不定式动作，between引出两种心态，不是名词轮班。"),
  },
  "question-13-option-B": {
    may:w("modal v.","可能","只保留竞争有助发展的可能性，不是许可或‘可能需要’。"),
    competition:w("n.","竞争","作may contribute主语，Intense加强竞争程度。"),
    to:w("prep.","对；引出贡献对象","contribute to后接economic progress名词，非不定式标记。"),
    progress:w("不可数名词","进步；发展","作to的宾语，不是主句谓语。"),
  },
  "question-13-option-C": {
    of:w("prep.","……的","of the economy限定revival是经济复苏。"),
    economy:w("n.","经济","复苏的经济领域，不是节约义。"),
    on:w("prep.","依赖于（结构成分）","depend on引出international cooperation，不是look back on。","depend on + 事物"),
  },
  "question-13-option-D": {
    long:w("adj.","长期的","修饰history，不是long before中的副词。"),
    of:w("prep.","……的","of success说明history的内容。"),
    may:w("modal v.","可能","may pave表达可能铺路，不是请求许可。"),
    way:w("n.（比喻结构组成）","道路","pave the way for将为发展创造条件比作铺路，不是做生意的方法。"),
    for:w("prep.","为；给","引出铺路的受益结果further development。","pave the way for something"),
  },
  "question-14-prompt": {
    to:w("不定式标记／介词","to believe引动作；to the引原因","seems to believe中的to是不定式；attributed to the...中的to是归因介词。"),
    of:w("prep.","……的","of the U.S. economy限定所谈复苏的经济体。"),
    economy:w("n.","经济","美国整体经济，不是规模经济的节约。"),
    be:w("aux.","被动助动词","can be attributed组成情态被动结构。"),
    believe:w("v.","认为；相信","接省略that的内容从句，句中未并列两个that。"),
    in:w("prep.","在","in the 1990s限定经济复苏发生的年代。"),
    attribute:w("v.（过去分词）","归因","被动结构中现象是主语、原因在to后；不能沿用主动宾语角色。","A can be attributed to B"),
  },
  "question-14-option-A": {
    of:w("prep.","……的","说明发生turning的是商业周期。"),
    business:w("名词作定语","商业；经济活动","business cycle整体是商业周期，不是企业数量。"),
    cycle:w("n.","周期","经济扩张和收缩的周期，不是骑车的动词。"),
  },
  "question-14-option-B": {
    of:w("prep.","对……的","industry是restructuring的对象，整个选项仍是名词短语。"),
    industry:w("不可数名词","工业","工业是被重组领域，不取勤奋义。"),
  },
  "question-14-option-C": {
    improve:w("过去分词作定语improved","已改进的","修饰management，短语没有限定谓语；不能套正文are improving进行时。"),
    business:w("名词作定语","企业经营","限定management领域，而非企业在执行句子动作。"),
    management:w("n.","管理","选项名词中心，improved作前置修饰。"),
  },
  "question-14-option-D": {
    success:w("n.","成功","in education限定成功领域，不是首句成功经历的详细描述。"),
    in:w("prep.","在……方面","限定success所属教育领域，不表时间。"),
  },
};

// 当前来源的语法先解释本句，稳定原形的通用知识仍可在其他来源复用。
export function getPassage2000P1WordKnowledge(headword: string, sourceId?: string): WordKnowledge | undefined {
  const context = sourceId ? passage2000P1Contexts[sourceId]?.[headword] : undefined;
  if (!context) return undefined;
  return { grammarRole: context.partOfSpeech!, grammarSummary: context.use!, structures: context.pattern ? [{ pattern: context.pattern, meaning: context.contextualMeaning!, rule: context.use! }] : [] };
}
