import type { PracticeTask, GrammarConceptId, ErrorCategory } from "./learning-model";

const choice = (id: string, prompt: string, options: string[], answer: number, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "choice", prompt, options, answer: options[answer], evidence, feedback, conceptId, errorType, ...extra });
const range = (id: string, prompt: string, answer: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "range", prompt, options: [], answer, evidence: answer, feedback, conceptId, errorType, ...extra });
const link = (id: string, prompt: string, pairs: Array<[string, string]>, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "link", prompt, links: pairs.map(([source, target]) => ({ source, target })), options: [...new Set(pairs.map(([, target]) => target))], answer: JSON.stringify(pairs.map(([, target]) => target)), evidence, feedback, conceptId, errorType, ...extra });
const order = (id: string, prompt: string, blocks: string[], distractors: string[], evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "order", prompt, options: [...blocks, ...distractors], answer: JSON.stringify(blocks), evidence, feedback, conceptId, errorType, ...extra });

// 新增任务从revision 1开始；hintWords使用页面原文词形及实际词组标签。
export const passage2000P1Practice: Record<string, PracticeTask[]> = {
  "p1-s1": [
    link("success-conditions", "把两个判断和它们之间的限制对应起来。", [["a dreadful handicap", "can be后的表语"], ["if properly handled", "成为动力的条件"], ["it", "先前的成功经历"]], "if properly handled, it may become a driving force", "两组都是主系表；if说明转化为动力所需的条件，不能把成功史直接等同于持续进步的保证。", "clause-condition", "attachment", { hintWords: ["if", "handled", "it", "if properly handled"], mapRevealsAnswer: true }),
  ],
  "p1-s2": [
    range("when-scope", "划出开头完整的时间从句，含战后时间说明。", "When the United States entered just such a glowing period after the end of the Second World War", "entered的宾语与after时间短语都在从句内；逗号后it had才是主句。", "clause-time", "clause-boundary", { hintWords: ["When", "entered", "after", "entered just such a glowing period", "after the end of the Second World War"] }),
    link("market-result", "匹配市场比较与giving结构中的角色。", [["any competitor", "市场比较对象"], ["its industries", "giving的间接宾语"], ["unparalleled economies of scale", "giving的直接宾语"]], "a market eight times larger than any competitor, giving its industries unparalleled economies of scale", "比较的是竞争者的市场；大市场给本国工业带来规模经济，giving不是competitor的新动作。", "comparison-scope", "attachment", { hintWords: ["competitor", "giving", "industries", "economies", "eight times larger than any competitor", "giving its industries unparalleled economies of scale"] }),
  ],
  "p1-s3": [choice("parallel-ellipsis", "分号后哪一项在原文省略了？", ["系动词were", "主语its workers", "形容词skilled"], 0, "its workers the most skilled", "前后平行主系表，后半句承接were；阅读时补足关系，选范围或抄主干时不添加原文没有的词。", "finite-predicate", "predicate", { hintWords: ["were", "workers", "skilled", "the most skilled"] })],
  "p1-s4": [
    link("whose-roles", "将定语从句的三个片段对应到内部功能。", [["whose economies", "前置宾语"], ["the war", "从句主语"], ["had destroyed", "从句谓语"]], "whose economies the war had destroyed", "战争摧毁了他们的经济：whose只表示所属，整个whose economies才是destroyed的宾语。", "clause-relative", "subject", { hintWords: ["whose", "economies", "war", "destroyed", "whose economies the war had destroyed"] }),
  ],
  "p1-s5": [
    range("real-subject", "划出与形式主语It对应的完整主语从句。", "that this primacy should have narrowed as other countries grew richer", "that内容必须包含as的同步变化；inevitable评价的是这一整件事。", "clause-subject", "clause-boundary", { hintWords: ["It", "that", "as", "It was inevitable that"] }),
    link("nested-growth", "区分主语从句内部的两组主谓关系。", [["this primacy", "should have narrowed的主语"], ["other countries", "grew的主语"], ["richer", "grew的表语"]], "this primacy should have narrowed as other countries grew richer", "as引出别国变富，解释优势缩小的同步背景；grew是系动词，不带richer作宾语。", "basic-svc", "attachment", { hintWords: ["primacy", "narrowed", "grew", "richer", "as other countries grew richer"] }),
  ],
  "p1-s6": [order("proved-state", "保留主系表，把句首评注和退却起点留在词块池。", ["the retreat", "proved", "painful"], ["Just as inevitably", "from predominance"], "the retreat from predominance proved painful", "proved在这里意为结果显得；painful描述退却的状态，不是证明出来的物品。", "basic-svc", "predicate", { hintWords: ["proved", "painful", "proved painful"] })],
  "p1-s7": [link("find-state", "匹配find结构中的宾语、状态和时间。", [["themselves", "发现的对象，与Americans同指"], ["at a loss", "宾语所处状态"], ["By the mid-1980s", "过去完成时的截止点"]], "By the mid-1980s Americans had found themselves at a loss", "find oneself + 状态描述发现自己的处境；by指到那时已经如此，不是从那时才开始。", "object-complement", "tense", { hintWords: ["By", "had", "found", "themselves", "loss", "found themselves at a loss over"] })],
  "p1-s8": [order("shared-perfect", "拼出核心主谓，保留两个变化；去掉举例和情境。", ["Some huge American industries", "had shrunk", "or vanished"], ["such as consumer electronics", "in the face of foreign competition"], "had shrunk or vanished", "had同时统领shrunk和vanished，两项都是行业已经经历的变化。", "finite-predicate", "predicate", { hintWords: ["had", "shrunk", "vanished", "had shrunk or vanished"] })],
  "p1-s9": [choice("left-role", "left在there was...maker left中起什么作用？", ["后置修饰maker，表示剩下的", "作句子唯一谓语，表示离开", "形容市场在左边"], 0, "there was only one American television maker left", "限定谓语是was；left为过去分词，说明剩下的厂商，Zenith再同位点名。", "nonfinite-participle", "predicate", { hintWords: ["left", "was", "there was only one American television maker left"] })],
  "p1-s10": [link("none-and-buyer", "把否定指代和被动角色对应起来。", [["none", "没有一家美国电视制造商"], ["Zenith", "被收购者"], ["South Korea's LG Electronics", "收购者"]], "none: Zenith was bought by South Korea's LG Electronics", "none承接上句maker；was bought是被动，by引出主动发起收购的公司。原文没有给July的年份。", "passive-voice", "reference", { hintWords: ["none", "bought", "by", "was bought by South Korea's LG Electronics"], mapRevealsAnswer: true })],
  "p1-s11": [choice("market-direction", "into the domestic market描述的方向是什么？", ["外国汽车和纺织品进入美国市场", "美国产品进入所有国外市场", "美国汽车工业完全消失"], 0, "Foreign-made cars and textiles were sweeping into the domestic market", "domestic以美国为观察位置；涌入意味着竞争冲击，但不等于美国车全部退出。", "modifier-prepositional", "option-logic", { hintWords: ["Foreign-made", "into", "domestic", "were sweeping into", "the domestic market"], mapRevealsAnswer: true })],
  "p1-s12": [choice("ropes-degree", "on the ropes保留哪种程度最准确？", ["处境岌岌可危", "已经完全倒闭", "正在飞速增长"], 0, "was on the ropes", "这个拳击比喻表示受到严重打击、濒于失败；不能把危急直接改写成失败已经发生。", "lexical-context", "vocabulary", { hintWords: ["ropes", "on the ropes"], mapRevealsAnswer: true })],
  "p1-s13": [
    range("appearance-content", "划出looked后的完整表语从句，保留插入的两项说明。", "as though the making of semiconductors, which America had invented and which sat at the heart of the new computer age, was going to be the next casualty", "外层as though说明看起来怎样；两个which从句插入主语与was之间，不能误当从句终点。", "clause-predicative", "clause-boundary", { hintWords: ["as", "though", "making", "was", "was going to be the next casualty"] }),
    link("two-which", "将两处which按实际语法功能区分。", [["which America had invented", "which是invented的宾语"], ["which sat at the heart of the new computer age", "which是sat的主语"]], "which America had invented and which sat at the heart of the new computer age", "两个which都回指semiconductors。第一处已有America作主语，第二处没有另外的主语，因此which自己承担主语功能。", "clause-relative", "subject", { hintWords: ["which", "invented", "sat", "sat at the heart of"] }),
    choice("forecast-boundary", "was going to be加上looked as though，表达什么证据强度？", ["当时看来可能成为下一个受害行业", "作者确认半导体业已被外企收购", "美国从未发明半导体"], 0, "looked as though", "这是当时的前景判断；不把预计受损换成已经发生的收购事实。", "time-reference", "option-logic", { hintWords: ["looked", "though", "going", "was going to be the next casualty"], mapRevealsAnswer: true }),
  ],
  "p1-s14": [choice("all-this", "All of this把哪一范围接到信心危机？", ["前段多个行业遭竞争冲击的情况", "仅Zenith这个公司的名字", "后段尚未出现的三位人士意见"], 0, "All of this caused a crisis of confidence", "this概括前段衰退例证，再由caused引出心理后果，不能只寻找最近的单一名词。", "reference-pronoun", "reference", { hintWords: ["All", "this", "All of this"], mapRevealsAnswer: true })],
  "p1-s15": [link("stop-taking", "对应停止的行为及其内部对象。", [["taking prosperity for granted", "stopped的宾语"], ["prosperity", "taking的宾语"], ["for granted", "对prosperity的看法"]], "stopped taking prosperity for granted", "stop doing停止这种做法；stop to do则是停下别的事去做，不能混用。", "nonfinite-subject", "attachment", { hintWords: ["stopped", "taking", "granted", "stopped taking prosperity for granted"] })],
  "p1-s16": [
    link("believe-both", "把两层动作和两项内容接回支配者。", [["to believe", "补足began"], ["that their way of doing business was failing", "believe的第一项内容"], ["that their incomes would therefore shortly begin to fall as well", "believe的第二项内容"]], "They began to believe", "that...and that...并列于believe之下；两项是他们的看法，不是作者直接宣布的事实。", "clause-object", "clause-boundary", { hintWords: ["began", "believe", "that", "and"] }),
    choice("income-time", "收入下降相对于began to believe是什么时间？", ["从过去那个相信的时点看，将要发生", "早在相信之前就已完全发生", "从读者今天算起的未来"], 0, "would therefore shortly begin to fall", "would把参照点放在当时的判断；shortly是不久，therefore连接他们推想的因果。", "time-reference", "tense", { hintWords: ["would", "shortly", "would therefore shortly begin to fall"] }),
  ],
  "p1-s17": [order("inquiry-trunk", "保留主谓宾，调查对象留在词块池。", ["The mid-1980s", "brought", "one inquiry after another"], ["into the causes of America's industrial decline"], "The mid-1980s brought one inquiry after another", "年代名词作主语，brought作谓语；into说明调查什么，不把causes接成brought的直接宾语。", "basic-svo", "subject", { hintWords: ["1980s", "brought", "inquiry", "one inquiry after another"] })],
  "p1-s18": [link("warning-layers", "把三项修饰分别接回直接对象。", [["sometimes", "sensational"], ["about the growing competition from overseas", "warnings"], ["from overseas", "competition"]], "Their sometimes sensational findings were filled with warnings about the growing competition from overseas", "有时是结论耸动，警告谈竞争，竞争来自海外；近邻词并非总是整个短语的修饰对象。", "modifier-prepositional", "attachment", { hintWords: ["sometimes", "about", "from", "warnings", "competition", "were filled with warnings about", "the growing competition from overseas"] })],
  "p1-s19": [choice("exclamation", "How things have changed!是什么语气？", ["感叹变化之大，转入复苏", "疑问：要求解释具体方法", "命令别人立即改变"], 0, "How things have changed", "没有have things倒装，且有感叹号；这句是危机到复苏的转折桥。", "negation-contrast", "passage-logic", { hintWords: ["How", "things", "changed"], mapRevealsAnswer: true })],
  "p1-s20": [link("growth-time", "把时间、回顾对象和对照关系对应起来。", [["In 1995", "文中观察的当前时点"], ["five years of solid growth", "look back on的对象"], ["while Japan has been struggling", "日本与美国的同期对比"]], "In 1995 the United States can look back on five years of solid growth while Japan has been struggling", "不能把five years读成回顾动作持续五年；has been struggling的当前也属于1995的文章视角。", "time-reference", "tense", { hintWords: ["In", "years", "while", "has", "been", "struggling", "look back on", "five years of solid growth"] , mapRevealsAnswer: true })],
  "p1-s21": [
    link("attribute-roles", "拆开attribute A to B及其范围限制。", [["this", "被解释的经济复苏"], ["to such obvious causes", "归因的原因"], ["solely", "仅仅归于这些原因"]], "Few Americans attribute this solely to such obvious causes", "A是被解释现象，B是原因；Few否定人数，solely限制单一归因，不等于这些原因毫无作用。", "comparison-scope", "option-logic", { hintWords: ["Few", "attribute", "this", "solely", "causes", "attribute this solely to", "such obvious causes as"], mapRevealsAnswer: true }),
  ],
  "p1-s22": [choice("yield-direction", "has yielded to中的新心态是什么？", ["blind pride", "Self-doubt", "二者没有发生替换"], 0, "Self-doubt has yielded to blind pride", "旧的自我怀疑让位于新的盲目自豪；blind带作者的批评，不是引语中的自我称赞。", "lexical-context", "reference", { hintWords: ["yielded", "to", "blind", "pride", "yielded to blind pride"], mapRevealsAnswer: true, leaksToTasks: [{ sentenceId: "p1-map", taskId: "author-voice" }] })],
  "p1-s23": [
    order("parallel-industry", "保留引语主语及三项变化，删去报道来源。", ["American industry", "has changed its structure", "has gone on a diet", "has learnt to be more quick-witted"], ["according to Richard Cavanaugh"], "American industry has changed its structure, has gone on a diet, has learnt to be more quick-witted", "三个has结构共用industry；according to说明这段话由谁提出，不是另一个有时态的句子。", "finite-predicate", "predicate", { hintWords: ["has", "changed", "gone", "learnt", "according", "has gone on a diet", "has learnt to be more quick-witted"] }),
    choice("cavanaugh-voice", "工业调整这三项评价是谁提出的？", ["Richard Cavanaugh", "作者直接下的最终结论", "the Europeans and Asians"], 0, "according to Richard Cavanaugh", "有明确according to来源；读到引语须区分被引者观点与作者紧前句的blind pride评价。", "author-voice", "passage-logic", { hintWords: ["according", "according to Richard Cavanaugh"], mapRevealsAnswer: true }),
  ],
  "p1-s24": [
    link("make-complements", "分别确定make结构里的三个层级。", [["me", "makes的宾语"], ["proud to be an American", "说明me状态的宾补"], ["just to see how our businesses are improving their productivity", "后置真正主语"]], "It makes me proud to be an American just to see how our businesses are improving their productivity", "It先占位，看到企业提升生产率使我自豪；to be补proud，to see才给出造成感受的事情。", "object-complement", "attachment", { hintWords: ["It", "makes", "me", "proud", "see", "makes me proud to be an American"] }),
    range("see-content", "只划出see后面的完整内容从句。", "how our businesses are improving their productivity", "how引导see的宾语；our businesses作主语、are improving作谓语、their productivity作宾语。", "clause-object", "clause-boundary", { hintWords: ["how", "businesses", "improving", "productivity", "see how our businesses are improving their productivity"] }),
    choice("think-tank-apposition", "a think-tank in Washington, DC解释哪个名称？", ["the Cato Institute", "Stephen Moore本人", "an American这个身份"], 0, "the Cato Institute, a think-tank in Washington, DC", "同位语说明Cato Institute是一家智库；Moore是来自这家机构的人。", "apposition", "attachment", { hintWords: ["think-tank", "Institute", "a think-tank in Washington, DC"] }),
  ],
  "p1-s25": [range("belief-boundary", "从that开始划出Sahlman相信的完整内容。", 'that people will look back on this period as "a golden age of business management in the United States', "will把评价放在将来的回顾中；黄金时代是Sahlman的预测，不是作者已经证实的历史共识。", "clause-object", "clause-boundary", { hintWords: ["that", "believes", "will", "look back on this period as"], mapRevealsAnswer: true })],
};
