import type { ContextualSubstitution } from "./contextual-vocabulary";

export type Passage2001P1LexiconEntry = {
  partOfSpeech: string;
  contextualMeaning: string;
  use: string;
  specialForms?: string[];
  examSynonyms?: string[];
  collocations?: string[];
  otherMeanings?: string[];
  wordFamily?: string[];
  confusions?: string[];
  contextualSubstitutions?: ContextualSubstitution[];
};

const e = (
  partOfSpeech: string,
  contextualMeaning: string,
  use: string,
  extra: Partial<Passage2001P1LexiconEntry> = {},
): Passage2001P1LexiconEntry => ({ partOfSpeech, contextualMeaning, use, ...extra });

export const passage2001P1LemmaAliases: Record<string, string> = {
  appeared: "appear", areas: "area", amateurs: "amateur", aimed: "aim", affecting: "affect",
  changing: "change", clearly: "clear", concerned: "concern", constitutes: "constitute", continued: "continue",
  delayed: "delay", developments: "development", exceptions: "exception", geologists: "geologist", greater: "great",
  harder: "hard", illustrated: "illustrate", implied: "imply", increasing: "increase", integrated: "integrate",
  journals: "journal", led: "lead", ones: "one", policies: "policy", professionals: "professional",
  publications: "publication", reckoned: "reckon", reinforced: "reinforce", represented: "represent", reveals: "reveal",
  sciences: "science", seen: "see", societies: "society", splitting: "split", studies: "study",
  tended: "tend", terms: "term", units: "unit", wider: "wide", writes: "write",
};

export const passage2001P1FamilyAliases: Record<string, string> = {
  accumulation: "accumulate",
  geological: "geology",
  geologist: "geology",
  participation: "participate",
  professionalisation: "profession",
  professional: "profession",
  refereeing: "referee",
  scientific: "science",
  specialisation: "specialise",
};

export const passage2001P1FormPartOfSpeech: Record<string, string> = {
  appeared: "v.（appear 的过去式/过去分词）", areas: "n.（area 的复数）", amateurs: "n.（amateur 的复数）",
  aimed: "v.（aim 的过去分词，构成后置定语）", affecting: "v.-ing（affect 的现在分词）",
  changing: "v.-ing/adj.（change 的现在分词，修饰 definition）", clearly: "adv.",
  concerned: "adj./过去分词（后置表示所涉及的）", constitutes: "v.（constitute 的第三人称单数）",
  continued: "v.（continue 的过去分词）", delayed: "v.（delay 的过去分词，被动语态）",
  developments: "n.（development 的复数）", exceptions: "n.（exception 的复数）",
  geologists: "n.（geologist 的复数）", greater: "adj.（great 的比较级）", harder: "adj./adv.（hard 的比较级）",
  illustrated: "v.（illustrate 的过去分词，被动语态）", implied: "v.（imply 的过去式）",
  increasing: "adj./v.-ing（不断增加的）", integrated: "v./adj.（integrate 的过去分词）",
  journals: "n.（journal 的复数）", led: "v.（lead 的过去式/过去分词）", ones: "pron.（one 的复数替代形式）",
  policies: "n.（policy 的复数）", professionals: "n.（professional 的复数）",
  publications: "n.（publication 的复数）", reckoned: "v.（reckon 的过去分词，被动语态）",
  reinforced: "v.（reinforce 的过去分词，被动语态）", represented: "v.（represent 的过去式）",
  reveals: "v.（reveal 的第三人称单数）", sciences: "n.（science 的复数，指不同学科）",
  seen: "v.（see 的过去分词）", societies: "n.（society 的复数）", splitting: "v.-ing（split 的动名词）",
  studies: "n.（study 的复数）", tended: "v.（tend 的过去分词）", terms: "n.（term 的复数）",
  units: "n.（unit 的复数）", wider: "adj.（wide 的比较级）", writes: "v.（write 的第三人称单数）",
};

const structure = ["结构词：无普通词形变化，重点看句法位置"];
const regular = ["规则变化；无需要单独记忆的不规则变形"];

export const passage2001P1Lexicon: Record<string, Passage2001P1LexiconEntry> = {
  specialisation: e("n.", "专业化；学科细分", "全文核心概念，指知识领域被细分、研究者在更窄领域接受专门训练。", { specialForms: ["specialisation（英式）/ specialization（美式）"], collocations: ["the growth of specialisation", "the process of professionalisation and specialisation"], examSynonyms: ["specialization（美式拼写）", "division of labour（分工，范围更广）"], wordFamily: ["specialise v. 专门研究", "specialist n. 专家；专业人员", "specialised adj. 专门的"] }),
  see: e("v.", "看作；认为", "can be seen as 是 see A as B 的被动式，本句表示专业化‘可被视为’一种回应。", { specialForms: ["see—saw—seen—seeing"], collocations: ["be seen as a response"], examSynonyms: ["regard（视为，常用 regard A as B）", "view（看作，常用 view A as B）"] }),
  response: e("n.", "回应；应对办法", "a response to the problem 中 response 指为解决知识激增问题而出现的制度性应对。", { specialForms: ["response—responses（复数）"], collocations: ["a response to the problem"], examSynonyms: ["reaction（反应，未必有意解决）", "answer（解决办法；回答）"], wordFamily: ["respond v. 回应", "responsive adj. 反应迅速的"] }),
  increase: e("v./n.", "增加；增长", "increasing 作形容词修饰 accumulation，表示积累量持续上升。", { specialForms: ["increase—increased—increased—increasing"], examSynonyms: ["grow（增长，可不及物）", "expand（扩大范围或规模）"] }),
  accumulation: e("n.", "积累；累积量", "an increasing accumulation of knowledge 指科学知识越积越多。", { specialForms: ["accumulation—accumulations（具体累积物时可数）"], collocations: ["an increasing accumulation of scientific knowledge"], examSynonyms: ["growth（增长）", "build-up（逐渐积聚）"], wordFamily: ["accumulate v. 积累", "accumulative adj. 累积的"] }),
  scientific: e("adj.", "科学的", "scientific knowledge/activity/community 分别指科学知识、科学活动和科学共同体。", { specialForms: regular, examSynonyms: ["academic（学术的，范围更广）", "empirical（实证的）"], wordFamily: ["science n. 科学", "scientist n. 科学家"] }),
  knowledge: e("n.", "知识；知识总量", "scientific knowledge 是不可数名词，作为 accumulation of 的对象。", { specialForms: ["knowledge 通常不可数"], examSynonyms: ["understanding（理解）", "expertise（专业知识）"] }),
  split: e("v./n.", "拆分；分割", "splitting up the subject matter into units 中 split up A into B 表把 A 分成 B。", { specialForms: ["split—split—split—splitting"], collocations: ["by splitting up the subject matter", "split A up into B"], examSynonyms: ["divide（分成若干部分）", "separate（使分开）"] }),
  subject: e("n./adj./v.", "主题；学科内容", "subject matter 是固定名词搭配，指一门学科或讨论所涉及的内容。", { specialForms: ["subject—subjects（复数）"], collocations: ["by splitting up the subject matter"], examSynonyms: ["topic（具体话题）", "discipline（学科）"] }),
  matter: e("n./v.", "内容；事项", "subject matter 中 matter 与 subject 组合，整体是‘研究内容’，不单独译为物质。", { specialForms: ["matter—matters（复数/动词三单）"], examSynonyms: ["issue（问题/事项）", "content（内容）"] }),
  unit: e("n.", "单元；单位", "smaller units 指把庞大学科拆成可由个人处理的较小知识单元。", { specialForms: ["unit—units（复数）"], examSynonyms: ["component（组成部分）", "division（分区/部门）"] }),
  information: e("n.", "信息；资料", "handle the information 中 information 是不可数名词，回指细分后的科学知识。", { specialForms: ["information 不可数；不能写 informations"], collocations: ["continue to handle the information"], examSynonyms: ["data（数据，传统上为复数但现代常作不可数）", "material（资料）"] }),
  basis: e("n.", "基础；依据", "use it as the basis for research 中 basis 指后续研究赖以进行的知识依据。", { specialForms: ["basis—bases（复数，读 /ˈbeɪsiːz/）"], collocations: ["use it as the basis for further research"], examSynonyms: ["foundation（基础，强调支撑）", "ground（理由/根据）"] }),
  series: e("n.", "一系列", "a series of related developments 中 series 形式上单复数同形，本句中心由 a 判定为单数。", { specialForms: ["series—series（单复数同形）"], collocations: ["one of a series of related developments"], examSynonyms: ["sequence（有顺序的一连串）", "range（一系列/范围）"] }),
  development: e("n.", "发展；变化；进程", "related developments 指专业化、职业化等相关变化；development of geology 指地质学发展。", { specialForms: ["development—developments（复数）"], collocations: ["developments in science", "the development of geology in the United Kingdom"], examSynonyms: ["evolution（渐进演变）", "change（变化，最宽泛）"] }),
  science: e("n.", "科学；科学学科", "in science generally 指科学整体；areas/sciences 可指不同科学领域。", { specialForms: ["science—sciences（不同学科时可数）"], collocations: ["developments in science", "in science generally"], examSynonyms: ["discipline（学科）", "scientific study（科学研究）"], wordFamily: ["scientific adj. 科学的", "scientist n. 科学家"] }),
  affect: e("v.", "影响", "affecting the process of communication 是现在分词后置修饰 developments。", { specialForms: ["affect—affected—affected—affecting"], collocations: ["affecting the process of communication"], examSynonyms: ["influence（影响，亦可作名词）", "shape（塑造）"], confusions: ["affect 通常是动词‘影响’；effect 多作名词‘影响/结果’。"] }),
  communication: e("n.", "交流；信息传播", "the process of communication 指科学知识在研究者之间传播与发表的过程。", { specialForms: ["communication—communications（通信系统/多次交流）"], examSynonyms: ["exchange（交流交换）", "transmission（传递）"], wordFamily: ["communicate v. 交流", "communicative adj. 善于交流的"] }),
  professionalisation: e("n.", "职业化；专业人员主导化", "指科学活动逐渐由受过专门训练、遵循共同规范的职业研究者主导。", { specialForms: ["professionalisation（英式）/ professionalization（美式）"], collocations: ["the growing professionalisation of scientific activity", "the process of professionalisation and specialisation"], examSynonyms: ["professionalization（美式拼写）", "institutionalisation（制度化，侧重点不同）"], wordFamily: ["profession n. 职业", "professional n./adj. 专业人士；专业的", "professionalise v. 使职业化"] }),
  "clear-cut": e("adj.", "界线清楚的；明确的", "clear-cut distinction 指可以明确划界、不含模糊地带的区分。", { specialForms: regular, collocations: ["draw a clear-cut distinction"], examSynonyms: ["definite（明确的）", "unambiguous（无歧义的）"] }),
  professional: e("n./adj.", "专业人士；专业的", "professionals 指科学职业共同体成员；professional journals/geologists 作定语表示专业界的。", { specialForms: ["professional—professionals（名词复数）"], collocations: ["between professionals and amateurs", "become acceptable to professionals"], examSynonyms: ["specialist（专家，强调专长）", "expert（专家，强调能力）"], wordFamily: ["profession n. 职业", "professionalise v. 使职业化", "professionalisation n. 职业化"] }),
  amateur: e("n./adj.", "业余研究者；非职业的", "全文指未完全融入专业科学共同体、通常未接受同等训练的研究者，不等于‘能力差的人’。", { specialForms: ["amateur—amateurs（复数）"], collocations: ["between professionals and amateurs", "amateur participation in science"], examSynonyms: ["non-professional（非职业者，中性）", "layperson（外行，强调缺乏专业知识）"], confusions: ["amateur 可有‘业余爱好者’的中性义，不能一律贬译为‘外行’。"] }),
  exception: e("n.", "例外", "exceptions to any rule 说明专业与业余的划分不能绝对化。", { specialForms: ["exception—exceptions（复数）"], collocations: ["exceptions to any rule"], examSynonyms: ["anomaly（异常现象）", "deviation（偏离常规）"] }),
  nevertheless: e("adv.", "尽管如此；然而", "承认二者界线不绝对后，转而强调 amateur 一词仍有典型含义。", { specialForms: structure, examSynonyms: ["nonetheless（尽管如此，几乎同义）", "however（然而，位置更灵活）"] }),
  carry: e("v.", "带有；传达", "carry a connotation 表词语附带某种联想义；does 用于强调。", { specialForms: ["carry—carried—carried—carrying"], collocations: ["does carry a connotation"], examSynonyms: ["convey（传达）", "bear（带有，较正式）"] }),
  connotation: e("n.", "言外之意；附加含义", "that 同位语从句完整解释 amateur 一词所带的 connotation。", { specialForms: ["connotation—connotations（复数）"], collocations: ["does carry a connotation"], examSynonyms: ["implication（暗含意义/影响）", "association（联想）"], confusions: ["denotation 指字面指称义；connotation 指附加联想义。"] }),
  person: e("n.", "人；个人", "the person concerned 指 amateur 这个词所指的那个人。", { specialForms: ["person—people/persons（复数；persons 更正式）"], collocations: ["the person concerned"], examSynonyms: ["individual（个人，强调个体）", "human being（人类个体）"] }),
  concern: e("v./n.", "涉及；与……有关", "the person concerned 中 concerned 后置表示‘所涉及/所说的’，不是‘担忧的’。", { specialForms: ["concern—concerned—concerned—concerning"], collocations: ["the person concerned"], examSynonyms: ["involved（涉及的）", "relevant（相关的）"], confusions: ["a concerned person 常指忧虑的人；the person concerned 指相关人员。"] }),
  integrate: e("v.", "使融入；使成为整体", "be integrated into the scientific community 表被接纳并融入科学共同体。", { specialForms: ["integrate—integrated—integrated—integrating"], collocations: ["be integrated into the scientific community"], examSynonyms: ["incorporate（纳入整体）", "assimilate（同化/融入）"], wordFamily: ["integration n. 融合", "integrated adj. 综合的；融合的"] }),
  nineteenth: e("ordinal number/adj.", "第十九；十九世纪的", "the nineteenth century 是全文主要历史时期。", { specialForms: ["nineteen—nineteenth（基数词—序数词）"], examSynonyms: ["19th（缩写形式）"] }),
  consequent: e("adj.", "随之产生的；作为结果的", "consequent requirement 表专业化增长直接带来的训练要求。", { specialForms: regular, collocations: ["with its consequent requirement"], examSynonyms: ["resulting（由此产生的）", "subsequent（随后的，但不必有因果）"], confusions: ["consequent 强调因果；subsequent 只强调时间在后。"] }),
  complex: e("adj./n.", "复杂的", "more complex training 与 longer 并列，表示训练内容和要求更加复杂。", { specialForms: ["complex—more complex—most complex"], examSynonyms: ["complicated（复杂的，常带难处理意味）", "intricate（错综复杂的）"] }),
  training: e("n.", "训练；专业培养", "mathematical or laboratory training 指进入相关学科所需的数学或实验技能培养。", { specialForms: ["training 通常不可数；具体训练项目时可数"], collocations: ["a longer, more complex training", "be based on a mathematical or laboratory training"], examSynonyms: ["education（教育，范围更广）", "instruction（指导教学）"] }),
  imply: e("v.", "意味着；必然带来", "implied greater problems 中主语是专业化增长，表示它客观上带来更大困难。", { specialForms: ["imply—implied—implied—implying"], examSynonyms: ["suggest（暗示）", "entail（必然包含/导致）"], confusions: ["本句接结果时更接近 entail，不是说话者含蓄暗示。"] }),
  great: e("adj.", "更大的；更严重的", "greater problems 是 great 的比较级，表示业余参与面临的困难增加。", { specialForms: ["great—greater—greatest"], examSynonyms: ["major（重大的）", "considerable（相当大的）"] }),
  trend: e("n.", "趋势", "The trend 回指专业化使业余参与越来越困难的变化。", { specialForms: ["trend—trends（复数）"], collocations: ["be most obvious in"], examSynonyms: ["tendency（倾向）", "development（发展趋势）"] }),
  area: e("n.", "领域；范围", "areas of science 指不同科学领域。", { specialForms: ["area—areas（复数）"], collocations: ["areas of science based on training"], examSynonyms: ["field（领域）", "domain（领域，较正式）"] }),
  mathematical: e("adj.", "数学的；需要数学训练的", "mathematical training 与 laboratory training 并列，作为第 21 题识别 physics 的依据。", { specialForms: regular, examSynonyms: ["quantitative（定量的）", "numerical（数值的）"], wordFamily: ["mathematics n. 数学", "mathematician n. 数学家"] }),
  laboratory: e("n./adj.", "实验室；实验室训练的", "laboratory training 指实验操作训练，是第 21 题识别 chemistry 的依据。", { specialForms: ["laboratory—laboratories（复数）"], examSynonyms: ["experimental（实验的）", "lab（实验室，非正式缩写）"] }),
  illustrate: e("v.", "举例说明；阐明", "can be illustrated in terms of geology 表可以通过地质学案例来说明这一趋势。", { specialForms: ["illustrate—illustrated—illustrated—illustrating"], collocations: ["be illustrated in terms of"], examSynonyms: ["demonstrate（说明/证明）", "exemplify（作为例子说明）"] }),
  term: e("n.", "方面；术语；条件", "in terms of 在本句表示‘从……方面/借助……来说明’，不是单独的‘术语’。", { specialForms: ["term—terms（复数）"], collocations: ["be illustrated in terms of"], examSynonyms: ["respect（方面，in this respect）", "language（措辞）"] }),
  geology: e("n.", "地质学", "英国地质学的发展被用作专业化与职业化过程的完整案例。", { specialForms: ["geology（学科名词，通常不可数）"], collocations: ["the development of geology in the United Kingdom"], examSynonyms: ["earth science（地球科学，范围更广）"], wordFamily: ["geological adj. 地质学的", "geologist n. 地质学家"] }),
  kingdom: e("n.", "王国；United Kingdom 国名组成", "the United Kingdom 是英国正式国名，不能把 Kingdom 单独按普通‘王国’拆译。", { specialForms: ["kingdom—kingdoms（复数）"], examSynonyms: ["Britain（英国，常用简称）"] }),
  comparison: e("n.", "比较；对照", "A comparison of publications 是主语，通过跨时期对照揭示标准变化。", { specialForms: ["comparison—comparisons（复数）"], examSynonyms: ["contrast（对比差异）", "analysis（分析）"], wordFamily: ["compare v. 比较", "comparative adj. 比较的"] }),
  geological: e("adj.", "地质学的", "geological publications/studies/picture/journals 均限定为地质学领域。", { specialForms: regular, examSynonyms: ["geologic（地质学的，美式常见变体）"], wordFamily: ["geology n. 地质学", "geologist n. 地质学家"] }),
  publication: e("n.", "出版物；发表", "British geological publications 在本篇指已发表的期刊论文和出版材料，而不是上一文章‘信件的发表’事件义。", { specialForms: ["publication—publications（复数）"], examSynonyms: ["journal article（期刊文章）", "published work（出版成果）"], wordFamily: ["publish v. 出版；发表", "publisher n. 出版者"] }),
  half: e("n./det./pron./adv.", "一半", "a century and a half 表一个半世纪。", { specialForms: ["half—halves（名词复数）"], examSynonyms: ["one-half（二分之一）"] }),
  reveal: e("v.", "揭示；显示", "comparison 作主语，reveals 后接 not simply A but also B 两项发现。", { specialForms: ["reveal—revealed—revealed—revealing"], examSynonyms: ["show（显示）", "disclose（披露隐藏信息）"] }),
  simply: e("adv.", "仅仅；只是", "not simply A but also B 中 simply 限定第一项，构成‘不仅……而且……’。", { specialForms: regular, collocations: ["not simply A but also B"], examSynonyms: ["merely（仅仅）", "only（只是）"] }),
  change: e("v./n.", "变化中的；改变", "changing definition 中 changing 作定语，表示论文定义正在变化。", { specialForms: ["change—changed—changed—changing"], examSynonyms: ["alter（改变）", "shift（转变）"] }),
  definition: e("n.", "定义；判定标准", "a changing definition of what constitutes... 指合格研究论文的判定标准发生变化。", { specialForms: ["definition—definitions（复数）"], examSynonyms: ["criterion（标准）", "description（界定说明）"], wordFamily: ["define v. 定义", "definite adj. 明确的"] }),
  constitute: e("v.", "构成；算作", "what constitutes an acceptable research paper 中 what 作主语，paper 是构成的结果。", { specialForms: ["constitute—constituted—constituted—constituting"], collocations: ["what constitutes an acceptable research paper"], examSynonyms: ["form（构成）", "amount to（相当于/构成）"] }),
  paper: e("n.", "研究论文", "research paper 指学术论文，不是纸张。", { specialForms: ["paper—papers（论文/报纸时可数）"], collocations: ["what constitutes an acceptable research paper"], examSynonyms: ["article（论文/文章）", "study（研究成果）"], confusions: ["paper 在考试语境也可指试卷；本句由 research 判定为论文。"] }),
  thus: e("adv.", "因此；由此", "承接上一句所说的定义变化，引出十九、二十世纪标准的具体对照。", { specialForms: structure, examSynonyms: ["therefore（因此）", "consequently（因此，强调结果）"] }),
  local: e("adj./n.", "地方性的；局部的", "local geological studies 指针对某一地区的地质研究，与 wider picture 对比。", { specialForms: regular, examSynonyms: ["regional（区域性的）", "limited（范围有限的）"] }),
  study: e("n./v.", "研究；研究成果", "local studies 作复数名词，指地区性地质研究项目或论文。", { specialForms: ["study—studies（复数）；study—studied—studied—studying（动词）"], collocations: ["continue to pursue local studies"], examSynonyms: ["research（研究，通常不可数）", "investigation（调查研究）"] }),
  represent: e("v.", "构成；算作", "represented worthwhile research 表地方研究在当时本身就算有价值的研究。", { specialForms: ["represent—represented—represented—representing"], examSynonyms: ["constitute（构成，较正式）", "amount to（相当于）"] }),
  worthwhile: e("adj.", "值得做的；有价值的", "worthwhile research 表具有独立学术价值、值得开展的研究。", { specialForms: regular, examSynonyms: ["valuable（有价值的）", "rewarding（有收获的）"], confusions: ["worthwhile 可直接修饰名词；worth 常用 be worth doing。"] }),
  incorporate: e("v.", "把……纳入；包含", "地方研究必须 incorporate the wider geological picture，即把局部发现放进整体框架。", { specialForms: ["incorporate—incorporated—incorporated—incorporating"], collocations: ["incorporate the wider geological picture"], examSynonyms: ["include（包括）", "integrate（整合）"] }),
  reflect: e("v.", "认真思考；评述", "reflect on the wider picture 中 on 不能省，表示思考整体含义。", { specialForms: ["reflect—reflected—reflected—reflecting"], collocations: ["reflect on the wider geological picture"], examSynonyms: ["consider（考虑）", "contemplate（深思）"], confusions: ["reflect sth 可表示‘反映某物’；reflect on sth 表‘思考某事’。"] }),
  wide: e("adj./adv.", "更广阔的；整体范围更大的", "wider geological picture 与 local studies 对比，指超出单一地区的总体地质框架。", { specialForms: ["wide—wider—widest"], examSynonyms: ["broader（范围更广）", "larger（规模更大）"] }),
  picture: e("n./v.", "整体图景；全局", "the wider geological picture 是抽象义，指更宏观的地质理论和区域联系。", { specialForms: ["picture—pictures（复数）"], examSynonyms: ["context（整体背景）", "framework（框架）"] }),
  continue: e("v.", "继续", "have continued to pursue 使用现在完成时，表示业余者一直沿用旧方式。", { specialForms: ["continue—continued—continued—continuing"], collocations: ["continue to pursue local studies"], examSynonyms: ["persist（坚持，常接 in）", "carry on（继续）"] }),
  pursue: e("v.", "从事；开展", "pursue local studies 是学术语境，表示持续进行研究。", { specialForms: ["pursue—pursued—pursued—pursuing"], collocations: ["continue to pursue local studies"], examSynonyms: ["conduct（开展研究）", "undertake（承担/从事）"] }),
  overall: e("adj./adv./n.", "总体的；综合的", "the overall result 汇总论文标准、业余做法等因素造成的最终结果。", { specialForms: regular, examSynonyms: ["general（总体的）", "total（全部的）"] }),
  entrance: e("n.", "进入资格；准入", "entrance to professional journals 不是走进建筑，而是论文获准发表。", { specialForms: ["entrance—entrances（复数）"], collocations: ["make entrance to professional journals harder"], examSynonyms: ["entry（进入/准入）", "access（进入权）"], wordFamily: ["enter v. 进入"] }),
  journal: e("n.", "学术期刊", "professional geological journals 指专业地质学期刊，是发表准入的载体。", { specialForms: ["journal—journals（复数）"], collocations: ["make entrance to professional journals harder", "separate journals have appeared"], examSynonyms: ["periodical（期刊，范围更广）", "academic publication（学术出版物）"] }),
  hard: e("adj./adv.", "更困难的", "make entrance harder 中 harder 是宾语补足语，说明准入难度提高。", { specialForms: ["hard—harder—hardest"], examSynonyms: ["difficult（困难的）", "demanding（要求高的）"], confusions: ["hardly 是‘几乎不’，不是 hard 的普通副词比较形式。"] }),
  reinforce: e("v.", "加强；进一步巩固", "同行评审的普及 reinforced 业余者难以进入期刊这一结果。", { specialForms: ["reinforce—reinforced—reinforced—reinforcing"], collocations: ["a result that has been reinforced"], examSynonyms: ["strengthen（加强）", "intensify（加剧）"] }),
  widespread: e("adj.", "广泛的；普遍的", "widespread introduction 表同行评审被许多期刊采用。", { specialForms: regular, examSynonyms: ["extensive（广泛的）", "prevalent（普遍存在的）"] }),
  refereeing: e("n./gerund", "同行评审；论文审稿", "此处指论文在发表前由同行专家评议的制度，不是体育裁判。", { specialForms: ["referee—refereed—refereed—refereeing"], collocations: ["the widespread introduction of refereeing"], examSynonyms: ["peer review（同行评审，现代常用表达）", "reviewing（审阅）"], wordFamily: ["referee n. 审稿人；裁判"] }),
  national: e("adj.", "全国性的；国家级的", "national journals 与 local journals 对比，说明同行评审先在全国性期刊采用。", { specialForms: regular, examSynonyms: ["nationwide（全国范围的）", "state-level（国家层面的，语义依制度）"] }),
  several: e("det./pron.", "若干；几个", "several local journals 表数量多于两个但不具体。", { specialForms: structure, examSynonyms: ["a number of（若干）", "some（一些，范围更宽）"] }),
  logical: e("adj.", "合乎逻辑的；必然可推得的", "logical consequence 表前述分化自然导致期刊分流。", { specialForms: regular, collocations: ["as a logical consequence of"], examSynonyms: ["reasonable（合理的）", "natural（自然产生的）"], wordFamily: ["logic n. 逻辑", "logically adv. 合乎逻辑地"] }),
  separate: e("adj./v.", "不同的；分开的", "separate journals 中作形容词，指专业与业余读者各有不同期刊。", { specialForms: ["separate—separated—separated—separating（动词）"], examSynonyms: ["distinct（不同的）", "independent（独立的）"] }),
  appear: e("v.", "出现；产生", "have appeared 是不及物现在完成时，表示分流期刊已经出现。", { specialForms: ["appear—appeared—appeared—appearing"], collocations: ["separate journals have appeared"], examSynonyms: ["emerge（逐渐出现）", "arise（出现，常指问题/机会）"] }),
  aim: e("v./n.", "面向；以……为目标", "journals aimed towards a readership 是过去分词后置定语，说明目标读者群。", { specialForms: ["aim—aimed—aimed—aiming"], collocations: ["be aimed towards"], examSynonyms: ["target（以……为目标）", "be intended for（为……而设）"] }),
  readership: e("n.", "读者群", "professional or amateur readership 表期刊各自面向的群体，常作集合名词。", { specialForms: ["readership—readerships（不同读者群时可数）"], examSynonyms: ["audience（受众，范围更广）", "readers（读者们）"], wordFamily: ["read v. 阅读", "reader n. 读者"] }),
  similar: e("adj.", "相似的", "a rather similar process 回指与期刊分流相似的学会组织分化。", { specialForms: regular, examSynonyms: ["comparable（可比较的）", "analogous（相似对应的）"], confusions: ["similar 常接 to；same 常接 as。"] }),
  differentiation: e("n.", "分化；差异化", "指专业与业余群体逐渐形成不同期刊、学会和规范。", { specialForms: ["differentiation 通常不可数"], collocations: ["a process of differentiation"], examSynonyms: ["division（分开）", "distinction（区别）"], wordFamily: ["different adj. 不同的", "differentiate v. 区分；使分化"] }),
  lead: e("v./n.", "导致；促成", "has led to 后接 geologists coming together，to 是介词。", { specialForms: ["lead—led—led—leading"], collocations: ["lead to professional geologists coming together"], examSynonyms: ["result in（导致）", "bring about（引起）"], confusions: ["lead 的过去式是 led，不是 leaded（除特定义‘加铅’）。"] }),
  geologist: e("n.", "地质学家", "professional geologists 是 coming together 的逻辑主语。", { specialForms: ["geologist—geologists（复数）"], examSynonyms: ["earth scientist（地球科学家，范围更广）"], wordFamily: ["geology n. 地质学", "geological adj. 地质学的"] }),
  together: e("adv.", "共同；联合起来", "come together nationally 指形成全国性组织联合。", { specialForms: structure, collocations: ["come together nationally"], examSynonyms: ["collectively（集体地）", "jointly（共同地）"] }),
  nationally: e("adv.", "在全国范围内", "分别修饰专业和业余群体 come together 的组织范围。", { specialForms: regular, collocations: ["come together nationally"], examSynonyms: ["nationwide（遍及全国地）", "at national level（在全国层面）"], wordFamily: ["nation n. 国家", "national adj. 全国性的"] }),
  within: e("prep./adv.", "在……内部；在……范围内", "within specific societies 指专业地质学家集中在少数特定学会内部。", { specialForms: structure, collocations: ["within specific societies"], examSynonyms: ["inside（在内部，更具体空间）", "in（在……中，范围更宽）"] }),
  specific: e("adj.", "特定的；专门的", "one or two specific societies 指少数明确、专门面向职业地质学家的全国性学会。", { specialForms: regular, examSynonyms: ["particular（特定的）", "specialized（专门的）"] }),
  society: e("n.", "学会；协会", "local/specific societies 在学术语境指研究者组织，不是整个‘社会’。", { specialForms: ["society—societies（复数）"], examSynonyms: ["association（协会）", "organization（组织）"], confusions: ["由 local/geological 语境判断为学会，而非社会整体。"] }),
  tend: e("v.", "往往；倾向于", "have tended either to remain... or to come... 表业余者长期形成的两种组织倾向。", { specialForms: ["tend—tended—tended—tending"], collocations: ["tend either to A or to B"], examSynonyms: ["be inclined to（倾向于）", "be likely to（很可能）"] }),
  although: e("conj.", "尽管；虽然", "引导让步从句，承认十九世纪过程已展开，再突出完整后果较晚显现。", { specialForms: structure, examSynonyms: ["though（尽管，较灵活）", "while（虽然/而，需看语境）"], confusions: ["although 从句后主句不再与 but 连用。"] }),
  during: e("prep.", "在……期间", "during the nineteenth century 后接名词时间段，说明过程发生时期。", { specialForms: structure, examSynonyms: ["throughout（贯穿整个期间）", "in（在某时期）"] }),
  full: e("adj.", "全部的；完整的", "full consequences 指职业化、专业化所造成的所有深层结构后果。", { specialForms: ["full—fuller—fullest（较少用于本义）"], examSynonyms: ["complete（完整的）", "entire（全部的）"] }),
  delay: e("v./n.", "推迟；较晚出现", "full consequences were delayed until... 是被动表达，表示完整影响到二十世纪才显现。", { specialForms: ["delay—delayed—delayed—delaying"], collocations: ["be delayed until the twentieth century"], examSynonyms: ["postpone（推迟安排）", "defer（延期，较正式）"] }),
  until: e("prep./conj.", "直到……为止", "until the twentieth century 给出延迟状态结束的时间点。", { specialForms: structure, examSynonyms: ["till（直到，较口语）", "up to（直到，适用结构不同）"] }),
  reckon: e("v.", "认为；视为", "must be reckoned as 是 reckon A as B 的被动式，评价十九世纪的历史地位。", { specialForms: ["reckon—reckoned—reckoned—reckoning"], collocations: ["be reckoned as"], examSynonyms: ["regard（视为）", "consider（认为，宾补前通常不用 as）"] }),
  clear: e("adj./adv./v.", "清楚地；明显地", "more clearly seen 中 clearly 修饰 seen，题干问在哪些学科中更明显看出趋势。", { specialForms: ["clear—clearer—clearest；clearly adv."], examSynonyms: ["plainly（清楚地）", "obviously（明显地）"] }),
  sociology: e("n.", "社会学", "第 21 题干扰项学科；原文强调数学或实验室训练最明显，sociology 不构成标准答案中的典型对应。", { specialForms: ["sociology（学科名词）"], examSynonyms: ["social science（社会科学，范围更广）"], wordFamily: ["sociological adj. 社会学的", "sociologist n. 社会学家"] }),
  chemistry: e("n.", "化学", "第 21 题正确项之一，典型依赖 laboratory training。", { specialForms: ["chemistry（学科名词）"], examSynonyms: ["chemical science（化学科学）"], wordFamily: ["chemical adj./n. 化学的；化学品", "chemist n. 化学家"] }),
  physics: e("n.", "物理学", "第 21 题正确项之一，典型依赖 mathematical training。", { specialForms: ["physics 形式似复数但作学科名时谓语用单数"], examSynonyms: ["physical science（物理科学，范围可更广）"], wordFamily: ["physical adj. 物理的", "physicist n. 物理学家"] }),
  psychology: e("n.", "心理学", "第 21 题干扰项学科，不能与 physics 组成原文两类训练的最佳典型组合。", { specialForms: ["psychology（学科名词）"], examSynonyms: ["behavioral science（行为科学，范围不同）"], wordFamily: ["psychological adj. 心理的", "psychologist n. 心理学家"] }),
  compete: e("v.", "竞争；比肩", "第 22 题 B 项指业余者在某些领域仍可能与专业人士竞争。", { specialForms: ["compete—competed—competed—competing"], examSynonyms: ["rival（与……竞争）", "contend（竞争/争夺）"], wordFamily: ["competition n. 竞争", "competitor n. 竞争者", "competitive adj. 有竞争力的"] }),
  welcome: e("v./adj./n.", "欢迎；乐于接纳", "第 22 题 C 项声称 professionals 欢迎 amateurs，但原文只描述门槛提高。", { specialForms: ["welcome—welcomed—welcomed—welcoming"], examSynonyms: ["accept（接受）", "embrace（欣然接受）"] }),
  academic: e("adj./n.", "学术的；学术人员", "academic societies 指学术团体，是第 22 题 D 项对原文 societies 的概括。", { specialForms: ["academic—academics（名词复数）"], examSynonyms: ["scholarly（学术性的）", "educational（教育的）"] }),
  one: e("pron./det./number", "前面提到的那一类/那些", "no local ones 中 ones 替代重复的 local academic societies。", { specialForms: ["one—ones（替代词复数）"], examSynonyms: ["those（那些，指代方式不同）"] }),
  write: e("v.", "写到；论述", "The author writes of... 中 write of 表写到、谈论地质学发展。", { specialForms: ["write—wrote—written—writing"], examSynonyms: ["discuss（论述）", "describe（描述）"] }),
  demonstrate: e("v.", "说明；展示", "第 23 题问地质学案例用来说明什么，答案是专业化与职业化过程。", { specialForms: ["demonstrate—demonstrated—demonstrated—demonstrating"], examSynonyms: ["illustrate（举例说明）", "show（显示）"] }),
  hardship: e("n.", "困难；困苦", "第 23 题 B 项只概括业余者面临的困难，是地质学案例的局部后果。", { specialForms: ["hardship—hardships（复数）"], examSynonyms: ["difficulty（困难）", "adversity（逆境）"] }),
  policy: e("n.", "政策；方针", "第 23 题 C 项把学术发表标准变化缩窄为 publications 的政策变化。", { specialForms: ["policy—policies（复数）"], examSynonyms: ["rule（规则）", "guideline（指导原则）"] }),
  discrimination: e("n.", "歧视；区别对待", "第 23 题 D 项加入主观歧视动机，而原文只说明结构性分化。", { specialForms: ["discrimination 通常不可数"], examSynonyms: ["bias（偏见）", "prejudice（成见）"], wordFamily: ["discriminate v. 区分；歧视", "discriminatory adj. 歧视性的"] }),
  direct: e("adj./v.", "直接的", "direct reason 要求找到首句明确因果，而不是相关发展或后续影响。", { specialForms: regular, examSynonyms: ["immediate（直接的/紧接的）", "primary（主要的）"] }),
  expansion: e("n.", "扩展；增长", "the expansion of scientific knowledge 是对 increasing accumulation 的同义改写。", { specialForms: ["expansion—expansions（复数）"], examSynonyms: ["growth（增长）", "increase（增加）"], wordFamily: ["expand v. 扩大", "expansive adj. 广阔的"] }),
  implication: e("n.", "含义；暗示", "可替换 connotation 表词语暗含的意义，但 implication 还常表示可能产生的后果。", { specialForms: ["implication—implications（复数）"], examSynonyms: ["connotation（词语的附加联想义）", "suggestion（暗示）"], wordFamily: ["imply v. 暗示；意味着"] }),
  strengthen: e("v.", "加强；使更有力", "可替换 reinforce 描述同行评审使期刊准入门槛的结果进一步加强。", { specialForms: ["strengthen—strengthened—strengthened—strengthening"], examSynonyms: ["reinforce（强化）", "enhance（增强）"], wordFamily: ["strength n. 力量", "strong adj. 强的"] }),
  emerge: e("v.", "出现；逐渐形成", "可替换 appear，强调专业与业余期刊在分化过程中逐渐形成。", { specialForms: ["emerge—emerged—emerged—emerging"], examSynonyms: ["appear（出现）", "arise（产生）"] }),
  decisive: e("adj.", "决定性的；关键的", "可替换 crucial 评价十九世纪对科学结构变化具有决定作用。", { specialForms: regular, examSynonyms: ["crucial（关键的）", "critical（决定性的/关键的）"], wordFamily: ["decide v. 决定", "decision n. 决定"] }),
  effect: e("n./v.", "影响；结果", "full effects 可替换 full consequences，表示专业化与职业化产生的全部结构性影响。", { specialForms: ["effect—effects（复数）；effect—effected—effected（动词）"], examSynonyms: ["consequence（后果，因果色彩更强）", "impact（影响，常强调力度）"], confusions: ["effect 通常作名词‘影响/结果’；affect 通常作动词‘影响’。"] }),
};
