import type { PracticeTask, GrammarConceptId, ErrorCategory } from "./learning-model";
const choice = (id: string, prompt: string, options: string[], answer: number, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "choice", prompt, options, answer: options[answer], evidence, feedback, conceptId, errorType, ...extra });
const range = (id: string, prompt: string, answer: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "range", prompt, options: [], answer, evidence: answer, feedback, conceptId, errorType, ...extra });
const link = (id: string, prompt: string, pairs: Array<[string, string]>, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "link", prompt, links: pairs.map(([source, target]) => ({ source, target })), options: [...new Set(pairs.map(([, target]) => target))], answer: JSON.stringify(pairs.map(([, target]) => target)), evidence, feedback, conceptId, errorType, ...extra });
const order = (id: string, prompt: string, blocks: string[], distractors: string[], evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "order", prompt, options: [...blocks, ...distractors], answer: JSON.stringify(blocks), evidence, feedback, conceptId, errorType, ...extra });

export const passage2001P2Practice: Record<string, PracticeTask[]> = {
  "2001-p2-s1": [
    range("progressive-passive", "划出表示目前正在受到关注的完整动词组，不含today。", "is being paid", "is加being表示进行，being paid表示被动；主语attention是被投入的关注，to再引出关注对象。", "passive-voice", "predicate", { hintWords: ["is", "being", "paid"] }),
    choice("dash-definition", "破折号后的division是什么作用？", ["解释digital divide所指差距", "另一个有独立谓语的句子", "证明信息贫困者都是经济富人"], 0, "the division of the world into the info (information) rich and the info poor", "division是名词，没有新的有限谓语；the rich/the poor名词化指两类群体，info说明信息资源层面的贫富。", "apposition", "attachment", { hintWords: ["division", "info", "rich", "poor"], mapRevealsAnswer: true }),
  ],
  "2001-p2-s2": [choice("emphatic-existence", "does exist里的does表达什么？", ["肯定句强调：确实存在", "疑问：是否存在", "实义动作：做一个鸿沟"], 0, "that divide does exist today", "does承担第三人称一致并强调exist，后者用原形；that在divide前限定所指，不是从句连接词。", "finite-predicate", "predicate", { hintWords: ["does", "exist", "that"] })],
  "2001-p2-s3": [link("danger-time", "将指代与时间各自接回参照点。", [["this looming danger", "前两句的数字鸿沟"], ["twenty years ago", "作者叙述时往前二十年"]], "this looming danger twenty years ago", "danger是作者对数字鸿沟的评价；ago不从现在做题的日期倒推，也不能只因2001为考试年份就给出精确演讲年。", "reference-pronoun", "reference", { hintWords: ["this", "looming", "danger", "ago"], mapRevealsAnswer: true })],
  "2001-p2-s4": [
    range("what-subject", "划出主句were的完整主语，从What开始。", "What was less visible then", "What从句整体作主语，内部was有自己的表语less visible；主句were在however之后。", "clause-subject", "subject", { hintWords: ["What", "was", "were"] }),
    link("two-relative-roles", "区分what与that所处层级和作用。", [["What was less visible then", "整体作主句主语"], ["that work against the digital divide", "修饰积极力量forces"]], "What was less visible then, however, were the new, positive forces that work against the digital divide", "what从句给待说明内容，forces表语给答案；that再限定力量的作用。积极的是缩小鸿沟的力量，不是鸿沟。", "clause-relative", "attachment", { hintWords: ["What", "that", "forces", "positive"], mapRevealsAnswer: true, leaksToTaskIds: ["what-subject"] }),
  ],
  "2001-p2-s5": [choice("optimistic-reasons", "to be optimistic与reasons是什么关系？", ["说明有理由采取的乐观态度", "表示reasons自己会乐观", "构成过去完成时"], 0, "reasons to be optimistic", "不定式补充理由指向的态度；there are为存在结构，there不指那里，reasons不是有情绪的人。", "nonfinite-infinitive", "attachment", { hintWords: ["There", "reasons", "to", "optimistic"] })],
  "2001-p2-s6": [range("hope-content", "只划出hope的完整宾语内容，不包含to hope。", "the digital divide will narrow", "这是省略that的宾语从句，有主语divide和谓语will narrow；to hope整组再补足reasons。不要补写原文未出现的that。", "clause-object", "clause-boundary", { hintWords: ["hope", "divide", "narrow"] })],
  "2001-p2-s7": [
    link("formal-and-real", "将主句占位、评价和真正内容对应起来。", [["it", "形式主语"], ["in the interest of business", "表语：符合商业利益"], ["to universalize access", "真正主语：普及接入"]], "it is in the interest of business to universalize access", "it不回指Internet；主句评价的是普及接入这件事符合商业利益。interest在此是利益，不是爱好。", "subject-head", "subject", { hintWords: ["it", "interest", "to", "universalize"] }),
    choice("customer-correlation", "the more...the more...联系哪两个数量？", ["上网人数与潜在顾客人数", "已付费顾客与所有穷人数量", "政府数量与已经消除的贫困数量"], 0, "the more people online, the more potential customers there are", "potential保留潜在性，更多用户带来更多可能顾客，不表示每位用户已购买；这是作者解释商业推广动力的逻辑。", "comparison-scope", "passage-logic", { hintWords: ["more", "online", "potential", "customers"], mapRevealsAnswer: true, leaksToTasks: [{ sentenceId: "2001-p2-map", taskId: "optimistic-forces" }] }),
  ],
  "2001-p2-s8": [
    order("government-trunk", "暂时移开担忧背景，重建政府的主句。", ["More and more governments", "want", "to spread Internet access"], ["their countries", "will be left behind"], "want to spread Internet access", "主语是governments；countries属于afraid内部内容从句，不能因位置靠近就当want的主语。", "subject-head", "subject", { hintWords: ["governments", "afraid", "want"] }),
    range("fear-content", "划出afraid后的完整担忧内容。", "their countries will be left behind", "their countries是内容从句主语；will be left behind是将来被动。担心发展掉队为政府推广网络提供动机。", "complement-content", "clause-boundary", { hintWords: ["afraid", "their", "left", "behind"], mapRevealsAnswer: true }),
  ],
  "2001-p2-s9": [link("forecast-scale", "按原句匹配预测的期限与人数范围。", [["Within the next decade or two", "叙述时之后一二十年内"], ["one to two billion people", "十亿至二十亿人"]], "Within the next decade or two, one to two billion people", "这是作者当时的预测，非本网站对现今联网人数的统计。原卷后半he疑似be误排，规范将来被动用will be netted；本题只训练可靠的时间与数字关系。", "time-reference", "tense", { hintWords: ["Within", "next", "decade", "billion"], mapRevealsAnswer: true })],
  "2001-p2-s10": [
    range("belief-content", "划出believe后完整的预测内容，包含未来时间。", "the digital divide will narrow rather than widen in the years ahead", "now属于主句相信发生的时间；in the years ahead属于预测变化时间。内容从句到句末，不在widen前后截断。", "clause-object", "clause-boundary", { hintWords: ["believe", "will", "ahead"], leaksToTaskIds: ["narrow-not-widen"] }),
    choice("narrow-not-widen", "rather than将作者的预测落在哪一边？", ["数字鸿沟将缩小", "数字鸿沟必将扩大", "数字鸿沟已经完全消失"], 0, "will narrow rather than widen", "narrow是所选方向，widen被rather than排除；will预测未来，不等于已经解决所有差距。", "negation-contrast", "passage-logic", { hintWords: ["narrow", "rather", "widen"], mapRevealsAnswer: true }),
  ],
  "2001-p2-s11": [
    link("that-levels", "将两个that分别接到其作用。", [["And that is中的that", "回指鸿沟将缩小的预测"], ["that we’ve ever had中的that", "回指tool并作had的宾语"]], "that is very good news because the Internet may well be the most powerful tool for combating world poverty that we’ve ever had", "第一个that是主句指示代词，第二个是关系代词；不能把第二个接成最近的poverty，也不能把两者都当内容连接词。", "clause-relative", "reference", { hintWords: ["that", "tool", "had"], mapRevealsAnswer: true }),
    choice("may-well-strength", "may well be the most powerful tool是否承诺很快消灭贫困？", ["没有：它强调很可能具有强大工具作用", "是：表示所有贫困已经消失", "是：well表示完成得很好"], 0, "may well be the most powerful tool", "may well是很可能、完全有理由认为，tool是手段；原文没有soon wipe out的快速、彻底保证。", "comparison-scope", "option-logic", { hintWords: ["may", "well", "powerful", "tool"], mapRevealsAnswer: true }),
  ],
  "2001-p2-s12": [choice("not-only-way", "isn’t the only way否定的是哪一项？", ["互联网是唯一扶贫方法", "互联网有任何扶贫作用", "世界存在贫困"], 0, "isn’t the only way to defeat poverty", "not否定only带来的唯一性，承认还有别的方法；不是把前面的巨大潜力全部推翻。", "negation-contrast", "passage-logic", { hintWords: ["isn’t", "only", "way"], mapRevealsAnswer: true })],
  "2001-p2-s13": [range("omitted-relative", "划出修饰tool的定语从句，只选原文实际出现的词。", "we have", "作宾语的that/which省略，回指tool；we为主语，have是拥有而非完成时。不能将省略关系词补写进选区。", "clause-relative", "clause-boundary", { hintWords: ["we", "have", "tool"] })],
  "2001-p2-s14": [choice("potential-limit", "But it has enormous potential如何承接前两句？", ["虽非唯一工具，仍有巨大潜力", "因为非唯一，所以毫无价值", "潜力已经等同全部实现的成果"], 0, "But it has enormous potential", "But转回肯定互联网潜力；potential保留可能发挥的能力，不是已完成的成绩。", "paragraph-role", "passage-logic", { hintWords: ["But", "it", "potential"], mapRevealsAnswer: true })],
  "2001-p2-s15": [
    range("purpose", "划出句首说明利用互联网目的的不定式。", "To take advantage of this tool", "To take...为目的状语，逻辑执行者是主句国家；this tool承接互联网。", "nonfinite-infinitive", "attachment", { hintWords: ["To", "tool", "To take advantage of this tool"] }),
    choice("prejudice-object", "with respect to foreign investment限定哪一组内容？", ["针对外国投资的偏见", "外国移民的人口规模", "已经得到尊重的国家"], 0, "their outdated anti-colonial prejudices with respect to foreign investment", "with respect to整体意为关于，补足prejudices对象；respect不按尊敬逐字读，investment不能换成immigrants。", "modifier-prepositional", "attachment", { hintWords: ["respect", "prejudices", "investment"], mapRevealsAnswer: true }),
  ],
  "2001-p2-s16": [
    range("country-subject", "划出might well study的完整主语，包括两层嵌套内容。", "Countries that still think foreign investment is an invasion of their sovereignty", "外层that修饰Countries并作think主语；think内部再带foreign investment is...的内容从句。句首长组结束后才到主句might study。", "subject-head", "subject", { hintWords: ["Countries", "that", "think", "might"], leaksToTaskIds: ["invasion-voice"] }),
    choice("invasion-voice", "外资侵犯主权这一看法归谁，作者的回应是什么？", ["某些国家持此看法，作者建议研究美国历史", "作者认同该看法并要求拒绝全部外资", "美国移民认定互联网无价值"], 0, "still think foreign investment is an invasion of their sovereignty", "think内是这些国家的观点；might well study是作者委婉建议，以美国史回应外资偏见，不等于作者站在同一立场。", "author-voice", "passage-logic", { hintWords: ["think", "invasion", "sovereignty", "might", "well"], mapRevealsAnswer: true }),
  ],
  "2001-p2-s17": [link("capital-reference", "将代词和替代动作接回原文。", [["it", "美国"], ["to do so", "建设本国工业基础设施"]], "it didn’t have the capital to do so", "capital为建设资金；so替代前面的build动作，不是所以。缺本国资金为下一句借外资提供原因。", "reference-pronoun", "reference", { hintWords: ["it", "capital", "so"], mapRevealsAnswer: true })],
  "2001-p2-s18": [
    range("why-content", "划出is后的完整why表语从句，保留插入列举。", "why America’s Second Wave infrastructure—including roads, harbors, highways, ports and so on—were built with foreign investment", "从why到investment都是表语内容。including只插入设施实例；主语仍为infrastructure，原卷与were搭配这一特殊形式保留而不改写。", "clause-predicative", "clause-boundary", { hintWords: ["why", "including", "were", "built"] }),
    choice("funding-not-ownership", "with foreign investment直接说明了什么？", ["建设资金来自外国投资", "设施永久属于外国投资者", "美国向外国提供援助"], 0, "were built with foreign investment", "with给出资金来源，没有自动给永久所有权；后文用投资、建造与拥有三个动词分清角色和时期。", "modifier-prepositional", "option-logic", { hintWords: ["with", "investment"], mapRevealsAnswer: true, leaksToTasks: [{ sentenceId: "2001-p2-map", taskId: "fund-build-own" }] }),
  ],
  "2001-p2-s19": [choice("former-colony", "Britain’s former colony指哪一方？", ["作为英国前殖民地的美国", "现在仍为殖民地的英国", "四个投资国的共同首都"], 0, "Britain’s former colony", "former表示曾经；结合前两句美国设施史，投资流入美国。四个并列国民名称是投资者，不是接受资金的殖民地。", "reference-pronoun", "reference", { hintWords: ["former", "colony", "Britain’s"], mapRevealsAnswer: true })],
  "2001-p2-s20": [link("finance-roles", "把They与them对应到不同角色。", [["They", "前句欧洲投资者"], ["them", "美国基础设施"]], "They financed them", "financed是为设施提供资金；不把他们出钱等同于他们必然亲自建造或永久拥有。", "reference-pronoun", "reference", { hintWords: ["They", "financed", "them"], mapRevealsAnswer: true, leaksToTasks: [{ sentenceId: "2001-p2-map", taskId: "fund-build-own" }] })],
  "2001-p2-s21": [choice("builders", "built将哪群人与前一句的出资者区分开？", ["移民出身的美国建造者", "外国公司董事会", "全部使用互联网的顾客"], 0, "Immigrant Americans built them", "本句只明确建造者为移民美国人；them依旧是基础设施。作者逐步区分资金、劳动与所有权。", "reference-pronoun", "reference", { hintWords: ["Immigrant", "Americans", "built", "them"], mapRevealsAnswer: true, leaksToTasks: [{ sentenceId: "2001-p2-map", taskId: "fund-build-own" }] })],
  "2001-p2-s22": [link("ownership-question", "把嵌入疑问从句内的词接到各自功能。", [["who", "主语：待确认的所有者"], ["owns", "谓语：拥有"], ["them", "宾语：基础设施"]], "who owns them now", "Guess是外层祈使谓语；who已经作从句主语，因此who owns无须do倒装，now问的是叙述时的所有权。", "clause-object", "predicate", { hintWords: ["who", "owns", "them"] })],
  "2001-p2-s23": [choice("answer-focus", "The Americans这个短答直接回答什么？", ["现在谁拥有那些设施", "以前所有资金都来自谁", "哪类公司可以不受监管"], 0, "The Americans", "答who owns them now，只把美国人标为现在所有者，不反推建设期间全部资金都来自美国人；省略的谓语不写回原文。", "reference-pronoun", "reference", { hintWords: ["Americans"], mapRevealsAnswer: true, leaksToTasks: [{ sentenceId: "2001-p2-map", taskId: "fund-build-own" }] })],
  "2001-p2-s24": [range("transfer-belief", "划出believe后经验可推广的完整内容。", "the same thing would be true in places like Brazil or anywhere else for that matter", "巴西和别处都在作者相信的内容中；would为设想适用，并非要求复制美国全部工业发展模式。", "clause-object", "clause-boundary", { hintWords: ["believe", "same", "would", "true"], mapRevealsAnswer: true })],
  "2001-p2-s25": [
    link("helping-actors", "为两层非谓语和关系词匹配对象。", [["helping的逻辑主语", "foreign capital"], ["build的逻辑主语", "you"], ["which的所指", "Third Wave infrastructure"]], "foreign capital you have helping you build your Third Wave infrastructure", "have capital doing中资本发挥帮助作用；help you build中you进行建设；which只解释基础设施，不能接回资本。", "nonfinite-subject", "attachment", { hintWords: ["capital", "helping", "you", "build", "which"] }),
    choice("electronic-prosperity", "the more...the better off...联系的是什么？", ["用外资建设电子基础设施与未来经济处境", "拒绝移民与工业模式完全复制", "外国公司无监管经营与必然脱贫"], 0, "the better off you’re going to be", "前项外资必须在帮助建设电子基础设施这一语境内读；后两句还排除失控，不是对任意外资的无条件收益保证。", "comparison-scope", "passage-logic", { hintWords: ["more", "electronic", "better", "off"], mapRevealsAnswer: true }),
  ],
  "2001-p2-s26": [
    range("let-object-complement", "划出mean所否定的第二组动名词内容，从letting开始。", "letting foreign corporations run uncontrolled", "letting仍在doesn't mean的否定范围；corporations既是let的宾语，又是run的执行者。run用原形。", "object-complement", "attachment", { hintWords: ["letting", "corporations", "run", "uncontrolled"], leaksToTaskIds: ["regulation-boundary"] }),
    choice("regulation-boundary", "作者是否支持让外企失控经营？", ["不支持，doesn't mean明确排除这一误解", "支持，let表示全部放任", "没有提到外企"], 0, "doesn't mean lying down and becoming fooled, or letting foreign corporations run uncontrolled", "or连接的第二组内容仍受否定；引入外资不等于放弃监管，下一句再承认其建设作用。", "negation-contrast", "passage-logic", { hintWords: ["doesn't", "mean", "or", "uncontrolled"], mapRevealsAnswer: true }),
  ],
  "2001-p2-s27": [
    range("recognition-content", "划出recognizing的完整how内容从句，包括领域和设施修饰。", "how important they can be in building the energy and telecom infrastructures needed to take full advantage of the Internet", "how important表语提前；they指外企。in building为重要性领域，needed再修饰设施，均属于认识内容。", "clause-object", "clause-boundary", { hintWords: ["recognizing", "how", "they", "needed"] }),
    link("company-and-facilities", "把代词与分词修饰分别连回正确对象。", [["they", "foreign corporations"], ["needed to take full advantage of the Internet", "the energy and telecom infrastructures"]], "they can be in building the energy and telecom infrastructures needed", "公司能帮助建设，而这些设施是充分利用互联网所需；不能把needed当公司的另一个谓语。", "nonfinite-participle", "attachment", { hintWords: ["they", "infrastructures", "needed"], mapRevealsAnswer: true }),
  ],
};
