import type { Question, SentenceAnalysis } from "./data";

export const cloze2001Sentences: SentenceAnalysis[] = [
  {
    id: "2001-cloze-s1",
    number: 1,
    text: "The government is to ban payments to witnesses by newspapers seeking to buy up people involved in prominent cases such as the trial of Rosemary West.",
    testText: "The government is to ban payments to witnesses by newspapers seeking to buy up people involved in prominent cases ___(1) the trial of Rosemary West.",
    chunks: [
      { text: "The government", role: "subject" },
      { text: " is to ban", role: "predicate" },
      { text: " payments to witnesses", role: "object" },
      { text: " by newspapers", role: "modifier" },
      { text: " seeking to buy up people", role: "modifier" },
      { text: " involved in prominent cases", role: "modifier" },
      { text: " such as the trial of Rosemary West.", role: "modifier" },
    ],
    trunk: "The government is to ban payments to witnesses.",
    layers: [
      { label: "主干", text: "The government is to ban payments to witnesses：政府将禁止向证人付款" },
      { label: "付款来源", text: "by newspapers：付款行为由报纸实施" },
      { label: "报纸目的", text: "seeking to buy up people：报纸试图出钱买断相关人的独家讲述" },
      { label: "人物范围", text: "involved in prominent cases such as...：这些人卷入重大案件，例如 Rosemary West 一案的审判" },
    ],
    grammar: [
      "be to do 表示已经安排或即将实施的官方措施，本句不是简单的系表结构。",
      "seeking to buy up people 是现在分词短语，后置修饰 newspapers，说明报纸付款的目的。",
      "involved in prominent cases 是过去分词短语，后置修饰 people；people 是‘卷入案件的人’。",
      "such as 后接具体例子；for instance 通常作插入语，不能直接占据这里的介词位置。",
    ],
    beginnerSyntax: {
      components: [
        { text: "The government", form: "定冠词 + 名词", function: "主语", modifies: "是 is to ban 的动作发出者", explanation: "先确定是谁要采取措施：the government，即政府。" },
        { text: "is to ban", form: "be to do 结构", function: "谓语", modifies: "说明政府已经安排要实施的禁令", explanation: "is to ban 整体理解为‘将要禁止’，不要把 is 单独译成‘是’。" },
        { text: "payments to witnesses", form: "名词短语 + to 介词短语", function: "宾语", modifies: "承受 ban 的动作", explanation: "禁止的对象是 payments；to witnesses 说明钱付给谁。" },
        { text: "by newspapers", form: "by + 名词的介词短语", function: "施事后置修饰语", modifies: "修饰 payments，说明付款来自报纸", explanation: "这里不是修饰 witnesses；它说明被禁止的是‘报纸实施的付款’。" },
        { text: "seeking to buy up people", form: "现在分词短语", function: "目的性后置定语", modifies: "修饰 newspapers", explanation: "哪些报纸？是那些正试图花钱买断相关人讲述的报纸。" },
        { text: "involved in prominent cases", form: "过去分词短语", function: "后置定语", modifies: "修饰 people", explanation: "哪些人？是卷入重大案件的人；involved 与 people 是被动关系。" },
        { text: "such as the trial of Rosemary West", form: "such as + 名词短语", function: "举例成分", modifies: "举例说明 prominent cases", explanation: "先读‘重大案件’，再把 Rosemary West 的审判当作其中一个例子。" },
      ],
      clauses: [],
    },
    literal: "政府将禁止报纸向证人付款；这些报纸试图花钱买断卷入重大案件者的讲述，例如 Rosemary West 一案的审判。",
    natural: "政府将禁止报纸付钱收买重大案件相关证人的独家故事，Rosemary West 审判案就是一例。",
    logic: "开篇直接提出政府拟采取的新闻与司法管制措施，并给出典型案件背景。",
    phrases: ["is to ban payments", "payments to witnesses", "seeking to buy up people", "involved in prominent cases", "such as the trial of Rosemary West"],
    answerWords: ["such as"],
  },
  {
    id: "2001-cloze-s2",
    number: 2,
    text: "In a significant tightening of legal controls over the press, Lord Irvine, the Lord Chancellor, will introduce a draft bill that will propose making payments to witnesses illegal and will strictly control the amount of publicity that can be given to a case before a trial begins.",
    testText: "In a significant ___(2) of legal controls over the press, Lord Irvine, the Lord Chancellor, will introduce a ___(3) bill that will propose making payments to witnesses ___(4) and will strictly control the amount of ___(5) that can be given to a case ___(6) a trial begins.",
    chunks: [
      { text: "In a significant tightening of legal controls over the press, ", role: "modifier" },
      { text: "Lord Irvine", role: "subject" },
      { text: ", the Lord Chancellor, ", role: "modifier" },
      { text: "will introduce", role: "predicate" },
      { text: " a draft bill", role: "object" },
      { text: " that will propose making payments to witnesses illegal", role: "modifier" },
      { text: " and will strictly control the amount of publicity", role: "modifier" },
      { text: " that can be given to a case", role: "modifier" },
      { text: " before a trial begins.", role: "modifier" },
    ],
    trunk: "Lord Irvine will introduce a draft bill.",
    layers: [
      { label: "政策背景", text: "In a significant tightening of legal controls over the press：这是一次明显收紧新闻法律监管的行动" },
      { label: "主句", text: "Lord Irvine... will introduce a draft bill：大法官 Lord Irvine 将提出一份法案草案" },
      { label: "法案内容一", text: "propose making payments to witnesses illegal：建议把向证人付款定为违法" },
      { label: "法案内容二", text: "strictly control the amount of publicity... before a trial begins：严格限制开庭前案件可获得的公开报道量" },
    ],
    grammar: [
      "a tightening of controls 表‘管制的收紧’；tightening 是名词，intensifying 不能直接放在冠词 a 后作同样的中心名词。",
      "draft bill 是固定法律表达，指尚未正式通过的法案草案。",
      "propose doing 表‘建议做某事’；make A illegal 是‘使 A 成为违法行为’的宾语补足语结构。",
      "that can be given to a case 是定语从句，修饰 publicity；before 引导时间状语从句，限定公开报道发生在开庭前。",
    ],
    beginnerSyntax: {
      components: [
        { text: "In a significant tightening of legal controls over the press", form: "in + 名词短语", function: "背景状语", modifies: "修饰 will introduce，说明提出法案属于怎样的监管变化", explanation: "先把整组理解为‘在大幅收紧新闻监管的举措中’，不要逐词拆散。" },
        { text: "Lord Irvine", form: "专有名词", function: "主语", modifies: "是 will introduce 的动作发出者", explanation: "Lord Irvine 是本句真正的主语。" },
        { text: "the Lord Chancellor", form: "名词短语", function: "同位语", modifies: "补充说明 Lord Irvine 的身份", explanation: "两个逗号夹住的部分可以暂时拿掉；它只告诉你此人是大法官。" },
        { text: "will introduce", form: "will + 动词原形", function: "主句谓语", modifies: "说明主语将采取的行动", explanation: "核心动作是‘将提出’。" },
        { text: "a draft bill", form: "名词短语", function: "主句宾语", modifies: "承受 introduce 的动作", explanation: "提出什么？一份法案草案。" },
        { text: "that will propose making payments to witnesses illegal", form: "that 引导的定语从句", function: "后置定语", modifies: "修饰 a draft bill", explanation: "这部分说明法案的第一项内容：建议把向证人付款定为非法。" },
        { text: "and will strictly control the amount of publicity", form: "and + 并列谓语", function: "定语从句内第二个谓语", modifies: "与 will propose 并列，共同说明 bill 的内容", explanation: "and 后省略了重复的关系主语 that；仍然是‘该法案将……’。" },
        { text: "that can be given to a case", form: "that 引导的被动定语从句", function: "后置定语", modifies: "修饰 publicity", explanation: "说明哪种 publicity：能够给予某案件的公开报道。" },
        { text: "before a trial begins", form: "before 引导的完整从句", function: "时间状语从句", modifies: "限定 can be given 的时间", explanation: "报道限制发生在审判开始之前。" },
      ],
      clauses: [
        { text: "that will propose making payments to witnesses illegal and will strictly control the amount of publicity that can be given to a case before a trial begins", type: "限制性定语从句", marker: "that（指代 a draft bill）", role: "修饰 a draft bill，完整说明法案的两项内容", subject: "that（= a draft bill）", predicate: "will propose；and will strictly control", objectOrComplement: "making payments to witnesses illegal；the amount of publicity...", translationOrder: "先译主句‘将提出法案’，再按‘该法案将……并将……’补出两项内容。" },
        { text: "that can be given to a case", type: "限制性定语从句", marker: "that（指代 publicity）", role: "修饰 publicity，限定可给予案件的公开报道", subject: "that（= publicity）", predicate: "can be given", objectOrComplement: "to a case（对象状语）", translationOrder: "先译 publicity 为‘公开报道’，再补‘能够给予某案件的’。" },
        { text: "before a trial begins", type: "时间状语从句", marker: "before", role: "说明报道限制所针对的时间界线", subject: "a trial", predicate: "begins", translationOrder: "中文先译‘在审判开始之前’，再接‘可给予案件的报道’。" },
      ],
    },
    literal: "在明显收紧对新闻界法律管制之际，大法官 Lord Irvine 将提出一份法案草案；该草案将建议把向证人付款定为非法，并严格控制审判开始前能够给予案件的公开报道量。",
    natural: "作为收紧新闻监管的重要举措，大法官 Lord Irvine 将提交法案草案，拟禁止向证人付费，并严格限制开庭前的案件曝光。",
    logic: "把首句的禁令具体化为两项立法内容：禁止付费与限制庭前报道。",
    phrases: ["tightening of legal controls", "controls over the press", "introduce a draft bill", "propose making payments to witnesses illegal", "control the amount of publicity", "before a trial begins"],
    answerWords: ["tightening", "draft", "illegal", "publicity", "before"],
  },
  {
    id: "2001-cloze-s3",
    number: 3,
    text: "In a letter to Gerald Kaufman, chairman of the House of Commons media select committee, Lord Irvine said he agreed with a committee report this year which said that self regulation did not offer sufficient control.",
    testText: "In a letter to Gerald Kaufman, chairman of the House of Commons media select committee, Lord Irvine said he ___(7) with a committee report this year which said that self regulation did not ___(8) sufficient control.",
    chunks: [
      { text: "In a letter to Gerald Kaufman, ", role: "modifier" },
      { text: "chairman of the House of Commons media select committee, ", role: "modifier" },
      { text: "Lord Irvine", role: "subject" },
      { text: " said", role: "predicate" },
      { text: " he agreed with a committee report this year", role: "object" },
      { text: " which said", role: "modifier" },
      { text: " that self regulation did not offer sufficient control.", role: "object" },
    ],
    trunk: "Lord Irvine said he agreed with a committee report.",
    layers: [
      { label: "信息出处", text: "In a letter to Gerald Kaufman：在写给 Gerald Kaufman 的信中" },
      { label: "人物身份", text: "chairman of... committee：Gerald Kaufman 是下议院媒体特别委员会主席" },
      { label: "主句与宾语", text: "Lord Irvine said he agreed with a committee report：Lord Irvine 表示自己赞同委员会报告" },
      { label: "报告结论", text: "which said that self regulation did not offer sufficient control：报告认为行业自律没有提供充分监管" },
    ],
    grammar: [
      "said 后省略 that，引出宾语从句 he agreed...；agree with + 人、意见或报告表示‘赞同’。",
      "chairman of... 是 Gerald Kaufman 的同位语，补充身份，不是句子谓语。",
      "which 引导定语从句修饰 report；从句中的 said 又接 that 宾语从句。",
      "offer sufficient control 表‘提供充分监管’，present 更偏‘正式呈交’，不能替代 offer。",
    ],
    beginnerSyntax: {
      components: [
        { text: "In a letter to Gerald Kaufman", form: "in + 名词短语", function: "信息来源状语", modifies: "修饰 said，说明这番话写在哪里", explanation: "先读成‘在一封写给 Gerald Kaufman 的信中’。" },
        { text: "chairman of the House of Commons media select committee", form: "名词短语", function: "同位语", modifies: "补充 Gerald Kaufman 的职务", explanation: "逗号间这一长串只是在介绍 Gerald Kaufman，可先括起来。" },
        { text: "Lord Irvine", form: "专有名词", function: "主句主语", modifies: "是 said 的动作发出者", explanation: "回到逗号后找主干：Lord Irvine 说。" },
        { text: "said", form: "及物动词过去式", function: "主句谓语", modifies: "引出后面的陈述内容", explanation: "said 后面省略了连接词 that。" },
        { text: "he agreed with a committee report this year", form: "省略 that 的完整从句", function: "宾语从句", modifies: "作 said 的宾语，说明他说了什么", explanation: "整句内容是‘他赞同本年度的一份委员会报告’。" },
        { text: "which said", form: "which 引导的定语从句开头", function: "后置定语", modifies: "修饰 a committee report", explanation: "which 指回 report，表示‘这份报告说……’。" },
        { text: "that self regulation did not offer sufficient control", form: "that 引导的完整从句", function: "宾语从句", modifies: "作 which said 中 said 的宾语", explanation: "这是报告的具体结论：自律监管力度不够。" },
      ],
      clauses: [
        { text: "he agreed with a committee report this year which said that self regulation did not offer sufficient control", type: "宾语从句", marker: "省略 that", role: "作 Lord Irvine said 的宾语", subject: "he", predicate: "agreed", objectOrComplement: "with a committee report this year...（介词宾语）", translationOrder: "先译‘Lord Irvine 说’，再回答‘说了什么’。" },
        { text: "which said that self regulation did not offer sufficient control", type: "限制性定语从句", marker: "which（指代 a committee report）", role: "修饰 committee report", subject: "which（= the report）", predicate: "said", objectOrComplement: "that self regulation did not offer sufficient control（宾语从句）", translationOrder: "先译‘一份委员会报告’，再补‘该报告认为……’。" },
        { text: "that self regulation did not offer sufficient control", type: "宾语从句", marker: "that", role: "作 which said 中 said 的宾语", subject: "self regulation", predicate: "did not offer", objectOrComplement: "sufficient control", translationOrder: "按‘行业自律—没有提供—充分监管’顺序理解。" },
      ],
    },
    literal: "在写给下议院媒体特别委员会主席 Gerald Kaufman 的信中，Lord Irvine 说他赞同本年度的一份委员会报告，该报告称行业自律并未提供充分监管。",
    natural: "Lord Irvine 在致下议院媒体特别委员会主席 Gerald Kaufman 的信中表示，他同意委员会今年的结论：仅靠新闻界自律不足以形成有效监管。",
    logic: "引用委员会报告，为政府加强外部法律监管提供依据。",
    phrases: ["in a letter to Gerald Kaufman", "agreed with a committee report", "self regulation", "offer sufficient control"],
    answerWords: ["agreed", "offer"],
  },
  {
    id: "2001-cloze-s4",
    number: 4,
    text: "Publication of the letter came two days after Lord Irvine caused a storm of media protest when he said the interpretation of privacy controls contained in European legislation would be left to judges rather than to Parliament.",
    testText: "___(9) of the letter came two days after Lord Irvine caused a ___(10) of media protest when he said the ___(11) of privacy controls contained in European legislation would be left to judges ___(12) to Parliament.",
    chunks: [
      { text: "Publication of the letter", role: "subject" },
      { text: " came", role: "predicate" },
      { text: " two days after Lord Irvine caused a storm of media protest", role: "modifier" },
      { text: " when he said", role: "modifier" },
      { text: " the interpretation of privacy controls contained in European legislation", role: "subject" },
      { text: " would be left", role: "predicate" },
      { text: " to judges rather than to Parliament.", role: "object" },
    ],
    trunk: "Publication of the letter came two days after Lord Irvine caused a storm of media protest.",
    layers: [
      { label: "时间主线", text: "Publication of the letter came two days after...：这封信公开于媒体抗议风波发生两天后" },
      { label: "风波原因", text: "when he said...：风波发生在他说出下述安排时" },
      { label: "被解释对象", text: "the interpretation of privacy controls contained in European legislation：对欧洲法律中隐私管制条款的解释" },
      { label: "责任归属", text: "would be left to judges rather than to Parliament：将交由法官而不是议会决定" },
    ],
    grammar: [
      "Publication of the letter 是名词化主语，表示信件内容被公开发表；publication 比 release 更准确地突出公之于众。",
      "cause a storm of protest 是固定比喻，表示引发一场强烈抗议。",
      "when 引导时间状语从句；said 后省略 that，引出内容宾语从句。",
      "leave A to B 表‘把 A 交给 B 处理’；rather than 两侧平行使用 to judges / to Parliament。",
    ],
    beginnerSyntax: {
      components: [
        { text: "Publication of the letter", form: "名词 + of 介词短语", function: "主语", modifies: "是 came 的主体", explanation: "谁‘发生在两天后’？不是 letter 本身，而是信件的公开发表。" },
        { text: "came", form: "不及物动词过去式", function: "主句谓语", modifies: "说明发表这一事件发生", explanation: "come 在这里不是‘来到某处’，而是‘发生、出现’。" },
        { text: "two days after Lord Irvine caused a storm of media protest", form: "时间长度 + after 从句", function: "时间状语", modifies: "修饰 came", explanation: "先定位时间：在 Lord Irvine 引发抗议风波后的两天。" },
        { text: "when he said", form: "when 引导的从句开头", function: "时间状语从句", modifies: "修饰 caused，说明风波在他说什么时出现", explanation: "when 把‘引发抗议’与他的公开表态连接起来。" },
        { text: "the interpretation of privacy controls contained in European legislation", form: "名词短语 + 过去分词后置定语", function: "宾语从句主语", modifies: "是 would be left 的承受者", explanation: "中心词是 interpretation；contained... 修饰 controls，说明这些规定写在欧洲法律中。" },
        { text: "would be left", form: "would + be + 过去分词", function: "宾语从句谓语", modifies: "说明解释权将被交付", explanation: "这是被动语态：解释工作‘将被留给’某一方。" },
        { text: "to judges rather than to Parliament", form: "to A rather than to B", function: "对象与取舍成分", modifies: "补充 would be left 的接收方", explanation: "A 是实际选择：法官；B 是被排除选择：议会。" },
      ],
      clauses: [
        { text: "after Lord Irvine caused a storm of media protest when he said the interpretation of privacy controls contained in European legislation would be left to judges rather than to Parliament", type: "时间状语从句", marker: "after", role: "修饰 came，给出信件发表前发生的事件", subject: "Lord Irvine", predicate: "caused", objectOrComplement: "a storm of media protest；when...（内嵌时间从句）", translationOrder: "先译‘两天后’，再交代参照事件‘Lord Irvine 引发抗议风波’。" },
        { text: "when he said the interpretation of privacy controls contained in European legislation would be left to judges rather than to Parliament", type: "时间状语从句", marker: "when", role: "修饰 caused，说明抗议因何时的表态而起", subject: "he", predicate: "said", objectOrComplement: "the interpretation... would be left...（省略 that 的宾语从句）", translationOrder: "先译‘当他说……时’，再进入表态内容。" },
        { text: "the interpretation of privacy controls contained in European legislation would be left to judges rather than to Parliament", type: "宾语从句", marker: "省略 that", role: "作 said 的宾语", subject: "the interpretation of privacy controls contained in European legislation", predicate: "would be left", objectOrComplement: "to judges rather than to Parliament", translationOrder: "先抓长主语中心 interpretation，再译被动谓语，最后处理 judges / Parliament 的取舍。" },
      ],
    },
    literal: "这封信的发表是在 Lord Irvine 引发媒体抗议风暴两天之后；当时他说，对欧洲立法中所含隐私管制的解释将留给法官，而不是议会。",
    natural: "两天前，Lord Irvine 表示欧洲隐私法规应由法官而非议会解释，引起媒体强烈抗议；随后这封信才被公开。",
    logic: "补充政策争议背景，说明司法解释权与议会立法权之间的冲突。",
    phrases: ["publication of the letter", "a storm of media protest", "privacy controls contained in European legislation", "be left to judges", "rather than to Parliament"],
    answerWords: ["Publication", "storm", "interpretation", "rather than"],
  },
  {
    id: "2001-cloze-s5",
    number: 5,
    text: "The Lord Chancellor said introduction of the Human Rights Bill, which makes the European Convention on Human Rights legally binding in Britain, laid down that everybody was entitled to privacy and that public figures could go to court to protect themselves and their families.",
    testText: "The Lord Chancellor said introduction of the Human Rights Bill, which ___(13) the European Convention on Human Rights legally ___(14) in Britain, laid down that everybody was ___(15) to privacy and that public figures could go to court to protect themselves and their families.",
    chunks: [
      { text: "The Lord Chancellor", role: "subject" },
      { text: " said", role: "predicate" },
      { text: " introduction of the Human Rights Bill", role: "subject" },
      { text: ", which makes the European Convention on Human Rights legally binding in Britain,", role: "modifier" },
      { text: " laid down", role: "predicate" },
      { text: " that everybody was entitled to privacy", role: "object" },
      { text: " and that public figures could go to court", role: "object" },
      { text: " to protect themselves and their families.", role: "modifier" },
    ],
    trunk: "The Lord Chancellor said introduction of the Human Rights Bill laid down that everybody was entitled to privacy and that public figures could go to court.",
    layers: [
      { label: "报道主句", text: "The Lord Chancellor said...：大法官表示……" },
      { label: "表态内容主干", text: "introduction of the Human Rights Bill laid down...：《人权法案》的引入明确规定……" },
      { label: "插入定语", text: "which makes the European Convention... binding in Britain：该法案使《欧洲人权公约》在英国具有法律约束力" },
      { label: "并列规定", text: "everybody was entitled to privacy；public figures could go to court...：人人享有隐私权，公众人物可以诉诸法院保护自己和家人" },
    ],
    grammar: [
      "said 后省略 that，整个 introduction... laid down... 是宾语从句。",
      "which 引导非限制性定语从句，修饰 Human Rights Bill；make A + adjective 构成宾语补足语，binding 是形容词。",
      "lay down that... 表‘正式规定……’；后面两个 that 从句由 and 并列。",
      "be entitled to + 名词表示‘有权享有……’；to protect... 是目的状语，说明去法院的目的。",
    ],
    beginnerSyntax: {
      components: [
        { text: "The Lord Chancellor", form: "名词短语", function: "主句主语", modifies: "是 said 的动作发出者", explanation: "先抓最外层：大法官说。" },
        { text: "said", form: "及物动词过去式", function: "主句谓语", modifies: "引出整段表态内容", explanation: "said 后省略 that；后面直到句末都属于他说的内容。" },
        { text: "introduction of the Human Rights Bill", form: "名词化短语", function: "宾语从句主语", modifies: "是 laid down 的施事主体", explanation: "中心词是 introduction，即‘法案的引入/实施’作主语。" },
        { text: "which makes the European Convention on Human Rights legally binding in Britain", form: "which 引导的非限制性定语从句", function: "插入说明", modifies: "修饰 the Human Rights Bill", explanation: "两个逗号之间先括起来：它说明这项法案在英国带来的法律效果。" },
        { text: "laid down", form: "短语动词过去式", function: "宾语从句谓语", modifies: "说明法案正式规定了什么", explanation: "laid down 不是‘放下’，法律语境中是‘明文规定’。" },
        { text: "that everybody was entitled to privacy", form: "that 引导的完整从句", function: "第一个宾语从句", modifies: "作 laid down 的第一项规定内容", explanation: "第一项：每个人都有权享有隐私。" },
        { text: "and that public figures could go to court", form: "and + that 从句", function: "并列宾语从句", modifies: "与前一个 that 从句并列，共同作 laid down 的宾语", explanation: "第二项：公众人物可以诉诸法院。" },
        { text: "to protect themselves and their families", form: "to do 不定式短语", function: "目的状语", modifies: "修饰 could go to court", explanation: "为什么去法院？为了保护自己和家人。" },
      ],
      clauses: [
        { text: "introduction of the Human Rights Bill, which makes the European Convention on Human Rights legally binding in Britain, laid down that everybody was entitled to privacy and that public figures could go to court to protect themselves and their families", type: "宾语从句", marker: "省略 that", role: "作 said 的宾语，承载大法官的完整表态", subject: "introduction of the Human Rights Bill", predicate: "laid down", objectOrComplement: "that everybody... and that public figures...（两个并列宾语从句）", translationOrder: "先译‘大法官说’，再进入‘法案的引入规定了两件事’。" },
        { text: "which makes the European Convention on Human Rights legally binding in Britain", type: "非限制性定语从句", marker: "which（指代 the Human Rights Bill）", role: "插入说明法案的法律效果", subject: "which（= the Human Rights Bill）", predicate: "makes", objectOrComplement: "the European Convention on Human Rights（宾语）+ legally binding（宾补）+ in Britain（地点范围）", translationOrder: "先确定 which 指法案，再按‘使公约在英国具有法律约束力’理解。" },
        { text: "that everybody was entitled to privacy", type: "宾语从句", marker: "that", role: "作 laid down 的第一项并列宾语", subject: "everybody", predicate: "was entitled", objectOrComplement: "to privacy（权利内容）", translationOrder: "按‘每个人—有权—享有隐私’理解。" },
        { text: "that public figures could go to court to protect themselves and their families", type: "宾语从句", marker: "that", role: "作 laid down 的第二项并列宾语", subject: "public figures", predicate: "could go", objectOrComplement: "to court（去向）；to protect...（目的状语）", translationOrder: "先译‘公众人物可以诉诸法院’，再补去法院的目的。" },
      ],
    },
    literal: "大法官说，《人权法案》的引入——该法案使《欧洲人权公约》在英国具有法律约束力——规定人人有权享有隐私，而且公众人物可以去法院保护自己和家人。",
    natural: "大法官表示，《人权法案》使《欧洲人权公约》在英国生效，并明确人人享有隐私权，公众人物也可诉诸法院保护本人及家属。",
    logic: "说明隐私保护的法律基础，以及公众人物可以采取的司法救济。",
    phrases: ["introduction of the Human Rights Bill", "makes the European Convention on Human Rights legally binding", "laid down that", "was entitled to privacy", "go to court", "protect themselves and their families"],
    answerWords: ["makes", "binding", "entitled"],
  },
  {
    id: "2001-cloze-s6",
    number: 6,
    text: "“Press freedoms will be in safe hands with our British judges,” he said.",
    testText: "“Press freedoms will be in safe hands ___(16) our British judges,” he said.",
    chunks: [
      { text: "“Press freedoms", role: "subject" },
      { text: " will be", role: "predicate" },
      { text: " in safe hands", role: "object" },
      { text: " with our British judges,”", role: "modifier" },
      { text: " he", role: "subject" },
      { text: " said.", role: "predicate" },
    ],
    trunk: "Press freedoms will be in safe hands with our British judges.",
    layers: [
      { label: "引语内容", text: "Press freedoms will be in safe hands：新闻自由将得到妥善保护" },
      { label: "责任承担者", text: "with our British judges：由英国法官掌管和保护" },
      { label: "报道语", text: "he said：他说" },
    ],
    grammar: [
      "be in safe hands 是习语，表示由可靠的人负责、处于安全可靠的掌管之下。",
      "with + 人说明控制或负责者，因此用 with our British judges；by 更常引出具体被动动作的施事。",
      "Press freedoms 用复数强调新闻界所享有的多项自由权利。",
    ],
    beginnerSyntax: {
      components: [
        { text: "Press freedoms", form: "复数名词短语", function: "引语内主语", modifies: "是 will be 描述的对象", explanation: "引号内先找主语：新闻自由。" },
        { text: "will be", form: "will + be", function: "引语内系动词", modifies: "连接主语与后面的状态", explanation: "表示未来将处于某种状态。" },
        { text: "in safe hands", form: "in + 名词短语的习语", function: "表语", modifies: "说明 Press freedoms 将处于可靠掌管之下", explanation: "不要直译成‘在安全的手里’，整体是‘得到妥善负责’。" },
        { text: "with our British judges", form: "with + 名词短语", function: "责任归属状语", modifies: "补充 in safe hands，说明由谁掌管", explanation: "新闻自由交在谁手里？英国法官。" },
        { text: "he", form: "人称代词", function: "报道语主语", modifies: "是 said 的动作发出者", explanation: "引号外的 he 指 Lord Irvine。" },
        { text: "said", form: "动词过去式", function: "报道语谓语", modifies: "说明引号内容是他说的话", explanation: "英语可把 he said 放在引语之后。" },
      ],
      clauses: [
        { text: "Press freedoms will be in safe hands with our British judges", type: "直接引语内容分句", marker: "引号（无从属连词）", role: "充当 said 的直接引语内容", subject: "Press freedoms", predicate: "will be", objectOrComplement: "in safe hands（表语）；with our British judges（责任归属状语）", translationOrder: "先完整译引号内内容，再补‘他说’。" },
      ],
    },
    literal: "‘新闻自由将由我们的英国法官妥善掌管，’他说。",
    natural: "他说：‘英国法官会稳妥保障新闻自由。’",
    logic: "用 Lord Irvine 的直接引语回应媒体对司法掌握解释权的担忧。",
    phrases: ["press freedoms", "be in safe hands", "with our British judges"],
    answerWords: ["with"],
  },
  {
    id: "2001-cloze-s7",
    number: 7,
    text: "Witness payments became an issue after West was sentenced to 10 life sentences in 1995.",
    testText: "Witness payments became an ___(17) after West was sentenced to 10 life sentences in 1995.",
    chunks: [
      { text: "Witness payments", role: "subject" },
      { text: " became", role: "predicate" },
      { text: " an issue", role: "object" },
      { text: " after West was sentenced to 10 life sentences", role: "modifier" },
      { text: " in 1995.", role: "modifier" },
    ],
    trunk: "Witness payments became an issue.",
    layers: [
      { label: "主句", text: "Witness payments became an issue：向证人付费成了一个公共争议问题" },
      { label: "时间事件", text: "after West was sentenced to 10 life sentences：在 West 被判十个无期徒刑之后" },
      { label: "年份", text: "in 1995：判决发生在 1995 年" },
    ],
    grammar: [
      "become + 名词表语表示‘变成/成为……’；issue 在此是需要讨论解决的争议问题。",
      "after 引导时间状语从句，交代 witness payments 受到关注的时间背景。",
      "be sentenced to + 刑罚表示‘被判处……’；life sentence 指无期徒刑。",
    ],
    beginnerSyntax: {
      components: [
        { text: "Witness payments", form: "名词 + 名词", function: "主语", modifies: "是 became 描述的现象", explanation: "payments 是中心词，Witness 说明这种付款给谁。" },
        { text: "became", form: "系动词过去式", function: "谓语", modifies: "连接主语与 an issue", explanation: "became 表示状态变化：此前存在，后来变成争议。" },
        { text: "an issue", form: "名词短语", function: "表语", modifies: "说明 Witness payments 后来成为什么", explanation: "issue 这里是‘争议问题’，不是杂志期号。" },
        { text: "after West was sentenced to 10 life sentences", form: "after 引导的完整从句", function: "时间状语从句", modifies: "修饰 became", explanation: "何时成为争议？在 West 被判刑之后。" },
        { text: "in 1995", form: "in + 年份", function: "时间状语", modifies: "修饰 was sentenced", explanation: "进一步说明判决发生的年份。" },
      ],
      clauses: [
        { text: "after West was sentenced to 10 life sentences in 1995", type: "时间状语从句", marker: "after", role: "修饰 became，说明争议形成的时间背景", subject: "West", predicate: "was sentenced", objectOrComplement: "to 10 life sentences（所判刑罚）；in 1995（时间）", translationOrder: "中文先译‘1995 年 West 被判十个无期徒刑之后’，再回主句。" },
      ],
    },
    literal: "在 West 于 1995 年被判处十个无期徒刑之后，向证人付款成为一个问题。",
    natural: "1995 年 West 被判十项无期徒刑后，媒体向证人付费的做法开始引发争议。",
    logic: "回溯争议的直接历史起点，为后文证人收款情况作铺垫。",
    phrases: ["witness payments", "became an issue", "was sentenced to 10 life sentences"],
    answerWords: ["issue"],
  },
  {
    id: "2001-cloze-s8",
    number: 8,
    text: "Up to 19 witnesses were said to have received payments for telling their stories to newspapers.",
    testText: "Up to 19 witnesses were ___(18) to have received payments for telling their stories to newspapers.",
    chunks: [
      { text: "Up to 19 witnesses", role: "subject" },
      { text: " were said", role: "predicate" },
      { text: " to have received payments", role: "object" },
      { text: " for telling their stories", role: "modifier" },
      { text: " to newspapers.", role: "modifier" },
    ],
    trunk: "Up to 19 witnesses were said to have received payments.",
    layers: [
      { label: "数量范围", text: "Up to 19 witnesses：多达 19 名证人" },
      { label: "消息来源结构", text: "were said to have received：据说已经收到了" },
      { label: "付款原因", text: "for telling their stories to newspapers：因为把自己的故事讲给报纸" },
    ],
    grammar: [
      "sb be said to do 是报道结构，表示‘据说某人……’；不能用 told，因为 tell 通常需要明确的受话人。",
      "to have received 是完成不定式，表示收款发生在‘据说’之前。",
      "payment for doing 表‘因做某事而得到的报酬’；tell a story to sb 中 to 引出听者。",
      "up to + 数字在此表示‘多达’，强调可能达到的上限。",
    ],
    beginnerSyntax: {
      components: [
        { text: "Up to 19 witnesses", form: "up to + 数字 + 复数名词", function: "主语", modifies: "是 were said 描述的对象", explanation: "整组是‘多达 19 名证人’，up to 不表示空间方向。" },
        { text: "were said", form: "be + 过去分词", function: "被动谓语", modifies: "表示外界如此报道这些证人", explanation: "没有指出是谁说的，因此用被动‘据说’。" },
        { text: "to have received payments", form: "完成不定式", function: "主语补足语", modifies: "补充说明 witnesses 被认为做过什么", explanation: "have received 表示收钱早于报道行为。" },
        { text: "for telling their stories", form: "for + 动名词短语", function: "原因状语", modifies: "说明 received payments 的原因", explanation: "他们为什么收钱？因为讲述自己的故事。" },
        { text: "to newspapers", form: "to + 名词", function: "对象状语", modifies: "修饰 telling，说明故事讲给谁", explanation: "故事的接收者是报纸媒体。" },
      ],
      clauses: [],
    },
    literal: "据说多达 19 名证人因为向报纸讲述自己的故事而收到了报酬。",
    natural: "据称，最多有 19 名证人把案情故事卖给报纸并因此获酬。",
    logic: "用具体人数说明证人收款并非孤例，从而强化立法必要性。",
    phrases: ["up to 19 witnesses", "were said to have received payments", "payments for telling their stories", "telling their stories to newspapers"],
    answerWords: ["said"],
  },
  {
    id: "2001-cloze-s9",
    number: 9,
    text: "Concerns were raised that witnesses might be encouraged exaggerate their stories in court to ensure guilty verdicts.",
    testText: "Concerns were raised ___(19) witnesses might be encouraged exaggerate their stories in court to ___(20) guilty verdicts.",
    chunks: [
      { text: "Concerns", role: "subject" },
      { text: " were raised", role: "predicate" },
      { text: " that witnesses", role: "subject" },
      { text: " might be encouraged", role: "predicate" },
      { text: " exaggerate their stories", role: "object" },
      { text: " in court", role: "modifier" },
      { text: " to ensure guilty verdicts.", role: "modifier" },
    ],
    trunk: "Concerns were raised that witnesses might be encouraged exaggerate their stories.",
    layers: [
      { label: "主句", text: "Concerns were raised：人们提出了担忧" },
      { label: "担忧内容", text: "that witnesses might be encouraged...：证人可能受到诱导" },
      { label: "被诱导行为", text: "exaggerate their stories in court：在法庭上夸大自己的说法" },
      { label: "行为目的", text: "to ensure guilty verdicts：以确保作出有罪裁决" },
    ],
    grammar: [
      "raise concerns / concerns are raised 表‘提出担忧’；that 引导同位语从句，具体解释 concerns 的内容。",
      "用户 PDF 原文在 encouraged 与 exaggerate 之间未印 to；规范英语应为 be encouraged to do。学习时按规范结构理解，但自测与原文展示保留试卷字样。",
      "in court 是地点/场合状语，修饰 exaggerate；to ensure... 是目的状语。",
      "ensure + 结果表示‘确保某结果发生’；assure 通常接人，guarantee 语气更绝对且搭配重点不同。",
    ],
    beginnerSyntax: {
      components: [
        { text: "Concerns", form: "复数名词", function: "主语", modifies: "是 were raised 的承受者", explanation: "先看主句：担忧被提了出来。" },
        { text: "were raised", form: "be + 过去分词", function: "主句被动谓语", modifies: "说明 concerns 被社会提出", explanation: "raise 在这里是‘提出’，不是‘提高高度’。" },
        { text: "that witnesses", form: "that + 名词短语", function: "同位语从句开头与从句主语", modifies: "that 从句解释 concerns 的具体内容", explanation: "that 不译成‘那个’，它把后面的完整担忧内容接到 concerns 后。" },
        { text: "might be encouraged", form: "might + be + 过去分词", function: "同位语从句谓语", modifies: "说明 witnesses 可能受到诱导", explanation: "might 表可能，be encouraged 是被动‘被鼓励/诱导’。" },
        { text: "exaggerate their stories", form: "动词原形 + 宾语", function: "被鼓励实施的动作", modifies: "补充 encouraged 的行为内容", explanation: "原卷这里漏印规范结构所需的 to；应按 be encouraged to exaggerate 理解。" },
        { text: "in court", form: "in + 名词", function: "地点与场合状语", modifies: "修饰 exaggerate", explanation: "说明夸大陈述发生在法庭这一场合。" },
        { text: "to ensure guilty verdicts", form: "to do 不定式短语", function: "目的状语", modifies: "修饰 exaggerate their stories", explanation: "为什么夸大？目的是促成有罪裁决。" },
      ],
      clauses: [
        { text: "that witnesses might be encouraged exaggerate their stories in court to ensure guilty verdicts", type: "同位语从句", marker: "that", role: "解释 concerns 的具体内容", subject: "witnesses", predicate: "might be encouraged", objectOrComplement: "exaggerate their stories（原卷漏印 to 的动作补足）；in court（场合）；to ensure...（目的）", translationOrder: "先译主句‘人们提出担忧’，再用冒号式中文展开担忧内容。" },
      ],
    },
    literal: "人们提出担忧：证人可能受到鼓励，在法庭上夸大自己的说法，以确保作出有罪裁决。",
    natural: "有人担心，媒体付费会诱使证人在庭审中夸大案情，从而促成有罪判决。",
    logic: "以对司法公正的直接风险收束全文，解释禁止证人收款的根本理由。",
    phrases: ["concerns were raised", "might be encouraged exaggerate", "exaggerate their stories in court", "ensure guilty verdicts"],
    answerWords: ["that", "ensure"],
  },
];

const q = (
  number: number,
  sentenceId: string,
  prompt: string,
  options: [string, string, string, string],
  answer: "A" | "B" | "C" | "D",
  locating: string,
  explanations: Record<"A" | "B" | "C" | "D", string>,
): Question => ({
  id: 200100 + number,
  number,
  sentenceId,
  prompt,
  options: (["A", "B", "C", "D"] as const).map((key, index) => ({ key, text: options[index] })),
  answer,
  locating,
  explanations,
});

export const cloze2001Questions: Question[] = [
  q(1, "2001-cloze-s1", "prominent cases ___ the trial of Rosemary West", ["as to", "for instance", "in particular", "such as"], "D", "cases 后要直接接一个具体例子；such as + 名词正好把 Rosemary West 的审判列为 prominent cases 的实例。", {
    A: "as to 表‘关于；至于’，会把 trial 变成讨论对象，不能表示举例。",
    B: "for instance 可作插入语‘例如’，通常需用逗号隔开，不能像介词一样直接连接 cases 与名词例子。",
    C: "in particular 表‘尤其；特别是’，强调已有对象中的某一项，但这里的基本关系是类别与实例。",
    D: "such as 后直接接名词或名词短语列举实例，结构和语义都完整。",
  }),
  q(2, "2001-cloze-s2", "a significant ___ of legal controls over the press", ["tightening", "intensifying", "focusing", "fastening"], "A", "冠词 a 后需要名词中心语；tightening of controls 是‘管制收紧’的固定名词化表达。", {
    A: "tightening 可作名词，a tightening of controls 表‘管制的收紧’。",
    B: "intensifying 通常是现在分词/动名词，常说 intensifying controls 或 an intensification of controls，不说 a significant intensifying of。",
    C: "focusing 表‘聚焦’，通常接 on，不能表达监管力度变严。",
    D: "fastening 表扣紧物件，如 fastening a belt，不与 legal controls 搭配。",
  }),
  q(3, "2001-cloze-s2", "will introduce a ___ bill", ["sketch", "rough", "preliminary", "draft"], "D", "法律语境中 draft bill 是固定组合，指尚未通过的法案草案。", {
    A: "sketch 作名词是素描或概略，不能直接作前置定语构成正式法律术语。",
    B: "rough bill 会让人理解为粗糙的账单或法案，不是法案草案的规范名称。",
    C: "preliminary 表初步的，但 preliminary bill 不是此处最固定的法律搭配。",
    D: "draft bill 即‘法案草案’，与 introduce 搭配自然。",
  }),
  q(4, "2001-cloze-s2", "propose making payments to witnesses ___", ["illogical", "illegal", "improbable", "improper"], "B", "法案要改变的是付款行为的法律性质；make A illegal 表‘把 A 定为违法’。", {
    A: "illogical 是‘不合逻辑的’，属于推理评价，不是立法禁止。",
    B: "illegal 明确表示违反法律，符合 bill 的立法作用。",
    C: "improbable 是‘不大可能的’，不能说明行为是否被法律禁止。",
    D: "improper 是‘不适当的’，道德或礼仪色彩较强，力度低于法律上的 illegal。",
  }),
  q(5, "2001-cloze-s2", "control the amount of ___ that can be given to a case", ["publicity", "penalty", "popularity", "peculiarity"], "A", "新闻监管控制的是案件在审判前得到的公开报道量；publicity 可与 amount of 及 give to a case 搭配。", {
    A: "publicity 表媒体曝光或公开报道，amount of publicity 正合新闻语境。",
    B: "penalty 是处罚；案件可以产生处罚，但不能说给案件一定数量的处罚来表示庭前报道。",
    C: "popularity 是受欢迎程度，不是媒体公开程度。",
    D: "peculiarity 是独特之处，既不合语义也不合 amount of... given to a case 的搭配。",
  }),
  q(6, "2001-cloze-s2", "publicity that can be given to a case ___ a trial begins", ["since", "if", "before", "as"], "C", "限制报道是为了防止影响尚未开始的审判，因此时间界线是 before a trial begins。", {
    A: "since 可表‘自从’或‘因为’，都不能准确限定庭前阶段。",
    B: "if 表条件，会变成‘如果审判开始’，不合时间先后。",
    C: "before 明确表示审判开始前，符合庭前报道限制。",
    D: "as 可表当……时或因为，不能强调报道必须早于开庭。",
  }),
  q(7, "2001-cloze-s3", "Lord Irvine said he ___ with a committee report", ["sided", "shared", "complied", "agreed"], "D", "agree with + report/opinion 表‘赞同报告或意见’，宾语与介词搭配同时锁定答案。", {
    A: "side with 后接人或一方，表示站在某人一边；不自然地接 report。",
    B: "share 通常直接接 opinion/view，不能说 share with a report 表赞同。",
    C: "comply with 表遵守规则或要求，报告在此是观点来源，不是必须执行的命令。",
    D: "agree with a report 表赞同报告中的观点，搭配准确。",
  }),
  q(8, "2001-cloze-s3", "self regulation did not ___ sufficient control", ["present", "offer", "manifest", "indicate"], "B", "行业自律没有‘提供’足够控制力；offer + control 表提供某种监管作用。", {
    A: "present 常指呈交、展示，不能表达自律机制产生监管作用。",
    B: "offer 表提供，offer sufficient control 语义完整。",
    C: "manifest 表显示或显现，宾语通常是特征/情绪，不是提供 control。",
    D: "indicate 表表明，若用它会变成‘没有表明充分控制’，偏离政策效果。",
  }),
  q(9, "2001-cloze-s4", "___ of the letter came two days after...", ["Release", "Publication", "Printing", "Exposure"], "B", "此处谈信件内容被公开发表；publication of the letter 与新闻报道语境最贴合。", {
    A: "release 可指发布，但更强调解除限制后放出消息、影片或产品；这里侧重信件被正式公开。",
    B: "publication 表发表、公之于众，能自然作事件名词主语。",
    C: "printing 只是印刷动作，不能说明内容已向公众披露。",
    D: "exposure 常指暴露问题或获得曝光，exposure of the letter 不自然。",
  }),
  q(10, "2001-cloze-s4", "caused a ___ of media protest", ["storm", "rage", "flare", "flash"], "A", "a storm of protest 是固定比喻，表示一阵猛烈抗议。", {
    A: "storm 可比喻突然而强烈的大量反应，a storm of protest 搭配固定。",
    B: "rage 表愤怒或暴怒，通常不可说 a rage of protest。",
    C: "flare 是火光或信号弹；flare-up 才可表示突然爆发。",
    D: "flash 表闪光或瞬间，a flash of protest 不能表达大规模媒体抗议。",
  }),
  q(11, "2001-cloze-s4", "the ___ of privacy controls contained in European legislation", ["translation", "interpretation", "exhibition", "demonstration"], "B", "法官承担的是对法律条文含义的解释；interpretation 是法律‘释法’的准确名词。", {
    A: "translation 是语言之间的翻译，不是确定法律条文含义。",
    B: "interpretation 指解释和阐释，法律语境中可指司法解释。",
    C: "exhibition 是展览或展示，不与 privacy controls 构成法律关系。",
    D: "demonstration 是示范或抗议游行，不表示解释法律。",
  }),
  q(12, "2001-cloze-s4", "would be left to judges ___ to Parliament", ["better than", "other than", "rather than", "sooner than"], "C", "句子在 judges 与 Parliament 两个承担者之间作取舍；rather than 表‘而不是’，两侧结构平行。", {
    A: "better than 表质量比较，会变成法官优于议会，而非解释权归属选择。",
    B: "other than 表除……以外；与前面的 to judges 不能形成规范取舍结构。",
    C: "rather than 正确连接 to judges 与 to Parliament，表示选择前者而非后者。",
    D: "sooner than 表时间更早，不能比较两个机构的责任归属。",
  }),
  q(13, "2001-cloze-s5", "which ___ the European Convention on Human Rights legally...", ["changes", "makes", "sets", "turns"], "B", "后面有宾语 Convention 与形容词补语 binding；make A + adjective 正好构成‘使 A 具有……状态’。", {
    A: "change A legally binding 结构不成立；change 通常要接 into 或改成 change A。",
    B: "make A legally binding 是标准宾语补足语结构。",
    C: "set 可接 certain/free 等少数补语，但不说 set a convention binding 表法律生效。",
    D: "turn A binding 不成立；turn A into B 才表示转变。",
  }),
  q(14, "2001-cloze-s5", "makes the European Convention... legally ___ in Britain", ["binding", "convincing", "restraining", "sustaining"], "A", "legally binding 是固定法律搭配，表示具有法律约束力。", {
    A: "binding 作形容词表示有约束力，legally binding 搭配固定。",
    B: "convincing 是有说服力的，不表示法律效力。",
    C: "restraining 是起限制作用的，不能表示条约在法律上生效。",
    D: "sustaining 是维持性的或支持性的，不与 legally 构成此义。",
  }),
  q(15, "2001-cloze-s5", "everybody was ___ to privacy", ["authorized", "credited", "entitled", "qualified"], "C", "be entitled to + 权利/事物表示依法有权享有；privacy 正是权利内容。", {
    A: "be authorized to 后通常接动词原形，表示获准做某事；不能接 privacy 表享有权。",
    B: "be credited with 表被认为具有成就，介词与含义都不合。",
    C: "be entitled to privacy 表有权享有隐私，法律搭配准确。",
    D: "be qualified for/to do 表具备资格，强调条件，而不是普遍权利。",
  }),
  q(16, "2001-cloze-s6", "Press freedoms will be in safe hands ___ our British judges", ["with", "to", "from", "by"], "A", "be in safe hands with sb 是固定习语，表示由某人妥善掌管。", {
    A: "with 引出负责掌管的人，be in safe hands with sb 搭配完整。",
    B: "to 不能接在 in safe hands 后表示责任归属。",
    C: "from 表来源或远离，不能表示由法官保护。",
    D: "by 常引出被动动作施事，但 in safe hands 是状态习语，规范搭配用 with。",
  }),
  q(17, "2001-cloze-s7", "Witness payments became an ___", ["impact", "incident", "inference", "issue"], "D", "全文讨论围绕付费证人的公共争议；become an issue 表成为需要处理的问题。", {
    A: "impact 是影响，通常说 have an impact on，不说 became an impact 表争议。",
    B: "incident 是一次具体事件；witness payments 是一种做法而非单一事故。",
    C: "inference 是推论，与媒体付费争议无关。",
    D: "issue 可指争议性问题，became an issue 准确承接后文 concerns。",
  }),
  q(18, "2001-cloze-s8", "Up to 19 witnesses were ___ to have received payments", ["stated", "remarked", "said", "told"], "C", "sb be said to have done 是固定报道结构，表示‘据说某人已经做了某事’。", {
    A: "state 通常用 it is stated that... 或 state sth；不说 witnesses were stated to have...。",
    B: "remark 表评论，不能用于 sb be remarked to do 这一报道结构。",
    C: "be said to have done 结构正确，完成不定式还表达收款发生在报道之前。",
    D: "tell 的被动通常是 sb be told to do，表示有人吩咐某人；这里不是证人被告知去收钱。",
  }),
  q(19, "2001-cloze-s9", "Concerns were raised ___ witnesses might be encouraged...", ["what", "when", "which", "that"], "D", "空后是完整陈述句，具体解释 concerns 的内容；that 引导同位语从句。", {
    A: "what 必须在从句内充当主语、宾语或表语，但后面句子成分完整。",
    B: "when 表时间，不能说明担忧的具体命题内容。",
    C: "which 需要先行词并在从句中充当成分；这里 concerns 与从句是内容解释关系。",
    D: "that 不充当成分，只连接 concerns 与其具体内容，正合同位语从句。",
  }),
  q(20, "2001-cloze-s9", "exaggerate their stories in court to ___ guilty verdicts", ["assure", "confide", "ensure", "guarantee"], "C", "空后直接接结果 guilty verdicts；ensure + 结果表示使该结果发生。", {
    A: "assure 通常接人，如 assure sb that...，不能直接 assure guilty verdicts。",
    B: "confide 表向某人吐露秘密，常用 confide in/to，完全不合结果语义。",
    C: "ensure 可直接接结果名词，ensure guilty verdicts 表确保出现有罪裁决。",
    D: "guarantee 也可表保证，但语气更绝对，常涉及承诺或担保；此处命题搭配以 ensure + outcome 最准确。",
  }),
];
