import type { Question } from "./data";
import type { DistractorType, QuestionReasoning } from "./article-teaching";
type Model = { n: number; type: string; quote: string; clue: string; limit: string; transfer: string; errors: [DistractorType, DistractorType, DistractorType, DistractorType]; extra?: { n: number; quote: string; role: string }; corrections?: Partial<Record<"A"|"B"|"C"|"D",string>> };
const models: Record<number, Model> = {
  1:{n:1,type:"类别与实例的连接",quote:"prominent cases such as the trial of Rosemary West",clue:"cases为上位类别，the trial为紧接其后的名词例子。",limit:"for instance也能举例，但不能忽略当前连续名词连接形式；不是说它从不接名词例子。",transfer:"先看空格连接的是两个名词组还是完整句，再选择举例方式。",errors:["语境不符","搭配不符","语境不符","搭配不符"]},
  2:{n:2,type:"名词化与监管搭配",quote:"a significant tightening of legal controls over the press",clue:"a significant之后是名词中心，of接受收紧的监管制度。",limit:"-ing可以名词化；不能概括成冠词后一律不能接动名词。此处考固定的a tightening of controls。",transfer:"词性许可只是一层，还需搭配和全文政策方向。",errors:["搭配不符","搭配不符","语境不符","搭配不符"],corrections:{B:"intensify意为加强，但此处自然名词化通常为intensification；a tightening of controls是监管趋严的惯用搭配，不能概括为所有a + -ing都错。"}},
  3:{n:2,type:"法律文本名词搭配",quote:"will introduce a draft bill",clue:"introduce与bill构成提出法案的语境，需要表示尚未通过的草案。",limit:"rough/preliminary语法上可修饰名词，sketch也可作名词定语；排除依据是当前正式法案表达，不是普遍禁止这些词作定语。",transfer:"术语选择要看名词中心的领域和固定组合。",errors:["搭配不符","搭配不符","搭配不符","搭配不符"],corrections:{A:"sketch是素描或概略，本位置的正式法案草案用draft bill；并非sketch在所有表达中都不能作名词定语。"}},
  4:{n:2,type:"宾补与法律性质",quote:"propose making payments to witnesses illegal",clue:"make的宾语payments后需要性质补足，法案目标是禁止该行为。",limit:"四项均可作形容词，关键是违法这一法律判断，而不只是挑词性。",transfer:"识别make宾补后继续核对状态与上下文是否相符。",errors:["语境不符","语境不符","语境不符","语境不符"],extra:{n:1,quote:"is to ban payments",role:"禁令方向"}},
  5:{n:2,type:"新闻语境名词与搭配",quote:"the amount of publicity that can be given to a case",clue:"要控制的是媒体给案件的公开报道量。",limit:"publicity不等于popularity；曝光多不必然受欢迎。",transfer:"同时检查数量表达、动词搭配与讨论领域。",errors:["语境不符","语境不符","语境不符","语境不符"]},
  6:{n:2,type:"时间边界与司法语境",quote:"publicity that can be given to a case before a trial begins",clue:"报道限制针对开庭前的案件曝光，避免对待审案件产生影响。",limit:"before并不禁止全部报道，只给出所讨论的阶段。",transfer:"条件、原因与时间都能引从句，需依据事件先后选择。",errors:["语境不符","语境不符","语境不符","语境不符"]},
  7:{n:3,type:"动词与观点对象搭配",quote:"he agreed with a committee report",clue:"Irvine表达对报告结论的赞同，with后是report而非规则命令。",limit:"side/comply也可接with，介词匹配不能单独决定答案。",transfer:"动词、介词及对象语义三者一起检查。",errors:["搭配不符","搭配不符","语境不符","搭配不符"]},
  8:{n:3,type:"机制作用的动词选择",quote:"self regulation did not offer sufficient control",clue:"自律机制没能提供足够监管，讨论作用而非显示表象。",limit:"否定的是sufficient程度，不是说自律没有任何作用。",transfer:"区分提供实际功能与呈现或表明某事实。",errors:["语境不符","语境不符","语境不符","语境不符"]},
  9:{n:4,type:"事件名词与公开语境",quote:"Publication of the letter came two days after",clue:"主语是信件内容公之于众这一事件，came给出发生时间。",limit:"release也能表示公开发布；本题选择publication最贴合信件发表，不能声称release语法错误或绝不能用于信件。",transfer:"近义名词在语法均可时，依据所强调的事件和惯常表达比较。",errors:["语境不符","语境不符","语境不符","搭配不符"],corrections:{A:"release也可指公开材料，语法上并非不可能；这里强调信件公开发表，独立核验答案选更贴切的Publication。"}},
  10:{n:4,type:"强烈反应的比喻搭配",quote:"caused a storm of media protest",clue:"a storm of protest为大量强烈抗议的惯用比喻。",limit:"不是天气报道；不要逐字解释storm为真的暴风雨。",transfer:"抽象名词前的形象名词常形成整体搭配。",errors:["搭配不符","搭配不符","搭配不符","搭配不符"]},
  11:{n:4,type:"法律条文的含义解释",quote:"the interpretation of privacy controls contained in European legislation would be left to judges",clue:"交给法官的是对条文含义的解释，不是跨语言翻译或公开展示。",limit:"同为解释行为，interpretation的对象为法规含义，不能仅按中文翻译二字选translation。",transfer:"查看动词或名词的对象和承担者以区分熟词近义义项。",errors:["语境不符","语境不符","语境不符","语境不符"]},
  12:{n:4,type:"平行介词结构的取舍",quote:"to judges rather than to Parliament",clue:"两个to分别给出法官与议会，在责任归属上选择前者。",limit:"sooner than也能在别的语境表示宁愿而非单纯时间；当前明确替代安排用rather than最自然。",transfer:"保持两侧结构平行，并判断是取舍、例外还是时间比较。",errors:["语境不符","搭配不符","搭配不符","搭配不符"],corrections:{D:"sooner than可表示比……更早，也可在特定搭配中表示宁愿；这里是be left to A rather than to B的直接责任取舍，选rather than。"}},
  13:{n:5,type:"make宾语加形容词补语",quote:"makes the European Convention on Human Rights legally binding in Britain",clue:"Convention为宾语，binding说明其被赋予的法律状态。",limit:"不能仅凭后面出现-ing就推断进行时；这里binding为形容词。",transfer:"先找宾语和对它的状态说明，辨认使役补足结构。",errors:["搭配不符","搭配不符","搭配不符","搭配不符"],corrections:{C:"set可接特定形容词补语，例如set somebody free，但set a convention binding不是当前法律效力的自然搭配。",D:"turn可以有turn leaves brown等形容词补足结构，不能概括为后面必须用into；此处使公约具有法律约束力惯用make A legally binding。"}},
  14:{n:5,type:"法律效力形容词",quote:"legally binding in Britain",clue:"legal效力语境要求有法律约束力，binding与legally组成惯用表达。",limit:"有说服力convincing与具有强制效力不同。",transfer:"分清论证可信度、一般限制作用和法律效力。",errors:["搭配不符","语境不符","语境不符","语境不符"]},
  15:{n:5,type:"权利与介词补足",quote:"everybody was entitled to privacy",clue:"to后privacy是名词，表达人人有权享有隐私。",limit:"entitled to接名词权利内容；authorized to do通常说明获准实施具体行为。",transfer:"同样是有资格或获准，先看to后词性及权利是否普遍。",errors:["搭配不符","搭配不符","语境不符","搭配不符"]},
  16:{n:6,type:"状态习语与负责者",quote:"in safe hands with our British judges",clue:"in safe hands为可靠掌管的状态，with说明负责的人。",limit:"will be后为介词表语，没有被动分词，不能见be就选by施事。",transfer:"区分系表状态和被动动作，再选择负责者的表达。",errors:["搭配不符","搭配不符","语境不符","语法不符"]},
  17:{n:7,type:"名词表语与争议语境",quote:"Witness payments became an issue",clue:"付款是一种做法，成为需要讨论处理的公共问题。",limit:"issue不是杂志期号；incident指个别事件，不能代替争议性质。",transfer:"系词后名词给对象归类，须联系对象是行为、事件还是问题。",errors:["搭配不符","语境不符","语境不符","语境不符"],extra:{n:9,quote:"Concerns were raised",role:"后文担忧呼应"}},
  18:{n:8,type:"报道被动与完成不定式",quote:"were said to have received payments",clue:"据说某人此前做过某事，以be said to have done表达。",limit:"stated to have并非在所有正式语境都不合法；此处惯常新闻报道结构及核验答案为said。",transfer:"先区分报道已有行为和被吩咐未来动作，再读完成不定式时序。",errors:["搭配不符","搭配不符","搭配不符","语境不符"],corrections:{A:"be stated to do在正式表达中可以出现，不能绝对说不成立；此处未指明正式声明来源，普通新闻转述be said to have done最贴切。"}},
  19:{n:9,type:"名词内容从句连接",quote:"Concerns were raised that witnesses might be encouraged exaggerate their stories",clue:"concerns需要说明担忧命题；内部主语witnesses已给出，连接词不占主宾位置。",limit:"原卷encouraged后缺to是另外的异常，不是what/which应填补的成分；不影响本空内容关系。",transfer:"判断名词后的从句是补充内容，还是关系词在内部代替名词。",errors:["语法不符","语境不符","语法不符","语法不符"]},
  20:{n:9,type:"促成结果的近义动词",quote:"exaggerate their stories in court to ensure guilty verdicts",clue:"to后为目的动作，guilty verdicts是期望促成的结果，不是听到保证的人。",limit:"guarantee可接结果名词，不能据此判语法错误；此处强调采取手段促成结果，核验答案ensure更贴切。",transfer:"区分对人作保证、吐露秘密以及促成结果；近义干扰项要保留真实可用范围。",errors:["搭配不符","语境不符","语境不符","语境不符"],corrections:{D:"guarantee也能接结果名词，不是语法不成立；本句强调通过夸大证词促成有罪裁决，ensure更直接表示使结果发生，按核验答案选C。"}},
};
export function attachCloze2001Reasoning(q: Question): Question {
 const model = models[q.number!], sid = `2001-cloze-s${model.n}`;
 const explanations = { ...q.explanations, ...model.corrections } as Question["explanations"];
 const evidence: QuestionReasoning["evidence"] = [{id:"local",sentenceId:sid,quote:model.quote,role:model.clue,strength:"直接证据"}];
 if(model.extra) evidence.push({id:"context",sentenceId:`2001-cloze-s${model.extra.n}`,quote:model.extra.quote,role:model.extra.role,strength:"上下文推断"});
 const correct = q.options.find(o=>o.key===q.answer)!;
 const reasoning: QuestionReasoning = {questionType:model.type,scope:q.number===17?"paragraph":model.extra?"adjacent-sentences":"sentence",restatement:`在第${q.number}空判断${model.type}。`,keyInstruction:model.clue,
 locationPolicy:{revision:1,paths:[{id:`blank-${q.number}-clues`,label:"空格所在句的语法搭配线索",groups:[[sid]],supportingSentenceIds:model.extra?[`2001-cloze-s${model.extra.n}`]:[],maxSentences:model.extra?2:1}]},evidence,
 paraphrases:[{evidenceIds:evidence.map(e=>e.id),meaning:model.clue,optionText:correct.text,relation:"同义转换",limit:model.limit}],
 options:Object.fromEntries(q.options.map((o,i)=>[o.key,{judgment:o.key===q.answer?"选入":"排除",errorType:o.key===q.answer?undefined:model.errors[i],evidenceIds:evidence.map(e=>e.id),reasoning:explanations[o.key]}])),transfer:model.transfer};
 return {...q,explanations,reasoning};
}
