import type { BeginnerSyntaxComponent as Component, BeginnerClauseDetail as Clause, SentenceAnalysis, SyntaxVisualRole } from "./data";
import { withReviewedSyntax } from "./reviewed-syntax";
import { passage2001P1Practice } from "./2001-passage-1-practice";

const c = (text: string, form: string, fn: string, modifies: string, explanation: string, children?: Component[]): Component => ({ text, form, function: fn, modifies, explanation, children });
type Model = { components: Component[]; colors: SyntaxVisualRole[]; translations: string[]; focus: string; evidence: string; answer: string; clauses?: Clause[] };
const clause = (text: string, type: string, marker: string, role: string, subject: string, predicate: string, details: Clause["predicateDetails"], translationOrder: string): Clause => ({ text, type, marker, role, subject, predicate, predicateDetails: details, translationOrder });

const models: Record<number, Model> = {
  1: {
    components: [c("Specialisation", "抽象名词", "主语", "can be seen的承受者", "讨论的是专业细分这一变化。"), c("can be seen", "情态动词加被动式", "谓语", "Specialisation", "can后接be，seen是过去分词；不是主动看见。"), c("as a response to the problem of an increasing accumulation of scientific knowledge", "as介词短语及嵌套名词补足", "主语补足语", "说明Specialisation被看作什么", "先读一种应对，再逐层问应对什么问题、什么在不断积累。", [c("to the problem of an increasing accumulation of scientific knowledge", "to介词短语", "名词补足语", "response", "回应针对这个问题，to不是不定式。", [c("of an increasing accumulation of scientific knowledge", "of介词短语", "内容补足语", "problem", "问题是科学知识不断积累。", [c("of scientific knowledge", "of介词短语", "名词补足语", "accumulation", "说明积累的对象是科学知识。")])])])],
    colors: ["subject", "predicate", "complement"], translations: ["专业化", "可以被看作", "应对科学知识日益积累这一问题的办法"], focus: "response后两层介词短语交代原因：知识积累在先，专业化是应对。", evidence: "a response to the problem of an increasing accumulation of scientific knowledge", answer: "to连接response与问题，of再解释问题内容；as短语补充主语被视为什么，不是seen的动作宾语。",
  },
  2: {
    components: [c("By splitting up the subject matter into smaller units", "by加动名词短语", "方式状语", "后面的处理和利用信息", "拆分是单个研究者仍能处理信息的办法；执行者与one man相同。", [c("the subject matter", "名词短语", "宾语", "splitting up", "被拆分的是研究内容。"), c("into smaller units", "into介词短语", "结果补足语", "splitting up", "说明拆成什么单位。")]), c("one man", "数量词加名词", "主语", "could continue", "指单个研究者。"), c("could continue", "情态动词加动词", "谓语", "one man", "有能力继续；后面to引出继续做的动作。"), c("to handle the information and use it as the basis for further research", "并列不定式动作", "不定式补足语", "continue", "handle与use由and连接，共享to；两者都由one man完成。", [c("handle the information", "动宾结构", "不定式动作一", "to", "handle直接接处理对象。", [c("the information", "名词短语", "宾语", "handle", "即拆分后能够处理的信息。")]), c("use it as the basis for further research", "动词、宾语及宾补", "不定式动作二", "to", "use A as B是把A用作B。", [c("it", "代词", "宾语", "use", "回指information。"), c("as the basis for further research", "as介词短语", "宾语补足语", "it", "说明把信息用作什么。", [c("for further research", "for介词短语", "用途补足语", "basis", "说明什么研究的基础。")])])])], colors: ["modifier", "subject", "predicate", "complement"], translations: ["通过把研究内容划为更小单元", "单个研究者", "就能继续", "处理这些信息，并把它作为进一步研究的基础"], focus: "先把By说明的方法括起来，再看continue后并列的两个动作。", evidence: "handle the information and use it as the basis for further research", answer: "handle和use共用不定式to，执行者都是one man；it是use的宾语，as the basis补足它的用途。不能把as组当修饰研究者。",
  },
  3: {
    components: [c("But", "并列连词", "转折连接语", "前两句与本句", "从专业化的作用转到还有其他变化。"), c("specialisation", "名词", "主语", "was", "继续讨论专业化。"), c("was", "系动词", "谓语", "specialisation", "连接身份说明，不带动作宾语。"), c("only one of a series of related developments in science affecting the process of communication", "名词性数量短语", "表语", "specialisation", "中心one；专业化只是影响科学交流的相关发展之一。", [c("of a series of related developments in science affecting the process of communication", "of介词短语", "数量范围补足语", "one", "从一系列发展中选出一个。", [c("in science", "介词短语", "领域限定", "developments", "这些发展发生在科学领域。"), c("affecting the process of communication", "现在分词短语", "后置定语", "related developments", "是这些发展影响交流过程，不是新起一个有时态的谓语。", [c("the process of communication", "名词短语", "宾语", "affecting", "影响对象是交流过程。")])])])], colors: ["connector", "subject", "predicate", "complement"], translations: ["但是", "专业化", "只是", "影响科学交流过程的一系列相关发展中的一项"], focus: "only one限制专业化的地位，affecting说明整类发展具有什么作用。", evidence: "related developments in science affecting the process of communication", answer: "affecting后置说明developments；in science只是插在中间的领域限定，不能见science邻近便认作分词执行者。",
  },
  4: {
    components: [c("Another", "代词", "主语", "was", "承接上一句related developments，指另一项发展。"), c("was", "系动词", "谓语", "Another", "后接具体身份。"), c("the growing professionalisation of scientific activity", "名词短语", "表语", "Another", "另一项发展是科学活动日益职业化。", [c("growing", "分词形容词", "前置定语", "professionalisation", "修饰职业化程度增加，不是进行时。"), c("of scientific activity", "of介词短语", "对象补足语", "professionalisation", "说明何种活动走向职业化。")])], colors: ["subject", "predicate", "complement"], translations: ["另一项发展", "是", "科学活动日益职业化"], focus: "Another承接发展，不是换成另一个研究者。", evidence: "Another was the growing professionalisation", answer: "前句中心是相关developments，本句补出其中另一项professionalisation；两项相关过程不能直接视作同义。",
  },
  5: {
    components: [c("No clear-cut distinction", "否定限定名词短语", "第一分句主语", "can be drawn", "没有绝对清晰的界线，不是否认任何差异。"), c("can be drawn", "情态被动式", "第一分句谓语", "distinction", "draw a distinction被动化，指作出区分。"), c("between professionals and amateurs in science", "between介词短语", "区分范围补足语", "distinction", "界线在哪两方之间。", [c("in science", "介词短语", "领域限定", "professionals and amateurs", "双方都是科学领域中的人。")]), c("exceptions", "复数名词", "第二分句主语", "can be found", "冒号后的独立分句解释无绝对界线的原因。"), c("can be found", "情态被动式", "第二分句谓语", "exceptions", "例外可以被找到。"), c("to any rule", "to介词短语", "后置补足语", "exceptions", "任何规则都有例外；to不是不定式。")], colors: ["subject", "predicate", "modifier", "subject", "predicate", "modifier"], translations: ["没有泾渭分明的界线", "能够被划出", "在科学界专业者与业余者之间", "例外", "总能找到", "对于任何规则"], focus: "冒号后的例外说明边界不是绝对的，不能把前句译成两类人没有区别。", evidence: "No clear-cut distinction can be drawn", answer: "否定受clear-cut限定；后句承认规则有例外，支持某些领域业余者仍有竞争可能，而非所有领域毫无差别。",
  },
  6: {
    components: [c("Nevertheless", "副词", "让步转折状语", "整句判断", "有例外仍不妨碍讨论一般含义。"), c("the word “amateur”", "名词短语", "主语", "does carry", "主语是这个词，不是某名业余者。"), c("does carry", "强调助动词加动词原形", "谓语", "the word", "does强调确实带有；carry还原为原形。"), c("a connotation that the person concerned is not fully integrated into the scientific community and, in particular, may not fully share its values", "名词及同位语内容从句", "宾语", "carry", "that后的全部内容说明connotation是什么。", [c("that the person concerned is not fully integrated into the scientific community and, in particular, may not fully share its values", "that内容从句", "同位语从句", "connotation", "内部同一主语有两项并列表述。", [c("the person concerned", "名词加后置分词形容词", "主语", "is integrated和may share", "concerned是所涉及的，不是担忧的。"), c("is not fully integrated", "被动或融入状态结构", "谓语", "the person concerned", "not fully说明未完全融入，不是完全未融入。"), c("into the scientific community", "into介词短语", "融入对象补足语", "integrated", "说明融入哪个群体。"), c("in particular", "副词短语", "强调状语", "may not fully share", "尤其指出价值认同这一点。"), c("may not fully share", "情态动词与否定谓语", "并列谓语", "the person concerned", "may保留可能性，not fully保留程度限制。"), c("its values", "名词短语", "宾语", "share", "its指科学共同体，不是业余者个人。")])])], colors: ["connector", "subject", "predicate", "object"], translations: ["尽管如此", "“业余者”这个词", "确实带有", "这样一层含义：该人未完全融入科学共同体，尤其可能并不完全认同其价值观"], focus: "that整组是词语隐含义的内容，其中的否定与may都有限制。", evidence: "may not fully share its values", answer: "may是可能，not fully是并未完全；不能删去两层限制说业余者绝不认同科学价值。its回指community。", clauses: [clause("that the person concerned is not fully integrated into the scientific community and, in particular, may not fully share its values", "同位语从句", "that", "解释connotation的内容", "the person concerned", "is not fully integrated；may not fully share", [{ function: "宾语", text: "its values" }], "先读这个词带有含义，再用冒号展开融入和价值认同两层。")],
  },
  7: {
    components: [c("The growth of specialisation in the nineteenth century", "名词短语", "主语", "implied", "中心growth，不是century。", [c("of specialisation", "of介词短语", "内容补足语", "growth", "说明专业化的发展。"), c("in the nineteenth century", "介词短语", "时间限定", "growth", "限定发展发生的世纪。")]), c("with its consequent requirement of a longer, more complex training", "with介词短语", "伴随背景状语", "专业化的发展", "随之产生的训练要求说明困难为何增加；没有with宾补结构。", [c("of a longer, more complex training", "of介词短语", "内容补足语", "requirement", "longer和more complex并列修饰同一个training。")]), c("implied", "动词过去式", "谓语", "growth", "意味着，并非某人暗示别人的话。"), c("greater problems for amateur participation in science", "名词短语", "宾语", "implied", "困难落在业余者参与研究上。", [c("for amateur participation in science", "for介词短语", "对象补足语", "problems", "说明什么活动遇到困难。", [c("in science", "in介词短语", "领域补足语", "participation", "参与科学活动。")])])], colors: ["subject", "modifier", "predicate", "object"], translations: ["十九世纪专业化的发展", "伴随其随之产生的更长期、更复杂训练要求", "意味着", "业余者参与科学面临更大困难"], focus: "跳过with插入背景，先找到主语growth对应的implied。", evidence: "with its consequent requirement of a longer, more complex training", answer: "with后是名词requirement，不是有时态的动词；其因果意义来自consequent，主句仍为growth implied problems。",
  },
  8: {
    components: [c("The trend", "名词短语", "主语", "was与can be illustrated", "承接专业化增加业余参与困难的趋势。"), c("was", "系动词", "谓语", "The trend", "先评价这一趋势明显在哪里。"), c("naturally most obvious", "副词修饰形容词", "表语", "was", "obvious说明趋势明显；naturally是作者对其可理解性的评注。"), c("in those areas of science based especially on a mathematical or laboratory training", "in介词短语及分词修饰", "范围状语", "most obvious", "范围限定于尤其依赖专门训练的科学领域。", [c("based especially on a mathematical or laboratory training", "过去分词短语", "后置定语", "areas of science", "based限定这些领域以何种训练为基础，没有新限定谓语。", [c("on a mathematical or laboratory training", "on介词短语", "基础补足语", "based", "mathematical与laboratory并列限定training。")])]), c("and", "并列连词", "并列连接语", "was和can be illustrated", "两个谓语共用The trend。"), c("can be illustrated", "情态被动式", "并列谓语", "The trend", "这趋势可以用案例说明。"), c("in terms of the development of geology in the United Kingdom", "介词表达与名词补足", "例证方式状语", "can be illustrated", "英国地质学作为接下来展开的例子。", [c("in the United Kingdom", "介词短语", "地域限定", "the development of geology", "限定地质学发展的地域。")])], colors: ["subject", "predicate", "complement", "modifier", "connector", "predicate", "modifier"], translations: ["这一趋势", "表现为", "自然最为明显", "在尤其以数学或实验室训练为基础的科学领域", "并且", "可以得到说明", "通过英国地质学的发展"], focus: "based限定领域，can be illustrated回到原主语并引出地质学例证。", evidence: "based especially on a mathematical or laboratory training", answer: "based是后置分词，说明哪些areas；两种训练特征为第21题学科选择提供线索，不能把based当新谓语。",
  },
  9: {
    components: [c("A comparison of British geological publications over the last century and a half", "长名词短语", "主语", "reveals", "中心comparison为单数。", [c("of British geological publications", "of介词短语", "比较对象补足语", "comparison", "比较材料是地质学出版物。"), c("over the last century and a half", "时间介词短语", "时间范围限定", "comparison of publications", "覆盖过去一个半世纪，以文章写作时为参照，不从考试年份倒推精确起点。")]), c("reveals", "及物动词单数形式", "谓语", "comparison", "引出两项变化。"), c("not simply an increasing emphasis on the primacy of research", "递进表达的名词部分", "并列宾语一", "reveals", "第一项是更强调研究首要地位。", [c("on the primacy of research", "on介词短语", "对象补足语", "emphasis", "研究的首要地位是被强调的内容，原文没有original。")]), c("but also a changing definition of what constitutes an acceptable research paper", "递进表达的名词部分", "并列宾语二", "reveals", "第二项是合格论文标准变化。", [c("of what constitutes an acceptable research paper", "of加名词性从句", "内容补足语", "definition", "what从句说明定义的对象。", [c("what constitutes an acceptable research paper", "名词性融合关系从句", "介词宾语", "of", "what自己承担从句主语，不另补先行词。", [c("what", "融合关系代词", "主语", "constitutes", "什么构成合格论文。"), c("constitutes", "及物动词", "谓语", "what", "表示构成、算作。"), c("an acceptable research paper", "名词短语", "宾语", "constitutes", "直接承接及物动词，不是另一个宾语的补足语。")])])])], colors: ["subject", "predicate", "object", "object"], translations: ["比较过去一个半世纪英国的地质学出版物", "可以看出", "不仅越来越强调研究的首要地位", "而且何种论文算作合格研究论文的定义也在变化"], focus: "reveals后有两个平行宾语；what从句在第二个宾语的内部。", evidence: "what constitutes an acceptable research paper", answer: "what是主语，constitutes是及物谓语，paper是宾语；没有另一个被补充说明的宾语，因此不能叫paper宾补。", clauses: [clause("what constitutes an acceptable research paper", "融合型关系从句（名词性）", "what", "作of的宾语，说明definition内容", "what", "constitutes", [{ function: "宾语", text: "an acceptable research paper" }], "先说定义变化，再解释什么才算合格论文。")],
  },
  10: {
    components: [c("Thus", "副词", "承接连接语", "标准变化的具体展开", "下文用跨世纪对比落实定义变化。"), c("in the nineteenth century", "介词短语", "时间状语", "represented", "旧标准所属世纪。"), c("local geological studies", "名词短语", "第一分句主语", "represented", "地方地质研究。"), c("represented", "及物动词过去式", "第一分句谓语", "local geological studies", "表示构成、算作。"), c("worthwhile research", "名词短语", "宾语", "represented", "有价值的研究。"), c("in their own right", "固定介词短语", "资格状语", "represented worthwhile research", "这些地方研究凭自身即可成立。"), c("but", "并列连词", "转折连接语", "两个世纪的标准", "分号后转到新的认可条件。"), c("in the twentieth century", "介词短语", "时间状语", "have become", "新标准所属世纪。"), c("local studies", "名词短语", "第二分句主语", "have become", "仍指地方研究。"), c("have increasingly become", "完成时系动词与副词", "第二分句谓语", "local studies", "逐渐变得，后接表语。"), c("acceptable to professionals", "形容词及补足语", "表语", "have become", "to professionals说明由哪类人接受。"), c("only if they incorporate, and reflect on, the wider geological picture", "only if条件从句", "条件状语从句", "have become acceptable", "是必要条件，满足它不等于其他发表条件自动满足。", [c("they", "代词", "主语", "incorporate和reflect on", "回指local studies。"), c("incorporate", "及物动词", "并列谓语一", "they", "直接接picture。"), c("reflect on", "动词加介词", "并列谓语二", "they", "思考、评述，on不能省。"), c("the wider geological picture", "名词短语", "共享宾语内容", "incorporate与on", "既是incorporate的直接宾语，也是介词on的宾语。")])], colors: ["connector", "modifier", "subject", "predicate", "object", "modifier", "connector", "modifier", "subject", "predicate", "complement", "modifier"], translations: ["因此", "在十九世纪", "地方地质研究", "本身构成", "有价值的研究", "凭自身条件", "但是", "在二十世纪", "地方研究", "逐渐才变得", "能被专业人士接受", "只有在纳入并思考更广阔地质学图景的条件下"], focus: "跨世纪变的是认可标准；only if给必要条件而非无条件保证。", evidence: "only if they incorporate, and reflect on, the wider geological picture", answer: "地方研究须纳入并思考更广阔的全局；incorporate直接接对象，reflect on保留介词，共享picture并不允许删on。", clauses: [clause("only if they incorporate, and reflect on, the wider geological picture", "必要条件状语从句", "only if", "限定获得专业认可的必要条件", "they", "incorporate；reflect on", [{ function: "宾语", text: "the wider geological picture" }], "只有把局部研究纳入并思考全局，才可获得认可。")],
  },
  11: {
    components: [c("Amateurs", "复数名词", "主语", "have continued", "业余研究者。"), c("on the other hand", "插入衔接短语", "对比状语", "专业者标准与业余者做法", "与前文专业者的新要求对照。"), c("have continued", "现在完成时", "谓语", "Amateurs", "延续至写作时的做法。"), c("to pursue local studies", "不定式短语", "不定式补足语", "continued", "继续从事地方研究。", [c("local studies", "名词短语", "宾语", "pursue", "pursue在这里是从事研究。")]), c("in the old way", "介词短语", "方式状语", "pursue", "延续旧研究方式，不额外断言完全没有其他活动。")], colors: ["subject", "connector", "predicate", "complement", "modifier"], translations: ["业余研究者", "另一方面", "一直继续", "从事地方研究", "沿用旧方式"], focus: "对比的是专业认可标准已经变，业余者的做法却延续。", evidence: "on the other hand, have continued to pursue local studies in the old way", answer: "on the other hand接第10句的新标准，old way回指地方研究自身即可有价值的旧方式；原句没有only，不加只做的绝对限制。",
  },
  12: {
    components: [c("The overall result", "名词短语", "主语", "has been", "概括前文专业标准变化与业余者未变的结果。"), c("has been", "完成时系动词", "谓语", "result", "结果是，后面的to do为表语。"), c("to make entrance to professional geological journals harder for amateurs", "不定式短语", "表语", "result", "make宾语加形容词宾补表达进入专业期刊更难。", [c("entrance to professional geological journals", "名词短语", "宾语", "make", "指在专业期刊发表的准入。", [c("to professional geological journals", "to介词短语", "方向对象补足语", "entrance", "进入哪一类期刊。")]), c("harder", "形容词比较级", "宾语补足语", "entrance", "变难的是准入。"), c("for amateurs", "for介词短语", "受影响者补足语", "harder", "对业余者而言更难。")]), c("a result that has been reinforced by the widespread introduction of refereeing, first by national journals in the nineteenth century and then by several local geological journals in the twentieth century", "同位复述名词及关系从句", "同位说明", "前面完整结果", "a result复述准入更难这一结果，再说明制度如何强化它。", [c("that has been reinforced by the widespread introduction of refereeing, first by national journals in the nineteenth century and then by several local geological journals in the twentieth century", "that定语从句", "后置定语", "a result", "that作从句主语；后两个by进一步说明引入审稿制度的机构与先后。", [c("that", "关系代词", "主语", "has been reinforced", "回指result。"), c("has been reinforced", "现在完成时被动", "谓语", "that", "这一结果被进一步强化。"), c("by the widespread introduction of refereeing", "by介词短语", "强化因素状语", "has been reinforced", "强化因素是审稿制度广泛引入。"), c("first by national journals in the nineteenth century", "介词短语及时间限定", "引入者及先行时间补充", "introduction of refereeing", "先在十九世纪由全国性期刊引入。"), c("and then by several local geological journals in the twentieth century", "并列介词短语及时间限定", "引入者及后续时间补充", "introduction of refereeing", "随后二十世纪由若干地方地质期刊引入；不是说所有地方期刊。")])])], colors: ["subject", "predicate", "complement", "modifier"], translations: ["总体结果", "是", "使业余者更难进入专业地质学期刊发表", "这一结果又因审稿制度广泛引入而强化：先是十九世纪的全国性期刊，随后是二十世纪的若干地方期刊"], focus: "主句result has been后接不定式表语；第二个result只是复述，再带自己的关系从句。", evidence: "to make entrance to professional geological journals harder for amateurs", answer: "make的宾语是entrance及其to补足，harder是对entrance的宾补。整组to make说明结果，不是目的状语。", clauses: [clause("that has been reinforced by the widespread introduction of refereeing, first by national journals in the nineteenth century and then by several local geological journals in the twentieth century", "定语从句", "that", "修饰同位复述的result", "that", "has been reinforced", [], "先说结果被强化，再讲全国期刊先、地方期刊后的审稿制度传播。")],
  },
  13: {
    components: [c("As a logical consequence of this development", "as介词短语", "结果背景状语", "后面的期刊出现", "this development承接前文专业发表门槛提高及分化发展。"), c("separate journals", "名词短语", "主语", "have appeared", "不同读者群对应不同期刊。"), c("have now appeared", "现在完成时及时间副词", "谓语", "journals", "appear不及物，未用被动。"), c("aimed mainly towards either professional or amateur readership", "过去分词短语", "后置定语", "journals", "说明这些期刊主要面向哪类读者。", [c("towards either professional or amateur readership", "介词短语及选择并列", "目标补足语", "aimed", "professional和amateur是两类readership，不是两种动作。")])], colors: ["modifier", "subject", "predicate", "modifier"], translations: ["作为这一发展的自然结果", "分开的期刊", "现在已经出现", "主要面向专业或业余读者群之一"], focus: "aimed后置说明期刊读者，不与appeared合成被动谓语。", evidence: "separate journals have now appeared aimed mainly towards either professional or amateur readership", answer: "限定谓语只有have appeared；aimed是过去分词修饰journals。either/or分开两个读者群，延续分化主线。",
  },
  14: {
    components: [c("A rather similar process of differentiation", "名词短语", "主语", "has led", "中心process，类似于期刊分流的过程。"), c("has led", "现在完成时", "谓语", "process", "lead to表示导致，后面的to为介词。"), c("to professional geologists coming together nationally within one or two specific societies", "介词加动名词结构", "结果补足语", "has led", "介词to后是地质学家联合起来这件事。", [c("professional geologists", "名词短语", "非谓语逻辑主语", "coming", "执行coming的专业地质学家不是本句有限谓语的主语。"), c("coming together nationally within one or two specific societies", "-ing非谓语短语", "动名词动作内容", "to后的结果", "在全国层面一两个特定学会中联合。", [c("nationally", "副词", "范围状语", "coming together", "全国层面联合。"), c("within one or two specific societies", "介词短语", "组织范围状语", "coming together", "在一两个特定学会内。")])]), c("whereas the amateurs have tended either to remain in local societies or to come together nationally in a different way", "whereas对照从句", "对比状语从句", "前面的专业者联合", "业余者有地方或不同全国方式两条路径，不是只在地方活动。", [c("the amateurs", "名词短语", "主语", "have tended", "业余研究者。"), c("have tended", "现在完成时", "谓语", "the amateurs", "tend保留倾向性。"), c("either to remain in local societies or to come together nationally in a different way", "选择并列不定式", "不定式补足语", "tended", "either/or连接形式平行的两条选择。", [c("to remain in local societies", "不定式短语", "选择一", "tended", "留在地方学会。"), c("to come together nationally in a different way", "不定式短语", "选择二", "tended", "以另一种方式在全国联合。")])])], colors: ["subject", "predicate", "complement", "modifier"], translations: ["一种颇为相似的分化过程", "已经导致", "专业地质学家在全国层面的一两个特定学会内联合", "而业余者往往留在地方学会，或以不同方式在全国联合"], focus: "主句to后是非谓语结果，而whereas之后才另有完整主谓。", evidence: "to professional geologists coming together", answer: "lead to中的to为介词；geologists是coming的逻辑主语，coming没有限定时态。对照从句的限定谓语则是have tended。", clauses: [clause("whereas the amateurs have tended either to remain in local societies or to come together nationally in a different way", "对比状语从句", "whereas", "对照专业者与业余者的组织方式", "the amateurs", "have tended", [], "先讲专业者集中联合，再说业余者两种选择；不漏第二种全国联合。")],
  },
  15: {
    components: [c("Although the process of professionalisation and specialisation was already well under way in British geology during the nineteenth century", "Although让步从句", "让步状语从句", "主句后果较晚显现", "承认过程在十九世纪已经充分展开。", [c("the process of professionalisation and specialisation", "名词短语", "主语", "was", "中心process。"), c("was", "系动词", "谓语", "process", "后接under way表状态。"), c("already well under way", "副词与固定介词表达", "表语", "was", "under way表示在进行中；already与well修饰进展状态。"), c("in British geology", "介词短语", "领域状语", "was under way", "限定英国地质学。"), c("during the nineteenth century", "介词短语", "时间状语", "was under way", "说明过程较早展开的世纪。")]), c("its full consequences", "名词短语", "主语", "were delayed", "its回指professionalisation and specialisation这一过程。"), c("were thus delayed", "一般过去时被动与副词", "谓语", "consequences", "后果较晚显现，不必有某人故意推迟。"), c("until the twentieth century", "时间介词短语", "时间终点状语", "were delayed", "完整后果直到二十世纪才显现。")], colors: ["modifier", "subject", "predicate", "modifier"], translations: ["尽管十九世纪英国地质学的职业化与专业化已充分展开", "其完整后果", "却因此较晚显现", "一直到二十世纪"], focus: "展开的时间与全部后果显现的时间不同，不能互相替代。", evidence: "was already well under way in British geology during the nineteenth century", answer: "十九世纪修饰过程已经展开；二十世纪修饰完整后果延后显现。Although不是否定前一事实，而是承认后突出反差。", clauses: [clause("Although the process of professionalisation and specialisation was already well under way in British geology during the nineteenth century", "让步状语从句", "Although", "承认过程展开较早，与完整后果较晚对比", "the process of professionalisation and specialisation", "was", [{ function: "表语", text: "already well under way" }], "虽然过程十九世纪已展开，完整后果却到二十世纪才显现。")],
  },
  16: {
    components: [c("In science generally", "介词短语与范围副词", "范围状语", "全句历史评价", "从英国地质学扩大到整个科学领域。"), c("however", "副词", "转折连接语", "前句个案与本句总体判断", "提醒不能用个案后果时间替代整体关键期。"), c("the nineteenth century", "名词短语", "主语", "must be reckoned", "被评价的世纪。"), c("must be reckoned", "情态动词加被动式", "谓语", "the nineteenth century", "必须视为，是作者历史评价，不是法律义务。"), c("as the crucial period for this change in the structure of science", "as介词短语及名词补足", "主语补足语", "the nineteenth century", "说明这一世纪被视为什么。", [c("for this change in the structure of science", "for介词短语", "对象补足语", "crucial period", "对科学结构变化而言关键。", [c("in the structure of science", "in介词短语", "变化领域限定", "change", "this change指专业化与职业化重塑科学结构。")])])], colors: ["modifier", "connector", "subject", "predicate", "complement"], translations: ["就科学总体而言", "然而", "十九世纪", "必须被看作", "科学结构这场变化的关键时期"], focus: "generally改变讨论范围，因此两句不同世纪判断并不冲突。", evidence: "In science generally", answer: "上一句只谈英国地质学的完整后果；本句评科学总体的关键转型期。范围和所评价的事件都不同。",
  },
};

const readingQuestions: Record<number, string> = {
  1: "as后的response、problem和accumulation如何逐层相接？", 2: "handle和use共享什么结构，it又回指什么？", 3: "affecting跨过in science后说明哪个中心名词？", 4: "Another为何指另一项发展，而非另一个人？", 5: "No clear-cut允许怎样的例外，不能扩大成什么结论？", 6: "may not fully与its分别保留什么限制和所指？", 7: "插入的with背景是否另含有限谓语？主句是谁意味着什么？", 8: "based与can be illustrated各处在哪个语法层级？", 9: "what从句中谁是主语，paper为什么是宾语而不是宾补？", 10: "only if怎样限制认可条件，incorporate与reflect on怎样共用对象？", 11: "on the other hand与old way接回前文什么对照？", 12: "to make整组是什么功能，内部entrance与harder又是什么关系？", 13: "appeared与aimed为何不能合读成被动谓语？", 14: "led to后为什么用coming，whereas从句的有限谓语又在哪里？", 15: "十九世纪与二十世纪分别对应哪个事件？", 16: "generally改变了什么范围，结尾为何不与上句日期矛盾？",
};

export function upgradePassage2001P1(draft: SentenceAnalysis): SentenceAnalysis {
  const model = models[draft.number];
  const naturalCorrections: Record<number, string> = {
    1: "专业化可以看作应对科学知识不断积累这一问题的办法。",
    6: "尽管如此，‘业余者’这个词确实暗含：这个人并未完全融入科学共同体，尤其可能不完全认同其价值观。",
    8: "这种趋势在尤其依赖数学或实验室训练的科学领域最明显，可以用英国地质学的发展来说明。",
    9: "比较英国过去一个半世纪的地质学出版物可以发现：学界日益强调研究的首要地位，而且怎样的论文才算合格研究论文的标准也在变化。",
    11: "另一方面，业余研究者仍沿用旧方式从事地方研究。",
  };
  const reviewed = withReviewedSyntax({ ...draft, trunk: draft.number === 9 ? "A comparison reveals not simply an increasing emphasis, but also a changing definition." : draft.trunk,
    natural: naturalCorrections[draft.number] ?? draft.natural,
    grammar: draft.number === 2 ? ["By doing作方式状语，splitting的执行者与one man一致。", "限定谓语是could continue；handle与use共用不定式to，不各自承担时态。", "use it as the basis中it为宾语，as短语作宾补，for further research再补充basis。"] : draft.grammar,
    beginnerSyntax: { components: model.components, clauses: model.clauses ?? [], reading: { focus: model.focus, questions: [{ question: readingQuestions[draft.number], evidence: model.evidence, answer: model.answer }] } },
    practice: passage2001P1Practice[draft.id],
  }, model.colors);
  return { ...reviewed, translationAlignment: reviewed.chunks.map((block, i) => ({ english: block.text, chinese: model.translations[i] })) };
}
