import type { ContextualSubstitution } from "./contextual-vocabulary";

export type Cloze2001LexiconEntry = {
  partOfSpeech: string;
  contextualMeaning: string;
  use: string;
  specialForms?: string[];
  examSynonyms?: string[];
  collocations?: string[];
  otherMeanings?: string[];
  wordFamily?: string[];
  confusions?: string[];
  contextualSubstitutions?: ContextualSubstitution[];
};

const e = (partOfSpeech: string, contextualMeaning: string, use: string, extra: Partial<Cloze2001LexiconEntry> = {}): Cloze2001LexiconEntry => ({
  partOfSpeech,
  contextualMeaning,
  use,
  ...extra,
});

export const cloze2001LemmaAliases: Record<string, string> = {
  agreed: "agree", authorized: "authorize", begins: "begin", came: "come", cases: "case",
  complied: "comply", concerns: "concern", contained: "contain", controls: "control", credited: "credit",
  days: "day", encouraged: "encourage", entitled: "entitle", families: "family", figures: "figure",
  freedoms: "freedom", hands: "hand", judges: "judge", laid: "lay", makes: "make", newspapers: "newspaper",
  payments: "payment", qualified: "qualify", received: "receive", remarked: "remark", rights: "right", said: "say",
  sentenced: "sentence", sentences: "sentence", sets: "set", sided: "side", stated: "state",
  stories: "story", sustaining: "sustain", telling: "tell", told: "tell", turns: "turn",
  verdicts: "verdict", witnesses: "witness", seeking: "seek", involved: "involve", raised: "raise", tightening: "tighten",
};

export const cloze2001FormPartOfSpeech: Record<string, string> = {
  agreed: "v.（agree 的过去式）", authorized: "v./adj.（authorize 的过去分词）", begins: "v.（begin 的第三人称单数）",
  came: "v.（come 的过去式）", cases: "n.（case 的复数）", complied: "v.（comply 的过去式）",
  concerns: "n.（concern 的复数）", contained: "v.（contain 的过去分词）", controls: "n.（control 的复数）",
  credited: "v./adj.（credit 的过去分词）", encouraged: "v.（encourage 的过去分词）", entitled: "v./adj.（entitle 的过去分词）",
  families: "n.（family 的复数）", figures: "n.（figure 的复数）", freedoms: "n.（freedom 的复数）",
  hands: "n.（hand 的复数）", judges: "n.（judge 的复数）", makes: "v.（make 的第三人称单数）",
  laid: "v.（lay 的过去式/过去分词）",
  newspapers: "n.（newspaper 的复数）", payments: "n.（payment 的复数）", received: "v.（receive 的过去分词）",
  remarked: "v.（remark 的过去式）", rights: "n.（right 的复数）", said: "v.（say 的过去式/过去分词）",
  sentenced: "v.（sentence 的过去分词）", sentences: "n.（sentence 的复数）", sets: "v.（set 的第三人称单数）",
  sided: "v.（side 的过去式）", stated: "v.（state 的过去式/过去分词）", stories: "n.（story 的复数）",
  telling: "v.-ing（tell 的动名词）", told: "v.（tell 的过去式/过去分词）", turns: "v.（turn 的第三人称单数）",
  verdicts: "n.（verdict 的复数）", witnesses: "n.（witness 的复数）", seeking: "v.-ing（seek 的现在分词）",
  involved: "v./adj.（involve 的过去分词）", raised: "v.（raise 的过去分词）",
};

export const cloze2001Lexicon: Record<string, Cloze2001LexiconEntry> = {
  agree: e("v.", "同意；赞同", "agree with a report 表示赞同报告中的观点。", { specialForms: ["agree—agreed—agreed—agreeing"], collocations: ["agreed with a committee report"], examSynonyms: ["consent（同意，较正式且常指许可）", "approve（赞成；批准）"] }),
  amount: e("n.", "数量；总量", "the amount of publicity 中 amount 接不可数名词 publicity。", { examSynonyms: ["quantity（数量，适用范围更广）", "number（可数名词的数量）"] }),
  assure: e("v.", "向某人保证", "第20题干扰项；assure 通常接人，而不是直接接 guilty verdicts。", { specialForms: ["assure—assured—assured—assuring"], examSynonyms: ["ensure（确保结果）", "guarantee（担保；保证）"] }),
  authorize: e("v.", "授权；批准", "第15题干扰项；be authorized to do 表获准做某事，不能说 authorized to privacy。", { specialForms: ["authorize—authorized—authorized—authorizing"], examSynonyms: ["permit（允许）", "empower（授权使有权）"] }),
  ban: e("v./n.", "禁止；禁令", "is to ban payments 中作及物动词，宾语是 payments。", { specialForms: ["ban—banned—banned—banning"], collocations: ["is to ban payments"], examSynonyms: ["prohibit（正式禁止）", "forbid（禁止某人做事）"] }),
  begin: e("v.", "开始", "before a trial begins 中作不及物谓语。", { specialForms: ["begin—began—begun—beginning"], collocations: ["before a trial begins"], examSynonyms: ["start（开始，较普通）", "commence（正式开始）"] }),
  better: e("adj./adv.", "更好的；更好地", "第12题 better than 是比较结构，不能表达‘而不是’。", { specialForms: ["good/well—better—best"], examSynonyms: ["superior（更优的，常接 to）", "preferable（更可取的）"] }),
  bill: e("n.", "法案；议案", "draft bill 指提交讨论但尚未成为法律的法案草案。", { collocations: ["introduce a draft bill"], examSynonyms: ["act（已经通过的法案/法令）", "proposal（提案，范围更广）"] }),
  binding: e("adj.", "有约束力的", "legally binding 作宾语补足语，说明公约在法律上必须遵守。", { specialForms: ["bind—bound—bound—binding"], collocations: ["make the European Convention on Human Rights legally binding"], examSynonyms: ["compulsory（强制的）", "obligatory（义务性的）"] }),
  britain: e("proper n.", "英国", "in Britain 是地点范围状语，限定公约在哪里具有法律效力。"),
  british: e("adj.", "英国的", "our British judges 中作定语修饰 judges。"),
  case: e("n.", "案件；案例", "prominent cases 指引人关注的重大案件；a case 后文指待审案件。", { specialForms: ["case—cases（复数）"], examSynonyms: ["lawsuit（诉讼案件）", "instance（实例，非法律案件专义）"] }),
  chancellor: e("n.", "大法官；大臣", "the Lord Chancellor 是 Lord Irvine 的正式职衔。", { specialForms: ["chancellor—chancellors（复数）"] }),
  commons: e("proper n.", "下议院", "the House of Commons 是英国议会下院的固定名称。"),
  comply: e("v.", "遵守；依从", "第7题干扰项；comply with 接规则或要求，不表示赞同报告观点。", { specialForms: ["comply—complied—complied—complying"], examSynonyms: ["obey（服从命令）", "conform（遵从规范）"] }),
  concern: e("n./v.", "担忧；使担忧", "Concerns were raised 是被动表达，that 从句说明担忧内容。", { collocations: ["concerns were raised"], examSynonyms: ["anxiety（焦虑）", "worry（担心，较普通）"] }),
  confide: e("v.", "吐露；信任", "第20题干扰项；confide in sb 或 confide sth to sb，不能表示确保裁决。", { specialForms: ["confide—confided—confided—confiding"], examSynonyms: ["reveal（透露）", "entrust（托付）"] }),
  contain: e("v.", "包含；容纳", "contained in European legislation 是过去分词短语，后置修饰 privacy controls。", { specialForms: ["contain—contained—contained—containing"], examSynonyms: ["include（包括）", "hold（容纳）"] }),
  control: e("n./v.", "监管；控制", "legal controls 是法规限制；control the amount 是动词用法。", { collocations: ["a tightening of legal controls", "control the amount of publicity", "offer sufficient control"], examSynonyms: ["regulation（规制）", "restriction（限制）"] }),
  convention: e("n.", "公约；惯例", "the European Convention on Human Rights 是《欧洲人权公约》。", { specialForms: ["convention—conventions（复数）"], examSynonyms: ["treaty（国家间条约）", "custom（习俗惯例）"] }),
  convincing: e("adj.", "有说服力的", "第14题干扰项；说明论据可信，不能表示法律约束力。", { specialForms: ["convince—convinced—convinced—convincing"], examSynonyms: ["persuasive（有说服力的）", "credible（可信的）"] }),
  court: e("n.", "法院；法庭", "go to court 表诉诸法院；in court 表在庭审场合。", { collocations: ["go to court", "exaggerate their stories in court"], examSynonyms: ["tribunal（特别法庭）", "courtroom（法庭房间）"] }),
  credit: e("v./n.", "认为有；归功于；信用", "第15题 credited 是干扰项；be credited with 表被认为具有某成就。", { specialForms: ["credit—credited—credited—crediting"], examSynonyms: ["attribute（归因于）", "recognize（认可）"] }),
  day: e("n.", "天；日", "two days after 是时间差表达。", { specialForms: ["day—days（复数）"] }),
  demonstration: e("n.", "示范；证明；示威", "第11题干扰项，不能表示对法律条文的解释。", { examSynonyms: ["display（展示）", "protest（抗议示威）"] }),
  down: e("adv./prep./adj.", "向下；处于较低状态", "lay down 是短语动词，法律语境表示明文规定。", { collocations: ["lay down that"] }),
  draft: e("adj./n./v.", "草拟的；草案", "a draft bill 中作定语，表示尚未正式通过。", { collocations: ["introduce a draft bill"], examSynonyms: ["preliminary（初步的）", "outline（提纲）"] }),
  encourage: e("v.", "鼓励；促使", "原卷 be encouraged 后漏印 to；规范结构是 be encouraged to exaggerate。", { specialForms: ["encourage—encouraged—encouraged—encouraging"], collocations: ["might be encouraged exaggerate"], examSynonyms: ["urge（力劝）", "prompt（促使）"] }),
  ensure: e("v.", "确保；保证结果", "to ensure guilty verdicts 中直接接结果名词。", { specialForms: ["ensure—ensured—ensured—ensuring"], collocations: ["ensure guilty verdicts"], examSynonyms: ["assure（向某人保证）", "guarantee（担保，语气更绝对）"] }),
  entitle: e("v.", "使有权；给……题名", "be entitled to privacy 表依法有权享有隐私。", { specialForms: ["entitle—entitled—entitled—entitling"], collocations: ["be entitled to privacy"], examSynonyms: ["authorize（授权做某事）", "qualify（使具备资格）"] }),
  everybody: e("indefinite pron.", "每个人；人人", "在 that 从句中作主语，语法上按第三人称单数处理。", { examSynonyms: ["everyone（每个人，基本同义）", "all people（所有人，复数结构）"] }),
  exaggerate: e("v.", "夸大；夸张", "exaggerate their stories 表夸大证词内容。", { specialForms: ["exaggerate—exaggerated—exaggerated—exaggerating"], collocations: ["exaggerate their stories in court"], examSynonyms: ["overstate（夸大陈述）", "magnify（放大；夸大）"] }),
  exhibition: e("n.", "展览；展示", "第11题干扰项，不表示法律解释。", { examSynonyms: ["display（陈列）", "show（展览）"] }),
  exposure: e("n.", "暴露；曝光", "第9题干扰项；exposure 强调暴露于公众或危险，不等于信件正式发表。", { examSynonyms: ["disclosure（披露）", "publicity（曝光）"] }),
  fastening: e("n./v.-ing", "扣紧；扣件", "第2题干扰项，通常用于安全带、绳索或物件连接。", { specialForms: ["fasten—fastened—fastened—fastening"], examSynonyms: ["securing（固定）", "attachment（连接件）"] }),
  figure: e("n./v.", "公众人物；数字；人物", "public figures 指经常受到公众关注的知名人士。", { collocations: ["public figures"], examSynonyms: ["personality（知名人物）", "celebrity（名人）"] }),
  flare: e("n./v.", "闪光；突然燃烧", "第10题干扰项；需用 flare-up 才可表示突然爆发的冲突。", { specialForms: ["flare—flared—flared—flaring"], examSynonyms: ["blaze（火焰）", "burst（突然爆发）"] }),
  flash: e("n./v.", "闪光；快速闪现", "第10题干扰项，a flash of protest 不能表示一场大规模抗议。", { specialForms: ["flash—flashed—flashed—flashing"], examSynonyms: ["glimpse（一瞥）", "spark（火花）"] }),
  focusing: e("n./v.-ing", "聚焦；集中", "第2题干扰项；focus 通常接 on，不表示管制变严。", { specialForms: ["focus—focused/focussed—focused/focussed—focusing/focussing"], examSynonyms: ["concentration（集中）", "attention（关注）"] }),
  freedom: e("n.", "自由；自由权", "Press freedoms 用复数，指新闻界享有的多项自由。", { specialForms: ["freedom—freedoms（复数）"], collocations: ["press freedoms"], examSynonyms: ["liberty（自由权，较正式）", "independence（独立）"] }),
  gerald: e("proper n.", "Gerald（人名）", "Gerald Kaufman 是文中下议院媒体特别委员会主席的姓名。"),
  guarantee: e("v./n.", "保证；担保", "第20题干扰项；可接结果但语气更绝对，常含承诺或担保责任。", { specialForms: ["guarantee—guaranteed—guaranteed—guaranteeing"], examSynonyms: ["ensure（确保结果）", "warrant（担保）"] }),
  guilty: e("adj.", "有罪的", "guilty verdicts 指认定被告有罪的裁决。", { collocations: ["ensure guilty verdicts"], examSynonyms: ["culpable（应受责备/有罪责的）", "criminal（犯罪的）"] }),
  hand: e("n.", "手；掌管", "in safe hands 是习语，指由可靠者负责。", { specialForms: ["hand—hands（复数）"], collocations: ["be in safe hands"] }),
  house: e("n.", "议院；房屋", "the House of Commons 中专指英国下议院。", { specialForms: ["house—houses（复数）；house v.—housed—housed—housing"] }),
  illegal: e("adj.", "违法的", "make payments illegal 中作宾语补足语，说明付款行为被定为违法。", { collocations: ["propose making payments to witnesses illegal"], examSynonyms: ["unlawful（违法的，法律正式用语）", "illicit（非法且常带隐秘意味）"] }),
  illogical: e("adj.", "不合逻辑的", "第4题干扰项，只评价推理，不说明法律地位。", { examSynonyms: ["irrational（不理性的）", "inconsistent（前后不一致的）"] }),
  impact: e("n./v.", "影响；冲击", "第17题干扰项；常说 have an impact on，而非 become an impact。", { collocations: ["have an impact on"], examSynonyms: ["effect（影响/结果）", "influence（影响力）"] }),
  improbable: e("adj.", "不大可能的", "第4题干扰项，说明概率而非合法性。", { examSynonyms: ["unlikely（不太可能的）", "implausible（难以置信的）"] }),
  improper: e("adj.", "不适当的；不合规矩的", "第4题干扰项，道德或程序评价弱于明确的 illegal。", { examSynonyms: ["inappropriate（不适当的）", "unacceptable（不可接受的）"] }),
  indicate: e("v.", "表明；指示", "第8题干扰项；不能表达行业自律‘提供’控制力。", { specialForms: ["indicate—indicated—indicated—indicating"], examSynonyms: ["show（表明）", "suggest（暗示）"] }),
  inference: e("n.", "推论；推断", "第17题干扰项，不是付费行为引发的公共问题。", { examSynonyms: ["deduction（演绎推论）", "conclusion（结论）"] }),
  instance: e("n.", "例子；实例", "for instance 是插入式举例表达，不能在第1题位置直接接名词。", { collocations: ["for instance"], examSynonyms: ["example（例子）", "case（实例/案件）"] }),
  intensifying: e("v.-ing", "加强；加剧", "第2题干扰项；规范名词应为 intensification，或直接用 intensifying controls。", { specialForms: ["intensify—intensified—intensified—intensifying"], examSynonyms: ["strengthening（加强）", "escalating（升级）"] }),
  interpretation: e("n.", "解释；阐释", "the interpretation of privacy controls 指对法律隐私规定的司法解释。", { collocations: ["privacy controls contained in European legislation"], examSynonyms: ["explanation（解释说明）", "construction（法律条文解释，专业义）"] }),
  introduction: e("n.", "引入；实施", "introduction of the Human Rights Bill 是名词化主语。", { collocations: ["introduction of the Human Rights Bill"], examSynonyms: ["implementation（实施）", "enactment（制定成法）"] }),
  irvine: e("proper n.", "Irvine（人名）", "Lord Irvine 是文中英国大法官的姓名。"),
  issue: e("n.", "争议问题；议题", "became an issue 表从一种做法变成公共争议。", { collocations: ["became an issue"], examSynonyms: ["problem（问题）", "controversy（争议）"] }),
  judge: e("n./v.", "法官；判断", "our British judges 中作名词，法官是隐私法规的解释者。", { specialForms: ["judge—judges（复数）；judge—judged—judged—judging"], collocations: ["be left to judges"] }),
  kaufman: e("proper n.", "Kaufman（人名）", "Gerald Kaufman 是下议院媒体特别委员会主席。"),
  lay: e("v.", "放置；规定", "laid down that 在法律语境表示正式规定。", { specialForms: ["lay—laid—laid—laying"], collocations: ["lay down that"], examSynonyms: ["stipulate（规定）", "establish（确立）"] }),
  legal: e("adj.", "法律的；合法的", "legal controls 指通过法律形成的监管措施。", { examSynonyms: ["lawful（合法的）", "judicial（司法的）"] }),
  legally: e("adv.", "在法律上；依法", "legally 修饰 binding，表示约束力来自法律。", { examSynonyms: ["lawfully（合法地）", "judicially（司法地）"] }),
  legislation: e("n.", "法律；立法", "European legislation 指欧洲层面的成文法律规定。", { examSynonyms: ["law（法律，范围更广）", "statute（成文法）"] }),
  letter: e("n.", "信件", "Publication of the letter 指这封信被公开发表。", { specialForms: ["letter—letters（复数）"], collocations: ["publication of the letter"] }),
  lord: e("n./title", "勋爵；阁下（头衔）", "Lord Irvine 中是人名前的英国贵族/官员头衔。"),
  make: e("v.", "使……成为", "make A legally binding 是宾语 + 形容词宾补结构。", { specialForms: ["make—made—made—making"], collocations: ["make the European Convention on Human Rights legally binding"], examSynonyms: ["render（使成为，正式）", "cause（导致）"] }),
  media: e("n.", "媒体；新闻界", "media select committee 与 media protest 都指新闻媒体领域。", { specialForms: ["medium—media（传统复数；现代 media 常作集合名词）"], examSynonyms: ["press（新闻界）", "news outlets（新闻机构）"] }),
  might: e("modal v.", "可能；也许", "might be encouraged 表较谨慎的可能性判断。", { specialForms: ["情态动词：无普通人称变化；后接动词原形"] }),
  newspaper: e("n.", "报纸；报社", "newspapers 在文中既是出版物也指经营报道的报社机构。", { specialForms: ["newspaper—newspapers（复数）"], examSynonyms: ["press（新闻界）", "paper（报纸，较口语）"] }),
  parliament: e("proper n.", "议会", "to Parliament 与 to judges 平行，表示解释权不交给议会。"),
  particular: e("adj./n.", "特定的；特别之处", "in particular 是‘尤其’，第1题中不能直接作为介词连接例子。", { collocations: ["in particular"], examSynonyms: ["specific（具体的）", "especially（尤其，副词）"] }),
  payment: e("n.", "付款；报酬", "payments to witnesses 指付给证人的钱。", { specialForms: ["payment—payments（复数）"], collocations: ["payments to witnesses", "payments for telling their stories"], examSynonyms: ["fee（服务费）", "compensation（报酬/补偿）"] }),
  peculiarity: e("n.", "特性；怪异之处", "第5题干扰项，不能表示案件受到的媒体报道量。", { examSynonyms: ["oddity（怪异之处）", "feature（特征）"] }),
  penalty: e("n.", "处罚；罚金", "第5题干扰项，案件在庭前受到的是 publicity，不是一定数量的 penalty。", { specialForms: ["penalty—penalties（复数）"], examSynonyms: ["punishment（惩罚）", "fine（罚款）"] }),
  popularity: e("n.", "受欢迎程度", "第5题干扰项；案件公开报道量不等于受欢迎度。", { examSynonyms: ["fame（知名度）", "appeal（吸引力）"] }),
  preliminary: e("adj./n.", "初步的；预备步骤", "第3题干扰项；可描述初步调查，但 draft bill 才是法案草案固定说法。", { examSynonyms: ["initial（最初的）", "provisional（临时的）"] }),
  press: e("n./v.", "新闻界；报刊", "controls over the press 和 Press freedoms 都指新闻媒体行业。", { collocations: ["controls over the press", "press freedoms"], examSynonyms: ["media（媒体）", "journalism（新闻业）"] }),
  printing: e("n./v.-ing", "印刷；打印", "第9题干扰项，只说明物理印刷，不能表示信件内容已被公开发表。", { specialForms: ["print—printed—printed—printing"], examSynonyms: ["publication（出版/发表）", "reproduction（复制印刷）"] }),
  privacy: e("n.", "隐私；隐私权", "privacy controls 指隐私保护规定；be entitled to privacy 表享有隐私权。", { collocations: ["privacy controls contained in European legislation", "be entitled to privacy"], examSynonyms: ["confidentiality（保密性）", "seclusion（独处/隔离）"] }),
  prominent: e("adj.", "重要而引人注目的", "prominent cases 指受到公众高度关注的重大案件。", { collocations: ["involved in prominent cases"], examSynonyms: ["notable（显著的）", "high-profile（高关注度的）"] }),
  propose: e("v.", "提议；建议", "propose doing 表建议采取某项措施。", { specialForms: ["propose—proposed—proposed—proposing"], collocations: ["propose making payments to witnesses illegal"], examSynonyms: ["suggest（建议）", "recommend（建议采取）"] }),
  protect: e("v.", "保护", "to protect themselves and their families 是 go to court 的目的状语。", { specialForms: ["protect—protected—protected—protecting"], collocations: ["protect themselves and their families"], examSynonyms: ["defend（防卫）", "safeguard（保护制度/权益）"] }),
  protest: e("n./v.", "抗议", "a storm of media protest 指媒体强烈抗议。", { collocations: ["a storm of media protest"], examSynonyms: ["objection（反对意见）", "demonstration（示威活动）"] }),
  prohibit: e("v.", "正式禁止", "可在本句替换 ban，prohibit payments 表由规则或法律禁止付款。", { specialForms: ["prohibit—prohibited—prohibited—prohibiting"], examSynonyms: ["ban（颁布禁令）", "forbid（禁止某人做事）"] }),
  "high-profile": e("adj.", "备受关注的；高曝光度的", "high-profile cases 可直接替换 prominent cases，更突出媒体关注度。", { specialForms: ["high-profile（复合形容词，无普通词形变化）"], examSynonyms: ["prominent（重要而显著的）", "notable（值得注意的）"] }),
  substantial: e("adj.", "实质性的；大幅的", "a substantial tightening 强调监管收紧幅度大且内容实在。", { specialForms: ["substantial—more substantial—most substantial"], examSynonyms: ["significant（重要且显著的）", "considerable（相当大的）"] }),
  provide: e("v.", "提供", "provide sufficient control 可替换 offer sufficient control，直接说明制度提供监管效果。", { specialForms: ["provide—provided—provided—providing"], examSynonyms: ["offer（提供、可供使用）", "supply（供应）"] }),
  construction: e("n.", "解释；法律条文的释义", "法律英语中 construction of a provision 指法院确定条文含义。", { specialForms: ["construction—constructions（复数）"], examSynonyms: ["interpretation（解释，通用）", "reading（对文本的理解）"] }),
  enforceable: e("adj.", "可依法执行的", "legally enforceable 强调权利或规则能够由法院强制实施。", { specialForms: ["enforce—enforced—enforced—enforcing；enforceable（形容词）"], examSynonyms: ["binding（具有约束力的）", "compulsory（强制的）"] }),
  controversy: e("n.", "争议；公开分歧", "became a controversy 强调该问题引发意见冲突。", { specialForms: ["controversy—controversies（复数）"], examSynonyms: ["issue（需要处理的问题）", "dispute（争端）"] }),
  fear: e("n./v.", "担忧；害怕", "Fears were expressed 可替换 Concerns were raised，但情绪强度更高。", { specialForms: ["fear—feared—feared—fearing；fear—fears（复数）"], examSynonyms: ["concern（正式、中性的担忧）", "anxiety（焦虑）"] }),
  publication: e("n.", "发表；公开发布", "Publication of the letter 作主语，指信件内容被公之于众。", { collocations: ["publication of the letter"], examSynonyms: ["release（发布，强调放出）", "disclosure（披露）"] }),
  publicity: e("n.", "公开报道；媒体曝光", "the amount of publicity 是受限制的庭前曝光量。", { collocations: ["control the amount of publicity"], examSynonyms: ["exposure（曝光）", "coverage（报道量）"] }),
  qualify: e("v.", "使具备资格；限定", "第15题 qualified 是干扰项；be qualified for/to do 强调资格条件。", { specialForms: ["qualify—qualified—qualified—qualifying"], examSynonyms: ["entitle（使有权）", "authorize（授权）"] }),
  rage: e("n./v.", "暴怒；肆虐", "第10题干扰项，不说 a rage of protest。", { specialForms: ["rage—raged—raged—raging"], examSynonyms: ["fury（狂怒）", "anger（愤怒）"] }),
  receive: e("v.", "收到；获得", "to have received payments 是完成不定式，表示此前已经收款。", { specialForms: ["receive—received—received—receiving"], collocations: ["be said to have received payments"], examSynonyms: ["obtain（获得）", "accept（接受）"] }),
  regulation: e("n.", "监管；规章", "self regulation 指行业或机构不靠外部法律而自行约束。", { collocations: ["self regulation"], examSynonyms: ["control（控制/监管）", "rule（规则）"] }),
  release: e("n./v.", "发布；释放", "第9题干扰项；可表示发布，但不如 publication 突出信件被正式发表。", { specialForms: ["release—released—released—releasing"], examSynonyms: ["publication（发表）", "discharge（释放）"] }),
  remark: e("v./n.", "评论；话语", "第18题干扰项，不能用于 be remarked to have done 报道结构。", { specialForms: ["remark—remarked—remarked—remarking"], examSynonyms: ["comment（评论）", "observe（评论指出）"] }),
  report: e("n./v.", "报告；报道", "committee report 是委员会形成的正式报告。", { specialForms: ["report—reports（复数）；report—reported—reported—reporting"], collocations: ["agreed with a committee report"], examSynonyms: ["account（叙述/报告）", "statement（声明）"] }),
  restraining: e("v.-ing/adj.", "限制的；克制的", "第14题干扰项，不能表示公约具有法律约束力。", { specialForms: ["restrain—restrained—restrained—restraining"], examSynonyms: ["limiting（限制的）", "controlling（控制的）"] }),
  right: e("n./adj./adv.", "权利；正确的", "Human Rights 中 rights 指法律和道德权利。", { specialForms: ["right—rights（复数）"], examSynonyms: ["entitlement（法定权利）", "liberty（自由权）"] }),
  rosemary: e("proper n.", "Rosemary（人名）", "Rosemary West 是文中重大刑事案件当事人姓名。"),
  rough: e("adj.", "粗略的；粗糙的", "第3题干扰项，rough bill 不是法案草案的正式搭配。", { specialForms: ["rough—rougher—roughest"], examSynonyms: ["approximate（大致的）", "crude（粗糙的）"] }),
  safe: e("adj.", "安全可靠的", "in safe hands 表由可靠的人妥善负责。", { specialForms: ["safe—safer—safest"], collocations: ["be in safe hands"], examSynonyms: ["secure（安全稳固的）", "protected（受保护的）"] }),
  say: e("v.", "说；据说", "were said to have received 是被动报道结构。", { specialForms: ["say—said—said—saying"], collocations: ["be said to have received payments"], examSynonyms: ["state（正式陈述）", "claim（声称）"] }),
  select: e("adj./v.", "特别选定的；挑选", "media select committee 中 select 表由议会特别设立并选定职责的。", { specialForms: ["select—selected—selected—selecting"], examSynonyms: ["choose（选择）", "special（专门的）"] }),
  self: e("n./prefix", "自身；自我", "self regulation 中 self- 表行业自我实施监管。", { collocations: ["self regulation"] }),
  sentence: e("n./v.", "刑罚；判刑；句子", "was sentenced to life sentences 中动词表示判处，名词表示刑期。", { specialForms: ["sentence—sentenced—sentenced—sentencing；sentence—sentences（复数）"], collocations: ["be sentenced to life sentences"], examSynonyms: ["condemn（判处，常指重刑）", "penalty（刑罚/处罚名词）"] }),
  set: e("v./n.", "设置；使处于", "第13题干扰项；set A binding 不是规范法律搭配。", { specialForms: ["set—set—set—setting"], examSynonyms: ["establish（设立）", "place（放置）"] }),
  side: e("v./n.", "站在……一边；一方", "第7题干扰项；side with 通常接人或阵营，不接 report 表赞同观点。", { specialForms: ["side—sided—sided—siding"], examSynonyms: ["support（支持）", "align（结盟）"] }),
  significant: e("adj.", "重大的；显著的", "a significant tightening 强调监管收紧幅度和重要性。", { examSynonyms: ["substantial（实质性的）", "notable（显著的）"] }),
  sketch: e("n./v.", "草图；概述", "第3题干扰项；a sketch of a plan 可说，但 sketch bill 不是正式法律术语。", { specialForms: ["sketch—sketched—sketched—sketching"], examSynonyms: ["outline（提纲）", "draft（草稿）"] }),
  sooner: e("adv.", "更早；宁可", "第12题 sooner than 比较时间先后，不能表达机构取舍。", { specialForms: ["soon—sooner—soonest"], examSynonyms: ["earlier（更早）", "rather（宁可，特定结构）"] }),
  state: e("v./n.", "陈述；状态", "第18题干扰项；通常说 it is stated that，而非 witnesses were stated to have done。", { specialForms: ["state—stated—stated—stating"], examSynonyms: ["declare（宣告）", "say（说）"] }),
  story: e("n.", "讲述；故事", "their stories 指证人关于案件经历的个人叙述。", { specialForms: ["story—stories（复数）"], collocations: ["tell their stories to newspapers"], examSynonyms: ["account（叙述）", "narrative（叙事）"] }),
  storm: e("n./v.", "风暴；强烈爆发", "a storm of media protest 是比喻，指媒体抗议浪潮。", { collocations: ["a storm of media protest"], examSynonyms: ["wave（浪潮）", "outcry（强烈抗议）"] }),
  strictly: e("adv.", "严格地", "strictly 修饰 control，说明限制执行力度。", { examSynonyms: ["rigorously（严格地）", "severely（严厉地）"] }),
  sufficient: e("adj.", "充分的；足够的", "sufficient control 指足以约束新闻界的监管。", { examSynonyms: ["adequate（足够且合适的）", "enough（足够的，较普通）"] }),
  sustain: e("v.", "维持；支撑", "第14题 sustaining 是干扰项；表示维持作用，不等于具有法律约束力。", { specialForms: ["sustain—sustained—sustained—sustaining"], examSynonyms: ["maintain（维持）", "support（支撑）"] }),
  tell: e("v.", "讲述；告诉", "telling their stories to newspapers 表把故事讲给报社；told 是第18题干扰项。", { specialForms: ["tell—told—told—telling"], collocations: ["tell their stories to newspapers"], examSynonyms: ["relate（讲述）", "inform（告知）"] }),
  tighten: e("v.", "收紧；加强", "tightening of legal controls 是动名词名词化，表示监管变严。", { specialForms: ["tighten—tightened—tightened—tightening"], collocations: ["a tightening of legal controls"], examSynonyms: ["strengthen（加强）", "restrict（收紧限制）"] }),
  translation: e("n.", "翻译", "第11题干扰项；涉及语言转换，而不是法律条文释义。", { examSynonyms: ["rendering（译文）", "interpretation（解释；口译）"] }),
  trial: e("n.", "审判；庭审", "the trial of Rosemary West 与 before a trial begins 均为法律审判义。", { specialForms: ["trial—trials（复数）"], collocations: ["before a trial begins"], examSynonyms: ["hearing（听证/审理）", "proceedings（诉讼程序）"] }),
  turn: e("v./n.", "使变成；转向", "第13题干扰项；turn A into B 才能表达把 A 变成 B。", { specialForms: ["turn—turned—turned—turning"], examSynonyms: ["transform（转变）", "convert（转换）"] }),
  verdict: e("n.", "裁决；判决", "guilty verdicts 是陪审团或法院作出的有罪裁决。", { specialForms: ["verdict—verdicts（复数）"], collocations: ["ensure guilty verdicts"], examSynonyms: ["judgment（判决/判断）", "decision（决定）"] }),
  witness: e("n./v.", "证人；目击", "payments to witnesses 指付给出庭或提供证词者的钱。", { specialForms: ["witness—witnesses（复数）；witness—witnessed—witnessed—witnessing"], collocations: ["payments to witnesses", "witness payments"], examSynonyms: ["observer（目击者）", "testifier（作证者）"] }),
};
