import type { ContextualSubstitution } from "./contextual-vocabulary";

export type Passage2001P2LexiconEntry = {
  partOfSpeech: string;
  contextualMeaning: string;
  use: string;
  specialForms?: string[];
  examSynonyms?: string[];
  collocations?: string[];
  otherMeanings?: string[];
  wordFamily?: string[];
  confusions?: string[];
  contextualSubstitutions?: ContextualSubstitution[];
};

const e = (
  partOfSpeech: string,
  contextualMeaning: string,
  use: string,
  extra: Partial<Passage2001P2LexiconEntry> = {},
): Passage2001P2LexiconEntry => ({ partOfSpeech, contextualMeaning, use, ...extra });

const structure = ["结构词：无普通词形变化，重点看本句中的连接、指代或限定作用"];
const regular = ["规则变化；无需要单独记忆的不规则变形"];
const f = (partOfSpeech: string, meaning: string, use: string) => e(partOfSpeech, meaning, use, {
  specialForms: structure,
  examSynonyms: ["结构词通常不能脱离完整句型直接替换"],
});

export const passage2001P2LemmaAliases: Record<string, string> = {
  "america's": "america", "britain's": "britain", "capital's": "capital", "country's": "country",
  "didn't": "do", "doesn't": "do", "isn't": "be", "we've": "we", "you're": "you",
  accepting: "accept", adopts: "adopt", americans: "american", becomes: "become", becoming: "become",
  better: "good", billion: "billion", built: "build", building: "build", commercialized: "commercialize",
  combating: "combat", connects: "connect", considered: "consider", corporations: "corporation", countries: "country",
  customers: "customer", depends: "depend", financed: "finance", fooled: "fool", forces: "force",
  foundations: "foundation", funds: "fund", germans: "german", getting: "get", governments: "government",
  had: "have", harbors: "harbor", has: "have", helping: "help", highways: "highway",
  immigrants: "immigrant", infrastructures: "infrastructure", investing: "invest", lectured: "lecture",
  left: "leave", letting: "let", lying: "lie", mentioned: "mention", needed: "need", netted: "net",
  offers: "offer", owns: "own", paid: "pay", places: "place", ports: "port", potentials: "potential",
  prejudices: "prejudice", preventing: "prevent", providing: "provide", reasons: "reason", recognizing: "recognize",
  roads: "road", states: "state", worse: "bad", years: "year",
};

export const passage2001P2FamilyAliases: Record<string, string> = {
  commercialized: "commerce", economic: "economy", electronically: "electron", financial: "finance",
  impoverished: "poor", information: "inform", investment: "invest", optimistic: "optimism",
  technological: "technology", structural: "structure", sovereignty: "sovereign", division: "divide",
};

export const passage2001P2FormPartOfSpeech: Record<string, string> = {
  "america's": "proper n. possessive（America 的所有格）", "britain's": "proper n. possessive（Britain 的所有格）",
  "capital's": "n. possessive（capital 的所有格）", "country's": "n. possessive（country 的所有格）",
  "didn't": "aux. + adv.（did not 的缩写）", "doesn't": "aux. + adv.（does not 的缩写）",
  "isn't": "v. + adv.（is not 的缩写）", "we've": "pron. + aux.（we have 的缩写）", "you're": "pron. + v.（you are 的缩写）",
  accepting: "v.-ing（accept 的动名词）", adopts: "v.（adopt 的第三人称单数）", americans: "n.（American 的复数）",
  becomes: "v.（become 的第三人称单数）", becoming: "v.-ing（become 的动名词）", better: "adj./adv.（good/well 的比较级）",
  built: "v.（build 的过去式/过去分词）", building: "v.-ing（build 的动名词/现在分词）",
  commercialized: "v./adj.（commercialize 的过去分词）", connects: "v.（connect 的第三人称单数）",
  considered: "v.（consider 的过去分词）", corporations: "n.（corporation 的复数）", countries: "n.（country 的复数）",
  customers: "n.（customer 的复数）", depends: "v.（depend 的第三人称单数）", financed: "v.（finance 的过去式）",
  fooled: "v./adj.（fool 的过去分词）", forces: "n.（force 的复数）", foundations: "n.（foundation 的复数）",
  funds: "n.（fund 的复数，资金）", germans: "n.（German 的复数）", getting: "v.-ing（get 的动名词）",
  governments: "n.（government 的复数）", had: "v.（have 的过去式）", harbors: "n.（harbor 的复数）",
  has: "v.（have 的第三人称单数）", helping: "v.-ing（help 的现在分词）", highways: "n.（highway 的复数）",
  immigrants: "n.（immigrant 的复数）", infrastructures: "n.（infrastructure 的复数/多类基础设施）",
  investing: "v.-ing（invest 的现在分词）", lectured: "v.（lecture 的过去式）", left: "v.（leave 的过去分词）",
  letting: "v.-ing（let 的动名词）", lying: "v.-ing（lie 的动名词，ie→y）", mentioned: "v.（mention 的过去式）",
  needed: "v./adj.（need 的过去分词）", netted: "v.（net 的过去分词，双写 t）", offers: "v.（offer 的第三人称单数）",
  owns: "v.（own 的第三人称单数）", paid: "v.（pay 的过去分词）", places: "n.（place 的复数）",
  ports: "n.（port 的复数）", potentials: "n.（potential 的复数）", prejudices: "n.（prejudice 的复数）",
  preventing: "v.-ing（prevent 的动名词）", providing: "v.-ing（provide 的动名词）", reasons: "n.（reason 的复数）",
  recognizing: "v.-ing（recognize 的动名词）", roads: "n.（road 的复数）", years: "n.（year 的复数）",
  combating: "v.-ing（combat 的动名词/现在分词）", impoverished: "adj./过去分词（贫困的）", technological: "adj.", structural: "adj.", electronically: "adv.",
  worse: "adj./adv.（bad/well 的比较级）",
};

export const passage2001P2Lexicon: Record<string, Passage2001P2LexiconEntry> = {
  i: f("pron.", "我", "与 My wife 并列作主语；正式英语中应说 My wife and I，而不是 Me and my wife。"),
  my: f("possessive det.", "我的", "限定 wife，说明作者与妻子共同发表演讲；my 后必须接名词。"),
  twenty: e("numeral", "二十", "twenty years ago 构成时间状语，说明演讲发生在二十年前。", { specialForms: structure, collocations: ["twenty years ago"], examSynonyms: ["two decades（两个十年，需调整结构）"] }),
  behind: f("adv./prep.", "落后；在后面", "be left behind 中作副词，与 left 构成被动短语，表示在发展竞争中掉队。"),
  why: f("conj./adv.", "为什么；……的原因", "that is why... 中引导表语从句，说明前述事实产生的结果。"),
  else: f("adv.", "其他；另外", "who else 中后置修饰疑问代词 who，表示‘还有谁’。"),
  attention: e("n.", "注意；关注", "pay attention to 的名词核心；本句作被动句主语，表示数字鸿沟正受到高度关注。", { specialForms: ["attention 通常不可数"], collocations: ["A great deal of attention", "is being paid today to"], examSynonyms: ["focus（关注焦点）", "notice（注意到）"], wordFamily: ["attentive adj. 专注的", "attentively adv. 专心地"] }),
  deal: e("n./v.", "数量；程度", "a great deal of 中与 great、of 组成数量结构，不能单独按‘交易’翻译。", { specialForms: ["deal—dealt—dealt—dealing（动词）"], collocations: ["A great deal of attention"], examSynonyms: ["amount（数量）", "quantity（量）"], otherMeanings: ["交易；协议", "处理，deal with"] }),
  pay: e("v./n.", "给予；投入（注意力）", "attention is being paid to 是 pay attention to 的被动式；不是付钱。", { specialForms: ["pay—paid—paid—paying"], collocations: ["is being paid today to"], examSynonyms: ["give（给予）", "devote（投入，常接 time/attention to）"], otherMeanings: ["支付；工资"] }),
  today: e("adv./n.", "今天；当今", "分别修饰 is being paid、does exist 和 is an electronic infrastructure，表示当前时代。", { specialForms: structure, examSynonyms: ["nowadays（如今）", "at present（目前）"] }),
  "so-called": e("adj.", "所谓的；通常所称的", "置于 digital divide 前标记术语名称。", { specialForms: regular, collocations: ["the so-called digital divide"], examSynonyms: ["what is called（所谓的）", "alleged（所谓的，常含怀疑，语气更强）"] }),
  digital: e("adj.", "数字化的；数字技术的", "digital divide 指拥有和无法获得数字信息技术之间的差距。", { specialForms: regular, collocations: ["the so-called digital divide"], examSynonyms: ["electronic（电子的，范围不同）", "computerized（计算机化的）"], wordFamily: ["digit n. 数字", "digitize v. 使数字化"] }),
  divide: e("n./v.", "鸿沟；分界", "作名词指群体在信息获取能力上的差距；narrow/widen the divide 表鸿沟缩小/扩大。", { specialForms: ["divide—divided—divided—dividing"], collocations: ["the so-called digital divide", "the digital divide will narrow", "work against the digital divide"], examSynonyms: ["gap（差距）", "division（划分/分歧）"], wordFamily: ["division n. 划分；分歧", "divisive adj. 引起分裂的"] }),
  division: e("n.", "划分；分化", "破折号后解释 digital divide：世界被分成信息富裕者与贫困者。", { specialForms: ["division—divisions（复数）"], collocations: ["the division of the world into the info (information) rich and the info poor"], examSynonyms: ["separation（分离）", "partition（分割）"], wordFamily: ["divide v./n. 分开；分界", "divisive adj. 引发分裂的"] }),
  world: e("n.", "世界；全球", "the division of the world 与 world poverty 都把论述范围扩大到全球。", { specialForms: ["world—worlds（复数，指不同世界/领域）"], examSynonyms: ["globe（全球）", "international community（国际社会）"] }),
  info: e("n. informal", "信息（information 的非正式缩写）", "info rich / info poor 中作名词定语，区分信息资源丰富者和匮乏者。", { specialForms: ["info 是 information 的非正式缩略形式，通常不可数"], examSynonyms: ["information（信息，正式完整形式）"], confusions: ["正式写作优先使用 information。"] }),
  information: e("n.", "信息；资讯", "括号中给出 info 的完整形式；通常不可数。", { specialForms: ["information 通常不可数，不能写 informations"], examSynonyms: ["data（数据）", "knowledge（知识，强调理解积累）"], wordFamily: ["inform v. 通知", "informative adj. 信息丰富的"] }),
  rich: e("adj./n.", "信息资源丰富的群体", "the info rich 中省略 people；the + 形容词结构表示一类人。", { specialForms: ["rich—richer—richest"], examSynonyms: ["wealthy（富有的）", "well-resourced（资源充足的）"], confusions: ["本句不是单纯金钱富裕，而是信息资源丰富。"] }),
  poor: e("adj./n.", "信息资源匮乏的；贫困的", "the info poor 指信息获取不足者；world poverty 和 impoverished countries 则是经济贫困语境。", { specialForms: ["poor—poorer—poorest"], examSynonyms: ["impoverished（贫困的，较正式）", "deprived（资源匮乏的）"], wordFamily: ["poverty n. 贫困", "impoverish v. 使贫困"] }),
  exist: e("v.", "存在", "does exist 用助动词强调数字鸿沟确实是当前事实。", { specialForms: ["exist—existed—existed—existing"], collocations: ["does exist today"], examSynonyms: ["remain（仍然存在）", "be present（存在）"], wordFamily: ["existence n. 存在", "existing adj. 现有的"] }),
  wife: e("n.", "妻子", "My wife and I 是并列主语。", { specialForms: ["wife—wives（复数，f→ves）"], examSynonyms: ["spouse（配偶，性别中性且正式）"] }),
  lecture: e("v./n.", "演讲；讲课", "lectured about 引出演讲主题，表示作者二十年前已警告数字鸿沟。", { specialForms: ["lecture—lectured—lectured—lecturing"], collocations: ["lectured about this looming danger"], examSynonyms: ["speak（讲话）", "give a talk（作报告）"], otherMeanings: ["训斥；说教"] }),
  looming: e("adj./v.-ing", "逼近的；隐约出现并令人担忧的", "修饰 danger，说明数字鸿沟的威胁在二十年前已经开始显现。", { specialForms: ["loom—loomed—loomed—looming"], examSynonyms: ["approaching（正在接近的）", "impending（迫近的，常指坏事）"], wordFamily: ["loom v. 逼近；赫然出现"] }),
  danger: e("n.", "危险；威胁", "this looming danger 回指 digital divide，是第 25 题判断作者态度的关键词。", { specialForms: ["danger—dangers（复数）"], examSynonyms: ["threat（威胁）", "risk（风险）"], wordFamily: ["dangerous adj. 危险的", "endanger v. 危及"] }),
  ago: f("adv.", "……以前", "time span + ago 以现在为基点向过去回溯，通常与一般过去时连用。"),
  visible: e("adj.", "明显的；可察觉的", "less visible 表当时这些积极力量还不容易被察觉，不限于肉眼可见。", { specialForms: ["visible—more visible—most visible"], collocations: ["less visible then"], examSynonyms: ["apparent（明显的）", "noticeable（容易注意到的）"], wordFamily: ["visibility n. 可见度", "invisible adj. 看不见的"] }),
  however: f("adv.", "然而；不过", "作为插入转折副词，用逗号隔开，连接‘危险已可见’与‘积极力量当时不明显’。"),
  new: e("adj.", "新的；新出现的", "与 positive 并列修饰 forces。", { specialForms: ["new—newer—newest"], examSynonyms: ["novel（新颖的）", "emerging（新兴的）"] }),
  positive: e("adj./n.", "积极的；有利的", "positive forces 指有助于抵消数字鸿沟的力量；第 25 题 D 错把 positive 修饰对象换成 divide。", { specialForms: regular, collocations: ["the new, positive forces"], examSynonyms: ["beneficial（有益的）", "favorable（有利的）"], confusions: ["positive 修饰 forces，不表示 digital divide 本身是好事。"] }),
  force: e("n./v.", "力量；推动因素", "positive forces 指技术、商业和政府动机等促使接入普及的因素。", { specialForms: ["force—forces（复数）；force—forced—forced—forcing（动词）"], examSynonyms: ["factor（因素）", "driver（驱动力）"], otherMeanings: ["武力；强迫"] }),
  work: e("v./n.", "起作用；发挥反向作用", "work against 表客观上抑制或抵消数字鸿沟。", { specialForms: ["work—worked—worked—working"], collocations: ["work against the digital divide"], examSynonyms: ["act（起作用）", "operate（运作）"] }),
  combat: e("v./n.", "对抗；遏制", "第 25 题中 combating world poverty 指借助互联网应对全球贫困。", { specialForms: ["combat—combated/combatting（英式常见）；combated/combating（美式常见）"], examSynonyms: ["fight（对抗）", "tackle（处理；应对）"], collocations: ["the most powerful tool for combating world poverty"] }),
  reason: e("n./v.", "理由；原因", "reasons to be optimistic / technological reasons to hope 分别说明乐观依据及其技术来源。", { specialForms: ["reason—reasons（复数）；reason—reasoned—reasoned（动词）"], collocations: ["reasons to be optimistic", "technological reasons to hope"], examSynonyms: ["basis（依据）", "ground（理由）"] }),
  optimistic: e("adj.", "乐观的", "be optimistic 表对数字鸿沟未来缩小持积极预期。", { specialForms: ["optimistic—more optimistic—most optimistic"], collocations: ["reasons to be optimistic"], examSynonyms: ["hopeful（抱有希望的）", "positive（积极的）"], wordFamily: ["optimism n. 乐观", "optimist n. 乐观主义者"] }),
  technological: e("adj.", "技术方面的；技术发展的", "technological reasons 指互联网技术与接入扩张为乐观判断提供依据。", { specialForms: regular, collocations: ["technological reasons to hope"], examSynonyms: ["technical（技术性的，常指具体技能细节）", "digital（数字技术的）"], wordFamily: ["technology n. 技术", "technologically adv. 技术上"] }),
  hope: e("v./n.", "希望；有理由期待", "hope 后接省略 that 的宾语从句，表示数字鸿沟缩小是仍可能实现的未来结果。", { specialForms: ["hope—hoped—hoped—hoping"], collocations: ["technological reasons to hope"], examSynonyms: ["expect（预计，确信程度更高）", "wish（愿望，结构和现实性不同）"], wordFamily: ["hopeful adj. 有希望的", "hopefully adv. 有希望地；但愿"] }),
  narrow: e("v./adj.", "缩小；变窄", "the digital divide will narrow 中作不及物动词；与 widen 构成反义并列。", { specialForms: ["narrow—narrowed—narrowed—narrowing；narrower—narrowest"], collocations: ["the digital divide will narrow", "narrow rather than widen"], examSynonyms: ["shrink（收缩）", "decrease（减少）"], confusions: ["作动词可不接宾语：the gap narrows；及物可说 narrow the gap。"] }),
  internet: e("proper n.", "互联网", "全文的核心工具；既指接入网络，也指支撑减贫和经济发展的信息基础设施。", { specialForms: ["Internet/internet（现代大小写均见，原文多用大写）"], collocations: ["spread Internet access", "the use of the Internet", "take full advantage of the Internet"], examSynonyms: ["the Net（互联网，较非正式）", "online network（在线网络，范围可能更窄）"] }),
  become: e("v.", "变得；进入某状态", "becomes commercialized 与 becoming fooled 都是 become + 表语结构。", { specialForms: ["become—became—become—becoming"], collocations: ["more and more commercialized", "becoming fooled"], examSynonyms: ["grow（逐渐变得）", "turn（变成）"] }),
  commercialize: e("v.", "使商业化", "过去分词 commercialized 作 become 的表语，表示互联网越来越按商业市场运行。", { specialForms: ["commercialize—commercialized—commercialized—commercializing"], collocations: ["more and more commercialized"], examSynonyms: ["marketize（使市场化）", "monetize（使产生收入，范围更窄）"], wordFamily: ["commerce n. 商业", "commercial adj. 商业的", "commercialization n. 商业化"] }),
  interest: e("n./v.", "利益；好处", "in the interest of business 中表示商业利益，不是兴趣或利息。", { specialForms: ["interest—interests（复数/动词三单）"], collocations: ["in the interest of business"], examSynonyms: ["benefit（利益；益处）", "advantage（有利条件）"], otherMeanings: ["兴趣", "利息；利率相关"] }),
  business: e("n.", "商业界；企业利益", "不可数泛指商业活动和企业群体；接入普及会增加潜在顾客。", { specialForms: ["business—businesses（企业复数）"], collocations: ["in the interest of business"], examSynonyms: ["commerce（商业活动）", "industry（行业/产业界）"] }),
  universalize: e("v.", "使普及；使人人可获得", "to universalize access 是形式主语 it 所代替的真正内容。", { specialForms: ["universalize—universalized—universalized—universalizing"], collocations: ["to universalize access"], examSynonyms: ["popularize（推广普及）", "extend（扩大覆盖）"], wordFamily: ["universal adj. 普遍的", "universally adv. 普遍地"] }),
  access: e("n./v.", "接入机会；使用权", "Internet access 指连接和使用互联网的机会，通常不可数。", { specialForms: ["access 通常不可数；作动词 access—accessed—accessing"], collocations: ["to universalize access", "spread Internet access"], examSynonyms: ["entry（进入）", "availability（可获得性）"], wordFamily: ["accessible adj. 可进入/可使用的", "accessibility n. 可达性"] }),
  online: e("adv./adj.", "在线；已接入网络", "people online 中后置说明 people 处于上网状态，可补 are。", { specialForms: regular, collocations: ["the more people online, the more potential customers there are"], examSynonyms: ["connected（已连接的）", "on the Internet（在网上）"] }),
  potential: e("adj./n.", "潜在的；潜力", "potential customers 是可能转化为消费者的人；enormous potential 是尚未实现的巨大能力。", { specialForms: ["potential—potentials（不同潜能/可能性）"], collocations: ["the more people online, the more potential customers there are", "has enormous potential"], examSynonyms: ["prospective（预期的，常修饰客户/学生）", "possible（可能的）"], wordFamily: ["potentially adv. 潜在地"] }),
  customer: e("n.", "顾客；客户", "互联网用户越多，企业可接触的 potential customers 越多。", { specialForms: ["customer—customers（复数）"], examSynonyms: ["consumer（消费者）", "client（客户，常接受专业服务）"] }),
  government: e("n.", "政府", "越来越多政府担心国家在互联网经济中落后，因此推广接入。", { specialForms: ["government—governments（复数）"], collocations: ["More and more governments"], examSynonyms: ["administration（政府/行政当局）", "authority（当局）"], wordFamily: ["govern v. 治理", "governance n. 治理"] }),
  afraid: e("adj.", "担心的；害怕的", "插入形容词短语说明各国政府推广互联网的原因；后接省略 that 的内容从句。", { specialForms: structure, examSynonyms: ["fearful（担忧的）", "concerned（担心的）"], collocations: ["be left behind"] }),
  country: e("n.", "国家", "their countries 指各国政府所属国家；question 28 的 country’s economy 表国家经济。", { specialForms: ["country—countries（复数，y→ies）"], examSynonyms: ["nation（国家/民族）", "state（国家，较政治法律化）"] }),
  leave: e("v.", "使落后；留下", "be left behind 是 leave sb behind 的被动式，表示国家在发展竞争中掉队。", { specialForms: ["leave—left—left—leaving"], collocations: ["be left behind"], examSynonyms: ["outpace（超过，使相对落后）", "abandon（抛下，语气不同）"] }),
  spread: e("v./n.", "推广；扩大覆盖", "spread Internet access 指让更多地区和人群接入网络。", { specialForms: ["spread—spread—spread—spreading"], collocations: ["spread Internet access"], examSynonyms: ["expand（扩大）", "extend（延伸覆盖）"] }),
  within: f("prep./adv.", "在……之内", "within + 时间段说明联网预测将在不超过该期限的范围内实现。"),
  next: e("adj./adv./n.", "接下来的；未来的", "the next decade or two 从当前向后计算一二十年。", { specialForms: structure, examSynonyms: ["following（接下来的）", "coming（即将到来的）"] }),
  decade: e("n.", "十年", "a decade or two 表十年或二十年。", { specialForms: ["decade—decades（复数）"], collocations: ["Within the next decade or two"], examSynonyms: ["ten-year period（十年期）"] }),
  billion: e("number/n.", "十亿", "one to two billion people 中 billion 前有具体数词时通常不加 -s。", { specialForms: ["two billion（数词后不加 s）；billions of（数十亿）"], examSynonyms: ["one thousand million（十亿，解释性表达）"] }),
  people: e("n. plural", "人们；人口", "one to two billion people 是被网络连接的群体；people 通常是 person 的普通复数。", { specialForms: ["person—people（普通复数）；peoples（不同民族）"], examSynonyms: ["individuals（个人）", "population（人口总量）"] }),
  planet: e("n.", "行星；本文特指地球", "on the planet 等于在全球范围内。", { specialForms: ["planet—planets（复数）"], collocations: ["on the planet"], examSynonyms: ["Earth（地球）", "globe（全球）"] }),
  net: e("v./n.", "把……连接成网络", "will be netted together 是将来时被动，net 动词化表示人被互联网连接。", { specialForms: ["net—netted—netted—netting（双写 t）"], collocations: ["will be netted together"], examSynonyms: ["connect（连接）", "network（使联网）"], otherMeanings: ["网；净得"] }),
  together: e("adv.", "一起；相互连接", "netted together 强调不同地区的人通过网络互联。", { specialForms: structure, collocations: ["will be netted together"], examSynonyms: ["jointly（共同地）", "collectively（集体地）"] }),
  result: e("n./v.", "结果", "As a result 汇总前述商业和政府动力并引出数字鸿沟缩小的预测。", { specialForms: ["result—results（复数/三单）；resulted—resulting"], collocations: ["As a result"], examSynonyms: ["consequence（后果）", "outcome（结果）"] }),
  believe: e("v.", "相信；认为", "后接省略 that 的宾语从句，表达作者现在对数字鸿沟的判断。", { specialForms: ["believe—believed—believed—believing"], examSynonyms: ["think（认为）", "hold（持有观点）"], confusions: ["believe sb 是相信某人的话；believe in sb 是信任其能力/信仰。"] }),
  rather: f("adv.", "而不是；宁可", "rather than 连接 narrow 与 widen，表示前者而非后者。"),
  widen: e("v.", "扩大；变宽", "与 narrow 构成反义并列，表示数字鸿沟扩大。", { specialForms: ["widen—widened—widened—widening"], collocations: ["narrow rather than widen"], examSynonyms: ["expand（扩大）", "broaden（拓宽）"], wordFamily: ["wide adj. 宽的", "width n. 宽度"] }),
  ahead: e("adv./adj.", "在前面；未来", "in the years ahead 表在今后的岁月中。", { specialForms: structure, collocations: ["in the years ahead"], examSynonyms: ["in the future（将来）", "forthcoming（即将到来的）"] }),
  news: e("n. uncountable", "消息；新闻", "very good news 作表语；形式有 s 但谓语通常按单数。", { specialForms: ["news 通常不可数；a piece/item of news 表一则消息"], collocations: ["very good news"], examSynonyms: ["information（消息/信息）", "report（报道）"], confusions: ["不能说 a news 或 news are。"] }),
  may: f("modal v.", "可能；可以", "may well be 中与 well 组合，表示很可能、完全有理由。"),
  well: e("adv./adj./n.", "很可能；完全有理由", "may well / might well 中强化合理性；不能单独按‘好地’翻译。", { specialForms: ["well—better—best（副词/形容词比较）"], collocations: ["may well be", "might well study"], examSynonyms: ["quite possibly（很可能）", "reasonably（有理由地）"] }),
  powerful: e("adj.", "强有力的；作用巨大的", "最高级 the most powerful 修饰减贫工具。", { specialForms: ["powerful—more powerful—most powerful"], collocations: ["the most powerful tool for combating world poverty"], examSynonyms: ["effective（有效的）", "potent（强有力的）"], wordFamily: ["power n./v. 力量；驱动", "powerfully adv. 强有力地"] }),
  tool: e("n.", "工具；手段", "互联网被比作 combating world poverty 的工具，不是具体器械。", { specialForms: ["tool—tools（复数）"], collocations: ["the most powerful tool for combating world poverty", "the only tool we have"], examSynonyms: ["means（手段，单复数同形）", "instrument（工具/手段，较正式）"] }),
  combat: e("v./n.", "抗击；与……斗争", "combating world poverty 是 for 后的动名词，combat 作及物动词直接接 poverty。", { specialForms: ["combat—combated/combatted—combated/combatted—combating/combatting"], collocations: ["the most powerful tool for combating world poverty"], examSynonyms: ["fight（抗击）", "tackle（着手解决）"], confusions: ["combat 已可直接接宾语，不必写 combat against poverty。"] }),
  poverty: e("n.", "贫困", "world poverty 是互联网可能帮助解决的全球性问题。", { specialForms: ["poverty 通常不可数"], collocations: ["the only way to defeat poverty", "the most powerful tool for combating world poverty"], examSynonyms: ["destitution（赤贫）", "deprivation（匮乏）"], wordFamily: ["poor adj. 贫困的", "impoverish v. 使贫困"] }),
  ever: f("adv.", "曾经；迄今任何时候", "最高级后的定语从句中扩大比较时间范围：我们迄今拥有过的。"),
  defeat: e("v./n.", "战胜；击败", "defeat poverty 把贫困拟作需要战胜的对象。", { specialForms: ["defeat—defeated—defeated—defeating"], collocations: ["the only way to defeat poverty"], examSynonyms: ["overcome（克服）", "combat（抗击，强调过程）"] }),
  enormous: e("adj.", "巨大的", "enormous potential 强调互联网潜力非常大，但尚未全部实现。", { specialForms: regular, collocations: ["has enormous potential"], examSynonyms: ["tremendous（巨大的）", "immense（极大的）"] }),
  advantage: e("n./v.", "优势；有利条件；利用", "take advantage of 表利用；take full advantage of 表充分利用。", { specialForms: ["advantage—advantages（复数）"], collocations: ["To take advantage of this tool", "take full advantage of the Internet"], examSynonyms: ["benefit（益处）", "merit（优点）"], confusions: ["take advantage of a person 常含‘占便宜’，对工具通常是中性‘利用’。"] }),
  impoverished: e("adj.", "贫困的；资源匮乏的", "修饰 countries，说明需要借外资建设电子基础设施的国家。", { specialForms: ["impoverish—impoverished—impoverished—impoverishing"], collocations: ["impoverished countries"], examSynonyms: ["poor（贫困的，普通词）", "underdeveloped（欠发达的，侧重发展水平）"], wordFamily: ["poor adj. 贫困的", "poverty n. 贫困"] }),
  get: e("v.", "克服（与 over 连用）", "get over prejudices 指摆脱、克服偏见；get 在其他结构中含义很多，必须整体判断。", { specialForms: ["get—got—got/gotten—getting"], collocations: ["get over their outdated anti-colonial prejudices"], examSynonyms: ["overcome（克服）", "surmount（战胜障碍，正式）"] }),
  outdated: e("adj.", "过时的；陈旧的", "修饰 anti-colonial prejudices，作者认为这些观念已不适合当前发展需求。", { specialForms: regular, collocations: ["get over their outdated anti-colonial prejudices"], examSynonyms: ["obsolete（废弃不用的）", "old-fashioned（过时的）"] }),
  "anti-colonial": e("adj.", "反殖民主义的", "修饰 prejudices，指由反殖民历史形成、把外资一概视为主权侵犯的观念。", { specialForms: ["anti- 前缀表示‘反对’"], examSynonyms: ["opposed to colonialism（反对殖民主义的）"], wordFamily: ["colonial adj. 殖民的", "colonialism n. 殖民主义"] }),
  prejudice: e("n./v.", "偏见；成见", "本句指对 foreign investment 的陈旧先入判断；第 28 题 B 错把对象换为 immigrants。", { specialForms: ["prejudice—prejudices（复数）；prejudiced—prejudicing"], collocations: ["get over their outdated anti-colonial prejudices"], examSynonyms: ["bias（偏见）", "preconception（先入之见）"], wordFamily: ["prejudiced adj. 有偏见的"] }),
  respect: e("n./v.", "方面；关于", "with respect to 是固定复合介词，表示关于外资。", { specialForms: ["respect—respects（复数/三单）；respected—respecting"], collocations: ["with respect to foreign investment"], examSynonyms: ["regarding（关于）", "concerning（关于）"], otherMeanings: ["尊重；敬意"] }),
  foreign: e("adj.", "外国的；外来的", "foreign investment/capital/corporations 分别指外资、外国资本、外国企业。", { specialForms: regular, collocations: ["foreign investment", "The more foreign capital"], examSynonyms: ["overseas（海外的）", "external（外部的）"] }),
  invest: e("v.", "投资；投入", "invest in 后接地区或项目；文中欧洲国家向美国建设投入资本。", { specialForms: ["invest—invested—invested—investing"], collocations: ["were investing in", "foreign investment"], examSynonyms: ["fund（资助）", "finance（为……提供资金）"], wordFamily: ["investment n. 投资", "investor n. 投资者"] }),
  investment: e("n.", "投资；投入的资本", "foreign investment 指来自国外、用于美国基础设施建设的资本；作不可数名词强调投资行为或总量。", { specialForms: ["investment—investments（具体投资项目或多笔投资）"], examSynonyms: ["capital（投入建设的资本）", "funding（资金支持）"], wordFamily: ["invest v. 投资", "investor n. 投资者"] }),
  invasion: e("n.", "侵犯；入侵", "an invasion of sovereignty 是抽象义，表示外资被误认为侵害国家主权。", { specialForms: ["invasion—invasions（复数）"], collocations: ["an invasion of their sovereignty"], examSynonyms: ["violation（侵犯规则/权利）", "intrusion（侵入、打扰）"], wordFamily: ["invade v. 入侵", "invasive adj. 侵入性的"] }),
  sovereignty: e("n.", "主权；自主权", "their sovereignty 指贫困国家对本国事务的最高决定权。", { specialForms: ["sovereignty 通常不可数"], collocations: ["an invasion of their sovereignty"], examSynonyms: ["autonomy（自治权）", "independence（独立）"], wordFamily: ["sovereign adj. 主权独立的"] }),
  might: f("modal v.", "不妨；可以考虑", "might well study 在劝说语境中提出委婉但有根据的建议。"),
  study: e("v./n.", "研究；考察", "study the history 不是泛泛学习，而是考察美国利用外资的历史经验。", { specialForms: ["study—studied—studied—studying"], collocations: ["might well study", "the history of infrastructure"], examSynonyms: ["examine（考察）", "investigate（调查研究）"] }),
  history: e("n.", "历史；发展历程", "the history of infrastructure 指美国基础设施建设的发展史。", { specialForms: ["history—histories（复数）"], collocations: ["the history of infrastructure"], examSynonyms: ["development（发展历程）", "record（历史记录）"] }),
  infrastructure: e("n.", "基础设施", "既包括工业时代道路港口，也包括信息时代能源和电信系统；通常作不可数集合名词。", { specialForms: ["infrastructure 通常不可数；强调不同系统类别时可用 infrastructures"], collocations: ["the history of infrastructure", "built its industrial infrastructure", "America’s Second Wave infrastructure", "an electronic infrastructure"], examSynonyms: ["basic facilities（基础设施）", "framework（基础框架，范围不同）"], wordFamily: ["structure n./v. 结构；构成", "structural adj. 结构的"] }),
  basic: e("adj./n.", "基本的；基础的", "修饰 structural foundations，解释基础设施是社会运行的基本支撑。", { specialForms: regular, collocations: ["the basic structural foundations of a society"], examSynonyms: ["fundamental（根本的）", "elementary（基础的/初级的）"] }),
  structural: e("adj.", "结构性的；构造上的", "structural foundations 指支撑社会整体运行的结构基础。", { specialForms: regular, collocations: ["the basic structural foundations of a society"], examSynonyms: ["systemic（系统性的）", "organizational（组织结构的）"], wordFamily: ["structure n./v. 结构；组织", "infrastructure n. 基础设施"] }),
  foundation: e("n.", "基础；根基", "括号中复数 foundations 解释 infrastructure 的社会支撑功能。", { specialForms: ["foundation—foundations（复数）"], collocations: ["the basic structural foundations of a society"], examSynonyms: ["basis（基础/依据）", "groundwork（基础工作）"], wordFamily: ["found v. 建立", "foundational adj. 基础性的"] }),
  society: e("n.", "社会", "a society 指一个国家或共同体的整体社会系统。", { specialForms: ["society—societies（复数）"], collocations: ["the basic structural foundations of a society"], examSynonyms: ["community（共同体）", "social system（社会体系）"] }),
  united: e("proper-name adj.", "联合的（国名组成）", "the United States 是固定国名，不单独拆译。", { specialForms: ["United States 固定专名形式"], examSynonyms: ["U.S.（美国缩写）"] }),
  state: e("n./v.", "州；国家（国名组成）", "the United States 中 States 为复数专名成分。", { specialForms: ["state—states（复数/三单）；stated—stating"], examSynonyms: ["nation（国家）", "condition（状态，另一词义）"] }),
  build: e("v./n.", "建设；建造", "build infrastructure 表建设基础设施；built 是不规则过去式/过去分词。", { specialForms: ["build—built—built—building"], collocations: ["built its industrial infrastructure", "built them", "helping you build your Third Wave infrastructure"], examSynonyms: ["construct（建造，较正式）", "establish（建立制度/体系）"] }),
  industrial: e("adj.", "工业的；工业时代的", "industrial infrastructure 对应 Second Wave 的道路、港口等工业化设施。", { specialForms: regular, collocations: ["built its industrial infrastructure"], examSynonyms: ["manufacturing（制造业的）", "commercial（商业的，范围不同）"], wordFamily: ["industry n. 工业；行业", "industrialize v. 使工业化"] }),
  capital: e("n./adj.", "资本；建设资金", "have the capital 与 foreign capital 都是经济义；第 27 题 capital’s control 则指外资控制。", { specialForms: ["capital—capitals（首都/大写字母等可数义）"], collocations: ["have the capital to do so", "The more foreign capital"], examSynonyms: ["funds（资金）", "finance（资金；融资）"], otherMeanings: ["首都", "大写字母", "资本的/主要的"] }),
  wave: e("n./v.", "浪潮；发展阶段", "Second Wave 指工业时代，Third Wave 指信息电子时代。", { specialForms: ["wave—waves（复数/三单）；waved—waving"], collocations: ["America’s Second Wave infrastructure", "helping you build your Third Wave infrastructure"], examSynonyms: ["phase（阶段）", "surge（浪潮式增长）"] }),
  including: f("prep./v.-ing", "包括", "引出道路、港湾、高速公路和港口等非穷尽例子。"),
  road: e("n.", "道路", "Second Wave infrastructure 的列举项。", { specialForms: ["road—roads（复数）"], examSynonyms: ["route（路线）", "street（街道）"] }),
  harbor: e("n./v.", "港湾；港口", "工业基础设施列举项；英式拼写为 harbour。", { specialForms: ["harbor—harbors（复数）；harbour（英式）"], examSynonyms: ["port（港口）", "haven（避风港）"] }),
  highway: e("n.", "高速公路；公路干线", "工业基础设施列举项。", { specialForms: ["highway—highways（复数）"], examSynonyms: ["motorway（英式高速公路）", "expressway（高速公路）"] }),
  port: e("n.", "港口", "工业基础设施列举项，负责水运和贸易。", { specialForms: ["port—ports（复数）"], examSynonyms: ["harbor（港湾/港口）", "dock（码头）"] }),
  finance: e("v./n.", "为……提供资金；融资", "They financed them 中作动词，主语是欧洲投资者，them 指美国基础设施。", { specialForms: ["finance—financed—financed—financing"], collocations: ["financed them"], examSynonyms: ["fund（资助）", "back（为……提供资金支持）"], wordFamily: ["financial adj. 金融的", "financing n. 融资"] }),
  fund: e("n./v.", "资金；为……提供资金", "第 17 句的替换表达 funds 强调可直接使用的款项；第 20 句 funded them 则是及物动词，表示为这些基础设施出资。", { specialForms: ["fund—funds（复数/三单）—funded—funding"], collocations: ["have the funds to do so", "fund infrastructure"], examSynonyms: ["capital（用于投资建设的资本）", "finance（提供或筹措资金）"], confusions: ["capital 更强调可投入并产生长期回报的资本；funds 常指眼下可动用的款项。"] }),
  english: e("n./adj.", "英国人；英格兰人", "The English 是 the + 国籍形容词，表示英国人这一群体。", { specialForms: ["the English 群体形式不再加 -s"], examSynonyms: ["British people（英国人，范围更准确）"] }),
  german: e("n./adj.", "德国人；德国的", "the Germans 是可数国籍名词复数。", { specialForms: ["German—Germans（复数）"], examSynonyms: ["German people（德国人）"] }),
  dutch: e("n./adj.", "荷兰人；荷兰的", "the Dutch 表荷兰人群体，形式不加 -s。", { specialForms: ["the Dutch 群体形式不加 -s"], examSynonyms: ["people from the Netherlands（荷兰人）"] }),
  french: e("n./adj.", "法国人；法国的", "the French 表法国人群体，形式不加 -s。", { specialForms: ["the French 群体形式不加 -s"], examSynonyms: ["French people（法国人）"] }),
  britain: e("proper n.", "英国", "Britain’s former colony 指曾为英国殖民地的美国。", { specialForms: ["Britain—Britain’s（所有格）"], examSynonyms: ["the United Kingdom（英国正式国名，范围表述有细微差别）"] }),
  former: e("adj./n.", "从前的；以前的", "former colony 指过去是殖民地、现在已独立的美国。", { specialForms: regular, collocations: ["Britain’s former colony"], examSynonyms: ["previous（以前的）", "one-time（曾经的）"], confusions: ["the former 还可表示前面两者中的前者。"] }),
  colony: e("n.", "殖民地", "Britain’s former colony 在历史语境指美国。", { specialForms: ["colony—colonies（复数，y→ies）"], collocations: ["Britain’s former colony"], examSynonyms: ["dependency（属地）", "territory（领地）"], wordFamily: ["colonial adj. 殖民的", "colonialism n. 殖民主义"] }),
  immigrant: e("n./adj.", "移民；移入的", "Immigrant Americans 指移民到美国并参与建设的人。", { specialForms: ["immigrant—immigrants（复数）"], collocations: ["Immigrant Americans"], examSynonyms: ["migrant（迁移者，范围更广）", "newcomer（新来者）"], confusions: ["immigrant 强调迁入；emigrant 强调从原国家迁出。"] }),
  american: e("n./adj.", "美国人；美国的", "The Americans 是上一设问 who 的答案，强调最终所有权归美国人。", { specialForms: ["American—Americans（复数）"], collocations: ["The Americans", "Immigrant Americans"], examSynonyms: ["U.S. citizen（美国公民）"] }),
  guess: e("v./n.", "猜；推测", "祈使句 Guess 后接 who 宾语从句，构成设问。", { specialForms: ["guess—guessed—guessed—guessing"], collocations: ["Guess who owns them now"], examSynonyms: ["suppose（猜想）", "estimate（估计）"] }),
  own: e("v./adj./pron.", "拥有；归……所有", "who owns them now 询问基础设施最终所有权。", { specialForms: ["own—owned—owned—owning"], collocations: ["Guess who owns them now"], examSynonyms: ["possess（拥有，较正式）", "hold（持有）"], wordFamily: ["owner n. 所有者", "ownership n. 所有权"] }),
  same: e("adj./pron.", "相同的；同样的规律", "the same thing 回指外资建设但最终由本国拥有这一经验。", { specialForms: structure, collocations: ["the same thing would be true"], examSynonyms: ["identical（完全相同的）", "similar（相似的，不是完全相同）"], confusions: ["same 通常与 the 连用；similar 常接 to。"] }),
  true: e("adj.", "成立的；适用的", "would be true 表同一规律在其他国家也成立，不是‘真实故事’。", { specialForms: ["true—truer—truest；truly adv."], collocations: ["the same thing would be true"], examSynonyms: ["valid（成立的）", "applicable（适用的）"] }),
  place: e("n./v.", "地方；国家或地区", "places like Brazil 把 Brazil 作为同类国家的例子。", { specialForms: ["place—places（复数/三单）；placed—placing"], collocations: ["in places like Brazil"], examSynonyms: ["location（地点）", "country/region（国家/地区，视语境）"] }),
  brazil: e("proper n.", "巴西", "作为可借鉴美国外资经验的发展中大国例子。", { specialForms: ["Brazil 专有名词"], examSynonyms: ["the Brazilian economy（巴西经济，按语境改写）"] }),
  anywhere: e("adv./pron.", "任何地方", "anywhere else 把适用范围从巴西扩大到其他任何地方。", { specialForms: structure, collocations: ["anywhere else for that matter"], examSynonyms: ["in any other place（在任何其他地方）"] }),
  matter: e("n./v.", "事情；用于补充强调", "for that matter 是固定插入语，表示就此而言、甚至可以说。", { specialForms: ["matter—matters（复数/三单）；mattered—mattering"], collocations: ["anywhere else for that matter"], examSynonyms: ["in fact（事实上，语气不同）", "indeed（甚至/确实）"] }),
  help: e("v./n.", "帮助；促成", "foreign capital helping you build... 中资本是 helping 的逻辑主语；help 后 build 前可省略 to。", { specialForms: ["help—helped—helped—helping"], collocations: ["helping you build your Third Wave infrastructure"], examSynonyms: ["assist（协助）", "facilitate（促进，使更容易）"] }),
  third: e("ordinal number/adj.", "第三；第三次浪潮的", "Third Wave 指电子信息时代，与工业时代 Second Wave 对应。", { specialForms: ["three—third（基数词—序数词）"], examSynonyms: ["3rd（缩写形式）"] }),
  electronic: e("adj.", "电子的；信息技术的", "electronic infrastructure 指当今网络、电信等第三次浪潮基础设施。", { specialForms: regular, collocations: ["an electronic infrastructure"], examSynonyms: ["digital（数字化的）", "computerized（计算机化的）"], confusions: ["electric 侧重用电的；electronic 侧重电子元件与信息系统。"], wordFamily: ["electron n. 电子", "electronically adv. 电子方式地"] }),
  writer: e("n.", "作者；本文作者", "题干 the writer’s purpose 指作者写作本文的目的，即说明互联网及外资对发展中国家的积极作用。", { specialForms: ["writer—writers（复数）"], examSynonyms: ["author（作者，较正式）", "essayist（散文作者，范围更窄）"] }),
  "well-developed": e("adj.", "发展完善的；高度发达的", "题目把 technological infrastructure 称为 well-developed，表示技术基础设施已经建设得较成熟。", { specialForms: ["复合形容词；well + 过去分词，置于名词前通常保留连字符"], examSynonyms: ["advanced（先进的）", "mature（成熟完善的）"], confusions: ["well-developed 强调发展程度；developing 表‘发展中的’，意义不同。"] }),
  good: e("adj./n.", "境况更好；经济更富裕", "better off 中 better 是 good/well 的比较级，整个短语表示经济或生活状况更好。", { specialForms: ["good/well—better—best"], collocations: ["the better off you’re going to be"], examSynonyms: ["prosperous（繁荣的）", "wealthy（富有的）"], confusions: ["better off 是固定短语，off 不单独译。"] }),
  mean: e("v./adj./n.", "意味着", "doesn't mean 与 does mean 构成对照；后接动名词表示一种做法所包含的后果或要求。", { specialForms: ["mean—meant—meant—meaning"], collocations: ["doesn't mean lying down", "does mean recognizing"], examSynonyms: ["imply（意味着）", "involve（涉及、需要）"], otherMeanings: ["打算，mean to do", "吝啬的；平均数"] }),
  lie: e("v./n.", "躺下；消极不作为", "lying down 在语境中比喻放弃主动、任人摆布。", { specialForms: ["lie（躺）—lay—lain—lying；lie（说谎）—lied—lied"], collocations: ["doesn't mean lying down"], examSynonyms: ["submit passively（消极屈从）", "give in（屈服）"], confusions: ["lie‘躺’与 lay‘放置’的变化不同。"] }),
  fool: e("v./n.", "欺骗；使受骗", "becoming fooled 表变成受骗状态。", { specialForms: ["fool—fooled—fooled—fooling"], collocations: ["becoming fooled"], examSynonyms: ["deceive（欺骗）", "mislead（误导）"] }),
  let: e("v./n.", "让；放任", "let foreign corporations run... 使用 let + 宾语 + 动词原形的使役结构。", { specialForms: ["let—let—let—letting（双写 t）"], collocations: ["letting foreign corporations run uncontrolled"], examSynonyms: ["allow（允许，接 to do）", "permit（准许，较正式）"], confusions: ["let sb do 不带 to；allow sb to do 必须带 to。"] }),
  corporation: e("n.", "公司；大型企业", "foreign corporations 指参与基础设施建设的外国企业。", { specialForms: ["corporation—corporations（复数）"], collocations: ["letting foreign corporations run uncontrolled"], examSynonyms: ["company（公司）", "enterprise（企业）"], wordFamily: ["corporate adj. 公司的"] }),
  run: e("v./n.", "经营；运作", "foreign corporations run uncontrolled 中 run 不及物，表示企业运作；uncontrolled 是状态补足。", { specialForms: ["run—ran—run—running（双写 n）"], collocations: ["letting foreign corporations run uncontrolled"], examSynonyms: ["operate（运营）", "function（运转）"], otherMeanings: ["跑；延伸；竞选"] }),
  uncontrolled: e("adj.", "不受控制的；缺乏监管的", "作 run 的主语补足语，说明外国公司处于无人监管的经营状态。", { specialForms: regular, collocations: ["letting foreign corporations run uncontrolled"], examSynonyms: ["unregulated（未受监管的）", "unchecked（未受约束的）"], wordFamily: ["control v./n. 控制", "controlled adj. 受控的"] }),
  recognize: e("v.", "认识到；承认", "recognizing 后接 how 从句，表示需要承认外企在基础设施建设中的重要性。", { specialForms: ["recognize—recognized—recognized—recognizing"], collocations: ["does mean recognizing", "how important they can be"], examSynonyms: ["acknowledge（承认）", "realize（意识到）"], wordFamily: ["recognition n. 认识；承认"] }),
  important: e("adj.", "重要的；作用重大的", "how important they can be 强调外国公司可能发挥的作用程度。", { specialForms: ["important—more important—most important"], collocations: ["how important they can be"], examSynonyms: ["crucial（关键的）", "significant（重要的）"], wordFamily: ["importance n. 重要性", "importantly adv. 重要地"] }),
  energy: e("n.", "能源；能量", "energy infrastructures 指电力等支撑互联网运行的能源系统。", { specialForms: ["energy—energies（不同能量类型时复数）"], collocations: ["in building the energy and telecom infrastructures"], examSynonyms: ["power（能源/电力）", "fuel（燃料）"] }),
  telecom: e("n./adj.", "电信；电信的", "telecom infrastructures 指通信网络和设施；telecom 是 telecommunications 的缩写。", { specialForms: ["telecom/telecommunications"], collocations: ["in building the energy and telecom infrastructures"], examSynonyms: ["telecommunications（电信）", "communications network（通信网络）"] }),
  need: e("v./n.", "需要；必需", "needed to take full advantage... 是过去分词后置修饰 infrastructures。", { specialForms: ["need—needed—needed—needing"], collocations: ["needed to take full advantage of the Internet"], examSynonyms: ["require（需要）", "be necessary（是必需的）"] }),

  guard: e("v./n.", "警惕；防范", "第 25 题 guard against 与 looming danger 对应，表示全世界必须防范数字鸿沟。", { specialForms: ["guard—guarded—guarded—guarding"], examSynonyms: ["protect against（防范）", "watch out for（警惕）"] }),
  responsible: e("adj.", "负有责任的；造成……的", "第 25 题 B 声称富国应为数字鸿沟负责，但原文没有说明责任归属。", { specialForms: regular, examSynonyms: ["accountable（应负责的）", "liable（负法律责任的）"], wordFamily: ["responsibility n. 责任"] }),
  attach: e("v.", "重视（attach importance to）", "题干 attach importance to the Internet 表政府重视互联网。", { specialForms: ["attach—attached—attached—attaching"], examSynonyms: ["value（重视）", "emphasize（强调）"], collocations: ["attach importance to"] }),
  importance: e("n.", "重要性", "attach importance to 是固定搭配，表示重视。", { specialForms: ["importance 通常不可数"], examSynonyms: ["significance（重要性）", "value（价值）"], wordFamily: ["important adj. 重要的"] }),
  economic: e("adj.", "经济上的；有经济价值的", "offers economic potentials 表互联网提供商业和经济发展机会。", { specialForms: regular, examSynonyms: ["financial（金融/财务的）", "commercial（商业的）"], wordFamily: ["economy n. 经济", "economically adv. 经济上"] }),
  offer: e("v./n.", "提供；带来", "第 26 题 A 指互联网带来经济潜力，与 potential customers 和 business interest 对应。", { specialForms: ["offer—offered—offered—offering"], examSynonyms: ["provide（提供）", "present（带来/呈现）"] }),
  bring: e("v.", "带来", "第 26 题 B 声称互联网能带来外资，但原文逻辑是外资帮助建设互联网基础设施。", { specialForms: ["bring—brought—brought—bringing"], examSynonyms: ["cause（带来结果）", "attract（吸引）"] }),
  soon: f("adv.", "很快；不久", "第 26 题 C 用 soon 夸大了作者只谈潜力的谨慎判断。"),
  wipe: e("v./n.", "擦去；彻底消除", "wipe out world poverty 表彻底消灭贫困，语气远强于原文 combat 和 potential。", { specialForms: ["wipe—wiped—wiped—wiping"], examSynonyms: ["eliminate（消除）", "eradicate（根除）"], collocations: ["wipe out"] }),
  connect: e("v.", "连接；使互联", "第 26 题 D 描述互联网功能，但不是政府重视它的直接商业原因。", { specialForms: ["connect—connected—connected—connecting"], examSynonyms: ["link（连接）", "join（连接）"], wordFamily: ["connection n. 连接", "connected adj. 相连的"] }),
  mention: e("v./n.", "提到；提及", "第 27 题问作者提到美国案例的论证目的。", { specialForms: ["mention—mentioned—mentioned—mentioning"], examSynonyms: ["refer to（提到）", "cite（引用）"] }),
  case: e("n.", "案例；事例", "the case of the United States 指美国利用外资建设基础设施的历史例证。", { specialForms: ["case—cases（复数）"], examSynonyms: ["example（例子）", "instance（事例）"], otherMeanings: ["案件；情况；箱子"] }),
  justify: e("v.", "证明……合理；为……提供依据", "题干问美国例子用来证明哪项政策合理。", { specialForms: ["justify—justified—justified—justifying"], examSynonyms: ["support（支持论点）", "validate（证实有效）"], wordFamily: ["justification n. 正当理由"] }),
  policy: e("n.", "政策；方针", "第 27 题正确政策是接受和利用外国投资。", { specialForms: ["policy—policies（复数）"], examSynonyms: ["strategy（策略）", "course（方针/路线）"] }),
  provide: e("v.", "提供", "providing financial support overseas 是第 27 题方向相反的干扰项。", { specialForms: ["provide—provided—provided—providing"], examSynonyms: ["offer（提供）", "supply（供应）"] }),
  financial: e("adj.", "财政的；资金方面的", "financial support 指资金援助。", { specialForms: regular, examSynonyms: ["monetary（货币/资金的）", "fiscal（财政的）"], wordFamily: ["finance n./v. 金融；提供资金", "financing n. 融资"] }),
  support: e("n./v.", "资金支持；援助", "第 27 题 A 中提供海外资金支持；本文历史事实是外国资本流入美国。", { specialForms: ["support—supported—supported—supporting"], examSynonyms: ["assistance（援助）", "backing（支持）"] }),
  overseas: e("adv./adj.", "向海外；海外的", "providing support overseas 表向国外提供援助，方向与原文不符。", { specialForms: structure, examSynonyms: ["abroad（在/到国外）", "foreign（外国的，作定语）"] }),
  prevent: e("v.", "防止；阻止", "preventing foreign capital’s control 是第 27 题干扰项，只取末段监管限制而非美国案例主旨。", { specialForms: ["prevent—prevented—prevented—preventing"], examSynonyms: ["stop（阻止）", "avoid（避免）"], collocations: ["prevent A from doing"] }),
  control: e("n./v.", "控制；监管", "文章说不能放任外企失控，但没有把控制程度说成经济发展的决定因素。", { specialForms: ["control—controlled—controlled—controlling（双写 l）"], examSynonyms: ["regulation（监管）", "command（控制权）"], wordFamily: ["controlled adj. 受控的", "uncontrolled adj. 不受控的"] }),
  accept: e("v.", "接受；接纳", "accepting foreign investment 是美国案例要证明合理的政策。", { specialForms: ["accept—accepted—accepted—accepting"], examSynonyms: ["receive（接收）", "welcome（欢迎接受）"], wordFamily: ["acceptance n. 接受", "acceptable adj. 可接受的"] }),
  seem: e("v.", "似乎；看起来", "It seems that... 引出第 28 题需要从文章推断的结论。", { specialForms: ["seem—seemed—seemed—seeming"], examSynonyms: ["appear（似乎）", "look（看起来）"] }),
  economy: e("n.", "经济；经济状况", "a country’s economy 与 better off 对应，题目问经济发展依赖什么。", { specialForms: ["economy—economies（复数）"], examSynonyms: ["economic system（经济体系）", "national economy（国民经济）"], wordFamily: ["economic adj. 经济的", "economically adv. 经济上"] }),
  depend: e("v.", "取决于；依赖", "depends much on 后接决定国家经济状况的因素。", { specialForms: ["depend—depended—depended—depending"], examSynonyms: ["rely on（依赖）", "hinge on（取决于）"], collocations: ["depend on"] }),
  electronically: e("adv.", "在电子信息技术方面", "how well-developed it is electronically 指一国电子基础设施的发展程度。", { specialForms: regular, examSynonyms: ["digitally（数字化地）", "technologically（技术上）"], wordFamily: ["electronic adj. 电子的", "electron n. 电子"] }),
  prejudiced: e("adj.", "有偏见的", "第 28 题 B 把原文针对外资的偏见偷换成对移民的偏见。", { specialForms: regular, examSynonyms: ["biased（有偏见的）", "intolerant（不宽容的）"], wordFamily: ["prejudice n./v. 偏见；使有偏见"] }),
  adopt: e("v.", "采用；采纳", "第 28 题 C 声称照搬美国工业模式，但作者只借美国证明利用外资的原则。", { specialForms: ["adopt—adopted—adopted—adopting"], examSynonyms: ["take up（采用）", "embrace（接受采纳）"], otherMeanings: ["收养"] }),
  pattern: e("n.", "模式；范式", "America’s industrial pattern 指美国工业建设模式，是题目设置的过度概括。", { specialForms: ["pattern—patterns（复数）"], examSynonyms: ["model（模式）", "framework（框架）"] }),

  focus: e("v./n.", "集中关注；焦点", "可替换 pay attention 的语义核心，强调把注意力集中到数字鸿沟。", { specialForms: ["focus—focused/focussed—focused/focussed—focusing/focussing"], examSynonyms: ["concentrate（集中）", "attention（关注）"] }),
  remain: e("v.", "仍然存在；保持", "可改写 that divide remains today，强调从过去持续到现在。", { specialForms: ["remain—remained—remained—remaining"], examSynonyms: ["continue（继续）", "persist（持续存在）"] }),
  speak: e("v.", "讲话；谈论", "spoke about 可替换 lectured about，但正式演讲色彩较弱。", { specialForms: ["speak—spoke—spoken—speaking"], examSynonyms: ["lecture（演讲/讲课）", "talk（谈论）"] }),
  apparent: e("adj.", "明显的；显而易见的", "less apparent 可替换 less visible，强调不容易察觉。", { specialForms: regular, examSynonyms: ["visible（明显的）", "evident（显然的）"] }),
  hopeful: e("adj.", "抱有希望的；有希望的", "be hopeful 可替换 be optimistic，但更强调希望，后者更强调乐观判断。", { specialForms: ["hopeful—more hopeful—most hopeful"], examSynonyms: ["optimistic（乐观的）", "promising（有希望的）"] }),
  shrink: e("v.", "缩小；收缩", "可替换 narrow 描述数字鸿沟变小，语气更形象。", { specialForms: ["shrink—shrank/shrunk—shrunk—shrinking"], examSynonyms: ["narrow（缩小）", "contract（收缩）"] }),
  benefit: e("v./n.", "使受益；利益", "it benefits business to... 可改写 in the interest of business，但句法需要调整。", { specialForms: ["benefit—benefited/benefitted—benefiting/benefitting"], examSynonyms: ["advantage（使有利）", "help（帮助）"] }),
  expand: e("v.", "扩大；扩展", "expand Internet access 可替换 spread access，语气更侧重覆盖范围。", { specialForms: ["expand—expanded—expanded—expanding"], examSynonyms: ["extend（延伸）", "spread（推广）"] }),
  effective: e("adj.", "有效的；产生预期效果的", "most effective tool 可替换 most powerful tool，但侧重效果而非力量。", { specialForms: ["effective—more effective—most effective"], examSynonyms: ["powerful（强有力的）", "efficient（高效的，强调投入产出）"] }),
  means: e("n. 单复数同形", "手段；方法", "可替换 tool 的抽象义；a means 是一种手段。", { specialForms: ["means—means（单复数同形）"], examSynonyms: ["method（方法）", "tool（工具/手段）"] }),
  tremendous: e("adj.", "巨大的；惊人的", "tremendous potential 可替换 enormous potential，感情色彩稍强。", { specialForms: regular, examSynonyms: ["enormous（巨大的）", "immense（极大的）"] }),
  examine: e("v.", "考察；仔细研究", "examine the history 可替换 study，强调仔细分析证据。", { specialForms: ["examine—examined—examined—examining"], examSynonyms: ["study（研究）", "inspect（检查）"] }),
  comprise: e("v.", "包括；由……组成", "可把 including 列举改写为 which comprised...，但需要完整从句结构调整。", { specialForms: ["comprise—comprised—comprised—comprising"], examSynonyms: ["include（包括）", "consist of（由……组成）"] }),
  construct: e("v.", "建造；构建", "可替换 build，语气更正式。", { specialForms: ["construct—constructed—constructed—constructing"], examSynonyms: ["build（建造）", "erect（建起）"] }),
  possess: e("v.", "拥有；持有", "可替换 own 询问基础设施所有权，语气更正式。", { specialForms: ["possess—possessed—possessed—possessing"], examSynonyms: ["own（拥有）", "hold（持有）"] }),
  citizen: e("n.", "公民", "U.S. citizens 可作为 The Americans 的明确改写。", { specialForms: ["citizen—citizens（复数）"], examSynonyms: ["national（国民）", "resident（居民，不一定有国籍）"] }),
  apply: e("v.", "适用；应用", "the same thing would apply 可替换 would be true，强调规律适用。", { specialForms: ["apply—applied—applied—applying"], examSynonyms: ["hold true（成立）", "be relevant（适用）"] }),
  prosperous: e("adj.", "繁荣的；富裕的", "more prosperous 可替换 better off，但更侧重经济繁荣。", { specialForms: ["prosperous—more prosperous—most prosperous"], examSynonyms: ["wealthy（富裕的）", "better-off（境况较好的）"], wordFamily: ["prosper v. 繁荣", "prosperity n. 繁荣"] }),
  imply: e("v.", "意味着；暗示", "does imply 可替换 does mean，语气更强调由事实推得含义。", { specialForms: ["imply—implied—implied—implying"], examSynonyms: ["mean（意味着）", "suggest（暗示）"] }),
  crucial: e("adj.", "关键的；至关重要的", "how crucial they can be 可替换 how important，语气更强。", { specialForms: regular, examSynonyms: ["important（重要的）", "vital（极其重要的）"] }),
};
