import type { Question, SentenceAnalysis } from "./data";

export const passage2001P2Sentences: SentenceAnalysis[] = [
  {
    id: "2001-p2-s1", number: 1,
    text: "A great deal of attention is being paid today to the so-called digital divide—the division of the world into the info (information) rich and the info poor.",
    chunks: [
      { text: "A great deal of attention", role: "subject" },
      { text: " is being paid", role: "predicate" },
      { text: " today", role: "modifier" },
      { text: " to the so-called digital divide", role: "modifier" },
      { text: "—the division of the world into the info (information) rich and the info poor.", role: "modifier" },
    ],
    trunk: "A great deal of attention is being paid to the so-called digital divide.",
    layers: [
      { label: "先抓被动主干", text: "A great deal of attention is being paid to...：大量注意力正被投入……，也就是‘人们正高度关注……’" },
      { label: "关注对象", text: "the so-called digital divide：所谓的数字鸿沟" },
      { label: "破折号解释", text: "the division of the world into...：把世界分成信息富裕者和信息贫困者的差距" },
    ],
    grammar: [
      "is being paid 是现在进行时的被动语态，强调‘目前正在受到关注’；pay attention to 的 to 是介词。",
      "a great deal of 只能直接修饰不可数名词，attention 在此不可数。",
      "破折号后的名词短语与 digital divide 构成同位解释，不是另一个完整句子。",
      "the rich / the poor 是‘the + 形容词’表示一类人；info rich 与 info poor 在此分别指信息资源丰富者和匮乏者。",
    ],
    beginnerSyntax: {
      components: [
        { text: "A great deal of attention", form: "数量结构 + 不可数名词", function: "主语", modifies: "是 is being paid 的承受者", explanation: "先看中心词 attention；a great deal of 只说明注意力很多，整组回答‘什么正被投入’。" },
        { text: "is being paid", form: "现在进行时被动语态", function: "谓语", modifies: "说明 attention 当前正受到怎样的处理", explanation: "拆成 is + being + paid；主动表达是 people are paying attention to...。" },
        { text: "today", form: "时间副词", function: "时间状语", modifies: "修饰 is being paid", explanation: "说明这种关注发生在当下，不要把 today 并入后面的名词。" },
        { text: "to the so-called digital divide", form: "to + 名词短语", function: "对象状语", modifies: "与 paid 组成 pay attention to", explanation: "回答‘注意力投向什么’；so-called 表‘所谓的’。" },
        { text: "the division of the world into the info (information) rich and the info poor", form: "破折号后的同位名词短语", function: "同位解释", modifies: "解释 digital divide 的具体含义", explanation: "没有新的谓语，整组按‘也就是……’接在数字鸿沟后理解。" },
      ], clauses: [],
    },
    literal: "今天，大量注意力正被给予所谓的数字鸿沟——即世界被分成信息富裕者和信息贫困者的状况。",
    natural: "如今，人们高度关注所谓的‘数字鸿沟’，也就是世界上信息资源丰富群体与匮乏群体之间的差距。",
    logic: "开篇界定全文核心概念，并说明这一问题已经受到广泛关注。",
    phrases: ["A great deal of attention", "is being paid today to", "the so-called digital divide", "the division of the world into the info (information) rich and the info poor"],
  },
  {
    id: "2001-p2-s2", number: 2,
    text: "And that divide does exist today.",
    chunks: [
      { text: "And", role: "connector" }, { text: " that divide", role: "subject" },
      { text: " does exist", role: "predicate" }, { text: " today.", role: "modifier" },
    ],
    trunk: "that divide does exist today.",
    layers: [
      { label: "承接确认", text: "And that divide：而且上述数字鸿沟" },
      { label: "强调谓语", text: "does exist today：今天确实存在" },
    ],
    grammar: ["肯定句中的 does 用来强调 exist；加 does 后实义动词必须用原形 exist。", "that divide 回指上一句的 digital divide。"],
    beginnerSyntax: { components: [
      { text: "And", form: "并列连词", function: "承接连接语", modifies: "连接首句定义与本句确认", explanation: "表示作者继续确认前面提出的问题，而不是转折。" },
      { text: "that divide", form: "指示限定词 + 名词", function: "主语", modifies: "是 exist 所描述的对象", explanation: "that 指上一句刚解释过的数字鸿沟。" },
      { text: "does exist", form: "助动词强调 + 动词原形", function: "谓语", modifies: "强调 divide 的确存在", explanation: "普通形式是 exists；does 把语气加强为‘确实存在’。" },
      { text: "today", form: "时间副词", function: "时间状语", modifies: "修饰 does exist", explanation: "限定为当前现实。" },
    ], clauses: [] },
    literal: "而且，那种鸿沟今天确实存在。", natural: "这种数字鸿沟在今天的确存在。",
    logic: "确认问题不是假设，为下一步讨论其危险和改善力量建立事实前提。",
    phrases: ["does exist today"],
  },
  {
    id: "2001-p2-s3", number: 3,
    text: "My wife and I lectured about this looming danger twenty years ago.",
    chunks: [
      { text: "My wife and I", role: "subject" }, { text: " lectured", role: "predicate" },
      { text: " about this looming danger", role: "modifier" }, { text: " twenty years ago.", role: "modifier" },
    ],
    trunk: "My wife and I lectured about this looming danger.",
    layers: [
      { label: "主干", text: "My wife and I lectured：我和妻子曾发表演讲" },
      { label: "主题与时间", text: "about this looming danger / twenty years ago：主题是这个逼近的危险，时间是二十年前" },
    ],
    grammar: ["lecture about/on sth 表‘就某主题讲课或演讲’。", "looming 是现在分词形容词，表示某种危险正在逼近、逐渐显现。", "twenty years ago 是确定的过去时间，谓语用一般过去时 lectured。"],
    beginnerSyntax: { components: [
      { text: "My wife and I", form: "两个名词/代词并列", function: "主语", modifies: "共同发出 lectured 的动作", explanation: "and 连接两个人，所以主语是复数；礼貌顺序通常把 I 放在后面。" },
      { text: "lectured", form: "一般过去时动词", function: "谓语", modifies: "说明二十年前做过的动作", explanation: "不是单纯‘读’，而是‘讲课、发表演讲’。" },
      { text: "about this looming danger", form: "about + 名词短语", function: "主题状语", modifies: "修饰 lectured", explanation: "说明演讲谈论什么；this danger 回指数字鸿沟。" },
      { text: "twenty years ago", form: "时间长度 + ago", function: "时间状语", modifies: "修饰 lectured", explanation: "ago 从说话的现在向前推二十年，因此与过去时连用。" },
    ], clauses: [] },
    literal: "我和我的妻子二十年前就这个正在逼近的危险作过演讲。", natural: "早在二十年前，我和妻子便曾演讲提醒人们警惕这一日益逼近的危险。",
    logic: "以作者过去的预警说明数字鸿沟并非新问题，同时为下句‘当时未看清的积极力量’作时间对照。",
    phrases: ["lectured about this looming danger", "twenty years ago"],
  },
  {
    id: "2001-p2-s4", number: 4,
    text: "What was less visible then, however, were the new, positive forces that work against the digital divide.",
    chunks: [
      { text: "What was less visible then", role: "subject" }, { text: ", however, ", role: "connector" },
      { text: "were", role: "predicate" }, { text: " the new, positive forces", role: "object" },
      { text: " that work against the digital divide.", role: "modifier" },
    ],
    trunk: "What was less visible then were the new, positive forces.",
    layers: [
      { label: "先看倒装式系表", text: "What was less visible then were the new, positive forces：当时不太明显的是一些新的积极力量" },
      { label: "转折", text: "however：与‘危险早已可见’相反，这些积极力量当时还看不清" },
      { label: "力量的作用", text: "that work against the digital divide：这些力量会抵消、缩小数字鸿沟" },
    ],
    grammar: [
      "What was less visible then 是融合型关系从句，整体作主语；what 相当于 the thing(s) that。",
      "表语中心 forces 为复数，所以系动词使用 were；语序看似倒装，理解时可还原为 The new forces were less visible then。",
      "that 引导限制性定语从句，修饰 forces；work against 表‘起反作用、抵制’。",
    ],
    beginnerSyntax: { components: [
      { text: "What was less visible then", form: "What 引导的融合型关系从句", function: "主语从句", modifies: "与 were 构成主句主干", explanation: "先整体替换成‘当时不太明显的事物’，不要把 what 只译成疑问词‘什么’。" },
      { text: "however", form: "插入副词", function: "转折状语", modifies: "修饰整句判断", explanation: "两个逗号夹住，可先拿掉读主干，再补成‘然而’。" },
      { text: "were", form: "系动词过去式复数", function: "主句谓语", modifies: "连接主语内容与后面的具体答案", explanation: "后面的 forces 是复数，决定这里用 were。" },
      { text: "the new, positive forces", form: "名词短语", function: "表语", modifies: "说明 what 具体指什么", explanation: "new 和 positive 并列修饰 forces：新的、积极的力量。" },
      { text: "that work against the digital divide", form: "that 引导的完整从句", function: "限制性定语从句", modifies: "修饰 forces", explanation: "回答‘哪些力量’：正是那些会对抗数字鸿沟的力量。" },
    ], clauses: [
      { text: "What was less visible then", type: "融合型关系主语从句", marker: "What（= the things that）", role: "整体作主句主语", subject: "What", predicate: "was", objectOrComplement: "less visible（表语）；then（时间状语）", translationOrder: "先译成‘当时不太明显的事物’，再接主句答案‘是这些新力量’。" },
      { text: "that work against the digital divide", type: "限制性定语从句", marker: "that", role: "限定 the new, positive forces", subject: "that（= forces）", predicate: "work", objectOrComplement: "against the digital divide（作用对象）", translationOrder: "先译中心词‘积极力量’，再前置为‘对抗数字鸿沟的积极力量’。" },
    ] },
    literal: "然而，当时不那么明显的是那些对抗数字鸿沟的新的积极力量。", natural: "但在当时，人们还不太能看见那些正在推动数字鸿沟缩小的新生积极力量。",
    logic: "由危险转向解决问题的积极因素，是全文由‘问题’进入‘乐观理由’的关键转折。",
    phrases: ["less visible then", "the new, positive forces", "work against the digital divide"],
  },
  {
    id: "2001-p2-s5", number: 5,
    text: "There are reasons to be optimistic.",
    chunks: [{ text: "There are", role: "predicate" }, { text: " reasons", role: "subject" }, { text: " to be optimistic.", role: "modifier" }],
    trunk: "There are reasons.",
    layers: [{ label: "存在句", text: "There are reasons：存在一些理由" }, { label: "理由的结论", text: "to be optimistic：使人可以保持乐观" }],
    grammar: ["There be 表示‘有/存在’，真正的内容主语是 reasons。", "to be optimistic 是不定式后置修饰 reasons，可理解为‘保持乐观的理由’。"],
    beginnerSyntax: { components: [
      { text: "There are", form: "There be 存在结构", function: "存在谓语框架", modifies: "引出 reasons", explanation: "there 不表示地点‘那里’，整组先译成‘有’。" },
      { text: "reasons", form: "复数名词", function: "实际主语", modifies: "决定 be 使用复数 are", explanation: "回答‘有什么’：有若干理由。" },
      { text: "to be optimistic", form: "to do 不定式短语", function: "后置定语", modifies: "修饰 reasons", explanation: "说明这些理由支持什么态度：保持乐观。" },
    ], clauses: [] },
    literal: "有理由保持乐观。", natural: "不过，我们有充分理由对未来持乐观态度。",
    logic: "用短句明确提出作者立场，统领第二段的技术和商业理由。",
    phrases: ["reasons to be optimistic"],
  },
  {
    id: "2001-p2-s6", number: 6,
    text: "There are technological reasons to hope the digital divide will narrow.",
    chunks: [{ text: "There are", role: "predicate" }, { text: " technological reasons", role: "subject" }, { text: " to hope", role: "modifier" }, { text: " the digital divide will narrow.", role: "object" }],
    trunk: "There are technological reasons.",
    layers: [{ label: "理由类型", text: "technological reasons：技术方面的理由" }, { label: "希望内容", text: "to hope the digital divide will narrow：据此可期待数字鸿沟缩小" }],
    grammar: ["hope 后接省略 that 的宾语从句 the digital divide will narrow。", "narrow 在此作不及物动词，表示差距缩小，不是形容词‘狭窄的’。"],
    beginnerSyntax: { components: [
      { text: "There are", form: "There be 存在结构", function: "存在谓语框架", modifies: "引出 technological reasons", explanation: "先译‘存在/有’。" },
      { text: "technological reasons", form: "形容词 + 复数名词", function: "实际主语", modifies: "说明理由来自技术层面", explanation: "technological 只限定 reasons，不直接修饰后面的 divide。" },
      { text: "to hope", form: "不定式", function: "后置定语", modifies: "修饰 reasons", explanation: "说明这些技术理由让人可以期待什么。" },
      { text: "the digital divide will narrow", form: "省略 that 的完整从句", function: "宾语从句", modifies: "作 hope 的内容宾语", explanation: "内部主谓完整：鸿沟将缩小。" },
    ], clauses: [
      { text: "the digital divide will narrow", type: "省略 that 的宾语从句", marker: "省略 that", role: "作 hope 的宾语，说明希望发生什么", subject: "the digital divide", predicate: "will narrow", translationOrder: "先读 to hope‘有理由希望’，再接内容‘数字鸿沟将缩小’。" },
    ] },
    literal: "存在技术方面的理由，使人可以希望数字鸿沟将会缩小。", natural: "从技术发展来看，我们有理由相信数字鸿沟会逐渐缩小。",
    logic: "提出第二段第一条论据：技术发展将推动网络接入普及。",
    phrases: ["technological reasons to hope", "the digital divide will narrow"],
  },
  {
    id: "2001-p2-s7", number: 7,
    text: "As the Internet becomes more and more commercialized, it is in the interest of business to universalize access—after all, the more people online, the more potential customers there are.",
    chunks: [
      { text: "As the Internet becomes more and more commercialized, ", role: "condition" },
      { text: "it", role: "subject" }, { text: " is", role: "predicate" },
      { text: " in the interest of business", role: "object" }, { text: " to universalize access", role: "modifier" },
      { text: "—after all, ", role: "connector" }, { text: "the more people online, the more potential customers there are.", role: "condition" },
    ],
    trunk: "it is in the interest of business to universalize access.",
    layers: [
      { label: "变化背景", text: "As the Internet becomes... commercialized：随着互联网越来越商业化" },
      { label: "主句判断", text: "it is in the interest of business to universalize access：普及接入符合商业利益" },
      { label: "破折号解释", text: "the more people online, the more potential customers there are：上网者越多，潜在顾客越多" },
    ],
    grammar: [
      "as 引导伴随变化状语从句，表示‘随着……’；become + 过去分词形容词表示逐渐进入某状态。",
      "it 是形式主语，真正内容是 to universalize access；in the interest of 表‘符合……的利益’。",
      "the more..., the more... 是比较级相关结构；people 后省略 are，完整理解为 the more people are online。",
      "after all 引出解释理由，不能机械译成时间上的‘毕竟在最后’。",
    ],
    beginnerSyntax: { components: [
      { text: "As the Internet becomes more and more commercialized", form: "As 引导的完整从句", function: "伴随变化状语从句", modifies: "修饰主句 is in the interest...", explanation: "表示两种变化同步推进，译成‘随着互联网越来越商业化’。" },
      { text: "it", form: "形式代词", function: "形式主语", modifies: "占据主语位置，真正内容在后面", explanation: "这里不指某件具体事物，真正要评价的是 to universalize access。" },
      { text: "is in the interest of business", form: "系动词 + 介词表语", function: "主句谓语与表语", modifies: "评价普及接入对商业是否有利", explanation: "整体记为‘符合商业利益’，不要把 interest 只译成兴趣。" },
      { text: "to universalize access", form: "to do 不定式", function: "真正主语", modifies: "说明什么事情符合商业利益", explanation: "universalize 表使之普及，access 指接入互联网的机会。" },
      { text: "after all", form: "插入连接短语", function: "解释原因的连接语", modifies: "引出后面的商业逻辑", explanation: "译成‘毕竟’，后面是在解释主句。" },
      { text: "the more people online", form: "the + 比较级省略分句", function: "比较条件分句", modifies: "与后面的 the more... 构成正相关", explanation: "online 是表语，省略 are：上网的人越多。" },
      { text: "the more potential customers there are", form: "the + 比较级完整分句", function: "比较结果分句", modifies: "给出人数增加的商业结果", explanation: "there are 表存在：潜在顾客就越多。" },
    ], clauses: [
      { text: "As the Internet becomes more and more commercialized", type: "伴随变化状语从句", marker: "As", role: "说明主句商业利益形成的背景变化", subject: "the Internet", predicate: "becomes", objectOrComplement: "more and more commercialized（表语）", translationOrder: "先译‘随着互联网越来越商业化’，再译主句。" },
      { text: "the more people online", type: "比较级相关省略从句", marker: "the more", role: "给出正相关关系的前项条件", subject: "people", predicate: "are（省略）", objectOrComplement: "online（表语）", translationOrder: "补出 are，译为‘上网的人越多’。" },
      { text: "the more potential customers there are", type: "比较级相关结果从句", marker: "the more", role: "给出正相关关系的后项结果", subject: "potential customers（There be 的实际主语）", predicate: "there are", translationOrder: "接着译‘潜在顾客就越多’。" },
    ] },
    literal: "随着互联网越来越商业化，使接入普及符合商业利益——毕竟，上网的人越多，存在的潜在顾客就越多。",
    natural: "互联网越走向商业化，企业就越有动力普及网络接入；毕竟，网民越多，潜在顾客也越多。",
    logic: "从商业逐利机制解释网络为什么会主动扩张，是‘数字鸿沟将缩小’的第一条具体因果链。",
    phrases: ["more and more commercialized", "in the interest of business", "to universalize access", "after all", "the more people online, the more potential customers there are"],
  },
  {
    id: "2001-p2-s8", number: 8,
    text: "More and more governments, afraid their countries will be left behind, want to spread Internet access.",
    chunks: [
      { text: "More and more governments", role: "subject" },
      { text: ", afraid their countries will be left behind, ", role: "modifier" },
      { text: "want to spread", role: "predicate" }, { text: " Internet access.", role: "object" },
    ],
    trunk: "More and more governments want to spread Internet access.",
    layers: [
      { label: "主干", text: "More and more governments want to spread Internet access：越来越多的政府希望普及互联网接入" },
      { label: "插入原因", text: "afraid their countries will be left behind：因为担心本国被落在后面" },
    ],
    grammar: ["afraid... 是形容词短语作插入性原因说明，其逻辑主语是 governments。", "afraid 后接省略 that 的内容从句 their countries will be left behind。", "leave sb behind 的被动式 be left behind 表‘落后、被甩在后面’。"],
    beginnerSyntax: { components: [
      { text: "More and more governments", form: "比较级数量结构 + 名词", function: "主语", modifies: "发出 want 的动作", explanation: "more and more 表数量持续增加，中心词 governments 是复数。" },
      { text: "afraid their countries will be left behind", form: "形容词短语 + 内容从句", function: "原因状语", modifies: "说明 governments 为什么 want to spread", explanation: "可在前面补 being：因为担心本国落后；逗号内是插入原因。" },
      { text: "want to spread", form: "want to do", function: "谓语", modifies: "说明各国政府想采取的行动", explanation: "spread 在这里是及物动词‘推广、普及’。" },
      { text: "Internet access", form: "名词作定语 + 名词", function: "宾语", modifies: "承受 spread 的动作", explanation: "不是‘互联网通道’，而是使用互联网的接入机会。" },
    ], clauses: [
      { text: "their countries will be left behind", type: "省略 that 的内容从句", marker: "省略 that", role: "补充说明 afraid 的具体担忧", subject: "their countries", predicate: "will be left", objectOrComplement: "behind（主语补足语，表示落后）", translationOrder: "先读 afraid‘担心’，再接‘自己的国家会落后’。" },
    ] },
    literal: "越来越多的政府，因为害怕自己的国家会被落在后面，想要推广互联网接入。", natural: "越来越多的政府担心本国掉队，因此都希望扩大互联网普及范围。",
    logic: "从政府竞争压力补充第二条扩网动力，与上一句的商业动力并列。",
    phrases: ["More and more governments", "be left behind", "spread Internet access"],
  },
  {
    id: "2001-p2-s9", number: 9,
    text: "Within the next decade or two, one to two billion people on the planet will be netted together.",
    chunks: [
      { text: "Within the next decade or two, ", role: "modifier" }, { text: "one to two billion people", role: "subject" },
      { text: " on the planet", role: "modifier" }, { text: " will be netted together.", role: "predicate" },
    ],
    trunk: "one to two billion people will be netted together.",
    layers: [{ label: "时间范围", text: "Within the next decade or two：在未来十到二十年内" }, { label: "预测", text: "one to two billion people... will be netted together：全球将有十亿到二十亿人被网络连接起来" }],
    grammar: ["within + 时间段表示‘在……之内’，强调不超过这一范围。", "will be netted 是一般将来时被动；net 在此动词化，表示通过网络连接。", "来源 PDF 把 be 排成 he；结合语法与可靠文本应为 will be netted together，本条已按正确形式录入并保留校勘说明。"],
    beginnerSyntax: { components: [
      { text: "Within the next decade or two", form: "within + 时间段", function: "时间范围状语", modifies: "修饰 will be netted", explanation: "decade 是十年；a decade or two 即十年或二十年。" },
      { text: "one to two billion people", form: "数值范围 + 复数名词", function: "主语", modifies: "是 will be netted 的承受者", explanation: "one to two 表从十亿到二十亿的估计范围。" },
      { text: "on the planet", form: "on + 名词", function: "地点/范围状语", modifies: "修饰 people", explanation: "限定为地球上的人，即全球人口。" },
      { text: "will be netted together", form: "一般将来时被动语态", function: "谓语", modifies: "预测人们将被网络连接", explanation: "will + be + 过去分词；together 强调彼此连在一起。" },
    ], clauses: [] },
    literal: "在未来一二十年内，地球上将有十亿到二十亿人被网络连接在一起。", natural: "未来十到二十年，全球将有十亿至二十亿人接入同一网络。",
    logic: "用具体规模预测说明互联网接入将迅速扩大。",
    phrases: ["Within the next decade or two", "on the planet", "will be netted together"],
  },
  {
    id: "2001-p2-s10", number: 10,
    text: "As a result, I now believe the digital divide will narrow rather than widen in the years ahead.",
    chunks: [
      { text: "As a result, ", role: "connector" }, { text: "I", role: "subject" }, { text: " now believe", role: "predicate" },
      { text: " the digital divide will narrow rather than widen", role: "object" }, { text: " in the years ahead.", role: "modifier" },
    ],
    trunk: "I now believe the digital divide will narrow rather than widen.",
    layers: [{ label: "因果结论", text: "As a result：因此，承接商业和政府扩网动力" }, { label: "判断内容", text: "the digital divide will narrow rather than widen：数字鸿沟将缩小而不是扩大" }, { label: "时间", text: "in the years ahead：在未来几年中" }],
    grammar: ["believe 后接省略 that 的宾语从句。", "rather than 连接两个平行的动词原形 narrow 与 widen，表示取前舍后。", "narrow / widen 都是不及物动词，主语是 digital divide。"],
    beginnerSyntax: { components: [
      { text: "As a result", form: "结果连接短语", function: "结果状语", modifies: "修饰整句 believe 判断", explanation: "把前面扩网原因汇总成结论，译成‘因此’。" },
      { text: "I", form: "人称代词", function: "主句主语", modifies: "发出 believe 的判断", explanation: "作者明确给出自己的判断。" },
      { text: "now believe", form: "副词 + 动词", function: "主句谓语", modifies: "说明作者现在的看法", explanation: "now 与二十年前形成时间对比。" },
      { text: "the digital divide will narrow rather than widen", form: "省略 that 的完整从句", function: "宾语从句", modifies: "作 believe 的宾语", explanation: "从句内部 narrow 与 widen 共用 will，表示缩小而非扩大。" },
      { text: "in the years ahead", form: "in + 时间名词短语", function: "时间状语", modifies: "修饰 will narrow", explanation: "ahead 后置修饰 years，表示今后的岁月。" },
    ], clauses: [
      { text: "the digital divide will narrow rather than widen in the years ahead", type: "省略 that 的宾语从句", marker: "省略 that", role: "作 believe 的宾语，给出作者的预测", subject: "the digital divide", predicate: "will narrow rather than widen", objectOrComplement: "in the years ahead（时间状语）", translationOrder: "先译‘我现在相信’，再译判断内容‘未来鸿沟会缩小而非扩大’。" },
    ] },
    literal: "因此，我现在相信数字鸿沟在未来几年会缩小而不是扩大。", natural: "所以我如今相信，今后的数字鸿沟不会继续拉大，反而会逐渐收窄。",
    logic: "汇总前述两类扩网力量，直接给出全文的乐观预测。",
    phrases: ["As a result", "narrow rather than widen", "in the years ahead"],
  },
  {
    id: "2001-p2-s11", number: 11,
    text: "And that is very good news because the Internet may well be the most powerful tool for combating world poverty that we’ve ever had.",
    chunks: [
      { text: "And", role: "connector" }, { text: " that", role: "subject" }, { text: " is", role: "predicate" },
      { text: " very good news", role: "object" }, { text: " because the Internet may well be the most powerful tool", role: "condition" },
      { text: " for combating world poverty", role: "modifier" }, { text: " that we’ve ever had.", role: "modifier" },
    ],
    trunk: "that is very good news.",
    layers: [{ label: "评价", text: "that is very good news：数字鸿沟将缩小是好消息" }, { label: "原因", text: "because the Internet may well be...：因为互联网很可能/完全有理由成为最强工具" }, { label: "工具用途与范围", text: "for combating world poverty / that we’ve ever had：用于抗击全球贫困，是我们迄今拥有过的工具中最强的" }],
    grammar: ["because 引导原因状语从句。", "may well + 动词原形表示‘很可能/完全有理由’，语气比普通 may 更有把握。", "for combating... 是 for + 动名词，后置说明 tool 的用途。", "that we’ve ever had 是限制性定语从句，修饰 tool；that 在从句中作 had 的宾语。"],
    beginnerSyntax: { components: [
      { text: "And", form: "并列连词", function: "承接连接语", modifies: "连接预测与评价", explanation: "承接上一句‘鸿沟会缩小’。" },
      { text: "that", form: "指示代词", function: "主句主语", modifies: "回指上一句整个结论", explanation: "不是关系代词，指‘数字鸿沟将缩小这件事’。" },
      { text: "is very good news", form: "系动词 + 名词表语", function: "主句谓语与表语", modifies: "评价上一结论", explanation: "news 是不可数名词，不说 a good news。" },
      { text: "because the Internet may well be the most powerful tool", form: "because 引导的完整从句", function: "原因状语从句", modifies: "解释为什么是好消息", explanation: "先抓内部主干 Internet may be tool；well 加强可能性。" },
      { text: "for combating world poverty", form: "for + 动名词短语", function: "用途后置定语", modifies: "修饰 tool", explanation: "说明这件工具用来做什么：抗击世界贫困。" },
      { text: "that we’ve ever had", form: "that 引导的完整从句", function: "限制性定语从句", modifies: "修饰 the most powerful tool", explanation: "把比较范围限定为‘我们迄今拥有过的所有工具’。" },
    ], clauses: [
      { text: "because the Internet may well be the most powerful tool for combating world poverty that we’ve ever had", type: "原因状语从句", marker: "because", role: "解释数字鸿沟缩小为何是好消息", subject: "the Internet", predicate: "may well be", objectOrComplement: "the most powerful tool（表语）", translationOrder: "先译主句评价，再用‘因为’解释互联网的扶贫潜力。" },
      { text: "that we’ve ever had", type: "限制性定语从句", marker: "that", role: "修饰 the most powerful tool，限定最高级的比较范围", subject: "we", predicate: "have ever had", objectOrComplement: "that（作 had 的宾语）", translationOrder: "译到 tool 时前置成‘我们迄今拥有过的最强大工具’。" },
    ] },
    literal: "而那是非常好的消息，因为互联网很可能是我们曾经拥有的、用来对抗世界贫困的最强大工具。", natural: "这无疑是个好消息，因为互联网很可能是人类迄今用于抗击全球贫困的最有力工具。",
    logic: "把缩小数字鸿沟与减贫联系起来，说明普及互联网具有超越商业的社会价值。",
    phrases: ["very good news", "may well be", "the most powerful tool for combating world poverty", "that we’ve ever had"],
  },
  {
    id: "2001-p2-s12", number: 12,
    text: "Of course, the use of the Internet isn’t the only way to defeat poverty.",
    chunks: [{ text: "Of course, ", role: "connector" }, { text: "the use of the Internet", role: "subject" }, { text: " isn’t", role: "predicate" }, { text: " the only way", role: "object" }, { text: " to defeat poverty.", role: "modifier" }],
    trunk: "the use of the Internet isn’t the only way.",
    layers: [{ label: "让步限定", text: "Of course：当然，作者主动承认互联网并非万能" }, { label: "主干", text: "the use of the Internet isn’t the only way：使用互联网不是唯一办法" }, { label: "办法目的", text: "to defeat poverty：战胜贫困" }],
    grammar: ["the use of... 是名词化主语，中心词 use 为单数，所以用 isn’t。", "to defeat poverty 是不定式后置修饰 way，表示‘做某事的办法’。", "only 限定 way；否定的是‘唯一性’，不是否定互联网有作用。"],
    beginnerSyntax: { components: [
      { text: "Of course", form: "句子副词短语", function: "让步/承认状语", modifies: "修饰整句否定判断", explanation: "作者先承认一个常识，避免把互联网说成唯一答案。" },
      { text: "the use of the Internet", form: "名词化短语", function: "主语", modifies: "与 isn’t 构成系表主干", explanation: "中心是 use‘使用’，of the Internet 说明使用对象。" },
      { text: "isn’t the only way", form: "系动词否定 + 名词表语", function: "谓语与表语", modifies: "说明互联网使用并非唯一办法", explanation: "不是说它没用，而是说还有别的办法。" },
      { text: "to defeat poverty", form: "不定式短语", function: "后置定语", modifies: "修饰 way", explanation: "回答‘做什么的办法’：战胜贫困。" },
    ], clauses: [] },
    literal: "当然，互联网的使用并不是战胜贫困的唯一方式。", natural: "当然，利用互联网并非消除贫困的唯一途径。",
    logic: "主动限制前一句的强判断，使论证更严谨。",
    phrases: ["Of course", "the use of the Internet", "the only way to defeat poverty"],
  },
  {
    id: "2001-p2-s13", number: 13,
    text: "And the Internet is not the only tool we have.",
    chunks: [{ text: "And", role: "connector" }, { text: " the Internet", role: "subject" }, { text: " is not", role: "predicate" }, { text: " the only tool", role: "object" }, { text: " we have.", role: "modifier" }],
    trunk: "the Internet is not the only tool.",
    layers: [{ label: "同义重申", text: "the Internet is not the only tool：互联网不是我们唯一拥有的工具" }, { label: "省略关系词", text: "we have：修饰 tool，可补 that/which" }],
    grammar: ["we have 是省略关系代词 that/which 的限制性定语从句；省略的关系词在从句中作 have 的宾语。", "与上一句平行重申，但把 way 换成 tool。"],
    beginnerSyntax: { components: [
      { text: "And", form: "并列连词", function: "递进连接语", modifies: "连接上一句与本句重申", explanation: "继续补充同一限制，而非另起话题。" },
      { text: "the Internet", form: "专有概念名词短语", function: "主语", modifies: "与 is not 构成主干", explanation: "本句直接评价互联网。" },
      { text: "is not the only tool", form: "系动词否定 + 名词表语", function: "谓语与表语", modifies: "说明互联网不是唯一工具", explanation: "only 仍限定‘唯一’，不否定工具价值。" },
      { text: "we have", form: "省略关系代词的完整从句", function: "限制性定语从句", modifies: "修饰 tool", explanation: "补成 that we have：我们所拥有的工具。" },
    ], clauses: [
      { text: "we have", type: "省略关系代词的限制性定语从句", marker: "省略 that/which", role: "修饰 the only tool", subject: "we", predicate: "have", objectOrComplement: "省略的 that/which（作宾语，指 tool）", translationOrder: "前置修饰为‘我们拥有的唯一工具’。" },
    ] },
    literal: "而且，互联网不是我们拥有的唯一工具。", natural: "互联网也并不是人类解决贫困问题的唯一工具。",
    logic: "再次压低绝对化表述，为下句转回‘但潜力巨大’蓄势。",
    phrases: ["the only tool we have"],
  },
  {
    id: "2001-p2-s14", number: 14,
    text: "But it has enormous potential.",
    chunks: [{ text: "But", role: "connector" }, { text: " it", role: "subject" }, { text: " has", role: "predicate" }, { text: " enormous potential.", role: "object" }],
    trunk: "it has enormous potential.",
    layers: [{ label: "转折结论", text: "But：虽非唯一工具，仍然……" }, { label: "核心判断", text: "it has enormous potential：它拥有巨大的潜力" }],
    grammar: ["it 回指 the Internet。", "potential 在此作不可数名词，have enormous potential 表‘潜力巨大’。"],
    beginnerSyntax: { components: [
      { text: "But", form: "并列连词", function: "转折连接语", modifies: "连接两句限制与本句肯定", explanation: "逻辑是‘不是唯一，但仍很重要’。" },
      { text: "it", form: "人称代词", function: "主语", modifies: "回指 the Internet", explanation: "代替重复的互联网。" },
      { text: "has", form: "一般现在时动词", function: "谓语", modifies: "说明互联网具有什么", explanation: "主语 it 为第三人称单数，所以用 has。" },
      { text: "enormous potential", form: "形容词 + 抽象名词", function: "宾语", modifies: "承受 has 的关系", explanation: "整体是‘巨大潜力’，potential 不表示已经实现的结果。" },
    ], clauses: [] },
    literal: "但它有巨大的潜力。", natural: "但互联网蕴含的潜力极其巨大。",
    logic: "用极短转折句重新突出互联网价值，并过渡到如何释放这种潜力。",
    phrases: ["has enormous potential"],
  },
  {
    id: "2001-p2-s15", number: 15,
    text: "To take advantage of this tool, some impoverished countries will have to get over their outdated anti-colonial prejudices with respect to foreign investment.",
    chunks: [
      { text: "To take advantage of this tool, ", role: "condition" }, { text: "some impoverished countries", role: "subject" },
      { text: " will have to get over", role: "predicate" }, { text: " their outdated anti-colonial prejudices", role: "object" },
      { text: " with respect to foreign investment.", role: "modifier" },
    ],
    trunk: "some impoverished countries will have to get over their outdated anti-colonial prejudices.",
    layers: [{ label: "目的", text: "To take advantage of this tool：为了利用互联网这一工具" }, { label: "必要行动", text: "countries will have to get over... prejudices：贫困国家必须克服陈旧偏见" }, { label: "偏见对象", text: "with respect to foreign investment：这些偏见针对外国投资" }],
    grammar: ["句首 To take advantage... 是目的状语。", "have to 表客观必要性；will have to 表未来必须。", "get over 在此表示克服观念障碍，不是‘从疾病中恢复’。", "with respect to 是正式介词短语，表示‘关于/就……而言’。"],
    beginnerSyntax: { components: [
      { text: "To take advantage of this tool", form: "to do 不定式短语", function: "目的状语", modifies: "修饰 will have to get over", explanation: "先译‘为了充分利用这一工具’，说明后面克服偏见的目的。" },
      { text: "some impoverished countries", form: "限定词 + 形容词 + 名词", function: "主语", modifies: "发出 get over 的动作", explanation: "impoverished 表贫困化的，中心词 countries 是复数。" },
      { text: "will have to get over", form: "将来时 + have to + 动词原形", function: "谓语", modifies: "说明这些国家必须采取什么行动", explanation: "整体是‘将不得不克服’，get over 不要拆成‘得到在上面’。" },
      { text: "their outdated anti-colonial prejudices", form: "物主限定词 + 两个形容词 + 名词", function: "宾语", modifies: "承受 get over 的动作", explanation: "outdated 说偏见过时，anti-colonial 说明偏见源于反殖民历史。" },
      { text: "with respect to foreign investment", form: "复合介词 + 名词", function: "对象后置定语", modifies: "修饰 prejudices", explanation: "说明这些偏见具体针对外资。" },
    ], clauses: [] },
    literal: "为了利用这个工具，一些贫困国家将不得不克服它们关于外国投资的过时反殖民偏见。", natural: "一些贫困国家若想发挥互联网的作用，就必须摒弃对外资抱有的陈旧反殖民成见。",
    logic: "从‘互联网有潜力’转向实现潜力所需的政策条件：接受并正确利用外资。",
    phrases: ["To take advantage of this tool", "impoverished countries", "get over their outdated anti-colonial prejudices", "with respect to foreign investment"],
  },
  {
    id: "2001-p2-s16", number: 16,
    text: "Countries that still think foreign investment is an invasion of their sovereignty might well study the history of infrastructure (the basic structural foundations of a society) in the United States.",
    chunks: [
      { text: "Countries", role: "subject" }, { text: " that still think foreign investment is an invasion of their sovereignty", role: "modifier" },
      { text: " might well study", role: "predicate" }, { text: " the history of infrastructure", role: "object" },
      { text: " (the basic structural foundations of a society)", role: "modifier" }, { text: " in the United States.", role: "modifier" },
    ],
    trunk: "Countries might well study the history of infrastructure in the United States.",
    layers: [{ label: "先抓主干", text: "Countries might well study...：这些国家不妨研究……" }, { label: "限定国家", text: "that still think...：仍把外资看作侵犯主权的国家" }, { label: "研究对象", text: "the history of infrastructure... in the United States：美国基础设施建设史；括号解释 infrastructure" }],
    grammar: ["that 引导限制性定语从句，修饰 Countries。", "think 后接省略 that 的宾语从句 foreign investment is...。", "might well + 动词原形在此表示委婉而有根据的建议‘不妨/大可以’。", "括号内容是 infrastructure 的同位解释；in the United States 修饰 history/infrastructure 的地域范围。"],
    beginnerSyntax: { components: [
      { text: "Countries", form: "复数名词", function: "主句主语", modifies: "发出 study 的动作", explanation: "先只抓‘国家不妨研究’，后面的 that 从句再限定哪些国家。" },
      { text: "that still think foreign investment is an invasion of their sovereignty", form: "that 引导的完整从句", function: "限制性定语从句", modifies: "修饰 Countries", explanation: "回答‘哪些国家’：仍然认为外资侵犯主权的国家。" },
      { text: "might well study", form: "情态动词短语 + 动词原形", function: "主句谓语", modifies: "提出委婉建议", explanation: "这里不是‘可能很好地研究’，might well 整体译‘不妨’。" },
      { text: "the history of infrastructure", form: "名词 + of 结构", function: "主句宾语", modifies: "承受 study 的动作", explanation: "研究的是基础设施的发展历史。" },
      { text: "the basic structural foundations of a society", form: "括号同位名词短语", function: "术语解释", modifies: "解释 infrastructure", explanation: "把基础设施解释为社会赖以运行的基本结构基础。" },
      { text: "in the United States", form: "in + 地名", function: "地点/范围状语", modifies: "修饰 infrastructure history", explanation: "限定研究的是美国的建设史。" },
    ], clauses: [
      { text: "that still think foreign investment is an invasion of their sovereignty", type: "限制性定语从句", marker: "that", role: "限定 Countries 的思想特征", subject: "that（= Countries）", predicate: "still think", objectOrComplement: "foreign investment is an invasion of their sovereignty（宾语从句）", translationOrder: "先译从句为前置定语‘仍认为……的国家’，再回到主句。" },
      { text: "foreign investment is an invasion of their sovereignty", type: "省略 that 的宾语从句", marker: "省略 that", role: "作 think 的宾语，说明这些国家的具体看法", subject: "foreign investment", predicate: "is", objectOrComplement: "an invasion of their sovereignty（表语）", translationOrder: "在定语从句内部按‘认为 + 外资是侵犯主权’理解。" },
    ] },
    literal: "那些仍认为外国投资是对其主权侵犯的国家，不妨研究美国的基础设施——一个社会的基本结构基础——的历史。", natural: "仍把外资视为侵犯国家主权的国家，不妨考察一下美国基础设施建设的历史。",
    logic: "提出美国案例作为反证，准备说明外资并不必然导致主权或资产丧失。",
    phrases: ["foreign investment", "an invasion of their sovereignty", "might well study", "the history of infrastructure", "the basic structural foundations of a society", "in the United States"],
  },
  {
    id: "2001-p2-s17", number: 17,
    text: "When the United States built its industrial infrastructure, it didn’t have the capital to do so.",
    chunks: [{ text: "When the United States built its industrial infrastructure, ", role: "condition" }, { text: "it", role: "subject" }, { text: " didn’t have", role: "predicate" }, { text: " the capital", role: "object" }, { text: " to do so.", role: "modifier" }],
    trunk: "it didn’t have the capital.",
    layers: [{ label: "时间背景", text: "When the United States built...：美国建设工业基础设施时" }, { label: "主句", text: "it didn’t have the capital：它自身没有所需资本" }, { label: "用途", text: "to do so：用来进行这项建设；so 代替 build its industrial infrastructure" }],
    grammar: ["when 引导时间状语从句。", "do so 代替前面已经出现的动作，避免重复；此处指 build its industrial infrastructure。", "capital 在经济语境指资本、建设资金，不是首都或大写字母。"],
    beginnerSyntax: { components: [
      { text: "When the United States built its industrial infrastructure", form: "When 引导的完整从句", function: "时间状语从句", modifies: "修饰 didn’t have", explanation: "先给出历史时间点：美国建设工业基础设施的时候。" },
      { text: "it", form: "人称代词", function: "主句主语", modifies: "回指 the United States", explanation: "国家名称作整体时用单数 it 回指。" },
      { text: "didn’t have", form: "一般过去时否定", function: "主句谓语", modifies: "说明当时缺少什么", explanation: "did 后实义动词用原形 have。" },
      { text: "the capital", form: "名词短语", function: "主句宾语", modifies: "承受 have 的关系", explanation: "特指建设所需要的资本。" },
      { text: "to do so", form: "不定式 + 替代词", function: "用途后置定语", modifies: "修饰 capital", explanation: "说明资本用来做什么；do so 代替重复建设动作。" },
    ], clauses: [
      { text: "When the United States built its industrial infrastructure", type: "时间状语从句", marker: "When", role: "说明美国缺少资本发生在何时", subject: "the United States", predicate: "built", objectOrComplement: "its industrial infrastructure（宾语）", translationOrder: "先译‘当美国建设……时’，再译主句‘它没有……’。" },
    ] },
    literal: "当美国建设其工业基础设施时，它没有这样做所需的资本。", natural: "美国当年建设工业基础设施时，自身并没有足够资金。",
    logic: "先指出美国建设时的资金缺口，为下一句说明采用外资提供必要前提。",
    phrases: ["built its industrial infrastructure", "have the capital to do so", "do so"],
  },
  {
    id: "2001-p2-s18", number: 18,
    text: "And that is why America’s Second Wave infrastructure—including roads, harbors, highways, ports and so on—were built with foreign investment.",
    chunks: [
      { text: "And", role: "connector" }, { text: " that", role: "subject" }, { text: " is", role: "predicate" },
      { text: " why America’s Second Wave infrastructure", role: "object" },
      { text: "—including roads, harbors, highways, ports and so on—", role: "modifier" },
      { text: "were built", role: "predicate" }, { text: " with foreign investment.", role: "modifier" },
    ],
    trunk: "that is why America’s Second Wave infrastructure were built with foreign investment.",
    layers: [{ label: "因果框架", text: "that is why...：这就是为什么……" }, { label: "列举说明", text: "including roads, harbors, highways, ports and so on：第二次浪潮基础设施包括公路、港湾、高速公路、港口等" }, { label: "结果", text: "were built with foreign investment：这些设施借助外资建成" }],
    grammar: ["why 引导表语从句，说明 that 所指原因导致的结果。", "including... 是现在分词介词化的插入列举，修饰 infrastructure；两条短横线限定其边界。", "with foreign investment 是方式/手段状语，表示建设资金来源。", "原卷把集合性的 infrastructure 与 were 连用，按原文保留；现代常规表达更常用 was built。"],
    beginnerSyntax: { components: [
      { text: "And that is", form: "连接词 + 指示代词 + 系动词", function: "主句主干", modifies: "引出 why 表语从句", explanation: "that 回指上一句‘美国没有资本’这一事实。" },
      { text: "why America’s Second Wave infrastructure—including roads, harbors, highways, ports and so on—were built with foreign investment", form: "why 引导的完整从句", function: "表语从句", modifies: "说明 that 导致了什么结果", explanation: "先把破折号内列举暂时括起来，抓住 infrastructure were built，再把道路、港口等实例放回去。" },
      { text: "America’s Second Wave infrastructure", form: "所有格 + 专名式名词短语", function: "表语从句主语", modifies: "是 were built 的承受者", explanation: "Second Wave 指工业时代的基础设施建设浪潮。" },
      { text: "—including roads, harbors, highways, ports and so on—", form: "破折号 + including + 并列名词", function: "插入列举说明", modifies: "修饰 infrastructure", explanation: "两条破折号标明插入语边界；只列出基础设施的实例，整段拿掉后主句仍完整。" },
      { text: "were built", form: "一般过去时被动语态", function: "表语从句谓语", modifies: "说明设施如何形成", explanation: "建设者不重要，重点是资金来源。" },
      { text: "with foreign investment", form: "with + 名词短语", function: "方式/资金来源状语", modifies: "修饰 were built", explanation: "说明借助什么建成：外国投资。" },
    ], clauses: [
      { text: "why America’s Second Wave infrastructure—including roads, harbors, highways, ports and so on—were built with foreign investment", type: "why 引导的表语从句", marker: "why", role: "在 that is why... 中说明前述资本不足造成的结果", subject: "America’s Second Wave infrastructure", predicate: "were built", objectOrComplement: "with foreign investment（方式/资金来源状语）", translationOrder: "先译‘这就是为什么’，再完整译出基础设施借助外资建成。" },
    ] },
    literal: "而这就是为什么美国的第二次浪潮基础设施——包括道路、港湾、高速公路、港口等等——是用外国投资建成的。", natural: "正因为本国资本不足，美国工业时代的道路、港湾、高速公路和港口等基础设施才依靠外资建成。",
    logic: "给出美国利用外资建设工业基础设施的核心事实，直接服务第 27 题。",
    phrases: ["that is why", "America’s Second Wave infrastructure", "including roads, harbors, highways, ports and so on", "were built with foreign investment"],
  },
  {
    id: "2001-p2-s19", number: 19,
    text: "The English, the Germans, the Dutch and the French were investing in Britain’s former colony.",
    chunks: [{ text: "The English, the Germans, the Dutch and the French", role: "subject" }, { text: " were investing", role: "predicate" }, { text: " in Britain’s former colony.", role: "modifier" }],
    trunk: "The English, the Germans, the Dutch and the French were investing in Britain’s former colony.",
    layers: [{ label: "投资者并列", text: "The English / the Germans / the Dutch / the French：英、德、荷、法投资者" }, { label: "投资对象", text: "were investing in Britain’s former colony：当时正在向英国的前殖民地投资" }],
    grammar: ["the + 国籍形容词可表示该国人民；English、Dutch、French 形式不加 -s，Germans 为名词复数。", "invest in + 项目/地区表示‘投资于……’。", "former colony 指过去曾是殖民地的美国，former 只表示过去身份。"],
    beginnerSyntax: { components: [
      { text: "The English, the Germans, the Dutch and the French", form: "四个国籍群体并列", function: "主语", modifies: "共同发出 were investing 的动作", explanation: "and 连接最后一项，整组是复数主语。" },
      { text: "were investing", form: "过去进行时", function: "谓语", modifies: "说明当时持续进行的投资", explanation: "强调美国建设时期外资正在流入。" },
      { text: "in Britain’s former colony", form: "invest in + 名词短语", function: "对象状语", modifies: "修饰 were investing", explanation: "invest 必须与 in 连用；Britain’s former colony 在这里指独立后的美国。" },
    ], clauses: [] },
    literal: "英国人、德国人、荷兰人和法国人当时正在英国的前殖民地投资。", natural: "当时，英国、德国、荷兰和法国的资本都在向这个英国的前殖民地投入。",
    logic: "具体列出外资来源，增强美国案例的历史可信度。",
    phrases: ["were investing in", "Britain’s former colony"],
  },
  {
    id: "2001-p2-s20", number: 20,
    text: "They financed them.",
    chunks: [{ text: "They", role: "subject" }, { text: " financed", role: "predicate" }, { text: " them.", role: "object" }],
    trunk: "They financed them.",
    layers: [{ label: "指代还原", text: "They = 前句外国投资者；them = 美国的道路、港口等基础设施" }, { label: "动作", text: "financed：为这些设施提供建设资金" }],
    grammar: ["finance 作及物动词，直接接项目作宾语，表示为其提供资金。", "两个代词必须跨句还原，不能把 they 和 them 都理解成同一群体。"],
    beginnerSyntax: { components: [
      { text: "They", form: "人称代词", function: "主语", modifies: "回指欧洲投资者", explanation: "动作发出者是上一句四国投资者。" },
      { text: "financed", form: "一般过去时及物动词", function: "谓语", modifies: "说明投资者提供了什么作用", explanation: "finance 在这里是动词‘出资’，不是名词‘金融’。" },
      { text: "them", form: "宾格代词", function: "宾语", modifies: "回指美国基础设施项目", explanation: "接受资金的是上一句之前列举的道路、港口等设施。" },
    ], clauses: [] },
    literal: "他们为它们提供资金。", natural: "这些欧洲投资者为美国的基础设施建设提供了资金。",
    logic: "用短句明确分工中的资本来源，为下一句‘移民负责建设’形成对照。",
    phrases: ["financed them"],
  },
  {
    id: "2001-p2-s21", number: 21,
    text: "Immigrant Americans built them.",
    chunks: [{ text: "Immigrant Americans", role: "subject" }, { text: " built", role: "predicate" }, { text: " them.", role: "object" }],
    trunk: "Immigrant Americans built them.",
    layers: [{ label: "建设者", text: "Immigrant Americans：来到美国的移民" }, { label: "动作与指代", text: "built them：实际建造这些基础设施" }],
    grammar: ["Immigrant 作名词定语修饰 Americans，指移民美国者。", "built 是 build 的不规则过去式；them 继续回指基础设施。"],
    beginnerSyntax: { components: [
      { text: "Immigrant Americans", form: "名词作定语 + 名词", function: "主语", modifies: "发出 built 的动作", explanation: "指移民到美国、后来成为美国人的建设者。" },
      { text: "built", form: "一般过去时动词", function: "谓语", modifies: "说明实际建设动作", explanation: "build—built—built，需要单独记忆。" },
      { text: "them", form: "宾格代词", function: "宾语", modifies: "回指基础设施", explanation: "与上一句 them 指向相同。" },
    ], clauses: [] },
    literal: "移民美国的人建造了它们。", natural: "而真正把这些设施建起来的，是美国的移民。",
    logic: "区分‘外国资本出资’与‘本国移民建设’，说明接受外资不等于把设施交给外国控制。",
    phrases: ["Immigrant Americans", "built them"],
  },
  {
    id: "2001-p2-s22", number: 22,
    text: "Guess who owns them now?",
    chunks: [{ text: "Guess", role: "predicate" }, { text: " who", role: "subject" }, { text: " owns", role: "predicate" }, { text: " them", role: "object" }, { text: " now?", role: "modifier" }],
    trunk: "Guess who owns them now?",
    layers: [{ label: "主句命令", text: "Guess：猜一猜" }, { label: "猜测内容", text: "who owns them now：如今谁拥有这些设施" }],
    grammar: ["Guess 是祈使句，省略主语 you。", "who owns them now 是间接疑问/宾语从句，使用陈述语序；who 本身作从句主语，所以表面与疑问语序相同。"],
    beginnerSyntax: { components: [
      { text: "Guess", form: "祈使句动词原形", function: "主句谓语", modifies: "要求读者作出猜测", explanation: "省略主语 you，作者借设问加强说服力。" },
      { text: "who owns them now", form: "who 引导的完整从句", function: "宾语从句", modifies: "作 Guess 的宾语", explanation: "要猜的是‘现在谁拥有它们’；who 同时是 owns 的主语。" },
    ], clauses: [
      { text: "who owns them now", type: "who 引导的宾语从句", marker: "who", role: "作 Guess 的宾语，给出设问内容", subject: "who", predicate: "owns", objectOrComplement: "them（宾语）；now（时间状语）", translationOrder: "先译祈使语气‘猜猜’，再译‘现在谁拥有它们’。" },
    ] },
    literal: "猜猜现在谁拥有它们？", natural: "猜猜看，如今这些设施归谁所有？",
    logic: "设置反问，促使读者自己得出‘最终仍归美国人’的结论。",
    phrases: ["Guess who owns them now"],
  },
  {
    id: "2001-p2-s23", number: 23,
    text: "The Americans.",
    chunks: [{ text: "The", role: "modifier" }, { text: " Americans.", role: "subject" }],
    trunk: "The Americans.",
    layers: [{ label: "省略回答", text: "完整意思是 The Americans own them now：现在拥有这些设施的是美国人" }],
    grammar: ["这是回答上一设问的省略句，省略重复谓语 own them now。", "the Americans 指美国人这一群体，不是外国投资者。"],
    beginnerSyntax: { components: [
      { text: "The Americans", form: "the + 国籍复数名词", function: "省略句的回答焦点/主语", modifies: "补足上一句 who 的答案", explanation: "把上一句结构补回来：The Americans own them now。" },
    ], clauses: [] },
    literal: "美国人。", natural: "答案是美国人自己。",
    logic: "用最短答案点明美国虽依靠外资建设，最终所有权仍在本国手中。",
    phrases: ["The Americans"],
  },
  {
    id: "2001-p2-s24", number: 24,
    text: "I believe the same thing would be true in places like Brazil or anywhere else for that matter.",
    chunks: [{ text: "I", role: "subject" }, { text: " believe", role: "predicate" }, { text: " the same thing would be true", role: "object" }, { text: " in places like Brazil", role: "modifier" }, { text: " or anywhere else", role: "modifier" }, { text: " for that matter.", role: "connector" }],
    trunk: "I believe the same thing would be true.",
    layers: [{ label: "主句", text: "I believe：作者作出推断" }, { label: "推断内容", text: "the same thing would be true：同样规律也会成立" }, { label: "适用范围", text: "in places like Brazil or anywhere else for that matter：在巴西等地，实际上任何其他地方都一样" }],
    grammar: ["believe 后接省略 that 的宾语从句。", "would 表基于假设/类比的推断，不是单纯过去将来。", "for that matter 是补充强调语，表示‘就此而言；甚至可以说’。", "like Brazil 表举例，不是动词‘喜欢’。"],
    beginnerSyntax: { components: [
      { text: "I", form: "人称代词", function: "主句主语", modifies: "发出 believe 的判断", explanation: "作者从美国案例推广结论。" },
      { text: "believe", form: "一般现在时动词", function: "主句谓语", modifies: "引出后面的判断内容", explanation: "后面省略了连接词 that。" },
      { text: "the same thing would be true", form: "省略 that 的完整从句", function: "宾语从句", modifies: "作 believe 的宾语", explanation: "same thing 指‘借外资建设但最终由本国拥有’这一规律。" },
      { text: "in places like Brazil", form: "in + 地点 + 举例", function: "地点/适用范围状语", modifies: "修饰 would be true", explanation: "先举巴西为例。" },
      { text: "or anywhere else", form: "or + 地点代词", function: "并列范围状语", modifies: "扩大 would be true 的范围", explanation: "不只巴西，其他地方也可能如此。" },
      { text: "for that matter", form: "固定插入短语", function: "补充强调语", modifies: "强调 anywhere else", explanation: "译成‘其实/就此而言’，把结论进一步推广。" },
    ], clauses: [
      { text: "the same thing would be true in places like Brazil or anywhere else for that matter", type: "省略 that 的宾语从句", marker: "省略 that", role: "作 believe 的宾语，说明美国经验可推广", subject: "the same thing", predicate: "would be", objectOrComplement: "true（表语）；in places...（适用范围）", translationOrder: "先译‘我相信’，再译‘同样规律在巴西乃至别处也成立’。" },
    ] },
    literal: "我相信，同样的事情在像巴西这样的地方，或者就此而言在任何其他地方，也会是真的。", natural: "我相信，美国的经验同样适用于巴西之类的国家，实际上其他地方也不例外。",
    logic: "把美国个案推广为对发展中国家的普遍政策建议。",
    phrases: ["the same thing would be true", "in places like Brazil", "anywhere else for that matter"],
  },
  {
    id: "2001-p2-s25", number: 25,
    text: "The more foreign capital you have helping you build your Third Wave infrastructure, which today is an electronic infrastructure, the better off you’re going to be.",
    chunks: [
      { text: "The more foreign capital you have helping you build your Third Wave infrastructure", role: "condition" },
      { text: ", which today is an electronic infrastructure, ", role: "modifier" },
      { text: "the better off", role: "object" }, { text: " you’re going to be.", role: "predicate" },
    ],
    trunk: "The more foreign capital you have, the better off you’re going to be.",
    layers: [{ label: "越……越……", text: "The more foreign capital..., the better off...：利用的外国资本越多，经济状况就会越好" }, { label: "资本的作用", text: "helping you build your Third Wave infrastructure：外资帮助建设第三次浪潮基础设施" }, { label: "术语解释", text: "which today is an electronic infrastructure：今天所谓第三次浪潮就是电子信息基础设施" }],
    grammar: ["the more..., the better... 是比较级相关结构，表示两项随动变化。", "have + 宾语 + doing 表让/有某人某物处于持续做某事的状态；foreign capital 是 helping 的逻辑主语。", "help sb (to) do 中 to 可省略，本句为 helping you build。", "which 引导非限制性定语从句，补充解释 Third Wave infrastructure。", "better off 是固定比较级表语，表示经济或生活状况更好。"],
    beginnerSyntax: { components: [
      { text: "The more foreign capital you have helping you build your Third Wave infrastructure", form: "the more 引导的比较级分句", function: "比较条件分句", modifies: "与 the better off... 构成正相关", explanation: "先抓 you have foreign capital：你拥有/利用外资；helping... 再说明外资在帮助建设。" },
      { text: "foreign capital", form: "形容词 + 名词", function: "have 的宾语兼 helping 的逻辑主语", modifies: "说明谁帮助建设", explanation: "不是抽象‘首都’，capital 在这里是外国资本。" },
      { text: "helping you build your Third Wave infrastructure", form: "现在分词 + 宾语 + 动词原形", function: "宾语补足语", modifies: "补充 foreign capital 正在发挥的作用", explanation: "理解为‘外资帮助你建设……’，build 前省略 to。" },
      { text: "which today is an electronic infrastructure", form: "which 引导的完整从句", function: "非限制性定语从句", modifies: "补充解释 Third Wave infrastructure", explanation: "两个逗号夹住，只提供术语说明：今天它就是电子基础设施。" },
      { text: "the better off", form: "the + 比较级固定表语", function: "比较结果部分", modifies: "与前面的 the more 呼应", explanation: "better off 整体表示境况更好，不能把 off 单独译成‘离开’。" },
      { text: "you’re going to be", form: "be going to + 动词原形", function: "结果分句谓语", modifies: "预测未来状态", explanation: "be 的表语 better off 被提前到前面，正常理解是 you are going to be better off。" },
    ], clauses: [
      { text: "The more foreign capital you have helping you build your Third Wave infrastructure", type: "比较级相关条件分句", marker: "The more", role: "给出‘外资越多’这一变化前项", subject: "you", predicate: "have", objectOrComplement: "foreign capital（宾语）；helping...（宾补）", translationOrder: "先译‘帮助你建设电子基础设施的外资越多’。" },
      { text: "which today is an electronic infrastructure", type: "非限制性定语从句", marker: "which", role: "补充解释 your Third Wave infrastructure", subject: "which（= Third Wave infrastructure）", predicate: "is", objectOrComplement: "an electronic infrastructure（表语）；today（时间状语）", translationOrder: "在术语后补译‘今天指电子信息基础设施’，再回到越……越……主线。" },
    ] },
    literal: "你拥有的、帮助你建设第三次浪潮基础设施——今天就是电子基础设施——的外国资本越多，你将会越富裕。", natural: "一个国家引入越多外资建设当今的电子信息基础设施，它未来的经济状况就越好。",
    logic: "把美国案例提炼为核心政策结论，也是第 28 题推断‘电子化程度决定经济发展’的关键句。",
    phrases: ["The more foreign capital", "helping you build your Third Wave infrastructure", "an electronic infrastructure", "the better off you’re going to be"],
  },
  {
    id: "2001-p2-s26", number: 26,
    text: "That doesn't mean lying down and becoming fooled, or letting foreign corporations run uncontrolled.",
    chunks: [{ text: "That", role: "subject" }, { text: " doesn't mean", role: "predicate" }, { text: " lying down and becoming fooled", role: "object" }, { text: ", or ", role: "connector" }, { text: "letting foreign corporations run uncontrolled.", role: "object" }],
    trunk: "That doesn't mean lying down and becoming fooled, or letting foreign corporations run uncontrolled.",
    layers: [{ label: "否定误解", text: "That doesn't mean...：接受外资并不意味着放弃监管" }, { label: "错误一", text: "lying down and becoming fooled：消极躺平、任人欺骗" }, { label: "错误二", text: "letting foreign corporations run uncontrolled：放任外国公司不受控制地经营" }],
    grammar: ["mean 后接动名词表示‘意味着做某事’；mean to do 则表示‘打算做’。", "lying 与 becoming 并列；or 再连接 letting，三者都是否定谓语 mean 的内容。", "let + 宾语 + 动词原形；run 后的 uncontrolled 是主语补足语，说明公司处于不受控制状态。"],
    beginnerSyntax: { components: [
      { text: "That", form: "指示代词", function: "主语", modifies: "回指接受外资建设电子基础设施这一主张", explanation: "不是指某个名词，而是前一句整套做法。" },
      { text: "doesn't mean", form: "一般现在时否定谓语", function: "谓语", modifies: "排除对该主张的误解", explanation: "does 后 mean 用原形；这里 mean 是‘意味着’。" },
      { text: "lying down and becoming fooled", form: "两个动名词短语并列", function: "宾语一", modifies: "作 mean 的内容宾语", explanation: "lying down 表消极不作为，becoming fooled 表受骗；两者由 and 连接。" },
      { text: "letting foreign corporations run uncontrolled", form: "动名词 + let 宾补结构", function: "宾语二", modifies: "与前项由 or 并列，继续说明不意味着什么", explanation: "let 后接 corporations，再接 run 原形；uncontrolled 说明运行状态。" },
    ], clauses: [] },
    literal: "那并不意味着躺下任人欺骗，或者让外国公司不受控制地经营。", natural: "当然，引进外资并不等于消极听任摆布，更不等于放任外国企业毫无监管地运作。",
    logic: "预先回应‘外资会失控’的反对意见，为最终的平衡立场划出监管边界。",
    phrases: ["doesn't mean lying down", "becoming fooled", "letting foreign corporations run uncontrolled"],
  },
  {
    id: "2001-p2-s27", number: 27,
    text: "But it does mean recognizing how important they can be in building the energy and telecom infrastructures needed to take full advantage of the Internet.",
    chunks: [{ text: "But", role: "connector" }, { text: " it", role: "subject" }, { text: " does mean", role: "predicate" }, { text: " recognizing", role: "object" }, { text: " how important they can be", role: "object" }, { text: " in building the energy and telecom infrastructures", role: "modifier" }, { text: " needed to take full advantage of the Internet.", role: "modifier" }],
    trunk: "it does mean recognizing how important they can be.",
    layers: [{ label: "转折正解", text: "But it does mean recognizing...：但真正需要的是认识到……" }, { label: "认识内容", text: "how important they can be：外国公司能够多么重要" }, { label: "重要领域", text: "in building the energy and telecom infrastructures：在建设能源和电信基础设施方面" }, { label: "设施目的", text: "needed to take full advantage of the Internet：这些设施是充分利用互联网所必需的" }],
    grammar: ["does mean 是肯定句强调，和上一句 doesn't mean 构成形式对照。", "recognize 后接 how 引导的感叹式宾语从句，how important 把表语提前。", "they 回指 foreign corporations。", "in building... 表示发挥重要性的领域。", "needed... 是过去分词短语后置修饰 infrastructures；to take advantage... 是目的/需求内容。"],
    beginnerSyntax: { components: [
      { text: "But", form: "并列连词", function: "转折连接语", modifies: "连接上一句误解与本句正确含义", explanation: "结构是‘不是……，而是……’。" },
      { text: "it", form: "人称代词", function: "主句主语", modifies: "继续回指接受外资这一主张", explanation: "与上一句 That 指向相同。" },
      { text: "does mean", form: "助动词强调 + 动词原形", function: "主句谓语", modifies: "强调真正含义", explanation: "普通形式 means；does 把语气加强为‘确实意味着’。" },
      { text: "recognizing", form: "动名词", function: "主句宾语", modifies: "说明真正意味着采取什么认识", explanation: "mean doing 表示‘意味着做’，这里是认识到某件事。" },
      { text: "how important they can be", form: "how 引导的完整从句", function: "宾语从句", modifies: "作 recognizing 的宾语", explanation: "还原内部顺序 they can be important；how 把程度‘多么重要’提前。" },
      { text: "in building the energy and telecom infrastructures", form: "in + 动名词短语", function: "领域状语", modifies: "修饰 important", explanation: "说明外国公司在哪方面重要：建设能源和电信基础设施。" },
      { text: "needed to take full advantage of the Internet", form: "过去分词短语", function: "后置定语", modifies: "修饰 infrastructures", explanation: "哪些基础设施？是充分利用互联网所必需的那些。" },
    ], clauses: [
      { text: "how important they can be in building the energy and telecom infrastructures needed to take full advantage of the Internet", type: "how 引导的感叹式宾语从句", marker: "how", role: "作 recognizing 的宾语，说明要认识到的重要程度", subject: "they（= foreign corporations）", predicate: "can be", objectOrComplement: "how important（表语）；in building...（领域状语）", translationOrder: "先还原为‘外国公司可能很重要’，再把 how 译成‘多么重要’，最后接建设领域。" },
    ] },
    literal: "但它确实意味着，要认识到它们在建设充分利用互联网所需要的能源和电信基础设施方面可以有多么重要。", natural: "但我们必须认识到，外国企业在建设能源、电信等充分发挥互联网作用所必需的基础设施方面，可以发挥十分重要的作用。",
    logic: "给出全文最终的平衡结论：既不能放弃监管，也必须承认外资在建设电子基础设施中的价值。",
    phrases: ["does mean recognizing", "how important they can be", "in building the energy and telecom infrastructures", "needed to take full advantage of the Internet", "take full advantage of the Internet"],
  },
];

export const passage2001P2Questions: Question[] = [
  {
    id: 200125, number: 25, sentenceId: "2001-p2-s3",
    prompt: "Digital divide is something _______.",
    options: [
      { key: "A", text: "getting worse because of the Internet" },
      { key: "B", text: "the rich countries are responsible for" },
      { key: "C", text: "the world must guard against" },
      { key: "D", text: "considered positive today" },
    ],
    answer: "C",
    locating: "定位第 3 句 this looming danger：this 回指 digital divide，looming danger 表示正在逼近、需要警惕的危险。因此数字鸿沟是全世界必须防范的问题，选 C。",
    explanations: {
      A: "第二段明确预测数字鸿沟将 narrow rather than widen，互联网是缩小鸿沟的力量，不是使其恶化的原因。",
      B: "文章没有追究数字鸿沟由富国负责；这一选项凭空加入责任主体。",
      C: "looming danger 与 guard against 在态度上准确对应：既然是逼近的危险，就必须加以警惕和防范。",
      D: "作者认为积极的是 work against the digital divide 的力量，不是数字鸿沟本身；对象被偷换。",
    },
  },
  {
    id: 200126, number: 26, sentenceId: "2001-p2-s7",
    prompt: "Governments attach importance to the Internet because it _______.",
    options: [
      { key: "A", text: "offers economic potentials" },
      { key: "B", text: "can bring foreign funds" },
      { key: "C", text: "can soon wipe out world poverty" },
      { key: "D", text: "connects people all over the world" },
    ],
    answer: "A",
    locating: "第 7—8 句给出因果：互联网商业化后，用户越多、潜在顾客越多，各国政府担心经济竞争中掉队而推广接入。因此政府看重的是互联网的经济潜力，选 A。",
    explanations: {
      A: "potential customers 与 in the interest of business 共同说明互联网能带来商业和经济机会。",
      B: "外资在末段是建设网络基础设施的资金手段，不是第 8 句中政府重视互联网的直接原因。",
      C: "作者只说互联网 may well 是扶贫工具且 has enormous potential，并明确说它不是唯一办法；soon wipe out 夸大为很快彻底消灭。",
      D: "连接全球人口是互联网的功能和发展结果，但题目问政府重视它的原因；原文直接强调商业利益和避免落后。",
    },
  },
  {
    id: 200127, number: 27, sentenceId: "2001-p2-s18",
    prompt: "The writer mentioned the case of the United States to justify the policy of _______.",
    options: [
      { key: "A", text: "providing financial support overseas" },
      { key: "B", text: "preventing foreign capital’s control" },
      { key: "C", text: "building industrial infrastructure" },
      { key: "D", text: "accepting foreign investment" },
    ],
    answer: "D",
    locating: "例子前第 15—16 句先劝贫困国家克服对 foreign investment 的偏见；美国案例说明其工业基础设施依靠外资建成而最终仍归美国人。例子服务的政策结论是接受并利用外资，选 D。",
    explanations: {
      A: "美国案例中的资金方向是欧洲资本流入美国，不是美国向海外提供财政援助，方向相反。",
      B: "文章最后才补充不能放任外企失控；美国案例的主要论点不是‘如何防止控制’，而是外资可以帮助建设。",
      C: "建设工业基础设施只是案例中的事实内容；题目问作者用案例证明什么政策，论点位于例子前后的接受外资主张。",
      D: "美国缺少本国资本却借助外资完成建设、最终仍拥有设施，正好反驳对外资的成见并证明接受外资的合理性。",
    },
  },
  {
    id: 200128, number: 28, sentenceId: "2001-p2-s25",
    prompt: "It seems that now a country’s economy depends much on ______.",
    options: [
      { key: "A", text: "how well-developed it is electronically" },
      { key: "B", text: "whether it is prejudiced against immigrants" },
      { key: "C", text: "whether it adopts America’s industrial pattern" },
      { key: "D", text: "how much control it has over foreign corporations" },
    ],
    answer: "A",
    locating: "第 25 句把 Third Wave infrastructure 解释为 today’s electronic infrastructure，并用 the more foreign capital..., the better off... 表明电子基础设施建设越充分，经济境况越好。因此选 A。",
    explanations: {
      A: "how well-developed it is electronically 准确概括电子基础设施发展程度与 better off 之间的正相关。",
      B: "原文讨论的是对 foreign investment 的偏见，不是对 immigrants 的偏见；对象被替换。",
      C: "美国只是利用外资的历史例证，作者说同一原则可适用于别国，并未要求复制美国工业模式。",
      D: "作者主张监管外企但没有说经济主要取决于控制程度；末句强调的是外企对建设能源、电信基础设施的重要性。",
    },
  },
];
