import type { SentenceAnalysis, BeginnerSyntaxComponent as Component, BeginnerClauseDetail as Clause, SyntaxVisualRole } from "./data";
import { withReviewedSyntax } from "./reviewed-syntax";
import { cloze2001Practice } from "./2001-cloze-practice";
const c = (text: string, form: string, fn: string, modifies: string, explanation: string, children?: Component[]): Component => ({ text, form, function: fn, modifies, explanation, children });
type Model = { components: Component[]; colors: SyntaxVisualRole[]; translations: string[]; focus: string; question: string; evidence: string; answer: string };
const controls = "that will propose making payments to witnesses illegal and will strictly control the amount of publicity that can be given to a case before a trial begins";
const report = "he agreed with a committee report this year which said that self regulation did not offer sufficient control";
const after = "two days after Lord Irvine caused a storm of media protest when he said the interpretation of privacy controls contained in European legislation would be left to judges rather than to Parliament";
const interpretation = "the interpretation of privacy controls contained in European legislation would be left to judges rather than to Parliament";
const content = "introduction of the Human Rights Bill, which makes the European Convention on Human Rights legally binding in Britain, laid down that everybody was entitled to privacy and that public figures could go to court to protect themselves and their families";
const concern = "that witnesses might be encouraged exaggerate their stories in court to ensure guilty verdicts";
const models: Record<number, Model> = {
  1: { components: [c("The government", "名词短语", "主语", "is to ban", "政府宣布措施。"), c("is to ban", "be to do", "谓语", "government", "官方计划安排，不把is单独当系词。"), c("payments to witnesses by newspapers seeking to buy up people involved in prominent cases such as the trial of Rosemary West", "名词及多层后置限定", "宾语", "ban", "禁止对象为付款；逐层辨明谁付款、付给谁、哪类人。", [c("to witnesses", "介词短语", "收款对象补足", "payments", "证人是收款人。"), c("by newspapers seeking to buy up people involved in prominent cases such as the trial of Rosemary West", "介词及分词修饰", "付款施事补足", "payments", "付款者为报纸媒体，不是证人。", [c("seeking to buy up people involved in prominent cases such as the trial of Rosemary West", "现在分词", "后置定语", "newspapers", "seeking的执行者是报纸媒体。", [c("to buy up people involved in prominent cases such as the trial of Rosemary West", "不定式", "seeking的补足语", "seeking", "寻求买断相关人的独家讲述。", [c("people involved in prominent cases such as the trial of Rosemary West", "名词及分词限定", "宾语", "buy up", "被收买的是与案件有关的人。", [c("involved in prominent cases such as the trial of Rosemary West", "过去分词", "后置定语", "people", "这些人涉及重大案件，involved没有独立时态。", [c("such as the trial of Rosemary West", "举例介词表达", "实例补充", "cases", "以审判举例，不是另一个有限分句。")])])])])])])], colors: ["subject", "predicate", "object"], translations: ["政府", "计划禁止", "报纸向证人付款；这些媒体试图买断与重大案件有关者的独家讲述，例如罗斯玛丽·韦斯特审判案"], focus: "payments的to与by分清收款人与付款人，两层分词分别修饰newspapers与people。", question: "谁付钱、谁收钱，seeking与involved分别修饰谁？", evidence: "payments to witnesses by newspapers seeking to buy up people involved", answer: "newspapers付款、witnesses收款；seeking修饰newspapers，involved修饰people。buy up在此指买断独家讲述，并非合法买卖人口。" },
  2: { components: [c("In a significant tightening of legal controls over the press", "介词短语", "背景状语", "will introduce", "监管趋严这一背景；over补足controls对象。"), c("Lord Irvine", "人名", "主语", "will introduce", "提出法案的人。"), c("the Lord Chancellor", "名词短语", "同位语", "Lord Irvine", "介绍同一人的职务。"), c("will introduce", "将来谓语", "谓语", "Lord Irvine", "准备提出，未声称法案已通过。"), c("a draft bill", "名词短语", "宾语", "introduce", "draft为名词定语，法案草案。"), c(controls, "定语从句", "后置定语", "bill", "that代表bill，同时支配propose和control。", [c("that", "关系代词", "从句主语", "will propose / will control", "指法案。"), c("will propose", "将来谓语", "从句谓语一", "that", "提出建议。"), c("making payments to witnesses illegal", "动名词及宾补", "宾语一", "propose", "propose doing，不是propose to加宾语。", [c("payments to witnesses", "名词短语", "宾语", "making", "被规定法律性质的付款行为。"), c("illegal", "形容词", "宾语补足语", "payments", "说明付款将被定为违法。")]), c("and will strictly control", "并列连词与谓语", "从句谓语二", "that", "与will propose共用关系主语。"), c("the amount of publicity that can be given to a case before a trial begins", "名词及关系从句", "宾语二", "control", "限制报道量，不是限制受欢迎程度。", [c("that can be given to a case before a trial begins", "被动关系从句", "后置定语", "publicity", "that承接publicity作主语。", [c("before a trial begins", "时间从句", "时间状语", "can be given", "a trial为主语，begins为谓语，限定庭前。")])])])], colors: ["modifier", "subject", "modifier", "predicate", "object", "modifier"], translations: ["作为明显收紧新闻法律监管的举措", "欧文勋爵", "也就是大法官", "将提出", "一份法案草案", "拟将向证人付款定为非法，并严格限制开庭前案件可以获得的公开报道量"], focus: "bill的关系从句有两个并列谓语，publicity再带被动关系从句与时间边界。", question: "making后谁是宾语、谁是宾补，will control是否仍属于法案内容？", evidence: "making payments to witnesses illegal and will strictly control", answer: "payments to witnesses作making宾语，illegal作宾补；will control与will propose同属that从句，共用bill为主语。" },
  3: { components: [c("In a letter to Gerald Kaufman", "介词短语", "信息出处状语", "said", "信的收件人为Kaufman。"), c("chairman of the House of Commons media select committee", "名词短语", "同位语", "Gerald Kaufman", "委员会主席指收件人，不是后面说话的Irvine。"), c("Lord Irvine", "人名", "主语", "said", "报道的发言人。"), c("said", "过去式", "谓语", "Lord Irvine", "后省略内容连接词that。"), c(report, "内容从句", "宾语从句", "said", "完整内容含报告观点，不能在year处截断。", [c("he", "代词", "主语", "agreed", "回指Irvine。"), c("agreed", "过去式", "谓语", "he", "赞同观点。"), c("with a committee report this year which said that self regulation did not offer sufficient control", "介词及嵌套关系从句", "赞同对象补足", "agreed", "报告是观点来源。", [c("which said that self regulation did not offer sufficient control", "关系从句", "后置定语", "report", "which代报告作said主语。", [c("that self regulation did not offer sufficient control", "内容从句", "宾语从句", "which said", "报告认为自律监管不足。", [c("self regulation", "名词短语", "主语", "did not offer", "行业自律。"), c("did not offer", "过去时否定", "谓语", "self regulation", "did承担时态，offer用原形。"), c("sufficient control", "名词短语", "宾语", "offer", "足够的监管。")])])])])], colors: ["modifier", "modifier", "subject", "predicate", "object"], translations: ["在致杰拉尔德·考夫曼的信中", "考夫曼是下议院媒体特别委员会主席", "欧文勋爵", "表示", "他同意委员会今年的一份报告；报告认为行业自律不足以提供充分监管"], focus: "Irvine说→同意报告→报告说，三层观点依次嵌套。", question: "which接report还是year，监管不足是谁的结论？", evidence: "a committee report this year which said that self regulation did not offer sufficient control", answer: "which承接report；自律不足先是委员会报告的结论，Irvine明确赞同。chairman职务属于Kaufman，不能接错人物。" },
  4: { components: [c("Publication of the letter", "名词化短语", "主语", "came", "公开发表这一事件，不是信件走来。"), c("came", "过去式", "谓语", "Publication", "发生。"), c(after, "时间差及嵌套从句", "时间状语", "came", "公开发生在抗议风波之后两天。", [c("after Lord Irvine caused a storm of media protest when he said the interpretation of privacy controls contained in European legislation would be left to judges rather than to Parliament", "after从句", "时间参照从句", "two days / came", "风波为相对时间起点。", [c("Lord Irvine", "人名", "主语", "caused", "引发争议者。"), c("caused", "过去式", "谓语", "Irvine", "引发。"), c("a storm of media protest", "名词短语", "宾语", "caused", "大量强烈抗议的比喻。"), c("when he said the interpretation of privacy controls contained in European legislation would be left to judges rather than to Parliament", "when从句", "时间状语从句", "caused", "说明引发风波时的表态。", [c("he said", "主谓组", "从句主谓", "when", "he为Irvine，said引出内容。"), c(interpretation, "省略that的内容从句", "宾语从句", "said", "真正被交付的是解释工作。", [c("the interpretation of privacy controls contained in European legislation", "名词及分词限定", "主语", "would be left", "中心词interpretation；contained只修饰controls。", [c("contained in European legislation", "过去分词", "后置定语", "privacy controls", "写在欧洲法律里的规定，不是独立谓语。")]), c("would be left", "过去将来被动", "谓语", "interpretation", "将由某方处理。"), c("to judges rather than to Parliament", "并列取舍介词短语", "承接者补足", "left", "选择法官而非议会，两个to保持平行。")])])])])], colors: ["subject", "predicate", "modifier"], translations: ["这封信的公开发表", "发生在", "欧文勋爵引发媒体抗议风波的两天后；他当时表示，欧洲立法中隐私规定的解释将交给法官而非议会"], focus: "after→when→said内容逐层展开，contained不是长主语之后的限定谓语。", question: "两天连接哪两个事件，interpretation之后的真正谓语在哪里？", evidence: "Publication of the letter came two days after Lord Irvine caused a storm of media protest", answer: "先有表态和抗议，后有信件公开，相隔两天；内容从句的谓语是would be left，contained后置限定controls。" },
  5: { components: [c("The Lord Chancellor", "名词短语", "主语", "said", "大法官Irvine。"), c("said", "过去式", "谓语", "Chancellor", "外层报道动词。"), c(content, "省略that的内容从句", "宾语从句", "said", "内部introduction作主语，laid down为谓语。", [c("introduction of the Human Rights Bill", "名词化短语", "主语", "laid down", "法案引入这一事件。"), c("which makes the European Convention on Human Rights legally binding in Britain", "非限制性关系从句", "定语从句", "the Human Rights Bill", "which回指法案，区别后文introduction的谓语。", [c("which", "关系代词", "主语", "makes", "指Bill。"), c("makes", "使役动词", "谓语", "which", "使公约取得某种状态。"), c("the European Convention on Human Rights", "文件名词短语", "宾语", "makes", "欧洲人权公约，不是本法案的另一名称。"), c("legally binding", "副词加形容词", "宾语补足语", "Convention", "具有法律约束力，binding不是进行时。"), c("in Britain", "介词短语", "效力范围", "legally binding", "在英国的效力。")]), c("laid down", "过去式短语动词", "谓语", "introduction", "正式规定。"), c("that everybody was entitled to privacy", "内容从句", "宾语从句一", "laid down", "everybody主语，was entitled系表，to privacy为权利内容。"), c("and", "连词", "并列连接语", "两个that从句", "连接两项规定，不接到which从句。"), c("that public figures could go to court to protect themselves and their families", "内容从句及目的不定式", "宾语从句二", "laid down", "另一项规定。", [c("public figures", "名词短语", "主语", "could go", "公众人物。"), c("could go", "情态动词加原形", "谓语", "public figures", "有途径诉诸法院。"), c("to court", "介词短语", "方向补足", "go", "court为名词。"), c("to protect themselves and their families", "不定式", "目的状语", "go to court", "protect为动词，themselves及families为并列宾语。")])])], colors: ["subject", "predicate", "object"], translations: ["大法官", "表示", "《人权法案》的引入明确规定人人享有隐私权，公众人物可诉诸法院保护自己和家人；这项法案使《欧洲人权公约》在英国具有法律约束力"], focus: "said外层内容内有which解释法案及laid down的两项并列规定。", question: "which与两个that各接什么，binding为何是宾补？", evidence: "which makes the European Convention on Human Rights legally binding in Britain", answer: "which修饰Bill；两个that同作laid down的内容。Convention是make宾语，binding是它被赋予的状态，不是另一个谓语。" },
  6: { components: [c("Press freedoms will be in safe hands with our British judges", "直接引语", "报道内容", "said", "这是大法官的保证，区别记者的独立事实判断。", [c("Press freedoms", "名词短语", "主语", "will be", "新闻自由。"), c("will be", "将来系动词", "谓语", "freedoms", "预期状态。"), c("in safe hands", "习语介词短语", "表语", "will be", "可靠掌管之下。"), c("with our British judges", "介词短语", "责任归属补充", "in safe hands", "由英国法官负责，没有with宾语加分词。")]), c("he", "代词", "报道语主语", "said", "回指Irvine。"), c("said", "过去式", "报道语谓语", "he", "引语后说明谁说。")], colors: ["object", "subject", "predicate"], translations: ["‘新闻自由将由我们的英国法官妥善掌管’", "他", "说"], focus: "引语内部为系表判断，with说明负责者而非被动施事。", question: "safe hands是否真指双手，这个保证属于谁？", evidence: "in safe hands with our British judges", answer: "in safe hands表示由可靠的人掌管；是Irvine对法官的保证，不能写成作者证实法官永远不会损害新闻自由。" },
  7: { components: [c("Witness payments", "名词短语", "主语", "became", "向证人付款的做法。"), c("became", "系动词过去式", "谓语", "payments", "状态变化。"), c("an issue", "名词短语", "表语", "became", "引发公共争议的问题。"), c("after West was sentenced to 10 life sentences in 1995", "时间从句", "时间状语从句", "became", "回溯付费引发争议的判决背景。", [c("West", "人名", "主语", "was sentenced", "被判刑者。"), c("was sentenced", "过去时被动", "谓语", "West", "sentence此处为动词判刑。"), c("to 10 life sentences", "介词短语", "刑罚补足", "sentenced", "sentences为名词刑期，不是语法句子。"), c("in 1995", "介词短语", "时间状语", "was sentenced", "年份对应判决。")])], colors: ["subject", "predicate", "complement", "modifier"], translations: ["向证人付款的做法", "成为", "一个争议问题", "是在韦斯特于1995年被判十项无期徒刑之后"], focus: "became后是表语，sentence的动词与名词在同句中分工。", question: "issue是一次事故还是争议问题，1995修饰哪个事件？", evidence: "became an issue after West was sentenced to 10 life sentences in 1995", answer: "issue是争议问题；1995直接限定West被判刑的时间，不是信件公开或政府提出法案的精确日期。" },
  8: { components: [c("Up to 19 witnesses", "数量范围名词短语", "主语", "were said", "最多达到19人，不是至少19人。"), c("were said", "过去时报道被动", "谓语", "witnesses", "据说，保留消息来源的不确定性。"), c("to have received payments for telling their stories to newspapers", "完成不定式", "主语补足语", "witnesses", "收钱早于报道，不补作新的有限从句。", [c("payments", "复数名词", "宾语", "have received", "收取的款项。"), c("for telling their stories to newspapers", "介词及动名词", "报酬缘由补足", "payments", "为讲述故事收钱。", [c("their stories", "名词短语", "宾语", "telling", "证人的经历讲述。"), c("to newspapers", "介词短语", "听者补足", "telling", "媒体为接收者，不是收款者。")])])], colors: ["subject", "predicate", "complement"], translations: ["多达19名证人", "据说", "此前因向报纸讲述自己的故事而收到报酬"], focus: "to have received是完成不定式，时间先于were said，不是过去完成时谓语。", question: "报道与收款谁先发生，telling的执行者是谁？", evidence: "were said to have received payments for telling their stories to newspapers", answer: "先收款、后有报道；telling执行者为witnesses，to newspapers说明讲给媒体。报道结构不等于已司法确认每位证人收款。" },
  9: { components: [c("Concerns", "复数名词", "主语", "were raised", "被提出的是担忧。"), c("were raised", "过去时被动", "谓语", "Concerns", "没有给出具体提出者。"), c(concern, "与名词分隔的内容从句", "同位内容从句", "Concerns", "that补足担忧命题，内部原卷缺to须单独提示。", [c("that", "内容连接词", "连接语", "Concerns与命题", "不充当从句主宾语。"), c("witnesses", "复数名词", "主语", "might be encouraged", "可能受到诱导的人。"), c("might be encouraged", "情态被动", "谓语", "witnesses", "只说可能受到诱导，并未断言确有作伪证。"), c("exaggerate their stories", "原卷缺少to的不定式位置", "补足动作（原卷异常）", "encouraged", "规范式为be encouraged to exaggerate；不补写to回原文，也不教成encourage可接裸不定式。", [c("their stories", "名词短语", "宾语", "exaggerate", "可能被夸大的讲述。")]), c("in court", "介词短语", "场所状语", "exaggerate", "夸大可能发生在法庭。"), c("to ensure guilty verdicts", "不定式", "目的状语", "exaggerate", "为促成有罪裁决，不是付款行为的直接宾语。")])], colors: ["subject", "predicate", "modifier"], translations: ["担忧", "被提出", "证人可能受到诱导，在法庭夸大自己的讲述，以促成有罪裁决"], focus: "that解释担忧内容，might保留可能性；原卷encouraged后缺to，规范结构须明示。", question: "that是否代concerns作主语，原卷exaggerate前的异常怎样处理？", evidence: "that witnesses might be encouraged exaggerate their stories", answer: "that只连接内容，witnesses已作主语。原卷缺规范结构需要的to，保留源文并解释应读be encouraged to exaggerate，不能归纳为被动后用裸动词。" },
};
const details: Record<number, Clause["predicateDetails"][]> = {
  1: [],
  2: [[{ function: "宾语一", text: "making payments to witnesses illegal" }, { function: "宾语二", text: "the amount of publicity that can be given to a case before a trial begins" }], [], []],
  3: [[], [{ function: "宾语", text: "that self regulation did not offer sufficient control" }], [{ function: "宾语", text: "sufficient control" }]],
  4: [[{ function: "宾语", text: "a storm of media protest" }], [{ function: "宾语", text: interpretation }], []],
  5: [[{ function: "并列宾语从句", text: "that everybody was entitled to privacy and that public figures could go to court to protect themselves and their families" }], [{ function: "宾语", text: "the European Convention on Human Rights" }, { function: "宾语补足语", text: "legally binding" }], [{ function: "表语", text: "entitled to privacy" }], []],
  6: [[{ function: "表语", text: "in safe hands" }]], 7: [[]], 8: [], 9: [[{ function: "主语补足动作（原卷缺to）", text: "exaggerate their stories" }]],
};
export function upgradeCloze2001(draft: SentenceAnalysis): SentenceAnalysis {
  const model = models[draft.number];
  const clauses = draft.beginnerSyntax!.clauses.map((old, i) => { const { objectOrComplement: _old, ...clause } = old; return { ...clause, predicateDetails: details[draft.number][i], ...(draft.number === 2 && i === 1 ? { text: "that can be given to a case before a trial begins" } : {}), ...(draft.number === 5 && i === 2 ? { predicate: "was", subject: "everybody" } : {}) }; });
  const reviewed = withReviewedSyntax({ ...draft, phrases: draft.number === 5 ? [...draft.phrases, "public figures"] : draft.phrases, beginnerSyntax: { components: model.components, clauses, reading: { focus: model.focus, questions: [{ question: model.question, evidence: model.evidence, answer: model.answer }] } }, practice: cloze2001Practice[draft.id] }, model.colors);
  return { ...reviewed, translationAlignment: reviewed.chunks.map((block, i) => ({ english: block.text, chinese: model.translations[i] })), translationNotes: draft.number === 1 ? ["buy up people按新闻付费语境补明为买断独家讲述，不作人口交易理解。"] : draft.number === 9 ? ["中文按上下文意图解释；原卷encouraged与exaggerate之间缺to，规范表达仅在讲解中补示。"] : undefined };
}
