import type { PhraseKnowledge, WordKnowledge } from "./knowledge-base";

type PhraseSeed = readonly [
  key: string, source: string, canonical: string, type: string, meaning: string,
  grammarRole: string, rule: string, exampleEnglish: string, exampleChinese: string, pitfall: string,
];

const seeds: PhraseSeed[] = [
  ["great-deal-attention", "A great deal of attention", "a great deal of + uncountable noun", "数量结构", "大量注意力", "被动句主语", "a great deal of 直接修饰不可数名词；attention 在本义下不可数。", "A great deal of attention was paid to the issue.", "这一问题受到了高度关注。", "不能直接修饰可数名词复数；可数复数通常用 a great many。"],
  ["attention-paid-to", "is being paid today to", "pay attention to / attention be paid to", "动词搭配及被动结构", "今天正受到关注", "现在进行时被动谓语和对象介词", "pay attention to 的被动可写 attention is being paid to；to 是介词。", "More attention is being paid to access.", "网络接入正受到更多关注。", "不能漏掉 to，也不要把 pay 只译成‘付款’。"],
  ["so-called-digital-divide", "the so-called digital divide", "the so-called + term", "名词短语", "所谓的数字鸿沟", "介词 to 的宾语", "so-called 放在术语前，表示‘所谓的/通常所称的’，语气可中性也可带保留。", "The so-called digital divide remains serious.", "所谓的数字鸿沟仍很严重。", "so-called 不等于‘错误地称为’，是否带讽刺要看语境。"],
  ["division-world-info", "the division of the world into the info (information) rich and the info poor", "the division of A into B and C", "同位解释结构", "把世界分成信息富裕者和信息贫困者", "破折号后同位解释 digital divide", "division of A into B and C 表 A 被划分成 B、C；两项要保持平行。", "The division of society into the connected and unconnected creates inequality.", "社会被分成联网者与未联网者会造成不平等。", "不要把 the rich/the poor 当作单数个人。"],
  ["does-exist-today", "does exist today", "do/does/did + verb", "强调谓语结构", "今天确实存在", "一般现在时强调谓语", "肯定句中 does 强调动作或状态；后面的实义动词用原形。", "The divide does exist today.", "这种鸿沟今天确实存在。", "不能写 does exists。"],
  ["lecture-looming-danger", "lectured about this looming danger", "lecture about/on + topic", "动词介词搭配", "就这一逼近的危险发表演讲", "主句谓语和主题状语", "lecture about/on 引出演讲主题；looming 表危险逐渐逼近。", "They lectured about the looming crisis.", "他们就日益逼近的危机发表了演讲。", "lecture 在此不是‘责骂’；具体含义由 about 后主题判断。"],
  ["twenty-years-ago", "twenty years ago", "time span + ago", "时间状语", "二十年前", "修饰一般过去时 lectured", "ago 以说话时为基点向前回溯，通常与一般过去时连用。", "They raised the issue twenty years ago.", "他们二十年前就提出了这个问题。", "ago 与 before 的基准点不同，不能机械互换。"],
  ["less-visible-then", "less visible then", "less + adjective + then", "比较级表语", "当时不那么明显", "What 从句的表语与时间状语", "less visible 表可见程度较低；then 指前述二十年前。", "The positive forces were less visible then.", "这些积极力量当时不太明显。", "visible 不只表示肉眼可见，也可表示容易察觉。"],
  ["new-positive-forces", "the new, positive forces", "coordinated adjectives + noun", "名词短语", "新的积极力量", "主句表语", "new 与 positive 并列修饰 forces，逗号表示两个独立性质。", "New, positive forces began to appear.", "新的积极力量开始出现。", "逗号不表示 new 修饰 positive。"],
  ["work-against-divide", "work against the digital divide", "work against + problem/tendency", "动词介词搭配", "发挥抵消数字鸿沟的作用", "定语从句谓语", "work against 表与某趋势相反、阻碍其发展。", "These policies work against inequality.", "这些政策有助于抵消不平等。", "不一定表示主观‘工作反对’，也可表示客观反作用。"],
  ["reasons-optimistic", "reasons to be optimistic", "reason(s) to do / for doing", "不定式后置定语", "保持乐观的理由", "There be 句实际主语", "reason to do 说明有理由采取某态度或行动。", "There are reasons to be optimistic.", "我们有理由保持乐观。", "reason for doing 常说明做某事的原因，语义角度不同。"],
  ["technological-reasons-hope", "technological reasons to hope", "reason(s) to hope + clause", "名词不定式结构", "从技术层面有理由希望", "存在句实际主语及后置定语", "to hope 后可接省略 that 的宾语从句。", "There are technological reasons to hope access will expand.", "从技术层面看，有理由期待接入范围扩大。", "hope 后不能使用 hope sb to do。"],
  ["hope-to-do", "hope to do sth", "hope to do sth", "动词不定式搭配", "希望做某事", "谓语动词与不定式宾语", "hope to do 表主语希望自己完成仍有可能实现的事。", "We hope to narrow the divide.", "我们希望缩小这一鸿沟。", "不能说 hope sb to do；若希望别人做某事，用 hope that sb will do。"],
  ["hope-that", "hope that...", "hope (that) + clause", "动词与宾语从句", "希望……；期待……", "谓语动词与内容宾语从句", "that 可以省略；从句通常陈述仍有可能发生的未来结果。", "We hope that access will expand.", "我们希望接入范围会扩大。", "与 wish that 的非现实或遗憾语气不同，hope 通常指仍可能实现的事。"],
  ["hope-for", "hope for sth", "hope for + noun", "动词介词搭配", "期望得到某事物", "不及物用法与介词宾语", "hope for 后接名词或代词，表示期待某个结果或事物。", "They hope for wider access.", "他们期待更广泛的接入。", "若后接完整句子，不使用 for，应写 hope (that)...。"],
  ["in-hope-of", "in the hope of doing", "in the hope of doing sth", "介词短语", "怀着做某事的希望；希望借此……", "目的状语", "of 是介词，后接动名词；整个短语说明行动目的。", "They invested in the hope of earning a return.", "他们进行投资，希望借此获得回报。", "不能写 in the hope to do。"],
  ["divide-will-narrow", "the digital divide will narrow", "gap/divide + narrow", "主谓搭配", "数字鸿沟将缩小", "hope/believe 的宾语从句", "narrow 可作不及物动词，主语是差距、范围或选择。", "The gap will narrow over time.", "这一差距会随时间缩小。", "不要因 narrow 常作形容词而漏判谓语。"],
  ["more-commercialized", "more and more commercialized", "more and more + adjective/past participle", "渐进比较结构", "越来越商业化", "As 从句表语", "more and more 表程度持续增强；commercialized 描述商业化状态。", "The Internet became more and more commercialized.", "互联网变得越来越商业化。", "不能写 more commercialized and more。"],
  ["interest-business", "in the interest of business", "in the interest(s) of + person/group", "利益搭配", "符合商业利益", "主句介词表语", "表示某做法有利于某人或群体；business 此处泛指商业界。", "Wider access is in the interest of business.", "更广泛的接入符合商业利益。", "interest 在此是利益，不是兴趣或利息。"],
  ["universalize-access", "to universalize access", "universalize + access/service", "不定式及动宾搭配", "使接入普及", "it 形式主语后的真正主语", "universalize 是及物动词，表示使某项服务人人可得。", "The policy aims to universalize Internet access.", "该政策旨在普及互联网接入。", "access 在此不可数，不说 an access。"],
  ["after-all-2001p2", "after all", "after all", "解释连接语", "毕竟", "破折号后原因说明连接语", "用于提醒读者一个能支持前述结论的已知事实。", "After all, more users mean more customers.", "毕竟，用户越多就意味着顾客越多。", "不要逐字译成‘在一切之后’。"],
  ["more-people-customers", "the more people online, the more potential customers there are", "the more..., the more...", "比较级相关结构", "上网人数越多，潜在顾客越多", "解释商业利益的正相关原因", "两部分都用 the + 比较级；第一部分 people 后省略 are。", "The more people online, the larger the market becomes.", "上网的人越多，市场就越大。", "the 不能省略；它不是定冠词的普通用法。"],
  ["more-governments", "More and more governments", "more and more + plural noun", "数量渐增结构", "越来越多的政府", "主句主语", "more and more 直接修饰复数可数名词，表示数量持续增加。", "More and more governments support access.", "越来越多的政府支持网络普及。", "不可写 more and more government。"],
  ["left-behind", "be left behind", "leave sb/sth behind / be left behind", "短语动词及被动", "落后；被甩在后面", "afraid 内容从句的被动谓语", "主动 leave sb behind；被动 sb be left behind，抽象语境常表示发展落后。", "No country wants to be left behind.", "没有国家愿意掉队。", "不一定表示把物品遗忘，需看竞争语境。"],
  ["spread-internet-access", "spread Internet access", "spread/expand Internet access", "动宾搭配", "推广、普及互联网接入", "want to 后的动作与宾语", "spread 在此为及物动词，表示把接入机会扩展到更大范围。", "Governments want to spread Internet access.", "各国政府希望普及互联网接入。", "access 通常不可数。"],
  ["within-decade-two", "Within the next decade or two", "within + future time span", "时间范围状语", "在未来十到二十年内", "修饰将来时谓语", "within 表不超过该时间范围；a decade or two 是一二十年。", "The network will expand within the next decade.", "网络将在未来十年内扩展。", "within 强调期限内，不等于 throughout‘贯穿全程’。"],
  ["on-planet", "on the planet", "on the planet", "地点/范围短语", "在地球上；全球", "后置限定 people", "在全球人口语境中相当于 in the world。", "Billions of people on the planet need access.", "全球数十亿人需要接入机会。", "planet 前在此用 the，特指地球。"],
  ["netted-together", "will be netted together", "be networked/netted together", "将来时被动结构", "将通过网络连接起来", "句子谓语", "will be + 过去分词构成将来时被动；net 在此动词化。", "More people will be netted together.", "更多人将被网络连接起来。", "原卷 he 是排印错误，正确助动词必须是 be。"],
  ["as-result-2001p2", "As a result", "as a result", "结果连接语", "因此；结果", "句首结果状语", "总结前述原因并引出其结果；常用逗号与主句隔开。", "As a result, access expanded.", "因此，接入范围扩大了。", "as a result of 后必须接名词；本句没有 of。"],
  ["narrow-rather-widen", "narrow rather than widen", "A rather than B", "取舍并列结构", "缩小而不是扩大", "will 后两个并列动词", "rather than 连接同级成分；narrow 与 widen 共用 will。", "The divide may narrow rather than widen.", "这一鸿沟可能缩小而非扩大。", "两侧要保持语法平行。"],
  ["years-ahead", "in the years ahead", "in the time/years ahead", "时间状语", "在未来的岁月中", "修饰 will narrow", "ahead 后置修饰 years，表示从现在往后的时间。", "Conditions may improve in the years ahead.", "未来几年情况可能改善。", "不要译成空间上的‘前面的年份’。"],
  ["very-good-news", "very good news", "good news", "不可数名词搭配", "非常好的消息", "系表句名词表语", "news 形式有 -s 但通常作不可数单数名词。", "That is very good news.", "那是非常好的消息。", "不能说 a good news；可说 a piece of good news。"],
  ["may-well-be", "may well be", "may/might well + verb", "情态强调结构", "很可能是；完全有理由是", "原因从句谓语", "may well 表有充分理由认为某事很可能成立。", "The Internet may well be a powerful tool.", "互联网很可能是一种强大工具。", "不要拆译成‘可能很好地是’。"],
  ["powerful-tool-poverty", "the most powerful tool for combating world poverty", "a tool for doing sth", "最高级名词结构", "抗击世界贫困的最有力工具", "because 从句表语", "for + doing 后置说明工具用途；最高级前用 the。", "Education is a powerful tool for combating poverty.", "教育是抗击贫困的有力工具。", "combat 本身及物，不需要 combat against poverty。"],
  ["ever-had", "that we’ve ever had", "superlative + noun + that ... ever ...", "最高级定语从句", "我们迄今拥有过的", "限制 the most powerful tool 的定语从句", "最高级后常接 that 从句限定比较范围；that 在从句中作宾语。", "It is the best tool that we have ever had.", "这是我们迄今拥有过的最好工具。", "ever 强化时间范围，不等于 always。"],
  ["of-course-2001p2", "Of course", "of course", "句子副词短语", "当然", "让步承认状语", "用于承认一个显而易见的限制，再继续论证。", "Of course, technology is not the only answer.", "当然，技术不是唯一答案。", "语气可能显得强势，正式交流中需结合语境。"],
  ["use-internet", "the use of the Internet", "the use of + tool/system", "名词化结构", "互联网的使用；利用互联网", "句子主语", "中心词 use 是名词；of 引出被使用的对象。", "The use of the Internet can reduce costs.", "利用互联网可以降低成本。", "名词 use 读 /juːs/，动词 use 读 /juːz/。"],
  ["only-way-defeat", "the only way to defeat poverty", "the way to do sth", "不定式后置定语", "战胜贫困的唯一办法", "系表句表语", "to do 后置修饰 way，说明办法要达成的目标。", "This is not the only way to reduce poverty.", "这不是减少贫困的唯一办法。", "否定 only 表‘不是唯一’，不等于‘完全不是办法’。"],
  ["only-tool-have", "the only tool we have", "noun + (that/which) + clause", "省略关系词的定语结构", "我们拥有的唯一工具", "系表句表语", "we have 前省略作宾语的 that/which。", "The Internet is not the only tool we have.", "互联网不是我们拥有的唯一工具。", "不要把 we have 误判为新的主句。"],
  ["enormous-potential", "has enormous potential", "have enormous/great potential", "动宾搭配", "具有巨大潜力", "短句谓语和宾语", "potential 在本义下通常不可数；have potential to do/for sth。", "The technology has enormous potential.", "这项技术潜力巨大。", "potential 表尚未完全实现的可能性，不等于现有效果。"],
  ["take-advantage-tool", "To take advantage of this tool", "take advantage of + noun", "不定式目的结构", "为了利用这一工具", "句首目的状语", "take advantage of 在中性语境表示充分利用；对人可含占便宜义。", "Countries must invest to take advantage of this tool.", "各国必须投资以利用这一工具。", "不能漏掉 of。"],
  ["impoverished-countries", "impoverished countries", "impoverished + country/community", "形容词名词搭配", "贫困国家", "主句主语", "impoverished 强调因资源匮乏而处于贫困状态，比 poor 更正式。", "Impoverished countries need infrastructure.", "贫困国家需要基础设施。", "impoverished 不等于 developing；发展中国家未必贫困。"],
  ["get-over-prejudices", "get over their outdated anti-colonial prejudices", "get over + obstacle/prejudice", "短语动词", "克服陈旧的反殖民偏见", "主句谓语和宾语", "get over 可表示克服困难、偏见或从疾病中恢复。", "They must get over outdated prejudices.", "他们必须克服陈旧偏见。", "具体义由宾语决定；不能机械译成‘越过’。"],
  ["respect-foreign-investment", "with respect to foreign investment", "with respect to + noun", "正式介词短语", "关于外国投资；就外资而言", "后置限定 prejudices", "等于 regarding/concerning，正式说明话题或对象。", "Attitudes with respect to foreign investment changed.", "对外资的态度发生了变化。", "with all due respect 是另一固定表达。"],
  ["foreign-investment", "foreign investment", "foreign investment/capital", "经济名词搭配", "外国投资；外资", "多个句子的核心名词概念", "investment 指投资行为或投入资本；可作不可数概念，也可指具体投资项目。", "Foreign investment helped build the ports.", "外资帮助建设了这些港口。", "foreign investment 不等于 foreign aid；前者通常追求投资回报。"],
  ["invasion-sovereignty", "an invasion of their sovereignty", "an invasion of + territory/privacy/sovereignty", "名词介词搭配", "对国家主权的侵犯", "think 宾语从句表语", "invasion 可指武力入侵，也可抽象指侵害权利、隐私或主权。", "They saw the policy as an invasion of sovereignty.", "他们把这项政策视为对主权的侵犯。", "不要只按军事‘侵略’理解。"],
  ["might-well-study", "might well study", "might well + verb", "委婉建议结构", "不妨研究；大可以考察", "主句谓语", "在劝说语境中 might well 接近 had better，但语气更委婉。", "Such countries might well study history.", "这些国家不妨研究一下历史。", "与 may well 表‘很可能’需结合语境区分。"],
  ["history-infrastructure", "the history of infrastructure", "the history of + field/system", "名词 of 结构", "基础设施建设史", "study 的宾语", "history of 引出被研究的发展对象。", "The history of infrastructure offers lessons.", "基础设施建设史提供了经验。", "history 不一定只指历史学科，也可指发展历程。"],
  ["structural-foundations", "the basic structural foundations of a society", "the foundations of + system/society", "同位术语解释", "一个社会的基本结构基础", "括号解释 infrastructure", "foundation 可指具体地基，也可指制度或社会运行基础。", "Energy is one of the structural foundations of society.", "能源是社会结构基础之一。", "foundation 与 infrastructure 有交叉，但并非所有语境都可互换。"],
  ["in-united-states", "in the United States", "in + country", "地点/范围状语", "在美国；美国范围内", "限定基础设施历史", "国家名前通常按固定国名使用冠词；the United States 必须带 the。", "The system developed in the United States.", "该体系在美国发展起来。", "不能省略 United States 前的 the。"],
  ["built-industrial-infrastructure", "built its industrial infrastructure", "build + infrastructure", "动宾搭配", "建设工业基础设施", "When 从句谓语和宾语", "infrastructure 常作不可数集合名词；build 表建设形成。", "The country built its industrial infrastructure.", "这个国家建设了自己的工业基础设施。", "不要随意写 infrastructures，除非强调不同系统类别。"],
  ["capital-do-so", "have the capital to do so", "have the capital to do sth", "资金与不定式结构", "拥有做这件事所需的资本", "主句谓语、宾语及用途定语", "capital 后不定式说明资本用途；do so 代替前述动作。", "They lacked the capital to do so.", "他们缺少这样做所需的资本。", "capital 在此不是首都或大写字母。"],
  ["funds-do-so", "have the funds to do so", "have the funds to do sth", "动宾与不定式定语", "拥有做某事所需的资金", "have 的宾语与资金用途说明", "funds 在资金义下常用复数；to do sth 说明这笔钱用于什么。", "The country did not have the funds to expand access.", "该国没有扩大接入所需的资金。", "与 capital 相比，funds 更强调眼下可以动用的款项。"],
  ["fund-infrastructure", "fund infrastructure", "fund + project/infrastructure", "动宾搭配", "为基础设施提供资金", "及物动词与宾语", "fund 作动词直接接被资助的项目、机构或活动。", "Foreign investors helped fund the infrastructure.", "外国投资者帮助为基础设施提供资金。", "fund 侧重出资；finance 还可强调组织或安排融资。"],
  ["depend-on-2001p2", "depend on", "depend on + factor/person", "动词介词搭配", "取决于；依赖", "不及物动词与介词补足语", "depend 不能直接接决定因素，必须用 on 引出条件或依赖对象。", "Economic growth depends on sound policy.", "经济增长取决于稳健的政策。", "不要漏掉 on；表示‘依靠某人做某事’可用 depend on sb to do sth。"],
  ["attach-importance", "attach importance to", "attach importance to + noun/doing", "动词搭配", "重视；认为……重要", "及物动词、宾语与对象介词", "attach 的宾语是 importance，再由 to 引出受到重视的对象。", "Governments attach importance to Internet access.", "各国政府重视互联网接入。", "to 是介词，后接名词、代词或动名词；不能写 attach important to。"],
  ["wipe-out-2001p2", "wipe out", "wipe out + problem/group", "短语动词", "彻底消灭；摧毁", "及物短语动词与宾语", "wipe out 强调完全清除，语气比 reduce 或 combat 强得多。", "Technology alone cannot wipe out poverty.", "单靠技术无法彻底消除贫困。", "本篇只说互联网是强有力工具，并未声称能彻底消灭贫困。"],
  ["prevent-from-2001p2", "prevent A from doing", "prevent sb/sth from doing sth", "动词宾语补足结构", "阻止 A 做某事", "谓语、宾语与 from doing 补足语", "prevent 后接被阻止的对象，再用 from + 动名词说明被阻止的动作。", "Rules prevent firms from taking control.", "规则防止企业取得控制权。", "from 后必须用 doing；正式英语中通常保留 from。"],
  ["do-so-2001p2", "do so", "do so", "动词替代结构", "这样做；完成前述动作", "不定式中的动作替代", "do so 替代前文明确动作，避免整段重复。", "The country wanted to expand access but lacked funds to do so.", "该国想扩大接入，却缺少这样做的资金。", "so 不能替代需要具体人称宾语的任意动作。"],
  ["that-is-why", "that is why", "that is why + clause", "表语从句框架", "这就是为什么……", "主句加 why 表语从句", "that 回指原因，why 从句给出结果。", "Capital was scarce; that is why foreign funds were used.", "本国资本不足；这就是使用外资的原因。", "that is because 后接原因，逻辑方向与 that is why 不同。"],
  ["second-wave-infrastructure", "America’s Second Wave infrastructure", "Second Wave infrastructure", "概念名词短语", "美国工业时代的基础设施", "why 从句主语", "Second Wave 在本文指工业化阶段，与后文电子化 Third Wave 对应。", "Second Wave infrastructure included roads and ports.", "工业时代基础设施包括道路和港口。", "不是字面海浪。"],
  ["including-roads-ports", "including roads, harbors, highways, ports and so on", "including A, B, C and so on", "插入列举结构", "包括道路、港湾、高速公路、港口等等", "后置列举 infrastructure 实例", "including 引出非穷尽列举；and so on 表还有同类项目。", "Infrastructure includes roads, ports and so on.", "基础设施包括道路、港口等等。", "and so on 前列举项应属于同一类别。"],
  ["built-foreign-investment", "were built with foreign investment", "be built with/by means of + funding", "被动与方式结构", "借助外资建成", "why 从句谓语和资金来源状语", "with 引出建设所用资金或手段；被动突出设施而非建设者。", "The ports were built with foreign investment.", "这些港口是借助外资建成的。", "with 不表示共同建设者；若强调施事者通常用 by。"],
  ["investing-in-colony", "were investing in", "invest in + project/place", "动词介词搭配", "正在向……投资", "过去进行时谓语", "invest in 引出投资对象；过去进行时强调当时持续进行。", "European firms were investing in America.", "欧洲企业当时正在美国投资。", "不能省略 in 直接接地区。"],
  ["former-colony", "Britain’s former colony", "former + role/status", "名词短语", "英国的前殖民地", "invest in 的宾语", "former 表过去曾有而现在不再具有的身份。", "The former colony became independent.", "这个前殖民地获得了独立。", "former 与 latter 是前者/后者时属于另一用法。"],
  ["financed-them", "financed them", "finance + project/construction", "动宾搭配", "为这些项目提供资金", "短句谓语和宾语", "finance 作及物动词，直接接被资助的项目。", "Foreign investors financed the roads.", "外国投资者为道路建设出资。", "finance sb 可表示为某人提供资金，但本句 them 指项目。"],
  ["immigrant-americans", "Immigrant Americans", "immigrant + nationality", "名词短语", "移民美国者；美国移民", "短句主语", "immigrant 作定语说明 Americans 的移民背景。", "Immigrant Americans built the network.", "美国移民建设了这套网络。", "immigrant 指迁入者；emigrant 强调迁出者。"],
  ["built-them", "built them", "build + object", "动宾搭配", "把这些设施建成", "短句谓语和宾语", "them 回指前文道路、港口等基础设施。", "Local workers built them.", "当地工人建造了它们。", "阅读时必须跨句还原 them。"],
  ["guess-who-owns", "Guess who owns them now", "guess + wh-clause", "祈使句加宾语从句", "猜猜现在谁拥有它们", "设问句", "Guess 省略主语 you；who 从句作宾语，who 同时作 owns 的主语。", "Guess who owns the ports now.", "猜猜现在谁拥有这些港口。", "间接疑问从句不使用多余助动词倒装。"],
  ["the-americans", "The Americans", "the + nationality plural", "省略回答", "美国人", "回答上一设问的焦点", "完整句意可补为 The Americans own them now。", "The Americans own the infrastructure now.", "如今这些基础设施归美国人所有。", "不要把它误指为前文欧洲投资者。"],
  ["same-thing-true", "the same thing would be true", "the same thing be true of/in", "类比判断结构", "同样的规律也会成立", "believe 的宾语从句主干", "would 表基于假设或类比的推断；same thing 回指前述规律。", "The same thing would be true in Brazil.", "同样规律在巴西也会成立。", "same 前通常必须有 the。"],
  ["places-like-brazil", "in places like Brazil", "in places/countries like + example", "举例范围短语", "在巴西这样的地方", "修饰 would be true 的适用范围", "like 作介词引出例子，表示‘例如/像……这样的’。", "The policy may work in countries like Brazil.", "这项政策可能适用于巴西这样的国家。", "正式列举可用 such as，但结构位置可能调整。"],
  ["anywhere-matter", "anywhere else for that matter", "for that matter", "补充强调短语", "其实在任何其他地方也一样", "扩大前述适用范围", "for that matter 用于补充一个同样成立、甚至范围更广的情况。", "It may work in Brazil, or anywhere else for that matter.", "它可能适用于巴西，其实其他任何地方也一样。", "不要按字面译成‘为了那件事’。"],
  ["more-foreign-capital", "The more foreign capital", "the more + uncountable noun", "比较级相关结构前项", "外国资本越多", "比较条件分句开头", "the more 引出随动关系的前项；foreign capital 通常不可数。", "The more foreign capital a country attracts, the faster it can build.", "一国吸引的外资越多，建设速度可能越快。", "the 不能省略。"],
  ["capital-helping-build", "helping you build your Third Wave infrastructure", "have + object + doing / help sb (to) do", "宾语补足结构", "帮助你建设第三次浪潮基础设施", "foreign capital 的现在分词宾补", "foreign capital 是 helping 的逻辑主语；help 后 build 前的 to 可省略。", "They had foreign capital helping them build the network.", "他们有外资帮助建设网络。", "不要误把 you 当 helping 的动作发出者。"],
  ["electronic-infrastructure", "an electronic infrastructure", "electronic/digital infrastructure", "名词短语", "电子信息基础设施", "非限制性定语从句表语", "指电信网络、能源支撑和数字接入等系统。", "Telecom networks form an electronic infrastructure.", "电信网络构成电子基础设施。", "electronic 不等于 electric；前者偏电子与信息系统。"],
  ["better-off-going", "the better off you’re going to be", "the + comparative..., the + comparative... / be better off", "比较级相关结构后项", "境况会越好；经济上会越富裕", "比较结果分句", "better off 是固定表语；在相关结构中被提前到主语前。", "The better connected you are, the better off you may be.", "连接条件越好，经济状况可能越好。", "off 不能单独按‘离开’理解。"],
  ["doesnt-mean-lying", "doesn't mean lying down", "mean doing sth", "动名词宾语结构", "并不意味着消极躺平", "否定谓语与宾语", "mean doing 表‘意味着做’；mean to do 表‘打算做’，不可混淆。", "Accepting funds doesn't mean lying down.", "接受资金并不意味着消极听任摆布。", "lying 是 lie‘躺’的 -ing 形式，要变 ie 为 y。"],
  ["becoming-fooled", "becoming fooled", "become + past participle/adjective", "系表状态结构", "变得受骗；任人欺骗", "与 lying down 并列的动名词内容", "become 表状态变化，fooled 描述被欺骗状态。", "A country need not become fooled by investors.", "一个国家不必被投资者欺骗。", "become fooled 比 be fooled 更强调进入该状态。"],
  ["let-corporations-uncontrolled", "letting foreign corporations run uncontrolled", "let + object + verb + complement", "使役宾补结构", "放任外国公司不受控制地经营", "mean 的第二个并列动名词宾语", "let 后接宾语和动词原形；uncontrolled 补充说明 run 时的状态。", "Governments must not let firms run uncontrolled.", "政府不能放任企业不受控制地经营。", "let 后不能写 to run。"],
  ["does-mean-recognizing", "does mean recognizing", "do/does/did + mean doing", "强调谓语与动名词宾语", "确实意味着要认识到", "主句强调谓语", "does 强调 mean；mean 后用 recognizing 表‘意味着认识到’。", "It does mean recognizing the benefits.", "这确实意味着要认识到这些益处。", "用了 does 后不能写 means。"],
  ["how-important-can-be", "how important they can be", "recognize how + adjective + subject + verb", "感叹式宾语从句", "认识到它们能够多么重要", "recognizing 的宾语从句", "how 把形容词 important 提前；从句内部保持陈述语序。", "We recognize how important investment can be.", "我们认识到投资可以多么重要。", "不能使用疑问倒装 how important can they be。"],
  ["building-energy-telecom", "in building the energy and telecom infrastructures", "in doing sth", "领域介词结构", "在建设能源和电信基础设施方面", "修饰 important 的领域状语", "in + doing 表在某项活动或方面中；energy 与 telecom 并列修饰 infrastructures。", "Investment matters in building telecom infrastructure.", "投资对建设电信基础设施很重要。", "telecom 是 telecommunications 的常见缩写。"],
  ["needed-full-advantage", "needed to take full advantage of the Internet", "noun + needed to do sth", "过去分词后置定语", "充分利用互联网所必需的", "后置修饰 infrastructures", "needed 与 infrastructures 是被动关系；to do 说明这些设施服务的目标。", "Networks needed to support access require capital.", "支持接入所需的网络需要资本。", "needed 不修饰紧邻的 telecom 单词，而修饰整个 infrastructures。"],
  ["full-advantage-internet", "take full advantage of the Internet", "take full advantage of + noun", "固定动宾搭配", "充分利用互联网", "needed 后不定式的核心动作", "full 加强 advantage 程度；of 引出被利用对象。", "Countries should take full advantage of the Internet.", "各国应充分利用互联网。", "不能漏掉 of。"],
];

const toGuide = (seed: PhraseSeed): PhraseKnowledge => ({
  key: seed[0], sourceExpression: seed[1], canonical: seed[2], type: seed[3], meaning: seed[4],
  summary: `${seed[4]}；${seed[6]}`, grammarRole: seed[5],
  structures: [{ pattern: seed[2], meaning: seed[4], rule: seed[6], examples: [{ english: seed[7], chinese: seed[8] }] }],
  pitfalls: [seed[9]],
});

export const passage2001P2PhraseGuides: Record<string, PhraseKnowledge> = Object.fromEntries(
  seeds.map((seed) => [seed[0], toGuide(seed)]),
);

export const passage2001P2PhraseAliases: Record<string, string> = Object.fromEntries(
  seeds.flatMap((seed) => [[seed[1].toLowerCase(), seed[0]], [seed[2].toLowerCase(), seed[0]]]),
);

export const passage2001P2CollocationGlosses: Record<string, { meaning: string; note?: string }> = Object.fromEntries(
  seeds.flatMap((seed) => [
    [seed[1].toLowerCase(), { meaning: seed[4], note: seed[6] }],
    [seed[2].toLowerCase(), { meaning: seed[4], note: seed[6] }],
  ]),
);

export const passage2001P2FamilyGlosses: Record<string, string> = {
  accept: "接受；认可", acceptance: "接受；认可", acceptable: "可接受的；合意的",
  access: "接入；使用权；进入", accessible: "可接近的；可使用的", accessibility: "可达性；可使用性",
  attention: "注意；关注", attentive: "专注的；留心的", attentively: "专心地；留意地",
  colony: "殖民地", colonial: "殖民的", colonialism: "殖民主义",
  commerce: "商业；贸易", commercial: "商业的", commercialize: "使商业化", commercialization: "商业化",
  connect: "连接", connected: "相连的", connection: "连接；联系", connectivity: "连接能力",
  control: "控制；管理", controlled: "受控的；有节制的", uncontrolled: "不受控制的",
  corporation: "公司；法人团体", corporate: "公司的；法人的",
  danger: "危险", dangerous: "危险的", endanger: "危及；使处于危险中",
  develop: "发展；开发", developed: "发达的；发展完成的", developing: "发展中的", development: "发展；开发",
  digit: "数字", digitize: "使数字化", digital: "数字的；数字技术的",
  divide: "分开；分界", division: "划分；分歧", divisive: "引起分裂的",
  economy: "经济；节约", economic: "经济的", economical: "节约的", economically: "经济上；节约地",
  electron: "电子", electronic: "电子的", electronically: "以电子方式；电子地",
  exist: "存在", existence: "存在", existing: "现有的；现存的",
  finance: "为……提供资金；金融", financial: "金融的；财政的", financing: "融资；资金筹措",
  found: "建立；创办", foundation: "基础；基金会", foundational: "基础性的",
  govern: "治理；管理", government: "政府", governance: "治理；管理方式",
  hope: "希望", hopeful: "抱有希望的；有希望的", hopefully: "有希望地；但愿", hopeless: "没有希望的；绝望的",
  industry: "工业；行业", industrial: "工业的", industrialize: "使工业化",
  inform: "通知；告知", information: "信息；资料", informative: "提供有用信息的",
  invade: "入侵；侵入", invasion: "入侵；侵犯", invasive: "侵入性的；入侵的",
  invest: "投资", investment: "投资；投入", investor: "投资者",
  important: "重要的", importance: "重要性", importantly: "重要地；要紧的是",
  justify: "证明……正当；为……辩护", justification: "正当理由；辩护",
  loom: "逼近；赫然出现", looming: "逼近的；迫在眉睫的",
  nation: "国家；民族", national: "国家的；全国性的", nationality: "国籍；民族身份",
  optimism: "乐观；乐观主义", optimistic: "乐观的", optimist: "乐观主义者",
  own: "拥有；自己的", owner: "所有者；物主", ownership: "所有权",
  power: "力量；动力；驱动", powerful: "强有力的", powerfully: "强有力地",
  poor: "贫困的；差的", poverty: "贫困", impoverish: "使贫困", impoverished: "贫困的",
  potential: "潜力；潜在的", potentially: "潜在地；可能地",
  prejudice: "偏见；使有成见", prejudiced: "有偏见的",
  prosper: "繁荣；兴旺", prosperous: "繁荣的；兴旺的", prosperity: "繁荣；兴旺",
  recognize: "认识到；承认", recognition: "认识；承认",
  responsible: "负责的；有责任的", responsibility: "责任；职责",
  sovereign: "主权独立的；君主", sovereignty: "主权",
  structure: "结构；构造", structural: "结构的", infrastructure: "基础设施",
  technology: "技术", technological: "技术的", technologically: "技术上",
  universe: "宇宙；全体", universal: "普遍的；通用的", universally: "普遍地；到处", universalize: "使普及",
  visibility: "可见度；明显程度", visible: "可见的；明显的", invisible: "看不见的；不明显的",
  wide: "宽的；广泛的", widen: "拓宽；扩大", width: "宽度",
};

export const passage2001P2WordKnowledge: Record<string, WordKnowledge> = {
  what: {
    grammarRole: "融合型关系代词；自身包含先行内容并在从句中作成分",
    grammarSummary: "What was less visible then 整体作主语，相当于 the things that were less visible then；what 在内部作主语。",
    structures: [{ pattern: "What + predicate + main verb...", meaning: "……的事物/事情……", rule: "what 不需要另加先行词；整个从句可作主语、宾语或表语。", examples: [{ english: "What was less visible then were the positive forces.", chinese: "当时不太明显的是那些积极力量。" }] }],
    pitfalls: ["不能写 the things what；若已有先行词应使用 that/which。"],
  },
  as: {
    grammarRole: "从属连词；本篇表示伴随变化‘随着’",
    grammarSummary: "As the Internet becomes... 给出与主句同步发展的背景；as 还可表示时间、原因、方式或比较，必须看句内逻辑。",
    structures: [{ pattern: "As + subject + change verb, main clause", meaning: "随着……，……", rule: "常连接两个同步变化过程。", examples: [{ english: "As access expands, the divide narrows.", chinese: "随着接入扩大，鸿沟逐渐缩小。" }] }],
    pitfalls: ["不能看到 as 就固定翻译为‘作为’。"],
  },
  more: {
    grammarRole: "比较级限定词/副词；与 the 构成比较级相关结构",
    grammarSummary: "the more..., the more... 表示‘越……越……’；两边应是可以随动变化的平行分句。",
    structures: passage2001P2PhraseGuides["more-people-customers"].structures,
    pitfalls: passage2001P2PhraseGuides["more-people-customers"].pitfalls,
  },
  rather: {
    grammarRole: "副词；与 than 构成取舍连接结构",
    grammarSummary: "rather than 连接两个平行选项，表示选择前项、排除后项；本句连接 narrow 与 widen。",
    structures: passage2001P2PhraseGuides["narrow-rather-widen"].structures,
    pitfalls: passage2001P2PhraseGuides["narrow-rather-widen"].pitfalls,
  },
  within: {
    grammarRole: "介词；限定时间或空间边界以内",
    grammarSummary: "within + 时间段表示不迟于该期限；本句 Within the next decade or two 是将来预测的时间范围。",
    structures: passage2001P2PhraseGuides["within-decade-two"].structures,
    pitfalls: passage2001P2PhraseGuides["within-decade-two"].pitfalls,
  },
  why: {
    grammarRole: "连接副词；引导表语从句并保留原因关系",
    grammarSummary: "that is why + 结果从句表示‘前述原因就是后面结果发生的原因’；与 that is because + 原因方向相反。",
    structures: passage2001P2PhraseGuides["that-is-why"].structures,
    pitfalls: passage2001P2PhraseGuides["that-is-why"].pitfalls,
  },
  how: {
    grammarRole: "连接副词；把形容词程度提前并引导宾语从句",
    grammarSummary: "recognize how important they can be 中 how important 位于从句前，但从句仍用 they can be 的陈述语序。",
    structures: passage2001P2PhraseGuides["how-important-can-be"].structures,
    pitfalls: passage2001P2PhraseGuides["how-important-can-be"].pitfalls,
  },
  mean: {
    grammarRole: "及物动词；后接动名词表示‘意味着’",
    grammarSummary: "mean doing 表某事意味着什么后果；mean to do 表主语打算做什么。本文用 doesn't/does mean 形成否定误解与肯定正解。",
    structures: passage2001P2PhraseGuides["doesnt-mean-lying"].structures,
    pitfalls: passage2001P2PhraseGuides["doesnt-mean-lying"].pitfalls,
  },
  capital: {
    grammarRole: "不可数名词；经济语境表示用于投资和建设的资本",
    grammarSummary: "capital 可表示资本、首都或大写字母；foreign capital 与 have the capital to do so 均由投资建设语境确定为资金义。",
    structures: passage2001P2PhraseGuides["capital-do-so"].structures,
    pitfalls: passage2001P2PhraseGuides["capital-do-so"].pitfalls,
  },
};
