import type { BeginnerSyntaxComponent as Component, BeginnerClauseDetail as Clause, SentenceAnalysis, SyntaxVisualRole } from "./data";
import { withReviewedSyntax } from "./reviewed-syntax";
import { passage2001P2Practice } from "./2001-passage-2-practice";
const c = (text: string, form: string, fn: string, modifies: string, explanation: string, children?: Component[]): Component => ({ text, form, function: fn, modifies, explanation, children });
type Model = { colors: SyntaxVisualRole[]; translations: string[]; focus: string; question: string; evidence: string; answer: string; components?: Component[] };
const models: Record<number, Model> = {
  1: { colors: ["subject", "predicate", "modifier", "complement", "modifier"], translations: ["大量关注", "正在被投入", "如今", "所谓的数字鸿沟", "也就是世界被分为信息富裕者与信息贫困者"], focus: "is being paid是进行时被动，破折号后的名词解释divide。", question: "被动中关注投向哪里，破折号是否另起句子？", evidence: "is being paid today to the so-called digital divide", answer: "attention是被投入的对象；to保留pay attention to的搭配，后面的division只是同位解释，没有另一个谓语。" },
  2: { colors: ["connector", "subject", "predicate", "modifier"], translations: ["而且", "这道鸿沟", "确实存在", "如今"], focus: "does在肯定句强调exist；that在名词前限定所指。", question: "does是否表示做，that是否引导从句？", evidence: "that divide does exist", answer: "does为强调助动词，exist用原形；that限定divide，回指前句刚定义的鸿沟。" },
  3: { colors: ["subject", "predicate", "modifier", "modifier"], translations: ["我与妻子", "曾演讲", "谈论这一逐渐逼近的危险", "在二十年前"], focus: "danger承接数字鸿沟；ago以作者叙述时为时间参照。", question: "this looming danger是什么，twenty years ago从哪一时点倒推？", evidence: "this looming danger twenty years ago", answer: "this danger指数字鸿沟，looming表逼近；二十年前相对于文章叙述时，不能直接拿今天或2001考试年份倒推精确日期。" },
  4: { components: [c("What was less visible then", "融合型关系从句", "主语从句", "were", "整个what组相当于当时不太明显的事物。", [c("What", "融合关系代词", "主语", "was", "同时连接从句并承担主语。"), c("was", "系动词", "谓语", "What", "内部从句的系动词，与外层were不同。"), c("less visible", "形容词比较结构", "表语", "was", "不那么明显，不是完全不存在。"), c("then", "时间副词", "时间状语", "was", "回指二十年前。")]), c("however", "副词", "转折连接语", "早已看到危险与未看清积极力量", "插入评注可暂时括起。"), c("were", "系动词过去式", "主句谓语", "what从句与forces", "此种what系表句可按后面的复数forces一致。"), c("the new, positive forces that work against the digital divide", "名词及限制性关系从句", "表语", "were", "说明当时不太明显的具体事物。", [c("that work against the digital divide", "定语从句", "后置定语", "forces", "积极的是抵消鸿沟的力量，不能把positive移给divide。", [c("that", "关系代词", "主语", "work", "代指forces。"), c("work", "不及物动词", "谓语", "that", "在work against中表示发挥抵消作用。"), c("against the digital divide", "介词短语", "作用对象补足语", "work", "被对抗的是鸿沟。")])])], colors: ["subject", "connector", "predicate", "complement"], translations: ["当时不那么明显的事物", "然而", "是", "那些能够抵消数字鸿沟的、新的积极力量"], focus: "what从句整体作主语，forces及其定语共同作表语。", question: "positive究竟修饰力量还是数字鸿沟？", evidence: "the new, positive forces that work against the digital divide", answer: "positive直接修饰forces；that从句再说这些力量抵消divide。因此作者没有把鸿沟本身评价为积极。" },
  5: { colors: ["predicate", "subject", "modifier"], translations: ["存在", "一些理由", "使我们可以乐观"], focus: "to be optimistic后置说明reasons所支持的态度。", question: "there在这里指哪里，to be是否是将来时？", evidence: "There are reasons to be optimistic", answer: "there只引入存在情况；to be optimistic是不定式，补足有理由采取何种态度，不是将来时标记。" },
  6: { components: [c("There are", "存在句框架", "存在谓语框架", "technological reasons", "there无地点所指，are对应复数reasons。"), c("technological reasons to hope the digital divide will narrow", "名词加不定式内容", "存在主体", "are", "理由来自技术层面，后面说明据此期待的事情。", [c("to hope the digital divide will narrow", "不定式及内容从句", "后置补足语", "reasons", "hope有自己的宾语从句，不能把后者提到与reasons同层。", [c("the digital divide will narrow", "省略that的内容从句", "宾语从句", "hope", "原文未写that，不补入原句。", [c("the digital divide", "名词短语", "主语", "will narrow", "被预测缩小的对象。"), c("will narrow", "将来式", "谓语", "divide", "narrow在此作不及物动词缩小。")])])])], colors: ["predicate", "subject"], translations: ["存在", "技术方面的理由，使人期待数字鸿沟将缩小"], focus: "hope嵌在reasons后的不定式内，will narrow属于hope的宾语内容。", question: "will narrow是谁的谓语，hope从句受哪个词支配？", evidence: "to hope the digital divide will narrow", answer: "the digital divide是will narrow的主语；整个内容受hope支配，to hope再补足reasons。" },
  7: { components: [c("As the Internet becomes more and more commercialized", "As变化从句", "伴随变化状语从句", "主句的商业利益判断", "随着商业化程度增加，并非as名词身份结构。", [c("the Internet", "名词", "主语", "becomes", "互联网。"), c("becomes", "系动词", "谓语", "Internet", "后面形容词性表语说明状态变化。"), c("more and more commercialized", "递增比较表达", "表语", "becomes", "越来越商业化，两个more共同修饰commercialized。")]), c("it", "形式代词", "形式主语", "后置的to universalize access", "这里不回指Internet；占主语位置。"), c("is", "系动词", "主句谓语", "it", "连接真正主语与商业利益评价。"), c("in the interest of business", "介词短语", "表语", "is", "符合商业利益，interest不是兴趣。"), c("to universalize access", "不定式短语", "真正主语", "it", "被评价的事情是普及接入。", [c("access", "不可数名词", "宾语", "universalize", "互联网接入机会。")]), c("after all", "衔接短语", "解释连接语", "后一段商业逻辑", "毕竟，给前面利益判断理由。"), c("the more people online", "省略系动词的关联比较分句", "比较条件分句", "后面的顾客数量", "上网者越多；解释可补are，原文不添词。", [c("people", "复数名词", "主语", "省略的are", "上网的人。"), c("online", "形容词性状态词", "表语", "省略的are", "处于联网状态。")]), c("the more potential customers there are", "存在结构的比较结果分句", "比较结果分句", "前项上网人数增加", "潜在顾客越多；the more前置数量成分，不是又一个普通定冠词名词组。", [c("the more potential customers", "数量比较名词短语", "存在主体", "there are", "potential限定潜在顾客，并非所有用户已经购买。"), c("there are", "存在结构", "谓语框架", "customers", "说明存在的数量。")])], colors: ["modifier", "subject", "predicate", "complement", "subject", "connector", "modifier", "modifier"], translations: ["随着互联网越来越商业化", "形式主语，指后面的普及接入", "是", "符合商业利益的", "普及接入这件事", "毕竟", "上网者越多", "潜在顾客就越多"], focus: "前半有形式主语和真正主语，后半才是the more...the more...。", question: "两处比较与it各属什么层级？", evidence: "it is in the interest of business to universalize access", answer: "more and more描述商业化递增；it替后置不定式占位；破折号后两组the more构成用户与潜在顾客的数量正相关。" },
  8: { components: [c("More and more governments", "递增数量名词短语", "主语", "want", "越来越多政府；more限定政府数量。"), c("afraid their countries will be left behind", "形容词及内容从句", "原因背景状语", "governments想推广接入", "afraid说明政府担忧，后面省略that的从句说担心什么。", [c("their countries will be left behind", "省略that的内容从句", "形容词内容补足语", "afraid", "有自己的主语countries与被动谓语。", [c("their countries", "名词短语", "主语", "will be left behind", "这些政府所属的国家。"), c("will be left behind", "将来时被动短语动词", "谓语", "countries", "在发展中被落下；behind为短语动词的小品词。")])]), c("want", "一般现在时动词", "谓语", "governments", "后接不定式说明希望做的事。"), c("to spread Internet access", "不定式短语", "不定式补足语", "want", "其逻辑主语仍是governments。", [c("Internet access", "名词短语", "宾语", "spread", "推广互联网接入。")])], colors: ["subject", "modifier", "predicate", "complement"], translations: ["越来越多的政府", "担心本国落后", "希望", "推广互联网接入"], focus: "afraid及其内容是插入原因，主句为governments want to spread。", question: "countries与governments各对应哪个谓语？", evidence: "afraid their countries will be left behind", answer: "countries对应will be left behind，governments对应want；不能因countries距want更近就把它当主句主语。" },
  9: { components: [c("Within the next decade or two", "时间介词短语", "时间范围状语", "联网预测", "未来一二十年以内，以文章叙述时为参照。"), c("one to two billion people on the planet", "数量名词短语及范围修饰", "主语", "后面的联网预测", "十亿到二十亿人口；on the planet限定全球范围。", [c("on the planet", "介词短语", "后置范围定语", "people", "说明所预测人口遍及地球。")]), c("will he netted together", "原卷带疑似误排的动词组", "谓语位置（原卷字形）", "people", "原卷印he，按结构疑似be；规范将来被动应为will be netted together。本句保留原卷，不把he教成人称代词或合法助动词。")], colors: ["modifier", "subject", "predicate"], translations: ["在未来一二十年内", "全球十亿到二十亿人", "将被网络连接起来（按语境解读原卷疑似误排）"], focus: "数字与未来时间是预测；原卷he疑似be误排，不能作为正确句型记忆。", question: "本句预测多少人、在什么时间内？he可以作正常助动词吗？", evidence: "one to two billion people on the planet will he netted together", answer: "预测十亿至二十亿人，在叙述时之后的一二十年内联网；he字形确见原卷，语法上疑似be的误排，规范式为will be netted。" },
  10: { components: [c("As a result", "衔接介词短语", "结果状语", "作者的新判断", "接商业与政府推广力量的合力。"), c("I", "人称代词", "主语", "believe", "作者本人，非政府。"), c("now believe", "副词与动词", "谓语", "I", "现在判断，与二十年前看见危险对照。"), c("the digital divide will narrow rather than widen in the years ahead", "省略that的内容从句", "宾语从句", "believe", "预测属于作者观点，不能变成已核实的历史事实。", [c("the digital divide", "名词短语", "主语", "will narrow rather than widen", "数字鸿沟。"), c("will narrow rather than widen", "情态动词与对照动作", "谓语", "divide", "narrow与widen在同一层，前者缩小，后者扩大。"), c("in the years ahead", "时间介词短语", "时间状语", "will narrow", "未来的年份，以作者叙述时为参照。")])], colors: ["modifier", "subject", "predicate", "object"], translations: ["因此", "我", "现在相信", "数字鸿沟在未来会缩小而不是扩大"], focus: "rather than把作者预测明确落在缩小；未来时间属于宾语内容。", question: "now believe与in the years ahead是否描述同一个时间？", evidence: "I now believe the digital divide will narrow rather than widen in the years ahead", answer: "now限定判断发生时，ahead限定预计变化时；作者现在作未来预测，不是断言文章写作后已发生的结果。" },
  11: { components: [c("And", "连词", "承接连接语", "缩小预测与评价", "接上句判断。"), c("that", "指示代词", "主语", "is", "回指鸿沟将缩小这一预测。"), c("is", "系动词", "谓语", "that", "连接评价。"), c("very good news", "名词短语", "表语", "is", "好消息是鸿沟缩小，不是鸿沟本身。"), c("because the Internet may well be the most powerful tool for combating world poverty that we’ve ever had", "原因从句及嵌套关系从句", "原因状语从句", "good news", "原因在于互联网可能有巨大的扶贫作用。", [c("the Internet", "名词", "主语", "may well be", "互联网。"), c("may well be", "情态系动词与副词", "谓语", "Internet", "很可能是；may well不把可能说成绝对保证。"), c("the most powerful tool for combating world poverty that we’ve ever had", "名词及两层修饰", "表语", "be", "for说明用途，that从句限定历史范围。", [c("for combating world poverty", "for加动名词", "用途定语", "tool", "说明工具用于对抗贫困。"), c("that we’ve ever had", "关系从句", "后置定语", "tool", "that作had宾语，回指tool而非poverty。", [c("we’ve ever had", "主语加完成时谓语", "关系从句主谓", "that所指的tool", "we’ve是we have，had是实义动词的过去分词。")])])])], colors: ["connector", "subject", "predicate", "complement", "modifier"], translations: ["而且", "这一点", "是", "很好的消息", "因为互联网很可能是我们迄今拥有的最强大的全球扶贫工具"], focus: "原因从句内的that回指tool，may well保留可能性。", question: "that we’ve ever had修饰贫困还是工具？", evidence: "the most powerful tool for combating world poverty that we’ve ever had", answer: "修饰tool，说明我们曾拥有的工具范围；中间for用途组不能把that的先行词改为最近的poverty。" },
  12: { components: [c("Of course", "衔接短语", "承认状语", "工具作用的限制", "承认不是唯一方法。"), c("the use of the Internet", "名词短语", "主语", "isn’t", "中心use是名词使用。"), c("isn’t", "否定系动词缩写", "谓语", "use", "否定唯一性，不是否定作用。"), c("the only way to defeat poverty", "名词加不定式修饰", "表语", "isn’t", "被否定的是唯一方法。", [c("to defeat poverty", "不定式短语", "后置定语", "way", "解决贫困的方法内容。")])], colors: ["connector", "subject", "predicate", "complement"], translations: ["当然", "使用互联网", "并不是", "战胜贫困的唯一方法"], focus: "not the only否定唯一，而非否定有效。", question: "isn’t the only way是否说明互联网无助扶贫？", evidence: "isn’t the only way to defeat poverty", answer: "不是；only限制唯一性，作者只说还有别的方法，后面仍强调互联网潜力。" },
  13: { components: [c("And", "连词", "承接连接语", "两个非唯一限定", "从方法推进到工具。"), c("the Internet", "名词", "主语", "is", "互联网。"), c("is not", "否定系动词", "谓语", "Internet", "仍是否定唯一性。"), c("the only tool we have", "名词与关系从句", "表语", "is", "我们有的工具不只互联网。", [c("we have", "省略宾语关系词的从句", "后置定语", "tool", "we是主语，have是实义谓语；省略的that/which指tool作宾语，不是完成时。")])], colors: ["connector", "subject", "predicate", "complement"], translations: ["并且", "互联网", "并非", "我们拥有的唯一工具"], focus: "we have是省略宾语关系词的定语从句。", question: "have后为什么没有显式宾语，它是完成时吗？", evidence: "the only tool we have", answer: "have是拥有义，宾语位置由省略的关系词回指tool；没有过去分词，因此不是完成时。" },
  14: { colors: ["connector", "subject", "predicate", "object"], translations: ["但是", "它", "具有", "巨大的潜力"], focus: "But承认限制后仍肯定潜力。", question: "potential是已有成果还是可能发挥的能力？", evidence: "has enormous potential", answer: "potential为潜力，不等于已经消除贫困；it回指互联网，has为实义动词有。" },
  15: { components: [c("To take advantage of this tool", "目的不定式", "目的状语", "countries需克服偏见", "使用该工具的目的背景；工具指互联网。"), c("some impoverished countries", "名词短语", "主语", "will have to get over", "some限定部分贫困国家。"), c("will have to get over", "将来情态必要性及短语动词", "谓语", "countries", "have to是必要，不是拥有；get over是克服。"), c("their outdated anti-colonial prejudices with respect to foreign investment", "名词与对象修饰", "宾语", "get over", "克服的是针对外资的过时反殖民偏见。", [c("with respect to foreign investment", "固定介词表达", "对象补足语", "prejudices", "就外资而言，respect不取尊敬义；目标不是移民。")])], colors: ["modifier", "subject", "predicate", "object"], translations: ["为了利用这一工具", "一些贫困国家", "将不得不克服", "对外国投资抱有的过时反殖民偏见"], focus: "目的不定式在句首，with respect to附着prejudices限定对象。", question: "偏见针对谁，have to是不是完成时？", evidence: "prejudices with respect to foreign investment", answer: "偏见针对外国投资；will have to get over表达未来必须克服，不含完成时的过去分词。" },
  16: { components: [c("Countries that still think foreign investment is an invasion of their sovereignty", "名词及嵌套从句", "主语", "might well study", "整个长主语是仍持某种看法的国家。", [c("that still think foreign investment is an invasion of their sovereignty", "关系从句", "后置定语", "Countries", "that回指国家并作think主语。", [c("that", "关系代词", "主语", "think", "指Countries。"), c("still think", "副词与动词", "谓语", "that", "still强调旧看法仍在。"), c("foreign investment is an invasion of their sovereignty", "省略that的内容从句", "宾语从句", "think", "这是这些国家的看法，并非作者认同。", [c("foreign investment", "名词短语", "主语", "is", "外国投资。"), c("is", "系动词", "谓语", "investment", "连接被批评的判断。"), c("an invasion of their sovereignty", "名词短语", "表语", "is", "侵犯主权；their指这些国家。")])])]), c("might well study", "情态动词与实义动词", "谓语", "Countries", "这里委婉建议不妨研究，不是预测他们很可能学习。"), c("the history of infrastructure (the basic structural foundations of a society) in the United States", "名词及术语解释、地域限定", "宾语", "study", "建议研究美国基础设施建设史，不是建议去美国学习。", [c("the basic structural foundations of a society", "括号内名词短语", "同位解释", "infrastructure", "原卷给出的基础设施定义，没有独立谓语。"), c("in the United States", "地域介词短语", "范围限定", "the history of infrastructure", "限定美国的设施史，避免错接study的动作地点。")])], colors: ["subject", "predicate", "object"], translations: ["那些仍认为外国投资侵犯本国主权的国家", "不妨研究", "美国基础设施的历史；基础设施即社会的基本结构性基础"], focus: "that修饰Countries，think再带内容从句；作者建议研究历史以反驳该看法。", question: "外资侵犯主权是谁的看法，in the United States限定什么？", evidence: "Countries that still think foreign investment is an invasion of their sovereignty", answer: "这是某些国家仍持的看法，作者正用美国史回应它；in the United States限定所研究的基础设施史。" },
  17: { components: [c("When the United States built its industrial infrastructure", "时间从句", "时间状语从句", "主句资本不足", "交代美国建设工业基础设施时的历史背景。", [c("the United States", "专名", "主语", "built", "美国。"), c("built", "过去式", "谓语", "United States", "建设，不是出资主体的直接判断。"), c("its industrial infrastructure", "名词短语", "宾语", "built", "美国自己的工业基础设施。")]), c("it", "代词", "主语", "didn’t have", "回指美国。"), c("didn’t have", "否定过去时", "谓语", "it", "have为拥有义，did承担过去时。"), c("the capital to do so", "名词及不定式", "宾语", "have", "缺建设所需资本，不是没有首都。", [c("to do so", "不定式及动作替代", "用途补足语", "capital", "do so代指build its industrial infrastructure。")])], colors: ["modifier", "subject", "predicate", "object"], translations: ["当美国建设本国工业基础设施时", "它", "没有", "进行这种建设所需的资本"], focus: "so替代建设行为，capital是资金。", question: "it与so分别代指国家还是行为？", evidence: "it didn’t have the capital to do so", answer: "it指美国，do so替代建设工业基础设施，不能把so当成所以而另起因果句。" },
  18: { components: [c("And", "连词", "承接连接语", "资本不足与借外资建设", "顺接因果。"), c("that", "指示代词", "主语", "is", "回指美国缺少建设资本。"), c("is", "系动词", "谓语", "that", "后接why内容作表语。"), c("why America’s Second Wave infrastructure—including roads, harbors, highways, ports and so on—were built with foreign investment", "why表语从句及插入列举", "表语从句", "is", "that is why给前因造成的结果。", [c("America’s Second Wave infrastructure", "名词短语", "主语", "were built", "美国第二次浪潮即工业时代的基础设施。"), c("including roads, harbors, highways, ports and so on", "介词化分词列举", "插入举例", "infrastructure", "道路、港湾、高速公路、港口为设施例子；不另增有限谓语。"), c("were built", "过去时被动（保留原卷一致形式）", "谓语", "infrastructure", "原卷infrastructure搭were；常规不可数用法通常配was。本句保留原形，不按列举项误换主语。"), c("with foreign investment", "介词短语", "资金来源状语", "were built", "借外国投资建设，并不表示永远归外国所有。")])], colors: ["connector", "subject", "predicate", "complement"], translations: ["而", "这", "正是", "美国工业时代基础设施借助外资建成的原因，其中包括道路、港湾、高速公路和港口等"], focus: "why从句包含自己的主语、插入实例和被动谓语。", question: "that所指前因是什么，with是否保证投资者永久拥有设施？", evidence: "were built with foreign investment", answer: "前因是本国资本不足；with只说明资金来源，后文将分开发生融资、建设和现在拥有这三种角色。" },
  19: { colors: ["subject", "predicate", "complement"], translations: ["英国人、德国人、荷兰人和法国人", "当时正在投资", "英国过去的殖民地"], focus: "四国投资者并列，former colony指美国。", question: "former是现在仍殖民吗，投资者与建设者是否必为同一群人？", evidence: "were investing in Britain’s former colony", answer: "former表示曾经，英国前殖民地在此是美国；这句仅说明投资者，后面另说建设者。" },
  20: { colors: ["subject", "predicate", "object"], translations: ["他们（前述欧洲投资者）", "提供资金建设", "这些基础设施"], focus: "They指投资者，them指设施，两者不是同一类对象。", question: "谁出资，为谁或什么出资？", evidence: "They financed them", answer: "They回指四国投资者，them回指基础设施；finance在此是动词资助，不能把them接成移民。" },
  21: { colors: ["subject", "predicate", "object"], translations: ["移民出身的美国人", "建造了", "这些基础设施"], focus: "建设者与前句出资者分开，them所指保持不变。", question: "Immigrant Americans与They分别承担什么角色？", evidence: "Immigrant Americans built them", answer: "本句移民美国人是建造者，前句欧洲人是投资者；作者借不同角色为后面所有权设问铺垫。" },
  22: { components: [c("Guess", "祈使句动词", "主句谓语", "省略的受话人you", "邀请读者猜，不把you添回原文。"), c("who owns them now", "嵌入疑问从句", "宾语从句", "Guess", "问现在谁拥有设施；who自身作主语。", [c("who", "疑问代词", "主语", "owns", "要猜的所有者。"), c("owns", "第三人称单数动词", "谓语", "who", "拥有，不是修饰名词的own。"), c("them", "宾格代词", "宾语", "owns", "那些基础设施。"), c("now", "时间副词", "时间状语", "owns", "作者叙述时，不是投资发生时。")])], colors: ["predicate", "object"], translations: ["猜猜", "如今谁拥有这些设施"], focus: "who作嵌入疑问从句主语，因此不需要do倒装。", question: "为何不是who does own，now与were investing时间相同吗？", evidence: "who owns them now", answer: "who已经是主语，后接owns陈述顺序；now询问现在所有者，与早先投资时期区别。" },
  23: { colors: ["subject"], translations: ["美国人"], focus: "名词短答承接上句who，只补说明省略内容，不捏造原文谓语。", question: "The Americans回答的是投资者、建设者还是现在所有者？", evidence: "The Americans", answer: "直接回答who owns them now，指现在所有者；不等于说此前全部建设资金来自美国人。" },
  24: { components: [c("I", "代词", "主语", "believe", "作者。"), c("believe", "动词", "谓语", "I", "引出经验可推广的判断。"), c("the same thing would be true in places like Brazil or anywhere else for that matter", "省略that的内容从句", "宾语从句", "believe", "would表达设想的适用，不是宣称各国历史完全相同。", [c("the same thing", "名词短语", "主语", "would be", "借外资建设且保有本国所有权的道理。"), c("would be", "情态系动词", "谓语", "thing", "假设相同原则可成立。"), c("true", "形容词", "表语", "be", "适用、成立。"), c("in places like Brazil or anywhere else", "范围及举例短语", "适用范围状语", "true", "巴西只是举例，or扩展到别处。"), c("for that matter", "补充衔接语", "范围扩展评注", "anywhere else", "就这一点而言，进一步说。")])], colors: ["subject", "predicate", "object"], translations: ["我", "相信", "同样道理在巴西这样的地方乃至别处也会成立"], focus: "the same thing接经验原则，would保留假设推广。", question: "same thing是否要求别国复制美国全部工业模式？", evidence: "the same thing would be true in places like Brazil", answer: "不是；前文论点是借外资建设不必失去所有权，同样的是原则，不是所有制度与发展路线。" },
  25: { components: [c("The more foreign capital you have helping you build your Third Wave infrastructure", "关联比较的前项分句", "比较条件分句", "后项经济状况", "先还原you have capital helping...，宾语数量被前置。", [c("The more foreign capital", "前置数量名词短语", "宾语", "have", "数量越多的外资，不是首都。"), c("you", "泛指代词", "主语", "have", "承接被建议的国家。"), c("have", "实义动词", "谓语", "you", "have宾语加doing说明有资本在发挥帮助作用。"), c("helping you build your Third Wave infrastructure", "现在分词与帮助结构", "宾语补足语", "foreign capital", "资本是helping逻辑主语；you是build逻辑主语。", [c("you", "宾格代词", "宾语兼逻辑主语", "helping与build", "资本帮助你，而不是你帮助资本建设。"), c("build your Third Wave infrastructure", "省略to的不定式", "宾语补足语", "you", "help somebody (to) do，build前可省to。")])]), c("which today is an electronic infrastructure", "非限制性关系从句", "定语从句", "Third Wave infrastructure", "解释第三次浪潮设施今天是电子基础设施。", [c("which", "关系代词", "主语", "is", "指infrastructure，不指capital。"), c("today", "时间副词", "时间状语", "is", "以作者时代为参照。"), c("is", "系动词", "谓语", "which", "引出解释。"), c("an electronic infrastructure", "名词短语", "表语", "is", "电子基础设施。")]), c("the better off", "前置比较表语", "表语", "后项be", "经济处境越好，off是固定表达组成部分。"), c("you’re going to be", "缩写主语及将来系动词", "比较结果分句主谓", "the better off", "you’re是you are；表语提前，解释顺序为you are going to be better off。")], colors: ["modifier", "modifier", "complement", "predicate"], translations: ["帮助你建设第三次浪潮基础设施的外国资本越多", "这种设施在当今指电子基础设施", "经济境况就越好", "这是对你未来处境的预测"], focus: "have capital helping...内再嵌help you build，which只解释基础设施。", question: "两层非谓语各由谁执行，which指资本还是设施？", evidence: "foreign capital you have helping you build your Third Wave infrastructure", answer: "capital帮助，you建设；which回指infrastructure。整句是作者的经济论证，不是无条件保证所有外资都带来收益，后面还有限制。" },
  26: { components: [c("That", "指示代词", "主语", "doesn't mean", "回指接受外资建设电子设施的主张。"), c("doesn't mean", "否定谓语", "谓语", "That", "mean doing表示意味着，不是mean to do打算。"), c("lying down and becoming fooled", "并列动名词", "宾语一", "mean", "否定消极听任和受骗。", [c("lying down", "动名词短语", "并列内容一", "mean", "比喻消极屈从，不是lying说谎。"), c("becoming fooled", "动名词加被动状态补足", "并列内容二", "mean", "变得受骗，becoming后过去分词说明状态。")]), c("or", "连词", "并列连接语", "两组不意味着的内容", "在否定范围内追加另一误解。"), c("letting foreign corporations run uncontrolled", "动名词及使役结构", "宾语二", "mean", "不能任由外企失控经营。", [c("foreign corporations", "名词短语", "宾语兼逻辑主语", "letting与run", "公司是let宾语，也是run执行者。"), c("run uncontrolled", "省略to的不定式及状态补充", "宾语补足语", "corporations", "let后run用原形，uncontrolled说明公司的经营状态。")])], colors: ["subject", "predicate", "object", "connector", "object"], translations: ["那", "并不意味着", "消极屈从并任人欺骗", "或者", "任由外国公司不受监管地经营"], focus: "doesn't mean否定两类误解，run的执行者为公司。", question: "lying是否说谎，run uncontrolled是否说明作者支持放任？", evidence: "doesn't mean lying down and becoming fooled, or letting foreign corporations run uncontrolled", answer: "lying down为消极屈从的比喻；整组letting仍在doesn't mean否定范围，作者反对无监管经营。" },
  27: { components: [c("But", "连词", "转折连接语", "排除误解与正面主张", "承接前句否定，转回真正应承认的作用。"), c("it", "代词", "主语", "does mean", "与前句That同指接受外资的主张。"), c("does mean", "强调助动词与实义动词", "谓语", "it", "does强调，mean原形。"), c("recognizing how important they can be in building the energy and telecom infrastructures needed to take full advantage of the Internet", "动名词及嵌套内容从句", "宾语", "mean", "mean doing宾语内部，recognizing再带how从句。", [c("how important they can be in building the energy and telecom infrastructures needed to take full advantage of the Internet", "how程度内容从句", "宾语从句", "recognizing", "how important为提前表语；they是外国公司。", [c("how important", "程度词加形容词", "表语", "can be", "多么重要。"), c("they", "代词", "主语", "can be", "回指foreign corporations，不是infrastructures。"), c("can be", "情态系动词", "谓语", "they", "可能发挥的作用，非保证全部项目成功。"), c("in building the energy and telecom infrastructures needed to take full advantage of the Internet", "领域介词短语及分词修饰", "领域状语", "important", "重要性体现在建设必要设施。", [c("the energy and telecom infrastructures", "并列性质名词短语", "宾语", "building", "能源与电信基础设施。"), c("needed to take full advantage of the Internet", "过去分词及不定式补足", "后置定语", "infrastructures", "这些设施是充分利用互联网所需的；needed不修饰公司。")])])])], colors: ["connector", "subject", "predicate", "object"], translations: ["但是", "这一主张", "确实意味着", "要认识到外国公司在建设充分利用互联网所需的能源和电信基础设施方面，可以发挥多么重要的作用"], focus: "mean→recognizing→how从句逐层嵌套，needed回接设施。", question: "they与needed分别接回公司还是基础设施？", evidence: "they can be in building the energy and telecom infrastructures needed", answer: "they接上一句外国公司；needed修饰能源和电信设施，不能因层级压平而把它当成公司另一个谓语。" },
};
const details: Record<number, Clause["predicateDetails"][]> = {
  4: [[{ function: "表语", text: "less visible" }], []], 6: [[]],
  7: [[{ function: "表语", text: "more and more commercialized" }], [{ function: "表语", text: "online" }], []], 8: [[]], 10: [[]],
  11: [[{ function: "表语", text: "the most powerful tool for combating world poverty that we’ve ever had" }], [{ function: "宾语", text: "that" }]],
  13: [[]], 16: [[{ function: "宾语", text: "foreign investment is an invasion of their sovereignty" }], [{ function: "表语", text: "an invasion of their sovereignty" }]],
  17: [[{ function: "宾语", text: "its industrial infrastructure" }]], 18: [[]], 22: [[{ function: "宾语", text: "them" }]],
  24: [[{ function: "表语", text: "true" }]], 25: [[{ function: "宾语", text: "foreign capital" }, { function: "宾语补足语", text: "helping you build your Third Wave infrastructure" }], [{ function: "表语", text: "an electronic infrastructure" }]],
  27: [[{ function: "表语", text: "how important" }]],
};
export function upgradePassage2001P2(draft: SentenceAnalysis): SentenceAnalysis {
  const model = models[draft.number];
  const clauses = (draft.beginnerSyntax?.clauses ?? []).map((old, i): Clause => {
    const { objectOrComplement: _oldDetail, ...clause } = old;
    return { ...clause, predicate: draft.number === 8 ? "will be left behind" : clause.predicate, predicateDetails: details[draft.number]?.[i] ?? [] };
  });
  const reviewed = withReviewedSyntax({ ...draft, textKind: draft.number === 23 ? "phrase" : draft.textKind,
    beginnerSyntax: { components: model.components ?? draft.beginnerSyntax!.components, clauses, reading: { focus: model.focus, questions: [{ question: model.question, evidence: model.evidence, answer: model.answer }] } },
    practice: passage2001P2Practice[draft.id],
  }, model.colors);
  return { ...reviewed, translationAlignment: reviewed.chunks.map((chunk, i) => ({ english: chunk.text, chinese: model.translations[i] })) };
}
