import type { SentenceWordContext } from "./contextual-vocabulary";

const w = (partOfSpeech: string, contextualMeaning: string, use: string): SentenceWordContext => ({ partOfSpeech, contextualMeaning, use });

// 25个真实来源分别存义。错误选项也解释其实际用词，不用正确答案改写选项含义。
export const passage2010P2QuestionContexts: Record<string, Record<string, SentenceWordContext>> = {
  "question-201026-prompt": {
    what: w("interrogative pron.", "什么", "What是前置的疑问表语，问expectation是什么；不是问哪位妻子。"),
    most: w("determiner", "大多数的", "most限定wives；不是most probably中的程度副词。"),
    wife: w("n.（复数所有格）", "妻子", "wives'是wife的复数所有格，表明期待由多数妻子提出；main expectation才是单数主语中心。"),
    main: w("adj.", "主要的；首要的", "修饰expectation；题目要求首要期待，不是所有合理的婚姻需求。"),
    expectation: w("n.", "期待", "中心名词expectation为单数，所以用is；of their husbands说明期待的对象。"),
    of: w("prep.", "对……的", "expectation of their husbands中引出被期待的丈夫，不把期待归属给丈夫。"),
    their: w("possessive determiner", "她们的", "限定husbands，回指most wives。"),
  },
  "question-201026-option-A": {
    talk: w("v.（动名词形式）", "交谈；说话", "Talking把行为作为期待内容，执行者承接题干的丈夫；不构成现在进行时。"),
    to: w("prep.", "与……；对……", "talk to somebody中to引出交谈对象，后接宾格them，不是不定式标记。"),
    they: w("pron.（宾格them）", "她们（妻子）", "them作to的宾语，不指丈夫。"),
  },
  "question-201026-option-B": {
    trust: w("v.（动名词形式）", "信任", "Trusting直接接them，表示期待丈夫信任妻子；不补加介词to。"),
    they: w("pron.（宾格them）", "她们（妻子）", "them是Trusting的直接宾语。词义按本项解释，不因本项不选就改成交流。"),
  },
  "question-201026-option-C": {
    support: w("v.（动名词形式）", "支持", "Supporting接their careers，动作由题干里的丈夫完成；不是名词支持者。"),
    their: w("possessive determiner", "她们的", "their限定妻子的事业，不是丈夫的事业。"),
    career: w("n.（复数）", "事业；职业发展", "careers指妻子各自的事业，不能把their包含在career的单词义中。"),
  },
  "question-201026-option-D": {
    share: w("v.（动名词形式）", "分担", "Sharing housework整体是分担家务；这里share是动词，区别于正文their share中的名词份额。"),
    housework: w("n.（不可数）", "家务劳动", "作Sharing的宾语，通常不加复数s；不是一栋房屋的工程。"),
  },
  "question-201027-prompt": {
    judge: w("v.（-ing形式）", "判断", "Judging from the context是固定评注表达，表示根据语境判断；不是phrase这个主语在执行判断。"),
    from: w("prep.", "根据；从……来看", "judging from引出判断依据，不表示来自某个地点。"),
    context: w("n.", "上下文；语境", "the context提示结合前后文判断含义，不只机械替换一个孤立单词。"),
    phrase: w("n.", "词组；短语", "phrase是means的主语中心，引号内wreaking havoc给出具体被解释的词组。"),
    wreak: w("v.（-ing形式）", "造成（破坏等）", "与havoc搭配，wreak是动作，havoc是造成的严重破坏；单词释义不混入受影响的婚姻。"),
    havoc: w("n.（不可数）", "严重破坏；混乱", "作wreaking的宾语，保留强烈负面含义；不是一般影响或积极动力。"),
    line: w("n.", "行", "Line 3定位原卷排版中的第三行；不是诗行、产品线，也不随网页换行重新计算。"),
    para: w("abbreviation", "段落（paragraph的缩写）", "Para. 2指原卷第2段，和Line 3共同用于定位。"),
    most: w("adv.", "最", "修饰probably，表示最可能；不是题26中限定wives数量的用法。"),
    probably: w("adv.", "很可能", "与most组成可能性说明，修饰means。"),
    mean: w("v.（第三人称单数）", "意思是；表示", "means是mean的第三人称单数谓语形式，主语the phrase；不能沿用名词means的手段义。"),
  },
  "question-201027-option-A": {
    generate: w("v.（动名词形式）", "产生；引起", "generating直接接motivation，作待选的词组释义；不是进行时。"),
    motivation: w("n.", "动力；动机", "作generating的宾语，表示做事的推动力，不是momentum的发展势头。"),
  },
  "question-201027-option-B": {
    exert: w("v.（动名词形式）", "施加；运用", "exert influence整体表示施加影响；exert直接接宾语，不是自己受到影响。"),
    influence: w("n.", "影响", "exerting后作名词宾语，本身不限定影响的好坏；区别于此处havoc的严重负面含义。"),
  },
  "question-201027-option-C": {
    cause: w("v.（动名词形式）", "造成；导致", "causing后接damage作宾语；不是名词原因。"),
    damage: w("n.（不可数）", "损害；破坏", "作causing的宾语，保留负面结果，不是复数damages的赔偿金义。"),
  },
  "question-201027-option-D": {
    create: w("v.（动名词形式）", "造成；形成", "creating pressure指形成压力；create的单词义不包含后面pressure的内容。"),
    pressure: w("n.", "压力", "作creating的宾语；压力与造成严重损害相关，但不能自动等同。"),
  },
  "question-201028-prompt": {
    all: w("pron.", "全部；所有各项", "All作主语，of the following限定为下列选项；EXCEPT再排除一项。"),
    follow: w("adj.（following名词化使用）", "下列的（各项）", "the following表示下列说法，不是正在跟随的谓语动作。"),
    true: w("adj.", "符合事实的；真实的", "在are后作表语，本题事实标准是文章；EXCEPT要求找不符合的一项。"),
    except: w("prep.", "除……之外", "从All所指的各项中排除空格里的那项；大写提示反向选择，不能忽略。"),
  },
  "question-201028-option-A": {
    man: w("n.（复数men）", "男性", "men为泛指群体，tend to限定一般倾向，不是指首段那一名男子。"),
    tend: w("v.", "往往；倾向于", "tend to talk表示通常呈现的倾向，不等于always或所有人无例外。"),
    more: w("adv.（比较级）", "更多地", "修饰talk，比较说话量；不是说男性人数更多。"),
    public: w("n.（用于in public）", "公众场合", "in public整体表示在公开场合，限定talk发生的场景。"),
    than: w("conj.", "比", "than women给出比较方，可按省略talk的比较分句理解；不是talk的宾语标记。"),
  },
  "question-201028-option-B": {
    nearly: w("adv.", "接近；将近", "修饰50 percent，不能改成精确等于。"),
    percent: w("n.", "百分比；百分之……", "50 percent of recent divorces把近期离婚案例当作统计总体；不同于正文divorce rate中的离婚率。"),
    of: w("prep.", "……中的", "of recent divorces限定50 percent的总体范围，是识别统计对象偷换的关键。"),
    recent: w("adj.", "近期的", "修饰divorces，这是选项提出的时间范围，不能未经核对就当作正文已有的限定。"),
    divorce: w("n.（复数）", "离婚；离婚案例", "recent divorces在本项中是被统计的案例，不是把50%直接附到divorce rate。"),
    cause: w("v.（过去分词）", "导致；造成", "are caused是被动谓语；本项断言因果，不能只按访谈中的原因归属来理解。"),
    by: w("prep.", "由；由于", "被动结构中引出failed conversation作为原因，不是表示变化幅度。"),
    fail: w("adj.（分词形式）", "失败的；未奏效的", "failed前置修饰conversation，不是主句的另一个谓语，也不是已经证明的离婚原因占比。"),
    conversation: w("n.", "交谈；沟通", "作by的宾语中心，failed说明沟通不成功；单词本身不等于整项因果陈述。"),
  },
  "question-201028-option-C": {
    attach: w("v.", "赋予；给予", "attach importance to整体表示重视；此处不是把实物贴在表面。"),
    much: w("determiner", "大量的；很大程度的", "限定不可数名词importance；much importance表示很重视。"),
    importance: w("n.（不可数）", "重要性", "attach的宾语；不是important这个形容词。"),
    to: w("prep.", "对；给", "attach importance to后接名词communication；不是to加动词的不定式。"),
    communication: w("n.", "交流；沟通", "to后的名词，between couples限定夫妻之间；不指交通运输或通信设备。"),
    between: w("prep.", "在……之间", "between couples说明夫妻之间的交流。此处后接复数名词，不应擅自把原文补成between A and B。"),
    couple: w("n.（复数）", "夫妻；伴侣", "couples在此指夫妻双方的关系，不是a couple of的几个。"),
  },
  "question-201028-option-D": {
    female: w("n.", "女性", "a female中female作单数名词；不是修饰另一个名词的形容词。"),
    tend: w("v.（第三人称单数）", "往往；倾向于", "tends对应a female；不把倾向扩大为全体夫妻的绝对规律。"),
    talkative: w("adj.", "健谈的；爱说话的", "more talkative在to be后作表语，描述女性健谈的程度。"),
    more: w("adv.", "更", "修饰talkative组成比较级，不是修饰某种人口数量。"),
    home: w("n.（用于at home）", "家", "at home整体限定在家的场合；区别于come home中home作方向副词。"),
    than: w("conj.", "比", "than her spouse给出比较方，省略的系动词可理解为is，不补入原文。"),
    her: w("possessive determiner", "她的", "限定spouse，回指a female；不是独立作宾语的her。"),
    spouse: w("n.", "配偶", "在本项中指女性的配偶，词本身可用于丈夫或妻子，不等同于所有男性。"),
  },
  "question-201029-prompt": {
    which: w("interrogative pron.", "哪一个", "Which作can summarize的主语，of the following限定备选范围。"),
    follow: w("adj.（following名词化使用）", "下列的（各项）", "the following指下面的选项，不是过去发生后的动作。"),
    best: w("adv.（最高级）", "最准确地；最好地", "修饰summarize，比较各选项概括主旨的准确性，不是形容词修饰idea。"),
    summarize: w("v.", "概括；总结", "can后使用动词原形，直接接the main idea作宾语。"),
    main: w("adj.", "主要的", "修饰idea，要求全文主旨，不是一个局部事实。"),
    idea: w("n.", "中心意思；主旨", "the main idea指全文核心意思，不沿用正文offering ideas中的零散看法。"),
    text: w("n.", "文章；文本", "this text是当前整篇阅读文章，不是短信。"),
  },
  "question-201029-option-A": {
    moral: w("adj.", "道德方面的", "修饰decay，不是名词寓意；文章引用社会学家不代表谈道德衰败。"),
    decay: w("n.", "衰败；败坏", "moral decay作主语，decay不是本句谓语；deserves才承担时态。"),
    deserve: w("v.（第三人称单数）", "值得；应受到", "deserves后接more research，表达值得进一步研究。"),
    research: w("n.（不可数）", "研究", "作deserves的宾语，more表示更多研究；不是谓语动词。"),
    by: w("prep.", "由……进行", "by sociologists修饰research，说明研究者，不是说衰败由社会学家造成。"),
    sociologist: w("n.（复数）", "社会学家", "作by的宾语，表示研究者的职业；不专指Riessman一个人。"),
  },
  "question-201029-option-B": {
    marriage: w("n.（作名词修饰语）", "婚姻", "修饰break-up，限定破裂所属的关系领域。"),
    "break-up": w("n.", "破裂；解体", "带连字符的名词作主语中心，不是动词短语break up的两个独立谓语。"),
    stem: w("v.（第三人称单数）", "起源；由……产生", "stems from整体表示源于，是因果来源判断；不是植物茎这个名词。"),
    from: w("prep.", "源于", "与stems组成因果来源表达，后接sex inequalities。"),
    sex: w("n.（作名词修饰语）", "性别", "修饰inequalities，指性别方面，不宜按其他常见义误译。"),
    inequality: w("n.（复数）", "不平等；不公平现象", "inequalities是inequality的复数，表示性别不平等，不是数学不等式。"),
  },
  "question-201029-option-C": {
    have: w("v.", "持有；怀有", "have后接expectations名词宾语，不是后接过去分词的完成时助动词。"),
    different: w("adj.", "不同的", "修饰expectations；本项并未将期待限定为交谈。"),
    expectation: w("n.（复数）", "期待", "different expectations是have的宾语；按选项实际范围解释，不能偷偷加入conversational。"),
    from: w("prep.", "从……中", "expectations from their marriage说明期待从婚姻中得到什么，不是夫妻来自哪里。"),
    their: w("possessive determiner", "他们的", "限定marriage，回指夫妻双方。"),
  },
  "question-201029-option-D": {
    conversational: w("adj.", "交谈方面的", "修饰patterns，保留全文讨论对象，不等于所有婚姻关系。"),
    pattern: w("n.（复数）", "模式；方式", "patterns是主语中心，具体指交谈模式，不是图案或剪裁纸样。"),
    between: w("prep.", "在……之间", "between man and wife构成between A and B，and连接夫妻双方，整组后置说明patterns。"),
    different: w("adj.", "不同的", "are后的表语，描述patterns，不是动作的宾语。"),
  },
  "question-201030-prompt": {
    follow: w("adj.（分词形式）", "接下来的；后续的", "following修饰part，指紧接本文的下一部分，不是第28题the following的下列选项。"),
    part: w("n.", "部分", "the following part表示后续篇章部分，不是人物扮演的角色。"),
    immediately: w("adv.", "紧接着；立即", "修饰after this text，要求直接承接结尾，不是以后任意一段。"),
    after: w("prep.", "在……之后", "after后是this text名词短语，不构成带主谓的时间从句。"),
    will: w("modal v.", "将会", "will focus表达对后续写作的预测，不是名词意愿，也不是at will中的随意。"),
    most: w("adv.", "最", "修饰probably，表示最可能，并非大多数作者。"),
    probably: w("adv.", "很可能", "保留推断性质；没有真实后文可供直接核实。"),
    focus: w("v.", "着重于；集中于", "focus on接要展开的话题，on后由名词短语选项补出；不是名词焦点。"),
    on: w("prep.", "关于；在……方面", "focus on中的介词引出关注对象，不是物理位置在表面。"),
  },
  "question-201030-option-A": {
    vivid: w("adj.", "生动的", "修饰account，说明介绍的表达效果，不是书名的一部分。"),
    account: w("n.", "叙述；介绍", "a vivid account的中心名词，of短语引出介绍对象；不是账户、账单或account for中的解释。"),
    new: w("adj.", "新的；新近的", "修饰book，仍是文中写作时的新书，不代表今天新出版。"),
    divorce: w("n.（书名成分）", "离婚", "Divorce与Talk组成书名，作为book的同位说明；不在这里产生一个离婚率统计。"),
    talk: w("n.（书名成分）", "谈话；交谈", "Talk是书名的一部分，不是谓语‘交谈’。"),
  },
  "question-201030-option-B": {
    detailed: w("adj.", "详细的", "修饰description；不是本项独立的过去时谓语。"),
    description: w("n.", "描写；描述", "名词短语中心，of说明描写对象；与describe动词区分。"),
    stereotypical: w("adj.", "模式化的；惯常形象的", "修饰cartoon，指常见的那类夫妻场景；不要求把性别刻板印象当成普遍事实。"),
    cartoon: w("n.", "漫画", "指末段引入的静态漫画场景，不是动画影片。"),
  },
  "question-201030-option-C": {
    other: w("determiner", "其他的", "限定reasons，把话题扩到刚才交流原因以外。"),
    possible: w("adj.", "可能的", "修饰reasons，保留原因尚属可能的语气。"),
    reason: w("n.（复数）", "原因", "reasons是中心名词，for引出需要解释的现象。"),
    for: w("prep.", "关于……的原因", "reasons for a high divorce rate说明何种现象的原因，不是目的不定式。"),
    rate: w("n.", "比率", "divorce rate整体为离婚率；单独rate不等于由沟通失败造成的比例。"),
    high: w("adj.", "高的", "修饰divorce rate，比率高，不是空间位置高。"),
  },
  "question-201030-option-D": {
    brief: w("adj.", "简要的；简短的", "修饰introduction，表示介绍篇幅不长；不是法律案情摘要这个名词。"),
    introduction: w("n.", "介绍", "中心名词，to后指明介绍对象；不是动词introduce。"),
    to: w("prep.", "对；关于", "introduction to somebody引出介绍对象，后接名词短语，不是不定式。"),
    political: w("adj.", "政治的；政治学的", "与scientist组合为political scientist，整体指政治学家；political单词本身不包含学家。"),
    scientist: w("n.", "研究者；学者", "political scientist整体是政治学家，Andrew Hacker是姓名同位说明。"),
    andrew: w("proper n.", "安德鲁（人名）", "与Hacker共同构成研究者姓名，识别人物即可。"),
    hacker: w("proper n.", "哈克（姓氏）", "此处为Andrew Hacker的姓，不是入侵计算机的黑客。"),
  },
};
