import type { SentenceWordContext } from "./contextual-vocabulary";
import type { WordKnowledge } from "./knowledge-base";
type Seed=SentenceWordContext&{knowledge:WordKnowledge};
const w=(partOfSpeech:string,contextualMeaning:string,use:string,pattern:string,meaning:string):Seed=>({partOfSpeech,contextualMeaning,use,knowledge:{grammarRole:partOfSpeech,grammarSummary:use,structures:[{pattern,meaning,rule:use}]}});
// 人工按原句和题项分别确认，避免正文定位句替代实际查词来源。
const sources:Record<string,Record<string,Seed>>={
"2010-p4-s1":{
american:w("n.（复数）","美国人","Americans是regard的主语，Many限定为许多美国人。","Many Americans regard A as B","许多美国人把A视为B"),as:w("prep.","作为","as引出jury system的宾语补足语，说明把制度视为什么。","regard A as B","把A视为B"),regard:w("v.","看作","主语Many Americans主动评价制度，as引出评价内容。","regard A as B","把A看作B"),of:w("prep.","的；说明内容或范围","of分别说明体现的价值、资格涉及的项目、样本来自的社区及良知或法条的所属。","qualifications of age and literacy","年龄与读写能力方面的资格"),value:w("n.（复数）","价值观","values作of的宾语，被crucial democratic共同限定。","crucial democratic values","重要民主价值观"),that:w("conj.","引出原则内容","五个that并列说明principles的具体内容，本身不作从句主语或宾语。","the principles that ...; that ...","……及……这些原则"),who:w("关系代词","符合条件的那些人","who回指citizens并作meet主语，限制all citizens的范围。","citizens who meet minimal qualifications","符合最低资格的公民"),all:w("det.","所有","all限定受到who从句限制的合格公民，并非无条件纳入任何人。","all citizens who meet minimal qualifications","所有达到最低条件的公民"),and:w("conj.","和；并且","and连接age/literacy、第五项原则及conscience/letter；最后一组含not just限制。","the conscience ... and not just the letter","良知，而不只是字面条文"),be:w("linking v./aux.","是；构成被动","are competent是系表，should be selected和be denied是被动，are entitled说明所享权利。","are competent; should be selected","有能力；应当被选出"),to:w("不定式标记 / prep.","引出活动或权利内容","to serve两处为不定式；entitled to trial中to为介词，trial是名词。","competent to serve; entitled to trial","有能力任职；有权接受审判"),on:w("prep.","作为成员；由于（搭配中）","serve on juries表示担任成员；on account of整体给出不应使用的排除理由。","serve on juries; on account of race","担任陪审员；因为种族"),should:w("modal v.","应当","should说明制度原则所要求的选取、权利保障与裁决标准。","jurors should be selected randomly","陪审员应随机选出"),from:w("prep.","从……中","from引出遴选陪审员的来源样本。","selected from a representative cross section","从具有代表性的样本中选取"),representative:w("adj.","有代表性的","修饰cross section，指样本能体现社区各类人。","a representative cross section of the community","社区各群体的代表性样本"),no:w("det.","没有任何","no citizen否定以所列背景剥夺任职权的行为。","no citizen should be denied the right","不应剥夺任何公民的权利"),by:w("prep.","由","by their peers说明执行审判的是被告的同侪。","trial by their peers","由其同侪进行的审判"),their:w("possessive det.","他们的","their回指defendants，peers是被告的同侪。","defendants ... their peers","被告及其同侪"),represent:w("v.","体现；代表","verdicts作主语，represent接conscience与letter两个对象。","verdicts should represent the conscience","裁决应体现良知"),just:w("adv.","仅仅","not just否定只拘泥法条，仍保留法条作为标准之一。","not just the letter of the law","不仅限于法律字面条文"),letter:w("n.","字面条文","letter与law组成固定表达，指法条的字面规定。","the letter of the law","法律的字面条文")},
"2010-p4-s2":{
be:w("aux./linking v.","构成被动；是","is said构成被动报道，to be中的be连接jury与example。","is said to be the best surviving example","据说是留存下来的最佳实例"),to:w("不定式标记","引出所述性质","to be补充said的内容，逻辑主语仍为jury。","be said to be ...","据说是……"),of:w("prep.","关于；所属类别","of说明example是哪一种民主的例子。","an example of direct democracy","直接民主的一个实例"),rather:w("adv.（搭配成分）","而非","rather than连接direct与representative两种民主形式。","direct rather than representative democracy","直接而非代议民主"),than:w("conj./prep.（搭配成分）","而不是","与rather一起引出被对照的representative。","A rather than B","是A而非B"),representative:w("adj.","代议制的","修饰democracy，指由选出的代表治理。","representative democracy","代议民主"),survive:w("v.-ing（定语）","留存","surviving在example前作定语，指至今仍存的制度实例。","the best surviving example","留存下来的最佳实例")},
"2010-p4-s3":{
in:w("prep.","在……中","句首限定直接民主这种制度情境。","in a direct democracy","在直接民主中"),take:w("v.","进行（搭配中）","take turns整体表示轮流，后接governing活动。","take turns governing themselves","轮流治理自己"),turn:w("n.（复数）","轮次","turns是take宾语；整个搭配表示轮流。","take turns doing something","轮流做某事"),themselves:w("reflexive pron.","他们自己","回指citizens，作governing的宾语。","citizens govern themselves","公民治理自己"),rather:w("adv.（搭配成分）","而非","rather than连接governing themselves与electing representatives的行为对照。","governing themselves rather than electing representatives","亲自治理而非选代表"),than:w("conj./prep.（搭配成分）","而不是","引出被对照的electing representatives。","rather than electing representatives","而不是选出代表"),representative:w("n.（复数）","代表","representatives作electing宾语，同时是to govern的逻辑主语。","elect representatives to govern","选出代表治理"),to:w("不定式标记","引出代表的任务","to govern说明代表被选出后负责的活动。","elect representatives to govern for them","选代表替他们治理"),for:w("prep.","替；代表","for them表代表代替公民从事治理。","govern for them","替他们治理"),they:w("pron.（宾格）","公民们","them回指citizens，不是指representatives。","representatives govern for them","代表替公民治理")},
"2010-p4-s4":{
as:w("adv.（比较结构）","迟至（搭配中）","as recently as突出1968年距离作者叙述时期仍很近，程序仍与理想相悖。","as recently as in 1968","甚至迟至1968年"),recently:w("adv.","最近","在as recently as中强调所举时间之近。","as recently as in 1968","甚至迟至1968年"),with:w("prep.","与","with引出conflicted所抵触的民主理想。","procedures conflicted with ideals","程序与理想相冲突"),these:w("det.","这些","these回指首段的民主价值与制度原则。","these democratic ideals","前述民主理想")},
"2010-p4-s5":{
for:w("prep.（搭配成分）","用于举例","for example整体插入举出部分州的具体做法。","for example","例如"),be:w("aux.","构成被动","was limited表示陪审义务被限制于指定人群。","was limited to persons ...","被限定为某类人"),to:w("prep.","仅限的范围","limited to后接persons名词，不是不定式。","be limited to persons of ...","只限于具备某种品质的人"),of:w("prep.","具有","persons of后接品质名词，说明这类人的所谓优越条件。","persons of supposedly superior intelligence","被认为智力优越的人"),moral:w("adj.","道德的","moral修饰character，整个短语为道德品格。","moral character","道德品格"),and:w("conj.","和","连接intelligence、education与moral character三个选拔标准。","intelligence, education, and moral character","智力、教育与道德品格")},
"2010-p4-s6":{
although:w("conj.","尽管","引出法院早已禁止歧视这一让步背景，主句强调精英筛选仍可规避。","Although the Court had prohibited discrimination, the practice provided a way around laws","虽已禁止歧视，做法仍可绕过法律"),have:w("aux.（过去式）","标记过去完成时","had prohibited说明1880年的禁令早于后来持续的规避做法。","had prohibited discrimination","此前已禁止歧视"),state:w("n.（国名组成）","州（国名组成）","States与United组成国名United States，整体指美国。","the United States","美国"),of:w("prep.","的；说明内容","Court of the United States限定法院所属国家；practice of selecting说明做法内容。","the practice of selecting elite juries","挑选精英陪审团的做法"),as:w("adv.（比较结构）","早至（搭配中）","as early as强调禁令早在1880年便已出现。","as early as the 1880 case","早在1880年案件中"),early:w("adv.","早","early在as early as中修饰时间，不作country定语。","as early as 1880","早在1880年"),case:w("n.","案件","case后接Strauder v. West Virginia这一案件名称。","the 1880 case of Strauder v. West Virginia","1880年的斯特劳德诉西弗吉尼亚州案"),west:w("专名组成","西（州名组成）","West与Virginia组成West Virginia，指西弗吉尼亚州。","West Virginia","西弗吉尼亚州"),around:w("prep.","绕过","around后接this and other antidiscrimination laws，说明规避对象。","a way around antidiscrimination laws","绕过反歧视法律的办法"),this:w("det.","这项","this与other共享后面的laws，首先回指刚述1880禁令。","this and other antidiscrimination laws","这项以及其他反歧视法律"),and:w("conj.","和","连接this与other两组法律限定，不连接两个主句。","this and other antidiscrimination laws","这项及其他反歧视法律")},
"2010-p4-s7":{
fail:w("v.","未能","failed to include说明未能实现regularly这一经常性要求。","failed to regularly include women","未能常态化纳入女性"),to:w("不定式标记","引出未实现的行为","to include是不定式，regularly插入修饰include。","fail to regularly include","未能经常纳入"),on:w("prep.","作为成员","include women on juries指把女性纳入陪审团任成员。","include women on juries","纳入女性陪审员"),until:w("prep.","直到","与failed这一否定义结合，表示直到20世纪中叶才常态化纳入。","failed to regularly include ... until ...","直到……才经常纳入……"),century:w("n.","世纪","mid-20th century为20世纪中叶这个时间段。","the mid-20th century","20世纪中叶")},
"2010-p4-s8":{
although:w("conj.","尽管","1898年的首次参与为让步背景，多数州承认资格则迟至1940年代。","Although women first served ...","尽管女性首次任职……"),first:w("adv.","首次","first修饰served，指犹他州女性首次任陪审员。","women first served on state juries","女性首次担任州陪审员"),it:w("形式代词","构成强调句","it为强调句形式成分，不指女性或州；强调not until the 1940s这一时间。","it was not until ... that ...","直到……才……"),be:w("v.（强调结构）","构成强调句","was与it和that组成强调结构，不是were made被动。","it was not until the 1940s that ...","直到1940年代才……"),that:w("强调句标记","引出被强调事件","that之后是多数州使女性具备资格的完整事件。","it was not until ... that states made women eligible","直到……各州才使女性具备资格"),of:w("prep.","说明多数的范围","of states限定majority统计的是州的数量。","a majority of states","大多数州"),make:w("v.（过去式）","使","made women eligible是宾语加形容词宾补，说明赋予女性资格。","make somebody eligible for something","使某人有资格参与某事"),for:w("prep.","参与的事项","for jury duty补足eligible，说明具备什么资格。","eligible for jury duty","有资格任陪审员")},
"2010-p4-s9":{
then:w("adv.","那时","Even then承接多数州已承认女性资格之后的阶段。","Even then","即使在那时"),from:w("prep.","免除的事项","from jury duty说明女性被豁免的义务。","exempt women from jury duty","免除女性的陪审义务"),unless:w("conj.","除非","引女性主动申请这一例外条件；默认豁免并不等于禁止。","unless they personally asked ...","除非她们亲自请求……"),they:w("pron.","她们","they回指women，是personally asked的主语。","they personally asked","她们亲自请求"),to:w("不定式标记","引出请求内容","asked to have说明女性请求将名字列入名单。","ask to have their names included","请求把她们的名字列入"),have:w("v.","使……得到办理","have接names宾语及included过去分词宾补，名字是被纳入的对象。","have their names included on the jury list","使自己的名字列入陪审名单"),their:w("possessive det.","她们的","their回指women，names指女性自己的名字。","their names","她们的名字"),name:w("n.（复数）","名字","names是have宾语，接受included所表示的处理。","have their names included","把她们的名字列入"),include:w("v.（过去分词）","纳入","included作names的宾语补足语，names为被纳入对象。","have their names included","使名字被纳入"),on:w("prep.","在……上","on the jury list为included的名单位置。","included on the jury list","列在陪审员名单上")},
"2010-p4-s10":{
this:w("det.","这种","This practice回指默认豁免女性但接受本人申请的做法。","This practice","前述默认豁免做法"),be:w("aux.","构成被动","was justified和were needed均为过去时被动，分别以做法和女性为主语。","was justified; were needed","被辩解为合理；被需要"),by:w("prep.","凭借","by the claim说明用于为做法辩护的理由。","justified by the claim","凭该主张获得辩解"),that:w("conj.","引出主张内容","that完整解释claim，不在从句中充当成分。","the claim that women were needed at home","家中需要女性这一主张"),need:w("v.（过去分词）","需要","were needed为被动，处于他人claim的内容中，不代表作者认可。","women were needed at home","家中需要女性"),at:w("prep.","在","at home组成地点状语。","at home","在家里"),home:w("n.","家","home是at的宾语，指家庭这一场所。","needed at home","家中需要"),and:w("conj.","并且","and连接做法获得辩护与做法造成代表不足两个完整分句。","This practice was justified ... and it kept ...","做法被辩护，并导致……"),it:w("pron.","这种做法","it回指This practice，是kept的主语；非形式主语。","it kept juries unrepresentative","这种做法使陪审团缺乏代表性"),of:w("prep.","所代表的群体","unrepresentative of women说明缺少女性代表。","unrepresentative of women","不能充分代表女性"),through:w("prep.","贯穿整个时期","through the 1960s表示这一状态贯穿60年代。","through the 1960s","贯穿20世纪60年代")},
"2010-p4-s11":{
of:w("prep.","所属；说明内容","Congress of the United States说明国家归属；era of democratic reforms说明时代内容。","an era of democratic reforms","民主改革时代"),state:w("n.（国名组成）","州（国名组成）","United States整体为美国国名，不能把国会读成某个州的议会。","the Congress of the United States","美国国会"),in:w("prep. / 短语动词成分","在；进入","句首In 1968表时间；ushering in中的in与usher共同表开启新时代。","In 1968; ushering in a new era","在1968年；开启新时代"),and:w("conj.","和","and在法案名称中连接Selection与Service两项内容。","the Jury Selection and Service Act","陪审员遴选与服务法"),usher:w("v.-ing（结果状语）","开创","ushering in附加说明通过法案带来的结果，不是第二个限定谓语。","ushering in a new era","开创新时代"),reform:w("n.（复数）","改革","reforms是of宾语，被democratic修饰，说明新时代的内容。","an era of democratic reforms","民主改革时代"),for:w("prep.","针对","for the jury说明改革的制度对象。","reforms for the jury","陪审制度改革")},
"2010-p4-s12":{
this:w("det.","这项","This law回指上句1968年通过的法案。","This law abolished ...","该法案废除了……"),special:w("adj.","特殊的","special修饰educational requirements，指额外特定教育要求。","special educational requirements","特殊教育要求"),for:w("prep.","针对","for federal jurors限定要求适用人群为联邦陪审员。","requirements for federal jurors","针对联邦陪审员的要求"),and:w("conj.","并且","and连接abolished与required两项共享This law主语的动作。","abolished requirements and required random selection","废除要求并规定随机选取"),they:w("pron.（宾格）","联邦陪审员","them回指federal jurors，作required宾语和被选择的对象。","required them to be selected","要求他们被选出"),to:w("不定式标记","引出要求内容","to be selected为被动不定式，补足required them。","require somebody to be selected","要求某人被选出"),be:w("aux.","构成被动","be与selected组成被动不定式，them是被遴选者。","to be selected at random","以随机方式被选出"),at:w("prep.（搭配成分）","以……方式","at random整体作selected的方式状语。","at random","随机地"),random:w("n.（固定搭配）","随机","random在at random固定介词短语中，整体译为随机地，单词本身不是副词。","at random","随机地"),from:w("prep.","从……中","from引出选取所依据的社区代表性样本。","selected from a cross section","从具有代表性的样本中选出"),of:w("prep.","所代表的整体","of the entire community限定cross section要代表社区整体。","a cross section of the entire community","整个社区各群体的样本")},
"2010-p4-s13":{
that:w("conj.","引出要求内容","that从句解释requirement；边界到community，后面的to the state level属于主句extended。","the requirement that juries be representative","陪审团须有代表性这一要求"),be:w("linking v.（原形虚拟）","应当具有","requirement所引要求类从句用原形be，表要求而非叙述已发生事实。","the requirement that juries be representative","陪审团应具有代表性的要求"),representative:w("adj.","有代表性的","作be的表语，of引出应代表的社区群体。","representative of all parts of the community","代表社区所有群体"),of:w("prep.","代表范围；所属整体","representative of引代表范围，parts of限定各部分所属社区。","all parts of the community","社区的所有群体"),all:w("det.","所有","all修饰parts，不是仅某些精英群体。","all parts of the community","社区的所有群体"),part:w("n.（复数）","组成部分；群体","parts指组成社区的各类群体。","all parts of the community","社区所有群体"),to:w("prep.","到","to the state level接主句extended，说明要求扩展到哪个层级。","extend the requirement to the state level","把要求扩展到州一级")},
"2010-p4-s14":{
to:w("不定式标记","引出认定或命令内容","to be补足declared discrimination，to use补足ordered states，两项宾补分别对应不同宾语。","declare A to be B; order somebody to do","认定A为B；命令某人做事"),be:w("linking v.","是","to be unconstitutional说明被认定的性别歧视具有违宪性质。","declare discrimination to be unconstitutional","认定歧视违宪"),and:w("conj.","并且","连接declared和ordered，两项主语都是The Taylor decision。","declared discrimination ... and ordered states ...","认定歧视……并命令各州……"),use:w("v.","使用","use为to后原形，接procedures宾语，执行者为states。","states to use the same procedures","各州使用相同程序"),same:w("adj.","相同的","same修饰procedures，要求遴选男性女性用同一程序。","the same procedures for selecting male and female jurors","遴选男女陪审员的相同程序"),for:w("prep.","用于","for后接selecting动名词，说明procedures的用途。","procedures for selecting jurors","遴选陪审员的程序"),male:w("adj.","男性的","与female并列，共同修饰jurors。","male and female jurors","男性和女性陪审员"),female:w("adj.","女性的","female与male并列修饰jurors，不单独作名词。","male and female jurors","男性与女性陪审员")},
};
const q=(n:number,k:string,words:Record<string,Seed>)=>{sources[`question-2010${n}-${k==="prompt"?"prompt":`option-${k}`}`]=words;};
q(36,"prompt",{us:w("专名缩写作定语","美国","US指United States，限定jury system，不是we的宾格us。","the US jury system","美国陪审制度"),from:w("prep.","依据","From引出读者推论所依据的制度原则。","From the principles ... we learn ...","由这些原则我们得知……"),of:w("prep.","所属制度","of the US jury system限定principles属于哪个制度。","the principles of the US jury system","美国陪审制度的原则"),learn:w("v.","得知","learn后接that内容从句，指从原则获得认识。","we learn that ...","我们得知……"),that:w("conj.","引出所知内容","that引learn的宾语从句，命题由选项补齐。","learn that + clause","得知……")});
q(36,"A",{both:w("并列限定成分","两者都","both...and连接literate和illiterate两类人。","both literate and illiterate people","识字和不识字的人都"),and:w("conj.","和","与both组成配对并列结构，连接两类人。","both A and B","A和B两者都"),on:w("prep.","作为成员","on juries补足serve，说明服务身份。","serve on juries","担任陪审员")});
q(36,"B",{be:w("linking v.","是；具有某状态","are连接defendants与immune表语。","are immune from trial","免受审判"),from:w("prep.","免受的事物","immune from引出被免除的trial。","immune from trial","免受审判"),by:w("prep.","由","by their peers限定审判由谁执行。","trial by their peers","由他们同侪执行的审判"),their:w("possessive det.","他们的","their回指defendants。","their peers","被告的同侪")});
q(36,"C",{limit:w("n.","限制","age limit作主语，no否定任何年龄限制。","no age limit","没有任何年龄限制"),should:w("modal v.","应当","should be imposed为应当施加，否定来自主语中的no。","no age limit should be imposed","不应施加任何年龄限制"),be:w("aux.","构成被动","be imposed以limit为承受对象。","should be imposed","应被施加"),for:w("prep.","针对","for jury service说明年龄限制的适用活动。","an age limit for jury service","担任陪审员的年龄限制")});
q(36,"D",{should:w("modal v.","应当","should consider对裁决应考虑的因素提出要求。","judgment should consider the opinion","裁决应考虑意见"),of:w("prep.","属于","of the public说明opinion的持有群体。","the opinion of the public","公众意见"),public:w("n.","公众","the public整体作of宾语，指公众群体。","the public","公众")});
q(37,"prompt",{of:w("prep.","说明做法内容","of selecting接动名词，解释practice内容。","the practice of selecting elite jurors","遴选精英陪审员的做法"),select:w("v.-ing（动名词）","挑选","selecting作of宾语，后接jurors。","the practice of selecting jurors","挑选陪审员的做法"),to:w("prep.","早于的时间点","prior to为介词性结构，to后1968为时间名词。","prior to 1968","1968年之前")});
q(37,"A",{of:w("prep.","说明不足的对象","of限定存在不足的是反歧视法律。","the inadequacy of antidiscrimination laws","反歧视法律的不充分")});
q(37,"B",{against:w("prep.","针对","against certain races限定受歧视对象。","discrimination against certain races","针对某些种族的歧视"),certain:w("det./adj.","某些","certain限定races为某些群体，不表示确信。","certain races","某些种族")});
q(37,"C",{conflict:w("v.-ing（定语）","相冲突","conflicting直接修饰ideals，声称不同理想相冲突。","the conflicting ideals","相互冲突的理想")});
q(37,"D",{common:w("adj.","普遍存在的","common among...后置修饰arrogance，说明傲慢在法官中常见。","arrogance common among the judges","法官中普遍存在的傲慢"),among:w("prep.","在……群体中","among限定common所描述的人群。","common among the Supreme Court judges","在最高法院法官中常见"),judge:w("n.（复数）","法官","judges作among的宾语，Supreme Court限定所属法院。","the Supreme Court judges","最高法院法官")});
q(38,"prompt",{be:w("linking v.","处于","were连接women与on the jury list，描述列名状态。","women were seldom on the jury list","女性很少列入陪审名单"),on:w("prep.","在……上","on the jury list说明名单收录状态。","on the jury list","在陪审员名单上"),because:w("conj.","因为","because后接选项完整命题，解释女性少见于名单的原因。","because + clause","因为……")});
q(38,"A",{they:w("pron.","她们","they回指题干women，是被禁止者。","they were banned","她们被禁止"),be:w("aux.","构成被动","were banned为过去时被动，banned声称禁止。","were automatically banned","被自动禁止"),by:w("prep.","由","by state laws说明禁止的施动因素。","banned by state laws","被州法律禁止")});
q(38,"B",{they:w("pron.","她们","they回指题干women，是声称未达标的群体。","they fell short of the qualifications","她们未达到资格要求"),fall:w("v.（过去式）","未达到（搭配中）","fell与short of组成习语，说明未达到资格，不表示跌落。","fall short of requirements","未达到要求"),far:w("adv.","远远","far加强short的不足程度。","far short of the required qualifications","远未达到所需资格"),short:w("adj.","不足的","short在fall short of中表示未达到某标准。","fall short of something","未达到某标准"),of:w("prep.","所未达到的标准","of引出qualifications，补足short。","short of the required qualifications","未达到所需资格"),require:w("v.（过去分词定语）","要求","required在qualifications前作被动意义定语。","the required qualifications","所要求的资格")});
q(38,"C",{they:w("pron.","她们","they回指女性，承受社会角色预期。","they were supposed to perform domestic duties","她们被认为应承担家务"),be:w("aux.","构成被动期待表达","were supposed to说明被认为应当，未直接断言女性确实做了什么。","be supposed to do something","被认为应当做某事"),to:w("不定式标记","引出预期行为","to perform补出supposed的行为内容。","supposed to perform domestic duties","被认为应承担家庭职责")});
q(38,"D",{they:w("pron.","她们","they回指女性，选项声称她们主动回避。","they tended to evade","她们倾向于逃避"),tend:w("v.（过去式）","倾向于","tended为限定过去式谓语，后接to evade不定式。","tend to evade public engagement","倾向于逃避公共参与"),to:w("不定式标记","引出倾向的行为","to evade为tended的内容补足语。","tend to evade","倾向于逃避"),public:w("adj.","公共的","public修饰engagement，指参与公共事务。","public engagement","公共事务参与")});
q(39,"prompt",{after:w("conj.","在……之后","After引完整时间从句，Act为主语，was passed为谓语。","After the Act was passed","在法案通过之后"),and:w("conj.","和","and连接法案名中的Selection与Service。","the Jury Selection and Service Act","陪审员遴选与服务法"),be:w("aux.","构成被动","was passed表示法案被通过，不是法案自己执行动作。","the Act was passed","法案获通过")});
q(39,"A",{be:w("linking v./aux.","是；构成被动","was unconstitutional为系表；be abolished为被动。","was unconstitutional and had to be abolished","违宪并必须被废除"),and:w("conj.","并且","连接同一主语的两个谓语，不连接两种歧视。","was unconstitutional and had to be abolished","违宪且必须废除"),have:w("情态性结构组成","必须","had to表示过去必须，后接be abolished被动原形结构。","had to be abolished","必须予以废除"),to:w("情态性结构组成","引出义务行为","had to与后面be abolished构成必须被废除的判断。","have to be abolished","必须被废除")});
q(39,"B",{less:w("adv.","不那么","less修饰rigid构成程度降低的比较。","became less rigid","变得不那么严格"),of:w("prep.","被遴选的对象","of federal jurors说明selection选择谁。","the selection of federal jurors","遴选联邦陪审员")});
q(39,"C",{to:w("情态性结构组成","引出应当具有的性质","ought to后接be原形，整个谓语表达应有代表性。","ought to be representative","应当具有代表性"),be:w("linking v.","具有","be连接jurors与representative表语。","be representative of the entire community","代表整个社区"),representative:w("adj.","有代表性的","作be的表语，of限定应代表全体社区。","representative of the entire community","代表整个社区"),of:w("prep.","所代表的群体","of引出代表范围，不是代议民主的修饰语。","representative of the community","有社区代表性")});
q(39,"D",{to:w("情态性结构组成 / prep.","引出行为；引出遵从对象","ought to后接conform原形；conform to后的to为介词，接the federal court。","ought to conform to the federal court","应当遵从联邦法院"),in:w("prep.","在……方面","in reforming限定conform发生的行为领域。","in reforming the jury system","在改革陪审制度方面"),reform:w("v.-ing（动名词）","改革","reforming作in的宾语，后接jury system。","in reforming the jury system","在改革陪审制度方面")});
q(40,"prompt",{us:w("专名缩写作定语","美国","US为美国国名缩写，限定jury system。","the US jury system","美国陪审制度"),in:w("prep.","在……时；在……方面","In discussing以动名词引话题背景。","In discussing the US jury system","在讨论美国陪审制度时"),center:w("v.（第三人称单数）","以……为中心","centers作text的谓语，on引全文中心议题。","the text centers on something","文章围绕某个主题"),on:w("prep.","围绕的主题","on补足centers，由选项提供名词短语。","center on a topic","围绕某个主题")});
q(40,"A",{its:w("possessive det.","它的","its回指美国陪审制度，同时限定nature与problems。","its nature and problems","该制度的性质与问题"),nature:w("n.","性质","nature在此指制度的本质特征。","the nature of the system","制度的性质"),and:w("conj.","和","and连接nature与problems两个主题。","nature and problems","性质与问题")});
q(40,"B",{its:w("possessive det.","它的","its指美国陪审制度。","its characteristics and tradition","该制度的特点与传统"),and:w("conj.","和","连接characteristics与tradition两个主题。","characteristics and tradition","特点与传统")});
q(40,"C",{its:w("possessive det.","它的","its指陪审制度，限定problems。","its problems","该制度的问题"),their:w("possessive det.","它们的","their回指复数problems，solutions是这些问题的解决办法。","problems and their solutions","问题及其解决办法"),and:w("conj.","和","连接问题与针对这些问题的解决办法。","problems and their solutions","问题及其解决办法")});
q(40,"D",{its:w("possessive det.","它的","its指陪审制度，共同限定tradition与development。","its tradition and development","该制度的传统与发展"),and:w("conj.","和","连接民主传统与历史演进两个主题。","tradition and development","传统与发展"),development:w("n.","发展；演变","development概括制度由理想到实际筛选再到改革的历史变化。","the development of the jury system","陪审制度的历史演变")});
Object.assign(sources["2010-p4-s2"],{say:w("v.（过去分词）","说；认为","said与is组成被动报道，to be补出所作评价。","be said to be something","被认为是……")});
Object.assign(sources["2010-p4-s5"],{limit:w("v.（过去分词）","限制","limited与was组成被动，to引受限的任职人群。","be limited to somebody","仅限于某类人")});
Object.assign(sources["2010-p4-s6"],{way:w("n.","办法","way接around引出规避对象，指绕过法律的方法。","a way around laws","规避法律的办法")});
Object.assign(sources["2010-p4-s7"],{regularly:w("adv.","经常地；常态化地","regularly修饰include，未常态化纳入允许存在少数先例。","regularly include women","经常纳入女性")});
Object.assign(sources["2010-p4-s8"],{until:w("prep.","直到","not until与强调句结合，突出多数州承认资格的迟延。","not until the 1940s","直到20世纪40年代才")});
Object.assign(sources["2010-p4-s12"],{entire:w("adj.","整个的","entire修饰community，样本须代表整个社区。","the entire community","整个社区")});
Object.assign(sources["question-201039-option-B"],{become:w("linking v.（过去式）","变得","became连接requirements与less rigid，说明要求严格程度下降。","became less rigid","变得不那么严格")});
Object.assign(sources["question-201039-option-C"],{entire:w("adj.","整个的","entire修饰community，说明应代表的完整范围。","the entire community","整个社区")});
export const passage2010P4ReviewedContexts:Record<string,Record<string,SentenceWordContext>>=Object.fromEntries(Object.entries(sources).map(([source,words])=>[source,Object.fromEntries(Object.entries(words).map(([head,entry])=>[head,{partOfSpeech:entry.partOfSpeech,contextualMeaning:entry.contextualMeaning,use:entry.use}]))]));
export function getPassage2010P4WordKnowledge(head:string,sourceId?:string):WordKnowledge|undefined{return sourceId?sources[sourceId]?.[head]?.knowledge:undefined;}
