import type { SentenceWordContext } from "./contextual-vocabulary";

type Entry = { partOfSpeech: string; contextualMeaning: string; use: string; specialForms: string[]; examSynonyms: string[]; confusions: string[] };
const rows = [
  ["enough", "", "adv.", "足够地", "放在副词hard后，表示观察得足够仔细；不放hard之前。", "sufficiently（充分地，位置和搭配需要调整）"],
  ["you", "you'll", "pron.", "你；泛指读者", "you'll是you will；If you look中的you同样泛指观察者。", "you主格与宾格同形；you'll不能当作独立词根。"],
  ["air", "", "n.", "空气", "air fresheners是空气清新剂，air限定产品作用对象。", "breath（呼吸气息，不等于环境空气）"],
  ["water", "waters", "n.", "水", "drink或sip的宾语；bottled water是瓶装水，通常不可数。", "beverage（饮料，类别比水更宽）"],
  ["decade", "decades", "n.", "十年", "past decade为过去十年；a few decades为几十年。", "century（世纪，一百年而非十年）"],
  ["drink", "drinks drank drunk drinking", "v.", "喝；饮用", "didn't drink以did承担过去时，drink保持原形。", "sip（小口喝，方式更具体）"],
  ["start", "starts started starting", "v.", "开始", "start bottling后接动名词作宾语，开始将泉水装瓶。", "begin（开始，搭配通常相近）"],
  ["company", "companies", "n.", "公司；企业", "the companies是投资主体；company不可与Tide等产品品牌混淆。", "firm（公司，强调经营组织）"],
  ["perfect", "perfects perfected perfecting", "v.", "使完善；熟练掌握", "had perfected the art指把培养消费习惯的手法完善成熟，不是形容词完美的。", "improve（改进，不必达到完善程度）"],
  ["art", "arts", "n.", "技巧；手法", "the art of doing表示做某事的技巧，本篇不指艺术市场。", "skill（技能，较强调个人能力）"],
  ["automatic", "", "adj.", "自动的；不假思索的", "修饰behaviors，把习惯解释为无须刻意思考的行为。", "unthinking（不加思索的，可能带贬义）"],
  ["behavior", "behaviors", "n.", "行为；举止", "creating behaviors与改变消费动作有关；可数复数强调不同类型行为。", "action（行动，较突出单次动作）"],
  ["habit", "habits", "n.", "习惯", "指反复发生而渐趋自动化的行为；manufactured habits为人为培养的习惯。", "routine（日常惯例，强调固定程序）"],
  ["consumer", "consumers consumers'", "n.", "消费者", "产品使用者；consumer psychologist中作名词定语，表示研究消费心理的人。", "customer（顾客，强调购买关系）"],
  ["these", "", "det./pron.", "这些", "These habits回指企业培养的消费习惯；these限定复数名词。", "this（这个，用于单数而非复数）"],
  ["help", "helps helped helping", "v.", "帮助；促成", "help companies earn是help+宾语+省to不定式，使企业获利。", "enable（使能够，后接宾语+to do）"],
  ["earn", "earns earned earning", "v.", "赚取", "earn billions of dollars以金额作宾语，表示获得收入。", "gain（获得，范围更广）"],
  ["billion", "billions", "num./n.", "十亿", "billions of表示数十亿；76 billion为760亿，确数后billion不加s。", "million（一百万，数量级不同）"],
  ["dollar", "dollars", "n.", "美元", "金额名词；billions of dollars以复数表示多美元。", "专指本文货币单位，不能随意换为其他货币。"],
  ["eat", "eats ate eaten eating", "v.", "吃", "eat snacks与wipe counters并列，主语都是customers。", "consume（消费、摄入，语体更正式）"],
  ["snack", "snacks", "n.", "零食；小吃", "eat snacks为吃零食；health snacks指作为健康产品推广的零食。", "food（食物，范围更宽）"],
  ["wipe", "wipes wiped wiping", "v.", "擦拭", "wipe counters指擦台面；disinfecting wipes中的wipes另按名词卡说明。", "clean（清洁，不限定擦拭动作）"],
  ["counter", "counters", "n.", "台面；柜台", "wipe的宾语，指日常清洁的表面，不是反击或计数器。", "surface（表面，范围更宽）"],
  ["without", "", "prep.", "没有；不经", "without thinking后接动名词，作行为的方式状语。", "介词后不直接接限定谓语；否定的是伴随思考。"],
  ["carefully", "", "adv.", "精心地", "修饰designed，说明提示系统经过有意安排。", "deliberately（有意地，更强调意图）"],
  ["design", "designs designed designing", "v.", "设计", "designed为过去分词，修饰set；设计的是触发消费的提示组合。", "plan（规划，不必落实细节）"],
  ["set", "sets", "n.", "一套；一组", "a set of daily cues以set为中心名词，不是动词设置。", "group（一组，未必是配套系统）"],
  ["cue", "cues", "n.", "提示；触发线索", "把日常提示与行为绑定，借环境和动作触发消费。", "signal（信号，更突出明确传递信息）"],
  ["fundamental", "", "adj.", "根本的；基础性的", "修饰public health problems，强调卫生习惯问题的基础地位。", "basic（基础的，语气较普通）"],
  ["dirty", "dirtier dirtiest", "adj.", "脏的", "dirty hands指没有清洁的手，是卫生风险例子。", "unclean（不洁的，较正式）"],
  ["soap", "soaps", "n.", "肥皂", "a soap habit是用肥皂洗手的习惯；with soap表示洗手使用的材料。", "不可把soap habit理解为生产肥皂的习惯。"],
  ["killer", "killers", "n.", "致命因素", "remain killers用疾病杀手作比喻，指卫生问题仍会夺命。", "danger（危险，未必致命）"],
  ["can", "could can't", "modal v.", "能够；可以", "can't figure out是不能弄清；could use说明可利用的提示。", "be able to（能够，需要结构调整）"],
  ["figure", "figures figured figuring", "v.", "弄清；想出", "figure out整体表示理解并找到办法，不能读作人物或数字。", "understand（理解，不一定含解决过程）"],
  ["people", "people's", "n.", "人们", "people's habits用所有格修饰习惯；people在这里是复数集合称人。", "persons（个人，语体和计数侧重点不同）"],
  ["dr", "", "n.（称谓缩写）", "博士", "Dr.放在人名前；句点属于缩写，不是分句界限。", "此处表示研究者学术称谓，不据此推断临床医师身份。"],
  ["curtis", "", "n.（专名）", "柯蒂斯", "公共卫生研究者姓氏，与Dr.连用。", "人名保留，不进行近义替换。"],
  ["hygiene", "", "n.", "卫生", "Hygiene Center和院校名中的Hygiene都指卫生学领域。", "health（健康，关注状态而非保持卫生的方法）"],
  ["center", "centers", "n.", "中心", "Hygiene Center指卫生中心机构；at引出所属院校。", "centre（英式拼写，原文仍保留center）"],
  ["tropical", "", "adj.", "热带的", "Tropical Medicine为热带医学，属于院校名称。", "不可把院校名称当作热带地区的地理位置。"],
  ["medicine", "medicines", "n.", "医学", "院校名中的Medicine指学科，而非一粒药。", "medical science（医学学科，须调整名称结构）"],
  ["want", "wants wanted wanting", "v.", "想要", "wanted to learn说明研究者希望学习培养卫生习惯的方法。", "wish（希望，语气可更正式）"],
  ["private", "", "adj.", "私营的；私人的", "private industry是私营企业界；31D的private concerns则把公共卫生误称私人问题。", "personal（个人的，不等于企业私营）"],
  ["industry", "industries", "n.", "企业界；行业", "private industry指商业企业部门，而非仅重工业。", "business（商业经营，范围与结构需区分）"],
  ["automatically", "", "adv.", "自动地；自然而然地", "修饰happen，与automatic为派生关系而非同一屈折词形。", "habitually（习惯性地，侧重反复行为）"],
  ["turn", "turns turned turning", "v.", "求助；转向", "turn to后接求助对象，关系代词that对应to的宾语。", "seek help（寻求帮助，需调整结构）"],
  ["procter", "", "n.（专名）", "宝洁名称的一部分", "与& Gamble合成Procter & Gamble公司名。", "公司专名不能按普通动词翻译。"],
  ["gamble", "", "n.（专名）", "宝洁名称的一部分", "在Procter & Gamble中属于公司专名，不是动词赌博。", "普通名词gamble另有冒险之义，不适用于此名称。"],
  ["colgate-palmolive", "", "n.（专名）", "高露洁-棕榄公司", "第5句公司名单中的一员；与牙膏品牌Colgate区分。", "专名不可用同义词替换。"],
  ["unilever", "", "n.（专名）", "联合利华公司", "companies后的同位列举，33题要求区分公司与产品。", "不是Tide或Crest这样的具体产品品牌。"],
  ["invest", "invests invested investing", "v.", "投入；投资", "invest money (in) doing表示投入资金做某事，本句finding前省in。", "spend（花费，不一定有投资回报目标）"],
  ["hundred", "hundreds", "num./n.", "百", "hundreds of millions是数亿；hundreds of后接复数名词。", "不能把hundreds of millions译成几百。"],
  ["find", "finds found finding", "v.", "寻找；发现", "finding cues是寻找提示；you'll find that是发现某个事实。", "discover（发现，强调此前不知）"],
  ["subtle", "subtler subtlest", "adj.", "细微的；不易察觉的", "修饰cues，说明触发行为的线索不一定明显。", "slight（轻微的，更强调程度小）"],
  ["life", "lives", "n.", "生活", "consumers' lives指日常生活，不是此处有几条生命。", "living（日常生活方式，需看名词结构）"],
  ["routine", "routines", "n.", "惯例；固定程序", "introduce new routines指引入新的日常行为程序。", "habit（习惯，侧重个人自动化行为）"],
  ["hard", "harder hardest", "adv.", "认真地；仔细地", "look hard enough中hard修饰look，不是hardly几乎不。", "carefully（仔细地，强调谨慎）"],
  ["product", "products", "n.", "产品", "企业销售的商品，不等于生产它的公司。", "goods（商品，通常复数集合用法）"],
  ["chew", "chews chewed chewing", "v.", "咀嚼", "chewing gum整体为口香糖，chewing说明用途。", "eat（吃，不限定咀嚼这个动作）"],
  ["gum", "gums", "n.", "口香糖", "chewing gum常作物质名词；列举中的gums指口香糖产品类型。", "普通gum另可指牙龈，本文不是这一义项。"],
  ["skin", "skins", "n.", "皮肤", "skin moisturizers中作名词定语，限定润肤品用途。", "不是动词剥皮。"],
  ["moisturizer", "moisturizers", "n.", "润肤品；保湿剂", "广告将其纳入早晨美容流程。", "cream（乳霜，未必专为保湿）"],
  ["disinfect", "disinfects disinfected disinfecting", "v.", "消毒", "disinfecting wipes为具有消毒用途的湿巾。", "clean（清洁，不必达到消毒效果）"],
  ["freshener", "fresheners", "n.", "清新剂", "air freshener清新空气；breath freshener清新口气，对象不同。", "fresh为形容词，不可当作同一原形计数。"],
  ["purifier", "purifiers", "n.", "净化器", "water purifiers是净水器，purifier为执行净化的器具。", "filter（过滤器，只突出过滤机制）"],
  ["tooth", "teeth", "n.", "牙齿", "teeth为不规则复数；brush one's teeth是刷牙。", "tooth与teeth属于同一词位。"],
  ["whitener", "whiteners", "n.", "美白剂", "teeth whiteners指牙齿美白产品。", "white与whiten为相关派生词，不是本名词的屈折变化。"],
  ["fabric", "fabrics", "n.", "织物；布料", "fabric softeners是织物柔顺剂，fabric限定使用对象。", "cloth（布，通常指材料或一块布）"],
  ["softener", "softeners", "n.", "柔顺剂；软化剂", "fabric softeners用于使织物柔软。", "soft为形容词，不能并入名词原形次数。"],
  ["vitamin", "vitamins", "n.", "维生素", "列举日常消费产品，可数复数指不同种类。", "不等于所有营养素。"],
  ["result", "results", "n.", "结果；产物", "results of manufactured habits指人为培养的习惯所催生的产品。", "outcome（结果，较强调过程终点）"],
  ["manufacture", "manufactures manufactured manufacturing", "v.", "人为制造；塑造", "manufactured修饰habits，含有非自然形成的意味。", "create（创造，贬褒色彩较弱）"],
  ["century", "centuries", "n.", "世纪；一百年", "A century ago提供刷牙习惯变化的历史参照。", "decade（十年，时间单位不同）"],
  ["regularly", "", "adv.", "有规律地；经常", "修饰brushed，说明行为重复并形成规律。", "often（经常，不必具有固定规律）"],
  ["brush", "brushes brushed brushing", "v.", "刷；梳", "brush teeth刷牙；hair brushing是梳头活动。", "wipe（擦，动作及工具不同）"],
  ["multiple", "", "adj.", "多次的；多个的", "multiple times a day表示一天不止一次。", "many（许多，不特别强调多重）"],
  ["time", "times", "n.", "次数", "multiple times中time为可数的次数，而非不可数的时间。", "occasion（场合、一次事件，搭配不同）"],
  ["today", "", "adv.", "如今；今天", "与百年前对照，指文章所述的当今，不自动更新为阅读当天。", "now（现在）"],
  ["shrewd", "shrewder shrewdest", "adj.", "精明的；巧妙的", "修饰advertising，强调营销对消费心理的把握。", "clever（聪明的，范围更广）"],
  ["advertising", "", "n.", "广告宣传", "作为不可数活动名词，与campaigns并列；不并入advertise的动词统计。", "promotion（推广，手段不限于广告）"],
  ["campaign", "campaigns", "n.", "宣传活动", "public health campaigns是公共卫生宣传，不是战役。", "drive（有组织的活动，需具体语境）"],
  ["habitually", "", "adv.", "习惯性地", "修饰give，强调刷牙已成为惯常行为。", "regularly（有规律地，更强调频次）"],
  ["pearly", "", "adj.", "珍珠般洁白的", "pearly whites是牙齿的形象称呼。", "white（白色的，缺少珍珠般的形象）"],
  ["white", "whites", "n.", "洁白的牙齿", "pearly whites中名词化，指牙齿，不是白人或蛋白。", "tooth（牙齿，用复数teeth表达）"],
  ["cavity-preventing", "", "adj.", "预防龋齿的", "复合形容词修饰scrub；cavity在这里是蛀牙形成的洞。", "prevent是动词，需改结构才能替换形容词。"],
  ["scrub", "scrubs", "n.", "刷洗；清洁", "give teeth a scrub以名词表示一次刷洗，不是灌木。", "cleaning（清洁，力度意味较弱）"],
  ["twice", "", "adv.", "两次", "twice a day为每天两次，twice无普通复数。", "two times（两次，结构展开）"],
  ["colgate", "", "n.（专名）", "高露洁", "第8句指刷牙使用的牙膏品牌，不是公司全称。", "品牌不能用其他品牌作同义替换。"],
  ["crest", "", "n.（专名）", "佳洁士", "牙膏产品品牌，属于宝洁公司的商品。", "普通crest可指顶峰，此处不取普通词义。"],
  ["brand", "brands", "n.", "品牌", "one of the other brands表示其他品牌中的一个。", "company（公司，与品牌不是同一层级）"],
  ["outside", "", "prep./adv.", "在……之外", "outside of a meal表示用餐时间以外，并非空间方位。", "beyond（超出，搭配和范围不同）"],
  ["meal", "meals", "n.", "一餐；用餐", "after a meal饭后；outside of a meal非用餐时段。", "food（食物，不指一次用餐）"],
  ["beverage", "beverages", "n.", "饮料", "beverage companies中名词作定语，指饮料公司。", "drink（饮料，较日常）"],
  ["bottle", "bottles bottled bottling", "v.", "把……装瓶", "started bottling以动名词表示开始灌装；bottled water为被动分词修饰水。", "package（包装，不限定瓶子）"],
  ["production", "productions", "n.", "产出；产物", "the production of springs指泉水产出，不是戏剧演出。", "output（产量或产出，较强调数量）"],
  ["far-off", "", "adj.", "遥远的", "修饰springs，说明水源位置偏远。", "distant（遥远的）"],
  ["spring", "springs", "n.", "泉；泉水源头", "far-off springs为远处泉眼，不是春天或弹簧。", "source（水源，范围较宽）"],
  ["office", "offices", "n.", "办公室", "office workers为办公室职员，office作名词定语。", "不是公职或办事处的特定义项。"],
  ["unthinkingly", "", "adv.", "不假思索地", "修饰sip，强调喝瓶装水已成为自动化习惯。", "automatically（自动地，更强调无需有意识控制）"],
  ["sip", "sips sipped sipping", "v.", "小口喝；啜饮", "sip water强调小口饮用；过去式及分词双写p。", "drink（喝，不限定小口）"],
  ["primary", "", "adj.", "主要的", "作为primarily的词族基础，不并入副词原形计数。", "main（主要的）"],
  ["primarily", "", "adv.", "主要地", "限定过去的购买人群主要为男孩，不排除其他人。", "mainly（主要地）"],
  ["adolescent", "adolescents", "adj.", "青春期的", "adolescent boys中作定语，不是成年男子。", "young（年轻的，年龄范围更宽）"],
  ["boy", "boys", "n.", "男孩", "指口香糖过去的主要购买群体。", "child（儿童，不限定性别）"],
  ["feature", "features featured featuring", "v.", "重点展示；突出宣传", "is featured in commercials是被动，表成为广告重点。", "present（呈现，不一定突出）"],
  ["commercial", "commercials", "n./adj.", "商业广告；商业的", "in commercials中为广告名词；commercial promotions中为形容词商业的。", "advertisement（广告，媒介范围较宽）"],
  ["breath", "breaths", "n.", "口气；呼吸气息", "breath freshener指清新口气用品；breath不是动词breathe。", "air（空气，不专指呼出气息）"],
  ["cleanser", "cleansers", "n.", "清洁剂", "teeth cleanser指牙齿清洁用品，是广告给口香糖的定位。", "clean为动词或形容词，不能作为同一名词原形统计。"],
  ["advertise", "advertises advertised", "v.", "做广告宣传", "are advertised as把产品宣传为某种日常必需环节。", "promote（推广，不限于广告）"],
  ["part", "parts", "n.", "部分；环节", "part of morning beauty rituals是晨间美容的一环。", "component（组成部分，较技术化）"],
  ["morning", "mornings", "n.", "早晨", "morning beauty rituals中名词作时间定语。", "不是全文每一天都发生的确切时刻。"],
  ["beauty", "beauties", "n.", "美容；美丽", "beauty rituals为美容程序；beauty creams为美容霜。", "不把美容功效当作作者已证实的事实。"],
  ["ritual", "rituals", "n.", "固定程序；惯常行为", "晨间美容的重复程序，借用仪式的含义，不指宗教仪式。", "routine（日常惯例，语气较中性）"],
  ["slip", "slips slipped slipping", "v.", "悄然加入", "slipped in表示产品使用被不知不觉嵌入流程；双写p。", "insert（插入，更中性）"],
  ["hair", "hairs", "n.", "头发", "hair brushing指梳头；整体头发通常不可数。", "不是逐根计数头发的可数用法。"],
  ["put", "puts putting", "v.", "施用；涂抹", "put on makeup表示化妆；过去式和分词均为put，现在分词双写t。", "apply（涂抹，结构为apply makeup）"],
  ["makeup", "", "n.", "化妆品；化妆", "putting on makeup表示化妆，不是弥补或组成结构。", "cosmetics（化妆品，复数集合表达）"],
  ["weekly", "", "adj.", "每周的", "daily or weekly patterns中与daily平行修饰patterns。", "every week（每周，需要调整句法结构）"],
  ["carol", "", "n.（专名）", "卡罗尔", "Carol Berning中的名字，不取颂歌词义。", "人名不作同义替换。"],
  ["berning", "", "n.（专名）", "伯宁", "消费心理学家姓氏，在末段Dr. Berning仍指同一人。", "不是burn的分词。"],
  ["psychologist", "psychologists", "n.", "心理学家", "consumer psychologist研究消费者心理，who从句说明退休背景。", "scientist（科学家，范围较广）"],
  ["recently", "", "adv.", "最近", "修饰retired，相对于文章叙述时间。", "lately（近来，常用于完成时语境）"],
  ["retire", "retires retired retiring", "v.", "退休", "retire from+单位表示从某机构退休。", "leave（离开，不一定是退休）"],
  ["tide", "", "n.（专名）", "汰渍", "宝洁洗涤产品品牌，不取普通名词潮汐义。", "品牌名不能随意换成其他商品。"],
  ["improve", "improves improved improving", "v.", "改善", "improving consumers' lives以生活为改善对象，-ing为介词of的宾语。", "enhance（提升，搭配需核对）"],
  ["commercially", "", "adv.", "在商业上", "修饰viable，强调产品具备商业生存能力。", "不是名词commercials广告。"],
  ["viable", "", "adj.", "可行的；能生存发展的", "make products viable中为宾语补足语，说明商业上站得住脚。", "possible（可能的，未必具备实际生存能力）"],
  ["experiment", "experiments", "n.", "实验", "through experiments说明研究者得知机制的方法，不是消费者习惯的直接原因。", "test（测试，范围更宽）"],
  ["observation", "observations", "n.", "观察", "与experiments并列作为研究依据；此处为观察活动。", "study（研究，范围较宽）"],
  ["learn", "learns learned learnt learning", "v.", "学习；了解到", "learn from企业界是学习方法；have learned that是通过研究发现。", "find（发现，较突出结果）"],
  ["power", "powers", "n.", "力量；影响力", "there is power in doing说绑定提示和行为很有效，不是购买力。", "influence（影响力）"],
  ["tie", "ties tied tying", "v.", "联系；绑定", "tie A to B使行为和提示关联；tying由tie去ie加ying。", "connect（连接，介词搭配需核对）"],
  ["habitual", "", "adj.", "惯常的；习惯性的", "修饰cues，指反复出现在生活程序中的提示。", "usual（通常的，不强调养成习惯）"],
  ["ruthless", "", "adj.", "无情的；不顾后果的", "ruthless advertising含批评意味，支持作者否定态度的判断。", "harsh（严厉的，意义侧重不同）"],
  ["emerge", "emerges emerged emerging", "v.", "出现；兴起", "习惯科学逐渐形成，用完成时强调已出现。", "appear（出现，不一定含逐渐显现）"],
  ["controversy", "controversies", "n.", "争议", "controversies have erupted说明商业运用已引起争论。", "debate（讨论或辩论，不一定激烈对立）"],
  ["erupt", "erupts erupted erupting", "v.", "爆发", "用于争议的比喻表达，不是火山喷发的字面意义。", "arise（出现，爆发意味较弱）"],
  ["tactic", "tactics", "n.", "策略；手段", "回指利用提示培养习惯的营销手法，不泛指所有科学实验。", "method（方法，策略色彩较弱）"],
  ["questionable", "", "adj.", "有问题的；效果可疑的", "修饰beauty creams，作者质疑相关美容产品。", "doubtful（可疑的，搭配范围不同）"],
  ["cream", "creams", "n.", "乳霜", "beauty creams是美容霜，不是奶油食品。", "moisturizer（保湿剂，用途更具体）"],
  ["unhealthy", "", "adj.", "不健康的", "修饰foods，指出营销可能推动有害消费。", "harmful（有害的，范围更宽）"],
  ["food", "foods", "n.", "食品；食物", "foods用复数强调种类；unhealthy foods为不健康食品。", "snack（零食，只是食品中的一类）"],
  ["wash", "washes washed washing", "v.", "洗", "hand washing为洗手活动；with soap说明用肥皂。", "clean（清洁，不限定用水洗）"],
  ["cultivate", "cultivates cultivated cultivating", "v.", "培养", "should be cultivated为情态被动，表示好习惯应得到培养。", "develop（养成，培养的主动引导意味较弱）"],
  ["gradually", "", "adv.", "逐渐地", "修饰changed；选项添加的变化速度不等于原文主张。", "slowly（缓慢地，侧重速度）"],
  ["root", "roots rooted rooting", "v.", "使扎根", "be rooted in history表示根植历史，第31题是未获原文支持的选项。", "base（以……为基础，搭配不同）"],
  ["basically", "", "adv.", "基本上；本质上", "限定private concerns这一判断，不使错误命题自动成立。", "essentially（本质上）"],
  ["concern", "concerns", "n.", "事务；关切之事", "private concerns是私人事务，不是动词涉及。", "matter（事情，较中性）"],
  ["urgent", "", "adj.", "迫切的", "urgent need为迫切需求，原文没有论证日用品短缺。", "pressing（紧迫的）"],
  ["necessity", "necessities", "n.", "必需品", "daily necessities指日用品；复数由y变ies。", "need（需要，未必指实体用品）"],
  ["role", "roles", "n.", "作用", "significant role为重要作用，不是戏剧角色。", "function（功能，更强调用途）"],
  ["good", "better best", "adj.", "好的；有益的", "good habits表有益习惯，不是生活富裕。", "positive（积极的，评价维度需区分）"],
  ["belong", "belongs belonged belonging", "v.", "属于", "belong to后接所属类别，通常不用于被动语态。", "be part of（属于一部分，需调整结构）"],
  ["develop", "develops developed developing", "v.", "形成；养成", "habits are developed是被动，指习惯被培养出来。", "cultivate（培养，更强调主动引导）"],
  ["creation", "creations", "n.", "创造；形成", "behavior creation是行为的建立，不能充当商业推广的同义原因。", "create为动词，保留独立词位。"],
  ["promotion", "promotions", "n.", "商业推广", "commercial promotions概括广告等促销方式，不是职位晋升。", "advertising（广告宣传，只是推广方式之一）"],
  ["author", "authors author's", "n.", "作者", "author's attitude区别于文章引用的企业人物意见。", "writer（写作者）"],
  ["attitude", "attitudes", "n.", "态度；立场", "attitude toward对某事的态度；要根据评价词及结尾判断。", "view（看法，较偏认知内容）"],
  ["advertisement", "advertisements", "n.", "广告", "35题考广告对习惯的影响；advertising侧重宣传活动。", "commercial（商业广告，尤其广播电视广告）"],
  ["indifferent", "", "adj.", "漠不关心的", "态度词，表示不关心，不等于谨慎或客观。", "neutral（中立，不必漠不关心）"],
  ["negative", "", "adj.", "否定的；批评的", "本题概括作者对广告塑造不健康习惯的负面评价。", "critical（批评的，着重指出问题）"],
  ["biased", "", "adj.", "有偏见的", "表示不公正偏向；批评有问题商品并不自动等于偏见。", "partial（偏袒的，需结合语境）"],
] as const;

export const passage2010P3Lexicon: Record<string, Entry> = Object.fromEntries(rows.map(([headword, forms, partOfSpeech, contextualMeaning, use, synonym]) => [headword, { partOfSpeech, contextualMeaning, use, specialForms: [forms ? `${headword}：${forms}` : "本义无需要另记的屈折变化"], examSynonyms: /^[a-z][a-z -]*（.+）$/i.test(synonym) ? [synonym] : [], confusions: /^[a-z][a-z -]*（.+）$/i.test(synonym) ? [] : [synonym] }]));
const related = [
  ["sufficiently", "adv.", "充分地", "副词修饰形容词或动词；enough常后置，而sufficiently通常前置。", "副词无屈折变化"],
  ["skill", "n.", "技能；技巧", "skill in doing指做某事的技能；art of doing常更强调熟练手法。", "skill—skills"],
  ["unthinking", "adj.", "不加思索的", "形容词修饰行为；unthinkingly为副词，二者不是同一屈折词形。", "形容词无单复数"],
  ["enable", "v.", "使能够", "enable somebody to do必须保留to；help somebody do则可省to。", "enable—enabled—enabling"],
  ["gain", "v.", "获得", "gain可接收益、经验等；earn突出通过活动赚取。", "gain—gained—gaining"],
  ["consume", "v.", "消费；消耗；摄入", "consume food较eat正式；consumer是消费者名词，单列原形。", "consume—consumed—consuming"],
  ["surface", "n.", "表面", "台面是surface的一类，surface本身不限于柜台。", "surface—surfaces"],
  ["deliberately", "adv.", "有意地", "deliberately侧重有意为之，carefully还强调仔细安排。", "副词无屈折变化"],
  ["unclean", "adj.", "不洁的", "可形容物体不干净，比dirty更正式。", "形容词无单复数"],
  ["understand", "v.", "理解", "understand重理解结果；figure out强调思索后弄清。", "understand—understood—understood"],
  ["persons", "n.", "个人（复数）", "persons用于正式或逐人计数场合；people为更普通的人们。", "person—persons；一般人群常用people"],
  ["centre", "n.", "中心", "center的英式拼写；专名仍按原卷拼写。", "centre—centres"],
  ["slight", "adj.", "轻微的", "slight强调量小，subtle强调不易察觉或细微差别。", "slight—slighter—slightest"],
  ["goods", "n.", "商品", "商品义通常用复数goods，不与形容词good合并。", "商品义为复数形式"],
  ["filter", "n.", "过滤器", "过滤器通过过滤分离杂质，purifier强调净化功能。", "filter—filters"],
  ["cloth", "n.", "布；布料", "cloth作材料常不可数；一块擦布可数。", "cloth—cloths；区别clothes衣服"],
  ["outcome", "n.", "结果", "outcome着重过程结束后的结果，result范围更广。", "outcome—outcomes"],
  ["occasion", "n.", "场合；一次事件", "on an occasion在某次场合；不直接代替times a day中的times。", "occasion—occasions"],
  ["clever", "adj.", "聪明的；巧妙的", "clever advertising可指巧妙广告，shrewd更强调精明判断。", "clever—cleverer—cleverest"],
  ["package", "v.", "包装", "package a product不限定容器为瓶子，bottle更具体。", "package—packaged—packaging"],
  ["output", "n.", "产出；产量", "可表示生产活动或自然过程产生的东西及数量。", "产出量义常不可数"],
  ["distant", "adj.", "遥远的", "distant springs表示遥远的泉眼；也可形容时间或关系疏远。", "形容词无单复数"],
  ["source", "n.", "来源；源头", "a source of water为水源，不限定为泉。", "source—sources"],
  ["component", "n.", "组成部分", "a component of结构突出整体中的组成单元。", "component—components"],
  ["insert", "v.", "插入", "insert A into B把A放入B，slip in更突出悄然发生。", "insert—inserted—inserting"],
  ["cosmetics", "n.", "化妆品", "通常用复数集合表达，不与make up动词短语混淆。", "化妆品义通常用复数"],
  ["lately", "adv.", "近来", "描述近一段时间的情况，常与完成时连用。", "副词无屈折变化"],
  ["enhance", "v.", "提升；增强", "enhance quality提升质量，improve lives改善生活，不能只看中文相似就替换。", "enhance—enhanced—enhancing"],
  ["harsh", "adj.", "严厉的；苛刻的", "harsh强调严酷，ruthless突出无情或不顾后果。", "harsh—harsher—harshest"],
  ["debate", "n.", "讨论；辩论", "debate可以理性中性，controversy更突出分歧争议。", "debate—debates"],
  ["method", "n.", "方法", "a method of doing表示做事方法，tactic更偏策略手段。", "method—methods"],
  ["doubtful", "adj.", "可疑的；不确定的", "doubtful可说真实性不确定，questionable常质疑质量或正当性。", "形容词无单复数"],
  ["harmful", "adj.", "有害的", "harmful to health表示有害健康，unhealthy可直接限定食品。", "形容词无单复数"],
  ["slowly", "adv.", "缓慢地", "slowly说明速度慢；gradually说明分阶段逐步变化。", "slowly—more slowly—most slowly"],
  ["pressing", "adj.", "紧迫的", "a pressing need为迫切需求；不是pressing按钮的动作义。", "形容词无单复数"],
  ["function", "n.", "功能；作用", "function偏客观用途，role可指论证中发挥的作用。", "function—functions"],
  ["view", "n.", "看法", "a view on something表示对某事的看法；attitude更包括情感评价倾向。", "view—views"],
  ["neutral", "adj.", "中立的", "不偏向双方，不等于indifferent所说的漠不关心。", "形容词无单复数"],
  ["critical", "adj.", "批评的；关键的", "态度题中表示审视并指出问题，不自动等于biased有偏见。", "形容词无单复数"],
  ["partial", "adj.", "偏袒的；部分的", "谈态度可指偏袒；谈范围则是部分的，必须依语境区分。", "形容词无单复数"],
] as const;
for (const [headword, partOfSpeech, contextualMeaning, use, forms] of related) {
  passage2010P3Lexicon[headword] = { partOfSpeech, contextualMeaning, use, specialForms: [forms], examSynonyms: [], confusions: [] };
}
export const passage2010P3LemmaAliases: Record<string, string> = Object.fromEntries(rows.flatMap(([headword, forms]) => forms.split(" ").filter(Boolean).map(form => [form, headword])));
passage2010P3LemmaAliases.people = "people";
export const passage2010P3FamilyAliases: Record<string, string> = { automatic: "automatic", automatically: "automatic", habit: "habit", habitual: "habit", habitually: "habit", consumer: "consume", consumption: "consume", creation: "create", advertising: "advertise", advertisement: "advertise", commercial: "commerce", commercially: "commerce", promotion: "promote", observation: "observe", moisturizer: "moisture", cleanser: "clean", whitener: "white", softener: "soft" };
export const passage2010P3FormPartOfSpeech: Record<string, string> = { wipes: "n.（消毒湿巾）", finding: "v.-ing（寻找）", thinking: "v.-ing（思考）", improving: "v.-ing（改善）", making: "v.-ing（使成为）", buying: "v.-ing（购买）", following: "adj.（下列的）", had: "aux.（过去完成时）", have: "aux.（完成时）", has: "aux.（完成时）", that: "关系代词/从句连接词" };
export const passage2010P3SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2010-p3-s1": { over: { contextualMeaning: "在……期间", use: "Over the past decade为过去十年这一时段。" }, create: { contextualMeaning: "培养；建立", use: "creating automatic behaviors是of的动名词宾语。" } },
  "2010-p3-s2": { response: { contextualMeaning: "反应", use: "in response to daily cues说明消费行为是对提示的反应。" }, think: { contextualMeaning: "思考", use: "without thinking为方式状语，不是‘有思想的’。" } },
  "2010-p3-s3": { like: { contextualMeaning: "例如", use: "引出卫生问题的例子，不是动词喜欢。" }, change: { contextualMeaning: "改变", use: "how to change habits为疑问不定式宾语。" }, that: { contextualMeaning: "引出限定卫生问题的关系", use: "that回指problems并作remain的主语。" } },
  "2010-p3-s5": { find: { contextualMeaning: "寻找", use: "finding cues说明投入资金的用途，不是名词研究结论。" } },
  "2010-p3-s6": { find: { contextualMeaning: "发现", use: "find that后接宾语从句，内容是许多产品源于人为培养的习惯。" }, wipe: { contextualMeaning: "湿巾", use: "disinfecting wipes中的wipes是名词产品名称，不是擦拭动作。" }, use: { contextualMeaning: "使用", use: "we use every day中省略的宾语关系词回指products。" } },
  "2010-p3-s8": { give: { contextualMeaning: "给……做一次", use: "give their pearly whites a scrub为双宾语，整体意为刷牙。" } },
  "2010-p3-s10": { long: { contextualMeaning: "整整；持续地", use: "all day long强化全天持续，不是修饰物体长度。" } },
  "2010-p3-s11": { use: { contextualMeaning: "使用（名词）", use: "for use after a meal中use为介词for的名词宾语。" }, commercial: { contextualMeaning: "商业广告片", use: "in commercials为呈现场合，复数名词。" } },
  "2010-p3-s12": { brush: { contextualMeaning: "梳头", use: "hair brushing与putting on makeup构成between的两个平行项。" }, on: { contextualMeaning: "涂上", use: "put on makeup整体表示化妆，on为动词小品词。" } },
  "2010-p3-s13": { they: { contextualMeaning: "这些产品", use: "回指Our products，产品融入惯例后成功。" } },
  "2010-p3-s14": { it: { contextualMeaning: "培养积极习惯这件事", use: "it's中的it回指Creating positive habits，不是形式主语；to是介词。" }, make: { contextualMeaning: "使……变得", use: "making new products commercially viable用形容词作宾语补足语。" } },
  "2010-p3-s15": { learn: { contextualMeaning: "通过研究了解到", use: "have learned that宾语从句说明广告绑定提示和行为的力量。" }, certain: { contextualMeaning: "某些特定的", use: "限定behaviors，不是确信无疑的。" }, that: { contextualMeaning: "引出所发现的事实", use: "that作宾语从句连接词，不在从句内作主语。" } },
  "2010-p3-s16": { as: { contextualMeaning: "随着", use: "引导时间背景从句，与后面的争议出现相伴。" }, use: { contextualMeaning: "使用；运用", use: "have been used是完成时被动；to sell说明用途，不是used to过去常常。" } },
};
