import type {BeginnerSyntaxComponent,BeginnerClauseDetail,QuestionAnalysis,SentenceAnalysis,SyntaxVisualRole} from "./data";
import {withReviewedSyntax} from "./reviewed-syntax";
const c=(text:string,form:string,fn:string,modifies:string,explanation:string,children?:BeginnerSyntaxComponent[]):BeginnerSyntaxComponent=>({text,form,function:fn,modifies,explanation,children});
const a=(n:number,text:string,trunk:string,meaning:string,focus:string,components:BeginnerSyntaxComponent[],colors:SyntaxVisualRole[],clauses:BeginnerClauseDetail[]=[]):SentenceAnalysis=>withReviewedSyntax({id:`2010${n}-prompt-analysis`,number:0,text,trunk,literal:meaning,natural:meaning,beginnerSyntax:{components,clauses},layers:[{label:"判断命题",text:focus}],grammar:[focus],logic:"先拆出题干的命题和限定，再对照原文；True与False只表示本题判断，不是额外事实。",phrases:[]},colors);
const options=(n:number):QuestionAnalysis["options"]=>Object.fromEntries((["T","F"]as const).map(key=>{const text=key==="T"?"True":"False",meaning=key==="T"?"该陈述与原文相符。":"该陈述不符合原文，或未获原文支持。";return[key,{...withReviewedSyntax({id:`2010${n}-${key}-analysis`,number:0,text,trunk:text,textKind:"phrase",literal:meaning,natural:meaning,layers:[{label:"判断标签",text:meaning}],grammar:["形容词作为真假判断标签，省略所评价的statement，不虚构原卷没有的完整英文句。"],logic:"判断的是题干整项陈述，不凭标签自身推断历史或科学事实。",phrases:[],beginnerSyntax:{components:[c(text,"形容词判断标签","选项核心","题干陈述",meaning)],clauses:[]}},["complement"])}];}));
export const passage2010P5QuestionAnalysis:Record<number,QuestionAnalysis>={
41:{prompt:a(41,"Findings of the Stanford University researchers will promote the sales of new Boeing and Airbus aircraft.","Findings will promote the sales.","斯坦福大学研究者的发现将促进波音和空客新飞机的销售。","Findings是发现成果这一名词复数，will promote明确断言未来促销作用；of短语分别限定成果来源与售卖对象。",[c("Findings of the Stanford University researchers","名词及of限定","主语","will promote","中心Findings，不是researchers作主句主语。",[c("of the Stanford University researchers","介词短语","来源定语","Findings","研究成果属于斯坦福团队。")]),c("will promote","一般将来表达","谓语","Findings","断言将促进。"),c("the sales of new Boeing and Airbus aircraft","名词及of限定","宾语","promote","销售对象是两家制造商的新飞机。",[c("of new Boeing and Airbus aircraft","介词短语","销售对象限定","sales","new修饰两家飞机，不能读成新成立的两家公司。")])],["subject","predicate","object"]),options:options(41)},
42:{prompt:a(42,"The upwash experience may save propelling energy as well as reducing resistance.","The upwash experience may save propelling energy.","对上洗气流的利用既可能节省推进能量，也可能减小阻力。","experience在题干为名词；may保留可能性。as well as后使用reducing动名词性结构，补充另一效果；忠实保留原卷句式。",[c("The upwash experience","名词短语","主语","may save","中心experience为名词，指经历或利用上洗气流。"),c("may save","情态谓语","谓语","experience","可能节省。"),c("propelling energy","动名词定语＋名词","宾语","save","推进所需能量。",[c("propelling","动名词性定语","用途定语","energy","限定推进用途，不是主句谓语。")]),c("as well as reducing resistance","并列补充结构及动名词","补充效果","save propelling energy","除节能外还减阻，reducing不是另一个限定谓语。",[c("reducing resistance","动名词短语","as well as后补充项","另一项效应","resistance作reducing宾语。")])],["subject","predicate","object","modifier"]),options:options(42)},
43:{prompt:a(43,"Formation flight is more comfortable because passengers can not see the other planes.","Formation flight is more comfortable.","编队飞行更舒适，因为乘客看不到其他飞机。","more comfortable作肯定比较，because提出因果，can not给出不能看见的判断；三项承诺都需原文支持。",[c("Formation flight","名词短语","主语","is","编队飞行。"),c("is","系动词","谓语","Formation flight","连接性质判断。"),c("more comfortable","比较级形容词","表语","is","断言更加舒适。"),c("because passengers can not see the other planes","原因从句","原因状语","is more comfortable","把不能看见作为更舒适的原因。",[c("passengers","复数名词","从句主语","can not see","乘客。"),c("can not see","否定情态谓语","从句谓语","passengers","原卷can not分写保留，断言看不见。"),c("the other planes","名词短语","宾语","see","其他飞机。")])],["subject","predicate","complement","modifier"],[{text:"because passengers can not see the other planes",type:"原因状语从句",marker:"because",role:"解释更舒适的原因",subject:"passengers",predicate:"can not see",predicateDetails:[{function:"宾语",text:"the other planes"}],translationOrder:"先译更舒适的判断，再译所声称原因。"}]),options:options(43)},
44:{prompt:a(44,"The role that weather plays in formation flight has not yet been clearly defined.","The role has not yet been clearly defined.","天气在编队飞行中所起的作用尚未被清楚界定。","中心主语role为单数；that作plays宾语，has not yet been defined为现在完成时被动，not yet表示尚未。",[c("The role that weather plays in formation flight","名词及关系从句","主语","has not yet been defined","中心role，关系从句说明哪种作用。",[c("that weather plays in formation flight","关系从句","后置定语","role","that指role并作plays宾语。",[c("weather","不可数名词","从句主语","plays","天气。"),c("plays","一般现在时","从句谓语","weather","play a role表示起作用。"),c("in formation flight","介词短语","作用领域状语","plays","在编队飞行中。")])]),c("has not yet been clearly defined","现在完成时被动及副词","谓语","The role","clear的副词形式clearly修饰defined，尚未被清楚确定。")],["subject","predicate"],[{text:"that weather plays in formation flight",type:"定语从句",marker:"that",role:"修饰role，关系词作宾语",subject:"weather",predicate:"plays",predicateDetails:[{function:"宾语（关系词）",text:"that"},{function:"范围状语",text:"in formation flight"}],translationOrder:"把天气在编队中起的译到作用前，再接尚未确定。"}]),options:options(44)},
45:{prompt:a(45,"It has been documented that during World War Ⅱ, America's armed forces once tried formation flight to save fuel.","It has been documented that America's armed forces once tried formation flight.","已有文献记录证实，二战期间美国军方曾为节省燃油尝试编队飞行。","It为形式主语，that给后置内容；has been documented声称证据已确立，America's、once和to save分别限定主体、过去尝试和目的。",[c("It","形式代词","形式主语","has been documented","不指某架飞机，真正主语是后面的that内容。"),c("has been documented","现在完成时被动","谓语","It所占的主语位置","已得到文献记录或证明。"),c("that during World War Ⅱ, America's armed forces once tried formation flight to save fuel","that内容从句","后置真正主语","It","题干所声称已确证的完整事实。",[c("during World War Ⅱ","介词短语","时间状语","tried","二战期间；原卷罗马数字Ⅱ保留。"),c("America's armed forces","名词短语","从句主语","tried","具体指定美国军方。"),c("once","副词","时间状语","tried","曾经，不必解释为准确一次。"),c("tried","一般过去时","从句谓语","armed forces","尝试。"),c("formation flight","名词短语","宾语","tried","所尝试的飞行方式。"),c("to save fuel","不定式","目的状语","tried formation flight","题干明确提出节油目的。")])],["subject","predicate","subject"],[{text:"that during World War Ⅱ, America's armed forces once tried formation flight to save fuel",type:"后置主语从句",marker:"that",role:"真正主语，It形式占位",subject:"America's armed forces",predicate:"tried",predicateDetails:[{function:"宾语",text:"formation flight"},{function:"目的状语",text:"to save fuel"},{function:"时间状语",text:"during World War Ⅱ"}],translationOrder:"先处理已获记载的证据声明，再读所称主体、战争时间与目的。"}]),options:options(45)},
};
