import type {SentenceWordContext} from "./contextual-vocabulary";
import type {WordKnowledge} from "./knowledge-base";
type Seed=SentenceWordContext&{knowledge:WordKnowledge};
const w=(partOfSpeech:string,contextualMeaning:string,use:string,pattern:string,meaning:string):Seed=>({partOfSpeech,contextualMeaning,use,knowledge:{grammarRole:partOfSpeech,grammarSummary:use,structures:[{pattern,meaning,rule:use}]}});
const sources:Record<string,Record<string,Seed>>={
"2010-p5-s1":{
and:w("conj.","和","分别连接两个厂商及两个机型，respectively按顺序配对。","Both Boeing and Airbus; the 787 and A350","波音与空客；787与A350"),have:w("aux.","标记现在完成时","have trumpeted与复数主语both A and B一致。","have trumpeted the efficiency","已大力宣扬效率"),efficiency:w("n.","效率","efficiency作trumpeted宾语，of说明所属飞机。","the efficiency of their newest aircraft","各自最新飞机的效率"),of:w("prep.","的","of aircraft说明效率属于哪些飞机。","the efficiency of their newest aircraft","各自最新飞机的效率"),they:w("possessive det.（their）","它们的","their指波音和空客，分别拥有后列的最新机型。","their newest aircraft","两家公司各自的最新飞机")},
"2010-p5-s2":{
they:w("possessive det.（Their）","它们的","Their指上句最新飞机的设计和材料。","Their clever designs and lightweight composites","这些飞机的巧妙设计和轻质材料"),and:w("conj.","和","连接designs与composites两项有效因素。","designs and composites","设计和复合材料"),make:w("v.","产生（搭配中）","make与a difference整体表示起作用，主语为设计与材料。","make a difference","起作用；产生影响")},
"2010-p5-s3":{
of:w("prep.","由……组成","of researchers说明group的成员。","a group of researchers","一组研究者"),lead:w("v.（过去分词）","带领","led by作团队的补充定语，团队为被带领者。","a group led by Ilan Kroo","由克鲁带领的团队"),by:w("prep.","由","by引出led的施事Ilan Kroo。","led by Ilan Kroo","由伊兰·克鲁带领"),have:w("aux.","标记现在完成时","has suggested由单数group决定has，描述已提出设想。","a group has suggested","一组人已提出"),that:w("conj.","引出建议内容","that统领两个并列命题，不充当内部主语或宾语。","suggested that airlines could ... and it would ...","提出航空公司可以……而该方法将……"),more:w("adv.","更","more修饰naturalistic形成单一比较级形容词，不是双分句越越结构。","a more naturalistic approach","一种更仿自然的方法"),to:w("prep. / 不定式标记","引方法内容或行为","approach to cutting中为介词，require them to buy中为不定式标记。","approach to doing; require somebody to do","做事的方法；要求某人做事"),cut:w("v.-ing（动名词）","降低","cutting作approach to的介词宾语，接jet-fuel use。","an approach to cutting jet-fuel use","降低航空燃油消耗的方法"),and:w("conj.","并且","连接that内部airlines could take和it would not require两个命题。","airlines could take ... and it would not require ...","航空公司可以采用……且它不要求……"),it:w("pron.","该方法","it回指a more naturalistic approach，是require主语。","it would not require them to buy new aircraft","这种方法不要求它们购买新飞机"),they:w("pron.（宾格them）","航空公司","them回指airlines，是require宾语及buy执行者。","require them to buy new aircraft","要求航空公司购买新飞机")},
"2010-p5-s4":{with:w("prep.","在……一方","lie with说明答案要从鸟类寻找。","the answer lies with birds","答案在鸟类身上"),lie:w("v.","在于","lies与with组成所在关系，主语是The answer。","the answer lies with birds","答案在鸟类身上")},
"2010-p5-s5":{
since:w("prep.","自……以来","Since接时间点1914，与have known的完成时配合。","Since 1914, scientists have known","自1914年以来科学家已知"),have:w("aux.","标记现在完成时","have known描述自1914以来已拥有的认识。","have known that birds expend less energy","已经知道鸟类耗能更少"),that:w("conj.","引出已知内容","that引known宾语从句，鸟类为内部主语。","known that birds expend less energy","知道鸟类耗能更少"),fly:w("v.-ing（分词）","飞行","flying后置修饰birds，主句从句内谓语是expend。","birds flying in formation","编队飞行的鸟类"),less:w("det.（比较限定词）","更少的","less修饰不可数energy，保留比较而非零能量。","expend less energy","耗费更少能量")},
"2010-p5-s6":{
flow:w("v.-ing（分词）","流过","flowing修饰air，说明经过鸟翼上方的空气。","air flowing over a bird's wings","流经鸟翼上方的空气"),know:w("v.（过去分词）","称作（搭配中）","known as作phenomenon的分词定语，说明名称。","a phenomenon known as upwash","称为上洗气流的现象"),as:w("prep.","称作","as在known as中引现象名称。","known as upwash","被称为上洗气流")},
"2010-p5-s7":{
fly:w("v.-ing（分词）","飞行","flying in the upwash为birds的后置定语。","birds flying in the upwash","在上洗气流中飞行的鸟"),experience:w("v.","经受；承受","experience为限定谓语，接reduced drag宾语。","experience reduced drag","承受较低阻力"),reduce:w("v.（过去分词定语）","降低","reduced修饰drag，阻力是被降低者。","reduced drag","较低的空气阻力"),and:w("conj.","并且","连接同一主语的experience与spend两个谓语。","experience reduced drag, and spend less energy","承受较低阻力并耗能更少"),themselves:w("reflexive pron.","鸟类自己","作propelling宾语，执行者同样为Other birds。","propelling themselves","推进鸟类自身")},
"2010-p5-s8":{
who:w("关系代词","这位专家","who回指expert，并在关系从句中作was主语。","an expert who was formerly at Caltech","曾在加州理工任职的专家"),be:w("linking v.（was）","曾在","was接at机构的介词短语，交代过去任职背景。","was formerly at Caltech","以前在加州理工学院任职"),at:w("prep.","在","at后并列两所学校，说明专家先前任职处。","at Caltech and the University of Southern California","在加州理工和南加州大学"),and:w("conj.","和","连接两所任职机构，共享at。","Caltech and the University of Southern California","加州理工学院和南加州大学"),of:w("prep.","所属；数量；增幅","of分别组成校名、25只鸟的编队和71%的增幅，须随中心名词理解。","a formation of 25 birds; an increase of 71%","25只鸟的编队；71%的增幅"),have:w("aux.","标记现在完成时","has suggested以专家Peter Lissaman为主语。","has suggested that ...","已经提出……"),that:w("conj.","引出估计内容","that引suggested的宾语从句。","suggested that a formation might enjoy ...","提出编队可能获得……"),enjoy:w("v.","获得","enjoy接a range increase，指得到航程增益。","enjoy a range increase","获得航程增幅"),increase:w("n.","增幅","increase前有a，是enjoy的名词宾语核心；of接增幅。","a range increase of 71%","航程增加71%")},
"2010-p5-s9":{
when:w("conj.","当……时","When引省略状语从句，被应用的是the principles，are一并省略。","When applied to aircraft","当这些原理被用于飞机时"),apply:w("v.（过去分词）","应用","applied承受者为主句principles，to引应用对象。","principles applied to aircraft","应用于飞机的原理"),to:w("prep.","用于的对象","to aircraft引出原理应用对象，不是不定式。","apply principles to aircraft","把原理用于飞机"),be:w("linking v.","是","are接not substantially different表语。","are not substantially different","并无实质区别")},
"2010-p5-s10":{
and:w("conj.","和；并且","首处连接研究者与团队；城市列表和末处proceed各在自己的并列层。","assemble, assume, change, and proceed","会合、列队、换位并前往"),he:w("possessive det.（his）","他的","his指Dr. Kroo，限定team。","Dr. Kroo and his team","克鲁及其团队"),what:w("疑问代词","会发生的情况","what引modeled宾语从句，并作would happen主语。","modeled what would happen","模拟将会发生什么"),if:w("conj.","假如","if为模型给假定条件，四项并列动作均在其范围内。","what would happen if jets were to ...","假如飞机……会发生什么"),depart:w("v.-ing（分词）","出发","departing后置修饰three passenger jets，from引三个出发城市。","jets departing from three cities","从三个城市出发的客机"),be:w("v.（were to假设结构）","假定要","were to统领assemble、assume、change、proceed，表示模拟安排。","were to assemble, assume, change, and proceed","假定会合、列队、换位及前往"),to:w("不定式标记 / prep.","引假定动作；到","were to中引并列原形动作，proceed to London中的to引目的地。","were to assemble; proceed to London","假定会合；前往伦敦"),assume:w("v.","呈现；组成","assume接队形，不取假定命题的含义。","assume an inverted V-formation","组成倒V字队形"),invert:w("v.（过去分词定语）","使倒置","inverted修饰V-formation，说明队形为倒V形。","an inverted V-formation","倒V字队形"),so:w("conj.","以便","so引换位的目的从句，相当于so that。","change places so all could have a turn","换位以便每架都有一次机会"),all:w("pron.","全部三架飞机","all独立作could have主语，回指three passenger jets。","all could have a turn","每架都可以轮到"),have:w("v.","获得","have a turn指取得一次轮到的机会，不是完成时。","have a turn in the most favourable positions","轮流处于最有利位置"),turn:w("n.","轮到的机会","a turn为have的宾语，指轮换中的一次机会。","have a turn","轮到一次")},
"2010-p5-s11":{
they:w("pron.","克鲁及团队","They承接模拟实施者，是found主语。","They found that ...","团队发现……"),that:w("conj.","引出发现内容","宾语从句含括号中的伴随排放变化。","found that the aircraft consumed ...","发现飞机消耗……"),as:w("adv.（比较结构成分）","多达（搭配中）","as much as在15%前突出降幅，不能当成因果连词。","as much as 15% less fuel","少耗最多15%的燃油"),much:w("adv.（程度结构成分）","多（搭配中）","as much as整体强调数量达到的程度。","as much as 15% less fuel","少耗多达15%的燃油"),less:w("det.（比较限定词）","更少的","15% less fuel指比基准少15%，不是剩余15%。","15% less fuel","少15%的燃油"),couple:w("v.（过去分词）","伴随；相结合","coupled with在括号内补充燃油减少伴随的排放下降。","coupled with a reduction","同时伴随下降"),with:w("prep.","与……相伴","with补足coupled，后接名词reduction。","coupled with a reduction in output","伴随排放量下降"),in:w("prep.","在……方面","in carbon-dioxide output说明reduction所涉及的指标。","a reduction in carbon-dioxide output","二氧化碳排放量减少")},
"2010-p5-s12":{
of:w("prep.","属于","of the flight限定cruising portions属于飞行的哪段过程。","the cruising portions of the flight","飞行中的巡航阶段"),by:w("prep.","变化幅度为","fell by引下降幅度，不是终值或施事。","fell by around a quarter","下降约四分之一"),around:w("adv.","大约","around修饰a quarter，是数量近似而非周围。","around a quarter","约四分之一")},
"2010-p5-s13":{
there:w("存在句引导词","引出存在事物","There are后实义主语是knots，不指地点。","There are knots to be worked out","有难题待解决"),be:w("v. / aux.","存在；构成被动","are与there引难题存在；to be worked out中的be构成被动。","There are knots to be worked out","有些难题待解决"),of:w("prep.（固定搭配）","构成评注短语","of与course组成of course，整体意为当然。","of course","当然"),to:w("不定式标记","引待解决的动作","to be worked out为被动不定式定语，修饰knots。","knots to be worked out","有待解决的难题"),work:w("v.（过去分词）","解决（搭配中）","worked与out组成解决，to be表示被动不定式。","to be worked out","有待解决")},
"2010-p5-s14":{
be:w("linking v.","是","is连接One consideration与safety及其修正表语。","One consideration is safety","一个考量是安全"),of:w("prep.","感知的对象","of it补足perception，it指safety。","the perception of it","对安全性的感受"),it:w("pron.","安全性","it回指safety，并非形式主语。","the perception of it","对安全的感受")},
"2010-p5-s15":{
will:w("modal v.（Would）","是否会","Would置于主语前构成假设疑问，未给肯定比较结论。","Would passengers feel comfortable?","乘客会感到安心吗"),travel:w("v.-ing（分词）","出行","travelling的逻辑主语为passengers，说明感受的情境。","passengers travelling in company","结伴飞行的乘客"),in:w("prep.","以……方式","in company作为travelling的结伴方式。","travelling in company","结伴出行"),company:w("n.","结伴；同伴","in company为与其他飞机同行，不是商业公司。","travel in company","结伴出行")},
"2010-p5-s16":{
that:w("conj.","引出指出的内容","that从句含两个共享aircraft主语的谓语。","points out that aircraft could ... and would ...","指出飞机可以……并将……"),be:w("aux. / linking v.","构成被动；处于","be separated为被动，be in groupings为系表状态。","could be separated; would not be in groupings","可以相隔；不会处于队形中"),by:w("prep.","相隔；由","第一处by引相隔海里数，第二处by引偏爱队形的表演队。","separated by miles; favoured by teams","相隔若干海里；受表演队青睐"),and:w("conj.","并且","连接could be separated与would not be，主语均为aircraft。","could be separated ... and would not be ...","可以相隔……并且不会处于……"),favour:w("v.（过去分词）","偏爱","favoured后置修饰groupings，被青睐者为队形。","groupings favoured by display teams","受表演队青睐的队形"),like:w("prep.","例如","like举Red Arrows为display teams的例子。","display teams like the Red Arrows","红箭这样的表演队")},
"2010-p5-s17":{
peer:w("v.-ing（分词）","张望","peering后置修饰passenger，out of the window说明向外看的方向。","a passenger peering out of the window","向窗外张望的乘客"),of:w("prep.（复合介词组成）","从……里面向外","out of整体引window这一向外观察的位置。","peering out of the window","向窗外张望"),may:w("modal v.（might）","可能","might not even see只表示可能看不到，未断言不能看见。","might not even see the other planes","可能甚至看不到其他飞机"),see:w("v.","看见","see接the other planes为视觉感知对象。","see the other planes","看见其他飞机")},
"2010-p5-s18":{
whether:w("conj.","是否","Whether引主语从句，整个合规问题作is主语。","Whether distances would satisfy regulations","间距是否满足规定"),involve:w("v.（过去分词定语）","涉及","involved后置修饰distances，不是从句谓语。","the separation distances involved","涉及的间隔距离"),satisfy:w("v.","符合；满足","satisfy接regulations，说明是否达到空管要求。","satisfy air-traffic-control regulations","符合空管规定"),be:w("linking v.","是","is以whether从句为主语，以another matter为表语。","Whether ... is another matter","是否……是另一问题"),although:w("conj.","尽管","让步承认已列蓝图，但主句合规问题仍未解决。","although a group has included the possibility","尽管工作组已纳入这一可能性"),work:w("v.-ing（定语）","工作的","working修饰group，组成工作组名称，非work out结构。","a working group","一个工作组"),have:w("aux.","标记现在完成时","has included的主语为单数working group。","has included the possibility","已纳入这种可能性"),include:w("v.（过去分词）","纳入","included与has为完成时，宾语为possibility，in为纳入蓝图。","include the possibility in a blueprint","将可能性纳入蓝图"),of:w("prep.","说明可能的事项","of formation flying说明possibility所指活动。","the possibility of formation flying","编队飞行的可能性"),fly:w("v.-ing（动名词）","飞行","formation flying作of宾语，指编队飞行这一活动。","the possibility of formation flying","编队飞行的可能性"),for:w("prep.","用于","for new operational guidelines限定blueprint的用途。","a blueprint for new operational guidelines","新操作准则的蓝图"),operational:w("adj.","操作的；运行的","operational修饰guidelines，限定航空运行准则。","new operational guidelines","新的操作准则")},
"2010-p5-s19":{
it:w("形式代词","形式主语","It占位，how从句才是有待确定的完整问题。","It remains to be seen how ...","怎样……仍有待确定"),to:w("不定式标记","引尚待确定的动作","to be seen为被动不定式，置于remains后。","remain to be seen","仍有待确定"),be:w("aux.","构成被动","be seen为被动，待弄清的内容在how从句。","to be seen how weather affects air flows","天气如何影响气流有待确定"),see:w("v.（过去分词）","弄清；确定","seen在remains to be seen中为弄清，不是乘客视觉观察。","remains to be seen","仍有待确定"),how:w("疑问副词","如何","how引后置主语从句，内部作affect的方式状语。","how weather conditions affect air flows","天气条件如何影响气流"),flow:w("n.（复数）","气流","flows为affect宾语核心，也是that的先行词。","the air flows that make formation flight more efficient","使编队更高效的气流"),that:w("关系代词","这些气流","that回指air flows并作make主语。","air flows that make formation flight more efficient","使编队飞行更高效的气流"),make:w("v.","使","make接formation flight宾语和more efficient宾补。","make formation flight more efficient","使编队飞行更高效"),more:w("adv.","更","more修饰efficient，表示效率更高。","more efficient","更高效的")},
"2010-p5-s20":{
of:w("prep.","具有","of increased turbulence后置限定zones的气流特征。","zones of increased turbulence","湍流增强的区域"),increase:w("v.（过去分词定语）","增强","increased在turbulence前作定语，不是increase名词增幅。","increased turbulence","增强的湍流"),wake:w("n.（复数）","尾流","planes' wakes为飞机身后留下的气流，作decay主语。","the planes' wakes","飞机尾流"),more:w("adv.","更","more修饰quickly，比较衰减速度。","decay more quickly","更快衰减"),and:w("conj.","并且","连接尾流衰减与效益减弱两个主谓分句。","wakes will decay ... and the effect will diminish","尾流将衰减且效果将减弱"),diminish:w("v.","减弱","diminish以the effect为主语，表示节能效益降低。","the effect will diminish","效果将减弱")},
"2010-p5-s21":{
this:w("pron.","这一问题","this承接天气及湍流如何影响气流和节能的研究领域。","this is one of the areas","这是相关领域之一"),be:w("linking v.","是","is连接this与one of the areas表语。","this is one of the areas","这是领域之一"),of:w("prep.","范围中的","one of从后面的复数areas中选取一个领域。","one of the areas","相关领域之一"),he:w("possessive det.（his）","他的","his指Dr. Kroo，限定继续研究的团队。","his team will investigate further","他的团队将进一步研究"),further:w("adv.","进一步","further在句尾修饰investigate研究的推进程度。","will investigate further","将进一步研究")},
"2010-p5-s22":{
it:w("形式代词","形式主语","It占位，to co-ordinate整体为真正主语。","It might be hard for airlines to co-ordinate ...","航空公司协调……可能困难"),be:w("linking v.","是","be连接形式主语位置和hard表语。","might also be hard","也可能是困难的"),for:w("prep.（逻辑主语结构）","对于；由","for airlines给出不定式co-ordinate的行动者。","for airlines to co-ordinate","由航空公司协调"),to:w("不定式标记","引出动作","to co-ordinate为真正主语，to gain为allow them后的宾补。","to co-ordinate; allow them to gain","协调；使其能够获益"),and:w("conj.","和","连接departure times与destinations两个协调对象。","the departure times and destinations","出发时刻和目的地"),of:w("prep.","所属","of passenger aircraft共同限定times与destinations。","the departure times and destinations of passenger aircraft","客机的出发时间和目的地"),that:w("关系代词","这种方式","that回指a way并作would allow主语。","a way that would allow them to gain","能使它们获益的方式"),they:w("pron.（them）","航空公司","them回指airlines，是allow宾语及gain执行者。","allow them to gain from formation flight","使航空公司从编队飞行获益")},
"2010-p5-s23":{
be:w("linking v.","是","be连接Cargo aircraft与easier表语，as分句省去重复部分。","might be easier to reschedule","可能更容易重新调度"),easy:w("adj.（比较级）","更容易的","easier作表语，to reschedule说明在哪方面容易；cargo aircraft是其逻辑宾语。","aircraft might be easier to reschedule","飞机可能更容易被重新调度"),to:w("不定式标记","引出容易完成的活动","to reschedule主动形式含被动意义，货机是被调度对象。","easy to reschedule","容易重新调度"),as:w("conj.","也如此","as引类比补充，might前置，省略be easier to reschedule。","as might routine military flights","例行军用航班也可能如此")},
"2010-p5-s24":{
as:w("conj.","恰好（搭配中）","As it happens是引入事实的评注从句。","As it happens","恰好；碰巧"),it:w("pron.（评注结构）","无具体实体指代","it在As it happens固定评注中，不回指某架飞机。","As it happens","恰好"),be:w("linking v.","处于某状态","are后on the case说明军方已着手研究此事。","are on the case already","已经着手处理此事"),case:w("n.","待研究的事情","on the case为正在处理编队研究这件事。","on the case","着手处理或研究此事")},
"2010-p5-s25":{
early:w("adv.（比较级）","较早地","Earlier this year指文章当年的较早时候。","Earlier this year","当年较早时"),country:w("n.（所有格）","国家","country's指美国，限定后面的国防研究机构。","the country's Defence Advanced Research Projects Agency","美国国防高级研究计划局"),research:w("n.作定语","研究","Research修饰Projects，是机构名称的组成部分。","Research Projects Agency","研究计划机构"),to:w("不定式标记","引计划内容及研究任务","to pay修饰plans，to investigate说明付费给波音后由其执行的任务，to begin接has yet。","plans to pay Boeing to investigate","付费请波音研究的计划"),though:w("conj.","不过；尽管","though说明计划已宣布，但项目尚未启动。","though the programme has yet to begin","不过项目尚未开始"),have:w("v.（have yet to结构）","尚待（搭配中）","has yet to begin表示尚未开始，不是has begun完成时。","has yet to begin","尚未开始"),yet:w("adv.","尚；还","has yet to整体表尚待，未显式not但整体否定已开始。","has yet to begin","尚未开始")},
"2010-p5-s26":{
there:w("存在句引导词","引出存在事物","There are引出报道存在，不担保报道真实。","There are reports that ...","有报道称……"),be:w("v. / linking v.","存在；处于","are reports为存在句，were low和are unsubstantiated为两处系表结构。","There are reports; they were low; they are unsubstantiated","有报道；军机缺油；报道未证实"),that:w("conj.","引出报道内容","that解释reports的同位内容，内部再有when从句。","reports that aircraft flew in formation","飞机曾编队飞行的报道"),they:w("pron.","军机；这些报道","when内they指军机；says后they指reports，指代随语义层变化。","they were low on fuel; they are unsubstantiated","军机燃油不足；报道未经证实"),on:w("prep.","所缺少的物资","low on fuel中的on引不足的燃油。","low on fuel","燃油不足"),unsubstantiated:w("adj.","未经证实的","作are的表语，说明reports缺乏证据，不判定飞机是否存在。","reports are unsubstantiated","报道未经证实")},
"2010-p5-s27":{
be:w("linking v.（was）","曾是","was接an RAF pilot；and后第二分句省略同样的was。","My father was an RAF pilot","我的父亲曾是皇家空军飞行员"),and:w("conj.","而；并且","连接两个亲属身份分句，第二分句省略was。","my father was ... and my cousin ...","父亲是……而一位亲属是……"),of:w("prep.","所属飞机","of说明skipper是哪架飞机的机长。","the skipper of a Lancaster","一架兰开斯特飞机的机长"),lose:w("v.（过去分词）","损失","lost over Berlin后置修饰Lancaster，不补造机长的最终命运。","a Lancaster lost over Berlin","在柏林上空损失的兰开斯特飞机"),he:w("pron.","利萨曼博士","he是adds主语，引语中My为同一说话者自己的。","he adds","利萨曼补充说")},
"2010-p5-s28":{
so:w("连接副词","因此","So由专家家庭背景引出合理推断，非目的从句。","So he should know","所以他按理应当了解"),he:w("pron.","利萨曼博士","he承接发表二战报道判断及补充家庭背景的专家。","he should know","他按理应当了解"),should:w("modal v.","按理应当","should由背景作合理推断，不是要求专家履行任务。","should know","按理应当知道")},
};
const q=(n:number,k:string,words:Record<string,Seed>)=>{sources[`question-2010${n}-${k==="prompt"?"prompt":`option-${k}`}`]=words;};
q(41,"prompt",{of:w("prep.","所属；销售对象","第一处of说明成果来源，第二处of说明销售的新飞机。","findings of researchers; sales of aircraft","研究者的发现；飞机销量"),finding:w("n.（复数）","研究发现","Findings为主语，不是find的动名词。","Findings will promote the sales","研究发现将促进销售"),and:w("conj.","和","连接Boeing和Airbus两个厂商限定，共同修饰aircraft。","Boeing and Airbus aircraft","波音和空客飞机")});
q(42,"prompt",{experience:w("n.","体验；利用","experience是主语中心，指经历或利用上洗气流，区别正文experience谓语。","The upwash experience may save energy","对上洗气流的利用可能节能"),as:w("复合连接结构成分","以及（搭配中）","两处as与well组成as well as，连接补充效果。","as well as reducing resistance","也能降低阻力"),well:w("adv.（搭配成分）","也（搭配中）","as well as整体表示除前项外还有后项，不独立修饰健康。","as well as reducing resistance","也降低阻力"),reduce:w("v.-ing（动名词）","降低","reducing在as well as之后接resistance宾语，原卷ing形式保留。","reducing resistance","降低阻力"),propel:w("v.-ing（用途定语）","推进","propelling修饰energy，说明能量用于推进。","propelling energy","推进能量")});
q(43,"prompt",{be:w("linking v.","是","is连接Formation flight与比较级表语。","is more comfortable","更加舒适"),more:w("adv.","更","more修饰comfortable，题干提出肯定比较。","more comfortable","更舒适的"),because:w("conj.","因为","because引完整原因从句，不能当because of后接名词。","because passengers can not see the other planes","因为乘客看不到其他飞机"),see:w("v.","看见","see接其他飞机，表示视觉感知。","can not see the other planes","看不到其他飞机")});
q(44,"prompt",{that:w("关系代词","所起的作用","that回指role，在weather plays后承担宾语，weather是主语。","the role that weather plays","天气所起的作用"),have:w("aux.","标记现在完成时","has与been defined构成完成时被动，not yet表示尚未。","has not yet been clearly defined","尚未被清楚界定"),be:w("aux.（过去分词been）","构成被动","been与has及defined组成现在完成时被动。","has been defined","已被界定"),yet:w("adv.","尚；还","not yet共同表达截至当时尚未完成。","not yet been clearly defined","尚未清楚界定")});
q(45,"prompt",{it:w("形式代词","形式主语","It占位，that内容为题干声称已记录的真正主语。","It has been documented that ...","已有文献记录……"),have:w("aux.","标记现在完成时","has been documented声称当前已有记录或证据。","has been documented","已有记录证实"),be:w("aux.（过去分词been）","构成被动","been与has、documented构成完成时被动。","has been documented","已被记录"),that:w("conj.","引出已记录内容","that引后置真正主语从句，不在内部作成分。","documented that forces tried formation flight","记录军方曾尝试编队飞行"),to:w("不定式标记","为了","to save fuel作tried formation flight的目的状语。","tried formation flight to save fuel","为节油尝试编队飞行")});
// 十个原卷真假标签逐来源绑定，未改为四选一或添加虚构选项。
for(const n of [41,42,43,44,45]){q(n,"T",{true:w("adj.（判断标签）","符合原文的","True用于判断本题陈述符合原文，并非单独肯定某一词义。","True","该陈述符合原文")});q(n,"F",{false:w("adj.（判断标签）","不符合原文的","False用于判断本题陈述不符合或未获原文支持，不强制推出命题的相反极端。","False","该陈述不符合原文")});}
export const passage2010P5ReviewedContexts:Record<string,Record<string,SentenceWordContext>>=Object.fromEntries(Object.entries(sources).map(([source,words])=>[source,Object.fromEntries(Object.entries(words).map(([head,entry])=>[head,{partOfSpeech:entry.partOfSpeech,contextualMeaning:entry.contextualMeaning,use:entry.use}]))]));
export function getPassage2010P5WordKnowledge(head:string,sourceId?:string):WordKnowledge|undefined{return sourceId?sources[sourceId]?.[head]?.knowledge:undefined;}
