import type { PracticeTask, GrammarConceptId, ErrorCategory } from "./learning-model";
const choice=(id:string,prompt:string,options:string[],answer:string,evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[]=[],mapRevealsAnswer=false):PracticeTask=>({id,revision:1,kind:"choice",prompt,options,answer,evidence,feedback,conceptId,errorType,hintWords,mapRevealsAnswer});
const range=(id:string,prompt:string,answer:string,feedback:string,conceptId:GrammarConceptId,hintWords:string[]=[]):PracticeTask=>({id,revision:1,kind:"range",prompt,options:[],answer,evidence:answer,feedback,conceptId,errorType:"clause-boundary",hintWords,mapRevealsAnswer:false});
const link=(id:string,prompt:string,links:[string,string][],evidence:string,feedback:string,conceptId:GrammarConceptId,hintWords:string[]=[],mapRevealsAnswer=false):PracticeTask=>({id,revision:1,kind:"link",prompt,links:links.map(([source,target])=>({source,target})),options:[...new Set(links.map(([,target])=>target))],answer:JSON.stringify(links.map(([,target])=>target)),evidence,feedback,conceptId,errorType:"attachment",hintWords,mapRevealsAnswer});
export const passage2010P5Practice:Record<number,PracticeTask[]>={
1:[link("respective-models","按respectively把厂商与机型配对。",[["Boeing","787"],["Airbus","A350"]],"Both Boeing and Airbus have trumpeted the efficiency of their newest aircraft, the 787 and A350 respectively","respectively依照前后相同次序对应，两个机型不随意交换。","parallel-structure",["respectively","Boeing","Airbus"])],
2:[choice("concession-before-but","certainly make a difference在论证中做什么？",["承认新机设计和材料确实有效","断言所有新机毫无作用","证明编队方法已完全商业化"],"承认新机设计和材料确实有效","certainly make a difference","先承认设计材料有用，后句But再提出另一条节能路径。","paragraph-role","passage-logic",["certainly","difference"],true)],
3:[range("suggested-content","选出has suggested的完整that宾语从句，保留并列的第二个判断。","that airlines could take a more naturalistic approach to cutting jet-fuel use and it would not require them to buy new aircraft","that统领airlines could take与it would not require，两项都属于团队提出的方案内容。","clause-object",["that","and","require"]),link("approach-airline-roles","把方法、航空公司与购买动作接准确。",[["it","新提出的仿自然方法"],["them","航空公司"],["to cutting jet-fuel use","补足approach的介词动名词结构"],["to buy new aircraft","补足them的购买行为"]],"a more naturalistic approach to cutting jet-fuel use and it would not require them to buy new aircraft","it指方法，them指航空公司；to cutting中to为介词，to buy是原形不定式。无需购买不能改成促进销量。","reference-pronoun",["it","them","cutting","buy"],true)],
4:[link("report-interruption","越过插入语，把两个动词接回各自主语。",[["lies","The answer"],["says","Dr. Kroo"]],"The answer, says Dr. Kroo, lies with birds","主句为The answer lies with birds，says Dr. Kroo插入标注信息来源。","subject-head",["says","lies"])],
5:[link("finite-and-modifier","区分that从句的动作、修饰和队形说明。",[["expend","birds的限定谓语"],["flying in formation","修饰birds的分词短语"],["a V-shape","解释formation的同位说明"]],"birds flying in formation – a V-shape – expend less energy","破折号中的V形说明不切断birds与expend，flying不另立限定谓语。","nonfinite-participle",["flying","expend","V-shape"])],
6:[link("air-flow-description","两处分词分别修饰什么？",[["flowing over a bird's wings","The air"],["known as upwash","a phenomenon"]],"The air flowing over a bird's wings curls upwards behind the wingtips, a phenomenon known as upwash","flowing说明空气的流动，known说明现象被如何称呼；主句谓语为curls。","nonfinite-participle",["flowing","known","curls"])],
7:[link("two-effects","把两个动词与实际对象连接。",[["experience","reduced drag"],["spend","less energy"],["propelling","themselves"]],"experience reduced drag, and spend less energy propelling themselves","experience是动词，drag是阻力；鸟类减少耗能来推进自身，themselves指Other birds。","parallel-structure",["experience","drag","spend","themselves"],true)],
8:[range("expert-who","选出说明专家先前任职背景的完整who从句。","who was formerly at Caltech and the University of Southern California","who修饰expert；两所学校都在was后的at范围内，has suggested才是主句谓语。","clause-relative",["who","formerly"]),choice("range-percent","might enjoy a range increase of 71%保留了哪些限制？",["25只鸟的编队可能增加71%的航程","三架飞机必定节省71%的燃油","航程仅为原来的71%"],"25只鸟的编队可能增加71%的航程","a formation of 25 birds might enjoy a range increase of 71%","range为航程，increase of给增幅，might为可能；不能换成后来飞机模型的燃油指标。","comparison-scope","translation",["range","increase","might"],true)],
9:[link("when-omission","把省略结构中的对象关系接清楚。",[["applied的承受对象","the principles"],["to aircraft","原理的应用对象"],["not substantially different","主句对原理作性质判断"]],"When applied to aircraft, the principles are not substantially different","when中省略与主句相同的the principles及are；飞机是to后的应用对象。","passive-voice",["applied","principles","different"])],
10:[range("purpose-so","选出解释换位目的的完整so从句。","so all could have a turn in the most favourable positions","so相当于so that，到positions完成轮流占有利位置的目的；and proceed返回if内四个并列动作。","clause-purpose",["so","all","turn"]),link("nested-levels","将三层动作及连接接回去。",[["what would happen","modeled的宾语内容"],["were to assemble / assume / change / proceed","if假设条件中的四个并列动作"],["departing from Los Angeles, San Francisco and Las Vegas","修饰three passenger jets"],["so all could have a turn","说明change places的目的"]],"modeled what would happen if three passenger jets","what问结果，if给模型假定；四个原形动词共享were to，不把伦敦航段当成已实施事实。","clause-condition",["what","if","departing","proceed"])],
11:[choice("less-fuel","as much as 15% less fuel应如何理解？",["燃油消耗较基准减少最多15%","燃油消耗只剩基准的15%","所有客机已稳定减少15%燃油"],"燃油消耗较基准减少最多15%","as much as 15% less fuel","less表示比基准少，15%给降幅，as much as突出幅度；found来自模拟。","comparison-scope","translation",["less","much"],true),link("found-result-parts","把发现内容的主干与括号中的伴随结果连接。",[["the aircraft","consumed的主语"],["as much as 15% less fuel","consumed的宾语，表示少耗最多15%"],["coupled with a reduction in carbon-dioxide output","燃油减少伴随的排放下降"]],"that the aircraft consumed as much as 15% less fuel (coupled with a reduction in carbon-dioxide output)","括号内容仍属于found的发现内容；宾语15% less fuel表示减幅，coupled分词补充排放下降。","clause-object",["that","coupled","output"])],
12:[choice("emission-decrease","fell by around a quarter说的是哪一项？",["巡航阶段氮氧化物排放约下降25%","全航程所有排放精确降至25%","巡航燃油消耗增加25%"],"巡航阶段氮氧化物排放约下降25%","Nitrogen-oxide emissions during the cruising portions of the flight fell by around a quarter","保留主语排放种类、巡航范围、around约数与by下降幅度。","comparison-scope","translation",["by","around","quarter"],true)],
13:[link("existence-and-work","把存在的事物与待解决关系区分。",[["There","存在句引导成分"],["knots","存在的难题"],["to be worked out","修饰knots的被动不定式"]],"There are, of course, knots to be worked out","knots比喻难题，承受work out动作；there不指地点，of course是评注。","nonfinite-infinitive",["There","knots","worked"])],
14:[choice("safety-perception","or at least the perception of it如何修正前项？",["至少考虑人们对安全性的主观感受","否认任何客观安全问题存在","把it指成新的飞机型号"],"至少考虑人们对安全性的主观感受","safety, or at least the perception of it","it指safety，at least谨慎收缩到安全感；不是另加无关问题。","reference-pronoun","reference",["perception","it","least"],true)],
15:[link("question-not-conclusion","把疑问形式和情境结构分开。",[["Would","放在主语前提出疑问"],["comfortable","feel后的形容词表语"],["travelling in company","乘客结伴飞行的情境"]],"Would passengers feel comfortable travelling in company?","疑问句没有断言更舒适，comfortable也无比较级；company在此为结伴。","author-voice",["Would","comfortable","company"],true)],
16:[link("by-two-roles","同一句两个by分别说明什么？",[["by several nautical miles","飞机之间相隔距离"],["by display teams","favoured的施事：表演队"]],"could be separated by several nautical miles, and would not be in the intimate groupings favoured by display teams","距离单位使第一处by表间隔，第二处by表谁偏爱这种队形；like再举红箭队。","modifier-prepositional",["by","miles","favoured"])],
17:[link("passenger-modality","把观察者、动作和程度限制连接。",[["peering out of the window","修饰A passenger的分词短语"],["might","保留可能性"],["not even see the other planes","可能连其他飞机都看不到"]],"A passenger peering out of the window might not even see the other planes","张望的是乘客，might not不等于can not；本句没有推出更舒适的原因。","nonfinite-participle",["peering","might","even"],true)],
18:[range("whether-subject","选出完整充当主语的whether从句。","Whether the separation distances involved would satisfy air-traffic-control regulations","是否满足规定整个问题作主语，主句is another matter在其后。involved只修饰distances。","clause-subject",["Whether","involved","satisfy"]),choice("blueprint-limit","although后的蓝图信息能证明什么？",["已列入规划，但并未确认间距满足法规","已经完全满足空管规定","任何工作组尚未考虑过编队飞行"],"已列入规划，但并未确认间距满足法规","has included the possibility of formation flying in a blueprint for new operational guidelines","although承认规划进展，主句仍保留是否合规的问题；possibility与blueprint不能升级为现行批准。","clause-concession","option-logic",["although","possibility","blueprint"],true)],
19:[range("real-subject-how","选出It所占位置对应的完整how真正主语从句。","how weather conditions affect the air flows that make formation flight more efficient","how从句包含修饰air flows的that从句，直到efficient才结束，形式It本身无天气实体指代。","clause-subject",["It","how","that"]),link("weather-airflow","谁影响谁，谁使什么更高效？",[["weather conditions","affect的主语"],["air flows","affect的宾语核心及that先行词"],["formation flight","make的宾语"],["more efficient","说明formation flight的宾补"]],"weather conditions affect the air flows that make formation flight more efficient","天气影响气流，气流使编队飞行更高效；外层how询问影响方式，remains to be seen保留未知。","object-complement",["conditions","flows","that","make"],true)],
20:[link("turbulence-effects","两项变化分别发生在什么对象上？",[["will decay more quickly","the planes' wakes"],["will diminish","the effect"]],"the planes' wakes will decay more quickly and the effect will diminish","尾流更快衰减，节能效益减弱；一个例子不能代替所有天气影响的完整研究。","parallel-structure",["wakes","decay","effect","diminish"],true)],
21:[link("two-omitted-connectors","两个省略位置需要区分哪两类功能？",[["says之后、this之前","可补that内容连接词"],["areas之后、his team之前","可补作investigate宾语的关系代词"]],"says this is one of the areas his team will investigate further","外层连接词不担任从句成分，内层关系代词指areas并充当宾语；同样省略that不等于同一语法作用。","clause-relative",["says","areas","investigate"])],
22:[link("coordination-roles","把形式主语、协调者和方式从句对应。",[["It","后置不定式的形式主语"],["for airlines","说明co-ordinate执行者"],["that","回指a way并作allow主语"],["them","回指airlines并作allow宾语"]],"It might also be hard for airlines to co-ordinate the departure times and destinations of passenger aircraft in a way that would allow them to gain from formation flight","协调客机时间和目的地可能困难；that限定方式，them不指目的地。","nonfinite-subject",["It","for","that","them"],true)],
23:[link("analogy-ellipsis","还原as分句中的主语、保留谓语及省略内容。",[["routine military flights","as分句主语"],["might","前置保留的情态动词"],["be easier to reschedule","承接前句而省略的谓语内容"]],"as might routine military flights","军用例行航班也可能更易调度；as为类比，不是因为；might仍是可能。","parallel-structure",["as","might","flights"])],
24:[choice("current-action","are on the case already说明哪个时间层？",["文章叙述当时美国军方已着手此事","二战美国军方的编队节油已经确证","美国军方已经完成未来全部试验"],"文章叙述当时美国军方已着手此事","America's armed forces are on the case already","现在时are配already表示文中当时已行动，不能跨到后文二战传闻。","time-reference","tense",["are","already","case"],true)],
25:[link("plan-actors-status","把机构、波音及项目状态连接。",[["the country's Defence Advanced Research Projects Agency","announced的主语及付费计划方"],["Boeing","pay的宾语及investigate执行者"],["has yet to begin","研究项目尚未启动"]],"announced plans to pay Boeing to investigate formation flight, though the programme has yet to begin","宣布的是付费研究计划；to pay说明plans内容，to investigate说明波音承担的任务，though限制实际进度。","nonfinite-infinitive",["plans","pay","Boeing","yet"],true)],
26:[link("two-they","两处they不能因字形相同就接同一对象。",[["when they were low on fuel","they指some military aircraft"],["they are unsubstantiated","they指reports"]],"when they were low on fuel during the Second World War, but Dr. Lissaman says they are unsubstantiated","飞机会缺油，报道会未经证实。后一个they越过军机回指reports，but限制报道可信度。","reference-pronoun",["they","reports","unsubstantiated"],true),range("report-content","选出解释reports的完整that内容从句，保留内部when情境。","that some military aircraft flew in formation when they were low on fuel during the Second World War","that统领报道的完整内容，内部when限定军机何时编队；but Dr. Lissaman says开始另一主句。","complement-content",["that","when","but"])],
27:[link("family-ellipsis","把省略、飞机修饰及引述者分开。",[["my cousin the skipper","cousin后省略was"],["lost over Berlin","修饰a Lancaster"],["he adds","he指Dr. Lissaman"]],"My father was an RAF pilot and my cousin the skipper of a Lancaster lost over Berlin","原文只明确飞机损失，不由lost推亲属死亡或性别；第二分句省was，adds在引语外标说话者。","parallel-structure",["cousin","skipper","lost","he"])],
28:[choice("should-inference","So he should know中should的作用是？",["根据家庭背景推断他应当了解","规定他必须去接受新培训","证明战争报道已经成为确凿档案"],"根据家庭背景推断他应当了解","So he should know","这是合理预期，不是义务命令，也不改变unsubstantiated给出的证据等级。","author-voice","translation",["should","So"],true)],
};

// 结构连接反馈明确解释15%为减幅，揭示同句数量题。
passage2010P5Practice[11][1].leaksToTaskIds=["less-fuel"];
