import type { PracticeTask,GrammarConceptId,ErrorCategory } from "./learning-model";
const choice=(id:string,prompt:string,options:string[],answer:string,evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[]=[]):PracticeTask=>({id,revision:1,kind:"choice",prompt,options,answer,evidence,feedback,conceptId,errorType,hintWords,mapRevealsAnswer:false});
const range=(id:string,prompt:string,answer:string,feedback:string,conceptId:GrammarConceptId,hintWords:string[]=[]):PracticeTask=>({id,revision:1,kind:"range",prompt,options:[],answer,evidence:answer,feedback,conceptId,errorType:"clause-boundary",hintWords,mapRevealsAnswer:false});
const link=(id:string,prompt:string,links:[string,string][],evidence:string,feedback:string,conceptId:GrammarConceptId,hintWords:string[]=[]):PracticeTask=>({id,revision:1,kind:"link",prompt,links:links.map(([source,target])=>({source,target})),options:[...new Set(links.map(([,target])=>target))],answer:JSON.stringify(links.map(([,target])=>target)),evidence,feedback,conceptId,errorType:"attachment",hintWords,mapRevealsAnswer:false});
export const translation2010Practice:Record<number,PracticeTask[]>={
1:[link("public-personal","把两个判断中的关键名词接回它的作用。",[["a popular word","become后的表语，说明社会流行"],["the concept","回指Sustainability的第二分句主语"],["personal meaning","have的宾语，说明切身意义"]],"has become a popular word these days, but to Ted Ning, the concept will always have personal meaning","become为系动词，have为实义动词；but把同一个概念的社会流行与个人意义对照。","basic-svc",["become","concept","meaning","but"])],
2:[range("complete-subject","选出made的完整主语，不包含made。","Having endured a painful period of unsustainability in his own life","Having endured直到life整体作主语，名词化表达亲身经历；主句有限谓语从made开始。","subject-head",["Having","endured","made"]),link("formal-object","将形式宾语结构中的成分接到各自作用。",[["it","先占宾语位置"],["clear","说明宾语内容的状态"],["to him","指出对谁而言清楚"],["that sustainability-oriented values must be expressed through everyday action and choice","后置的真正宾语内容"]],"made it clear to him that sustainability-oriented values must be expressed through everyday action and choice","it不是前面那段经历；经历是主语。clear为宾补，that从句说明必须落实价值观的认识。","object-complement",["it","clear","that","made it clear to him"])],
3:[link("nested-doing","把两层-ing结构与支配它的表达配对。",[["spending a confusing year in the late 1990s selling insurance","recalls的整个动名词宾语"],["a confusing year","spending所花的时间"],["selling insurance","spend time doing中的具体活动"]],"recalls spending a confusing year in the late 1990s selling insurance","只有recalls为主句有限谓语。spending表达回忆内容，selling说明时间花在卖保险上，两个非谓语动作的执行者同为宁。","nonfinite-subject",["recalls","spending","selling"]),choice("decade-range","in the late 1990s应译成什么时间？",["20世纪90年代末","1990年年底","1999年某个确定日期"],"20世纪90年代末","in the late 1990s","1990s表示十年，late表示其后期；原句没有把卖保险年份精确到某一年或某天。","time-reference","translation",["in the late 1990s","1990s","late"])],
4:[link("two-and-levels","把并列与插入结构的层次接准确。",[["boom and burst","并列互联网行业的两个阶段"],["and, desperate for a job, signed on","在第二个并列谓语前插入求职状态"],["desperate for a job","补充He的处境，解释签约动机"],["He'd been","'d为had，构成过去完成时"]],"He'd been through the dot-com boom and burst and, desperate for a job, signed on","第一个and连接名词，第二个连接谓语部分；desperate短语没有限定动词。'd在been前不能展开为would。","parallel-structure",["He'd","and","desperate","signed"]),choice("agency-action","signed on with a Boulder agency在这段经历中表示什么？",["与博尔德一家代理机构签约工作","在巨石机构的网站登录账号","给博尔德一家机构张贴招牌"],"与博尔德一家代理机构签约工作","signed on with a Boulder agency","sign on with接工作机构；Boulder为地名，结合前句销售保险可明白机构业务。","lexical-context","collocation",["signed on with a Boulder agency","Boulder","agency"])],
5:[choice("real-reference","It在本句指什么？",["前文卖保险工作的开展情况","尚未出现的后置that从句","宁所站的某条道路"],"前文卖保险工作的开展情况","It didn't go well","It有具体回指，go well意为进展顺利；didn't使整项判断为否定。这里没有形式主语的后置内容。","reference-pronoun","reference",["It","go well"])],
6:[range("whose-boundary","选出完整whose从句，保留插入评注和结果短语。","whose dilemma about the job translated, predictably, into a lack of sales","whose从句从所属限定词到sales结束；predictably是内部插入评注，逗号不结束该从句。","clause-relative",["whose","translated","predictably"]),link("quote-and-narration","把评价、原因和结果接到它们的叙述层次。",[["a really bad move","宁在引语中评价入职决定"],["because that's not my passion","引语内部的原因"],["says Ning","引语外标明说话者"],["whose dilemma about the job","引语外补充宁的工作两难"]],"It was a really bad move because that's not my passion,\" says Ning, whose dilemma about the job","because在引号内，whose在引号外。that's的that为指示代词，不是宾语从句连接词；says Ning是报道倒装。","author-voice",["because","that's","says","whose"])],
7:[choice("miserable-role","miserable在句中是什么成分，主要表达什么？",["形容词表语，说明宁当时很痛苦","动词宾语，表示宁实施伤害","方式副词，说明宁如何说话"],"形容词表语，说明宁当时很痛苦","I was miserable","was为系动词，miserable描述I的精神状态；后句用焦虑与夜醒具体说明。","basic-svc","predicate",["was","miserable"])],
8:[range("whole-result","选出完整that结果从句，保留两个并列动作。","that I would wake up in the middle of the night and stare at the ceiling","从句直到ceiling结束；and stare与wake up共用主语I和would，仍在结果范围内。","clause-result",["that","so much anxiety that I would wake up in the middle of the night and stare at the ceiling"]),choice("would-habit","would在这段回忆中最合适的解释是什么？",["过去常常反复发生的行为","一个尚未给出的条件所造成的虚拟结果","明确要求别人必须醒来的义务"],"过去常常反复发生的行为","I would wake up in the middle of the night and stare at the ceiling","宁描述当时焦虑导致的反复夜醒和凝视。句中没有if条件，也没有向别人提出义务。","time-reference","tense",["would","wake up"])],
9:[link("two-needs","把并列谓语和宾语对应起来。",[["had","以no money为宾语：没有钱"],["needed","以the job为宾语：需要工作"],["I","两个过去时实义动词共享的主语"]],"I had no money and needed the job","had和needed都为实义动词过去式；没有钱且需要工作，解释了为何缺少热情却不能轻易离开。","parallel-structure",["had","needed","money","job"])],
10:[link("three-utterances","将大家的话分成两项建议和一项未来判断。",[["Just wait","祈使建议，省略you"],["you'll turn the corner","陈述判断，you will加原形"],["give it some time","祈使建议，含双宾语"]],"Just wait, you'll turn the corner, give it some time","原卷三个分句用逗号并置；单引号结束大家的话，双引号再结束宁的自述。不要把所有动词都当作一个祈使句。","parallel-structure",["Just wait","you'll","give it some time"]),choice("encouragement-not-outcome","you'll turn the corner应怎样理解和翻译？",["大家鼓励他将会迎来转机，原文未交代后来的结果","作者确认他当时已经扭转销售业绩","大家指示他在下一个街角转弯"],"大家鼓励他将会迎来转机，原文未交代后来的结果","Everyone said, 'Just wait, you'll turn the corner, give it some time.'","turn the corner为摆脱困境、开始好转的比喻。句子保留他人当时的劝慰，不能补写成功结局。","author-voice","translation",["Everyone","you'll","turn the corner"])],
};
// s8第二项反馈给出两个动作均属结果从句，但未给完整起止边界；不自动泄露划界答案。
