import type { PhraseKnowledge } from "./knowledge-base";

type PhraseSeed = [key: string, canonical: string, sources: string[], meaning: string, role: string, rule: string, english: string, chinese: string, pitfall: string];

const seeds: PhraseSeed[] = [
  ["address-audience", "address + audience", ["was addressing a small gathering"], "向听众讲话", "动宾结构；本句为过去进行时谓语与宾语", "address 是及物动词，直接接听众，不加 to；进行时使用 be addressing。", "She addressed a small gathering.", "她向一小群聚会者讲话。", "不能把 address 机械译为地址，也不要说 address to an audience 表向听众讲话。"],
  ["invite-somebody-to-do", "invite somebody to do something", ["had invited men to join them"], "邀请某人做某事", "定语从句内的谓语、宾语和宾语补足语", "somebody 是 invite 的宾语，也是 to do 的逻辑主语。", "They invited us to join the discussion.", "他们邀请我们参加讨论。", "这里用 to join，不用 invite somebody doing；join them 不加 to。"],
  ["throughout-period", "throughout + period", ["Throughout the evening"], "在整个时段内", "时间状语", "throughout 强调整段时间；后接名词时为介词，不直接引导完整主谓句。", "He remained silent throughout the meeting.", "他在整场会议期间一直沉默。", "during 只说明在某期间，不必然与 throughout 的全过程意味相同。"],
  ["offer-ideas", "offer + ideas / anecdotes", ["offering ideas and anecdotes"], "发表看法、讲述趣闻", "现在分词伴随状语中的动宾结构", "offer 接 ideas 与 anecdotes 两个并列宾语，逻辑主语与男子一致。", "She offered ideas and anecdotes during the discussion.", "她在讨论中发表看法并讲述趣闻。", "offering 本身没有限定时态，不能将其单独标为新从句。"],
  ["toward-end", "toward the end of + period", ["Toward the end of the evening"], "接近某时段结束时", "时间状语", "toward 表接近，end 后的 of 短语指出是哪一段时间的末尾。", "They reached an agreement toward the end of the meeting.", "快到会议结束时，他们达成了共识。", "toward the end 是接近结尾，不等于 throughout 所表示的全过程。"],
  ["talk-to-somebody", "talk to somebody", ["talk to them", "talk to me"], "与某人交谈", "谓语中的动词和交谈对象补足语", "talk 通常不及物，to 或 with 引出交谈对象；本句的对象不可省掉，否则改变否定范围。", "He does not talk to me at home.", "他在家不与我交谈。", "talk to me 不表示告诉我某件具体事情；tell 通常另需内容宾语。"],
  ["nod-in-agreement", "nod in agreement", ["nodded in agreement"], "点头表示赞同", "谓语和态度状语", "nod 描述动作，in agreement 说明动作表达的态度；过去式双写 d。", "She nodded in agreement.", "她点头表示赞同。", "agreement 此处为认同状态，不是协议文本。"],
  ["gesture-toward", "gesture toward somebody", ["gestured toward his wife"], "朝某人做手势示意", "谓语及方向状语", "toward 引方向；手势的具体含义需由上下文判断。", "He gestured toward the door.", "他朝门的方向示意了一下。", "gesture 不自动表示指责或愤怒，不应在译文中补入。"],
  ["burst-into-laughter", "burst into laughter", ["burst into laughter"], "突然大笑起来", "不及物动词固定搭配", "burst 的过去式仍为 burst；into 后接 laughter 这种表示突然出现行为状态的名词。", "The audience burst into laughter.", "听众突然大笑起来。", "laughter 不可数；不要写 burst into laugh 或 a laughter。"],
  ["look-adjective", "look + adjective", ["looked puzzled and hurt"], "显得处于某种状态", "系动词与表语", "look 后接形容词作表语，本句用 and 连接 puzzled 与 hurt 两种感受。", "He looked puzzled and hurt.", "他显得既困惑又委屈。", "系动词后的状态用形容词，不能因中文有‘地’而误用副词。"],
  ["come-home-from-work", "come home from work", ["come home from work"], "下班回家", "时间从句中的谓语和方向、来源状语", "home 在 come home 中为方向副词，前面不加 to；from work 说明来处。", "I usually come home from work at six.", "我通常六点下班回家。", "不能写 come to home；work 此处是工作场所或上班状态，不是艺术作品。"],
  ["nothing-to-say", "nothing to say", ["nothing to say"], "没有什么可说的", "不定代词与后置不定式", "nothing 为中心词，to say 后置修饰，nothing 是 say 的逻辑宾语。", "I have nothing to say.", "我没有什么可说的。", "nothing 已含否定，不再加 not 构成无意的双重否定。"],
  ["keep-object-doing", "keep something doing", ["keep the conversation going"], "使某事持续进行", "动词、宾语和现在分词宾语补足语", "宾语与 doing 构成主动关系：conversation 在继续进行。", "Her questions kept the conversation going.", "她提出的问题让谈话继续了下去。", "keep doing 是主语自己持续做，keep something doing 是让宾语所指的事情持续。"],
  ["in-silence", "in silence", ["in silence"], "沉默地；在沉默中", "状态或方式状语", "in 后接名词 silence；相应副词为 silently，两者是不同句法形式。", "They spent the evening in silence.", "他们默默地度过了那个晚上。", "不要写 in silent，silent 是形容词。"],
  ["tend-to-do", "tend to do something", ["tend to talk"], "往往会；倾向于做某事", "动词与不定式补足语", "tend 表一般倾向而非没有例外的规律；to 后用动词原形。", "People tend to talk more when they feel comfortable.", "人们感到自在时往往说得更多。", "不能把 tend to 加强为 always；题目选项须保留倾向性。"],
  ["in-public-situations", "in public situations", ["in public situations"], "在公共或有外人在场的场合", "场合状语", "public situations 与 at home 构成范围对照，分别限制交谈表现。", "He is talkative in public situations.", "他在公共场合很健谈。", "公开场合不等于仅在政府机构，也包括本文的社交聚会。"],
  ["wreak-havoc", "wreak havoc with / on something", ["wreaking havoc with marriage"], "对某事造成严重破坏", "谓语固定搭配及受影响对象", "wreak 是及物动词，havoc 是不可数宾语；with/on 引受损对象，原文用 with。", "The storm wreaked havoc with transport.", "风暴严重扰乱了交通。", "不能只解释为一般的施加影响，必须保留 havoc 的强烈负面意义。"],
  ["in-late-decade", "in the late + decade", ["in the late 1970s"], "在某年代后期", "时间状语", "1970s 表1970—1979这一年代，late 缩小到后期；年代前用 in。", "The change began in the late 1970s.", "这一变化始于20世纪70年代后期。", "不要把1970s读成1970年，也不要在普通复数年代中加入所有格撇号。"],
  ["only-a-few-of", "only a few of + definite plural noun", ["only a few of the men"], "这些人中只有少数", "数量名词短语；本句为插入对照成分", "a few 表有一些，only 强调数量少；of 后用有明确范围的复数名词。", "Only a few of the men agreed.", "这些男性中只有少数赞同。", "few 强调几乎没有；a few 则肯定仍有一些，不应混同。"],
  ["lack-of-something", "lack of something", ["lack of communication"], "缺乏某事物", "名词与 of 补足语", "lack 作名词时常接 of；作及物动词时直接接宾语。", "Lack of communication can damage a relationship.", "缺乏沟通可能损害一段关系。", "不能把名词 lack of 与动词 lack 的句法直接混用。"],
  ["reason-for-something", "the reason for something", ["the reason for their divorces"], "某事发生的原因", "名词与后置补足语", "for 后接被解释的事件；give A as the reason for B 是将A列为B的原因。", "She gave stress as the reason for leaving.", "她把压力列为离开的原因。", "当事人陈述的原因不自动等于已统计证实的全部原因占比。"],
  ["given-fact", "given + noun phrase", ["Given the current divorce rate"], "考虑到；鉴于", "依据状语", "given 在此为介词，后接作为判断背景的名词短语，不需要为其补主语。", "Given the limited time, we must focus.", "鉴于时间有限，我们必须集中精力。", "此处不是 give 的被动谓语，也不是一个已有主谓的条件从句。"],
  ["amount-to-number", "amount to + quantity", ["amounts to millions of cases"], "总计为；相当于某数量", "动词和介词数量补足语", "amount 作不及物动词，通过 to 引数量；millions of 表概数。", "The cost amounts to a million dollars.", "费用总计一百万美元。", "amount 在本句不是名词‘数量’，也不能漏掉 to。"],
  ["virtual-epidemic", "a virtual epidemic of something", ["a virtual epidemic"], "几乎达到流行病程度的普遍现象", "名词短语；本句作比喻性同位评价", "virtual 这里是‘几乎等同于’，epidemic 用于比喻频繁发生的问题。", "The region faced a virtual epidemic of theft.", "这一地区的盗窃现象几乎泛滥成灾。", "不要当作虚拟现实，也不能把修辞比喻报道成医学流行病。"],
  ["focus-on-object", "focus on something", ["focused not on tangible inequities", "focused on communication"], "集中关注某事", "谓语和关注对象补足语", "on 引对象；not on A 与后句 Instead...on B 表示焦点不在A而在B。", "Their complaints focused on communication.", "他们的抱怨集中在沟通问题上。", "排除主要关注点不等于否认事业牺牲或家务不公平存在。"],
  ["give-up-opportunity", "give up + opportunity", ["given up the chance"], "放弃机会", "完成形式非谓语内部的动宾搭配", "give up 可接名词或动名词；having given up 表放弃发生在比较研究发现之前。", "She gave up the chance to study abroad.", "她放弃了出国学习的机会。", "不能把 given up 当成被动，因为前面有 having 构成主动完成形式。"],
  ["more-than-share", "far more than one's share", ["far more than their share"], "远超过某人应承担的份额", "数量比较结构", "far 加强比较级 more，one's share 为比较基准；本句是家务分工份额。", "She did far more than her share of the work.", "她做的工作远超过自己应承担的份额。", "这里 share 是名词，不是动词分享，也不是股票。"],
  ["daily-life-work", "daily life-support work", ["daily life-support work"], "维持日常生活的事务", "名词短语", "daily 与 life-support 共同修饰 work，下文用清洁、做饭、社交安排作例子。", "They shared daily life-support work such as cooking.", "他们分担做饭等维持日常生活的事务。", "本句无医疗设备语境，不应译为医院生命支持工作。"],
  ["listen-to-somebody", "listen to somebody", ["listen to me"], "听某人说话", "不及物动词和对象补足语", "listen 强调主动倾听，介词 to 引出被倾听的人。", "Please listen to me.", "请听我说。", "hear 重感知结果；listen 重主动行为，不能机械互换。"],
  ["first-and-foremost", "first and foremost", ["first and foremost"], "首先；最重要的是", "优先顺序状语", "作为整体强调最重要的事项，可插入句中；不意味着其他角色都不存在。", "A partner should be, first and foremost, a good listener.", "伴侣首先应该是一个好的倾听者。", "不是两个不同的名次，也不应只按时间先后理解。"],
  ["conversational-partner", "conversational partner", ["conversational partners"], "交谈伙伴", "名词短语；本句为不定式中的表语", "conversational 为形容词修饰 partner；复数 partners 对应复数 husbands。", "They want to be conversational partners.", "他们希望成为能够相互交谈的伙伴。", "此处不是商业合伙人，也不是要求另找伴侣。"],
  ["share-expectation", "share an expectation", ["share this expectation"], "持有同样的期待", "动宾搭配", "share 表共同持有同一想法，不是把期待分成若干份；of somebody 说明期望对象。", "Few husbands share this expectation.", "很少有丈夫持有同样的期待。", "不要套用 their share of work 中名词‘份额’的意思。"],
  ["in-short-summary", "in short", ["In short"], "简言之", "总结衔接语", "用于概括前文，通常用逗号与主句隔开。", "In short, communication matters.", "简言之，沟通很重要。", "与 in the short term（短期内）不同，本结构不限定时间。"],
  ["at-meal-table", "at the breakfast table", ["at the breakfast table"], "在早餐桌旁", "地点状语", "at 描述人在桌旁的位置或用餐情境，on 则通常表示物体在桌面上。", "He sat at the breakfast table.", "他坐在早餐桌旁。", "不能译成人坐在早餐桌面上。"],
  ["with-noun-participle", "with + noun + past participle", ["with a newspaper held up in front of his face"], "某物处于被……的伴随状态", "with 复合结构；伴随状语", "a newspaper 是 with 的宾语，held up 是过去分词宾补，两者为被动关系。", "He sat with a newspaper held up in front of his face.", "他坐着，报纸举在脸前。", "没有独立的限定动词，不能把 with 结构标成完整从句。"],
  ["in-front-of-object", "in front of something", ["in front of his face"], "在某物前面", "位置状语", "in front of 为整体位置表达；his face 是参照物，报纸位于其前面。", "She stood in front of the house.", "她站在房屋前面。", "in front of 指外部前方，in the front of 常指某空间内部前部。"],
  ["glare-at-object", "glare at somebody / something", ["glares at the back of it"], "怒视；瞪着某人或某物", "谓语与目光对象补足语", "at 引目光所向；the back of it 指报纸背面，it 必须回指 newspaper。", "She glared at the back of the newspaper.", "她瞪着报纸的背面。", "glare 比 look 更带不满或怒意；不能把 it 错指为男人的脸。"],
  ["judging-from-evidence", "judging from + evidence", ["Judging from the context"], "根据某依据判断", "固定评注表达", "judging from 引出判断依据；该表达评注整个判断，不要求句子主语是 judge 的动作发出者。", "Judging from the context, this word means a serious problem.", "根据语境，这个词意为一个严重问题。", "这里的 judging 是判断，不是名词 judges 所指的法官。"],
  ["expression-means", "an expression means + meaning", ["the phrase means"], "某表达意思是……", "主语与释义谓语结构", "mean 直接接所表示的内容；the phrase 为单数，谓语用 means。此处展示规范搭配，不把引号与位置标注删除后伪称原文连续片段。", "The phrase means causing damage.", "这个短语的意思是造成损害。", "means 在这里是动词第三人称单数，不是名词手段，也不是 mean to do 的打算。"],
  ["in-public", "in public", ["in public"], "在公开场合", "场合状语", "public 在固定表达 in public 中作名词，整组限定行为发生的场合。", "He talks more in public than at home.", "他在公开场合比在家说得更多。", "in public 不等于只在政府机关，也不是 public defender 的公共法律服务义。"],
  ["share-housework", "share housework", ["Sharing housework", "Sharing housework."], "分担家务", "动词搭配；选项为动名词短语", "share 直接接不可数名词 housework；Sharing 把该行为作为期待的内容。", "Both partners should share housework.", "伴侣双方都应分担家务。", "这里 share 是动词分担，不是 their share 中的名词份额。"],
  ["divorce-talk-title", "Divorce Talk", ["Divorce Talk"], "《离婚谈话》（书名）", "专有名词短语", "Divorce 与 Talk 共同构成书名，补充说明 book；Talk 在书名中为名词，不是正在执行谈话动作。", "The findings appear in the book Divorce Talk.", "这些发现见于《离婚谈话》一书。", "书名只需识别，不把它误解成要求夫妻谈离婚的祈使句。"],
  ["more-research", "more + uncountable noun", ["more research"], "更多的不可数事物；此处为更多研究", "数量限定结构", "more 限定不可数名词 research；此处不修饰动词，也不构成 the more..., the more... 的关联比较。", "The issue deserves more research.", "这个问题值得更多研究。", "research 表研究活动时通常不可数；一项具体研究可以用 a study。"],
  ["expectation-of-person", "an expectation of somebody", ["main expectation of their husbands"], "对某人抱有的期待", "名词与期待对象补足语", "of 引出被期待的人；题干的 wives' 才说明期待由谁提出。", "She had high expectations of her husband.", "她对丈夫抱有很高的期待。", "不能把 of their husbands 误解为期待由丈夫提出。"],
  ["trust-person", "trust somebody", ["Trusting them", "Trusting them."], "信任某人", "及物动词搭配", "trust 直接接人物作宾语，动名词 Trusting 把该行为作为期待内容。", "They trust each other.", "他们互相信任。", "不加 to；信任与交谈是不同的行为。"],
  ["support-career", "support somebody's career", ["Supporting their careers", "Supporting their careers."], "支持某人的事业", "动名词与名词宾语", "support 直接接 career，their 限定事业属于谁。", "He supports his wife's career.", "他支持妻子的事业。", "support 作动词可直接接宾语，不套名词 support for 的介词结构。"],
  ["generate-motivation", "generate motivation", ["generating motivation"], "产生动力", "动词搭配", "generate 后接产生的结果，motivation 指做事的动力。", "Clear goals can generate motivation.", "明确的目标可以产生动力。", "动力与严重破坏不同，不能因同为结果名词就当作近义。"],
  ["exert-influence", "exert influence", ["exerting influence"], "施加影响", "动词搭配", "exert 直接接 influence，影响的方向需由上下文说明。", "His advice exerted influence on the decision.", "他的建议对这一决定产生了影响。", "影响可以是正面或负面，不能自动等同于造成严重破坏。"],
  ["cause-damage", "cause damage", ["causing damage"], "造成损害", "动词与不可数名词宾语", "damage 作不可数名词，表示受损结果；受损对象可由 to 引出。", "The storm caused damage to the bridge.", "暴风雨损坏了桥梁。", "damages 在法律语境可指赔偿金，与不可数损害义不同。"],
  ["create-pressure", "create pressure", ["creating pressure"], "造成压力", "动词搭配", "create 后接结果名词 pressure；对谁的压力可由 on 引出。", "The deadline created pressure on the team.", "截止日期给团队带来了压力。", "产生压力不必然意味着已经造成严重损害。"],
  ["all-of-following", "all of the following", ["All of the following"], "下列所有各项", "数量代词与范围补足语", "all 为数量代词，of the following 指明范围，following 在 the 后名词化。", "All of the following are true except one.", "下列各项除一项外均为真。", "遇到 EXCEPT 必须保留排除要求，不能直接选一个正确陈述。"],
  ["which-of-following", "which of the following", ["Which of the following"], "下列哪一项", "疑问代词与选择范围", "which 为疑问代词，of the following 指向后面的候选项；可整体作疑问句主语。", "Which of the following best summarizes the text?", "下列哪一项最能概括这篇文章？", "不是关系代词 which 引导的定语从句。"],
  ["percentage-of-whole", "percentage of + whole", ["nearly 50 percent of recent divorces"], "某一总体中的某个百分比", "比例名词短语", "of 后明确统计总体；nearly 50 percent of recent divorces 指近期离婚案例中的近一半。", "Nearly 50 percent of the cases involved a delay.", "近一半案例涉及延误。", "必须核对分母；离婚案例中的某原因比例与离婚率本身不是同一指标。"],
  ["be-caused-by", "be caused by + cause", ["are caused by failed conversation"], "由某原因造成", "被动谓语及原因补足语", "be caused 为被动结构，by 引原因；本项把沟通失败断言为某些离婚的原因。", "The delay was caused by bad weather.", "延误是恶劣天气造成的。", "访谈中的原因归属不自动证明总体中的因果比例。"],
  ["between-plural-noun", "between + plural noun", ["between couples"], "在所述各方之间", "介词与复数名词", "between 可以直接接表示各方的复数名词；这里限定夫妻之间的交流，不补造 A and B。", "Communication between partners matters.", "伴侣之间的沟通很重要。", "between A and B 是另一种展开形式，不能要求原句一定另有 and。"],
  ["stem-from-cause", "stem from + cause", ["stems from sex inequalities", "stems from", "stem from"], "源于某原因", "动词与来源补足语", "stem 作不及物动词，from 引出根源；主语单数时用 stems。", "The problem stems from poor communication.", "问题源于沟通不畅。", "表原因来源，不是名词茎，也不能将相关性直接强化为因果。"],
  ["expectations-from", "expectations from something", ["different expectations from their marriage"], "对从某事中得到什么的期待", "名词与期待来源补足语", "from their marriage 说明期待从婚姻中得到什么，different 修饰期待。", "They have different expectations from their marriage.", "他们对婚姻抱有不同期待。", "这个表达比对交谈的期待范围宽；不能在翻译中擅加 conversational。"],
  ["immediately-after-text", "immediately after + noun phrase", ["immediately after this text"], "紧接在某事物之后", "副词修饰介词短语", "immediately 加强 after 的紧接关系，after 后为名词短语，不是完整时间从句。", "The explanation appears immediately after this paragraph.", "解释紧接在这一段后面。", "紧接下文与以后任意位置不同，篇章预测不能忽略这个范围。"],
  ["account-of-object", "an account of something", ["a vivid account of the new book Divorce Talk"], "对某事物的叙述或介绍", "名词与内容补足语", "account 为叙述，of 引介绍对象；vivid 形容介绍生动，Divorce Talk 是 book 的书名说明。", "She gave a vivid account of the meeting.", "她生动地介绍了会议情况。", "此处 account 不是账户，也不是动词 account for 表解释。"],
  ["description-of-object", "a description of something", ["a detailed description of the stereotypical cartoon"], "对某事物的描写", "名词与内容补足语", "description 为中心名词，of 引描写对象，detailed 修饰描述的详尽程度。", "The report contains a detailed description of the scene.", "报告包含对该场景的详细描述。", "description 是名词，不是 describe 的谓语形式。"],
  ["introduction-to-person", "an introduction to somebody", ["a brief introduction to the political scientist Andrew Hacker"], "对某人的简要介绍", "名词与介绍对象补足语", "to 后接被介绍的人物名词短语；Andrew Hacker 是 political scientist 的姓名同位说明。", "The article gives a brief introduction to the scientist.", "文章简要介绍了这位科学家。", "to 是介词，不是不定式；introduction of 在其他语境还可表引入某事物。"],
];

export const passage2010P2PhraseGuides: Record<string, PhraseKnowledge> = Object.fromEntries(seeds.map(([key, canonical, , meaning, grammarRole, rule, english, chinese, pitfall]) => [key, {
  key, canonical, type: "交谈与婚姻语篇中的词组/句法结构", meaning, summary: `${meaning}。${rule}`, grammarRole,
  structures: [{ pattern: canonical, meaning, rule, examples: [{ english, chinese }] }], pitfalls: [pitfall],
}]));

export const passage2010P2PhraseAliases: Record<string, string> = Object.fromEntries(seeds.flatMap(([key, canonical, sources]) => [...sources, canonical].map(source => [source.toLowerCase(), key])));
export const passage2010P2CollocationGlosses = Object.fromEntries(seeds.flatMap(([, , sources, meaning, , rule]) => sources.map(source => [source.toLowerCase(), { meaning, note: rule }])));
Object.assign(passage2010P2PhraseAliases, {
  "talking to them": "talk-to-somebody",
  "talking to them.": "talk-to-somebody",
  "wreaking havoc": "wreak-havoc",
  "attach much importance to communication": "attach-importance",
  "tends to be more talkative": "tend-to-do",
  "focus on": "focus-on-object",
  "reasons for a high divorce rate": "reason-for-something",
  "communication between couples": "between-a-and-b",
  "between man and wife": "between-a-and-b",
});
Object.assign(passage2010P2CollocationGlosses, {
  "talking to them": { meaning: "与她们交谈", note: "Talking为动名词，them回指题干中的妻子；to是引出交谈对象的介词。" },
  "talking to them.": { meaning: "与她们交谈", note: "Talking为动名词，them回指题干中的妻子；to是引出交谈对象的介词。" },
  "wreaking havoc": { meaning: "造成严重破坏", note: "wreaking是动词的-ing形式，havoc为不可数宾语；保留严重负面的程度。" },
  "attach much importance to communication": { meaning: "很重视交流", note: "attach importance to为规范结构；much限定不可数importance，to后接名词communication。" },
  "tends to be more talkative": { meaning: "往往更加健谈", note: "tends to表示倾向，to be后接形容词比较表达，不保证所有人都如此。" },
  "focus on": { meaning: "集中关注；着重于", note: "on为引出话题的介词，后接名词或动名词；题干中的话题由选项补出。" },
  "reasons for a high divorce rate": { meaning: "高离婚率的原因", note: "for引出需要解释的现象；other possible另外限定还有哪些可能原因。" },
  "communication between couples": { meaning: "夫妻双方之间的沟通", note: "本题 couples 指夫妻关系中的双方；不能脱离婚姻语境读成多对夫妻彼此聊天。" },
  "between man and wife": { meaning: "在丈夫和妻子之间", note: "man 与 wife 用 and 平行连接，between 短语限定所比较的交谈模式属于哪两方。" },
});
export const passage2010P2FamilyGlosses: Record<string, string> = {
  talk: "交谈", talker: "爱说话的人", talkative: "健谈的", conversation: "交谈", conversational: "交谈的",
  complain: "抱怨", complaint: "抱怨；不满意见",
};
