import type { SentenceWordContext } from "./contextual-vocabulary";
import type { WordKnowledge } from "./knowledge-base";
type Seed = SentenceWordContext & { knowledge: WordKnowledge };
const w=(partOfSpeech:string,contextualMeaning:string,use:string,pattern:string,meaning:string):Seed=>({partOfSpeech,contextualMeaning,use,knowledge:{grammarRole:partOfSpeech,grammarSummary:use,structures:[{pattern,meaning,rule:use}]}});
// 每条均按当前来源人工写明结构；不让通用旧篇示例覆盖当前句。
const sources:Record<string,Record<string,Seed>>={
"2010-p3-s1":{
past:w("adj.","过去的","past修饰decade，限定此前十年。","the past decade","过去十年"),have:w("aux.","标记过去完成时","had与perfected构成过去完成时，不能解作拥有。","had perfected the art","此前已完善手法"),of:w("prep.","引出内容","of后接creating短语，解释art具体是哪种手法。","the art of doing something","做某事的手法"),among:w("prep.","在……群体中","among consumers限定培养行为的人群范围，不是在老年人中比较。","among consumers","在消费者群体中"),decade:w("n.","十年","over the past decade覆盖此前十年，原文没有or so约数。","over the past decade","在过去十年里")},
"2010-p3-s2":{
have:w("aux.","标记现在完成时","have helped为现在完成时，说明已产生的帮助作用。","have helped companies earn","已经帮助企业赚取"),of:w("prep.","引出数量或内容范围","billions of dollars说明金额，a set of daily cues说明一套提示的内容。","billions of dollars; a set of cues","数十亿美元；一套提示"),when:w("conj.","当……时","when引出消费者吃零食或擦台面的场景，主语为customers。","when customers eat snacks or wipe counters","当顾客吃零食或擦台面时"),customer:w("n.","顾客","customers是eat和wipe共同主语，不涉及互联网潜在客户。","customers eat snacks or wipe counters","顾客吃零食或擦台面"),almost:w("adv.","几乎","almost修饰without thinking，保留未必完全无意识的程度。","almost without thinking","几乎不假思索"),often:w("adv.","经常","often限定消费者行为响应日常提示的频率。","often in response to daily cues","常作为对日常提示的反应"),in:w("prep.","处于……反应关系中","in response to整体说明行为对提示作出响应。","in response to something","对某事作出反应"),to:w("prep.","引出响应对象","response to中的to接一套提示的名词短语，不是不定式。","in response to a set of cues","对一套提示作出反应"),daily:w("adj.","日常的","daily修饰cues，说明生活中反复出现的提示。","daily cues","日常提示")},
"2010-p3-s3":{
be:w("v.","存在；有","are与There组成存在句，后接复数实义主语problems。","There are problems","存在一些问题"),public:w("adj.","公共的","public修饰health，组成公共卫生领域，不是公开辩护者。","public health problems","公共卫生问题"),health:w("n.","卫生；健康","health在public health中为卫生领域，再限定problems。","public health","公共卫生"),problem:w("n.","问题","problems指卫生问题，同时是关系词that的先行词。","problems that remain killers","仍然致命的问题"),like:w("prep.","例如","like举出脏手而未形成肥皂洗手习惯的例子。","problems, like dirty hands","例如脏手这样的公共卫生问题"),hand:w("n.","手","hands为身体部位，由dirty修饰，不能套用in safe hands负责之义。","dirty hands","脏手"),of:w("prep.","引出替代项或所属","instead of连接脏手与好习惯的对照；director of说明中心主任，School of给院校学科名。","instead of a soap habit; the director of the Hygiene Center","而非肥皂洗手习惯；卫生中心主任"),that:w("关系代词","回指卫生问题","that回指problems，作remain的主语；不是引出不充当成分的内容。","problems that remain killers","仍是致命因素的问题"),remain:w("linking v.","仍然是","remain接killers为名词表语，说明问题仍然致命。","remain killers","仍是致命因素"),only:w("adv.","仅仅","only强调because给出的原因；没有only if条件结构。","only because we can't figure out how to change habits","仅仅因为弄不清如何改变习惯"),because:w("conj.","因为","because引出的原因从句嵌在that关系从句中，解释问题为何仍致命。","remain killers because ...","因为……仍然致命"),we:w("pron.","我们","we指Curtis所代表的公共卫生研究和实践者。","we can't figure out how to change habits","我们弄不清如何改变习惯"),can:w("modal v.","能够","can't是否定形式，整组表示不能弄清；不能只显示肯定能力而漏掉否定。","can't figure out","不能弄清楚"),out:w("particle","构成弄清之义的小品词","out与figure形成figure out，后接how不定式内容，不是空间外面。","figure out how to do something","弄清怎样做某事"),how:w("疑问副词","怎样","how to change为疑问不定式宾语，没有how important感叹结构。","how to change people's habits","怎样改变人们的习惯"),to:w("不定式标记","引出改变动作","to后接change原形，整体how to change作figure out宾语。","how to change something","怎样改变某事"),say:w("v.","说","said为引语后倒装报道的谓语，主语Dr. Curtis；没有were said被动。","said Dr. Curtis","柯蒂斯博士说"),director:w("n.","主任","the director of the Hygiene Center解释Curtis的身份，不是director general职衔。","the director of the Hygiene Center","卫生中心主任"),at:w("prep.","在；隶属于","at引中心所在院校，挂到Hygiene Center，不修饰said的方式。","the Hygiene Center at the London School","该学院的卫生中心"),london:w("专名","伦敦","London属于院校名称London School，不是in London地点状语。","the London School of Hygiene & Tropical Medicine","伦敦卫生与热带医学院"),school:w("n.","学院","School是院校专名的组成部分。","School of Hygiene & Tropical Medicine","卫生与热带医学院")},
"2010-p3-s4":{
we:w("pron.","我们","延续Curtis的引语，指研究者一方，不是公司自述。","We wanted to learn","我们想学习"),to:w("不定式标记","引出学习或培养动作","to learn作wanted宾语，how to create作learn宾语，两层不定式不能混成两个主句。","want to learn how to create something","想学习如何培养某事物"),from:w("prep.","向；从","from private industry说明向哪一方学习。","learn from private industry","向企业界学习"),industry:w("n.","企业界","private industry指私营商业部门，不限于重工业。","private industry","私营企业界"),private:w("adj.","私营的","private修饰industry，区别31D中私人事务的private。","private industry","私营企业界"),how:w("疑问副词","怎样","how引出培养行为的方法，是learn的学习内容。","learn how to create new behaviors","学习怎样培养新行为"),create:w("v.","培养；建立","create接new behaviors，不是造成压力。","create new behaviors","培养新行为"),new:w("adj.","新的","new修饰behaviors，指希望建立的新习惯性行为。","new behaviors","新行为"),that:w("关系代词","回指行为","that回指behaviors，作happen的主语。","behaviors that happen automatically","会自动发生的行为"),happen:w("v.","发生","happen是不及物动词，automatically为方式状语。","happen automatically","自动发生")},
"2010-p3-s5":{
that:w("关系代词","回指公司或提示","第一处that是to的宾语，回指companies；第二处是use的宾语，回指cues。","companies that Curtis turned to; cues that corporations could use","博士求助的公司；企业能够利用的提示"),turn:w("v.","求助；转向","turned to后介词宾语由关系词that回指companies，没有in turn结构。","turn to a company","向公司求助"),to:w("介词/不定式标记","引出求助对象或用途","turned to中的to是介词，to introduce中的to是不定式标记。","turn to somebody; to introduce new routines","向某人求助；为了引入新惯例"),have:w("aux.","标记过去完成时","had invested表示企业此前已投入资金。","had invested money finding cues","此前已投入资金寻找提示"),of:w("prep.","引出数量范围","hundreds of millions of dollars把百与百万、货币单位组成概数。","hundreds of millions of dollars","数亿美元"),in:w("prep.","在……中","in consumers' lives限定提示出现的生活场景。","cues in consumers' lives","消费者生活中的提示"),corporation:w("n.","公司；企业","corporations是could use的主语，指使用提示培养惯例的企业。","corporations could use cues","企业可以使用提示"),use:w("v.","利用","could use的宾语由that前置，to introduce说明利用提示的目的。","use cues to introduce new routines","利用提示引入新惯例"),introduce:w("v.","引入","introduce直接接new routines，执行者为corporations。","introduce new routines","引入新的日常程序"),new:w("adj.","新的","new修饰routines，不是与positive并列修饰forces。","new routines","新的日常程序")},
"2010-p3-s6":{
look:w("v.","观察","look hard enough是仔细观察，look不是系动词看起来。","look hard enough","观察得足够仔细"),that:w("conj.","引出所发现的内容","that引宾语从句，不在从句中充当products的主语或宾语。","find that products are results of manufactured habits","发现产品是人为习惯的产物"),many:w("pron.","许多","many of限定所列产品中的许多种，而非全部。","many of the products","这些产品中的许多种"),of:w("prep.","引出范围或来源","many of限定产品范围；results of说明结果源于人为习惯。","many of the products; results of manufactured habits","许多产品；人为习惯的产物"),we:w("pron.","我们","we泛指日常使用这些产品的人，作use的主语。","products we use every day","我们每天使用的产品"),every:w("det.","每一","every与单数day组成每日时间状语，不表示数量比例。","every day","每天"),day:w("n.","天","every day修饰use，说明日常重复使用。","use every day","每天使用"),health:w("n.作定语","健康","health限定snacks，指作为健康类产品推广的零食。","health snacks","健康零食"),be:w("linking v.","是","are连接many of the products与表语results，不是被动。","products are results","产品是产物")},
"2010-p3-s7":{
few:w("det.","很少","few people带否定数量意味，区别a few所说的有一些。","few people regularly brushed their teeth","很少有人有规律地刷牙"),people:w("n.","人们","people为复数名词，作brushed主语，不指某个特定person。","few people","很少有人"),their:w("possessive det.","他们的","their回指people，限定自己的牙齿。","their teeth","他们的牙齿"),a:w("art.","一；每一","A century表示一个世纪；times a day中的a表示每一天。","a century; multiple times a day","一个世纪；每天多次"),day:w("n.","天","a day用作频率基准，非two days after时间差。","multiple times a day","每天多次")},
"2010-p3-s8":{
because:w("复合介词组成部分","因为","because与of组成复合介词，接广告和卫生宣传两项名词，不独立引从句。","because of advertising and campaigns","因为广告和宣传活动"),of:w("prep.","引出原因或范围","because of整体表原因；one of the other brands中of限定选择范围。","because of advertising; one of the other brands","因为广告；其他品牌中的一种"),and:w("conj.","和","and连接advertising与public health campaigns两个并列原因。","advertising and public health campaigns","广告和公共卫生宣传"),public:w("adj.","公共的","public修饰health，整体限定卫生宣传。","public health campaigns","公共卫生宣传活动"),health:w("n.","卫生；健康","public health整体说明campaigns所属领域。","public health campaigns","公共卫生宣传活动"),american:w("n.","美国人","many Americans是give主语，没有在回答企业所有权。","many Americans habitually give ... a scrub","许多美国人习惯性地清洁……"),their:w("possessive det.","他们的","their回指many Americans，限定牙齿。","their pearly whites","他们自己的牙齿"),with:w("prep.","用","with作为工具介词，引出刷牙使用的产品品牌，没有with+宾语+doing复合结构。","with Colgate, Crest or another brand","用高露洁、佳洁士或别的品牌产品"),one:w("pron.","一种","one of the other brands意为其他品牌中的一种，并非替代学术团体。","one of the other brands","其他品牌中的一种"),a:w("art.","一次；每一","a scrub为一次刷洗；twice a day中的a表示每。","a scrub twice a day","每天刷洗两次"),day:w("n.","天","twice a day作为频率状语修饰清洁牙齿。","twice a day","每天两次")},
"2010-p3-s9":{
few:w("det.","几个","a few整体表示一些，限定decades；不是few people的否定数量。","a few decades ago","几十年前"),people:w("n.","人们","many people作didn't drink主语，指当时许多人。","many people didn't drink water outside of a meal","许多人用餐之外不喝水"),do:w("aux.","构成过去时否定","didn't是did not，承担过去时和否定，drink保持原形；do不译做。","didn't drink water","过去不喝水"),of:w("复合介词组成部分","引出范围","outside of后接a meal表示用餐时间之外。","outside of a meal","用餐以外的时段"),decade:w("n.","十年","a few decades表示若干个十年，不能误读为几年或几个世纪。","a few decades ago","几十年前")},
"2010-p3-s10":{
then:w("adv.","后来","Then引出企业开始装瓶销售这一后续行动，不连接两个不定式。","Then companies started bottling water","后来企业开始将水装瓶"),of:w("prep.","引出产物来源","of far-off springs说明production来自遥远泉眼。","the production of far-off springs","远方泉眼的产出"),and:w("conj.","而且；而","and连接企业started与职员sip两套主谓，包含过去与如今的对照。","companies started ... and now workers sip ...","企业开始……而如今职员喝……"),now:w("adv.","如今","now修饰sip，以文中当时为参照，与Then对照。","now office workers sip bottled water","如今职员喝瓶装水"),worker:w("n.","职员；工作人员","office workers为办公室职员，作sip主语。","office workers","办公室职员"),all:w("det.","整个","all限定单数day，long加强整天持续之意。","all day long","一整天"),day:w("n.","天","all day long为持续时间状语，不是每天的频率。","sip water all day long","整天小口喝水")},
"2010-p3-s11":{
once:w("adv.","曾经","once修饰bought，不是一旦引导条件从句。","once bought primarily by boys","曾主要由男孩购买"),buy:w("v.（过去分词）","购买","bought修饰gum并有被动关系，指买口香糖，不是收购企业。","gum bought by adolescent boys","由青春期男孩购买的口香糖"),be:w("aux.","构成被动","is与featured构成现在时被动，now为中间时间状语。","is now featured in commercials","如今在广告中被重点展示"),now:w("adv.","如今","now限定广告定位，和once限定的旧购买情况对照。","is now featured","如今被重点展示"),in:w("prep.","在……中","in commercials说明宣传呈现的载体。","in commercials","在广告片中"),commercial:w("n.","广告片","commercials是复数名词，作in宾语，区别34C中的commercial形容词。","in commercials","在广告片中"),as:w("prep.","作为","as后接两项产品用途，给出广告赋予的定位，没有As时间从句。","as a breath freshener and teeth cleanser","作为清新口气和清洁牙齿的用品"),and:w("conj.","和","and并列freshener与cleanser两种用途。","a breath freshener and teeth cleanser","清新口气用品和牙齿清洁用品"),for:w("prep.","供；用于","for use表示供使用，use为名词，不是不定式。","for use after a meal","供饭后使用"),use:w("n.","使用","use为for后名词，after a meal限定使用时间。","for use after a meal","供饭后使用"),after:w("prep.","在……之后","after接名词a meal，限定使用时间，没有时间从句。","after a meal","饭后")},
"2010-p3-s12":{
be:w("aux.","构成被动","are advertised说明润肤品被宣传为日常美容一部分。","are advertised as part of a ritual","被宣传成日常程序的一部分"),as:w("prep.","作为","as part of给出广告定位，不是随着引导从句。","as part of morning beauty rituals","作为晨间美容程序的一部分"),of:w("prep.","引出整体","of说明part所属的整体，即morning beauty rituals。","part of morning beauty rituals","晨间美容程序的一部分"),in:w("particle","表示加入的小品词","in与slipped构成slip in悄然插入；后面between说明插入哪两个活动之间。","slipped in between A and B","被悄然插入A与B之间"),brush:w("n./动名词","梳理","hair brushing是梳理头发的活动，与化妆平行；单词义不吞并hair的含义。","hair brushing","梳理头发"),and:w("conj.","和","and连接between的两个平行活动，而非连接两个主句。","between hair brushing and putting on makeup","在梳头和化妆之间"),on:w("particle","表示施用的小品词","on属于put on，put on makeup整体表示化妆；不单独译作涂上。","put on makeup","化妆")},
"2010-p3-s13":{
our:w("possessive det.","我们的","our为Berning企业一方的自称，不是作者或美国全体企业。","Our products succeed","我们的产品取得成功"),succeed:w("v.","成功","succeed以products为主语，when从句给出商业成功的条件。","products succeed when they become part of routines","产品融入惯例时成功"),when:w("conj.","当……时","when兼有成功条件意味，引出产品融入日常程序；不是美国历史背景。","when they become part of patterns","当产品成为惯例的一部分时"),become:w("linking v.","成为","become接名词part为表语，不是商业化分词。","become part of daily or weekly patterns","成为每天或每周惯例的一部分"),part:w("n.","部分","part作become的表语，of说明生活惯例整体。","part of daily or weekly patterns","每天或每周惯例的一部分"),of:w("prep.","引出整体或金额涉及的商品","part of说明整体；$76 billion of给出相应金额的商品内容。","part of patterns; $76 billion of products","惯例的一部分；价值760亿美元的产品"),daily:w("adj.","每天的","daily与weekly并列修饰patterns，说明行为周期。","daily or weekly patterns","每天或每周的惯例"),pattern:w("n.","模式；惯例","patterns指消费者每日或每周的重复行为，不是美国工业模式。","daily or weekly patterns","每天或每周的惯例"),say:w("v.","说","said引出Berning的直接引语，后置主语为Carol Berning。","said Carol Berning","卡罗尔·伯宁说"),who:w("关系代词","回指心理学家","who回指psychologist，在关系从句中作retired主语。","a psychologist who recently retired","一位最近退休的心理学家"),from:w("prep.","从","from接退休前的工作单位Procter & Gamble。","retire from Procter & Gamble","从宝洁退休"),that:w("关系代词","回指公司","that回指company即宝洁，作sold的主语，不能指Berning。","the company that sold products","销售产品的公司"),and:w("conj.","和","and连接Tide、Crest与other products的商品列举。","Tide, Crest and other products","汰渍、佳洁士和其他产品"),last:w("adj.","上一的","last year限定sold，相对于原文写作时点的上一年。","last year","上一年"),year:w("n.","年","last year是销售发生时间，不表示连续五年增长。","sold products last year","上一年销售产品")},
"2010-p3-s14":{
create:w("v.-ing","培养","Creating positive habits为动名词主语，后接单数is。","Creating positive habits is ...","培养积极习惯是……"),positive:w("adj.","积极的；有益的","positive修饰habits，属于企业受访者对习惯的评价，不是数字鸿沟。","positive habits","积极有益的习惯"),be:w("linking v.","是","第一处is接名词表语part；it's中的is接形容词表语essential。","Creating habits is a part; it's essential","培养习惯是一部分；这至关重要"),huge:w("adj.","重大的","huge修饰part，表示重要程度，不是行业规模。","a huge part","一个重要部分"),part:w("n.","部分；环节","of improving说明所属的整体活动是改善消费者生活。","part of improving consumers' lives","改善消费者生活的一部分"),of:w("prep.","引出整体活动","of后接动名词improving及其宾语。","part of improving lives","改善生活的一部分"),our:w("possessive det.","我们的","our指企业一方，限定consumers，再由消费者所有格限定lives。","our consumers' lives","我们的消费者的生活"),and:w("conj.","而且","and连接培养习惯是改善生活一部分、又是商业生存关键两项判断。","Creating habits is ... and it's essential ...","培养习惯是……而且它至关重要……"),it:w("pron.","培养积极习惯这件事","it's为it is，it回指Creating positive habits，是有具体指代的主语，不是形式主语。","it's essential to making products viable","培养习惯对使产品可行至关重要"),essential:w("adj.","必不可少的","essential接to介词短语，表示对商业生存的重要性。","be essential to doing something","对做某事至关重要"),to:w("prep.","对于","essential to中的to为介词，后接making动名词。","essential to making products viable","对使产品可行至关重要"),new:w("adj.","新的","new只修饰products，commercially修饰viable。","new products","新产品")},
"2010-p3-s15":{
through:w("prep.","通过；借助","句首through修饰have learned，说明研究依据；末尾through修饰tying，说明广告手段。","through experiments; through advertising","通过实验；借助广告"),and:w("conj.","和","and连接experiments与observation两个研究依据。","experiments and observation","实验和观察"),social:w("adj.","社会的","social限定scientists所属学科，整体为社会科学家。","social scientists","社会科学家"),scientist:w("n.","科学家","social scientists作have learned主语，like以Berning举例。","social scientists like Dr. Berning","伯宁博士这样的社会科学家"),like:w("prep.","例如；像……这样的","like引出Berning作为社会科学家的例子，不是动词喜欢。","scientists like Dr. Berning","伯宁博士这样的科学家"),have:w("aux.","标记现在完成时","have learned表示已通过研究了解到。","have learned that ...","已经了解到……"),that:w("conj.","引出发现内容","that引宾语从句，内部there为存在句引导成分、power为实义主语。","have learned that there is power","已了解到存在效力"),be:w("v.","存在；有","is与there组成存在句，后接不可数power。","there is power in doing something","做某事具有影响力"),in:w("prep.","在……中","in tying说明力量或效力存在于什么机制中。","power in tying A to B","把A与B绑定的效力"),to:w("prep.","引出关联对象","tie A to B中的to接habitual cues，不是不定式。","tie behaviors to habitual cues","把行为与习惯性提示关联"),certain:w("det./adj.","某些特定的","certain限定behaviors，不表示研究者确信。","certain behaviors","某些特定行为"),advertising:w("n.","广告宣传","advertising为through的名词宾语，ruthless给出负面评价；本句不与campaigns并列。","through ruthless advertising","借助不顾后果的广告")},
"2010-p3-s16":{
as:w("conj.","随着","As引新学科兴起的时间背景，不是产品定位as，也不是拍卖师动作。","As the science has emerged","随着该学科兴起"),this:w("det.","这一","this限定science，承接前文习惯形成机制的研究。","this new science of habit","这门新的习惯科学"),new:w("adj.","新兴的","new修饰science，不是与positive并列。","new science of habit","新兴的习惯科学"),science:w("n.","科学；学科","science of habit指研究习惯的新学科，of限定研究内容。","the science of habit","习惯科学"),of:w("prep.","关于","of habit限定science研究的对象。","science of habit","关于习惯的科学"),have:w("aux.","标记现在完成时","has emerged、have erupted、have been used都是完成时；第三处还含被动。","has emerged; have erupted; have been used","已经兴起；已经爆发；已经被使用"),when:w("conj.","当……时","when限定策略被用于问题商品时争议出现的情形。","when tactics have been used to sell questionable products","当策略被用来销售问题产品时"),be:w("aux.（过去分词）","构成被动","been是be过去分词，与have及used组成完成时被动。","have been used to sell","已经被用来销售"),to:w("不定式标记","引出用途","to sell说明使用策略的目的，不是习惯于doing。","be used to sell products","被用来销售产品")},
};
const q=(n:number,k:string,entries:Record<string,Seed>)=>{sources[`question-2010${n}-${k==="prompt"?"prompt":`option-${k}`}`]=entries;};
q(31,"prompt",{according:w("复合介词组成部分","根据","According与to组成观点来源结构，后接Dr. Curtis。","according to Dr. Curtis","根据柯蒂斯博士的观点"),to:w("prep.","引出观点来源","according to整体标示观点归属，不是不定式。","according to somebody","根据某人的观点"),like:w("prep.","例如","like举hand washing with soap作为习惯例子。","habits like hand washing with soap","用肥皂洗手这样的习惯"),hand:w("n.作定语","手","hand限定washing对象，整体为洗手。","hand washing","洗手"),with:w("prep.","用","with soap为洗手使用的材料，不是with+doing独立结构。","wash with soap","用肥皂清洗")});
q(31,"A",{should:w("modal v.","应该","should be cultivated表示应当被培养，不是虚拟感叹。","should be cultivated","应该得到培养"),be:w("aux.","构成被动","be后cultivated为过去分词，习惯是培养对象。","should be cultivated","应该被培养"),further:w("adv.","进一步","further修饰be cultivated的程度，不指空间更远。","be further cultivated","被进一步培养")});
q(31,"B",{should:w("modal v.","应该","should be changed对习惯提出改变要求，不能读成事实上已改变。","should be changed","应该被改变"),be:w("aux.","构成被动","be changed为被动，题干habits是改变对象。","be changed gradually","被逐渐改变"),change:w("v.（过去分词）","改变","changed与be组成被动，不是changing作定语。","be changed gradually","被逐渐改变")});
q(31,"C",{be:w("linking v./aux.","处于某种状态","are rooted表示植根的状态，deeply强化程度。","are deeply rooted in history","深深植根于历史"),deeply:w("adv.","深深地","deeply修饰rooted，不是unfashionable。","deeply rooted","深深扎根的"),in:w("prep.","在……中","in history引出根基所在，补足rooted。","rooted in history","植根于历史"),history:w("n.","历史","history为rooted in的根基领域，不是基础设施发展史。","rooted in history","植根于历史")});
q(31,"D",{be:w("linking v.","是；属于","are后接private concerns为名词表语。","are private concerns","属于私人事务"),private:w("adj.","私人的","private修饰concerns，区别正文private industry的私营。","private concerns","私人事务")});
q(32,"prompt",{be:w("aux.","构成被动","are mentioned为被动，三个产品是被作者提到的对象。","are mentioned in Paragraph 5","在第五段被提及"),mention:w("v.（过去分词）","提到","mentioned与are构成被动，题目问三产品举例目的。","are mentioned so as to ...","被提到是为了……"),in:w("prep.","在……中","in Paragraph 5定位第五段。","in Paragraph 5","在第五段"),paragraph:w("n.","段落","Paragraph 5是第五段，不是第一段。","Paragraph 5","第五段"),so:w("目的结构组成部分","引出目的","so与as to组成目的结构，后接原形动词。","so as to do something","为了做某事"),as:w("目的结构组成部分","引出目的","as属于so as to，不是身份介词或时间从句。","so as to reveal something","为了揭示某事"),to:w("不定式标记","引出目的动作","to后接选项原形动词，与so as组成目的表达。","so as to do something","为了做某事")});
q(32,"A",{reveal:w("v.","揭示","reveal接their impact为宾语，不是not simply A but also B结构。","reveal their impact on habits","揭示它们对习惯的影响"),their:w("possessive det.","它们的","their回指题干三种产品。","their impact","这些产品的影响"),impact:w("n.","影响","impact是reveal的宾语，on引影响对象。","impact on people's habits","对人们习惯的影响"),on:w("prep.","对","on people's habits说明impact的作用对象。","impact on habits","对习惯的影响")});
q(32,"B",{show:w("v.","表明","show直接接名词need作宾语，没有what从句。","show the urgent need","表明迫切需求"),need:w("n.","需求","need是名词，urgent修饰它，of引出日用品对象。","the urgent need of daily necessities","对日用品的迫切需求"),of:w("prep.","引出需求对象","of daily necessities限定need，不是所有格所属。","the need of daily necessities","对日用品的需求"),daily:w("adj.","日常的","daily修饰necessities，整体为日用品。","daily necessities","日用品")});
q(32,"C",{indicate:w("v.","表明","indicate接their effect名词宾语，表达举例目的，不是完形第8题。","indicate their effect","表明它们的影响"),their:w("possessive det.","它们的","their回指题干三种产品。","their effect","这些产品的影响"),effect:w("n.","影响","effect是indicate的宾语，on引出购买力这个受影响对象。","effect on buying power","对购买力的影响"),on:w("prep.","对","on补足effect，表示影响作用于购买力。","effect on people's buying power","对人们购买力的影响"),buy:w("v.-ing作定语","购买","buying限定power的能力类型，不是企业收购。","buying power","购买力"),power:w("n.","能力","power在buying power中为经济购买能力，区别正文there is power的机制效力。","people's buying power","人们的购买力")});
q(32,"D",{manifest:w("v.","显示；表明","manifest在此为原形及物动词，直接接role，不是be manifested被动。","manifest the significant role","显示重要作用"),significant:w("adj.","重要的","significant修饰role，不涉及监管幅度。","a significant role","重要作用"),of:w("prep.","引出作用主体","of good habits限定role，指良好习惯发挥的作用。","the role of good habits","良好习惯的作用")});
q(33,"prompt",{which:w("疑问代词","哪一个","Which of the following作疑问主语，不是关系代词回指物品。","Which of the following does not belong ...?","下列哪一项不属于……？"),of:w("prep.","引出选择范围","of the following限定Which的候选范围。","Which of the following","下列哪一项"),follow:w("名词化形容词","下列各项","the following指随后列出的选项，不是跟随动作。","of the following","在下列各项中"),do:w("aux.","构成疑问与否定","does与NOT配合，belong保留原形；do没有实义动作。","does NOT belong to","不属于"),to:w("prep.","引出归属类别","belong to接products名词，不是不定式。","belong to products","属于产品"),that:w("关系代词","回指产品","that作help的主语，回指products。","products that help create habits","有助形成习惯的产品"),help:w("v.","有助于","help接省to不定式create，没有companies宾语。","help create people's habits","帮助形成人们的习惯"),create:w("v.","形成；培养","create接people's habits，补足help的具体动作。","help create habits","有助形成习惯")});
q(33,"A",{tide:w("专名","汰渍","本文指产品品牌，不按潮汐普通义解释。","Tide products","汰渍产品")});q(33,"B",{crest:w("专名","佳洁士","本文为牙膏品牌，不按山脊普通义解释。","Crest toothpaste","佳洁士牙膏")});q(33,"C",{colgate:w("专名","高露洁","此项是牙膏品牌，区别公司全称Colgate-Palmolive。","Colgate toothpaste","高露洁牙膏")});q(33,"D",{unilever:w("专名","联合利华","文中属于companies名单，不是具体产品品牌。","Unilever company","联合利华公司")});
q(34,"prompt",{from:w("prep.","根据","From the text引出判断依据，不是来自海外竞争。","From the text we know","根据本文可知"),we:w("pron.","我们","we泛指读者，作know主语。","we know that ...","我们知道……"),know:w("v.","知道","know后接that陈述内容，不是where间接疑问。","know that habits are developed","知道习惯被培养形成"),that:w("conj.","引出所知内容","that引宾语从句，不在内部充当主宾语。","know that some habits are developed","知道一些习惯被形成"),some:w("pron.","一些；一部分","some of限定消费者习惯中的一部分，不能扩成全部。","some of consumers' habits","消费者的一些习惯"),of:w("prep.","引出部分所涉范围","some of后接消费者习惯，限制数量范围。","some of consumers' habits","消费者习惯中的一部分"),be:w("aux.","构成被动","are developed为现在时被动，habits是被培养对象。","habits are developed","习惯被培养形成"),due:w("复合介词组成部分","引出原因","due与to组成due to，后接原因名词；不是到期或预定。","due to commercial promotions","由于商业推广"),to:w("prep.","引出原因对象","to属于due to，后接选项名词短语，不是不定式。","due to something","由于某原因")});
q(34,"A",{perfect:w("过去分词作定语","完善的","perfected修饰art，区别首句had perfected的谓语过去分词。","perfected art","完善的技艺"),art:w("n.","技艺；手法","art是名词中心，选项以of products限定；不可替选项补回原文of creating behaviors。","art of products","产品的技艺"),of:w("prep.","引出所属对象","of products把art归于产品，是选项实际限定。","art of products","产品的技艺")});
q(34,"B",{automatic:w("adj.","自动的","automatic先修饰behavior，不直接修饰creation的方式。","automatic behavior creation","自动行为的形成"),behavior:w("n.作定语","行为","behavior作为creation前置限定，说明形成什么。","behavior creation","行为的形成")});
q(34,"C",{commercial:w("adj.","商业的","commercial修饰promotions，区别正文commercials广告片名词。","commercial promotions","商业推广"),promotion:w("n.","推广","promotion由commercial限定为商业推广，不能把整个短语义全塞给单词。","commercial promotions","商业推广")});
q(34,"D",{scientific:w("adj.","科学的","scientific限定experiments性质，而不是科学共同体等别篇搭配。","scientific experiments","科学实验")});
q(35,"prompt",{author:w("n.","作者","author's为所有格，限定attitude；这里问作者态度而非企业受访者意见。","the author's attitude","作者的态度"),toward:w("prep.","对于","toward引出attitude所针对的影响，不是朝向或时间接近。","attitude toward the influence","对该影响的态度"),influence:w("n.","影响","influence是toward的名词宾语，of说明来源，on说明作用对象。","the influence of advertisement on habits","广告对习惯的影响"),of:w("prep.","引出影响来源","of advertisement说明影响来自广告。","the influence of advertisement","广告的影响"),on:w("prep.","对","on people's habits说明影响作用于习惯。","influence on people's habits","对人们习惯的影响"),be:w("linking v.","是","is连接单数attitude与待选形容词表语。","the attitude is negative","态度是否定的")});
q(35,"A",{indifferent:w("adj.","漠不关心的","作is后态度表语；不是认真分析后的中立。","an indifferent attitude","漠不关心的态度")});q(35,"B",{negative:w("adj.","负面的；否定的","作态度表语，表示批评方向，不额外断言偏见。","a negative attitude","负面态度")});q(35,"C",{positive:w("adj.","正面的；肯定的","作态度表语，不是修饰别篇forces；本题要区分作者与企业引语。","a positive attitude","正面态度")});q(35,"D",{biased:w("adj.","有偏见的","作态度表语，表示有失公正，含义不同于negative。","a biased attitude","带偏见的态度")});
// 词汇优先搭配涉及的透明词仍保留完整语境，不仅挂一个按钮。
Object.assign(sources["2010-p3-s1"], { many:w("det.","许多","many限定复数companies，表示企业数量多。","many companies","许多企业") });
Object.assign(sources["2010-p3-s3"], { there:w("存在句引导词","引出存在的事物","there不指地点，There are后接卫生问题。","There are public health problems","存在公共卫生问题") });
Object.assign(sources["2010-p3-s7"], { ago:w("adv.","以前","ago接在a century后，向原文叙述当时回溯一百年。","a century ago","一百年前") });
Object.assign(sources["2010-p3-s8"], { many:w("det.","许多","many限定Americans，未扩大为所有美国人。","many Americans","许多美国人") });
Object.assign(sources["2010-p3-s9"], { many:w("det.","许多","many限定people，表示当时许多人具有所述饮水习惯。","many people","许多人"),ago:w("adv.","以前","ago接在a few decades后，表示几十年前。","a few decades ago","几十年前") });
Object.assign(sources["2010-p3-s12"], { between:w("prep.","在……之间","between连接梳头和化妆两个平行活动，说明程序位置。","between hair brushing and putting on makeup","在梳头与化妆之间") });
Object.assign(sources["2010-p3-s15"], { there:w("存在句引导词","引出存在的事物","there is power指出该绑定机制确有影响力，不是地点那里。","there is power in doing something","做某事确有效力"),learn:w("v.","了解到","learned后接that内容，through experiments解释获得认识的依据。","have learned that there is power","已经了解到该机制有效") });
export const passage2010P3ReviewedContexts:Record<string,Record<string,SentenceWordContext>>=Object.fromEntries(Object.entries(sources).map(([source,words])=>[source,Object.fromEntries(Object.entries(words).map(([headword,value])=>[headword,{partOfSpeech:value.partOfSpeech,contextualMeaning:value.contextualMeaning,use:value.use}]))]));
export function getPassage2010P3WordKnowledge(headword:string,sourceId?:string):WordKnowledge|undefined{return sourceId?sources[sourceId]?.[headword]?.knowledge:undefined;}
