import type {SentenceWordContext} from "./contextual-vocabulary";
import type {WordKnowledge} from "./knowledge-base";
type Seed=SentenceWordContext&{knowledge:WordKnowledge};
const w=(partOfSpeech:string,contextualMeaning:string,use:string,pattern:string,meaning:string):Seed=>({partOfSpeech,contextualMeaning,use,knowledge:{grammarRole:partOfSpeech,grammarSummary:use,structures:[{pattern,meaning,rule:use}]}});
const sources:Record<string,Record<string,Seed>>={
"2010-translation-s1":{
have:w("aux. / v.","标记完成时；具有","has与become构成完成时；后面的have为实义动词，接personal meaning。","has become; will always have personal meaning","已经成为；始终将有切身意义"),a:w("art.","一个","a限定可数名词word，与popular构成表语。","a popular word","一个流行词"),these:w("det.","这些","these与复数days组合，整体表示近来。","these days","如今；近来"),to:w("prep.","对……而言","to Ted Ning限定后句观点的感受者。","to Ted Ning","对特德·宁而言"),ning:w("proper n.","宁（姓氏）","Ted Ning为人名，to引出他的个人视角。","to Ted Ning","对特德·宁而言"),the:w("art.","这个","the concept回指本句开头的Sustainability。","the concept","这个概念"),always:w("adv.","始终","always修饰have，强调个人意义持续存在。","will always have personal meaning","始终会有切身意义")},
"2010-translation-s2":{
have:w("aux.（动名词形式）","标记已完成","Having加过去分词endured构成完成式动名词，整个经历短语作made主语。","Having endured a painful period","曾经历一段痛苦时期"),a:w("art.","一段","a限定可数名词period，painful说明时期感受。","a painful period","一段痛苦时期"),of:w("prep.","处于……状态","of unsustainability后置限定period，说明时期的状态。","a painful period of unsustainability","一段生活难以为继的痛苦时期"),in:w("prep.","在……中","in his own life说明经历发生于宁的个人生活。","in his own life","在他自己的生活中"),it:w("形式代词","形式宾语","it先占宾语位置，后置that从句说明真正内容；不回指主语中的经历。","make it clear (to somebody) that + clause","使他清楚地认识到……"),to:w("prep.","对……而言","to him说明clear的感受者为宁。","clear to him","对他而言清楚"),that:w("conj.","引出宾语内容","that引后置真正宾语，补足形式宾语it，不作从句内部成分。","made it clear to him that values must be expressed","使他明白价值观必须得到体现"),be:w("aux.","构成被动","be接过去分词expressed，与must组成情态被动。","must be expressed","必须得到体现"),through:w("prep.","通过","through引价值观得以体现的实践途径。","through everyday action and choice","通过日常行动和选择"),and:w("conj.","和","and连接action与choice两个并列介词宾语，everyday共同限定日常实践。","everyday action and choice","日常行动和选择")},
"2010-translation-s3":{
ning:w("proper n.","宁（姓氏）","Ning为主语，recalls接对过去卖保险经历的回忆。","Ning recalls spending","宁回忆曾花费"),a:w("art.","一","a限定year，是spending所花的时间。","a confusing year","令人困惑的一年"),in:w("prep.","在……时","in the late 1990s限定卖保险的发生时间，不限定现在的recalls。","in the late 1990s","在20世纪90年代末"),the:w("art.","特定年代标记","the与late 1990s构成年代后期表达。","the late 1990s","20世纪90年代末"),"1990s":w("年代表达","1990—1999年这一年代","年代数字与s为完整词形，late进一步限定这一年代后期。","in the late 1990s","在20世纪90年代末")},
"2010-translation-s4":{
"he'd":w("pron. + aux.","他已……","He'd为He had，后接been所以不能展开为would。","He'd been through","他已经历过"),be:w("v.（过去分词）","经历（搭配中）","been与had构成过去完成时，through后接兴衰经历。","been through the dot-com boom and burst","经历过互联网行业兴衰"),through:w("prep.","历经（搭配中）","be through整体表示经历，后接boom与burst。","through the dot-com boom and burst","经历互联网行业繁荣与泡沫破裂"),the:w("art.","特指这轮","the共同限定dot-com boom and burst两个并列名词。","the dot-com boom and burst","互联网行业的繁荣与泡沫破裂"),and:w("conj.","和；并且","第一处and连接boom和burst，第二处连接经历与签约两个谓语部分。","boom and burst; been through ... and signed on","繁荣与破裂；经历并签约"),a:w("art.","一份；一家","a分别限定job与Boulder agency：谋生机会及实际签约机构。","a job; a Boulder agency","一份工作；博尔德一家机构"),job:w("n.","工作；职位","a job泛指宁急需的谋生机会，是for的宾语。","desperate for a job","急需工作"),on:w("动词短语小品词","加入（搭配中）","on与signed组成签约加入，再由with引出机构。","signed on with a Boulder agency","与博尔德一家机构签约")},
"2010-translation-s5":{
it:w("pron.","这份工作的开展情况","It回指卖保险工作的开展情况，是有实义指代的主语。","It didn't go well","这份工作进展不顺利"),do:w("aux.（否定缩写）","没有（助动词否定）","didn't展开为did not，承载过去时，后面go用原形。","didn't go well","进展不顺利")},
"2010-translation-s6":{
it:w("pron.","这个决定","It回指接受保险工作的选择，是was的主语。","It was a really bad move","这个决定实在很糟"),be:w("linking v.（过去式）","是","was连接It与名词表语a really bad move。","was a really bad move","是个糟糕决定"),a:w("art.","一个；一项","两处a分别限定move和lack，后者整体表示销售不足。","a really bad move; a lack of sales","糟糕决定；销售不足"),"that's":w("pron. + linking v.","那是","that回指卖保险，is连接表语my passion，not否定该判断。","that's not my passion","那不是我热爱的事情"),say:w("v.（第三人称单数）","说","says的主语Ning放在动词之后，前置引语为说话内容。","says Ning","宁说"),ning:w("proper n.","宁（姓氏）","Ning是says的后置主语，又被whose从句补充。","says Ning, whose dilemma","宁说，他的两难"),whose:w("relative det.","他的","whose以Ning为先行词，在关系从句中限定dilemma，whose本身不是完整主语。","whose dilemma about the job","他在工作上的两难"),the:w("art.","这份","the job回指前文已经签约的保险工作。","the job","这份工作"),job:w("n.","工作","about the job限定dilemma，说明两难涉及的事项。","dilemma about the job","工作方面的两难"),of:w("prep.","所缺少的对象","of sales限定名词lack，指销售不足。","a lack of sales","销售不足"),into:w("prep.","成为（结果）","into引出translated造成或表现出的结果，不表空间进入。","translated, predictably, into a lack of sales","不出所料地表现为销售不足")},
"2010-translation-s7":{
i:w("pron.","我","I指正在直接引语中自述的宁。","I was miserable","我当时很痛苦"),be:w("linking v.（过去式）","处于某状态","was接形容词miserable作表语，说明当时心情。","was miserable","当时很痛苦")},
"2010-translation-s8":{
i:w("pron.","我","两处I都指宁，分别作主句和that结果从句主语。","I had ... that I would wake up","我如此焦虑以至于常会醒来"),have:w("v.（过去式）","有；感到","had为实义动词，接so much anxiety；后面没有构成完成时的过去分词。","had so much anxiety","感到如此强烈的焦虑"),that:w("conj.","以至于（结果）","that与so much呼应，引出结果从句，说明焦虑所造成的行为后果。","so much anxiety that I would wake up","焦虑得常会醒来"),would:w("modal v.","过去常常会","would与wake和stare两个原形共用，叙述过去反复行为。","would wake up ... and stare","过去常常醒来并凝视"),up:w("动词短语小品词","醒来（搭配中）","up是wake up中的小品词；wake up在此为不及物的醒来。","wake up","醒来"),in:w("prep.","在（某一时段）","in引出wake up的时间状语，范围为半夜。","in the middle of the night","在半夜"),of:w("prep.","……的","of the night限定middle，说明夜晚的中间时段。","the middle of the night","夜半"),the:w("art.","特定对象标记","三处the分别限定middle、night、ceiling；最后一处为当时房间里可辨认的天花板。","the middle of the night; the ceiling","半夜；天花板"),and:w("conj.","并且","连接wake up与stare，共用结果从句主语I和would。","wake up in the middle of the night and stare at the ceiling","半夜醒来并盯着天花板")},
"2010-translation-s9":{
i:w("pron.","我","I指宁，是had与needed共享的主语。","I had no money and needed the job","我没有钱又需要工作"),have:w("v.（过去式）","拥有","had为实义动词，宾语no money含否定，不是完成时。","had no money","没有钱"),and:w("conj.","又；而且","and连接两个共享I的谓语部分，共同交代谋生压力。","had no money and needed the job","没钱又需要这份工作"),the:w("art.","这份","the job特指前文卖保险的工作，为needed宾语。","needed the job","需要这份工作"),job:w("n.","工作","宁虽不热爱卖保险，仍因谋生需要这份工作。","needed the job","需要这份工作")},
"2010-translation-s10":{
say:w("v.（过去式）","说；劝慰","Everyone为said主语，后接当时大家对宁说的原话。","Everyone said","大家说"),you:w("pron. + modal（you'll）","你将……","you'll为you will，you是劝慰者称呼宁，不是泛指读者。","you'll turn the corner","你会迎来转机"),the:w("art.","习语中的限定词","the corner为固定习语组成，在本句不指具体街角。","turn the corner","开始好转"),it:w("pron.","工作处境的发展","give it some time中it为间接宾语，指工作及处境的发展，不是形式宾语。","give it some time","给这件事一些时间")},
};
export const translation2010ReviewedContexts:Record<string,Record<string,SentenceWordContext>>=Object.fromEntries(Object.entries(sources).map(([source,words])=>[source,Object.fromEntries(Object.entries(words).map(([head,entry])=>[head,{partOfSpeech:entry.partOfSpeech,contextualMeaning:entry.contextualMeaning,use:entry.use}]))]));
export function getTranslation2010ReviewedKnowledge(head:string,sourceId?:string):WordKnowledge|undefined{return sourceId?sources[sourceId]?.[head]?.knowledge:undefined;}
