import type { Question, SentenceAnalysis } from "./data";

export const cloze2010Sentences: SentenceAnalysis[] = [
  {
    id: "2010-cloze-s1", number: 1,
    text: "The outbreak of swine flu that was first detected in Mexico was declared a global epidemic on June 11, 2009.",
    chunks: [
      { text: "The outbreak of swine flu", role: "subject" },
      { text: " that was first detected in Mexico", role: "modifier" },
      { text: " was declared", role: "predicate" },
      { text: " a global epidemic", role: "object" },
      { text: " on June 11, 2009.", role: "modifier" },
    ],
    trunk: "The outbreak of swine flu was declared a global epidemic.",
    layers: [
      { label: "主干", text: "The outbreak... was declared a global epidemic：这次疫情被宣布为全球性传染病" },
      { label: "疫情来源", text: "that was first detected in Mexico：该猪流感最初在墨西哥被发现" },
      { label: "宣布时间", text: "on June 11, 2009：2009 年 6 月 11 日" },
    ],
    grammar: [
      "that 引导限制性定语从句，修饰 swine flu；that 在从句中作主语，was detected 是被动语态。",
      "declare A B 的被动形式是 A be declared B，B 是主语补足语，说明 A 被宣布为什么。",
      "on + 具体日期构成时间状语，修饰 was declared。",
    ],
    beginnerSyntax: { components: [
      { text: "The outbreak of swine flu", form: "名词 + of 介词短语", function: "主句主语", modifies: "是 was declared 的承受者", explanation: "中心词是 outbreak；of swine flu 回答‘什么疫情的暴发’。" },
      { text: "that was first detected in Mexico", form: "that 引导的完整从句", function: "限制性定语从句", modifies: "修饰 swine flu", explanation: "先行词是猪流感；从句内部 that 作主语，was detected 表‘被发现’，in Mexico 是地点状语。" },
      { text: "was declared", form: "一般过去时被动语态", function: "主句谓语", modifies: "说明疫情被官方作出怎样的认定", explanation: "谁宣布并不重要，重点是疫情获得了什么官方定性。" },
      { text: "a global epidemic", form: "名词短语", function: "主语补足语", modifies: "补充说明 outbreak 被宣布为什么", explanation: "按 declare A B 理解：宣布 A 是 B；变被动后 B 仍说明 A 的身份。" },
      { text: "on June 11, 2009", form: "on + 具体日期", function: "时间状语", modifies: "修饰 was declared", explanation: "回答‘什么时候宣布’，具体某一天前使用 on。" },
    ], clauses: [
      { text: "that was first detected in Mexico", type: "限制性定语从句", marker: "that（指代 swine flu）", role: "修饰 swine flu，限定是哪一次猪流感", subject: "that（= swine flu）", predicate: "was first detected", objectOrComplement: "in Mexico（地点状语）", translationOrder: "先译先行词‘猪流感’，再补‘最初在墨西哥被发现的’。" },
    ] },
    literal: "最初在墨西哥被发现的猪流感疫情，于 2009 年 6 月 11 日被宣布为全球性传染病。",
    natural: "2009 年 6 月 11 日，最早在墨西哥发现的猪流感疫情被正式认定为全球性疫情。",
    logic: "交代事件、地点和官方定性，为下一句说明这是 41 年来首次全球认定提供背景。",
    phrases: ["the outbreak of swine flu", "was first detected in Mexico", "was declared a global epidemic", "on June 11, 2009"],
  },
  {
    id: "2010-cloze-s2", number: 2,
    text: "It is the first worldwide epidemic designated by the World Health Organization in 41 years.",
    testText: "It is the first worldwide epidemic ___(1) by the World Health Organization in 41 years.",
    chunks: [
      { text: "It", role: "subject" }, { text: " is", role: "predicate" },
      { text: " the first worldwide epidemic", role: "object" },
      { text: " designated by the World Health Organization", role: "modifier" },
      { text: " in 41 years.", role: "modifier" },
    ],
    trunk: "It is the first worldwide epidemic.",
    layers: [
      { label: "主干", text: "It is the first worldwide epidemic：这是首场全球性疫情" },
      { label: "谁认定", text: "designated by the World Health Organization：由世界卫生组织认定" },
      { label: "时间范围", text: "in 41 years：41 年来" },
    ],
    grammar: [
      "designated... 是过去分词短语，后置修饰 epidemic，相当于 which was designated...。",
      "designate A as B 表正式把 A 定为 B；本句省去 as B，因为 epidemic 已说明类别。",
      "the first... in 41 years 表‘41 年来第一次/首个……’，in 表覆盖的时间范围。",
    ],
    beginnerSyntax: { components: [
      { text: "It", form: "人称代词", function: "主语", modifies: "回指上一句的 swine flu outbreak", explanation: "这里不是形式主语，直接指这次猪流感疫情。" },
      { text: "is", form: "系动词一般现在时", function: "谓语", modifies: "连接 It 与身份说明", explanation: "is 后面不是动作宾语，而是说明这场疫情的历史地位。" },
      { text: "the first worldwide epidemic", form: "序数词 + 形容词 + 名词", function: "表语", modifies: "说明 It 是什么", explanation: "first 前用 the；worldwide 修饰 epidemic，表示范围遍及全球。" },
      { text: "designated by the World Health Organization", form: "过去分词短语", function: "后置定语", modifies: "修饰 epidemic", explanation: "哪一场疫情？由世界卫生组织正式认定的；by 引出认定者。" },
      { text: "in 41 years", form: "in + 时间长度", function: "时间范围状语", modifies: "限定 the first", explanation: "不是‘在第 41 年内’，而是‘过去 41 年中第一次’。" },
    ], clauses: [] },
    literal: "它是 41 年来第一场由世界卫生组织认定的全球性疫情。",
    natural: "这是世界卫生组织 41 年来首次将一种疫情认定为全球性疫情。",
    logic: "用 first 和 41 years 突出本次疫情的全球影响与历史罕见性。",
    phrases: ["the first worldwide epidemic", "designated by the World Health Organization", "in 41 years"],
    answerWords: ["designated"],
  },
  {
    id: "2010-cloze-s3", number: 3,
    text: "The heightened alert followed an emergency meeting with flu experts in Geneva that assembled after a sharp rise in cases in Australia, and rising numbers in Britain, Japan, Chile and elsewhere.",
    testText: "The heightened alert ___(2) an emergency meeting with flu experts in Geneva that assembled after a sharp rise in cases in Australia, and rising ___(3) in Britain, Japan, Chile and elsewhere.",
    chunks: [
      { text: "The heightened alert", role: "subject" }, { text: " followed", role: "predicate" },
      { text: " an emergency meeting with flu experts in Geneva", role: "object" },
      { text: " that assembled", role: "modifier" },
      { text: " after a sharp rise in cases in Australia, and rising numbers in Britain, Japan, Chile and elsewhere.", role: "modifier" },
    ],
    trunk: "The heightened alert followed an emergency meeting.",
    layers: [
      { label: "事件顺序", text: "The heightened alert followed an emergency meeting：提高警戒级别发生在紧急会议之后" },
      { label: "会议参与者与地点", text: "with flu experts in Geneva：会议在日内瓦举行，参与者是流感专家" },
      { label: "开会原因", text: "after a sharp rise... and rising numbers...：澳大利亚病例激增，英、日、智利等地病例数也在上升" },
    ],
    grammar: [
      "A followed B 表 A 在 B 之后发生；不要受中文顺序影响误判为 B 跟随 A。",
      "that assembled... 是定语从句；语义上指参加紧急会议的 flu experts 集合开会。",
      "a rise in cases 与 rising numbers 形成并列；numbers 指病例数量，amounts 不修饰可数病例。",
      "in Geneva 说明会议地点；in Australia / Britain... 说明病例发生地点。",
    ],
    beginnerSyntax: { components: [
      { text: "The heightened alert", form: "过去分词形容词 + 名词", function: "主句主语", modifies: "是 followed 的动作发出者", explanation: "heightened 表‘被提高的’，整组指提高后的警戒状态。" },
      { text: "followed", form: "及物动词过去式", function: "主句谓语", modifies: "说明警戒升级与会议的先后关系", explanation: "A followed B = A 发生在 B 后；先开会，后升级警戒。" },
      { text: "an emergency meeting", form: "名词短语", function: "主句宾语", modifies: "承受 followed 的关系", explanation: "警戒升级发生在什么之后？一次紧急会议之后。" },
      { text: "with flu experts", form: "with + 名词短语", function: "参与者后置说明", modifies: "修饰 meeting", explanation: "说明这是一次有流感专家参加的会议。" },
      { text: "in Geneva", form: "in + 地名", function: "地点状语", modifies: "修饰 meeting", explanation: "说明会议举行地点是日内瓦。" },
      { text: "that assembled after a sharp rise in cases in Australia, and rising numbers in Britain, Japan, Chile and elsewhere", form: "that 引导的完整从句", function: "限制性定语从句", modifies: "承接 flu experts/meeting，说明为何集合开会", explanation: "先抓 experts assembled：专家们集合；after 后面再解释病例上升这一触发背景。" },
      { text: "after a sharp rise in cases in Australia", form: "after + 名词短语", function: "时间兼原因背景状语", modifies: "修饰 assembled", explanation: "专家在澳大利亚病例数急剧上升后集合；sharp 修饰 rise 的幅度。" },
      { text: "rising numbers in Britain, Japan, Chile and elsewhere", form: "现在分词形容词 + 名词 + 地点", function: "并列背景", modifies: "与 a sharp rise... 并列", explanation: "numbers 省略了 of cases，由多个国家地点帮助确定‘病例数’。" },
    ], clauses: [
      { text: "that assembled after a sharp rise in cases in Australia, and rising numbers in Britain, Japan, Chile and elsewhere", type: "限制性定语从句", marker: "that", role: "说明紧急会议/与会专家在何种疫情背景下集合", subject: "that（语义上承接 flu experts）", predicate: "assembled", objectOrComplement: "after...（时间兼原因背景状语）", translationOrder: "先译‘流感专家集合开会’，再补‘在各地病例上升之后’。" },
    ] },
    literal: "提高警戒级别发生在日内瓦流感专家紧急会议之后；专家是在澳大利亚病例急剧增加，以及英国、日本、智利等地病例数上升后集合的。",
    natural: "澳大利亚病例激增、英国等国病例持续上升后，流感专家在日内瓦召开紧急会议，随后警戒级别被调高。",
    logic: "交代警戒升级的直接程序与数据背景，说明决定并非无缘无故作出。",
    phrases: ["the heightened alert", "followed an emergency meeting", "with flu experts in Geneva", "after a sharp rise in cases", "rising numbers", "in Britain, Japan, Chile and elsewhere"],
    answerWords: ["followed", "numbers"],
  },
  {
    id: "2010-cloze-s4", number: 4,
    text: "But the epidemic is \"moderate\" in severity, according to Margaret Chan, the organization's director general, with the overwhelming majority of patients experiencing only mild symptoms and a full recovery, often in the absence of any medical treatment.",
    testText: "But the epidemic is \"___(4)\" in severity, according to Margaret Chan, the organization's director general, ___(5) the overwhelming majority of patients experiencing only mild symptoms and a full recovery, often in the ___(6) of any medical treatment.",
    chunks: [
      { text: "But", role: "connector" }, { text: " the epidemic", role: "subject" },
      { text: " is", role: "predicate" }, { text: " \"moderate\" in severity", role: "object" },
      { text: ", according to Margaret Chan", role: "modifier" },
      { text: ", the organization's director general", role: "modifier" },
      { text: ", with the overwhelming majority of patients experiencing only mild symptoms and a full recovery", role: "modifier" },
      { text: ", often in the absence of any medical treatment.", role: "modifier" },
    ],
    trunk: "the epidemic is moderate in severity.",
    layers: [
      { label: "转折结论", text: "But the epidemic is moderate in severity：尽管影响全球，但严重程度为中等" },
      { label: "信息来源", text: "according to Margaret Chan, the organization's director general：据该组织总干事陈冯富珍说" },
      { label: "判断依据", text: "with... patients experiencing...：绝大多数患者症状轻微并能完全康复" },
      { label: "康复条件", text: "in the absence of any medical treatment：往往没有接受任何治疗也能康复" },
    ],
    grammar: [
      "moderate in severity 表‘严重程度中等’，moderate 是程度评价，normal 不能表达疫情级别。",
      "according to... 是信息来源状语；逗号后的 the organization's director general 是 Margaret Chan 的同位语。",
      "with + 名词 + doing 构成 with 复合结构：majority 是 experiencing 的逻辑主语，整组提供伴随情况和判断依据。",
      "in the absence of 是固定结构，表示‘在没有……的情况下’；absence 与 presence 相反。",
    ],
    beginnerSyntax: { components: [
      { text: "But", form: "并列连词", function: "转折连接语", modifies: "连接全球警戒与较轻严重度", explanation: "前文强调全球性，本句转而说明大多数病例并不严重。" },
      { text: "the epidemic", form: "名词短语", function: "主句主语", modifies: "与 is moderate 构成系表主干", explanation: "本句评价的是这场疫情的严重程度。" },
      { text: "is \"moderate\" in severity", form: "系动词 + 形容词表语 + 范围短语", function: "主句谓语与表语", modifies: "说明疫情严重程度", explanation: "先读 is moderate = 程度中等；in severity 限定是‘在严重程度方面’。" },
      { text: "according to Margaret Chan", form: "according to + 人", function: "信息来源状语", modifies: "修饰整个判断", explanation: "表示这项评价来自谁，不是说疫情‘服从’某个人。" },
      { text: "the organization's director general", form: "名词所有格 + 职务", function: "同位语", modifies: "补充 Margaret Chan 的身份", explanation: "两个逗号夹住，可先拿掉；the organization 回指世界卫生组织。" },
      { text: "with the overwhelming majority of patients experiencing only mild symptoms and a full recovery", form: "with + 名词 + doing", function: "伴随/依据状语", modifies: "说明为何判断为 moderate", explanation: "majority of patients 是 experiencing 的逻辑主语；患者经历轻微症状和完全康复。" },
      { text: "only mild symptoms and a full recovery", form: "形容词 + 并列名词", function: "experiencing 的并列宾语", modifies: "说明患者经历什么", explanation: "only 限定程度；symptoms 与 recovery 由 and 并列。" },
      { text: "in the absence of any medical treatment", form: "in the absence of + 名词", function: "条件/伴随状语", modifies: "修饰 recovery/experiencing", explanation: "即使没有治疗也能恢复，是疫情严重度不高的重要依据。" },
    ], clauses: [] },
    literal: "但是，据该组织总干事 Margaret Chan 所说，这场疫情在严重程度上属于‘中等’；绝大多数患者只有轻微症状并完全康复，而且往往没有任何医疗治疗。",
    natural: "不过，世卫组织总干事陈冯富珍表示，这次疫情严重程度为中等：绝大多数患者症状轻微，即使不接受治疗也能完全康复。",
    logic: "通过轻症和自然康复数据限制前文的紧张语气，形成‘传播范围广但严重度有限’的准确判断。",
    phrases: ["\"moderate\" in severity", "according to Margaret Chan", "the organization's director general", "with the overwhelming majority of patients experiencing", "mild symptoms and a full recovery", "in the absence of any medical treatment"],
    answerWords: ["moderate", "with", "absence"],
  },
  {
    id: "2010-cloze-s5", number: 5,
    text: "The outbreak came to global notice in late April 2009, when Mexican authorities noted an unusually large number of hospitalizations and deaths among healthy adults.",
    testText: "The outbreak came to global ___(7) in late April 2009, when Mexican authorities noted an unusually large number of hospitalizations and deaths ___(8) healthy adults.",
    chunks: [
      { text: "The outbreak", role: "subject" }, { text: " came", role: "predicate" },
      { text: " to global notice", role: "modifier" }, { text: " in late April 2009", role: "modifier" },
      { text: ", when Mexican authorities noted", role: "modifier" },
      { text: " an unusually large number of hospitalizations and deaths", role: "object" },
      { text: " among healthy adults.", role: "modifier" },
    ],
    trunk: "The outbreak came to global notice.",
    layers: [
      { label: "主干", text: "The outbreak came to global notice：疫情引起全球关注" },
      { label: "时间", text: "in late April 2009：2009 年 4 月下旬" },
      { label: "触发事件", text: "when Mexican authorities noted...：墨西哥当局注意到健康成年人中住院和死亡人数异常多" },
    ],
    grammar: [
      "come to notice 表‘受到注意、进入公众视野’，global 修饰 notice；reality/phenomenon/concept 都不构成此搭配。",
      "when 引导非限制性时间状语从句，补充说明疫情何时受到全球关注。",
      "a large number of 修饰可数名词复数 hospitalizations and deaths。",
      "among healthy adults 表事件发生在健康成年人这一群体之中；between 不适合未逐一区分的大群体。",
    ],
    beginnerSyntax: { components: [
      { text: "The outbreak", form: "名词短语", function: "主句主语", modifies: "是 came to notice 的主体", explanation: "仍指这次猪流感暴发。" },
      { text: "came to global notice", form: "动词搭配", function: "主句谓语", modifies: "说明疫情进入全球视野", explanation: "整组译为‘引起全球关注’，不能逐字译成‘来到通知’。" },
      { text: "in late April 2009", form: "in + 月份时间", function: "时间状语", modifies: "修饰 came to notice", explanation: "说明受到关注的时间；月份、年份前使用 in。" },
      { text: "when Mexican authorities noted an unusually large number of hospitalizations and deaths among healthy adults", form: "when 引导的完整从句", function: "时间状语从句", modifies: "补充说明关注出现的具体节点", explanation: "从句主干是 authorities noted a number；后面逐层说明数量内容和人群。" },
      { text: "Mexican authorities", form: "形容词 + 复数名词", function: "从句主语", modifies: "是 noted 的动作发出者", explanation: "authorities 表‘当局、主管部门’，通常用复数。" },
      { text: "noted", form: "及物动词过去式", function: "从句谓语", modifies: "说明当局注意到异常情况", explanation: "这里是‘注意到’，不是写笔记。" },
      { text: "an unusually large number of hospitalizations and deaths", form: "数量短语 + 并列名词", function: "从句宾语", modifies: "承受 noted 的动作", explanation: "number 的具体内容是住院事件和死亡事件；unusually 修饰 large。" },
      { text: "among healthy adults", form: "among + 人群", function: "群体范围状语", modifies: "修饰 hospitalizations and deaths", explanation: "说明异常住院和死亡出现在哪类人中。" },
    ], clauses: [
      { text: "when Mexican authorities noted an unusually large number of hospitalizations and deaths among healthy adults", type: "时间状语从句", marker: "when", role: "说明疫情受到全球关注的时间节点和触发情况", subject: "Mexican authorities", predicate: "noted", objectOrComplement: "an unusually large number of hospitalizations and deaths；among...（范围）", translationOrder: "先译主句‘引起全球关注’，再补‘当墨西哥当局注意到……时’。" },
    ] },
    literal: "疫情在 2009 年 4 月下旬引起全球注意，当时墨西哥当局注意到健康成年人中出现了异常多的住院和死亡。",
    natural: "2009 年 4 月下旬，墨西哥当局发现健康成年人住院和死亡病例异常增多，这场疫情由此进入全球视野。",
    logic: "从官方定级转回疫情早期发展，说明全球关注是由异常病例信号触发的。",
    phrases: ["came to global notice", "in late April 2009", "Mexican authorities noted", "an unusually large number of", "hospitalizations and deaths among healthy adults"],
    answerWords: ["notice", "among"],
  },
  {
    id: "2010-cloze-s6", number: 6,
    text: "As much of Mexico City shut down at the height of a panic, cases began to crop up in New York City, the southwestern United States and around the world.",
    testText: "As much of Mexico City shut down at the height of a panic, cases began to ___(9) in New York City, the southwestern United States and around the world.",
    chunks: [
      { text: "As much of Mexico City shut down", role: "condition" },
      { text: " at the height of a panic", role: "modifier" }, { text: ", cases", role: "subject" },
      { text: " began to crop up", role: "predicate" },
      { text: " in New York City, the southwestern United States and around the world.", role: "modifier" },
    ],
    trunk: "cases began to crop up.",
    layers: [
      { label: "背景", text: "As much of Mexico City shut down at the height of a panic：墨西哥城大部分地区在恐慌最严重时停摆" },
      { label: "主句", text: "cases began to crop up：病例开始接连出现" },
      { label: "出现地点", text: "in New York City, the southwestern United States and around the world：纽约、美国西南部乃至世界各地" },
    ],
    grammar: [
      "as 引导时间/伴随状语从句，表示两种情况同期发展，可译为‘随着/当……时’。",
      "much of + 地名/不可数整体表示其中很大一部分；shut down 在此是不及物短语，表示城市活动停摆。",
      "at the height of 表‘在……最严重/最鼎盛时’。",
      "crop up 是不及物短语，表示问题或病例意外、陆续出现；后接 in 引出地点。",
    ],
    beginnerSyntax: { components: [
      { text: "As much of Mexico City shut down at the height of a panic", form: "As 引导的完整从句", function: "时间/伴随状语从句", modifies: "整体修饰 cases began to crop up", explanation: "先译‘当墨西哥城大部分地区因恐慌而停摆时’，再读主句。" },
      { text: "much of Mexico City", form: "much of + 地名整体", function: "从句主语", modifies: "是 shut down 的主体", explanation: "指墨西哥城的大部分区域或社会活动，不是‘许多墨西哥城’。" },
      { text: "shut down", form: "不规则动词短语过去式", function: "从句谓语", modifies: "说明城市活动停摆", explanation: "shut 的过去式仍是 shut；这里没有宾语，是‘关闭、停摆’。" },
      { text: "at the height of a panic", form: "at the height of + 名词", function: "时间/程度状语", modifies: "修饰 shut down", explanation: "height 比喻恐慌达到最高点，不是物理高度。" },
      { text: "cases", form: "复数名词", function: "主句主语", modifies: "是 began to crop up 的主体", explanation: "指感染病例，不是案件或箱子。" },
      { text: "began to crop up", form: "begin to do + 短语动词", function: "主句谓语", modifies: "说明病例开始陆续出现", explanation: "crop up 整体记忆为‘意外出现、冒出来’，不能按农作物翻译。" },
      { text: "in New York City, the southwestern United States and around the world", form: "in/around + 并列地点", function: "地点状语", modifies: "修饰 crop up", explanation: "按从具体地点到全球范围依次说明病例在哪里出现。" },
    ], clauses: [
      { text: "As much of Mexico City shut down at the height of a panic", type: "时间/伴随状语从句", marker: "As", role: "为主句病例向外扩散提供同期背景", subject: "much of Mexico City", predicate: "shut down", objectOrComplement: "at the height of a panic（时间/程度状语）", translationOrder: "先译‘当/随着墨西哥城大部分地区停摆’，再译病例出现。" },
    ] },
    literal: "当墨西哥城大部分地区在恐慌顶峰停摆时，病例开始在纽约市、美国西南部以及世界各地出现。",
    natural: "墨西哥城因恐慌大面积停摆之际，纽约、美国西南部乃至全球各地也开始陆续发现病例。",
    logic: "展示疫情从墨西哥向全球扩散，解释为何随后被提升为全球性警戒。",
    phrases: ["much of Mexico City", "shut down", "at the height of a panic", "began to crop up", "the southwestern United States", "around the world"],
    answerWords: ["crop up"],
  },
  {
    id: "2010-cloze-s7", number: 7,
    text: "In the United States, new cases seemed to fade as warmer weather arrived.",
    testText: "In the United States, new cases seemed to fade ___(10) warmer weather arrived.",
    chunks: [
      { text: "In the United States", role: "modifier" }, { text: ", new cases", role: "subject" },
      { text: " seemed to fade", role: "predicate" }, { text: " as warmer weather arrived.", role: "modifier" },
    ],
    trunk: "new cases seemed to fade.",
    layers: [
      { label: "地点", text: "In the United States：在美国" },
      { label: "表面趋势", text: "new cases seemed to fade：新增病例似乎逐渐减少" },
      { label: "同期变化", text: "as warmer weather arrived：随着天气转暖" },
    ],
    grammar: [
      "seem to do 表‘似乎做/出现某趋势’，保留说话者并不完全确定的语气。",
      "fade 在此指病例活动逐渐减弱、淡出，不是颜色褪去。",
      "as 引导时间/伴随状语从句，表示天气变暖与病例减弱同期发生；if/unless 是条件，until 强调持续到某时。",
    ],
    beginnerSyntax: { components: [
      { text: "In the United States", form: "in + 地名", function: "地点状语", modifies: "修饰 seemed to fade", explanation: "把结论限定在美国，而不是全球所有地区。" },
      { text: "new cases", form: "形容词 + 复数名词", function: "主句主语", modifies: "是 seemed to fade 的主体", explanation: "这里指新增感染病例。" },
      { text: "seemed to fade", form: "seem to do", function: "主句谓语", modifies: "说明病例呈现减弱趋势", explanation: "seemed 表‘看起来如此’，fade 表数量或活动逐渐减弱。" },
      { text: "as warmer weather arrived", form: "as 引导的完整从句", function: "时间/伴随状语从句", modifies: "修饰 seemed to fade", explanation: "从句主语是 warmer weather，谓语 arrived；译为‘随着天气转暖’。" },
    ], clauses: [
      { text: "as warmer weather arrived", type: "时间/伴随状语从句", marker: "as", role: "说明病例减弱发生时伴随的天气变化", subject: "warmer weather", predicate: "arrived", translationOrder: "中文可先译‘随着天气转暖’，再译‘病例似乎减少’。" },
    ] },
    literal: "在美国，随着更温暖的天气到来，新增病例似乎逐渐消退。",
    natural: "在美国，天气转暖后，新增病例一度看似在减少。",
    logic: "先写疫情短暂缓和，为下一句秋季显著反弹形成转折。",
    phrases: ["In the United States", "new cases", "seemed to fade", "as warmer weather arrived"],
    answerWords: ["as"],
  },
  {
    id: "2010-cloze-s8", number: 8,
    text: "But in late September 2009, officials reported there was significant flu activity in almost every state and that virtually all the samples tested are the new swine flu, also known as (A) H1N1, not seasonal flu.",
    testText: "But in late September 2009, officials reported there was ___(11) flu activity in almost every state and that virtually all the ___(12) tested are the new swine flu, also known as (A) H1N1, not seasonal flu.",
    chunks: [
      { text: "But in late September 2009", role: "connector" }, { text: ", officials", role: "subject" },
      { text: " reported", role: "predicate" },
      { text: " there was significant flu activity in almost every state", role: "object" },
      { text: " and that virtually all the samples tested are the new swine flu", role: "object" },
      { text: ", also known as (A) H1N1", role: "modifier" }, { text: ", not seasonal flu.", role: "modifier" },
    ],
    trunk: "officials reported there was significant flu activity and that the samples are the new swine flu.",
    layers: [
      { label: "转折时间", text: "But in late September 2009：但到 2009 年 9 月下旬" },
      { label: "报告一", text: "there was significant flu activity in almost every state：几乎每州都有显著流感活动" },
      { label: "报告二", text: "virtually all the samples tested are the new swine flu：几乎所有受检样本都是新型猪流感" },
      { label: "名称排除", text: "also known as (A) H1N1, not seasonal flu：即甲型 H1N1，而非季节性流感" },
    ],
    grammar: [
      "reported 后并列两个宾语从句：第一个省略 that（there was...），第二个保留 that；and 连接两项报告内容。",
      "significant 表数量或程度达到值得注意的水平；enormous/magnificent 与 flu activity 搭配不当，excessive 带‘过度’评价。",
      "samples tested 是‘被检测的样本’，tested 为过去分词后置定语，相当于 samples that were tested。",
      "also known as... 是过去分词插入语，补充新型猪流感的别名；not seasonal flu 排除另一类别。",
    ],
    beginnerSyntax: { components: [
      { text: "But in late September 2009", form: "转折词 + 时间短语", function: "转折连接与时间状语", modifies: "修饰 officials reported", explanation: "But 把夏季缓和转到秋季反弹；in late... 说明报告时间。" },
      { text: "officials", form: "复数名词", function: "主句主语", modifies: "是 reported 的动作发出者", explanation: "指卫生官员。" },
      { text: "reported", form: "及物动词过去式", function: "主句谓语", modifies: "引出两项报告内容", explanation: "后面不是一个超长宾语，而是两个由 and 连接的内容从句。" },
      { text: "there was significant flu activity in almost every state", form: "省略 that 的完整从句", function: "宾语从句一", modifies: "作 reported 的第一项内容", explanation: "从句用 there be 表存在；significant 修饰 flu activity，地点是几乎每个州。" },
      { text: "that virtually all the samples tested are the new swine flu", form: "that 引导的完整从句", function: "宾语从句二", modifies: "与前一从句并列作 reported 的宾语", explanation: "主语是 all the samples tested；系动词 are 后说明样本检测结果。" },
      { text: "tested", form: "过去分词", function: "后置定语", modifies: "修饰 samples", explanation: "哪些样本？已经接受检测的样本；样本与 test 是被动关系。" },
      { text: "also known as (A) H1N1", form: "过去分词插入语", function: "补充说明", modifies: "修饰 the new swine flu", explanation: "be known as 表‘被称为’，省略 being 后作为插入说明。" },
      { text: "not seasonal flu", form: "否定对照短语", function: "类别排除", modifies: "与 the new swine flu 对照", explanation: "说明检测到的不是普通季节性流感。" },
    ], clauses: [
      { text: "there was significant flu activity in almost every state", type: "宾语从句", marker: "省略 that", role: "作 reported 的第一项报告内容", subject: "there（形式存在结构）", predicate: "was", objectOrComplement: "significant flu activity；in almost every state（地点）", translationOrder: "先译‘官员报告’，再补‘几乎每个州都有……’。" },
      { text: "that virtually all the samples tested are the new swine flu, also known as (A) H1N1, not seasonal flu", type: "宾语从句", marker: "that", role: "与前一从句并列，作 reported 的第二项内容", subject: "virtually all the samples tested", predicate: "are", objectOrComplement: "the new swine flu（表语）", translationOrder: "按‘几乎所有受检样本—都是—新型猪流感’理解，再补名称和排除项。" },
    ] },
    literal: "但在 2009 年 9 月下旬，官员报告说，几乎每个州都有显著的流感活动，并且几乎所有接受检测的样本都是新型猪流感，也称为甲型 H1N1，而不是季节性流感。",
    natural: "然而到 2009 年 9 月下旬，疫情明显反弹：官员称几乎各州均出现显著流感活动，受检样本几乎全是甲型 H1N1 新型猪流感，而非季节性流感。",
    logic: "用秋季数据否定‘疫情已经消退’的表象，并明确流行毒株身份。",
    phrases: ["in late September 2009", "significant flu activity", "in almost every state", "virtually all the samples tested", "the new swine flu", "also known as (A) H1N1", "not seasonal flu"],
    answerWords: ["significant", "samples"],
  },
  {
    id: "2010-cloze-s9", number: 9,
    text: "In the U.S., it has infected more than one million people, and caused more than 600 deaths and more than 6,000 hospitalizations.",
    testText: "In the U.S., it has ___(13) more than one million people, and caused more than 600 deaths and more than 6,000 hospitalizations.",
    chunks: [
      { text: "In the U.S.", role: "modifier" }, { text: ", it", role: "subject" },
      { text: " has infected", role: "predicate" }, { text: " more than one million people", role: "object" },
      { text: ", and caused", role: "predicate" },
      { text: " more than 600 deaths and more than 6,000 hospitalizations.", role: "object" },
    ],
    trunk: "it has infected people and caused deaths and hospitalizations.",
    layers: [
      { label: "地点", text: "In the U.S.：在美国" },
      { label: "感染规模", text: "has infected more than one million people：已感染一百多万人" },
      { label: "严重后果", text: "caused more than 600 deaths and more than 6,000 hospitalizations：造成六百多例死亡和六千多例住院" },
    ],
    grammar: [
      "has infected 与 (has) caused 是现在完成时并列谓语，caused 前省略重复的 has。",
      "infect + 人表示使人感染；inject 是注射，immerse 是使沉浸，impart 是传授。",
      "more than 分别限定 one million、600 和 6,000；people、deaths、hospitalizations 保持可数复数。",
    ],
    beginnerSyntax: { components: [
      { text: "In the U.S.", form: "in + 地点缩写", function: "地点状语", modifies: "修饰 has infected and caused", explanation: "把数据范围限定在美国。" },
      { text: "it", form: "人称代词", function: "主句主语", modifies: "是 infected 和 caused 的动作发出者", explanation: "it 回指 the new swine flu，不指 United States。" },
      { text: "has infected", form: "现在完成时", function: "并列谓语一", modifies: "说明截至报告时的累计感染", explanation: "has + 过去分词 infected；强调过去发生并累计到现在。" },
      { text: "more than one million people", form: "数量短语", function: "宾语一", modifies: "承受 infected 的动作", explanation: "感染的是人，因此用 people。" },
      { text: "and caused", form: "and + 过去分词", function: "并列谓语二", modifies: "与 has infected 并列，共用 has", explanation: "完整形式是 and has caused；为避免重复省略第二个 has。" },
      { text: "more than 600 deaths and more than 6,000 hospitalizations", form: "两个并列数量名词短语", function: "宾语二", modifies: "承受 caused 的动作", explanation: "caused 后有两个并列结果：死亡和住院。" },
    ], clauses: [] },
    literal: "在美国，它已经感染了一百多万人，并造成六百多人死亡和六千多人住院。",
    natural: "仅在美国，甲型 H1N1 就已感染逾百万人，导致六百多人死亡、六千多人住院。",
    logic: "用累计感染、死亡和住院数据证明疫情虽多为轻症，仍需采取公共卫生措施。",
    phrases: ["In the U.S.", "has infected more than one million people", "caused more than 600 deaths", "more than 6,000 hospitalizations"],
    answerWords: ["infected"],
  },
  {
    id: "2010-cloze-s10", number: 10,
    text: "Federal health officials released Tamiflu for children from the national stockpile and began taking orders from the states for the new swine flu vaccine.",
    testText: "Federal health officials ___(14) Tamiflu for children from the national stockpile and began ___(15) orders from the states for the new swine flu vaccine.",
    chunks: [
      { text: "Federal health officials", role: "subject" }, { text: " released", role: "predicate" },
      { text: " Tamiflu for children", role: "object" }, { text: " from the national stockpile", role: "modifier" },
      { text: " and began taking", role: "predicate" }, { text: " orders from the states", role: "object" },
      { text: " for the new swine flu vaccine.", role: "modifier" },
    ],
    trunk: "Federal health officials released Tamiflu and began taking orders.",
    layers: [
      { label: "措施一", text: "released Tamiflu for children from the national stockpile：从国家储备中调拨儿童用达菲" },
      { label: "措施二", text: "began taking orders from the states：开始接受各州的订购申请" },
      { label: "订购物", text: "for the new swine flu vaccine：订购新型猪流感疫苗" },
    ],
    grammar: [
      "release A from stockpile 表从储备中放出、调拨物资；relay 是转发信息，relieve 是缓解。",
      "release 与 began 是由 and 连接的两个一般过去时谓语，共用主语 officials。",
      "begin doing / begin to do 均可；take orders 是固定搭配，表示接受订单。",
      "from the states 说明订单来源，for the vaccine 说明订购对象。",
    ],
    beginnerSyntax: { components: [
      { text: "Federal health officials", form: "形容词 + 名词组合", function: "主语", modifies: "是 released 和 began 的动作发出者", explanation: "Federal 表联邦层面，health 说明官员所属领域。" },
      { text: "released Tamiflu for children", form: "及物动词 + 宾语 + 用途", function: "并列谓语一", modifies: "说明第一项卫生措施", explanation: "release 在物资语境中是‘调拨、发放’，for children 说明供谁使用。" },
      { text: "from the national stockpile", form: "from + 名词短语", function: "来源状语", modifies: "修饰 released", explanation: "说明达菲从国家储备库中调出。" },
      { text: "and began taking orders", form: "and + begin doing", function: "并列谓语二", modifies: "与 released 并列", explanation: "taking orders 不是‘拿走命令’，而是商业/供应语境中的‘接受订单’。" },
      { text: "from the states", form: "from + 机构复数", function: "来源状语", modifies: "修饰 orders/taking", explanation: "说明订单由各州提交。" },
      { text: "for the new swine flu vaccine", form: "for + 名词短语", function: "对象后置定语", modifies: "修饰 orders", explanation: "回答‘订购什么’：新型猪流感疫苗。" },
    ], clauses: [] },
    literal: "联邦卫生官员从国家储备中发放儿童用达菲，并开始接受各州对新型猪流感疫苗的订单。",
    natural: "联邦卫生部门从国家储备库调拨儿童用达菲，同时开始接收各州的新型猪流感疫苗订购申请。",
    logic: "由疫情数据转向政府应对措施：先调拨现有药物，再组织新疫苗供应。",
    phrases: ["Federal health officials", "released Tamiflu for children", "from the national stockpile", "began taking orders", "orders from the states", "for the new swine flu vaccine"],
    answerWords: ["released", "taking"],
  },
  {
    id: "2010-cloze-s11", number: 11,
    text: "The new vaccine, which is different from the annual flu vaccine, is available ahead of expectations.",
    testText: "The new vaccine, which is different from the annual flu vaccine, is ___(16) ahead of expectations.",
    chunks: [
      { text: "The new vaccine", role: "subject" },
      { text: ", which is different from the annual flu vaccine", role: "modifier" },
      { text: ", is", role: "predicate" }, { text: " available", role: "object" },
      { text: " ahead of expectations.", role: "modifier" },
    ],
    trunk: "The new vaccine is available.",
    layers: [
      { label: "主干", text: "The new vaccine is available：新疫苗已经可以供应" },
      { label: "区别", text: "which is different from the annual flu vaccine：它不同于每年使用的季节性流感疫苗" },
      { label: "进度", text: "ahead of expectations：早于预期" },
    ],
    grammar: [
      "which 引导非限制性定语从句，补充说明 vaccine；两侧逗号表明去掉后主句仍完整。",
      "be different from 是固定搭配，表示与……不同。",
      "available 表物品可以获得或投入使用；feasible 修饰计划是否可行，applicable 表规则是否适用，reliable 表是否可靠。",
      "ahead of expectations 表比预期更早或进展更快。",
    ],
    beginnerSyntax: { components: [
      { text: "The new vaccine", form: "名词短语", function: "主句主语", modifies: "与 is available 构成系表主干", explanation: "指前一句的 new swine flu vaccine。" },
      { text: "which is different from the annual flu vaccine", form: "which 引导的完整从句", function: "非限制性定语从句", modifies: "补充说明 The new vaccine", explanation: "先把逗号间部分括起来，主句仍是 The new vaccine is available。" },
      { text: "is different from", form: "系动词 + 形容词 + 介词", function: "从句谓语与表语", modifies: "说明两种疫苗不同", explanation: "different 必须与 from 搭配，再接比较对象。" },
      { text: "the annual flu vaccine", form: "形容词 + 名词组合", function: "介词宾语", modifies: "作 from 的比较对象", explanation: "annual 指每年例行使用的流感疫苗。" },
      { text: "is available", form: "系动词 + 形容词", function: "主句谓语与表语", modifies: "说明疫苗供应状态", explanation: "available 在这里是‘已经可获得/可供应’，不是‘有空的’。" },
      { text: "ahead of expectations", form: "ahead of + 名词", function: "时间/进度状语", modifies: "修饰 is available", explanation: "说明可供应的时间比原先预期更早。" },
    ], clauses: [
      { text: "which is different from the annual flu vaccine", type: "非限制性定语从句", marker: "which（指代 The new vaccine）", role: "补充说明新疫苗与年度流感疫苗不同", subject: "which", predicate: "is", objectOrComplement: "different from the annual flu vaccine（表语）", translationOrder: "先译主句，再插入‘这种疫苗不同于……’。" },
    ] },
    literal: "这种不同于年度流感疫苗的新疫苗，在预期之前已经可以获得。",
    natural: "这款新疫苗与每年的季节性流感疫苗不同，而且比预计时间更早投入供应。",
    logic: "说明新疫苗的类别和供应进度，为下一句具体数量、剂型及适用限制作铺垫。",
    phrases: ["the new vaccine", "is different from", "the annual flu vaccine", "is available", "ahead of expectations"],
    answerWords: ["available"],
  },
  {
    id: "2010-cloze-s12", number: 12,
    text: "More than three million doses were to be made available in early October 2009, though most of those initial doses were of the FluMist nasal spray type, which is not recommended for pregnant women, people over 50 or those with breathing difficulties, heart disease or several other problems.",
    testText: "More than three million doses were to be made available in early October 2009, though most of those ___(17) doses were of the FluMist nasal spray type, which is not ___(18) for pregnant women, people over 50 or those with breathing difficulties, heart disease or several other ___(19).",
    chunks: [
      { text: "More than three million doses", role: "subject" }, { text: " were to be made available", role: "predicate" },
      { text: " in early October 2009", role: "modifier" },
      { text: ", though most of those initial doses", role: "condition" }, { text: " were", role: "predicate" },
      { text: " of the FluMist nasal spray type", role: "object" },
      { text: ", which is not recommended", role: "modifier" },
      { text: " for pregnant women, people over 50 or those with breathing difficulties, heart disease or several other problems.", role: "modifier" },
    ],
    trunk: "More than three million doses were to be made available.",
    layers: [
      { label: "供应计划", text: "More than three million doses were to be made available...：计划在 10 月初供应三百多万剂" },
      { label: "让步限制", text: "though most of those initial doses were of the FluMist nasal spray type：但首批多数是 FluMist 鼻喷剂" },
      { label: "不适用人群", text: "which is not recommended for...：这种剂型不建议孕妇、50 岁以上人群及有若干健康问题者使用" },
    ],
    grammar: [
      "be to do 表计划安排；be made available 是 make A available 的被动，合起来表示‘计划被供应’。",
      "though 引导让步状语从句：有三百多万剂可供使用，但首批剂型存在适用限制。",
      "be of the... type 表‘属于……类型’；initial 修饰首次推出的 doses，prevalent/principal/innovative 均不合时间顺序。",
      "which 引导非限制性定语从句，指 FluMist nasal spray type；be recommended for + 人群表示适合/建议某类人使用。",
      "pregnant women、people over 50、those with... 是三个并列人群；those 代替 people。",
    ],
    beginnerSyntax: { components: [
      { text: "More than three million doses", form: "数量 + 复数名词", function: "主句主语", modifies: "是 were to be made available 的承受者", explanation: "dose 指一剂药或疫苗；more than 表超过三百万剂。" },
      { text: "were to be made available", form: "be to do + 被动宾补结构", function: "主句谓语", modifies: "说明疫苗供应计划", explanation: "拆成 were to（计划）+ be made available（被提供）；整体译成‘计划供应’。" },
      { text: "in early October 2009", form: "in + 时间", function: "时间状语", modifies: "修饰 were to be made available", explanation: "说明预计供应时间。" },
      { text: "though most of those initial doses were of the FluMist nasal spray type", form: "though 引导的完整从句", function: "让步状语从句", modifies: "限制主句的利好信息", explanation: "虽然数量不少，但首批多数剂量属于鼻喷剂；though 提醒后面有使用限制。" },
      { text: "most of those initial doses", form: "most of + 限定词 + 复数名词", function: "让步从句主语", modifies: "与 were of 构成主干", explanation: "initial 表第一批、最初供应的，不是主要的。" },
      { text: "were of the FluMist nasal spray type", form: "be of + 类型名词", function: "让步从句谓语与表语", modifies: "说明首批疫苗剂型", explanation: "be of the... type = 属于……类型；这里是 FluMist 鼻喷型。" },
      { text: "which is not recommended for pregnant women, people over 50 or those with breathing difficulties, heart disease or several other problems", form: "which 引导的完整从句", function: "非限制性定语从句", modifies: "修饰 FluMist nasal spray type", explanation: "先读 which is not recommended for people：不建议某些人使用；后面再列三类人群。" },
      { text: "pregnant women, people over 50 or those with breathing difficulties, heart disease or several other problems", form: "三个并列名词短语", function: "for 的介词宾语", modifies: "说明不建议使用的人群", explanation: "第一类孕妇；第二类 50 岁以上者；第三类有呼吸困难、心脏病等问题者。" },
    ], clauses: [
      { text: "though most of those initial doses were of the FluMist nasal spray type, which is not recommended for pregnant women, people over 50 or those with breathing difficulties, heart disease or several other problems", type: "让步状语从句", marker: "though", role: "对三百多万剂提前供应的利好作限制", subject: "most of those initial doses", predicate: "were", objectOrComplement: "of the FluMist nasal spray type（类型表语）", translationOrder: "先译主句供应计划，再用‘不过/尽管’补充首批剂型限制。" },
      { text: "which is not recommended for pregnant women, people over 50 or those with breathing difficulties, heart disease or several other problems", type: "非限制性定语从句", marker: "which（指代 FluMist nasal spray type）", role: "说明该鼻喷剂不适用的人群", subject: "which", predicate: "is not recommended", objectOrComplement: "for...（适用对象）", translationOrder: "先译鼻喷剂类型，再补‘不建议以下人群使用’并列举。" },
    ] },
    literal: "三百多万剂疫苗计划于 2009 年 10 月初提供，尽管这些最初剂量中的大多数属于 FluMist 鼻喷剂类型，而这种类型不推荐给孕妇、50 岁以上人群，或有呼吸困难、心脏病及其他若干问题的人。",
    natural: "原计划 2009 年 10 月初供应三百多万剂疫苗，不过首批大多是 FluMist 鼻喷剂，不适合孕妇、50 岁以上人群以及有呼吸系统、心脏等健康问题者。",
    logic: "在供应进度利好后补充剂型限制，避免把‘可获得’误解为‘人人适用’。",
    phrases: ["more than three million doses", "were to be made available", "in early October 2009", "most of those initial doses", "the FluMist nasal spray type", "recommended for", "pregnant women", "people over 50", "those with breathing difficulties", "heart disease", "several other problems"],
    answerWords: ["initial", "recommended", "problems"],
  },
  {
    id: "2010-cloze-s13", number: 13,
    text: "But it was still possible to vaccinate people in other high-risk groups: health care workers, people caring for infants and healthy young people.",
    testText: "But it was still possible to vaccinate people in other high-risk groups: health care workers, people ___(20) infants and healthy young people.",
    chunks: [
      { text: "But", role: "connector" }, { text: " it", role: "subject" }, { text: " was", role: "predicate" },
      { text: " still possible", role: "object" }, { text: " to vaccinate people in other high-risk groups", role: "modifier" },
      { text: ": health care workers, people caring for infants and healthy young people.", role: "modifier" },
    ],
    trunk: "it was still possible to vaccinate people.",
    layers: [
      { label: "形式主语", text: "it was still possible to vaccinate...：仍然可以给其他高风险群体接种" },
      { label: "群体范围", text: "people in other high-risk groups：其他高风险人群" },
      { label: "冒号列举", text: "health care workers, people caring for infants and healthy young people：医护人员、照料婴儿者及健康年轻人" },
    ],
    grammar: [
      "it 是形式主语，真正主语是 to vaccinate people...；结构为 It be possible to do sth。",
      "冒号后的三个名词短语同位解释 other high-risk groups。",
      "caring for infants 是现在分词短语，后置修饰 people；care for 表照料。",
      "involved in 表参与，concerned with 表涉及，ward off 表抵御，都不能表达照顾婴儿。",
    ],
    beginnerSyntax: { components: [
      { text: "But", form: "并列连词", function: "转折连接语", modifies: "由不适用人群转向仍可接种人群", explanation: "上一句说谁不适合鼻喷疫苗，本句说明还有哪些高风险人群可以接种。" },
      { text: "it", form: "形式代词", function: "形式主语", modifies: "替代后面的 to vaccinate...", explanation: "it 不指疫苗或疫情，只为避免把很长的不定式放句首。" },
      { text: "was still possible", form: "系动词 + 副词 + 形容词", function: "主句谓语与表语", modifies: "评价接种行为仍可实行", explanation: "still 表尽管有限制，接种仍然可行。" },
      { text: "to vaccinate people in other high-risk groups", form: "不定式短语", function: "真正主语", modifies: "说明什么事情是 possible", explanation: "把句子还原为 To vaccinate... was possible；正常表达用形式主语 it。" },
      { text: "in other high-risk groups", form: "in + 名词短语", function: "后置定语", modifies: "修饰 people", explanation: "说明接种对象属于哪些群体。" },
      { text: "health care workers, people caring for infants and healthy young people", form: "三个并列名词短语", function: "同位列举", modifies: "具体解释 other high-risk groups", explanation: "冒号就是‘具体包括’：医护、照料婴儿者、健康年轻人。" },
      { text: "caring for infants", form: "现在分词短语", function: "后置定语", modifies: "修饰 people", explanation: "哪些人？正在照顾婴儿的人；care 必须与 for 连用。" },
    ], clauses: [] },
    literal: "但是，仍然可以为其他高风险群体的人接种：医护工作者、照顾婴儿的人和健康的年轻人。",
    natural: "不过，其他高风险人群仍可接种，包括医护人员、婴儿照护者和健康年轻人。",
    logic: "以可接种人群收束全文，呈现疫苗供应与风险分层管理的实际安排。",
    phrases: ["it was still possible to vaccinate", "people in other high-risk groups", "health care workers", "people caring for infants", "healthy young people"],
    answerWords: ["caring for"],
  },
];

const q = (
  number: number,
  sentenceId: string,
  prompt: string,
  options: [string, string, string, string],
  answer: "A" | "B" | "C" | "D",
  locating: string,
  explanations: Record<"A" | "B" | "C" | "D", string>,
): Question => ({
  id: 201000 + number,
  number,
  sentenceId,
  prompt,
  options: (["A", "B", "C", "D"] as const).map((key, index) => ({ key, text: options[index] })),
  answer,
  locating,
  explanations,
});

export const cloze2010Questions: Question[] = [
  q(1, "2010-cloze-s2", "the first worldwide epidemic ___ by the World Health Organization", ["criticized", "appointed", "commented", "designated"], "D", "空格后接 by 引出实施者，需用过去分词后置修饰 epidemic；designate 表官方认定、命名，符合世卫组织宣布疫情等级的语境。", {
    A: "criticized 表批评，世卫组织不是在评价疫情的缺点。", B: "appoint 通常任命人担任职务，不能任命一场 epidemic。", C: "comment 是评论，常用 comment on，不能直接构成 epidemic commented by。", D: "designated 表正式认定或指定，designated by WHO 结构与官方定级语义都准确。",
  }),
  q(2, "2010-cloze-s3", "The heightened alert ___ an emergency meeting", ["proceeded", "activated", "followed", "prompted"], "C", "语篇先写专家紧急会议，之后警戒升级；A followed B 表 A 发生在 B 之后。", {
    A: "proceed 表继续进行，常用 proceed with/to，不能直接表示在会议之后发生。", B: "activate 表启动设备或机制，会变成警戒启动会议，逻辑不符。", C: "followed 既可直接接 meeting，又准确表达先会议、后警戒升级。", D: "prompted 表促使，会变成警戒升级促使召开会议，因果顺序与原文相反。",
  }),
  q(3, "2010-cloze-s3", "rising ___ in Britain, Japan, Chile and elsewhere", ["digits", "numbers", "amounts", "sums"], "B", "语境谈可数病例数量，rising numbers 省略 of cases，表示病例数不断上升。", {
    A: "digits 是单个数字符号 0—9，不表示病例总量。", B: "numbers 可指人或病例的数量，rising numbers 搭配自然。", C: "amounts 通常修饰或指不可数事物的量，病例可数。", D: "sums 常指金额或算术总和，不用于病例增长。",
  }),
  q(4, "2010-cloze-s4", "the epidemic is ___ in severity", ["moderate", "normal", "unusual", "extreme"], "A", "下文给出绝大多数患者症状轻且完全康复，因此严重程度被评为中等，而不是极端。", {
    A: "moderate 表程度中等，与 mild symptoms 和 full recovery 一致。", B: "normal 表正常或常规，不能作为疫情严重度等级的准确评价。", C: "unusual 表异常，只说明罕见，不说明严重程度。", D: "extreme 表极端严重，与下文多数轻症相反。",
  }),
  q(5, "2010-cloze-s4", "___ the overwhelming majority of patients experiencing only mild symptoms", ["with", "in", "from", "by"], "A", "空后是名词 majority 加现在分词 experiencing，只有 with 可构成 with + 名词 + doing 的复合结构。", {
    A: "with 引出独立的伴随/依据结构，patients 是 experiencing 的逻辑主语。", B: "in 不能连接名词逻辑主语与现在分词形成此结构。", C: "from 表来源，无法说明多数患者的伴随情况。", D: "by doing 需要直接接动名词，不能先接 the majority of patients。",
  }),
  q(6, "2010-cloze-s4", "in the ___ of any medical treatment", ["progress", "absence", "presence", "favor"], "B", "患者往往未接受治疗也能完全康复；in the absence of 是‘在没有……的情况下’的固定结构。", {
    A: "in the progress of 不表示治疗进行中，通常说 in the process of。", B: "absence 与 without 对应，准确说明无治疗也康复。", C: "presence 表存在，会变成在治疗存在时，不支持多数病例较轻的强调。", D: "in favor of 表支持，不能表示是否接受治疗。",
  }),
  q(7, "2010-cloze-s5", "The outbreak came to global ___", ["reality", "phenomenon", "concept", "notice"], "D", "come to notice 是固定搭配，表示进入公众视野、受到注意；global 进一步说明关注范围。", {
    A: "come to reality 表成为现实，但疫情此前已经存在。", B: "phenomenon 是现象，不说 come to phenomenon。", C: "concept 是概念，不能表示全球开始关注。", D: "come to global notice 表引起全球注意，搭配完整。",
  }),
  q(8, "2010-cloze-s5", "hospitalizations and deaths ___ healthy adults", ["over", "for", "among", "to"], "C", "住院和死亡事件发生在健康成年人这一群体中，among 用于未逐一区分的群体内部。", {
    A: "over 可表关于或在上方，不能说明病例发生人群。", B: "for 表目的、原因或受益者，不表示人群内部出现事件。", C: "among healthy adults 表在健康成年人当中，范围关系准确。", D: "deaths to 不成立；to 不能同时连接 hospitalizations and deaths 与人群。",
  }),
  q(9, "2010-cloze-s6", "cases began to ___ in New York City", ["stay up", "crop up", "fill up", "cover up"], "B", "病例在多地开始意外、陆续出现；crop up 正是问题或事件‘冒出来’。", {
    A: "stay up 表熬夜或保持升起，不能以 cases 作主语表示出现。", B: "crop up 是不及物短语，表示突然或陆续出现，后接地点 in...。", C: "fill up 表填满，通常需要容器或空间对象。", D: "cover up 表掩盖，需有实施者和被掩盖对象，语义相反。",
  }),
  q(10, "2010-cloze-s7", "new cases seemed to fade ___ warmer weather arrived", ["as", "if", "unless", "until"], "A", "病例减弱与天气转暖同时发生，as 引导时间/伴随状语从句，可译为‘随着’。", {
    A: "as 表随着、当……时，准确连接两种同期变化。", B: "if 表条件，会变成是否转暖尚不确定，不符已发生的 arrived。", C: "unless 表除非，逻辑上要求否定条件。", D: "until 表持续到某一终点，但 fade 不是持续状态，且语义不合。",
  }),
  q(11, "2010-cloze-s8", "there was ___ flu activity in almost every state", ["excessive", "enormous", "significant", "magnificent"], "C", "官方报告强调流感活动已达到显著、值得关注的程度；significant 与 activity 搭配自然。", {
    A: "excessive 表超过合理限度，带规范评价，不是客观疫情强度报告的首选。", B: "enormous 通常修饰规模巨大的可感知事物或数量，与 flu activity 搭配生硬。", C: "significant 表显著且具有重要性，符合几乎每州均有活动的语境。", D: "magnificent 表壮丽、宏伟，带褒义，不能形容疫情。",
  }),
  q(12, "2010-cloze-s8", "virtually all the ___ tested are the new swine flu", ["categories", "examples", "patterns", "samples"], "D", "实验室检测对象是样本；samples tested 即被检测的样本。", {
    A: "categories 是类别，类别本身不是实验检测材料。", B: "examples 是例子，不与 tested 构成医学检验对象。", C: "patterns 是模式，通常由数据呈现而非被检测为病毒。", D: "samples 指采集的检验样本，医学语境准确。",
  }),
  q(13, "2010-cloze-s9", "it has ___ more than one million people", ["imparted", "immersed", "injected", "infected"], "D", "主语 it 指病毒；病毒使人感染，infect + people 是标准动宾搭配。", {
    A: "impart 表传授知识或赋予性质，通常 impart sth to sb。", B: "immerse 表使浸没或使沉浸，常用 immerse sb in。", C: "inject 表注射，通常是人把药物注入身体，主客体不合。", D: "infect 表使人感染疾病，语义和结构都准确。",
  }),
  q(14, "2010-cloze-s10", "Federal health officials ___ Tamiflu for children from the national stockpile", ["released", "relayed", "relieved", "remained"], "A", "卫生官员从国家储备中调拨并发放药物，release supplies from a stockpile 搭配准确。", {
    A: "released 表从储备中放出、投放物资，符合政府应急措施。", B: "relayed 表转传信息或接力运输，不表示正式调拨库存。", C: "relieved 表缓解痛苦或解除职务，不能接 Tamiflu 作此义。", D: "remained 是不及物动词，不能直接接 Tamiflu。",
  }),
  q(15, "2010-cloze-s10", "began ___ orders from the states", ["placing", "delivering", "taking", "giving"], "C", "take orders 是固定搭配，表示接受订单；订单来源是各州。", {
    A: "place an order 是下订单；主语若用 placing，就成联邦官员向各州下单，与 from the states 冲突。", B: "deliver orders 可指传达命令或交付订单，但不是接受订购。", C: "take orders from sb 表接受某人的订单，搭配和方向准确。", D: "give orders 表下命令，orders 会被误解为命令且方向相反。",
  }),
  q(16, "2010-cloze-s11", "The new vaccine ... is ___ ahead of expectations", ["feasible", "available", "reliable", "applicable"], "B", "ahead of expectations 说明供应时间早于预期；available 表疫苗已可获得、可供应。", {
    A: "feasible 评价计划或方法是否可行，不表示疫苗已经上市供应。", B: "available 表物品可获得，与时间进度 ahead of expectations 搭配自然。", C: "reliable 表可靠，不能说明供应时间。", D: "applicable 表规则或方法适用于某情况，不表示疫苗可得到。",
  }),
  q(17, "2010-cloze-s12", "most of those ___ doses", ["prevalent", "principal", "innovative", "initial"], "D", "上下文说 10 月初首批供应的三百多万剂；initial doses 指最初、首批剂量。", {
    A: "prevalent 表流行、普遍存在，通常修饰 disease/practice，不表示批次。", B: "principal 表主要的，会强调重要性而非时间先后。", C: "innovative 表创新的，疫苗剂量本身不按创新性区分。", D: "initial 表最初的、首批的，与 early October 的供应时间呼应。",
  }),
  q(18, "2010-cloze-s12", "which is not ___ for pregnant women", ["presented", "restricted", "recommended", "introduced"], "C", "医学建议使用 be recommended for + 人群；下文列出不适合该鼻喷剂的群体。", {
    A: "presented for 表提交或展示给，不说明医学适用性。", B: "restricted 常说 be restricted to 某范围或 restricted for reasons，介词和语义都不如 recommended。", C: "be recommended for sb 表建议某人使用，否定后即不建议该人群使用。", D: "introduced to 表向人介绍，不能表达疫苗禁忌。",
  }),
  q(19, "2010-cloze-s12", "breathing difficulties, heart disease or several other ___", ["problems", "issues", "agonies", "sufferings"], "A", "列举的是具体健康问题；health problems 是通用搭配，并能统摄呼吸困难和心脏病。", {
    A: "problems 可指疾病或健康障碍，other problems 与前两项同类。", B: "issues 多指议题或需要讨论的事项，直接指疾病不自然。", C: "agonies 强调剧痛或精神折磨，不是疾病类别总称。", D: "sufferings 指痛苦经历，通常不可数或不用于列举病症。",
  }),
  q(20, "2010-cloze-s13", "people ___ infants", ["involved in", "caring for", "concerned with", "warding off"], "B", "高风险人群包括照顾婴儿的人；care for infants 表照料婴儿，现在分词后置修饰 people。", {
    A: "involved in infants 结构和含义都不成立；involved in 后接活动。", B: "caring for infants 表照料婴儿，准确说明接触高风险人群的照护者。", C: "concerned with 表涉及或关注，不能说明日常照护和密切接触。", D: "ward off 表抵御疾病、危险，不能以 infants 作被抵御对象。",
  }),
];
