import type { BeginnerSyntaxComponent, BeginnerClauseDetail, SentenceAnalysis, SentenceReadingGuide, SyntaxVisualRole } from "./data";
import { withReviewedSyntax } from "./reviewed-syntax";
import { translation2010Practice } from "./2010-translation-practice";
const c=(text:string,form:string,fn:string,modifies:string,explanation:string,children?:BeginnerSyntaxComponent[]):BeginnerSyntaxComponent=>({text,form,function:fn,modifies,explanation,children});
const cl=(text:string,type:string,marker:string,role:string,subject:string,predicate:string,predicateDetails:BeginnerClauseDetail["predicateDetails"],translationOrder:string):BeginnerClauseDetail=>({text,type,marker,role,subject,predicate,predicateDetails,translationOrder});
const d=(fn:string,text:string)=>({function:fn,text});
const q=(question:string,evidence:string,answer:string)=>({question,evidence,answer});
type Reviewed={components:BeginnerSyntaxComponent[];colors:SyntaxVisualRole[];translations:string[];clauses:BeginnerClauseDetail[];reading:SentenceReadingGuide};
const r=(components:BeginnerSyntaxComponent[],colors:SyntaxVisualRole[],translations:string[],clauses:BeginnerClauseDetail[],focus:string,questions:SentenceReadingGuide["questions"]):Reviewed=>({components,colors,translations,clauses,reading:{focus,questions}});
const subject2="Having endured a painful period of unsustainability in his own life";
const content2="that sustainability-oriented values must be expressed through everyday action and choice";
const relative6="whose dilemma about the job translated, predictably, into a lack of sales";
const result8="that I would wake up in the middle of the night and stare at the ceiling";
const reviewed:Record<number,Reviewed>={
1:r([c('"Sustainability"',"抽象名词，术语引号","第一分句主语","has become","谈论可持续性这个概念。"),c("has become","现在完成时系动词","第一分句谓语","Sustainability","已经成为，强调当前形成的状态。"),c("a popular word","名词短语","表语","has become","说明概念成为流行词；不是become的动作宾语。"),c("these days","时间名词短语","时间状语","has become","近来、如今，不指定若干天。"),c("but","并列连词","转折连接","两个完整分句","由社会流行转向个人体验。"),c("to Ted Ning","介词短语","观点状语","the concept will always have personal meaning","对宁而言，不是运动方向。"),c("the concept","名词短语","第二分句主语","will have","回指Sustainability。"),c("will always have","情态动词及实义动词、频度副词","第二分句谓语","the concept","will have表示将具有，always强调始终。",[c("always","副词","时间持续性修饰","have","意义始终存在。")]),c("personal meaning","名词短语","宾语","have","概念对宁具有切身意义。")],["subject","predicate","complement","modifier","connector","modifier","subject","predicate","object"],["可持续性","已成为","一个流行词","如今","但是","对特德·宁而言","这个概念","始终会有","切身意义"],[],"but并列两个完整判断；前一个become接表语，后一个have接宾语。",[q("concept是否另一个新概念？","the concept will always have personal meaning","不是。the concept回指可持续性，to Ted Ning限定观察视角；下文用个人经历解释它为何有切身意义。")]),
2:r([c(subject2,"动名词完成式短语","主语","made","整个经历是主语；Having不独立充当主句谓语。",[c("Having endured","完成式动名词","非谓语核心","整个主语短语","having加过去分词表示此前已经历。"),c("a painful period of unsustainability","名词及of限定","endured的宾语","endured","经历生活难以为继的痛苦时期。",[c("of unsustainability","介词短语","后置限定","period","说明时期的状态。")]),c("in his own life","介词短语","经历范围状语","endured","发生在宁自己的生活中，his指宁。")]),c("made","一般过去时实义动词","谓语","整个动名词主语","这段经历使某件事变得清楚。"),c("it","形式代词","形式宾语","made","先占位置，后置that从句给出真正内容。"),c("clear","形容词","宾语补足语","it所代表的内容","补充内容清楚这一状态。"),c("to him","介词短语","感受者补足语","clear","对宁而言清楚。"),c(content2,"that内容从句","后置真正宾语","made it clear","说明明白的内容。",[c("sustainability-oriented values","复合形容词及复数名词","从句主语","must be expressed","以可持续性为导向的价值观。"),c("must be expressed","情态被动结构","从句谓语","values","必须通过实践得到体现，并非已经实现。"),c("through everyday action and choice","介词及并列名词","途径状语","be expressed","everyday限定日常行动与选择。")])],["subject","predicate","object","complement","modifier","object"],["曾在自己的生活中经历一段难以为继的痛苦时期","使","这一点","清楚起来","对他而言","以可持续性为导向的价值观必须通过日常行动和选择体现出来"],[cl(content2,"后置宾语从句","that","补出形式宾语it的内容","sustainability-oriented values","must be expressed",[d("途径状语","through everyday action and choice")],"先译经历使他明白，再译必须通过行动和选择体现价值观。")],"先找到made和它前面的完整经历主语；it不是回指这段经历，而是占位等待that的内容。",[q("Having endured能当作省略主语的原因状语吗？",subject2+" made it clear","不能。去掉整个Having短语，made就没有主语；这里完成式动名词短语整体承担主语。"),q("must be expressed表示价值观已经落实了吗？","must be expressed through everyday action and choice","没有。must表示必要性，be expressed为被动；原文提出应怎样体现价值观，不能译成已经做到。")]),
3:r([c("Ning","专名","主语","recalls","回忆者为宁。"),c("recalls","一般现在时","谓语","Ning","回忆以往经历，后接动名词。"),c("spending a confusing year in the late 1990s selling insurance","动名词短语","宾语","recalls","回忆花一年卖保险这段经历。",[c("spending","动名词","宾语短语核心","recalls","recall doing为回忆已经做过。"),c("a confusing year","名词短语","时间宾语","spending","花去的一年，其经历令人困惑。"),c("in the late 1990s","介词短语","时间状语","spending所述经历","在20世纪90年代末，不修饰现在回忆行为。"),c("selling insurance","动名词短语","活动补足语","spending a confusing year","spend time doing说明时间花在哪项活动上；insurance是selling宾语。")])],["subject","predicate","object"],["宁","回忆起","在20世纪90年代末卖保险，度过了令人困惑的一年"],[],"recall doing套入spend time doing：spending与selling分别受不同结构支配，执行者都为宁。",[q("spending和selling是两个并列谓语吗？","recalls spending a confusing year in the late 1990s selling insurance","不是。recalls为主句谓语；spending短语作宾语，selling说明那一年所做活动，没有and把二者并列。")]),
4:r([c("He'd","主语和助动词缩写","主语与完成时助动词","been through","He为宁，'d在been前只能为had。"),c("been","过去分词","第一谓语的实义核心","He'd","与前面的had构成过去完成时。"),c("through the dot-com boom and burst","介词及并列名词","经历内容补足语","been","经历互联网行业兴衰；原卷burst不改字。",[c("the dot-com boom and burst","并列名词短语","介词宾语","through","第一个and只连接boom与burst。")]),c("and","并列连词","谓语部分连接","been through与signed on","与前一名词内部and层次不同。"),c("desperate for a job","形容词短语","主语状态补充，兼表原因","He及其signed on行为","没有限定动词；描述宁急于求职，不修饰agency。"),c("signed on","短语动词","第二并列谓语部分","He","签约加入；signed过去式和过去分词同形，不据此强推另一具体时点。"),c("with a Boulder agency","介词短语","签约对象补足语","signed on","与博尔德一家机构签约，结合前句为保险代理机构。")],["subject","predicate","complement","connector","modifier","predicate","complement"],["他此前已经","经历","互联网行业的繁荣与泡沫破裂","并且","因急于找到工作","签约入职","博尔德的一家代理机构"],[],"'d必须读had；两个and层级不同，desperate短语插在第二个谓语前说明主语处境。",[q("desperate修饰机构还是求职者？","and, desperate for a job, signed on with a Boulder agency","修饰He即宁；短语补其迫切求职的状态，也解释选择动机。不能译为一家急需工作的机构。"),q("原文明确了互联网行业每一阶段的具体年份吗？","the dot-com boom and burst","没有。保留经历兴衰的背景，与上一句年代并读，不补造具体起止年份，也不擅改原卷burst为bust。")]),
5:r([c("It","回指代词","主语","didn't go","指卖保险这份工作的开展情况。"),c("didn't go","一般过去时否定","谓语","It","did承担过去时，go用原形；go指进展。"),c("well","副词","方式状语","go","否定整体表示不顺利。")],["subject","predicate","modifier"],["这份工作","进展得并不","顺利"],[],"It有具体语境所指；go well是进展顺利，并非走路方式。",[q("It与第2句it用法相同吗？","It didn't go well","不同。本句It回指这份工作的情况；第2句it为形式宾语，真正内容在后置that从句。")]),
6:r([c('"It was a really bad move because that\'s not my passion,"',"直接引语","前置引述内容","says","宁对入职决定的评价及原因。",[c("It","代词","引语主语","was","回指接受该工作的决定。"),c("was","过去时系动词","引语谓语","It","引出决定的性质。"),c("a really bad move","名词短语","表语","was","move指决定或举措，really修饰bad。"),c("because that's not my passion","原因从句","原因状语","It was a really bad move","原因在于卖保险并非自己热爱的事情。",[c("that's","代词与系动词缩写","从句主语与谓语","that is","that是指示代词，is为谓语，不是连接词。"),c("not my passion","否定词及名词表语","否定判断内容","is","my指引语说话人宁。")])]),c("says","一般现在时报道动词","谓语","后置主语Ning","引述置前时报道框架倒装。"),c("Ning","专名","主语","says","引语来自宁。"),c(relative6,"非限制性关系从句","补充定语","Ning","whose表示宁的，评注结果在引语外。",[c("whose dilemma about the job","关系限定词及名词短语","从句主语","translated","whose限定dilemma，about限定工作方面的两难。"),c("translated","一般过去时实义动词","从句谓语","dilemma","转化为、表现为结果。"),c("predictably","评注副词","整件事的评注","困境表现为销售不佳这一事件","作者称这一结果不出所料。"),c("into a lack of sales","介词短语","结果补足语","translated","销售不足，不断言完全没有成交。")])],["object","predicate","subject","modifier"],["这个决定实在很糟，因为卖保险并非我热爱的工作","说道","宁","他在工作上的两难处境，不出所料地表现为销售业绩欠佳"],[cl("because that's not my passion","原因状语从句","because","引语内部说明bad move的原因","that（卖保险）","is（that's中的系动词，受not否定）",[d("表语","my passion")],"把这不是自己热爱的工作译成决定糟糕的原因。"),cl(relative6,"非限制性定语从句","whose","补充Ning的处境及后果","whose dilemma about the job","translated",[d("评注状语","predictably"),d("结果补足语","into a lack of sales")],"whose还原为他的，再译困境表现为销售不足。")],"分清引语内的because原因与引语外的whose后果；says Ning标明谁说了什么。",[q("whose从句是否也是宁引号内原话？",'says Ning, '+relative6,"不是。引号已经在passion后关闭；whose从句由叙述者补充Ning的困境和结果。"),q("translate在本句是语言翻译吗？","translated, predictably, into a lack of sales","不是。主语是困境，into接销售不足这一结果，表示转化为、表现为。")]),
7:r([c("I","第一人称代词","主语","was","新引语说话者宁。"),c("was","过去时系动词","谓语","I","描述当时状态。"),c("miserable","形容词","表语","was","精神痛苦，后文焦虑行为加以展开。")],["subject","predicate","complement"],["我","当时","非常痛苦"],[],"主系表句概括感受；双引号从本句开启，直至第10句才结束。",[q("miserable是否已经断言身体受伤？","I was miserable","没有。结合后文焦虑、失眠和经济压力，应读为精神痛苦，不能补出原文没有的身体伤害。")]),
8:r([c("I","人称代词","主语","had","宁回忆自己。"),c("had","实义动词过去式","谓语","I","有某种情绪，不是完成时助动词。"),c("so much anxiety","程度限定的不可数名词","宾语","had","so much说明焦虑很重，并与that呼应。"),c(result8,"that结果从句","结果状语","so much anxiety","焦虑严重到反复出现夜醒与凝视。",[c("I","代词","从句主语","would wake up及stare","两个动作同为宁执行。"),c("would wake up","情态词及短语动词","第一并列谓语","I","would表示过去反复发生，wake up在此不及物。"),c("in the middle of the night","介词短语","时间状语","wake up","半夜。"),c("and stare","并列连接及原形动词","第二并列谓语部分","I，共用would","stare与wake up并列，不落回主句had。"),c("at the ceiling","介词短语","注视对象补足语","stare","指房间天花板。")])],["subject","predicate","object","modifier"],["我","感到","如此强烈的焦虑","以至于常会半夜醒来，盯着天花板"],[cl(result8,"结果状语从句","that，与so much呼应","说明焦虑所造成的行为后果","I","would wake up；（would）stare",[d("wake up的时间状语","in the middle of the night"),d("stare的注视对象补足语","at the ceiling")],"先译焦虑程度，再译常常半夜醒来并盯着天花板。")],"that从句范围须包含and后的第二动作；would表过去反复习惯，不是虚拟条件。",[q("stare的主语是谁、助动词在哪里？","I would wake up in the middle of the night and stare at the ceiling","主语仍为结果从句中的I，与wake up共用would；不能把stare并列到主句had。")]),
9:r([c("I","代词","主语","had和needed","共享主语为宁。"),c("had no money","否定动宾结构","第一谓语部分","I","had为实义动词过去式，否定在宾语no money中。",[c("had","实义动词过去式","谓语核心","I","表示拥有。"),c("no money","否定限定名词","宾语","had","没有钱，money不可数。")]),c("and","并列连词","谓语连接","had与needed","两方面共同解释不能轻易放弃工作。"),c("needed","实义动词过去式","第二分句谓语","I","直接接名词宾语，不是情态动词。"),c("the job","名词短语","宾语","needed","定冠词回指卖保险的工作。")],["subject","predicate","connector","predicate","object"],["我","没有钱","又","需要","这份工作"],[],"两个实义动词共用主语；没有钱与需要工作一起构成兴趣之外的现实约束。",[q("needed后为什么可以直接接the job？","needed the job","need这里为实义动词，needed带过去式标记，the job作名词宾语；不是情态need后接动词原形。")]),
10:r([c("Everyone","不定代词","主语","said","周围劝慰宁的人。"),c("said","一般过去时报道动词","谓语","Everyone","后接他们当时说的话。"),c("Just wait","祈使分句","第一项引语","said","省略主语you即宁；Just缓和建议。",[c("Just","副词","语气修饰","wait","且再、只需，不是刚刚。"),c("wait","动词原形","祈使谓语","省略you","劝听话人等待。")]),c("you'll turn the corner","陈述分句","第二项引语","said","他人鼓励宁将会渡过难关。",[c("you'll","主语及情态词缩写","主语及助动词","turn","you will，you指宁。"),c("turn","动词原形","实义谓语核心","you'll","与the corner构成好转的习语。"),c("the corner","名词短语","宾语","turn","习语中的转折点，不指现实街角。")]),c("give it some time","祈使分句","第三项引语","said","再劝他给工作处境发展留时间。",[c("give","动词原形","祈使谓语","省略you","后接双宾语。"),c("it","代词","间接宾语","give","指这份工作及处境的发展。"),c("some time","不可数名词短语","直接宾语","give","给出的时间，不是次数。")])],["subject","predicate","object","object","object"],["大家","都说","再等等吧","你会迎来转机的","再给这件事一点时间"],[],"三项引语由逗号并置，两个祈使夹一个陈述；单引号包大家的话，末尾双引号结束宁的自述。",[q("最后一句证明宁之后一定成功了吗？","Everyone said, 'Just wait, you'll turn the corner, give it some time.'","没有。you'll turn the corner是周围人当时的鼓励，文章没有叙述其后结局。"),q("give中it和time分别作什么？","give it some time","it是间接宾语，指工作处境的发展；some time为直接宾语，指给出的一些时间。")]),
};
export function reviewTranslation2010(sentence:SentenceAnalysis):SentenceAnalysis {
 const value=reviewed[sentence.number];
 const result=withReviewedSyntax({...sentence,beginnerSyntax:{components:value.components,clauses:value.clauses,reading:value.reading},practice:translation2010Practice[sentence.number]},value.colors);
 return {...result,translationAlignment:result.chunks.map((chunk,i)=>({english:chunk.text,chinese:value.translations[i]})),translationNotes:["词块对译跟随原文成分顺序，完整中文表达请看自然译文；引号和标点按原卷保留。",...sentence.grammar]};
}
