import type { ContextualSubstitution } from "./contextual-vocabulary";

export type Cloze2010LexiconEntry = {
  partOfSpeech: string; contextualMeaning: string; use: string; specialForms?: string[];
  examSynonyms?: string[]; collocations?: string[]; otherMeanings?: string[]; wordFamily?: string[];
  confusions?: string[]; contextualSubstitutions?: ContextualSubstitution[];
};

const e = (partOfSpeech: string, contextualMeaning: string, use: string, extra: Partial<Cloze2010LexiconEntry> = {}): Cloze2010LexiconEntry => ({ partOfSpeech, contextualMeaning, use, specialForms: ["按词性和语境辨认词形；规则变化见原文形式"], examSynonyms: ["近义替换需同时核对搭配、语气和句法"], ...extra });

export const cloze2010LemmaAliases: Record<string, string> = {
  detected: "detect", declared: "declare", designated: "designate", heightened: "heighten", followed: "follow",
  experts: "expert", assembled: "assemble", rising: "rise", numbers: "number", patients: "patient", noted: "note",
  experiencing: "experience", symptoms: "symptom", hospitalizations: "hospitalization", deaths: "death", adults: "adult",
  cases: "case", seemed: "seem", warmer: "warm", arrived: "arrive", officials: "official", reported: "report",
  samples: "sample", tested: "test", known: "know", infected: "infect", caused: "cause", released: "release",
  children: "child", orders: "order", states: "state", expectations: "expectation", doses: "dose",
  recommended: "recommend", women: "woman", difficulties: "difficulty", problems: "problem", groups: "group",
  workers: "worker", caring: "care", infants: "infant", people: "person", "organization's": "organization",
  criticized: "criticize", appointed: "appoint", commented: "comment", proceeded: "proceed", activated: "activate",
  prompted: "prompt", digits: "digit", amounts: "amount", sums: "sum", categories: "category", examples: "example",
  patterns: "pattern", imparted: "impart", immersed: "immerse", injected: "inject", relayed: "relay", relieved: "relieve",
  remained: "remain", placing: "place", delivering: "deliver", presented: "present", restricted: "restrict",
  introduced: "introduce", issues: "issue", agonies: "agony", sufferings: "suffering", involved: "involve",
  concerned: "concern", warding: "ward", healthy: "health", worldwide: "worldwide", southwestern: "southwestern",
};

const rows: Record<string, [string, string, string]> = {
  follow:["v.","跟随；发生在……之后","A followed B 表先 B 后 A。"], cause:["v./n.","造成；原因","cause deaths/hospitalizations 表导致死亡或住院。"],
  outbreak:["n.","暴发；突然发生","the outbreak of swine flu 中作主语中心词。"], swine:["n./adj.","猪；猪的","swine flu 是猪流感的固定医学称呼。"], flu:["n.（通常不可数）","流感","swine flu / seasonal flu 中指流感类型。"],
  detect:["v.","发现；检测出","be detected in 表在某地经监测被发现。"], mexico:["proper n.","墨西哥","in Mexico 作首次发现地点状语。"], declare:["v.","宣布；宣告","declare A B 表宣布 A 为 B。"], global:["adj.","全球的","global epidemic/notice 表全球范围。"], epidemic:["n./adj.","流行病；流行性的","本篇作名词，指跨地区传播的疫情。"], june:["proper n.","六月","on June 11 用于具体日期。"], worldwide:["adj./adv.","世界范围的/地","worldwide epidemic 中作前置定语。"],
  designate:["v.","正式指定；认定","designated by WHO 是过去分词后置定语。"], health:["n./adj.","健康；卫生的","health officials/workers 中作领域定语。"], organization:["n.","组织；机构","World Health Organization 指世界卫生组织。"],
  heighten:["v.","提高；加强","heightened alert 是过去分词形容词修饰警戒。"], alert:["n./adj./v.","警戒；警觉的；提醒","the heightened alert 中作名词。"], emergency:["n./adj.","紧急情况；紧急的","emergency meeting 指紧急会议。"], meeting:["n.","会议","follow an emergency meeting 表会议之后发生。"], expert:["n./adj.","专家；熟练的","flu experts 指流感专家。"], geneva:["proper n.","日内瓦","in Geneva 作会议地点。"], assemble:["v.","集合；召集","that assembled 中表示专家集合开会。"], sharp:["adj./adv.","急剧的；尖锐的","a sharp rise 中修饰上升幅度。"], rise:["n./v.","上升；增加","a rise in cases 为名词；rising numbers 为分词定语。"], australia:["proper n.","澳大利亚","in Australia 作病例地点。"], number:["n./v.","数量；编号","rising numbers 指不断上升的病例数。"], chile:["proper n.","智利","与 Britain、Japan 并列作地点。"], elsewhere:["adv.","在别处；其他地方","列举地点后概括其他地区。"],
  moderate:["adj./v.","中等的；缓和","本句作表语，评价疫情严重程度中等。"], severity:["n.","严重程度","in severity 限定评价维度。"], margaret:["proper n.","Margaret（人名）","Margaret Chan 的名字。"], chan:["proper n.","Chan（姓氏）","Margaret Chan 的姓氏。"], director:["n.","负责人；主管","director general 是组织总干事职衔。"], general:["adj./n.","总的；将军","director general 中后置构成总干事职衔。"], overwhelming:["adj.","压倒性的；占绝大多数的","overwhelming majority 强调比例极高。"], patient:["n./adj.","患者；耐心的","本篇作名词，指感染患者。"], experience:["v./n.","经历；体验","patients experiencing... 是 with 复合结构。"], mild:["adj.","轻微的；温和的","mild symptoms 表症状较轻。"], symptom:["n.","症状","patients experience symptoms。"], recovery:["n.","康复；恢复","a full recovery 表完全康复。"], absence:["n.","缺少；缺席","in the absence of 表在没有……时。"], medical:["adj.","医疗的；医学的","medical treatment 指医疗治疗。"], treatment:["n.","治疗；处理","本句指医疗治疗。"],
  notice:["n./v.","注意；注意到","come to notice 是进入公众视野。"], april:["proper n.","四月","in late April 表四月下旬。"], mexican:["adj./n.","墨西哥的；墨西哥人","Mexican authorities 中作定语。"], authority:["n.","当局；权威","authorities 复数表示政府主管部门。"], note:["v./n.","注意到；记录","authorities noted 后接异常数据。"], unusually:["adv.","异常地","修饰 large，表示数量异常多。"], hospitalization:["n.","住院；住院病例","与 deaths 并列作统计项目。"], death:["n.","死亡；死亡人数","caused deaths 表造成死亡。"], adult:["n./adj.","成年人；成年的","healthy adults 指健康成年人。"],
  shut:["v./adj.","关闭；停止运转","shut down 表城市活动停摆。"], height:["n.","高度；顶峰","at the height of 表在最严重时。"], panic:["n./v./adj.","恐慌","at the height of a panic 指恐慌顶峰。"], crop:["v./n.","突然出现（crop up）；作物","crop up 整体表示病例陆续出现。"], york:["proper n.","约克；纽约名称组成","New York City 的专名组成。"], southwestern:["adj.","西南部的","the southwestern United States 指美国西南部。"], around:["prep./adv.","在……各处；围绕","around the world 表世界各地。"],
  case:["n.","病例；情况","new cases 在本文指新增病例。"], seem:["v.","似乎；看来","seem to fade 表带保留的观察判断。"], warm:["adj./v.","温暖的；变暖","warmer weather 为比较级。"], arrive:["v.","到来；抵达","weather arrived 表暖和天气到来。"], weather:["n./v.","天气；经受住","本篇作不可数名词。"], september:["proper n.","九月","in late September 作时间状语。"], official:["n./adj.","官员；官方的","officials reported 中作复数主语。"], report:["v./n.","报告；报道","后接两个 that 宾语从句。"], significant:["adj.","显著的；重要的","significant flu activity 表值得关注的活动水平。"], virtually:["adv.","几乎；实际上","virtually all 表几乎全部。"], sample:["n./v.","样本；抽样","samples tested 指受检样本。"], test:["v./n.","检测；测试","tested 是过去分词后置修饰 samples。"], know:["v.","知道；称为","be known as 表被称作。"], seasonal:["adj.","季节性的","seasonal flu 指季节性流感。"],
  infect:["v.","使感染","病毒作主语，people 作宾语。"], federal:["adj.","联邦的","Federal health officials 指联邦卫生官员。"], release:["v./n.","释放；投放","从国家储备中调拨药物。"], tamiflu:["proper n.","达菲（抗流感药）","released Tamiflu for children 中作宾语。"], child:["n.","儿童","for children 引出药品适用人群。"], stockpile:["n./v.","储备；储存","national stockpile 指国家应急药品储备。"], order:["n./v.","订单；订购；命令","take orders from 表接收订单。"], state:["n.","州；状态","the states 在美国语境指各州。"], vaccine:["n.","疫苗","swine flu vaccine 是针对该病毒的疫苗。"], annual:["adj.","每年的；年度的","annual flu vaccine 指每年使用的季节性疫苗。"], available:["adj.","可获得的；可供应的","is available 表已进入供应。"], expectation:["n.","预期；期待","ahead of expectations 表早于预期。"], dose:["n./v.","一剂；给药","three million doses 是疫苗剂量。"], october:["proper n.","十月","in early October 作时间状语。"], initial:["adj./n.","最初的；首批的；首字母","initial doses 指首批供应。"], flumist:["proper n.","FluMist（鼻喷流感疫苗商品名）","限定 nasal spray type。"], nasal:["adj.","鼻的；鼻腔的","nasal spray 表鼻喷剂。"], spray:["n./v.","喷雾；喷洒","nasal spray type 指鼻喷剂型。"], recommend:["v.","推荐；建议","be recommended for 表建议某人群使用。"], pregnant:["adj.","怀孕的","pregnant women 指孕妇。"], woman:["n.","女性；妇女","pregnant women 中用复数形式。"], breathe:["v.","呼吸","breathing difficulties 表呼吸困难。"], breathing:["n./adj.","呼吸；呼吸的","作 difficulties 的定语。"], difficulty:["n.","困难；障碍","breathing difficulties 为复数健康问题。"], disease:["n.","疾病","heart disease 指心脏病。"], problem:["n.","问题；健康障碍","other problems 统摄其他疾病或状况。"], vaccinate:["v.","给……接种疫苗","to vaccinate 是形式主语 it 所替代的真正主语。"], "high-risk":["adj.","高风险的","置于 groups 前作复合形容词。"], group:["n.","群体；组","high-risk groups 指高风险人群类别。"], worker:["n.","工作者","health care workers 指医护人员。"], care:["v./n.","照料；护理","care for infants 表照顾婴儿。"], infant:["n./adj.","婴儿；婴儿的","caring for infants 中作介词宾语。"],
  criticize:["v.","批评","第 1 题干扰项，不表示官方认定。"], appoint:["v.","任命；指定时间","第 1 题干扰项，通常任命人。"], comment:["v./n.","评论","常用 comment on，不能直接替代 designated。"], proceed:["v.","继续；前进","常接 with/to，不表示发生在会议之后。"], activate:["v.","启动；激活","第 2 题干扰项，会造成错误因果。"], prompt:["v./adj./n.","促使；迅速的；提示","prompt A to do 表促使，与 follow 的先后关系不同。"], digit:["n.","数字；数位","只指数字符号，不指病例数量。"], amount:["n./v.","数量；总计","常用于不可数事物，不能替换可数病例 numbers。"], sum:["n./v.","总数；金额；合计","常指算术或金钱总和。"], normal:["adj./n.","正常的；常态","不等于疫情严重程度的 moderate。"], unusual:["adj.","不同寻常的","评价罕见性，不直接评价严重度。"], extreme:["adj./n.","极端的；极端","与多数轻症的语境相反。"], presence:["n.","存在；在场","in the presence of 与 absence 意义相反。"], favor:["n./v.","支持；赞同；偏爱","in favor of 表支持，不表缺少。"], reality:["n.","现实","come to reality 表成为现实，非引起注意。"], phenomenon:["n.","现象","不能构成 come to phenomenon。"], concept:["n.","概念","不表示受到公众关注。"], stay:["v./n.","停留；保持","stay up 表熬夜或保持不倒。"], fill:["v./n.","填满","fill up 需要容器或空间语义。"], cover:["v./n.","覆盖；掩盖","cover up 表掩饰。"], unless:["conj.","除非","引导否定条件，不合天气同期变化。"], excessive:["adj.","过度的","强调超过合理限度。"], enormous:["adj.","巨大的","强调规模，修饰 flu activity 不如 significant。"], magnificent:["adj.","壮丽的；宏伟的","褒义词，不能形容疫情活动。"], category:["n.","类别","类别不是医学检测材料。"], example:["n.","例子","不等于实验室 sample。"], pattern:["n.","模式；样式","模式由数据呈现，不是受检样本。"], impart:["v.","传授；赋予","常用 impart sth to sb，不表示感染。"], immerse:["v.","使浸没；使沉浸","常用 immerse sb in。"], inject:["v.","注射；注入","人给药，不表示病毒使人感染。"], relay:["v./n.","转传；接力","不表示从储备正式投放药品。"], relieve:["v.","缓解；解除","不能以 Tamiflu 作宾语表达调拨。"], remain:["v.","仍然；保持","不及物，不能直接接 Tamiflu。"], place:["v./n.","放置；下订单","place an order 是下单，与 take orders 方向相反。"], deliver:["v.","递送；发表","不能表示从各州接受订单。"], give:["v.","给；下达","give orders 常指下命令。"], feasible:["adj.","可行的","通常评价计划或方法。"], reliable:["adj.","可靠的","评价可信度而非供应时间。"], applicable:["adj.","适用的","常用 applicable to，不表示可获得。"], prevalent:["adj.","流行的；普遍的","不表示时间顺序上的首批。"], principal:["adj./n.","主要的；负责人","强调重要性，不等于 initial。"], innovative:["adj.","创新的","评价创新性，不说明批次。"], present:["v./adj./n.","呈现；在场的；礼物","be presented for 不表示建议使用。"], restrict:["v.","限制","常用 be restricted to，与 recommended for 不同。"], introduce:["v.","介绍；引入","be introduced to 表被介绍给。"], issue:["n./v.","议题；发布","健康语境直接指疾病不如 problem。"], agony:["n.","剧痛；痛苦","不作为疾病类别总称。"], suffering:["n.","痛苦；苦难","强调感受，不是具体健康问题类别。"], involve:["v.","涉及；使参与","involved in 后接活动，不接 infants。"], concern:["v./n.","涉及；关心；担忧","concerned with 表涉及，不等于照料。"], ward:["v./n.","抵御；病房","ward off 表抵御危险，不能接 infants。"], person:["n.","人","people 是 person 的常用复数。"],
  discover:["v.","发现","可替换 detect，但弱化监测识别色彩。"], classify:["v.","分类；归类","classify A as B 表把 A 归入 B 类。"], increase:["n./v.","增加；上升","a sharp increase 可替换 a sharp rise。"], vast:["adj.","广大的；大量的","vast majority 表绝大多数。"], observe:["v.","观察到；遵守","可替换 note 表通过观察注意到。"], emerge:["v.","出现；显现","cases emerge 表病例出现。"], subside:["v.","逐渐平息；减弱","常以疫情、疼痛、风暴等作主语。"], substantial:["adj.","大量的；实质性的","可形容达到相当规模的活动。"], distribute:["v.","分发；分配","distribute supplies 表向多方调配物资。"], obtainable:["adj.","可获得的","强调能够取得。"], first:["ordinal/adj./adv.","第一的；最先","可直白替换 initial 表首批。"],
};

export const cloze2010Lexicon: Record<string, Cloze2010LexiconEntry> = Object.fromEntries(Object.entries(rows).map(([word, [pos, meaning, use]]) => [word, e(pos, meaning, use)]));
Object.assign(cloze2010Lexicon, {
  designate: e("v.", "正式指定；认定", "designated by WHO 是过去分词后置定语。", { specialForms:["designate—designated—designated—designating"], examSynonyms:["classify（归类，常接 as）", "declare（正式宣布）"], collocations:["designate A as B", "be designated by an authority"] }),
  follow: e("v.", "发生在……之后", "A followed B 表先 B 后 A。", { specialForms:["follow—followed—followed—following"], examSynonyms:["come after（随后发生）", "ensue（随后发生，常不及物）"], confusions:["follow 表 A 在 B 后；prompt 表 A 促使 B，方向不同。"] }),
  number: e("n./v.", "数量；数目", "rising numbers 省略 of cases，指病例数上升。", { specialForms:["number—numbers（复数/三单）—numbered—numbering"], examSynonyms:["figure（统计数字）", "quantity（数量，范围更广）"], confusions:["a number of + 复数谓语；the number of + 单数谓语。"] }),
  moderate: e("adj./v.", "中等的", "be moderate in severity 评价严重程度。", { specialForms:["moderate—more moderate—most moderate；moderate—moderated—moderating（动词）"], examSynonyms:["mild（温和的，程度更轻）", "medium（中等大小/水平）"], confusions:["moderate 指程度中等；normal 指符合常态。"] }),
  absence: e("n.", "缺少；不存在", "in the absence of 表在没有……的情况下。", { specialForms:["absence—absences（复数）"], examSynonyms:["lack（缺乏）", "nonexistence（不存在）"], wordFamily:["absent adj. 缺席的；不存在的"] }),
  notice: e("n./v.", "注意；关注", "come to global notice 表进入全球视野。", { specialForms:["notice—noticed—noticed—noticing"], examSynonyms:["attention（注意）", "awareness（意识、知晓）"], collocations:["come to notice", "take notice of"] }),
  crop: e("v./n.", "突然出现（crop up）", "cases began to crop up 表病例开始在多地陆续出现。", { specialForms:["crop—cropped—cropped—cropping（动词双写 p）"], examSynonyms:["emerge（出现，较正式）", "arise（出现、产生）"], collocations:["crop up"] }),
  significant: e("adj.", "显著且值得关注的", "significant flu activity 是 there be 句实际主语。", { specialForms:["significant—more significant—most significant"], examSynonyms:["substantial（大量的/实质性的）", "notable（值得注意的）"], wordFamily:["significance n. 重要性", "significantly adv. 显著地"] }),
  sample: e("n./v.", "检验样本", "samples tested 指实验室受检样本。", { specialForms:["sample—samples；sampled—sampled—sampling"], examSynonyms:["specimen（检验标本）", "selection（抽取的一部分）"], confusions:["sample 是样本；example 是说明观点的例子。"] }),
  infect: e("v.", "使感染", "病毒作主语，more than one million people 作宾语。", { specialForms:["infect—infected—infected—infecting"], examSynonyms:["transmit to（传播给，需调整结构）", "contaminate（污染，不必然使人患病）"], wordFamily:["infection n. 感染", "infectious adj. 传染性的", "infected adj. 已感染的"] }),
  release: e("v./n.", "从储备中调拨、投放", "release Tamiflu from the stockpile 表把药品投入使用。", { specialForms:["release—released—released—releasing"], examSynonyms:["distribute（分发）", "issue（发放）"], collocations:["release supplies from a stockpile"] }),
  available: e("adj.", "可获得；可供应", "vaccine is available 表疫苗已经可以取得。", { specialForms:["形容词无普通词形变化；比较级 more available，最高级 most available"], examSynonyms:["obtainable（可获得的）", "accessible（可接近/可使用的）"], confusions:["人 is available 常表示有空；物 is available 表可获得。"] }),
  initial: e("adj./n.", "最初的；首批的", "initial doses 按供应时间说明首批剂量。", { specialForms:["形容词无普通词形变化；initials 为名词复数‘姓名首字母’"], examSynonyms:["first（第一批的）", "preliminary（初步的）"], confusions:["initial 强调时间起点；principal 强调最主要。"] }),
  recommend: e("v.", "推荐；建议使用", "be recommended for + 人群说明适用对象。", { specialForms:["recommend—recommended—recommended—recommending"], examSynonyms:["advise（劝告，常接人）", "suggest（建议）"], collocations:["be recommended for", "recommend doing", "recommend that sb (should) do"] }),
  problem: e("n.", "健康问题；疾病状况", "other problems 统摄前列的呼吸困难和心脏病。", { specialForms:["problem—problems（复数）"], examSynonyms:["condition（健康状况）", "disorder（机能紊乱）"], confusions:["issue 常指议题；具体健康障碍通常用 problem/condition。"] }),
  care: e("v./n.", "照料；护理", "caring for infants 是现在分词后置修饰 people。", { specialForms:["care—cared—cared—caring（去 e）"], examSynonyms:["look after（照顾，较口语）", "tend（照料病人/需要照顾者）"], collocations:["care for infants", "health care"], confusions:["care for 表照料；care about 强调在意、关心。"] }),
});
export const cloze2010FormPartOfSpeech: Record<string, string> = Object.fromEntries(Object.entries(cloze2010LemmaAliases).map(([form, lemma]) => [form, `${rows[lemma]?.[0] ?? "word"}（${lemma} 的本句变形）`]));
export const cloze2010FamilyAliases: Record<string, string> = { detection:"detect", declaration:"declare", designation:"designate", severity:"severe", recovery:"recover", absence:"absent", hospitalization:"hospitalize", infection:"infect", recommendation:"recommend", vaccination:"vaccinate", breathing:"breathe" };
