import type { BeginnerClauseDetail, BeginnerSyntaxComponent, SyntaxVisualRole } from "./data";
const c = (text: string, form: string, fn: string, modifies: string, explanation: string, children?: BeginnerSyntaxComponent[]): BeginnerSyntaxComponent => ({ text, form, function: fn, modifies, explanation, children });
const cl = (text: string, type: string, marker: string, role: string, subject: string, predicate: string, predicateDetails: BeginnerClauseDetail["predicateDetails"], translationOrder: string): BeginnerClauseDetail => ({ text, type, marker, role, subject, predicate, predicateDetails, translationOrder });
type Reviewed = { components: BeginnerSyntaxComponent[]; clauses: BeginnerClauseDetail[]; colors: SyntaxVisualRole[]; translations: string[] };
const r = (components: BeginnerSyntaxComponent[], colors: SyntaxVisualRole[], translations: string[], clauses: BeginnerClauseDetail[] = []): Reviewed => ({ components, colors, translations, clauses });

export const passage2010P3Syntax: Record<number, Reviewed> = {
  1: r([
    c("Over the past decade", "介词短语", "时间状语", "had perfected", "限定企业完善手法的十年时段；原卷用过去完成时，不自行改成现在完成时。"),
    c("many companies", "数量限定词＋复数名词", "主语", "had perfected", "实施手法的是许多企业。"),
    c("had perfected", "过去完成时", "谓语", "many companies", "perfect是动词‘使完善’，不是形容词完美的。"),
    c("the art of creating automatic behaviors – habits – among consumers", "名词短语及of补充", "宾语", "had perfected", "中心art为手法；整个of结构说明培养什么。", [c("of creating automatic behaviors – habits – among consumers", "of＋动名词短语", "内容定语", "art", "手法是让消费者形成自动化行为。", [c("creating", "动名词", "介词宾语的动作中心", "of", "不是第二个限定谓语。"), c("automatic behaviors", "形容词＋复数名词", "动名词宾语", "creating", "自动发生的行为。"), c("habits", "复数名词", "同位语", "automatic behaviors", "破折号中把自动行为解释成习惯。"), c("among consumers", "介词短语", "人群范围状语", "creating", "培养行为发生于消费者群体中。")])]),
  ], ["modifier", "subject", "predicate", "object"], ["在过去十年里", "许多公司", "已经完善了", "在消费者中培养自动行为——也就是习惯——的手法"]),
  2: r([
    c("These habits", "指示限定词＋名词", "主语", "have helped", "these回指企业培养的自动行为。"), c("have helped", "现在完成时", "谓语", "These habits", "说明这些习惯已经产生的作用。"), c("companies", "复数名词", "宾语", "have helped", "被帮助的是企业，也是earn的执行者。"),
    c("earn billions of dollars", "省略to的不定式", "宾语补足语", "companies", "企业赚取收入，不是habits自己赚钱。", [c("billions of dollars", "数量名词短语", "不定式宾语", "earn", "数十亿美元；billions of不是精确十亿美元。")]),
    c("when customers eat snacks or wipe counters almost without thinking, often in response to a carefully designed set of daily cues", "when从句", "时间状语从句", "have helped companies earn", "在消费者反复消费的场景下，企业获利。", [c("customers", "复数名词", "从句主语", "eat与wipe", "两项动作共用消费者这个主语。"), c("eat snacks or wipe counters", "并列动宾结构", "从句谓语部分", "customers", "eat接snacks，wipe接counters，or连接两个选择性的例子。", [c("eat", "动词", "从句第一谓语", "customers", "吃。"), c("snacks", "复数名词", "宾语", "eat", "吃的对象是零食。"), c("wipe", "动词", "从句第二谓语", "customers", "擦拭。"), c("counters", "复数名词", "宾语", "wipe", "擦的是台面。")]), c("almost without thinking", "副词＋介词短语", "方式状语", "eat或wipe", "almost保留几乎之意，没有说完全失去意识。"),
    c("often in response to a carefully designed set of daily cues", "频率副词＋介词性结构", "行为触发说明", "消费者吃零食或擦台面的动作", "这些日常动作常是对精心安排的提示作出的反应。", [c("a carefully designed set of daily cues", "名词短语", "介词宾语", "to", "中心set，一套日常提示。", [c("carefully designed", "副词＋过去分词", "前置定语", "set", "carefully修饰designed，整组再修饰set。"), c("of daily cues", "介词短语", "内容定语", "set", "说明这套东西由日常提示组成。")])])]),
  ], ["subject", "predicate", "object", "complement", "modifier"], ["这些习惯", "已经帮助", "企业", "赚取数十亿美元", "当消费者几乎不假思索地吃零食或擦台面、常对一套精心设计的日常提示作出反应时"], [cl("when customers eat snacks or wipe counters almost without thinking, often in response to a carefully designed set of daily cues", "时间状语从句", "when", "说明习惯帮助企业获利的消费场景", "customers", "eat / wipe", [{ function: "宾语", text: "snacks" }, { function: "宾语", text: "counters" }], "先读消费者的行为，再连接这些习惯带来的企业收益。")]),
  3: r([
    c("There", "存在句引导词", "存在句引导成分", "are", "引出某类事物存在，不表示在那里。"), c("are", "一般现在时be", "谓语", "存在句实义主语problems", "复数问题对应are。"), c("fundamental public health problems", "名词短语", "存在句实义主语", "are", "中心problems，限定为基础性的公共卫生问题。"),
    c("like dirty hands instead of a soap habit", "like举例短语", "举例补充", "problems", "以手脏而未养成肥皂洗手习惯说明问题。", [c("instead of a soap habit", "介词性结构", "对照补充", "dirty hands", "有的是脏手，而不是良好的肥皂洗手习惯。")]),
    c("that remain killers only because we can't figure out how to change people's habits", "嵌有原因从句的关系从句", "后置定语", "problems", "that越过插入例子，回指问题；原因层包含在关系从句内。", [c("that", "关系代词", "从句主语", "remain", "回指problems，不是soap habit。"), c("remain", "系动词", "从句谓语", "that", "仍然是。"), c("killers", "名词", "表语", "remain", "致命因素，不是remain的动作宾语。"), c("only because we can't figure out how to change people's habits", "only＋原因从句", "原因状语", "remain killers", "only强调原因；缺少改变习惯的方法使问题继续致命。", [c("we", "代词", "从句主语", "can't figure out", "泛指公共卫生研究和实践者。"), c("can't figure out", "情态动词否定＋动词短语", "从句谓语", "we", "不能弄清楚。"), c("how to change people's habits", "疑问词＋不定式", "宾语", "figure out", "询问改变习惯的方法，不是另一个有限定时态的从句。", [c("people's habits", "所有格＋名词", "不定式宾语", "change", "被改变的是人们的习惯。")])])]),
    c("said", "一般过去时", "报道语谓语", "Dr. Curtis", "引语后倒装报道语。"), c("Dr. Curtis", "称谓＋专名", "报道语主语", "said", "引语观点属于Curtis。"), c("the director of the Hygiene Center at the London School of Hygiene & Tropical Medicine", "名词及嵌套介词短语", "同位语", "Dr. Curtis", "说明主任身份及所属中心、学校。", [c("of the Hygiene Center at the London School of Hygiene & Tropical Medicine", "of短语", "所属定语", "director", "中心主任。", [c("at the London School of Hygiene & Tropical Medicine", "介词短语", "机构归属定语", "the Hygiene Center", "中心隶属该院校，不修饰said。")])]),
  ], ["modifier", "predicate", "subject", "modifier", "modifier", "predicate", "subject", "modifier"], ["（引出存在句，不单译）", "有", "一些根本性的公共卫生问题", "例如手脏而未养成用肥皂洗手的习惯", "这些问题仍然致命，仅仅因为我们弄不清如何改变人们的习惯", "说道", "柯蒂斯博士", "即伦敦卫生与热带医学院卫生中心主任"], [cl("that remain killers only because we can't figure out how to change people's habits", "定语从句", "that", "修饰problems", "that（problems）", "remain", [{function:"表语",text:"killers"}], "先理解问题仍致命，再进入原因。"), cl("because we can't figure out how to change people's habits", "原因状语从句", "because", "说明remain killers的原因", "we", "can't figure out", [{function:"宾语",text:"how to change people's habits"}], "先读无法弄清改变习惯的方法，再联系问题继续致命。")]),
  4: r([
    c("We", "代词", "主语", "wanted", "指Curtis等研究者。"), c("wanted", "一般过去时", "谓语", "We", "想要学习。"), c("to learn from private industry how to create new behaviors that happen automatically", "不定式短语", "宾语", "wanted", "想做的事是向企业界学习培养习惯。", [c("from private industry", "介词短语", "学习来源状语", "learn", "从私营企业界学习，不表示卫生是私人问题。"), c("how to create new behaviors that happen automatically", "疑问不定式", "宾语", "learn", "学习内容是如何培养行为。", [c("new behaviors that happen automatically", "名词及关系从句", "不定式宾语", "create", "培养的是无需刻意思考便会发生的新行为。", [c("that happen automatically", "关系从句", "后置定语", "behaviors", "that作happen的主语，automatically修饰happen。")])])]),
  ], ["subject", "predicate", "object"], ["我们", "想要", "向企业界学习如何培养会自动发生的新行为"], [cl("that happen automatically", "定语从句", "that", "修饰behaviors", "that（behaviors）", "happen", [], "先读自动发生，再回到这些新行为。")]),
  5: r([
    c("The companies", "名词短语", "主语", "had invested", "公司是投资主体。"), c("that Dr. Curtis turned to", "关系从句", "后置定语", "companies", "that是turned to的介词宾语，不是从句主语。", [c("Dr. Curtis", "专名", "从句主语", "turned to", "求助者是博士。"), c("turned to", "动词短语", "从句谓语", "Dr. Curtis", "turn to表示求助，求助对象由that回指companies。")]), c("Procter & Gamble, Colgate-Palmolive and Unilever", "并列公司名", "同位说明", "The companies", "三项都是企业，区别后文牙膏、洗衣粉的产品品牌。"), c("had invested", "过去完成时", "谓语", "The companies", "企业此前已投入资金。"), c("hundreds of millions of dollars", "金额名词短语", "宾语", "had invested", "数亿美元，不是几百美元。"),
    c("finding the subtle cues in consumers' lives that corporations could use to introduce new routines", "-ing非谓语短语", "投资用途补足成分", "had invested", "投入资金寻找提示；find的整个宾语直到routines才结束。", [c("the subtle cues in consumers' lives that corporations could use to introduce new routines", "含关系从句的名词短语", "动名词宾语", "finding", "中心cues；生活场景和可利用性分别说明这些提示。", [c("in consumers' lives", "介词短语", "范围定语", "cues", "提示存在于消费者生活中。"), c("that corporations could use to introduce new routines", "关系从句", "后置定语", "cues", "that对应use的宾语，不能挂到lives。", [c("corporations", "复数名词", "从句主语", "could use", "使用提示的是公司。"), c("could use", "情态动词＋动词", "从句谓语", "corporations", "宾语that已移至从句开头。"), c("to introduce new routines", "不定式", "目的状语", "could use", "企业利用提示来引入新惯例；不是提示自己执行引入。", [c("new routines", "名词短语", "不定式宾语", "introduce", "新日常程序。")])])])]),
  ], ["subject", "modifier", "modifier", "predicate", "object", "complement"], ["那些公司", "即柯蒂斯博士求助的公司", "——宝洁、高露洁-棕榄和联合利华——", "早已投入", "数亿美元", "寻找消费者生活中可供企业用来引入新习惯的细微提示"], [cl("that Dr. Curtis turned to", "定语从句", "that", "限定companies", "Dr. Curtis", "turned to", [{function:"介词宾语",text:"that"}], "先理解博士向谁求助，再确定公司。"), cl("that corporations could use to introduce new routines", "定语从句", "that", "限定cues", "corporations", "could use", [{function:"宾语",text:"that"}], "先读公司可以利用这些提示，再读用途。")]),
  6: r([
    c("If you look hard enough", "条件从句", "条件状语从句", "you'll find", "仔细观察是后面发现的条件。", [c("you", "代词", "从句主语", "look", "泛指读者。"), c("look", "动词", "从句谓语", "you", "观察。"), c("hard enough", "副词及程度补充", "方式状语", "look", "hard是认真地，enough后置修饰hard。")]),
    c("you'll find", "主语＋will缩写＋动词", "主句主谓", "整句", "you是主语，will find是谓语；后接发现的内容。"),
    c("that many of the products we use every day – chewing gums, skin moisturizers, disinfecting wipes, air fresheners, water purifiers, health snacks, teeth whiteners, fabric softeners, vitamins – are results of manufactured habits", "that内容从句", "宾语从句", "find", "跳过清单后，主干是many of the products are results。", [c("many of the products we use every day", "数量代词＋of短语及关系从句", "从句主语", "are", "这些日用品中的许多种。", [c("we use every day", "省略关系词的从句", "后置定语", "products", "we是主语，use缺少的宾语是products，every day修饰use。")]), c("chewing gums, skin moisturizers, disinfecting wipes, air fresheners, water purifiers, health snacks, teeth whiteners, fabric softeners, vitamins", "九项并列名词短语", "同位列举", "products", "全部例子说明日用品，不承担主句谓语。"), c("are", "系动词", "从句谓语", "many of the products", "跟复数主语一致。"), c("results of manufactured habits", "名词短语", "表语", "are", "是人为塑造的习惯所催生的产物；manufactured修饰habits。")]),
  ], ["modifier", "predicate", "object"], ["如果你观察得足够仔细", "你就会发现", "我们每天使用的许多产品——口香糖、润肤品、消毒湿巾、空气清新剂、净水器、健康零食、牙齿美白剂、衣物柔顺剂和维生素——都是人为塑造习惯的产物"], [cl("If you look hard enough", "条件状语从句", "If", "限定find", "you", "look", [], "先理解仔细观察的条件，再读发现内容。"), cl("that many of the products we use every day – chewing gums, skin moisturizers, disinfecting wipes, air fresheners, water purifiers, health snacks, teeth whiteners, fabric softeners, vitamins – are results of manufactured habits", "宾语从句", "that", "作find的宾语", "many of the products we use every day", "are", [{function:"表语",text:"results of manufactured habits"}], "先把产品清单视为插入说明，再接是何种产物。"), cl("we use every day", "定语从句", "宾语关系词省略", "修饰products", "we", "use", [{function:"宾语",text:"省略的关系词，回指products"}], "先理解我们每天使用，再限定这些产品。")]),
  7: r([c("A century ago", "时间名词短语", "时间状语", "brushed", "相对于原文叙述当时的一百年前。"), c("few people", "否定数量词＋名词", "主语", "brushed", "很少有人，并非没有人。"), c("regularly", "副词", "频率状语", "brushed", "有规律地。"), c("brushed", "一般过去时", "谓语", "few people", "brush one's teeth刷牙。"), c("their teeth", "物主限定词＋不规则复数名词", "宾语", "brushed", "这些人自己的牙齿。"), c("multiple times a day", "频次名词短语", "频率状语", "brushed", "一天多次；a表示每。")], ["modifier","subject","modifier","predicate","object","modifier"], ["一百年前", "很少有人", "有规律地", "刷", "自己的牙齿", "每天多次"]),
  8: r([c("Today", "时间副词", "时间状语", "give", "与上一句百年前对照，指文章所述的如今。"), c("because of shrewd advertising and public health campaigns", "介词性结构＋并列名词", "原因状语", "give their pearly whites a scrub", "广告和公共卫生宣传共同促成刷牙习惯，不能漏掉其中一方。"), c("many Americans", "数量词＋复数名词", "主语", "give", "许多美国人，不是全部消费者。"), c("habitually", "副词", "方式状语", "give", "习惯性地。"), c("give", "一般现在时", "谓语", "many Americans", "give A B为给A做一次B。"), c("their pearly whites", "形象性名词短语", "间接宾语", "give", "牙齿接受清洁，pearly whites代指洁白牙齿。"), c("a cavity-preventing scrub", "名词短语", "直接宾语", "give", "一次防蛀清洁；cavity-preventing修饰scrub。"), c("twice a day", "频次短语", "频率状语", "give a scrub", "每天两次。"), c("often with Colgate, Crest or one of the other brands", "频率副词＋介词短语", "工具状语", "give a scrub", "刷牙时常用高露洁、佳洁士或其他品牌产品；专名指品牌。")], ["modifier","modifier","subject","modifier","predicate","object","object","modifier","modifier"], ["如今", "由于精明的广告和公共卫生宣传", "许多美国人", "习惯性地", "给", "自己的牙齿", "做一次防蛀清洁", "每天两次", "常用高露洁、佳洁士或其他品牌的产品"]),
  9: r([c("A few decades ago", "时间名词短语", "时间状语", "didn't drink", "几十年前，不是几个世纪前。"), c("many people", "名词短语", "主语", "didn't drink", "许多人，保留数量限制。"), c("didn't drink", "一般过去时否定", "谓语", "many people", "did承担过去时，drink保持原形。"), c("water", "不可数名词", "宾语", "drink", "水。"), c("outside of a meal", "介词短语", "时间范围状语", "didn't drink", "非用餐时段；不表示完全不喝水。")], ["modifier","subject","predicate","object","modifier"], ["几十年前", "很多人", "不喝", "水", "在用餐以外的时段"]),
  10: r([c("Then", "时间副词", "时间状语", "started", "接前文过去状态，表示后来。"), c("beverage companies", "名词短语", "第一分句主语", "started", "饮料企业。"), c("started", "一般过去时", "第一分句谓语", "beverage companies", "开始做后面的事情。"), c("bottling the production of far-off springs", "-ing补足结构", "宾语", "started", "装瓶的是远方泉水的出产物，即泉水。", [c("the production of far-off springs", "名词短语", "动名词宾语", "bottling", "production在此指产出的水。", [c("of far-off springs", "介词短语", "来源定语", "production", "far-off修饰springs，spring为泉不是春天。")])]), c("and", "并列连词", "连接分句", "前后两套主谓", "从企业行动接到如今消费习惯。"), c("now", "时间副词", "时间状语", "sip", "与Then对照。"), c("office workers", "名词短语", "第二分句主语", "sip", "办公室职员。"), c("unthinkingly", "副词", "方式状语", "sip", "不假思索地。"), c("sip", "一般现在时", "第二分句谓语", "office workers", "小口喝。"), c("bottled water", "分词定语＋名词", "宾语", "sip", "bottled是定语，区别前半句装瓶动作bottling。"), c("all day long", "时间短语", "持续时间状语", "sip", "一整天；不表示每一天。")], ["modifier","subject","predicate","object","connector","modifier","subject","modifier","predicate","object","modifier"], ["后来", "饮料企业", "开始", "将遥远泉眼产出的泉水装瓶", "而", "如今", "办公室职员", "不假思索地", "小口喝着", "瓶装水", "一整天"]),
  11: r([c("Chewing gum", "名词短语", "主语", "is featured", "口香糖是整体产品名。"), c("once bought primarily by adolescent boys", "过去分词短语", "补充性后置定语", "Chewing gum", "回顾主要购买者，bought与gum是被动关系。", [c("once", "时间副词", "时间状语", "bought", "曾经。"), c("primarily", "副词", "程度范围状语", "by adolescent boys", "主要由这类人购买，并非只有他们。"), c("by adolescent boys", "介词短语", "施事补充", "bought", "购买者为青春期男孩。")]), c("is now featured", "被动谓语及时间副词", "谓语", "Chewing gum", "is featured才是限定谓语，now与once对照。"), c("in commercials", "介词短语", "呈现场合状语", "is featured", "在广告片中。"), c("as a breath freshener and teeth cleanser for use after a meal", "as＋并列名词及用途限定", "产品定位补足语", "is featured", "广告把口香糖塑造成两类用品。", [c("a breath freshener and teeth cleanser", "并列名词短语", "介词宾语", "as", "清新口气用品与牙齿清洁用品。"), c("for use after a meal", "介词短语", "用途定语", "freshener and cleanser", "限定为饭后使用。", [c("after a meal", "介词短语", "时间限定", "use", "use是名词‘使用’，饭后限定其时间。")])])], ["subject","modifier","predicate","modifier","complement"], ["口香糖", "过去主要由青春期男孩购买", "如今被重点展示", "在广告中", "作为饭后使用的口气清新用品和牙齿清洁用品"]),
  12: r([c("Skin moisturizers", "名词短语", "主语", "are advertised", "润肤品。"), c("are advertised", "一般现在时被动", "谓语", "Skin moisturizers", "被宣传。"), c("as part of morning beauty rituals", "as介词短语", "产品定位补足语", "are advertised", "被宣传成晨间美容惯例的一部分；of说明整体。"), c("slipped in between hair brushing and putting on makeup", "过去分词短语", "补充状态状语", "Skin moisturizers", "产品的使用被悄然插入原有程序。", [c("between hair brushing and putting on makeup", "between＋两项活动", "次序状语", "slipped in", "这里是时间程序，不是空间夹缝。", [c("hair brushing", "名词性活动", "第一并列介词宾语", "between", "梳头。"), c("putting on makeup", "动名词短语", "第二并列介词宾语", "between", "化妆；makeup是put on的宾语。")])])], ["subject","predicate","complement","modifier"], ["润肤品", "被宣传", "为晨间美容惯例的一部分", "被悄然插入梳头与化妆之间"]),
  13: r([c("Our products", "物主限定词＋名词", "引语主语", "succeed", "our属于企业说话者。"), c("succeed", "一般现在时", "引语谓语", "Our products", "取得商业成功。"), c("when they become part of daily or weekly patterns", "when从句", "时间兼条件状语", "succeed", "融入惯例时产品成功，they回指产品。", [c("they", "代词", "从句主语", "become", "产品。"), c("become", "系动词", "从句谓语", "they", "成为。"), c("part of daily or weekly patterns", "名词短语", "表语", "become", "日常或每周模式的一部分。")]), c("said", "一般过去时", "报道语谓语", "Carol Berning", "引语后倒装报道。"), c("Carol Berning", "专名", "报道语主语", "said", "受访者为伯宁。"), c("a consumer psychologist who recently retired from Procter & Gamble, the company that sold $76 billion of Tide, Crest and other products last year", "名词短语及嵌套身份说明", "同位语", "Carol Berning", "先解释人，再在退休来源内部解释公司。", [c("who recently retired from Procter & Gamble, the company that sold $76 billion of Tide, Crest and other products last year", "关系从句", "后置定语", "psychologist", "who回指心理学家，退休动作属于人。", [c("recently", "副词", "时间状语", "retired", "最近，不能接到sold。"), c("from Procter & Gamble, the company that sold $76 billion of Tide, Crest and other products last year", "介词短语及公司说明", "退休来源补足语", "retired", "从宝洁退休。", [c("the company that sold $76 billion of Tide, Crest and other products last year", "名词及关系从句", "同位语", "Procter & Gamble", "公司说明属于宝洁，不属于伯宁个人。", [c("that sold $76 billion of Tide, Crest and other products last year", "关系从句", "后置定语", "company", "that代公司作sold主语。", [c("$76 billion of Tide, Crest and other products", "金额及商品名词短语", "宾语", "sold", "760亿美元的汰渍、佳洁士等商品；品牌不是公司名。"), c("last year", "时间名词短语", "时间状语", "sold", "相对于原文当时的上一年，不自动更新年份。")])])])])])], ["subject","predicate","modifier","predicate","subject","modifier"], ["我们的产品", "就获得成功", "当它们融入每天或每周的惯例时", "说", "卡罗尔·伯宁", "一位刚从宝洁退休的消费心理学家；宝洁上一年卖出了760亿美元的汰渍、佳洁士等产品"], [cl("when they become part of daily or weekly patterns", "时间兼条件状语从句", "when", "限定succeed", "they（products）", "become", [{function:"表语",text:"part of daily or weekly patterns"}], "先理解产品融入惯例，再接成功。"), cl("who recently retired from Procter & Gamble, the company that sold $76 billion of Tide, Crest and other products last year", "定语从句", "who", "修饰psychologist；退休来源内包含公司同位说明", "who（Berning）", "retired", [], "先理解她从宝洁退休，再在机构层补充公司销售额。"), cl("that sold $76 billion of Tide, Crest and other products last year", "定语从句", "that", "修饰company", "that（Procter & Gamble）", "sold", [{function:"宾语",text:"$76 billion of Tide, Crest and other products"}], "先明确是公司销售，再接金额和上一年。")]),
  14: r([c("Creating positive habits", "动名词短语", "主语", "is", "整件事作单数主语。", [c("positive habits", "名词短语", "动名词宾语", "Creating", "positive属于企业受访者的评价。")]), c("is", "系动词", "谓语", "Creating positive habits", "将培养习惯与改善生活联系起来。"), c("a huge part of improving our consumers' lives", "名词短语及of结构", "表语", "is", "改善生活活动中的重要部分。", [c("of improving our consumers' lives", "of＋动名词", "整体范围定语", "part", "说明是哪项活动的一部分。", [c("our consumers' lives", "双重所属限定名词短语", "动名词宾语", "improving", "我们消费者的生活。")])]), c("and", "连词", "连接分句", "前后两个判断", "并列改善生活和商业生存两层价值。"), c("it", "代词", "第二分句主语", "'s", "回指培养积极习惯这件事。"), c("'s", "is的缩写", "第二分句谓语", "it", "后接形容词，所以是is。"), c("essential", "形容词", "表语", "'s", "必不可少的。"), c("to making new products commercially viable", "to介词短语", "形容词补足语", "essential", "对让产品商业上可行而言至关重要。", [c("making new products commercially viable", "动名词及宾语宾补", "介词宾语", "to", "to是介词所以接making。", [c("new products", "名词短语", "动名词宾语", "making", "使什么变得可行。"), c("commercially viable", "副词＋形容词", "宾语补足语", "new products", "viable说明产品状态；commercially修饰viable。")])])], ["subject","predicate","complement","connector","subject","predicate","complement","complement"], ["培养积极的习惯", "是", "改善我们消费者生活的重要一环", "而且", "这件事", "是", "至关重要的", "对于让新产品具备商业生存能力而言"]),
  15: r([c("Through experiments and observation", "介词短语", "认识依据状语", "have learned", "实验观察是获得认识的方法，不是消费者习惯的直接促成因素。"), c("social scientists like Dr. Berning", "名词及举例短语", "主语", "have learned", "伯宁这样的社会科学家。", [c("like Dr. Berning", "like介词短语", "举例定语", "social scientists", "like是例如，不是喜欢。")]), c("have learned", "现在完成时", "谓语", "social scientists", "已得知。"), c("that there is power in tying certain behaviors to habitual cues through ruthless advertising", "that内容从句", "宾语从句", "have learned", "发现绑定行为与提示确实有效。", [c("there", "存在句引导词", "存在句引导成分", "is", "非地点副词。"), c("is", "be", "从句谓语", "power", "存在某种力量。"), c("power", "不可数名词", "存在句实义主语", "is", "效力、影响力。"), c("in tying certain behaviors to habitual cues through ruthless advertising", "介词＋动名词短语", "效力所在补充", "power", "效力在于以广告将行为与提示绑定。", [c("certain behaviors", "名词短语", "动名词宾语", "tying", "tie A to B中的A。"), c("to habitual cues", "介词短语", "关联对象补足语", "tying", "to后是名词，不是不定式；B为习惯性提示。"), c("through ruthless advertising", "介词短语", "手段状语", "tying", "广告是绑定手段，区别句首through引出的研究方法。")])])], ["modifier","subject","predicate","object"], ["通过实验与观察", "伯宁博士这样的社会科学家", "已经了解到", "借助不顾后果的广告，将某些行为与习惯性提示绑定，确实会产生效力"], [cl("that there is power in tying certain behaviors to habitual cues through ruthless advertising", "宾语从句", "that", "作have learned的宾语", "power（存在句实义主语）", "is", [], "先读绑定机制有效，再分别接广告手段和外层研究依据。")]),
  16: r([c("As this new science of habit has emerged", "As从句", "时间状语从句", "have erupted", "随着新学科出现；不直接改为唯一原因。", [c("this new science of habit", "名词短语", "从句主语", "has emerged", "关于习惯形成的新学科。"), c("has emerged", "现在完成时", "从句谓语", "science", "已经兴起。")]), c("controversies", "复数名词", "主语", "have erupted", "出现的是争议。"), c("have erupted", "现在完成时", "谓语", "controversies", "erupt比喻爆发。"), c("when the tactics have been used to sell questionable beauty creams or unhealthy foods", "when从句", "时间兼条件状语", "have erupted", "将争议限定到手段被用于问题商品的情形。", [c("the tactics", "名词短语", "从句主语", "have been used", "这些培养消费习惯的策略。"), c("have been used", "现在完成时被动", "从句谓语", "the tactics", "策略被使用，区别过去常常used to。"), c("to sell questionable beauty creams or unhealthy foods", "目的不定式", "目的状语", "have been used", "用于推销两类问题商品。", [c("questionable beauty creams or unhealthy foods", "并列名词短语", "不定式宾语", "sell", "questionable只修饰美容霜，unhealthy只修饰食品。")])])], ["modifier","subject","predicate","modifier"], ["随着这门习惯新科学兴起", "争议", "已经爆发", "当这些策略被用来销售效果可疑的美容霜或不健康食品时"], [cl("As this new science of habit has emerged", "时间状语从句", "As", "提供have erupted的背景", "this new science of habit", "has emerged", [], "先译随着科学兴起，再读争议出现。"), cl("when the tactics have been used to sell questionable beauty creams or unhealthy foods", "时间兼条件状语从句", "when", "限定争议发生情形", "the tactics", "have been used", [], "先识别策略被使用，再读销售目的及争议。")]),
};
