import type { SentenceWordContext } from "./contextual-vocabulary";
type Entry = { partOfSpeech: string; contextualMeaning: string; use: string; specialForms: string[]; examSynonyms: string[] };
const rows = [
  ["twentieth", "20th", "序数词", "第二十", "mid-20th century指20世纪中叶；20th整体是序数词，不能拆成h。", ""],
  ["1940s", "", "年代表达", "20世纪40年代", "the 1940s表示1940—1949年这一年代；s是年代标记。", ""],
  ["1960s", "", "年代表达", "20世纪60年代", "through the 1960s表示贯穿1960—1969年这一年代，不是仅1960年。", ""],
  ["permit", "permits permitted permitting", "v.", "准许", "permit somebody to do表示允许做某事；重读末音节，过去式和分词双写t。", "allow（允许）"],
  ["turn", "turns", "n.", "轮次", "take turns整体表示轮流；本句不取转向或求助的动词义。", ""],
  ["take", "takes took taken taking", "v.", "承担；进行（搭配中）", "take turns后接动名词，整体表示轮流进行某活动。", ""],
  ["including", "", "prep.", "包括", "including引出民主价值所包含的原则，本文是介词用法。", ""],
  ["manifestation", "manifestations", "n.", "表现；体现", "a manifestation of values为价值的具体体现，较expression正式。", "expression（体现）"],
  ["satisfy", "satisfies satisfied satisfying", "v.", "满足", "satisfy requirements表示满足要求，与meet qualifications近义。", "meet（满足要求）"],
  ["able", "", "adj.", "有能力的", "be able to do表示能做，competent还强调胜任程度。", "competent（胜任的）"],
  ["choose", "chooses chose chosen choosing", "v.", "选择", "choose人选不限定随机、投票还是按标准筛选。", "select（挑选，较正式）"],
  ["choice", "choices", "n.", "选择；被选者", "名词可指选择行为或结果，与动词choose分开统计。", "selection（遴选）"],
  ["belief", "beliefs", "n.", "信念；信仰", "religious beliefs是宗教信仰，belief范围不限宗教。", "opinion（看法，信念强度较弱）"],
  ["allow", "allows allowed allowing", "v.", "允许", "allow somebody to do需要宾语及to不定式；entitle更突出授予权利。", "permit（准许）"],
  ["equal", "equals", "n./adj.", "地位平等者；平等的", "名词equal可指同等者，peer在同侪审判中强调社会身份相当。", "peer（同侪）"],
  ["manage", "manages managed managing", "v.", "管理", "manage an organization指管理组织，govern偏政治治理。", "govern（治理）"],
  ["clash", "clashes clashed clashing", "v.", "冲突", "clash with principles可指与原则抵触，比conflict可能更强烈。", "conflict（抵触）"],
  ["responsibility", "responsibilities", "n.", "责任", "承担某事务的责任；duty更强调制度或道德义务。", "duty（义务、职责）"],
  ["allegedly", "", "adv.", "据称", "标明说法来自他人而非已由作者独立证实。", "supposedly（据说，常含怀疑距离）"],
  ["deliberate", "", "adj.", "故意的", "deliberate discrimination指有意实施的歧视。", "intentional（有意的）"],
  ["bias", "biases", "n.", "偏见；偏向", "bias可为歧视背后的倾向，discrimination更偏区别对待行为。", "attitude（态度，不一定有偏见）"],
  ["request", "requests requested requesting", "v./n.", "请求", "request较ask正式；request that从句与ask to do结构不同。", "ask（请求，搭配需核对）"],
  ["defend", "defends defended defending", "v.", "辩护；捍卫", "defend a practice为做法辩护，justify强调给出正当理由。", "justify（证明合理）"],
  ["approve", "approves approved approving", "v.", "批准", "approve a proposal表示正式批准；pass an Act为通过法律。", "pass（通过法案）"],
  ["failure", "failures", "n.", "失败；未能做到", "failure of safeguards表保障失效，inadequacy只是保障不足。", "inadequacy（不足，程度较弱）"],
  ["rarely", "", "adv.", "很少", "修饰动作频率，含否定倾向；不是绝对从未。", "seldom（很少）"],
  ["strict", "stricter strictest", "adj.", "严格的", "strict requirements为严格要求；rigid还含缺少弹性。", "rigid（严苛、僵化的）"],
  ["answer", "answers", "n.", "答案；应对办法", "an answer to a problem为问题的应对办法，solution更强调解决。", "solution（解决办法）"],
  ["jury", "juries", "n.", "陪审团", "jury指群体，juror指其中一名陪审员；on a jury表示担任成员。", "group（群体，未限定司法职责）"],
  ["juror", "jurors", "n.", "陪审员", "可数个人名词；federal jurors联邦陪审员与state jurors州陪审员须区分。", "citizen（公民，不一定担任陪审员）"],
  ["system", "systems", "n.", "制度；体系", "the jury system指陪审制度，不是单个案件的陪审团。", "structure（结构，未必是制度）"],
  ["regard", "regards regarded regarding", "v.", "看作；认为", "regard A as B以as引对A的评价，本句把制度视为民主价值体现。", "consider（认为，宾补结构不同）"],
  ["concrete", "", "adj.", "具体的", "concrete expression强调可具体体现的形式，不是混凝土材料。", "tangible（可感知的，侧重点不同）"],
  ["expression", "expressions", "n.", "体现；表达", "expression of values表示价值在制度中的体现。", "manifestation（表现形式，较正式）"],
  ["crucial", "", "adj.", "至关重要的", "修饰democratic values，强调民主价值的重要地位。", "essential（必要的，必要性更强）"],
  ["democratic", "", "adj.", "民主的", "democratic values/ideals/reforms分别为民主价值、理想和改革。", "不是名词democracy，派生词独立计数。"],
  ["democracy", "democracies", "n.", "民主；民主制度", "direct与representative标出直接和代议两种民主形式。", "不是动词govern治理。"],
  ["principle", "principles", "n.", "原则", "首句五个that从句并列说明原则内容。", "rule（规则，较具体可执行）"],
  ["citizen", "citizens", "n.", "公民", "citizens受who meet...限定，民主权利不等于完全无基本资格要求。", "person（人，未必具有特定公民身份）"],
  ["meet", "meets met meeting", "v.", "满足；符合", "meet qualifications表示达到资格要求，不是见面。", "satisfy（满足要求）"],
  ["minimal", "", "adj.", "最低限度的", "minimal qualifications仍有基本门槛，不表示没有任何限制。", "basic（基本的，不强调最低量）"],
  ["qualification", "qualifications", "n.", "资格；条件", "年龄与读写能力是基本资格，不能因特殊教育门槛取消就全部删除。", "requirement（要求，从制度一方表述）"],
  ["age", "ages", "n.", "年龄", "qualifications of age指年龄条件；不能推出no age limit。", "不是本文的时代义。"],
  ["literacy", "", "n.", "读写能力", "资格要求是基本识字读写水平，不是文学修养。", "education（教育，范围更广）"],
  ["equally", "", "adv.", "同等地", "修饰competent，表示满足基本条件者能力资格地位平等。", "不是所有人的知识技能完全一样。"],
  ["competent", "", "adj.", "有能力的；胜任的", "competent to serve用不定式说明胜任何种职责。", "able（能够，强调一般能力）"],
  ["serve", "serves served serving", "v.", "任职；服务", "serve on a jury担任陪审员，on引所属委员会或组织。", "work（工作，范围较宽）"],
  ["select", "selects selected selecting", "v.", "挑选；遴选", "be selected是被动；selecting jurors为挑选陪审员的活动。", "choose（选择，较普通）"],
  ["selection", "selections", "n.", "遴选；选拔", "jury selection为陪审员遴选，和动词select分开计数。", "choice（选择，可突出选出的结果）"],
  ["randomly", "", "adv.", "随机地", "修饰be selected，表示不按精英偏好定向选择。", "at random（随机地，介词短语）"],
  ["representative", "representatives", "adj./n.", "有代表性的；代表", "cross section前为形容词；electing representatives中为可数名词代表。", "typical（典型的，不一定覆盖所有群体）"],
  ["cross", "", "adj.", "横向的", "cross section整体为横截面，本文借指反映社会构成的样本。", "不是动词穿过或形容词生气的。"],
  ["section", "sections", "n.", "部分；截面", "cross section of the community取社会各群体的代表性构成。", "part（部分，未必具有代表性）"],
  ["community", "communities", "n.", "社会群体；社区", "强调陪审员所代表的整个社会共同体，不局限于一个小区。", "society（社会，范围需依语境判断）"],
  ["deny", "denies denied denying", "v.", "剥夺；拒绝给予", "deny somebody the right为双宾语；被动句保留right作宾语。", "refuse（拒绝，搭配不同）"],
  ["right", "rights", "n.", "权利", "the right to serve是参与陪审的权利，不是右侧或正确。", "不是职责duty，两者立足点不同。"],
  ["account", "accounts", "n.", "缘由（固定搭配中）", "on account of表示由于，不能按账户或叙述解读。", "reason（原因，需改为for reasons of等结构）"],
  ["race", "races", "n.", "种族", "歧视因素列举中的race不是竞赛。", "racial为形容词，不是race的屈折变化。"],
  ["religion", "religions", "n.", "宗教", "列为不得据以剥夺陪审权的身份因素。", "belief（信仰，范围较广）"],
  ["sex", "sexes", "n.", "性别", "sex discrimination是性别歧视，本篇讨论男女参与资格。", "不是性行为含义。"],
  ["national", "", "adj.", "民族的；国家的", "national origin指民族或国家出身，原文列为反歧视维度。", "不是national government这一中央政府结构。"],
  ["origin", "origins", "n.", "出身；来源", "national origin中指身份来源背景。", "source（来源，较一般化）"],
  ["defendant", "defendants", "n.", "被告", "享有由同侪审判的权利，不能把被告自动视为已定罪者。", "不是juror，后者参与作出裁决。"],
  ["entitle", "entitles entitled entitling", "v.", "使有权", "be entitled to trial意为有权接受审判；to为介词。", "allow（允许，不必包含法定权利）"],
  ["trial", "trials", "n.", "审判", "trial by peers由同侪审判；不是商品试用。", "不是verdict裁决结果。"],
  ["peer", "peers", "n.", "同侪；同等身份的人", "trial by their peers表示由同等社会身份的人参与审判，不专指同龄人。", "equal（地位平等者，名词义）"],
  ["verdict", "verdicts", "n.", "裁决；裁定", "陪审团对案件作出的判断，应体现社会良知。", "judgment（判断或裁决，范围较广）"],
  ["conscience", "", "n.", "良知；道德判断", "community conscience指社会共同的道德判断；不是consciousness意识。", "不等于某一个人的偏好。"],
  ["letter", "letters", "n.", "字面条文", "the letter of the law指法律字面规定，不是信件。", "text（文本，需限定为法律文本）"],
  ["law", "laws", "n.", "法律", "this law在末段专指1968年法案；不得与1975年判决混淆。", "rule（规则，法律约束层级不同）"],
  ["also", "", "adv.", "也；还", "补充同一主题的新方面，如民主性质或另一项改革。", "too（也，位置通常不同）"],
  ["survive", "survives survived surviving", "v.", "存续；保留下来", "surviving example中分词作定语，指仍然存在的制度范例。", "remain（仍然存在，结构不同）"],
  ["direct", "", "adj.", "直接的", "direct democracy指公民直接参与，而非选代表代办。", "不是动词指导。"],
  ["govern", "governs governed governing", "v.", "治理", "govern themselves表示公民自治；govern for them表示代表代为治理。", "manage（管理，未必涉及政治治理）"],
  ["elect", "elects elected electing", "v.", "选举", "elect representatives指以选举方式产生代表，与随机select不同。", "select（选取，不一定通过投票）"],
  ["procedure", "procedures", "n.", "程序；步骤", "jury selection procedures是遴选程序，与民主理想发生冲突。", "method（方法，程序性较弱）"],
  ["conflict", "conflicts conflicted conflicting", "v.", "冲突；抵触", "conflict with ideals指出实践与理想不一致，而非理想彼此对立。", "clash（冲突，可能更强烈）"],
  ["ideal", "ideals", "n.", "理想；理想原则", "these democratic ideals回指首段五项原则。", "principle（原则，侧重行为规范）"],
  ["duty", "duties", "n.", "职责；义务", "jury duty为陪审义务；domestic duties为家庭事务，两者对比。", "responsibility（责任，范围较广）"],
  ["person", "persons", "n.", "人；个人", "persons of superior...表示具有某些属性的人。", "people（人们，通常为群体复数）"],
  ["supposedly", "", "adv.", "据说；被认为", "修饰superior，作者与所谓优越的评价保持距离。", "allegedly（据称，更正式）"],
  ["superior", "", "adj.", "更优越的", "限定智力、教育、品德的所谓优越标准；比较通常用superior to。", "better（更好，结构不同）"],
  ["intelligence", "", "n.", "智力", "精英筛选所看重的属性，不是情报消息。", "ability（能力，范围较宽）"],
  ["character", "characters", "n.", "品格", "moral character为道德品格，不是文字字符或故事人物。", "quality（品质，范围需限定）"],
  ["supreme", "", "adj.", "最高的", "Supreme Court是最高法院，属于机构名称。", "highest（最高的，专名仍保留Supreme）"],
  ["court", "courts", "n.", "法院", "文中的最高法院与国会分别负责判决和立法。", "不是体育球场。"],
  ["prohibit", "prohibits prohibited prohibiting", "v.", "禁止", "had prohibited discrimination承认早已有反歧视要求。", "ban（禁止，较直接）"],
  ["intentional", "", "adj.", "故意的", "限定racial discrimination，不应漏掉主观故意这一原文限定。", "deliberate（蓄意的）"],
  ["racial", "", "adj.", "种族的", "racial discrimination与后文sex discrimination为不同维度。", "race为名词，二者仅关联词族。"],
  ["discrimination", "", "n.", "歧视", "本文指不公平区别对待，不是中性辨别能力。", "bias（偏见，可为歧视的思想基础）"],
  ["strauder", "", "n.（专名）", "斯特劳德", "1880年案件名称中的当事方，按原卷保留拼写。", ""],
  ["v", "", "缩写", "诉；对", "案件名中的v.为versus，点号不是句尾。", ""],
  ["practice", "practices", "n.", "做法；惯例", "本篇指精英筛选或女性豁免，不是练习技能。", "method（方法，惯常性较弱）"],
  ["so-called", "", "adj.", "所谓的", "对elite标准带保留态度，不是作者完全赞同其优越。", ""],
  ["elite", "elites", "adj./n.", "精英的；精英", "elite jurors指被认为优越者，不代表程序天然民主。", "superior（优越的，此处是被假定的评价）"],
  ["blue-ribbon", "", "adj.", "精英的；一流的", "blue-ribbon juries为由被视为优秀者组成的陪审团，不是佩戴蓝带的描述。", "elite（精英的）"],
  ["provide", "provides provided providing", "v.", "提供", "provide a way提供途径；这一途径是绕过反歧视要求。", "offer（提供，可能含主动提议）"],
  ["convenient", "", "adj.", "方便的", "a convenient way around为便于规避，不是值得称赞的便利措施。", "easy（容易的，侧重点不同）"],
  ["around", "", "prep.", "绕过；规避", "a way around laws是绕开法律限制，不是法律周围的地点。", ""],
  ["antidiscrimination", "", "adj.", "反歧视的", "修饰laws，anti-表示反对，保留原卷连写。", ""],
  ["th", "", "序数词后缀", "第……的序数后缀", "20th中的th不是独立词汇；与数字20共同构成第二十。", ""],
  ["utah", "", "n.（专名）", "犹他州", "1898年女性参与州陪审的地点。", ""],
  ["eligible", "", "adj.", "有资格的", "eligible for jury duty具备陪审资格，不表示实际一定入选。", "qualified（合格的，搭配可能不同）"],
  ["exempt", "exempts exempted exempting", "v.", "豁免；免除", "exempt women from duty为免除义务，不是ban禁止参与。", "release（免除，需补from等结构）"],
  ["personally", "", "adv.", "亲自地；本人", "亲自申请是当时女性获得列名的额外条件。", "不是person的屈折词形。"],
  ["ask", "asks asked asking", "v.", "请求", "asked to have names included表示请求列入名单，不是询问信息。", "request（请求，更正式）"],
  ["include", "includes included including", "v.", "包括；纳入", "include women纳入女性；have names included为过去分词宾补。", "involve（涉及或使参与，结构不同）"],
  ["list", "lists", "n.", "名单", "jury list是陪审员候选名单，on the list为在名单上。", "record（记录，范围更广）"],
  ["justify", "justifies justified justifying", "v.", "为……辩护；证明合理", "was justified by the claim是当时的辩护，不等于作者认可。", "defend（辩护，语义范围较广）"],
  ["claim", "claims", "n.", "说法；主张", "that从句解释‘家中需要女性’这一主张，不保证事实成立。", "statement（陈述，确信程度较中性）"],
  ["keep", "keeps kept keeping", "v.", "使保持", "keep juries unrepresentative为宾语+形容词宾补，持续缺乏代表性。", "maintain（维持，需要调整宾补结构）"],
  ["unrepresentative", "", "adj.", "缺乏代表性的", "unrepresentative of women指女性未被充分代表，不是女性无能力。", "与representative相反，不是同一屈折词形。"],
  ["congress", "", "n.（机构名）", "国会", "the Congress of the United States指美国国会，1968年法案的通过者。", "不是最高法院Court。"],
  ["pass", "passes passed passing", "v.", "通过（法案）", "passed the Act为立法行为，不是经过。", "approve（批准，程序范围不同）"],
  ["service", "services", "n.", "任职；履行职责", "Jury Selection and Service Act中指陪审任职。", "duty（职责，强调义务）"],
  ["act", "acts", "n.", "法案；法律", "大写Act是法律名称组成部分，不是普通动词行动。", "law（法律，较广泛）"],
  ["usher", "ushers ushered ushering", "v.", "引领进入；开创", "usher in a new era开启新时代；in为短语动词成分。", "introduce（引入，未必有开启时代意味）"],
  ["era", "eras", "n.", "时代；时期", "a new era of reforms为改革新时代。", "period（时期，划时代意味较弱）"],
  ["reform", "reforms reformed reforming", "n./v.", "改革", "democratic reforms为名词；reforming the system为动名词活动。", "change（改变，未必意味着制度改善）"],
  ["abolish", "abolishes abolished abolishing", "v.", "废除", "废除的是特殊教育要求，并非整个陪审制度。", "end（结束，法律制度色彩较弱）"],
  ["educational", "", "adj.", "教育方面的", "special educational requirements是特殊教育门槛，不是对特殊教育学生的要求。", "education为独立名词，仅作词族关联。"],
  ["requirement", "requirements", "n.", "要求", "第12句教育门槛；第13句代表性要求，内容不同但词义一致。", "condition（条件，约束侧重点不同）"],
  ["require", "requires required requiring", "v.", "要求", "require somebody to do以不定式作宾补；them指联邦陪审员。", "demand（要求，不能任意套用相同宾补结构）"],
  ["federal", "", "adj.", "联邦的", "限定1968年法案段的陪审员层级，与state州一级对照。", "national（全国的，制度层级不完全相同）"],
  ["random", "", "adj./n.", "随机的；随机方式", "at random整体表示随机，与randomly为不同词位。", "randomly（随机地，副词）"],
  ["landmark", "landmarks", "n.（定语）", "里程碑；转折性的", "landmark decision为具有重大意义的判决，不是地理标志。", "significant（重要的，力度较弱）"],
  ["decision", "decisions", "n.", "判决；裁定", "Taylor decision特指法院裁判，不是普通个人决定。", "judgment（判决、判断）"],
  ["taylor", "", "n.（专名）", "泰勒", "1975年泰勒诉路易斯安那州案名称中的当事方。", ""],
  ["louisiana", "", "n.（专名）", "路易斯安那州", "1975年案件被诉州，与1880年West Virginia不同。", ""],
  ["extend", "extends extended extending", "v.", "扩展；延伸", "extend the requirement to the state level把要求扩展到州层级。", "expand（扩大，介词搭配需核对）"],
  ["level", "levels", "n.", "层级", "the state level指州一级管辖层次，不是水平高低。", "stage（阶段，主要是时间进程，不能直接替换层级）"],
  ["declare", "declares declared declaring", "v.", "宣布；认定", "declare discrimination to be unconstitutional认定歧视违宪。", "state（声明，不必具有法律裁定效力）"],
  ["unconstitutional", "", "adj.", "违宪的", "指不符合宪法，不只是社会上不受欢迎。", "illegal（违法的，法源范围较宽）"],
  ["order", "orders ordered ordering", "v.", "命令；责令", "ordered states to use是法院要求各州执行，不是订购。", "require（要求，语气和权力背景不同）"],
  ["state", "states", "n.", "州", "美国联邦体系中的州；state juries中的state为名词定语。", "不是动词陈述。"],
  ["literate", "", "adj.", "识字的", "与illiterate对照，首句有literacy基本资格。", "educated（受过教育的，范围更广）"],
  ["illiterate", "", "adj.", "不识字的", "第36题A将不识字者也列入资格范围，违背首句条件。", "与literate相反，不是同义词。"],
  ["immune", "", "adj.", "免受……的", "immune from trial是免受审判，与entitled to trial有权受审含义相反。", "exempt（获豁免的，法律身份侧重不同）"],
  ["impose", "imposes imposed imposing", "v.", "施加；规定", "impose a limit设限制，选项的no会否认原文年龄条件。", "set（设定，语气较中性）"],
  ["judgment", "judgments", "n.", "判断；裁决", "应考虑公众道德判断，不是单凭人数决定所有法律问题。", "verdict（裁决，更具体）"],
  ["opinion", "opinions", "n.", "意见；看法", "the opinion of the public概括community conscience这一维度。", "view（看法）"],
  ["prior", "", "adj./介词搭配成分", "在……之前", "prior to 1968锁定立法改革前的实践。", "before（在……之前，结构更简单）"],
  ["show", "shows showed shown showing", "v.", "显示；表明", "showed后接做法揭示的深层问题。", "indicate（表明，语气较谨慎）"],
  ["inadequacy", "inadequacies", "n.", "不充分；不足", "法律可被绕过体现保障不足，不表示没有任何反歧视法。", "failure（失败，表述可能更强）"],
  ["prevalent", "", "adj.", "普遍存在的", "第37题B强调歧视现象广泛，但未概括法律约束不足的让步逻辑。", "common（常见的）"],
  ["arrogance", "", "n.", "傲慢", "评价法官傲慢在原文中无依据，不能从制度缺陷推出人物心理。", "不是criticism批评行为。"],
  ["common", "", "adj.", "普遍的；常见的", "common among judges为在法官群体中常见，不是某人共享所有权。", "usual（通常的）"],
  ["seldom", "", "adv.", "很少", "seldom on the jury list指女性极少列名，不等于绝无例外。", "rarely（很少）"],
  ["ban", "bans banned banning", "v.", "禁止", "banned含禁止参与之义，强于exempted默认免除职责；过去式双写n。", "prohibit（禁止）"],
  ["suppose", "supposes supposed supposing", "v.", "认为；预设", "be supposed to perform表示社会期待女性承担家务。", "expect（期待或认为应当）"],
  ["domestic", "", "adj.", "家庭的", "domestic duties指家务职责，不是国内事务。", "household（家庭事务的，名词定语）"],
  ["evade", "evades evaded evading", "v.", "逃避；规避", "evade public engagement把责任归给女性意愿，原文没有支持。", "avoid（避免，未必含逃避责任）"],
  ["engagement", "engagements", "n.", "参与", "public engagement为公共参与，不是订婚或约会。", "participation（参与）"],
  ["rigid", "", "adj.", "严苛的；僵硬的", "less rigid说明特殊教育门槛放宽，不表示完全无要求。", "strict（严格的）"],
  ["ought", "", "modal v.", "应当", "ought to后接动词原形，是规范性判断而非已经发生的事实。", "should（应当，不带to）"],
  ["conform", "conforms conformed conforming", "v.", "遵从；符合", "conform to后接规范或要求；选项泛化了文中具体改革内容。", "follow（遵循，直接接宾语）"],
  ["discuss", "discusses discussed discussing", "v.", "讨论", "in discussing...为介词加动名词，限定讨论主题。", "examine（考察，分析意味更强）"],
  ["characteristic", "characteristics", "n.", "特点；特征", "its characteristics指制度特点，单列该名词而非character品格。", "feature（特征）"],
  ["solution", "solutions", "n.", "解决办法", "problems and solutions只覆盖部分叙事，不能遗漏民主传统和整体发展。", "answer（答案、应对办法，范围不同）"],
  ["tradition", "traditions", "n.", "传统", "全文开篇民主价值与直接民主形式构成制度传统。", "practice（惯例，未必历史悠久）"],
  ["development", "developments", "n.", "发展；演变", "时间线中的制度演进，涵盖歧视问题及改革，不只经济增长。", "change（变化，未必含历时演进）"],
] as const;
export const passage2010P4Lexicon: Record<string, Entry> = Object.fromEntries(rows.map(([headword, forms, partOfSpeech, contextualMeaning, use, comparison]) => [headword, { partOfSpeech, contextualMeaning, use: comparison && !/^[a-z][a-z -]*（.+）$/i.test(comparison) ? `${use}${comparison}` : use, specialForms: [forms ? `${headword}：${forms}` : "本义无需要另记的屈折变化"], examSynonyms: /^[a-z][a-z -]*（.+）$/i.test(comparison) ? [comparison] : [] }]));
export const passage2010P4LemmaAliases: Record<string, string> = Object.fromEntries(rows.flatMap(([headword, forms]) => forms.split(" ").filter(Boolean).map(form => [form, headword])));
passage2010P4LemmaAliases.including = "including";
// 本篇 US 均为国家缩写；仅在本篇隔离，保留其他篇 us→we。
passage2010P4LemmaAliases.us = "us";
export const passage2010P4FamilyAliases: Record<string, string> = { juror: "jury", democratic: "democracy", literacy: "literate", illiterate: "literate", representative: "represent", unrepresentative: "represent", selection: "select", racial: "race", discrimination: "discriminate", antidiscrimination: "discriminate", educational: "education", requirement: "require", unconstitutional: "constitution", inadequacy: "adequate", development: "develop" };
export const passage2010P4FormPartOfSpeech: Record<string, string> = { including: "prep.（包括）", representatives: "n.（代表）", representative: "adj.（有代表性的；代议的）", direct: "adj.（直接的）", right: "n.（权利）", following: "adj.（下列的）", surviving: "v.-ing（作定语）", best: "adj.（最高级）", mid: "构词成分（中期）", th: "序数词后缀" };
export const passage2010P4SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2010-p4-s1": { meet: { contextualMeaning: "达到；满足", use: "meet minimal qualifications直接接资格要求作宾语。" }, letter: { contextualMeaning: "法律的字面条文", use: "the letter of the law与the conscience of the community对比。" }, national: { contextualMeaning: "民族或国家的", use: "national origin表示出身背景，作为不应据以歧视的因素。" } },
  "2010-p4-s2": { representative: { contextualMeaning: "代议制的", use: "representative democracy指由选举代表代为治理的民主形式。" } },
  "2010-p4-s3": { representative: { contextualMeaning: "代表（名词复数）", use: "electing representatives中为选举的宾语，代表替公民治理。" }, turn: { contextualMeaning: "轮次", use: "take turns governing表示轮流治理，不是向某人求助。" } },
  "2010-p4-s6": { around: { contextualMeaning: "绕过；规避", use: "way around laws指规避反歧视要求的途径。" } },
  "2010-p4-s8": { it: { contextualMeaning: "强调句的形式成分", use: "it was not until...that强调多数州迟至1940年代才承认女性资格，不指代具体人或物。" }, make: { contextualMeaning: "使具备某种资格", use: "made women eligible中women为宾语，eligible为形容词宾补。" } },
  "2010-p4-s9": { have: { contextualMeaning: "使……得到处理", use: "have their names included为使役结构，included是过去分词宾补，不是完成时。" }, they: { contextualMeaning: "女性", use: "unless they personally asked指女性本人主动请求，不是各州提出请求。" } },
  "2010-p4-s10": { it: { contextualMeaning: "默认豁免女性的做法", use: "it回指This practice，这一做法使陪审团缺乏女性代表性。" }, need: { contextualMeaning: "被认为需要（留在家中）", use: "were needed at home是当时为排除女性提供的辩护，不能当成作者赞同。" }, through: { contextualMeaning: "贯穿整个时期", use: "through the 1960s表示这一状态贯穿整个1960年代，而非通过某手段。" } },
  "2010-p4-s12": { they: { contextualMeaning: "联邦陪审员", use: "宾格them回指federal jurors，是required的宾语及被选出的对象。" }, random: { contextualMeaning: "随机地（搭配中）", use: "at random整体作方式状语，修饰to be selected。" } },
  "2010-p4-s13": { be: { contextualMeaning: "应当具有（代表性）", use: "requirement后that从句采用原形be表示要求类虚拟语气，不是漏写时态。" }, representative: { contextualMeaning: "有代表性的", use: "be representative of说明应代表哪些社会群体，与第2句代议制含义不同。" } },
};
