import type { SentenceWordContext } from "./contextual-vocabulary";
type Entry = { partOfSpeech: string; contextualMeaning: string; use: string; specialForms: string[]; examSynonyms: string[]; collocations: string[]; contextualSubstitutions?: SentenceWordContext["contextualSubstitutions"] };
const rows = [
  ["a350", "", "proper n.（机型代号）", "空客A350机型", "原卷第1句由respectively把A350与Airbus对应；字母和数字为整体，不能拆成冠词A。", "the A350 aircraft（A350飞机）"],
  ["boeing", "", "proper n.", "波音公司", "飞机制造商；787对应波音，后文波音为受资助研究方。", "pay Boeing（向波音付费）"],
  ["airbus", "", "proper n.", "空客公司", "飞机制造商；respectively把A350与空客对应。", "Boeing and Airbus（波音与空客）"],
  ["trumpet", "trumpets trumpeted trumpeting", "v.", "大力宣扬", "比喻高调宣传，宾语为飞机效率，不是吹乐器。", "trumpet the efficiency（大力宣扬效率）", "publicize（宣传，较中性）"],
  ["publicize", "publicizes publicized publicizing", "v.", "宣传；使公众知晓", "直接接宣传的信息，比trumpet少夸耀意味。", "publicize an advantage（宣传优势）"],
  ["efficiency", "", "n.", "效率；能效", "飞机用较少燃油完成运输的效率，区别有效性effectiveness。", "aircraft efficiency（飞机能效）"],
  ["new", "newer newest", "adj.", "新的；最新的", "newest最高级修饰机型，并非研究要求必须购新机。", "new aircraft（新飞机）"],
  ["aircraft", "aircraft", "n.", "飞机；航空器", "单复数同形，结合three或上下文判断数量。", "passenger aircraft（客机）", "plane（飞机，较日常）"],
  ["respectively", "", "adv.", "分别；依次对应地", "前后列表依次对应：波音—787，空客—A350。", "A and B respectively（分别为A和B）"],
  ["clever", "cleverer cleverest", "adj.", "巧妙的", "clever designs赞扬设计巧思，不是飞机有人的智力。", "clever designs（巧妙设计）"],
  ["design", "designs", "n.", "设计方案", "designs与composites并列作主语，为名词复数。", "aircraft designs（飞机设计）"],
  ["lightweight", "", "adj.", "轻质的", "修饰composites，强调材料的重量优势。", "lightweight composites（轻质复合材料）"],
  ["composite", "composites", "n.", "复合材料", "由不同材料结合而成，本文为名词复数。", "lightweight composites（轻质复合材料）"],
  ["certainly", "", "adv.", "确实；无疑", "承认新机设计有用，为But引出不同思路铺垫。", "certainly make a difference（确实起作用）"],
  ["difference", "differences", "n.", "作用；差别", "make a difference整体为产生影响。", "make a difference（起作用）"],
  ["researcher", "researchers", "n.", "研究人员", "斯坦福研究团队；名词不归入research动词的屈折词形。", "a group of researchers（一组研究人员）"],
  ["stanford", "", "proper n.", "斯坦福（大学）", "与University共同构成学校专名，指出研究来源。", "Stanford University（斯坦福大学）"],
  ["university", "universities", "n.", "大学", "专名中大写，本文出现斯坦福和南加州大学。", "at university（在大学）"],
  ["lead", "leads led leading", "v.", "带领", "led by为被动分词短语，说明研究负责人；过去式、分词均为led。", "be led by somebody（由某人带领）"],
  ["ilan", "", "proper n.", "伊兰（人名）", "Ilan Kroo中的名，与姓共同标识研究负责人。", "Ilan Kroo（伊兰·克鲁）"],
  ["kroo", "", "proper n.", "克鲁（姓氏）", "研究负责人，不是末段讲述战时家族背景的Lissaman。", "Dr. Kroo（克鲁博士）"],
  ["suggest", "suggests suggested suggesting", "v.", "提出；指出可能性", "suggest that给出研究设想，could/might仍保留不确定性。", "suggest that...（提出……）", "propose（提出方案，更主动）"],
  ["propose", "proposes proposed proposing", "v.", "提出", "可接方案或that从句，比suggest更突出主动主张。", "propose a plan（提出计划）"],
  ["airline", "airlines", "n.", "航空公司", "经营航班的企业，与飞机制造商区分。", "for airlines（对航空公司而言）"],
  ["naturalistic", "", "adj.", "模仿自然的", "指效仿鸟类编队，不是艺术流派的自然主义。", "a naturalistic approach（仿自然的方法）"],
  ["approach", "approaches", "n.", "方法；途径", "approach to中的to为介词，后接cutting。", "an approach to doing（做某事的方法）"],
  ["cut", "cuts cutting", "v.", "减少；削减", "cut-cut-cut；cutting双写t，是介词to后的动名词。", "cut fuel use（减少燃油消耗）", "reduce（减少，较中性）"],
  ["jet-fuel", "", "n.（复合定语）", "航空喷气燃油", "修饰use，保留原卷连字符。", "jet-fuel use（航空燃油消耗）"],
  ["use", "uses", "n.", "使用量；消耗", "cutting jet-fuel use中为名词宾语。", "fuel use（燃油使用量）"],
  ["require", "requires required requiring", "v.", "要求；需要", "require them to buy中的them指航空公司，not否定购买要求。", "require somebody to do（要求某人做事）"],
  ["buy", "buys bought buying", "v.", "购买", "buy new aircraft为购新机，不取企业并购义。", "buy aircraft（购买飞机）"],
  ["answer", "answers", "n.", "答案；解决办法", "回指如何用仿自然方法节油，lies with birds说明启示所在。", "the answer lies with...（答案在于……）"],
  ["lie", "lies lay lain lying", "v.", "在于；存在于", "lies with birds说明答案所在；与过去式为lied的撒谎义区分。", "lie with somebody（在于某一方）"],
  ["bird", "birds bird's", "n.", "鸟", "birds为复数，bird's为单数所有格。", "a bird's wings（一只鸟的双翼）"],
  ["fly", "flies flew flown flying", "v.", "飞行", "flying为分词或动名词，flew为过去式；flight不是屈折词形。", "fly in formation（编队飞行）"],
  ["formation", "formations", "n.", "编队；队形", "in formation指按队形飞行。", "formation flight（编队飞行）"],
  ["v-shape", "", "n.", "V字形", "破折号间a V-shape解释鸟类编队形状。", "a V-shape（V字队形）"],
  ["expend", "expends expended expending", "v.", "消耗；耗费", "expend energy较spend正式，不是expand扩大。", "expend less energy（耗费更少能量）", "spend（耗费，较日常）"],
  ["energy", "", "n.", "能量", "飞行、推进所需物理能量，不是个人精力。", "propelling energy（推进能量）"],
  ["air", "", "n.", "空气", "流过鸟翼的空气，不是抽象气氛。", "air flows（气流）"],
  ["flow", "flows flowing flowed", "n./v.", "气流；流动", "flowing over wings为分词；air flows为名词复数。", "flow over wings（流过翼面）"],
  ["wing", "wings", "n.", "翅膀；机翼", "第6句为鸟翼，气流经过翼面后上卷。", "a bird's wings（鸟的双翼）"],
  ["curl", "curls curled curling", "v.", "卷曲；盘卷", "curls upwards描述气流向上卷，主语为air。", "curl upwards（向上卷起）"],
  ["upwards", "", "adv.", "向上", "修饰curls表达方向，不接名词宾语。", "curl upwards（向上盘卷）"],
  ["wingtip", "wingtips", "n.", "翼尖", "wing与tip的复合词，指翼面末端。", "behind the wingtips（翼尖后方）"],
  ["phenomenon", "phenomena", "n.", "现象", "概括空气上卷整件事，复数为phenomena。", "a phenomenon known as...（称为……的现象）"],
  ["upwash", "", "n.", "上洗；上洗气流", "本文为翼尖后方上卷的气流现象，是减阻机制核心。", "in the upwash（在上洗气流中）"],
  ["experience", "experiences experienced experiencing", "v./n.", "经受；体验", "正文experience reduced drag为动词；42题为名词。", "experience reduced drag（承受较小阻力）"],
  ["reduce", "reduces reduced reducing", "v.", "减少；降低", "reduced修饰drag；reducing resistance为动名词结构。", "reduce drag（减小阻力）", "decrease（减少，范围较广）"],
  ["drag", "", "n.", "空气阻力", "飞行阻力，不取拖拽动词义。", "reduced drag（减小的阻力）", "resistance（阻力，适用范围较广）"],
  ["spend", "spends spent spending", "v.", "耗费", "spend energy doing为做某事耗能，不局限花钱。", "spend energy doing（做某事耗费能量）"],
  ["propel", "propels propelled propelling", "v.", "推进", "重读末音节，propelled/propelling双写l；themselves作宾语。", "propel themselves（推进自身）"],
  ["peter", "", "proper n.", "彼得（人名）", "专家Peter Lissaman的名，不与姓作同义词关系。", "Peter Lissaman（彼得·利萨曼）"],
  ["lissaman", "", "proper n.", "利萨曼（姓氏）", "航空学专家，末段亲属飞行经历属于此人。", "Dr. Lissaman（利萨曼博士）"],
  ["aeronautics", "", "n.", "航空学", "学科名以s结尾但并非可数复数。", "an aeronautics expert（航空学专家）"],
  ["expert", "experts", "n.", "专家", "an aeronautics expert为人名的同位说明。", "an expert in aviation（航空专家）"],
  ["formerly", "", "adv.", "以前；从前", "formerly at说明先前任职背景，不表示仍在任。", "formerly at a university（曾在某大学）"],
  ["caltech", "", "proper n.", "加州理工学院", "California Institute of Technology的简称。", "at Caltech（在加州理工学院）"],
  ["southern", "", "adj.", "南部的", "University of Southern California校名组成部分。", "Southern California（南加利福尼亚）"],
  ["california", "", "proper n.", "加利福尼亚", "州名；与Southern共同构成大学名称。", "the University of Southern California（南加州大学）"],
  ["enjoy", "enjoys enjoyed enjoying", "v.", "享有；获得有利结果", "enjoy an increase为获得航程增益，不是心理愉快。", "enjoy a range increase（获得航程提升）"],
  ["range", "ranges", "n.", "航程", "飞行可覆盖的距离，不是价格区间。", "a range increase（航程增加）"],
  ["increase", "increases increased increasing", "n./v.", "增加；增幅", "第8句为名词增幅，第20句increased为分词定语。", "an increase of 71%（增加71%）"],
  ["apply", "applies applied applying", "v.", "应用", "applied to aircraft为被动分词，原理被用于飞机。", "apply a principle to something（把原理用于某物）"],
  ["principle", "principles", "n.", "原理", "指编队利用气流的物理原理，不是道德原则。", "apply principles（应用原理）"],
  ["substantially", "", "adv.", "实质上；在很大程度上", "not substantially different不等于每个细节完全相同。", "substantially different（实质不同）"],
  ["team", "teams", "n.", "团队；队伍", "his team为研究团队，display teams为飞行表演队。", "a research team（研究团队）"],
  ["model", "models modeled modeling modelled modelling", "v.", "建立模型；模拟", "原卷modeled为过去式，研究模型不等于实际客运实施。", "model what would happen（模拟会发生的结果）", "simulate（模拟，强调再现条件）"],
  ["simulate", "simulates simulated simulating", "v.", "模拟", "模拟条件、过程或结果，不必特指哪种模型。", "simulate a flight（模拟飞行）"],
  ["happen", "happens happened happening", "v.", "发生", "what would happen询问结果，As it happens为评注习语。", "what would happen（会发生什么）"],
  ["three", "", "numeral", "三", "模型中有三架客机，不是三个航班总批次。", "three passenger jets（三架喷气客机）"],
  ["passenger", "passengers", "n.", "乘客；客运的（名词定语）", "passenger jets中作定语，A passenger指机内乘客。", "passenger aircraft（客机）"],
  ["jet", "jets", "n.", "喷气式飞机", "模型中的三架喷气客机，不是水流喷射。", "passenger jets（喷气客机）"],
  ["depart", "departs departed departing", "v.", "出发；起飞离开", "departing from修饰jets，说明出发城市。", "depart from a city（从某城市出发）"],
  ["los", "", "proper-name part", "洛斯（地名组成部分）", "Los Angeles整体译洛杉矶，不把Los单独当普通英文词。", "Los Angeles（洛杉矶）"],
  ["angeles", "", "proper-name part", "安吉利斯（地名组成部分）", "与Los共同构成洛杉矶，s不作复数归一化。", "Los Angeles（洛杉矶）"],
  ["san", "", "proper-name part", "圣（地名组成部分）", "San Francisco整体为旧金山，是一架飞机的出发地。", "San Francisco（旧金山）"],
  ["francisco", "", "proper-name part", "弗朗西斯科（地名组成部分）", "与San组成城市名称，不指本文某名人物。", "San Francisco（旧金山）"],
  ["las", "", "proper-name part", "拉斯（地名组成部分）", "Las Vegas整体为拉斯维加斯，不能混同Los Angeles。", "Las Vegas（拉斯维加斯）"],
  ["vegas", "", "proper-name part", "维加斯（地名组成部分）", "与Las构成第三架飞机的出发地名。", "Las Vegas（拉斯维加斯）"],
  ["assemble", "assembles assembled assembling", "v.", "集合；会合", "三机在空中会合，不是装配制造飞机。", "assemble over Utah（在犹他州上空会合）"],
  ["utah", "", "proper n.", "犹他州", "美国州名，模型中的会合空域。", "over Utah（犹他州上空）"],
  ["assume", "assumes assumed assuming", "v.", "采取；呈现", "assume a formation为采取队形，不是假定某观点。", "assume a formation（排成某种队形）"],
  ["invert", "inverts inverted inverting", "v.", "使倒置", "inverted分词作V-formation的定语。", "an inverted V-formation（倒V字队形）"],
  ["v-formation", "", "n.", "V字编队", "与inverted搭配说明模型的队形。", "assume a V-formation（采取V字编队）"],
  ["occasionally", "", "adv.", "偶尔；不时", "修饰change places，表示途中不时交换位置。", "occasionally change places（不时换位）"],
  ["change", "changes changed changing", "v.", "交换；改变", "change places为互换位置，使各机轮流获益。", "change places（换位）"],
  ["place", "places", "n.", "位置", "change places用复数，指不同飞机互换队列位置。", "change places（交换位置）"],
  ["turn", "turns", "n.", "轮次；轮到的机会", "have a turn为轮到有利位置，不是turn to求助。", "have a turn（轮到一次）"],
  ["favourable", "", "adj.", "有利的", "位置气动收益有利，保留英式拼写。", "favourable positions（有利位置）"],
  ["position", "positions", "n.", "位置", "队列中的空间位置，不是职业或观点。", "in a favourable position（处于有利位置）"],
  ["proceed", "proceeds proceeded proceeding", "v.", "继续前往", "to London给出目的地，不是处理某事。", "proceed to a destination（前往目的地）"],
  ["london", "", "proper n.", "伦敦", "英国城市，模型中三机的目的地。", "proceed to London（飞往伦敦）"],
  ["find", "finds found finding", "v.", "发现", "find-found-found；found that引出研究结果，不是found建立。", "find that...（发现……）"],
  ["finding", "findings", "n.", "研究发现；研究结果", "41题Findings为派生名词复数，独立于find动词统计。", "research findings（研究结果）"],
  ["consume", "consumes consumed consuming", "v.", "消耗", "consumed fuel为耗油，不是乘客消费支出。", "consume less fuel（消耗更少燃油）"],
  ["fuel", "", "n.", "燃料；燃油", "航空语境中指飞机消耗的燃油。", "low on fuel（燃油不足）"],
  ["couple", "couples coupled coupling", "v.", "使结合；伴随", "coupled with分词补充节油伴随的碳排放下降。", "coupled with a reduction（伴随减少）"],
  ["reduction", "reductions", "n.", "减少；下降", "reduce的派生名词，保留独立原形、只关联词族。", "a reduction in output（排放量减少）"],
  ["carbon-dioxide", "", "n.（复合定语）", "二氧化碳", "修饰output，不与下一句的氮氧化物混淆。", "carbon-dioxide output（二氧化碳排放量）"],
  ["output", "outputs", "n.", "排出量；排放量", "燃烧所产生的排放量，不是工厂产品产量。", "carbon-dioxide output（二氧化碳排放量）"],
  ["nitrogen-oxide", "", "n.（复合定语）", "氮氧化物", "下降约四分之一的是氮氧化物排放指标。", "nitrogen-oxide emissions（氮氧化物排放）"],
  ["emission", "emissions", "n.", "排放；排放物", "复数作fell主语，指污染物排放量。", "emissions during cruising（巡航中的排放）"],
  ["cruise", "cruises cruised cruising", "v.", "巡航", "cruising修饰飞行阶段，指相对稳定状态下飞行。", "the cruising portions（巡航阶段）"],
  ["portion", "portions", "n.", "部分；阶段", "按飞行过程分阶段，不是食物份量。", "portions of a flight（飞行阶段）"],
  ["flight", "flights", "n.", "飞行；航班", "formation flight指飞行方式，military flights指军事飞行任务。", "formation flight（编队飞行）"],
  ["fall", "falls fell fallen falling", "v.", "下降", "fell by表示下降幅度，fell to才是下降到的数值。", "fall by a quarter（下降四分之一）"],
  ["quarter", "quarters", "n.", "四分之一", "a quarter等于25%，不是一个季度或居住区。", "around a quarter（约四分之一）"],
  ["knot", "knots", "n.", "难题；纠结点", "用绳结比喻问题，不取航速单位‘节’的含义。", "work out knots（解决难题）"],
  ["work", "works worked working", "v.", "解决；开展工作", "work out为解决，working group为开展工作的团队。", "work out a problem（解决问题）"],
  ["consideration", "considerations", "n.", "需要考虑的因素", "One consideration为一个考量，不是体贴他人。", "a safety consideration（安全考量）"],
  ["safety", "", "n.", "安全", "须区分客观安全与乘客主观感受。", "the perception of safety（安全感）"],
  ["perception", "perceptions", "n.", "感受；认知", "the perception of it中的it回指safety。", "the perception of safety（对安全的感受）"],
  ["comfortable", "", "adj.", "舒适的；安心的", "feel comfortable为主系表，关注乘客对编队的感受。", "feel comfortable doing（做某事感到安心）"],
  ["travel", "travels travelled travelling traveled traveling", "v.", "旅行；出行", "原卷travelling为英式双l，逻辑主语为passengers。", "travel in company（结伴出行）"],
  ["company", "companies", "n.", "陪伴；结伴", "in company指与其他飞机结伴，不是企业。", "in company（结伴）"],
  ["point", "points pointed pointing", "v.", "指出", "points out接that从句，out为短语动词一部分。", "point out that...（指出……）"],
  ["separate", "separates separated separating", "v.", "分隔；使相距", "separated by几海里中by引距离而非施动者。", "be separated by miles（相隔数英里）"],
  ["nautical", "", "adj.", "航海的", "nautical mile为海里，航空导航也使用，不等于普通英里。", "nautical miles（海里）"],
  ["mile", "miles", "n.", "英里；海里（在搭配中）", "本篇由nautical限定，必须整体理解为海里。", "a nautical mile（一海里）"],
  ["intimate", "", "adj.", "紧密的", "intimate groupings为空间上靠近的队形，不是私人关系。", "intimate groupings（紧密编队）"],
  ["grouping", "groupings", "n.", "分组；编队排列", "名词表示排列形态，与group动词分开统计。", "intimate groupings（紧密排列）"],
  ["favour", "favours favoured favouring", "v.", "偏爱；倾向采用", "favoured by为被动分词，英式拼写。", "a grouping favoured by teams（队伍偏爱的队形）"],
  ["display", "displays", "n.", "展示；飞行表演", "display teams为飞行表演队，不是显示屏。", "display teams（飞行表演队）"],
  ["red", "", "adj.（专名组成部分）", "红色的", "Red Arrows为红箭队，不是现场红色箭头。", "the Red Arrows（红箭飞行表演队）"],
  ["arrow", "arrows", "n.（专名组成部分）", "箭；红箭队名称组成部分", "Arrows为队名中的名词，原形arrow用于屈折统计。", "the Red Arrows（红箭飞行表演队）"],
  ["peer", "peers peered peering", "v.", "仔细看；张望", "peering修饰乘客，不能套用Text 4的同侪名词义。", "peer out of the window（向窗外张望）"],
  ["window", "windows", "n.", "窗户；舷窗", "飞机上的舷窗，乘客由此向外看。", "out of the window（向窗外）"],
  ["see", "sees saw seen seeing", "v.", "看到；弄清", "看其他飞机为视觉义；remain to be seen为尚待确定。", "see other planes（看到其他飞机）"],
  ["plane", "planes planes'", "n.", "飞机", "planes'为复数所有格，修饰wakes。", "the planes' wakes（飞机尾流）"],
  ["separation", "separations", "n.", "间隔；分离", "派生名词保留独立原形，不归入separate屈折词形。", "separation distances（间隔距离）"],
  ["distance", "distances", "n.", "距离", "本句为机间距离，不是可飞行的航程。", "separation distances（机间距离）"],
  ["involve", "involves involved involving", "v.", "涉及", "distances involved中分词后置，指有关间距。", "the distances involved（涉及的距离）"],
  ["satisfy", "satisfies satisfied satisfying", "v.", "满足；符合", "satisfy regulations是符合要求，不是使乘客心理满意。", "satisfy regulations（满足规章要求）"],
  ["air-traffic", "", "n.（复合定语）", "空中交通", "air-traffic-control整体修饰regulations，说明规定对象。", "air-traffic control（空中交通管制）"],
  ["control", "controls", "n.", "管制；控制", "空管复合词组成部分，不是控制实验中的动词。", "air-traffic-control regulations（空管规定）"],
  ["regulation", "regulations", "n.", "规章；规定", "复数指具体飞行运行要求。", "satisfy regulations（符合规定）"],
  ["matter", "matters", "n.", "问题；事情", "another matter为另一回事，不是物质。", "be another matter（是另一回事）"],
  ["international", "", "adj.", "国际的", "修饰机构性质和范围，不表示国内机关。", "an international organisation（国际组织）"],
  ["civil", "", "adj.", "民用的", "civil aviation与军事航空相对，不是礼貌或民事诉讼。", "civil aviation（民用航空）"],
  ["aviation", "", "n.", "航空；航空活动", "机构名中的航空事业，与航空学aeronautics侧重点不同。", "civil aviation（民用航空）"],
  ["organisation", "organisations", "n.", "组织；机构", "保留原卷英式拼写，本文为国际民航组织。", "the International Civil Aviation Organisation（国际民航组织）"],
  ["include", "includes included including", "v.", "包括；纳入", "纳入规划不等于批准实际运营。", "include something in a plan（把某事纳入计划）"],
  ["possibility", "possibilities", "n.", "可能性", "possibility of formation flying保留实施不确定性。", "the possibility of doing（做某事的可能性）"],
  ["blueprint", "blueprints", "n.", "蓝图；规划", "新运行准则的规划，不是已经生效的法规。", "a blueprint for guidelines（准则规划蓝图）"],
  ["operational", "", "adj.", "运行的；操作的", "飞行运行方面的指导规范，不是战争计划。", "operational guidelines（运行准则）"],
  ["guideline", "guidelines", "n.", "指导原则；准则", "新运行指导要求，不能自动等同已实施法规。", "new operational guidelines（新运行准则）"],
  ["remain", "remains remained remaining", "v.", "仍然；有待", "remains to be seen说明仍未确定。", "remain to be seen（有待确定）"],
  ["weather", "", "n.", "天气", "weather conditions为天气条件，不取经受住动词义。", "weather conditions（天气条件）"],
  ["condition", "conditions", "n.", "条件；状况", "天气状态，不是本文某个语法条件从句。", "weather conditions（天气状况）"],
  ["affect", "affects affected affecting", "v.", "影响", "天气影响气流，区别名词effect。", "affect air flows（影响气流）"],
  ["efficient", "", "adj.", "高效的", "make flight more efficient为提高飞行效率。", "more efficient flight（更高效的飞行）"],
  ["zone", "zones", "n.", "区域", "zones of increased turbulence限定湍流增强的范围。", "zones of turbulence（湍流区域）"],
  ["turbulence", "", "n.", "湍流；紊流", "不规则波动的气流运动，可使有利尾流更快衰减。", "increased turbulence（增强的湍流）"],
  ["wake", "wakes", "n.", "尾流", "飞机后方气流，不是wake up的苏醒动词。", "aircraft wakes（飞机尾流）"],
  ["decay", "decays decayed decaying", "v.", "衰减；逐渐减弱", "尾流作用衰减，不是食物腐烂或道德败坏。", "wakes decay（尾流衰减）"],
  ["quickly", "", "adv.", "迅速地", "more quickly为副词比较级，说明衰减更快。", "decay more quickly（更快衰减）"],
  ["effect", "effects", "n.", "效果；效应", "编队利用气流的有益效应，与affect动词区分。", "the effect will diminish（效应将减弱）"],
  ["diminish", "diminishes diminished diminishing", "v.", "减弱；减少", "本文不及物，the effect为主语，不意味着完全消失。", "the effect diminishes（效果减弱）"],
  ["area", "areas", "n.", "领域；研究问题", "one of the areas为领域之一，不是地理区域。", "areas to investigate（待研究领域）"],
  ["investigate", "investigates investigated investigating", "v.", "调查；研究", "系统研究天气影响或编队技术，不限定犯罪调查。", "investigate further（进一步研究）"],
  ["further", "", "adv.", "进一步", "修饰investigate，指研究深度而非地理距离。", "investigate further（深入研究）"],
  ["hard", "harder hardest", "adj.", "困难的", "hard for airlines to...说协调难度，不是坚硬。", "be hard to co-ordinate（难以协调）"],
  ["co-ordinate", "co-ordinates co-ordinated co-ordinating", "v.", "协调；统筹", "原卷连字符拼写，协调时间与目的地，不是数学坐标。", "co-ordinate departure times（协调起飞时间）"],
  ["departure", "departures", "n.", "出发；起飞", "departure times为起飞时刻，名词独立于depart。", "departure times（起飞时间）"],
  ["time", "times", "n.", "时间；时刻", "departure times为多个起飞时刻，不是倍数。", "departure times（出发时刻）"],
  ["destination", "destinations", "n.", "目的地", "航班目的地，不与destiny命运混用。", "flight destinations（航班目的地）"],
  ["allow", "allows allowed allowing", "v.", "使能够；允许", "allow them to gain为让航空公司能够获益。", "allow somebody to do（让某人能做事）"],
  ["gain", "gains gained gaining", "v.", "获益", "gain from接收益来源。", "gain from formation flight（从编队中获益）", "benefit（受益，常接from）"],
  ["benefit", "benefits benefited benefiting", "v.", "受益", "benefit from指出收益来源，主体可为航空公司。", "benefit from an arrangement（从安排中获益）"],
  ["cargo", "", "n.（作定语）", "货物；货运", "cargo aircraft与客机对照。", "cargo aircraft（货机）"],
  ["contrast", "contrasts", "n.", "对比；对照", "in contrast连接客机与货机的调度差异。", "in contrast（相比之下）"],
  ["easy", "easier easiest", "adj.", "容易的", "easier to reschedule为较容易重新安排航程。", "be easier to reschedule（更易重新调度）"],
  ["reschedule", "reschedules rescheduled rescheduling", "v.", "重新安排时间；重新调度", "re-为再次，宾语可为航班或计划。", "reschedule flights（重新安排航班）"],
  ["routine", "", "adj.", "例行的；常规的", "routine military flights是常规飞行，不代表所有战斗行动。", "routine military flights（例行军事飞行）"],
  ["military", "", "adj.", "军事的；军用的", "some military aircraft并未明确军队国别。", "military aircraft（军用飞机）"],
  ["armed", "", "adj.", "武装的", "armed forces为固定表达，形容词词位不并入arm手臂统计。", "armed forces（武装部队）"],
  ["force", "forces", "n.", "部队；力量", "armed forces为军队，不是气动力数值。", "America's armed forces（美国武装部队）"],
  ["case", "cases", "n.", "事情；待处理问题", "on the case为正在研究此事，不是法庭案件。", "be on the case（着手处理此事）"],
  ["early", "earlier earliest", "adv.", "早；较早", "Earlier this year相对原文写作时定位，不是当前公历年。", "earlier this year（文章当年较早时候）"],
  ["defence", "", "n.", "国防；防御", "机构名称中表示国防，保留英式拼写。", "Defence Advanced Research Projects Agency（国防高级研究计划局）"],
  ["advanced", "", "adj.", "高级的；先进的", "在机构名称中修饰研究项目，不取过去动作义。", "advanced research（先进研究）"],
  ["project", "projects", "n.", "项目；计划", "Research Projects为机构名的一部分，不是投射动词。", "research projects（研究项目）"],
  ["agency", "agencies", "n.", "机构；局", "机构名中心词，作announced的主语。", "a research agency（研究机构）"],
  ["announce", "announces announced announcing", "v.", "宣布", "宣布计划不等于已经执行。", "announce plans（宣布计划）"],
  ["plan", "plans", "n.", "计划", "plans后to pay说明计划内容。", "plans to pay（付费计划）"],
  ["pay", "pays paid paying", "v.", "支付；付费", "pay Boeing to investigate表示付费委托波音研究。", "pay somebody to do（付费让某人做事）"],
  ["programme", "programmes", "n.", "项目；计划", "指研究项目，英式拼写，不是电视节目。", "the programme has yet to begin（项目尚未启动）"],
  ["begin", "begins began begun beginning", "v.", "开始", "has yet to begin整体为尚未开始；beginning双写n。", "has yet to begin（仍未开始）"],
  ["report", "reports", "n.", "报道；传闻", "真实性被unsubstantiated限制，不是确证记录。", "unsubstantiated reports（未经证实的报道）"],
  ["low", "lower lowest", "adj.", "不足的；少的", "low on fuel为燃油存量不足，不是低空飞行。", "be low on fuel（燃油不足）"],
  ["unsubstantiated", "", "adj.", "未经证实的；缺乏证据的", "没有证据支持，不等于已经被证伪。", "unsubstantiated reports（未证实报道）", "unconfirmed（未获确认，不必强调证据不足）"],
  ["unconfirmed", "", "adj.", "未经确认的", "尚未得到可靠确认，不等于false确定为假。", "unconfirmed reports（未确认报道）"],
  ["father", "fathers", "n.", "父亲", "My father中的my为引语说话者利萨曼，不是作者。", "my father（我的父亲）"],
  ["raf", "", "proper n.（缩写）", "英国皇家空军", "Royal Air Force缩写，读字母首音为元音，所以用an。", "an RAF pilot（皇家空军飞行员）"],
  ["pilot", "pilots", "n.", "飞行员", "RAF pilot为人的职业，不是试点形容词。", "an RAF pilot（皇家空军飞行员）"],
  ["cousin", "cousins", "n.", "堂亲；表亲", "词本身不区分堂表及长幼，不能自行明确亲属称谓。", "my cousin（我的一位堂表亲）"],
  ["skipper", "skippers", "n.", "机长；船长", "本文为轰炸机机长，不是船长。", "the skipper of a Lancaster（兰开斯特轰炸机机长）"],
  ["lancaster", "", "proper n.", "兰开斯特轰炸机", "a Lancaster指该型号的一架飞机，不是人物或城市。", "a Lancaster lost over Berlin（损失于柏林上空的兰开斯特轰炸机）"],
  ["lose", "loses lost losing", "v.", "损失；失去", "lost over Berlin修饰飞机，原文未明确机组命运。", "an aircraft lost over a city（损失于某城市上空的飞机）"],
  ["berlin", "", "proper n.", "柏林", "德国城市，over Berlin为飞机损失所在空域。", "over Berlin（柏林上空）"],
  ["add", "adds added adding", "v.", "补充说", "he adds引述家庭背景，不是数学相加。", "he adds（他补充说）"],
  ["promote", "promotes promoted promoting", "v.", "促进；推动", "41题will promote sales是待判断的主张，并非已知结论。", "promote sales（促进销售）"],
  ["sale", "sales", "n.", "销售；销量", "新机销售，不是拍卖场次。", "aircraft sales（飞机销量）"],
  ["save", "saves saved saving", "v.", "节省", "节能、省油，不是挽救生命。", "save fuel（节省燃油）"],
  ["resistance", "", "n.", "阻力", "42题对应正文drag，不是政治抵抗。", "reduce resistance（减少阻力）"],
  ["role", "roles", "n.", "作用", "the role that weather plays中role是plays的宾语。", "play a role（起作用）"],
  ["define", "defines defined defining", "v.", "界定；明确说明", "has not yet been clearly defined为否定完成时被动。", "clearly define a role（明确界定作用）"],
  ["clearly", "", "adv.", "清楚地；明确地", "派生副词修饰defined，不并入形容词clear统计。", "clearly defined（得到明确界定的）"],
  ["document", "documents documented documenting", "v.", "记录；用资料证实", "45题把传闻提升为已有资料确证，原文不支持。", "document an event（记录事件并提供资料）"],
  ["try", "tries tried trying", "v.", "尝试", "45题指尝试编队飞行，需要以原文判断。", "try formation flight（尝试编队飞行）"],
  ["true", "", "adj.", "正确的；符合原文的", "T选项要求整项陈述符合原文，而非只对一部分。", "a true statement（正确陈述）"],
  ["false", "", "adj.", "不正确的；不符合原文的", "F选项为题干不成立；未证实不可当成已经确证。", "a false statement（不正确陈述）"],
  ["take", "takes took taken taking", "v.", "采取", "take an approach为采取方法，不是接管企业。", "take an approach（采取方法）"],
  ["make", "makes made making", "v.", "产生；使", "make a difference为起作用，make flight efficient为使飞行高效。", "make a difference（产生影响）"],
  ["feel", "feels felt feeling", "v.", "感到", "feel comfortable接形容词表语，不接副词comfortably。", "feel comfortable（感到安心）"],
  ["have", "has had having", "aux./v.", "完成时助动词；有", "have trumpeted为完成时；have a turn为实义动词。", "have a turn（轮到一次）"],
  ["know", "knows knew known knowing", "v.", "知道；了解", "have known为已知，known as为被称作，should know为理应了解。", "be known as（被称作）"],
  ["around", "", "adv./prep.", "大约；周围", "around a quarter在数量前表示约数，不是规避规定。", "around a quarter（约四分之一）"],
  ["behind", "", "prep.", "在……后方", "翼尖后方为空间位置，不是发展落后。", "behind the wingtips（翼尖后方）"],
  ["over", "", "prep.", "越过；在……上方", "气流越过翼面、飞机在州或城市上空，均为空间义。", "over Utah（犹他州上空）"],
  ["with", "", "prep.", "与；在……一方", "lies with表示答案所在，coupled with表示伴随。", "coupled with（伴随）"],
  ["by", "", "prep.", "由；相隔；减少了", "按句分别引施动者、间距或变化幅度。", "fall by a quarter（下降了四分之一）"],
  ["as", "", "prep./conj./adv.", "作为；如同；程度标记", "known as引名称，as much as表幅度，as might为类比，As it happens为评注。", "as much as（多达）"],
  ["since", "", "prep.", "自……以来", "Since 1914与have known配合，不是原因连词。", "since 1914（自1914年以来）"],
  ["so", "", "conj./adv.", "以便；因此", "第10句表换位目的，末句表作者推断。", "so all could have a turn（以便所有飞机轮流获益）"],
  ["should", "", "modal v.", "按理应当；应当", "末句为合理推断，而非要求他去了解的义务。", "should know（理应了解）"],
  ["will", "would", "modal v.", "将；假设会", "will表预测，would用于假设，不取意愿名词义。", "what would happen（会发生什么）"],
  ["can", "could", "modal v.", "能够；可能", "could表假设能力或可能，can not不能替代might not的可能否定。", "could be separated（可以相隔）"],
  ["may", "might", "modal v.", "可能", "may/might均保留可能性，不是必然结论。", "might not see（可能看不到）"],
  ["most", "", "adv.", "最", "the most favourable构成最高级，不是大多数。", "the most favourable positions（最有利的位置）"],
  ["more", "", "adv.", "更", "修饰naturalistic、efficient、quickly、comfortable构成比较。", "more efficient（更高效）"],
  ["less", "", "det./adv.", "更少（的）", "修饰不可数energy/fuel，区别复数可数词用fewer。", "less fuel（更少燃油）"],
  ["well", "", "adv.（固定结构中）", "也；以及", "as well as连接另一项益处，不是健康或水井义。", "as well as（也；以及）"],
  ["yet", "", "adv.", "还；尚", "has yet to与not yet都强调当时仍未完成。", "not yet（尚未）"],
  ["themselves", "", "reflexive pron.", "它们自己", "propelling themselves中为鸟类自身，不指其他文章的迁移运动。", "propel themselves（推进自身）"],
  ["play", "plays played playing", "v.", "起作用；扮演", "44题play a role指天气在编队飞行中起的作用，不是玩耍。", "play a role（起作用）"],
  ["both", "", "det./pron.", "两者都", "both A and B连接波音与空客，作主语时谓语用have。", "both Boeing and Airbus（波音和空客两者）"],
  ["and", "", "conj.", "和；并且", "连接词、短语或分句；第10句并列四个动词均受were to支配。", "assemble and proceed（会合并前往）"],
  ["the", "", "art.", "特指已知对象", "the aircraft指已引入的飞机，the air flows指相关气流；无普通屈折变化。", "the aircraft（这些飞机）"],
  ["of", "", "prep.", "……的；由……构成", "of their aircraft表所属，of 25 birds表组成，of 71%表增幅。", "a formation of birds（鸟类组成的编队）"],
  ["they", "them their theirs", "pron.", "他们；它们", "按句回指研究者、航空公司、飞机或报道，宾格them、物主形式their须分别识别。", "their newest aircraft（它们最新的飞机）"],
  ["a", "", "art.", "一个；泛指一类", "用于辅音音素开头的单数可数名词，如a passenger。", "a passenger（一名乘客）"],
  ["an", "", "art.", "一个（元音音素前）", "按读音用an，如an aeronautics expert和an RAF pilot。", "an RAF pilot（一名皇家空军飞行员）"],
  ["but", "", "conj.", "但是；然而", "第3句转向另一方案，第26句转向报道未获证实的限制。", "but reports are unsubstantiated（但报道未经证实）"],
  ["group", "groups", "n.", "群体；小组", "a group of researchers中心为group，所以用has。", "a group of researchers（一组研究人员）"],
  ["at", "", "prep.", "在；至少（搭配中）", "at Stanford表研究机构；at least表最低限度，必须整体理解。", "at Stanford University（在斯坦福大学）"],
  ["that", "", "conj./relative pron.", "引出内容或限定关系", "suggested that引宾语，reports that引内容，air flows that中作定语从句主语。", "reports that...（关于……的报道）"],
  ["to", "", "prep./infinitive marker", "到；不定式标记", "approach to cutting中为介词；to buy为不定式；to London表目的地。", "proceed to London（前往伦敦）"],
  ["it", "", "pron.", "它；形式主语", "可指节油方法或安全，也可为后置从句或不定式占主语位置，逐句区分。", "It remains to be seen（这仍有待确定）"],
  ["not", "", "adv.", "不；否定", "not require否定购机要求，might not表可能不发生，不能省略否定。", "not require new aircraft（不要求新飞机）"],
  ["say", "says said saying", "v.", "说；表示", "says引研究者话语；第4句says Dr. Kroo为插入倒装引述。", "Dr. Kroo says（克鲁博士说）"],
  ["scientist", "scientists", "n.", "科学家", "科学家自1914年以来认识到鸟类编队能节能。", "scientists have known（科学家早已知道）"],
  ["in", "", "prep.", "在……中；以……方式", "in formation和in company表飞行方式；in zones表所在区域。", "in formation（以编队方式）"],
  ["other", "", "det./adj.", "其他的", "Other birds为其他鸟；the other planes为同一编队其余飞机。", "the other planes（其他飞机）"],
  ["who", "", "relative pron.", "引出人的定语从句", "who was formerly...回指expert，在从句中作主语。", "an expert who...（一位……的专家）"],
  ["be", "am is are was were been being", "aux./v.", "是；处于；被动助动词", "are different为系表，could be separated为被动，were to为假设安排。", "be separated（被分隔）"],
  ["when", "", "conj.", "当……时", "When applied省主语及are；when they were low说明燃油不足情境。", "when low on fuel（燃油不足时）"],
  ["different", "", "adj.", "不同的", "not substantially different否认实质差别，不保证完全相同。", "substantially different（实质不同）"],
  ["he", "him his", "pron.", "他；他的（his）", "按句指克鲁或利萨曼，he adds和he should know指后者。", "his team（他的团队）"],
  ["what", "", "interrogative pron.", "什么；会发生的事情", "modeled what would happen为间接疑问，what作内部主语。", "what would happen（会发生什么）"],
  ["if", "", "conj.", "如果；假如", "if three jets were to引模型的假设条件，不是已实施事实。", "if aircraft were to assemble（假如飞机会合）"],
  ["from", "", "prep.", "从；来自", "departing from引出发地，gain from引收益来源。", "depart from a city（从城市出发）"],
  ["all", "", "pron./det.", "所有；全部", "so all could have a turn中all为三架飞机，独立作主语。", "all could have a turn（全部都能轮到）"],
  ["much", "", "adv./det.", "很多；程度标记", "as much as 15%突出数量幅度，与less一同说明省油。", "as much as 15%（多达15%）"],
  ["during", "", "prep.", "在……期间", "接名词时间段，如巡航阶段或二战时期，不直接引主谓从句。", "during the flight（飞行期间）"],
  ["there", "", "existential marker", "有；存在", "There are knots/reports引出存在的难题或报道，不是地点副词。", "There are reports（有报道）"],
  ["course", "", "n.（固定短语中）", "当然（of course中）", "of course为插入评注，不是课程。", "of course（当然）"],
  ["out", "", "particle/adv.", "出来；短语动词小品词", "work out为解决、point out为指出、out of the window为朝窗外。", "point out（指出）"],
  ["one", "", "numeral/pron.", "一个；之一", "One consideration是一个因素；one of the areas为领域之一。", "one of the areas（领域之一）"],
  ["or", "", "conj.", "或者；或至少", "or at least修正前面safety为至少要考虑安全感，不是两个互斥选项。", "or at least（或至少）"],
  ["least", "", "adv.（固定短语中）", "至少（at least中）", "at least限定最低要求，不能使用not least尤其的义项。", "at least（至少）"],
  ["several", "", "det.", "数个；若干", "修饰nautical miles，说明数海里而非精确距离。", "several nautical miles（数海里）"],
  ["like", "", "prep.", "像；例如", "like the Red Arrows为表演队举例，不是喜欢的动词。", "teams like the Red Arrows（像红箭这样的队伍）"],
  ["even", "", "adv.", "甚至", "not even see突出可能连其他飞机都看不到，不是让步连词。", "might not even see（可能甚至看不到）"],
  ["whether", "", "conj.", "是否", "引出机间距是否合规的主语从句，不表示已经合规。", "whether distances satisfy regulations（间距是否满足规定）"],
  ["another", "", "det.", "另一个", "another matter为另一问题，不是重复发生的连串调查。", "another matter（另一回事）"],
  ["although", "", "conj.", "尽管；虽然", "已有规划是让步，不能消除间距是否合规的疑问。", "although a plan exists（尽管已有计划）"],
  ["for", "", "prep.", "对；为了", "for new guidelines引规划对象，for airlines为不定式指定逻辑主语。", "hard for airlines（对航空公司而言困难）"],
  ["how", "", "interrogative adv.", "如何；怎样", "how weather conditions affect...是间接疑问，不是感叹句。", "how weather affects flows（天气如何影响气流）"],
  ["this", "", "pron./det.", "这；这一", "this指天气影响问题；this year相对文章写作时间。", "this is one of the areas（这是领域之一）"],
  ["also", "", "adv.", "还；也", "增加航班调度困难这一方面，与天气等难题并列。", "might also be hard（还可能困难）"],
  ["way", "ways", "n.", "方式；方法", "in a way that...中的that限定能带来编队收益的安排方式。", "in a way that...（以一种……的方式）"],
  ["america", "america's", "proper n.", "美国", "America's修饰armed forces；当时计划不能证明二战已实践。", "America's armed forces（美国军队）"],
  ["on", "", "prep.", "在；关于（搭配中）", "on the case为在处理此事；low on fuel为燃油不足，均需整体理解。", "on the case（处理这件事）"],
  ["already", "", "adv.", "已经", "军方在原文所述当时已着手，不指阅读者现在。", "already on the case（已经着手处理）"],
  ["year", "years", "n.", "年", "Earlier this year相对文章当时定位，不自动指当前年份。", "earlier this year（文章当年较早时候）"],
  ["country", "countries country's", "n.", "国家", "the country's指美国的，修饰机构名称。", "the country's agency（该国机构）"],
  ["research", "", "n.", "研究", "机构名Advanced Research Projects表示先进研究项目，不特指运筹学。", "research projects（研究项目）"],
  ["though", "", "conj.", "不过；尽管", "though programme has yet to begin限制宣布计划的实施程度。", "though it has yet to begin（不过尚未开始）"],
  ["some", "", "det.", "一些", "some military aircraft不指全部军机，也没有明确国别。", "some military aircraft（一些军用飞机）"],
  ["second", "", "ordinal numeral", "第二", "Second World War为固定历史名称，第二次世界大战。", "the Second World War（第二次世界大战）"],
  ["world", "", "n.（作定语）", "世界", "World War构成世界大战名称，不是本篇统计的全球样本。", "World War（世界大战）"],
  ["war", "wars", "n.", "战争", "末段与题45谈论二战期间的历史说法。", "the Second World War（第二次世界大战）"],
  ["my", "", "possessive det.", "我的", "引语中my father/my cousin属于利萨曼的亲属，不是作者亲属。", "my father（我的父亲）"],
  ["because", "", "conj.", "因为", "43题声称看不到别机导致更舒适，此因果未经原文支持。", "because passengers cannot see（因为乘客看不到）"],
  ["once", "", "adv.", "曾经", "45题once tried指过去曾尝试，而非一旦的条件连词。", "once tried（曾尝试）"],
];

export const passage2010P5Lexicon: Record<string, Entry> = Object.fromEntries(rows.map(([headword, forms, partOfSpeech, contextualMeaning, use, collocation, synonym]) => [headword, { partOfSpeech, contextualMeaning, use, specialForms: [forms ? `${headword}：${forms}` : "本义无需要另记的屈折变化"], examSynonyms: synonym ? [synonym] : [], collocations: [collocation.split("（")[0]] }]));
export const passage2010P5CollocationNotes = Object.fromEntries(rows.map(([, , , , note, collocation]) => [collocation.split("（")[0].toLowerCase(), { meaning: collocation.match(/（(.+)）/)![1], note }]));
export const passage2010P5LemmaAliases: Record<string, string> = Object.fromEntries(rows.flatMap(([headword, forms]) => [headword, ...forms.split(" ").filter(Boolean)].map(form => [form, headword])));
export const passage2010P5FamilyAliases: Record<string, string> = { efficiency: "efficient", formation: "form", flight: "fly", researcher: "research", finding: "find", reduction: "reduce", separation: "separate", departure: "depart", resistance: "resist", clearly: "clear", grouping: "group", favourable: "favour", operational: "operate" };
export const passage2010P5FormPartOfSpeech: Record<string, string> = { designs: "n.（复数）", findings: "n.（研究结果，复数）", flowing: "v.-ing（分词）", flows: "n.（气流，复数）", flying: "v.-ing（分词或动名词）", cruising: "v.-ing（作定语）", propelling: "v.-ing（动名词）", peering: "v.-ing（作定语）", increased: "v.-ed（分词作定语）", points: "v.（第三人称单数）", armed: "adj.", routine: "adj.", use: "n.", times: "n.（时刻，复数）", less: "det./adv.（比较级）", more: "adv.（比较级）", most: "adv.（最高级）" };
Object.assign(passage2010P5FormPartOfSpeech, { their: "possessive det.（它们的）", theirs: "possessive pron.（它们的事物）", them: "pron.（宾格）", his: "possessive det.（他的）", him: "pron.（宾格）" });
export const passage2010P5SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2010-p5-s1": { they: { contextualMeaning: "波音和空客（所有格their）", use: "their newest aircraft指两家公司各自最新飞机，respectively依次对应型号。" }, have: { contextualMeaning: "已经（完成时助动词）", use: "have trumpeted与复数主语Both Boeing and Airbus一致，表示此前已作宣传。" } },
  "2010-p5-s2": { make: { contextualMeaning: "起作用", use: "make a difference整体表示产生作用，主语是设计与复合材料。" } },
  "2010-p5-s3": { it: { contextualMeaning: "这种仿自然的节能方法", use: "it would not require中的it回指approach，不是飞机。" }, they: { contextualMeaning: "航空公司（宾格them）", use: "require them to buy中them回指airlines，是购买动作的潜在执行者。" }, that: { contextualMeaning: "引出建议内容", use: "that统领airlines could take与it would not require两个判断，不作内部主宾成分。" } },
  "2010-p5-s4": { with: { contextualMeaning: "在于；存在于……一方", use: "lies with birds表示答案要从鸟类寻找，不是与鸟共处。" } },
  "2010-p5-s5": { since: { contextualMeaning: "自1914年以来", use: "Since后接时间点，主句have known使用现在完成时。" } },
  "2010-p5-s6": { know: { contextualMeaning: "被称为", use: "known as upwash为分词定语，给phenomenon命名。" }, as: { contextualMeaning: "称作；作为名称", use: "known as中的as引现象名称，不引原因或比较从句。" }, flow: { contextualMeaning: "流过", use: "flowing over wings作air的后置分词定语，主句谓语是curls。" } },
  "2010-p5-s7": { experience: { contextualMeaning: "经受；承受", use: "experience为动词，reduced drag为宾语；42题experience为名词。" }, themselves: { contextualMeaning: "鸟类自己", use: "propelling themselves的执行者和承受者都是birds。" } },
  "2010-p5-s8": { enjoy: { contextualMeaning: "获得航程方面的增益", use: "might enjoy a range increase指可能飞得更远，不是主观心情。" }, at: { contextualMeaning: "曾在某机构任职", use: "was formerly at Caltech and...交代专家先前任职背景。" } },
  "2010-p5-s9": { when: { contextualMeaning: "当这些原理用于飞机时", use: "When applied省略the principles are，原理是被应用对象。" } },
  "2010-p5-s10": { assume: { contextualMeaning: "排成；采取（队形）", use: "assume与assemble、change、proceed并列，共享were to。" }, so: { contextualMeaning: "以便", use: "so all could引出交换位置的目的，不是总结模型结果。" }, all: { contextualMeaning: "全部三架飞机", use: "all独立作so从句主语，回指三机。" }, be: { contextualMeaning: "假设要（were to中）", use: "were to统领四个并列动词，说明模型中的假设安排。" } },
  "2010-p5-s11": { they: { contextualMeaning: "克鲁及研究团队", use: "They found为研究者发现模型结果，不是飞机发现事实。" }, as: { contextualMeaning: "多达（as much as中）", use: "as much as 15%突出节油幅度，不是只用15%的油。" } },
  "2010-p5-s12": { by: { contextualMeaning: "下降了（幅度）", use: "fell by a quarter表示减少约四分之一，不能改为fell to降到。" } },
  "2010-p5-s13": { there: { contextualMeaning: "存在（存在句标记）", use: "There are knots引出难题，不表示地点。" }, work: { contextualMeaning: "解决", use: "to be worked out为被动不定式，后置修饰knots。" } },
  "2010-p5-s14": { it: { contextualMeaning: "安全", use: "the perception of it中的it回指safety；感到安全不证明客观安全。" } },
  "2010-p5-s15": { company: { contextualMeaning: "结伴；有同伴", use: "travelling in company为与其他飞机结伴，不是企业义。" }, will: { contextualMeaning: "在假设情境下是否会（would）", use: "Would前置构成疑问，不能译成更舒适的肯定断言。" } },
  "2010-p5-s16": { by: { contextualMeaning: "相隔；由（两处功能不同）", use: "separated by several nautical miles中引距离；favoured by display teams中引偏爱者。" }, intimate: { contextualMeaning: "空间上紧密的", use: "intimate groupings为表演队密集队形，不是人际亲密关系。" } },
  "2010-p5-s17": { peer: { contextualMeaning: "仔细看；张望", use: "peering out of the window作乘客后置定语，不用同侪名词义。" }, may: { contextualMeaning: "可能（might）", use: "might not even see只是可能看不到，不是确定不能看到。" }, see: { contextualMeaning: "看到", use: "see the other planes为视觉感知，不是把某事看作某物。" } },
  "2010-p5-s18": { whether: { contextualMeaning: "是否", use: "Whether...regulations整项疑问作主语，is another matter表示仍待解决。" }, include: { contextualMeaning: "已纳入规划", use: "has included the possibility in a blueprint不等于批准运营。" }, work: { contextualMeaning: "开展工作的（分词定语）", use: "a working group为工作组，与第13句work out解决的搭配不同。" } },
  "2010-p5-s19": { it: { contextualMeaning: "形式主语，不指具体事物", use: "后置how从句才是真正有待确定的内容。" }, see: { contextualMeaning: "确定；弄清", use: "remains to be seen是仍有待确定，不是乘客看飞机。" }, flow: { contextualMeaning: "气流（名词复数）", use: "air flows是affect宾语，that从句解释其使编队高效的作用。" }, make: { contextualMeaning: "使……变得", use: "make formation flight more efficient中flight为宾语，more efficient为宾补。" } },
  "2010-p5-s20": { wake: { contextualMeaning: "飞机尾流", use: "planes' wakes指飞机身后的气流，不是醒来。" }, increase: { contextualMeaning: "增强的（increased）", use: "分词定语修饰turbulence，与第8句名词增幅不同。" }, effect: { contextualMeaning: "气流带来的有益效应", use: "尾流加速衰减使编队节能效益降低。" } },
  "2010-p5-s21": { this: { contextualMeaning: "天气及湍流影响问题", use: "回指上文尚需研究的机制，不是全部研究均未开始。" } },
  "2010-p5-s22": { it: { contextualMeaning: "形式主语", use: "真正主语是to co-ordinate，for airlines给出执行方。" }, they: { contextualMeaning: "航空公司（them）", use: "allow them to gain回指airlines，说明谁从编队获益。" } },
  "2010-p5-s23": { as: { contextualMeaning: "也同样如此", use: "as might routine military flights倒装且省略be easier to reschedule。" }, routine: { contextualMeaning: "例行的", use: "形容军事飞行的常规性质，不是惯例名词。" } },
  "2010-p5-s24": { as: { contextualMeaning: "碰巧；事实上（评注）", use: "As it happens整体引出与前句设想相呼应的事实。" }, case: { contextualMeaning: "这项待研究的事情", use: "on the case表示军方已着手处理，不是案件。" } },
  "2010-p5-s25": { early: { contextualMeaning: "文章写作当年较早时候", use: "Earlier this year不是读者当前年份的新闻。" }, yet: { contextualMeaning: "尚未", use: "has yet to begin整体表示项目仍未启动。" } },
  "2010-p5-s26": { they: { contextualMeaning: "军机；报道（两次回指不同）", use: "when they were low中的they指军机；they are unsubstantiated中的they指reports。" }, that: { contextualMeaning: "引出报道内容", use: "reports that为同位内容从句，that不在内部充当主宾。" } },
  "2010-p5-s27": { lose: { contextualMeaning: "损失（lost分词）", use: "lost over Berlin修饰Lancaster，原文未明确机组最终命运。" }, he: { contextualMeaning: "利萨曼博士", use: "he adds的he为引语说话者，my father和my cousin是他的亲属。" } },
  "2010-p5-s28": { should: { contextualMeaning: "按理应当（推断）", use: "基于背景推断其理应了解，不是给他布置义务。" }, so: { contextualMeaning: "因此", use: "So引出作者推断，不是第10句的目的连词。" } },
};
passage2010P5SentenceContexts["2010-p5-s17"].peer.contextualSubstitutions = [{ label: "look", chinese: "看；向外看", fit: "direct", rewrittenSentence: "A passenger looking out of the window might not even see the other planes.", nuance: "look减弱peer仔细或费力观察的意味，保留可能看不到其他飞机的主命题。", target: "word:look" }];
passage2010P5SentenceContexts["2010-p5-s26"].unsubstantiated = { contextualMeaning: "未经证实的", use: "表语说明报道缺乏证据，不能说历史事件已确证。", contextualSubstitutions: [{ label: "unconfirmed", chinese: "未获确认的", fit: "direct", rewrittenSentence: "There are reports that some military aircraft flew in formation when they were low on fuel during the Second World War, but Dr. Lissaman says they are unconfirmed.", nuance: "unconfirmed偏未获确认；unsubstantiated更强调证据不足，两者均不把报道当成确证事实。", target: "word:unconfirmed" }] };
