import type {SentenceWordContext} from "./contextual-vocabulary";
import type {PhraseKnowledge} from "./knowledge-base";
import {passage2010P5Lexicon} from "./2010-passage-5-lexicon";
import {passage2010P5ReviewedContexts} from "./2010-passage-5-contexts";
type Row=[string,string[],string,string,string,string];
const rows:Row[]=[
["s1",["both","and","boeing","airbus"],"Both Boeing and Airbus","both A and B","波音与空客两者都","两公司并列为主语，后接复数have。"],
["s1",["efficiency","aircraft"],"the efficiency of their newest aircraft","the efficiency of something","各自最新飞机的效率","of引效率所属对象，their回指两家公司。"],
["s2",["make","difference","certainly"],"certainly make a difference","make a difference","确实起作用","承认设计材料有效，再由下一句But转向另一方案。"],
["s3",["lead","by"],"led by Ilan Kroo","be led by somebody","由伊兰·克鲁带领","过去分词补充团队被带领的关系，不是主句谓语。"],
["s3",["approach","to","cut","use"],"a more naturalistic approach to cutting jet-fuel use","an approach to doing something","一种更仿自然的降低航空燃油消耗的方法","approach to中to为介词，cutting接消耗量为宾语。"],
["s3",["it","require","they","buy"],"it would not require them to buy new aircraft","require somebody to do something","该方法不要求航空公司购买新飞机","it为方法，them为航空公司，to buy补足要求内容。"],
["s4",["answer","lie","with"],"lies with birds","the answer lies with somebody / something","答案在鸟类身上","lie with说明答案或关键所在。"],
["s5",["since","have","know"],"Since 1914, scientists have known","since + time with present perfect","自1914年以来科学家已知","since接过去时间起点，完成时表达延续的认识。"],
["s5",["bird","fly","formation"],"birds flying in formation","birds flying in formation","编队飞行的鸟","flying为后置分词，不能当作从句有限谓语。"],
["s6",["air","flow","over"],"The air flowing over a bird's wings","air flowing over wings","流过鸟翼上方的空气","flowing为主动分词定语，中心主语air。"],
["s6",["know","as","phenomenon"],"a phenomenon known as upwash","be known as something","一种称为上洗气流的现象","known as为被动分词定语，as引名称。"],
["s7",["experience","reduce","drag"],"experience reduced drag","experience reduced drag","承受较小的空气阻力","experience在此为动词，reduced修饰drag。"],
["s7",["spend","energy","propel","themselves"],"spend less energy propelling themselves","spend energy doing something","耗费更少能量推进自身","doing说明能量耗费的活动，themselves指鸟类。"],
["s8",["range","increase","enjoy","of"],"might enjoy a range increase of 71%","an increase of a percentage","可能获得71%的航程增幅","increase为名词，of接增幅；might和鸟类模型范围均保留。"],
["s9",["when","apply","to","principle"],"When applied to aircraft","when something is applied to something","当这些原理被用于飞机时","省略the principles are，被应用者为原理，飞机为应用对象。"],
["s10",["model","what","happen","if"],"modeled what would happen if","model what would happen if ...","模拟假如……将发生什么","what作would happen主语，if给假定条件。"],
["s10",["be","assemble","to"],"were to assemble over Utah","were to do something","假定在犹他州上空会合","were to引假设安排，并统领后面三个并列动词。"],
["s10",["assume","invert","v-formation"],"assume an inverted V-formation","assume a formation","组成倒V字队形","assume为呈现队形，inverted为分词定语。"],
["s10",["change","place","so"],"change places so all could have a turn","change places so that ...","换位以便每架都能轮到","so为目的连接词，并非结论因此。"],
["s10",["have","turn","all","position"],"all could have a turn in the most favourable positions","have a turn","每架都能轮流处于最有利位置","all指三架客机，a turn为轮到的机会。"],
["s10",["proceed"],"proceed to London","proceed to a destination","继续前往伦敦","to London引目的地，proceed仍与assemble共享were to。"],
["s11",["as","much","less","fuel"],"as much as 15% less fuel","as much as + percentage + less + noun","少耗最多15%的燃油","15%为较基准的减幅，不是终值。"],
["s11",["couple","with","reduction","output"],"coupled with a reduction in carbon-dioxide output","be coupled with something","伴随二氧化碳排放量减少","过去分词为结果补充，in说明下降指标。"],
["s12",["during","cruise","portion","flight"],"during the cruising portions of the flight","during a phase of something","在飞行巡航阶段","期间介词限定结果范围，不能扩大成全部航程。"],
["s12",["fall","by","around","quarter"],"fell by around a quarter","fall by an amount","下降约四分之一","by为减幅，around为约数。"],
["s13",["there","knot","work","out"],"knots to be worked out","problems to be worked out","有待解决的难题","knots为比喻，to be worked out含被动意义。"],
["s14",["perception","of","it","safety"],"safety, or at least the perception of it","safety, or at least the perception of it","安全性，或至少对安全性的感受","or at least谨慎修正，it回指safety。"],
["s15",["travel","in","company"],"travelling in company","travel in company","结伴出行","company为有同伴，travelling说明乘客感受的情境。"],
["s16",["separate","by","mile"],"separated by several nautical miles","be separated by a distance","相隔数海里","by后距离单位说明相隔幅度，非施事。"],
["s16",["favour","grouping","display"],"groupings favoured by display teams","groupings favoured by somebody","表演队偏爱的队形","favoured为被动分词定语，这里的by引施事。"],
["s17",["peer","out","of","window"],"peering out of the window","peer out of a window","向窗外张望","peering为乘客的分词定语；peer不是同侪名词。"],
["s17",["may","see","even"],"might not even see the other planes","might not even do something","可能甚至看不到其他飞机","might保留可能性，不能替换为确定的can not。"],
["s18",["involve","distance"],"the separation distances involved","the distances involved","涉及的间隔距离","involved后置作分词定语，would satisfy才是从句谓语。"],
["s18",["satisfy","regulation"],"satisfy air-traffic-control regulations","satisfy regulations","满足空管规定","satisfy直接接规定为宾语，不接with。"],
["s18",["include","possibility","in","blueprint"],"included the possibility of formation flying in a blueprint for new operational guidelines","include a possibility in a blueprint","将编队飞行的可能性纳入新准则蓝图","纳入规划不等于法规已确认允许运营。"],
["s18",["for","operational","guideline"],"for new operational guidelines","a blueprint for operational guidelines","用于新操作准则","for限定蓝图用途，operational修饰guidelines。"],
["s19",["it","remain","to","be","see","how"],"It remains to be seen how weather conditions affect the air flows","it remains to be seen how ...","天气如何影响气流仍有待确定","It为形式主语，how从句为后置真正主语。"],
["s19",["make","formation","flight","more","efficient"],"make formation flight more efficient","make something + adjective","使编队飞行更高效","flight为宾语，more efficient为宾补；make主语为that所指气流。"],
["s20",["wake","decay","more","quickly"],"the planes' wakes will decay more quickly","wakes decay more quickly","飞机尾流会更快衰减","wakes为名词主语，more比较衰减速度。"],
["s21",["one","of","area"],"one of the areas his team will investigate further","one of the areas + relative clause","他的团队将进一步研究的领域之一","关系代词省略，areas是investigate的被研究对象。"],
["s21",["investigate","further"],"will investigate further","investigate further","将进一步研究","further在句尾修饰研究活动的推进程度。"],
["s22",["it","hard","for","airline","co-ordinate"],"It might also be hard for airlines to co-ordinate","it may be hard for somebody to do something","航空公司协调……也可能困难","for airlines为真正主语不定式的逻辑主语。"],
["s22",["way","that","allow","they","gain"],"a way that would allow them to gain from formation flight","allow somebody to do something","让航空公司能从编队飞行获益的方式","that指way，them指airlines，to gain补足allow宾语。"],
["s23",["easy","to","reschedule"],"easier to reschedule","be easier to do something","更容易被重新调度","主动不定式含被动关系，主语货机为被调度者。"],
["s23",["as","may","routine"],"as might routine military flights","as + auxiliary + subject","例行军用航班也可能如此","类比倒装，省去be easier to reschedule，保留might。"],
["s24",["as","it","happen"],"As it happens","as it happens","恰好；碰巧","固定评注从句，引入文中当时已发生的事情。"],
["s24",["be","on","case","already"],"are on the case already","be on the case","已经着手研究此事","当前研究动向不能替后文二战传闻提供确证。"],
["s25",["early","this","year"],"Earlier this year","earlier this year","当年较早时候","时间以文章叙述当时为基准。"],
["s25",["plan","pay","boeing","investigate"],"plans to pay Boeing to investigate formation flight","plans to pay somebody to do something","付费请波音研究编队飞行的计划","外层计划方为机构，内层研究执行者为波音。"],
["s25",["have","yet","begin","programme"],"the programme has yet to begin","have yet to do something","项目尚未开始","不是现在完成时has begun，也不是已经启动。"],
["s26",["low","on","fuel"],"low on fuel","be low on something","燃油不足","on引短缺的资源，不是低于物理位置。"],
["s26",["they","unsubstantiated"],"they are unsubstantiated","reports are unsubstantiated","这些报道未经证实","they在此回指reports，区别前一处指军机。"],
["s27",["skipper","of","lancaster","lose"],"the skipper of a Lancaster lost over Berlin","the skipper of an aircraft","在柏林上空损失的一架兰开斯特飞机的机长","lost修饰飞机，亲属身份后省was，不补机组命运。"],
["s28",["so","he","should","know"],"So he should know","should know from one's background","所以他按理应当了解","should为合理推断，非义务命令，也不改变报道未证实的判断。"],
["question-201041-prompt",["finding","promote","sale"],"Findings of the Stanford University researchers will promote the sales","findings will promote sales","研究发现将促进销售","这是题干声称的因果与未来结果，须接受原文检验。"],
["question-201042-prompt",["as","well","reduce","resistance"],"as well as reducing resistance","as well as doing something","也降低阻力","as well as后动名词补充另一项效果，原句形式保留。"],
["question-201042-prompt",["experience","upwash"],"The upwash experience","the upwash experience","对上洗气流的体验或利用","experience为名词主语中心，不是正文中接drag的动词。"],
["question-201043-prompt",["more","comfortable"],"more comfortable","more + adjective","更舒适的","单一比较级，题干明确作出肯定比较。"],
["question-201044-prompt",["role","that","play"],"The role that weather plays in formation flight","the role that something plays","天气在编队飞行中所起作用","that代替role作plays宾语，weather为主语。"],
["question-201044-prompt",["have","be","yet","define"],"has not yet been clearly defined","have not yet been done","尚未被清楚界定","完成时被动配not yet说明尚未完成。"],
["question-201045-prompt",["it","have","be","document","that"],"It has been documented that","it has been documented that ...","已有文献记录证实……","It为形式主语，that给出声称已被记录的内容。"],
["question-201045-prompt",["try","to","save"],"tried formation flight to save fuel","try something to do something","为了节油尝试编队飞行","to save作目的状语，题干明确声称动机。"],
];
export const passage2010P5PreferredContexts:Record<string,Record<string,SentenceWordContext>>={};
export const passage2010P5SourcePhraseGuides:Record<string,PhraseKnowledge>={};
export const passage2010P5SourcePhraseAliases:Record<string,string>={};
export const passage2010P5SourceCollocationGlosses:Record<string,{meaning:string;note:string}>={};
for(const[shortSource,heads,expression,canonical,meaning,rule]of rows){const source=shortSource.startsWith("s")?`2010-p5-${shortSource}`:shortSource;const key=`flight-source-${expression.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}`;passage2010P5SourcePhraseGuides[key]={key,canonical,type:"编队飞行语篇结构",meaning,summary:rule,grammarRole:rule,structures:[{pattern:canonical,meaning,rule,examples:[{english:expression,chinese:meaning}]}],pitfalls:[]};passage2010P5SourcePhraseAliases[expression.toLowerCase()]=key;passage2010P5SourceCollocationGlosses[expression.toLowerCase()]={meaning,note:rule};for(const head of heads){const entry=passage2010P5ReviewedContexts[source]?.[head]??passage2010P5Lexicon[head];(passage2010P5PreferredContexts[source]??={})[head]={...(entry?{partOfSpeech:entry.partOfSpeech,contextualMeaning:entry.contextualMeaning,use:entry.use}:{}),preferredCollocations:[expression]};}}
