import type { ErrorCategory, GrammarConceptId, PracticeTask } from "./learning-model";
const choice = (id: string, prompt: string, options: string[], answer: string, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, hintWords: string[] = [], extra: Partial<PracticeTask> = {}): PracticeTask => ({id, revision:1, kind:"choice", prompt, options, answer, evidence, feedback, conceptId, errorType, hintWords, mapRevealsAnswer:false, ...extra});
const range = (id: string, prompt: string, answer: string, feedback: string, conceptId: GrammarConceptId, hintWords: string[] = [], extra: Partial<PracticeTask> = {}): PracticeTask => ({id, revision:1, kind:"range", prompt, options:[], answer, evidence:answer, feedback, conceptId, errorType:"clause-boundary", hintWords, mapRevealsAnswer:false, ...extra});
const link = (id: string, prompt: string, links: Array<[string,string]>, evidence: string, feedback: string, conceptId: GrammarConceptId, hintWords: string[] = [], extra: Partial<PracticeTask> = {}): PracticeTask => ({id, revision:1, kind:"link", prompt, links:links.map(([source,target])=>({source,target})), options:[...new Set(links.map(([,target])=>target))], answer:JSON.stringify(links.map(([,target])=>target)), evidence, feedback, conceptId, errorType:"attachment", hintWords, mapRevealsAnswer:false,...extra});
export const passage2010P3Practice: Record<number, PracticeTask[]> = {
  1:[link("art-layers", "把手法、行为解释和人群范围分别接回去。", [["of creating automatic behaviors","说明art的内容"],["habits","解释automatic behaviors"],["among consumers","限定creating涉及的人群"]], "the art of creating automatic behaviors – habits – among consumers", "art是手法，of给出手法内容；habits是插入同位解释；among限定培养行为发生在哪类人中。", "apposition", ["art","creating","habits","among"])],
  2:[link("help-actions", "判断help结构里谁做哪件事。", [["These habits","帮助企业"],["companies","赚取收入"],["customers","吃零食或擦台面"]], "These habits have helped companies earn billions of dollars when customers eat snacks or wipe counters", "help companies earn包含宾语和省to的不定式宾补。when之后换成消费者的主语，不能让habits去赚钱。", "object-complement", ["helped","earn"]), range("customer-clause", "选出when引出的完整消费场景从句，包括逗号后解释动作触发缘由的补充。", "when customers eat snacks or wipe counters almost without thinking, often in response to a carefully designed set of daily cues", "when之内由customers共用eat与wipe；almost without thinking和often in response to均补充消费者动作，逗号并未终止从句。", "clause-time", ["when","thinking"])],
  3:[range("problem-relative", "选出that引出的完整定语从句；内部的原因说明也要保留。", "that remain killers only because we can't figure out how to change people's habits", "that回指problems，后面的because说明这些问题仍致命的原因，不能到killers就结束关系从句。", "clause-relative", ["that","remain","because"], {leaksToTaskIds:["nested-subjects"]}), link("nested-subjects", "把存在句、关系从句和原因从句里的角色接准确。", [["fundamental public health problems","存在句中的实义主语"],["that","remain的主语，回指problems"],["we","can't figure out的主语"],["how to change people's habits","figure out的疑问不定式宾语"]], "that remain killers only because we can't figure out how to change people's habits", "that越过插入例子指问题；how to change没有独立时态，属于疑问不定式，不新增一个有限定谓语的从句。", "clause-relative", ["that","we","how"], {leaksToTaskIds:["problem-relative"]})],
  4:[range("learning-content", "选出learn后面的完整学习内容，包括限定behaviors的从句。", "how to create new behaviors that happen automatically", "学习的是如何培养新行为；that从句限定这些行为能自动发生，必须保留在how to create的宾语内部。", "nonfinite-infinitive", ["learn","how","behaviors"]), choice("industry-role", "from private industry说明什么？", ["向企业界学习的方法来源","把公共卫生认作私人问题","新行为只在工厂发生"], "向企业界学习的方法来源", "learn from private industry", "from连到learn，说明向谁学习。private industry是私营企业界，不能据此把public health改为私人问题。", "modifier-prepositional", "attachment", ["from","private","industry"], {mapRevealsAnswer:true})],
  5:[link("two-relative-objects", "两处that分别回指什么，并补哪个位置？", [["that Dr. Curtis turned to","companies；to的宾语"],["that corporations could use to introduce new routines","cues；use的宾语"]], "that Dr. Curtis turned to", "第一处已有主语Curtis，第二处已有主语corporations；两个that都作宾语，但前者是介词to的对象，后者是use的直接宾语。", "clause-relative", ["that","turned","use"]), range("finding-scope", "选出完整finding短语，保留提示的生活范围和能被利用的说明。", "finding the subtle cues in consumers' lives that corporations could use to introduce new routines", "finding的宾语中心是cues，in consumers' lives及that从句都属于提示的信息；to introduce又在关系从句内说明利用目的。", "nonfinite-participle", ["finding","cues","introduce"], {leaksToTaskIds:["two-relative-objects"]})],
  6:[range("daily-relative", "只选出修饰products的省略关系词从句。", "we use every day", "we作主语，use缺宾语，由products补足；every day是use的时间状语。清单与主句find都不属于这个小从句。", "clause-relative", ["use","every"]), choice("products-predicate", "跳过破折号内的清单，that从句的核心判断是什么？", ["many of the products are results of manufactured habits","vitamins manufacture products","products find daily habits"], "many of the products are results of manufactured habits", "are results of manufactured habits", "many of the products是复数主语，are是系动词，results是表语；清单列举产品，不改变核心主谓。", "basic-svc", "predicate", ["are","results","manufactured"], {mapRevealsAnswer:true})],
  7:[choice("few-frequency", "这句在否定什么？", ["当时规律地每天刷牙多次的人很少","当时没有任何人刷牙","当时人们刷牙过于频繁"], "当时规律地每天刷牙多次的人很少", "few people regularly brushed their teeth multiple times a day", "few people是很少有人，不能扩成无人。regularly与multiple times a day共同限定所比较的刷牙习惯。", "negation-contrast", "translation", ["few","regularly","multiple"], {mapRevealsAnswer:true})],
  8:[link("give-objects", "把give结构中的对象与补充信息分开。", [["their pearly whites","接受清洁的牙齿，间接宾语"],["a cavity-preventing scrub","一次防蛀清洁，直接宾语"],["twice a day","清洁频率"],["with Colgate, Crest or one of the other brands","清洁所用的品牌产品"]], "give their pearly whites a cavity-preventing scrub twice a day, often with Colgate, Crest or one of the other brands", "give A B在这里相当于给A做B；牙齿不是被送走的物品，scrub是清洁动作。", "basic-svo", ["give","whites","scrub","with"]), choice("two-causes", "原文把如今的刷牙习惯归因于哪些因素？", ["广告和公共卫生宣传共同作用","只有商业广告，卫生宣传不起作用","纯粹由百年前的科学实验决定"], "广告和公共卫生宣传共同作用", "because of shrewd advertising and public health campaigns", "because of接两项并列名词，两个因素都应保留；本文讨论商业影响不等于可删掉卫生宣传。", "paragraph-role", "passage-logic", ["because","campaigns"], {mapRevealsAnswer:true})],
  9:[choice("outside-meal", "didn't drink water的范围受到什么限制？", ["用餐以外的时间","全天包括所有用餐时间","餐厅以外的物理空间"], "用餐以外的时间", "didn't drink water outside of a meal", "outside of a meal按活动时段理解。很多人当时只在就餐时喝水，不是完全不饮水。", "negation-contrast", "translation", ["outside","meal"])],
  10:[link("two-bottle-forms", "将装瓶动作、水的状态与喝水动作分开。", [["bottling","start后表示开始进行的装瓶动作"],["bottled","修饰water的过去分词"],["unthinkingly","修饰sip的方式"],["all day long","修饰sip的持续时间"]], "started bottling the production of far-off springs, and now office workers unthinkingly sip bottled water all day long", "started接bottling短语，后半句真正谓语为sip。bottled只说明水已装瓶；方式和时长围绕喝水动作。", "nonfinite-participle", ["bottling","bottled","unthinkingly","long"]), {id:"company-consumer-order",revision:1,kind:"order",prompt:"按原句两分句的结构，重建企业行动与如今消费者行为；不加入原因词。",options:["beverage companies","started bottling","the production of far-off springs","and now","office workers","sip bottled water"],answer:JSON.stringify(["beverage companies","started bottling","the production of far-off springs","and now","office workers","sip bottled water"]),evidence:"Then beverage companies started bottling the production of far-off springs, and now office workers unthinkingly sip bottled water all day long",feedback:"and连接两套主谓。Then与now提供时间推进，原文没有把每位职员的行为都证明成唯一原因作用。",conceptId:"basic-svo",errorType:"subject",hintWords:["started","workers","sip"],mapRevealsAnswer:true}],
  11:[range("old-buyers", "选出回顾旧购买群体的整个非谓语修饰语。", "once bought primarily by adolescent boys", "once bought修饰gum，by引购买者，primarily保留‘主要’限制。真正带限定时态的谓语在后面的is featured。", "nonfinite-participle", ["once","bought","primarily"], {leaksToTaskIds:["gum-time-links"]}), link("gum-time-links", "把时间表达接到它限定的动作。", [["once","bought：曾经的购买"],["now","is featured：如今的广告呈现"],["after a meal","use：产品使用时间"]], "once bought primarily by adolescent boys, is now featured", "旧购买者、当下宣传和建议使用时段分属三层；饭后修饰use，不是说男孩都在饭后购买。", "time-reference", ["once","now","after","use"], {mapRevealsAnswer:true})],
  12:[link("routine-activities", "between两边是什么，slipped in说明什么？", [["hair brushing","第一项日常活动：梳头"],["putting on makeup","第二项日常活动：化妆"],["slipped in","润肤品使用被插入这两项活动之间"]], "slipped in between hair brushing and putting on makeup", "两端都是名词性活动；putting不是主句进行时。slipped为过去分词，补充产品使用被嵌入程序的状态。", "nonfinite-participle", ["slipped","between","brushing","putting"], {mapRevealsAnswer:true})],
  13:[link("people-company-links", "把三个从句各自的主语接准确。", [["they become part of daily or weekly patterns","they指Our products"],["who recently retired from Procter & Gamble","who指consumer psychologist，即Berning"],["that sold $76 billion of Tide, Crest and other products last year","that指company，即Procter & Gamble"]], "Our products succeed when they become part of daily or weekly patterns", "产品融入惯例，心理学家退休，公司销售产品；不能把公司销售额安到心理学家个人头上。", "clause-relative", ["they","who","that"], {leaksToTaskIds:["time-ownership"]}), choice("time-ownership", "recently和last year分别限定哪件事？", ["recently限定退休，last year限定公司销售","recently限定销售，last year限定产品成功","两者都限定心理学家个人收入"], "recently限定退休，last year限定公司销售", "who recently retired from Procter & Gamble, the company that sold $76 billion of Tide, Crest and other products last year", "时间词跟各自从句的谓语，last year以文章叙述时点为参照；原文没有给出读者当下的年份。", "time-reference", "attachment", ["recently","retired","last","sold"], {leaksToTaskIds:["people-company-links"]})],
  14:[range("essential-complement", "选出essential后面的完整介词补足语，包括making的宾语和宾补。", "to making new products commercially viable", "essential to中的to是介词。making接new products作宾语，commercially viable说明产品达到的状态。", "object-complement", ["essential","making","viable"], {leaksToTaskIds:["make-internal"]}), link("make-internal", "把代词和make内部的关系接准确。", [["it","回指Creating positive habits这件事"],["new products","making的宾语"],["viable","补充new products达到的状态"],["commercially","修饰viable：商业上"]], "it's essential to making new products commercially viable", "it不指产品；making是使某物处于某状态，commercially是副词修饰形容词viable。", "object-complement", ["it's","making","commercially","viable"])],
  15:[link("two-throughs", "两个through短语各服务于哪件事？", [["Through experiments and observation","修饰have learned，研究认识的依据"],["through ruthless advertising","修饰tying，绑定行为和提示的手段"],["to habitual cues","tying的关联对象，不是不定式"]], "Through experiments and observation, social scientists like Dr. Berning have learned that there is power in tying certain behaviors to habitual cues through ruthless advertising", "实验使科学家理解机制，广告用来塑造消费者习惯。把两层through混淆，就会把34题的原因错选为scientific experiments。", "modifier-prepositional", ["through","learned","tying","to"], {mapRevealsAnswer:true}), choice("ruthless-voice", "这里ruthless透露了谁的评价？", ["叙述者对广告手段的不利评价","企业受访者原话说广告完全有益","消费者普遍赞美所有产品"], "叙述者对广告手段的不利评价", "through ruthless advertising", "本句已结束前段引语，ruthless是叙述层的负面用词；应结合末句问题商品和争议，不把企业的自我肯定当作者态度。", "author-voice", "passage-logic", ["ruthless"], {mapRevealsAnswer:true})],
  16:[range("controversy-condition", "选出限制争议发生情形的完整when从句。", "when the tactics have been used to sell questionable beauty creams or unhealthy foods", "when把争议限定到策略被用于销售问题商品的情形；to sell在从句内部说明策略使用目的，两个商品都要保留。", "clause-time", ["when","used","sell"], {leaksToTaskIds:["used-structure"]}), choice("used-structure", "have been used to sell中的used to是什么结构？", ["完成时被动加目的不定式：已被用来销售","过去习惯：过去经常出售","习惯于销售：be used to加名词"], "完成时被动加目的不定式：已被用来销售", "have been used to sell", "have been used是完整的完成时被动，to sell为目的。不可以忽略have been，套用used to do过去常常。", "passive-voice", "predicate", ["have","been","used","sell"])],
};
