import type { SentenceWordContext } from "./contextual-vocabulary";

type PassageLexiconEntry = {
  partOfSpeech: string;
  contextualMeaning: string;
  use: string;
  specialForms: string[];
  examSynonyms: string[];
  collocations?: string[];
  otherMeanings?: string[];
  wordFamily?: string[];
  confusions?: string[];
};

const word = (partOfSpeech: string, contextualMeaning: string, use: string, forms: string, synonyms: string[], extra: Partial<PassageLexiconEntry> = {}): PassageLexiconEntry => ({
  partOfSpeech, contextualMeaning, use, specialForms: [forms], examSynonyms: synonyms, ...extra,
});

export const passage2010P2LemmaAliases: Record<string, string> = {
  addressing: "address", invited: "invite", offering: "offer", anecdotes: "anecdote", husbands: "husband",
  nodded: "nod", gestured: "gesture", "she's": "she", puzzled: "puzzle", explained: "explain", "we'd": "we",
  crystallizes: "crystallize", situations: "situation", wreaking: "wreak", observed: "observe", reports: "report",
  gave: "give", divorces: "divorce", millions: "million", failed: "fail", complaints: "complaint", focused: "focus",
  inequities: "inequity", having: "have", cleaning: "clean", cooking: "cook", arrangements: "arrangement",
  wives: "wife", partners: "partner", represents: "represent", sitting: "sit", sat: "sit", held: "hold",
  glares: "glare", wanting: "want", talking: "talk", trusting: "trust", supporting: "support", careers: "career",
  sharing: "share", judging: "judge", generating: "generate", exerting: "exert", causing: "cause",
  creating: "create", couples: "couple", deserves: "deserve", sociologists: "sociologist", stems: "stem",
  inequalities: "inequality", him: "he", ideas: "idea", laughing: "laugh",
  latest: "late",
};

export const passage2010P2FamilyAliases: Record<string, string> = {
  gathering: "gather", talkative: "talk", talker: "talk", conversational: "conversation", silence: "silent",
  silently: "silent", agreement: "agree", complaint: "complain", laughter: "laugh", sociologist: "sociology",
  motivation: "motivate", communication: "communicate", arrangement: "arrange", inequity: "equity",
  inequality: "equal", stereotypical: "stereotype", suburb: "suburb", suburban: "suburb", description: "describe",
};

export const passage2010P2Lexicon: Record<string, PassageLexiconEntry> = {
  address: word("v.", "向聚会者讲话", "address + 听众为及物结构；was addressing 表示当时正在讲话，不加 to。", "address—addresses—addressed—addressing", ["speak to（向……讲话，需要补介词 to）"], { collocations: ["was addressing a small gathering"], otherMeanings: ["n. 地址；演说", "v. 处理问题，如 address a problem"] }),
  gathering: word("n.", "聚会；聚集的人群", "a small gathering 是 addressing 的宾语；本句 gathering 是可数名词，不是正在聚集的动词。", "gathering—gatherings；名词保留原形 gathering", ["meeting（会议或会面，不一定具有社交聚会性质）"], { otherMeanings: ["gathering 也可作 gather 的现在分词，但本句是独立名词词位。"] }),
  suburban: word("adj.", "郊区的", "修饰 living room 所在地区；suburban Virginia 指弗吉尼亚州的郊区区域。", "形容词无单复数；suburb 为名词，不能并入本词原形次数", ["outside the city center（在市中心之外，范围较宽）"]),
  virginia: word("n.（专有名词）", "弗吉尼亚州", "美国州名，与 suburban 一起限定场景所在地；首字母大写。", "专有地名，无本句单复数变化", ["the state of Virginia（美国弗吉尼亚州的全称表达）"]),
  room: word("n.", "房间；客厅；满屋的人", "living room 是客厅；The room burst into laughter 用房间借代里面的人，两处义项逐句区分。", "room—rooms；不可数义‘空间’不加复数", ["space（空间，不可直接替换这里的满屋听众）"], { otherMeanings: ["不可数名词：余地、空间，如 room for improvement（改进空间）"] }),
  invite: word("v.", "邀请", "invite somebody to do something：邀请某人做某事；men 是宾语，也是 join 的逻辑主语。", "invite—invites—invited—inviting（去末尾 e 加 ing）", ["ask（请求或邀请，意义比 invite 宽）"], { collocations: ["had invited men to join them"] }),
  join: word("v.", "加入；和……一起参加", "join them 直接接宾语 them，不加 to；join a group 表加入群体，join in an activity 表参与活动。", "join—joins—joined—joining", ["take part（参加活动，后接对象通常需 in）"]),
  throughout: word("prep.", "在整个……期间", "throughout the evening 作时间状语，强调全过程；toward the end 只指接近末尾。", "介词，无屈折变化", ["during（在……期间，未必强调整个时段）"], { collocations: ["Throughout the evening"] }),
  evening: word("n.", "晚上；当晚的聚会时间", "the evening 指现场那个晚上；the whole evening 强调一整晚，every evening 才是每晚。", "evening—evenings", ["night（夜晚，范围往往比 evening 更晚）"]),
  talkative: word("adj.", "健谈的；爱说话的", "had been 后作表语，particularly 修饰程度；不等于总爱空谈或说谎。", "talkative—more talkative—most talkative；与 talk 仅作词族关联", ["fond of talking（喜欢说话，需用系表结构）"], { wordFamily: ["talk v. 交谈", "talker n. 爱说话的人"] }),
  frequently: word("adv.", "频繁地；经常", "修饰 offering 或 complain；谈的是动作发生频率，不是动作速度。", "frequently—more frequently—most frequently；不归并到形容词 frequent", ["often（经常，语气比 frequently 更日常）"]),
  offer: word("v.", "提出；提供", "offering ideas and anecdotes 表发表看法、提供趣闻；offering 的逻辑主语是 one man。", "offer—offers—offered—offering（不双写 r）", ["give（给出，语义更宽且搭配需核对）"], { collocations: ["offering ideas and anecdotes"] }),
  anecdote: word("n.", "趣闻；轶事", "ideas and anecdotes 为并列宾语；anecdote 是关于人物或经历的简短故事。", "anecdote—anecdotes", ["short story（短故事，未必来自真实经历）"]),
  silently: word("adv.", "默不作声地", "修饰 sat，表示妻子坐着时没有说话；不是说明所在环境绝对无声。", "副词无单复数；silently、silent、silence 分别保留原形", ["quietly（安静地，也可只指动作声音很小）"]),
  beside: word("prep.", "在……旁边", "beside him 指妻子挨着丈夫的位置；后接宾格 him，不用主格 he。", "介词，无屈折变化", ["next to（紧挨着，距离含义相近）"], { confusions: ["beside 是在旁边；besides 是除此之外，不能互换。"] }),
  couch: word("n.", "长沙发", "on the couch 作 sat 的地点状语；说坐在沙发上用 on。", "couch—couches（加 es）", ["sofa（沙发，常可近义使用）"]),
  toward: word("prep.", "朝着；接近", "Toward the end 表时间接近末尾；gestured toward 表手势的方向，两处不能机械同译。", "toward 与 towards 为常见变体；介词无时态变化", ["towards（主要是拼写变体，不表示另一种方向）"]),
  complain: word("v.", "抱怨", "complain that + 陈述句表示抱怨的内容；complain about + 名词表示抱怨的对象。", "complain—complains—complained—complaining", ["express dissatisfaction（表达不满，较正式的释义）"], { wordFamily: ["complaint n. 抱怨"] }),
  husband: word("n.", "丈夫", "his wife 与 her husband 对应；husbands 为复数，their husbands 指女性各自的丈夫。", "husband—husbands；husband's 为单数所有格，husbands' 为复数所有格", ["spouse（配偶，不限定为男性）"]),
  talk: word("v./n.", "交谈；谈话", "talk to somebody 表与某人交谈，more/less 修饰交谈的量；Divorce Talk 中 Talk 是书名中的名词。", "talk—talks—talked—talking；名词谈话可为 a talk，泛指交谈可不可数", ["speak（说话，常更重表达或正式发言；talk 更强调交流）"], { collocations: ["talk to them", "talk to me"], wordFamily: ["talkative adj. 健谈的", "talker n. 爱说话的人"] }),
  quickly: word("adv.", "迅速地；立刻", "quickly nodded 表迅速点头，强调反应快；与 frequently 的频率意义不同。", "quickly—more quickly—most quickly", ["rapidly（迅速地，常用于变化速度）"]),
  nod: word("v.", "点头", "nodded in agreement 表用点头表示赞同；nod 可不及物，也可说 nod one's head。", "nod—nods—nodded—nodding（双写 d）", ["move one's head up and down（点头的动作释义，不必然表示认同）"], { collocations: ["nodded in agreement"] }),
  agreement: word("n.", "赞同；意见一致", "in agreement 作态度状语；此处为不可数状态，不是双方签订的协议文本。", "状态义通常不可数；协议义可数 agreement—agreements", ["consent（同意，常指许可而非观点一致）"], { collocations: ["nodded in agreement"], otherMeanings: ["可数名词：协议、协定，如 reach an agreement（达成协议）"] }),
  gesture: word("v.", "做手势示意", "gestured toward his wife 指朝妻子做手势，不需要补成指责妻子。", "gesture—gestures—gestured—gesturing", ["signal（示意，未必通过手势）"], { collocations: ["gestured toward his wife"], otherMeanings: ["n. 手势；表示某种态度的举动"] }),
  talker: word("n.", "爱说话的人", "the talker 作表语，指家中比较爱说话的那一方；不能把名词直接统计为 talk 的动词变形。", "talker—talkers；派生名词保留原形 talker", ["person who talks a lot（话多的人，解释 talker 在本句中的含义）"]),
  family: word("n.", "家庭", "in our family 限定男子对话多者的判断范围；our 指夫妻共同的家庭。", "family—families（辅音字母加 y，变 y 为 ies）", ["household（同住的一户人，未必都具有亲属关系）"]),
  burst: word("v.", "突然爆发；突然开始", "burst into laughter 是不及物短语，into 引出突然进入的状态。", "burst—burst—burst；第三人称 bursts；现在分词 bursting", ["suddenly begin（突然开始，需相应调整后接结构）"], { collocations: ["burst into laughter"] }),
  laughter: word("n.", "笑声；发笑", "into laughter 与 burst 组成搭配；laughter 是不可数名词，不写 a laughter。", "不可数名词，通常不作复数；与 laugh 仅作词族关联", ["laughing（发笑这一行为；不是可随意互换的词形）"], { collocations: ["burst into laughter"] }),
  puzzle: word("v.", "使困惑；本句 puzzled 为感到困惑的", "looked puzzled 中过去分词形容词表示男子的感受；puzzling 才表示令人困惑。", "puzzle—puzzles—puzzled—puzzling（去 e 加 ing）", ["confuse（使困惑，常强调难以分辨）"], { collocations: ["looked puzzled and hurt"], otherMeanings: ["n. 谜题；令人费解的事"] }),
  hurt: word("adj./v.", "感情受伤的；委屈的", "looked puzzled and hurt 中与 puzzled 并列作表语；不是说男子身体受伤。", "hurt—hurt—hurt；hurt 作表语形容词时无时态变化", ["upset（难过或不安，不一定由感情受伤引起）"], { collocations: ["looked puzzled and hurt"] }),
  explain: word("v.", "解释", "he explained 的直接引语置于前面；explain something to somebody，不能说 explain somebody something。", "explain—explains—explained—explaining", ["make clear（说明清楚，需按宾语位置重组结构）"]),
  nothing: word("pron.", "没有什么；没有任何事情", "have nothing to say 中是 have 的宾语，不定式 to say 后置限定；nothing 已带否定含义。", "不定代词，无常规复数；作主语时谓语通常用单数", ["not anything（任何事情都没有，需要调整否定的位置）"], { collocations: ["nothing to say"] }),
  conversation: word("n.", "交谈；交流过程", "keep the conversation going 中作 keep 的宾语；failed conversation 中强调交流失败，不是某个句子语法错误。", "conversation—conversations；泛指交流时也可用不可数义", ["communication（沟通，范围包括书面及非语言交流）"], { collocations: ["keep the conversation going"], wordFamily: ["conversational adj. 交谈的"] }),
  silence: word("n.", "沉默", "in silence 表没有交谈的状态；spend the evening in silence 说明晚上如何度过。", "状态义通常不可数；a silence 可指一段沉默", ["quiet（安静，未必完全不说话）"], { collocations: ["in silence"] }),
  episode: word("n.", "插曲；一段经历", "This episode 回指聚会中男子发言、众人发笑和他继续解释这一连串事件。", "episode—episodes", ["incident（事件，通常范围较小且可能带突发意味）"], { otherMeanings: ["电视剧或广播剧的一集"] }),
  crystallize: word("v.", "使清晰；使具体化", "episode crystallizes the irony 用结晶作比喻，表示个案将抽象反差具体呈现。", "crystallize—crystallizes—crystallized—crystallizing；英式也拼 crystallise", ["make clear（使清晰，少了结晶成形的比喻色彩）"], { otherMeanings: ["使结晶；结晶形成"] }),
  irony: word("n.", "反差；具有反讽意味的情形", "the irony 后的 that 内容说明男子在外话多、在家话少的反差；并非作者在说反话。", "irony—ironies；泛指反讽性质时通常不可数", ["contrast（对比，不一定带有出乎意料的反差意味）"]),
  situation: word("n.", "场合；情境", "public situations 指有外人在场的社交环境，与 at home 对照。", "situation—situations", ["circumstance（情况或条件，常用复数 circumstances）"], { collocations: ["in public situations"] }),
  wreak: word("v.", "造成；引发破坏", "wreak havoc with/on something 是强负面固定搭配；不能按一般的 work 理解。", "wreak—wreaks—wreaked—wreaking", ["cause（造成，褒贬取决于后面的宾语）"], { collocations: ["wreaking havoc with marriage"], confusions: ["wreak 与 wreck（毁坏）拼写不同；本句是 wreak havoc。"] }),
  havoc: word("n.", "严重破坏；混乱", "wreaking 的宾语，不可数；第27题需要保留其强烈负面含义。", "不可数名词，通常不用 a 或复数 havocs", ["damage（损害，与本题语境相符）"], { collocations: ["wreaking havoc with marriage"] }),
  marriage: word("n.", "婚姻；婚姻关系", "with marriage 指谈话模式所伤害的对象；此处谈婚姻这一制度及关系，使用不可数义。", "具体婚姻可数 marriage—marriages；泛指婚姻时不可数", ["married life（婚后生活，侧重生活状态而非关系本身）"]),
  political: word("adj.", "政治的；政治学的", "political scientist 是政治学家，不是某党派的科学家。", "形容词无单复数；politically 是独立副词", ["relating to politics（与政治或政治学有关）"]),
  scientist: word("n.", "科学家；本句为政治学研究者", "与 political 组成职业名称，整体作 Andrew Hacker 的称谓。", "scientist—scientists", ["researcher（研究者，范围不限于科学或政治学）"]),
  andrew: word("n.（人名）", "安德鲁", "Andrew Hacker 中的名字，与后面的姓氏共同指同一位政治学家。", "人名首字母大写，本句无复数变化", ["personal given name（人的名字，不作语义近义替换）"]),
  hacker: word("n.（姓氏）", "哈克", "Andrew Hacker 的姓氏；本文不表示入侵计算机系统的人。", "姓氏首字母大写，本句无复数变化", ["family name（姓氏，只按人物指代辨认）"], { otherMeanings: ["普通名词 hacker 可指计算机黑客，但不属于本句义。"] }),
  sociologist: word("n.", "社会学家", "Catherine Kohler Riessman 前为职业称谓；第29题A项中 sociologists 泛指社会学家。", "sociologist—sociologists；不能并为 sociology 的词形次数", ["social researcher（社会研究者，比学科身份更宽）"]),
  catherine: word("n.（人名）", "凯瑟琳", "Catherine Kohler Riessman 的名字，是一位社会学家姓名的组成部分。", "人名首字母大写，无本句词形变化", ["personal given name（名字，不作一般词义替换）"]),
  kohler: word("n.（人名组成部分）", "科勒", "与 Catherine、Riessman 共同构成人名，不独立指另一位作者。", "人名组成部分，首字母大写", ["name component（完整姓名的一部分）"]),
  riessman: word("n.（姓氏）", "里斯曼", "Catherine Kohler Riessman 的姓氏，reports 的主语包含这个完整姓名。", "姓氏首字母大写，本句无屈折变化", ["family name（姓氏，不替换为普通名词）"]),
  virtual: word("adj.", "几乎可称为的；事实上的", "a virtual epidemic 指程度上几乎相当于流行病，强调普遍，不涉及虚拟现实技术。", "形容词无单复数；virtually 是独立副词", ["almost actual（几乎等同于实际的，说明其近乎成立的程度）"], { collocations: ["a virtual epidemic"], otherMeanings: ["计算机模拟的；虚拟的，如 virtual reality（虚拟现实）"] }),
  complaint: word("n.", "抱怨；不满意见", "complaints 为第15句主语；from women 标来源，about their husbands 标抱怨对象。", "complaint—complaints；派生名词不合并到 complain", ["expression of dissatisfaction（表达不满，解释行为性质）"], { wordFamily: ["complain v. 抱怨"] }),
  tangible: word("adj.", "具体可感的；明确可见的", "修饰 inequities，指事业牺牲、家务负担等能具体指出的不公，不是说能用手触摸不公。", "tangible—more tangible—most tangible", ["concrete（具体的，与抽象的相对）"]),
  inequity: word("n.", "不公；不公平待遇", "tangible inequities 指妻子在事业和日常分工上遭遇的具体不公；与 inequality 同源相关但不是同一个原形。", "inequity—inequities（y 变 ies）", ["inequality（不平等，常侧重差距；inequity 更强调不公正）"], { collocations: ["focused not on tangible inequities"] }),
  career: word("n.", "事业；职业发展", "the chance for a career 是发展自己事业的机会；to his 中省略的名词也是 career。", "career—careers", ["job（某一份具体工作，不等于长期职业发展）"], { collocations: ["given up the chance"] }),
  accompany: word("v.", "陪同；陪伴", "accompany a husband to his 指陪丈夫追求他的事业；accompany 直接接人物宾语，to 再引方向。", "accompany—accompanies—accompanied—accompanying", ["go with（与……同行，需要改写原句结构）"]),
  daily: word("adj.", "日常的；每天的", "daily life-support work 中限定事务发生在日常生活层面。", "形容词无单复数；daily 也可作副词表示每天", ["everyday（形容词，日常的；every day 两词为时间短语）"]),
  "life-support": word("adj.（复合修饰语）", "维持日常生活的", "修饰 work，例子是打扫、做饭和社交安排，不是医院的生命维持设备。", "复合修饰语不加复数，保留原卷连字符", ["supporting everyday life（维持日常生活，释义需重组句法）"], { collocations: ["daily life-support work"] }),
  clean: word("v.", "打扫；清洁", "cleaning 为名词性 -ing 形式，和 cooking、social arrangements 并列作 like 后的例子。", "clean—cleans—cleaned—cleaning", ["make clean（使干净，较为解释性的表达）"], { otherMeanings: ["adj. 干净的；清白的"] }),
  cook: word("v.", "做饭；烹饪", "cooking 在本句为名词性 -ing 形式，举例说明日常生活事务。", "cook—cooks—cooked—cooking", ["prepare food（准备食物，范围还包括不需烹煮的步骤）"], { otherMeanings: ["n. 厨师；做饭的人"] }),
  arrangement: word("n.", "安排", "social arrangements 指对社交活动所作的组织安排，与清洁、做饭并列。", "arrangement—arrangements；名词不归并到 arrange", ["plan（计划，未必已经落实具体安排）"]),
  listen: word("v.", "倾听；听", "listen to me 表主动听我说话；listen 为不及物动词，不能省掉 to 直接接人物。", "listen—listens—listened—listening", ["hear（听见，强调感知结果，不等于主动倾听）"], { collocations: ["listen to me"] }),
  wife: word("n.", "妻子", "his wife 指这位男士的妻子；most wives 指研究中的多数妻子；wives' 是复数所有格。", "wife—wives（f 变 v）；wife's 单数所有格，wives' 复数所有格", ["spouse（配偶，不限定性别）"]),
  foremost: word("adv.", "首先；最重要地", "first and foremost 为整体强调优先顺序，插在 to be 与表语之间。", "固定表达中的副词，无时态或复数变化", ["above all（最重要的是，强调优先性）"], { collocations: ["first and foremost"] }),
  conversational: word("adj.", "交谈的；适于交谈的", "conversational partners 是能相互交谈的伙伴，不是商业合伙人。", "形容词无单复数；不并入名词 conversation 的原形统计", ["for conversation（用于交流的，需要调整修饰语位置）"], { collocations: ["conversational partners"], wordFamily: ["conversation n. 交谈"] }),
  partner: word("n.", "伙伴", "conversational partners 是丈夫在妻子期待中应承担的角色；这里不是另找恋人。", "partner—partners", ["companion（同伴，侧重相伴而非共同参与某活动）"], { collocations: ["conversational partners"], otherMeanings: ["合伙人；伴侣；搭档"] }),
  image: word("n.", "形象；画面", "the image 是最后一句的主语，后面的 that 从句限定其代表当前危机。", "image—images", ["picture（图画或画面，通常较具体）"]),
  represent: word("v.", "表现；代表", "that best represents... 中 that 指 image，best 修饰代表得最贴切的程度。", "represent—represents—represented—representing", ["show（展示，比 represent 的代表性含义更宽）"]),
  stereotypical: word("adj.", "老套的；刻板印象式的", "修饰 cartoon scene，强调常见到几乎成为固定印象的夫妻画面，不表示所有夫妻真实如此。", "形容词无单复数；比较级可用 more stereotypical", ["conventional（惯常的，未必带刻板或老套的意味）"]),
  cartoon: word("n.", "漫画", "cartoon scene 为漫画中的场景；这里不是动画片制作或儿童节目。", "cartoon—cartoons", ["comic drawing（漫画画作，侧重图画形式）"]),
  scene: word("n.", "场景；画面", "作 is 后的表语中心词，of a man... 说明画面内容。", "scene—scenes", ["situation（情境，不一定强调视觉画面）"]),
  sit: word("v.", "坐", "sat 为过去式；sitting 修饰 man，指坐在早餐桌旁的男人，非主句谓语。", "sit—sat—sat；sits；sitting（双写 t）", ["be seated（坐着，使用被动形式表示状态）"], { collocations: ["at the breakfast table"] }),
  breakfast: word("n.", "早餐", "breakfast table 中名词前置修饰 table，表示吃早餐用的桌子。", "泛指早餐通常不可数；某次早餐可用 a breakfast", ["morning meal（早晨的一餐，解释早餐含义）"]),
  table: word("n.", "桌子", "at the breakfast table 表坐在桌旁，不能误译为坐在桌面上。", "table—tables", ["desk（书桌，典型用途是学习或办公）"], { collocations: ["at the breakfast table"], otherMeanings: ["数据表格"] }),
  hold: word("v.", "举着；保持", "held up 是 hold up 的过去分词，被动描述报纸举在脸前的状态。", "hold—held—held；holds；holding", ["keep（保持，能否替换取决于宾补结构）"], { collocations: ["with a newspaper held up in front of his face"] }),
  front: word("n.", "前面；前方", "in front of 是复合介词结构，说明报纸位于脸的前方。", "front—fronts；固定短语 in front of 中不用复数", ["ahead of（在前方，也常用于时间或进度领先）"], { collocations: ["in front of his face"] }),
  glare: word("v.", "怒视；瞪着", "glare at somebody/something，at 引出目光对象；体现想交流却受阻的不满。", "glare—glares—glared—glaring", ["look（看，中性词会丢失不满或愤怒的语气）"], { collocations: ["glares at the back of it"], otherMeanings: ["n. 刺眼的强光；怒视"] }),
  main: word("adj.", "主要的；最重要的", "第26题修饰 expectation，对应原文 first and foremost，而非所有可能期待。", "形容词，通常不用比较级或最高级", ["chief（主要的，强调首要地位）"]),
  housework: word("n.", "家务", "Sharing housework 指分担家务，是第26题干扰项；原文把它排除为主要关注点。", "不可数名词，不写 a housework 或 houseworks", ["domestic work（家庭日常劳动）"]),
  context: word("n.", "上下文；语境", "Judging from the context 要求根据前后信息推断词组含义，而不是脱离婚姻危机语境。", "context—contexts", ["surrounding text（前后文，限定为语言上下文）"]),
  motivation: word("n.", "动力；动机", "generating motivation 指产生动力，与 havoc 的负面破坏方向不一致。", "泛指动力时不可数；motivation—motivations 可指多种动机", ["incentive（激励因素，常指外部诱因）"]),
  exert: word("v.", "施加；运用", "exert influence 表施加影响；exert 是及物动词，直接接 influence。", "exert—exerts—exerted—exerting", ["apply（施加或运用，但搭配对象不同）"]),
  damage: word("n./v.", "损害；破坏", "causing damage 中为不可数名词，能保留 wreaking havoc 的负面意义。", "损害义不可数；动词 damage—damaged—damaging；damages 可另指赔偿金", ["harm（伤害，范围包括身体或利益受损）"]),
  pressure: word("n.", "压力", "creating pressure 表制造压力，不能完全表达 havoc 已造成严重破坏的语义强度。", "泛指压力时不可数；多种压力可用 pressures", ["stress（压力或紧张，常侧重个人承受状态）"]),
  couple: word("n.", "夫妻；一对伴侣", "between couples 在本题语境谈夫妻间的交流，不是两对家庭之间的往来。", "couple—couples；a couple of 还可表示两个或几个", ["married pair（已婚的一对，范围比 couple 更明确）"]),
  spouse: word("n.", "配偶", "her spouse 在第28题D项中指她的丈夫；spouse 本身是性别中性的正式用语。", "spouse—spouses", ["husband（丈夫，限定为男性）", "wife（妻子，限定为女性）"]),
  summarize: word("v.", "概括；总结", "can best summarize 中用动词原形；宾语 the main idea 指全文主旨。", "summarize—summarizes—summarized—summarizing；英式也拼 summarise", ["sum up（概括，短语动词形式）"]),
  decay: word("n.", "衰退；败坏", "moral decay 指道德衰败，是第29题无原文依据的选项，不可当成作者立场。", "抽象过程义通常不可数；动词 decay—decayed—decaying", ["decline（衰退，不一定涉及道德或腐坏）"]),
  deserve: word("v.", "值得；应得到", "deserves more research 直接接名词宾语，表示值得更多研究；deserve to do 才接不定式。", "deserve—deserves—deserved—deserving", ["be worthy of（值得，后接名词或动名词）"]),
  "break-up": word("n.", "破裂；解体", "Marriage break-up 是名词短语主语；保留原卷连字符，区别动词 break up。", "break-up—break-ups；名词与动词短语 break up 分开", ["divorce（离婚，通常强调婚姻正式终止）"]),
  stem: word("v.", "源于；由……引起", "stem from 接原因；选项把婚姻破裂归因于性别不平等，原文不支持此主旨。", "stem—stems—stemmed—stemming（双写 m）", ["result from（由……导致，注意 from 引原因）"], { otherMeanings: ["n. 植物的茎；词干", "v. 阻止或遏制某事发展"] }),
  inequality: word("n.", "不平等", "sex inequalities 指性别不平等；与 inequity 相近但前者侧重差距，后者强调不公正。", "inequality—inequalities；不归并到 equal 或 inequity", ["inequity（不公，带更明确的公正性评价）"]),
  immediately: word("adv.", "紧接着；立即", "immediately after this text 限定所推测的是紧接末段的部分，而非全文任意远处。", "副词，无单复数；不合并到形容词 immediate", ["directly after（紧随其后，用于先后关系）"]),
  vivid: word("adj.", "生动的；鲜明的", "a vivid account 指生动叙述；该项谈的是新书而非末段新引入的漫画。", "vivid—more vivid—most vivid", ["lively（生动活泼的，不总强调鲜明如见的形象感）"]),
  account: word("n.", "叙述；说明", "an account of something：对某事的叙述；第30题不是账户或账目。", "account—accounts", ["description（描述，侧重具体特征；account 可包括事件经过）"], { otherMeanings: ["银行账户；账目", "account for：解释；占某比例"] }),
  detailed: word("adj.", "详细的", "a detailed description 指对漫画进一步展开的描写；只表示推断的可能方向。", "detailed—more detailed—most detailed；本句为形容词，不计作 detail 的动词时态", ["full（充分完整的，未必像 detailed 一样强调细节）"]),
};

Object.assign(passage2010P2Lexicon, {
  he: word("pron.", "他", "he 是主格，him 是宾格；正文主要指聚会中健谈的男士，妻子抱怨中的 He 指各自丈夫。", "he—him—his—himself；him 归入 he", ["the man（这名男子，须有明确先行对象）"]),
  she: word("pron.", "她", "指妻子；she's 为 she is，后面接名词表语；第13句 she 回指女性社会学家。", "she—her—hers—herself；she's = she is", ["the woman（这名女子，要根据先行词确定身份）"]),
  her: word("possessive determiner / pron.", "她的；她", "her new book 和 her spouse 中为所有格限定词，后接名词；不是这两处动词的宾语。", "主格 she；宾格及所有格限定词 her；名词性所有格 hers", ["belonging to her（属于她的，需调整修饰语结构）"]),
  we: word("pron.", "我们", "we'd spend 中指说话的丈夫与妻子两人；'d 后接原形 spend，展开为 would 而非 had。", "we—us—our—ours；we'd = we would 或 we had，按后接形式区分", ["the two of us（我们两人，仅适用于此处夫妻语境）"]),
  i: word("pron.", "我", "叙述层的 I 是作者；直接引语中的 I 是正在解释的男子，不能把二者视为同一人。", "I—me—my—mine；I 始终大写", ["the speaker（说话者，改用第三人称时需重组句子）"]),
  me: word("pron.", "我（宾格）", "listen to me / talk to me 中指提出抱怨的妻子，作介词 to 的宾语。", "I 的宾格 me；与 my 所有格区分", ["the speaker（这里是表达抱怨的妻子）"]),
  my: word("possessive determiner", "我的", "In my own research 中指作者自己的研究；own 加强所属关系。", "my 后接名词；mine 可独立使用；主格 I", ["belonging to me（属于我的，不能直接代替名词前的限定词）"]),
  our: word("possessive determiner", "我们的", "in our family 中指男子和妻子的家庭；属于引语中的第一人称，不指现场全部听众。", "our 后接名词；ours 独立使用；主格 we", ["belonging to us（属于我们的，需重组结构）"]),
  his: word("possessive determiner / pron.", "他的；他的事业", "his wife / his face 中限定名词；to his 中独立代指 his career。", "he—him—his；his 既可限定名词，也可独立作物主代词", ["belonging to him（属于他的；具体省略内容由前文确定）"]),
  their: word("possessive determiner", "他们的；她们的", "their husbands 指妻子们的丈夫；their wives 指丈夫们的妻子；their share 指妻子们应承担的份额。", "主格 they；宾格 them；their 后接名词，theirs 可独立使用", ["belonging to them（属于他们或她们的）"]),
  they: word("pron.", "他们；她们；那些抱怨", "主格 they 和宾格 them 的指代随句子改变；第16句 they 承接 complaints。", "they—them—their—theirs—themselves", ["the people or things mentioned（前面提过的人或事物）"]),
  it: word("pron.", "它；这一说法", "It's true 中回指男子刚说的情况；末句 the back of it 中回指 newspaper，均须按句解析。", "it—its—itself；it's = it is，不是所有格 its", ["the thing just mentioned（刚提到的事物或命题）"]),
  that: word("pron. / conjunction", "那；引导具体内容或限定关系", "第1、19句作定语从句主语；第3、13、18句引出宾语内容；第10句引出 irony 的内容；第14句作指示代词主语。", "指示代词单数 that、复数 those；连接词及关系代词无时态变化", ["the fact that（引出事实内容，但不能替换关系代词或指示代词用法）"]),
  while: word("conj.", "而；与此同时", "连接男子和妻子的不同表现，主要突出对照；不是所有出现的 while 都表示‘一段时间’。", "连词无词形变化；名词 while 才有 for a while 用法", ["whereas（而，专门突出对比，时间意味更弱）"]),
  as: word("prep. / conjunction / relative pronoun", "作为；正如", "give lack of communication as the reason 中为作为；as Hacker observed 中为评注性关系词；such as 是举例结构。", "结构词无屈折变化，不可统一解释成‘因为’", ["in the role of（作为，只说明介词义）"]),
  give: word("v.", "给出；列作；放弃搭配的动词", "gave A as B 表将A列为B；given up 是 give up 的完成形式。句首 Given 则需按介词义读取。", "give—gave—given；gives；giving", ["offer（给出或提出，须根据 as、up 等搭配判断）"], { collocations: ["given up the chance"] }),
  be: word("v.（系动词或助动词）", "是；构成时态或被动", "had been talkative 为系表；was addressing 为进行时；was observed 为被动，按后面词形辨别。", "be—am/is/are—was/were—been—being", ["linking verb（系动词用途，不存在可机械替换的单一近义词）"]),
  have: word("aux./v.", "已经；有", "had invited / had been 为完成时助动词；have nothing 为实义动词‘有’，having given up 为完成式非谓语。", "have—has—had—having", ["possess（拥有，只近于实义动词，不能替换完成时助动词）"]),
  do: word("aux./v.", "构成否定；做", "don't、doesn't、didn't 中 do 为否定助动词；doing far more... 中为实义动词‘做’。", "do—does—did—done—doing；助动词后实义动词用原形", ["perform（做或执行，只适用于实义动词用法）"]),
  live: word("adj.（living room 中的修饰成分）", "起居；生活", "living room 整体为客厅；living 不表示这间房间‘活着’，统计沿用既有 live 原形键。", "live—lives—lived—living；living room 为固定名词组合", ["sitting room（客厅，整体表达近义）"]),
  work: word("n.", "工作；日常生活事务", "from work 指下班的来源，life-support work 指家务和生活事务；不是上一篇艺术品义。", "劳动或事务义通常不可数；艺术作品义才常用 works", ["labor（劳动，常更强调付出的体力或努力）"], { collocations: ["come home from work", "daily life-support work"] }),
  look: word("linking v.", "显得；看起来", "looked puzzled and hurt 后接形容词作表语；不是把 puzzled 当被看的对象。", "look—looks—looked—looking", ["seem（似乎，未必来自外表观察）"], { collocations: ["looked puzzled and hurt"] }),
  pattern: word("n.", "行为模式", "this pattern / The pattern 回指男子在公共场合多话、在家少话的交谈模式。", "pattern—patterns", ["regular way of behaving（重复出现的行为方式）"]),
  observe: word("v.", "观察到；注意到", "was observed 表某模式被发现；as Hacker observed 回指同一研究发现，不是遵守规则义。", "observe—observes—observed—observing", ["notice（注意到，未必经过系统观察）"]),
  report: word("v.", "报告；指出研究发现", "reports that... 接完整研究内容；in her new book 表报告的载体。", "report—reports—reported—reporting", ["state（陈述，未必基于研究或调查）"]),
  interview: word("v.", "访谈", "women she interviewed 中被访谈者是 women，she 为社会学家；不取求职面试义。", "interview—interviews—interviewed—interviewing", ["question（询问，未必是系统访谈）"]),
  lack: word("n.", "缺乏；不足", "lack of communication 作 gave 的宾语；此处是名词，of 引出缺少的对象。", "名词缺乏状态通常不可数；动词 lack—lacked—lacking", ["absence（缺失，可能比 lack 更接近完全没有）"], { collocations: ["lack of communication"] }),
  communication: word("n.", "沟通；交流", "lack of communication 和 focused on communication 均指夫妻互动，不是通信设备或单向传播。", "泛指沟通不可数；communications 可另指通信系统或多次信息传递", ["conversation（交谈，较偏口头互动）"], { collocations: ["lack of communication", "focused on communication"] }),
  reason: word("n.", "原因；理由", "the reason for their divorces 中 for 引出要解释的事件；描述受访者归因，不自动构成总体因果比例。", "reason—reasons", ["cause（原因，更直接强调造成结果的因素）"], { collocations: ["the reason for their divorces"] }),
  divorce: word("n.", "离婚", "their divorces 指具体离婚事件；divorce rate 中名词修饰 rate；Divorce Talk 是书名。", "divorce—divorces；动词 divorce—divorced—divorcing", ["marriage break-up（婚姻破裂，未必已完成法律手续）"]),
  current: word("adj.", "当时的；当前的", "current divorce rate / current crisis 指文章写作语境中的状况，不是对2026年统计的陈述。", "形容词无单复数；currently 是独立副词", ["present（目前的，时间参照仍由文章决定）"]),
  rate: word("n.", "比率", "divorce rate 是离婚率，不能换成‘离婚原因占比’；第28题考查统计对象不能偷换。", "rate—rates", ["proportion（比例，需要说明各自的分母和统计对象）"]),
  amount: word("v.", "总计；相当于", "amounts to + 数量，为不及物动词搭配；that 作主语所以用 amounts。", "amount—amounts—amounted—amounting；作名词时指数量", ["add up to（合计为，强调累加结果）"], { collocations: ["amounts to millions of cases"] }),
  million: word("numeral / n.", "百万", "millions of 表数百万的概数；具体数词后用 million 单数，如 two million。", "two million；millions of（有 of 时可用复数表示概数）", ["a thousand thousand（百万的数量释义）"]),
  case: word("n.", "案例；个案", "millions of cases 指所讨论的离婚或沟通失败相关个案，不是传染病病例的医学用法。", "case—cases", ["instance（实例，通常不强调被研究或处理的个案）"]),
  epidemic: word("n.", "流行病般普遍的现象", "a virtual epidemic of failed conversation 是比喻，形容沟通失败广泛发生。", "epidemic—epidemics；本句为可数名词", ["widespread problem（广泛存在的问题，去掉了疾病比喻）"], { collocations: ["a virtual epidemic"] }),
  fail: word("v.", "失败；未能奏效", "failed conversation 中 failed 作过去分词修饰语，表示未能达到交流目的。", "fail—fails—failed—failing", ["not succeed（未成功，解释失效含义）"]),
  focus: word("v.", "集中关注", "focus on + 对象；focused not on tangible inequities 与 Instead...on communication 跨句形成排除与强调。", "focus—focuses—focused—focusing；也可写 focussed/focussing", ["concentrate（集中，通常同样用 on 引对象）"], { collocations: ["focused not on tangible inequities", "focused on communication"] }),
  share: word("n./v.", "份额；共同持有；分担", "their share 是应承担的家务份额；share this expectation 是持有同一期待；Sharing housework 为分担家务。", "名词 share—shares；动词 share—shared—sharing", ["portion（份额，限名词义）", "have in common（共同具有，限动词义）"], { collocations: ["far more than their share", "share this expectation"] }),
  expectation: word("n.", "期待", "this expectation 回指妻子希望丈夫成为交谈伙伴的期待；expectation of their wives 指丈夫对妻子的期待。", "expectation—expectations；独立于 expect 的词形统计", ["hope（希望，未必含期待别人满足的要求）"], { collocations: ["share this expectation"] }),
  short: word("adj.", "简短的；简言之结构中的成分", "In short 整体为总结语，不指漫画人物的身高。", "short—shorter—shortest；in short 为固定表达", ["brief（简短的，in brief 与 in short 近义）"], { collocations: ["In short"] }),
  back: word("n.", "背面", "the back of it 指报纸背面，it 回指 newspaper；不是女人在看丈夫的后背。", "back—backs；本句为名词，非‘返回’的副词", ["reverse side（物体的背面）"], { collocations: ["glares at the back of it"] }),
  face: word("n.", "脸", "in front of his face 中是男人的脸，报纸举在脸前阻隔视线和交流。", "face—faces；动词 face—faced—facing 有面对义", ["front of the head（头部正面的释义，不适合机械替换）"]),
  description: word("n.", "描述；描写", "description of the cartoon 中 of 引出描写对象，detailed 强调细致程度。", "description—descriptions；不合并到 describe", ["account（叙述，也可包含事件经过）"]),
  introduction: word("n.", "介绍", "第30题 a brief introduction to the political scientist 中 to 引被介绍的人，不取法规实施义。", "introduction—introductions；独立于 introduce", ["brief account（简要说明，未必是初次介绍人物）"]),
  brief: word("adj.", "简短的", "修饰 introduction，说明人物简介篇幅短；这里不是 in brief 的句子副词用法。", "brief—briefer—briefest；briefly 为副词", ["short（短的，适用范围更广）"]),
  judge: word("v.", "判断", "Judging from the context 是据上下文判断的评注表达，其理解者是读者或做题者。", "judge—judges—judged—judging", ["assess（评估，常按标准估量而非作特定推断）"]),
  generate: word("v.", "产生", "generating motivation 中以 -ing 形式表示产生动力，和另外三个释义选项保持平行。", "generate—generates—generated—generating", ["produce（产生，是否近义要看后接宾语）"]),
  cause: word("v.", "造成；引起", "causing damage 为造成损害；are caused by 中 by 引原因，第28题B把未给出的因果比例加进来。", "cause—causes—caused—causing", ["bring about（导致，需要重组短语）"]),
  create: word("v.", "造成；产生", "creating pressure 是产生压力；create 可以接负面结果，不总译成正面的创造。", "create—creates—created—creating", ["generate（产生，搭配 pressure 时可近义）"]),
  support: word("v.", "支持", "Supporting their careers 中 their 指妻子们，表示支持她们的职业发展，是本题干扰选项。", "support—supports—supported—supporting", ["help（帮助，未必表示持续支持立场或事业）"]),
  trust: word("v.", "信任", "Trusting them 中 them 指妻子；原文并未将信任列为首要期待。", "trust—trusts—trusted—trusting", ["believe in（信赖，对人的能力或品格有信心）"]),
  attach: word("v.", "赋予；认为具有", "attach importance to + 事物表示重视某事；to 为介词，不是不定式符号。", "attach—attaches—attached—attaching", ["give importance to（认为重要，可用于解释该搭配）"]),
  importance: word("n.", "重要性", "much importance 为不可数用法；attach much importance to communication 表非常重视交流。", "不可数名词，不用 importances 表一般的重要性", ["significance（重要性，也可能含意义或含义）"]),
  female: word("n.", "女性", "a female 在第28题D项为可数名词，her spouse 指她的配偶；本题并非生物学性别分类讨论。", "名词 female—females；形容词 female 无单复数", ["woman（成年女性，在本篇夫妻语境更自然）"]),
  moral: word("adj.", "道德的", "moral decay 为道德衰败；只是错误选项的表述，不代表原文认定交流问题是道德败坏。", "形容词无单复数；morals 作名词另指道德观念", ["ethical（伦理的，常侧重行为规范）"]),
  sex: word("n.", "性别", "sex inequalities 指男女之间的不平等，不取性行为义。", "性别类别可用 the two sexes；此处作前置名词修饰语", ["gender（性别，常着重社会角色而非生物分类）"]),
  expect: word("v.", "期待；预期", "expect somebody to do something 表期待某人做某事；为 expectation 的词族词，不计入其原形次数。", "expect—expects—expected—expecting", ["hope（希望，不可说 hope somebody to do）"]),
  sofa: word("n.", "沙发", "与 couch 都可指供多人坐的软座；sit on a sofa 使用 on。", "sofa—sofas", ["couch（长沙发，常与 sofa 近义）"]),
  quiet: word("n./adj.", "安静；安静的", "quiet 不一定完全没有说话；silence 更明确强调无声或不交谈。", "quiet—quieter—quietest；安静状态通常不可数", ["silence（沉默，常比 quiet 更绝对）"]),
  consent: word("n.", "同意；许可", "consent 常指允许某行为，agreement 还可表示观点一致；不是所有点头认同都涉及许可。", "同意义通常不可数；动词 consent—consented—consenting", ["agreement（意见一致或达成协议，范围不同）"]),
  household: word("n.", "一户人；同住者", "强调住在同一住所的人员，family 则强调家庭或亲属关系。", "household—households", ["family（家庭，成员可能并不共同居住）"]),
  upset: word("adj./v.", "难过的；使不安", "作形容词描述情绪受扰；hurt 更突出受到情感伤害。", "动词 upset—upset—upset；upsetting 双写 t", ["hurt（感情受伤的，含被伤害意味）"]),
});

Object.assign(passage2010P2Lexicon, {
  space: word("n.", "空间；余地", "room 表空间时可与 space 近义，但不能替换 living room 中的一间房间。", "空间义通常不可数；具体空位可用 spaces", ["room（空间义不可数，与房间义不同）"]),
  ask: word("v.", "询问；请求", "ask somebody to do 表请求某人做事；invite 更突出邀请参加或加入。", "ask—asks—asked—asking", ["invite（邀请，仅与 ask 的部分请求用法接近）"]),
  night: word("n.", "夜晚", "night 通常包括更晚的时段；evening 常指傍晚至入夜的活动时间。", "night—nights", ["evening（傍晚或晚间，边界与 night 不完全相同）"]),
  quietly: word("adv.", "安静地", "quietly 可表示小声或不引人注意；silently 明确没有发出声音或说话。", "quietly—more quietly—most quietly", ["silently（默默地，比 quietly 更强调无声）"]),
  rapidly: word("adv.", "迅速地", "常修饰增长或变化速度；quickly 还可突出立即作出反应。", "rapidly—more rapidly—most rapidly", ["quickly（快速地，也可强调反应及时）"]),
  signal: word("v./n.", "示意；信号", "signal 可通过声音、手势等传递信息；gesture 主要强调身体动作。", "signal—signals—signaled—signaling；英式可双写 l", ["gesture（做手势示意，方式更具体）"]),
  laugh: word("v.", "发笑", "laughing 是 laugh 的 -ing 形式，表示发笑这一行为；laughter 是独立名词，burst into laughter 不能机械改成 burst into laugh。", "laugh—laughs—laughed—laughing；laughter 仅关联词族", ["laughter（笑声或发笑状态，名词，不能直接替换动词）"]),
  contrast: word("n./v.", "对照；反差", "contrast 只表示差别，irony 还含出乎预期或颇具讽刺意味的反差。", "名词 contrast—contrasts；动词 contrasted—contrasting", ["difference（差异，不一定被放在一起突出比较）"]),
  circumstance: word("n.", "情况；条件", "常用复数 circumstances 表周围条件；situation 也可指具体社交场合。", "circumstance—circumstances", ["situation（情境，常作为整体状态来描述）"]),
  researcher: word("n.", "研究者", "研究者的学科范围很广；political scientist 特指政治学研究者。", "researcher—researchers", ["scientist（科学家或特定学科研究者，身份范围较窄）"]),
  concrete: word("adj.", "具体的", "与 abstract（抽象的）相对；tangible 还强调可感知或可明确指出。", "concrete—more concrete—most concrete", ["tangible（可明确感知的，侧重点略不同）"]),
  everyday: word("adj.", "日常的", "everyday work 为日常工作；every day 两个词为每天的时间状语。", "形容词无单复数；不拆成 every day 作前置形容词", ["daily（日常的或每日的，侧重点可能在频率）"]),
  plan: word("n./v.", "计划；规划", "a plan 是预先设想的行动方案；arrangements 常包括已经商定的具体安排。", "名词 plans；动词 plan—planned—planning（双写 n）", ["arrangement（安排，常比 plan 更具体）"]),
  hear: word("v.", "听见", "hear 强调声音进入听觉或获知消息；listen to 则强调主动倾听。", "hear—heard—heard；hears；hearing", ["listen（倾听，常需 to 引对象）"]),
  companion: word("n.", "同伴", "companion 侧重陪伴；conversational partner 具体指交谈的伙伴。", "companion—companions", ["partner（伙伴，常共同参与某项活动）"]),
  conventional: word("adj.", "惯常的；传统的", "conventional 可中性地指遵循惯例；stereotypical 更突出刻板和定型。", "conventional—more conventional—most conventional", ["usual（通常的，未必涉及社会惯例）"]),
  desk: word("n.", "书桌；办公桌", "desk 通常用于学习或办公；breakfast table 是吃早餐的桌子。", "desk—desks", ["table（桌子，范围比 desk 宽）"]),
  incentive: word("n.", "激励因素", "incentive 常指奖金、利益等外部诱因；motivation 可指内在动力。", "incentive—incentives", ["motivation（动力或动机，内外来源皆可）"]),
  harm: word("n./v.", "伤害；损害", "cause harm 为造成伤害；可涉及人、环境或利益，damage 也常指物体或关系受损。", "名词损害义不可数；动词 harm—harmed—harming", ["damage（损害，与本篇婚姻受损语境相近）"]),
  lively: word("adj.", "生动的；活跃的", "lively description 强调活泼生动；vivid 还突出清晰鲜明、如在眼前。", "lively—livelier—liveliest（虽以 ly 结尾但为形容词）", ["vivid（生动鲜明的，突出形象清晰）"]),
  considering: word("prep.", "考虑到", "considering + 名词短语可引出判断依据，与介词 given 的这种用法接近。", "介词 considering 不作时态变化；另可为 consider 的动词分词", ["given（鉴于，仅指其介词用法）"]),
  perform: word("v.", "执行；做", "perform a task 表执行任务；不能替换 do 的否定助动词功能。", "perform—performs—performed—performing", ["do（做，范围更宽；助动词义不能这样替换）"]),
  labor: word("n./v.", "劳动", "labor 常强调付出的劳动；work 在本篇还可指日常事务整体。", "劳动义名词通常不可数；动词 labored—laboring；英式 labour", ["work（工作或事务，范围较宽）"]),
  concentrate: word("v.", "集中注意力", "concentrate on somebody/something，on 引关注对象，常与 focus on 接近。", "concentrate—concentrates—concentrated—concentrating", ["focus（集中关注，也常用 on）"]),
  portion: word("n.", "一部分；一份", "portion 强调划分出来的一部分；one's share 常进一步表示应分得或应承担的份额。", "portion—portions", ["share（份额，常带分配或承担关系）"]),
  assess: word("v.", "评估", "assess 强调按照依据评定；judge from the context 强调由上下文作判断。", "assess—assesses—assessed—assessing", ["judge（判断，范围比评估更宽）"]),
  produce: word("v.", "产生；生产", "produce a result 表产生结果；作为 generate 的辨析词，不改变2000年农业原文的生产义。", "produce—produces—produced—producing", ["generate（产生，常用于能量、影响或结果）"]),
  significance: word("n.", "重要性；意义", "significance 可指重要程度，也可指某事意味着什么；importance 主要突出重要程度。", "通常不可数；significant 为形容词，不是其屈折形式", ["importance（重要性，未必含某种含义或指示作用）"]),
  ethical: word("adj.", "伦理的；合乎道德的", "ethical 常涉及行为规范或职业伦理；moral 在 moral decay 中泛指道德层面。", "形容词无单复数；ethically 为独立副词", ["moral（道德的，范围和搭配需分别判断）"]),
  gender: word("n.", "性别；社会性别", "gender 常强调性别角色和社会身份；本题 sex inequalities 谈男女不平等。", "gender—genders；泛指性别概念也可不可数", ["sex（性别，常偏生物分类）"]),
});

Object.assign(passage2010P2Lexicon, {
  about: word("prep.", "关于；涉及", "complaints about their husbands 中 about 引出抱怨涉及的对象，修饰 complaints；不是数量上的‘大约’。", "介词，无屈折变化", ["concerning（关于，比 about 更书面）"]),
  after: word("prep.", "在……之后", "immediately after this text 作后置修饰语，限定第30题所问的相邻后续部分，不表示很久以后。", "介词，无屈折变化", ["following（在……之后，须按修饰关系使用）"]),
  all: word("pron.", "全部", "All of the following 指第28题全部四项陈述；EXCEPT 要求找出其中唯一不成立的一项。", "代词，无普通单复数变化；all of 后接限定的整体", ["every（每一个，后接单数名词，不能直接替换 All of）"]),
  although: word("conj.", "虽然；尽管", "引导男人在公共场合说得更多这一让步前提，与主句在家往往说得更少对照；不再与 but 连用。", "连词，无屈折变化", ["though（虽然，较日常，也可有句末副词用法）"]),
  american: word("adj.", "美国的", "American men 中修饰 men，限定所述男性群体；这里不是单独作名词‘美国人’。", "作形容词无单复数；作名词 American—Americans", ["from the United States（来自美国，需要调整修饰位置）"]),
  at: word("prep.", "在；朝向", "at home 表地点；at the breakfast table 表坐在早餐桌旁；glare at 中引出怒视对象，不都译为‘在……上’。", "介词，无屈折变化", ["in（也可表地点，但 in home 不能替换 at home）"]),
  before: word("adv.", "以前；此前", "years before 作 observed 的时间状语，参照作者这次研究往前推多年；此处 before 后没有宾语。", "副词，无屈折变化", ["earlier（较早，以文中参照时间为基准）"]),
  best: word("adv.（最高级）", "最恰当地；最好地", "best represents 和 can best summarize 中修饰动词，分别比较画面的代表性和概括的贴切程度。", "well—better—best；此处是副词最高级", ["most effectively（最有效地，强调效果，未必完全等于最贴切）"]),
  between: word("prep.", "在……之间", "communication between couples 指夫妻双方的沟通，结合本篇不能读成多对夫妻之间聊天；between man and wife 明确夫妻两方。", "介词，无屈折变化", ["among（在群体之中，不能直接表达本篇夫妻两方的相互关系）"], { collocations: ["communication between couples", "between man and wife"] }),
  book: word("n.", "书；著作", "her new book Divorce Talk 中书名补充说明 book；第30题 new book 回指同一本书，不是新的未介绍著作。", "book—books；此处不是动词‘预订’", ["volume（书卷，可强调某一册或较正式的著作）"]),
  but: word("conj.", "但是；而", "but only a few of the men 对比受访男女给出的理由；第18句 but few husbands 对比夫妻的交流期待。", "连词，无屈折变化", ["yet（然而，也能连接转折分句，但不可在任意位置机械替换）"]),
  by: word("prep.", "由；被", "was observed by... 中引出观察者；are caused by... 中引出原因；research by sociologists 表研究的实施者。", "介词，无屈折变化", ["through（通过，侧重途径，不等于被动句的施事 by）"]),
  chance: word("n.", "机会", "the chance for a career 指发展事业的机会；give up the chance 表放弃机会，不是随机概率。", "chance—chances", ["opportunity（机会，常指有利的条件或时机）"]),
  come: word("v.", "来；回来", "come home from work 表下班回家，home 是方向副词，前面不加 to；When 从句描述惯常情形。", "come—came—come；comes；coming（去 e）", ["return（返回，强调回到原处，结构需相应调整）"], { collocations: ["come home from work"] }),
  comment: word("v.", "评论道；谈到", "I commented that... 以 that 从句报告作者评论的内容；本句不是 comment on + 名词的结构。", "comment—comments—commented—commenting", ["remark（评论说，通常指简短的观察或意见）"]),
  crisis: word("n.", "危机", "the current crisis 回指夫妻沟通模式所造成的婚姻危机；最后一句以漫画将这一问题具体化。", "crisis—crises（不规则复数）", ["emergency（紧急情况，往往更突出需要立即行动）"]),
  different: word("adj.", "不同的", "第29题的 different expectations 与 different conversational patterns 分别谈期待和交谈模式，概括范围不能混为一谈。", "形容词无单复数；differently 为独立副词", ["distinct（有区别的，常强调界限清楚）"]),
  end: word("n.", "末尾；结束时", "toward the end of the evening 表接近当晚聚会结束之时；不是已经结束之后。", "end—ends；本处为名词，不是谓语", ["close（结束，常用于 the close of an event）"]),
  every: word("det.", "每一个；每逢", "every year 整体作频率状语，表示每年；every 后接单数 year。", "限定词，无屈折变化", ["each（每一，较强调逐个个体）"]),
  except: word("prep.", "除……以外", "EXCEPT 在第28题要求从概括的‘均正确’中排除一个错误陈述；大写用于突出逆向设问。", "介词，无屈折变化", ["but（可作‘除……外’，但题干中 EXCEPT 的提示更明确）"]),
  far: word("adv.", "远远地；大大地", "far more than 中加强比较级 more，表示所做家务远超应承担的份额，不表示地理距离。", "程度副词无单复数；本结构不使用 farther", ["much（可加强比较级，强调程度大）"]),
  few: word("det. / pron.", "少数；几乎没有", "only a few of the men 表只有少数受访男性；few husbands 不带 a，强调有同样期待的丈夫很少。", "few—fewer—fewest；接可数名词复数", ["little（少量，用于不可数名词，不能修饰 husbands）"]),
  find: word("v.", "发现", "I found that... 引出作者研究所得结论；不是找回丢失物，也不是 find out 的完整短语。", "find—found—found；finds；finding", ["discover（发现，常更突出此前未知的信息）"]),
  first: word("adv.", "首先；首要地", "first and foremost 是强调优先性的固定搭配，插入 want...to be... 的表语前，不指时间上的第一任伴侣。", "序数词兼副词，无普通复数变化", ["primarily（主要地，侧重重点）"]),
  follow: word("v.", "跟随；随后", "题干 the following 中 following 形容词化或名词化，指下列选项；the following part 指接在本文之后的部分。", "follow—follows—followed—following；following 保留 -ing 词形", ["come after（随后出现，改成谓语时需调整句子）"]),
  for: word("prep.", "对于；为了；……的原因", "reason for their divorces 中引出离婚这件事；chance for a career 中引出机会涉及的事业，并非都表目的。", "介词，无屈折变化", ["of（也可连接名词，但 reason for 的原因关系不能机械换成 of）"]),
  from: word("prep.", "从；来自", "from work 表回家的出发情境；complaints from women 表抱怨来源；judging from 表判断依据。", "介词，无屈折变化", ["out of（从……中出来，范围和搭配不同）"]),
  go: word("v.", "进行；继续", "keep the conversation going 中 going 是宾语补足语，表示使谈话持续，不是人走向某地。", "go—went—gone；goes；going", ["continue（继续，转换 keep 结构时须调整语法）"]),
  group: word("n.", "团体；一群人", "a women's group 补充说明 gathering；that 从句修饰这个女性团体，men 是它邀请的参加者。", "group—groups", ["gathering（聚会或聚集的人，未必是有组织的团体）"]),
  high: word("adj.", "高的", "a high divorce rate 指离婚率数值高，不指人数本身，也不直接给出离婚原因所占比例。", "high—higher—highest", ["large（大的，可修饰数量，但 large rate 不如 high rate 自然）"]),
  home: word("adv. / n.", "家；在家", "come home 中 home 是方向副词，无 to；at home 中与介词 at 组成地点状语，和 in public 对照。", "home—homes 可指具体住所；副词 home 无复数", ["house（房屋，强调建筑，不等于家的场景）"]),
  idea: word("n.", "想法；看法；主旨", "offering ideas 表发表想法；main idea 在第29题指整篇文章主旨，不能只概括其中一个研究结论。", "idea—ideas；复数 ideas 归入同一原形", ["thought（想法；main idea 则常指文章主旨）"]),
  if: word("conj.", "如果", "If she didn't keep... 与 we'd spend... 构成非真实条件，男子设想妻子不主动维持交谈的情况。", "连词，无屈折变化", ["unless（除非，相当于 if...not，但具体改写仍需保持否定范围）"]),
  in: word("prep.", "在……中；以……状态", "in a living room / in public situations 表场景；in silence 表沉默状态；in the late 1970s 表时间；in short 表概括。", "介词，无屈折变化", ["within（在……范围内，不能替换全部 in 的固定搭配）"]),
  influence: word("n.", "影响；影响力", "exerting influence 表施加影响，未说明好坏；第27题须保留 havoc 的破坏性，因此该项过于中性。", "抽象义通常不可数；具体影响可用 influences", ["effect（影响或效果，常强调作用结果）"]),
  instead: word("adv.", "相反；转而", "承接上一句 focused not on...，转入她们真正聚焦的沟通问题；这里不是 instead of + 名词。", "副词，无屈折变化", ["rather（反而，可用于纠正先前说法，位置和搭配需调整）"]),
  into: word("prep.", "进入某种状态", "burst into laughter 中 into 引出突然出现的发笑状态；不是走进一个有形空间。", "介词，无屈折变化", ["in（在某状态中，不表达 burst into 的突发变化）"]),
  line: word("n.", "行", "Line 3, Para. 2 是第27题在试卷排版中的定位标记，指第2段第3行，不是诗行或网站屏幕第3行。", "line—lines", ["row（横排，常用于表格或座位，不宜替换试题定位的 line）"]),
  man: word("n.", "男人；男子", "one man 是聚会中健谈的丈夫；American men 泛指研究所谈美国男性；man and wife 指夫妻双方。", "man—men（不规则复数）；man's / men's 为所有格", ["male（男性，偏性别分类；作名词时语体较不同）"]),
  more: word("adv. / pron.", "更多；更大程度", "talk more 表说话更多；far more than their share 表所做家务超出份额；more talkative 加强形容词程度。", "much/many—more—most；按后接成分区分数量与程度", ["to a greater extent（在更大程度上，不能直接替换所有数量结构）"]),
  most: word("det. / pron. / adv.", "多数；最", "most of the women / most wives 表多数；most often / most probably 中作程度副词，不能都理解为‘大多数’。", "many/much—more—most；most of 后需限定的名词组", ["the majority（多数，作名词时通常需 of 接范围）"]),
  new: word("adj.", "新出的；新的", "her new book Divorce Talk 指该社会学家新出的著作；第30题 the new book 回指同一本书。", "new—newer—newest", ["recent（最近的，强调时间近，不必是全新的）"]),
  not: word("adv.", "不；并非", "focused not on... 将主要关注点从有形不平等中排除，再由 Instead 转到沟通；不表示这些不平等不存在。", "否定副词，无屈折变化；don't / doesn't / didn't 均含 not", ["never（从不，否定时间范围，比单纯 not 更强）"]),
  of: word("prep.", "……的；……之中的", "most of the women 限定多数所指范围；lack of communication 补足所缺内容；share of work 表工作中的份额。", "介词，无屈折变化", ["among（在群体中，不能直接替换 most of 的部分关系）"]),
  often: word("adv.", "经常；往往", "talk less at home 前的 often 限定频率，不说所有男人每次都如此；most often 表最常见的关注方向。", "often—more often—most often", ["frequently（经常，较书面；都不等于 always‘总是’）"]),
  on: word("prep.", "在……上；关于", "on the couch 表坐的位置；focus on 中 on 引出关注对象；not on 中否定的是所关注的事项。", "介词，无屈折变化", ["about（关于，但 focus 固定使用 on，不能直接改为 about）"]),
  one: word("number / det.", "一位；一个", "one man 从在场男子中引出一位，修饰单数名词 man；这里不是替代前文名词的代词 ones。", "数词用法不加复数；代词 one 可有 ones", ["a（一个，可引入不特定对象，但 one 更明确强调一个）"]),
  only: word("adv.", "仅仅；只有", "only a few of the men 限制受访男性的数量，和 most of the women 对照；不表示男性完全没人这样说。", "副词，无屈折变化", ["just（仅仅，较日常；需放在对应焦点前）"]),
  or: word("conj.", "或者；或是", "连接 having given up... 与 doing far more... 两个有形不平等的例子；两项保持名词性 -ing 结构平行。", "连词，无屈折变化", ["and（并且，改变选择或列举的连接关系，不能视为等义）"]),
  other: word("det.", "其他的", "other possible reasons 指除了文中沟通问题之外的其他可能原因，是第30题备选的续写方向。", "other + 名词；others 独立作代词，不是此处的词形", ["additional（额外的，强调在已有项目之外增加）"]),
  own: word("adj.（强调所属）", "自己的", "my own research 强调作者自己的研究，与先前引述其他学者的发现衔接；此处不是谓语‘拥有’。", "强调所属用法无屈折变化；动词 own 另有 owns/owned", ["personal（个人的，未必突出研究由本人进行）"]),
  para: word("n. abbreviation", "段落（paragraph 的缩写）", "Para. 2 与 Line 3 配合，定位第27题的词组在第2段；按原试卷的段落和行数理解。", "para. 缩写自 paragraph；paras. 可作复数缩写", ["paragraph（段落，para. 的完整拼写）"]),
  part: word("n.", "部分", "the following part 指本文后面紧接的部分，不是这篇已给文本中的某一段，也不是下一个选项。", "part—parts", ["section（部分或章节，常有明确分段标题）"]),
  particularly: word("adv.", "特别地；尤其", "修饰形容词 talkative，表示这位男士当晚格外健谈；不是只修饰随后列举的某个话题。", "副词无屈折变化；particular 为独立形容词", ["especially（特别地，两者都可强调程度或突出对象）"]),
  percent: word("n. / adv.", "百分之……", "nearly 50 percent 在正文修饰 divorce rate；第28题却将分母换成 recent divorces，不能把两个比例等同。", "与数值连用通常用 percent，不因50而加 s", ["per hundred（每一百份中的若干份，解释百分比的单位）"]),
  phrase: word("n.", "短语；词组", "第27题 phrase 指引号中的 wreaking havoc，须按造成严重破坏的整体义理解，而非逐词孤立翻译。", "phrase—phrases", ["expression（表达，范围可比短语更宽）"]),
  possible: word("adj.", "可能的", "possible reasons 表可能导致高离婚率的原因，不把选项提出的可能性视为文章已经确认的事实。", "possible—more possible—most possible 较少使用；常说 more likely", ["potential（潜在的，强调尚未显现但有可能发生）"]),
  probably: word("adv.", "很可能；大概", "most probably 在第27、30题限制判断强度，要求选最合语境的含义或续写，不是断言唯一逻辑可能。", "副词无屈折变化；probably 与 possible 不同词性", ["likely（可能地，作副词时常与 most/very 连用）"]),
  public: word("adj.", "公众场合的；公开的", "in public situations 指有其他人在场的交往情境，与 at home 对照；不是政府公有或公共辩护人。", "形容词无单复数；public 作名词可指公众", ["social（社交的，但家中也可能有社交活动，范围不完全等同）"]),
  recent: word("adj.", "最近的", "recent divorces 出现在第28题干扰项，限定近期离婚案例；不能据此说正文给出该范围的原因比例。", "recent—more recent—most recent；recently 为副词", ["latest（最新的，比 recent 更强调时间最靠后）"]),
  research: word("n.", "研究；调查", "my own research 指作者关于婚姻交流的研究；more research 是第29题错误概括提出的更多研究，不是原文主张。", "泛指研究通常不可数，使用 some/more research", ["study（研究，可指一项具体调查，常可数）"]),
  say: word("v.", "说；说话", "said 引出男子的直接引语；nothing to say 中 to say 限定可说的内容，不能扩大成完全没有说话能力。", "say—said—said；says；saying", ["tell（告诉，通常需指明听者，如 tell somebody something）"]),
  small: word("adj.", "小型的；人数少的", "a small gathering 中修饰 gathering，说明聚会规模不大，不指场地狭窄或参加者个子矮。", "small—smaller—smallest", ["little（小的，但可附带感情色彩，不必总指数量少）"]),
  social: word("adj.", "社交的", "social arrangements 指日常生活中安排社交往来的事务，与清洁、做饭并列；不是整个社会制度安排。", "形容词无单复数；socially 为独立副词", ["interpersonal（人际的，范围和典型搭配不同）"]),
  spend: word("v.", "度过；花费时间", "we'd spend the whole evening in silence 表在沉默中度过整晚；spend 后直接接时间，不取花钱义。", "spend—spent—spent；spends；spending", ["pass（度过，但具体搭配和是否主动打发时间有所不同）"]),
  state: word("n. / v.", "州；陈述", "United States 中 States 为国名组成部分；作为 report 的辨析词或改写词时，state 是陈述事实的动词，两种用法分开理解。", "名词 state—states；动词 state—states—stated—stating", ["report（报告，通常强调信息来自观察或调查）"]),
  such: word("det.", "这样的；诸如", "such as 引出 tangible inequities 的两个具体例子；having given up 与 doing... 是列举对象。", "限定词，无屈折变化", ["like（可用于举例，但用法和语体不完全相同）"]),
  tend: word("v.", "往往；倾向于", "tend to talk / tends to be 表一般倾向而非人人如此；后接不定式，tends 与单数 a female 一致。", "tend—tends—tended—tending", ["be inclined to（倾向于，常可带意愿或性格方面的含义）"]),
  than: word("conj. / prep.", "比", "talk more than women 的比较基准是女性说话量；far more than their share 比较实际家务量与应承担份额。", "比较连接成分，无屈折变化", ["compared with（与……相比，须调整结构，不能直接放在 more 后）"]),
  the: word("art.", "特指已知对象", "the man / the evening 回指已经引入的人和聚会当晚；the current crisis 指前文讨论的婚姻危机。", "定冠词，无单复数变化", ["a（泛指一个，与 the 的已知或可确定对象不同）"]),
  this: word("det. / pron.", "这；这个", "This man 回指聚会中的男子；this episode 概括刚讲的事件；this pattern 指公共场合与家庭中说话量相反的模式。", "this—these；名词前作限定词，独立时作代词", ["that（那个，距离和篇章指示焦点不同）"]),
  true: word("adj.", "确实如此；正确的", "It's true 中男子坚持妻子在家更健谈的说法；题干 All...true 用于判断陈述是否有原文依据。", "true—truer—truest；此处无需比较级", ["correct（正确的，侧重与事实或规则吻合）"]),
  up: word("particle", "放弃或举起等短语动词中的小品词", "given up the chance 中 up 与 give 构成‘放弃’；held up 中与 hold 构成‘举起’，不能统一译成向上。", "小品词，无屈折变化", ["above（在上方，介词或副词，不能替换这里的短语动词小品词）"]),
  want: word("v.", "想要；希望", "want their husbands to be... 是宾语加不定式补语；wanting to talk 作伴随分词，逻辑主语是漫画中的 woman。", "want—wants—wanted—wanting", ["wish（希望，往往带愿望色彩，结构及现实可能性不同）"]),
  what: word("interrogative pron.", "什么", "What is most wives' main expectation...? 中 what 询问期待的内容，不是引导名词性从句的连接代词。", "疑问代词，无屈折变化", ["which（哪一个，通常在较明确的范围内选择）"]),
  when: word("conj.", "当……时", "When I come home from work 是时间状语从句，限定 have nothing to say 发生的惯常情形，不询问日期。", "连词，无屈折变化", ["whenever（每当，明确强调每次，语气可能更强）"]),
  which: word("interrogative pron.", "哪一个", "Which of the following 是第29题主语，询问下列哪个陈述最能概括全文；此处不是定语从句关系代词。", "疑问代词，无屈折变化", ["what（什么，通常不强调从已给范围中选择）"]),
  whole: word("adj.", "整个的", "the whole evening 是 spend 的时间宾语，whole 强调整晚这一完整时段，前面已有 the。", "形容词无单复数；a whole 可修饰单个可数整体", ["entire（整个的，也强调整体无遗漏）"]),
  will: word("modal v.", "将；预计会", "第30题 will most probably focus on 推测接下来文字将聚焦什么；will 后接动词原形 focus，不是名词意愿。", "情态动词不加第三人称 s；would 可作过去式或条件式", ["be going to（将要，语气和对既定意图的暗示不完全相同）"]),
  with: word("prep.", "与；带有", "wreak havoc with 引出受损对象婚姻；with a newspaper held up 为报纸处于某状态的附带结构，内部不是完整主谓从句。", "介词，无屈折变化", ["having（带有，不能直接替换 with + 宾语 + 分词的结构）"]),
  woman: word("n.", "女性；女人", "women's group 表女性团体；访谈中的 women 指受访女性；末段 a woman 是漫画中想与丈夫交流的妻子。", "woman—women（不规则复数）；woman's / women's 为所有格", ["female（女性，偏性别分类，语体与 woman 不同）"]),
  year: word("n.", "年", "every year 表每年这一频率；years before 表多年前，不可把两处都译成持续若干年。", "year—years；every 后接单数 year", ["annual period（一年的时段，解释义，不能直接替换所有搭配）"]),
});

Object.assign(passage2010P2Lexicon, {
  mean: word("v.", "意味着；意思是", "第27题主语为单数 the phrase，means 是 mean 的第三人称单数，询问短语的含义；与 means of transport 中名词‘手段’是不同词位。", "mean—means—meant—meaning；名词 means 单复数同形，单独统计", ["signify（表示或意味着，较正式）"], { confusions: ["第27题 means 是动词 mean 的屈折形式；名词 means（手段）不能一概合并到 mean。"] }),
  signify: word("v.", "表示；意味着", "signify 表示某个符号、行为或表达具有某种含义；语体比 mean 正式，不包含 mean 的‘打算’等全部义项。", "signify—signifies—signified—signifying；辅音字母加 y 的词尾变化", ["mean（意味着，使用范围更广）"]),
  probable: word("adj.", "很可能的", "It is probable that... 表某事很可能发生；probable 主要评价事件，不像 likely 那样常用 somebody is likely to do。", "probable—more probable—most probable；probably 为独立副词", ["likely（可能的，可用于 be likely to do）"]),
  late: word("adj. / adv.", "晚期的；较晚地", "the late 1970s 指20世纪70年代后期；最高级 latest 在时间先后语境可表示最新的，不等于正文的年代后期。", "late—later—latest；latest 可表示最新，last 可表示最后，搭配不同", ["recent（最近的，不一定处于某年代的后期）"]),
  proportion: word("n.", "比例；所占份额", "a proportion of a total 表某部分占总体的份额；判断百分比必须明确分子与分母，不能混淆离婚率与离婚原因占比。", "proportion—proportions", ["rate（比率，可按总量或时间等基准计算）"]),
  concerning: word("prep.", "关于", "concerning 后接名词或名词短语，用于较正式地引出所谈对象；此处作 about 的辨析词，不是担忧的谓语。", "介词，无屈折变化；动词 concern 的分词须另按句法判断", ["about（关于，更日常且用法更广）"]),
  volume: word("n.", "书卷；一册", "表示书卷时 volume 是可数名词；与 book 相比，常突出某册书或系列中的一卷。", "volume—volumes", ["book（书，通用称呼）"], { otherMeanings: ["体积；音量；数量"] }),
  yet: word("conj. / adv.", "然而；还；尚", "连接转折分句时 yet 近于 but；用于否定句末表示‘尚未’则是另一副词义项。", "连词或副词，无屈折变化", ["but（但是，转折连词，句法位置须匹配）"]),
  through: word("prep.", "通过；穿过", "through 强调路径、过程或中介，by 在被动句中可引出施事；不能将 was observed by 的 by 换成 through。", "介词，无屈折变化", ["by（通过；由，强调手段或施事，需结合句型）"]),
  distinct: word("adj.", "有区别的；清楚不同的", "distinct from 表与某事物不同，常比 different 更强调边界清楚或可分辨。", "distinct—more distinct—most distinct", ["different（不同的，不一定强调截然可分）"]),
  each: word("det. / pron.", "每一个", "each 强调逐一看待成员；作限定词时接单数名词，each of 后可接限定的复数名词组。", "限定词或代词，无屈折变化", ["every（每一，更侧重群体整体的普遍性）"]),
  primarily: word("adv.", "主要地；首要地", "primarily 修饰动词或整个判断，突出主要目的、原因或部分；first and foremost 更强调优先顺序。", "副词无屈折变化；primary 为独立形容词", ["mainly（主要地，较通用）"]),
  row: word("n.", "一排；一行", "row 多指横向排列的座位、物品或表格单元；试卷文本定位用 line 更自然。", "row—rows", ["line（行；线，文本排版中用 line）"]),
  section: word("n.", "部分；章节", "section 指整体中相对明确的一部分，常有标题或边界；part 不要求有正式划分。", "section—sections", ["part（部分，更通用）"]),
  likely: word("adj. / adv.", "可能的；很可能", "be likely to do 中作表语；most likely 可作副词表示很可能，与题干 most probably 对应，但不能到处按同词性替换。", "likely—likelier/more likely—likeliest/most likely", ["probable（很可能的，形容词，通常不能说 somebody is probable to do）"]),
  interpersonal: word("adj.", "人际的", "interpersonal 修饰人与人之间的关系或交流；social arrangements 更强调安排社交活动等具体事务。", "形容词，无单复数；inter- 表在……之间", ["social（社交的；社会的，范围更广）"]),
  pass: word("v.", "度过；经过", "pass the time 可指打发或度过时间；spend time 更侧重时间如何使用，两者搭配和语气并非处处相同。", "pass—passes—passed—passing", ["spend（花费或度过时间，也可指花钱）"]),
  correct: word("adj. / v.", "正确的；纠正", "作形容词强调答案、判断符合事实或规则；true 也可强调某个说法确实如此，不是虚构。", "形容词常不比较；动词 correct—corrects—corrected—correcting", ["true（真实的；成立的，侧重事实相符）"]),
  whenever: word("conj.", "每当；无论何时", "whenever 可强调每一次出现某情况；when 只给出时间条件时，机械替换会加强频率含义。", "连词，无屈折变化", ["when（当……时，未必明确表示每一次）"]),
  entire: word("adj.", "整个的；全部的", "the entire evening 与 the whole evening 都可强调整个时段；entire 通常放在名词前。", "形容词，通常不作程度比较", ["whole（整个的，常与定冠词或物主限定词连用）"]),
});

export const passage2010P2FormPartOfSpeech: Record<string, string> = {
  ideas: "n.（idea 的复数）", laughing: "v.-ing（laugh 的现在分词）", latest: "adj.（late 的最高级）",
  following: "adj. / pron.（follow 的 -ing 形式，表示下列或接下来的）", states: "n.（United States 中的国名组成）",
  puzzled: "adj.（puzzle 的过去分词形容词）", hurt: "adj.（感情受伤的）", gathering: "n.",
  cleaning: "v.-ing（名词性用法）", cooking: "v.-ing（名词性用法）", living: "adj.（living room 的复合修饰部分）",
  sat: "v.（sit 的过去式）", sitting: "v.-ing（后置修饰 man）", held: "v.-ed（hold 的过去分词，作宾补）",
  "she's": "pron. + v.（she is）", "we'd": "pron. + modal（we would）", "it's": "pron. + v.（it is）",
  given: "prep. / v.-ed（句首表示鉴于；given up 中为 give 的过去分词）",
  his: "possessive determiner / pron.（所有格限定词；to his 中为名词性物主代词）",
  that: "pron. / conjunction（指示代词、关系代词或内容从句连接词）",
};

export const passage2010P2SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2010-p2-s1": {
    address: { contextualMeaning: "向……讲话", use: "addressing 为过去进行时的实义动词，直接接听众。", contextualSubstitutions: [{ label: "speak", chinese: "向……讲话", fit: "with-adjustment", rewrittenSentence: "I was speaking to a small gathering in a suburban Virginia living room – a women's group that had invited men to join them.", nuance: "speak to 更日常；address 更突出面向听众发言。两者保留此处作者在聚会中讲话的命题。", adjustment: "将 addressing 改为 speaking to；speak 在此通过 to 引出听众。", target: "word:speak" }] },
    i: { contextualMeaning: "我（文章叙述者）", use: "I 是 was addressing 的主语；此处还没有进入男子的直接引语。" },
    live: { contextualMeaning: "起居（living room 整体为客厅）", use: "living 为名词复合修饰部分，不是本句的进行时谓语。" },
    room: { contextualMeaning: "房间；室", use: "living room 是房间名称，in...room 作讲话地点状语。" },
    that: { contextualMeaning: "引出限定女性团体的关系", use: "关系代词 that 指 group，作 had invited 的主语；不是没有句法成分的宾语从句连接词。" },
    have: { contextualMeaning: "构成先于讲话发生的过去完成时", use: "had + invited 表事先已经邀请，不取‘拥有’义。" },
    they: { contextualMeaning: "她们（女性团体成员）", use: "them 是 join 的宾语，回指 women's group 中的女性。" },
  },
  "2010-p2-s2": {
    one: { contextualMeaning: "一位（男子）", use: "数词 one 引入一位在场男子，修饰单数 man，不是代替名词的 ones。" },
    particularly: { contextualMeaning: "格外地", use: "程度副词修饰形容词 talkative，突出男子当晚非常健谈。" },
    idea: { contextualMeaning: "想法；看法", use: "复数 ideas 与 anecdotes 并列作 offering 的宾语，此处不是全文主旨。" },
    frequently: { contextualMeaning: "经常地", use: "修饰 offering，说明男子频繁发表看法、讲述趣闻。", contextualSubstitutions: [{ label: "often", chinese: "经常", fit: "direct", rewrittenSentence: "Throughout the evening, one man had been particularly talkative, often offering ideas and anecdotes, while his wife sat silently beside him on the couch.", nuance: "often 较日常，frequently 较书面；两者都表示反复发生，不改变夫妻当晚的表现。", target: "word:often" }] },
    have: { contextualMeaning: "构成过去完成时", use: "had been particularly talkative 为完成时系表结构；talkative 不是现在分词。" },
    be: { contextualMeaning: "处于……状态", use: "been 是 be 的过去分词，与 had 构成过去完成时；talkative 作表语。" },
    offer: { contextualMeaning: "提供；提出", use: "offering 是补充男子具体表现的伴随分词，逻辑主语 one man。" },
    while: { contextualMeaning: "而（同时形成对照）", use: "连接男子健谈与妻子沉默两种表现，主要关系为对比。" },
    sit: { contextualMeaning: "坐着", use: "sat 为 sit 的过去式，silently 修饰坐着时沉默的状态。" },
    he: { contextualMeaning: "他（沙发上的丈夫）", use: "him 是 beside 的宾语，妻子坐在他旁边。" },
  },
  "2010-p2-s3": {
    to: { partOfSpeech: "prep.", contextualMeaning: "与；对", use: "talk to me中to引出交谈对象，后接宾格me，不是不定式标记。" },
    frequently: { contextualMeaning: "经常地", use: "修饰 complain，强调女性反复提出这种抱怨。", contextualSubstitutions: [{ label: "often", chinese: "常常", fit: "direct", rewrittenSentence: "Toward the end of the evening, I commented that women often complain that their husbands don't talk to them.", nuance: "often 的书面色彩比 frequently 弱，但保留抱怨经常发生这一信息。", target: "word:often" }] },
    comment: { contextualMeaning: "评论道；谈到", use: "commented 后接完整 that 内容从句；不是2010完形干扰项里的搭配辨析。" },
    that: { contextualMeaning: "引出评论或抱怨的内容", use: "两个 that 分别引出 commented 与 complain 的宾语从句，都不在从句内部作主语或宾语。" },
    they: { contextualMeaning: "她们（抱怨的女性）", use: "talk to them 中 them 作 to 的宾语，指丈夫不与之交谈的妻子。" },
    do: { contextualMeaning: "不（构成一般现在时否定）", use: "don't = do not，否定 talk to them；不表示丈夫与任何人都不讲话。" },
    toward: { partOfSpeech: "prep.（时间）", contextualMeaning: "临近", use: "Toward the end of the evening说明评论发生的时间；此处不是手势指向。" },
  },
  "2010-p2-s4": {
    agreement: { contextualMeaning: "赞同；一致", use: "in agreement 修饰 nodded 的态度，名词不可数，不是签署协议。" },
    nod: { contextualMeaning: "点头", use: "nodded 是不及物过去式；原卷用动作表达，不改成网上转载的 concurred。" },
  },
  "2010-p2-s5": {
    say: { contextualMeaning: "说", use: "said 为一般过去时，与 gestured 并列，后面直接引用男子说的话。" },
    she: { contextualMeaning: "她（男士的妻子）", use: "She's = She is；the talker 是表语，不是 She has。" },
    our: { contextualMeaning: "我们的", use: "our 属直接引语，指男子与妻子，不是聚会全体成员。" },
    toward: { contextualMeaning: "朝向", use: "与 gestured 组合表手势方向，与第3句 toward 表时间接近的用法不同。" },
  },
  "2010-p2-s6": {
    room: { contextualMeaning: "满屋的人", use: "The room 借地点代指听众，作 burst into laughter 的主语，不是房间本身发笑。" },
    look: { contextualMeaning: "显得；看起来", use: "looked 为系动词，puzzled 和 hurt 并列作表语。" },
    puzzle: { contextualMeaning: "感到困惑的", use: "puzzled 是过去分词形容词，描述男子的感受；puzzling 则描述事物令人困惑。" },
    hurt: { contextualMeaning: "感到委屈、情感受伤的", use: "与 puzzled 并列，指他听到众人笑声时的感受，不指身体损伤。" },
  },
  "2010-p2-s7": {
    it: { contextualMeaning: "这一说法（妻子才是家中话多者）", use: "It's = It is；It 回指前面的命题，不指房间或笑声。" },
    true: { contextualMeaning: "确实如此的", use: "true 作 is 的表语，男子肯定自己刚才的陈述。" },
  },
  "2010-p2-s8": {
    come: { contextualMeaning: "来；返回", use: "come home from work 表从工作场所回家，home 前不加 to。" },
    say: { contextualMeaning: "说；谈", use: "to say 后置修饰 nothing，表示没有可谈的内容；不指不能发音或不会说话。" },
    i: { contextualMeaning: "我（正在解释的丈夫）", use: "两个 I 都位于男子的直接引语内，不再指文章作者。" },
    when: { contextualMeaning: "每当……时", use: "引出时间状语从句，come 与 have 都用现在时描述惯常情况。" },
    home: { partOfSpeech: "adv.（方向）", contextualMeaning: "回家", use: "come home 中 home 作方向副词，不加 to；第10句 at home 才是位置表达。" },
    work: { contextualMeaning: "工作；上班的地方", use: "from work 说明下班回家的来处，不指艺术作品或家务总量。" },
    have: { contextualMeaning: "有", use: "have 是实义及物动词，nothing 作宾语，不是完成时助动词。" },
    to: { partOfSpeech: "infinitive marker", contextualMeaning: "引出说明可说内容的不定式", use: "to say 后置修饰 nothing；此处不是介词，也不表示目的。" },
  },
  "2010-p2-s9": {
    if: { contextualMeaning: "如果；要不是", use: "If she didn't... 与 we'd... 配合，表示与妻子实际上维持谈话的情况相反的假设。" },
    she: { contextualMeaning: "她（维持谈话的妻子）", use: "she 作条件从句主语；不是文章作者或社会学家。" },
    keep: { contextualMeaning: "使持续", use: "keep + the conversation + going；conversation 是宾语，going 是宾语补足语。" },
    go: { partOfSpeech: "v.-ing（宾语补足语）", contextualMeaning: "进行；持续", use: "going 作 conversation 的宾语补足语，不是移动到某处。" },
    we: { contextualMeaning: "我们夫妻两人", use: "we'd = we would，would 与条件从句的过去式共同构成虚拟条件。" },
    spend: { contextualMeaning: "度过", use: "spend 后接 the whole evening 作时间宾语，in silence 表状态，不涉及花钱。" },
  },
  "2010-p2-s10": {
    public: { contextualMeaning: "公共场合的", use: "in public situations 作 talk 的场景状语，和主句的 at home 对比。" },
    home: { partOfSpeech: "n.", contextualMeaning: "家", use: "at home 作 talk less 的地点状语；不是 come home 的方向副词用法。" },
    that: { contextualMeaning: "引出这一反差的具体内容", use: "that 引导同位语从句解释 irony；主语在从句内部是 they，不由 that 充当。" },
    although: { contextualMeaning: "尽管", use: "引出让步从句，承认男子在外常比女性话多，再与在家话少对照。" },
    more: { partOfSpeech: "adv.（比较级）", contextualMeaning: "更多地（说话量）", use: "more 修饰 talk，than women 给出比较方；不是修饰女性的人数。" },
    than: { contextualMeaning: "比", use: "than women 为省略比较分句，理解时补 talk，但不把补词写回原文。" },
    they: { contextualMeaning: "美国男性", use: "they 回指 American men，作同位语从句主句的主语。" },
    less: { partOfSpeech: "adv.（比较级）", contextualMeaning: "较少地（交谈）", use: "less 修饰 talk，与公开场合的 more 对照，不修饰房屋大小。" },
  },
  "2010-p2-s11": {
    wreak: { contextualMeaning: "造成；引发", use: "wreak havoc with marriage 为整个动词搭配，不能只替换 wreak 而不检查后面的介词。", contextualSubstitutions: [{ label: "cause", chinese: "造成", fit: "with-adjustment", rewrittenSentence: "And this pattern is causing serious damage to marriage.", nuance: "cause serious damage 更直白；wreak havoc 带更强烈的破坏比喻。serious 保留原表达的严重程度。", adjustment: "将 wreaking havoc with 整体改为 causing serious damage to，damage 的受损对象用 to 引出。", target: "word:cause" }] },
    pattern: { contextualMeaning: "模式；行为方式", use: "this 回指第10句的完整概括，不仅指某次点头动作。" },
    with: { contextualMeaning: "对（婚姻这一受损对象）", use: "wreak havoc with marriage 中 with 引受影响对象，不表示和婚姻一起做某事。" },
  },
  "2010-p2-s12": {
    observe: { contextualMeaning: "观察到", use: "was observed 为被动语态，by 后才是实施观察的 Andrew Hacker。" },
    by: { contextualMeaning: "由（观察者）", use: "被动句施事介词，不取‘在旁边’或‘截至’义。" },
    late: { partOfSpeech: "adj.", contextualMeaning: "年代后期的", use: "the late 1970s 指20世纪70年代后期，不是迟到，也不表示已故。" },
  },
  "2010-p2-s13": {
    most: { partOfSpeech: "pron.（数量）", contextualMeaning: "大多数", use: "most of the women 限定为受访女性中的大多数，是数量关系，不是副词最高级。" },
    her: { contextualMeaning: "她的（社会学家 Riessman 的）", use: "her new book 中 her 限定 book，不能指开篇聚会中那位妻子。" },
    new: { contextualMeaning: "新出的", use: "修饰 book，书名 Divorce Talk 随后补充说明；不表示某种新的离婚方式。" },
    report: { contextualMeaning: "报告；报道", use: "reports 的主语为社会学家，that 从句是报告内容，in her new book 是载体。", contextualSubstitutions: [{ label: "state", chinese: "陈述；指出", fit: "with-adjustment", rewrittenSentence: "Sociologist Catherine Kohler Riessman states in her new book Divorce Talk that most of the women she interviewed – but only a few of the men – gave lack of communication as the reason for their divorces.", nuance: "state 强调把内容明确说出，report 更强调汇报研究所得；不改变书中报告的女性、男性和离婚归因事实。", adjustment: "reports 改为第三人称单数 states；其余结构保留。", target: "word:state" }] },
    talk: { partOfSpeech: "n.（书名组成）", contextualMeaning: "谈话（书名 Divorce Talk 的组成部分）", use: "这里 Talk 为名词，位于书名中，不作报告句的谓语。" },
    she: { contextualMeaning: "她（社会学家里斯曼）", use: "she 是 interviewed 的主语；women 是省略关系词所代指的宾语。" },
    that: { contextualMeaning: "引出研究报告的内容", use: "that 后的完整句子作 reports 的宾语；不是修饰 book 的定语从句。" },
    give: { contextualMeaning: "列举；给出", use: "gave lack of communication as the reason 表把缺乏交流列为原因，不是给予某人某物。" },
    as: { contextualMeaning: "作为", use: "give A as B 中 as 引出A被列为的身份或解释。" },
    few: { partOfSpeech: "pron.（数量）", contextualMeaning: "少数", use: "a few 表有一些，only 加强数量少的对照；不要与第18句没有 a 的 few 混同。" },
  },
  "2010-p2-s14": {
    give: { partOfSpeech: "prep.", contextualMeaning: "鉴于；考虑到", use: "原文 Given 在此为介词，后接离婚率这个名词短语；沿用既有 give 键，但本句义不能套用‘给’。" },
    that: { contextualMeaning: "上述与沟通有关的情况", use: "that 为指示代词，直接作 amounts 的主语，不是引导从句的连词。" },
    rate: { contextualMeaning: "比率", use: "近50%修饰离婚率，而不是离婚案例中由沟通失败导致的比例；不要变换统计对象。" },
    amount: { contextualMeaning: "总计达到", use: "amounts to + 数量，that 为单数所以用 amounts，不是名词‘总额’。" },
    case: { contextualMeaning: "个案；情况", use: "cases 不取本卷完形中的医学病例义，epidemic 也只是后面的比喻。" },
    virtual: { contextualMeaning: "简直可称为的；几乎等同于的", use: "virtual 修饰 epidemic，强调程度，不表示虚拟计算机世界。" },
    epidemic: { contextualMeaning: "广泛蔓延的问题（流行病比喻）", use: "a virtual epidemic of failed conversation 为同位性评价，没有医学诊断含义。" },
    united: { partOfSpeech: "adj.（国名组成）", contextualMeaning: "联合的", use: "United States为国名美国；United在此不是独立的过去时谓语。" },
    state: { partOfSpeech: "n.（复数，国名组成）", contextualMeaning: "州", use: "States是United States国名的组成部分，不取动词陈述义。" },
    fail: { partOfSpeech: "adj.（分词形容词）", contextualMeaning: "失败的；未奏效的", use: "failed修饰conversation，说明沟通失败的状态，不是本句限定谓语。" },
  },
  "2010-p2-s15": {
    more: { partOfSpeech: "pron.（比较级数量表达）", contextualMeaning: "更多的量", use: "doing far more than their share中more作数量性宾语中心，than their share给出比较基准。" },
    as: { partOfSpeech: "prep.（such as的组成部分）", contextualMeaning: "引出例子", use: "与such组成such as，举例说明tangible inequities；整体义为例如，不是作为或正如。" },
    tangible: { contextualMeaning: "可以具体指出的", use: "修饰 inequities，后面用事业牺牲与家务分担列出实例。", contextualSubstitutions: [{ label: "concrete", chinese: "具体的", fit: "direct", rewrittenSentence: "In my own research, complaints from women about their husbands most often focused not on concrete inequities such as having given up the chance for a career to accompany a husband to his, or doing far more than their share of daily life-support work like cleaning, cooking and social arrangements.", nuance: "concrete 与 abstract 相对，强调具体；tangible 更强调明确可感。列举事实不变，仍与交流期待形成对照。", target: "word:concrete" }] },
    own: { contextualMeaning: "自己的", use: "my own research 强调作者本人开展的研究；own 不是拥有的谓语。" },
    from: { contextualMeaning: "来自（抱怨者）", use: "from women 后置修饰 complaints，交代抱怨的来源。" },
    about: { contextualMeaning: "针对；关于", use: "about their husbands 修饰 complaints，指出抱怨对象，不表示大约。" },
    focus: { contextualMeaning: "把关注重点放在", use: "focused not on... 与下一句 Instead...on... 对照，排除主要关注点，不否认这些不公存在。" },
    most: { partOfSpeech: "adv.", contextualMeaning: "最（常见的关注重点）", use: "most 修饰 often 构成频率最高级状语；不同于 most of the women 中的多数。" },
    give: { partOfSpeech: "v.（过去分词）", contextualMeaning: "与up组成“放弃”的动词成分", use: "having given up 为主动完成式非谓语，the chance 作宾语，不能理解为被给予机会。" },
    his: { contextualMeaning: "他的事业", use: "to his 中 his 独立作名词性物主代词，省略 career；不能补成 his wife。" },
    share: { partOfSpeech: "n.", contextualMeaning: "应当分担的份额", use: "their share of work 中 share 为名词，是 far more than 的比较基准。" },
    work: { contextualMeaning: "工作；事务", use: "life-support work 在这里指维持日常生活的事务，包括清洁、做饭、社交安排，不是职业艺术作品，也不是医疗抢救。" },
    like: { partOfSpeech: "prep.", contextualMeaning: "例如；诸如", use: "like 为举例介词，后接 cleaning、cooking 和 social arrangements，不是喜欢的谓语。" },
    clean: { contextualMeaning: "打扫；清洁", use: "cleaning 为 -ing 的名词性用法，是 like 后的列举项，不作本句谓语。" },
    cook: { contextualMeaning: "做饭；烹饪", use: "cooking 与 cleaning、social arrangements 并列，描述家务内容。" },
    up: { partOfSpeech: "particle（小品词）", contextualMeaning: "构成“放弃”义的短语动词成分", use: "given up整体表示放弃机会；up在此不单独表示向上。" },
  },
  "2010-p2-s16": {
    they: { contextualMeaning: "这些抱怨", use: "they 承接第15句主语 complaints，表示抱怨聚焦于沟通；不是丈夫们。" },
    instead: { contextualMeaning: "相反；实际所关注的是", use: "衔接上一句 not on...，将焦点转到 communication。" },
    focus: { contextualMeaning: "集中；聚焦", use: "focused on communication 给出女性抱怨的实际重点，与上句排除项对照。" },
    he: { contextualMeaning: "他（提出抱怨者的丈夫）", use: "冒号后是示例性直接引语，不特指开篇那位男子。" },
    me: { contextualMeaning: "我（抱怨丈夫不倾听的妻子）", use: "listen to me 中为介词宾语，不能误指文章作者。" },
  },
  "2010-p2-s17": {
    he: { contextualMeaning: "他（提出抱怨者的丈夫）", use: "属于妻子抱怨的直接引语，与上句并列。" },
    me: { contextualMeaning: "我（希望交谈的妻子）", use: "talk to me 指丈夫不与妻子交流，保留特定对象，不扩大成不和任何人说话。" },
    do: { contextualMeaning: "不（现在时否定助动词）", use: "doesn't 承担第三人称单数变化，后面的 talk 保持原形。" },
  },
  "2010-p2-s18": {
    most: { partOfSpeech: "determiner（数量限定词）", contextualMeaning: "大多数的", use: "限定复数 wives，与 but few husbands 的少数形成数量对照。" },
    find: { contextualMeaning: "通过研究发现", use: "found 是 find 的过去式；宾语是整个 that 内容从句，不是寻找某物。" },
    as: { contextualMeaning: "正如", use: "引导评注性非限制性定语从句，as 对应 observed 的宾语，指与作者相同的发现。" },
    before: { contextualMeaning: "以前", use: "years before 指作者发现之前多年，用于比较过去时间，不以读者当前年份为参照。" },
    that: { contextualMeaning: "引出作者发现的内容", use: "连接 found 与包含 but 并列对照的完整宾语从句，不充当内部主语。" },
    want: { contextualMeaning: "希望；想要", use: "want somebody to be + 表语，husbands 是宾语且是不定式的逻辑主语。" },
    first: { contextualMeaning: "首先；最重要地", use: "与 and foremost 组成优先顺序表达，强调交谈伙伴这一角色的重要性。" },
    few: { partOfSpeech: "determiner（数量限定词）", contextualMeaning: "很少的；几乎没有的", use: "few husbands 无不定冠词 a，强调具有同一期待的丈夫很少。" },
    share: { partOfSpeech: "v.", contextualMeaning: "共有；持有同样的", use: "share 为及物动词，this expectation 是宾语，与第15句名词‘份额’不同。" },
    of: { contextualMeaning: "对……所抱有的", use: "this expectation of their wives 中 of their wives 指丈夫期望的对象，不把期待归属给妻子。" },
  },
  "2010-p2-s19": {
    short: { contextualMeaning: "简言之结构中的成分", use: "In short 为概括前文的固定总结语，不是时间短或身材矮。" },
    that: { contextualMeaning: "引出限定 image 的关系", use: "关系代词 that 回指 image，作 represents 的主语，和第14句指示代词不同。" },
    best: { contextualMeaning: "最贴切地", use: "best 为副词最高级修饰 represents，不是表语或名词。" },
    sit: { contextualMeaning: "坐着", use: "sitting 为后置修饰 man 的现在分词，不是整句主干谓语。" },
    hold: { partOfSpeech: "v.（过去分词）", contextualMeaning: "举起", use: "held up 为 with 结构的过去分词宾补，报纸与举起之间是被动关系。" },
    with: { contextualMeaning: "伴随着……的状态", use: "with + a newspaper + held up，名词和分词构成宾语及宾补，不是完整从句。" },
    while: { contextualMeaning: "而（画面中的夫妻对照）", use: "连接男人坐着读报和女人瞪着报纸的场景，同时发生且形成反差。" },
    it: { contextualMeaning: "报纸", use: "the back of it 的 it 回指 a newspaper，不是男人的脸或整幅漫画。" },
    want: { partOfSpeech: "v.-ing（伴随分词）", contextualMeaning: "想要", use: "wanting to talk 为伴随分词短语，逻辑主语是 woman，不是 man 或 newspaper。" },
    newspaper: { partOfSpeech: "n.", contextualMeaning: "报纸", use: "a newspaper是with结构的宾语；后面的held up补充它被举起的状态。" },
    up: { partOfSpeech: "particle（小品词）", contextualMeaning: "向上", use: "held up表示报纸被举起；与第15句given up中的放弃义不同。" },
  },
};
