import type { BeginnerClauseDetail, BeginnerSyntaxComponent, Question, SentenceAnalysis } from "./data";

const component = (text: string, form: string, fn: string, modifies: string, explanation: string): BeginnerSyntaxComponent => ({ text, form, function: fn, modifies, explanation });
const clause = (text: string, type: string, marker: string, role: string, subject: string, predicate: string, objectOrComplement: string, translationOrder: string): BeginnerClauseDetail => ({ text, type, marker, role, subject, predicate, objectOrComplement, translationOrder });

export const passage2010P1Sentences: SentenceAnalysis[] = [
  {
    id: "2010-p1-s1", number: 1,
    text: "The longest bull run in a century of art-market history ended on a dramatic note with a sale of 56 works by Damien Hirst, Beautiful Inside My Head Forever, at Sotheby's in London on September 15th 2008.",
    chunks: [{ text: "The longest bull run in a century of art-market history", role: "subject" }, { text: " ended", role: "predicate" }, { text: " on a dramatic note", role: "modifier" }, { text: " with a sale of 56 works by Damien Hirst, Beautiful Inside My Head Forever,", role: "modifier" }, { text: " at Sotheby's in London", role: "modifier" }, { text: " on September 15th 2008.", role: "modifier" }],
    trunk: "The longest bull run ended.",
    layers: [{ label: "主干", text: "The longest bull run ended：持续时间最长的一轮牛市结束了。" }, { label: "结束方式", text: "on a dramatic note / with a sale...：以一场轰动的专场拍卖收尾。" }, { label: "地点与时间", text: "at Sotheby's in London / on September 15th 2008：地点从拍卖行到城市，时间精确到日期。" }],
    grammar: ["bull run 借用金融市场术语，指价格长期上涨的行情。", "by Damien Hirst 后置修饰 works，说明作品作者；Beautiful Inside My Head Forever 是拍卖专场名称的同位语。", "多个状语按方式—地点—时间展开，找主干时可先全部拿掉。"],
    beginnerSyntax: { components: [component("The longest bull run in a century of art-market history", "名词短语", "主语", "是 ended 的发出者", "中心词是 bull run；longest 表最长，in...history 给出比较范围。"), component("ended", "一般过去时动词", "谓语", "说明牛市走到终点", "不接宾语，是完整的不及物谓语。"), component("on a dramatic note", "on + 名词短语", "方式状语", "修饰 ended", "回答‘以怎样的情形结束’，不能按字面译成‘在一个音符上’。"), component("with a sale of 56 works by Damien Hirst", "with + 名词短语", "伴随/方式状语", "进一步说明 ended 的具体事件", "sale 是中心词；of 引出拍卖对象，by 引出作品创作者。"), component("at Sotheby's in London", "两个地点介词短语", "地点状语", "修饰 sale/ended", "at 指具体机构，in 指更大的城市范围。"), component("on September 15th 2008", "on + 具体日期", "时间状语", "修饰 ended", "具体到某一天用 on。")], clauses: [] },
    literal: "艺术市场百年历史中持续时间最长的一轮牛市，以达米恩·赫斯特的56件作品于2008年9月15日在伦敦苏富比拍卖行的一场拍卖，戏剧性地落幕了。",
    natural: "2008年9月15日，达米恩·赫斯特的56件作品在伦敦苏富比专场拍卖；艺术市场百年来最长的一轮牛市由此戏剧性收官。",
    logic: "以牛市终结的标志性事件开篇，同时埋下‘盛况即转折点’的伏笔。",
    phrases: ["the longest bull run", "in a century of art-market history", "ended on a dramatic note", "a sale of 56 works", "at Sotheby's in London"],
  },
  {
    id: "2010-p1-s2", number: 2,
    text: "All but two pieces sold, fetching more than £70m, a record for a sale by a single artist.",
    chunks: [{ text: "All but two pieces", role: "subject" }, { text: " sold", role: "predicate" }, { text: ", fetching more than £70m", role: "modifier" }, { text: ", a record for a sale by a single artist.", role: "modifier" }],
    trunk: "All but two pieces sold.",
    layers: [{ label: "数量主干", text: "All but two pieces sold：除两件外，其余作品全部售出。" }, { label: "结果", text: "fetching more than £70m：并取得超过七千万英镑的成交额。" }, { label: "同位评价", text: "a record...：这一金额创下单一艺术家专场拍卖纪录。" }],
    grammar: ["all but two = 除了两个以外全部；but 在此是介词‘除……之外’。", "sold 是 sell 的主动形式表达‘卖出、售出’，主语为商品时不必使用被动。", "fetching... 是现在分词结果状语；a record 是对前面金额的同位补充。"],
    beginnerSyntax: { components: [component("All but two pieces", "all but + 数量 + 复数名词", "主语", "是 sold 的对象性主语", "先读 but two‘除两件外’，再回到 all：其余全部。"), component("sold", "一般过去时不及物用法", "谓语", "说明作品成功成交", "这里不是‘作品卖别人’，而是商品以某价格售出。"), component("fetching more than £70m", "现在分词短语", "结果状语", "修饰整句成交结果", "fetch 在交易语境表示‘卖得、取得某金额’，逻辑主语仍是这批作品。"), component("a record for a sale by a single artist", "名词同位短语", "补充说明", "概括 £70m 的纪录性质", "省略了 which was；for 说明哪类纪录，by 说明专场所属艺术家。")], clauses: [] },
    literal: "除两件作品外其余全部售出，取得超过七千万英镑，成为单一艺术家作品拍卖的纪录。",
    natural: "除两件流拍外，其余作品全部成交，总额超过7000万英镑，创下单一艺术家专场拍卖纪录。",
    logic: "用惊人成交结果证明上一句所谓的‘戏剧性’与市场最后的繁荣。",
    phrases: ["all but two", "fetching more than £70m", "a record for a sale", "by a single artist"],
  },
  {
    id: "2010-p1-s3", number: 3,
    text: "It was a last victory.",
    chunks: [{ text: "It", role: "subject" }, { text: " was", role: "predicate" }, { text: " a last victory.", role: "object" }],
    trunk: "It was a last victory.",
    layers: [{ label: "指代", text: "It 回指前两句的赫斯特拍卖成功。" }, { label: "关键判断", text: "a last victory：衰退到来前的最后一次胜利，而非普通的‘上一次胜利’。" }],
    grammar: ["last 放在名词前可表示‘最后的’，这里由下句雷曼破产解释为何是最后一次。", "短句在长句之间形成强烈转折和悬念，是第21题的直接定位句。"],
    beginnerSyntax: { components: [component("It", "人称代词", "主语", "回指前述拍卖", "不要译成无具体内容的‘它’，应还原为‘这场拍卖的成功’。"), component("was", "一般过去时系动词", "谓语", "连接主语与评价", "系动词后不是动作宾语，而是表语。"), component("a last victory", "名词短语", "表语", "说明此次拍卖的历史位置", "last 表‘危机前最后的’，其含义需结合下一句推断。")], clauses: [] },
    literal: "这是最后一次胜利。", natural: "然而，这也成了市场转衰前最后的一场胜利。",
    logic: "用极短句把拍卖成功重新定义为繁荣终点，引出金融危机。", phrases: ["a last victory"],
  },
  {
    id: "2010-p1-s4", number: 4,
    text: "As the auctioneer called out bids, in New York one of the oldest banks on Wall Street, Lehman Brothers, filed for bankruptcy.",
    chunks: [{ text: "As the auctioneer called out bids", role: "condition" }, { text: ", in New York", role: "modifier" }, { text: " one of the oldest banks on Wall Street, Lehman Brothers,", role: "subject" }, { text: " filed for bankruptcy.", role: "predicate" }],
    trunk: "Lehman Brothers filed for bankruptcy.",
    layers: [{ label: "同时背景", text: "As the auctioneer called out bids：就在拍卖师报出竞价时。" }, { label: "主句", text: "Lehman Brothers filed for bankruptcy：雷曼兄弟申请破产。" }, { label: "身份补充", text: "one of the oldest banks on Wall Street 是雷曼兄弟的同位身份。" }],
    grammar: ["as 引导时间/伴随状语从句，强调两件事同时发生。", "call out bids 表高声报出竞价；file for bankruptcy 是法律和商业固定搭配。", "one of + 复数名词作同位说明，真正主语名称 Lehman Brothers 虽含 Brothers，但作为机构名称与 filed 搭配。"],
    beginnerSyntax: { components: [component("As the auctioneer called out bids", "As 引导完整从句", "时间/伴随状语从句", "修饰主句 filed", "先建立时间画面：拍卖师还在喊价。"), component("in New York", "地点介词短语", "地点状语", "修饰 filed", "说明破产申请发生的城市；提前是为了与伦敦拍卖形成对照。"), component("one of the oldest banks on Wall Street, Lehman Brothers", "同位名词结构", "主语", "是 filed 的发出者", "中心名称是 Lehman Brothers；前面的 one of... 解释它的地位。"), component("filed for bankruptcy", "动词 + for 介词宾语", "谓语", "说明银行申请进入破产程序", "file for 是‘正式申请’，bankruptcy 是申请内容。")], clauses: [clause("As the auctioneer called out bids", "时间/伴随状语从句", "As", "为主句提供同步发生的背景", "the auctioneer", "called out", "bids（宾语）", "先译‘就在拍卖师报出竞价时’，再译纽约发生的主句。") ] },
    literal: "当拍卖师报出竞价时，在纽约，华尔街最古老的银行之一——雷曼兄弟——申请了破产。",
    natural: "伦敦拍卖师仍在高声报出竞价之际，纽约的华尔街老牌银行雷曼兄弟却申请了破产。",
    logic: "把艺术市场最后的胜利与金融危机爆发并置，直接解释 last victory。",
    phrases: ["called out bids", "one of the oldest banks", "on Wall Street", "filed for bankruptcy"],
  },
  {
    id: "2010-p1-s5", number: 5,
    text: "The world art market had already been losing momentum for a while after rising bewilderingly since 2003.",
    chunks: [{ text: "The world art market", role: "subject" }, { text: " had already been losing", role: "predicate" }, { text: " momentum", role: "object" }, { text: " for a while", role: "modifier" }, { text: " after rising bewilderingly since 2003.", role: "modifier" }],
    trunk: "The world art market had been losing momentum.",
    layers: [{ label: "主干", text: "The world art market had been losing momentum：全球艺术市场此前一直在失去增长动力。" }, { label: "时间线", text: "after rising...since 2003：这发生在市场自2003年以来令人眼花缭乱的上涨之后。" }],
    grammar: ["had been losing 是过去完成进行时：以2008年为参照，此前已持续一段时间。", "lose momentum 表失去发展势头。", "after rising... 是介词 after + 动名词短语；rising 的逻辑主语是 art market，since 2003 给上涨设置起点。"],
    beginnerSyntax: { components: [component("The world art market", "名词短语", "主语", "是 losing 的主体", "world 和 art 都前置限定 market。"), component("had already been losing momentum", "过去完成进行时 + 宾语", "谓语", "说明截至当时持续发生的变化", "had been doing 强调在另一个过去节点前已经持续；momentum 是失去的对象。"), component("for a while", "for + 时段", "时间状语", "修饰 had been losing", "回答失去势头持续了多久。"), component("after rising bewilderingly since 2003", "after + 动名词短语", "时间状语", "修饰 losing 的先后背景", "rising 由 market 发出；bewilderingly 修饰 rising，since 2003 表上涨起点。")], clauses: [] },
    literal: "全球艺术市场在自2003年以来令人困惑地上涨之后，已经有一段时间一直在失去动力。",
    natural: "自2003年起经历一轮令人眼花缭乱的上涨后，全球艺术市场其实早已持续一段时间显露颓势。",
    logic: "从象征事件转入整体市场走势，说明危机前市场已开始降温。",
    phrases: ["the world art market", "losing momentum", "for a while", "after rising bewilderingly", "since 2003"],
  },
  {
    id: "2010-p1-s6", number: 6,
    text: "At its peak in 2007 it was worth some $65 billion, reckons Clare McAndrew, founder of Arts Economics, a research firm – double the figure five years earlier.",
    chunks: [{ text: "At its peak in 2007", role: "modifier" }, { text: " it", role: "subject" }, { text: " was worth", role: "predicate" }, { text: " some $65 billion", role: "object" }, { text: ", reckons Clare McAndrew, founder of Arts Economics, a research firm", role: "modifier" }, { text: " – double the figure five years earlier.", role: "modifier" }],
    trunk: "It was worth some $65 billion.",
    layers: [{ label: "峰值", text: "At its peak in 2007 / worth some $65 billion：2007年顶峰时规模约650亿美元。" }, { label: "消息来源", text: "reckons Clare McAndrew：克莱尔·麦克安德鲁估算。" }, { label: "比较", text: "double the figure five years earlier：是五年前数字的两倍。" }],
    grammar: ["be worth + 金额表示价值为；some 放在数字前约等于 approximately。", "reckons Clare McAndrew 是插入式倒装的报道语，不改变主句结构。", "founder... 与 a research firm 分别为人和机构补充同位信息；double... 是省略式比较说明。"],
    beginnerSyntax: { components: [component("At its peak in 2007", "at + 名词；in + 年份", "时间/状态状语", "修饰 was worth", "at its peak 表处于最高点，in 2007 精确说明年份。"), component("it was worth some $65 billion", "主系表式价值结构", "主句", "it 回指艺术市场", "worth 是形容词表语；金额直接放在 worth 后，不加 for。"), component("reckons Clare McAndrew", "插入式报道语", "信息来源", "修饰前面的估值判断", "正常语序是 Clare McAndrew reckons；插入后可先括起来。"), component("founder of Arts Economics, a research firm", "两个同位名词短语", "身份说明", "分别解释 Clare 和 Arts Economics", "Clare 是创始人；Arts Economics 是一家研究公司，勿把二者混为同一层。"), component("double the figure five years earlier", "倍数 + 名词短语", "比较补充", "说明 $65bn 与过去数字的关系", "相当于 twice the figure；five years earlier 修饰 figure。")], clauses: [] },
    literal: "艺术市场在2007年的顶峰价值约650亿美元，艺术经济研究公司创始人克莱尔·麦克安德鲁估计——是五年前数字的两倍。",
    natural: "艺术经济研究公司创始人克莱尔·麦克安德鲁估算，2007年巅峰期全球艺术市场规模约650亿美元，足足是五年前的两倍。",
    logic: "用峰值与五年前对比量化此前上涨幅度。",
    phrases: ["at its peak", "was worth some $65 billion", "a research firm", "double the figure", "five years earlier"],
  },
  {
    id: "2010-p1-s7", number: 7,
    text: "Since then it may have come down to $50 billion.",
    chunks: [{ text: "Since then", role: "modifier" }, { text: " it", role: "subject" }, { text: " may have come down", role: "predicate" }, { text: " to $50 billion.", role: "modifier" }],
    trunk: "It may have come down.",
    layers: [{ label: "时间起点", text: "Since then：自2007年峰值以来。" }, { label: "谨慎估计", text: "may have come down to...：市场规模可能已经降至500亿美元。" }],
    grammar: ["may have done 表对过去到现在已发生情况的推测。", "come down to + 数字表示下降到某水平；to 是终点，不能误读为下降了多少。"],
    beginnerSyntax: { components: [component("Since then", "since + 时间点", "时间状语", "修饰 may have come down", "then 回指2007年峰值，说明下降的起点。"), component("it", "代词", "主语", "回指 world art market 的规模", "结合上句金额理解为市场规模。"), component("may have come down", "情态动词 + 完成式", "谓语", "表示对已发生下降的非确定判断", "may 表可能；have come down 表下降已经发生。"), component("to $50 billion", "to + 数值", "结果状语", "修饰 come down", "回答‘降到多少’，不是‘下降了多少’。")], clauses: [] },
    literal: "从那以后，它可能已经降到500亿美元。", natural: "此后，市场规模可能已回落至500亿美元。", logic: "由峰值转向当前缩水，为衰退主题提供数字证据。", phrases: ["since then", "may have come down to"],
  },
  {
    id: "2010-p1-s8", number: 8,
    text: "But the market generates interest far beyond its size because it brings together great wealth, enormous egos, greed, passion and controversy in a way matched by few other industries.",
    chunks: [{ text: "But", role: "connector" }, { text: " the market", role: "subject" }, { text: " generates", role: "predicate" }, { text: " interest", role: "object" }, { text: " far beyond its size", role: "modifier" }, { text: " because it brings together great wealth, enormous egos, greed, passion and controversy", role: "condition" }, { text: " in a way matched by few other industries.", role: "modifier" }],
    trunk: "The market generates interest.",
    layers: [{ label: "转折主干", text: "the market generates interest far beyond its size：市场受关注度远超其规模。" }, { label: "原因", text: "because it brings together...：因为它汇聚财富、自负、贪婪、激情和争议。" }, { label: "比较方式", text: "in a way matched by few other industries：其汇聚方式很少有其他行业能比。" }],
    grammar: ["generate interest 表引发关注；far 修饰 beyond，加强‘远远超出’。", "because 引导原因状语从句，内部 bring together A, B and C 为并列宾语。", "matched by few other industries 是过去分词短语后置修饰 way，相当于 which is matched...；few 含否定意味。"],
    beginnerSyntax: { components: [component("But", "并列连词", "转折连接", "连接规模下降与关注度仍高", "不是推翻下降事实，而是转向解释为何市场仍受关注。"), component("the market generates interest", "主谓宾", "主句主干", "market 发出 generates，interest 承受动作", "generate 在此是‘引起’，不是物理上的发电。"), component("far beyond its size", "副词 + 介词短语", "程度状语", "修饰 generates interest", "说明关注度与市场体量不成比例；far 加强 beyond。"), component("because it brings together great wealth, enormous egos, greed, passion and controversy", "because 引导完整从句", "原因状语从句", "解释为何关注度超出规模", "it 回指市场；bring together 后接五项并列宾语。"), component("in a way matched by few other industries", "介词短语 + 过去分词后置定语", "方式状语", "修饰 brings together", "in a way 表‘以一种方式’；matched...限定这种方式罕有行业可比。")], clauses: [clause("because it brings together great wealth, enormous egos, greed, passion and controversy", "原因状语从句", "because", "解释市场格外引人关注的原因", "it（the market）", "brings together", "great wealth, enormous egos, greed, passion and controversy（并列宾语）", "先译主句结论，再用‘因为’引出五项原因。") ] },
    literal: "但这个市场产生的兴趣远远超出其规模，因为它以一种很少有其他行业可匹敌的方式，把巨大财富、膨胀的自我、贪婪、激情和争议汇聚在一起。",
    natural: "不过，艺术市场吸引的关注远超其体量，因为它把巨额财富、强烈自负、贪婪、激情和争议熔于一炉，鲜有其他行业能与之相比。",
    logic: "解释文章为何聚焦一个体量有限的市场，并修正第23题B的偷换：超出的是关注度，不是增长势头。",
    phrases: ["generates interest", "far beyond its size", "brings together", "in a way matched by few other industries"],
  },
  {
    id: "2010-p1-s9", number: 9,
    text: "In the weeks and months that followed Mr. Hirst's sale, spending of any sort became deeply unfashionable.",
    chunks: [{ text: "In the weeks and months that followed Mr. Hirst's sale", role: "modifier" }, { text: ", spending of any sort", role: "subject" }, { text: " became", role: "predicate" }, { text: " deeply unfashionable.", role: "object" }],
    trunk: "Spending became deeply unfashionable.",
    layers: [{ label: "时间范围", text: "In the weeks and months...：在赫斯特拍卖后的数周与数月。" }, { label: "核心判断", text: "spending of any sort became deeply unfashionable：任何形式的消费都变得很不得人心。" }],
    grammar: ["that followed... 是限制性定语从句，修饰 weeks and months；follow 表时间上紧随其后。", "of any sort 后置修饰 spending，表示任何种类。", "become + 形容词是系表结构；deeply 修饰 unfashionable，表示程度深。"],
    beginnerSyntax: { components: [component("In the weeks and months that followed Mr. Hirst's sale", "in + 时间名词 + 定语从句", "时间状语", "修饰 became", "先找到 weeks and months，再用 that 从句确定是拍卖之后的那些时间。"), component("spending of any sort", "动名词式名词 + of 短语", "主语", "是 became unfashionable 的对象", "spending 是‘花钱/消费’这一行为；of any sort 表任何类型。"), component("became", "一般过去时系动词", "谓语", "连接 spending 与状态变化", "强调从原先可接受变成不受欢迎。"), component("deeply unfashionable", "副词 + 形容词", "表语", "说明 spending 变成的状态", "deeply 是程度状语；unfashionable 在语境中不是衣着过时，而是社会上不受欢迎。")], clauses: [clause("that followed Mr. Hirst's sale", "限制性定语从句", "that", "限定 weeks and months", "that（= weeks and months）", "followed", "Mr. Hirst's sale（宾语）", "先译中心词‘数周和数月’，再前置为‘赫斯特拍卖之后的数周和数月’。") ] },
    literal: "在赫斯特先生拍卖之后的数周和数月里，任何种类的花钱行为都变得极不时髦。",
    natural: "赫斯特拍卖后的几周乃至几个月里，人们对各种消费都迅速失去兴趣。",
    logic: "从宏观危机落到消费行为，是第22题引用句；下一句给出艺术市场中的具体表现。",
    phrases: ["in the weeks and months that followed", "spending of any sort", "became deeply unfashionable"],
  },
  {
    id: "2010-p1-s10", number: 10,
    text: "In the art world that meant collectors stayed away from galleries and salerooms.",
    chunks: [{ text: "In the art world", role: "modifier" }, { text: " that", role: "subject" }, { text: " meant", role: "predicate" }, { text: " collectors stayed away from galleries and salerooms.", role: "object" }],
    trunk: "That meant collectors stayed away.",
    layers: [{ label: "领域", text: "In the art world：落实到艺术界。" }, { label: "具体含义", text: "collectors stayed away...：收藏家不再去画廊和拍卖场。" }],
    grammar: ["that 回指上一句‘消费失宠’。", "meant 后接省略 that 的宾语从句。", "stay away from + 地点/事物表示避开、不参与，不只是物理上离得远。"],
    beginnerSyntax: { components: [component("In the art world", "in + 领域名词", "范围状语", "修饰 meant", "限定上一句现象在艺术市场中的表现。"), component("that", "指示代词", "主语", "回指消费普遍降温", "要还原为上一整句事实，而不是译成‘那个’。"), component("meant", "一般过去时动词", "谓语", "引出具体结果", "mean 在此是‘意味着’，后面接一个完整事件。"), component("collectors stayed away from galleries and salerooms", "省略 that 的完整从句", "宾语从句", "作 meant 的宾语", "collectors 是从句主语，stayed away 是谓语，from...说明避开的地点。")], clauses: [clause("collectors stayed away from galleries and salerooms", "省略 that 的宾语从句", "省略 that", "作 meant 的宾语，解释艺术界的具体表现", "collectors", "stayed away", "from galleries and salerooms（介词补足语）", "先译‘这意味着’，再译‘收藏家远离画廊和拍卖场’。") ] },
    literal: "在艺术界，那意味着收藏家远离画廊和拍卖场。", natural: "具体到艺术界，就是收藏家不再积极光顾画廊和拍卖场。", logic: "直接解释上一句抽象表述，是第22题A的同义改写依据。", phrases: ["in the art world", "stayed away from", "galleries and salerooms"],
  },
  {
    id: "2010-p1-s11", number: 11,
    text: "Sales of contemporary art fell by two-thirds, and in the most overheated sector, they were down by nearly 90% in the year to November 2008.",
    chunks: [{ text: "Sales of contemporary art", role: "subject" }, { text: " fell", role: "predicate" }, { text: " by two-thirds", role: "modifier" }, { text: ", and", role: "connector" }, { text: " in the most overheated sector", role: "modifier" }, { text: ", they", role: "subject" }, { text: " were down", role: "predicate" }, { text: " by nearly 90%", role: "modifier" }, { text: " in the year to November 2008.", role: "modifier" }],
    trunk: "Sales fell, and they were down.",
    layers: [{ label: "总体降幅", text: "Sales of contemporary art fell by two-thirds：当代艺术品销售额下降三分之二。" }, { label: "过热板块", text: "in the most overheated sector...down by nearly 90%：最过热板块近乎暴跌九成。" }, { label: "统计区间", text: "in the year to November 2008：截至2008年11月的一年。" }],
    grammar: ["fall by + 数量表示下降了多少；若表示降到某数用 fall to。", "and 连接两个独立分句，they 回指 sales。", "the year to November 2008 表截至该月为止的十二个月统计期。"],
    beginnerSyntax: { components: [component("Sales of contemporary art", "名词 + of 短语", "第一分句主语", "是 fell 的主体", "中心词 sales；of contemporary art 说明销售对象。"), component("fell by two-thirds", "动词 + by 幅度", "第一分句谓语", "说明总体下降幅度", "by 回答‘下降了多少’，two-thirds 是三分之二。"), component("in the most overheated sector", "in + 行业板块", "范围状语", "修饰第二分句 were down", "限定更严重降幅发生在哪个细分领域。"), component("they were down by nearly 90%", "代词 + 系表式下降表达", "第二分句", "they 回指 sales", "down 是表语；by nearly 90% 仍表示下降幅度。"), component("in the year to November 2008", "in + 截止期", "时间状语", "修饰 were down", "理解为‘截至2008年11月的一年内’。")], clauses: [] },
    literal: "当代艺术销售下降了三分之二，而在最过热的板块，截至2008年11月的一年里，它们下降了将近90%。",
    natural: "当代艺术品销售额缩水三分之二；最过热的细分市场在截至2008年11月的一年内更是暴跌近九成。",
    logic: "用两级降幅量化收藏家退场造成的后果。", phrases: ["sales of contemporary art", "fell by two-thirds", "the most overheated sector", "were down by nearly 90%", "in the year to"],
  },
  {
    id: "2010-p1-s12", number: 12,
    text: "Within weeks the world's two biggest auction houses, Sotheby's and Christie's, had to pay out nearly $200m in guarantees to clients who had placed works for sale with them.",
    chunks: [{ text: "Within weeks", role: "modifier" }, { text: " the world's two biggest auction houses, Sotheby's and Christie's,", role: "subject" }, { text: " had to pay out", role: "predicate" }, { text: " nearly $200m in guarantees", role: "object" }, { text: " to clients who had placed works for sale with them.", role: "modifier" }],
    trunk: "Sotheby's and Christie's had to pay out nearly $200m.",
    layers: [{ label: "时间", text: "Within weeks：短短几周内。" }, { label: "主干", text: "two biggest auction houses...had to pay out nearly $200m：两大拍卖行不得不赔付近两亿美元。" }, { label: "收款对象", text: "to clients who...：付给曾委托它们出售作品的客户。" }],
    grammar: ["Sotheby's and Christie's 是对 two biggest auction houses 的同位说明。", "pay out 表大额支付或赔付；in guarantees 说明款项性质。", "who 引导定语从句修饰 clients；had placed 是过去完成时，委托出售先于赔付。"],
    beginnerSyntax: { components: [component("Within weeks", "within + 时段", "时间状语", "修饰 had to pay out", "表示不超过几周，强调后果来得很快。"), component("the world's two biggest auction houses, Sotheby's and Christie's", "名词短语 + 同位语", "主语", "是 had to pay out 的发出者", "先抓中心 auction houses；两个专名给出具体是哪两家。"), component("had to pay out nearly $200m in guarantees", "had to + 动词短语 + 宾语", "谓语", "说明被迫赔付的金额和性质", "had to 表客观不得不；pay out 表支出大笔款项；in guarantees 表保证金性质。"), component("to clients who had placed works for sale with them", "to 短语 + 定语从句", "对象补足", "说明款项支付给谁", "to clients 是收款对象；who 从句进一步限定这些客户。")], clauses: [clause("who had placed works for sale with them", "限制性定语从句", "who", "修饰 clients", "who（= clients）", "had placed", "works（宾语）；for sale / with them（补充状态与受托方）", "先译成‘客户’，再前置为‘曾把作品交给两家拍卖行出售的客户’。") ] },
    literal: "几周内，世界最大的两家拍卖行苏富比和佳士得不得不向把作品交给它们出售的客户支付近2亿美元保证金。",
    natural: "短短数周，苏富比和佳士得两大拍卖行就被迫向委托售画的客户支付近2亿美元担保款。",
    logic: "从成交下降推进到拍卖行实际损失，显示危机迅速传导。", phrases: ["Within weeks", "auction houses", "pay out", "in guarantees", "placed works for sale with"],
  },
  {
    id: "2010-p1-s13", number: 13,
    text: "The current downturn in the art market is the worst since the Japanese stopped buying Impressionists at the end of 1989.",
    chunks: [{ text: "The current downturn in the art market", role: "subject" }, { text: " is", role: "predicate" }, { text: " the worst", role: "object" }, { text: " since the Japanese stopped buying Impressionists", role: "condition" }, { text: " at the end of 1989.", role: "modifier" }],
    trunk: "The current downturn is the worst.",
    layers: [{ label: "主干评价", text: "The current downturn...is the worst：当前低迷是此后最严重的一次。" }, { label: "比较起点", text: "since the Japanese stopped buying...：自日本买家停止购买印象派作品以来。" }, { label: "具体时间", text: "at the end of 1989：1989年末。" }],
    grammar: ["downturn in + market 表某市场的低迷。", "最高级 the worst 后接 since 从句，表示从过去节点至今的比较范围。", "the Japanese 是 the + 国籍形容词，表示日本人这一群体；stop doing 表停止原先在做的事。"],
    beginnerSyntax: { components: [component("The current downturn in the art market", "名词短语 + in 范围", "主语", "是 is the worst 的对象", "中心词 downturn；current 表当前，in...说明哪个市场的低迷。"), component("is the worst", "系动词 + 最高级表语", "谓语/表语", "评价本轮低迷程度", "the worst 省略了 downturn，可理解为‘最严重的一次低迷’。"), component("since the Japanese stopped buying Impressionists", "since 引导完整从句", "时间比较状语", "限定 the worst 的比较时段", "the Japanese 作主语；stopped 作谓语；buying... 作 stop 的宾语。"), component("at the end of 1989", "at + 时间节点", "时间状语", "修饰 stopped", "说明日本买家停止购买的具体时期。")], clauses: [clause("since the Japanese stopped buying Impressionists at the end of 1989", "时间状语从句", "since", "给最高级 worst 划定从1989年底至今的范围", "the Japanese", "stopped", "buying Impressionists（动名词宾语）；at the end of 1989（时间状语）", "先译主句‘是最严重的一次’，再补‘自1989年底……以来’。") ] },
    literal: "当前艺术市场的低迷，是自日本人在1989年底停止购买印象派作品以来最严重的一次。",
    natural: "自1989年底日本买家退出印象派艺术品市场以来，本轮艺术市场下滑最为严重。",
    logic: "以历史比较界定本轮衰退的严重性，开启对当前阶段的判断。", phrases: ["The current downturn", "the worst since", "stopped buying", "at the end of"],
  },
  {
    id: "2010-p1-s14", number: 14,
    text: "This time experts reckon that prices are about 40% down on their peak on average, though some have been far more fluctuant.",
    chunks: [{ text: "This time", role: "modifier" }, { text: " experts", role: "subject" }, { text: " reckon", role: "predicate" }, { text: " that prices are about 40% down on their peak on average", role: "object" }, { text: ", though some have been far more fluctuant.", role: "condition" }],
    trunk: "Experts reckon that prices are down.",
    layers: [{ label: "专家估计", text: "prices are about 40% down on their peak on average：价格平均比峰值低约40%。" }, { label: "让步例外", text: "though some have been far more fluctuant：不过部分价格波动大得多。" }],
    grammar: ["reckon 后的 that 从句是宾语；be down on + 基准表示低于该基准。", "on average 修饰40%的总体估计，不能套用到每件作品。", "though 引导让步状语从句；some 代指 some prices/works。原卷用 fluctuant，按所给试卷保留，含义为‘波动的’。"],
    beginnerSyntax: { components: [component("This time", "指示词 + 名词", "时间/情境状语", "修饰 reckon", "把本轮低迷与1989年那次区分开。"), component("experts reckon", "主谓", "主句主干", "experts 作判断者", "reckon 在正式报道中是‘估计、认为’，后接判断内容。"), component("that prices are about 40% down on their peak on average", "that 引导完整从句", "宾语从句", "作 reckon 的宾语", "prices 是从句主语；are down 是谓语/表语；on their peak 是比较基准；on average 是总体口径。"), component("though some have been far more fluctuant", "though 引导完整从句", "让步状语从句", "对平均值补充例外", "some 回指部分价格；far 修饰 more，加强比较级。")], clauses: [clause("that prices are about 40% down on their peak on average", "宾语从句", "that", "作 reckon 的内容宾语", "prices", "are", "about 40% down（表语）；on their peak（比较基准）；on average（统计状语）", "先译‘专家估计’，再译完整判断‘价格平均比峰值低约40%’。"), clause("though some have been far more fluctuant", "让步状语从句", "though", "补充不受平均值完全概括的个别情况", "some（prices）", "have been", "far more fluctuant（表语）", "主句后补‘尽管有些价格的波动要大得多’。") ] },
    literal: "这一次，专家估计价格平均比其峰值低约40%，尽管有些一直波动得更厉害。",
    natural: "专家估计，本轮市场价格平均已较峰值下跌约40%，但不同作品的波动幅度差别很大。",
    logic: "给出总体降幅，同时提醒平均值掩盖了个体差异。", phrases: ["This time", "reckon that", "are about 40% down on their peak", "on average", "far more fluctuant"],
  },
  {
    id: "2010-p1-s15", number: 15,
    text: "But Edward Dolman, Christie's chief executive, says: \"I'm pretty confident we're at the bottom.\"",
    chunks: [{ text: "But", role: "connector" }, { text: " Edward Dolman, Christie's chief executive,", role: "subject" }, { text: " says", role: "predicate" }, { text: ": \"I'm pretty confident we're at the bottom.\"", role: "object" }],
    trunk: "Edward Dolman says.",
    layers: [{ label: "转折来源", text: "Edward Dolman, Christie's chief executive：佳士得首席执行官爱德华·多尔曼。" }, { label: "判断", text: "I'm pretty confident we're at the bottom：他相当确信市场已经触底。" }],
    grammar: ["Christie's chief executive 是同位语，补充 Edward Dolman 的身份。", "confident 后接省略 that 的宾语/补足从句 we're at the bottom。", "at the bottom 是市场隐喻，指跌至最低点，不是空间上的底部。"],
    beginnerSyntax: { components: [component("But", "并列连词", "转折连接", "连接严重下跌与触底判断", "表示虽跌幅很大，但业内人士认为最坏阶段或已过去。"), component("Edward Dolman, Christie's chief executive", "专名 + 同位语", "主语", "是 says 的发出者", "逗号之间是身份说明，拿掉仍剩完整主干。"), component("says", "一般现在时动词", "谓语", "引出直接引语", "新闻写作常用现在时转述当前观点。"), component("I'm pretty confident we're at the bottom", "直接引语，内含从句", "宾语内容", "说明说了什么", "I am confident 是外层；we're at the bottom 是 confident 的具体内容。")], clauses: [clause("we're at the bottom", "省略 that 的内容从句", "省略 that", "补充 confident 的确信内容", "we（泛指艺术市场参与者/市场）", "are", "at the bottom（表语）", "先译‘我相当确信’，再接‘市场已经触底’。") ] },
    literal: "但佳士得首席执行官爱德华·多尔曼说：‘我相当有信心，我们正处于底部。’", natural: "不过，佳士得首席执行官爱德华·多尔曼表示：‘我很有把握，市场已经触底。’", logic: "在悲观数据后引入谨慎乐观判断，为末段分析本轮低迷的不同之处过渡。", phrases: ["chief executive", "I'm pretty confident", "we're at the bottom"],
  },
  {
    id: "2010-p1-s16", number: 16,
    text: "What makes this slump different from the last, he says, is that there are still buyers in the market.",
    chunks: [{ text: "What makes this slump different from the last", role: "subject" }, { text: ", he says,", role: "modifier" }, { text: " is", role: "predicate" }, { text: " that there are still buyers in the market.", role: "object" }],
    trunk: "What makes this slump different is that there are still buyers.",
    layers: [{ label: "主语从句", text: "What makes this slump different from the last：使本轮低迷不同于上一次的因素。" }, { label: "插入来源", text: "he says：仍是多尔曼的判断。" }, { label: "表语从句", text: "that there are still buyers in the market：市场中仍有买家。" }],
    grammar: ["What 引导融合型关系主语从句，相当于 the thing that。", "make A different from B 是 make + 宾语 + 形容词补足语。", "is 后 that 引导表语从句；there be 表存在，真正内容是 buyers。"],
    beginnerSyntax: { components: [component("What makes this slump different from the last", "What 引导完整从句", "主语从句", "整体作主句 is 的主语", "先把整块替换成‘使本轮低迷不同的因素’，不要逐字疑问式翻译。"), component("he says", "插入式主谓", "信息来源", "修饰整句判断", "两个逗号夹住，可先拿掉读主干。"), component("is", "系动词", "主句谓语", "连接问题式主语与答案", "前面是‘不同之处’，后面给出具体答案。"), component("that there are still buyers in the market", "that 引导完整从句", "表语从句", "说明不同之处是什么", "there are 表存在；buyers 是真正内容主语；still 强调危机中仍然存在。")], clauses: [clause("What makes this slump different from the last", "融合型关系主语从句", "What（= the thing that）", "整体作主句主语", "What", "makes", "this slump（宾语）+ different from the last（宾语补足语）", "整体先译为‘使本轮低迷不同于上次的地方’，再接 is 后答案。"), clause("that there are still buyers in the market", "表语从句", "that", "作 is 的表语，给出差异内容", "buyers（there be 的实际主语）", "are", "still / in the market（状语）", "译为‘市场中仍然存在买家’。") ] },
    literal: "他说，使这次低迷与上次不同的是，市场中仍然有买家。", natural: "他认为，本轮低迷与上一次不同之处在于：市场需求方并未消失，买家仍在。", logic: "提出本轮低迷的核心特征：问题不在买家完全消失，为下句供给不足作铺垫。", phrases: ["makes this slump different from the last", "this slump", "there are still buyers", "in the market"],
  },
  {
    id: "2010-p1-s17", number: 17,
    text: "Almost everyone who was interviewed for this special report said that the biggest problem at the moment is not a lack of demand but a lack of good work to sell.",
    chunks: [{ text: "Almost everyone who was interviewed for this special report", role: "subject" }, { text: " said", role: "predicate" }, { text: " that the biggest problem at the moment is not a lack of demand but a lack of good work to sell.", role: "object" }],
    trunk: "Almost everyone said that the biggest problem is a lack of good work.",
    layers: [{ label: "调查来源", text: "Almost everyone who was interviewed...：本专题采访到的几乎所有人。" }, { label: "否定误判", text: "not a lack of demand：最大问题不是需求不足。" }, { label: "真正问题", text: "but a lack of good work to sell：而是缺少可供出售的优质作品。" }],
    grammar: ["who was interviewed... 是定语从句，修饰 everyone；for 表为了这份专题报道。", "said 后 that 引导宾语从句。", "not A but B 为纠正型并列‘不是A，而是B’；to sell 后置修饰 good work，逻辑上是供人出售。"],
    beginnerSyntax: { components: [component("Almost everyone who was interviewed for this special report", "代词 + 定语从句", "主语", "是 said 的发出者", "everyone 是中心；who 从句限定为接受本专题采访的人。"), component("said", "一般过去时动词", "主句谓语", "引出受访者共识", "后面整块 that 从句是所说内容。"), component("that the biggest problem at the moment is not a lack of demand but a lack of good work to sell", "that 引导完整从句", "宾语从句", "作 said 的宾语", "problem 是从句主语；at the moment 修饰 is；后面 not...but... 是表语。"), component("not a lack of demand but a lack of good work to sell", "not A but B 并列结构", "表语", "说明 biggest problem 的真正内容", "先否定需求不足，再肯定优质货源不足；to sell 修饰 work。")], clauses: [clause("who was interviewed for this special report", "限制性定语从句", "who", "修饰 everyone", "who（= everyone）", "was interviewed", "for this special report（目的/用途状语）", "译成‘为本专题报道接受采访的人’后放到 everyone 前。"), clause("that the biggest problem at the moment is not a lack of demand but a lack of good work to sell", "宾语从句", "that", "作 said 的内容宾语", "the biggest problem", "is", "not a lack of demand but a lack of good work to sell（表语）", "先译‘几乎所有人都说’，再按‘不是……而是……’译判断。") ] },
    literal: "几乎每一个为本专题报道接受采访的人都说，目前最大的问题不是缺乏需求，而是缺乏可以出售的好作品。",
    natural: "本专题采访的业内人士几乎一致认为：眼下最大难题不是没人想买，而是没有足够优质的作品可卖。",
    logic: "用多方采访验证上句判断，把市场矛盾明确定位为供给不足。", phrases: ["was interviewed for", "at the moment", "not a lack of demand but a lack of good work", "a lack of demand", "good work to sell"],
  },
  {
    id: "2010-p1-s18", number: 18,
    text: "The three Ds – death, debt and divorce – still deliver works of art to the market.",
    chunks: [{ text: "The three Ds – death, debt and divorce –", role: "subject" }, { text: " still deliver", role: "predicate" }, { text: " works of art", role: "object" }, { text: " to the market.", role: "modifier" }],
    trunk: "The three Ds deliver works of art to the market.",
    layers: [{ label: "三D解释", text: "death, debt and divorce 是 three Ds 的同位解释。" }, { label: "作用", text: "deliver works of art to the market：促使艺术品流入市场。" }],
    grammar: ["破折号之间不是插入句，而是列举 three Ds 的具体内容。", "deliver A to B 表把A送到B；这里是拟人化用法，三种人生事件迫使藏家出售作品。", "still 表尽管优质供给不足，这些传统因素仍在发挥作用。"],
    beginnerSyntax: { components: [component("The three Ds", "限定词 + 复数名词", "主语中心", "是 deliver 的发出者", "三个D不是字母本身，而是三个以D开头的因素。"), component("death, debt and divorce", "三个并列名词", "同位解释", "解释 the three Ds", "分别是死亡、债务和离婚；两侧破折号可理解为‘也就是’。"), component("still deliver", "副词 + 一般现在时动词", "谓语", "说明这些因素至今仍促成供给", "still 修饰 deliver，强调危机中作用持续。"), component("works of art to the market", "宾语 + to 方向短语", "宾语与方向补足", "works 承受 deliver；to 指流向市场", "不要译成三D亲自运输，而是‘促使作品上市流通’。")], clauses: [] },
    literal: "三个D——死亡、债务和离婚——仍然把艺术作品送到市场。", natural: "死亡、债务和离婚这三类变故，仍会迫使藏品进入市场流通。", logic: "解释市场尚存的一类被动供给，也是第24题‘促进艺术品流通的因素’的定位句。", phrases: ["The three Ds", "works of art", "deliver works of art to the market"],
  },
  {
    id: "2010-p1-s19", number: 19,
    text: "But anyone who does not have to sell is keeping away, waiting for confidence to return.",
    chunks: [{ text: "But", role: "connector" }, { text: " anyone who does not have to sell", role: "subject" }, { text: " is keeping away", role: "predicate" }, { text: ", waiting for confidence to return.", role: "modifier" }],
    trunk: "Anyone is keeping away.",
    layers: [{ label: "主语限定", text: "anyone who does not have to sell：任何没有被迫出售压力的人。" }, { label: "当前行为", text: "is keeping away：都在离场观望。" }, { label: "等待目标", text: "waiting for confidence to return：等待市场信心恢复。" }],
    grammar: ["who 引导定语从句修饰 anyone；have to 表客观必要，否定后是‘不必卖’。", "keep away 在此是不参与市场、暂不出售，语义由上下文补足。", "waiting... 是现在分词伴随状语；for confidence to return 是 for + 名词 + to do 的复合结构，confidence 是 return 的逻辑主语。"],
    beginnerSyntax: { components: [component("But", "并列连词", "转折连接", "连接被迫供给与主动观望", "三D仍带来作品，但没有出售压力的人选择不卖。"), component("anyone who does not have to sell", "不定代词 + 定语从句", "主语", "是 is keeping away 的主体", "anyone 是中心；who 从句限定为‘不必出售的人’。"), component("is keeping away", "现在进行时短语", "谓语", "说明当下持续观望", "省略了 from the market/from selling，由语境补出；进行时强调当前阶段。"), component("waiting for confidence to return", "现在分词 + for 复合结构", "伴随/目的倾向状语", "修饰 is keeping away", "waiting 的逻辑主语仍是 anyone；confidence 是 to return 的逻辑主语。")], clauses: [clause("who does not have to sell", "限制性定语从句", "who", "修饰 anyone", "who（= anyone）", "does not have to sell", "无直接宾语（sell 在语境中指卖作品）", "译成‘不必非卖不可的人’放在 anyone 前。") ] },
    literal: "但任何不必出售的人都在避开，等待信心回来。", natural: "但凡没有迫切出售压力的藏家都选择继续观望，静待市场信心恢复。", logic: "以自愿卖家惜售收束全文，解释为何需求尚在却优质供给不足，并支撑市场仍处低迷期的主旨。", phrases: ["have to sell", "keeping away", "waiting for confidence to return"],
  },
];

const q = (number: number, sentenceId: string, prompt: string, options: [string, string, string, string], answer: "A" | "B" | "C" | "D", locating: string, explanations: Question["explanations"]): Question => ({
  id: 201000 + number, number, sentenceId, prompt,
  options: (["A", "B", "C", "D"] as const).map((key, index) => ({ key, text: options[index] })),
  answer, locating, explanations,
});

export const passage2010P1Questions: Question[] = [
  q(21, "2010-p1-s3", "In the first paragraph, Damien Hirst's sale was referred to as \"a last victory\" because________________.", ["the art market had witnessed a succession of victories", "the auctioneer finally got the two pieces at the highest bids", "Beautiful Inside My Head Forever won over all masterpieces", "it was successfully made just before the world financial crisis"], "D", "第3句称其为‘最后的胜利’，第4句立即把伦敦拍卖的叫价与雷曼兄弟申请破产并置：拍卖成功恰好发生在金融危机全面冲击市场之前。", { A: "文中只回顾一轮长期牛市，没有说艺术市场连续取得多场‘胜利’；succession 属无依据扩展。", B: "第2句说除两件外其余售出，未说拍卖师以最高价卖出那两件；事实方向相反。", C: "Beautiful Inside My Head Forever 是专场名称，文中没有与所有杰作比较。", D: "正确。拍卖成交盛况与雷曼破产同步，成为金融危机前最后一次显著成功。" }),
  q(22, "2010-p1-s10", "By saying \"spending of any sort became deeply unfashionable\" (Line 1-2, Para. 3), the author suggests that ________________.", ["collectors were no longer actively involved in art-market auctions", "people stopped every kind of spending and stayed away from galleries", "art collection as a fashion had lost its appeal to a great extent", "works of art in general had gone out of fashion so they were not worth buying"], "A", "引用句后的第10句给出作者自己的解释：在艺术界，这意味着收藏家远离画廊和拍卖场，即不再积极参与交易。", { A: "正确。collectors stayed away from galleries and salerooms 正是‘不再积极参与艺术市场拍卖’的同义表达。", B: "every kind of spending 是将强调性的 any sort 绝对化；原文重点落在艺术市场中的具体表现。", C: "失宠的是 spending（花钱行为），不是把 art collection 作为一种时尚本身。", D: "文中没有说艺术品本身不再时髦或不值得购买，后文反而说市场仍有买家。" }),
  q(23, "2010-p1-s8", "Which of the following statements is NOT true?", ["Sales of contemporary art fell dramatically from 2007 to 2008.", "The art market surpassed many other industries in momentum.", "The art market generally went downward in various ways.", "Some art dealers were awaiting better chances to come."], "B", "第8句说艺术市场因汇聚财富、欲望和争议而获得远超体量的关注，few other industries 能匹敌的是这种汇聚方式，并非市场增长 momentum。", { A: "符合第11句：当代艺术销售下跌三分之二，过热板块近九成。", B: "不正确，故为答案。原文的比较项是关注度及其汇聚财富、激情与争议的方式，不是增长势头。", C: "符合第5、7、11、14句：势头、市场规模、销量和价格均出现下降。", D: "与第19句一致：没有出售压力的人离场等待信心恢复，即等待更好时机。" }),
  q(24, "2010-p1-s18", "The three Ds mentioned in the last paragraph are ________________.", ["auction houses' favorites", "contemporary trends", "factors promoting artwork circulation", "styles representing Impressionists"], "C", "第18句使用 deliver A to B：死亡、债务和离婚会迫使持有人出售，从而把艺术品带入市场流通。", { A: "文中没有说拍卖行偏爱这些事件；它们只是造成被迫出售的外部因素。", B: "three Ds 是三类人生变故，不是当代艺术潮流。", C: "正确。deliver works of art to the market 即推动艺术品进入市场、促进流通。", D: "它们与印象派风格无关；Impressionists 只出现在上一段的历史比较中。" }),
  q(25, "2010-p1-s19", "The most appropriate title for this text could be ________________.", ["Fluctuation of Art Prices", "Up-to-date Art Auctions", "Art Market in Decline", "Shifted Interest in Arts"], "C", "全文从赫斯特拍卖这场‘最后的胜利’写到销量、价格下跌以及卖家惜售，中心是金融危机背景下艺术市场的衰退。", { A: "价格波动只是第四段的一项数据，范围过窄，不能覆盖销量、拍卖行赔付与供给问题。", B: "文章不是介绍最新拍卖动态，而是借一场拍卖标志市场转折。", C: "正确。Art Market in Decline 准确概括全文持续讨论的艺术市场下滑。", D: "文中变化的是消费与交易行为，并未把重点放在人们艺术兴趣转移到别处。" }),
];
