import type { BeginnerSyntaxComponent, BeginnerClauseDetail, QuestionAnalysis, SentenceAnalysis, SyntaxVisualRole } from './data';
import { withReviewedSyntax } from './reviewed-syntax';
const c=(text:string,form:string,fn:string,modifies:string,explanation:string,children?:BeginnerSyntaxComponent[]):BeginnerSyntaxComponent=>({text,form,function:fn,modifies,explanation,children});
const a=(id:string,text:string,trunk:string,components:BeginnerSyntaxComponent[],colors:SyntaxVisualRole[],meaning:string,focus:string,clauses:BeginnerClauseDetail[]=[]):SentenceAnalysis=>withReviewedSyntax({id,number:0,text,trunk,beginnerSyntax:{components,clauses},layers:[{label:'读题关键',text:focus}],grammar:[focus],literal:meaning,natural:meaning,logic:'先辨明本项实际命题；是否选入另看题目原文证据。',phrases:[]},colors);
const p=(...args:Parameters<typeof a>):SentenceAnalysis=>({...a(...args),textKind:'phrase'});
export const passage2011P1QuestionAnalysis:Record<number,QuestionAnalysis>={
21:{prompt:a('201121-prompt-analysis','According to Paragraph 1, Ms. Simmons was criticized for____.','Ms. Simmons was criticized for____.',[
 c('According to Paragraph 1','介词结构','依据状语','整句提问','限定根据第一段作答，不按人物常识推测。'),c('Ms. Simmons','称谓加人名','主语','was criticized','受批评的人。'),c('was criticized','过去时被动语态','谓语','Ms. Simmons','criticism来自他人，主语不是主动批评者。'),c('for____','介词与待填内容','原因状语','was criticized','for后接原因；四项均为动名词短语。')],['modifier','subject','predicate','modifier'],'根据第一段，西蒙斯女士因什么受到批评？','be criticized for因……受批评，原因与后续辞职分开。'),options:{
 A:p('201121-A-analysis','gaining excessive profits','gaining excessive profits',[c('gaining','动名词','原因的动作中心','接在for后','逻辑主语承接西蒙斯。'),c('excessive profits','名词短语','宾语','gaining','过高的利润，excessive表超出适度。')],['complement','object'],'获取过高利润。','这是她本人获利的命题，不是监督他人奖金。'),
 B:p('201121-B-analysis','failing to fulfill her duty','failing to fulfill her duty',[c('failing','动名词','原因的动作中心','接在for后','fail to do表示没有做到。'),c('to fulfill her duty','不定式短语','不定式补足语','failing','未完成的行为是履行职责。',[c('her duty','名词短语','宾语','fulfill','her指西蒙斯；duty是职责，不是关税。')])],['complement','complement'],'未能履行她的职责。','fail to do不要求把to误读成介词；fulfill直接接duty。'),
 C:p('201121-C-analysis','refusing to make compromises','refusing to make compromises',[c('refusing','动名词','原因的动作中心','接在for后','拒绝做某事。'),c('to make compromises','不定式短语','宾语','refusing','make compromises是作出妥协。')],['complement','object'],'拒绝作出妥协。','refuse to do表达主动拒绝，和未完成职责不同。'),
 D:p('201121-D-analysis','leaving the board in tough times','leaving the board',[c('leaving','动名词','原因的动作中心','接在for后','离开某组织。'),c('the board','名词短语','宾语','leaving','董事会，不是木板。'),c('in tough times','介词短语','时间状语','leaving','处于艰难时期；times是时期复数。')],['complement','object','modifier'],'在困难时期离开董事会。','选项把辞职当受批评原因，需要回原文核对先后。')
}},
22:{prompt:a('201122-prompt-analysis','We learn from Paragraph 2 that outside directors are supposed to be____.','We learn that outside directors are supposed to be____.',[
 c('We','人称代词','主语','learn','读者从文中得知。'),c('learn','一般现在时动词','谓语','We','后接所知内容。'),c('from Paragraph 2','介词短语','信息来源状语','learn','限定第二段。'),c('that outside directors are supposed to be____','内容从句','宾语从句','learn','问本应是什么角色；supposed to保留规范预期。',[c('outside directors','名词短语','从句主语','are supposed','外部董事。'),c('are supposed to be','职责预期结构','从句谓语','outside directors','本应处于某身份。'),c('____','待填内容','表语','be','用名词短语填写角色。')])],['subject','predicate','modifier','object'],'从第二段可以得知，外部董事本应是怎样的人？','角色中心词与修饰语必须一起成立；本应不是现实已做到。',[{text:'that outside directors are supposed to be____',type:'宾语从句',marker:'that',role:'作learn宾语',subject:'outside directors',predicate:'are supposed to be',predicateDetails:[{function:'表语',text:'____'}],translationOrder:'先译得知，再译外部董事本应是哪种角色。'}]),options:{
 A:p('201122-A-analysis','generous investors','investors',[c('generous','形容词','前置定语','investors','慷慨描述态度，不直接等于有钱。'),c('investors','复数名词','角色中心','接在题干be后作表语','投资者是资本角色。')],['modifier','complement'],'慷慨的投资者。','有财富不等于慷慨，更不等于需要出资救助公司。'),
 B:p('201122-B-analysis','unbiased executives','executives',[c('unbiased','形容词','前置定语','executives','没有偏见、公正。'),c('executives','复数名词','角色中心','接在题干be后作表语','经营管理人员，与advisers的建议角色不同。')],['modifier','complement'],'公正的经营管理人员。','一个修饰词贴近原文，不能掩盖中心角色被改换。'),
 C:p('201122-C-analysis','share price forecasters','forecasters',[c('share price','名词短语','前置定语','forecasters','股价；share此处为名词股票。'),c('forecasters','复数名词','角色中心','接在题干be后作表语','进行预测的人。')],['modifier','complement'],'股价预测者。','share price共同限定预测对象，不是三项并列职位。'),
 D:p('201122-D-analysis','independent advisers','advisers',[c('independent','形容词','前置定语','advisers','能自主判断、不受管理层利益牵制。'),c('advisers','复数名词','角色中心','接在题干be后作表语','提供建议的人。')],['modifier','complement'],'独立顾问。','independent与正文independence为词族转换；adviser与executive不混用。')
}},
23:{prompt:a('201123-prompt-analysis',"According to the researchers from Ohio University, after an outside director's surprise departure, the firm is likely to____.",'the firm is likely to____.',[
 c('According to the researchers from Ohio University','介词结构','依据状语','整句','依据研究人员发现。',[c('from Ohio University','介词短语','后置定语','researchers','大学所属，不修饰depart。')]),c("after an outside director's surprise departure",'介词短语','时间背景状语','is likely','在外部董事意外离任之后；surprise前置限定departure。'),c('the firm','名词短语','主语','is','被离开的原公司。'),c('is','系动词','谓语','the firm','与likely构成可能性结构。'),c('likely to____','形容词短语','表语','is','to后填动词原形短语，不填完整新主语。')],['modifier','modifier','subject','predicate','complement'],'根据俄亥俄大学研究人员的发现，外部董事意外离任后，该公司可能怎样？','题干已经提供主语和to，选项是接续动词短语；likely保留概率。'),options:{
 A:p('201123-A-analysis','become more stable','become more stable',[c('become','系动词原形','待接不定式的动词','题干to','表示变得。'),c('more stable','形容词比较级短语','表语','become','更加稳定，而不是绝对没有风险。')],['predicate','complement'],'变得更加稳定。','与题干组合为to become；稳定修饰公司。'),
 B:p('201123-B-analysis','report increased earnings','report increased earnings',[c('report','动词原形','待接不定式的动词','题干to','报告财务结果。'),c('increased earnings','名词短语','宾语','report','increased前置限定earnings，表示更高的盈利。')],['predicate','object'],'报告增长了的盈利。','increased修饰盈利，命题是盈利增加，非重述概率增加。'),
 C:p('201123-C-analysis','do less well in the stock market','do less well',[c('do','动词原形','待接不定式的动词','题干to','do在此表表现如何。'),c('less well','副词比较短语','表现程度状语','do','较不理想，与worse对应。'),c('in the stock market','介词短语','领域状语','do less well','在股票市场表现上。')],['predicate','modifier','modifier'],'在股票市场表现较差。','well修饰do为副词，less well保留比较，不能改成完全崩盘。'),
 D:p('201123-D-analysis','perform worse in lawsuits','perform worse',[c('perform','动词原形','待接不定式的动词','题干to','表现。'),c('worse','副词比较级','表现程度状语','perform','badly的比较级。'),c('in lawsuits','介词短语','领域状语','perform','把表现领域设为官司诉讼。')],['predicate','modifier','modifier'],'在诉讼中表现更差。','领域从股票换成诉讼，不能因perform worse复现就选。')
}},
24:{prompt:a('201124-prompt-analysis','It can be inferred from the last paragraph that outside directors____.','It can be inferred that outside directors____.',[
 c('It','形式主语','主语','can be inferred','先占主语位置，真正待推断内容在that从句。'),c('can be inferred','情态被动结构','谓语','It','可以推断，要求原文依据，不问常识。'),c('from the last paragraph','介词短语','信息来源状语','inferred','限定末段。'),c('that outside directors____','待补全内容从句','外置主语从句','形式主语It','选项补出outside directors的谓语内容。')],['subject','predicate','modifier','subject'],'从末段可以推断外部董事怎样？','形式主语It不指某家公司；that从句是推断内容。',[{text:'that outside directors____',type:'外置主语从句（待补全）',marker:'that',role:'与形式主语It对应的真正内容',subject:'outside directors',predicate:'____',predicateDetails:[],translationOrder:'先译可以推断，再接董事的待选行为。'}]),options:{
 A:p('201124-A-analysis','may stay for the attractive offers from the firm','may stay',[c('may stay','情态动词加动词原形','待接主语的谓语','题干outside directors','可能留下，may限制确定程度。'),c('for the attractive offers from the firm','介词短语','原因状语','may stay','为了公司提供的有吸引力的条件。',[c('from the firm','介词短语','后置定语','offers','说明条件来自公司；offers是名词复数。')])],['predicate','modifier'],'可能因公司提供有吸引力的条件而留下。','for说明留任诱因，may不保证所有董事都接受。'),
 B:p('201124-B-analysis','have often had records of wrongdoings in the firm','have had records',[c('have often had','现在完成时结构','待接主语的谓语','题干outside directors','have为完成标记，had为实义动词拥有；often表经常。'),c('records of wrongdoings in the firm','名词短语','宾语','had','声称董事有公司内违规记录。',[c('of wrongdoings in the firm','介词短语','记录内容补足语','records','违规行为记录，而非单纯在任记录。')])],['predicate','object'],'常有在该公司违规的记录。','选项把在任推进到有违规记录，是不同命题。'),
 C:p('201124-C-analysis','are accustomed to stress-free work in the firm','are accustomed',[c('are','系动词','待接主语的谓语','题干outside directors','连接状态。'),c('accustomed to stress-free work in the firm','形容词短语','表语','are','习惯公司的无压力工作。',[c('to stress-free work in the firm','介词短语','形容词补足语','accustomed','to后work为名词，不能按不定式处理。')])],['predicate','complement'],'习惯在公司从事无压力的工作。','be accustomed to后接名词或doing；此处work有stress-free形容词修饰。'),
 D:p('201124-D-analysis','will decline incentives from the firm','will decline incentives',[c('will decline','情态将来结构','待接主语的谓语','题干outside directors','decline及物为拒绝，不是下降。'),c('incentives from the firm','名词短语','宾语','decline','公司给出的激励条件。')],['predicate','object'],'将拒绝公司的激励。','decline直接带incentives宾语，选择拒绝义。')
}},
25:{prompt:a('201125-prompt-analysis',"The author's attitude toward the role of outside directors is____.","The author's attitude is____.",[
 c("The author's attitude toward the role of outside directors",'名词短语','主语','is','中心attitude，不是紧邻系动词的directors。',[c('toward the role of outside directors','介词短语','态度对象补足语','attitude','问对外部董事角色的态度，不是对校园人气的态度。')]),c('is','系动词','谓语','attitude','单数is与attitude一致。'),c('____','待填形容词','表语','is','用态度形容词补足。')],['subject','predicate','complement'],'作者对外部董事角色持什么态度？','先锁定态度对象是角色与履职，再比较正负和程度。'),options:{
 A:p('201125-A-analysis','permissive','permissive',[c('permissive','形容词','待填表语','题干is','宽容放任、容许行为的态度。')],['complement'],'宽容放任的。','permissive含允许、放任，不等于客观分析。'),
 B:p('201125-B-analysis','positive','positive',[c('positive','形容词','待填表语','题干is','积极肯定的态度。')],['complement'],'积极肯定的。','在态度语境不是检测阳性或数学正数。'),
 C:p('201125-C-analysis','scornful','scornful',[c('scornful','形容词','待填表语','题干is','带轻蔑、看不起的情绪。')],['complement'],'轻蔑的。','比理性提出批评更强，须有明确语气证据。'),
 D:p('201125-D-analysis','critical','critical',[c('critical','形容词','待填表语','题干is','指出问题并评判不足。')],['complement'],'批评的。','态度义为批评，不能取危急的或关键的常见另一义。')
}}
};
