import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";

const rows: LexiconRow[] = [
  ["tend", "tends tended tending", "v.", "往往；倾向于", "tend to think表通常的历史印象，不是每位读者都必然如此。", "tend to think（往往认为）", "tend后接不定式，语气保留倾向。"],
  ["think", "thought thinks thinking", "v.", "认为；看作", "think of A as B把战后几十年看作繁荣发展时期。", "think of A as B（把A看作B）", "of引评价对象，as引所作评价。"],
  ["decade", "decades", "n.", "十年；十年时期", "the decades immediately following World War II为二战后紧接的几十年。", "postwar decades（战后的几十年）", "复数decades不代表原文给出精确结束年份。"],
  ["immediately", "", "adv.", "紧接着；立即", "修饰following，限定年代紧随二战之后。", "immediately following World War II（紧接二战之后）", "本句不是一……就……的连词用法。"],
  ["follow", "following follows followed", "v.（现在分词）", "接在……之后", "following World War II后置限定decades，说明所谈年代。", "the decades following the war（战争之后的几十年）", "不是主句的有限谓语；题目the following另指下列选项。"],
  ["world", "worlds", "n.（名称组成）", "世界", "World War II为第二次世界大战名称，整体用于年代定位。", "World War II（第二次世界大战）", "不能由名称中的world泛化所有国家住宅情况。"],
  ["war", "wars", "n.", "战争", "World War II及后文the war指二战，提供战前战后的参照。", "before World War II（第二次世界大战之前）", "before限定移居时间，不是战争改变理念的因果。"],
  ["ii", "", "Roman numeral", "二（罗马数字）", "World War II中标识第二次世界大战。", "World War II（第二次世界大战）", "不是英文字母词位或第一人称代词。"],
  ["time", "times", "n.", "时期；时代", "a time of后接该时期的社会状态或心理观念。", "a time of prosperity and growth（繁荣发展的时期）", "不是倍数times，也不表示具体钟点。"],
  ["prosperity", "", "n.", "繁荣", "与growth并列，描述通常所见的战后总体时代背景。", "prosperity and growth（繁荣与发展）", "时代背景与But后住宅的节制观念要区分。"],
  ["growth", "", "n.", "发展；增长", "prosperity and growth概括战后时代印象。", "prosperity and growth（繁荣与发展）", "没有给出具体增长率，不能自行量化。"],
  ["home", "", "adv.", "回家；到家", "returning home中home为方向副词，不必加to。", "return home（返乡；回家）", "home不是此处另一个居住房屋名词宾语。"],
  ["million", "millions", "n.（数量单位）", "百万", "by the millions表示返乡士兵数以百万计。", "by the millions（数以百万计地）", "这是概数规模，不是某个精确人数。"],
  ["go", "going goes went gone", "v.（现在分词）", "去；前往", "going off to college与returning、lining并列，动作主体均为士兵。", "go off to college（去上大学）", "to college为学习去向，on the G. I. Bill说明资助依据。"],
  ["bill", "bills", "n.（法案名称组成）", "法案", "G. I. Bill在文中指为退伍军人提供教育等支持的法案。", "the G. I. Bill（退伍军人法案）", "此处是既有名称，不把Bill译成人名或账单。"],
  ["marriage", "marriages", "n.", "婚姻；结婚", "marriage bureaus指婚姻登记机构，士兵排队登记。", "marriage bureaus（婚姻登记处）", "marriage前置限定机构用途。"],
  ["belief", "beliefs", "n.", "信念；看法", "belief后内容从句解释少即是多或自给自足的理念。", "a belief that less can be more（少可以胜过多的信念）", "that解释具体内容，不代替从句内主语。"],
  ["learn", "learned learnt learns learning", "v.", "学会；得知", "正文had learned to live with less指先前学会节俭，题干learn about询问可得知内容。", "learn to live with less（学会用更少资源生活）", "to do与about话题结构按当前来源区分。"],
  ["live", "lives lived living", "v.", "生活", "live with less为在较少物质条件下生活；efficient living指高效生活方式。", "live with less（以更少资源生活）", "正文live是动词原形，living是活动名词化形式，不是形容词活着的。"],
  ["postwar", "", "adj.", "战后的", "限定住宅风格或对未来的信心，指二战之后。", "postwar confidence（战后的信心）", "postwar只定位时期，不自动表示财富或房屋面积增加。"],
  ["confidence", "", "n.", "信心", "the postwar confidence in the future为战后对未来的信心，与节制共同塑造住宅风格。", "confidence in the future（对未来的信心）", "信心与faithfulness忠诚不同。"],
  ["future", "futures", "n.", "未来", "可为信心所指的未来，也为新材料当年象征的未来。", "symbolize the future（象征未来）", "未来是人们当时的想象方向，不是原文保证的具体技术实现。"],
  ["make", "made makes making", "v.", "使……变得", "made housing stylish为使役宾补结构，housing受影响，stylish为结果状态。", "make housing stylish（使住宅成为时尚）", "made为过去式，不能把它与形容词stylish合为不可分谓语块。"],
  ["small", "smaller smallest", "adj.", "小的；较小的", "小型住宅仍可高效优雅；smaller比较两组同类公寓面积。", "small and efficient spaces（小而高效的空间）", "small不等于拥挤或缺少优雅。"],
  ["efficient", "", "adj.", "高效的；利用合理的", "形容住宅和生活方式，强调较少空间与资源的合理利用。", "efficient housing（高效实用的住宅）", "是住宅功能特点，不等于塑造它的节制与信心两种心理。"],
  ["economic", "", "adj.", "经济的", "修饰condition，说明经济条件只是设计趋势的一项推动力。", "economic condition（经济条件）", "原卷condition为单数，保留原文，不改造词汇例证为其他题目。"],
  ["condition", "conditions", "n.", "条件；状况", "Economic condition为单数主语，与was一致。", "economic condition（经济状况）", "只说明推动因素之一，不能扩大成唯一原因。"],
  ["trend", "trends", "n.", "趋势；潮流", "toward efficient living或toward less说明住宅趋向简约高效。", "the trend toward efficient living（高效生活的趋势）", "趋势的外来与本土来源并存。"],
  ["phrase", "phrases", "n.", "说法；格言", "less is more这句话由引语说明内容，是密斯标志性表述。", "a signature phrase（标志性表述）", "推广phrase不等于创建设计学校。"],
  ["german", "germans", "n.", "德国人", "a German为一个德国人，同位语进一步说明是建筑师密斯。", "a German architect（一位德国建筑师）", "原句German前有a，作可数国民名词。"],
  ["person", "people persons", "n.", "人；人员", "other people associated with the Bauhaus指其他与包豪斯有关的人。", "people associated with the Bauhaus（与包豪斯有关的人）", "有关联不必然等于全是毕业生或创办者。"],
  ["school", "schools", "n.", "学校；院校", "a school of design解释包豪斯，architecture schools是赴美任教的建筑院校。", "architecture schools（建筑院校）", "须区分被介绍的学校与美国的任教机构。"],
  ["design", "designed designs designing", "n. / v.", "设计；构思建造", "名词说明建筑设计，designed作动词说明建筑师设计空间或住宅。", "architectural design（建筑设计）", "design与designer、designing及形容词architectural按实际句法区分。"],
  ["united", "", "adj.（国名组成）", "联合的（美国名称组成）", "the United States作为固定国名指美国。", "the United States（美国）", "在国名中整体识别，不把United当主句被动分词。"],
  ["state", "states", "n.（国名组成）", "州（美国名称组成）", "States在the United States中为复数国名成分，指赴美目的地。", "the United States（美国）", "不取国家补贴的the state或状态义。"],
  ["exert", "exerted exerts exerting", "v.", "产生；施加", "exert enormous influence指设计师对美国建筑发展发挥巨大影响。", "exert influence on architecture（影响建筑发展）", "及物动词直接接influence；on再引影响对象。"],
  ["enormous", "", "adj.", "巨大的", "限定influence，形容相关设计师在美国建筑中的影响程度。", "enormous influence（巨大影响）", "程度大不等于所有建筑师都与包豪斯有关。"],
  ["influence", "influences", "n.", "影响；推动力", "作exert/have宾语或表语，说明设计师、项目对建筑潮流的作用。", "influence on architecture（对建筑的影响）", "此处为名词，不能按被动be influenced拆解。"],
  ["properly", "", "adv.", "恰当地；合理地", "修饰organized，说明少量装饰发挥效果需合理安排。", "properly organized（安排得当的）", "条件不能漏掉，不能推出任意减少装饰都更优雅。"],
  ["believe", "believed believes believing", "v.", "认为；相信", "he believed为插入引述语，标明观点属于密斯。", "he believed（他认为）", "过去式believed不是表示确信的形容词。"],
  ["modern", "", "adj.", "现代的；现代派的", "修饰architects，指采用现代建筑理念的设计师。", "modern architects（现代建筑师）", "讨论历史中的现代建筑设计，不等于叙述今天所有建筑师。"],
  ["grant", "granted grants granting", "v.（固定搭配分词）", "视为理所当然（take for granted）", "take materials for granted表示如今对这些材料习以为常。", "take for granted（视为寻常）", "granted不是获批材料，须连同take与for理解。"],
  ["today", "", "adv.", "今天；如今", "与1940年代比较，说明现在已把这些材料视为寻常。", "take for granted today（如今习以为常）", "不能把今天的常见程度移回当年。"],
  ["fact", "facts", "n.", "事实", "that从句解释空间小而高效这一事实，内部还有限定spaces的关系从句。", "mask the fact that（掩盖……事实）", "内容从句不缺主宾，that不代替spaces。"],
  ["big", "bigger biggest", "adj.", "大的；宽大的", "big and often empty是rather than排除的空间描述。", "big and often empty（宽大却常显空洞）", "与small and efficient平行对比，不把宽大视为优雅必要条件。"],
  ["build", "built builds building", "v.", "建造", "built可作定语从句过去式或题目被动分词；started building中为动名词。", "build houses（建造住宅）", "build动词与building建筑物名词按来源保持独立词位。"],
  ["example", "examples", "n.", "例子", "for example把芝加哥公寓作为密斯设计的实例引入。", "for example（例如）", "作插入篇章标记，不是were的宾语。"],
  ["popular", "", "adj.", "受欢迎的；流行的", "主句popular说公寓受欢迎，后置popular说当时抽象艺术流行。", "art popular at the time（当时流行的艺术）", "题目将popular挂到materials，必须检查修饰对象。"],
  ["equivalent", "equivalents", "n.", "对应物；相应表现", "architectural equivalent指抽象艺术在建筑形式中的对应。", "the architectural equivalent of abstract art（抽象艺术在建筑中的对应表现）", "共同形式特点不等于同一实体。"],
  ["art", "arts", "n.", "艺术", "abstract art为抽象艺术，也是建筑形式的类比对象；Arts还用于杂志名称。", "abstract art（抽象艺术）", "at the time限定当时流行的艺术，不是材料。"],
  ["foreign", "", "adj.", "外来的；来自外国的", "not entirely foreign承认美国简约趋势还包含本土源流。", "not entirely foreign（并非完全外来的）", "部分否定不能变成完全本土或全为外来。"],
  ["start", "started starts starting", "v.", "开始", "started building说明赖特30年代转向较适度高效住宅。", "start building houses（开始建造住宅）", "building后接houses，是动作的动名词而非楼房名词。"],
  ["early", "", "adj.", "早期的；初期的", "the early 20th century指20世纪初，和1890年代并列。", "the early 20th century（20世纪初）", "限定赖特较早设计的时期，不修饰1930年代新住宅。"],
  ["century", "centuries", "n.", "世纪", "20th century为20世纪，early给其初期范围。", "the early 20th century（20世纪初）", "序数20th和年代表达1930s不能互换。"],
  ["case", "cases", "n.（项目名称组成）", "案例", "Case Study Houses为项目名，指委托建筑师设计的一批住宅。", "Case Study Houses（案例研究住宅）", "不取诉讼案件义，与Study/Houses合看名称。"],
  ["study", "studies", "n.（项目名称组成）", "研究", "Case Study Houses为设计项目名，Study不在此作谓语。", "Case Study Houses（案例研究住宅）", "不能按命令式研究房子去拆原文主语。"],
  ["california", "", "proper n.", "加利福尼亚", "标明《艺术与建筑》杂志的地域，杂志为项目委托者。", "California Arts & Architecture magazine（加利福尼亚《艺术与建筑》杂志）", "by引杂志，不是设计提供者建筑师。"],
  ["effect", "effects", "n.", "效果", "Aesthetic effect指审美效果，来源包括景观、材料与细部。", "aesthetic effect（审美效果）", "名词effect与动词affect影响不同。"],
  ["new", "", "adj.", "新的；新型的", "限定materials，只提供新型属性，不证明环保。", "new materials（新材料）", "new与eco-friendly不是同义改写。"],
  ["mechanical", "", "adj.", "机械技术的", "mechanical revolution/devices讨论技术设备对日常生活的影响。", "mechanical devices（机械设备）", "不取机械死记硬背的比喻义。"],
  ["everyday", "", "adj.", "日常的", "everyday life为日常生活，形容词前置修饰life。", "everyday life（日常生活）", "everyday一词为形容词，every day两词常表每天。"],
  ["life", "lives", "n.", "生活", "机械技术将怎样改变everyday life，是Rapson预测的内容。", "everyday life（日常生活）", "这里是生活方式，不指某一个人的生物生命。"],
  ["family", "families", "n.", "家庭", "few American families和most对比两类设备的家庭普及程度。", "American families（美国家庭）", "few指直升机，most承接家庭并转为干衣机，不能合并范围。"],
  ["eventually", "", "adv.", "最终", "修饰got，说明大多数家庭后来最终获得干衣机。", "eventually got clothes dryers（最终拥有干衣机）", "表示结果时间而非频率经常。"],
  ["inevitable", "", "adj.", "不可避免的；必然的", "与desirable并列，表示Rapson对自给自足趋势的判断。", "desirable and inevitable（可取且不可避免的）", "这是信念中的评价，别写成已由事实证明所有家庭实现自给自足。"],
  ["style", "styles", "n.", "风格", "postwar American housing style为题干主语，询问其反映的心态。", "housing style（住宅风格）", "中心style不是Americans；题目宾语才问美国人的心理。"],
  ["largely", "", "adv.", "主要地；在很大程度上", "修饰reflected，要求住宅风格主要体现哪种心理。", "largely reflected（主要体现）", "保留主要程度，不作唯一原因断言。"],
  ["efficiency", "", "n.", "效率；高效性", "形容住宅使用资源的特征，题目也用它讨论优雅与实用的关系。", "efficiency and practicality（效率与实用性）", "心理原因restraint/confidence与设计特征有不同层级。"],
  ["pride", "", "n.", "自豪", "选项pride and faithfulness提出自豪与忠诚两种心理。", "pride and faithfulness（自豪与忠诚）", "原文没有这组共同原因；不要加入骄傲自负的贬义。"],
  ["infer", "inferred infers inferring", "v.（过去分词）", "推断", "can be inferred要求根据第三段推断包豪斯作用。", "infer from Paragraph 3（根据第三段推断）", "结合相关设计师传播影响，不能添加创办者等未给事实。"],
  ["paragraph", "paragraphs", "n.", "段落", "Paragraph 3限定学校影响题的证据范围。", "Paragraph 3（第三段）", "按原卷段落边界，不依屏幕换行。"],
  ["concept", "concepts", "n.", "理念；概念", "Its designing concept为选项主语，指包豪斯设计理念。", "designing concept（设计理念）", "被二战影响是选项新增的因果命题，原文只给移居时间。"],
  ["affect", "affected affects affecting", "v.（过去分词）", "影响", "was affected by World War II为被动，声称理念受到战争影响。", "be affected by war（受到战争影响）", "by原因来源与before时间关系不同。"],
  ["use", "used uses using", "v.", "过去曾；使用", "used to be associated表示过去曾有关联；were used表示设备被使用。", "used to be associated with（过去曾与……有关）", "先看to或被动助动词，区分习惯结构与实义使用。"],
  ["great", "greater greatest", "adj.", "巨大的", "a great influence概括设计师对美国建筑影响的程度。", "a great influence（巨大影响）", "对应enormous，不表示每位建筑师都曾就读该校。"],
  ["relate", "related relates relating", "v.（分词）", "有关联", "was related to large space声称优雅与大空间相关。", "be related to large space（与大空间有关）", "to为介词，后接名词space。"],
  ["large", "larger largest", "adj.", "大的；宽大的", "large space指大空间，选项将它与优雅相连。", "large space（大空间）", "原文小空间仍可优雅，不以通透效果代替面积。"],
  ["true", "", "adj.", "属实的；正确的", "What is true要求选符合原文的公寓事实。", "What is true about the apartments（关于公寓哪一项属实）", "true为is表语，不是truly副词。"],
  ["ignore", "ignored ignores ignoring", "v.", "忽视", "They ignored details and proportions声称设计忽略细部比例。", "ignore details（忽视细部）", "核对原文恰把细部比例列作优雅来源。"],
  ["characteristic", "characteristics", "n.", "特点；特征", "some characteristics of abstract art指建筑与抽象艺术相应的部分特点。", "characteristics of abstract art（抽象艺术的特点）", "some限制范围，不说建筑与画作完全一致。"],
  ["natural", "", "adj.", "自然的", "Natural scenes对应景观landscape，指住宅周边自然景色。", "natural scenes（自然景观）", "没有自然选择的生物学含义。"],
  ["consideration", "considerations", "n.", "考虑", "be taken into consideration表示被纳入设计考虑。", "take into consideration（纳入考虑）", "与take搭配作被动时，所考虑对象放在主语位置。"],
  ["overall", "", "adj.", "整体的", "限定effect，选项声称为了整体效果而牺牲细部。", "the overall effect（整体效果）", "原文细部本是美感来源，不能假定整体与细节必然冲突。"],

  ["stem", "stems stemmed stemming", "v.", "源自；由……产生", "stem from说明来源，可用于替换derive from，必须保留介词from。", "stem from simplicity（源自简洁）", "stem from比derive from稍口语，两者此处都表达来源而非造成结果。"],
  ["soldier", "soldiers", "n.", "士兵；军人", "战后士兵返乡、入学与结婚共同构成繁荣时代背景。", "returning soldiers（返乡军人）", "soldier为军人，veteran特指有服役经历者，不能一概任意替换。"],
  ["return", "returning returned returns", "v.", "返回", "returning home为with结构中的第一项分词动作，主语是soldiers。", "return home（回家）", "returning在with结构里说明士兵返回家乡。"],
  ["college", "colleges", "n.", "大学；高等院校", "go off to college指军人借助法案资助入大学读书。", "go to college（上大学）", "college不等于中学school，原文不限定某一大学。"],
  ["line", "lining lined lines", "v.", "排队（与up连用）", "lining up为士兵在婚姻登记机构排队的并列动作。", "line up（排队）", "此处为排队的动词；line去e加ing为lining。"],
  ["bureau", "bureaus bureaux", "n.", "办事机构；登记处", "marriage bureaus为婚姻登记机构，士兵在此排队结婚。", "marriage bureaus（婚姻登记处）", "同词随修饰语改变具体机构类型，bureaus和bureaux均为复数。"],
  ["house", "houses", "n.", "住宅；房屋", "全文讨论居住建筑，Case Study Houses为项目名称。", "efficient houses（高效实用的住宅）", "不是议院House；house名词与housing住房集合概念分别保留。"],
  ["common", "", "adj.", "常识性的；共同认可的", "common sense整体指务实判断，而不是某种普遍感官。", "common sense（常识；务实判断）", "不能把common单独译成普通而漏掉固定搭配。"],
  ["sense", "senses", "n.", "理性判断；常识", "common sense说明住宅取向讲求实用与节制。", "common sense（常识）", "与a sense of security安全感、word sense词义不同。"],
  ["truly", "", "adv.", "真正地；确实", "修饰could be more，加强少而精可带来更强效果的信念。", "truly effective（确实有效的）", "副词truly修饰判断，不是形容词true直接修饰名词。"],
  ["depression", "depressions", "n.", "经济大萧条", "the Depression特指文中战前的经济萧条时期，与the war并列。", "during the Depression（在经济大萧条时期）", "不同于心理抑郁或地表凹陷义。"],
  ["restraint", "restraints", "n.", "节制；克制", "that restraint回指学会用较少物质资源生活，是31题关键词。", "restraint in design（设计中的节制）", "与外部restriction限制不同，此处偏主动克制。"],
  ["combination", "combinations", "n.", "结合；组合", "in combination with说明节制与信心共同作用。", "in combination with（与……结合）", "不是把两个概念说成完全相同。"],
  ["housing", "", "n. uncountable", "住房；住宅设计", "small, efficient housing作为make的宾语，指一类居住建筑。", "efficient housing（高效利用空间的住房）", "housing作为集合名词独立于house单栋住宅，不能一律合并。"],
  ["positively", "", "adv.", "非常；确实", "positively stylish强调十分时髦，不是在谈肯定回答或正电荷。", "positively stylish（确实很时髦）", "副词修饰stylish，而不是说明人们对经济持积极态度。"],
  ["stylish", "", "adj.", "时髦的；有格调的", "made housing stylish中作宾语补足语。", "stylish housing（时髦的住宅）", "有风格不必依赖繁多装饰，正是文章主题。"],
  ["stimulus", "stimuli", "n.", "刺激因素；推动力", "经济状况只是高效生活趋势的一项推动因素。", "a stimulus for change（推动变化的因素）", "复数stimuli不规则；only提示不能作唯一原因解释。"],
  ["actually", "", "adv.", "实际上", "引出少即是多理念传播的事实，对只从经济条件理解作补充。", "actually originated elsewhere（实际上起源于别处）", "不同于currently目前，不是单纯时间词。"],
  ["popularize", "popularized popularizes popularizing", "v.", "推广；使广为人知", "was first popularized强调首先推广，不断言首次创造格言。", "popularize an idea（推广一种观念）", "与invent发明、found创建区别，32题不可偷换。"],
  ["architect", "architects", "n.", "建筑师", "Mies、Wright和Rapson均以建筑设计者身份出现。", "modern architects（现代建筑师）", "architect职业名词与architecture建筑学、architectural建筑的为词族而非屈折。"],
  ["associate", "associated associates associating", "v.", "联系；使有关联", "people associated with the Bauhaus中分词短语限定与该校有关的人。", "be associated with a school（与某所学校有关联）", "有关联不必然意味着创建、毕业或成为该校多数人群。"],
  ["emigrate", "emigrated emigrates emigrating", "v.", "移居国外", "emigrate to the United States从原居国视角说移居美国。", "emigrate to another country（移居另一个国家）", "immigrate从迁入国视角说移民；to引目的地。"],
  ["post", "posts", "n.", "职位；职务", "take up posts at schools指在建筑院校开始任职。", "take up a post（开始任职）", "不是邮政、柱子或网络帖子义。"],
  ["architecture", "", "n.", "建筑；建筑学", "American architecture为美国建筑发展，architecture schools为建筑院校。", "the course of architecture（建筑的发展进程）", "不可数领域名词，不是某一栋building。"],
  ["designer", "designers", "n.", "设计师", "These designers回指与包豪斯有关并移居美国的人。", "modern designers（现代设计师）", "与design设计动词和设计方案名词分开计数。"],
  ["course", "courses", "n.", "发展进程；走向", "the course of American architecture讨论建筑史演进，不是某门课程。", "the course of development（发展的进程）", "同词也有课程、路线、一餐中的一道菜等义。"],
  ["signature", "signatures", "n. attributive", "标志性的；代表性的", "signature phrase指密斯最具代表性的格言，不是签名用的一句话。", "a signature phrase（标志性表述）", "signature名词本义签名；前置修饰可表示独有特色。"],
  ["mean", "means meant meaning", "v.", "意味着；意思是", "phrase means that解释格言含义，means是第三人称单数动词。", "a phrase means that（某句话意味着）", "means后接that内容从句，按动词mean理解。"],
  ["decoration", "decorations", "n.", "装饰", "less decoration与a lot of decoration比较的是装饰数量而非住宅面积。", "abundant decoration（大量装饰）", "与detailing细部处理不完全相同，细部可简洁且不堆砌装饰。"],
  ["organize", "organized organizes organizing", "v.", "组织；安排", "properly organized为装饰经过合理布局的被动分词说明。", "properly organized decoration（安排得当的装饰）", "不是成立组织，重点在构成方式。"],
  ["impact", "impacts impacted impacting", "n. / v.", "效果；影响", "第7句has more impact中为名词效果；末句would impact life中为及物动词影响。", "have an impact（产生影响）", "名动同形必须按句法位置区分，不把would后的impact标成名词。"],
  ["lot", "lots", "n.", "大量（a lot）", "than a lot省略of decoration，比较大量装饰。", "a lot of decoration（大量装饰）", "不是拍卖批次或地块义；不能省略其指代对象。"],
  ["elegance", "", "n.", "优雅；雅致", "建筑形式的审美品质，并不依赖装饰堆积。", "architectural elegance（建筑的优雅）", "elegant为形容词，elegance为独立派生名词。"],
  ["derive", "derives derived deriving", "v.", "源于；来自", "derive from abundance被否定，说明优雅不源于数量繁多。", "derive from simplicity（源于简洁）", "与cause造成方向相反；from引来源。"],
  ["abundance", "", "n.", "丰富；大量", "abundance回指装饰上的堆叠丰繁，不是住宅所有者财富。", "an abundance of decoration（大量装饰）", "abundant为形容词，两者不合并原形次数。"],
  ["employ", "employed employs employing", "v.", "采用；使用", "employ metal, glass and laminated wood指选用建筑材料。", "employ new materials（采用新材料）", "employ人可表示雇用，接材料时不能译成聘用。"],
  ["metal", "metals", "n.", "金属", "与glass、wood并列作employed宾语，为材料名词。", "metal and glass（金属和玻璃）", "不是形容词metallic，材料名词可直接构成名词定语。"],
  ["glass", "glasses", "n.", "玻璃", "建筑材料的不可数用法，glass walls中前置作材料定语。", "glass walls（玻璃墙）", "复数glasses常指眼镜或多个杯子，本文不能这样理解。"],
  ["laminated", "", "adj.", "层压的；多层黏合的", "laminated wood为经过层压加工的木材。", "laminated wood（层压木材）", "区别于整块实木；材料新型不自动等于环保。"],
  ["wood", "woods", "n.", "木材", "wood在材料清单中不可数，laminated说明加工方式。", "wood as a building material（作为建材的木材）", "woods复数可指树林，本文不是种树或林地。"],
  ["material", "materials", "n.", "材料", "同位概括metal、glass和wood，后接两个平行定语从句。", "new materials（新材料）", "new说明新型，不证明eco-friendly环保。"],
  ["symbolize", "symbolized symbolizes symbolizing", "v.", "象征；代表", "新材料在20世纪40年代象征未来，与today习以为常对照。", "symbolize the future（象征未来）", "symbolize不是已经成为未来的实物，而是承载象征意义。"],
  ["sophisticated", "", "adj.", "精巧的；讲究的", "修饰presentation，强调设计呈现的高明。", "sophisticated design（精巧设计）", "不取人世故圆滑义，也不必译为装饰复杂繁多。"],
  ["presentation", "presentations", "n.", "呈现方式；表现手法", "Mies's presentation指建筑外在效果，而非幻灯片演示。", "architectural presentation（建筑呈现方式）", "present作动词展示与presentation名词分开计数。"],
  ["mask", "masked masks masking", "v.", "掩盖；遮蔽", "精巧的呈现掩盖空间其实小而实用的事实。", "mask the fact that（掩盖……事实）", "动词比喻遮住认知焦点，不是口罩名词。"],
  ["space", "spaces", "n.", "空间", "the spaces he designed为室内可用空间，spaces可数指不同区域。", "efficient use of space（高效利用空间）", "不是宇宙太空，也不能仅凭small断言拥挤。"],
  ["empty", "emptier emptiest", "adj.", "空的；空荡的", "big and often empty是被rather than排除的空间状态。", "empty space（空荡的空间）", "并非少即是多就等于空无一物。"],
  ["apartment", "apartments", "n.", "公寓住宅", "towers中的居住单元，比较对象仍为邻楼中的公寓。", "a two-bedroom apartment（一套两居室公寓）", "apartment是一户住房，不等于整座tower。"],
  ["elegant", "", "adj.", "优雅的；雅致的", "elegant towers说明楼宇审美，与住宅面积大小分开判断。", "elegant towers（优雅的高楼）", "优雅不必大而奢华，正是文章的反常识点。"],
  ["tower", "towers", "n.", "高层楼宇；塔楼", "Mies built的对象，公寓位于其中。", "apartment towers（高层公寓楼）", "不是单独一户公寓，也不是泛指年长邻居。"],
  ["drive", "drives", "n.", "大道；道路名称组成", "Lake Shore Drive为芝加哥道路名，本文不取驾驶动词。", "Lake Shore Drive（湖滨大道）", "Drive出现在道路专名中可表大道，Drive在此是名词，不作驾驶谓语。"],
  ["two-bedroom", "", "adj.", "有两间卧室的", "复合形容词限定units，bedroom保持单数。", "two-bedroom units（两居室单元）", "不是只有两个房间，卧室数不同于总房间数。"],
  ["unit", "units", "n.", "住宅单元；一套住房", "two-bedroom units指每套公寓，而非计量单位这个抽象概念。", "housing units（住宅单元）", "under 1,000 square feet是每套住房面积。"],
  ["square", "squares", "adj.", "平方的", "square feet组合为面积单位，不表示住宅形状是正方形。", "square feet（平方英尺）", "length feet是长度，square feet是面积，不可混算。"],
  ["foot", "feet", "n.", "英尺（长度单位）", "与square连用表示平方英尺，feet为不规则复数。", "one square foot（一平方英尺）", "不同于身体脚或山脚义，本文数字给出面积。"],
  ["old", "older oldest", "adj.", "较早建成的；旧的", "older neighbors指这些公寓楼附近更早的建筑，不是住户年龄。", "older buildings（较老的建筑）", "与elder年长的不同，older可修饰建筑。"],
  ["neighbor", "neighbors", "n.", "邻近建筑（拟人用法）", "their older neighbors在建筑比较中指相邻老楼。", "older neighbors（附近更老的楼宇）", "不能将those apartments与邻居这个人比较面积。"],
  ["along", "", "prep.", "沿着；位于……一带", "along the city's Gold Coast说明附近旧楼所在区域。", "along the coast（沿海岸一带）", "强调线状地域分布，而非穿过某物的through。"],
  ["city", "cities city's", "n.", "城市", "the city's Gold Coast中city指芝加哥，所有格限定区域。", "the city's buildings（这座城市的建筑）", "city's为所有格，不是复数cities。"],
  ["airy", "airier airiest", "adj.", "通透的；明亮开阔的", "airy glass walls说明玻璃墙带来的开放感。", "an airy room（通透明亮的房间）", "这里不是漫不经心、空想式的引申义。"],
  ["wall", "walls", "n.", "墙；墙面", "glass walls由玻璃构成，是公寓受欢迎的原因之一。", "glass walls（玻璃墙）", "不是文章中的城市壁垒或网络围墙比喻。"],
  ["view", "views", "n.", "视野；可见景观", "the views they afforded指公寓提供的外部视野，不是观点意见。", "views from an apartment（从公寓看到的景观）", "view还可表示看法，本文由afford及空间环境确定景观义。"],
  ["afford", "afforded affords affording", "v.", "提供；给予", "apartments afforded views指公寓提供景观视野，不是负担购买公寓的费用。", "afford a view（提供视野）", "afford to buy才常为买得起，两种结构须分开。"],
  ["building", "buildings", "n.", "建筑物", "the buildings' details and proportions为复数建筑的细部和比例。", "a building's details（一栋建筑的细部）", "另一个句子started building中building为build动名词，按来源分开归一。"],
  ["detail", "details", "n.", "细部；细节", "建筑细部的优雅是受欢迎原因，而非被忽略的部分。", "architectural details（建筑细部）", "detailing为细部处理这个过程或方式，属派生名词而不并为屈折。"],
  ["proportion", "proportions", "n.", "比例关系；尺度配比", "建筑细部和整体之间的协调比例，强调各部分协调的尺度关系。", "elegant proportions（优雅协调的比例）", "复数proportions常指形体各部分的尺度关系。"],
  ["architectural", "", "adj.", "建筑的", "architectural equivalent表示抽象艺术在建筑领域的对应表现。", "architectural design（建筑设计）", "派生形容词不同于architect建筑师和architecture建筑学。"],
  ["abstract", "", "adj.", "抽象的", "abstract art指文章用来类比建筑形式的艺术风格。", "abstract art（抽象艺术）", "不是论文摘要abstract的名词义。"],
  ["entirely", "", "adv.", "完全地", "not entirely foreign为部分否定，承认外来与本土两种来源。", "not entirely foreign（并非完全外来的）", "不能简化为完全不是外来的。"],
  ["modest", "", "adj.", "朴素的；适度的", "形容住宅规模和设计不奢张，非房屋具有谦虚人格。", "modest houses（朴素适度的住宅）", "modest修饰人可表谦逊，修饰规模常为不大的、适度的。"],
  ["usually", "", "adv.", "通常", "usually around 1,200 square feet限定典型面积，不作所有房屋准确数值。", "usually around that size（通常约为那个规模）", "usually和around都降低绝对精度，不能漏译。"],
  ["spread", "spreading spread spreads", "v.", "铺展；伸展开", "spreading分词修饰旧式大宅，强调占地展开。", "spreading houses（铺展开来的住宅）", "spread过去式与过去分词同形，本文是现在分词定语。"],
  ["two-story", "", "adj.", "两层的", "two-story限定ones所指的旧住宅，story为美式楼层表达。", "two-story houses（两层住宅）", "复合形容词story用单数，不译成两个故事。"],
  ["commission", "commissioned commissions commissioning", "v.", "委托设计或制作", "住宅由杂志向建筑师委托设计；from引受托方、by引委托者。", "commission a design（委托设计）", "commissioned以分词形式修饰住宅项目，说明委托关系。"],
  ["talented", "", "adj.", "有才华的", "修饰现代建筑师，说明杂志选择的受托设计者。", "talented architects（有才华的建筑师）", "与famous著名的不同，有才华不自动意味着人人知晓。"],
  ["magazine", "magazines", "n.", "杂志", "Arts & Architecture magazine是案例住宅项目的委托方。", "an architecture magazine（建筑杂志）", "不是建筑师协会，也不是住宅开发商的同义名称。"],
  ["homegrown", "", "adj.", "本土产生的", "homegrown influence指美国本土对简约趋势的推动。", "a homegrown influence（一项本土影响）", "与foreign相对，不是家庭自己种的植物。"],
  ["aesthetic", "", "adj.", "审美的；美学的", "aesthetic effect讨论作品美感来源，作effect前置定语。", "aesthetic effect（审美效果）", "不同于功能效率本身，本文展示二者可兼容。"],
  ["landscape", "landscapes", "n.", "景观；周围自然景色", "是案例住宅审美效果的来源，直接支撑35题自然景观。", "the surrounding landscape（周围景观）", "不是政治局势的比喻用法；没有自动推出所有材料环保。"],
  ["forthright", "", "adj.", "直白的；坦率展现的", "forthright detailing在设计语境指简洁直白、不刻意遮掩的细部表达。", "forthright detailing（直白的细部处理）", "不能把它误读为放弃细节，亦非建筑师脾气直率的描述。"],
  ["detailing", "", "n.", "细部设计；细节处理", "与landscape、materials并列作from宾语，指处理细部的方式。", "careful detailing（细致的细部处理）", "本文名词化建筑术语独立于detail具体细节，不混算词位。"],
  ["mispredict", "mispredicted mispredicts mispredicting", "v.", "预测失误；错估", "may have mispredicted对Rapson过去的技术预见提出保留判断。", "mispredict a change（错估某种变化）", "mis-表错误；may have保留可能性，不是断言全部理念错误。"],
  ["revolution", "revolutions", "n.", "革命；重大变革", "mechanical revolution指机械技术改变生活的趋势，不是政权更迭。", "the mechanical revolution（机械技术革命）", "范围由mechanical限定，不自动改成特定历史工业革命时期。"],
  ["acquire", "acquired acquires acquiring", "v.", "获得；购得", "few families acquired helicopters指很少家庭实际拥有直升机。", "acquire equipment（购置设备）", "与predict预测不同，acquire描述实际取得。"],
  ["helicopter", "helicopters", "n.", "直升机", "作为没有在家庭广泛普及的技术设想，受few否定量限定。", "family helicopters（家庭使用的直升机）", "不能把存在某些家庭获得读成普遍拥有。"],
  ["get", "got gets getting gotten", "v.", "获得；拥有", "got clothes dryers指多数家庭最终获得干衣机。", "get a clothes dryer（购得一台干衣机）", "不是get over克服的搭配义。"],
  ["clothes", "", "plural n.", "衣服", "clothes dryers中作名词定语说明干燥对象。", "clothes dryers（衣物干燥机）", "clothes通常以复数形式使用，不等于cloth布料的普通复数。"],
  ["dryer", "dryers", "n.", "干燥机", "clothes dryer为家用干衣设备，与未普及的直升机形成对照。", "a clothes dryer（一台干衣机）", "dryer是设备名词，不是形容词dry的比较级drier。"],
  ["self-sufficiency", "", "n.", "自给自足；自立自足", "是Rapson相信值得追求且必然到来的生活理想。", "a belief in self-sufficiency（对自给自足的信念）", "不等于隔绝社会或所有家庭必须自己制造一切。"],
  ["desirable", "", "adj.", "值得向往的；可取的", "与inevitable并列作self-sufficiency的表语，前者评价价值。", "a desirable goal（值得追求的目标）", "desirable可取与inevitable必然并非同义：价值判断与趋势判断不同。"],
  ["widely", "", "adv.", "广泛地", "widely shared说明信念被许多人认同，保留独立副词词条。", "a widely shared belief（广泛认同的信念）", "wide形容范围宽，widely副词表示广泛，不作为屈折合并。"],
  ["share", "shared shares sharing", "v.", "共同持有；认同", "belief was widely shared为被动，意为信念广受认同。", "share a belief（认同同一信念）", "不是股票名词share或分配实物，而是共同持有观点。"],
  ["reflect", "reflected reflects reflecting", "v.", "反映；体现", "31题问住宅风格体现怎样的国民心态。", "reflect an attitude（反映一种态度）", "此处不是光学反射或深思熟虑的reflect on。"],
  ["practicality", "", "n.", "实用性", "31题干扰项描述设计功能，不是原文明确并列的节制与信心。", "efficiency and practicality（效率与实用性）", "要区分住宅特征与产生特征的心理因素。"],
  ["faithfulness", "", "n.", "忠诚；忠实", "31题干扰项与pride并列，原文未提这两种心理。", "faithfulness to a principle（忠于某项原则）", "confidence对未来的信心不等于faithfulness忠诚。"],
  ["found", "founded founds founding", "v.", "创建；创立", "32题干扰项说Mies创立包豪斯，原文只说推广理念与该校有关。", "found a school（创建一所学校）", "founded是found创建的规则过去分词，不归入find发现。"],
  ["hold", "held holds holding", "v.", "认为；持有观点", "Mies held that询问他关于优雅来源的主张。", "hold that something is true（认为某事成立）", "held后接that观点从句，按认为理解。"],
  ["identify", "identified identifies identifying", "v.", "把……等同；联系", "be identified with emptiness为33题干扰项，把优雅等同空无。", "be identified with an idea（与某观念联系或等同）", "这里讨论概念关系，不是表明个人身份。"],
  ["emptiness", "", "n.", "空无；空荡", "33题错项将优雅与空洞等同，原文反而否定big and often empty。", "spatial emptiness（空间空荡）", "empty形容词与emptiness派生名词分开计数。"],
  ["reliant", "", "adj.", "依赖的", "not reliant on abundant decoration概括优雅不靠大量装饰。", "be reliant on decoration（依赖装饰）", "与dependent on相近，须保留not否定。"],
  ["abundant", "", "adj.", "丰富的；大量的", "abundant decoration为33题正确选项中被否定依赖的对象。", "abundant decoration（大量装饰）", "大量不必然精巧，原文强调安排是否得当。"],
  ["spacious", "", "adj.", "宽敞的", "34题more spacious与原文smaller相反。", "spacious apartments（宽敞的公寓）", "看起来优雅通透不等于实际面积比邻楼更大。"],
  ["neighboring", "", "adj.", "邻近的", "修饰34题buildings，指附近楼宇，不能据此改变原文面积对比方向。", "neighboring buildings（邻近建筑）", "neighboring为定语形容词，neighbor名词可指邻居或邻近建筑。"],
  ["device", "devices", "n.", "装置；设备", "35题机械设备广泛使用的说法超出末句具体例证。", "mechanical devices（机械设备）", "不能由干衣机普及推出所有设备都广泛用于案例住宅。"],
  ["scene", "scenes", "n.", "景色；景观", "Natural scenes对应原文landscape，指被纳入审美的自然环境。", "natural scenes（自然景观）", "不是戏剧场景或新闻现场义。"],
  ["sacrifice", "sacrificed sacrifices sacrificing", "v.", "牺牲；舍弃", "35题说为总体效果牺牲细节，与forthright detailing为效果来源相反。", "sacrifice details（牺牲细节）", "简洁处理细节不等于不要细节。"],
  ["eco-friendly", "", "adj.", "环保的；对环境友好的", "35题干扰项把new materials偷换为环保材料，文中无此性质依据。", "eco-friendly materials（环保材料）", "新型与环保不是同义词，不能自动推断。"],
];

const names: Array<[string, string, string, string, string]> = [
  ["g", "", "G.I.缩写的组成字母", "G. I. Bill（退伍军人法案）", "原卷G. I.分开书写；与Bill合看为帮助退伍军人接受教育等的法案名称。"],
  ["i", "", "G.I.缩写的组成字母", "G. I. Bill（退伍军人法案）", "本文I为缩写字母，不是第一人称我；须与G.及Bill一起理解。"],
  ["ludwig", "", "路德维希（人名）", "Ludwig Mies van der Rohe（路德维希·密斯·凡·德·罗）", "密斯完整姓名中的名字部分，文中为推广少即是多的建筑师。"],
  ["mies", "mies's", "密斯（建筑师姓名）", "Mies's signature phrase（密斯的标志性格言）", "文中以Mies简称Ludwig Mies van der Rohe；Mies's为所有格。"],
  ["van", "", "凡（人名组成部分）", "Ludwig Mies van der Rohe（路德维希·密斯·凡·德·罗）", "van在此是姓名组成，不取普通名词厢式货车义。"],
  ["der", "", "德（人名组成部分）", "Ludwig Mies van der Rohe（路德维希·密斯·凡·德·罗）", "der是完整姓名称呼的一部分，不是英文比较级后缀。"],
  ["rohe", "", "罗（人名组成部分）", "Ludwig Mies van der Rohe（路德维希·密斯·凡·德·罗）", "与Mies van der共同构成文中建筑师姓名。"],
  ["bauhaus", "", "包豪斯（设计学校）", "the Bauhaus（包豪斯设计学校）", "原文同位语a school of design给出学校属性，相关设计师影响美国建筑。"],
  ["chicago", "chicago's", "芝加哥", "Chicago's Lake Shore Drive（芝加哥湖滨大道）", "Chicago's为城市名所有格，限定道路所属城市。"],
  ["lake", "lakes", "湖（湖滨大道名称组成）", "Lake Shore Drive（湖滨大道）", "Lake Shore Drive为道路专名，Lake与Shore组合描述湖滨地带。"],
  ["shore", "shores", "岸（湖滨大道名称组成）", "Lake Shore Drive（湖滨大道）", "Shore与Lake和Drive共同构成专名，不能把整串译成驾驶到湖岸。"],
  ["gold", "", "黄金（区域名组成）", "Gold Coast（黄金海岸区）", "由the city's限定可知是芝加哥的区域，不是澳大利亚城市。"],
  ["coast", "coasts", "海岸（区域名组成）", "Gold Coast（黄金海岸区）", "与Gold共同构成原文芝加哥区域名，普通coast是海岸。"],
  ["frank", "", "弗兰克（人名）", "Frank Lloyd Wright（弗兰克·劳埃德·赖特）", "美国本土设计源流例证中的建筑师名字，不是形容词坦率。"],
  ["lloyd", "", "劳埃德（人名组成）", "Frank Lloyd Wright（弗兰克·劳埃德·赖特）", "与Frank、Wright共同识别风格由铺展转向适度的建筑师。"],
  ["wright", "", "赖特（建筑师姓名）", "Frank Lloyd Wright（弗兰克·劳埃德·赖特）", "不要与Mies混同，30年代房屋与他自己早先设计比较。"],
  ["ralph", "", "拉尔夫（人名）", "Ralph Rapson（拉尔夫·拉普森）", "末句案例住宅建筑师的名字部分。"],
  ["rapson", "", "拉普森（建筑师姓名）", "Ralph Rapson（拉尔夫·拉普森）", "文中讨论他的技术预测可能失准，但自给自足理念广受认可。"],
];
rows.push(...names.map(([headword, forms, meaning, collocation, use]): LexiconRow => [headword, forms, "proper n. / name part", meaning, use, collocation, "专名用于识别人或地点，不以普通词近义词替换；具体身份按本篇原文判断。"]));
const reviewed = reviewedLexicon(rows);
export const passage2011P3Lexicon = reviewed.entries;
export const passage2011P3LemmaAliases: Record<string, string> = { ...reviewed.aliases, widely: "widely", detailing: "detailing", housing: "housing" };
export const passage2011P3CollocationGlosses = reviewed.glosses;
export const passage2011P3FormPartOfSpeech: Record<string, string> = {
  live: "v.", returning: "v.-ing（伴随分词）", going: "v.-ing（伴随分词）", lining: "v.-ing（伴随分词）", following: "v.-ing（后置定语）", home: "adv.", on: "prep.", before: "prep.", living: "gerund", designing: "v.-ing（定语）", german: "n.", american: "adj.", associated: "v.-ed（分词定语）", organized: "v.-ed（分词）", commissioned: "v.-ed（分词定语）", means: "v.（第三人称单数）", signature: "n.（前置定语）", building: "n.", buildings: "n.（复数）", square: "adj.", under: "prep.", first: "adv.", empty: "adj.", foreign: "adj.", yet: "adv.", both: "correlative conjunction part", widely: "adv.", shared: "v.-ed（被动分词）", founded: "v.-ed（创建的过去分词）", identified: "v.-ed（被动分词）", held: "v.（过去式）", used: "v.-ed（过去习惯结构/被动）", arts: "n.（杂志名称组成）", study: "n.（项目名称组成）",
};
const otherMeanings: Record<string, string[]> = {
  depression: ["抑郁；低落；凹陷处。本文the Depression为经济大萧条。"],
  post: ["邮政；岗位；柱子；网络帖子；v. 邮寄或发布。"],
  course: ["课程；路线；一道菜；of course当然。本文为建筑发展的进程。"],
  signature: ["签名；特有标志。signature作名词定语可表示标志性的。"],
  employ: ["雇用人员；运用方法。employ a method采用一种方法。"],
  mask: ["n. 面具；口罩。v. 掩盖，如mask a problem掩盖问题。"],
  view: ["观点、看法；v. 看待、观看；in view of鉴于。"],
  modest: ["谦逊的；不多的、不大的，如a modest income不高的收入。"],
  abstract: ["n. 摘要；v. 提取、抽象概括。本文为抽象艺术的形容词。"],
  commission: ["n. 委员会；佣金；委托任务。本文为委托设计的动词。"],
  afford: ["afford to do负担得起或有条件做某事。afford a view则是提供视野。"],
};
for (const [headword, meanings] of Object.entries(otherMeanings)) passage2011P3Lexicon[headword].otherMeanings = meanings;

export const passage2011P3SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2011-p3-s8": { derive: { contextualSubstitutions: [{ label: "stem", chinese: "源自", fit: "direct", rewrittenSentence: "Elegance, he believed, did not stem from abundance.", nuance: "stem from与derive from均表示来源，前者稍日常；保留否定，不能变成优雅依赖堆砌。", target: "word:stem" }] } },
  "2011-p3-s1": { with: { contextualMeaning: "伴随着（引独立结构）", use: "with soldiers returning/going/lining引三个并列分词，逻辑主语均为soldiers。" }, on: { contextualMeaning: "借助；依据资助安排", use: "on the G. I. Bill指借助退伍军人法案的教育支持上大学。" }, i: { partOfSpeech: "abbreviation part", contextualMeaning: "G.I.缩写中的字母", use: "G. I. Bill整体指法案名称，不是人称代词我。" } },
  "2011-p3-s2": { it: { contextualMeaning: "话题结构形式主语；回指战后时期", use: "when it came to是谈及某事的习语；主句it was回指那个时代，两个it作用不同。" }, that: { partOfSpeech: "conj.", contextualMeaning: "引出信念的内容", use: "belief that后为完整less could be more命题，that不作从句主宾。" } },
  "2011-p3-s3": { that: { partOfSpeech: "det.", contextualMeaning: "那种（节制）", use: "that restraint回指live with less形成的克制，非从句引导词。" }, make: { contextualMeaning: "使……变得", use: "made housing stylish是make+宾语+形容词，stylish作宾补。" } },
  "2011-p3-s5": { who: { partOfSpeech: "relative pron.", contextualMeaning: "指密斯", use: "同作emigrated与took up的主语，中间like...为比较背景。" }, take: { contextualMeaning: "开始担任（take up）", use: "took up posts为开始任职，posts限定take up为任职义。" } },
  "2011-p3-s6": { come: { contextualMeaning: "逐渐；后来开始", use: "came to exert表示发展成产生影响的局面，不是空间来到。" }, so: { contextualMeaning: "如此（发挥影响）", use: "none more so than Mies省略重复的exert influence，意为无人影响更大。" } },
  "2011-p3-s7": { impact: { partOfSpeech: "n.", contextualMeaning: "效果；表现力", use: "has more impact的名词宾语，比较少而精与大量装饰的效果。" }, have: { partOfSpeech: "v.", contextualMeaning: "产生；具有", use: "has more impact中has为实义动词，不是完成时助动词。" } },
  "2011-p3-s9": { that: { partOfSpeech: "relative pron.", contextualMeaning: "指前述材料", use: "第一个that作take宾语，第二个that作symbolized主语，两个从句平行修饰materials。" }, take: { contextualMeaning: "视为（take for granted）", use: "take something for granted指习以为常，不是拿走材料。" } },
  "2011-p3-s10": { that: { partOfSpeech: "conj.", contextualMeaning: "引出事实内容", use: "the fact that后内容完整；spaces后的he designed另是省略关系词的定语从句。" } },
  "2011-p3-s11": { those: { contextualMeaning: "那些公寓", use: "than those in their older neighbors避免重复apartments，比较对象必须同类。" }, their: { contextualMeaning: "这些新塔楼的", use: "their older neighbors指新塔楼附近更老的建筑，非邻居年龄。" }, under: { contextualMeaning: "不到；少于", use: "under 1,000 square feet限定面积小于这一数值。" } },
  "2011-p3-s12": { they: { contextualMeaning: "这些公寓", use: "they were popular与views they afforded均以公寓为主体。" }, proportion: { contextualMeaning: "建筑的比例与尺度关系", use: "details and proportions是并列审美因素，强调各建筑部分之间的比例关系。" }, so: { contextualMeaning: "如此；很", use: "so popular修饰abstract art，不能把当时流行误连到建筑材料。" } },
  "2011-p3-s13": { entirely: { contextualMeaning: "完全地（在否定范围内）", use: "not entirely foreign为并非完全外来，引出本土例子。" } },
  "2011-p3-s14": { he: { contextualMeaning: "弗兰克·劳埃德·赖特", use: "比较他30年代与19世纪90年代、20世纪初的设计，不是密斯。" }, around: { contextualMeaning: "大约", use: "around 1,200 square feet表示近似面积，不是围绕某地。" }, one: { partOfSpeech: "pron.（复数ones）", contextualMeaning: "住宅", use: "two-story ones替代前面的houses。" } },
  "2011-p3-s15": { by: { contextualMeaning: "由（委托方）", use: "by杂志引委托者，from architects引受托提供设计者，不能倒置。" }, yet: { contextualMeaning: "又；再", use: "yet another homegrown influence添加第二个本土影响，不是转折然而。" } },
  "2011-p3-s17": { impact: { partOfSpeech: "v.", contextualMeaning: "影响", use: "would impact everyday life为及物谓语，与第7句名词效果区分。" }, have: { partOfSpeech: "aux.", contextualMeaning: "构成情态完成式", use: "may have mispredicted表示对既往预测作可能失准的推断。" }, few: { contextualMeaning: "几乎没有几个", use: "few American families有否定意味，不能译成许多家庭。" }, most: { partOfSpeech: "pron.", contextualMeaning: "大多数美国家庭", use: "most省略前文American families，作got主语。" }, that: { partOfSpeech: "conj.", contextualMeaning: "引出信念内容", use: "belief that self-sufficiency...为同位内容从句，that不作主宾。" } },
};
