import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";

const rows: LexiconRow[] = [
  ["proposal", "proposals", "n.", "提案；建议", "the chief executive's proposals指首席执行官提出的经营建议，董事应能持异议。", "disagree with proposals（对提案持异议）", "不同于正式决议，proposal仍是提出供讨论的方案。"],
  ["compromise", "compromises compromised compromising", "n.", "妥协；折中", "make compromises为21题干扰项，原文没有西蒙斯拒绝妥协的事实。", "make compromises（作出妥协）", "compromise作动词还可表示损害；本题复数为名词。"],
  ["retain", "retains retained retaining", "v.", "留住；保留", "可替换第18句keep，指通过条件使外部董事继续任职。", "retain outside directors（留住外部董事）", "比keep正式，均可直接接人作宾语；本句不是保持物品所有权。"],
  ["ruth", "", "proper n.", "鲁思（人名）", "Ruth Simmons的名字部分，与姓氏共同识别本文人物。", "Ruth Simmons（鲁思·西蒙斯）", "专名用于定位人物，不按普通词找近义替换。"],
  ["simmons", "", "proper n.", "西蒙斯（姓氏）", "Ms. Simmons与Ruth Simmons指同一位董事兼大学校长。", "Ms. Simmons（西蒙斯女士）", "姓氏结尾s不是名词复数，不能删去。"],
  ["goldman", "goldman's", "proper n.", "高盛（机构名组成部分）", "Goldman Sachs为公司全名，Goldman's为其简称所有格。", "Goldman's compensation committee（高盛薪酬委员会）", "专名不可凭形似拆成gold黄金和man男人。"],
  ["sachs", "sachs's", "proper n.", "萨克斯（高盛公司名组成部分）", "Sachs's为原文所有格写法，保留双s及撇号。", "Goldman Sachs's board（高盛董事会）", "所有格表示董事会所属，专名无需近义改写。"],
  ["join", "joined joins joining", "v.", "加入；成为成员", "join the board指成为董事会成员，原句是过去式joined。", "join a board（加入董事会）", "与join in参加活动不同，join组织直接接宾语。"],
  ["board", "boards", "n.", "董事会", "公司的决策监督机构；on the board表示作为其成员任职。", "on the board（在董事会任职）", "与committee委员会相比，board在此特指公司治理机构。"],
  ["outside", "", "adj.", "外部的；不属内部管理层的", "在outside directors中前置限定董事身份，非介词在外面。", "outside directors（外部董事）", "与independent独立有关但不完全相同，外部身份不保证实际独立。"],
  ["director", "directors director's", "n.", "公司董事", "本文不是电影导演或部门主管，复数directors及所有格director's均归本词。", "an outside director（一名外部董事）", "与executive经营管理人员、adviser顾问区分职责身份。"],
  ["january", "", "proper n.", "一月", "in January 2000表示2000年1月，月份前用in。", "in January（一月份）", "月份专名首字母大写，不是可替换的普通形容词。"],
  ["later", "", "adv.", "后来；之后", "a year later以之前的2000年1月为参照。", "a year later（一年后）", "与latter后者形近不同；later给出相对时间。"],
  ["president", "presidents", "n.", "大学校长", "president of Brown University由机构语境确定为大学校长。", "president of a university（一所大学的校长）", "与head泛指负责人不同；president也可指国家总统或公司总裁。"],
  ["brown", "", "proper n.", "布朗（大学名称）", "Brown University为专名，不表示大学颜色是棕色。", "Brown University（布朗大学）", "普通词brown为棕色的，但本句专名不能这样翻译。"],
  ["rest", "rests resting rested", "n.", "余下部分", "the rest of the decade表示这十年剩余的时间。", "the rest of the decade（这十年余下的时间）", "与rest休息、rest on依赖区别；这里是名词余下部分。"],
  ["apparently", "", "adv.", "看来；表面上", "限定managed的可靠程度，作者描述表面平稳，并非无条件赞扬。", "apparently successful（表面上成功的）", "比certainly确定地更审慎，不能遗漏推断语气。"],
  ["manage", "managed manages managing", "v.", "处理；兼顾", "managed both roles指同时处理董事与校长两项职务。", "manage both roles（兼顾两个角色）", "不同于manage to do设法做成，本文直接接名词宾语。"],
  ["role", "roles", "n.", "角色；职责", "both roles指董事与校长两种身份，题干the role讨论外部董事的职能。", "the role of directors（董事的职责）", "与position职位不同，role更突出在体系中发挥的作用。"],
  ["attract", "attracts attracted attracting", "v.", "招致；引来", "attract criticism表示引起批评，without后用动名词attracting。", "attract criticism（招致批评）", "不是所有attract都译成吸引好感，可接注意、批评等。"],
  ["criticism", "criticisms", "n.", "批评；非议", "much criticism作attracting宾语，为不可数评价性用法。", "face criticism（面临批评）", "与review评论不同，criticism在此偏负面指责。"],
  ["ms", "", "title", "女士", "Ms.是女性称谓，接Simmons；句点为缩写标点，不切断原句。", "Ms. Simmons（西蒙斯女士）", "与Mrs.不同，Ms.不表示已婚；不是名词复数。"],
  ["fire", "fires fired firing", "n.", "猛烈批评（比喻义）", "under fire是习语遭到抨击，与薪酬监督失职相连。", "under fire（遭到抨击）", "非实际火灾；fire作动词还可表示开除或射击。"],
  ["sit", "sat sits sitting", "v.", "在委员会任职", "having sat on...用完成式动名词，说明她曾为薪酬委员会成员。", "sit on a committee（在委员会任职）", "与坐在物体上不同，on后是组织时可表成员身份。"],
  ["compensation", "compensations", "n.", "薪酬；报酬", "compensation committee负责高管薪酬等事务，后文bonus payouts说明该语境。", "compensation committee（薪酬委员会）", "与损失赔偿义区分，本文不在谈侵权赔款。"],
  ["bonus", "bonuses", "n.", "奖金", "bonus前置限定payouts，指额外奖金的支付。", "bonus payouts（奖金发放）", "与salary固定薪水不同，bonus是额外报酬。"],
  ["payout", "payouts", "n.", "支付款项；发放金额", "enormous bonus payouts为let宾语，未说属于Simmons个人收入。", "enormous payouts（巨额款项支付）", "名词payout与动词短语pay out分开，复数加s。"],
  ["pass", "passes passed passing", "v.", "获准通过；被放行", "let payouts pass unremarked表示放任奖金方案在无质疑下通过。", "pass unremarked（未经评论地通过）", "不取pass time消磨时间义，后接状态形容词作补足。"],
  ["unremarked", "", "adj.", "未受评论或质疑的", "pass unremarked中说明奖金发放未被指出问题的状态。", "go unremarked（未被评论）", "与unremarkable平平无奇不同，不是奖金不值得注意。"],
  ["february", "", "proper n.", "二月", "By February the next year指到2010年2月为止。", "by February（到二月为止）", "by是截止，不等于只能在二月份发生。"],
  ["leave", "left leaves leaving", "v.", "离开；辞去", "leave a firm或the board表示离开任职组织，不取leave somebody vulnerable的使处于义。", "leave a board（离开董事会）", "与stay留任相对，left是过去式及过去分词。"],
  ["position", "positions", "n.", "职位；职务", "the position回指董事职位，占用时间是她给出的离职理由。", "hold a position（担任职位）", "同词也可表示位置或立场，本文不取空间义。"],
  ["take", "takes taking took taken", "v.", "占用（与up构成短语）", "was taking up too much time表示董事职务耗时过多。", "take up time（占用时间）", "不同于take over接管或take as视为，必须连同up理解。"],
  ["up", "", "particle", "构成占用或升级的短语", "take up表占用；trade up表升级更换，均不是单独向上运动。", "trade up（升级更换）", "同一小品词随动词形成不同意义，不直接逐词相加。"],
  ["too", "", "adv.", "过于；太", "too much time表示超过可承受程度，非句末too也。", "too much time（太多时间）", "much仅多，too much带过量评价。"],
  ["time", "times", "n.", "时间；时期；经历", "take up time表时长；have an easier time of doing表较容易的经历；tough times表艰难时期。", "through tough times（度过艰难时期）", "times在本文不是倍数；同句at the time与have an easier time语法不同。"],
  ["suppose", "supposes supposed supposing", "v.", "按职责应当（be supposed to）", "are supposed to serve表应有职能，非对实际履职的事实肯定。", "be supposed to do（理应做）", "不同于主动suppose that假设；此处强调规范预期。"],
  ["helpful", "", "adj.", "有帮助的；有用的", "修饰advisers，说明建议应对公司有帮助。", "helpful advisers（有帮助的顾问）", "有帮助不自动等于无偏见，原文另用less biased限定。"],
  ["adviser", "advisers", "n.", "顾问；提供建议的人", "advisers是serve as后身份中心，两个形容词共同修饰它。", "independent advisers（独立顾问）", "与executive负责执行管理的人不同，顾问侧重提供意见。"],
  ["firm", "firms firm's", "n.", "公司；企业", "本篇始终为公司义；a firm's board中的所有格表示所属。", "a firm's board（一家公司的董事会）", "普通形容词firm可表坚定或牢固，本文不取该词性。"],
  ["make", "made makes making", "v.", "获得；形成", "Having made their wealth and their reputations表示在别处积累财富声望。", "make one's reputation（树立个人声誉）", "不同于make somebody do使役结构，本文后接成果名词。"],
  ["reputation", "reputations", "n.", "声誉；名声", "与财富并列，后文又谈避免声誉打击，是解释离任动机的关键词。", "a blow to one's reputation（对声誉的打击）", "与popularity受欢迎程度有关但不相同；声誉包含评价与信任。"],
  ["enough", "", "det.", "足够的", "enough independence中前置限定不可数名词，to disagree说明足以做什么。", "enough independence to disagree（足以提出异议的独立性）", "名词前用enough，形容词后的副词用法如independent enough不能混排。"],
  ["independence", "", "n.", "独立性；自主性", "财富声望来自别处，因此理论上能不受管理层牵制。", "independence from management（独立于管理层）", "名词independence与形容词independent属词族而不合并原形。"],
  ["disagree", "disagrees disagreed disagreeing", "v.", "不同意；持异议", "disagree with the proposals表示对提案不赞同。", "disagree with a proposal（不赞同提案）", "与reject正式否决不同，disagree首先表示意见不同。"],
  ["executive", "executives executive's", "n.", "经营管理人员；执行主管", "chief executive为首席执行官；选项executives不能替换顾问advisers。", "chief executive（首席执行官）", "董事、顾问、执行管理层不可不加区分地混用。"],
  ["sky", "skies", "n.", "天空（此处借指灾难临头）", "the sky is falling为夸张比喻，与股价下跌并列营造危机情境。", "the sky is falling（仿佛天要塌了）", "不是文章在报道气象事件。"],
  ["share", "shares", "n.", "股票；股份", "share price中名词前置限定price，表示股票价格。", "share price（股价）", "不同于share分享的动词义，不能译成共享价格。"],
  ["advice", "", "n. uncountable", "建议；意见", "give advice指外部董事在危机中提出建议。", "give advice（提出建议）", "advice为不可数名词；advise为动词，不是其词形变化。"],
  ["weather", "weathered weathers weathering", "v.", "经受住；渡过", "having weathered their own crises以危机经历说明建议基础。", "weather a crisis（渡过危机）", "名词weather为天气，此处直接接crises而用动词。"],
  ["crisis", "crises", "n.", "危机", "their own crises指董事各自在别处经历并应对的危机。", "weather crises（经受住危机）", "复数crises是不规则变化，与crisis稳定归一。"],
  ["ohio", "", "proper n.", "俄亥俄（大学名组成部分）", "Ohio University为研究人员所属大学。", "Ohio University（俄亥俄大学）", "机构专名负责来源定位，不做词义近义替换。"],
  ["database", "databases", "n.", "数据库", "涵盖公司、董事及时间范围的资料库，作used宾语。", "use a database（使用数据库）", "与data资料不同，database强调系统组织的资料集合。"],
  ["cover", "covered covers covering", "v.", "涵盖；收录", "database covered多家公司董事资料，不是用物体覆盖。", "cover a period（涵盖一段时期）", "同词也可表报道、支付费用；本文为资料范围义。"],
  ["check", "checked checks checking", "v.", "核查；对照检查", "checked which directors stayed核查连续披露中哪些董事留任。", "check records（核查记录）", "与prove证明不同，check说明核查行为。"],
  ["proxy", "proxies", "n.", "代理投票；委托授权", "proxy statement是提交股东的委托投票相关披露文件，可核对董事名单。", "proxy statement（委托投票说明书）", "普通proxy也可指代理人；本文不涉及网络代理服务器。"],
  ["statement", "statements", "n.", "说明书；披露文件", "proxy statement在公司治理语境是股东代理投票的相关披露材料。", "a proxy statement（一份委托投票说明书）", "不是某董事的一句口头声明，也不等同于一届任期。"],
  ["depart", "departing departed departs", "v.", "离任；离开", "departing a board指辞去董事会席位，非飞机起飞。", "depart a board（离开董事会）", "与leave在本语境相近，depart更正式。"],
  ["age", "ages", "n.", "年龄", "说明常规离任的年龄因素，under the age of 70排除部分退休干扰。", "under the age of 70（未满70岁）", "不是时代或年代义，数字70指董事年龄。"],
  ["concentrate", "concentrated concentrates concentrating", "v.", "集中注意；重点研究", "concentrate on后接70岁以下董事的意外离任。", "concentrate on departures（重点研究离任）", "与focus on相近；不是使液体浓缩的物理义。"],
  ["surprise", "surprises", "n. attributive", "意外的；出乎预期的", "surprise前置限定departure和disappearances，指非预期离任。", "a surprise departure（一次意外离职）", "不是让他人惊讶的谓语动词；引号提示研究分类的用语。"],
  ["disappearance", "disappearances", "n.", "不再出现；退出", "指董事不再出现于董事名单，本文语境为离任，不是失踪案件。", "surprise disappearances（意外退出）", "与departure离任在本篇呼应；词形不能直接归入disappear动词。"],
  ["departure", "departures", "n.", "离任；离职", "surprise departure回指外部董事的非预期离职。", "after a departure（离任之后）", "名词与depart动词各保留原形，本文不取航班起飞义。"],
  ["probability", "probabilities", "n.", "概率；可能性", "增长的是重述财报的概率，that从句说明所谈事件。", "the probability that a firm restates earnings（公司重述盈利数据的概率）", "概率增长不能换成实际盈利增加。"],
  ["subsequently", "", "adv.", "此后；随后", "置于will have to之间，给出董事离任后事件的时间顺序。", "subsequently restate earnings（随后重述盈利数据）", "时间先后本身不证明因果。"],
  ["restate", "restates restated restating", "v.", "重述；重新报告", "restate earnings指对先前报告的盈利数据作修订披露。", "restate earnings（重述盈利数据）", "与increase earnings增加盈利不同，也不只是将原数字再念一遍。"],
  ["earnings", "", "plural n.", "盈利；收益", "公司财务报告中的盈利数据，常以复数形式使用。", "reported earnings（已报告的盈利）", "与earn赚取为派生关系，不能把earnings计入动词earn次数。"],
  ["likelihood", "", "n.", "可能性", "of being named说明卷入集体诉讼的事件，未断定一定败诉。", "the likelihood of litigation（发生诉讼的可能性）", "与certainty确定性不同，likelihood保留风险概率。"],
  ["name", "named names naming", "v.", "列名；将……列为当事人", "being named in a lawsuit为被动动名词，说明公司被列入诉讼。", "be named in a lawsuit（被列入一项诉讼）", "不是给公司起名字，更不等于已经败诉。"],
  ["class-action", "", "adj. attributive", "集体诉讼的", "class-action限定lawsuit，保留原文连字符。", "a class-action lawsuit（一宗集体诉讼）", "class在这里不是教学班级，须整体理解法律搭配。"],
  ["lawsuit", "lawsuits", "n.", "诉讼；官司", "联邦集体诉讼的风险增大，而选项诉讼表现变差缺乏依据。", "face a lawsuit（面临诉讼）", "被起诉与败诉是不同命题，不能相互替换。"],
  ["stock", "stocks", "n.", "股票", "the stock指离任董事所在公司的股票，非仓库库存。", "stock performance（股票表现）", "与earnings盈利水平相关但不是同一指标。"],
  ["perform", "performs performed performing", "v.", "表现；运行状况如何", "stock perform worse表示股票市场表现较差，不是执行某个任务。", "perform worse（表现更差）", "不及物用法，worse是修饰perform的副词比较级。"],
  ["badly", "worse worst", "adv.", "差地；不佳地", "perform worse中的worse为badly比较级，说明股票表现。", "perform badly（表现不佳）", "形容词bad修饰名词，副词badly修饰perform；本篇worse不能标作形容词。"],
  ["correlation", "correlations", "n.", "相关性；关联", "between并列董事离职与其后公司表现不佳两项。", "a correlation between two events（两件事之间的关联）", "correlation不等于causation因果关系，原文专门限制动机推断。"],
  ["subsequent", "", "adj.", "随后的；此后的", "限定bad performance，时间参照是董事离职。", "subsequent performance（后续表现）", "形容词subsequent与副词subsequently各保留独立词条。"],
  ["performance", "performances", "n.", "表现；业绩", "公司离任后的经营、股价等表现，不是舞台演出。", "bad performance（业绩不佳）", "与perform动词属词族，不能并入同一词位计数。"],
  ["suggestive", "", "adj.", "暗示着某种情况的；耐人寻味的", "correlation is suggestive表关联引人联想，但不构成确定证明。", "suggestive evidence（带有暗示性的证据）", "比conclusive确凿的弱；此处不是带色情暗示。"],
  ["jump", "jumping jumped jumps", "v.", "跳离；脱身", "jump off a sinking ship比喻离开前景不妙的公司。", "jump off a sinking ship（从沉船脱身）", "全文否定的是总这样做，不能译成从不逃避风险。"],
  ["sink", "sinking sank sunk sinks", "v.", "下沉；陷入困境", "sinking现在分词作ship定语，以沉船比喻风险公司。", "a sinking ship（正在下沉的船）", "sank为过去式，sunk为过去分词；本文并非公司已经倒闭。"],
  ["trade", "trades traded trading", "v.", "升级更换（与up连用）", "trade up比喻董事换到更大、更稳的任职平台。", "trade up（升级换购；另谋高就）", "不是指董事亲自进行股票交易。"],
  ["risky", "riskier riskiest", "adj.", "风险大的", "riskier比较级与smaller并列，形容董事离开的公司。", "riskier firms（风险更大的公司）", "与stable稳定的形成平台选择对比；风险不等于已遭损失。"],
  ["stable", "", "adj.", "稳定的", "more stable形容董事转去的公司，非原公司的后续状态。", "more stable firms（更稳定的公司）", "比较级用more stable，不能误造stabler为本句词形。"],
  ["avoid", "avoiding avoids avoided", "v.", "避免；躲开", "avoid a blow to reputations指避开声誉损害。", "avoid a reputational blow（避免声誉受损）", "avoid后接名词或doing，不接to do作宾语。"],
  ["blow", "blows", "n.", "打击", "a blow to reputations用打击比喻声誉损害，是可数名词。", "a blow to one's reputation（对个人声誉的打击）", "不是动词吹气；to引出受损对象。"],
  ["break", "breaks broke broken breaking", "v.", "消息传出；曝光", "bad news breaks是新闻出现的熟词义，news作单数不可数主语。", "news breaks（消息传出）", "不是把新闻打碎；break还可表示打破、休息或中断。"],
  ["review", "reviews reviewed reviewing", "n.", "回顾；重新审视", "a review of history为shows主语，考察过去在任与违规的时点。", "a review of history（对历史的回顾）", "与book review书评或复习不同，本文为回顾调查。"],
  ["wrongdoing", "wrongdoings", "n.", "不当行为；违规行为", "指公司中发生的违规，董事当时在任并不自动证明其亲自参与。", "corporate wrongdoing（公司违规行为）", "wrongdoing可泛指不当行为，不能无依据升级为个人定罪。"],
  ["occur", "occurred occurs occurring", "v.", "发生", "wrongdoing occurred中不及物谓语，宾语为空。", "when wrongdoing occurred（违规发生时）", "与occur to somebody某人想到的结构区分；过去式双写r。"],
  ["keep", "kept keeps keeping", "v.", "留住；使继续留任", "keep their outside directors通过激励留住董事。", "keep directors through tough times（在困难时期留住董事）", "不是对物品的保存，也不等于强制拘留。"],
  ["tough", "tougher toughest", "adj.", "艰难的；棘手的", "tough times指公司的困难时期。", "tough times（艰难时期）", "不同于身体强壮或食物坚韧的具体义。"],
  ["incentive", "incentives", "n.", "激励；有吸引力的条件", "公司可能需要提供激励促使董事留任，原文未限定必须是加薪。", "create incentives（提供激励条件）", "与coercion强制不同，incentive通过吸引使人愿意行动。"],
  ["otherwise", "", "adv.", "否则；若不如此", "承接没有留任激励的情况，预测董事仿效离职。", "otherwise leave（否则离开）", "不是与前面并列的另一个不相关观点。"],
  ["follow", "follows followed following", "v.", "仿效；效法", "follow the example of Simmons表示采取相似的离职选择。", "follow somebody's example（效仿某人）", "不取在道路上跟随的空间义。"],
  ["popular", "", "adj.", "受欢迎的", "修饰Ms. Simmons在校园里的声誉，不是说董事制度流行。", "popular on campus（在校园受欢迎）", "受学生欢迎不是作者对董事角色的positive评价。"],
  ["campus", "campuses", "n.", "校园", "on campus指Simmons担任校长的大学环境。", "on campus（在校园）", "不等于公司所在地；与board形成两种角色背景。"],
  ["profit", "profits profited profiting", "n.", "利润；获利", "21题干扰项说她获取过高利润，原文没有这种事实。", "excessive profits（过高利润）", "奖金支付与她本人盈利不能直接划等号。"],
  ["refuse", "refusing refused refuses", "v.", "拒绝", "21题refusing to make compromises是假设的原因，原文未述。", "refuse to compromise（拒绝妥协）", "refuse后接to do；与reject后接名词的结构不同。"],
  ["generous", "", "adj.", "慷慨的；大方的", "修饰22题干扰项investors，原文不要求董事慷慨投资。", "generous investors（慷慨的投资者）", "wealthy有钱不等于generous慷慨。"],
  ["investor", "investors", "n.", "投资者", "22题错项把外部顾问偷换为出资者。", "outside investors（外部投资者）", "director董事是治理角色，investor投资者是资本角色。"],
  ["unbiased", "", "adj.", "公正的；无偏见的", "22题形容词贴近less biased，但其后executives角色有误。", "unbiased advice（公正的建议）", "有一个词与原文接近不意味着整个选项成立。"],
  ["forecaster", "forecasters", "n.", "预测者", "share price forecasters为股价预测者，不是文中董事的应有职责。", "share price forecasters（股价预测者）", "提供危机应对建议不等于预测未来价格。"],
  ["independent", "", "adj.", "独立的；自主的", "independent advisers对应第二段independence和advisers。", "independent advisers（独立顾问）", "独立并非完全不与公司合作，而是能提出不迎合管理层的意见。"],
  ["attractive", "", "adj.", "有吸引力的", "24题attractive offers对应原文留任激励，不指人的外貌。", "attractive offers（有吸引力的条件）", "与forced被迫相反，强调条件诱因。"],
  ["offer", "offers offered offering", "n.", "提议；给予的条件", "24题复数offers作介词for宾语，表示公司提出的优厚条件。", "attractive offers from a firm（公司提供的有吸引力的条件）", "offers此处不是第三人称单数动词提供。"],
  ["record", "records recorded recording", "n.", "记录；过往行为记录", "records of wrongdoings为干扰项，没有证据说董事本人有违规记录。", "records of wrongdoing（违规记录）", "记录与罪责认定不同；不能从在任推断亲自违规。"],
  ["accustomed", "", "adj.", "习惯于的", "be accustomed to work中to是介词，表示习惯某类工作环境。", "be accustomed to doing（习惯做某事）", "不同于used to do过去常做；此题原文未证明习惯无压力工作。"],
  ["stress-free", "", "adj.", "没有压力的", "修饰24题干扰项work，不能从困难时离开反推过去一直无压力。", "stress-free work（没有压力的工作）", "与tough times形成干扰对照，不是原文明说的事实。"],
  ["work", "works worked working", "n.", "工作", "stress-free work中的work为不可数名词，不是动词起作用。", "work in a firm（在公司的工作）", "同词动词work表示工作或奏效；本选项是名词。"],
  ["decline", "declines declined declining", "v.", "拒绝；婉拒", "will decline incentives中的decline接宾语表示拒绝，不表示激励自己下降。", "decline an offer（拒绝提议）", "与reject相比通常语气较礼貌；本文选项与留人激励逻辑不符。"],
  ["permissive", "", "adj.", "宽容放任的；纵容的", "25题态度选项，指允许或宽容某行为。", "a permissive attitude（放任的态度）", "与positive积极肯定不同，也不等同于中立分析。"],
  ["scornful", "", "adj.", "轻蔑的；鄙视的", "25题程度较强的负面态度词，超出本文分析性批评的语气。", "a scornful response（轻蔑的回应）", "critical可理性批评，scornful带看不起的情绪，不能等同。"],
];

const reviewed = reviewedLexicon(rows);
export const passage2011P1Lexicon = reviewed.entries;
export const passage2011P1LemmaAliases: Record<string, string> = { ...reviewed.aliases, being: "be" };
export const passage2011P1CollocationGlosses = reviewed.glosses;
export const passage2011P1FormPartOfSpeech: Record<string, string> = {
  outside: "adj.", offers: "n.（复数）", worse: "adv.（badly的比较级）", times: "n.（时期的复数）", for: "prep.", before: "conj.", that: "relative pron. / conj.", enough: "det.", having: "aux.（完成式动名词/分词）", being: "aux.（被动动名词）", unremarked: "adj.", supposed: "v.-ed（职责结构）", biased: "adj.", made: "v.-ed（过去分词）", weathered: "v.-ed（过去分词）", found: "v.（过去式）", named: "v.-ed（被动分词）", sinking: "v.-ing（分词定语）", departing: "gerund", leaving: "v.-ing / gerund", once: "adv.", very: "adv.", well: "adv.", failing: "gerund", work: "n.", profits: "n.（复数）",
};

const otherMeanings: Record<string, string[]> = {
  board: ["木板；公告板；食宿，如room and board。", "v. 登上车辆或船只，如board a plane登机。"],
  compensation: ["补偿；赔偿，如compensation for damage损害赔偿。"],
  rest: ["休息；休息时间。rest on以……为基础，与the rest of余下部分不同。"],
  position: ["位置；姿势；立场。take a position on就某事表明立场。"],
  weather: ["n. 天气；v. 经受风化。本文weather a crisis为渡过危机。"],
  stock: ["库存；储备，如out of stock缺货。", "v. 储备、备有货品；股票义与库存义不要混读。"],
  firm: ["adj. 坚定的；牢固的，如a firm decision坚定的决定。"],
  break: ["打破；中断；违反，如break a rule违反规则。", "n. 休息间歇；机会；裂口。"],
  decline: ["v. 下降；衰退；n. 下降或衰落。接offer作宾语时常表示婉拒。"],
  trade: ["n. / v. 贸易、交易；n. 行业、手艺。trade A for B用A换B。"],
};
for (const [headword, meanings] of Object.entries(otherMeanings)) passage2011P1Lexicon[headword].otherMeanings = meanings;

export const passage2011P1SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2011-p1-s1": { as: { contextualMeaning: "作为（任职身份）", use: "as an outside director说明加入董事会时的身份。" }, she: { contextualMeaning: "西蒙斯", use: "回指第一分句的Ruth Simmons。" } },
  "2011-p1-s2": { for: { contextualMeaning: "在……这段时间内", use: "For the rest of the decade表持续范围，不是原因。" }, both: { contextualMeaning: "这两个（角色）", use: "对应董事与大学校长。" } },
  "2011-p1-s3": { by: { contextualMeaning: "到……为止", use: "by the end of 2009是截止时间。" }, for: { contextualMeaning: "因为", use: "for having sat引出受到批评的原因。" }, on: { contextualMeaning: "在……任职", use: "sit on a committee表示担任委员会成员。" }, have: { partOfSpeech: "aux.", contextualMeaning: "构成完成式", use: "having sat与could have let均使用完成结构，回看已发生行为。" } },
  "2011-p1-s4": { by: { contextualMeaning: "到……为止", use: "By February the next year与had left过去完成时配合。" }, have: { partOfSpeech: "aux.", contextualMeaning: "构成过去完成时", use: "had left强调到2010年2月已离任。" } },
  "2011-p1-s5": { time: { contextualMeaning: "时间（时长）", use: "too much time是taking up占用的资源，不是倍数。" } },
  "2011-p1-s6": { yet: { contextualMeaning: "但又", use: "连接helpful与less biased两种预期品质。" }, on: { contextualMeaning: "在……任职", use: "on a firm's board表示董事会内的任职关系。" } },
  "2011-p1-s7": { they: { contextualMeaning: "外部董事", use: "财富与声望在别处积累，按说有自主判断能力。" }, have: { partOfSpeech: "aux. / v.", contextualMeaning: "已做成；拥有", use: "Having made构成完成式分词；have enough independence中have为实义拥有。" } },
  "2011-p1-s8": { own: { partOfSpeech: "det.", contextualMeaning: "他们自己的", use: "their own crises以经历者身份强调董事本人曾经应对的危机。" }, have: { partOfSpeech: "aux.", contextualMeaning: "已经（完成式）", use: "having weathered在on后作完成式动名词。" } },
  "2011-p1-s9": { that: { partOfSpeech: "relative pron.", contextualMeaning: "关系代词，指数据库", use: "that作covered的主语，限定database。" } },
  "2011-p1-s10": { they: { contextualMeaning: "研究人员", use: "承接Ohio University的researchers，执行名单核查。" }, which: { partOfSpeech: "interrogative det.", contextualMeaning: "哪些", use: "which directors共同作stayed主语，是checked后的嵌入疑问，不是关系定语从句。" } },
  "2011-p1-s11": { so: { partOfSpeech: "conj.", contextualMeaning: "因此", use: "连接年龄为常见原因与聚焦非预期离任的研究选择。" } },
  "2011-p1-s12": { they: { contextualMeaning: "研究人员", use: "They found报告统计发现。" }, that: { partOfSpeech: "conj.", contextualMeaning: "引出发现的内容或概率涉及的事件", use: "found that为宾语从句；probability that为同位内容从句，that均不作从句主宾。" }, by: { contextualMeaning: "增加了（幅度）", use: "by nearly 20%不能译成增加到20%或擅自改成20个百分点。" } },
  "2011-p1-s13": { be: { partOfSpeech: "aux. / linking v.", contextualMeaning: "被；可能处于某表现", use: "being named为被动；is likely to为可能性系表结构。" } },
  "2011-p1-s14": { for: { contextualMeaning: "对于", use: "for larger firms限定效应在哪类公司较大。" } },
  "2011-p1-s15": { they: { partOfSpeech: "pron.（宾格them）", contextualMeaning: "这些董事", use: "them leaving中的them是动名词结构的逻辑主语，非researchers。" }, it: { contextualMeaning: "这种相关性", use: "it回指董事离任与后续差表现的correlation。" }, always: { contextualMeaning: "总是（在否定范围内）", use: "does not mean...always表达不能一概而论，不是从未脱身。" } },
  "2011-p1-s16": { they: { contextualMeaning: "离任的董事", use: "主体通过换去更稳的大公司改善任职平台。" }, for: { contextualMeaning: "转向；以……为去向", use: "leave A for B构成离开A去B，非原因。" } },
  "2011-p1-s17": { they: { contextualMeaning: "外部董事", use: "条件中leave和回顾中were on the board均指董事。" }, have: { contextualMeaning: "经历；处于", use: "have an easier time of doing表示做某事较容易，非完成时助动词。" }, time: { contextualMeaning: "经历；时点", use: "an easier time of doing说明较易做到；at the time any wrongdoing occurred指出违规发生时点。" }, before: { partOfSpeech: "conj.", contextualMeaning: "在……之前", use: "引导bad news breaks时间从句。" } },
  "2011-p1-s18": { keep: { contextualSubstitutions: [{ label: "retain", chinese: "留住；使继续任职", fit: "direct", rewrittenSentence: "Firms who want to retain their outside directors through tough times may have to create incentives.", nuance: "retain比keep正式，保留通过激励使董事继续留任的原命题。", target: "word:retain" }] }, who: { partOfSpeech: "relative pron.", contextualMeaning: "指那些公司", use: "原文who回指Firms并作want主语，保留附件拟人化表达。" }, have: { contextualMeaning: "不得不（have to）", use: "may have to create兼有可能性与实际必要性。" }, time: { partOfSpeech: "n.（复数）", contextualMeaning: "时期", use: "through tough times表示经历困难时期，不是倍数。" }, through: { contextualMeaning: "贯穿；度过", use: "限定在艰难时期仍留住董事。" } },
  "2011-p1-s19": { once: { partOfSpeech: "adv.", contextualMeaning: "再一次（once again）", use: "与again共同表再次，不是once作连词一旦。" }, very: { partOfSpeech: "adv.", contextualMeaning: "很；非常", use: "very修饰popular，与完形that very anonymity的形容词用法不同。" } },
};
