import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";

const rows: LexiconRow[] = [
  ["happen", "happened happens happening", "v.", "发生；后来怎样", "Whatever happened to...以反问追问消亡预言的下文。", "happen to something（某事后来怎样）", "to后接所谈对象，不是happen to do碰巧做。"],
  ["newspaper", "newspapers", "n.", "报纸；报社", "指报业出版物或经营这些出版物的机构，按主句动作理解。", "the newspaper business（报业）", "报纸的经营情况与具体报道内容需要区分。"],
  ["year", "years", "n.", "年", "year与ago构成回看过去的时间短语，几年前与一年前的长度不同。", "a year ago（一年前）", "a few years ago是几年前，不擅加具体年份。"],
  ["ago", "", "adv.", "……以前", "a year ago和a few years ago都以叙述当下为参照回看过去。", "a few years ago（几年前）", "ago置于时间长度后，和since表示起点不同。"],
  ["end", "ends ended ending", "n.", "终结；消亡", "the end承接报纸消亡，是一年前看似临近的前景。", "the end seemed near（终结似乎临近）", "seemed保留观感，不能译成已经终结。"],
  ["seem", "seemed seems seeming", "linking v.", "似乎；看起来", "seem后接near或out of date作表语，分别评价终结与讨论。", "seem out of date（似乎已经过时）", "seem不是证明事实的动词，保留表象判断。"],
  ["near", "", "adj.", "临近的", "near在seemed后作表语，说明终结看似近在眼前。", "seem near（似乎临近）", "不是介词near后接地点的结构。"],
  ["remove", "removed removes removing", "v.", "夺走；使流失", "remove的宾语为尚未转网的广告业务和读者，说明衰退带来的威胁。", "remove advertising and readers（夺走广告业务和读者）", "threatened to remove表风险，不证明全部已经流失。"],
  ["advertising", "", "n.", "广告业务；广告收入来源", "在报业经营中指广告活动及其带来的收入，和付费读者共同支撑经营。", "revenue from advertising（来自广告的收入）", "advertising收入与扣除成本后的profit不同。"],
  ["internet", "", "n.", "互联网", "广告和读者已部分转向互联网，余下部分又受到衰退威胁。", "flee to the internet（转向互联网）", "to引去向；不要漏掉not already对剩余部分的限定。"],
  ["san", "", "proper-name part", "旧金山名称的组成部分", "与Francisco组成San Francisco，出现在报纸名称San Francisco Chronicle中。", "San Francisco Chronicle（《旧金山纪事报》）", "地名与报纸名整体识别即可。"],
  ["francisco", "", "proper-name part", "旧金山名称的组成部分", "San Francisco为旧金山，修饰报纸名称Chronicle。", "San Francisco Chronicle（《旧金山纪事报》）", "不将城市名称拆成普通词义。"],
  ["america", "america's", "proper n.", "美国", "America's为所有格，限定Federal Trade Commission这一美国机构。", "America's Federal Trade Commission（美国联邦贸易委员会）", "所有格s不能单独计为另一个词。"],
  ["federal", "", "adj.", "联邦的", "Federal在Trade Commission中标明美国联邦层级。", "Federal Trade Commission（联邦贸易委员会）", "这里是机构专名的一部分，先整体识别。"],
  ["become", "became becomes becoming", "linking v.", "成为；变得", "后接机构身份或经营结构作表语：成为慈善机构、成为更均衡的企业。", "become balanced businesses（成为收入结构均衡的企业）", "should become是提议，are becoming是正在发生的变化。"],
  ["corporation", "corporations", "n.", "法人机构；公司", "charitable corporations指救济讨论中的慈善性质机构。", "charitable corporations（慈善性质的法人机构）", "问句不等于已转型；charitable限定组织性质。"],
  ["another", "", "det.", "另一场；再一场", "another修饰meeting，承接此前已发起的会谈。", "another meeting（另一场会议）", "后接单数meeting，不是one after another结构。"],
  ["soon", "", "adv.", "不久；很快", "修饰will hold，说明委员会将再开会的时间。", "hold another meeting soon（不久再开一次会）", "不是对报业多久会繁荣的预测。"],
  ["now", "", "adv.", "如今；现在", "now与一年前的危机对照，说明救济讨论目前似乎已过时。", "now seem out of date（如今似乎过时）", "时间变化是第一段的转折依据。"],
  ["world", "worlds", "n.", "世界", "much of the world指世界很大一部分地区，不扩为全部地区。", "in much of the world（在世界许多地区）", "限定范围时保留much of，避免全称化。"],
  ["sign", "signs", "n.", "迹象", "sign of crisis为危机迹象，little sign表示几乎看不到。", "sign of crisis（危机迹象）", "在宾语或存在句中为名词，不是签名动词。"],
  ["crisis", "crises", "n.", "危机", "指报业面临衰退、资源流失等经营困境。", "sign of crisis（危机迹象）", "crises为复数，本文crisis为单数形式。"],
  ["german", "", "adj.", "德国的", "与Brazilian并列修饰papers，给出两国报业的例子。", "German and Brazilian papers（德国和巴西的报纸）", "形容词国别，不是带the的国民集合名词。"],
  ["american", "", "adj.", "美国的", "限定报纸、同类比较者或机构名称，构成本文重点讨论的国别。", "American newspapers（美国报纸）", "依所修饰名词判断对象，不单独译作美国人。"],
  ["global", "", "adj.", "全球的", "限定industry，说明比较是在全球报业范围内。", "the global industry（全球报业）", "美国是该行业中受困严重的一部分，不等于全世界都同样受困。"],
  ["industry", "industries", "n.", "行业；报业", "global industry在本文指全球报纸行业，不是一般工业制造业。", "the global newspaper industry（全球报纸行业）", "corner of the industry是行业局部的比喻。"],
  ["survive", "survived survives surviving", "v.", "存活；维持经营", "have survived说明美国报纸挺过危机，后面才递进到恢复盈利。", "survive and return to profit（存活并恢复盈利）", "存活不等于thrive兴旺。"],
  ["profit", "profits", "n.", "利润；盈利", "return to profit指恢复盈利；profit margins则讨论盈利水平。", "return to profit（恢复盈利）", "profit扣除成本，revenue是收入；20%利润率不等于87%广告收入占比。"],
  ["stay", "stayed stays staying", "linking v.", "保持", "stayed afloat表示报社维持经营，是保持状态的系表结构。", "stay afloat（维持经营）", "afloat为表语，by pushing说明实现手段。"],
  ["news", "", "n. uncountable", "新闻", "News Editors是新闻编辑人员，News为前置名词限定。", "News Editors（新闻编辑）", "news形式带s但通常不可数，此处不是复数人员。"],
  ["job", "jobs", "n.", "岗位；职位", "13,500 newsroom jobs为被裁撤的岗位数，不是报社数量。", "newsroom jobs（新闻采编岗位）", "have gone描述岗位流失的结果。"],
  ["product", "products", "n.", "产品；报纸产品", "slimmer products指篇幅变薄的报纸，读者却支付更多。", "slimmer products（内容更少的报纸产品）", "产品变薄是事实，不能据此推定读者已经投诉。"],
  ["distant", "", "adj.", "距离较远的", "修饰suburbs，指送报路线较远的郊区。", "distant suburbs（偏远郊区）", "配送目的地不等于报纸所报道的业务领域。"],
  ["measure", "measures", "n.", "措施；办法", "these desperate measures回指裁员、提价、缩减配送等求生办法。", "desperate measures（迫不得已的措施）", "不是测量动作或尺寸单位；后文ones与they均承接它。"],
  ["prove", "proved proves proving", "linking v.", "证明是；结果表明是", "have proved the right ones以名词表语评价措施奏效。", "prove the right ones（证明是正确的措施）", "此处prove后为表语，不把ones当被证明的人。"],
  ["right", "", "adj.", "正确的；有效的", "right修饰ones，肯定这些求生措施的经营效果。", "the right measures（正确有效的措施）", "这里不是名词权利，也不否定记者承受损失。"],
  ["further", "", "adv.", "进一步", "can be pushed further说明紧缩措施仍可继续推进。", "push measures further（进一步推行措施）", "程度副词，不是journalists被推到更远地点。"],
  ["unusual", "", "adj.", "不同寻常的", "highly unusual in their reliance on ads指出美国报业广告依赖显著偏高。", "highly unusual（极不寻常的）", "in限定比较方面，后文百分比把这一特点具体化。"],
  ["according", "", "prep. phrase part", "根据；据……所示", "according to引出经合组织作为收入比例数据的来源。", "according to the OECD（根据经合组织的数据）", "according to整体识别，不是有限动词谓语。"],
  ["organization", "organizations", "n.", "组织", "Organization为经合组织全名的中心名词，后面说明其经济合作与发展宗旨。", "Organization for Economic Cooperation & Development（经济合作与发展组织）", "OECD与完整名称同指一个机构。"],
  ["economic", "", "adj.", "经济的", "机构名称Economic Cooperation & Development指经济合作与发展。", "economic cooperation（经济合作）", "economic涉及经济，economical偏节约，不能随意替换。"],
  ["cooperation", "", "n.", "合作", "在经合组织全名中与Development并列。", "economic cooperation（经济合作）", "此词出现在数据来源的名称，不是文章另给的报业复苏原因。"],
  ["development", "developments", "n.", "发展", "机构名称中与Cooperation并列，指经济发展。", "economic development（经济发展）", "组织名整体用于说明资料来源。"],
  ["japan", "", "proper n.", "日本", "与美国比较报纸广告收入比例：日本为35%。", "in Japan（在日本）", "地点范围改变，所比较的收入比例口径不变。"],
  ["japanese", "", "adj.", "日本的", "限定newspapers，与美国同类报纸作收入结构和稳定性比较。", "Japanese newspapers（日本报纸）", "此处作定语，不是日本人或日语。"],
  ["proportion", "proportions", "n.", "比例", "the proportion回指广告收入占全部报纸收入的比例。", "the proportion of advertising revenue（广告收入的占比）", "美国87%和日本35%比较同一指标，不是利润率。"],
  ["stable", "", "adj.", "稳定的", "日本报纸较少依赖广告，因此经营比美国报纸更稳定。", "much more stable（稳定得多）", "much加强比较级；稳定不是完全没有风险。"],
  ["damage", "damages", "n. uncountable", "损害；裁撤带来的损失", "much of the damage作主语，说明削减主要集中在哪些报道业务。", "much of the damage（很大一部分损害）", "此处不可数，谓语用has；不是赔偿金damages义。"],
  ["area", "areas", "n.", "领域；区域", "末段areas指特色不足的报道业务领域；题目27的these areas则指郊区。", "areas where newspapers are least distinctive（报纸最缺乏特色的领域）", "由修饰和指代区分业务领域与地理区域。"],
  ["car", "cars", "n.", "汽车", "car前置限定reviewers或reviews，指汽车评论员或汽车评测。", "car and film reviews（汽车评测与影评）", "汽车是评论的对象，不是被裁的人员。"],
  ["science", "", "n.", "科学", "science前置限定reporters，指科学报道记者。", "science reporters（科学记者）", "和general business共同划分两类报道岗位。"],
  ["general", "", "adj.", "一般的；综合性的", "general business reporters指普通商业新闻记者。", "general business reporters（一般商业报道记者）", "general修饰business报道类型，不是总干事职衔。"],
  ["foreign", "", "adj.", "驻外的；国外的", "foreign bureaus为报社设在国外的采编机构。", "foreign bureaus（驻外新闻机构）", "原文说机构被裁撤，题目另问其作用，不能由裁撤自动推出关键地位。"],
  ["cut", "cuts cutting", "v.（过去分词）", "削减；裁撤", "have been cut off为现在完成时被动，表示驻外机构遭裁撤。", "cut off foreign bureaus（裁撤驻外机构）", "cut过去式和过去分词同形，当前位置由have been判为过去分词。"],
  ["result", "results", "n.", "结果", "as a result承接岗位和机构裁撤，说明内容因此不全面。", "as a result（因此；结果）", "不带of宾语；结果是覆盖缩减，不是报业已经消亡。"],
  ["para", "", "n. abbreviation", "段（paragraph的缩写）", "题干Para. 1指原卷第一段，与Lines3-4共同定位引文。", "Para. 1（第一段）", "按原段核对；页面断行不会改写真题行号。"],
  ["author", "authors", "n.", "作者", "the author indicates询问文章作者借引句要表明什么。", "the author indicates（作者表明）", "作者的表达意图与政府讨论方案不是同一层。"],
  ["say", "says said saying", "v.", "说；表述", "By saying后接引文，询问作者借这句话表达的意思。", "by saying something（通过说某句话）", "saying为介词by后的动名词，逻辑主语是作者。"],
  ["fail", "failed fails failing", "v.", "未能；没有做到", "failed to get state subsidies声称未能得到补贴，是选项自身的命题。", "fail to get subsidies（未能获得补贴）", "是否符合原文需另核证据，不能把讨论补贴改成失败结果。"],
  ["get", "gets got getting", "v.", "获得", "get state subsidies为获得政府补贴，接在failed to后。", "get state subsidies（获得国家补贴）", "get直接接宾语，不含get over克服的结构。"],
  ["situation", "situations", "n.", "处境；局面", "a desperate situation概括报纸当时的严重困境。", "a desperate situation（严重困境）", "situation为可数名词，前面用a；不是断言已经消亡。"],
  ["probably", "", "adv.", "很可能；大概", "题目用probably要求依据求生措施推断拒送的最可能原因。", "probably because（很可能因为）", "保留推断性质，不宣称原文给出了精确配送费用。"],
  ["want", "wanted wants wanting", "v.", "想要", "wanted to reduce costs表示报社采取行动的经营目的。", "want to reduce costs（想降低成本）", "want后接不定式，不是want somebody to do结构。"],
  ["reduce", "reduced reduces reducing", "v.", "降低；减少", "reduce costs为降低经营支出。", "reduce costs（降低成本）", "减少的是成本，不是读者数量或报业收入。"],
  ["cost", "costs", "n.", "成本；费用", "作reduce宾语，说明拒送意在降低经营成本。", "reduce costs（降低成本）", "此处复数名词，不是cost使花费的第三人称动词。"],
  ["report", "reported reports reporting", "v.", "报道", "reported little about these areas声称记者很少报道这些郊区。", "report little about an area（很少报道某地区）", "选项为过去式主动，不是名词报告。"],
  ["compare", "compared compares comparing", "v.（过去分词）", "比较", "Compared with引出日本报纸的美国同类比较对象。", "compared with American counterparts（与美国同类相比）", "过去分词短语，逻辑上比较的是两国报纸。"],
  ["counterpart", "counterparts", "n.", "对应的同类事物", "American counterparts指日本报纸的美国同类，即美国报纸。", "American counterparts（美国的同类报纸）", "保持比较对象同类，不能译成美国记者。"],
  ["affect", "affected affects affecting", "v.（过去分词）", "影响", "are less affected by readership声称受读者规模影响更少。", "be affected by readership（受到读者数量的影响）", "被动结构不表示日本报纸主动改变读者。"],
  ["readership", "", "n.", "读者群；读者数量", "by readership将读者群规模作为影响报纸的因素。", "be affected by readership（受读者规模影响）", "读者影响与广告依赖是不同命题，须核对证据。"],
  ["infer", "inferred infers inferring", "v.（过去分词）", "推断", "can be inferred from the last paragraph要求由末段依据推出内容。", "infer from the last paragraph（根据末段推断）", "推断限于证据合理支持的范围，不补未给出的因果。"],
  ["last", "", "adj.", "最后的", "限定paragraph，指本文第五段。", "the last paragraph（最后一段）", "不是动词持续，也不是last year中的去年。"],
  ["paragraph", "paragraphs", "n.", "段落", "the last paragraph要求根据原卷末段判断当前报业。", "the last paragraph（最后一段）", "段落边界依原卷五段，不依当前屏幕换行。"],
  ["current", "", "adj.", "当前的", "限定newspaper business，要求理解如今报业的取舍。", "the current newspaper business（当前报业）", "时间范围是现状，不把过去全面性的价值直接沿用到现在。"],
  ["essential", "", "adj.", "必不可少的；重要的", "限定feature，强调独特性作为报纸特点的重要程度。", "an essential feature（必要特点）", "是否成立须结合裁撤领域与末句对全面性的判断。"],
  ["failure", "failures", "n.", "失败", "the failure of newspaper在选项中被归因于全面性。", "be to blame for failure（应为失败负责）", "不再是优势和导致失败不是同一因果命题。"],
  ["play", "played plays playing", "v.", "发挥；起（作用）", "play a crucial role为发挥关键作用，主语是驻外机构。", "play a crucial role（发挥关键作用）", "play与role搭配，不取玩耍义。"],
  ["crucial", "", "adj.", "至关重要的", "限定role，选项声称驻外机构发挥关键作用。", "a crucial role（关键作用）", "程度很强，需要原文证据，不能由被裁撤自动推出。"],
  ["role", "roles", "n.", "作用", "作play宾语，指驻外机构在报业中的经营作用。", "play a role in the business（在行业中发挥作用）", "in限定作用领域，不是剧中人物角色。"],
  ["lose", "lost loses losing", "v.（过去分词）", "失去", "have lost their interest表示兴趣已经消失这一选项命题。", "lose interest in reviews（对评论失去兴趣）", "读者兴趣消失不能由评论员裁撤直接推出。"],
  ["appropriate", "", "adj.", "合适的；恰当的", "most appropriate title要求标题范围和评价强度均匹配全文。", "the most appropriate title（最恰当的标题）", "不能只因含有文章局部名词就判断标题恰当。"],
  ["title", "titles", "n.", "标题", "title for this text指这篇文章的标题，中心名词为title。", "a title for this text（本文标题）", "不是头衔义；标题选项允许省略式表达。"],
  ["text", "texts", "n.", "文章；文本", "this text指当前报业阅读文章，要求按全文选择标题。", "this text（这篇文章）", "范围比单句、单段更广。"],
  ["struggle", "struggled struggles struggling", "v.（现在分词）", "艰难努力；奋力应对", "Struggling for Survival在标题中补充说明美国报纸正奋力求生。", "struggle for survival（艰难求生）", "标题省略系助动词，不把Struggling标作独立名词。"],
  ["survival", "", "n.", "生存", "for Survival说明努力目标是保持经营、生存下去。", "struggle for survival（艰难求生）", "生存与兴旺不同，和付出代价可以同时成立。"],
  ["story", "stories", "n.", "故事；经历", "A Hopeless Story以经历概括报业处境，并给出无望的评价。", "a hopeless story（一段无望的经历）", "此处标题评价需与全文存活和复苏事实对照。"],

  ["refuse", "refused refuses refusing", "v.", "拒绝", "refuse delivery指拒绝提供配送，refused为27题题干中的过去式。", "refuse delivery（拒绝配送）", "refuse可接名词或to do，不能因复用词条丢失本篇过去式。"],
  ["sweep", "swept sweeps sweeping", "v.", "席卷", "swept through newsrooms指裁员风暴波及新闻编辑部，表现行业重组影响的广泛。", "sweep through newsrooms（席卷编辑部）", "swept为过去式和过去分词，此处为定语从句过去时。"],
  ["thrive", "thrived thrives thriving", "v.", "兴旺；繁荣", "30题A Thriving Business中的thriving为分词形容词，夸大报业复苏程度。", "a thriving business（兴旺的行业或企业）", "survive只说明存活，thrive强调繁荣，两者不能混同。"],
  ["whatever", "", "interrogative pron.", "究竟什么；到底怎么回事", "开篇Whatever happened to...是加强语气的疑问，质疑原来的消亡预言。", "whatever happened to something（某事究竟怎么样了）", "不同于whatever happens无论发生什么，不引让步从句。"],
  ["death", "deaths", "n.", "消亡；终结", "death of newspapers比喻报业衰亡，是被质疑的旧预言。", "the death of newspapers（报纸的消亡）", "与人的生理死亡不同，不能把反问写成已发生的事实。"],
  ["recession", "recessions", "n.", "经济衰退", "给报纸广告与读者收入带来进一步压力。", "an economic recession（经济衰退）", "与行业长期转型不同，recession侧重经济活动萎缩。"],
  ["threaten", "threatened threatens threatening", "v.", "有可能造成坏结果；威胁", "threatened to remove表示衰退眼看要夺走剩余资源，非口头恐吓。", "threaten to remove revenue（可能夺走收入）", "threaten强调风险，不等于结果已经全部发生。"],
  ["reader", "readers", "n.", "读者", "报纸的消费与付费对象，与广告商构成两大收入来源。", "revenue from readers（来自读者的收入）", "reader读者、read阅读、readership读者群为不同词位。"],
  ["flee", "fled flees fleeing", "v.", "逃离；转移", "had not already fled to the internet比喻广告与读者尚未转向网络的部分。", "flee to the internet（转向互联网）", "fled是过去式及过去分词，to引去向。"],
  ["chronicle", "chronicling chronicled chronicles", "v. / proper n.", "记述；《纪事报》名的组成部分", "同句Chronicle是报纸名称，chronicling为正在记述，构成文字呼应。", "chronicle one's own doom（记述自身厄运）", "不能把报纸专名出现的Chronicle一律标成谓语动词。"],
  ["doom", "", "n.", "厄运；毁灭前景", "their own doom指报纸对自身濒临衰亡处境的描述。", "face doom（面临毁灭）", "比ordinary difficulty一般困难强，说明危机严重。"],
  ["trade", "trades traded trading", "n.", "贸易；商业活动", "Federal Trade Commission中的Trade为机构名组成，说明委员会所监管的贸易领域。", "Federal Trade Commission（联邦贸易委员会）", "trade在不同语境可为贸易名词或交易动词，本句专名不拆义。"],
  ["commission", "commissions", "n.", "委员会", "Federal Trade Commission指召开报业讨论的政府机构。", "a government commission（政府委员会）", "同词可表示佣金或委托任务，本文取机构义。"],
  ["launch", "launched launches launching", "v.", "发起；启动", "launched a round of talks指发起会谈而非发射实体。", "launch talks（启动会谈）", "与hold举行不同，launch强调开始一项行动。"],
  ["round", "rounds", "n.", "一轮；一系列", "a round of talks以round量化一轮会谈。", "a round of talks（一轮会谈）", "不是形容词圆的或介词围绕。"],
  ["talk", "talks talked talking", "n.", "会谈；讨论", "复数talks作launched的宾语，about后说明议题。", "talks about reform（关于改革的会谈）", "本句不是第三人称单数动词交谈。"],
  ["save", "saved saves saving", "v.", "挽救；使免于衰亡", "save newspapers指让报纸生存下去，而非节省纸张。", "save an industry（挽救一个行业）", "不同于save money省钱，save由宾语决定意义。"],
  ["charitable", "", "adj.", "慈善性质的", "修饰corporations，表示讨论中一种机构转型方案。", "charitable corporations（慈善性质的机构）", "不是说机构性格慷慨，也没有宣告已经转为非营利组织。"],
  ["state", "states", "n.", "国家；政府", "the state作subsidize主语，代表可能提供补贴的政府。", "state subsidies（国家补贴）", "不是美国某州的名称，也不是状态义。"],
  ["subsidize", "subsidized subsidizes subsidizing", "v.", "补贴；给予经济资助", "Should the state subsidize them是探讨是否提供财政支持。", "subsidize newspapers（补贴报纸）", "与take over接管不同，资助不必然取得所有权。"],
  ["hold", "held holds holding", "v.", "举行；召开", "hold another meeting表示委员会将再召开会议。", "hold a meeting（举行会议）", "不是用手举着，也非hold an opinion持观点。"],
  ["meeting", "meetings", "n.", "会议", "another meeting为hold宾语，是独立名词，不计入meet动词原形。", "another meeting（另一场会议）", "与meet会面存在词族联系，但此处不是分词。"],
  ["discussion", "discussions", "n.", "讨论", "the discussions回指政府机构组织的报业救济讨论。", "discussions about newspapers（关于报纸的讨论）", "discuss为动词，discussion为独立派生名词。"],
  ["date", "dates", "n.", "时效；日期", "out of date整体指讨论已不合当下情况，非约会义。", "out of date（过时的）", "up to date与其相反，表示跟上当前情况。"],
  ["little", "", "det.", "几乎没有", "little sign of crisis否定意味明显，不能译成有一点危机迹象。", "little sign of recovery（几乎没有复苏迹象）", "a little有一点，little几乎没有，冠词改变语气。"],
  ["brazilian", "brazilians", "adj.", "巴西的", "与German并列修饰papers，表示两个国家的报纸。", "Brazilian papers（巴西报纸）", "形容词不因papers复数而变化。"],
  ["paper", "papers", "n.", "报纸；报社", "本篇多次以papers替代newspapers，指新闻出版机构与产品。", "American papers（美国报纸）", "不取学术论文或试卷义；不可数paper还可指纸张。"],
  ["shrug", "shrugged shrugs shrugging", "v.", "甩开；不受影响（与off连用）", "shrug off the recession表示摆脱衰退冲击。", "shrug off a recession（摆脱经济衰退冲击）", "shrug基本义耸肩，但此处短语不逐词译动作。"],
  ["inhabit", "inhabited inhabits inhabiting", "v.", "处于；身处", "inhabit the most troubled corner比喻处在行业最困难的一部分。", "inhabit a troubled corner of an industry（身处行业的困难角落）", "比live in更正式，可用于比喻领域而非真实居所。"],
  ["troubled", "", "adj.", "陷入困境的", "most troubled修饰corner，强调美国报业受困程度。", "a troubled industry（陷入困境的行业）", "不是被某个人打扰的短暂情绪。"],
  ["corner", "corners", "n.", "角落；领域中的一部分", "the most troubled corner of the global industry指全球报业最困难的区域。", "a corner of an industry（行业中的一部分）", "比喻义，不是道路拐弯处。"],
  ["return", "returned returns returning", "v.", "恢复；回到", "return to profit表示重新进入盈利状态。", "return to profit（恢复盈利）", "不等于利润率已回到危机前水平。"],
  ["margin", "margins", "n.", "利润率；幅度", "20% profit margins指盈利占收入比例，不是盈利绝对金额。", "profit margins（利润率）", "同词可指页边空白、差距，本文由profit确定财务义。"],
  ["routine", "routines", "adj.", "常见的；惯常的", "were routine作系表，形容几年前常见的20%利润率。", "routine profits（惯常的盈利）", "这里不是名词日常程序，词性由were后位置决定。"],
  ["fun", "", "n. uncountable", "乐趣；轻松愉快的体验", "not much fun是轻描淡写地说复苏并不轻松。", "not much fun（并不好受）", "不能只按娱乐活动理解，后文裁员说明代价。"],
  ["afloat", "", "adj. predicative", "维持经营；免于破产", "stay afloat以船保持浮起比喻企业存活。", "stay afloat（维持经营）", "多作表语，不理解为报社建筑漂在水上。"],
  ["push", "pushing pushed pushes", "v.", "推下；进一步推进", "pushing journalists overboard比喻裁员；measures be pushed further指进一步推行措施。", "push measures further（进一步推行措施）", "根据宾语区分推下记者的比喻与推进措施。"],
  ["journalist", "journalists", "n.", "记者；新闻工作者", "裁员使报纸维持经营，但损害新闻从业者利益。", "lay off journalists（裁减记者）", "与editor编辑、reporter采访记者有职责侧重差别。"],
  ["overboard", "", "adv.", "从船上落下；被抛出（比喻裁员）", "push journalists overboard延续stay afloat的航船比喻。", "push somebody overboard（把某人推下船）", "这里不描述真实人身伤害，而是岗位被牺牲。"],
  ["society", "societies", "n.", "协会；学会", "American Society of News Editors为专业组织名，不是整个美国社会。", "a professional society（专业协会）", "society还有社会或社交界义，须结合专名。"],
  ["editor", "editors", "n.", "编辑", "组织名称News Editors说明由新闻编辑人组成。", "news editors（新闻编辑）", "edit为编辑动词，editor为人员名词，分别计数。"],
  ["reckon", "reckons reckoned reckoning", "v.", "估计；判断", "reckons that后接协会对岗位流失数量的估计。", "reckon that jobs have gone（估计岗位已流失）", "与prove证明不同，reckon保留估计属性。"],
  ["newsroom", "newsrooms", "n.", "新闻编辑部", "newsroom jobs是采编岗位；newsrooms复数为遭遇裁员的部门。", "newsroom jobs（新闻采编岗位）", "不是供公众阅读新闻的阅览室。"],
  ["go", "goes went gone going", "v.", "消失；被裁减", "jobs、reviewers have gone表示岗位或人员不再保留。", "jobs have gone（岗位被裁撤）", "与普通去某地不同，本文gone含失去岗位的结果。"],
  ["pay", "paying paid pays", "v.", "支付", "pay more for slimmer products说明读者花更多钱买更薄的报纸。", "pay for a newspaper（付费买报）", "不取pay attention注意的搭配义。"],
  ["slim", "slimmer slimmest", "adj.", "更薄的；内容更少的", "slimmer products比喻报纸篇幅缩减，不是身材苗条。", "slimmer newspapers（更薄的报纸）", "比较级双写m；slim还可表示机会很小，如a slim chance。"],
  ["nerve", "nerves", "n.", "胆量；冒失的勇气", "have the nerve to do常含批评或惊讶，说明竟然敢拒送。", "have the nerve to refuse（竟敢拒绝）", "不取身体神经义，与neutral courage的语气不同。"],
  ["delivery", "deliveries", "n.", "配送；送达", "delivery to distant suburbs表示向偏远郊区送报服务。", "newspaper delivery（送报）", "不同于演讲表达方式或分娩义，to引去向。"],
  ["suburb", "suburbs", "n.", "郊区", "distant suburbs为送报距离较远的地带。", "distant suburbs（偏远郊区）", "郊区并非农村的同义词，不能自行改为农场。"],
  ["desperate", "", "adj.", "处境艰难的；迫不得已的", "desperate measures为危急时的非常措施，desperate situation为困境。", "desperate measures（迫不得已的措施）", "不是热切盼望某物的desperate for结构。"],
  ["sadly", "", "adv.", "令人遗憾地", "插入语sadly for many journalists承认进一步缩减对记者不利。", "sadly for workers（令员工遗憾的是）", "评价员工代价，不否认措施让企业存活。"],
  ["balanced", "", "adj.", "均衡的", "balanced businesses解释为读者与广告收入比例更健康。", "balanced revenues（均衡的收入结构）", "不是报道观点的公正性，也不是编辑部人员配比。"],
  ["business", "businesses", "n.", "企业；经营行业", "businesses指报业经营体，newspaper business指整个报业。", "the newspaper business（报业）", "由单复数与修饰语区分经营主体和行业。"],
  ["healthy", "healthier healthiest", "adj.", "合理稳健的；健康的", "healthier mix指更有利于稳健经营的收入搭配。", "a healthier revenue mix（更稳健的收入组合）", "比喻财务结构，不是报纸本身具有身体健康。"],
  ["mix", "mixes mixed mixing", "n.", "组合；搭配", "a mix of revenues以名词表示多来源收入的搭配。", "a mix of revenues（收入组合）", "不是动词把不同收入相加的动作。"],
  ["revenue", "revenues", "n.", "营业收入；收益来源", "readers与advertisers提供的总收入，区别于扣除成本后的profit。", "advertising revenue（广告收入）", "revenue收入不等于profit利润，比例基数不能混淆。"],
  ["advertiser", "advertisers", "n.", "广告主；投放广告者", "与readers并列，说明报业收入来自不同付费群体。", "readers and advertisers（读者与广告主）", "不等于advertisement广告作品或advertising广告业务。"],
  ["highly", "", "adv.", "非常；高度地", "highly修饰unusual强调不同寻常程度，保留独立副词词条。", "highly unusual（极不寻常的）", "high表示位置高时可作形容词或副词；highly侧重抽象程度，不合并为词形变化。"],
  ["reliance", "", "n.", "依赖", "reliance on ads说明美国报业的广告收入依赖。", "reliance on advertising（对广告的依赖）", "reliance名词与rely动词为派生关系，不能混计原形。"],
  ["ad", "ads", "n.", "广告（advertisement的缩写）", "on ads中复数广告代表报社的广告业务收入。", "revenue from ads（广告带来的收入）", "ad是缩写词，不是advertising的屈折形式。"],
  ["fully", "", "adv.", "足足；高达", "Fully置于87%前强调比例之高，非说达到100%。", "fully 87 percent（足足87%）", "fully有完全义，但数字前常表达惊讶强调。"],
  ["come", "came comes coming", "v.", "来自", "came from advertising说明收入来源，came过去时对应2008数据。", "come from advertising（来自广告）", "from不能漏译成收入自己到来的动作。"],
  ["oecd", "", "proper abbreviation", "经济合作与发展组织", "括号内缩写与前面Organization for Economic Cooperation & Development同指。", "OECD data（经合组织数据）", "机构缩写按整体保留，不能拆为字母词义。"],
  ["surprisingly", "", "adv.", "令人惊讶地", "Not surprisingly对前文收入比例推导的稳定结果作评价。", "not surprisingly（不足为奇地）", "不可漏掉not，否则态度相反。"],
  ["whirlwind", "whirlwinds", "n.", "旋风；猛烈的变革风暴", "whirlwind比喻席卷编辑部的裁员重组冲击。", "a whirlwind of change（急剧变革的风暴）", "不是文章报道自然灾害。"],
  ["harm", "harmed harms harming", "v.", "损害；伤害", "harmed everybody指重组对新闻从业人员的冲击。", "harm workers（损害员工利益）", "与damage常接事物相比，harm可直接接人，本文含职业利益。"],
  ["concentrate", "concentrated concentrates concentrating", "v.", "集中；主要落在", "damage has been concentrated in areas表示裁减集中于某些业务领域。", "be concentrated in an area（集中于某个领域）", "be concentrated in说明集中分布的领域；in后为范围。"],
  ["distinctive", "", "adj.", "独特的；有鲜明特色的", "least distinctive指报纸与其他信息来源相比最缺乏特色的业务领域。", "distinctive reporting（有特色的报道）", "distinct清楚可辨与distinctive有特色有交集但不等同。"],
  ["film", "films", "n.", "电影", "film reviewers为电影评论员，名词film前置限定人员。", "film reviews（影评）", "同词还可指薄膜、胶片；本文由reviewers确定电影义。"],
  ["reviewer", "reviewers", "n.", "评论员；评论者", "car and film reviewers指专门评价汽车或电影的人员。", "film reviewers（电影评论员）", "reviewer评论员不同于review评论作品，不能归同一原形。"],
  ["reporter", "reporters", "n.", "记者", "science and general business reporters为被裁岗位的另外两类记者。", "science reporters（科学记者）", "与editor编辑分工不同，reporter侧重采访报道。"],
  ["bureau", "bureaus bureaux", "n.", "新闻机构；办事处", "foreign bureaus指报纸在国外的新闻采编机构。", "foreign bureaus（驻外新闻机构）", "本文不指政府某局；复数两种形式都保留在同一词位。"],
  ["savagely", "", "adv.", "猛烈地；大幅度地", "修饰cut off，强调机构被裁撤的强度。", "savagely cut costs（大幅削减成本）", "比喻财务收缩的猛烈，不是在评价某民族野蛮。"],
  ["complete", "", "adj.", "全面的；完整的", "less complete说明报纸报道覆盖范围缩小，不是谓语完成任务。", "complete coverage（全面报道）", "与动词complete a task不同；形容词比较用more/less。"],
  ["completeness", "", "n.", "全面性；完整性", "作为末句主语，讨论全面覆盖是否仍是报纸的优点。", "completeness of coverage（报道的全面性）", "不能把派生名词合并到complete的原形次数。"],
  ["virtue", "virtues", "n.", "优点；长处", "a virtue表示一种经营优势，非道德品行评价。", "a virtue of a product（产品的一项优点）", "virtue还可指美德；by virtue of则是凭借的固定搭配。"],
  ["line", "lines lined lining", "n.", "行；文本行", "题干Lines3-4用于定位选文中的文本行。", "the first line（第一行）", "不是生产线或电话线路；范围定位以原段内容为准。"],
  ["indicate", "indicates indicated indicating", "v.", "表明；暗示", "26题询问借报纸自述厄运说明何种处境。", "indicate a crisis（表明危机）", "与state直说相比，indicate可通过描述间接表现。"],
  ["neglect", "neglected neglects neglecting", "v.", "忽视；未加关注", "26题干扰项，报纸已报道自身厄运并未忽视危机。", "neglect warning signs（忽视警示迹象）", "不是未获得补贴的同义说法。"],
  ["subsidy", "subsidies", "n.", "补贴；资助", "state subsidies在干扰项中出现，原文只讨论是否应提供。", "state subsidies（国家补贴）", "subsidy与subsidize为名动派生，分别保留词条。"],
  ["subscriber", "subscribers", "n.", "订户；订阅者", "27题干扰项用subscribers指付费订报的人，原文未说他们投诉。", "newspaper subscribers（报纸订户）", "reader读者不一定付费订阅，范围更广。"],
  ["complain", "complained complains complaining", "v.", "抱怨；投诉", "complained about slimmer products属于干扰项虚构的原因。", "complain about a service（投诉某项服务）", "complain about说明所抱怨事项；原文没有此事实。"],
  ["source", "sources", "n.", "来源", "sources of revenue指收入渠道，题目须区分渠道数量与比例。", "sources of revenue（收入来源）", "比例更均衡不等于来源种类更多。"],
  ["dependent", "", "adj.", "依赖的", "less dependent on advertising概括日本广告收入占比较低。", "be dependent on advertising（依赖广告）", "less降低依赖程度，不等于完全不依赖。"],
  ["distinctiveness", "", "n.", "独特性；差异化特征", "29题正确选项概括报纸在缩减全面覆盖后更应保留的优势。", "distinctiveness of newspapers（报纸的独特性）", "与completeness全面性形成文章结尾的价值对比。"],
  ["feature", "features", "n.", "特点；特征", "an essential feature为名词短语，不是动词重点展示。", "an essential feature（必要的特征）", "feature作动词可表示以……为特色，本文选项为名词。"],
  ["blame", "blames blamed blaming", "v.", "归咎；责怪", "be to blame for表应为某事负责，是29题过度因果推断的结构。", "be to blame for failure（应为失败负责）", "不再是优势不等于就是失败原因。"],
  ["interest", "interests", "n.", "兴趣", "lost their interest in...表示对内容失去兴趣，是未被原文证明的干扰项。", "interest in film reviews（对影评的兴趣）", "不取利益或利息义；in引兴趣对象。"],
  ["review", "reviews", "n.", "评论；评测", "car and film reviews是汽车评测与影评，指评论内容。", "car and film reviews（汽车评测和影评）", "评论员被裁不证明读者失去兴趣。"],
  ["wind", "winds", "n.", "风", "Gone with the Wind标题借随风消失的意象，暗示报纸已衰亡，故不合主旨。", "gone with the wind（随风而逝）", "同形wind作动词有缠绕义且发音不同，本文为名词。"],
  ["hopeless", "", "adj.", "没有希望的", "A Hopeless Story把报业处境说成无望，忽略恢复盈利与措施奏效。", "a hopeless situation（无望的处境）", "与struggling仍在奋力求生不同，hopeless过于绝对。"],
];
const reviewed = reviewedLexicon(rows);
export const passage2011P2Lexicon = reviewed.entries;
export const passage2011P2LemmaAliases: Record<string, string> = { ...reviewed.aliases, lines3: "line", meeting: "meeting", highly: "highly", being: "be" };
export const passage2011P2CollocationGlosses = reviewed.glosses;
export const passage2011P2FormPartOfSpeech: Record<string, string> = {
  chronicle: "proper n.（报纸名称）", chronicling: "v.-ing（进行时分词）", routine: "adj.", lines3: "n.（原卷行号连写）", little: "det.（否定数量）", trade: "n.（机构名称组成）", talks: "n.（复数）", meeting: "n." , balanced: "adj.", complete: "adj.", feature: "n.", interest: "n.", reviews: "n.（复数）", fully: "adv.（强调数量）", thriving: "adj.（分词定语）", struggled: "v.-ed", struggling: "v.-ing（现在分词）", right: "adj.", general: "adj.", foreign: "adj.", german: "adj.", american: "adj.", japanese: "adj.", own: "det.", for: "prep.", on: "prep.", off: "particle", out: "adv.（搭配组成）", near: "adj.", have: "aux.", had: "aux.", has: "aux.", becoming: "v.-ing（进行时分词）",
};
const otherMeanings: Record<string, string[]> = {
  paper: ["不可数n. 纸张；可数n. 论文、试卷、文件。语境不同不要一律译成报纸。"],
  commission: ["佣金；委托任务；v. 委托制作或开展某事。"],
  margin: ["页边空白；边缘；差距，如a narrow margin微弱差距。"],
  nerve: ["神经；紧张不安（常用nerves）；冷静的勇气，如lose one's nerve失去勇气。"],
  delivery: ["演讲的表达方式；交付；分娩。本文为送报配送。"],
  virtue: ["美德；德行。by virtue of凭借、由于，与a virtue一项优点分开。"],
  save: ["节省金钱或时间；保存文件；保留。本文save newspapers为挽救报业。"],
  interest: ["利益；利息；v. 使感兴趣。interest in...在本题表示对内容的兴趣。"],
};
for (const [headword, meanings] of Object.entries(otherMeanings)) passage2011P2Lexicon[headword].otherMeanings = meanings;

export const passage2011P2SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2011-p2-s11": { shrug: { contextualSubstitutions: [{ label: "weather", chinese: "经受住；渡过", fit: "with-adjustment", adjustment: "把shrugged off整体改为weathered；weather为及物动词，不保留off。", rewrittenSentence: "German and Brazilian papers have weathered the recession.", nuance: "weather强调经受住困难，原文shrug off更突出没有被冲击拖垮；均说明报纸挺过衰退。", target: "word:weather" }] } },
  "2011-p2-s1": { whatever: { contextualMeaning: "究竟怎么回事", use: "强调疑问主语，质疑报纸消亡预言的下文，不是无论什么。" } },
  "2011-p2-s3": { that: { partOfSpeech: "relative pron.", contextualMeaning: "指尚未转移的广告和读者", use: "作had not fled主语，限定advertising and readers。" }, have: { partOfSpeech: "aux.", contextualMeaning: "构成过去完成时", use: "had not already fled说明此前尚未转向网络。" } },
  "2011-p2-s4": { own: { contextualMeaning: "自身的", use: "their own doom强调报纸报道自己的厄运。" } },
  "2011-p2-s5": { trade: { contextualMeaning: "贸易（委员会名称组成）", use: "Federal Trade Commission为机构专名，Trade在此限定委员会的贸易监管职能。" } },
  "2011-p2-s6": { they: { contextualMeaning: "报纸；报社", use: "提问报纸是否应改制为慈善机构，不指委员会。" } },
  "2011-p2-s7": { they: { partOfSpeech: "pron.（宾格them）", contextualMeaning: "这些报纸", use: "作subsidize宾语，是拟议接受补贴的对象。" } },
  "2011-p2-s8": { it: { contextualMeaning: "美国联邦贸易委员会", use: "回指会谈主办方，不是报纸或政府补贴这件事。" } },
  "2011-p2-s10": { there: { contextualMeaning: "存在句引导词", use: "there is little sign以形式引导存在，真正主语为little sign。" }, little: { contextualMeaning: "几乎没有", use: "little sign是否定量，不是a little少量存在。" } },
  "2011-p2-s12": { which: { contextualMeaning: "这些美国报纸", use: "非限制性定语从句主语，回指American newspapers。" }, have: { partOfSpeech: "aux.", contextualMeaning: "构成现在完成时", use: "survived和returned共用have，两个分词并列。" } },
  "2011-p2-s13": { that: { partOfSpeech: "relative pron.", contextualMeaning: "那些20%的利润率", use: "关系代词作were主语，限定profit margins。" }, few: { contextualMeaning: "几个（a few）", use: "a few years ago为几年前，不是few years的几乎没有几年。" }, same: { contextualMeaning: "仍然；毕竟（all the same）", use: "不是数额相同，而是虽利润率较低仍有利润。" } },
  "2011-p2-s14": { it: { contextualMeaning: "报业求生复苏的过程", use: "回指前段经历，不是形式主语。" } },
  "2011-p2-s15": { push: { contextualMeaning: "推下（比喻裁员）", use: "push journalists overboard与stay afloat同为船的比喻，表示靠裁员维持经营。" }, by: { contextualMeaning: "通过；靠", use: "by doing引手段，动作主体为Many papers。" } },
  "2011-p2-s16": { that: { partOfSpeech: "conj.", contextualMeaning: "引出估计内容", use: "that不作主宾，后接13,500 newsroom jobs have gone完整从句。" } },
  "2011-p2-s17": { for: { contextualMeaning: "为购买……", use: "pay money for products表示钱与购买对象，不是持续时间。" } },
  "2011-p2-s18": { have: { partOfSpeech: "v.", contextualMeaning: "有胆量；竟敢（have the nerve）", use: "had是实义过去时，后接the nerve和说明行为的to refuse，不是完成时助动词。" } },
  "2011-p2-s19": { they: { contextualMeaning: "这些应急措施", use: "they can be pushed further的主体是measures，不是记者。" }, one: { partOfSpeech: "pron.（复数ones）", contextualMeaning: "那些措施", use: "the right ones中ones替代measures，避免重复。" }, push: { contextualMeaning: "推进；进一步实施", use: "被动be pushed further修饰measures，与第15句推人下船的比喻区分。" } },
  "2011-p2-s20": { with: { contextualMeaning: "伴随着；具有", use: "with a healthier mix补充说明收入结构更均衡的具体含义。" } },
  "2011-p2-s21": { in: { contextualMeaning: "在……方面", use: "in their reliance on ads限定unusual是哪方面不同寻常。" } },
  "2011-p2-s22": { their: { contextualMeaning: "美国报纸", use: "其所有格their限定revenues，承接前句American papers。" }, fully: { contextualMeaning: "足足；高达", use: "数字前强调87%很高，不把它改成百分之百。" } },
  "2011-p2-s23": { proportion: { contextualMeaning: "广告收入占全部收入的比例", use: "与美国87%按同一统计口径比较，不是日本报纸的世界份额。" } },
  "2011-p2-s25": { that: { partOfSpeech: "relative pron.", contextualMeaning: "指裁员重组风暴", use: "that作swept主语，修饰whirlwind。" }, where: { partOfSpeech: "relative adv.", contextualMeaning: "在这些报道领域里", use: "where相当于in which限定areas，不指实际地理区域。" }, least: { contextualMeaning: "最不；程度最低", use: "least distinctive表示独特性最低的那些报道业务。" } },
  "2011-p2-s27": { so: { contextualMeaning: "也一样", use: "So have倒装承接上一句have gone，不表示因此。" }, have: { partOfSpeech: "aux.", contextualMeaning: "承接并省略gone", use: "So have + 主语表示同样被裁减，have不是拥有。" } },
  "2011-p2-s28": { foreign: { contextualMeaning: "驻外的", use: "修饰bureaus，指报纸在国外的新闻机构，不是外来物质。" } },
  "2011-p2-s30": { business: { contextualMeaning: "报业；报纸经营行业", use: "newspaper business为评价全面性是否有利的行业范围。" }, long: { contextualMeaning: "再继续（no longer）", use: "no longer表示如今不再是优点，不是物理长短。" } },
};
