import type { PracticeTask, GrammarConceptId, ErrorCategory } from './learning-model';
const range=(id:string,prompt:string,answer:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[],extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:'range',prompt,options:[],answer,evidence:answer,feedback,conceptId,errorType,hintWords,...extra});
const choice=(id:string,prompt:string,options:string[],answer:number,evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[],extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:'choice',prompt,options,answer:options[answer],evidence,feedback,conceptId,errorType,hintWords,...extra});
const link=(id:string,prompt:string,pairs:Array<[string,string]>,evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[],extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:'link',prompt,options:[...new Set(pairs.map(p=>p[1]))],links:pairs.map(([source,target])=>({source,target})),answer:JSON.stringify(pairs.map(p=>p[1])),evidence,feedback,conceptId,errorType,hintWords,...extra});
const order=(id:string,prompt:string,answer:string[],distractors:string[],evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[],extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:'order',prompt,options:[...answer,...distractors],answer:JSON.stringify(answer),evidence,feedback,conceptId,errorType,hintWords,...extra});
export const passage2011P1Practice:Record<string,PracticeTask[]>={
'2011-p1-s1':[
 link('two-appointments','把两次任职的动词与角色连起来。',[['joined Goldman Sachs\'s board','以外部董事身份加入'],['became president','成为大学校长']],'joined Goldman Sachs\'s board as an outside director','joined接宾语board；became接表语president。角色不同，不能把两次任职合成同一个动作。','basic-svc','predicate',['joined','became','president','as an outside director']),
 choice('later-reference','a year later从哪个时间往后计算？',['2000年1月加入董事会','2009年底受批评','2010年2月离任'],0,'in January 2000; a year later','从前一分句的任职时间向后一年；不能用后文的2009或2010作参照。','time-reference','tense',['later','January'],{mapRevealsAnswer:true})],
'2011-p1-s2':[
 range('negative-accompaniment','划出表示没有招致太多批评的完整伴随短语。','without attracting much criticism','without管动名词attracting及其宾语；不是把managed本身否定。','modifier-prepositional','attachment',['without','attracting','without attracting much criticism']),
 choice('qualified-appearance','apparently与much使原句保留了什么？',['看起来兼顾两职，且没有太多批评','作者保证她完美履职','过去完全没有任何批评'],0,'apparently managed both roles without attracting much criticism','apparently保留外部判断，much使否定不等于没有任何批评；这两项不能漏读。','comparison-scope','option-logic',['apparently','much'])],
'2011-p1-s3':[
 link('let-actors','把let结构的角色对应起来。',[['she','放任行为的主体'],['those enormous bonus payouts','let的宾语、pass的逻辑主语'],['unremarked','通过时未经质疑的状态']],'she have let those enormous bonus payouts pass unremarked','let something do中宾语同时是后面动作的逻辑主语；原文没说西蒙斯本人获得奖金。','object-complement','attachment',['let','pass','unremarked','pass unremarked']),
 range('criticism-reason','划出for引出的完整原因，停止在分号之前。',"for having sat on Goldman's compensation committee",'having sat是完成式动名词，说明此前任职；for解释遭到抨击的原因，后面的反问落实监督失职。','nonfinite-participle','clause-boundary',['for','having','sat',"having sat on Goldman's compensation committee"]),
 choice('failure-not-profit','后半句反问批评的核心是什么？',['对巨额奖金放行未加质疑','西蒙斯亲自获得巨额奖金','她提前辞去大学校长'],0,'how could she have let those enormous bonus payouts pass unremarked','被监督的奖金不能偷换成她本人收入；反问指出的是任职职责未履行。','author-voice','option-logic',['unremarked','under fire'],{mapRevealsAnswer:true})],
'2011-p1-s4':[
 choice('past-reference','had left表明什么？',['到次年2月已经离任，具体日期未说','离职只能发生在2月最后一天','离职先于2000年任职'],0,'By February the next year Ms. Simmons had left the board','过去完成时相对By给出的过去参照点；the next year接上句2009，不给出精确离职日。','time-reference','tense',['By','had','left'],{mapRevealsAnswer:true})],
'2011-p1-s5':[
 link('reported-explanation','区分职位状态与说话来源。',[['The position was just taking up too much time','西蒙斯给出的离职解释'],['she said','标明这句话是谁说的']],'The position was just taking up too much time, she said','引述语归属当事人。作者后文讨论声誉动机，并未把这个说法证明为唯一原因。','author-voice','reference',['position','she','said','taking up too much time'],{mapRevealsAnswer:true})],
'2011-p1-s6':[
 order('expected-role','保留外部董事的应有职责，排回主干；去掉任职范围和品质修饰。',['Outside directors','are supposed to serve','as advisers'],["on a firm's board",'helpful'],'Outside directors are supposed to serve','保留are supposed to，才能表达应有职责而非已兑现的现实；serve as后为角色。','modal-obligation','predicate',['supposed','serve','are supposed to serve']),
 choice('standard-not-praise','第二段这个句子的主要作用是什么？',['提出检验后续行为的职责标准','证明所有董事都已公正履职','要求董事成为股价预测员'],0,'as helpful, yet less biased, advisers','advisers是顾问；supposed to给应有标准，不能直接用作全文positive态度依据。','paragraph-role','passage-logic',['supposed','advisers'],{mapRevealsAnswer:true,leaksToTasks:[{sentenceId:'2011-p1-map',taskId:'role-and-reality'}]})],
'2011-p1-s7':[
 link('two-have-functions','匹配两种have结构。',[['Having made','完成式非谓语，说明先前积累'],['have enough independence','主句谓语与宾语，说明拥有独立性']],'Having made their wealth and their reputations elsewhere, they presumably have enough independence','句首Having没有构成独立有限谓语；主句have才承担对they的陈述，两者主体都为董事。','finite-predicate','predicate',['Having','made','have']),
 choice('infinitive-function','to disagree说明什么？',['独立性足以使董事提出异议','董事为了被反对而积累财富','首席执行官在反对董事'],0,"enough independence to disagree with the chief executive's proposals",'enough加名词再接to do，补充该条件足以支持何种行为；to disagree的执行者仍是they。','nonfinite-infinitive','attachment',['enough','disagree',"disagree with the chief executive's proposals"])],
'2011-p1-s8':[
 range('crisis-condition','划出完整if条件从句，包含两个并列主语。','If the sky and the share price are falling','the sky和the share price共用are falling；outside directors已转入主句。','clause-condition','clause-boundary',['If','falling']),
 link('experience-attachment','把建议与经验的关系连清楚。',[['based on','修饰advice，说明建议依据'],['having weathered their own crises','董事过去渡过危机的经历']],'advice based on having weathered their own crises','advice并不会经历危机；their own回指董事，weather在此为及物动词渡过。','nonfinite-subject','attachment',['based','weathered','their','having weathered their own crises'])],
'2011-p1-s9':[
 range('database-relative','划出修饰database的完整定语从句。','that covered more than 10,000 firms and more than 64,000 different directors between 1989 and 2004','that作covered的主语；数量与年份都是该数据库所覆盖的资料范围，不把年代挂回主句used。','clause-relative','clause-boundary',['that','covered'],{leaksToTaskIds:['data-period']}),
 choice('data-period','1989—2004这段时间说明什么？',['数据库涵盖的观察时期','研究者一定连续研究了15年','西蒙斯任职的完整时期'],0,'between 1989 and 2004','时间短语在covered的从句内部，限定资料覆盖，不提供研究实施起止或西蒙斯任期。','time-reference','attachment',['between'],{mapRevealsAnswer:true})],
'2011-p1-s10':[
 range('embedded-question','划出checked后要核查的完整内容。','which directors stayed from one proxy statement to the next','which directors作内部主语，stayed作谓语；这是“哪些董事仍留任”的嵌入疑问。','clause-object','clause-boundary',['which','checked']),
 choice('next-ellipsis','the next省略了什么？',['proxy statement','完整董事任期','下一所大学'],0,'from one proxy statement to the next','通过前后披露文件核对名单，不能把两次披露擅自推成两届任期。','reference-pronoun','reference',['next','proxy','from one proxy statement to the next'])],
'2011-p1-s11':[
 order('reason-main-clause','去掉原因所针对的事件与概率修饰，排出第一分句主系表。',['The reason','was','age'],['departing a board','directors'],'The most likely reason for departing a board was age','中心是reason，for departing说明什么事件的原因；age是表语，不能算was的宾语。','basic-svc','subject',['reason','was','age']),
 link('selection-attachments','把两个后置限定接回它们说明的对象。',[['by directors','说明谁发生disappearances'],['under the age of 70','限定directors年龄']],'disappearances by directors under the age of 70','70限制董事的年龄，而非公司或研究持续时间；so交代筛选意外离任的理由。','modifier-prepositional','attachment',['by','under','under the age of 70'])],
'2011-p1-s12':[
 link('nested-content','为两层that内容找支配对象。',[['after a surprise departure...increases by nearly 20%','found所报告的整项发现'],['the company will subsequently have to restate earnings','probability所指的事件']],'They found that after a surprise departure, the probability that the company will subsequently have to restate earnings increases by nearly 20%','外层that接found；内层that解释概率的内容，不是定语关系代词。','complement-content','clause-boundary',['that','found','probability'],{leaksToTaskIds:['increasing-subject']}),
 choice('increasing-subject','increases增长的究竟是什么？',['重述盈利数据的概率','公司的利润金额','董事的年龄'],0,'the probability that the company will subsequently have to restate earnings increases','earnings在内层作restate宾语；外层主语中心probability才与increases对应。','subject-head','subject',['probability','earnings','increases','restate earnings']),
 choice('relative-increase','by nearly 20%可以准确译成哪项？',['相对增加近20%','一定增加20个百分点','增加到20%'],0,'increases by nearly 20%','by表示变化幅度，原文没有说百分点；to才用于到达水平。','comparison-scope','option-logic',['by','nearly','increases by nearly 20%'])],
'2011-p1-s13':[
 link('separate-outcomes','匹配两种后果与各自的主体。',[['increases','被列入诉讼的可能性'],['is likely to perform worse','公司的股票']],'The likelihood of being named in a federal class-action lawsuit also increases, and the stock is likely to perform worse','不能把股票perform worse移作诉讼结果；被列入诉讼并非败诉。','subject-head','subject',['likelihood','named','stock','perform','being named in a federal class-action lawsuit','is likely to perform worse'])],
'2011-p1-s14':[
 link('two-comparisons','两个larger分别说明什么？',[['to be larger中的larger','关联效应的幅度'],['larger firms中的larger','公司的规模']],'The effect tended to be larger for larger firms','第一个形容词作be表语，第二个修饰firms；tended保留总体趋势限制。','comparison-scope','attachment',['effect','larger','firms','tended to be larger'])],
'2011-p1-s15':[
 range('concession-boundary','划出完整让步从句，停止在逗号之前。','Although a correlation between them leaving and subsequent bad performance at the firm is suggestive','让步内部有主语correlation、系动词is和表语suggestive；后面的it才是主句主语。','negation-contrast','clause-boundary',['Although','suggestive']),
 choice('not-always','作者否定的是哪一种判断？',['把每一次离职都解释成逃离危机','离任与后续表现存在任何关联','任何董事都不可能逃离危机'],0,'does not mean that such directors are always jumping off a sinking ship','外层not mean管整个含always命题：关联不证明总是预见危机脱身；不是not ever。','negation-contrast','option-logic',['not','always','mean'],{mapRevealsAnswer:true})],
'2011-p1-s16':[
 link('old-and-new-firms','分清leave A for B的两端。',[['riskier, smaller firms','离开的公司A'],['larger and more stable firms','转去的公司B']],'leaving riskier, smaller firms for larger and more stable firms','for引去向，更稳定的是新公司；不能据此推断原公司会变得更稳。','modifier-prepositional','attachment',['for','riskier','stable','leaving riskier, smaller firms for larger and more stable firms'])],
'2011-p1-s17':[
 order('outer-report','暂时去掉条件与让步，重建从外到内的主要判断。',['the researchers','believe','that outside directors','have an easier time of avoiding a blow to their reputations'],['a review of history','bad news breaks'],'the researchers believe that outside directors have an easier time of avoiding a blow to their reputations','最外层研究者believe，内部董事have；shows与breaks分别属于后面的让步和时间从句。','clause-object','predicate',['believe','have']),
 link('nested-relations','把三个连接结构接回它限定的对象。',[['if they leave a firm...','较容易避免声誉受损的条件'],['before bad news breaks','限定leave的时间'],['even if a review of history shows...','即使查明当时在任也保留上述判断']],'if they leave a firm before bad news breaks, even if a review of history shows they were on the board at the time any wrongdoing occurred','条件、时间、让步三层不能平铺成三个并列原因；消息曝光不等于违规发生。','clause-time','attachment',['if','before','even','before bad news breaks'],{leaksToTaskIds:['news-versus-wrongdoing']}),
 choice('news-versus-wrongdoing','这句允许出现哪种时间情况？',['违规时仍在任，但在坏消息公开前已离职','任何违规一定在离职后才发生','离职日期与坏消息公开日期必定相同'],0,'they were on the board at the time any wrongdoing occurred','在任事实对应违规发生时；before只保证离职早于消息曝光。别把两个事件混为一谈，也别把在任推成亲自违规。','time-reference','tense',['before','time','occurred'],{mapRevealsAnswer:true})],
'2011-p1-s18':[
 range('firm-relative','划出修饰Firms的整个who从句。','who want to keep their outside directors through tough times','who作want主语，to keep及时间短语属于从句；may have to create开始主句谓语。','clause-relative','clause-boundary',['who','want']),
 choice('incentive-inference','create incentives与keep directors的关系是什么？',['激励可能有助于留任','董事已被证明必定拒绝激励','激励只可能指强制加薪'],0,'may have to create incentives','公司为了留人可能需要提供激励，支持may stay；may不是必然，incentives也没有限定只能为金钱。','modal-obligation','option-logic',['may','incentives','keep'],{mapRevealsAnswer:true})],
'2011-p1-s19':[
 link('closing-reference','把结尾的衔接与补充对象匹配起来。',[['Otherwise','不提供上一句所说的留任激励'],['once again very popular on campus','补充西蒙斯在大学中的个人处境']],'Otherwise outside directors will follow the example of Ms. Simmons, once again very popular on campus','Otherwise承接条件；popular修饰Ms. Simmons，不是作者称赞外部董事角色。该形容词短语没有显式主谓，不新造完整从句。','reference-pronoun','reference',['Otherwise','popular','once again'],{mapRevealsAnswer:true})],
};
