import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";

const rows: LexiconRow[] = [
  ["rescue", "rescues rescued rescuing", "v.", "挽救；解救", "rescue currency from disintegration可替换save from，保持免于瓦解的目的。", "rescue A from B（挽救A免于B）", "rescue更强调从急迫困境中解救，不能表达节省开支。"],
  ["compete", "competes competed competing", "v.", "争夺；竞争", "37题干扰项说德法争夺领导位置，文中没有此因果依据。", "compete for a position（争夺位置）", "compete for引争夺目标，compete with引竞争对手。"],
  ["crisis", "crises", "n.", "危机", "原文为货币体系危机；37题干扰项另说德法各自国内危机。", "an economic crisis（经济危机）", "crisis单数，crises不规则复数；不因选项出现就把它当事实。"],
  ["regarding", "", "prep.", "关于", "40题句首引出判断对象欧盟前途。", "regarding the future（关于未来）", "此处已经是介词用法，不取regard动词看待。"],
  ["e.g.", "", "abbreviation", "例如", "引出限制企业税率或劳动成本竞争的实例。", "e.g. curbing competition（例如限制竞争）", "例如是举例，不是i.e.也就是的同义重述。"],
  ["remain", "remains remained remaining", "linking v.", "仍然是；保持", "后接贸易集团身份表语，说明危机中优势尚在。", "remain a trading block（仍是贸易集团）", "remain强调原有状态延续，be只陈述状态。"],
  ["union", "unions", "n.", "联盟（此处指欧盟）", "European Union为组织全称，EU为其缩写。", "European Union（欧洲联盟）", "union还可指工会或联合，不同于unit单个单位。"],
  ["eu", "eu's", "proper n. abbreviation", "欧盟", "指原文时代的27国联盟，不等于使用欧元的16国核心。", "EU members（欧盟成员）", "EU与euro zone范围不能互换。"],
  ["sound", "sounded sounds sounding", "linking v.", "听起来", "sound strange为系表，strange说明问题给人的感觉。", "sound strange（听起来奇怪）", "sound还可作声音名词或健全的形容词，此处非发出声响。"],
  ["strange", "stranger strangest", "adj.", "奇怪的；出人意料的", "问题若不久前提出会显得奇怪，与如今担忧对照。", "a strange question（奇怪的问题）", "strange也指陌生的；这里不是外国的foreign。"],
  ["project", "projects project's", "n.", "欧洲一体化计划", "the project回指欧洲联合进程，并非施工项目。", "the European project（欧洲一体化计划）", "project作动词可预测或投射，本篇为名词。"],
  ["great", "greater greatest", "adj.", "程度高的；强的", "greatest cheerleaders指最坚定支持者；greater harmonisation为更大程度协调。", "greater harmonisation（更充分的协调）", "比较级greater、最高级greatest不是独立词位。"],
  ["cheerleader", "cheerleaders", "n.", "热心支持者", "政治比喻，even强调连最坚定的支持者也担忧。", "the project's cheerleaders（计划的热心支持者）", "字面义为啦啦队员；supporter支持者更中性。"],
  ["continent", "continents", "n.", "大陆；此处欧洲", "facing修饰continent，说明欧洲面临三重问题。", "the European continent（欧洲大陆）", "continent不是国家country，也不是内容content。"],
  ["face", "faces faced facing", "v.", "面临", "face a crisis为及物用法，be faced with为被动固定表达。", "face a crisis（面临危机）", "作名词为脸；face问题不必加to。"],
  ["bermuda", "", "proper n.", "百慕大（地名）", "Bermuda triangle在此被用作三项危机困境的比喻。", "Bermuda triangle（百慕大三角）", "原文引号提示比喻，不需要把地理传闻当作事实。"],
  ["triangle", "triangles", "n.", "三角；三重困境的比喻", "of后列债务、人口下降、低增长三项。", "a triangle of problems（三重问题构成的困境）", "与circle圆不同，数量三对应原文三项列举。"],
  ["chronic", "", "adj.", "长期存在的；慢性的", "修饰problems，与acute crisis构成时间性质对照。", "chronic problems（长期问题）", "chronic非一定很剧烈，acute突出急迫。"],
  ["acute", "", "adj.", "急迫的；严重的", "修饰货币核心区正面对的危机。", "an acute crisis（急迫危机）", "还可指敏锐的、尖的；不与长期chronic混同。"],
  ["core", "cores", "n.", "核心", "economic core由后面的16个使用统一货币国家解释。", "the inner core（内部核心）", "成员范围依原文而定，不能理解成欧盟全部。"],
  ["currency", "currencies", "n.", "货币", "single currency此处为欧元，统一货币限制本币贬值。", "a single currency（统一货币）", "currency还可指流通、通行程度，不是current电流。"],
  ["market", "markets", "n.", "市场；金融市场参与者", "Markets失去的是经济体趋同信心；single market指共同市场。", "a single market（共同市场）", "市场作为判断主体是参与者转喻，非欧盟失去对市场的信心。"],
  ["faith", "", "n.", "信心；信任", "faith后that从句说明所相信的完整命题。", "lose faith（失去信心）", "faith还可指宗教信仰，本句接经济预期。"],
  ["euro", "euros", "n.", "欧元", "货币名称，不等于欧洲整体。", "save the euro（挽救欧元）", "euro与Europe地名、European形容词分为不同词位。"],
  ["zone", "zones zone's", "n.", "区域", "euro zone为使用欧元的区域，zone's为所有格。", "the euro zone（欧元区）", "不是time zone时区；不把zone's另造原形。"],
  ["weak", "weaker weakest", "adj.", "经济实力弱的", "weaker or stronger插入说明经济体无论强弱。", "weaker economies（较弱经济体）", "与poor贫穷接近但不完全等同，竞争力和收入可有差别。"],
  ["strong", "stronger strongest", "adj.", "经济实力强的", "与weaker并列，用于让步性范围说明。", "stronger economies（较强经济体）", "不在此译成强壮的人。"],
  ["converge", "converges converged converging", "v.", "趋同；靠拢", "经济体作主语，指表现走向接近，不是合并成一个国家。", "economies converge（经济体趋同）", "diverge分化为反义；converge不等于convert转变。"],
  ["thanks", "", "n. in phrase", "由于（thanks to）", "thanks to引原先设想的趋同原因。", "thanks to discipline（由于纪律约束）", "本句不是真正对货币道谢，也不能无视have lost faith的范围。"],
  ["discipline", "disciplines", "n.", "纪律；共同规则约束", "sharing a single currency规定了约束来源。", "economic discipline（经济纪律）", "还可指学科、训练；这里非学校课程。"],
  ["deny", "denies denied denying", "v.", "使无法获得；不予给予", "deny members the quick fix是双宾语，不是成员否认贬值。", "deny somebody something（不让某人获得某物）", "deny doing是否认做过，结构和本义不同。"],
  ["uncompetitive", "", "adj.", "缺乏竞争力的", "修饰受统一货币约束的成员经济体。", "uncompetitive members（缺乏竞争力的成员）", "un-为否定前缀，competitive与competitiveness分别保留词位。"],
  ["member", "members", "n.", "成员国", "本篇组织成员为国家，非个人会员。", "EU member states（欧盟成员国）", "16货币成员与27欧盟成员按原卷历史时点分开。"],
  ["quick", "quicker quickest", "adj.", "快速的", "修饰fix临时解决办法，不指人的敏捷。", "a quick fix（速效解决办法）", "quick fix常暗含短期性，未必根治。"],
  ["fix", "fixes", "n.", "解决办法", "the quick fix of devaluation为依靠贬值快速解困。", "a quick fix（权宜的快速办法）", "动词fix修理、固定和本篇名词区分。"],
  ["devaluation", "devaluations", "n.", "货币贬值", "统一货币成员无法单独让自己的货币贬值。", "currency devaluation（货币贬值）", "词族devalue动词降低价值，不能与evaluation评价混淆。"],
  ["save", "saved saves saving", "v.", "挽救；使免于毁坏", "save currency from disintegration说明避免瓦解。", "save A from B（挽救A免于B）", "其他常见义节省、储存，此处不是省钱。"],
  ["europe", "europe's", "proper n.", "欧洲", "Europe's所有格限定single currency。", "Europe's currency（欧洲的货币）", "地理欧洲、政治欧盟和货币欧元区范围不同。"],
  ["disintegration", "", "n.", "瓦解；解体", "save...from说明需要避免的后果。", "prevent disintegration（避免瓦解）", "integration一体化为相反方向，不是disagreement分歧。"],
  ["stick", "stuck sticks sticking", "v.", "卡住；陷于停滞", "is stuck中stuck为状态分词，主语是debate。", "be stuck（陷入僵局）", "stick—stuck—stuck不规则变化；名词stick为棍棒。"],
  ["dominant", "", "adj.", "主导的", "修饰powers，德法是欧元区有主导影响的大国。", "dominant powers（主导大国）", "并未由dominant推出两国正在争夺领导地位。"],
  ["power", "powers", "n.", "大国；有影响力的国家", "France and Germany同位说明powers所指。", "dominant powers（主导大国）", "还可指权力、能力、电力；本句为国家转喻。"],
  ["france", "", "proper n.", "法国", "提出欧元区核心内部政府干预方案的一方。", "France and Germany（法国和德国）", "France名词与French形容词分别归一。"],
  ["germany", "", "proper n.", "德国", "主张严格规则并让全欧盟参与协调。", "Germany's proposal（德国的建议）", "国家名为政府立场的转喻，不说所有德国人均持此观点。"],
  ["harmonisation", "", "n.", "协调；趋于一致", "德法赞同加强协调，但对协调对象存在分歧。", "fiscal harmonisation（财政协调）", "英式拼写保留；harmonise动词与本名词分开。"],
  ["harmonise", "harmonised harmonises harmonising", "v.", "协调；使一致", "what to harmonise为该协调什么，不是怎么解体。", "harmonise policies（协调政策）", "不等于双方已经达成一致。"],
  ["think", "thinks thought thinking", "v.", "认为", "Germany thinks后接省略that的完整主张。", "think that（认为）", "think about考虑与think+命题的判断结构不同。"],
  ["rule", "rules", "n.", "规则；规定", "德国主张借贷、支出、竞争力方面更严格规则。", "stricter rules（更严格的规则）", "rule作动词可统治或裁定，本句为名词。"],
  ["borrowing", "", "n. / gerund", "借贷；借款", "on borrowing中为名词化动作；cheaper borrowing指借贷成本更低。", "government borrowing（政府借贷）", "borrow借入与lend借出方向相反。"],
  ["back", "backs backed backing", "v.", "支持；支撑", "backed by sanctions修饰rules，以制裁保证规则。", "back rules with sanctions（以制裁支持规则）", "其他义背部、后面；不是回到某地。"],
  ["quasi-automatic", "", "adj.", "近乎自动的", "修饰sanctions，表示违规后较自动触发。", "quasi-automatic sanctions（近乎自动的制裁）", "quasi-表示准、近似，不能译成完全自动。"],
  ["sanction", "sanctions", "n.", "制裁；惩罚措施", "针对不遵守规则的政府。", "impose sanctions（实施制裁）", "也可指正式批准，本文根据punishment语境取制裁义。"],
  ["obey", "obeys obeyed obeying", "v.", "遵守", "do not obey省略上下文明确的规则宾语。", "obey rules（遵守规则）", "obey直接接宾语，不必加to。"],
  ["threat", "threats", "n.", "威胁", "threats to freeze是不遵守规则可能受到的压力。", "a threat to freeze funds（冻结资金的威胁）", "威胁采取某行动不等于已经执行。"],
  ["freeze", "freezes froze frozen freezing", "v.", "冻结；停止拨付", "freeze EU funds为暂停资金，非物理结冰。", "freeze funds（冻结资金）", "freeze—froze—frozen不规则变化，经济语境比喻限制。"],
  ["poor", "poorer poorest", "adj.", "贫困的；经济较弱的", "poorer regions和poorer members为援助或转移对象。", "poorer members（较贫困成员国）", "不沿用信息贫困语境；poor也可指质量差。"],
  ["region", "regions", "n.", "地区", "for poorer regions说明资金用途，不是完整欧盟成员数。", "poorer regions（较贫困地区）", "region地区不等于religion宗教。"],
  ["mega-project", "mega-projects", "n.", "大型项目", "与poorer regions并列为可能被停资的用途。", "EU mega-projects（欧盟大型项目）", "mega-表示巨大，完整复合词保留为一个词位。"],
  ["suspension", "suspensions", "n.", "暂停；中止", "suspension of voting rights指暂停投票资格。", "suspension of rights（暂停权利）", "不是保障guarantee，也不必然为永久取消。"],
  ["vote", "votes voted voting", "v.", "投票", "voting作rights的动名词定语，说明权利类型。", "voting rights（投票权）", "不把voting rights中的rights译成正确。"],
  ["ministerial", "", "adj.", "部长级的", "修饰councils，指欧盟相关部长级理事会。", "ministerial councils（部长理事会）", "由minister部长派生，保留独立词位。"],
  ["council", "councils", "n.", "理事会；委员会", "国家在这些机构中可能被暂停投票权。", "a ministerial council（部长理事会）", "勿与counsel建议或律师混同。"],
  ["insist", "insists insisted insisting", "v.", "坚持主张", "insist that...should involve为要求全体参与。", "insist that somebody should do（坚持要求某人做）", "insist on后接名词或doing；此处that引完整命题。"],
  ["co-ordination", "", "n.", "协调", "economic co-ordination为德国要求全体欧盟成员参与的事项。", "economic co-ordination（经济协调）", "原卷带连字符保留，与动词coordinate为词族而非屈折。"],
  ["club", "clubs", "n.", "集团；成员组织", "EU club为欧盟的比喻，不是娱乐场所。", "the EU club（欧盟这个成员集团）", "本篇club不是球棒或夜总会。"],
  ["whom", "", "relative pron.", "这些成员（关系代词宾格）", "among whom将介词前置，先行词为27国成员。", "among whom（在这些成员之中）", "whom作介词among宾语，不是there is从句主语。"],
  ["free-market", "", "adj.", "自由市场的", "修饰liberalism，说明支持较少政府干预的经济思想。", "free-market liberalism（自由市场主义）", "free在此非商品免费。"],
  ["liberalism", "", "n.", "自由主义", "与economic rigour并列为欧盟全体内微弱多数支持的取向。", "economic liberalism（经济自由主义）", "与liberal形容词相关但不并入同一原形。"],
  ["rigour", "", "n.", "严格；严谨的经济纪律", "与自由市场观点配合说明德国希望的政策方向。", "economic rigour（严格经济纪律）", "原卷为英式rigour，美式rigor是拼写变体。"],
  ["inner", "", "adj.", "内部的", "inner core指较小核心成员范围。", "the inner core（内部核心）", "不能把inner core读成全部欧盟成员。"],
  ["alone", "", "adv.", "仅；只", "in the inner core alone限定只在核心区内比较多数。", "the core alone（仅核心部分）", "不是这些国家感到孤独。"],
  ["fear", "fears feared fearing", "v.", "担忧", "Germany fears为插入报告分句，交代判断来源。", "fear that（担忧）", "本文担忧法国干预支持者占多数，不是已经发生制裁。"],
  ["camp", "camps", "n.", "阵营", "法国为首的南方政策阵营，不是露营地。", "a political camp（政治阵营）", "比喻意见立场相近的一组成员。"],
  ["head", "heads headed heading", "v.", "领导；率领", "headed by France为过去分词定语修饰camp。", "a camp headed by France（法国为首的阵营）", "名词head头部与本篇及物动词区分。"],
  ["euro-zone", "", "adj.", "欧元区的", "复合定语修饰members，与分写euro zone为同一概念的不同词形结构。", "euro-zone members（欧元区成员国）", "不能与EU全部成员直接等同。"],
  ["mean", "means meant meaning", "v.", "意味着", "that means引出法国方案的实际含义。", "that means（这意味着）", "means此处为动词单三，不是means手段名词。"],
  ["politician", "politicians", "n.", "政治家；政界人士", "intervening的逻辑主语，实施货币政策干预。", "politicians intervene（政治家干预）", "政治人物不等同economist经济学家。"],
  ["intervene", "intervenes intervened intervening", "v.", "干预；介入", "intervene in monetary policy为法国方案的政策内容。", "intervene in policy（干预政策）", "interference名词与intervene动词分别保留，不并成屈折。"],
  ["monetary", "", "adj.", "货币的", "修饰policy，与财政fiscal虽相关但不相同。", "monetary policy（货币政策）", "货币政策不自动等于紧缩，本文未作严格方向限定。"],
  ["redistribution", "", "n.", "再分配", "from richer to poorer说明资源由富向贫。", "redistribution of funds（资金再分配）", "re-表示重新；distribution分配保留独立词位。"],
  ["rich", "richer richest", "adj.", "富裕的", "richer members为向较贫困成员转移资源的出发方。", "richer members（更富裕的成员）", "此处为经济财富，不沿用信息资源丰富释义。"],
  ["via", "", "prep.", "通过；经由", "引出实现再分配的政策手段。", "via fiscal transfers（通过财政转移）", "via也可引途经地点，本篇为方式非路线。"],
  ["cheap", "cheaper cheapest", "adj.", "成本较低的", "cheaper borrowing指借贷成本低，而非借款额小。", "cheaper borrowing（成本更低的借贷）", "cheap也可指廉价低质，本文不表达质量判断。"],
  ["common", "", "adj.", "共同的；联合的", "common Eurobonds为共同发行或承担的债券方案。", "common Eurobonds（共同欧元债券）", "不是常见、普通的债券，须随语境取义。"],
  ["eurobond", "eurobonds", "n.", "欧元共同债券（本文政策语境）", "本文用于解释法国方案下的共同政府借贷工具。", "common Eurobonds（共同欧元债券）", "按文中共同借贷语境理解，不引申为富国控制的证据。"],
  ["complete", "", "adj.", "完全的；直接的", "complete fiscal transfers与债券融资方式对举。", "complete fiscal transfers（直接财政转移）", "complete此处形容词，不是动词完成。"],
  ["fiscal", "", "adj.", "财政的", "fiscal transfers为财政资源转移，fiscal harmonisation为财政政策协调。", "fiscal transfers（财政转移）", "fiscal财政与monetary货币区分，不能互相抹平。"],
  ["transfer", "transfers", "n.", "转移；划拨", "与借贷途径并列，指直接资金转移。", "fiscal transfers（财政转移支付）", "也可作动词调动、转移，本文为名词复数。"],
  ["figure", "figures", "n.", "人士；人物", "close to政府说明这些政界人物的关系。", "government figures（政府相关人士）", "其他义数字、图形；此处不是政府附近的统计数字。"],
  ["close", "closer closest", "adj.", "关系密切的", "close to French government后置修饰figures。", "be close to somebody（与某人关系密切）", "不是关闭close的动词，也不是只谈物理距离。"],
  ["murmur", "murmurs murmured murmuring", "v.", "低声说；低调提出", "have murmured为报告言论的完成时谓语。", "murmur a suggestion（低声提出建议）", "与declare公开宣布的力度不同，不能推断已实施。"],
  ["curb", "curbs curbed curbing", "v.", "抑制；限制", "curbing引财政社会协调的例子，宾语competition。", "curb competition（限制竞争）", "不是鼓励竞争；名词curb可指路缘或限制措施。"],
  ["corporate-tax", "", "adj.", "企业税的", "修饰rates，原文保留连字符。", "corporate-tax rates（企业税税率）", "不是公司价格或税收总额。"],
  ["labour", "", "n.", "劳动力；劳动", "labour costs是劳动力成本，open to labour指劳动力自由流动。", "labour costs（劳动力成本）", "英式labour保留；此处不是产科分娩。"],
  ["large", "larger largest", "adj.", "规模大的", "largest trading block为原文时代比较中的最大贸易集团。", "the largest trading block（最大的贸易集团）", "largest为最高级，不构成单独原形。"],
  ["trade", "trades traded trading", "n. / v.", "贸易；开展贸易", "trading作block的定语，表示跨国商品服务交换。", "a trading area（贸易区）", "不是Text 1的trade up升级替换。"],
  ["block", "blocks", "n.", "集团；联盟（原卷拼写）", "trading block原样保留；这里语义为贸易集团。", "trading block（贸易集团）", "常见同义拼写bloc，本项目不擅改用户真题；其他义街区、块或阻挡。"],
  ["remarkably", "", "adv.", "显著地；格外地", "修饰liberal，强调最佳状态下的开放程度。", "remarkably open（格外开放）", "remarkable形容词与remarkably副词不并入同一原形。"],
  ["liberal", "", "adj.", "开放的；自由的", "本文评价共同市场内部要素流动开放。", "a liberal market（开放市场）", "不是人物花钱大方或美国党派标签。"],
  ["internal", "", "adj.", "内部的", "internal borders指欧盟成员间边界。", "internal borders（内部边界）", "external外部的为反义；不把内外贸易边界混淆。"],
  ["border", "borders", "n.", "边界", "对商品、资本、劳动力开放程度高。", "open borders（开放的边界）", "原文比较跨境流通，不表示边界不再存在。"],
  ["open", "", "adj.", "开放的", "be open to说明允许各类经济要素流动。", "be open to goods（对商品流动开放）", "也可表示愿意接受意见；此处不是动词打开。"],
  ["comparable", "", "adj.", "可比较的；类似的", "限定trading area的比较范围。", "a comparable area（可比地区）", "不等于comparable就完全相同，different规模未必适合比较。"],
  ["attempt", "attempts", "n.", "尝试；努力", "不定式说明欧洲一体化计划的目标。", "an attempt to do（做某事的尝试）", "attempt是目标性行动，不保证结果已实现。"],
  ["blunt", "blunts blunted blunting", "v.", "削弱；缓和", "blunt sharpest edges比喻缓解全球化最尖锐弊端。", "blunt the impact（减弱冲击）", "形容词blunt可指钝的或直言的；本句动词非完全消灭。"],
  ["sharp", "sharper sharpest", "adj.", "尖锐的；严重的", "sharpest edges为全球化最尖锐负面影响的比喻。", "sharp edges（尖锐边缘）", "sharp还可指敏锐或急剧；此处不是增长陡峭。"],
  ["edge", "edges", "n.", "锋芒；尖锐负面一面", "edges of globalisation比喻全球化造成的冲击。", "blunt the edges（缓和锋芒）", "edge其他义边缘、优势；不能取竞争优势而反转作者意思。"],
  ["globalisation", "", "n.", "全球化", "文章谈一体化缓解全球化弊端的目标。", "the effects of globalisation（全球化的影响）", "英式拼写保留，与global形容词分开。"],
  ["capitalism", "", "n.", "资本主义", "make capitalism benign为计划的第二目标。", "benign capitalism（较温和的资本主义）", "capital资本与capitalism制度概念分开归一。"],
  ["benign", "", "adj.", "温和的；有益而少害的", "作make的宾补，评价capitalism目标状态。", "make something benign（使某物趋于温和有益）", "医学可指良性，但此处非肿瘤；不等于完美无缺。"],
  ["concerned", "", "adj.", "担忧的", "feel concerned为36题支持者的心理状态。", "feel concerned（感到担忧）", "这里不取concern动词涉及；形容词独立语义。"],
  ["abandon", "abandons abandoned abandoning", "v.", "放弃", "36题干扰项声称成员计划弃用欧元，原文无此证据。", "abandon a currency（放弃一种货币）", "abandon放弃并不等于discuss讨论问题。"],
  ["intend", "intends intended intending", "v.", "打算；意图", "intend to强调主观计划，不能套在客观货币约束上。", "intend to do（打算做）", "intend与tend倾向不要混同。"],
  ["busy", "", "adj.", "忙于的", "busy handling为37题无原文依据的干扰说法。", "be busy doing（忙于做）", "busy后常接doing，不接to do作此义补足。"],
  ["handle", "handles handled handling", "v.", "处理；应对", "handling crises指处理危机，题干另有处理方案义。", "handle a crisis（应对危机）", "handle也可作把手名词，本篇为动词。"],
  ["step", "steps", "n.", "步骤；措施", "steps towards disintegration为干扰项，将避免瓦解方向反转。", "steps towards a goal（迈向目标的步骤）", "不按脚步声理解政策过程。"],
  ["solve", "solves solved solving", "v.", "解决", "38题所问解决欧元难题的方法。", "solve a problem（解决问题）", "solve常接problem，answer常接question，不一概互换。"],
  ["guarantee", "guarantees guaranteed guaranteeing", "v.", "保障；保证", "38题错误项说保障投票权，与暂停权利相反。", "guarantee rights（保障权利）", "guarantee不能解释suspension暂停。"],
  ["loan", "loans", "n.", "贷款", "39题选项将更容易取得贷款的对象错放在富国。", "government loans（政府贷款）", "贷款loan需偿还，与直接财政转移非同一机制。"],
  ["readily", "", "adv.", "容易地；随时可得地", "readily available表示容易取得，不表示必须已经获贷。", "readily available（容易获得的）", "ready形容词准备好，readily副词不等于already已经。"],
  ["pessimistic", "", "adj.", "悲观的", "作者承认危机但末段不否定前景，所以不选此项。", "be pessimistic about（对……悲观）", "opposed反对是立场不是悲观情绪。"],
  ["desperate", "", "adj.", "绝望的", "40题选项用于态度判断，与结尾保留希望不符。", "a desperate outlook（绝望的前景判断）", "也可指迫切需要，此处四项对照取绝望。"],
  ["conceited", "", "adj.", "自负的；自大的", "评价傲慢性格，不合作者有条件的积极判断。", "a conceited person（自负的人）", "confident有信心不一定有conceited的贬义。"],
];
const reviewed = reviewedLexicon(rows);
export const passage2011P4Lexicon = reviewed.entries;
export const passage2011P4LemmaAliases: Record<string, string> = { ...reviewed.aliases, borrowing: "borrowing", concerned: "concerned", regarding: "regarding" };
export const passage2011P4CollocationGlosses = reviewed.glosses;
export const passage2011P4FormPartOfSpeech: Record<string, string> = { european: "adj.", french: "adj.", lower: "adj.（比较级）", greatest: "adj.（最高级）", that: "conj. / pron.", borrowing: "n. / gerund", spending: "gerund", backed: "v.-ed（分词定语）", voting: "gerund（定语）", among: "prep.", favour: "v.", translated: "v.-ed（解释状语）", means: "v.", figures: "n.", trading: "v.-ing（定语）", complete: "adj.", best: "adj. used as noun", regarding: "prep.", leading: "v.-ing（定语）" };
passage2011P4Lexicon.sanction.otherMeanings = ["正式批准；认可（可作名词或动词）。本文为制裁，不能套用批准义。"];
passage2011P4Lexicon.currency.otherMeanings = ["流通；通行，如gain currency获得传播或接受。"];
passage2011P4Lexicon.power.otherMeanings = ["能力；权力；电力；数学中的幂；v. 为……提供动力。"];
passage2011P4Lexicon.figure.otherMeanings = ["数字；人物；体形；图表；v. 认为、估计；figure out弄清。"];
export const passage2011P4SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2011-p4-s6": { save: { contextualSubstitutions: [{ label: "rescue", chinese: "挽救", fit: "direct", rewrittenSentence: "Yet the debate about how to rescue Europe's single currency from disintegration is stuck.", nuance: "rescue from比save from更突出从困境中解救；保留讨论陷入僵局而非已经挽救的命题。", target: "word:rescue" }] } },
  "2011-p4-s1": { make: { contextualMeaning: "成功挺过难关（make it）", use: "make it为习语，it不对应某个制造物。" }, it: { contextualMeaning: "make it习语组成", use: "与make共同表示成功、挺过难关，不读成制造它。" } },
  "2011-p4-s2": { will: { contextualMeaning: "假设过去提出会……", use: "would have sounded表达放回过去的假想评价，不是未来承诺。" }, have: { partOfSpeech: "aux.", contextualMeaning: "完成式助动词", use: "would have sounded将假想判断放在过去。" } },
  "2011-p4-s3": { even: { contextualMeaning: "连……都", use: "强调最坚定支持者也开始担忧，36题关键。" } },
  "2011-p4-s4": { as: { contextualMeaning: "除……之外还（as well as）", use: "as well as整体为追加，并非同级方式比较。" }, those: { contextualMeaning: "前述长期问题", use: "回指债务、人口减少、增长放缓。" } },
  "2011-p4-s5": { that: { partOfSpeech: "conj.", contextualMeaning: "引出所相信的命题", use: "faith的内容从句，that不作从句主语或宾语。" }, which: { contextualMeaning: "统一货币", use: "关系代词作denies主语，解释统一货币的约束。" }, share: { contextualMeaning: "共同使用", use: "sharing a single currency的对象为共同货币，不指分配货币份额。" } },
  "2011-p4-s7": { it: { contextualMeaning: "挽救欧元的讨论", use: "回指上一句debate，不是欧盟已停止运作。" } },
  "2011-p4-s9": { these: { contextualMeaning: "这些制裁", use: "回指sanctions，随后给出可能措施。" }, right: { partOfSpeech: "n.", contextualMeaning: "权利", use: "voting rights为投票权，不是正确答案。" } },
  "2011-p4-s10": { it: { contextualMeaning: "德国", use: "承接Germany的政策主张。" }, for: { contextualMeaning: "支持；赞成", use: "majority for说明多数人支持的方向。" }, favour: { contextualMeaning: "支持；赞同", use: "宾语French interference，说明只看核心区的多数取向。" } },
  "2011-p4-s12": { that: { partOfSpeech: "pron.", contextualMeaning: "法国的欧洲经济政府方案", use: "作means主语，不是从句连词。" }, translate: { contextualMeaning: "换成明白话解释", use: "句首Translated为对政治口号的实质解释。" } },
  "2011-p4-s13": { finally: { contextualMeaning: "最后一点", use: "引入法国方案的另一内容，不是故事最后结局。" } },
  "2011-p4-s14": { it: { contextualMeaning: "形式主语", use: "真正评价的动作是to write off the EU。" }, too: { contextualMeaning: "过于；太", use: "too soon表示认定失败为时过早，不取也。" }, write: { contextualMeaning: "认定无望（write off）", use: "write off the EU是放弃其前途，不是书写；财务义核销为其他语境。" } },
  "2011-p4-s15": { it: { contextualMeaning: "欧盟", use: "回指EU，评价整体贸易规模。" } },
  "2011-p4-s16": { its: { contextualMeaning: "欧洲一体化计划的", use: "its best为其最佳状态，its internal borders为共同市场内部边界。" }, far: { contextualMeaning: "远远；大得多", use: "far加强more open的比较程度，不是距离遥远。" } },
  "2011-p4-s17": { it: { contextualMeaning: "欧洲一体化计划", use: "回指European project，后接对目标的评价。" }, make: { contextualMeaning: "使……变得", use: "make capitalism benign中capitalism宾语、benign宾补，非第1句make it。" } },
};
