import type { BeginnerSyntaxComponent, BeginnerClauseDetail, QuestionAnalysis, SentenceAnalysis, SyntaxVisualRole } from './data';
import { withReviewedSyntax } from './reviewed-syntax';
const c=(text:string,form:string,fn:string,modifies:string,explanation:string,children?:BeginnerSyntaxComponent[]):BeginnerSyntaxComponent=>({text,form,function:fn,modifies,explanation,children});
const a=(id:string,text:string,trunk:string,components:BeginnerSyntaxComponent[],colors:SyntaxVisualRole[],meaning:string,focus:string,clauses:BeginnerClauseDetail[]=[]):SentenceAnalysis=>withReviewedSyntax({id,number:0,text,trunk,beginnerSyntax:{components,clauses},layers:[{label:'读题关键',text:focus}],grammar:[focus],literal:meaning,natural:meaning,logic:'先辨明本项实际命题；是否选入另看题目原文证据。',phrases:[]},colors);
const p=(...args:Parameters<typeof a>):SentenceAnalysis=>({...a(...args),textKind:'phrase'});
export const passage2011P2QuestionAnalysis:Record<number,QuestionAnalysis>={
26:{prompt:a('201126-prompt-analysis','By saying "Newspapers like … their own doom" (Lines3-4, Para. 1), the author indicates that newspapers____.','the author indicates that newspapers____.',[
 c('By saying "Newspapers like … their own doom" (Lines3-4, Para. 1)','介词加动名词与引文','表达手段状语','indicates','询问作者借这句话表达什么；括号标明原卷位置。',[c('saying "Newspapers like … their own doom"','动名词结构','介词宾语','By','saying的宾语是被引用的原句片段，不把省略号补成新原文。')]),c('the author','名词短语','主语','indicates','表达意图的主体。'),c('indicates','一般现在时动词','谓语','the author','表明、暗示，不是要求按字面翻译doom。'),c('that newspapers____','待补全内容从句','宾语从句','indicates','选项接在newspapers后补谓语。')],['modifier','subject','predicate','object'],'作者说“像……的报纸……自身的厄运”（第一段第3—4行），是在表明报纸怎样？','by doing说明表达手段；that引待补全的表意内容。',[{text:'that newspapers____',type:'宾语从句（待补全）',marker:'that',role:'作indicates宾语',subject:'newspapers',predicate:'____',predicateDetails:[],translationOrder:'先译作者表明，再接报纸当时的处境。'}]),options:{
 A:p('201126-A-analysis','neglected the sign of crisis','neglected the sign',[c('neglected','过去式动词','待接主语的谓语','题干newspapers','忽视、没有留意。'),c('the sign of crisis','名词短语','宾语','neglected','危机的迹象，of说明迹象内容。')],['predicate','object'],'忽视了危机迹象。','过去式neglected承接题干主语；辨别察觉危机与忽视危机。'),
 B:p('201126-B-analysis','failed to get state subsidies','failed to get state subsidies',[c('failed','过去式动词','待接主语的谓语','题干newspapers','fail to do表示未能做到。'),c('to get state subsidies','不定式短语','补足语','failed','未获得的对象是国家补贴。',[c('state subsidies','名词短语','宾语','get','state前置限定subsidies；不是动词陈述。')])],['predicate','complement'],'未能获得国家补贴。','未能获得已经断言一个失败结果，和是否应补贴的提问不同。'),
 C:p('201126-C-analysis','were not charitable corporations','were not charitable corporations',[c('were not','否定过去时系动词','待接主语的谓语','题干newspapers','否定某种身份。'),c('charitable corporations','名词短语','表语','were','慈善性质的法人机构。')],['predicate','complement'],'不是慈善性质的机构。','charitable修饰组织性质；需判断是否切合引句要表达的重点。'),
 D:p('201126-D-analysis','were in a desperate situation','were in a desperate situation',[c('were','过去时系动词','待接主语的谓语','题干newspapers','说明当时状态。'),c('in a desperate situation','介词短语','表语','were','陷入严重困境；desperate修饰situation。')],['predicate','complement'],'处于严重困境之中。','desperate situation概括处境；不是已经消亡的完成事实。')
}},
27:{prompt:a('201127-prompt-analysis','Some newspapers refused delivery to distant suburbs probably because____.','Some newspapers refused delivery because____.',[
 c('Some newspapers','名词短语','主语','refused','仅部分报纸，保留Some范围。'),c('refused','过去式动词','谓语','Some newspapers','拒绝提供某项服务。'),c('delivery to distant suburbs','名词短语','宾语','refused','delivery中心，to引配送目的地。',[c('to distant suburbs','介词短语','后置定语','delivery','较远的郊区，不是报道话题。')]),c('probably','概率副词','推断程度状语','because引出的原因','表示最可能的解释，不是原文逐字直说的必然原因。'),c('because____','待补全原因从句','原因状语','refused','because后接完整主谓句，四个选项各自已有主语。')],['subject','predicate','object','modifier','modifier'],'一些报纸拒绝向偏远郊区配送，很可能是因为什么？','because需要完整原因；probably提示依据上下文作有限推断。',[{text:'because____',type:'原因状语从句（待补全）',marker:'because',role:'解释refused的原因',subject:'____',predicate:'____',predicateDetails:[],translationOrder:'先读拒送行为，再寻找符合本段求生目的的原因。'}]),options:{
 A:a('201127-A-analysis','readers threatened to pay less','readers threatened to pay less',[c('readers','复数名词','主语','threatened','威胁行为的发出者。'),c('threatened','过去式动词','谓语','readers','此选项为扬言采取某种行动。'),c('to pay less','不定式短语','补足语','threatened','扬言少付钱，less省略钱的数额。')],['subject','predicate','complement'],'读者威胁要少付钱。','此处是人扬言，不能将正文经济衰退threatened的风险义直接移来。'),
 B:a('201127-B-analysis','newspapers wanted to reduce costs','newspapers wanted to reduce costs',[c('newspapers','复数名词','主语','wanted','指报业经营者。'),c('wanted','过去式动词','谓语','newspapers','表示目的意愿。'),c('to reduce costs','不定式短语','宾语','wanted','降低成本，costs为reduce宾语。')],['subject','predicate','object'],'报纸想降低成本。','reduce costs是减少支出；不要把costs理解成读者付给报纸的收入。'),
 C:a('201127-C-analysis','journalists reported little about these areas','journalists reported little',[c('journalists','复数名词','主语','reported','记者。'),c('reported','过去式动词','谓语','journalists','报道。'),c('little','不定代词','宾语','reported','很少的内容，不是小记者。'),c('about these areas','介词短语','话题补充','reported little','这些地理区域是所报道的话题。')],['subject','predicate','object','modifier'],'记者很少报道这些地区。','little作报道内容的量；these areas在本选项承接偏远郊区。'),
 D:a('201127-D-analysis','subscribers complained about slimmer products','subscribers complained',[c('subscribers','复数名词','主语','complained','付费订阅报纸的人。'),c('complained','过去式动词','谓语','subscribers','抱怨、投诉。'),c('about slimmer products','介词短语','抱怨对象补足语','complained','产品更薄、内容更少。')],['subject','predicate','complement'],'订户抱怨报纸内容变少。','complain about引抱怨事项；正文的产品变薄并不自动证明投诉发生。')
}},
28:{prompt:a('201128-prompt-analysis','Compared with their American counterparts, Japanese newspapers are much more stable because they____.','Japanese newspapers are more stable because they____.',[
 c('Compared with their American counterparts','过去分词短语','比较状语','Japanese newspapers','与同类美国报纸比较；their在这里联系日本报纸的美国对应者。',[c('with their American counterparts','介词短语','比较对象补足语','Compared','counterparts保证比较双方同类。')]),c('Japanese newspapers','名词短语','主语','are','日本报纸。'),c('are','系动词','谓语','Japanese newspapers','连接稳定性判断。'),c('much more stable','形容词比较级短语','表语','are','much加强more stable，表示稳定得多。'),c('because they____','待补全原因从句','原因状语','are much more stable','they指日本报纸，选项补谓语。')],['modifier','subject','predicate','complement','modifier'],'与美国报纸相比，日本报纸稳定得多，因为它们怎样？','Compared的逻辑比较对象是Japanese newspapers；because引原因而非另一个结果。',[{text:'because they____',type:'原因状语从句（待补全）',marker:'because',role:'解释稳定性差异',subject:'they',predicate:'____',predicateDetails:[],translationOrder:'先确定两国比较，再读日本报纸更稳定的原因。'}]),options:{
 A:p('201128-A-analysis','have more sources of revenue','have more sources',[c('have','动词原形','待接主语的谓语','题干they','拥有。'),c('more sources of revenue','名词短语','宾语','have','more修饰来源数量，of revenue限定哪种来源。')],['predicate','object'],'拥有更多收入来源。','来源更多是数量命题，不能与两类收入的比例更均衡混淆。'),
 B:p('201128-B-analysis','have more balanced newsrooms','have newsrooms',[c('have','动词原形','待接主语的谓语','题干they','拥有。'),c('more balanced newsrooms','名词短语','宾语','have','more balanced共同修饰newsrooms，指编辑部更均衡。')],['predicate','object'],'拥有更加均衡的新闻编辑部。','more修饰balanced的程度，不是说编辑部数量更多。'),
 C:p('201128-C-analysis','are less dependent on advertising','are less dependent',[c('are','系动词','待接主语的谓语','题干they','连接依赖状态。'),c('less dependent on advertising','形容词短语','表语','are','依赖程度更低。',[c('on advertising','介词短语','形容词补足语','dependent','说明依赖对象是广告业务。')])],['predicate','complement'],'对广告的依赖较低。','dependent on与正文reliance on对应，less不等于毫无依赖。'),
 D:p('201128-D-analysis','are less affected by readership','are less affected',[c('are less affected','比较程度被动结构','待接主语的谓语','题干they','受到的影响较小。'),c('by readership','介词短语','影响来源补足语','affected','readership指读者群或读者数量。')],['predicate','modifier'],'较少受到读者数量的影响。','by引影响来源；读者数量影响与广告依赖是两个不同指标。')
}},
29:{prompt:a('201129-prompt-analysis','What can be inferred from the last paragraph about the current newspaper business?','What can be inferred?',[
 c('What','疑问代词','主语','can be inferred','询问可以推出的内容，不是形式主语。'),c('can be inferred','情态被动结构','谓语','What','可以根据证据推断。'),c('from the last paragraph','介词短语','依据状语','inferred','限定末段。'),c('about the current newspaper business','介词短语','话题状语','What can be inferred','问如今的报业，current限定时间范围。')],['subject','predicate','modifier','modifier'],'从末段可以推断出关于当前报业的什么情况？','What自身充当疑问主语，不另补it；from是依据，about是话题。'),options:{
 A:a('201129-A-analysis','Distinctiveness is an essential feature of newspapers.','Distinctiveness is a feature.',[c('Distinctiveness','抽象名词','主语','is','独特性，和distinctive有派生关系但词性不同。'),c('is','系动词','谓语','Distinctiveness','连接价值判断。'),c('an essential feature of newspapers','名词短语','表语','is','报纸必不可少的重要特点；essential限定feature。')],['subject','predicate','complement'],'独特性是报纸的一项必要特点。','feature在此是特点名词，essential强调重要性。'),
 B:a('201129-B-analysis','Completeness is to blame for the failure of newspaper.','Completeness is to blame.',[c('Completeness','抽象名词','主语','is','全面性。'),c('is','系动词','谓语','Completeness','与to blame构成责任表达。'),c('to blame for the failure of newspaper','不定式习语结构','表语','is','声称全面性应为报纸失败负责；原卷单数措辞照录。',[c('for the failure of newspaper','介词短语','责任事项补足语','to blame','把失败归因于全面性，强于不再是优势。')])],['subject','predicate','complement'],'报纸的失败应归咎于全面性。','be to blame for是应为……负责，形式主动而语义指可归责。'),
 C:a('201129-C-analysis','Foreign bureaus play a crucial role in the newspaper business.','Foreign bureaus play a role.',[c('Foreign bureaus','名词短语','主语','play','报社驻外新闻机构。'),c('play','一般现在时动词','谓语','Foreign bureaus','与role搭配表示发挥作用。'),c('a crucial role','名词短语','宾语','play','至关重要的作用。'),c('in the newspaper business','介词短语','领域状语','play a crucial role','限定在报业经营中。')],['subject','predicate','object','modifier'],'驻外机构在报业中发挥至关重要的作用。','play a role为固定搭配，crucial表达重要程度，需要原文支持。'),
 D:a('201129-D-analysis','Readers have lost their interest in car and film reviews.','Readers have lost their interest.',[c('Readers','复数名词','主语','have lost','读者。'),c('have lost','现在完成时','谓语','Readers','已经失去，强调如今结果。'),c('their interest in car and film reviews','名词短语','宾语','lost','失去对汽车评测与影评的兴趣。',[c('in car and film reviews','介词短语','兴趣对象补足语','interest','reviews为评论作品，car和film共同限定。')])],['subject','predicate','object'],'读者已失去对汽车评测和影评的兴趣。','岗位不再保留与读者不再感兴趣不是同一命题。')
}},
30:{prompt:a('201130-prompt-analysis','The most appropriate title for this text would be____.','The title would be____.',[
 c('The most appropriate title for this text','名词短语','主语','would be','中心title，most appropriate限定最合适，for限定所属文章。'),c('would be','情态动词加系动词','谓语','title','在给定选项中作判断，不是报道将来事件。'),c('____','待填名词短语','表语','be','四项均为标题。')],['subject','predicate','complement'],'最适合本文的标题是什么？','most appropriate要求整体覆盖且语气恰当，不能只匹配一个局部词。'),options:{
 A:p('201130-A-analysis','American Newspapers: Struggling for Survival','American Newspapers: Struggling for Survival',[c('American Newspapers','名词短语','标题对象','整个标题','美国报纸。'),c('Struggling for Survival','现在分词短语','标题补充说明','American Newspapers','奋力求生，省略标题中可理解的are。',[c('for Survival','介词短语','目标补足语','Struggling','努力的目标是生存。')])],['subject','complement'],'美国报纸：艰难求生。','标题分词表达持续努力；求生兼容已有转机和仍有代价。'),
 B:p('201130-B-analysis','American Newspapers: Gone with the Wind','American Newspapers: Gone with the Wind',[c('American Newspapers','名词短语','标题对象','整个标题','美国报纸。'),c('Gone with the Wind','分词短语','标题补充说明','American Newspapers','借随风而逝的意象表示消逝。')],['subject','complement'],'美国报纸：随风而逝。','Gone暗示已消失，须核对正文仍存活的事实。'),
 C:p('201130-C-analysis','American Newspapers: A Thriving Business','American Newspapers: A Thriving Business',[c('American Newspapers','名词短语','标题对象','整个标题','美国报纸。'),c('A Thriving Business','名词短语','标题补充说明','American Newspapers','一个兴旺的行业；Thriving作前置定语。')],['subject','complement'],'美国报纸：欣欣向荣的行业。','thrive强调繁荣，强于survive存活。'),
 D:p('201130-D-analysis','American Newspapers: A Hopeless Story','American Newspapers: A Hopeless Story',[c('American Newspapers','名词短语','标题对象','整个标题','美国报纸。'),c('A Hopeless Story','名词短语','标题补充说明','American Newspapers','一段没有希望的经历，Hopeless否定转机。')],['subject','complement'],'美国报纸：无望的故事。','hopeless是强烈悲观评价，要与恢复盈利和措施奏效对照。')
}}
};
