import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";

const rows: LexiconRow[] = [
  ["stem", "stems stemmed stemming", "v.", "源自；由……产生", "stem from说明来源，可用于替换derive from，必须保留介词from。", "stem from simplicity（源自简洁）", "stem from比derive from稍口语，两者此处都表达来源而非造成结果。"],
  ["soldier", "soldiers", "n.", "士兵；军人", "战后士兵返乡、入学与结婚共同构成繁荣时代背景。", "returning soldiers（返乡军人）", "soldier为军人，veteran特指有服役经历者，不能一概任意替换。"],
  ["return", "returning returned returns", "v.", "返回", "returning home为with结构中的第一项分词动作，主语是soldiers。", "return home（回家）", "本文为返乡，不同于Text 2 return to profit恢复盈利。"],
  ["college", "colleges", "n.", "大学；高等院校", "go off to college指军人借助法案资助入大学读书。", "go to college（上大学）", "college不等于中学school，原文不限定某一大学。"],
  ["line", "lining lined lines", "v.", "排队（与up连用）", "lining up为士兵在婚姻登记机构排队的并列动作。", "line up（排队）", "与Text 2题干的line文本行名词区分；去e加ing。"],
  ["bureau", "bureaus bureaux", "n.", "办事机构；登记处", "marriage bureaus为婚姻登记机构，不是Text 2的驻外新闻机构。", "marriage bureaus（婚姻登记处）", "同词随修饰语改变具体机构类型，bureaus和bureaux均为复数。"],
  ["house", "houses", "n.", "住宅；房屋", "全文讨论居住建筑，Case Study Houses为项目名称。", "efficient houses（高效实用的住宅）", "不是议院House；house名词与housing住房集合概念分别保留。"],
  ["common", "", "adj.", "常识性的；共同认可的", "common sense整体指务实判断，而不是某种普遍感官。", "common sense（常识；务实判断）", "不能把common单独译成普通而漏掉固定搭配。"],
  ["sense", "senses", "n.", "理性判断；常识", "common sense说明住宅取向讲求实用与节制。", "common sense（常识）", "与a sense of security安全感、word sense词义不同。"],
  ["truly", "", "adv.", "真正地；确实", "修饰could be more，加强少而精可带来更强效果的信念。", "truly effective（确实有效的）", "副词truly修饰判断，不是形容词true直接修饰名词。"],
  ["depression", "depressions", "n.", "经济大萧条", "the Depression特指文中战前的经济萧条时期，与the war并列。", "during the Depression（在经济大萧条时期）", "不同于心理抑郁或地表凹陷义。"],
  ["restraint", "restraints", "n.", "节制；克制", "that restraint回指学会用较少物质资源生活，是31题关键词。", "restraint in design（设计中的节制）", "与外部restriction限制不同，此处偏主动克制。"],
  ["combination", "combinations", "n.", "结合；组合", "in combination with说明节制与信心共同作用。", "in combination with（与……结合）", "不是把两个概念说成完全相同。"],
  ["housing", "", "n. uncountable", "住房；住宅设计", "small, efficient housing作为make的宾语，指一类居住建筑。", "efficient housing（高效利用空间的住房）", "housing作为集合名词独立于house单栋住宅，不能一律合并。"],
  ["positively", "", "adv.", "非常；确实", "positively stylish强调十分时髦，不是在谈肯定回答或正电荷。", "positively stylish（确实很时髦）", "副词修饰stylish，而不是说明人们对经济持积极态度。"],
  ["stylish", "", "adj.", "时髦的；有格调的", "made housing stylish中作宾语补足语。", "stylish housing（时髦的住宅）", "有风格不必依赖繁多装饰，正是文章主题。"],
  ["stimulus", "stimuli", "n.", "刺激因素；推动力", "经济状况只是高效生活趋势的一项推动因素。", "a stimulus for change（推动变化的因素）", "复数stimuli不规则；only提示不能作唯一原因解释。"],
  ["actually", "", "adv.", "实际上", "引出少即是多理念传播的事实，对只从经济条件理解作补充。", "actually originated elsewhere（实际上起源于别处）", "不同于currently目前，不是单纯时间词。"],
  ["popularize", "popularized popularizes popularizing", "v.", "推广；使广为人知", "was first popularized强调首先推广，不断言首次创造格言。", "popularize an idea（推广一种观念）", "与invent发明、found创建区别，32题不可偷换。"],
  ["architect", "architects", "n.", "建筑师", "Mies、Wright和Rapson均以建筑设计者身份出现。", "modern architects（现代建筑师）", "architect职业名词与architecture建筑学、architectural建筑的为词族而非屈折。"],
  ["associate", "associated associates associating", "v.", "联系；使有关联", "people associated with the Bauhaus中分词短语限定与该校有关的人。", "be associated with a school（与某所学校有关联）", "有关联不必然意味着创建、毕业或成为该校多数人群。"],
  ["emigrate", "emigrated emigrates emigrating", "v.", "移居国外", "emigrate to the United States从原居国视角说移居美国。", "emigrate to another country（移居另一个国家）", "immigrate从迁入国视角说移民；to引目的地。"],
  ["post", "posts", "n.", "职位；职务", "take up posts at schools指在建筑院校开始任职。", "take up a post（开始任职）", "不是邮政、柱子或网络帖子义。"],
  ["architecture", "", "n.", "建筑；建筑学", "American architecture为美国建筑发展，architecture schools为建筑院校。", "the course of architecture（建筑的发展进程）", "不可数领域名词，不是某一栋building。"],
  ["designer", "designers", "n.", "设计师", "These designers回指与包豪斯有关并移居美国的人。", "modern designers（现代设计师）", "与design设计动词和设计方案名词分开计数。"],
  ["course", "courses", "n.", "发展进程；走向", "the course of American architecture讨论建筑史演进，不是某门课程。", "the course of development（发展的进程）", "同词也有课程、路线、一餐中的一道菜等义。"],
  ["signature", "signatures", "n. attributive", "标志性的；代表性的", "signature phrase指密斯最具代表性的格言，不是签名用的一句话。", "a signature phrase（标志性表述）", "signature名词本义签名；前置修饰可表示独有特色。"],
  ["mean", "means meant meaning", "v.", "意味着；意思是", "phrase means that解释格言含义，means是第三人称单数动词。", "a phrase means that（某句话意味着）", "不能沿用means名词手段的稳定词条；本篇按语境归mean。"],
  ["decoration", "decorations", "n.", "装饰", "less decoration与a lot of decoration比较的是装饰数量而非住宅面积。", "abundant decoration（大量装饰）", "与detailing细部处理不完全相同，细部可简洁且不堆砌装饰。"],
  ["organize", "organized organizes organizing", "v.", "组织；安排", "properly organized为装饰经过合理布局的被动分词说明。", "properly organized decoration（安排得当的装饰）", "不是成立组织，重点在构成方式。"],
  ["impact", "impacts impacted impacting", "n. / v.", "效果；影响", "第7句has more impact中为名词效果；末句would impact life中为及物动词影响。", "have an impact（产生影响）", "名动同形必须按句法位置区分，不把would后的impact标成名词。"],
  ["lot", "lots", "n.", "大量（a lot）", "than a lot省略of decoration，比较大量装饰。", "a lot of decoration（大量装饰）", "不是拍卖批次或地块义；不能省略其指代对象。"],
  ["elegance", "", "n.", "优雅；雅致", "建筑形式的审美品质，并不依赖装饰堆积。", "architectural elegance（建筑的优雅）", "elegant为形容词，elegance为独立派生名词。"],
  ["derive", "derives derived deriving", "v.", "源于；来自", "derive from abundance被否定，说明优雅不源于数量繁多。", "derive from simplicity（源于简洁）", "与cause造成方向相反；from引来源。"],
  ["abundance", "", "n.", "丰富；大量", "abundance回指装饰上的堆叠丰繁，不是住宅所有者财富。", "an abundance of decoration（大量装饰）", "abundant为形容词，两者不合并原形次数。"],
  ["employ", "employed employs employing", "v.", "采用；使用", "employ metal, glass and laminated wood指选用建筑材料。", "employ new materials（采用新材料）", "employ人可表示雇用，接材料时不能译成聘用。"],
  ["metal", "metals", "n.", "金属", "与glass、wood并列作employed宾语，为材料名词。", "metal and glass（金属和玻璃）", "不是形容词metallic，材料名词可直接构成名词定语。"],
  ["glass", "glasses", "n.", "玻璃", "建筑材料的不可数用法，glass walls中前置作材料定语。", "glass walls（玻璃墙）", "复数glasses常指眼镜或多个杯子，本文不能这样理解。"],
  ["laminated", "", "adj.", "层压的；多层黏合的", "laminated wood为经过层压加工的木材。", "laminated wood（层压木材）", "区别于整块实木；材料新型不自动等于环保。"],
  ["wood", "woods", "n.", "木材", "wood在材料清单中不可数，laminated说明加工方式。", "wood as a building material（作为建材的木材）", "woods复数可指树林，本文不是种树或林地。"],
  ["material", "materials", "n.", "材料", "同位概括metal、glass和wood，后接两个平行定语从句。", "new materials（新材料）", "new说明新型，不证明eco-friendly环保。"],
  ["symbolize", "symbolized symbolizes symbolizing", "v.", "象征；代表", "新材料在20世纪40年代象征未来，与today习以为常对照。", "symbolize the future（象征未来）", "symbolize不是已经成为未来的实物，而是承载象征意义。"],
  ["sophisticated", "", "adj.", "精巧的；讲究的", "修饰presentation，强调设计呈现的高明。", "sophisticated design（精巧设计）", "不取人世故圆滑义，也不必译为装饰复杂繁多。"],
  ["presentation", "presentations", "n.", "呈现方式；表现手法", "Mies's presentation指建筑外在效果，而非幻灯片演示。", "architectural presentation（建筑呈现方式）", "present作动词展示与presentation名词分开计数。"],
  ["mask", "masked masks masking", "v.", "掩盖；遮蔽", "精巧的呈现掩盖空间其实小而实用的事实。", "mask the fact that（掩盖……事实）", "动词比喻遮住认知焦点，不是口罩名词。"],
  ["space", "spaces", "n.", "空间", "the spaces he designed为室内可用空间，spaces可数指不同区域。", "efficient use of space（高效利用空间）", "不是宇宙太空，也不能仅凭small断言拥挤。"],
  ["empty", "emptier emptiest", "adj.", "空的；空荡的", "big and often empty是被rather than排除的空间状态。", "empty space（空荡的空间）", "并非少即是多就等于空无一物。"],
  ["apartment", "apartments", "n.", "公寓住宅", "towers中的居住单元，比较对象仍为邻楼中的公寓。", "a two-bedroom apartment（一套两居室公寓）", "apartment是一户住房，不等于整座tower。"],
  ["elegant", "", "adj.", "优雅的；雅致的", "elegant towers说明楼宇审美，与住宅面积大小分开判断。", "elegant towers（优雅的高楼）", "优雅不必大而奢华，正是文章的反常识点。"],
  ["tower", "towers", "n.", "高层楼宇；塔楼", "Mies built的对象，公寓位于其中。", "apartment towers（高层公寓楼）", "不是单独一户公寓，也不是泛指年长邻居。"],
  ["drive", "drives", "n.", "大道；道路名称组成", "Lake Shore Drive为芝加哥道路名，本文不取驾驶动词。", "Lake Shore Drive（湖滨大道）", "Drive出现在道路专名中可表大道，不能沿用完形drive开车义。"],
  ["two-bedroom", "", "adj.", "有两间卧室的", "复合形容词限定units，bedroom保持单数。", "two-bedroom units（两居室单元）", "不是只有两个房间，卧室数不同于总房间数。"],
  ["unit", "units", "n.", "住宅单元；一套住房", "two-bedroom units指每套公寓，而非计量单位这个抽象概念。", "housing units（住宅单元）", "under 1,000 square feet是每套住房面积。"],
  ["square", "squares", "adj.", "平方的", "square feet组合为面积单位，不表示住宅形状是正方形。", "square feet（平方英尺）", "length feet是长度，square feet是面积，不可混算。"],
  ["foot", "feet", "n.", "英尺（长度单位）", "与square连用表示平方英尺，feet为不规则复数。", "one square foot（一平方英尺）", "不同于身体脚或山脚义，本文数字给出面积。"],
  ["old", "older oldest", "adj.", "较早建成的；旧的", "older neighbors指这些公寓楼附近更早的建筑，不是住户年龄。", "older buildings（较老的建筑）", "与elder年长的不同，older可修饰建筑。"],
  ["neighbor", "neighbors", "n.", "邻近建筑（拟人用法）", "their older neighbors在建筑比较中指相邻老楼。", "older neighbors（附近更老的楼宇）", "不能将those apartments与邻居这个人比较面积。"],
  ["along", "", "prep.", "沿着；位于……一带", "along the city's Gold Coast说明附近旧楼所在区域。", "along the coast（沿海岸一带）", "强调线状地域分布，而非穿过某物的through。"],
  ["city", "cities city's", "n.", "城市", "the city's Gold Coast中city指芝加哥，所有格限定区域。", "the city's buildings（这座城市的建筑）", "city's为所有格，不是复数cities。"],
  ["airy", "airier airiest", "adj.", "通透的；明亮开阔的", "airy glass walls说明玻璃墙带来的开放感。", "an airy room（通透明亮的房间）", "这里不是漫不经心、空想式的引申义。"],
  ["wall", "walls", "n.", "墙；墙面", "glass walls由玻璃构成，是公寓受欢迎的原因之一。", "glass walls（玻璃墙）", "不是文章中的城市壁垒或网络围墙比喻。"],
  ["view", "views", "n.", "视野；可见景观", "the views they afforded指公寓提供的外部视野，不是观点意见。", "views from an apartment（从公寓看到的景观）", "view还可表示看法，本文由afford及空间环境确定景观义。"],
  ["afford", "afforded affords affording", "v.", "提供；给予", "apartments afforded views指公寓提供景观视野，不是负担购买公寓的费用。", "afford a view（提供视野）", "afford to buy才常为买得起，两种结构须分开。"],
  ["building", "buildings", "n.", "建筑物", "the buildings' details and proportions为复数建筑的细部和比例。", "a building's details（一栋建筑的细部）", "另一个句子started building中building为build动名词，按来源分开归一。"],
  ["detail", "details", "n.", "细部；细节", "建筑细部的优雅是受欢迎原因，而非被忽略的部分。", "architectural details（建筑细部）", "detailing为细部处理这个过程或方式，属派生名词而不并为屈折。"],
  ["proportion", "proportions", "n.", "比例关系；尺度配比", "建筑细部和整体之间的协调比例，不是Text 2广告收入占比。", "elegant proportions（优雅协调的比例）", "复数proportions常指形体各部分的尺度关系。"],
  ["architectural", "", "adj.", "建筑的", "architectural equivalent表示抽象艺术在建筑领域的对应表现。", "architectural design（建筑设计）", "派生形容词不同于architect建筑师和architecture建筑学。"],
  ["abstract", "", "adj.", "抽象的", "abstract art指文章用来类比建筑形式的艺术风格。", "abstract art（抽象艺术）", "不是论文摘要abstract的名词义。"],
  ["entirely", "", "adv.", "完全地", "not entirely foreign为部分否定，承认外来与本土两种来源。", "not entirely foreign（并非完全外来的）", "不能简化为完全不是外来的。"],
  ["modest", "", "adj.", "朴素的；适度的", "形容住宅规模和设计不奢张，非房屋具有谦虚人格。", "modest houses（朴素适度的住宅）", "modest修饰人可表谦逊，修饰规模常为不大的、适度的。"],
  ["usually", "", "adv.", "通常", "usually around 1,200 square feet限定典型面积，不作所有房屋准确数值。", "usually around that size（通常约为那个规模）", "usually和around都降低绝对精度，不能漏译。"],
  ["spread", "spreading spread spreads", "v.", "铺展；伸展开", "spreading分词修饰旧式大宅，强调占地展开。", "spreading houses（铺展开来的住宅）", "spread过去式与过去分词同形，本文是现在分词定语。"],
  ["two-story", "", "adj.", "两层的", "two-story限定ones所指的旧住宅，story为美式楼层表达。", "two-story houses（两层住宅）", "复合形容词story用单数，不译成两个故事。"],
  ["commission", "commissioned commissions commissioning", "v.", "委托设计或制作", "住宅由杂志向建筑师委托设计；from引受托方、by引委托者。", "commission a design（委托设计）", "不是Text 2委员会名词，也不是佣金义。"],
  ["talented", "", "adj.", "有才华的", "修饰现代建筑师，说明杂志选择的受托设计者。", "talented architects（有才华的建筑师）", "与famous著名的不同，有才华不自动意味着人人知晓。"],
  ["magazine", "magazines", "n.", "杂志", "Arts & Architecture magazine是案例住宅项目的委托方。", "an architecture magazine（建筑杂志）", "不是建筑师协会，也不是住宅开发商的同义名称。"],
  ["homegrown", "", "adj.", "本土产生的", "homegrown influence指美国本土对简约趋势的推动。", "a homegrown influence（一项本土影响）", "与foreign相对，不是家庭自己种的植物。"],
  ["aesthetic", "", "adj.", "审美的；美学的", "aesthetic effect讨论作品美感来源，作effect前置定语。", "aesthetic effect（审美效果）", "不同于功能效率本身，本文展示二者可兼容。"],
  ["landscape", "landscapes", "n.", "景观；周围自然景色", "是案例住宅审美效果的来源，直接支撑35题自然景观。", "the surrounding landscape（周围景观）", "不是政治局势的比喻用法；没有自动推出所有材料环保。"],
  ["forthright", "", "adj.", "直白的；坦率展现的", "forthright detailing在设计语境指简洁直白、不刻意遮掩的细部表达。", "forthright detailing（直白的细部处理）", "不能把它误读为放弃细节，亦非建筑师脾气直率的描述。"],
  ["detailing", "", "n.", "细部设计；细节处理", "与landscape、materials并列作from宾语，指处理细部的方式。", "careful detailing（细致的细部处理）", "本文名词化建筑术语独立于detail具体细节，不混算词位。"],
  ["mispredict", "mispredicted mispredicts mispredicting", "v.", "预测失误；错估", "may have mispredicted对Rapson过去的技术预见提出保留判断。", "mispredict a change（错估某种变化）", "mis-表错误；may have保留可能性，不是断言全部理念错误。"],
  ["revolution", "revolutions", "n.", "革命；重大变革", "mechanical revolution指机械技术改变生活的趋势，不是政权更迭。", "the mechanical revolution（机械技术革命）", "范围由mechanical限定，不自动改成特定历史工业革命时期。"],
  ["acquire", "acquired acquires acquiring", "v.", "获得；购得", "few families acquired helicopters指很少家庭实际拥有直升机。", "acquire equipment（购置设备）", "与predict预测不同，acquire描述实际取得。"],
  ["helicopter", "helicopters", "n.", "直升机", "作为没有在家庭广泛普及的技术设想，受few否定量限定。", "family helicopters（家庭使用的直升机）", "不能把存在某些家庭获得读成普遍拥有。"],
  ["get", "got gets getting gotten", "v.", "获得；拥有", "got clothes dryers指多数家庭最终获得干衣机。", "get a clothes dryer（购得一台干衣机）", "不是get over克服的搭配义。"],
  ["clothes", "", "plural n.", "衣服", "clothes dryers中作名词定语说明干燥对象。", "clothes dryers（衣物干燥机）", "clothes通常以复数形式使用，不等于cloth布料的普通复数。"],
  ["dryer", "dryers", "n.", "干燥机", "clothes dryer为家用干衣设备，与未普及的直升机形成对照。", "a clothes dryer（一台干衣机）", "dryer是设备名词，不是形容词dry的比较级drier。"],
  ["self-sufficiency", "", "n.", "自给自足；自立自足", "是Rapson相信值得追求且必然到来的生活理想。", "a belief in self-sufficiency（对自给自足的信念）", "不等于隔绝社会或所有家庭必须自己制造一切。"],
  ["desirable", "", "adj.", "值得向往的；可取的", "与inevitable并列作self-sufficiency的表语，前者评价价值。", "a desirable goal（值得追求的目标）", "desirable可取与inevitable必然并非同义：价值判断与趋势判断不同。"],
  ["widely", "", "adv.", "广泛地", "widely shared说明信念被许多人认同，保留独立副词词条。", "a widely shared belief（广泛认同的信念）", "wide形容范围宽，widely副词表示广泛，不作为屈折合并。"],
  ["share", "shared shares sharing", "v.", "共同持有；认同", "belief was widely shared为被动，意为信念广受认同。", "share a belief（认同同一信念）", "不是股票名词share或分配实物，而是共同持有观点。"],
  ["reflect", "reflected reflects reflecting", "v.", "反映；体现", "31题问住宅风格体现怎样的国民心态。", "reflect an attitude（反映一种态度）", "此处不是光学反射或深思熟虑的reflect on。"],
  ["practicality", "", "n.", "实用性", "31题干扰项描述设计功能，不是原文明确并列的节制与信心。", "efficiency and practicality（效率与实用性）", "要区分住宅特征与产生特征的心理因素。"],
  ["faithfulness", "", "n.", "忠诚；忠实", "31题干扰项与pride并列，原文未提这两种心理。", "faithfulness to a principle（忠于某项原则）", "confidence对未来的信心不等于faithfulness忠诚。"],
  ["found", "founded founds founding", "v.", "创建；创立", "32题干扰项说Mies创立包豪斯，原文只说推广理念与该校有关。", "found a school（创建一所学校）", "founded是found创建的规则过去分词，不归入find发现。"],
  ["hold", "held holds holding", "v.", "认为；持有观点", "Mies held that询问他关于优雅来源的主张。", "hold that something is true（认为某事成立）", "不是Text 2举行会议，也不是举着物体。"],
  ["identify", "identified identifies identifying", "v.", "把……等同；联系", "be identified with emptiness为33题干扰项，把优雅等同空无。", "be identified with an idea（与某观念联系或等同）", "与完形identify oneself表明身份不同。"],
  ["emptiness", "", "n.", "空无；空荡", "33题错项将优雅与空洞等同，原文反而否定big and often empty。", "spatial emptiness（空间空荡）", "empty形容词与emptiness派生名词分开计数。"],
  ["reliant", "", "adj.", "依赖的", "not reliant on abundant decoration概括优雅不靠大量装饰。", "be reliant on decoration（依赖装饰）", "与dependent on相近，须保留not否定。"],
  ["abundant", "", "adj.", "丰富的；大量的", "abundant decoration为33题正确选项中被否定依赖的对象。", "abundant decoration（大量装饰）", "大量不必然精巧，原文强调安排是否得当。"],
  ["spacious", "", "adj.", "宽敞的", "34题more spacious与原文smaller相反。", "spacious apartments（宽敞的公寓）", "看起来优雅通透不等于实际面积比邻楼更大。"],
  ["neighboring", "", "adj.", "邻近的", "修饰34题buildings，指附近楼宇，不能据此改变原文面积对比方向。", "neighboring buildings（邻近建筑）", "neighboring为定语形容词，neighbor名词可指邻居或邻近建筑。"],
  ["device", "devices", "n.", "装置；设备", "35题机械设备广泛使用的说法超出末句具体例证。", "mechanical devices（机械设备）", "不能由干衣机普及推出所有设备都广泛用于案例住宅。"],
  ["scene", "scenes", "n.", "景色；景观", "Natural scenes对应原文landscape，指被纳入审美的自然环境。", "natural scenes（自然景观）", "不是戏剧场景或新闻现场义。"],
  ["sacrifice", "sacrificed sacrifices sacrificing", "v.", "牺牲；舍弃", "35题说为总体效果牺牲细节，与forthright detailing为效果来源相反。", "sacrifice details（牺牲细节）", "简洁处理细节不等于不要细节。"],
  ["eco-friendly", "", "adj.", "环保的；对环境友好的", "35题干扰项把new materials偷换为环保材料，文中无此性质依据。", "eco-friendly materials（环保材料）", "新型与环保不是同义词，不能自动推断。"],
];

const names: Array<[string, string, string, string, string]> = [
  ["g", "", "G.I.缩写的组成字母", "G. I. Bill（退伍军人法案）", "原卷G. I.分开书写；与Bill合看为帮助退伍军人接受教育等的法案名称。"],
  ["i", "", "G.I.缩写的组成字母", "G. I. Bill（退伍军人法案）", "本文I为缩写字母，不是第一人称我；须与G.及Bill一起理解。"],
  ["ludwig", "", "路德维希（人名）", "Ludwig Mies van der Rohe（路德维希·密斯·凡·德·罗）", "密斯完整姓名中的名字部分，文中为推广少即是多的建筑师。"],
  ["mies", "mies's", "密斯（建筑师姓名）", "Mies's signature phrase（密斯的标志性格言）", "文中以Mies简称Ludwig Mies van der Rohe；Mies's为所有格。"],
  ["van", "", "凡（人名组成部分）", "Ludwig Mies van der Rohe（路德维希·密斯·凡·德·罗）", "van在此是姓名组成，不取普通名词厢式货车义。"],
  ["der", "", "德（人名组成部分）", "Ludwig Mies van der Rohe（路德维希·密斯·凡·德·罗）", "der是完整姓名称呼的一部分，不是英文比较级后缀。"],
  ["rohe", "", "罗（人名组成部分）", "Ludwig Mies van der Rohe（路德维希·密斯·凡·德·罗）", "与Mies van der共同构成文中建筑师姓名。"],
  ["bauhaus", "", "包豪斯（设计学校）", "the Bauhaus（包豪斯设计学校）", "原文同位语a school of design给出学校属性，相关设计师影响美国建筑。"],
  ["chicago", "chicago's", "芝加哥", "Chicago's Lake Shore Drive（芝加哥湖滨大道）", "Chicago's为城市名所有格，限定道路所属城市。"],
  ["lake", "lakes", "湖（湖滨大道名称组成）", "Lake Shore Drive（湖滨大道）", "Lake Shore Drive为道路专名，Lake与Shore组合描述湖滨地带。"],
  ["shore", "shores", "岸（湖滨大道名称组成）", "Lake Shore Drive（湖滨大道）", "Shore与Lake和Drive共同构成专名，不能把整串译成驾驶到湖岸。"],
  ["gold", "", "黄金（区域名组成）", "Gold Coast（黄金海岸区）", "由the city's限定可知是芝加哥的区域，不是澳大利亚城市。"],
  ["coast", "coasts", "海岸（区域名组成）", "Gold Coast（黄金海岸区）", "与Gold共同构成原文芝加哥区域名，普通coast是海岸。"],
  ["frank", "", "弗兰克（人名）", "Frank Lloyd Wright（弗兰克·劳埃德·赖特）", "美国本土设计源流例证中的建筑师名字，不是形容词坦率。"],
  ["lloyd", "", "劳埃德（人名组成）", "Frank Lloyd Wright（弗兰克·劳埃德·赖特）", "与Frank、Wright共同识别风格由铺展转向适度的建筑师。"],
  ["wright", "", "赖特（建筑师姓名）", "Frank Lloyd Wright（弗兰克·劳埃德·赖特）", "不要与Mies混同，30年代房屋与他自己早先设计比较。"],
  ["ralph", "", "拉尔夫（人名）", "Ralph Rapson（拉尔夫·拉普森）", "末句案例住宅建筑师的名字部分。"],
  ["rapson", "", "拉普森（建筑师姓名）", "Ralph Rapson（拉尔夫·拉普森）", "文中讨论他的技术预测可能失准，但自给自足理念广受认可。"],
];
rows.push(...names.map(([headword, forms, meaning, collocation, use]): LexiconRow => [headword, forms, "proper n. / name part", meaning, use, collocation, "专名用于识别人或地点，不以普通词近义词替换；具体身份按本篇原文判断。"]));
const reviewed = reviewedLexicon(rows);
export const passage2011P3Lexicon = reviewed.entries;
export const passage2011P3LemmaAliases: Record<string, string> = { ...reviewed.aliases, widely: "widely", detailing: "detailing", housing: "housing" };
export const passage2011P3CollocationGlosses = reviewed.glosses;
export const passage2011P3FormPartOfSpeech: Record<string, string> = {
  returning: "v.-ing（伴随分词）", going: "v.-ing（伴随分词）", lining: "v.-ing（伴随分词）", following: "v.-ing（后置定语）", home: "adv.", on: "prep.", before: "prep.", living: "gerund", designing: "v.-ing（定语）", german: "n.", american: "adj.", associated: "v.-ed（分词定语）", organized: "v.-ed（分词）", commissioned: "v.-ed（分词定语）", means: "v.（第三人称单数）", signature: "n.（前置定语）", building: "gerund", buildings: "n.（复数）", square: "adj.", under: "prep.", first: "adv.", empty: "adj.", foreign: "adj.", yet: "adv.", both: "correlative conjunction part", widely: "adv.", shared: "v.-ed（被动分词）", founded: "v.-ed（创建的过去分词）", identified: "v.-ed（被动分词）", held: "v.（过去式）", used: "v.-ed（过去习惯结构/被动）", arts: "n.（杂志名称组成）", study: "n.（项目名称组成）",
};
const otherMeanings: Record<string, string[]> = {
  depression: ["抑郁；低落；凹陷处。本文the Depression为经济大萧条。"],
  post: ["邮政；岗位；柱子；网络帖子；v. 邮寄或发布。"],
  course: ["课程；路线；一道菜；of course当然。本文为建筑发展的进程。"],
  signature: ["签名；特有标志。signature作名词定语可表示标志性的。"],
  employ: ["雇用人员；运用方法。employ a method采用一种方法。"],
  mask: ["n. 面具；口罩。v. 掩盖，如mask a problem掩盖问题。"],
  view: ["观点、看法；v. 看待、观看；in view of鉴于。"],
  modest: ["谦逊的；不多的、不大的，如a modest income不高的收入。"],
  abstract: ["n. 摘要；v. 提取、抽象概括。本文为抽象艺术的形容词。"],
  commission: ["n. 委员会；佣金；委托任务。本文为委托设计的动词。"],
  afford: ["afford to do负担得起或有条件做某事。afford a view则是提供视野。"],
};
for (const [headword, meanings] of Object.entries(otherMeanings)) passage2011P3Lexicon[headword].otherMeanings = meanings;

export const passage2011P3SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2011-p3-s8": { derive: { contextualSubstitutions: [{ label: "stem", chinese: "源自", fit: "direct", rewrittenSentence: "Elegance, he believed, did not stem from abundance.", nuance: "stem from与derive from均表示来源，前者稍日常；保留否定，不能变成优雅依赖堆砌。", target: "word:stem" }] } },
  "2011-p3-s1": { with: { contextualMeaning: "伴随着（引独立结构）", use: "with soldiers returning/going/lining引三个并列分词，逻辑主语均为soldiers。" }, on: { contextualMeaning: "借助；依据资助安排", use: "on the G. I. Bill指借助退伍军人法案的教育支持上大学。" }, i: { partOfSpeech: "abbreviation part", contextualMeaning: "G.I.缩写中的字母", use: "G. I. Bill整体指法案名称，不是人称代词我。" } },
  "2011-p3-s2": { it: { contextualMeaning: "话题结构形式主语；回指战后时期", use: "when it came to是谈及某事的习语；主句it was回指那个时代，两个it作用不同。" }, that: { partOfSpeech: "conj.", contextualMeaning: "引出信念的内容", use: "belief that后为完整less could be more命题，that不作从句主宾。" } },
  "2011-p3-s3": { that: { partOfSpeech: "det.", contextualMeaning: "那种（节制）", use: "that restraint回指live with less形成的克制，非从句引导词。" }, make: { contextualMeaning: "使……变得", use: "made housing stylish是make+宾语+形容词，stylish作宾补。" } },
  "2011-p3-s5": { who: { partOfSpeech: "relative pron.", contextualMeaning: "指密斯", use: "同作emigrated与took up的主语，中间like...为比较背景。" }, take: { contextualMeaning: "开始担任（take up）", use: "took up posts为开始任职，不是Text 1占用时间。" } },
  "2011-p3-s6": { come: { contextualMeaning: "逐渐；后来开始", use: "came to exert表示发展成产生影响的局面，不是空间来到。" }, so: { contextualMeaning: "如此（发挥影响）", use: "none more so than Mies省略重复的exert influence，意为无人影响更大。" } },
  "2011-p3-s7": { impact: { partOfSpeech: "n.", contextualMeaning: "效果；表现力", use: "has more impact的名词宾语，比较少而精与大量装饰的效果。" }, have: { partOfSpeech: "v.", contextualMeaning: "产生；具有", use: "has more impact中has为实义动词，不是完成时助动词。" } },
  "2011-p3-s9": { that: { partOfSpeech: "relative pron.", contextualMeaning: "指前述材料", use: "第一个that作take宾语，第二个that作symbolized主语，两个从句平行修饰materials。" }, take: { contextualMeaning: "视为（take for granted）", use: "take something for granted指习以为常，不是拿走材料。" } },
  "2011-p3-s10": { that: { partOfSpeech: "conj.", contextualMeaning: "引出事实内容", use: "the fact that后内容完整；spaces后的he designed另是省略关系词的定语从句。" } },
  "2011-p3-s11": { those: { contextualMeaning: "那些公寓", use: "than those in their older neighbors避免重复apartments，比较对象必须同类。" }, their: { contextualMeaning: "这些新塔楼的", use: "their older neighbors指新塔楼附近更老的建筑，非邻居年龄。" }, under: { contextualMeaning: "不到；少于", use: "under 1,000 square feet限定面积小于这一数值。" } },
  "2011-p3-s12": { they: { contextualMeaning: "这些公寓", use: "they were popular与views they afforded均以公寓为主体。" }, proportion: { contextualMeaning: "建筑的比例与尺度关系", use: "details and proportions是并列审美因素，不是广告收入占比。" }, so: { contextualMeaning: "如此；很", use: "so popular修饰abstract art，不能把当时流行误连到建筑材料。" } },
  "2011-p3-s13": { entirely: { contextualMeaning: "完全地（在否定范围内）", use: "not entirely foreign为并非完全外来，引出本土例子。" } },
  "2011-p3-s14": { he: { contextualMeaning: "弗兰克·劳埃德·赖特", use: "比较他30年代与19世纪90年代、20世纪初的设计，不是密斯。" }, around: { contextualMeaning: "大约", use: "around 1,200 square feet表示近似面积，不是围绕某地。" }, one: { partOfSpeech: "pron.（复数ones）", contextualMeaning: "住宅", use: "two-story ones替代前面的houses。" } },
  "2011-p3-s15": { by: { contextualMeaning: "由（委托方）", use: "by杂志引委托者，from architects引受托提供设计者，不能倒置。" }, yet: { contextualMeaning: "又；再", use: "yet another homegrown influence添加第二个本土影响，不是转折然而。" } },
  "2011-p3-s17": { impact: { partOfSpeech: "v.", contextualMeaning: "影响", use: "would impact everyday life为及物谓语，与第7句名词效果区分。" }, have: { partOfSpeech: "aux.", contextualMeaning: "构成情态完成式", use: "may have mispredicted表示对既往预测作可能失准的推断。" }, few: { contextualMeaning: "几乎没有几个", use: "few American families有否定意味，不能译成许多家庭。" }, most: { partOfSpeech: "pron.", contextualMeaning: "大多数美国家庭", use: "most省略前文American families，作got主语。" }, that: { partOfSpeech: "conj.", contextualMeaning: "引出信念内容", use: "belief that self-sufficiency...为同位内容从句，that不作主宾。" } },
};
