import type { ContextualSubstitution, SentenceWordContext } from "./contextual-vocabulary";

type Entry = {
  partOfSpeech: string; contextualMeaning: string; use: string; specialForms: string[];
  examSynonyms: string[]; collocations: string[]; otherMeanings?: string[];
  contextualSubstitutions?: ContextualSubstitution[];
};

const rows: string[][] = [
  ["speech", "speeches", "n.", "言论；说话", "freedom of speech中speech指表达观点的活动，非某场演讲；of引出自由涉及的领域。", "freedom of speech（言论自由）", "与talk交谈相比，speech可指正式演讲或语言表达能力；本文指公开发表观点。"],
  ["very", "", "adj.（强调用法）", "恰恰的；正是这一", "that very anonymity中very位于限定词后、名词前，强调正是前文匿名性；不是程度副词非常。", "that very anonymity（恰恰这种匿名性）", "与very safe的副词用法不同；本句可理解为precisely that所表达的强调。"],
  ["behind", "", "prep.", "是……背后的原因", "be behind the explosion以位置比喻因果，说明匿名性促成犯罪激增。", "be behind a change（是变化背后的原因）", "本句不是落在后面；不能沿用描述发展落后的behind义项。"],
  ["approach", "approaches", "n.", "做法；方案", "回指自愿的身份认证安排；the approach是名词，不是动词接近。", "an approach to security（保障安全的做法）", "与method偏具体方法相比，approach可表示整体处理思路。"],
  ["concern", "concerned concerns concerning", "v.", "使担忧", "are concerned中concerned按状态形容词理解，说明另一些倡导者担忧。", "be concerned about privacy（担忧隐私）", "与be concerned with涉及区别；本句不是说这些人只是与某事有关。"],
  ["once", "", "adv.", "一次", "log in just once与many different services对比，强调一次认证而非从前。", "log in once（登录一次）", "同形once作连词可表一旦，另有曾经义；本句由just及single sign-on锁定次数。"],
  ["still", "", "adv.", "尽管如此；仍然", "句首Still转折前文优点；would still leave中的still指保护不足仍持续，两处不可强行共用一个细义。", "still leave a risk（仍留下风险）", "句首转折可与nevertheless比较；句中持续义可与continue的含义比较。"],
  ["while", "", "conj.", "在……的同时", "while bringing...给出并行政策目标，bringing是非限定形式；不表示两个人的态度对比。", "while protecting privacy（在保护隐私的同时）", "与though尽管区别；while也能表对比，但本文强调同时兼顾。"],
  ["leave", "leaves left leaving", "v.", "使……仍处于某状态", "leave much of the Internet vulnerable中vulnerable是宾语补足语；不表示离开。", "leave a system vulnerable（使系统仍易受攻击）", "与make侧重造成新状态相比，leave突出未消除或保留现有状态。"],
  ["themselves", "", "reflexive pron.", "他们自己的身份", "identify themselves中的反身代词回指Internet users，说明网民表明自身身份，不指迁移运动。", "identify themselves（表明他们自己的身份）", "与them不同，themselves明确动作的对象与主语同指。"],
  ["drive", "drives drove driven driving", "v.", "驾驶；开车", "to drive on public roads为取得许可后所能进行的行为，取交通义而非推动作用。", "drive on public roads（在公共道路上开车）", "与ride常指骑乘区别；drive强调操纵车辆，过去式drove、分词driven。"],
  ["carry", "carries carried carrying", "v.", "继续（与on连用）", "第十一题carry on为继续活动的短语，不表达进入账号。", "carry on（继续）", "与log in登录不同；carry单独可表示携带或承载。"],
  ["set", "sets setting", "v.", "开始出现（与in连用）", "第十一题set in多指恶劣天气、衰败等开始并持续；过去式和分词均为set。", "set in（开始并持续）", "与start相比，set in通常不以用户为主动登录主体。"],
  ["effect", "effects", "n.", "实际效果（in effect整体表实际上）", "In effect位于句首概括提案实际作用，不按孤立的影响逐字翻译。", "in effect（实际上；实质上）", "与in fact都可引出实情，in effect更常概括实际作用。"],
  ["return", "returns", "n.", "回报；回应", "第十二题in return是作为回报，需前面有给予或交换关系。", "in return（作为回报）", "与in effect实际上不同；return作动词另可表返回。"],
  ["suggest", "suggested suggests suggesting", "v.", "建议；提出", "第九题suggest which...会成为建议加入哪个系统，未表达用户自行挑选的权利。", "suggest a plan（提出计划）", "与select选择不同；suggest还可表示迹象暗示，但非本题所需动作。"],
  ["have", "has had having", "aux. / v.", "构成完成时；拥有", "has swept、has divided及have been authenticated中have是完成时助动词；already have systems中是实义动词。", "have been authenticated（已经获得认证）", "助动词have不能随意改为possess；只有拥有义才可作词义比较。"],
  ["be", "am is are was were been being", "aux. / v.", "是；处于；构成被动", "本篇既有is behind、are concerned等系表，也有be preserved、be forced等被动结构；后接分词须判断语态。", "be forced to register（被强制注册）", "助动词和系动词属于结构功能，不能用词义相近的普通实义动词替换。"],
  ["will", "would", "modal v.", "会；将（设想中的结果）", "本文would描述提案实施后可能出现的功能或后果，不表示过去反复习惯，也不是随意。", "would create a safer system（会建立更安全的系统）", "与will直接预测相比，would适合在提案设想和过去报道框架下表达后果。"],
  ["may", "might", "modal v.", "可能；或许", "might use表示系统可能选择哪种技术形式，不是实际已经完成的部署。", "might use a smart card（可能使用智能卡）", "与must必须不同，might保留可选方案和不确定性。"],
  ["and", "", "conj.", "和；并且", "可连接safety and security等名词，use与authenticate等谓语，或Users...and only registered users...两个分句。", "register and identify（注册并表明身份）", "并列关系不能不加区分换成but转折或or选择。"],
  ["but", "", "conj.", "但是；却", "句首But转折匿名性的优缺点；log in once but use...对照少量登录与多种服务。", "once but many services（一次认证却能使用多种服务）", "与and不同，but突出预期或数量关系的反差。"],
  ["to", "", "prep. / 不定式标记", "给；关联到；引出动作", "afford...to users中引接受者，linked to引关联目标，to create、to register引不定式动作；按后接成分区分。", "linked to a computer（与电脑关联）", "to后接名词时为介词，接动词原形时常是不定式标记，不能一律译成到。"],
  ["that", "", "det. / relative pron. / conj.", "那一；引出限定或命题", "that very anonymity中限定名词；that has swept等引定语；seems clear that与argue that引命题内容。", "that very anonymity（恰恰这种匿名性）", "定语从句中that担任成分，内容从句中that仅作连接；须查看从句是否缺主宾语。"],
  ["with", "", "prep.", "带有；以；和……相比", "contrasts with引比较对象；with confidence或skepticism说明态度；with neighborhoods补充环境特征。", "with confidence（充满信心地）", "同一个介词随中心词改变关系，不能统一替换为表示工具的by。"],
  ["on", "", "prep. / 小品词", "在……平台上；构成动词短语", "on which指交易运行依托的基础设施；选项carry on、linger on中则为小品词。", "run on infrastructure（依托基础设施运行）", "平台义on与穿越范围的across不同；短语中不可只按在……上逐字译。"],
  ["as", "", "prep.", "作为；称为", "describe it as a voluntary ecosystem中as引对宾语身份的补充说明，不是原因连词。", "describe A as B（把A描述为B）", "此处as不能换成because；A与B指同一对象的两种说法。"],
  ["by", "", "prep.", "由；被", "issued by government、envisioned by Schmidt、greeted by experts中引被动动作的施事。", "issued by the government（由政府签发的）", "与with引态度或工具区别；by在这些短语中回答由谁做。"],
  ["it", "", "pron.", "该方案；形式主语或宾语", "described it中的it回指提案；make it possible为形式宾语；It seems clear为形式主语，分别由后文补足内容。", "make it possible（使某事成为可能）", "形式it通常不单独译为它；实义it则需找前文所指。"],
  ["which", "", "interrogative det. / relative pron.", "哪一个；该……", "which system to join中为疑问限定词；in which与on which回指系统或基础设施。", "which system to join（加入哪个系统）", "不能把间接疑问的which全部当定语关系代词；先看有无先行词。"],
  ["create", "created creates creating", "v.", "建立；创建", "create a federation和create a walled garden均表示产生新的组织或受控环境。", "create a federation（建立联盟）", "与discover发现已有事物不同，create强调使此前没有的东西出现。"],
  ["afford", "affords afforded affording", "v.", "提供；给予", "afford anonymity to users中afford直接接所提供的条件，再用to引接受者。", "afford protection（提供保护）", "与provide相近；afford to do则指有条件或负担得起做某事。"],
  ["anonymity", "", "n.", "匿名性；身份不被识别的状态", "不可数名词；affords的宾语，也是下句that very所回指的中心，不是某人的名字。", "online anonymity（网络匿名性）", "与privacy不同：前者强调身份不可知，后者强调个人领域不被侵犯。"],
  ["blessing", "blessings", "n.", "有利的事；福祉", "a blessing to...对隐私和言论自由的益处作补充评价；可数名词。", "a blessing to freedom（对自由有益的事）", "与benefit相近，但blessing带更强的积极评价，也可表示祝福。"],
  ["sweep", "swept sweeps sweeping", "v.", "迅速席卷；蔓延", "has swept across the Web是现在完成时；主语是犯罪激增这一现象，取比喻义。", "sweep across the Web（席卷网络）", "与spread相比，sweep更强调迅猛和覆盖面广；也有扫地义。"],
  ["across", "", "prep.", "遍及；横越", "across the Web说明网络犯罪蔓延的范围，不是介词on所表示的承载平台。", "across the Web（遍及网络）", "与through相比，across着眼覆盖整个范围，through强调穿过内部或借助途径。"],
  ["cyber-crime", "", "n.", "网络犯罪", "cyber-表示网络相关；of cyber-crime限定explosion，讨论数量激增。", "the explosion of cyber-crime（网络犯罪激增）", "与普通crime相比，cyber-crime限定网络犯罪，不表示全部犯罪。"],
  ["web", "", "n.", "万维网；网络", "the Web在本文指互联网服务空间，专门称呼通常首字母大写。", "across the Web（遍及网络）", "与Internet在通俗语境可近指；技术上Web是互联网的一类服务，不完全等同。"],
  ["preserve", "preserved preserves preserving", "v.", "保护；维持", "can privacy be preserved是疑问句中的情态被动，privacy为受保护对象。", "preserve privacy（保护隐私）", "与protect接近；preserve更强调让既有状态延续，protect侧重免受损害。"],
  ["bring", "bringing brings brought", "v.", "带来", "bringing safety and security中带来安全是while后的同时发生行为；bring的过去式和分词均为brought。", "bring safety to users（给用户带来安全）", "与take区别在观察方向：bring带到说话视点，take带往别处。"],
  ["security", "", "n.", "安全保障；防护", "与safety并列；computer security具体指对攻击或未经授权访问的防护。", "computer security（计算机安全）", "与safety侧重免于危险相比，security常突出防范蓄意攻击和威胁。"],
  ["lawless", "", "adj.", "无法无天的；缺乏法治约束的", "作seems后的表语，increasingly修饰程度；承接网络犯罪激增。", "a lawless world（失序的世界）", "与careless粗心、helpless无助不同，lawless的核心是法律和秩序缺失。"],
  ["careless", "", "adj.", "粗心的；不小心的", "第三题干扰项，评价行事缺少注意，不说明法治约束不足。", "a careless mistake（粗心造成的错误）", "与lawless的无法无天不同；careless强调疏忽而非违法。"],
  ["pointless", "", "adj.", "无意义的；无益的", "第三题干扰项，pointless讨论目标价值，不表达网络秩序失控。", "a pointless argument（无意义的争论）", "与useless相近，但pointless尤其强调无目的或不值得做。"],
  ["helpless", "", "adj.", "无助的；无力的", "第三题干扰项，表示缺少能力或帮助，不是缺少法律约束。", "feel helpless（感到无助）", "与hopeless无望不同：helpless强调无力处理，hopeless强调看不到希望。"],
  ["howard", "", "proper n.", "霍华德（人名）", "与Schmidt共同组成提案者姓名，作offered的主语。", "Howard Schmidt（霍华德·施密特）", "专有姓名不作近义替换，保持人物指代一致。"],
  ["schmidt", "", "proper n.", "施密特（姓氏）", "Howard Schmidt及Mr. Schmidt指同一提案者，不拆译为普通词。", "Mr. Schmidt（施密特先生）", "专有姓氏不作近义替换；Mr.为称谓，不是名字的一部分。"],
  ["nation", "nation's nations", "n.", "国家", "the nation's为所有格，限定网络事务主管的所属层级。", "the nation's cyber-czar（国家网络事务主管）", "与state都可指国家；nation还可侧重国民或民族共同体。"],
  ["cyber-czar", "", "n.", "网络事务主管（比喻性称呼）", "作为Howard Schmidt的同位语，表示负责协调网络事务的高级官员，不是实际沙皇。", "the nation's cyber-czar（国家网络事务主管）", "该新闻用语的czar比喻统筹某领域的主管，不能按君主头衔直译。"],
  ["offer", "offered offers offering", "v.", "提出；提供", "offered the government a proposal为双宾语，政府是接受方，proposal是所提供内容。", "offer somebody a proposal（向某人提出方案）", "与give相比，offer侧重提出可供接受的东西，并不保证对方采纳。"],
  ["proposal", "proposals", "n.", "提案；建议；方案", "offered的直接宾语；to make the Web a safer place说明方案目标。", "a proposal to improve safety（改善安全的提案）", "与compromise相比，proposal不必已经包含双方让步。"],
  ["reminder", "reminders", "n.", "提醒；提醒物", "第四题干扰项，不能概括后文一整套身份认证方案。", "a reminder to act（提醒采取行动）", "与proposal提案不同，reminder让人记起已有事项而非提出新制度。"],
  ["compromise", "compromises compromised compromising", "n. / v.", "妥协；折中方案；损害", "第四题a后需名词，compromise虽可作折中方案，但原段没有协商让步的依据。", "reach a compromise（达成妥协）", "与proposal相比，compromise特指让步达成的折中；动词还可表示损害安全。"],
  ["safe", "safer safest", "adj.", "安全的", "safer修饰place，是safe的比较级；后文safe neighborhoods仍为形容词定语。", "make the Web safer（使网络更安全）", "与secure相近；secure更常突出防护可靠，safe强调不易遭受危险。"],
  ["voluntary", "", "adj.", "自愿的；非强制的", "限定identity system与ecosystem，重点是是否参加由用户决定，不是认证标准可随意改变。", "voluntary participation（自愿参与）", "与compulsory强制的、forced被迫的相反；不要误读为没有准入验证。"],
  ["trust", "trusts trusted trusting", "v.", "信任；相信", "trusting以交易者为逻辑主语，后接双方及基础设施的身份；trusted作被信任的定语。", "trust each other（互相信任）", "与believe相比，trust更侧重可靠性和可托付；believe还可表示相信陈述为真。"],
  ["identity", "identities", "n.", "身份", "复数identities分别指用户、交易者和系统的可核验身份，不能与账户密码混为一谈。", "authenticate an identity（核验身份）", "与identification不同，identity是身份本身，identification是识别过程或身份证明。"],
  ["high-tech", "", "adj.", "高科技的", "修饰名词equivalent，对比后面的实体钥匙、指纹及照片证件。", "a high-tech equivalent（高科技对应物）", "与advanced先进的相比，high-tech具体强调运用高技术，而非所有方面都优越。"],
  ["equivalent", "equivalents", "n.", "等效物；对应物", "the equivalent of后列出三项凭证，指功能等效而不是外形相同。", "the equivalent of a key（相当于钥匙的东西）", "与equal相近但词性结构不同；equivalent可作名词或形容词，常接of或to。"],
  ["interference", "", "n.", "干扰；干预", "第五题干扰项，不可数；不能表达一个系统与三种凭证功能等效。", "interference with a signal（对信号的干扰）", "与intervention干预相比，interference通常更偏负面或指信号扰动。"],
  ["entertainment", "", "n.", "娱乐；娱乐活动", "第五题干扰项，语义属于休闲消遣，不是认证凭证。", "online entertainment（在线娱乐）", "与amusement同属娱乐领域，均不能表达equivalent的对应关系。"],
  ["physical", "", "adj.", "实体的；物质的", "physical key与数字认证对应，指可触摸的实物钥匙，不是身体健康义。", "a physical key（实体钥匙）", "与digital数字的在本句形成实体与电子形式的对照。"],
  ["key", "keys", "n.", "钥匙", "与fingerprint和photo ID card并列，physical限定其实体形态。", "a physical key（实体钥匙）", "本句不是形容词关键的，也不是答案要点；比喻义可指关键或解题方法。"],
  ["fingerprint", "fingerprints", "n.", "指纹", "作为可识别个人的生理特征，与钥匙和照片证件并列。", "a fingerprint scan（指纹扫描）", "与photo照片不同，fingerprint记录手指纹路，不是整个人像。"],
  ["photo", "photos", "n.", "照片", "在photo ID card中作名词定语，说明证件带照片；复数photos，不加es。", "a photo ID card（带照片的身份证件）", "与photograph同义，photo为常用短式；不等于身份identity本身。"],
  ["id", "", "n.", "身份证明；身份证件", "ID为identification的缩写，photo ID card是一种带照片的身份证明。", "photo ID（带照片的身份证明）", "缩略语通常大写，不能按两个独立字母的日常词义拆译。"],
  ["card", "cards", "n.", "卡片；证卡", "identity card为身份证明卡，智能卡与数字凭证是可选择的认证形式。", "an identity card（身份证明卡）", "与credential相比，card强调实体形式，credential可为数字资格凭证。"],
  ["roll", "rolled rolls rolling", "v.", "卷；使合为一体", "all rolled into one为固定比喻表达，以过去分词说明多种功能被整合。", "rolled into one（合为一体）", "本句不是物体滚动，而是把多个角色或功能综合起来。"],
  ["smart", "", "adj.", "智能的", "smart identity card指带电子处理或存储能力的身份卡，不是外表漂亮的卡。", "a smart card（智能卡）", "与clever都可描述聪明，但形容技术设备时smart有智能化专门用法。"],
  ["credential", "credentials", "n.", "身份凭证；资格证明", "digital credential是电子认证材料；linked to短语说明它与特定电脑关联。", "a digital credential（数字身份凭证）", "与password不同，credential范围更广，还可能包括证书等认证材料。"],
  ["link", "linked links linking", "v.", "关联；连接", "linked to是被动分词定语，修饰credential；to说明绑定的计算机。", "be linked to a computer（与电脑关联）", "与connect相近；chain to更强调用链条束缚，不宜当作中性技术关联。"],
  ["direct", "directed directs directing", "v.", "引导；指向", "第七题干扰项，directed to可表示被引向某处，而非凭证绑定。", "direct attention to a problem（把注意力引向问题）", "与link to建立关联不同，direct to着重指向或引导方向。"],
  ["chain", "chained chains chaining", "v.", "用链子锁住；束缚", "第七题干扰项，chained to强调物理或比喻束缚，不是中性身份关联。", "chain something to a post（把某物锁在柱子上）", "与link不同，chain常含无法自由离开的束缚意味。"],
  ["authenticate", "authenticated authenticates authenticating", "v.", "验证真实性；核验身份", "authenticate users为及物用法；have been authenticated为现在完成时被动。", "authenticate users（核验用户身份）", "与identify识别谁是谁不同，authenticate强调核实声称身份是否真实。"],
  ["user", "users", "n.", "用户；使用者", "指网络服务使用者；既是匿名性受益者，也是认证、注册和选择系统的主体。", "Internet users（网民）", "与customer顾客相比，user强调使用，不必已经付费购买。"],
  ["range", "ranges", "n.", "一系列；多种", "a range of online services中range表示多样范围，不是航程。", "a range of services（一系列服务）", "与variety相近，但range更突出覆盖范围；本句不能沿用飞行文章的航程义。"],
  ["service", "services", "n.", "服务；在线功能", "online services及different services均指通过网络提供的功能，不是任职。", "online services（在线服务）", "与system不同，service是提供给用户的功能，system是实现服务的体系。"],
  ["federation", "federations", "n.", "联盟；联合体", "of private online identity systems说明成员为各私营系统，不是政治国家联邦。", "a federation of systems（系统联盟）", "与a single system不同，federation强调多个保有自身身份的成员联合。"],
  ["private", "", "adj.", "私营的；非政府的", "private online identity systems与government issued license对照，不是说只有私人可见。", "private identity systems（私营身份认证系统）", "与public在经营主体上相对；不应直接等同privacy的隐私保护。"],
  ["dismiss", "dismissed dismisses dismissing", "v.", "解散；驳回；不予考虑", "第八题干扰项，dismiss a federation与建立认证联盟的方向相反。", "dismiss a proposal（不予考虑一项提案）", "与reject都可表不接受；dismiss还可表解雇某人。"],
  ["select", "selected selects selecting", "v.", "选择；挑选", "could select后接which system to join，突出用户在系统之间自行选择。", "select a system（选择系统）", "与choose近义，select稍偏从一组候选中审慎挑选；本句不是形容词精选的。"],
  ["realize", "realized realizes realizing", "v.", "意识到；实现", "第九题干扰项，这里需作选择而非仅意识到哪个系统可加入。", "realize a mistake（意识到错误）", "与select选择不同；realize a goal又可表示实现目标。"],
  ["register", "registered registers registering", "v.", "注册；登记", "registered users中的分词表示已登记；to register是应进行的注册行为。", "register for a service（注册一项服务）", "与log in不同：注册建立使用资格，登录使用既有资格进入系统。"],
  ["navigate", "navigated navigates navigating", "v.", "浏览；访问；在……中找到路径", "navigate those systems取计算机网络用法，those systems是直接宾语。", "navigate a website（浏览网站）", "与browse相近；navigate还可指航海或辨认路线，不能只译成驾船。"],
  ["contrast", "contrasts contrasted contrasting", "v.", "与……形成对照", "contrasts with连接自愿方案和政府许可方案，主语单数用contrasts。", "contrast with another approach（与另一做法对照）", "与compare比较不同，contrast突出差异而不仅是共同点。"],
  ["license", "licensed licenses licensing", "n. / v.", "执照；许可；发给许可", "第八句是名词执照，末句be licensed为动词被动；须按句分辨。", "be licensed to drive（获准驾车）", "与permission相比，license常是正式制度性许可；英式名词也常拼作licence。"],
  ["driver", "drivers driver's", "n.", "驾驶者；司机", "driver's为所有格修饰license；drivers作末句must be licensed的主语。", "a driver's license（驾驶执照）", "本篇指驾驶者；在其他语境driver也可指驱动程序或推动因素。"],
  ["issue", "issued issues issuing", "v.", "签发；颁发", "issued by the government后置修饰license，表示正式授权而非把证件运输过去。", "issue a license（签发执照）", "与deliver送达、distribute分发区分：issue侧重正式签发和效力。"],
  ["deliver", "delivered delivers delivering", "v.", "递送；交付", "第十题干扰项，delivered强调送到接收者手中，不突出执照授权。", "deliver a package（递送包裹）", "与issue签发不同；deliver a speech又表示发表讲话。"],
  ["distribute", "distributed distributes distributing", "v.", "分发；分配", "第十题干扰项，distributed强调把东西分给多个接收者。", "distribute supplies（分发物资）", "与issue颁发不同，distribute不必包含官方授权的含义。"],
  ["google", "", "proper n.", "谷歌（公司名）", "与Microsoft并列，举出现成单点登录系统的提供者。", "Google and Microsoft（谷歌和微软）", "公司专名不作近义替换；此处不是动词‘用搜索引擎查询’。"],
  ["microsoft", "", "proper n.", "微软（公司名）", "与Google同作are的并列主语，不能拆译成micro与soft两个普通词。", "Microsoft services（微软提供的服务）", "公司专名不作近义替换，保持实体指代。"],
  ["sign-on", "", "n.", "登录；身份进入验证", "single sign-on整体指一次认证进入多个服务的单点登录机制。", "single sign-on（单点登录）", "与log in的区别主要是词性：sign-on作名词，log in是动词短语。"],
  ["log", "logged logs logging", "v.", "登录（与in连用）", "log in just once与single sign-on对应；log作动词时过去式logged双写g。", "log in（登录）", "与register注册不同，log in指用既有凭证进入；log也可作日志或原木名词。"],
  ["linger", "lingered lingers lingering", "v.", "逗留；迟迟不消失", "第十一题linger on为继续逗留或持续存在，不是网络登录。", "linger on（迟迟不散）", "与stay停留相比，linger常含超出预期或不愿离开的意味。"],
  ["vain", "", "adj.", "徒劳的；无效果的", "in vain是固定副词短语‘徒劳地’，第十二题无结果失败的依据。", "in vain（徒劳地）", "与in effect实际上不同；vain形容人时另有自负的义项。"],
  ["garden", "gardens", "n.", "花园；园地", "walled garden作封闭网络环境的比喻，强调边界和准入。", "a walled garden（有围墙的花园；封闭网络环境）", "此处不是介绍真实园艺场地；花园意象承接安全社区比喻。"],
  ["wall", "walls walled walling", "n. / v.", "墙；用墙围住", "walled为过去分词作定语，garden是被围住的园地；引申为准入受控环境。", "a walled garden（围墙内的花园）", "与open开放的在本段网络空间比喻中形成对照。"],
  ["cyberspace", "", "n.", "网络空间", "in cyberspace为地点或领域状语，指电子通信构成的虚拟活动空间。", "security in cyberspace（网络空间安全）", "与physical space实体空间对照；不是具体的一台电脑。"],
  ["neighborhood", "neighborhoods", "n.", "邻里；社区", "safe neighborhoods为安全用户群的空间比喻；原卷使用美式拼写。", "safe neighborhoods（安全的社区）", "与community相比，neighborhood更突出相邻居住或局部区域。"],
  ["bright", "brighter brightest", "adj.", "明亮的", "修饰streetlights，延续夜间社区安全的形象比喻。", "bright streetlights（明亮的路灯）", "与smart在形容人时都可涉及聪明，但bright在本句只表示亮度。"],
  ["streetlight", "streetlights", "n.", "路灯", "bright streetlights与safe neighborhoods并列，作为安全网络环境的类比特征。", "bright streetlights（明亮的路灯）", "复合名词由street与light组成；不能理解为街上的交通指令。"],
  ["establish", "established establishes establishing", "v.", "建立；确立", "to establish a sense...为目的状语，目标是营造可信感。", "establish trust（建立信任）", "与create相比，establish常强调形成较稳定的制度、关系或认知。"],
  ["sense", "senses", "n.", "感觉；意识", "a sense of a trusted community表示可信社区感，不是感官器官。", "a sense of security（安全感）", "与feeling近义；sense还可表词义、判断力或感官，按搭配选义。"],
  ["modernize", "modernized modernizes modernizing", "v.", "使现代化", "modernized为分词形容词干扰项；社区可信不等于设施现代化。", "modernize a system（使系统现代化）", "与improve改善相比，modernize特指向现代制度或技术转变。"],
  ["thrive", "thrived thrives thriving", "v.", "兴旺；蓬勃发展", "thriving作定语表示繁荣，第十三题缺少繁荣程度的论述。", "a thriving community（兴旺的社区）", "与survive生存不同，thrive表示不仅存活，而且发展良好。"],
  ["compete", "competed competes competing", "v.", "竞争", "competing作定语表示竞争中的；并不能说明可信环境。", "compete with others（与他人竞争）", "与cooperate合作不同；共同认证系统不必以竞争为核心。"],
  ["describe", "described describes describing", "v.", "描述；称为", "describe it as...为宾语加as补足说明；it指认证方案。", "describe something as safe（把某物描述为安全的）", "与call可近义，但describe as更强调描绘特征，不只是命名。"],
  ["ecosystem", "ecosystems", "n.", "生态系统；相互关联的体系", "voluntary ecosystem在此比喻用户、机构及技术设施组成的网络环境。", "a digital ecosystem（数字生态体系）", "与system相比，ecosystem更突出多主体互相依赖的关系。"],
  ["individual", "individuals", "n.", "个人", "与organizations并列为从句主语，两者均可开展线上交易。", "individuals and organizations（个人和组织）", "与organization组织相对；individual作形容词又可指个别的、个人的。"],
  ["organization", "organizations", "n.", "组织；机构", "与individuals并列，表示集体参与者；原卷用美式organization。", "online organizations（在线活动的组织）", "与company公司相比，organization还包括非营利机构等团体。"],
  ["complete", "completed completes completing", "v.", "完成", "can complete online transactions中为及物动词，transactions作宾语。", "complete a transaction（完成交易）", "与finish近义；complete强调把完整过程做完，形容词义为完整的。"],
  ["transaction", "transactions", "n.", "交易；业务往来", "online transactions是complete的宾语；末尾the transaction回指交易行为。", "online transactions（在线交易）", "与interaction互动相比，transaction更常涉及具体业务或交换。"],
  ["caution", "", "n.", "谨慎；警惕", "with caution表示小心地，第十四题上下文强调相信身份后的信心。", "with caution（谨慎地）", "与confidence信心不同，caution突出对风险有所戒备。"],
  ["delight", "", "n.", "喜悦；高兴", "with delight表示高兴地，身份可信直接支持的是放心而非情绪兴奋。", "with delight（高兴地）", "与pleasure相近；不能用喜悦直接替代因信任产生的confidence。"],
  ["patience", "", "n.", "耐心", "with patience表示耐心地；第十四题未涉及等待或容忍困难。", "with patience（耐心地）", "与tolerance容忍相关，但patience尤其指等待或反复处理时的耐性。"],
  ["run", "runs ran running", "v.", "运行；运转", "the transaction runs on the infrastructure表示交易依托基础设施运作。", "run on a platform（在平台上运行）", "与operate运行相近；run在本文不是跑步，过去式ran、分词run。"],
  ["administration", "administration's administrations", "n.", "政府当局；行政机构", "the administration's plan为所有格结构，指当前政府的政策方案。", "the administration's plan（政府的计划）", "与government相近；administration还可指管理活动，但本句指机构。"],
  ["divide", "divided divides dividing", "v.", "使产生分歧；使分裂", "has divided activists说明同一群体出现支持与忧虑两派。", "divide public opinion（使公众意见分裂）", "与unite使团结相反；不是人人都失望的disappoint。"],
  ["disappoint", "disappointed disappoints disappointing", "v.", "使失望", "第十六题干扰项；Some applaud表明不能概括为全体失望。", "disappoint supporters（让支持者失望）", "与divide区别：disappoint是负面情绪，divide是态度不一致。"],
  ["protect", "protected protects protecting", "v.", "保护", "第十六题干扰项；段落讨论方案收到的意见而非已产生的保护效果。", "protect privacy（保护隐私）", "与preserve维持相比，protect更强调免受侵害。"],
  ["unite", "united unites uniting", "v.", "使团结；使联合", "第十六题united若作谓语，意味着群体一致，反于后文Some...others...。", "unite a community（使社群团结）", "与divide使分裂相反；此处united不是国名United States的一部分。"],
  ["activist", "activists", "n.", "积极倡导者；活动人士", "privacy rights activists专指积极维护隐私权的人群，不是所有网民。", "privacy rights activists（隐私权倡导者）", "与supporter支持者相比，activist常更强调参与行动。"],
  ["applaud", "applauded applauds applauding", "v.", "赞同；称赞", "applaud the approach指对方案表示支持，不必真的用手鼓掌。", "applaud an approach（赞同一种做法）", "与approve of相近；applaud常带较明确的赞赏意味。"],
  ["other", "others", "pron. / det.", "其他的；其他人", "others独立作are concerned的主语，代指另一些隐私权倡导者；each other为相互。", "some...others...（一些人……另一些人……）", "others可独立作代词，other作限定词时后接名词；不要说others users。"],
  ["scheme", "schemes", "n.", "方案；计划", "such a scheme回指自愿身份认证安排，此处无需译成阴谋。", "an identity scheme（身份认证方案）", "与plan相近；scheme有时带负面阴谋义，但本句评价须由上下文而定。"],
  ["initiative", "initiatives", "n.（作定语）", "倡议；主动推行的行动", "附件写an initiative push，保留其原词；initiative在此限定政策推动的性质，不改成initial。", "a policy initiative（一项政策倡议）", "与initial最初的不是同一词；不能为了常见搭配擅自替换原卷文本。"],
  ["push", "pushes", "n.", "推动；推进", "an initiative push中push是可数名词，toward引政策方向。", "a push toward reform（推动改革的努力）", "与动词push推不同，本句由an限定，必须按名词解释。"],
  ["eventually", "", "adv.", "最终；到头来", "修饰would be，担心制度最终变成强制许可，不是说频繁发生。", "eventually become compulsory（最终变成强制性的）", "与frequently经常、occasionally偶尔区别在时间终点而非频率。"],
  ["incidentally", "", "adv.", "偶然地；顺便说一句", "第十七题干扰项，不能表达toward所指向的最终制度结果。", "occur incidentally（偶然发生）", "与eventually最终不同，incidentally强调附带性或偶然性。"],
  ["compulsory", "", "adj.", "强制的；必须履行的", "限定上网许可思维，与反复出现的voluntary形成政策取向对照。", "compulsory registration（强制注册）", "与mandatory相近；均不同于voluntary自愿。"],
  ["mentality", "mentalities", "n.", "心态；思维方式", "driver's license mentality指像驾车许可那样看待网络准入的制度思路。", "a licensing mentality（许可制思维）", "与mindset相近，不能只译成智力或精神疾病。"],
  ["greet", "greeted greets greeting", "v.", "对……作出反应；迎接", "be greeted with skepticism表示受到怀疑，with引回应态度，by引作出反应的人。", "be greeted with skepticism（受到质疑）", "与welcome欢迎不同，greet可搭配正面或负面回应；本义也可为打招呼。"],
  ["skepticism", "", "n.", "怀疑；质疑态度", "with skepticism为方式状语，who worry解释专家为何怀疑方案效果。", "greet a plan with skepticism（对方案持怀疑态度）", "与doubt相近；skepticism更指不轻信的审慎态度，原卷用美式拼写。"],
  ["tolerance", "", "n.", "容忍；宽容", "第十八题干扰项，不能精确概括专家对保护不足的质疑。", "tolerance of differences（对差异的容忍）", "与indifference冷漠不同：容忍不等于不关心，也不等于enthusiasm热情。"],
  ["indifference", "", "n.", "漠不关心；冷淡", "第十八题干扰项，专家明确担忧并提出主张，不能说他们不关心。", "indifference to risk（对风险漠不关心）", "与skepticism不同，怀疑者关注真实性，而冷漠者缺乏关注。"],
  ["enthusiasm", "", "n.", "热情；积极兴趣", "第十八题干扰项，与who worry说明的担忧不符。", "enthusiasm for a plan（对计划的热情）", "与confidence不同，enthusiasm强调积极情绪，confidence强调信任或把握。"],
  ["envision", "envisioned envisions envisioning", "v.", "设想；展望", "envisioned by Mr. Schmidt为过去分词定语，修饰自愿生态系统。", "envision a safer Internet（设想更安全的互联网）", "与imagine相近，envision常用于未来计划的具体构想。"],
  ["vulnerable", "", "adj.", "易受攻击的；脆弱的", "leave much of the Internet vulnerable是宾语加宾补结构，担心方案覆盖不足。", "vulnerable to attack（易受攻击的）", "与defendable可防护的方向相反；不是invisible看不见的。"],
  ["manageable", "", "adj.", "可管理的；可处理的", "第十九题干扰项；可管理是积极状态，不是专家所担忧的保护缺口。", "a manageable problem（可处理的问题）", "与vulnerable易受攻击不同；manageable关注处理难度。"],
  ["defendable", "", "adj.", "可防卫的；可辩护的", "第十九题干扰项，原卷拼写defendable予以保留。", "a defendable position（可防守或可辩护的立场）", "与vulnerable易受攻击的相反；defensible也是常见相关形容词。"],
  ["invisible", "", "adj.", "看不见的；不可见的", "第十九题干扰项，原段担心受到攻击，而非网站无法看见。", "an invisible threat（看不见的威胁）", "与vulnerable不同，一个谈可见性，一个谈易受伤害性。"],
  ["force", "forced forces forcing", "v.", "强迫；强制", "be forced to register为被动结构；这里强调全部用户都必须履行注册义务。", "force somebody to register（强制某人注册）", "与allow允许、invite邀请相反；本句不是名词力量或推动因素。"],
  ["identify", "identified identifies identifying", "v.", "表明身份；识别", "identify themselves让用户说明自己是谁；与register并列，共用to。", "identify oneself（表明自身身份）", "与authenticate核验不同：identify提出或确认是谁，authenticate核实身份可信。"],
  ["ride", "ridden rode rides riding", "v.", "骑；乘坐", "第一题ridden是过去分词干扰项；ride的过去式rode，分词ridden。", "ride a bicycle（骑自行车）", "与sweep across的席卷不同，ride需要骑乘或依附移动的语义。"],
  ["skip", "skipped skips skipping", "v.", "跳过；蹦跳", "第一题skipped为过去式或分词，双写p；不表示犯罪激增蔓延。", "skip a step（跳过一步）", "与sweep席卷不同；skip侧重略过或跳跃，不是广泛传播。"],
  ["walk", "walked walks walking", "v.", "步行；走", "第一题walked为干扰项，犯罪激增不是能够步行的主体。", "walk across a bridge（步行过桥）", "与ride骑乘相比，walk靠步行；两者均不适合本文的犯罪浪潮。"],
];

export const cloze2011Lexicon: Record<string, Entry> = Object.fromEntries(rows.map(([headword, forms, partOfSpeech, contextualMeaning, use, collocation, distinction]) => [headword, {
  partOfSpeech, contextualMeaning, use,
  specialForms: [forms ? `${headword} 的相关词形：${forms.split(" ").join(" / ")}；按词性区分时态、分词与名词复数。` : "本句使用该词的原形；派生词不作为屈折形式合并。"],
  examSynonyms: [distinction], collocations: [collocation.split("（")[0]],
}]));
export const cloze2011LemmaAliases: Record<string, string> = Object.fromEntries(rows.flatMap(([headword, forms]) => forms.split(" ").filter(Boolean).map(form => [form, headword])));
export const cloze2011FormPartOfSpeech: Record<string, string> = {
  registered: "adj.（过去分词作定语）", trusted: "adj.（过去分词作定语）", trusting: "v.-ing（现在分词）", authenticated: "v.-ed（被动分词）", issued: "v.-ed（过去分词作定语）", linked: "v.-ed（过去分词作定语）", walled: "adj.（过去分词作定语）", modernized: "adj.（过去分词作定语）", thriving: "adj.（现在分词作定语）", competing: "adj.（现在分词作定语）", others: "pron.", "nation's": "n.（所有格）", "administration's": "n.（所有格）", "driver's": "n.（所有格）", safer: "adj.（比较级）",
  concerned: "adj.（担忧的）", once: "adv.（次数）", very: "adj.（强调）", push: "n.", select: "v.", services: "n.（复数）", united: "v.-ed（unite的过去分词）",
};
export const cloze2011CollocationGlosses = Object.fromEntries(rows.map(([, , , , note, collocation]) => {
  const [label, meaning] = collocation.split("（");
  return [label.toLowerCase(), { meaning: meaning.replace(/）$/, ""), note }];
}));

cloze2011Lexicon.afford.otherMeanings = ["afford to do：有能力或经济条件做某事，常与can或cannot连用。"];
cloze2011Lexicon.very.otherMeanings = ["adv. 非常，如very safe很安全；副词义不能覆盖that very anonymity中的形容词强调义。"];
cloze2011Lexicon.license.otherMeanings = ["n. 执照；许可；v. 发给许可；本文第8句用名词，第16句用动词被动。"];
cloze2011Lexicon.sense.otherMeanings = ["词语的含义；判断力；感官。a sense of security表示安全感，不是词义或感觉器官。"];
cloze2011Lexicon.greet.otherMeanings = ["向人打招呼；迎接。be greeted with + 态度表示受到怎样的回应。"];

export const cloze2011SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2011-cloze-s1": { afford: { contextualSubstitutions: [{ label: "provide", chinese: "提供", fit: "direct", rewrittenSentence: "The Internet provides anonymity to its users, a blessing to privacy and freedom of speech.", nuance: "provide明确指提供条件；afford较正式。这里不是afford to do的负担能力义。", target: "word:provide" }] }, to: { contextualMeaning: "向；对……有利", use: "to its users引匿名性的接受者，a blessing to privacy...引受益领域，均为介词。" } },
  "2011-cloze-s2": { that: { contextualMeaning: "那种；引出定语", use: "that very anonymity中的that为指示限定词；that has swept中的that为定语从句主语，回指犯罪激增。" }, have: { partOfSpeech: "aux.", contextualMeaning: "已经（构成现在完成时）", use: "has与swept组成现在完成时，表示犯罪浪潮已席卷网络。" } },
  "2011-cloze-s3": { be: { partOfSpeech: "aux.", contextualMeaning: "被（构成被动）", use: "be preserved与前置情态词Can构成被动疑问句，privacy是保护对象。" }, that: { partOfSpeech: "relative pron.", contextualMeaning: "这个世界（关系指代）", use: "that seems...中that指world并在定语从句中作主语。" } },
  "2011-cloze-s4": { make: { contextualMeaning: "使……成为", use: "make the Web a safer place中Web为宾语，a safer place为宾补；to make后置说明proposal的目标。" }, that: { partOfSpeech: "relative pron.", contextualMeaning: "这个系统（关系指代）", use: "that would be...修饰system；that作从句主语。" } },
  "2011-cloze-s5": { to: { partOfSpeech: "prep.", contextualMeaning: "关联到", use: "linked to a specific computer中to引出凭证所绑定的电脑，不是不定式标记。" }, range: { partOfSpeech: "n.", contextualMeaning: "一系列；多种", use: "a range of online services中of引出多种在线服务；不是飞行航程。" } },
  "2011-cloze-s6": { be: { partOfSpeech: "v.（系动词）", contextualMeaning: "是", use: "The idea is to create...中is连接主语与不定式表语，不是被动助动词。" }, private: { contextualMeaning: "私营的；非政府的", use: "private修饰online identity systems，指由私营主体提供的系统，不是不可见的私人账号。" } },
  "2011-cloze-s7": { which: { partOfSpeech: "interrogative det.", contextualMeaning: "哪一个", use: "which限定system，which system to join整体为select的宾语，表达待作出的选择。" }, have: { partOfSpeech: "aux.", contextualMeaning: "已经（构成完成时）", use: "have been authenticated中have为完成时助动词，been authenticated为被动结构。" }, whose: { contextualMeaning: "这些用户的", use: "whose identities中whose为所属关系，先行词registered users，从句主语为identities。" } },
  "2011-cloze-s8": { one: { contextualMeaning: "另一种方案", use: "one代替approach，后接that限定该方案要求政府签发执照；不是指一个用户。" }, license: { partOfSpeech: "n.", contextualMeaning: "执照；许可凭证", use: "an Internet driver's license作require的宾语，issued by...后置修饰该执照。" } },
  "2011-cloze-s9": { have: { partOfSpeech: "v.", contextualMeaning: "拥有；提供", use: "companies that already have...systems中have为实义动词，systems是宾语，不是完成时助动词。" }, it: { contextualMeaning: "形式宾语（不单独翻译）", use: "make it possible中it占宾语位置，for users to log in...说明真正的可能行为。" }, that: { partOfSpeech: "relative pron.", contextualMeaning: "引出公司或系统的限定", use: "第一个that修饰companies作have的主语；第二个that修饰systems作make的主语，不能都指公司。" }, once: { contextualMeaning: "一次", use: "just once限定log in次数，single sign-on和many services构成一对多的关系。" } },
  "2011-cloze-s10": { with: { contextualMeaning: "带有", use: "with safe neighborhoods and bright streetlights引伴随特征，不是交流对象。" }, to: { partOfSpeech: "不定式标记", contextualMeaning: "为了", use: "to establish...为目的状语，说明营造安全环境要建立可信社区感。" } },
  "2011-cloze-s11": { it: { contextualMeaning: "这项认证方案", use: "described it as...中的it为实义宾语，回指方案，不是make it possible的形式宾语。" }, on: { partOfSpeech: "prep.", contextualMeaning: "依托……运行", use: "on which前置，恢复为the transaction runs on the infrastructure。" }, other: { contextualMeaning: "彼此（each other整体）", use: "the identities of each other说明交易双方相互的身份，each other是相互代词。" } },
  "2011-cloze-s12": { still: { contextualMeaning: "尽管如此；然而", use: "句首Still转折前文宣称的好处，引出隐私倡导者意见不一；不是表示仍留在原地。" }, right: { partOfSpeech: "n.（复数）", contextualMeaning: "权利", use: "privacy rights作名词定语限定activists的倡导领域，不是正确或右边。" } },
  "2011-cloze-s13": { some: { partOfSpeech: "pron.", contextualMeaning: "一些隐私权倡导者", use: "Some独立作applaud主语，承接上句activists；与others对照。" }, concern: { partOfSpeech: "adj.（concerned）", contextualMeaning: "担忧的", use: "are concerned为系表结构，说明另一些倡导者的态度，不是be concerned with的涉及。" } },
  "2011-cloze-s14": { it: { contextualMeaning: "形式主语（不单独翻译）", use: "It seems clear that...中that从句为真正主语，it不回指网络系统。" }, that: { partOfSpeech: "conj.", contextualMeaning: "引出被判断为清楚的内容", use: "that such a scheme is...为后置主语从句，that不在从句内担任主宾语。" }, what: { contextualMeaning: "最终会形成的那种思维", use: "what would...be...中what既连接toward的宾语从句，也作从句主语。" } },
  "2011-cloze-s15": { still: { contextualMeaning: "仍然", use: "would still leave说明即使采取方案，互联网大片区域易受攻击的状态仍未改变。" }, who: { contextualMeaning: "这些专家", use: "who worry...为补充专家观点的非限制性定语从句，who作worry的主语。" }, with: { contextualMeaning: "以怀疑的态度", use: "with skepticism描述greeted的回应方式；by experts才指作出回应者。" } },
  "2011-cloze-s16": { they: { contextualMeaning: "这些计算机安全专家", use: "They承接上一句experts，主张强制注册；不指上一段全部隐私权倡导者。" }, license: { partOfSpeech: "v.", contextualMeaning: "授予许可", use: "must be licensed to drive为情态被动，drivers是被许可者，to drive是获准行为。" }, that: { partOfSpeech: "conj.", contextualMeaning: "引出主张内容或方式说明", use: "argue that引宾语从句；the same way that...引方式限定，两者作用不同。" }, themselves: { contextualMeaning: "网民他们自己", use: "identify themselves中反身代词与主语all Internet users同指，表示网民表明自身身份。" } },
};
