import type { PracticeTask, GrammarConceptId, ErrorCategory } from './learning-model';
const range=(id:string,prompt:string,answer:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[],extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:'range',prompt,options:[],answer,evidence:answer,feedback,conceptId,errorType,hintWords,...extra});
const choice=(id:string,prompt:string,options:string[],answer:number,evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[],extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:'choice',prompt,options,answer:options[answer],evidence,feedback,conceptId,errorType,hintWords,...extra});
const link=(id:string,prompt:string,pairs:Array<[string,string]>,evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[],extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:'link',prompt,options:[...new Set(pairs.map(p=>p[1]))],links:pairs.map(([source,target])=>({source,target})),answer:JSON.stringify(pairs.map(p=>p[1])),evidence,feedback,conceptId,errorType,hintWords,...extra});
const order=(id:string,prompt:string,answer:string[],distractors:string[],evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,hintWords:string[],extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:'order',prompt,options:[...answer,...distractors],answer:JSON.stringify(answer),evidence,feedback,conceptId,errorType,hintWords,...extra});
export const passage2011P3Practice:Record<string,PracticeTask[]>={
'2011-p3-s1':[
 range('shared-participle-subject','划出with结构中三个并列分词共同的逻辑主语。','soldiers','with后的soldiers共同执行returning、going、lining；这些分词不是We的三个主句谓语。','nonfinite-subject','subject',['with','soldiers','returning','going','lining']),
 range('decades-modifier','划出紧贴decades、限定时代的完整后置分词短语。','immediately following World War II','following修饰decades，immediately说明紧接二战；returning等在后面的with背景中，层级不同。','nonfinite-participle','attachment',['following','immediately'])],
'2011-p3-s2':[
 range('belief-content','划出解释belief内容的完整从句。','that less could truly be more','that后有less主语、could be谓语、more表语；that不在从句内代替任何名词。','complement-content','clause-boundary',['that','belief','less could truly be more']),
 link('two-it-functions','两个it各起什么作用？',[['when it came to their houses','话题习语里的形式代词'],['it was a time','回指战后时期']],'when it came to their houses, it was a time','前者整体译为说到住宅；后者说明那个时代的住宅观念。不同位置不能只按同一代词机械回指。','reference-pronoun','reference',['it','when','when it came to their houses'],{mapRevealsAnswer:true})],
'2011-p3-s3':[
 link('make-object-complement','把主语、对象与结果状态配对。',[['that restraint','made的主语'],['small, efficient housing','made的宾语'],['positively stylish','说明housing结果状态的宾补']],'that restraint, in combination with the postwar confidence in the future, made small, efficient housing positively stylish','in combination with把confidence作为共同因素；housing是被影响的对象，stylish不是made的方式副词。','object-complement','predicate',['made','housing','stylish','made small, efficient housing positively stylish'],{leaksToTaskIds:['mindset-versus-feature']}),
 choice('mindset-versus-feature','哪些是塑造住宅风格的两种心理，哪些是住宅特点？',['节制与信心是心理；小巧高效是特点','繁荣与增长是心理；节制是建筑面积','忠诚与自豪是心理；信心是材料'],0,'that restraint, in combination with the postwar confidence in the future','restraint承接战前节俭，confidence指战后对未来的信心。题目问心态，不能直接用efficient housing的建筑特征代替。','paragraph-role','option-logic',['restraint','confidence'],{mapRevealsAnswer:true})],
'2011-p3-s4':[choice('limited-economic-cause','only a stimulus限制了什么？',['经济条件只是推动因素之一，后文还给理念影响','经济条件是唯一原因','经济条件完全没有影响'],0,'Economic condition was only a stimulus','保留stimulus确有推动作用，同时only阻止把经济因素当作全部解释。','negation-contrast','passage-logic',['only','stimulus'],{mapRevealsAnswer:true})],
'2011-p3-s5':[
 range('who-boundary','划出完整who从句，保留比较插入语和两个动作。','who like other people associated with the Bauhaus, a school of design, emigrated to the United States before World War II and took up posts at American architecture schools','who是emigrated与took up的共同主语；like短语及Bauhaus同位语都在从句内部，不能在设计学校处提前截断。','clause-relative','clause-boundary',['who','emigrated','took']),
 link('person-school-and-time','把名称与时间接回实际说明对象。',[['a school of design','同位解释the Bauhaus'],['before World War II','限定emigrated的时间'],['the architect Ludwig Mies van der Rohe','同位解释a German']],'a German, the architect Ludwig Mies van der Rohe, who like other people associated with the Bauhaus, a school of design, emigrated to the United States before World War II','原句说推广格言、战前移民和任职；没有创立包豪斯，也没有二战改变理念的命题。','apposition','attachment',['German','Bauhaus','before','associated with the Bauhaus'],{mapRevealsAnswer:true})],
'2011-p3-s6':[link('influence-comparison','把共同作用与最高程度分别译准。',[['These designers came to exert enormous influence','这些设计师后来产生巨大影响'],['none more so than Mies','其中没有谁比密斯影响更大']],'These designers came to exert enormous influence on the course of American architecture, but none more so than Mies','came to do表示发展成某结果；none加比较级突出密斯，不是否认所有人有影响。','comparison-scope','option-logic',['came','none','more','none more so than Mies'],{mapRevealsAnswer:true})],
'2011-p3-s7':[
 link('two-comparison-dimensions','less、more和a lot分别对应什么？',[['less decoration','较少的装饰数量'],['more impact','更强的审美效果'],['a lot','大量装饰这一比较对象']],'less decoration, properly organized, has more impact than a lot','装饰数量少和效果强属于不同维度；properly organized补足安排得当的条件，不是完全无装饰。','comparison-scope','attachment',['less','more','lot','more impact than a lot'],{mapRevealsAnswer:true}),
 choice('organized-receiver','properly organized的逻辑受事是谁？',['less decoration','Mies本人','more impact这个效果'],0,'less decoration, properly organized','过去分词说明装饰经过恰当安排；它不是新的有限谓语，不能并列到means。','nonfinite-subject','attachment',['organized','properly','properly organized'])],
'2011-p3-s8':[order('remove-voice-insertion','排出保留否定的主干，把观点来源留在词块池。',['Elegance','did not derive','from abundance'],['he believed'],'Elegance, he believed, did not derive from abundance','he believed标明观点来自密斯；Elegance才是主句主语，did not否定堆砌作为优雅来源。','finite-predicate','predicate',['believed','did','derive','derive from abundance'])],
'2011-p3-s9':[
 link('two-that-roles','两个that在各自从句内分别作什么？',[['that we take for granted today','take的宾语，指材料'],['that in the 1940s symbolized the future','symbolized的主语，指材料']],'that we take for granted today but that in the 1940s symbolized the future','两个从句同修饰materials，但第一个已有we作主语，第二个that自己充当主语。','clause-relative','subject',['that','we','symbolized','take for granted']),
 choice('materials-time','today与in the 1940s怎样对照？',['如今寻常，当年象征未来','当年已普遍流行，如今无人使用','两个时间都证明材料环保'],0,'we take for granted today but that in the 1940s symbolized the future','时间改变了同一批材料的新颖程度；末段说当时流行的另一个对象是抽象艺术。','time-reference','tense',['today','1940s','future'],{mapRevealsAnswer:true})],
'2011-p3-s10':[
 range('fact-content','划出说明fact的完整内容从句。','that the spaces he designed were small and efficient, rather than big and often empty','that引事实内容；内嵌he designed修饰spaces。外层masked的宾语是整个the fact及其内容。','complement-content','clause-boundary',['that','fact'],{leaksToTaskIds:['nested-actors']}),
 link('nested-actors','给嵌套结构匹配主语及结果。',[['he designed','he是设计者，省略宾语指spaces'],['the spaces ... were','spaces作系动词were的主语'],['small and efficient','肯定的真实空间特点'],['big and often empty','被rather than排除的描述']],'the spaces he designed were small and efficient, rather than big and often empty','设计者的定语从句嵌在内容从句主语中；两组形容词共同参与比较，不能把he当were主语。','clause-relative','attachment',['he','spaces','were','rather than big and often empty'])],
'2011-p3-s11':[
 link('same-kind-size','把数字与比较对象分别对应。',[['two-bedroom units','两间卧室的一套公寓'],['under 1,000 square feet','每套总面积不足一千平方英尺'],['those in their older neighbors','附近老楼中的公寓']],'were smaller – two-bedroom units under 1,000 square feet – than those in their older neighbors','smaller比较公寓与公寓；neighbors借指楼房，those替代apartments。面积上限不能换成卧室大小或整栋楼面积。','comparison-scope','reference',['smaller','under','those','two-bedroom units under 1,000 square feet','than those in their older neighbors'],{mapRevealsAnswer:true}),
 range('tower-relative','划出限定towers的定语从句。',"Mies built on Chicago's Lake Shore Drive",'关系词that/which省略，作built宾语并指towers；Mies是从句主语，主句真正主语仍是apartments。','clause-relative','clause-boundary',['Mies','built'])],
'2011-p3-s12':[
 link('because-of-three-items','把三项原因与后置形容词接回正确层级。',[['their airy glass walls','because of第一原因项'],['the views they afforded','because of第二原因项'],["the elegance of the buildings' details and proportions",'because of第三原因项'],['so popular at the time','修饰abstract art']],'because of their airy glass walls, the views they afforded and the elegance of the buildings\' details and proportions, the architectural equivalent of the abstract art so popular at the time','because of接三组名词；末尾popular限定art，不是材料。views内部省略关系词，they指公寓。','modifier-prepositional','attachment',['because','views','popular','the views they afforded']),
 choice('art-equivalent','architectural equivalent允许怎样概括？',['公寓的建筑形式具有与抽象艺术相应的特点','公寓本身是同一幅抽象画','所有当时材料都已普遍流行'],0,'the architectural equivalent of the abstract art','equivalent表示不同艺术领域中的对应表现，支持具有一些共同形式特点；没有把建筑与画作说成同一个实体。','lexical-context','option-logic',['equivalent','abstract','the architectural equivalent of the abstract art'],{mapRevealsAnswer:true})],
'2011-p3-s13':[choice('partial-negation','not entirely foreign准确保留哪项？',['既有外来影响，也有美国本土来源','完全没有外来影响','完全来自外国而无本土作用'],0,'not entirely foreign','否定entirely的完全程度，承认前述欧洲影响，接着补充赖特和案例住宅。','negation-contrast','passage-logic',['not','entirely','not entirely foreign'],{mapRevealsAnswer:true})],
'2011-p3-s14':[
 link('wright-timeline','把动作、指代和面积精度配对。',[['started building','1930年代的新变化'],['he had designed','赖特更早在1890年代及20世纪初的设计'],['ones','houses的替代'],['usually around 1,200 square feet','典型近似面积，非每套精确值']],'usually around 1,200 square feet – than the spreading two-story ones he had designed in the 1890s and the early 20th century','过去完成时相对started更早；主角是Wright。两个时期的住宅同类比较，usually和around都限制精确程度。','time-reference','reference',['had','he','ones','around','1930s'],{mapRevealsAnswer:true})],
'2011-p3-s15':[
 link('commission-roles','from、by和between各标记什么？',[['from talented modern architects','提供设计的受托方'],['by California Arts & Architecture magazine','发出委托的杂志'],['between 1945 and 1962','委托发生的时期']],'commissioned from talented modern architects by California Arts & Architecture magazine between 1945 and 1962','commissioned分词修饰住宅；were才是主句有限谓语。杂志委托建筑师，不可倒置。','nonfinite-participle','attachment',['commissioned','from','by','commissioned from talented modern architects']),
 choice('another-local-example','yet another承接哪一个作用？',['赖特之后的另一项美国本土影响','重新介绍密斯移居欧洲','否定所有本土设计师作用'],0,'yet another homegrown influence','第六段先给赖特例子，第七段案例住宅继续补充本土源流；yet在这里加强another，不是然而。','paragraph-role','passage-logic',['yet','another','homegrown','yet another homegrown influence'],{mapRevealsAnswer:true})],
'2011-p3-s16':[link('aesthetic-sources','三项原文能支持到哪一步？',[['the landscape','考虑周围自然景观'],['new materials','采用新材料，未断言环保'],['forthright detailing','明快处理细部，非牺牲细节']],'the landscape, new materials and forthright detailing','三项都在from后说明美感来源；保持每个词给出的属性，不补新材料必然环保的前提。','lexical-context','option-logic',['landscape','new','detailing','forthright detailing'],{mapRevealsAnswer:true})],
'2011-p3-s17':[
 link('prediction-belief-levels','区分两个主分句和插入对照。',[['may have mispredicted','对过去技术预测可能失准的判断'],['few ... helicopters','直升机未在家庭普及'],['most ... clothes dryers','多数家庭最终拥有干衣机'],['his belief ... was widely shared','总体自给自足理念广受认同']],'may have mispredicted just how the mechanical revolution would impact everyday life','主句but把技术细节与总体理念分开；few与most限定不同设备，不能合为全部机械设备普及。','negation-contrast','passage-logic',['may','few','most','but','may have mispredicted','was widely shared'],{mapRevealsAnswer:true}),
 range('belief-after-dashes','划出第二主分句belief的完整内容从句。','that self-sufficiency was both desirable and inevitable','that引内容补足，不作主宾；两个形容词并列表语，一个评价可取，一个判断必然趋势。','complement-content','clause-boundary',['that','self-sufficiency','both desirable and inevitable'],{leaksToTaskIds:['prediction-belief-levels']})],
};
// 人工核对反馈中透露的内容，仅登记方向明确的关联。
const feedbackEdges:Array<[number,string,string,string]>=[
 [3,'make-object-complement','2011-p3-map','mindset-and-style'],
 [3,'mindset-versus-feature','2011-p3-map','mindset-and-style'],
 [4,'limited-economic-cause','2011-p3-map','paragraph-route'],
 [5,'who-boundary','2011-p3-s5','person-school-and-time'],
 [7,'two-comparison-dimensions','2011-p3-s7','organized-receiver'],
 [7,'two-comparison-dimensions','2011-p3-map','less-with-conditions'],
 [7,'organized-receiver','2011-p3-map','less-with-conditions'],
 [13,'partial-negation','2011-p3-s15','another-local-example'],
 [13,'partial-negation','2011-p3-map','paragraph-route'],
 [15,'another-local-example','2011-p3-s13','partial-negation'],
 [15,'another-local-example','2011-p3-map','paragraph-route'],
 [16,'aesthetic-sources','2011-p3-map','less-with-conditions'],
];
for(const[n,id,sentenceId,taskId]of feedbackEdges){const task=passage2011P3Practice[`2011-p3-s${n}`].find(t=>t.id===id)!;task.leaksToTasks=[...(task.leaksToTasks??[]),{sentenceId,taskId}];}
