import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";
const rows: LexiconRow[] = [
  ["turn", "turned turns turning", "v.", "转交；移交（turn over）", "第8题turned over为移交物品或权责，不等于普通分发。", "turn over something to someone（把某物移交给某人）", "turn into为变成；turn over在此是移交，不能只用变成义。"],
  ["over", "", "adv. / particle", "交出；转交（turn over的一部分）", "第8题turned over与to组成移交给某人的结构。", "turn something over（交出某物）", "此处不是空间上方，也不是超过数量。"],
  ["bring", "brought brings bringing", "v.", "带来；此处bring back为带回", "第8题brought back强调返回，原文无物品带回何处的语境。", "bring back supplies（把物资带回来）", "hand out强调分发，bring back强调返回。"],
  ["pass", "passed passes passing", "v.", "传递；此处pass down为传承", "第8题passed down指代代相传，不等于军需分配。", "pass down a tradition（传承传统）", "pass by为经过，pass down为传下来，不能不看副词。"],
  ["means", "", "n.", "方式；手段", "by this means为通过这种方式，单复数同形，非mean的三单。", "by this means（通过这种方式）", "meaning在第7题为mean的分词；means在第20题则是独立名词。"],
  ["resemble", "resembled resembles resembling", "v.", "与……相似", "可改写paralleled对报道与漫画相似性的判断，直接接比较对象。", "resemble another work（与另一作品相似）", "resemble强调相似，不直接表达对应发展；后面不加to。"],
  ["appoint", "appointed appoints appointing", "v.", "任命；指定", "第13题干扰项，记者采访士兵，不是为他们任职。", "appoint someone to a post（任命某人担任职务）", "interview采访不等于appoint任命。"],
  ["point", "points", "n.", "时刻；阶段", "at that point表示那时，本文两次相关来源均非指出的动词。", "at that point（在那个时刻）", "point还可指观点、要点、分数；point out为指出。"],
  ["symbol", "symbols", "n.", "象征；标志", "the symbol of说明玩具形象所代表的军事冒险主义。", "a symbol of peace（和平的象征）", "sign可指一般迹象，symbol通常具有约定的代表意义。"],
  ["cold", "colder coldest", "adj.", "寒冷的；冰冷的", "修饰foxholes，描绘士兵住宿环境。", "a cold night（寒冷的夜晚）", "cool通常是凉爽，cold温度更低；也可比喻冷漠。"],
  ["someone", "", "pron.", "某个人；有人", "not someone well paid指并非报酬优厚的人。", "someone well paid（报酬优厚的人）", "someone不指定身份；anyone常用于不限定某人的场合。"],
  ["well", "better", "adv.", "好地；充分地", "well paid表示报酬优厚；best trained/equipped为训练装备最好的。", "well paid（报酬优厚的）", "此处well不是井或推测副词，best为修饰分词的最高级。"],
  ["pay", "paid pays paying", "v.", "支付；付给报酬", "well paid中paid为被动分词，修饰someone。", "pay a soldier（付给士兵报酬）", "pay attention是注意，此处无attention，取薪酬义。"],
  ["train", "trained trains training", "v.", "训练", "best trained为过去分词短语，修饰敌军。", "train troops（训练军队）", "teach侧重传授知识，train侧重练习技能或军事能力。"],
  ["equip", "equipped equips equipping", "v.", "装备；配备", "best equipped表示装备最精良的，修饰enemies。", "equip troops with weapons（给部队配备武器）", "equip以p结尾，过去式和-ing双写p；equipment是不可数派生名词。"],
  ["soldier", "soldiers", "n.", "士兵；军人", "贯穿普通军人的身份、苦难和贡献。", "an American soldier（一名美国士兵）", "troops常集体指军队，soldier指个体成员。"],
  ["president", "presidents", "n.", "总统", "与副总统、国务卿并列，指国家领导职位。", "a president of the United States（一位美国总统）", "president也可指公司总裁或大学校长，此处国家语境不能用校长义。"],
  ["fight", "fought fights fighting", "v.", "作战；与……战斗", "fighting后直接接交战对象，补充军旅生涯内容。", "fight enemy troops（与敌军作战）", "fight against也表对抗，但此处及物结构无需补介词。"],
  ["write", "wrote written writes writing", "v.", "写作；报道", "writing about以现在分词解释记者关注的题材。", "write about soldiers（写士兵的故事）", "writing在本句为动词分词，不是写作题型的名词。"],
  ["town", "towns", "n.", "城镇", "what towns作为被动从句主语，询问哪些城镇被攻占。", "capture a town（攻占城镇）", "city通常规模更大，town为城镇。"],
  ["star", "stars", "n.", "星（报纸名的一部分）", "Stars and Stripes整体为《星条旗报》。", "Stars and Stripes（星条旗报）", "star还可指明星，此处报刊名称不能取明星义。"],
  ["coffee", "", "n.", "咖啡", "作为战地生活中可共享的日常物品列举。", "share coffee（分享咖啡）", "coffee常为不可数，a coffee可口语指一杯。"],
  ["perform", "performed performs performing", "v.", "履行；表演", "第1题干扰项，需要任务宾语才能表达执行，不代替serve in服役。", "perform a task（执行任务）", "serve in the army指服兵役，perform不与in a war直接构成此义。"],
  ["actual", "", "adj.", "实际的；真实的", "第2题比较普通人与英雄，不是在区分真实与虚构。", "actual events（真实事件）", "actual对比想象或预期，common对比特殊杰出。"],
  ["special", "", "adj.", "特殊的；特别的", "第2题与下文ordinary身份对立，不能据英雄结果倒推特殊出身。", "a special role（特殊角色）", "specific表示具体特定，special表示非普通。"],
  ["ease", "eased eases easing", "v.", "减轻；缓解", "第3题若填eased变成减轻重担，不合士兵承受艰苦的列举。", "ease a burden（减轻负担）", "bear承担与ease减轻不是同义替换。"],
  ["commodity", "commodities", "n.", "商品", "第4题强调可买卖属性，不如necessities突出生活必需。", "basic commodities（基本商品）", "necessity可不是商品，commodity可不是必需品。"],
  ["nor", "", "conj.", "也不；亦非", "第5题会继续否认身份，不能肯定an average guy。", "neither rich nor famous（既不富有也不出名）", "but转向肯定另一情况，nor仍延续否定。"],
  ["mean", "means meant meaning", "v.", "意为；意思是", "第7题meaning为分词候选，解释名称意义，不是名词意义。", "an abbreviation meaning something（意为某内容的缩写）", "此语法可成立；试题参考解析选象征代表义symbolizing。"],
  ["claim", "claimed claims claiming", "v.", "声称；宣称", "第7题干扰项，缩写本身不发表立场性断言。", "claim a victory（宣称获胜）", "state为陈述，claim常表示尚需核实的说法。"],
  ["push", "pushed pushes pushing", "v.", "推；推动", "第9题中pushed it把it当被推的对象，不能表达本人跻身上层。", "push an object（推某物）", "make it是成功的习语，不按普通推移结构理解。"],
  ["get", "got gotten gets getting", "v.", "获得；到达", "第9题get to the top没有it；原题保留it需用make it。", "get to the top（到达顶端）", "get over才是克服，不能将介词搭配义无条件套在get上。"],
  ["manage", "managed manages managing", "v.", "设法做到；管理", "manage to do需要to后接动词，不接the top名词结构。", "manage to finish（设法完成）", "make it to a place表示到达，manage to do表示办成动作。"],
  ["neither", "", "det. / pron. / adv.", "两者都不；也不", "第10题无两者对照，不能代替从未的never。", "neither of them（他们两个都不）", "never否定时间经历，neither否定两个对象。"],
  ["disturb", "disturbed disturbs disturbing", "v.", "打扰；使不安", "第11题disturbed为受干扰或心神不宁的，不是成就卓越。", "disturb someone's sleep（打扰某人睡眠）", "distinguished形容杰出，与disturbed词形相近但词义不同。"],
  ["dispute", "disputed disputes disputing", "v.", "争议；质疑", "第11题disputed为有争议的，文中未质疑军旅经历。", "dispute a claim（质疑一种主张）", "distinguish为区分，dispute为争论，不能凭外形混同。"],
  ["employ", "employed employs employing", "v.", "雇用；使用", "第13题记者采访士兵，不是雇用其服役。", "employ workers（雇用工人）", "interview也可指招聘面试，但此处记者语境是采访。"],
  ["question", "questioned questions questioning", "v.", "询问；审问；质疑", "第13题为动词干扰项，不是名词问题。", "question a witness（询问证人）", "interview在记者背景中特指采访，question更宽泛也可含质疑。"],
  ["neglect", "neglected neglects neglecting", "v.", "忽视；疏于照料", "第17题不能和作者反复刻画战争苦难的内容衔接。", "neglect one's duty（玩忽职守）", "emphasize是强调，neglect是未给予应有关注。"],
  ["avoid", "avoided avoids avoiding", "v.", "避免；回避", "第17题与主动呈现尘土和疲惫相反。", "avoid doing something（避免做某事）", "avoid后接名词或doing，不接to do。"],
  ["stage", "stages", "n.", "阶段", "第18题文明阶段不能由咖啡烟草住所列举出来。", "a stage of development（发展阶段）", "fragment是片段，不必代表先后相继的发展阶段。"],
  ["advance", "advances advanced advancing", "n.", "进步；发展", "第18题为复数名词候选，日常资源不是文明进步的证据。", "advances in science（科学进步）", "advance还可作推进的动词，此选项位于the后作名词。"],
  ["contrary", "", "adj. / n.", "相反的；相反情况", "on the contrary表示恰恰相反，不能充当时间状语。", "on the contrary（恰恰相反）", "by contrast可对比不同对象，on the contrary常纠正前述命题。"],
  ["g.i.", "", "abbreviation", "美国兵；原为Government Issue的缩写", "正文依次讨论其军需缩写、普通军人和玩具形象，按句区分。", "G.I. Joe（美国大兵乔）", "G.I.是缩写整体，不拆成两个字母词条。"],
  ["joe", "", "proper n.", "乔；文中普通美国兵的名字", "G.I. Joe是人物与玩具形象；本段用Joe表现平民意味。", "G.I. Joe（美国大兵乔）", "专名不逐字译为普通名词，也不是所有美国人的真实姓名。"],
  ["mindless", "", "adj.", "无头脑的；缺乏思考的", "修饰war toy，表达公众对战争玩具的负面印象。", "a mindless war toy（无脑战争玩具）", "thoughtless偏欠考虑；mindless还可指机械而无需思考的活动。"],
  ["toy", "toys", "n.", "玩具", "war toy为战争题材玩具，与原先的普通军人形象形成对照。", "a war toy（战争玩具）", "model可指模型，toy强调供玩耍的物件。"],
  ["adventurism", "", "n.", "冒险主义", "military adventurism是带批评色彩的军事冒险行径。", "military adventurism（军事冒险主义）", "adventure冒险经历可中性或褒义；adventurism指冒险政策倾向。"],
  ["military", "", "adj.", "军事的；军用的", "修饰adventurism或abbreviation；第14题不等于human。", "a military abbreviation（军用缩略语）", "martial也与战争有关；military通常涉及军队及其活动。"],
  ["serve", "served serves serving", "v.", "服役", "serve in World War II指在第二次世界大战中服兵役。", "serve in the army（在军队服役）", "perform强调执行任务，serve in强调服役所属或背景。"],
  ["liberate", "liberated liberates liberating", "v.", "解放", "主句视角包括被军人解放的人民；后文被动式用于城镇。", "liberate a town（解放一座城镇）", "release偏释放被关押者；liberate强调摆脱压迫或控制。"],
  ["common", "", "adj.", "普通的；常见的", "common man强调平民身份，common name强调名字常见。", "the common man（普通人）", "normal是正常而非异常，common是普通或普遍。"],
  ["hero", "heroes", "n.", "英雄", "grown into hero表示成长为英雄，保留原卷单数无冠词写法。", "a war hero（战争英雄）", "hero可指作品男主人公，本文重在英雄事迹。"],
  ["grow", "grew grown grows growing", "v.", "成长；变成", "grown into是完成变化后的分词定语，不表示主动种植。", "grow into a hero（成长为英雄）", "become泛指变成；grow into强调逐渐发展。"],
  ["farm", "farms", "n. used attributively", "农场；农家的", "farm kid中名词作定语，说明孩子的生活背景。", "a farm kid（农家孩子）", "farmer是农民本人，不把派生词并入farm计数。"],
  ["kid", "kids", "n.", "孩子；年轻人", "poor farm kid指贫苦农家子弟，口语色彩贴近普通人。", "a poor kid（贫苦的孩子）", "child较中性正式；kid更口语，也可作动词开玩笑。"],
  ["tear", "tore torn tears tearing", "v.", "强行扯离；撕开", "torn away from home是被迫离家，过去分词作定语。", "tear somebody away from home（强使某人离家）", "leave为离开，不一定含被迫和痛苦意味。"],
  ["guy", "guys", "n.", "家伙；普通人", "文中亲切通俗地称平凡的男性军人。", "an average guy（一个普通人）", "man更中性，guy较口语；不自动含贬义。"],
  ["bear", "bore borne bears bearing", "v.", "承受；承担", "bore all the burdens以过去式叙述士兵承担苦难。", "bear a burden（承担重担）", "carry常指搬运，bear还可指忍受压力或责任。"],
  ["burden", "burdens", "n.", "重担；负担", "of battle限定负担来源于作战生活。", "the burdens of battle（战争的重担）", "responsibility偏责任，burden强调沉重难以承受。"],
  ["battle", "battles", "n.", "战斗；战争", "burdens of battle指作战带来的重担。", "a fierce battle（激烈的战斗）", "war是较大规模战争，battle常指其中一次交战。"],
  ["sleep", "slept sleeps sleeping", "v. / n.", "睡觉；睡眠", "slept为过去式；末段sleep是共享的基本生活条件。", "sleep in a foxhole（睡在散兵坑里）", "rest是休息，不一定进入睡眠。"],
  ["foxhole", "foxholes", "n.", "散兵坑", "战地临时掩体，in cold foxholes说明睡眠处境艰苦。", "a cold foxhole（冰冷的散兵坑）", "按军事义理解，不能机械译成狐狸洞。"],
  ["necessity", "necessities", "n.", "必需品；必要条件", "复数necessities由food and shelter具体说明。", "the necessities of life（生活必需品）", "commodity为商品，necessity强调不可缺少，不取交易角度。"],
  ["shelter", "shelters sheltered sheltering", "n.", "栖身之所；遮蔽处", "与食物、睡眠并列，指维持日常生活的住所或掩蔽条件。", "food and shelter（食物与栖身之所）", "house是一类具体住房；shelter范围更广，未必为房屋。"],
  ["stick", "stuck sticks sticking", "v.", "坚持；撑住", "stick it out为习语，坚持到困难结束，stuck是过去式。", "stick it out（坚持到底）", "persist继续努力；stick it out突出忍受困难不退缩。"],
  ["drive", "drove driven drives driving", "v.", "驱赶；击退", "drove back与敌方统治搭配，表示迫使其退却。", "drive back the enemy（击退敌人）", "drive有驾驶、驱动义，本句不是开车返回。"],
  ["nazi", "nazis", "adj. / n.", "纳粹的；纳粹分子", "Nazi修饰reign，指纳粹的残暴统治。", "the Nazi reign（纳粹统治）", "专指纳粹，不等于所有德国人。"],
  ["reign", "reigns reigned reigning", "n.", "统治；统治时期", "reign of murder用murder说明统治的残暴特征。", "a reign of terror（恐怖统治）", "rein为缰绳、控制；rain为雨，三者不同。"],
  ["murder", "murders murdered murdering", "n.", "谋杀；杀戮", "of murder限定纳粹统治的暴行特征。", "commit murder（犯谋杀罪）", "kill泛指致死，murder强调故意且非法杀人。"],
  ["volunteer", "volunteers volunteered volunteering", "n. used attributively", "志愿者；志愿入伍的", "volunteer soldier与普通人被迫离家作战相对照。", "a volunteer soldier（志愿兵）", "voluntary形容自愿；volunteer可作名词或动词。"],
  ["average", "averages averaged averaging", "adj.", "普通的；一般的", "average guy说平凡身份，而不是数学平均数。", "an average person（普通人）", "ordinary也表示普通；average还可指平均水平。"],
  ["fierce", "fiercer fiercest", "adj.", "凶猛的；猛烈的", "fiercest与其他最高级一起限定enemies。", "fierce enemies（凶猛的敌人）", "brutal更强调残忍，fierce强调猛烈强悍。"],
  ["brutal", "", "adj.", "残暴的；残忍的", "most brutal说明敌人残暴程度的最高级。", "brutal enemies（残暴的敌人）", "cruel强调造成痛苦，brutal另带野蛮凶暴意味。"],
  ["enemy", "enemies", "n.", "敌人；敌军", "最高级定语及seen in centuries共同修饰敌军。", "face an enemy（面对敌人）", "opponent可以只是比赛对手，enemy表示敌对关系。"],
  ["abbreviation", "abbreviations", "n.", "缩略语", "G.I.为Government Issue的缩写标记。", "a military abbreviation（军用缩略语）", "acronym常指可按单词读的首字母缩略词，abbreviation范围更广。"],
  ["symbolize", "symbolizing symbolizes symbolized", "v.", "代表；象征", "分词修饰abbreviation，指G.I.代表Government Issue。", "symbolize an idea（象征一种观念）", "mean偏词语表示的意义，symbolize偏符号的代表关系；并非所有语境都互斥。"],
  ["issue", "issues issued issuing", "n.", "配发；发给的物品", "Government Issue整体说明政府配发军需品。", "Government Issue（政府配发）", "issue还可指问题、议题或报刊一期，不把本句译成政府问题。"],
  ["article", "articles", "n.", "物品；用品", "all of the articles handed out指发给士兵的军需物品。", "articles handed out to soldiers（发给士兵的物品）", "article也指文章或冠词；这两义均不合军需配发背景。"],
  ["hand", "handed hands handing", "v.", "递交；分发", "handed out为被动分词定语，整体表示配发。", "hand out supplies（分发用品）", "hand down指传承，hand out指分发给多人。"],
  ["top", "tops", "n.", "社会顶层；最高地位", "make it to the top为取得成功、跻身上层。", "make it to the top（跻身上层）", "peak可指山峰或顶点；此处top是社会地位的比喻。"],
  ["blow", "", "proper n.", "布洛（Joe Blow中的姓氏）", "本句为普通人称呼的组成部分，不表示风吹。", "Joe Blow（泛称普通人）", "同形动词blow吹、刮风是其他语境。"],
  ["palooka", "", "proper n.", "帕卢卡（姓名）", "Joe Palooka为文中列举的平民化人物称呼。", "Joe Palooka（乔·帕卢卡）", "此处按专名处理，不推断真实人物履历。"],
  ["magrac", "", "proper n.", "马格拉克（原卷姓名拼写）", "保留用户原卷Magrac，不静默改成其他版本拼写。", "Joe Magrac（乔·马格拉克）", "专名拼写按原卷，不套用其他同名人物资料。"],
  ["class", "classes", "n.", "阶级；阶层", "working class指劳动者阶层，与社会顶层对照。", "working class（工人阶级）", "class可指班级、类别；本句不是课堂。"],
  ["vice-president", "vice-presidents", "n.", "副总统", "与president、secretary of state并列列举高层职位。", "a vice-president（副总统）", "vice-表示副职，不表示恶习的名词vice。"],
  ["secretary", "secretaries", "n.", "部长；大臣（此处国务卿）", "secretary of state是美国国务卿的职务名称。", "secretary of state（国务卿）", "secretary常见秘书义，具体职位需整体理解。"],
  ["distinguished", "", "adj.", "卓越的；杰出的", "修饰career，评价军旅经历。此处作为形容词独立处理。", "a distinguished career（卓越的生涯）", "distinguish动词为辨认、区别；distinguished在此非主动辨别。"],
  ["career", "careers", "n.", "生涯；军旅经历", "fighting补充该生涯从事的活动。", "a military career（军旅生涯）", "job是一份具体工作，career通常涵盖较长经历。"],
  ["german", "germans", "adj.", "德国的", "与Japanese、Korean一起修饰troops。", "German troops（德国军队）", "German也可作德国人或德语，本文为形容词。"],
  ["japanese", "", "adj.", "日本的", "形容词修饰troops，不表示日语课程。", "Japanese troops（日本军队）", "Japanese作名词还可指日本人或日语，语境决定词性。"],
  ["korean", "koreans", "adj.", "朝鲜的；韩国的（本文战争指称依原文）", "Korean troops出现在战争经历列举，不能自行添加未给出的具体部队。", "Korean troops（朝鲜军队）", "以历史语境理解，不将一般族属形容词扩大为今日政治判断。"],
  ["troop", "troops", "n.", "部队；军队", "复数troops表示参战军队。", "enemy troops（敌军）", "soldier指单个士兵，troops常集体指军队。"],
  ["character", "characters", "n.", "角色；人物形象", "He appears as a character表示电影中的人物。", "a film character（电影角色）", "personality偏个性；character还可指性格、文字字符。"],
  ["collection", "collections", "n.", "集合；综合体", "a collection of American personalities指角色汇集多种性格。", "a collection of personalities（多种个性的集合）", "community是共同生活的群体，collection只强调聚合。"],
  ["personality", "personalities", "n.", "个性；性格", "American personalities说明角色承载的多种美国人性格特点。", "different personalities（不同的性格）", "person指人本身，personality指个性，也可指知名人物。"],
  ["movie", "movies", "n.", "电影", "1945限定影片年代，后接电影标题。", "a war movie（战争电影）", "film也指电影，movie更常见于美式口语。"],
  ["correspondent", "correspondents", "n.", "记者；通讯员", "war correspondent为战地记者，解释Pyle采访军人的身份。", "a war correspondent（战地记者）", "reporter泛指记者，correspondent常驻特定地区或领域。"],
  ["ernie", "", "proper n.", "厄尼（人名）", "Ernie Pyle为记者的姓名，Ernie是名。", "Ernie Pyle（厄尼·派尔）", "姓名不按其他常见词义拆解。"],
  ["pyle", "", "proper n.", "派尔（记者姓氏）", "本篇记者，His reports中的His回指他。", "Ernie Pyle（厄尼·派尔）", "Pyle与pile一堆拼写相似，不能混为一词。"],
  ["interview", "interviewed interviews interviewing", "v.", "采访", "Pyle interviewed为省略宾语关系词的从句，修饰soldiers。", "interview soldiers（采访士兵）", "question指询问或盘问，interview在记者语境指正式采访。"],
  ["portray", "portrayed portrays portraying", "v.", "扮演；描绘", "portrayed themselves说明士兵本人在影片中演自己。", "portray oneself（扮演自己）", "describe侧重语言描述，portray可用表演或艺术表现。"],
  ["cover", "covering covers covered", "v.", "报道", "covering the human side为记者报道战争中人的境遇。", "cover the war（报道战争）", "report也为报道，cover强调负责追踪某一题材。"],
  ["human", "humans", "adj.", "人的；体现人性关怀的", "human side指普通士兵的感受与生活，不是抽象伦理评价。", "the human side（与人的生活有关的一面）", "humane是仁慈人道的，human是人的，二者不可任意互换。"],
  ["dirt-snow-and-mud", "", "compound adj.", "满身尘土、积雪和泥浆的", "整体修饰soldiers，连字符把生活环境压缩为一个定语。", "dirt-snow-and-mud soldiers（满身尘土泥雪的士兵）", "这是描述性复合词，不是三个不同兵种。"],
  ["dirt", "", "n.", "尘土；污秽", "与exhaustion并列概括战争生活的艰苦。", "the dirt of war（战争生活的污秽）", "mud为泥浆，dust为灰尘，dirt泛指脏土污物。"],
  ["gain", "gained gains gaining", "v.", "取得；推进", "miles were gained表示战线推进了相应距离。", "gain ground（推进；取得进展）", "patrol为巡逻，gain强调取得空间或进展。"],
  ["capture", "captured captures capturing", "v.", "攻占；占领", "towns were captured为一般过去时被动。", "capture a town（攻占城镇）", "liberate强调解放，capture强调取得控制，两者侧重点不同。"],
  ["parallel", "paralleled parallels paralleling", "v.", "与……相似；与……相呼应", "新闻报道与漫画关注点相近，但并非直接复制。", "parallel another account（与另一叙述相呼应）", "duplicate为复制，contradict为矛盾，parallel只说明相似对应。"],
  ["willie", "", "proper n.", "威利（漫画人物）", "引号标明漫画中的人物名。", "the Willie cartoons（威利漫画）", "专名按漫画称呼理解，不翻成普通物件。"],
  ["cartoon", "cartoons", "n.", "漫画", "这里是报纸画家的作品，不必是动画电影。", "newspaper cartoons（报纸漫画）", "animation特指动画，cartoon可指单幅或连环漫画。"],
  ["famed", "", "adj.", "著名的", "修饰artist，说明画家的声誉。", "a famed artist（著名的艺术家）", "famous也为著名的；fame是不可数名词名声。"],
  ["stripe", "stripes", "n.", "条纹（报纸名的一部分）", "Stars and Stripes整体是《星条旗报》。", "Stars and Stripes（星条旗报）", "专名整体译报纸，不只指布料上的星星和条纹。"],
  ["bill", "", "proper n.", "比尔（人名）", "Bill Mauldin中Bill为名，不是账单。", "Bill Mauldin（比尔·莫尔丁）", "普通名词bill可指账单、法案，需与姓名语境区分。"],
  ["mauldin", "", "proper n.", "莫尔丁（漫画家姓氏）", "与Bill构成画家全名，Both men包括他与Pyle。", "Bill Mauldin（比尔·莫尔丁）", "专名不建立无依据的同源词。"],
  ["emphasize", "emphasized emphasizes emphasizing", "v.", "强调；突出呈现", "主语Both men说明记者与画家共同凸显士兵的生活。", "emphasize hardship（突出艰苦处境）", "admire表示赞美，强调苦难不等于赞美苦难。"],
  ["exhaustion", "", "n.", "筋疲力尽；疲惫", "与dirt并列，强调战争中的身体耗竭。", "physical exhaustion（身体极度疲劳）", "tiredness为一般疲倦，exhaustion程度更深。"],
  ["fragment", "fragments", "n.", "碎片；片段", "比喻战争中保留下来的点滴文明生活。", "fragments of civilization（文明生活的片段）", "stage是阶段，fragment强调从整体中残存的小部分。"],
  ["civilization", "civilizations", "n.", "文明；文明生活", "由咖啡、住所等生活片段具体体现，而非新发明。", "the comforts of civilization（文明生活的便利）", "culture偏文化习俗和价值，civilization更广指社会文明。"],
  ["civilian", "civilians", "n.", "平民", "与soldiers区分，为分享基本生活资源的另一人群。", "soldiers and civilians（军人与平民）", "citizen是公民，可以具有军人身份；civilian指非军人。"],
  ["tobacco", "", "n.", "烟草", "列举士兵分享的日常物品，不作健康益处宣传。", "share tobacco（分享烟草）", "cigarette是香烟，tobacco是烟草原料或制品总称。"],
  ["whiskey", "", "n.", "威士忌酒", "与coffee等并列描述当时士兵生活片段。", "a glass of whiskey（一杯威士忌）", "美式常拼whiskey，whisky为另一常见拼写。"],
  ["egypt", "", "proper n.", "埃及", "国家名在本句借指当地民众。", "Egypt and France（埃及和法国）", "Egyptian为形容词或人称派生词，不并入Egypt词形。"],
  ["dozen", "dozens", "n. / number", "十二个；一打", "a dozen more countries约指另外十多个国家。", "a dozen more countries（另外十多个国家）", "具体数字后dozen通常不用复数；dozens of表示数十个。"],
  ["rebel", "rebelled rebels rebelling", "v.", "反叛", "第1题干扰项，不等于在军队服役。", "rebel against authority（反抗权威）", "resist为抵抗，rebel常指反抗统治或权威。"],
  ["betray", "betrayed betrays betraying", "v.", "背叛；出卖", "第1题干扰项，与解放人民的贡献不是同一行为。", "betray one's country（背叛祖国）", "betray也可指无意显露，如betray anxiety流露焦虑。"],
  ["load", "loaded loads loading", "v.", "装载；使负载", "第3题干扰项，负载通常用load A with B。", "load a truck（给卡车装货）", "bear a burden是承担重担，不等于装载货物。"],
  ["facility", "facilities", "n.", "设施；设备", "第4题干扰项，不能同时概括食物和住所作为必需品。", "public facilities（公共设施）", "necessity按不可或缺划分，facility按服务用途划分。"],
  ["property", "properties", "n.", "财产；特性", "第4题干扰项，非生存必需品的最准确概括。", "private property（私有财产）", "财产义常不可数，properties还可指房产或事物性质。"],
  ["imply", "implying implies implied", "v.", "暗示；意味着", "第7题强调缩写直接代表全称，不是间接暗示。", "imply a connection（暗示某种联系）", "infer是读者推断，imply是表达者隐含表意。"],
  ["disguise", "disguised disguises disguising", "v. / adj.", "伪装；被伪装的", "第11题干扰项不表达军旅生涯杰出。", "disguise one's identity（伪装身份）", "distinguished为杰出的，不要混淆拼写相近词。"],
  ["colony", "colonies", "n.", "殖民地；群落", "第12题干扰项不能作性格集合的近义词。", "a colony of birds（一群鸟的聚居地）", "collection强调集合，colony强调聚居或殖民关系。"],
  ["ethical", "", "adj.", "伦理的；道德的", "第14题非human的直接同义词；本文重在人而非道德规范。", "ethical standards（道德标准）", "ethnic为民族的，ethical为伦理的，注意词形差异。"],
  ["ruin", "ruined ruins ruining", "v.", "毁坏；毁掉", "第15题干扰项，不表达战线推进距离。", "ruin a plan（毁掉计划）", "gain取得进展与ruin毁坏方向不同。"],
  ["commute", "commuted commutes commuting", "v.", "通勤；减轻刑罚", "第15题干扰项与取得作战距离无关。", "commute to work（通勤上班）", "commute指定期往返，不等于军事行军推进。"],
  ["patrol", "patrolled patrols patrolling", "v.", "巡逻", "第15题干扰项，不能把推进距离误读为巡逻路线。", "patrol an area（在某区域巡逻）", "guard侧重守卫，patrol侧重来回巡查。"],
  ["counteract", "counteracted counteracts counteracting", "v.", "抵消；抵制", "第16题干扰项，作品共同呈现类似内容不是互相抵消。", "counteract an effect（抵消某种影响）", "parallel相呼应，counteract作用方向相反。"],
  ["duplicate", "duplicated duplicates duplicating", "v.", "复制；重复", "第16题不能由题材相近推成原样复制。", "duplicate a document（复制文件）", "resemble仅指相似；duplicate含做出副本或重复工作。"],
  ["contradict", "contradicted contradicts contradicting", "v.", "与……矛盾；反驳", "第16题与下文Both men的相同主题不相符。", "contradict a report（与报道矛盾）", "contrast可只表示形成对比，contradict是命题冲突。"],
  ["illusion", "illusions", "n.", "幻觉；错觉", "第18题干扰项，士兵的咖啡、住处不是不存在的幻象。", "an illusion of safety（安全的错觉）", "fragment是真实的一部分，illusion为误认的印象。"],
  ["outset", "", "n.", "开始；开端", "from the outset表示从开始，不等于某一历史时点。", "from the outset（从一开始）", "at that point指当时，未承诺从开始持续到后来。"],
];
const reviewed = reviewedLexicon(rows);
export const cloze2012Lexicon = reviewed.entries;
export const cloze2012LemmaAliases: Record<string, string> = { ...reviewed.aliases, ...Object.fromEntries(rows.map(([headword]) => [headword, headword])), "g.i": "g.i.", best: "best", means: "means", "dirt-snow": "dirt-snow-and-mud", "and-mud": "dirt-snow-and-mud" };
export const cloze2012CollocationGlosses = reviewed.glosses;
export const cloze2012FormPartOfSpeech: Record<string, string> = { american: "adj.", americans: "n.", working: "v.-ing（定语）", writing: "v.-ing（分词）", side: "n.", point: "n.", best: "adv.（最高级）", well: "adv.", grown: "v.-ed（分词定语）", torn: "v.-ed（分词定语）", trained: "v.-ed（分词定语）", equipped: "v.-ed（分词定语）", seen: "v.-ed（分词定语）", based: "v.-ed（分词定语）", paid: "v.-ed（分词定语）", sleep: "n.", "that's": "pron. + linking v." };
cloze2012Lexicon.article.otherMeanings = ["文章；论文，如a newspaper article报纸文章。", "冠词，如the definite article定冠词。", "协议或法律中的条款，如Article 1第一条。"];
cloze2012Lexicon.issue.otherMeanings = ["问题；议题，如address an issue处理问题。", "报刊的一期，如the latest issue最新一期。", "v. 发布、发行、配发，如issue a statement发表声明。"];
cloze2012Lexicon.bear.otherMeanings = ["忍受（bear pain）；承担费用（bear the cost）；具有、带有（bear a name）；结果实（bear fruit）。", "n. 熊；此义与承担负担无关。"];
cloze2012Lexicon.cover.otherMeanings = ["覆盖；遮盖；包含、涉及；支付足够费用；走完一段路程。", "n. 封面；掩护。cover costs支付费用，cover a topic涉及话题，take cover寻找掩护。"];
cloze2012Lexicon.character.otherMeanings = ["性格；品格；特点；文字或符号，如Chinese characters汉字。"];
cloze2012Lexicon.parallel.otherMeanings = ["adj. 平行的；同时发生的；n. 相似之处、对应事物。draw a parallel作类比。"];
export const cloze2012SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {




  "2012-cloze-s1": { see: { contextualMeaning: "看作；视为", use: "see A as B把A看成B，宾语不是从句。" }, it: { contextualMeaning: "G.I. Joe过去的形象", use: "how it used to be回看这一形象从前的情况。" }, use: { contextualMeaning: "过去常常；过去曾经（used to）", use: "used to be是过去状态，非使用某物。" } },
  "2012-cloze-s2": { poor: { contextualMeaning: "贫苦的", use: "修饰farm kid，说明经济出身，不是学业差。" }, go: { contextualMeaning: "在缺乏……的情况下维持（go without）", use: "went without的宾语为必需的食物和住所。" }, they: { contextualMeaning: "二战中服役的男女", use: "they liberated中主语回指军人。" }, it: { contextualMeaning: "stick it out中的习语宾语", use: "不是独立物品；整体表示撑过困难。" } },
  "2012-cloze-s3": { up: { contextualMeaning: "面对；遭遇（up against）", use: "与against共同说明士兵面对强敌的处境，不是向上。" }, this: { contextualMeaning: "上文所说的普通美国兵", use: "以This承接上一句人物画像。" } },
  "2012-cloze-s4": { much: { contextualMeaning: "了不起的东西；特别之处", use: "isn't much是在说名字普通，并非数量很少。" } },
  "2012-cloze-s5": { "g.i.": { contextualMeaning: "Government Issue（政府配发）的缩写", use: "本句专门解释缩写字面来源，不直接作人物名称。" }, it: { contextualMeaning: "G.I.这个标记", use: "was on the articles说明其印在物品上。" }, just: { contextualMeaning: "不过；仅仅", use: "修饰系表结构，淡化名字的特殊性。" } },
  "2012-cloze-s7": { make: { contextualMeaning: "成功到达；跻身（make it to）", use: "made it to the top指取得社会高位，never否定。" }, common: { contextualMeaning: "常见的；普通的", use: "修饰name，指名字不稀奇，非共同拥有。" } },
  "2012-cloze-s8": { work: { contextualMeaning: "劳动；做工（working class）", use: "working作定语构成工人阶级，不是正在工作的临时状态。" } },
  "2012-cloze-s9": { have: { contextualMeaning: "曾有过", use: "has为完成时助动词，had为实义动词；否定局限于文章历史时点。" }, state: { contextualMeaning: "国家事务（secretary of state）", use: "整个职务名称为国务卿，不是州秘书。" } },
  "2012-cloze-s10": { have: { contextualMeaning: "有过；经历过", use: "had a career叙述军旅经历，非完成时助动词。" } },
  "2012-cloze-s11": { he: { contextualMeaning: "G.I. Joe这一人物形象", use: "appears as介绍其在影片中的呈现。" }, last: { contextualMeaning: "最后的", use: "the last days指记者生命最后阶段，不是持续的动词。" } },
  "2012-cloze-s12": { themselves: { contextualMeaning: "这些士兵自己", use: "反身代词说明本人出演本人，主宾同指。" } },
  "2012-cloze-s13": { side: { contextualMeaning: "方面；一面", use: "human side说明战争中的人的处境，不是阵营。" } },
  "2012-cloze-s14": { parallel: { contextualSubstitutions: [{ label: "resembled", chinese: "与……相似", fit: "direct", rewrittenSentence: 'His reports resembled the "Willie" cartoons of famed Stars and Stripes artist Bill Mauldin.', nuance: "resembled侧重题材呈现的相似，paralleled另有相呼应的意味；均不表示复制。", target: "word:resemble" }] }, his: { contextualMeaning: "派尔的", use: "His reports指记者的报道，不是画家的报道。" }, star: { contextualMeaning: "星（Stars and Stripes报纸名的一部分）", use: "整体为星条旗报，不能误作明星。" } },
  "2012-cloze-s15": { both: { contextualMeaning: "两位都", use: "限定men，指派尔与莫尔丁。" }, that: { contextualMeaning: "关系代词，指文明生活的片段", use: "在定语从句中作shared的宾语。" } },
  "2012-cloze-s16": { to: { contextualMeaning: "对……来说", use: "引出各国民众的视角，与第2句相同。" }, their: { contextualMeaning: "上述国家民众的", use: "their lives不是指美军士兵自己的生活。" }, point: { contextualMeaning: "时刻；阶段", use: "at that point限定那一历史时刻。" } },
};
