import type { PracticeTask, GrammarConceptId, ErrorCategory } from "./learning-model";
type Hints = Pick<PracticeTask, "hintWords" | "mapRevealsAnswer" | "leaksToTaskIds" | "leaksToTasks">;
const range = (id: string, prompt: string, answer: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, hints: Hints): PracticeTask => ({ id, revision: 1, kind: "range", prompt, options: [], answer, evidence: answer, feedback, conceptId, errorType, ...hints });
const choice = (id: string, prompt: string, options: string[], answer: number, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, hints: Hints): PracticeTask => ({ id, revision: 1, kind: "choice", prompt, options, answer: options[answer], evidence, feedback, conceptId, errorType, ...hints });
const link = (id: string, prompt: string, pairs: Array<[string,string]>, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, hints: Hints): PracticeTask => ({ id, revision: 1, kind: "link", prompt, options: pairs.map(pair => pair[1]), answer: JSON.stringify(pairs.map(pair => pair[1])), links: pairs.map(([source,target]) => ({ source,target })), evidence, feedback, conceptId, errorType, ...hints });
const order = (id: string, prompt: string, answer: string[], extras: string[], evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, hints: Hints): PracticeTask => ({ id, revision: 1, kind: "order", prompt, options: [...answer,...extras], answer: JSON.stringify(answer), evidence, feedback, conceptId, errorType, ...hints });
const s=(n:number)=>`2012-p3-s${n}`;
export const passage2012P3Practice:Record<string,PracticeTask[]>={
[s(1)]:[link("shock-roles","将动作、受影响者与指代连接。",[["a federal judge","shook的施事"],["America's biotech industry","shook的宾语"],["its","回指产业，不是法官身体"]],"shook America's biotech industry to its core","to its core为震动程度，core比喻根本；2010限定原文历史事件。","basic-svo","reference",{hintWords:["shook","its","core","to its core"]})],
[s(2)]:[link("two-for-and-by","匹配三种介词关系。",[["for isolated DNA","专利对象"],["for decades","持续长度"],["by 2005","截止时点"]],"patents for isolated DNA for decades","两个for不是同义重复；by给统计截止，而some使20%成为约数。","time-reference","attachment",{hintWords:["for","by","some","for decades"]}),choice("approximate-statistic","20%的范围与精度是哪一种？",["截至2005年约20%的人类基因","当今恰好20%的全部DNA分子","某些公司的20%股份"],0,"by 2005 some 20% of human genes","some在数值前是大约，of human genes给分母，不把历史统计移到今日。","comparison-scope","tense",{hintWords:["some","human","genes"],mapRevealsAnswer:true})],
[s(3)]:[range("ruling-content","划出ruled的完整that宾语从句。","that genes were unpatentable","were为系动词，unpatentable为表语，说不具备可专利性，而非只是尚未申请。","clause-object","clause-boundary",{hintWords:["that","ruled","unpatentable"]})],
[s(4)]:[choice("agitated-state","violently agitated描述什么？",["高管极度不安的状态","高管积极活跃的工作表现","已经发生的暴力袭击"],0,"were violently agitated","violently加强情绪，agitated为不安的分词形容词；不能用active偷换。","lexical-context","vocabulary",{hintWords:["violently","agitated"]})],
[s(5)]:[range("assurance-content","划出从that开始的完整保证内容。",'that this was just a "preliminary step" in a longer battle',"this回指不利裁决，just弱化终局性；BIO的安抚不是作者保证未来一定胜利。","clause-object","clause-boundary",{hintWords:["that","this","just","preliminary"]}),link("assure-two-objects","匹配保证结构中的角色。",[["BIO","保证发出者"],["members","接受保证的人"],["that this was just a \"preliminary step\" in a longer battle","保证的内容"]],"assured members that this was just a \"preliminary step\" in a longer battle","assure somebody that...先接人再接内容，区别说话者、听者和命题。","author-voice","attachment",{hintWords:["assured","members"],mapRevealsAnswer:true})],
[s(6)]:[choice("temporary-relief","at least temporarily阻止哪种扩大解读？",["争议已经永久终结","当时行业人士得到暂时宽慰","原文记载日期为7月29日"],0,"at least temporarily","暂时宽慰与终局解决不同；月日原文未附年份，不自行补写。","time-reference","option-logic",{hintWords:["temporarily","least","at least temporarily"],mapRevealsAnswer:true})],
[s(7)]:[range("forecast-relative","只划出修饰two genes的that定语从句。","that help forecast a woman's risk of breast cancer","此that作help主语，forecast为省to不定式；第一个that则引ruling的内容，层级不同。","clause-relative","clause-boundary",{hintWords:["that","help","forecast","risk"]}),link("court-and-company","匹配法院、公司和基因三组动作。",[["appeals court","overturned / ruling"],["Myriad Genetics","could hold patents"],["two genes","help forecast risk"]],"ruling that Myriad Genetics could indeed hold patents to two genes","分词ruling继承法院施事；公司是内容从句主语，基因再作定语从句的先行词。","nonfinite-subject","attachment",{hintWords:["ruling","could","hold","genes"]})],
[s(8)]:[link("company-and-voice","将公司补充、发言者及评价匹配。",[["a company in Utah","解释Myriad，不是executive"],["The chief executive","said的发言者"],["a blessing","发言者对判决的评价"]],"The chief executive of Myriad, a company in Utah, said","嵌入同位语不能误接为高管是一家公司；评价由said归给高管。","apposition","attachment",{hintWords:["company","executive","said","blessing"],mapRevealsAnswer:true,leaksToTasks:[{sentenceId:"2012-p3-map",taskId:"argument-voices"}]})],
[s(9)]:[range("as-development","划出as引导的完整背景从句，不包含句首But。","as companies continue their attempts at personalised medicine","as意为随着，提供持续探索背景；主句courts will remain busy另有主系表。","clause-time","clause-boundary",{hintWords:["as","continue","attempts"]})],
[s(10)]:[choice("probably-not-over","is probably not over的力度是哪一种？",["很可能尚未终结","已确定永不终结","已确定彻底结束"],0,"is probably not over","probably保留推测，not否定结束状态；不能删任一个限定词。","negation-contrast","option-logic",{hintWords:["probably","not","over"],mapRevealsAnswer:true})],
[s(11)]:[link("two-it","把两处it接回各自对象。",[["may not be patented中的it","a gene"],["reward it中的it","innovation"]],"a gene is a product of nature, so it may not be patented; gene patents suppress innovation rather than reward it","第一个论点谈自然物不得专利，第二个谈是否奖励创新；不能按同词形统一指代。","reference-pronoun","reference",{hintWords:["it","patented","reward","rather than reward it"]}),choice("critics-position","三项论点是谁的主张？",["反对基因专利的Critics","作者明确宣告的个人立场","Myriad首席执行官的支持理由"],0,"Critics make three main arguments against gene patents","Critics在冒号前明确归属；支持者a blessing出自上一段，不能混声。","author-voice","passage-logic",{hintWords:["Critics","against"],mapRevealsAnswer:true,leaksToTasks:[{sentenceId:"2012-p3-map",taskId:"argument-voices"}]})],
[s(12)]:[choice("growing-number","A growing number能安全还原到哪个范围？",["越来越多的人，未指定所有法官","所有最高法院法官","固定的某个数学整数"],0,"A growing number seem to agree","承前是认同批評意见的人数增加，seem还保留看来如此；不补职业与全称。","comparison-scope","option-logic",{hintWords:["number","growing","seem","A growing number"]})],
[s(13)]:[range("related-patents","划出限定patents的过去分词短语。","related to genetic tests","related没有独立时态或主语，是patents后置定语；不是另一个主句改革行动。","nonfinite-participle","attachment",{hintWords:["related","patents","related to genetic tests"]}),choice("urged-not-enacted","urged reform实际报告了什么？",["工作组敦促改革","改革已经全部生效","所有专利立即作废"],0,"urged reform","敦促是提出要求，未报告完成；Last year相对文章原来时点。","author-voice","option-logic",{hintWords:["urged","reform"]})],
[s(14)]:[link("comparison-inversion","匹配比较结构中的主语、谓语和定语。",[["an isolated DNA molecule","主比较项"],["are","比较分句前置谓语"],["cotton fibres","比较分句主语中心"],["that have been separated from cotton seeds","修饰cotton fibres"]],"no less a product of nature…than are cotton fibres that have been separated from cotton seeds","no less否定更低自然属性，类比为同样自然；are在长主语前不是提问。","comparison-scope","clause-boundary",{hintWords:["no","less","than","are","fibres","no less a product of nature…than are cotton fibres"]}),range("separated-fibres","划出最后一个that定语从句。","that have been separated from cotton seeds","have been separated为完成时被动，from给来源，that代替被分离的纤维作主语。","passive-voice","clause-boundary",{hintWords:["that","been","separated","separated from cotton seeds"]})],
[s(15)]:[order("remaining-question-trunk","排除让步背景，重建主系表。",["big questions","remain","unanswered"],["Despite the appeals court's decision"],"big questions remain unanswered","despite后接名词短语，主句仍是重大疑问未答；不是有了法院裁决就一切明确。","basic-svc","predicate",{hintWords:["remain","unanswered","Despite","remain unanswered"]})],
[s(16)]:[range("whether-uncertain","划出unclear所评价的完整whether主语从句。","whether the sequencing of a whole genome violates the patents of individual genes within it","whether保留是否，不能摘取violates变为已侵权；whole genome与individual genes范围不同。","clause-subject","clause-boundary",{hintWords:["whether","unclear","whole","individual"]}),link("two-it-roles","匹配句首与句尾it。",[["it is unclear中的it","形式主语，对应whether命题"],["within it中的it","回指a whole genome"]],"it is unclear whether the sequencing of a whole genome violates the patents of individual genes within it","前者是句法占位，后者是实体回指；二者不能合成同一个基因专利对象。","reference-pronoun","reference",{hintWords:["it","within","whether"]})],
[s(17)]:[choice("may-yet","may yet reach保留哪种状态？",["从文章时点看未来仍可能进入最高法院","已经进入并已获得终审结果","永远不会进入最高法院"],0,"may yet reach the Supreme Court","may标可能，yet表示后续仍可发生；既不报告已经发生，也不保证未来。","time-reference","tense",{hintWords:["may","yet","reach"],mapRevealsAnswer:true})],
[s(18)]:[range("industry-background","划出As时间背景从句，在逗号前停止。","As the industry advances","industry为主语，advances为动词谓语，不能把advances读作名词复数。","clause-time","predicate",{hintWords:["As","industry","advances"]})],
[s(19)]:[link("most-and-limits","匹配数量、概率和两种状态。",[["unlikely to file many more","不大可能大量新增，非绝无申请"],["most","多数human DNA molecules"],["already patented or in the public domain","两种备选状态，非全部受专利保护"]],"most are already patented or in the public domain","most按DNA分子回指；public domain和patented不能合并成一样的排他权状态。","comparison-scope","reference",{hintWords:["unlikely","most","or","public","in the public domain"]})],
[s(20)]:[range("study-object","只划出studying的how宾语从句。","how genes interact","研究对象是基因怎样相互作用；病因与药效在后面属于这些关联的潜在用途。","clause-object","clause-boundary",{hintWords:["how","genes","interact"]}),link("research-and-use","分清发现与用途。",[["how genes interact","研究的对象"],["determine the causes of disease","可能用途之一：查明病因"],["predict a drug's efficacy","可能用途之二：预测药效"]],"might be used to determine the causes of disease or predict a drug's efficacy","might限制潜在用途，determine和predict共用to；不能将疾病应用偷换成研究疾病之间的关系。","nonfinite-infinitive","attachment",{hintWords:["might","determine","predict","efficacy"],mapRevealsAnswer:true,leaksToTasks:[{sentenceId:"2012-p3-map",taskId:"research-shift"}]})],
[s(21)]:[link("reporting-inversion","匹配引述愿望、解释者与比喻。",[["Companies are eager","被转述的企业愿望"],["Hans Sauer","explains的后置主语"],["connecting the dots","将线索联系起来，承前指发现基因互动"]],"explains Hans Sauer","报道倒装不改解释者身份；比喻必须读前句研究对象，不能字面化为画图。","author-voice","attachment",{hintWords:["explains","Hans","Sauer","connecting the dots"],mapRevealsAnswer:true})],
[s(22)]:[range("case-relative","划出which引导的完整非限制性定语从句。","which the Supreme Court will hear in its next term","which在从句作hear宾语，回指suit；Court为主语，its回指法院，term为审期。","clause-relative","clause-boundary",{hintWords:["which","hear","its","term","in its next term"]}),link("suit-modifiers","匹配案件的两项分词限定。",[["related to this issue","案件与当前专利议题有关"],["brought by the Mayo Clinic","案件由梅奥诊所提起"]],"a suit related to this issue, brought by the Mayo Clinic","两个分词短语都修饰suit，没有另立主句；bring a suit是提起诉讼。","nonfinite-participle","attachment",{hintWords:["related","brought","suit","brought by the Mayo Clinic"]})],
[s(23)]:[range("convention-relative","划出修饰convention的完整which定语从句。","which included sessions to coach lawyers on the shifting landscape for patents","included为从句谓语，sessions为宾语；to coach为用途不定式，on引培训主题。","clause-relative","clause-boundary",{hintWords:["which","included","sessions","coach","landscape"]})],
[s(24)]:[choice("packed-and-topic","结合前句会议主题，packed最贴合哪种推断？",["基因专利变化广受关注","律师通常热爱所有大会","最高法院一定支持基因专利"],0,"Each meeting was packed","packed先表示座无虚席；用前句培训专利形势的主题才能推到关切对象，不泛化为参会癖好或法院立场。","paragraph-role","passage-logic",{hintWords:["Each","meeting","packed"],mapRevealsAnswer:true})],
};
