import type { BeginnerClauseDetail, BeginnerSyntaxComponent, SentenceAnalysis, SyntaxVisualRole } from "./data";
import { withReviewedSyntax } from "./reviewed-syntax";
import { passage2012P2Practice } from "./2012-passage-2-practice";
type Part = { component: BeginnerSyntaxComponent; color: SyntaxVisualRole; chinese: string };
const c = (text:string,color:SyntaxVisualRole,form:string,fn:string,modifies:string,explanation:string,chinese:string,children?:BeginnerSyntaxComponent[]):Part=>({component:{text,form,function:fn,modifies,explanation,children},color,chinese});
const child=(text:string,form:string,fn:string,modifies:string,explanation:string,children?:BeginnerSyntaxComponent[]):BeginnerSyntaxComponent=>({text,form,function:fn,modifies,explanation,children});
const cl=(text:string,type:string,marker:string,role:string,subject:string,predicate:string,details:Array<[string,string]>,translationOrder:string):BeginnerClauseDetail=>({text,type,marker,role,subject,predicate,predicateDetails:details.map(([fn,value])=>({function:fn,text:value})),translationOrder});
type Review={parts:Part[];clauses:BeginnerClauseDetail[];focus:string;question:string;evidence:string;answer:string;natural?:string;notes?:string[]};
const reviews:Record<number,Review>={
  1:{parts:[
    c("Pretty in pink","modifier","形容词短语","题目式引题","冒号后粉色文化讨论","这是带评论色彩的开头短语，无独立限定谓语。","穿粉色很漂亮"),
    c("adult women","subject","名词短语","第一分句主语","do not remember的施事","adult限定成年女性，与young girls构成代际对照。","成年女性"),c("do not remember","predicate","一般现在时否定","第一分句谓语","adult women","do为否定助动词，remember后接动名词表示回忆已发生的经验。","不记得"),
    c("being so obsessed with the colour","object","动名词短语","宾语","remember","being obsessed说过去处于痴迷状态；不是remember to do记得将来要做。","自己曾如此痴迷这种颜色",[child("so","副词","程度状语","obsessed","so强调痴迷程度。"),child("with the colour","介词短语","痴迷对象补足语","obsessed","the colour指pink。")]),
    c("yet","connector","并列连词","转折连接","成年女性回忆与当下女孩生活","这里相当于but。","然而"),c("it","subject","代词","第二分句主语","回指pink","指粉色在生活中的普遍存在。","粉色"),c("is","predicate","系动词","第二分句谓语","连接it与pervasive","后接形容词表语。","却是"),c("pervasive","complement","形容词","表语","说明pink的影响范围","表示渗透各处，比单纯受欢迎更强调无处不在。","无处不在的"),c("in our young girls' lives","modifier","介词短语","生活范围状语","is pervasive","限定为我们年幼女孩的生活。","在我们的年幼女孩生活中"),
  ],clauses:[],focus:"remember doing回忆既有经验，yet把成年女性的记忆与现在女孩的生活并置。",question:"being obsessed是正在新发生的主句动作吗？",evidence:"adult women do not remember being so obsessed with the colour",answer:"不是。remember的宾语是整个动名词短语，回忆自己过去是否如此痴迷；being没有另立限定时态。yet后it is才是另一组主谓。"},
  2:{parts:[
    c("It","subject","评价结构形式主语","第一分句主语","用于It is not that结构","该结构先否定一种对作者观点的理解，不把It指定为具体物品。","并不是说（与后面结构合译）"),c("is not","predicate","否定系动词","第一分句谓语","否定后面的判断内容","否定的是粉色本身不好这一判断。","并非如此"),c("that pink is intrinsically bad","complement","that内容从句","表语从句","给出被否定判断","pink为内部主语，bad为表语，intrinsically修饰bad。","粉色本身不好",[child("intrinsically bad","形容词短语","从句表语","is","intrinsically表示本质上，不是强调市场效果。")]),
    c("but","connector","转折连词","转折连接","引出真正批评理由","颜色无罪与文化垄断可以区分。","但是"),c("it","subject","代词","第二分句主语","回指pink","此处为实际指代粉色。","它"),c("is","predicate","系动词","第二分句谓语","连接粉色与比喻身份","主系表。","只是"),c("such a tiny slice of the rainbow","complement","名词短语","表语","说明粉色只是色彩的一小部分","slice为一小片的比喻；such a加形容词和单数名词。","彩虹中如此小的一片",[child("of the rainbow","介词短语","整体范围限定","slice","粉色只属于多彩可能性的一部分。")]),c("and","connector","并列连词","并列连接","连接两项批评","继续讨论粉色带来的身份限制。","而且"),
    c("though it may celebrate girlhood in one way","modifier","让步从句","让步状语从句","限定后面fuses的评价","承认某一种可能的赞美作用，不同于同意唯一标签。","尽管它也许能以一种方式赞美女孩时期",[child("in one way","介词短语","方式状语","celebrate","只说一种方式，不包揽女孩全部可能。")]),
    c("it","subject","代词","第三分句主语","回指pink","保持同一批评对象。","它"),c("also repeatedly and firmly fuses","predicate","一般现在时动词含副词","第三分句谓语","说明绑定作用","also表示还有，repeatedly与firmly共同修饰fuses。","也反复而牢固地绑定"),c("girls' identity","object","所有格名词短语","宾语","fuses","被绑定的是女孩的身份。","女孩的身份"),c("to appearance","complement","介词短语","绑定对象补足语","fuses girls' identity","fuse A to B把A与B结合。","与外貌"),
  ],clauses:[cl("that pink is intrinsically bad","表语内容从句","that","补充被否定的判断","pink","is",[["表语","intrinsically bad"]],"用并不是说先否定误解，再读颜色本身不好。"),cl("though it may celebrate girlhood in one way","让步状语从句","though","对主句批评作让步","it","may celebrate",[["宾语","girlhood"]],"先承认一种可能作用，再回主句反复绑定身份的批评。")],focus:"先排除颜色本身不好，再批评单一标签把女孩身份绑到外表。",question:"tiny slice是否说明粉色没有影响？",evidence:"such a tiny slice of the rainbow",answer:"不是。slice只说它在丰富颜色中占一小部分；后面fuses明确说它能影响身份。作者反对把这一小部分当成女孩的全部代表。",natural:"并不是说粉色本身不好，但它只是彩虹中极小的一部分；而且，尽管它或许能以一种方式赞美女孩时期，却也不断把女孩的身份牢牢与外貌绑定。",notes:["It is not that合译为‘并不是说’；表语结构中的is在第二分句译作‘只是’以承接tiny slice，限制来自整组表达。"]},
  3:{parts:[
    c("Then","connector","顺承副词","论述推进","承接身份与外貌的绑定","说明这种联系接下来被怎样呈现，不提供精确时刻。","接着"),c("it","subject","代词","主语","回指前文粉色文化的作用","把颜色及其文化使用视为施事，不另引入新人物。","它"),c("presents","predicate","一般现在时及物动词","谓语","说明对connection的包装","present A as B为把A呈现为B。","把……呈现为"),c("that connection","object","名词短语","宾语","presents","that connection承接前句身份与外貌的绑定。","那种联系"),c("even among two-year-olds","modifier","副词加介词短语","涉及人群范围状语","presents that connection","even突出年龄很小也被包括。","甚至在两岁儿童当中"),c("between girls","modifier","原卷保留的异常介词片段","关系片段（对象未完整给出）","与connection相邻，具体并列关系无法从原卷补全","between后的girls缺少可确认的另一并列对象；保留原文，不自行补入颜色词。","between girls：原卷关系表达不完整，不能据此补出另一对象"),c("as not only innocent but as evidence of innocence","complement","as引出的呈现内容（保留原卷不对称形式）","呈现状态补足语","presents that connection","可确认的评价递进是innocent到evidence of innocence；原卷重复as形式保留。","不仅是无害的，而且是纯真的证据"),
  ],clauses:[],focus:"connection的回指与两级评价可以确认，异常between片段不能猜词补全。",question:"哪些关系有原文依据，哪些不能擅自补出？",evidence:"between girls as not only innocent but as evidence of innocence",answer:"that connection承接上一句身份与外貌的绑定；not only...but...把无害推进到纯真证据。这些可读出，但between girls没有完整提供另一对象，不能把猜测的pink或and写回正文或当作已核对的句法。",notes:["用户原卷快照保留between girls异常片段；本句通顺译文只表达上下文可确认的联系与评价，不作为修复原文的依据。"]},
  4:{parts:[c("Looking around","modifier","现在分词短语","伴随观察状语","主语I","观察者是作者；非谓语没有另一个主语。","环顾四周"),c("I","subject","代词","主语","despaired的施事","作者直接表达感受。","我"),c("despaired","predicate","一般过去时","谓语","说明作者的失望","despair at引造成失望的对象。","深感失望"),c("at the singular lack of imagination about girls' lives and interests","complement","介词短语含名词修饰","失望对象补足语","despaired","lack of imagination的内容是关于女孩生活兴趣的社会想象，不是说女孩智力贫乏。","对于人们对女孩生活和兴趣的想象如此贫乏",[child("the singular lack of imagination","名词短语","介词宾语","at","singular强调突出程度，中心lack。"),child("about girls' lives and interests","介词短语","内容限定","imagination","缺乏的是人们对女孩生活可能性的丰富想象。")])],clauses:[],focus:"缺乏想象力的是对女孩生活的设想，不是作者指责女孩本人。",question:"about girls' lives and interests说明什么？",evidence:"the singular lack of imagination about girls' lives and interests",answer:"它限定imagination涉及的内容，作者不满对女孩生活兴趣的设想单一。不能将about删去，误读为女孩自身没有想象力。"},
  5:{parts:[
    c("Girls' attraction to pink","subject","名词短语","第一分句主语","may seem的主语","中心attraction；Girls'说明喜爱者，to pink说明喜爱对象。","女孩对粉色的喜爱",[child("to pink","介词短语","喜爱对象补足语","attraction","不是女孩本身吸引粉色。")]),c("may seem","predicate","情态动词加系动词","第一分句谓语","说明表面印象","may和seem均不能变成科学事实。","似乎是"),c("unavoidable","complement","形容词","表语","说明attraction的表面性质","这里说看来无法避免。","不可避免的"),c("somehow encoded in their DNA","modifier","过去分词短语","假定性状态补充","Girls' attraction","像是写进DNA的假想说明，受may seem限定；没有断言实际编码事实。","仿佛以某种方式被写进她们的DNA",[child("in their DNA","介词短语","编码位置补足语","encoded","their指女孩。")]),c("but","connector","转折连词","转折连接","表象与研究者观点对照","下文否定天生必然的想法。","但是"),c("according to Jo Paoletti, an associate professor of American Studies","modifier","来源介词短语含同位语","观点来源状语","it is not","专名之后是其学术身份。","按美国研究副教授乔·保莱蒂的说法",[child("an associate professor of American Studies","同位语名词短语","身份说明","Jo Paoletti","associate professor为副教授；不是两个不同说话人。")]),c("it","subject","代词","第二分句主语","回指Girls' attraction to pink","不是指教授本人。","这种喜爱"),c("is not","predicate","系动词否定与表语省略","第二分句谓语","否定前述不可避免或基因预定的看法","省略已出现的表语内容，不把未写词补回英文。","并非如此"),
  ],clauses:[],focus:"may seem把DNA解释放在表面印象层；but it is not才是研究者给出的纠正。",question:"encoded in their DNA能单独当作文章的结论吗？",evidence:"may seem unavoidable, somehow encoded in their DNA, but according to Jo Paoletti, an associate professor of American Studies, it is not",answer:"不能。分词短语补充的是看似天生的印象，而but后的is not明确否定。后文历史上的粉蓝意义变化为否定提供依据。"},
  6:{parts:[
    c("Children","subject","复数名词","第一分句主语","were colour-coded的对象","儿童是被按颜色分类的对象。","儿童"),c("were not colour-coded","predicate","一般过去时否定被动","第一分句谓语","说明尚无按颜色分类","colour-coded为复合分词。","没有被按颜色分类"),c("at all","modifier","固定副词短语","否定程度状语","were not colour-coded","at all加强not。","完全没有"),c("until the early 20th century","modifier","until介词短语","时间界限状语","were not colour-coded","与否定合读为20世纪初之前一直没有，不能反转为从此以后没有。","一直到20世纪初之前"),c("in the era before domestic washing machines","modifier","介词短语含时间后置限定","时间背景状语","all babies wore white","洗衣机出现前限定era，不是额外主谓句。","在家用洗衣机出现之前的时代",[child("before domestic washing machines","介词短语","后置定语","era","原文以洗衣机指其出现与使用的时代界限。")]),c("all babies","subject","数量限定名词短语","第二分句主语","wore的施事","说那个历史阶段婴儿普遍穿白色。","所有婴儿"),c("wore","predicate","一般过去时及物动词","第二分句谓语","all babies","wear过去式为wore。","都穿"),c("white","object","颜色名词","宾语","wore","颜色名词指白色衣物。","白色衣物"),c("as a practical matter","modifier","固定介词短语","实际考虑状语","wore white","说明出于实际考虑，理由随后给出。","出于实际考虑"),c("since the only way of getting clothes clean was to boil them","modifier","since原因从句","原因状语从句","解释白色衣物的实用性","since意为因为，was连接way与不定式表语。","因为把衣服洗干净的唯一方法是将其煮沸",[child("the only way of getting clothes clean","名词短语","从句主语","was","中心way，getting clothes clean说明方法要实现的结果。",[child("getting clothes clean","动名词短语含宾补","介词of的宾语","way of","clothes作getting宾语，clean作宾语补足语。")]),child("to boil them","不定式短语","从句表语","was","them指clothes，方法是煮衣服。")]),
  ],clauses:[cl("since the only way of getting clothes clean was to boil them","原因状语从句","since","解释穿白色的实用原因","the only way of getting clothes clean","was",[["表语","to boil them"]],"先交代婴儿穿白色，再解释洗净只能靠煮的原因。")],focus:"until给出历史界限，since给原因；白色是清洗条件的选择，不是婴儿偏好。",question:"since是否也表示从某时以来？",evidence:"since the only way of getting clothes clean was to boil them",answer:"此处since后解释为什么穿白色，意为因为。它的主语中心为way，表语to boil them；them指衣服，不是孩子。",natural:"20世纪初之前，儿童完全没有按颜色分类。家用洗衣机出现以前，婴儿都穿白色衣服，这是出于实际考虑，因为把衣服洗干净的唯一办法是煮沸。",notes:["white译成白色衣物，衣物来自wear的穿着语境；before domestic washing machines译出洗衣机‘出现以前’，原文未给精确发明或普及年份。"]},
  7:{parts:[c("What's more","connector","固定连接表达","递进连接","补充历史证据","整体意为而且，不作一个新的问句。","而且"),c("both boys and girls","subject","both…and并列名词短语","主语","wore的施事","男孩和女孩均包含在内。","男孩和女孩"),c("wore","predicate","一般过去时","谓语","说明两者穿着","后接what从句作宾语。","都穿"),c("what were thought of as gender-neutral dresses","object","what融合关系从句","宾语从句","wore","what在内部为were thought of的主语，整体指被视为中性裙装的衣物。","被视为不分性别的连衣裙",[child("as gender-neutral dresses","介词短语","主语身份补足语","what were thought of","think of A as B的被动：所穿衣物被看作B。")])],clauses:[cl("what were thought of as gender-neutral dresses","融合关系名词性从句","what","作wore宾语；what兼作内部主语","what","were thought of",[["主语身份补足语","as gender-neutral dresses"]],"整体译为被认为是不分性别的裙装。")],focus:"gender-neutral限定dresses，不能搬到下一句的pink颜色上。",question:"what在从句中只是连接词吗？",evidence:"what were thought of as gender-neutral dresses",answer:"what还作were thought of的主语；整个从句作wore宾语。中性描述的是衣物，不能据此说粉色过去是中性色。",natural:"而且，男孩和女孩都穿被认为是不分性别的连衣裙。"},
  8:{parts:[
    c("When nursery colours were introduced","modifier","时间从句","时间状语从句","限定主句历史情形","nursery colours是被引入的色彩分类，不是自己引入东西。","当婴幼儿色彩分类被引入时"),c("pink","subject","颜色名词","主语","was considered的评价对象","粉色是被看作男性化的一方。","粉色"),c("was actually considered","predicate","一般过去时被动","谓语","说明当时评价","actually纠正现代读者直觉；被动主语已是pink。","实际上被认为是"),c("the more masculine colour","complement","比较级名词短语","主语补足语","补充pink被视为何种颜色","主动式consider A B中的B在被动后补充主语，不再叫宾语或宾补。","更男性化的颜色"),c("a pastel version of red, which was associated with strength","modifier","同位语名词短语含定语从句","同位说明","pink","解释粉色是红色的浅淡版本；which就近回指red。","是红色的浅淡版本，而红色与力量相联系",[child("of red, which was associated with strength","介词短语含定语从句","来源限定","version","which从句放在red后说明红色的象征。",[child("which was associated with strength","非限制性定语从句","补充定语","red","which不是回指整句，也不是蓝色。")])]),
  ],clauses:[cl("When nursery colours were introduced","时间状语从句","When","限定当时的颜色分类情形","nursery colours","were introduced",[],"先交代婴幼儿色彩被引入时，再说粉色评价。"),cl("which was associated with strength","非限制性定语从句","which","修饰red","which","was associated",[["关联对象补足语","with strength"]],"先读浅红色，再补红色与力量的联系。")],focus:"被动后的男性化颜色补充pink，which则回指红色的力量联想。",question:"the more masculine colour为什么不是considered的宾语？",evidence:"pink was actually considered the more masculine colour",answer:"pink已经是被动主语，后面的名词说明它被看作什么。主动关系是把粉色看作更男性化的颜色，被动后这是主语补足语；不能把颜色再当动作接收者。"},
  9:{parts:[c("Blue","subject","颜色名词","主语","symbolised的对象","蓝色承担象征作用。","蓝色"),c("with its intimations of the Virgin Mary, constancy and faithfulness","modifier","with介词短语","伴随特征说明","Blue","its指Blue；of后并列三项联想，不把constancy另接主句谓语。","因它使人联想到圣母玛丽亚、坚定与忠贞",[child("of the Virgin Mary, constancy and faithfulness","介词短语","联想内容补足语","intimations","三项同属of所引内容。")]),c("symbolised","predicate","一般过去时","谓语","说明蓝色历史含义","象征关系由文化赋予，不证明生物本质。","象征着"),c("femininity","object","抽象名词","宾语","symbolised","指女性气质，不是形容词女性的。","女性气质")],clauses:[],focus:"插入的with短语解释蓝色联想，主干是Blue symbolised femininity。",question:"Virgin Mary、constancy和faithfulness属于哪一层？",evidence:"with its intimations of the Virgin Mary, constancy and faithfulness",answer:"三项都是intimations所引出的联想内容，位于with插入说明内。主句只有Blue与symbolised femininity，不能把并列名词错当新的谓语。",natural:"蓝色因使人想到圣母玛丽亚、坚定和忠贞，而象征女性气质。",notes:["with本身表示带有这些联想；通顺译文用‘因’呈现这里的说明关系，不代表原文另有because。"]},
  10:{parts:[
    c("It was","predicate","强调句框架","强调结构起点","与后面的that呼应","It在强调结构中不指粉色或婴儿，不按普通主系表逐词硬译。","直到……才（与not until及that合译）"),
    c("not until the mid-1980s, when amplifying age and sex differences became a dominant children's marketing strategy","modifier","被强调的时间成分含定语从句","时间焦点","限定pink came into its own","when补充80年代中期的营销特点，amplifying整个动名词短语为became主语。","直到20世纪80年代中期，当放大年龄和性别差异成为主导的儿童营销策略时",[child("when amplifying age and sex differences became a dominant children's marketing strategy","时间定语从句","时代背景说明","the mid-1980s","不是与后面pink平行的主句。",[child("amplifying age and sex differences","动名词短语","从句主语","became","被放大的对象是年龄和性别差异。")])]),
    c("that pink fully came into its own","complement","强调句被还原的命题部分","强调结构后项","与It was not until组成整体","pink为主语，came into its own为习语真正兴盛。","粉色才真正兴盛起来"),
    c("when it began to seem inherently attractive to girls, part of what defined them as female","modifier","when补充时间说明含表语并置","时间场景补充","pink兴盛的阶段","it指pink；seem保留看起来天然的印象，part补充其身份标签作用。","那时它开始显得天生吸引女孩，成为界定她们为女性的因素之一",[child("it began to seem inherently attractive to girls","主谓结构","when从句主体","说明那时粉色的表象","inherently修饰attractive，不能删去seem就当基因事实。"),child("part of what defined them as female","名词短语","补充表语","粉色被赋予的身份作用","part只说其中一部分。",[child("what defined them as female","融合关系名词性从句","介词of的宾语","part of","what兼任defined主语，them指女孩，as female说明分类身份。")])]),
    c("at least for the first few critical years","modifier","限定副词加时间介词短语","时间范围限定","上述吸引与身份作用","at least给出最低范围，first few critical years只说最初关键几年，未限定终身。","至少在最初的几个关键年份里"),
  ],clauses:[cl("when amplifying age and sex differences became a dominant children's marketing strategy","时间定语从句","when","补充the mid-1980s背景","amplifying age and sex differences","became",[["表语","a dominant children's marketing strategy"]],"把营销策略背景放在80年代中期之后说明。"),cl("that pink fully came into its own","强调结构命题部分","that（强调连接）","与It was not until构成强调句","pink","came",[["习语补足语","into its own"]],"合译直到该时期粉色才真正兴盛，不把that当普通宾语引导词。"),cl("when it began to seem inherently attractive to girls, part of what defined them as female","补充时间关系从句","when","说明粉色兴盛时出现的表象","it","began",[["不定式补足语","to seem inherently attractive to girls"],["补充表语","part of what defined them as female"]],"先保留开始显得天然吸引，再补它成了身份标签的一部分。"),cl("what defined them as female","融合关系名词性从句","what","作of宾语，what为内部主语","what","defined",[["宾语","them"],["身份补足语","as female"]],"译作把她们界定为女性的因素。")],focus:"not until强调较晚历史时点；seem保留营销造成的天然印象，不能删掉。",question:"这句话为何同时需要保留1980s、marketing和seem？",evidence:"not until the mid-1980s, when amplifying age and sex differences became a dominant children's marketing strategy",answer:"时点表明这种固定联系形成较晚，when明确交代营销策略，后面seem说明‘天然吸引’是开始呈现的印象。三者共同反对不变的DNA解释，不能简化成粉色天生适合女孩。",natural:"直到20世纪80年代中期，放大年龄和性别差异成为主导的儿童营销策略时，粉色才真正兴盛起来；那时它开始显得天生吸引女孩，成为把她们界定为女性的因素之一，至少在最初几个关键年份里是如此。"},
  11:{parts:[c("I","subject","代词","主语","had realised的认识者","作者描述自己此前的认识局限。","我"),c("had not realised","predicate","过去完成时否定","谓语","说明过去参照点以前尚未认识到","相对后文获知历史信息的叙述阶段，不补具体日期。","此前没有意识到"),c("how profoundly marketing trends dictated our perception of what is natural to kids, including our core beliefs about their psychological development","object","how宾语从句含嵌套what从句","宾语从句","realised的内容","how profoundly表示左右程度；包括心理发展信念在内，marketing trends是dictated主语。","营销趋势竟如此深刻地左右我们关于什么对儿童是自然的看法，其中包括对他们心理发展的核心信念",[child("how profoundly","感叹程度表达","程度状语","dictated","问句词序没有倒装，how强调影响多深。"),child("our perception of what is natural to kids","名词短语","dictated的宾语","dictated","中心perception，what从句限定我们理解的内容。",[child("what is natural to kids","融合关系名词性从句","介词of的宾语","perception of","what为is主语，natural为表语。")]),child("including our core beliefs about their psychological development","including介词短语","包含内容补充","our perception","心理发展信念是被影响认知的一部分。")])],clauses:[cl("how profoundly marketing trends dictated our perception of what is natural to kids, including our core beliefs about their psychological development","宾语从句","how","作realised宾语","marketing trends","dictated",[["宾语","our perception of what is natural to kids"]],"先译营销影响程度，再译我们的认知及包含的心理发展信念。"),cl("what is natural to kids","融合关系名词性从句","what","作of宾语","what","is",[["表语","natural to kids"]],"译成对儿童而言自然的事物，不另举原文没有的具体行为。")],focus:"营销趋势左右的是人们的认知，不是原文已经证明它直接改写儿童DNA。",question:"dictated的主语和宾语分别是什么？",evidence:"marketing trends dictated our perception of what is natural to kids",answer:"主语marketing trends，宾语our perception及其内容限定。心理发展信念被including纳入被影响的认知范围，不能把它错当营销趋势的施事。"},
  12:{parts:[c("Take","predicate","祈使动词原形","谓语","省略的读者you","本句以take引例，不是要求抱起儿童。","以……为例"),c("the toddler","object","名词短语","宾语","Take","在下文讨论幼儿称谓与阶段概念的来源。","toddler这一幼儿概念")],clauses:[],focus:"短祈使句用于转入实例，toddler不是新研究的施事。",question:"Take在这里要求读者做什么？",evidence:"Take the toddler",answer:"让读者考虑toddler这个例子。主语you在祈使句中省略，下一句马上讨论该阶段的来源，不能译成把幼儿带走。"},
  13:{parts:[c("I","subject","代词","主语","assumed的施事","作者先报告自己的原先设想。","我"),c("assumed","predicate","一般过去时","谓语","引原先未经证实的理解","后面内容从句省略连接词that。","原以为"),c("that phase was something experts developed after years of research into children's behaviour","object","省略连接词的宾语从句含定语从句","宾语从句","assumed的内容","that phase的that是指示限定词；不是同时再充当从句连接词。","那个阶段是专家经过多年研究儿童行为后提出的某种概念",[child("that phase","名词短语","从句主语","was","that指上句toddler阶段，整个名词短语作主语。"),child("something experts developed after years of research into children's behaviour","名词短语含定语从句","从句表语","was","something为中心，experts从句说明其来由。",[child("experts developed after years of research into children's behaviour","省略关系词的定语从句","后置定语","something","experts为developed主语；宾语关系词省略。")])]),c("wrong","complement","形容词性省略评注","自我纠正","前面整项assumption","冒号后否定自己的原先理解，不是批评儿童行为错了。","这想法错了")],clauses:[cl("that phase was something experts developed after years of research into children's behaviour","省略连接词的宾语从句","连接词that省略；原文that修饰phase","作assumed宾语","that phase","was",[["表语","something experts developed after years of research into children's behaviour"]],"先译那个阶段是什么，再把专家研究加入其来源。"),cl("experts developed after years of research into children's behaviour","省略关系词的定语从句","省略that/which","修饰something；省略关系词作宾语","experts","developed",[],"译作专家多年研究后提出的概念，不补写原文没有的关系词。")],focus:"that phase是从句主语，连接词被省略；冒号后的wrong推翻前面整项设想。",question:"第一个that是不是assumed后的连接词？",evidence:"I assumed that phase was something",answer:"这里that与phase组成‘那个阶段’，共同作was主语；宾语从句的连接词另被省略。若把that当纯连接词，就会漏掉phase前的指示作用。"},
  14:{parts:[c("Turns out","connector","口语省略的结果表达","叙述纠正连接","对照上一句wrong后的真实情况","It turns out (that)中的形式主语和连接词没有写出，原文照存。","结果发现"),c("according to Daniel Cook, a historian of childhood consumerism","modifier","来源介词短语含同位语","观点来源状语","说明推广史信息由谁提出","a historian为Daniel Cook的身份。","据儿童消费史研究者丹尼尔·库克所说",[child("a historian of childhood consumerism","同位语名词短语","身份说明","Daniel Cook","研究者是信息来源，不是服装制造商。")]),c("it","subject","代词","主语","回指toddler称谓或阶段概念","被推广的是术语，非这个研究者本人。","这个概念"),c("was popularised","predicate","一般过去时被动","谓语","说明概念被推广","施事由by短语给出。","被推广开来"),c("as a marketing trick","complement","as介词短语","推广性质补足语","was popularised","把推广定性为营销手段。","作为一种营销花招"),c("by clothing manufacturers","modifier","by介词短语","被动施事状语","was popularised","制造商是推广者。","由服装制造商"),c("in the 1930s","modifier","时间介词短语","时间状语","was popularised","the 1930s表示20世纪30年代，没有具体某一天。","在20世纪30年代")],clauses:[],focus:"according to说明信息来源，by说明实际推广者，两者不可调换。",question:"Daniel Cook与clothing manufacturers承担相同角色吗？",evidence:"according to Daniel Cook, a historian of childhood consumerism, it was popularised as a marketing trick by clothing manufacturers",answer:"不是。Cook提供消费史信息，服装制造商是被动句明确写出的推广施事。不能把研究者身份当成影响儿童发展观念的实际原因。"},
  15:{parts:[c("Trade publications","subject","名词短语","主语","counselled的施事","行业刊物是建议来源。","行业刊物"),c("counselled","predicate","一般过去时及物动词","谓语","说明提出建议","英式过去式双写l。","建议"),c("department stores","object","名词短语","接受对象宾语","counselled","百货商店是建议接受者。","百货商店"),c("that, in order to increase sales, they should create a \"third stepping stone\" between infant wear and older kids' clothes","object","that内容从句","建议内容宾语","counselled","they回指商店，目的短语不另成有时态的从句。","为了增加销售额，应当在婴儿装与较大孩子服装之间创造一个‘第三块踏脚石’",[child("in order to increase sales","目的不定式短语","目的状语","they should create","说明目标，并非已经增长的结果。"),child("a \"third stepping stone\" between infant wear and older kids' clothes","名词短语","从句宾语","create","比喻新增中间市场层级。",[child("between infant wear and older kids' clothes","介词短语","分类范围限定","third stepping stone","两端都明确给出，wear在这里为服装名词。")])])],clauses:[cl("that, in order to increase sales, they should create a \"third stepping stone\" between infant wear and older kids' clothes","内容宾语从句","that","给出counselled的建议内容","they","should create",[["宾语","a \"third stepping stone\" between infant wear and older kids' clothes"]],"先译接受建议的商店，再加增销目的和新增中间分类。")],focus:"在两类服装之间再加一层才是建议重点，不是只关注已有两端。",question:"they指谁，third stepping stone又是什么？",evidence:"they should create a \"third stepping stone\" between infant wear and older kids' clothes",answer:"they指department stores；踏脚石是比喻，表示在婴儿与较大儿童之间新增幼儿市场层级，目的是增加销售。不能把它译成第三件实体商品。"},
  16:{parts:[c("It was","predicate","强调句框架","强调结构起点","与that呼应","不把It当成toddler的指代。","只有……之后才（合并强调结构）"),c("only after \"toddler\" became a common shoppers' term","modifier","被强调的时间从句","时间焦点","限定evolved发生的先决时间","only突出先成购物术语，后被当作发展阶段。","只有在‘toddler’成为购物者常用术语之后"),c("that it evolved into a broadly accepted developmental stage","complement","强调结构命题部分","强调结构后项","与It was only after构成整体","此处it才回指toddler称谓，into引演变结果。","它才演变成一个被广泛接受的发展阶段",[child("a broadly accepted developmental stage","名词短语","介词into的宾语","evolved into","accepted为被接受的过去分词定语，broadly修饰accepted。")])],clauses:[cl("after \"toddler\" became a common shoppers' term","时间状语从句","after","构成被强调的时间范围","\"toddler\"","became",[["表语","a common shoppers' term"]],"先译术语普及，再译其被当成发展阶段。"),cl("that it evolved into a broadly accepted developmental stage","强调结构命题部分","that（强调连接）","与It was only after呼应","it","evolved",[["结果补足语","into a broadly accepted developmental stage"]],"合译只有在前一事件之后，它才演变为后者。")],focus:"术语的消费使用在先，发展阶段的社会接受在后；不能把顺序反过来。",question:"两个It/it分别在做什么？",evidence:"It was only after \"toddler\" became a common shoppers' term that it evolved",answer:"句首It仅构成强调框架，that后it才指toddler称谓。only after把购物术语先普及的时间关系凸显出来，并非说科学研究先定义好阶段才命名。"},
  17:{parts:[c("Splitting kids, or adults, into ever-tinier categories","subject","动名词短语含插入补充","主语","has proved的主语","整个划分类别行为作单数主语；or adults补充也适用于成人。","把儿童或者成年人分成越来越细的类别",[child("kids, or adults","名词及插入选择说明","动名词宾语","Splitting","被分类的人群。"),child("into ever-tinier categories","介词短语","分类结果补足语","Splitting","ever-tinier表示不断更小的类别，不是较早年代。")]),c("has proved","predicate","现在完成时系动词用法","谓语","说明该行为显示出的效果","prove此处为证明是、结果表明是，后接表语。","已被证明是"),c("a sure-fire way to boost profits","complement","名词短语含不定式定语","表语","说明Splitting行为的作用","sure-fire评价可靠，to boost解释这种办法用于什么。","一种能可靠增加利润的办法",[child("to boost profits","不定式短语","后置定语","way","profit是利润，与sales销售额并非同一指标。")])],clauses:[],focus:"整个分类行为作主语，proved后是表语；利润增长不应改写为销量必增。",question:"has为什么不跟kids或adults用复数？",evidence:"Splitting kids, or adults, into ever-tinier categories has proved",answer:"主语是整个动名词短语Splitting...，说一种行为，按单数看待。kids/adults只是splitting的宾语，不能决定has的形式。",natural:"把儿童或成年人划分为越来越细的类别，已被证明是增加利润的一种可靠办法。"},
  18:{parts:[c("And","connector","并列连词","补充连接","接市场细分的盈利逻辑","继续举最容易细分的一个维度。","而且"),c("one of the easiest ways to segment a market","subject","数量名词短语含不定式定语","主语","is的主语","中心one为单数，ways为of内部复数；to segment说明方法目标。","细分市场最容易的办法之一",[child("to segment a market","不定式短语","后置定语","ways","没有独立限定谓语，不列作从句。")]),c("is","predicate","系动词","谓语","连接one与具体办法","单数由one决定。","是"),c("to magnify gender differences – or invent them where they did not previously exist","complement","不定式短语含并列动作和状语从句","表语","给出市场细分办法","invent与magnify共享to；them与they均回指gender differences。","夸大性别差异——或者在差异原先不存在的情形中创造它们",[child("gender differences","名词短语","magnify的宾语","magnify","被夸大的对象是性别差异。"),child("invent them where they did not previously exist","动词短语含状语从句","并列不定式动作","与to magnify并列，共享to","破折号引入更尖锐的选择。",[child("where they did not previously exist","地点或情形状语从句","情形状语","invent","没有名词先行词；说明在哪种情形下人为制造差异。")])])],clauses:[cl("where they did not previously exist","地点或情形状语从句","where","限定invent差异的情形","they","did not exist",[],"译为在这些差异原先并不存在的情形中，不能把它误作修饰名词的定语。")],focus:"where修饰制造差异的行为，them/they都指差异；不是宣布一切性别差异都不存在。",question:"where前没有地点名词，它还应叫定语从句吗？",evidence:"invent them where they did not previously exist",answer:"这里where从句直接限定invent的情形，属于地点或情形状语。原句允许在本无差异的地方制造差异，并没有断言所有性别差异都是虚构。"},
};
export function upgradePassage2012P2Sentence(source:SentenceAnalysis):SentenceAnalysis{
  const review=reviews[source.number];if(!review)throw new Error(`2012 Text2缺人工复核：${source.id}`);
  const {chunks:_legacy,...draft}=source;const components=review.parts.map(p=>p.component);
  const sentence=withReviewedSyntax({...draft,natural:review.natural??source.natural,beginnerSyntax:{components,clauses:review.clauses,reading:{focus:review.focus,questions:[{question:review.question,evidence:review.evidence,answer:review.answer}]}},layers:components.map(p=>({label:p.function,text:`${p.text}：${p.explanation}`})),grammar:components.map(p=>`${p.form}；${p.explanation}`),translationNotes:review.notes,practice:passage2012P2Practice[source.id]},review.parts.map(p=>p.color));
  return {...sentence,translationAlignment:sentence.chunks.map((chunk,i)=>({english:chunk.text,chinese:review.parts[i].chinese}))};
}
