import type { BeginnerClauseDetail, BeginnerSyntaxComponent, QuestionAnalysis, SentenceAnalysis, SyntaxVisualRole } from "./data";
import { withReviewedSyntax } from "./reviewed-syntax";
const c = (text: string, color: SyntaxVisualRole, form: string, fn: string, modifies: string, explanation: string, children?: BeginnerSyntaxComponent[]) => ({ component: { text, form, function: fn, modifies, explanation, children }, color });
const child = (text: string, form: string, fn: string, modifies: string, explanation: string): BeginnerSyntaxComponent => ({ text, form, function: fn, modifies, explanation });
const cl = (text: string, type: string, marker: string, role: string, subject: string, predicate: string, details: Array<[string,string]>, translationOrder: string): BeginnerClauseDetail => ({ text,type,marker,role,subject,predicate,predicateDetails:details.map(([fn,value])=>({function:fn,text:value})),translationOrder });
const a = (id: string, text: string, trunk: string, parts: ReturnType<typeof c>[], meaning: string, focus: string, clauses: BeginnerClauseDetail[] = [], textKind: "sentence" | "phrase" = "sentence"): SentenceAnalysis => withReviewedSyntax({ id,number:0,text,trunk,textKind,beginnerSyntax:{components:parts.map(p=>p.component),clauses},layers:[{label:"读题关键",text:focus}],grammar:[focus],literal:meaning,natural:meaning,logic:"先确定本项实际命题；选入与否另看原文证据，语言成立不等于答案成立。",phrases:[] },parts.map(p=>p.color));
const p = (id: string,text: string,trunk: string,parts: ReturnType<typeof c>[],meaning: string,focus: string) => a(id,text,trunk,parts,meaning,focus,[],"phrase");

export const passage2012P3QuestionAnalysis:Record<number,QuestionAnalysis>={
31:{prompt:a("201231-prompt-analysis","It can be learned from Paragraph 1 that the biotech companies would like____.","It can be learned that companies would like____",[c("It","subject","形式主语","主语","对应后置that命题","不指某个公司或基因。"),c("can be learned","predicate","情态被动结构","谓语","表示可从文本得知","learn在此为得知、推知。"),c("from Paragraph 1","modifier","介词短语","来源状语","can be learned","证据限定第一段。"),c("that the biotech companies would like____","subject","待补that内容从句","后置主语从句","对应It","would like后接某对象和希望其发生的非限定动作，由选项补足。")],"可以从第一段得知，生物技术企业希望……。","would like询问期望，不是已发生事实。",[cl("that the biotech companies would like____","后置主语从句（待补全）","that","对应形式主语It","the biotech companies","would like",[],"先确定企业的愿望，再补对象及动作。")]),options:{
A:p("201231-A-analysis","genes to be patentable","genes to be patentable",[c("genes","object","复数名词","待接like的对象","接would like","genes同时为to be的逻辑主语。"),c("to be patentable","complement","不定式短语","对象状态补足语","genes","patentable为可获专利的表语，没有独立时态。")],"基因能够获得专利。","would like genes to be...中基因是希望处于某状态的对象，不伪造独立完整句。"),
B:p("201231-B-analysis","the BIO to issue a warning","the BIO to issue a warning",[c("the BIO","object","机构名词短语","待接like的对象","接would like","同时是issue的逻辑施事。"),c("to issue a warning","complement","不定式短语","对象动作补足语","the BIO","issue为发布动词，a warning为宾语。")],"BIO发布一项警告。","issue在这里不是议题名词，warning为警告，不等于assurance安抚保证。"),
C:p("201231-C-analysis","their executives to be active","their executives to be active",[c("their executives","object","所有格名词短语","待接like的对象","接would like","their回指题干企业，executives是其高管。"),c("to be active","complement","不定式系表短语","对象状态补足语","executives","active表示积极活跃，非焦躁不安。")],"它们的高管积极活跃。","active与agitated情绪义不同；选项说希望高管如此。"),
D:p("201231-D-analysis","judges to rule out gene patenting","judges to rule out gene patenting",[c("judges","object","复数名词","待接like的对象","接would like","法官为rule out的逻辑施事。"),c("to rule out gene patenting","complement","不定式动词短语","对象动作补足语","judges","rule out是排除，gene patenting为授予基因专利这一活动。")],"法官排除对基因授予专利。","rule out与rule that裁定内容结构不同，out改变动词关系。"),
}},
32:{prompt:a("201232-prompt-analysis","Those who are against gene patents believe that____.","Those believe that____",[c("Those who are against gene patents","subject","代词中心含定语从句","主语","believe的施事","Those指持某立场的一群人，由who限定。",[child("who are against gene patents","定语从句","后置定语","Those","who作are主语，against短语为立场表语。")]),c("believe","predicate","一般现在时","谓语","引出信念内容","要求归属反对者看法。"),c("that____","object","待补内容从句","宾语从句","believe的内容","选项提供完整命题，不能把作者声音混入。")],"反对基因专利的人认为……。","who先限定持反对立场者，that再引他们所相信的命题。",[cl("who are against gene patents","定语从句","who","修饰Those","who","are",[["表语","against gene patents"]],"合译为反对基因专利的人。"),cl("that____","宾语从句（待补全）","that","believe的内容","由选项提供","由选项提供",[],"接上选项完整命题。")]),options:{
A:a("201232-A-analysis","genetic tests are not reliable","genetic tests are not reliable",[c("genetic tests","subject","名词短语","主语","are reliable的评价对象","tests指基因检测，不是考试。"),c("are not","predicate","否定系动结构","谓语","否定可靠状态","not作用于reliable判断。"),c("reliable","complement","形容词","表语","说明tests可靠性","说结果或方法可信度，并非服务获得机会。")],"基因检测不可靠。","reliable与accessible在命题上不同，不能由检测受限推到不可靠。"),
B:a("201232-B-analysis","only man-made products are patentable","only man-made products are patentable",[c("only man-made products","subject","only限定的名词短语","主语","are patentable","only把可获专利的对象限于人造物，不说所有人造物都合格。"),c("are","predicate","系动词","谓语","连接products与资格属性","主系表关系。"),c("patentable","complement","形容词","表语","说明可专利性","-able为可以，非已获专利的patented。")],"只有人造产品才可能获得专利。","only A are B使A为B的必要条件，不可倒置为凡A均B。"),
C:a("201232-C-analysis","patents on genes depend much on innovation","patents depend on innovation",[c("patents on genes","subject","名词短语","主语","depend的主语","on genes限定专利对象。"),c("depend","predicate","一般现在时","谓语","表示依赖关系","depend on不是影响或抑制关系。"),c("much","modifier","程度副词","程度状语","depend","表示很大程度。"),c("on innovation","complement","介词短语","依赖对象补足语","depend","innovation为条件或所依赖因素。")],"基因专利很大程度上取决于创新。","两处on分别限定专利对象和引依赖因素；与专利抑制创新不是同一句话。"),
D:a("201232-D-analysis","courts should restrict access to genetic tests","courts should restrict access",[c("courts","subject","复数名词","主语","should restrict的施事","把实施限制的主体设为法院。"),c("should restrict","predicate","情态动词结构","谓语","表达应该限制的建议","规范主张，不是描述既有后果。"),c("access to genetic tests","object","名词短语","宾语","restrict","to引可获得服务，access为机会不是地点入口。")],"法院应该限制人们获得基因检测的机会。","应当限制与批评已经存在的限制方向相反。"),
}},
33:{prompt:a("201233-prompt-analysis","According to Hans Sauer, companies are eager to win patents for____.","companies are eager to win patents",[c("According to Hans Sauer","modifier","来源介词短语","来源状语","后面命题","须定位Hans Sauer的发言及邻句解释。"),c("companies","subject","复数名词","主语","are eager的对象","企业是愿望主体。"),c("are","predicate","系动词","谓语","连接companies与eager","表达意愿状态。"),c("eager to win patents for____","complement","形容词短语含不定式","表语","说明companies的愿望","to win补充渴望做什么，for后由动名词选项给专利对象。",[child("to win patents for____","不定式短语","内容补足语","eager","不把eager当作已经获批。")])],"据Hans Sauer说，企业急切希望为……取得专利。","for后接动作名词化的成果对象；研究对象与用途须区分。"),options:{
A:p("201233-A-analysis","discovering gene interactions","discovering gene interactions",[c("discovering","predicate","动名词","待接for的非限定动作中心","接题干for","企业希望取得专利的发现活动。"),c("gene interactions","object","名词短语","动名词宾语","discovering","gene限定interaction类型，派生名词对应interact。")],"发现基因相互作用。","interact到interactions是词性转换，保留原研究关系。"),
B:p("201233-B-analysis","establishing disease correlations","establishing disease correlations",[c("establishing","predicate","动名词","待接for的非限定动作中心","接题干for","表示确立或建立关联。"),c("disease correlations","object","名词短语","动名词宾语","establishing","disease把关联对象改为疾病，需与原文gene研究区分。")],"确立疾病关联。","disease作名词定语，不能略过它将本项直接等同原文所有correlations。"),
C:p("201233-C-analysis","drawing pictures of genes","drawing pictures",[c("drawing","predicate","动名词","待接for的非限定动作中心","接题干for","draw pictures是绘图，不是draw conclusions推论。"),c("pictures of genes","object","名词短语","动名词宾语","drawing","of genes给图像内容，整体为字面绘图。")],"绘制基因图像。","选项按字面图画理解，与串联证据的比喻应分开。"),
D:p("201233-D-analysis","identifying human DNA","identifying human DNA",[c("identifying","predicate","动名词","待接for的非限定动作中心","接题干for","表示识别或鉴定。"),c("human DNA","object","名词短语","动名词宾语","identifying","human限定DNA来源，没有表达多个基因如何互动。")],"鉴定人类DNA。","识别对象与研究对象之间的关系不同。"),
}},
34:{prompt:a("201234-prompt-analysis",'By saying "Each meeting was packed" (Line 4, Para. 6), the author means that ____.',"the author means that ____",[c('By saying "Each meeting was packed" (Line 4, Para. 6)',"modifier","by加动名词与引文","方式状语","means","引文为完整主系表，括号限定第六段第四行。",[child('"Each meeting was packed"',"被引用完整分句","saying的内容","saying","meeting为主语，was系动词，packed为状态。")]),c("the author","subject","名词短语","主语","means的施事","询问作者借细节表达的意思。"),c("means","predicate","一般现在时","谓语","引出解释内容","means为mean三单动词，不是名词手段。"),c("that ____","object","待补内容从句","宾语从句","means的内容","四选项均提供完整命题。")],"作者说‘每个会议都满座’意在说明……。","深层含义需要联读会议主题，不能只翻译packed。",[cl("Each meeting was packed","引文中的完整分句","直接引文","saying所引的内容","Each meeting","was",[["表语","packed"]],"先理解满座事实，再读作者借事实说明什么。"),cl("that ____","宾语从句（待补全）","that","means的内容","由选项提供","由选项提供",[],"以that接选项的完整命题。")]),options:{
A:a("201234-A-analysis","the supreme court was authoritative","the supreme court was authoritative",[c("the supreme court","subject","机构名词短语","主语","was的主语","原卷小写保留，指最高法院。"),c("was","predicate","系动词过去时","谓语","连接法院与评价","讨论权威。"),c("authoritative","complement","形容词","表语","说明court的性质","有权威的，不是专制的authoritarian。")],"最高法院具有权威。","满座会议和法院权威是两个命题，需额外证据才能联系。"),
B:a("201234-B-analysis","the BIO was a powerful organisation","the BIO was a powerful organisation",[c("the BIO","subject","机构名称","主语","was的主语","组织是评价对象。"),c("was","predicate","系动词过去时","谓语","连接BIO与身份评价","主系表。"),c("a powerful organisation","complement","名词短语","表语","说明BIO性质","powerful限定组织的实力影响，非会议具体主题。")],"BIO是一个强大的组织。","有能力举办会议不直接等于本文据满席证明权力强大。"),
C:a("201234-C-analysis","gene patenting was a great concern","gene patenting was a great concern",[c("gene patenting","subject","动名词性名词短语","主语","was的主语","授予基因专利这一议题，而非一个基因动作施事。"),c("was","predicate","系动词过去时","谓语","连接议题与关切评价","主系表。"),c("a great concern","complement","名词短语","表语","说明gene patenting地位","concern为重要关注事项，不只个人焦虑感。")],"基因专利是一个重大关切。","从特定培训内容加满席事实概括议题受到重视。"),
D:a("201234-D-analysis","lawyers were keen to attend conventions","lawyers were keen",[c("lawyers","subject","复数名词","主语","were keen的对象","选项泛称律师这一群体。"),c("were","predicate","系动词过去时","谓语","连接lawyers与keen","表达热衷状态。"),c("keen to attend conventions","complement","形容词短语含不定式","表语","说明律师喜好","to attend给热衷动作，conventions泛称大会。")],"律师热衷参加大会。","没有专利主题限定，范围比原文具体场次热度更广。"),
}},
35:{prompt:a("201235-prompt-analysis","Generally speaking, the author's attitude toward gene patenting is ____.","the author's attitude is ____",[c("Generally speaking","modifier","固定分词评注","概括范围状语","整句提问","总体而言，要求考虑全文而非一处引语。"),c("the author's attitude toward gene patenting","subject","所有格名词短语","主语","is的主语","author's限定谁的态度，toward引态度对象。",[child("toward gene patenting","介词短语","态度对象补足语","attitude","针对基因专利问题。")]),c("is","predicate","系动词","谓语","连接attitude和选项形容词","四项形容词作表语。"),c("____","complement","待补形容词","表语","is","只补态度性质，不补新事实。")],"总体而言，作者对基因专利的态度是……。","作者声音与被引人物声音必须分开。"),options:{
A:p("201235-A-analysis","critical","critical",[c("critical","complement","形容词","待接系动词的表语","接is说明attitude","此题态度语境为批评的，不是关键的。")],"批评的。","全文是否由作者直接评价缺陷，不能只看Critics发言。"),
B:p("201235-B-analysis","supportive","supportive",[c("supportive","complement","形容词","待接系动词的表语","接is说明attitude","表示支持态度，不等于只是报道支持者。")],"支持的。","需要作者认可证据，不能把高管的blessing移给作者。"),
C:p("201235-C-analysis","scornful","scornful",[c("scornful","complement","形容词","待接系动词的表语","接is说明attitude","轻蔑鄙视，情绪强于理性批评。")],"轻蔑的。","须有作者鄙视嘲弄的语气，非只出现争议或焦虑。"),
D:p("201235-D-analysis","objective","objective",[c("objective","complement","形容词","待接系动词的表语","接is说明attitude","在态度题为客观的，不是目标名词。")],"客观的。","平衡报道不同来源并保留不确定性可支持这种态度。"),
}},
};
