import type { Question } from "./data";
import { sentenceFactory, segment, clause } from "./2011-content-helpers";
const sentence = sentenceFactory("2012-p4");
export const passage2012P4Sentences = [
  sentence(1, [segment("The great recession may be over, ", "predicate", "主语加情态系表", "第一分句", "说明经济衰退可能结束", "may表示可能，over为结束，未说作者确信一切经济问题已过去。"), segment("but this era of high joblessness is probably beginning.", "connector", "but转折分句", "第二分句", "把失业时期与衰退期区分", "of high joblessness限定era；probably保留可能性，beginning表示才开始。")], "The great recession may be over, but this era is beginning.", "大衰退可能已经结束，但高失业率的时代很可能才刚开始。", "经济大衰退或许过去了，高失业时代却可能刚刚到来。", "区分经济周期与社会后果的持续时间，开启全文长期影响议题。", ["this era of high joblessness"]),
  sentence(2, [segment("Before it ends, ", "condition", "before时间从句", "时间状语", "限定主句变化发生在何时", "it回指高失业时期，不能错指已经结束的事件。"), segment("it will likely change the life course and character of a generation of young adults.", "predicate", "主句将来时主谓宾", "主句", "it仍指高失业时期", "life course为人生轨迹，character为性格；of a generation说明受影响群体。")], "it will change the life course and character.", "在它结束之前，它很可能改变一代年轻成年人的人生轨迹与性格。", "等到这一时期结束时，一代年轻人的人生道路和性格很可能都已经改变。", "将高失业后果具体落到年轻一代。", ["the life course and character"], [clause("Before it ends", "时间状语从句", "Before", "限定变化在高失业时期结束前发生", "it", "ends", "无宾语", "先译在这一时期结束之前，再译可能改变的一代人。")]),
  sentence(3, [segment("And ultimately, ", "connector", "承接连词加时间结果副词", "篇章推进", "从个人推向社会", "ultimately表最终，不等于立刻。"), segment("it is likely to reshape our politics, our culture, and the character of our society for years.", "predicate", "be likely to结构及并列宾语", "主句", "说明高失业时期长期影响", "reshape为重新塑造；三个宾语为政治、文化、社会特性；for years限定影响持续多年。")], "it is likely to reshape our politics, our culture, and the character of our society.", "最终，它很可能在多年间重塑我们的政治、文化和社会特性。", "最终，它还可能在此后多年里改变我们的政治、文化乃至整个社会的特质。", "提出贯穿全文的社会影响判断，同时用likely保留预测性质。", ["is likely to reshape"]),
  sentence(4, [segment("No one tries harder than the jobless ", "predicate", "否定主语加比较级", "主句比较结构", "强调失业者寻找好处的努力最大", "No one ... harder than相当于没有谁比失业者更努力，不能译成无人努力。"), segment("to find silver linings in this national economic disaster.", "modifier", "不定式目的及范围介词短语", "努力的目的", "说明tries要做什么", "silver linings比喻困境中的亮点，economic disaster限定逆境背景。")], "No one tries harder than the jobless.", "没有谁比失业者更努力地在这场全国性经济灾难中寻找光明的一面。", "面对这场全国性的经济灾难，最努力寻找一线希望的，恰恰是失业者自己。", "承认人们寻找积极意义的努力，对应36题D。", ["find silver linings"], [clause("than the jobless", "比较从句省略形式", "than", "作为harder的比较对象", "the jobless", "省略try", "不及物谓语，其目的由后文不定式说明", "还原为比失业者努力，再与No one合译为失业者最努力。")]),
  sentence(5, [segment("Many said ", "predicate", "省略名词的代词主语加谓语", "主句", "Many指许多受访失业者", "这是转述他们的看法，并非作者已证明失业整体有益。"), segment("that unemployment, while extremely painful, had improved them in some ways: ", "object", "that宾语从句内嵌省略让步从句", "say的内容", "unemployment为从句主语，them指失业者", "while painful相当于虽然失业极痛苦；in some ways限制改善范围。"), segment("they had become less materialistic and more financially prudent; ", "object", "冒号后第一解释分句", "改善的第一方面", "they回指受访失业者", "less与more是两个方向相反的程度变化，financially只限定prudent。"), segment("they were more aware of the struggles of others.", "object", "第二解释分句", "改善的第二方面", "说明对他人困境的认识", "aware of为意识到；struggles指艰辛，不是人们互相争斗。")], "Many said that unemployment had improved them in some ways.", "许多人说，失业虽极其痛苦，却在某些方面让他们变好：他们不那么物质至上，经济上更谨慎，也更了解他人的艰辛。", "不少失业者表示，失业虽然痛苦，却也让自己少了些物质欲望、花钱更谨慎，更能体会别人的难处。", "列出受访者感到的有限好处，不把其经验推成整个社会净收益。", ["in some ways", "less materialistic", "more financially prudent", "aware of the struggles of others"], [clause("that unemployment, while extremely painful, had improved them in some ways", "宾语从句", "that", "作said宾语", "unemployment", "had improved", "them；in some ways为范围", "先说明这是一部分人的说法，再译有限改善。"), clause("while extremely painful", "让步状语从句的省略形式", "while", "说明失业虽痛苦仍可有部分改善", "省略unemployment/it", "省略was", "extremely painful为表语", "先译虽然失业十分痛苦，不能把while当同时。")]),
  sentence(6, [segment("In limited respects, perhaps ", "modifier", "范围介词短语加可能性副词", "范围与语气限定", "共同限定主句正面判断", "limited限制适用方面，perhaps限制确定程度，两者不可省。"), segment("the recession will leave society better off.", "predicate", "主谓宾及宾语补足语", "主句", "说明社会可能处于何种结果状态", "leave society better off中better off为结果补语，表示境况更好。")], "the recession will leave society better off.", "在有限的方面，衰退也许会让社会的境况更好。", "或许，在某些有限方面，衰退确实能让社会有所改善。", "作者谨慎承认好处，为转折留下明确限制。", ["In limited respects", "leave society better off"]),
  sentence(7, [segment("At the very least, ", "modifier", "程度下限介词短语", "评注", "限定作者能确认的益处", "very加强至少，不是最大程度。"), segment("it has awoken us from our national fever dream of easy riches and bigger houses, ", "predicate", "现在完成时主谓宾及from来源", "第一并列谓语", "it指衰退，us为公众", "awoken为awake分词；fever dream比喻不切实际的狂热幻想。"), segment("and put a necessary end to an era of reckless personal spending.", "connector", "and连接第二谓语", "第二并列谓语", "与has awoken共用主语it及助动词has", "put an end to为终结；reckless修饰个人消费方式，necessary为作者评价。")], "it has awoken us and put a necessary end to an era.", "至少，衰退把我们从轻松发财、住更大房子的全民狂热梦中唤醒，并必要地结束了不顾后果的个人消费时代。", "至少，这场衰退让人们不再沉迷于轻易致富、换大房子的狂热幻想，也给盲目挥霍的消费时代画上了必要的句号。", "正面后果为反思生活方式，对应37题D；不等于实现全国梦想。", ["At the very least", "awoken us from our national fever dream", "put a necessary end to"]),
  sentence(8, [segment("But for the most part, ", "connector", "转折连词及总体范围习语", "从局部益处转向总体判断", "限定benefits的评估范围", "for the most part表示总体上，与前文limited respects对照。"), segment("these benefits seem thin, uncertain, and far off.", "predicate", "主系表含三项并列评价", "主句", "these回指上段益处", "thin是微薄，uncertain为不确定，far off为尚遥远；seem仍保留判断语气。")], "these benefits seem thin, uncertain, and far off.", "但总体而言，这些益处似乎微薄、不确定，而且遥远。", "但从整体看，这些好处既有限，又没把握，可能还要很久才看得见。", "关键转折：承认局部正面不等于对衰退持乐观态度。", ["for the most part", "far off"]),
  sentence(9, [segment("In The Moral Consequences of Economic Growth, ", "modifier", "书名介词短语", "论据来源状语", "说明argues的出处", "书名整体为《经济增长的道德后果》，不是说作者在经济增长内部争论。"), segment("the economic historian Benjamin Friedman argues ", "predicate", "主语名词与人名同位加谓语", "主句", "标明论断提出者", "Friedman为经济史学者，后面的说法属于他的历史概括。"), segment("that both inside and outside the U.S., ", "object", "that宾语从句引导及并列地域状语", "从句范围", "限定以下历史经验适用地区", "both ... and既包括美国国内也包括国外。"), segment("lengthy periods of economic stagnation or decline have almost always left society more mean-spirited and less inclusive, ", "object", "从句主谓宾补结构", "第一个并列谓语", "社会为left的宾语", "almost always并非每次无例外；两个形容词说明社会变刻薄且更不包容。"), segment("and have usually stopped or reversed the advance of rights and freedoms.", "connector", "并列完成时谓语", "第二组并列谓语", "与have left共用lengthy periods主语", "stopped或reversed表示停滞甚至倒退，usually保留通常而非必然。")], "the economic historian Benjamin Friedman argues that lengthy periods have left society more mean-spirited and less inclusive, and have stopped or reversed the advance of rights and freedoms.", "经济史学者本杰明·弗里德曼在《经济增长的道德后果》中指出，无论美国内外，长期停滞或衰退几乎总会使社会更刻薄、更不包容，通常还会阻碍甚至逆转权利和自由的进步。", "本杰明·弗里德曼在《经济增长的道德后果》中指出，国内外历史显示，经济长期停滞或下滑几乎总会使社会更冷酷、更排斥异己，通常还会让权利与自由的发展停步甚至倒退。", "引用历史论据说明社会性负面影响，定位38题B；保留频率限定。", ["both inside and outside the U.S.", "left society more mean-spirited and less inclusive", "the advance of rights and freedoms"], [clause("that both inside and outside the U.S., lengthy periods of economic stagnation or decline have almost always left society more mean-spirited and less inclusive, and have usually stopped or reversed the advance of rights and freedoms", "宾语从句", "that", "作argues宾语", "lengthy periods of economic stagnation or decline", "have left / have stopped or reversed", "society加宾补；the advance of rights and freedoms", "先译长期衰退的主语，再分别译社会气质和权利进步的两类结果。")]),
  sentence(10, [segment("Anti-immigrant sentiment typically increases, ", "predicate", "主谓结构含频率副词", "主句", "举社会态度的例子", "anti-表反对，sentiment为情绪倾向，typically表示通常。"), segment("as does conflict between races and classes.", "modifier", "as引同样情况的倒装分句", "补充并列变化", "conflict是倒装分句主语", "does代替increases，between races and classes限定冲突群体。")], "Anti-immigrant sentiment increases, as does conflict.", "反移民情绪通常会增强，种族和阶层之间的冲突也一样。", "反移民情绪往往升温，种族、阶层之间的冲突也会加剧。", "用平行增长证明38题不是减少冲突或推进自由。", ["Anti-immigrant sentiment", "between races and classes"], [clause("as does conflict between races and classes", "as相似情况从句（倒装）", "as", "表示冲突也以同样方式增加", "conflict between races and classes", "does（代替increases）", "不及物，无宾语", "还原为冲突也增加，不能把as译成因为。")]),
  sentence(11, [segment("Income inequality usually falls during a recession, ", "predicate", "主谓结构含频率和时间状语", "第一分句", "说明通常规律", "falls表示差距缩小，不是收入本身下降。"), segment("but it has not shrunk in this one.", "connector", "转折完成时否定", "第二分句", "it指income inequality，one指recession", "shrink缩小，has not否定当前这次衰退符合通常规律。")], "Income inequality falls, but it has not shrunk.", "收入不平等在衰退期间通常会减少，但这次却没有缩小。", "一般而言，经济衰退会缩小收入差距，但这一次并没有。", "区分通常情况与本次特例，不能反向读为此次已经更平等。", ["Income inequality"]),
  sentence(12, [segment("Indeed, this period of economic weakness ", "subject", "确认副词加名词短语", "主语", "指当前经济疲弱时期", "Indeed加强下文证据推进，而不是引相反情况。"), segment("may reinforce class divides, and decrease opportunities to cross them ", "predicate", "情态动词及并列动宾", "主句谓语", "说明阶层差距和流动机会", "may统领reinforce与decrease，to cross them修饰opportunities，them指class divides。"), segment("– especially for young people.", "modifier", "破折号补充人群范围", "重点对象", "限定机会减少影响谁", "especially突出青年，不排除其他群体受影响。")], "this period may reinforce class divides, and decrease opportunities.", "这段经济疲弱期实际上可能强化阶层分野，并减少跨越它们的机会，尤其对年轻人如此。", "事实上，经济低迷可能加深阶层鸿沟、压缩跨越阶层的机会，年轻人受到的影响尤为突出。", "从总体社会情绪转入机会不平等，铺垫大学毕业生研究。", ["class divides", "opportunities to cross them"]),
  sentence(13, [segment("The research of Till Von Wachter, the economist at Columbia University, suggests ", "predicate", "主语名词加研究者及同位说明", "主句", "引研究证据来源", "research为中心主语；the economist同位解释研究者，不解释research。"), segment("that not all people graduating into a recession see their life chances dimmed: ", "object", "that宾语从句含分词定语与宾补", "研究结论总述", "not all限定受损群体并非全部", "graduating为people定语；see chances dimmed是看到机会被削弱，不是他们主动使机会变暗。"), segment("those with degrees from elite universities catch up fairly quickly ", "object", "冒号第一解释分句", "说明优势群体", "those指精英大学毕业生", "with degrees限定学历来源，fairly修饰quickly表示较快。"), segment("to where they otherwise would have been ", "modifier", "to介词加where名词性从句", "追赶的目标", "限定catch up的到达状态", "would have been为过去虚拟结果，参照未遭衰退时的反事实位置。"), segment("if they had graduated in better times; ", "condition", "if过去虚拟条件从句", "反事实条件", "说明would have been成立条件", "had graduated表示与实际毕业时局不同的假设。"), segment("it is the masses beneath them that are left behind.", "object", "it is ... that强调句", "第二解释分句", "突出真正被落下的大多数人", "the masses beneath them与精英毕业生对照；that后的are与masses一致，it非普通指代。")], "The research suggests that not all people see their life chances dimmed.", "哥伦比亚大学经济学家蒂尔·冯·瓦赫特的研究表明，并非所有在衰退时毕业的人，人生机会都会黯淡：精英大学毕业生较快就能赶上假如在更好时期毕业本应达到的位置；真正被甩下的是处于他们之下的大多数人。", "哥伦比亚大学经济学家蒂尔·冯·瓦赫特发现，衰退期毕业并不让所有人都同样失去机会。名校毕业生较快就能追上经济景气时毕业本来可能达到的发展水平；被落在后面的，是条件不如他们的广大普通人。", "解释机会差距；名校生追赶的是自身反事实轨迹，不是有经验雇员。定位39题D。", ["not all people", "catch up fairly quickly", "it is the masses beneath them that are left behind"], [
    clause("that not all people graduating into a recession see their life chances dimmed", "宾语从句", "that", "作suggests宾语，冒号后另举两类人说明", "not all people graduating into a recession", "see", "their life chances为宾语，dimmed为被动结果宾补", "先译并非所有人都，再译人生机会受损，不译成所有人都不。"),
    clause("where they otherwise would have been if they had graduated in better times", "where名词性从句", "where", "作to的宾语，说明追赶到的状态", "they", "would have been", "where表示反事实位置或发展状态", "译为如果在景气时期毕业本来会达到的位置。"),
    clause("if they had graduated in better times", "虚拟条件状语从句", "if", "限定would have been的假设条件", "they", "had graduated", "in better times为时间状语", "先译与事实不同的好时机毕业，再回到本可达到的发展水平。"),
    clause("that are left behind", "强调句的that分句", "that", "与it is构成强调结构，强调the masses beneath them", "被强调的the masses beneath them", "are left", "behind为结果副词", "译为真正被落下的是普通大众，不把it作独立有意义的主语。"),
  ]),
  sentence(14, [segment("In the Internet age, ", "modifier", "时间背景介词短语", "时代状语", "限定easy的观察背景", "网络时代使情绪更容易被看见，不等于首次产生该情绪。"), segment("it is particularly easy to see the resentment ", "predicate", "形式主语及不定式真正主语", "主句", "评价看到社会怨愤的难易", "it为形式主语，to see说明被评价的动作。"), segment("that has always been hidden within American society.", "modifier", "that定语从句含完成时被动", "定语", "修饰resentment", "has always been hidden为一直潜藏，within说明美国社会内部。")], "it is easy to see the resentment.", "在互联网时代，尤其容易看到美国社会中一直隐藏的怨愤。", "到了互联网时代，美国社会深处一直潜藏的怨愤变得格外容易察觉。", "区分观察到既有情绪与准确判断社会长期变化的难度。", [], [clause("that has always been hidden within American society", "定语从句", "that", "修饰resentment", "that", "has been hidden", "within American society为范围", "译为一直隐藏在美国社会内部的怨愤。")]),
  sentence(15, [segment("More difficult, in the moment, ", "object", "比较级表语前置加时间插入语", "前置表语", "评价后面discerning动作", "more difficult与上句easy对照；in the moment为当下。"), segment("is discerning precisely ", "predicate", "系动词加动名词主语起点", "倒装系表结构", "真正主语为discerning及其宾语", "正常语序可理解为辨明影响更难，但主干必须仍沿原文词序。"), segment("how these lean times are affecting society's character.", "object", "how宾语从句", "discerning的宾语", "询问困难时期的具体影响方式", "lean比喻经济拮据，不是身体苗条；precisely强调准确判断。")], "More difficult is discerning how these lean times are affecting society's character.", "在眼下，更难的是准确辨明这些艰难时期正在怎样影响社会的特性。", "此刻更难看清的是，这段经济困境究竟在怎样改变社会的气质。", "说明影响方向与具体形式仍待观察，不否认影响本身存在。", ["these lean times"], [clause("how these lean times are affecting society's character", "宾语从句", "how", "作discerning宾语", "these lean times", "are affecting", "society's character", "先译困境如何影响社会，再译目前很难精确辨明。")]),
  sentence(16, [segment("In many respects, the U.S. was more socially tolerant ", "predicate", "范围状语加主系表比较级", "第一分句", "评价进入衰退时的社会状态", "in many respects限定多个方面，不是所有方面。"), segment("entering this recession than at any time in its history, ", "modifier", "现在分词时间背景加省略比较从句", "时间与比较范围", "entering逻辑主语U.S.；than对比此前历史", "进入本次衰退时的美国较以往更包容，不说衰退造成这一优势。"), segment("and a variety of national polls on social conflict since then have shown mixed results.", "connector", "and并列主谓宾", "第二分句", "报告随后民调的复杂结果", "since then从进入衰退算起；mixed是结果不一致或好坏参杂，不是全负面。")], "the U.S. was more socially tolerant, and a variety of national polls have shown mixed results.", "在许多方面，美国进入本次衰退时比其历史上任何时候都更包容社会差异，而此后有关社会冲突的全国民调给出了不一致的结果。", "美国进入这次衰退时，在许多方面的社会包容度都高于以往；但此后围绕社会冲突进行的多种全国民调，结果并不一致。", "交代起点和混合证据，防止将影响方向过早断为纯负面或正面。", ["In many respects", "a variety of national polls", "mixed results"], [clause("than at any time in its history", "比较从句的省略形式", "than", "限定more tolerant的比较基准", "省略the U.S.", "省略was/had been", "at any time in its history为比较时间", "译为比此前历史上任何时期都更包容，省略部分只在解释中还原。")]),
  sentence(17, [segment("We will have to wait and see exactly ", "predicate", "主语加情态性结构和并列动词", "主句", "提出需要继续观察", "have to表示必要，wait and see是等待事态明朗，不是无所作为的政策建议。"), segment("how these hard times will reshape our social fabric.", "object", "how宾语从句", "see的宾语", "说明仍需观察的具体内容", "social fabric比喻社会关系与组织结构，how问具体方式而非是否。")], "We will have to wait and see how these hard times will reshape our social fabric.", "我们将不得不等待观察，这些艰难时光究竟会怎样重塑我们的社会结构。", "经济困境到底会如何改变社会关系与结构，还需要时间来观察。", "仍不明确的是怎样改变，为最后一句确定会改变作对照。", ["wait and see", "our social fabric"], [clause("how these hard times will reshape our social fabric", "宾语从句", "how", "作see宾语", "these hard times", "will reshape", "our social fabric", "译为究竟如何重塑，保留how而不是whether。")]),
  sentence(18, [segment("But they certainly will reshape it, ", "predicate", "转折主句含强调副词", "确定判断", "they指hard times，it指social fabric", "certainly明确影响必然存在，与不清楚具体方式区分。"), segment("and all the more so ", "connector", "and并列省略的程度表达", "程度递进", "so代替reshape社会这一结果", "省略重复谓语，表示会更是如此。"), segment("the longer they extend.", "condition", "the比较级引比例变化分句", "程度条件", "说明时长增加会加深影响", "the longer ... all the more为越久越强的对应关系，不能简单当最长的一次。")], "they will reshape it.", "但这些艰难时光肯定会重塑社会结构，而且持续得越久，影响就越大。", "但有一点可以肯定：它们一定会改变社会，而且拖得越久，改变就越深。", "落脚于影响的确定性而非确定破坏性，定位40题C。", ["all the more so", "the longer they extend"], [clause("the longer they extend", "比例比较分句", "the + 比较级longer", "与all the more so构成程度联动", "they", "extend", "longer为时间程度", "译为持续越久，社会变化就越明显。")]),
];
const question = (number: number, sentenceNumber: number, prompt: string, options: string[], answer: Question["answer"], locating: string, explanations: Question["explanations"]): Question => ({ id: 201200 + number, number, sentenceId: `2012-p4-s${sentenceNumber}`, prompt, options: options.map((text, index) => ({ key: "ABCD"[index] as Question["answer"], text })), answer, locating, explanations });
export const passage2012P4Questions = [
  question(36, 4, 'By saying "to find silver linings" (Line 1, Para. 2) the author suggests that the jobless try to____.', ["seek subsidies from the government", "make profits from the troubled economy", "explore reasons for the unemployment", "look on the bright side of the recession"], "D", "后文列举少些物欲、更谨慎、更体谅他人等正面变化，解释silver linings为逆境中光明的一面。", { A: "文中未谈寻求政府补贴。", B: "更少物欲、更谨慎不是从困境中赚取利润。", C: "此处讨论如何看待失业的影响，不是探索失业成因。", D: "bright side对应逆境中的希望和有限益处。" }),
  question(37, 7, "According to Paragraph 2, the recession has made people ____.", ["struggle against each other", "realize the national dream", "challenge their prudence", "reconsider their lifestyle"], "D", "less materialistic、more financially prudent及从轻易致富大房子幻想中醒来，都说明反思消费与生活方式。", { A: "struggles of others为他人的艰辛，不是彼此争斗。", B: "文中说从狂热梦中醒来，不是实现那个梦。", C: "谨慎程度增加，不是挑战或否定谨慎。", D: "消费和物质观念变化概括为重新审视生活方式。" }),
  question(38, 9, "Benjamin Friedman believes that economic recessions may ____.", ["impose a heavier burden on immigrants", "bring out more evils of human nature", "promote the advance of rights and freedoms", "ease conflicts between races and classes"], "B", "第3段说社会更mean-spirited、更不inclusive，反移民情绪及种族阶层冲突上升，表明人性消极面被激发。", { A: "反移民情绪增加不等于原文具体论述移民经济负担增重，概括过窄且换了对象。", B: "更刻薄和更排斥异己概括为人性负面一面显现。", C: "原文为stopped or reversed，方向恰相反。", D: "原文conflict increases为冲突加剧，不是缓和。" }),
  question(39, 13, "The research of Till Von Wachter suggests that in the recession graduates from elite universities tend to____.", ["lag behind the others due to decreased opportunities", "catch up quickly with experienced employees", "see their life chances as dimmed as the others'", "recover more quickly than the others"], "D", "名校毕业生较快赶上在好时机毕业本可达到的水平，被落下的是其下的普通大众。", { A: "被落下的是masses beneath them，不是精英大学毕业生。", B: "追赶参照为自身反事实发展轨迹，原文无experienced employees这一群体。", C: "not all和后面两类人对照明确否定机会同等受损。", D: "fairly quickly catch up与普通大众被落下对比，说明恢复更快。" }),
  question(40, 18, "The author thinks that the influence of hard times on society is ____.", ["trivial", "positive", "certain", "destructive"], "C", "末段先说具体怎样改变仍需观察，最后用certainly will reshape明确改变本身是确定的。", { A: "作者认为影响涉及社会结构且延续多年，不是微不足道。", B: "仅在有限方面有可能好处，不能概括整体影响为积极。", C: "certain直接对应certainly，区分影响确定和具体方向未明。", D: "负面风险很多，但末段强调民调复杂、具体方式待观察，不能把确定存在换成确定破坏性。" }),
];
