import type { SentenceWordContext } from "./contextual-vocabulary";
type ReviewedContext = SentenceWordContext & { pattern: string; patternMeaning: string };
const w = (partOfSpeech: string, contextualMeaning: string, use: string, pattern: string, patternMeaning: string): ReviewedContext => ({ partOfSpeech, contextualMeaning, use, pattern, patternMeaning, preferredCollocations: [pattern] });
// 同一篇中的相同义项复用；功能或指代不同者在逐来源表中明确覆盖。没有扫描词形猜语义。
export const passage2012P1CommonContexts: Record<string, ReviewedContext> = {
  have:w("aux. / v.","完成时助动词；有","本篇has/have接过去分词时构成完成时；have difficulty/problems中的have则为实义动词。具体功能随当前动词组合区分。","has produced an inflexible policy","已制定一项僵化政策"),
  be:w("aux. / linking v.","系动词或时态语态助动词","接形容词或名词构成系表；接-ing构成进行时；接过去分词构成被动。本篇popular与scorned尤其需要区分。","homework will still be a part of schooling","作业仍将是学校教育的一部分"),
  never:w("adv.","从未；从不","修饰has been，否定作业长期很受欢迎的状态。","has never been terribly popular","一直都不怎么受欢迎"),
  even:w("adv.","甚至","even many parents将家长也列入不喜欢作业的人群，并突出这一点。","even many parents","甚至许多家长"),
  many:w("det.","许多","限定可数复数parents，强调许多家长也不喜欢作业。","many parents","许多家长"),
  parent:w("n.","家长；父母","parents指学生的父母，出现在评价作业受欢迎程度的人群中。","many parents","许多家长"),
  but:w("conj.","但是；然而","本篇各处but连接相对的评价或情形；由其后实际命题确定转折对象，不表示结论一定转正。","But the policy is unclear and contradictory","但政策含糊且自相矛盾"),
  recent:w("adj.","近来的","修饰years；时间范围相对原文写作时，而不是今天。","in recent years","近年来"),
  year:w("n.","年","years在in recent years中表示文中当时之前的近几年，没有精确起止年份。","in recent years","近年来"),
  particularly:w("adv.","尤其；特别","修饰scorned，强调近年来作业受到轻视的程度。","particularly scorned","尤其受到轻视"),
  school:w("n.（定语）","学校；学校教育的","school districts是学区，school board是教育管理委员会；school在这两处均作名词定语。","School districts across the country","全国各学区"),
  across:w("prep.","遍及；遍布","across the country后置限定school districts，说明学区遍布全国。","across the country","全国各地"),
  country:w("n.","国家；全国","across the country指全国范围的学区，结合洛杉矶背景是美国。","across the country","全国各地"),
  most:w("adv.","最","most recently中most修饰recently，意为最近的一例，不是大多数学区。","most recently Los Angeles Unified","最近的一例是洛杉矶联合学区"),
  recently:w("adv.","最近","most recently引出最新开始反思作业的学区例子。","most recently Los Angeles Unified","最近的一例是洛杉矶联合学区"),
  policy:w("n.","政策","本文指洛杉矶联合学区的作业计分政策，核心措施是规定作业成绩权重上限。","an inflexible policy","一项僵化政策"),
  difficulty:w("n.","困难","指家庭贫困或混乱的学生完成作业时可能遇到的障碍；定语that代回difficulty作have宾语。","in completing their homework","在完成作业方面"),
  certainly:w("adv.","当然；确实","作者用Certainly承认不该布置独立做不来或依赖昂贵设备的作业。","Certainly, no homework should be assigned","当然，不应布置这类作业（类型由后文限定）"),
  should:w("modal v.","应该；应当","在本篇表达作者对布置、计分或暂缓规则的建议；后接动词原形，不是过去评价结构中的特殊should。","should be put on hold","应当暂缓执行"),
  give:w("v.-ing（进行时）","给予","giving a pass整体是放过或免于追究；give接a pass和to引出的接受对象。","giving a pass to students","不追究学生"),
  family:w("n.（定语）","家庭","修饰lives，说明学生家庭生活复杂导致未完成作业，未推断其学习能力。","complicated family lives","复杂的家庭生活"),
  life:w("n.（复数）","生活","lives为life的复数，指这些学生各自的家庭生活状况。","complicated family lives","复杂的家庭生活"),
  go:w("v.-ing（进行时）","趋向；走向","is going close to表示学区做法接近某种暗示，不是be going to将来结构。","going riskily close to the implication","危险地接近这种暗示"),
  close:w("adv.","接近；近乎","close to限定is going所趋近的含义；并非动词关闭或结束。","close to the implication","接近这种暗示"),
  need:w("v.","需要","standards need to be lowered中接被动不定式；降低标准处在被警惕的暗示内，不是作者直接建议。","need to be lowered for poor children","需要为贫困儿童降低（标准）"),
  poor:w("adj.","贫困的","修饰children或students，指经济条件；不能译成学习差或教育期望低。","poor children","贫困儿童"),
  child:w("n.（不规则复数）","孩子；儿童","children是child的不规则复数，poor限定家庭经济处境。","poor children","贫困儿童"),
  say:w("v.","说；表示","District administrators say引出管理者的政策辩护，作者随后检验其实际后果。","District administrators say","学区管理者表示"),
  will:w("modal v.","将；将会","will still be属于管理者对作业继续存在的承诺，后接be原形。","homework will still be a part of schooling","作业仍将是学校教育的一部分"),
  part:w("n.","部分","a part of schooling指出家庭作业是学校教育的一部分，并非教育的全部。","a part of schooling","学校教育的一部分"),
  teacher:w("n.","教师","本文讨论教师布置作业的许可、因材判断空间和检查批改的意愿。","teachers are allowed to assign","教师被允许布置"),
  allow:w("v.-ed（被动）","允许","are allowed to assign的主语teachers是获准者，许可不等于强制要求。","are allowed to assign","获准布置"),
  easily:w("adv.","轻易地；容易地","修饰skip，说明低计分权重下学生很容易少做一半作业。","can easily skip half their homework","可以轻易少做一半作业"),
  see:w("v.","看到；观察到","see very little difference指成绩单上几乎看不出差异；不是see A as B的视为结构。","see very little difference","看到的差异很小"),
  very:w("adv.","很；极其","very little difference中加强little的少量程度，合起来是差异极小。","very little difference","极小的差异"),
  difference:w("n.","差异；差别","指少做作业后成绩单上的变化，不表示对成绩漠不关心。","very little difference on their report cards","成绩单上极小的差异"),
  help:w("v.（过去式）","有帮助；起促进作用","the homework helped是that主语从句内容；作者只说很可能帮助了前句学生，未证明唯一因果。","the homework helped","作业起了帮助作用"),
  yet:w("conj. / adv.","然而","句首Yet引出与教师自行判断相对的一刀切做法，此处不是句末尚未。","Yet rather than empowering teachers","然而，并未赋权教师"),
  rather:w("adv.（固定连接表达成分）","用于rather than，表示而非","rather than后为未采取的赋权方式，主句才给出实际强推统一规则的做法。","rather than empowering teachers","而非赋权教师"),
  find:w("v.","寻找；认为","to find what works best是寻找有效做法；finds homework to be unimportant则是认为作业不重要，按来源分别辨认。","finds homework to be unimportant","认为作业不重要"),
  work:w("v.（第三人称单数）","奏效；起作用","what works best for their students中，what为主语，works为谓语，不是艺术作品或工作岗位名词。","what works best for their students","对他们的学生最奏效的做法"),
  same:w("adj.（固定表达成分）","相同的","At the same time整体引出另一项批评；不能把same当成回指另篇所谓同样规律。","At the same time","与此同时；此外"),
  time:w("n.（固定表达成分）","时间","At the same time在本段用于补充论点，未计算倍数或精确同步时刻。","At the same time","与此同时；此外"),
  none:w("pron.","一个也没有","none of the ... questions作addresses宾语，使整句表示一个实质问题也未解决。","none of the truly thorny questions","真正棘手的问题中一个也没有"),
  its:w("possessive det.","它的；该学区的","its students指the district管理的学生；its不是it's。","its students' academic achievement","该学区学生的学业成就"),
  move:w("v.","着手；采取行动","should move to reduce中move为动词，后接行动内容不定式，不是移动或举措名词。","move to reduce or eliminate the assignments","着手减少或取消作业"),
  reduce:w("v.","减少","与eliminate并列，宾语为assignments；减少与完全取消力度不同。","reduce or eliminate the assignments","减少或取消作业"),
  almost:w("adv.","几乎","almost nothing修饰近乎零的计分比重，不断言作业教育价值必然为零。","count for almost nothing","在成绩中几乎不占分量"),
  significant:w("adj.","相当大的；显著的","修饰portion，表示作业有教育价值时应有相当计分比重；没有具体百分数。","a significant portion of the grade","成绩中相当大的比重"),
  age:w("n.","年龄","their age指接受作业的学生年龄，不是时代或教师年龄。","appropriate to their age and the subject","适合其年龄和学科"),
  willing:w("adj.","愿意的","are willing to review and correct说明教师愿意承担的批改量；不能换成有能力。","are willing to review and correct","愿意检查和批改"),
  put:w("v.-ed（被动分词）","置于；使处于","put on hold整体是暂缓，put过去分词与原形同形，与should be构成被动。","be put on hold","被暂缓执行"),
  responsible:w("adj.","负有职责的；负责的","董事会负责制定教育政策，是职责说明，不是在归咎谁造成问题。","is responsible for setting educational policy","负责制定教育政策"),
  into:w("prep.（短语动词成分）","用于look into，表示调查对象","looks into the matter整体为调查此事；不能按进入某处的空间义解释。","looks into the matter","调查这件事"),
  public:w("adj.","公开的；面向公众的","修饰hearings，表示公开听证会；此处是形容词，不是名词公众。","conducts public hearings","举行公开听证会"),
  too:w("adv.","过于；太","not too late中too修饰late；不是句末也。否定作用于太晚这一程度。","not too late","还不算太晚"),
  late:w("adj.","晚的；迟的","作is的表语，not too late说明学区仍有改正余地。","not too late","还来得及"),
  imply:w("v.-ed（被动分词）","暗示","is implied表示命题为文本所暗示，读者据首段推断；不是过去式独立谓语。","It is implied in Paragraph 1","第一段暗示"),
  nowadays:w("adv.","如今；现今","限定题干中作业当前评价，承接原文in recent years，时间相对原文写作时。","nowadays homework","如今的家庭作业（后接选项命题）"),
  mainly:w("adv.","主要地","mainly because限定制定规则的主要原因，此题不是问全文主旨。","mainly because poor students","主要因为贫困学生（后接选项情况）"),
  tend:w("v.","往往；倾向于","tend to have后接不定式，表示学生期望的倾向性断言；是否有据仍须核对原文。","tend to have moderate expectations","往往抱有适度期望"),
  education:w("n.","教育","their education指学生自身教育，power in education指教育领域的权力。","their education","他们的教育"),
  ask:w("v.-ed（完成时分词）","要求；请求","have asked for接a different educational standard，断言学生已请求不同标准，不是问问题。","have asked for a different educational standard","已经要求不同的教育标准"),
  different:w("adj.","不同的","修饰educational standard，指有区别的标准，而不是多种颜色或成绩差异。","a different educational standard","一种不同的教育标准"),
  problem:w("n.","问题；困难","have problems doing表示做某事有困难；one problem with the policy说明政策的问题，按来源区分。","may have problems finishing their homework","可能难以完成作业"),
  according:w("prep. phrase component","根据；按照","According to Paragraph 3要求回到第三段核对政策后果；按信息来源理解整个表达。","According to Paragraph 3","根据第三段"),
  one:w("det. / number","一个；一项","one problem表示政策问题中的一项，不是代替前文名词的ones。","one problem with the policy","这项政策的一个问题"),
  result:w("v.","导致；造成","题目选项接may，result为动词原形，result in引结果，不是As a result名词结构。","result in students' indifference","导致学生漠不关心"),
  authority:w("n.","权威；公信力","of state tests限定为州统考的权威，不是当局管理人员。","the authority of state tests","州统考的权威"),
  power:w("n.","权力；权限","teachers' power in education指教师在教育中的决定权限，不是供电或自然选择的作用力。","teachers' power in education","教师在教育中的权力"),
  mention:w("v.-ed（被动分词）","提到；说及","As mentioned in Paragraph 4为省略评注结构，限定题目证据来源第四段。","As mentioned in Paragraph 4","如第四段所述"),
  key:w("adj.","关键的","a key question中key修饰question，不是实体钥匙名词。","a key question","一个关键问题"),
  whether:w("conj.","是否","is whether引出待回答问题的内容，后由完整选项命题补足；不是假设如果。","a key question unanswered about homework is whether","关于作业一个尚未回答的关键问题是是否"),
  place:w("v.（第三人称单数）","施加；置于","it places extra burdens on teachers为主谓宾，places不是地方的复数。","places extra burdens on teachers","给教师增加额外负担"),
  important:w("adj.","重要的","第24题D将重要性的范围限定为grades，与B的schooling教育作用区别。","important for grades","对成绩重要"),
  approach:w("n.","办法；处理方式","A Faulty Approach to Homework中心为名词approach，to为介词引处理对象；不是接近历史的动词。","A Faulty Approach to Homework","一种有缺陷的作业处理办法"),
};
export const passage2012P1SpecificContexts: Record<string,Record<string,ReviewedContext>> = {
  "2012-p1-s1":{ have:w("aux.（完成时）","完成时助动词","两处has均接been构成现在完成时，前项系表，后项被动。","has been particularly scorned","尤其受到轻视"),with:w("prep.","对……；在……人群中","popular with引出认为作业受欢迎与否的人群。","popular with students","受学生欢迎"),it:w("pron.","它（指家庭作业）","it回指Homework，作has been scorned的主语。","it has been particularly scorned","它尤其受到轻视")},
  "2012-p1-s3":{which:w("relative pron.","关系代词，指政策","which回指policy，在从句中作mandates的主语，说明政策规定什么。","which mandates that","该政策规定……"),that:w("conj.","引出规定内容","that连接mandates宾语从句，不作其内部主语或宾语。","which mandates that","该政策规定……"),may:w("modal v.","可以；被允许","政策语境may no longer限制许可范围，表示不准再超过上限，不是猜测也许。","homework may no longer count for more than 10%","作业所占比重不得再超过10%"),long:w("adv.（比较级）","更久；再继续","longer在no longer中表示不再继续，整体修饰count。","no longer","不再"),more:w("adv.（比较数量表达）","超过","more than 10%给出数量上限，处在may no longer否定内。","more than 10%","超过10%")},
  "2012-p1-s4":{that:w("relative pron.","关系代词，代指困难","that修饰difficulty并作have宾语；后面have未再写宾语不是残缺。","the difficulty that students from impoverished or chaotic homes might have","贫困或混乱家庭学生可能遇到的困难"),have:w("v.","有；遇到","might have的宾语是前置关系词that所指difficulty，不是完成时。","might have in completing their homework","在完成作业方面可能遇到（困难）"),mean:w("v.-ed（被动分词）","意在；打算","be meant to address说明规则的设计意图，不是mean doing意味着。","is meant to address","旨在处理")},
  "2012-p1-s6":{that:w("relative pron.","关系代词，代指作业","两个that均修饰homework，分别作complete和do宾语。","that students cannot complete on their own","学生无法独立完成的（作业）"),they:w("pron.","他们（指学生）","they在第二个定语从句中承接students。","they cannot do without expensive equipment","他们没有昂贵设备就做不了"),do:w("v.","做；完成","cannot do中do为实义动词，宾语that提前，without说明设备条件。","cannot do without expensive equipment","没有昂贵设备就做不了"),without:w("prep.","没有；不借助","后接expensive equipment，表示完成作业所缺条件。","without expensive equipment","没有昂贵设备")},
  "2012-p1-s7":{it:w("pron.","它（指学区）","回指条件从句the district，评价其政策做法。","it is going riskily close to the implication","学区的做法危险地接近这种暗示"),who:w("relative pron.","关系代词，指学生","who在students定语从句内作do not do的主语。","who do not do their homework","没有完成作业的（学生）"),that:w("conj.","引出暗示的内容","that完整说明implication，不作从句主宾语，也不表示作者赞同该内容。","that standards need to be lowered for poor children","对贫困儿童需要降低标准这一暗示"),do:w("aux. / v.","否定助动词；做","do not do中第一个do承载否定语法，第二个do为完成作业的实义动词；同一来源的两处形式相同，卡片明确区分。","do not do their homework","不做他们的作业"),because:w("prep. phrase component","因为；由于","because of接complicated family lives名词短语，不是because直接引主谓句。","because of complicated family lives","因为家庭生活复杂")},
  "2012-p1-s8":{it:w("pron.","它（指家庭作业）","as much of it中的it指不可数homework，作of宾语。","as much of it as they want","想要多少作业就多少"),as:w("adv. / conj.","构成数量比较的as…as","第一个as修饰much，第二个as引they want数量比较从句；不是时间当……时。","as much of it as they want","教师想布置多少作业就多少"),much:w("pron.","多；大量","as much of it表示不可数homework的数量，整体为assign宾语。","as much of it as they want","想布置多少作业就多少")},
  "2012-p1-s9":{with:w("prep.","在……情况下","with引homework加counting的非谓语结构，交代计分条件。","with homework counting for no more than 10% of their grades","作业最多只占成绩10%的情况下")},
  "2012-p1-s10":{what:w("interrogative pron.","什么；怎样","what about引出另一类学生的反问，原文没有完整补出主谓。","what about the students","那些学生又如何"),who:w("relative pron.","关系代词，指学生","who修饰后一组students，统领performed和did两个并列动作。","who performed well on the tests and did their homework","考得好且做作业的学生"),do:w("v.","做；表现","might do well中do well是表现好；did their homework中did是实义做作业，分别辨认。","did their homework","做了作业"),without:w("prep.","没有；未曾","without completing引动名词，说明没完成作业的情况下仍可能考好。","without completing their homework","没有完成作业")},
  "2012-p1-s11":{it:w("pron.（形式主语）","形式主语","It占位，真正主语为that the homework helped。","It is quite possible that the homework helped","作业很可能起了帮助作用"),that:w("conj.","引出被评价的命题","that引后置主语从句，不是possible这个形容词的动词宾语。","that the homework helped","作业起了帮助作用这一命题")},
  "2012-p1-s12":{find:w("v.（不定式）","寻找；找出","教师寻找对学生最有效的做法，find后为what名词性从句，不是find A to be B。","find what works best for their students","找出对学生最奏效的做法"),what:w("fused relative pron.","……的做法；所……的事物","what既连接find宾语从句，又作works主语。","what works best for their students","对学生最奏效的做法")},
  "2012-p1-s14":{it:w("pron.","它（指学区）","it主语承接the district，采取减少或取消作业行动。","it should move to reduce or eliminate the assignments","学区应着手减少或取消作业"),find:w("v.（第三人称单数）","认为；认定","finds homework to be unimportant含宾语homework及不定式宾补，只在if条件中提出。","finds homework to be unimportant","认为作业不重要"),make:w("v.","使；让","make them count中them为assignments，count为不带to的宾语补足语。","make them count for almost nothing","使作业几乎不计入成绩"),nothing:w("pron.","近乎零的分量","almost nothing指计分权重近乎零，不是作业内容空白。","count for almost nothing","在成绩中几乎不占比重")},
  "2012-p1-s15":{it:w("pron.","它（指家庭作业）","本句it指homework，不能沿用上句学区指代。","it should account for a significant portion of the grade","作业应占成绩相当大的比重")},
  "2012-p1-s16":{that:w("conj.","引出确保的内容","两个that从句并列作ensure宾语；students receive内部的关系词则被省略。","to ensure that the homework students receive is meaningful","确保学生收到的作业有意义"),more:w("pron.（比较级）","更多的作业量","assigning more后省略已知homework，than引愿意检查批改的数量标准。","more than they are willing to review and correct","超过教师愿意检查批改的数量"),nothing:w("pron.","没有任何事情；没有任何措施","does nothing to ensure指政策没有采取保障措施，不推出所有坏结果已经发生。","does nothing to ensure","没有采取措施来确保"),do:w("v.（第三人称单数）","做；采取行动","does的宾语是nothing，整组表示未采取措施，不是这里的否定助动词。","does nothing to ensure","没有采取措施来确保")},
  "2012-p1-s17":{which:w("relative pron.","关系代词，指董事会","which补充school board职责，在定语从句中作is主语。","which is responsible for setting educational policy","负责制定教育政策的（董事会）"),while:w("conj.","在……期间","引调查听证的时间从句，说明规则暂停的期间，不是让步或对照。","while the school board","在董事会开展相关行动期间")},
  "2012-p1-s18":{it:w("pron.（形式主语）","形式主语","真正主语是不定式for L.A. Unified to do homework right。","It is not too late for L.A. Unified to do homework right","学区把作业政策做好还来得及"),do:w("v.（不定式）","做；处理","do homework right以做作业双关学区认真处理政策，right为副词。","do homework right","把作业这件事做好")},
  "question-201221-prompt":{it:w("pron.（形式主语）","形式主语","It对应后置that nowadays homework____，不是泛指某个事实对象。","It is implied in Paragraph 1","第一段暗示")},
  "question-201221-option-A":{receive:w("v.-ing（进行时）","受到","is receiving more criticism中receiving指受到批评，不是收取学生作业。","receiving more criticism","受到更多批评"),more:w("det.","更多的","限定不可数criticism，说明批评更多，不是the more…比较关联。","more criticism","更多批评")},
  "question-201221-option-B":{more:w("det.","更多的","限定复数preferences，表示更多偏爱，保留原卷表达。","more preferences","更多偏爱")},
  "question-201222-prompt":{make:w("v.-ed（完成时分词）","制定","has made the rule是制定规则，made不是使役宾补结构。","has made the rule about homework","已经制定作业规则"),because:w("conj.","因为","because poor students ____引原因从句，后接主语和由选项补全的谓语，不是because of。","mainly because poor students","主要因为贫困学生（后续由选项补全）")},
  "question-201222-option-C":{have:w("v.","有；遇到","may have problems finishing中have是实义动词，problems为宾语，不是完成时。","may have problems finishing their homework","可能难以完成作业")},
  "question-201223-prompt":{it:w("pron.","它（指政策）","that it may____中的it承接policy，问政策可能带来的后果。","one problem with the policy","这项政策的一个问题"),problem:w("n.","问题；缺陷","one problem with the policy是主语，with限定问题属于该政策。","one problem with the policy","这项政策的一个问题")},
  "question-201224-prompt":{as:w("conj.","正如；如……所述","As mentioned为省略评注从句，引题目来源第四段；此处as表示如……所述。","As mentioned in Paragraph 4","如第四段所述")},
  "question-201224-option-A":{it:w("pron.","它（指家庭作业）","it承接题干homework，问是否应取消，非形式主语。","it should be eliminated","作业应该被取消")},
  "question-201224-option-B":{it:w("pron.","它（指家庭作业）","it是counts主语，指家庭作业，不是形式主语。","it counts much in schooling","作业在学校教育中有重要作用"),count:w("v.（第三人称单数）","重要；有价值","counts是不及物动词，much加强程度，in schooling给教育领域，不是count for计分占比。","counts much in schooling","在学校教育中有重要作用"),much:w("adv.","很；程度大","修饰counts的重要程度，不是不可数名词的数量限定。","counts much in schooling","在学校教育中有重要作用")},
  "question-201224-option-C":{it:w("pron.","它（指家庭作业）","作places主语，作业被说成给教师施加负担的因素。","it places extra burdens on teachers","作业给教师施加额外负担")},
  "question-201224-option-D":{it:w("pron.","它（指家庭作业）","it作主系表主语，问作业对成绩的重要性。","it is important for grades","作业对成绩重要")},
};

Object.assign(passage2012P1CommonContexts, {
  in:w("prep.","在……内；在……方面","本篇in recent years限定时间，in completing限定困难领域，in schooling限定教育领域；按当前宾语组合辨认。","in completing their homework","在完成作业方面"),
  on:w("prep.","关于；在……上；用于固定表达","本篇thinking on说明思考对象，on tests说明考试表现领域，on hold为暂缓状态；关系取决于当前整体结构。","on their report cards","在他们的成绩单上"),
  of:w("prep.","表示所属、内容或部分关系","of把份额与整体、问题与范围等连接；10% of a student's academic grade把百分比的分母限定为学生成绩。","10% of a student's academic grade","学生学业成绩的10%"),
  to:w("prep. / infinitive marker","介词或不定式标记","接动词原形时如to address构成不定式；接名词时如appropriate to their age为介词，不可只看to就统一分类。","to address the difficulty","为处理困难"),
  for:w("prep.","引出范围、对象或比例","本篇count for/account for接计分份额，responsible for接职责，for L.A. Unified引不定式逻辑主语；看前后完整组合辨认。","for a significant portion of the grade","在总成绩中占相当份额（与account连读）"),
  from:w("prep.","来自；用于阻止或劝阻结构","students from ... homes说明家庭来源；discourage students from doing homework中from引受抑制的行为，不是动作地点。","students from impoverished or chaotic homes","来自贫困或混乱家庭的学生"),
  this:w("det.","这；这一","this educational ritual回指作业惯例；this rule/policy回指本文计分政策。后接名词限定当前讨论对象。","this educational ritual","这项教育惯例"),
  that:w("conj. / relative pron.","从句引导词或关系代词","在本篇有内容从句与定语从句两类；内容that不作内部主宾语，定语that回指policy之外的difficulty或homework并承担宾语。以实际动词关系为准。","that the homework helped","作业起了帮助作用这一命题"),
  which:w("relative pron.","关系代词，回指前面的事物","本篇which分别回指policy或school board，均在各自定语从句中作主语；要回到当前句确认先行词。","which is responsible for setting educational policy","负责制定教育政策的（董事会）"),
  as:w("adv. / conj.","用于比较或引述的连接成分","正文as much ... as连接数量比较，24题As mentioned引述第四段内容；不能沿用时间as的解释。","as much of it as they want","想布置多少作业就多少"),
  what:w("pron.","什么；所……的做法","what about引反问；what works best中what既连接又作主语，指最有效的做法。不是每处what都直接提问。","what works best for their students","对其学生最有效的做法"),
  than:w("conj. / prep. phrase component","比；用于比较或rather than结构","more than引数量比较；rather than在第12句排除赋权教师的办法，须按整体关系理解。","more than they are willing to review and correct","超过他们愿意检查批改的数量"),
  no:w("det. / adv.","没有；不","no homework否定带后置定语限定的作业种类；no longer为不再；no more than为不超过。不能省略其后的限定范围。","no more than 10%","至多10%"),
  not:w("adv.","不","否定当前谓语、做法或程度；not too late否定太迟，not make排除一种处理方式，不随意扩大到整段。","not too late","还不算太晚"),
  and:w("conj.","和；并且","连接当前句中平行成分：如unclear与contradictory、skip与see、review与correct；先确认是否共用主语与助动词。","review and correct","检查和批改"),
  at:w("prep.（固定表达成分）","用于At the same time","与the same time组成篇章衔接语，引出政策遗漏实质问题的另一项批评。","At the same time","与此同时；此外"),
  paragraph:w("n.","段落","题干Paragraph 1/3/4分别限定所需原文范围，数字是原卷段落号，不是句号。","According to Paragraph 3","根据第三段"),
});
passage2012P1SpecificContexts["2012-p1-s12"].board = w("phrase component","一刀切表达的组成部分","此处位于across-the-board，整组是形容词一律适用，不是第17句school board的董事会。","across-the-board rule","一刀切的规定");

// 以下只记录既有原文词形归一化后的出现清单，用于限定人工语境的有效来源；不据词形推断词义。
passage2012P1CommonContexts.may = w("modal v.","可能","may在题干和推论中保留可能性；第3句政策条文另按许可义单独覆盖。","it may","它可能（后接动词原形）");
passage2012P1SpecificContexts["2012-p1-s3"].with = w("prep.（固定表达成分）","用于例外范围表达","with the exception of整体排除部分高级课程，不能用popular with或with加分词的结构解释。","with the exception of some advanced courses","除部分高级课程之外");
passage2012P1SpecificContexts["2012-p1-s9"].more = w("adv.（数量比较表达）","超过","no more than限定10%的上限，不是the more...the more...双分句比较。","no more than 10%","不超过10%");
passage2012P1SpecificContexts["question-201223-prompt"].with = w("prep.","关于；存在于","one problem with the policy中的with引出有问题的对象，不是伴随条件结构。","one problem with the policy","该政策的一个问题");
const sourceHeadwords: Record<string,string[]> = {
  "2012-p1-s1": [
    "and",
    "be",
    "but",
    "even",
    "have",
    "homework",
    "in",
    "it",
    "many",
    "never",
    "parent",
    "particularly",
    "popular",
    "recent",
    "scorn",
    "student",
    "terribly",
    "with",
    "year"
  ],
  "2012-p1-s2": [
    "across",
    "angeles",
    "be",
    "country",
    "district",
    "educational",
    "los",
    "most",
    "on",
    "recently",
    "revise",
    "ritual",
    "school",
    "the",
    "their",
    "thinking",
    "this",
    "unified"
  ],
  "2012-p1-s3": [
    "a",
    "academic",
    "advanced",
    "an",
    "count",
    "course",
    "exception",
    "for",
    "grade",
    "have",
    "homework",
    "inflexible",
    "l.a.",
    "long",
    "mandate",
    "may",
    "more",
    "no",
    "of",
    "policy",
    "produce",
    "some",
    "student",
    "than",
    "that",
    "the",
    "unfortunately",
    "unified",
    "which",
    "with"
  ],
  "2012-p1-s4": [
    "address",
    "be",
    "chaotic",
    "complete",
    "difficulty",
    "from",
    "have",
    "home",
    "homework",
    "impoverished",
    "in",
    "may",
    "mean",
    "or",
    "rule",
    "student",
    "that",
    "the",
    "their",
    "this",
    "to"
  ],
  "2012-p1-s5": [
    "and",
    "be",
    "but",
    "contradictory",
    "policy",
    "the",
    "unclear"
  ],
  "2012-p1-s6": [
    "assign",
    "be",
    "can",
    "certainly",
    "complete",
    "do",
    "equipment",
    "expensive",
    "homework",
    "no",
    "on",
    "or",
    "own",
    "should",
    "student",
    "that",
    "their",
    "they",
    "without"
  ],
  "2012-p1-s7": [
    "a",
    "be",
    "because",
    "but",
    "child",
    "close",
    "complicated",
    "district",
    "do",
    "essentially",
    "family",
    "for",
    "give",
    "go",
    "homework",
    "if",
    "implication",
    "it",
    "life",
    "lower",
    "need",
    "not",
    "of",
    "pass",
    "poor",
    "riskily",
    "standard",
    "student",
    "that",
    "the",
    "their",
    "to",
    "who"
  ],
  "2012-p1-s8": [
    "a",
    "administrator",
    "allow",
    "as",
    "assign",
    "be",
    "district",
    "homework",
    "it",
    "much",
    "of",
    "part",
    "say",
    "schooling",
    "still",
    "teacher",
    "that",
    "they",
    "to",
    "want",
    "will"
  ],
  "2012-p1-s9": [
    "and",
    "but",
    "can",
    "card",
    "count",
    "difference",
    "easily",
    "for",
    "grade",
    "half",
    "homework",
    "little",
    "more",
    "no",
    "of",
    "on",
    "report",
    "see",
    "skip",
    "student",
    "than",
    "their",
    "very",
    "with"
  ],
  "2012-p1-s10": [
    "about",
    "and",
    "but",
    "complete",
    "do",
    "homework",
    "may",
    "on",
    "perform",
    "some",
    "state",
    "student",
    "test",
    "the",
    "their",
    "well",
    "what",
    "who",
    "without"
  ],
  "2012-p1-s11": [
    "be",
    "help",
    "homework",
    "it",
    "possible",
    "quite",
    "that",
    "the"
  ],
  "2012-p1-s12": [
    "a",
    "across-the-board",
    "best",
    "board",
    "empower",
    "find",
    "flat",
    "for",
    "impose",
    "policy",
    "rather",
    "rule",
    "student",
    "teacher",
    "than",
    "the",
    "their",
    "to",
    "what",
    "work",
    "yet"
  ],
  "2012-p1-s13": [
    "about",
    "address",
    "at",
    "homework",
    "none",
    "of",
    "policy",
    "question",
    "same",
    "the",
    "thorny",
    "time",
    "truly"
  ],
  "2012-p1-s14": [
    "academic",
    "achievement",
    "almost",
    "assignment",
    "be",
    "count",
    "district",
    "eliminate",
    "find",
    "for",
    "homework",
    "if",
    "it",
    "its",
    "make",
    "move",
    "not",
    "nothing",
    "or",
    "reduce",
    "should",
    "student",
    "the",
    "they",
    "to",
    "unimportant"
  ],
  "2012-p1-s15": [
    "a",
    "account",
    "conversely",
    "for",
    "grade",
    "homework",
    "if",
    "it",
    "matter",
    "of",
    "portion",
    "should",
    "significant",
    "the"
  ],
  "2012-p1-s16": [
    "age",
    "and",
    "appropriate",
    "assign",
    "be",
    "correct",
    "do",
    "ensure",
    "homework",
    "meaningful",
    "meanwhile",
    "more",
    "not",
    "nothing",
    "or",
    "policy",
    "receive",
    "review",
    "student",
    "subject",
    "teacher",
    "than",
    "that",
    "the",
    "their",
    "they",
    "this",
    "to",
    "willing"
  ],
  "2012-p1-s17": [
    "and",
    "be",
    "board",
    "conduct",
    "educational",
    "for",
    "hearing",
    "hold",
    "homework",
    "into",
    "look",
    "matter",
    "on",
    "policy",
    "public",
    "put",
    "responsible",
    "rule",
    "school",
    "set",
    "should",
    "the",
    "which",
    "while"
  ],
  "2012-p1-s18": [
    "be",
    "do",
    "for",
    "homework",
    "it",
    "l.a.",
    "late",
    "not",
    "right",
    "to",
    "too",
    "unified"
  ],
  "question-201221-prompt": [
    "be",
    "homework",
    "imply",
    "in",
    "it",
    "nowadays",
    "paragraph",
    "that"
  ],
  "question-201221-option-A": [
    "be",
    "criticism",
    "more",
    "receive"
  ],
  "question-201221-option-B": [
    "be",
    "gain",
    "more",
    "preference"
  ],
  "question-201221-option-C": [
    "an",
    "be",
    "educational",
    "long",
    "no",
    "ritual"
  ],
  "question-201221-option-D": [
    "advanced",
    "be",
    "course",
    "for",
    "not",
    "require"
  ],
  "question-201222-prompt": [
    "about",
    "because",
    "have",
    "homework",
    "l.a.",
    "mainly",
    "make",
    "poor",
    "rule",
    "student",
    "the",
    "unified"
  ],
  "question-201222-option-A": [
    "education",
    "expectation",
    "for",
    "have",
    "moderate",
    "tend",
    "their",
    "to"
  ],
  "question-201222-option-B": [
    "a",
    "ask",
    "different",
    "educational",
    "for",
    "have",
    "standard"
  ],
  "question-201222-option-C": [
    "finish",
    "have",
    "homework",
    "may",
    "problem",
    "their"
  ],
  "question-201222-option-D": [
    "about",
    "complaint",
    "have",
    "homework",
    "their",
    "voice"
  ],
  "question-201223-prompt": [
    "according",
    "be",
    "it",
    "may",
    "one",
    "paragraph",
    "policy",
    "problem",
    "that",
    "the",
    "to",
    "with"
  ],
  "question-201223-option-A": [
    "card",
    "in",
    "indifference",
    "report",
    "result",
    "student",
    "their",
    "to"
  ],
  "question-201223-option-B": [
    "authority",
    "of",
    "state",
    "test",
    "the",
    "undermine"
  ],
  "question-201223-option-C": [
    "education",
    "in",
    "power",
    "restrict",
    "teacher"
  ],
  "question-201223-option-D": [
    "discourage",
    "do",
    "from",
    "homework",
    "student"
  ],
  "question-201224-prompt": [
    "a",
    "about",
    "as",
    "be",
    "homework",
    "in",
    "key",
    "mention",
    "paragraph",
    "question",
    "unanswered",
    "whether"
  ],
  "question-201224-option-A": [
    "be",
    "eliminate",
    "it",
    "should"
  ],
  "question-201224-option-B": [
    "count",
    "in",
    "it",
    "much",
    "schooling"
  ],
  "question-201224-option-C": [
    "burden",
    "extra",
    "it",
    "on",
    "place",
    "teacher"
  ],
  "question-201224-option-D": [
    "be",
    "for",
    "grade",
    "important",
    "it"
  ],
  "question-201225-prompt": [
    "a",
    "be",
    "can",
    "for",
    "suitable",
    "text",
    "this",
    "title"
  ],
  "question-201225-option-A": [
    "a",
    "approach",
    "faulty",
    "homework",
    "to"
  ],
  "question-201225-option-B": [
    "a",
    "for",
    "policy",
    "poor",
    "student",
    "welcomed"
  ],
  "question-201225-option-C": [
    "about",
    "homework",
    "question",
    "thorny"
  ],
  "question-201225-option-D": [
    "an",
    "educational",
    "interpretation",
    "of",
    "policy",
    "wrong"
  ]
};
export const passage2012P1ReviewedContexts: Record<string,Record<string,ReviewedContext>> = Object.fromEntries(Object.entries(sourceHeadwords).map(([sourceId, heads]) => [sourceId, Object.fromEntries(heads.flatMap(headword => {
  const context = passage2012P1SpecificContexts[sourceId]?.[headword] ?? passage2012P1CommonContexts[headword];
  return context ? [[headword, context]] : [];
}))]));
export const passage2012P1ContextGlosses: Record<string,{meaning:string;note?:string}> = Object.fromEntries([...Object.values(passage2012P1CommonContexts),...Object.values(passage2012P1SpecificContexts).flatMap(contexts => Object.values(contexts))].map(context => [context.pattern.toLowerCase(), { meaning: context.patternMeaning, note: context.use }]));
