import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";
const rows: LexiconRow[] = [
  ["end", "ends ended ending", "v. / n.", "结束；终结", "Before it ends为动词，put an end to为名词习语。", "put an end to spending（结束消费）", "end也可指末尾，按主谓或名词位置判断。"],
  ["politics", "", "n.", "政治；政治生活", "与文化、社会特性并列，列举长期影响范围。", "reshape politics（重塑政治）", "politics为领域名词，不能按复数归入politic形容词。"],
  ["culture", "cultures", "n.", "文化", "our culture指社会文化观念与实践，不是培养微生物。", "reshape culture（重塑文化）", "本文为社会层面的文化，不是生物实验培养物。"],
  ["other", "others", "pron. / det.", "其他人；其他的", "struggles of others指他人艰辛，39题others与名校生比较。", "the struggles of others（他人的艰辛）", "other加名词，others可独立代替其他人或物。"],
  ["big", "bigger biggest", "adj.", "大的", "bigger houses为追求更大住房的幻想。", "bigger houses（更大的房子）", "比较级bigger双写g，不是greater在所有搭配均可替换。"],
  ["u.s.", "", "abbreviation proper n.", "美国", "the U.S.为United States的缩写，保留点号。", "inside the U.S.（美国国内）", "不拆成U和S，也不同于代词us我们。"],
  ["period", "periods", "n.", "时期；时段", "lengthy periods指长时间停滞，修饰不可忽略。", "periods of decline（衰退时期）", "period也可句号或课时，本文为时间段。"],
  ["typically", "", "adv.", "通常地；典型地", "限制反移民情绪的变化频率，不表示无例外必然。", "typically increase（通常会增加）", "always总是比typically更绝对。"],
  ["class", "classes", "n.", "阶层；阶级", "与race并列或修饰divides，讨论社会分层。", "class divides（阶层鸿沟）", "不是班级或课堂，不能沿用教育题材默认义。"],
  ["degree", "degrees", "n.", "学位", "degrees from elite universities指名校学历背景。", "a university degree（大学学位）", "degree也可程度、温度，本句高等教育语境为学位。"],
  ["hide", "hides hid hidden hiding", "v.", "隐藏；掩藏", "has been hidden形容怨愤长期潜藏于社会内部。", "hidden resentment（隐藏的怨愤）", "hide过去式hid、分词hidden，非规则hided。"],
  ["enter", "enters entered entering", "v.", "进入", "entering this recession为美国进入衰退时的背景。", "enter a recession（进入经济衰退）", "enter通常直接接宾语，不必加into。"],
  ["variety", "varieties", "n.", "多样；多种", "a variety of national polls指多种调查。", "a variety of polls（多种民意调查）", "数量或种类多不等于结果一致。"],
  ["wait", "waits waited waiting", "v.", "等待", "wait and see为等待事情的具体后果显现。", "wait and see（等待观察）", "不等于断言不会发生变化。"],
  ["profit", "profits profited profiting", "n.", "利润；收益", "36题make profits干扰项为从困境牟利，非原文积极心态。", "make profits（获利）", "silver lining可为非金钱好处，不等于利润。"],
  ["explore", "explores explored exploring", "v.", "探索；探究", "36题探索失业原因与原文寻找积极意义不同。", "explore the reasons（探究原因）", "reason原因与consequence后果不可混同。"],
  ["challenge", "challenges challenged challenging", "v.", "质疑；挑战", "37题挑战prudence不合原文更审慎的变化。", "challenge a belief（质疑一种看法）", "reconsider是重新考虑，不必像challenge那样提出异议。"],
  ["reconsider", "reconsiders reconsidered reconsidering", "v.", "重新考虑；反思", "37题reconsider lifestyle概括消费和财富观变化。", "reconsider one's lifestyle（反思生活方式）", "re-表示重新，reconsider不等于彻底否认原来生活。"],
  ["heavy", "heavier heaviest", "adj.", "沉重的", "38题a heavier burden表示更重负担，但原文未给该具体结论。", "a heavier burden（更沉重的负担）", "比较级y变i再加er，不按名词处理heavier。"],
  ["decrease", "decreases decreased decreasing", "v.", "减少；降低", "正文decrease opportunities为减少机会，39题decreased作分词定语。", "decrease opportunities（减少机会）", "reinforce差距与decrease机会指向同一负面趋势而动词方向不同。"],
  ["employee", "employees", "n.", "雇员；员工", "39题B无依据引入有经验雇员这一比较对象。", "experienced employees（有经验的雇员）", "employer为雇主，与employee角色不同。"],
  ["think", "thinks thought thinking", "v.", "认为", "40题询问作者对影响的判断，以末段确定句作依据。", "think that ...（认为……）", "think询问立场不等于提出亲身经历。"],
  ["put", "puts putting", "v.", "使处于；造成", "put an end to整体为结束，不能沿用涂抹义。", "put an end to an era（结束一个时代）", "put过去式和分词仍为put，不写putted。"],
  ["side", "sides", "n.", "方面；一面", "bright side为积极面，是36题对比喻的解释。", "the bright side（光明的一面）", "此处不是站队的动词side with。"],
  ["before", "", "conj.", "在……之前", "Before it ends连接时间从句，非孤立副词此前。", "before the era ends（在这一时代结束之前）", "before后有主谓时为连词；后名词时可为介词。"],
  ["worsen", "worsens worsened worsening", "v.", "加重；恶化", "可改写reinforce class divides以突出社会差距恶化。", "worsen class divides（加剧阶层分野）", "worsen明确负面评价，reinforce本身中性但该宾语语境为负面。"],
  ["recession", "recessions", "n.", "经济衰退", "全文区分经济收缩期与延续更久的失业和社会影响。", "an economic recession（经济衰退）", "depression一般指更严重持久的萧条，不能任意替换。"],
  ["era", "eras", "n.", "时代；时期", "era of high joblessness为高失业时期，未必与衰退结束同步。", "an era of unemployment（失业时期）", "era强调具有某特征的较长时期。"],
  ["joblessness", "", "n.", "失业；无工作状态", "high joblessness指失业严重，不只是找工作困难的个人感受。", "high joblessness（高失业水平）", "jobless为失业的形容词，joblessness为状态名词，派生词不混计。"],
  ["course", "courses", "n.", "轨迹；进程", "life course为人生轨迹，不沿用课程义。", "the life course（人生历程）", "course还可课程、航线，本文描述生活发展路径。"],
  ["character", "characters", "n.", "性格；特性", "个人的character为性格，社会的character为社会特质。", "society's character（社会的特性）", "character在完形可为电影角色，本篇不能沿用人物角色义。"],
  ["generation", "generations", "n.", "一代人", "a generation of young adults指受到失业影响的同代青年。", "a generation of young adults（一代年轻成年人）", "generation还可指产生或发电，此处是人群代际。"],
  ["adult", "adults", "n.", "成年人", "young adults强调年轻但已成年的群体。", "young adults（年轻成年人）", "adult不是所有年龄儿童，需保留成年范围。"],
  ["ultimately", "", "adv.", "最终；归根结底", "把个人影响推进到长期政治文化社会影响。", "ultimately change society（最终改变社会）", "immediately是立即，ultimately不要求短期发生。"],
  ["reshape", "reshapes reshaped reshaping", "v.", "重塑；改变形态或特性", "可作用于政治、文化、社会结构，不必只是物理造型。", "reshape society（重塑社会）", "reshape强调重新形成，是否有利须由上下文判断。"],
  ["jobless", "", "adj. used as plural noun", "失业者", "the jobless为定冠词加形容词表示一类人，概括失业群体。", "the jobless（失业者）", "作群体通常按复数概念理解，不加joblesses。"],
  ["silver", "", "adj. / n.", "银色的；银", "silver linings整体比喻困境中的光明一面，不是实际金属。", "silver linings（困境中的光明面）", "需整体识别，不把经济灾难中的收益译成找银矿。"],
  ["lining", "linings", "n.", "衬里；边缘", "silver lining取乌云边缘的一线亮光的比喻。", "find a silver lining（找到困境中的希望）", "line线条与lining衬层是相关而非同一屈折词位。"],
  ["disaster", "disasters", "n.", "灾难", "national economic disaster指全国性经济困境。", "an economic disaster（经济灾难）", "不是只限于地震洪水等自然灾害。"],
  ["unemployment", "", "n.", "失业", "受访者在极痛苦的失业中发现局部正面变化。", "the pain of unemployment（失业的痛苦）", "employment就业与unemployment失业方向相反。"],
  ["painful", "", "adj.", "痛苦的", "while extremely painful是让步插入语，说明失业带来的痛苦。", "a painful experience（痛苦的经历）", "painful形容引起痛苦，不是疼痛名词pain。"],
  ["materialistic", "", "adj.", "物质至上的；重物质享受的", "less materialistic说明不再那么看重财富物质。", "a materialistic lifestyle（物质至上的生活方式）", "material材料的与materialistic价值取向不同。"],
  ["financially", "", "adv.", "在财务方面；花钱方面", "限定prudent，表金钱管理更谨慎，而非普遍性格胆小。", "financially prudent（理财谨慎的）", "financial形容词与financially副词功能不同。"],
  ["prudent", "", "adj.", "谨慎的；审慎的", "more financially prudent指消费与财务决策更谨慎。", "prudent spending（审慎消费）", "cautious较泛指小心，prudent强调周全判断避免风险。"],
  ["aware", "", "adj.", "意识到的；了解的", "aware of others' struggles表示更体会他人困境。", "be aware of difficulties（意识到困难）", "aware通常作表语，后用of引意识对象。"],
  ["struggle", "struggles struggled struggling", "n.", "艰辛；挣扎求存", "the struggles of others是他人面临的困难，不是彼此争斗。", "the struggles of others（他人的艰辛）", "struggle against彼此斗争不适合当前名词所有关系。"],
  ["respect", "respects", "n.", "方面", "in limited/many respects说明讨论维度，非尊敬的动作。", "in some respects（在某些方面）", "respect可为尊重，in ... respects则为在……方面。"],
  ["awake", "awoke awoken awakes awaking", "v.", "唤醒；醒来", "has awoken us from比喻让人摆脱不切实际的幻梦。", "awake from a dream（从梦中醒来）", "awake此处动词分词awoken，不是形容词醒着的。"],
  ["fever", "fevers", "n. used attributively", "狂热；发烧", "fever dream比喻狂热而不切实际的财富幻想。", "a fever dream（狂热幻梦）", "本文非诊断发烧症状，按经济愿望比喻理解。"],
  ["riches", "", "plural n.", "财富", "easy riches指轻松致富的幻想。", "easy riches（唾手可得的财富）", "rich形容富有，riches名词财富，不等于富人复数。"],
  ["reckless", "", "adj.", "不顾后果的；鲁莽的", "reckless personal spending指缺少财务约束的个人消费。", "reckless spending（挥霍无度的消费）", "brave勇敢可褒义，reckless批评忽视风险。"],
  ["spending", "", "n.", "消费；支出", "personal spending指个人开支，名词独立保留。", "personal spending（个人消费）", "spend为花费动词，本处spending是消费行为的名词。"],
  ["benefit", "benefits benefited benefiting", "n.", "好处；益处", "these benefits回指失业者感受到的有限正面变化。", "limited benefits（有限好处）", "benefit可为福利待遇，但此处不是政府补贴。"],
  ["thin", "thinner thinnest", "adj.", "微薄的；不充分的", "thin与uncertain、far off并列评价益处。", "thin benefits（微薄的好处）", "字面瘦、薄在此引申为分量有限。"],
  ["uncertain", "", "adj.", "不确定的；没有把握的", "评价好处是否出现及规模不明，而非否认社会一定受影响。", "uncertain benefits（不确定的好处）", "末句certain说影响存在，uncertain在此说益处不确定，对象不同。"],
  ["moral", "", "adj.", "道德的", "书名The Moral Consequences of Economic Growth讨论增长对社会品格的后果。", "moral consequences（道德后果）", "moral非morale士气，注意词形。"],
  ["consequence", "consequences", "n.", "后果；结果", "在书名中指经济增长的社会道德后果。", "the consequences of growth（增长的后果）", "consequence可好可坏，需由内容判断。"],
  ["historian", "historians", "n.", "历史学家", "economic historian为经济史研究者，不直接等同经济预测师。", "an economic historian（经济史学者）", "historical形容历史的，historian为从事研究的人。"],
  ["benjamin", "", "proper n.", "本杰明（人名）", "Benjamin Friedman为所引经济史学者姓名。", "Benjamin Friedman（本杰明·弗里德曼）", "人名整体保留，不凭同姓推为另一经济学家。"],
  ["friedman", "", "proper n.", "弗里德曼（姓氏）", "指本杰明·弗里德曼，提出长时期衰退的历史概括。", "Benjamin Friedman（本杰明·弗里德曼）", "不能因姓氏相同混同其他著名人物。"],
  ["lengthy", "lengthier lengthiest", "adj.", "漫长的；持续很久的", "lengthy periods限定经济停滞持续时长。", "lengthy periods of decline（漫长的衰退时期）", "length名词长度与lengthy形容漫长不并入原形。"],
  ["stagnation", "", "n.", "停滞", "经济长期不增长，与decline下降并列。", "economic stagnation（经济停滞）", "decline为下滑，stagnation强调停滞不前。"],
  ["mean-spirited", "", "adj.", "刻薄的；心胸狭窄的", "社会变得更加刻薄，作为leave的宾语补足语。", "a mean-spirited society（刻薄排他的社会）", "mean在复合词里是刻薄，不是平均或意味着。"],
  ["inclusive", "", "adj.", "包容的", "less inclusive表示更排斥他人或群体，与反移民情绪呼应。", "an inclusive society（包容的社会）", "exclusive可表排外或独有，inclusive强调广泛接纳。"],
  ["reverse", "reverses reversed reversing", "v.", "逆转；使倒退", "reverse the advance使权利自由的进步倒退。", "reverse progress（使进步倒退）", "stop为停止前进，reverse更进一步变为反向。"],
  ["advance", "advances advanced advancing", "n.", "进步；发展", "the advance of rights and freedoms为名词，区别Text3动词advances。", "the advance of rights（权利的发展）", "停止或逆转进步，与促进进步不是同方向。"],
  ["right", "rights", "n.", "权利", "rights and freedoms为社会权利与自由，并非方位或正确性。", "rights and freedoms（权利与自由）", "Text1 right为副词正确地，本句复数名词需隔离。"],
  ["freedom", "freedoms", "n.", "自由；各种自由权利", "复数指不同领域的自由，与rights并列。", "civil freedoms（公民自由）", "free形容词自由的与freedom名词不并入词形。"],
  ["anti-immigrant", "", "adj.", "反移民的", "修饰sentiment，指对移民的敌意。", "anti-immigrant sentiment（反移民情绪）", "anti-表示反对，不能漏译成移民本身的情绪。"],
  ["sentiment", "sentiments", "n.", "情绪；态度倾向", "社会层面的反移民情绪，不是具体法令。", "public sentiment（公众情绪）", "sentiment是态度，可影响行动但不自动等于政策。"],
  ["conflict", "conflicts", "n.", "冲突", "种族、阶层间冲突在经济困难时可能加剧。", "social conflict（社会冲突）", "competition可为规则内竞争，conflict强调对立冲突。"],
  ["race", "races", "n.", "种族；族群", "between races and classes指群体间的紧张，不是体育赛跑。", "conflict between races（种族间冲突）", "race可为赛跑，本句由social conflict确定族群义。"],
  ["inequality", "inequalities", "n.", "不平等；差距", "income inequality为收入分配差距。", "income inequality（收入不平等）", "差距缩小不自动等于所有人的收入增加。"],
  ["shrink", "shrinks shrank shrunk shrinking", "v.", "缩小；收缩", "has not shrunk说明这次收入差距未缩小。", "inequality shrinks（差距缩小）", "shrink过去式shrank、分词shrunk；本文not不可漏。"],
  ["weakness", "weaknesses", "n.", "疲弱；薄弱", "economic weakness为经济低迷状态，非个人性格懦弱。", "economic weakness（经济疲弱）", "weak形容词与weakness名词分开计数。"],
  ["reinforce", "reinforces reinforced reinforcing", "v.", "强化；加深", "reinforce class divides指阶层差距更加稳固。", "reinforce class divides（强化阶层分野）", "reinforce不一定是积极增强，宾语决定效果。"],
  ["divide", "divides divided dividing", "n.", "分野；鸿沟", "class divides为阶层壁垒，名词复数而非动词三单。", "class divides（阶层分野）", "divide作动词为分开，本文指社会群体间界限。"],
  ["till", "", "proper n.", "蒂尔（人名）", "Till Von Wachter中Till为研究者名字，非直到。", "Till Von Wachter（蒂尔·冯·瓦赫特）", "普通till可作直到的介词或连词，姓名处不能套用。"],
  ["von", "", "proper name component", "冯（姓名组成）", "Von为Till Von Wachter姓名一部分。", "Till Von Wachter（蒂尔·冯·瓦赫特）", "专名组成不编造一般英语动词义。"],
  ["wachter", "", "proper n.", "瓦赫特（姓氏）", "哥伦比亚大学经济学家的姓氏，39题研究来源。", "Till Von Wachter（蒂尔·冯·瓦赫特）", "保留用户原卷拼写。"],
  ["columbia", "", "proper n.", "哥伦比亚（大学名组成）", "Columbia University指哥伦比亚大学。", "Columbia University（哥伦比亚大学）", "Columbia与国家Colombia拼写不同，不译成哥伦比亚共和国大学。"],
  ["graduate", "graduates graduated graduating", "v. / n.", "毕业；毕业生", "graduating/had graduated为动词，题干graduates为毕业生名词。", "graduate in a recession（在经济衰退时毕业）", "graduate可名词与动词同词位；graduation为派生名词另记。"],
  ["dim", "dims dimmed dimming dimmer dimmest", "v.", "使黯淡；削弱", "life chances dimmed为过去分词宾补，人生机会受损。", "dim someone's prospects（使某人前景黯淡）", "dim亦可形容光线暗，此处对机会为比喻。"],
  ["elite", "elites", "adj.", "精英的；一流的", "elite universities为声望资源优越的名校。", "elite universities（精英大学）", "此处指学校类别，不把所有graduates概括为社会精英。"],
  ["catch", "catches caught catching", "v.", "赶上（catch up）", "名校生追赶的是经济景气时自己本可到达的发展轨迹。", "catch up to a level（赶上某一水平）", "不是赶上原文未出现的有经验员工。"],
  ["fairly", "", "adv.", "相当；较为", "fairly quickly表示恢复较快，不是以公平方式。", "fairly quickly（相当快地）", "fairly有公平地义，本句修饰程度取相当。"],
  ["otherwise", "", "adv.", "否则；在另一种条件下", "where they otherwise would have been指若未在衰退中毕业的反事实轨迹。", "otherwise would have been（在别种情况下本会达到）", "不是另外又一群人，而是同一人不同条件下的位置。"],
  ["mass", "masses", "n.", "大众；大批普通人", "the masses beneath them与名校毕业生形成阶层对照。", "the masses（普通大众）", "mass还可质量、大量，本句明确人群。"],
  ["beneath", "", "prep.", "在……之下", "beneath them表示社会机会或地位较低，不是物理位置。", "beneath the elite（处于精英阶层之下）", "没有贬低人的价值，只陈述文中地位差异。"],
  ["resentment", "", "n.", "怨愤；愤懑", "原文说这种情绪一直潜藏，互联网让其更容易观察。", "social resentment（社会怨愤）", "anger为愤怒，resentment常源于感到不公且积累较久。"],
  ["discern", "discerns discerned discerning", "v.", "辨明；识别", "discerning how...为动名词主语，说明辨明具体影响更难。", "discern a change（辨明变化）", "see泛指看到，discern强调仔细分辨看清。"],
  ["precisely", "", "adv.", "准确地；确切地", "修饰discerning，强调当下难以准确判断变化机制。", "discern precisely（准确辨明）", "不是只问有无变化，而是要精确了解如何变化。"],
  ["lean", "leaner leanest", "adj.", "艰难的；经济拮据的", "lean times与hard times同指经济不景气阶段。", "lean times（经济困难时期）", "lean还可瘦的或动词倚靠，本文不是身体外形。"],
  ["socially", "", "adv.", "在社会层面", "修饰tolerant，表示对不同群体的社会包容。", "socially tolerant（社会上包容差异的）", "不单指个人社交活跃。"],
  ["tolerant", "", "adj.", "宽容的；包容的", "进入衰退时较以往更包容，不能归因于衰退造成。", "a tolerant society（包容的社会）", "tolerate动词容忍，tolerant形容词，两者分开计数。"],
  ["poll", "polls polled polling", "n.", "民意调查", "national polls围绕社会冲突调查公众态度。", "national polls（全国民意调查）", "poll还可投票，此处为调查结果而非某次选举得票。"],
  ["mixed", "", "adj.", "不一致的；好坏参杂的", "mixed results不能支持全为积极或全为消极的统一判断。", "mixed results（不一致的结果）", "mixed不等于没有任何结果，而是结果方向复杂。"],
  ["fabric", "fabrics", "n.", "结构；组织体系", "social fabric比喻社会关系的交织整体。", "social fabric（社会结构）", "fabric本义织物，在此不译社会布料。"],
  ["extend", "extends extended extending", "v.", "延续；持续", "the longer they extend表示困难时期持续越久。", "hard times extend（困难时期持续）", "本文是时间延长，不是地理扩张。"],
  ["subsidy", "subsidies", "n.", "补贴；津贴", "36题干扰项，原文寻找积极面而非申请政府补助。", "government subsidies（政府补贴）", "benefits在本文为一般好处，不能自动译为政府津贴。"],
  ["bright", "brighter brightest", "adj.", "光明的；积极的", "bright side为正面意义，对应silver linings。", "the bright side（光明的一面）", "不是实际灯光明亮，而是对困境的积极看法。"],
  ["lifestyle", "lifestyles", "n.", "生活方式", "37题概括财富观、消费和理财方式的改变。", "reconsider one's lifestyle（反思生活方式）", "不是只换工作或改变学校成绩。"],
  ["prudence", "", "n.", "谨慎；审慎", "37题C与原文更审慎相对，不能误读成谨慎被挑战。", "financial prudence（理财审慎）", "prudent形容词与prudence名词派生关系，不合并词形。"],
  ["evil", "evils", "n.", "恶；恶劣倾向", "38题概括衰退激发的刻薄、排斥和冲突。", "evils of human nature（人性的消极恶面）", "不要把may bring out读成人必然全然邪恶。"],
  ["immigrant", "immigrants", "n.", "移民", "38题干扰项借用了反移民情绪，但未给经济负担证据。", "a burden on immigrants（移民的负担）", "emigrant侧重迁出者，immigrant侧重迁入者。"],
  ["lag", "lags lagged lagging", "v.", "落后", "39题干扰项误把名校生与被落下的大众交换。", "lag behind others（落后于他人）", "catch up赶上与lag behind落后方向相反。"],
  ["experienced", "", "adj.", "有经验的", "39题B添加原文没有的experienced employees参照群体。", "experienced employees（有经验的员工）", "原文追赶的是自身反事实发展水平，不是工龄较长者。"],
  ["recover", "recovers recovered recovering", "v.", "恢复；赶上受损前的发展轨迹", "39题D概括名校毕业生较快补上衰退造成的落差。", "recover more quickly（恢复得更快）", "此处是人生就业机会恢复，不是医疗康复。"],
  ["trivial", "", "adj.", "微不足道的", "40题与作者强调多年、整个社会结构的影响相反。", "a trivial influence（微不足道的影响）", "影响形态未明不等于影响很小。"],
  ["destructive", "", "adj.", "破坏性的", "40题语义过于确定负面方向，末段只肯定会改变。", "a destructive effect（破坏性影响）", "certain肯定存在，destructive判断性质，不是同一维度。"],
];
const reviewed = reviewedLexicon(rows);
export const passage2012P4Lexicon = reviewed.entries;
export const passage2012P4LemmaAliases: Record<string, string> = { ...reviewed.aliases, ...Object.fromEntries(rows.map(([headword]) => [headword, headword])), "society's": "society", "others'": "other", "u.s.": "u.s." };
export const passage2012P4CollocationGlosses = reviewed.glosses;
export const passage2012P4FormPartOfSpeech: Record<string, string> = { graduating: "v.-ing（定语）", graduated: "v.-ed（过去完成时）", graduates: "n.", dimmed: "v.-ed（宾补）", divides: "n.", respects: "n.", better: "adv. / adj.", discerning: "gerund", entering: "v.-ing（时间状语）", hidden: "v.-ed（被动）", before: "conj.", harder: "adv.（比较级）", decreased: "v.-ed（分词定语）", great: "adj." };
passage2012P4Lexicon.character.otherMeanings = ["（小说电影）角色；品格；文字字符。Chinese characters汉字。"];
passage2012P4Lexicon.course.otherMeanings = ["课程；航线；一道菜；过程。of course当然，in the course of在……过程中。"];
passage2012P4Lexicon.respect.otherMeanings = ["尊敬、尊重（名词/动词）；顾及、遵守（respect rules）。in respect of关于。"];
passage2012P4Lexicon.fabric.otherMeanings = ["布料；织物；构造、基本框架，如the fabric of a building建筑结构。"];
passage2012P4Lexicon.lean.otherMeanings = ["瘦的；精简高效的（lean production精益生产）；v. 倚靠、倾斜、倾向于。"];
export const passage2012P4SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2012-p4-s1": { over: { contextualMeaning: "结束", use: "may be over推测衰退可能结束，非在上方。" } },
  "2012-p4-s2": { it: { contextualMeaning: "高失业时期", use: "两次it都回指前句era of high joblessness。" } },
  "2012-p4-s3": { it: { contextualMeaning: "高失业时期", use: "长期失业可能影响整个社会，非个别年轻人。" } },
  "2012-p4-s4": { hard: { contextualMeaning: "努力地", use: "harder为副词比较级，修饰tries，不是更硬的材料。", partOfSpeech: "adv." } },
  "2012-p4-s5": { many: { contextualMeaning: "许多失业者", use: "省略people作主语，承接上句jobless。" }, while: { contextualMeaning: "虽然；尽管", use: "while extremely painful为让步省略从句，非时间同时。" }, they: { contextualMeaning: "这些失业者", use: "解释他们所感受到的心理和财务变化。" } },
  "2012-p4-s6": { leave: { contextualMeaning: "使……处于某状态", use: "leave society better off为宾语加结果补语，不是离开社会。" } },
  "2012-p4-s7": { it: { contextualMeaning: "经济衰退", use: "共享主语支配has awoken和put an end to。" }, easy: { contextualMeaning: "轻易获得的", use: "easy riches指不费力发财的幻想。" } },
  "2012-p4-s9": { leave: { contextualMeaning: "使……变得", use: "left society后接两组社会特征宾补，不是留下某人离开。" } },
  "2012-p4-s10": { do: { contextualMeaning: "代替increases，表示也增加", use: "as does conflict为倒装，does代替上句实义谓语。" }, as: { contextualMeaning: "……也同样如此", use: "引冲突增加的相似情况，不是因果because。" } },
  "2012-p4-s11": { it: { contextualMeaning: "收入不平等；收入差距", use: "has not shrunk否定差距缩小，不是否定收入减少。" }, one: { contextualMeaning: "这一次衰退", use: "this one代替前面的a recession。" }, fall: { contextualMeaning: "下降；缩小", use: "income inequality falls为收入差距缩小。" } },
  "2012-p4-s12": { they: { contextualMeaning: "阶层鸿沟", use: "them在cross them中作宾语，回指class divides。" }, cross: { contextualMeaning: "跨越", use: "跨越阶层分野指社会流动，不是过马路。" }, reinforce: { contextualSubstitutions: [{ label: "worsen", chinese: "加剧", fit: "direct", rewrittenSentence: "Indeed, this period of economic weakness may worsen class divides, and decrease opportunities to cross them – especially for young people.", nuance: "worsen更明确负面评价；reinforce强调使阶层鸿沟更稳固，结合本文同样为不利变化。", target: "word:worsen" }] } },
  "2012-p4-s13": { chance: { contextualMeaning: "人生机会；发展前景", use: "life chances受毕业时期和教育资源影响。" }, they: { contextualMeaning: "精英大学毕业生", use: "they would have been/they had graduated及beneath them都回指名校生。" }, it: { contextualMeaning: "强调句形式成分", use: "it is ... that强调被落下的是普通大众，不回指某件事。" } },
  "2012-p4-s14": { it: { contextualMeaning: "形式主语", use: "真正主语为to see the resentment及其修饰从句。" } },
  "2012-p4-s15": { time: { contextualMeaning: "时期；日子", use: "lean times为经济困难时期，不是次数。" } },
  "2012-p4-s16": { its: { contextualMeaning: "美国的", use: "its history为美国历史，非互联网历史。" }, then: { contextualMeaning: "进入此次衰退的那时", use: "since then以进入衰退为民调时间起点。" } },
  "2012-p4-s18": { they: { contextualMeaning: "艰难的经济时期", use: "两处they均指hard times，非失业者个人。" }, it: { contextualMeaning: "社会结构与关系体系", use: "回指social fabric。" }, so: { contextualMeaning: "如此改变社会", use: "all the more so省略重复结果，so替代reshape it。" } },
};
