import type { Question, SentenceAnalysis } from "./data";
import { sentenceFactory, segment, clause } from "./2011-content-helpers";

const sentence = sentenceFactory("2012-cloze");
export const cloze2012Sentences: SentenceAnalysis[] = [
  sentence(1, [
    segment("Millions of Americans and foreigners ", "subject", "数量词加并列名词", "主语", "see的感知者", "millions of表示数以百万计，并非精确人数。"),
    segment("see G.I. Joe as a mindless war toy, ", "predicate", "see A as B复合宾语结构", "谓语及宾语补足语", "把G.I. Joe看作什么", "as后是对玩具形象的评价；mindless批评其缺乏思考。"),
    segment("the symbol of American military adventurism, ", "modifier", "名词短语", "同位语", "解释a mindless war toy", "of连接象征所代表的军事冒险主义，不是玩具的物理组成。"),
    segment("but that's not how it used to be.", "connector", "but并列分句，内含how表语从句", "转折", "对照今天形象与过去形象", "that指上述看法；used to be表示过去的状况，not否定与过去相同。"),
  ], "Millions of Americans and foreigners see G.I. Joe as a mindless war toy, but that's not how it used to be.", "数百万美国人和外国人把G.I. Joe看成无头脑的战争玩具、美国军事冒险主义的象征，但它过去并非如此。", "在数百万美国人和外国人眼中，G.I. Joe是一个无脑战争玩具，象征着美国的军事冒险主义；但它最初不是这样的。", "以今昔反差引出普通士兵形象，不能把开头的负面印象当成全文结论。", ["see G.I. Joe as a mindless war toy", "used to be"], [clause("how it used to be", "表语从句", "how", "充当is not后的表语", "it", "used to be", "how表示过去的状况", "先译过去是什么样，再理解not否定今日形象与之相同。")]),
  sentence(2, [
    segment("To the men and women ", "modifier", "to介词短语的开头", "视角状语", "限定was的评价者", "这些人与后面的the people共同作to的宾语。"),
    segment("who served in World War II ", "modifier", "who定语从句", "后置定语", "修饰men and women", "served在二战背景中是服役，不是提供餐饮。"),
    segment("and the people they liberated, ", "modifier", "并列名词加省略关系代词的定语从句", "视角状语的第二对象", "与men and women并列", "they指服役的男女；the people是liberated的宾语先行词。"),
    segment("the G.I. was the common man grown into hero, ", "predicate", "主系表加过去分词定语", "主句", "说明G.I.的真实身份", "common是平凡普通；grown into hero修饰man，强调成长为英雄的结果。原文hero前没有冠词。"),
    segment("the poor farm kid torn away from his home, ", "modifier", "名词同位语加过去分词短语", "同位说明", "解释the common man", "torn away被迫离开，his指农家孩子；不是主动旅行。"),
    segment("the guy who bore all the burdens of battle, ", "modifier", "同位名词加who定语从句", "同位说明和定语", "guy与man同指；who修饰guy", "bore是bear的过去式，宾语为战争的全部重担。"),
    segment("who slept in cold foxholes, ", "modifier", "并列who定语从句", "定语", "继续修饰guy", "foxholes在战争语境是散兵坑，in表示睡觉的地点。"),
    segment("who went without the necessities of food and shelter, ", "modifier", "并列who定语从句", "定语", "继续修饰guy", "go without表示没有某物而勉强维持，food和shelter说明必需品内容。"),
    segment("who stuck it out and drove back the Nazi reign of murder.", "modifier", "who从句含并列谓语", "定语", "继续修饰guy", "stuck it out为坚持到底，drove back为击退；两个过去式共有who主语。"),
  ], "the G.I. was the common man.", "对于在二战中服役的男女和他们解放的人民来说，美国兵是成长为英雄的普通人，是被迫离乡的贫苦农家孩子，是承担战争重担、睡在冰冷散兵坑里、缺乏食物和住所却坚持到底并击退纳粹杀戮统治的人。", "在二战军人及被他们解放的人们看来，美国兵原本只是平凡人：贫苦的农家孩子被迫背井离乡，扛起战争的全部重担，睡冷冰冰的散兵坑，连食物和栖身之所都没有，却仍坚持作战，击退了纳粹的残暴统治。", "用多组同位语和定语从句累积普通士兵的苦难与贡献，为1—4题提供整体语境。", ["grown into hero", "torn away from his home", "went without", "stuck it out", "drove back"], [
    clause("who served in World War II", "定语从句", "who", "修饰men and women", "who", "served", "in World War II为背景状语", "先确定男女军人，再补充二战服役背景。"),
    clause("they liberated", "省略宾语关系代词的定语从句", "省略that/whom", "修饰the people", "they", "liberated", "被省略的关系代词作宾语，指people", "译为他们所解放的人民。"),
    clause("who bore all the burdens of battle", "定语从句", "who", "修饰guy", "who", "bore", "all the burdens of battle", "先译他承担重担。"),
    clause("who slept in cold foxholes", "定语从句", "who", "修饰guy", "who", "slept", "in cold foxholes为地点状语", "并列补充住宿的艰苦。"),
    clause("who went without the necessities of food and shelter", "定语从句", "who", "修饰guy", "who", "went without", "the necessities of food and shelter", "译为缺乏食物和住所等必需条件。"),
    clause("who stuck it out and drove back the Nazi reign of murder", "定语从句", "who", "修饰guy", "who", "stuck ... out / drove back", "it（习语宾语）/ the Nazi reign of murder", "先译坚持，再译击退残暴统治。"),
  ]),
  sentence(3, [
    segment("This was not a volunteer soldier, not someone well paid, ", "predicate", "主系表及并列否定表语", "主句的否定部分", "说明This所指士兵不是谁", "well paid为someone的分词定语，指报酬优厚，不是道德高尚。"),
    segment("but an average guy, ", "connector", "but加名词表语", "纠正前面的否定", "与not a volunteer soldier相对", "not A but B表示不是A而是B；was由前半句共用。"),
    segment("up against the best trained, best equipped, fiercest, most brutal enemies seen in centuries.", "modifier", "形容词性习语加名词短语", "补充处境", "说明an average guy面对的敌手", "up against表示面对强敌；四组最高级共同限定enemies；seen in centuries为其分词定语。"),
  ], "This was not a volunteer soldier, not someone well paid, but an average guy.", "这不是一个志愿兵，也不是报酬优厚的人，而是面对几个世纪以来训练最有素、装备最精良、最凶猛残暴的敌人的普通人。", "他不是拿着优厚薪饷的志愿兵，只是一个普通人，却要迎战几个世纪以来训练、装备最强、最凶残的敌军。", "普通人的平凡身份与敌人的强大形成反差。", ["not a volunteer soldier, not someone well paid, but an average guy", "up against"]),
  sentence(4, [segment("His name ", "subject", "物主限定词加名词", "主语", "is的主语", "His指普通美国兵的统称G.I. Joe。"), segment("isn't much.", "predicate", "否定系表结构", "谓语及表语", "评价名称", "not much在此是没什么特别，而非姓名字数少。")], "His name isn't much.", "他的名字没什么了不起。", "他的名字也很普通。", "从军人经历转向名称的平民意味。", []),
  sentence(5, [segment("G.I. is just a military abbreviation ", "predicate", "主系表", "主句第一分句", "解释G.I.的形式", "just强调不过是；abbreviation指缩略语。"), segment("symbolizing Government Issue, ", "modifier", "现在分词短语", "后置定语", "修饰abbreviation", "symbolizing表示代表Government Issue这一名称。第7题依据核验参考答案取C，不把meaning说成语法错误。"), segment("and it was on all of the articles handed out to soldiers.", "connector", "and并列主系表；内含分词定语", "补充使用场景", "it回指G.I.缩写", "articles此处是物品；handed out to soldiers为被动分词定语，修饰articles。")], "G.I. is a military abbreviation, and it was on all of the articles.", "G.I.只是一种代表‘政府配发’的军事缩写，它出现在所有发给士兵的物品上。", "G.I.原本只是Government Issue（政府配发）的军用缩写，发给士兵的所有物品上都印着它。", "说明称呼源自普通军需用品，而非特殊身份。", ["handed out to soldiers"]),
  sentence(6, [segment("And ", "connector", "承接连词", "话题连接", "承接G.I.的解释", "And把话题从G.I.引向Joe。"), segment("Joe?", "object", "专名组成的省略问句", "设问对象", "询问Joe名称的意味", "原句省略谓语，不得把推想的what about补入主干。")], "And Joe?", "那么，Joe呢？", "那Joe这个名字呢？", "设问引出下一句的回答。", []),
  sentence(7, [segment("A common name for a guy ", "object", "独立名词短语", "承接设问的省略回答", "解释Joe", "原文不是完整陈述句，省去的主语和系词不补入主干。"), segment("who never made it to the top.", "modifier", "who定语从句", "定语", "修饰guy", "make it to the top指跻身上层；never否定这种成功。")], "A common name for a guy.", "一个从未登上社会顶层的普通人的常见名字。", "这是再普通不过的名字，属于那些从未跻身社会上层的小人物。", "用习语突出平凡身份，对应第9题。", ["made it to the top"], [clause("who never made it to the top", "定语从句", "who", "修饰guy", "who", "never made", "it；to the top表示到达地位", "译为从未跻身上层的人。")]),
  sentence(8, [segment("Joe Blow, Joe Palooka, Joe Magrac…", "subject", "并列专名", "举例", "列举平民化的Joe称呼", "这些是姓名，不逐字译成吹气或其他普通词义。保留原卷Magrac拼写。"), segment("a working class name.", "object", "概括性名词短语", "同位概括", "评价前面的名字", "working class为工人阶级；此处为无谓语的修辞片段。")], "Joe Blow, Joe Palooka, Joe Magrac…a working class name.", "Joe Blow、Joe Palooka、Joe Magrac……一个工人阶级的名字。", "无论是Joe Blow、Joe Palooka还是Joe Magrac，都是劳动者式的普通名字。", "通过列举强化名称的阶层含义。", ["working class"]),
  sentence(9, [segment("The United States ", "subject", "国家专名", "主语", "has had的主语", "United States作为国家名按单数处理。"), segment("has never had ", "predicate", "否定现在完成时", "谓语", "说明文章写作时点以前的经历", "never表示从未；这是原文历史时点的说法，不是对今日美国历任领导人的统计。"), segment("a president or vice-president or secretary of state Joe.", "object", "并列职务名词加姓名", "宾语", "说明没有过的领导人称呼", "Joe限定名字；secretary of state指国务卿。")], "The United States has never had a president or vice-president or secretary of state Joe.", "美国此前从未有过一位叫Joe的总统、副总统或国务卿。", "按作者当时的说法，美国还不曾有过叫Joe的总统、副总统或国务卿。", "以历史时点的修辞性例子对照社会上层，不能用后来人事变化改原题。", ["secretary of state"]),
  sentence(10, [segment("G.I. Joe had a distinguished career ", "predicate", "主谓宾", "主句", "叙述军旅经历", "distinguished形容卓越出色；career不是此处的商业职业规划。"), segment("fighting German, Japanese, and Korean troops.", "modifier", "现在分词短语", "经历内容的补充", "说明career中的作战活动，逻辑主语G.I. Joe", "fighting后接交战对象，三国形容词共同修饰troops。")], "G.I. Joe had a distinguished career.", "G.I. Joe在与德国、日本和朝鲜军队作战中有过卓越的军旅经历。", "从对德、对日作战到朝鲜战场，G.I. Joe这个形象有着非凡的军旅经历。", "由名称转入人物形象的历史和电影再现。", ["a distinguished career"]),
  sentence(11, [segment("He appears as a character, or a collection of American personalities, ", "predicate", "主谓语加as身份结构", "主句", "He指G.I. Joe", "or重述角色是多种美国人性格的集合，不是说影片有若干名字相同的人。"), segment("in the 1945 movie The Story of G.I. Joe, ", "modifier", "介词短语及片名同位语", "出现媒介状语", "修饰appears", "in说明在哪部影片中出现，不是现实地点。"), segment("based on the last days of war correspondent Ernie Pyle.", "modifier", "过去分词短语", "后置说明", "修饰movie，说明影片素材", "based on表示以……为依据；war correspondent为战地记者，Ernie Pyle为其姓名。")], "He appears as a character, or a collection of American personalities, in the 1945 movie The Story of G.I. Joe.", "在1945年的电影《大兵乔的故事》中，他作为一个角色，或者说多种美国人性格的集合出现；影片依据战地记者厄尼·派尔最后的日子创作。", "1945年的电影《大兵乔的故事》以战地记者厄尼·派尔生命最后阶段的经历为素材，塑造了这一汇集多种美国人性格的角色。", "将平民军人的抽象形象具体化为影视角色。", ["a collection of American personalities", "based on"]),
  sentence(12, [segment("Some of the soldiers ", "subject", "部分数量名词短语", "主语", "portrayed的施事", "some不能译成全部；of限定某个士兵群体中的部分。"), segment("Pyle interviewed ", "modifier", "省略关系代词的定语从句", "定语", "修饰soldiers", "Pyle为从句主语，士兵是interviewed的宾语。"), segment("portrayed themselves in the film.", "predicate", "一般过去时主谓宾", "主句谓语", "soldiers演谁", "themselves反身代词与soldiers同指，意为本人出镜演自己。")], "Some of the soldiers portrayed themselves in the film.", "派尔采访过的一些士兵在影片中扮演他们自己。", "派尔采访过的部分士兵在电影中本色出演。", "进一步把艺术形象与真实军人经历联系起来。", ["portrayed themselves"], [clause("Pyle interviewed", "省略宾语关系代词的定语从句", "省略that/whom", "修饰soldiers", "Pyle", "interviewed", "关系代词省略，指soldiers", "先译派尔采访过的士兵，再译主句本色出演。")]),
  sentence(13, [segment("Pyle was famous for covering the human side of the war, ", "predicate", "主系表加for动名词", "主句", "说明派尔成名原因", "human side为普通人的生活与感受，不是军事实力或伦理原则。"), segment("writing about the dirt-snow-and-mud soldiers, ", "modifier", "现在分词短语", "具体说明", "解释covering的报道内容", "复合定语生动写士兵满身尘土、积雪和泥浆。"), segment("not how many miles were gained ", "modifier", "否定的间接疑问从句", "与soldiers对照的报道对象", "仍受writing about支配", "how many miles作从句主语；were gained为被动，指战线推进距离。"), segment("or what towns were captured or liberated.", "connector", "or连接第二个间接疑问从句", "并列宾语", "与how many miles从句并列", "what towns为主语，两个被动分词共用were；整个从句在not范围内。")], "Pyle was famous for covering the human side of the war.", "派尔以报道战争中人的一面著名，写那些满身尘土、积雪与泥浆的士兵，而不是推进了多少英里或占领、解放了哪些城镇。", "派尔的报道以关注战争中的人而闻名。他写的是风尘泥雪中的普通士兵，而非战线推进了多远、哪些城镇被攻占或解放。", "人性关怀与战报数字对照，约束14、15题。", ["was famous for", "the human side of the war"], [clause("how many miles were gained", "间接疑问宾语从句", "how many", "作about后的否定并列宾语", "how many miles", "were gained", "无另加宾语，被动结构", "译为推进了多少英里，再带入not范围。"), clause("what towns were captured or liberated", "间接疑问宾语从句", "what", "与前一个宾语从句并列", "what towns", "were captured or liberated", "无另加宾语", "译为哪些城镇被占领或解放，两件事都不是报道重心。")]),
  sentence(14, [segment("His reports ", "subject", "物主限定词加名词", "主语", "paralleled的比较对象之一", "His指派尔；reports是新闻报道。"), segment("paralleled the \"Willie\" cartoons ", "predicate", "主谓宾中的谓宾部分", "谓语", "说明报道与漫画的关系", "parallel作动词表示相似、相呼应，不是复制或互相矛盾。"), segment("of famed Stars and Stripes artist Bill Mauldin.", "modifier", "of所属结构", "定语", "修饰cartoons", "Stars and Stripes是《星条旗报》，Bill Mauldin为画家；famed形容其知名。")], "His reports paralleled the \"Willie\" cartoons.", "他的报道与著名《星条旗报》画家比尔·莫尔丁的‘威利’漫画相呼应。", "他的报道与《星条旗报》著名画家比尔·莫尔丁创作的‘威利’漫画有异曲同工之处。", "下句Both men总结二人共有关注点。", ["Stars and Stripes"]),
  sentence(15, [segment("Both men emphasized the dirt and exhaustion of war, ", "predicate", "主谓宾", "主句", "Both men指派尔与莫尔丁", "emphasized为突出呈现，不表示赞美战争的肮脏。"), segment("the fragments of civilization ", "object", "第二组名词宾语", "并列报道对象", "与dirt and exhaustion共同作emphasized宾语", "fragments比喻战争中残存的文明生活片段。"), segment("that the soldiers shared with each other and the civilians: ", "modifier", "that定语从句", "定语", "修饰fragments of civilization", "that作shared宾语；with连接分享对象，包括战友和平民。"), segment("coffee, tobacco, whiskey, shelter, sleep.", "modifier", "冒号后的名词列举", "具体举例", "解释fragments所指生活内容", "这不是新的完整从句，不凭空增加谓语。")], "Both men emphasized the dirt and exhaustion of war, the fragments of civilization.", "两人都着重表现战争的肮脏与疲惫，以及士兵彼此之间和与平民分享的文明生活片段：咖啡、烟草、威士忌、住处和睡眠。", "两人笔下都有战争的污秽与疲惫，也有士兵同战友和平民共享的点滴文明生活——咖啡、烟草、威士忌、栖身之所和睡眠。", "具体列举解释18题为何是片段，而不是阶段、幻觉或进步。", ["shared with each other and the civilians", "each other"], [clause("that the soldiers shared with each other and the civilians", "定语从句", "that", "修饰fragments of civilization", "the soldiers", "shared", "that为宾语，with后是分享对象", "先理解文明生活的片段，再补充分享给谁。")]),
  sentence(16, [segment("To Egypt, France, and a dozen more countries, ", "modifier", "to加并列国家名词", "视角状语", "限定was的评价范围", "国家借指这些国家的人们；to不是前往的方向。"), segment("G.I. Joe was any American soldier, ", "predicate", "主系表", "主句", "解释该称呼涵盖谁", "any强调无论哪一位美国兵，而非特定个体。"), segment("at that point the most important person in their lives.", "modifier", "时间状语加名词同位补充", "补充评价", "说明soldier在当时的重要性", "at that point限定历史时刻，their指上述国家的人们。")], "G.I. Joe was any American soldier.", "对埃及、法国和另外十多个国家来说，G.I. Joe就是任何一名美国士兵，在那个时刻是他们生命中最重要的人。", "在埃及、法国以及另外十多个国家的人们眼中，每一位美国兵都是G.I. Joe——在那个时刻，他们是这些人生命中最重要的人。", "结尾回扣普通士兵的意义，与首句玩具形象形成对比。", ["a dozen more countries", "at that point"]),
];

const questionRows: Array<[number, number, string[], Question["answer"], string, string[]]> = [
  [1, 2, ["served", "performed", "rebelled", "betrayed"], "A", "定语从句修饰二战中的男女，下文liberated说明其军人身份。", ["serve in a war表示参战服役。", "perform通常指完成任务或表演，不能在此直接表达服兵役。", "rebel是反叛，原文未说他们反抗本国政权。", "betray表示背叛，不能与解放人民的正面描写衔接。"]],
  [2, 2, ["actual", "common", "special", "normal"], "B", "hero与下文poor farm kid、average guy对照的是普通身份。", ["actual强调真实而非虚构，未表达平凡出身。", "common man为普通人，和成长为英雄形成反差。", "special为特别的，与average guy相反。", "normal强调正常而非异常，此处不是正常与反常的对照。"]],
  [3, 2, ["loaded", "eased", "removed", "bore"], "D", "宾语all the burdens of battle要求表达承受战争重担。", ["load指装载，常用load A with B，非此处承担。", "ease是减轻，与列举艰辛的方向不同。", "remove是移除，文中说士兵承受而非消除了重担。", "bore是bear过去式，bear burdens是承担重担。"]],
  [4, 2, ["necessities", "facilities", "commodities", "properties"], "A", "冒出的food and shelter是维持生存的基本条件。", ["necessities为必需品，准确概括食物和住处。", "facilities为设施，食物不属于设施。", "commodities强调交易商品，此处不是市场买卖。", "properties指财产或特性，不表达生存必需条件。"]],
  [5, 3, ["and", "nor", "but", "hence"], "C", "前面连用not，后面an average guy是作者确认的身份。", ["and只添加，不形成不是而是的纠正关系。", "nor继续否定，会错误地否认他是普通人。", "not ... but ...：不是……而是……。", "hence为因此，不能作为这里的转折连词。"]],
  [6, 3, ["for", "into", "from", "against"], "D", "up后接强大的敌人，说明普通士兵面对的对手。", ["up for表示准备参加或可供选择，不是面对强敌。", "up into表示向上进入，需要运动含义，此处没有。", "from表来源，与面对敌人的含义不同。", "up against为面对、与……对抗。"]],
  [7, 5, ["implying", "meaning", "symbolizing", "claiming"], "C", "中国教育在线与哈尔滨工程大学所载解析均列C，强调缩写代表Government Issue；这不是仅靠语法能排除B的题。", ["imply是间接暗示，此处直接解释缩写代表的名称。", "meaning在解释缩写时语言上可以成立，不能说它不合语法；此题核验参考解析采用强调符号代表的C。", "symbolizing为代表、象征；两份已核验参考解析均据缩写代表全称选C。", "claim是声称主张，缩写并未提出有争议的断言。"]],
  [8, 5, ["handed out", "turned over", "brought back", "passed down"], "A", "articles为军需物品，后接to soldiers说明配发对象。", ["hand out是分发，与军用品发给士兵相合。", "turn over偏移交管理或控制权，不是这里的一般配发。", "bring back强调带回来，文中无返回地点。", "pass down指代代相传，军需配给没有传承含义。"]],
  [9, 7, ["pushed", "got", "made", "managed"], "C", "固定结构___ it to the top概括是否跻身上层。", ["push it指推动它，不构成取得成功的本习语。", "get to the top可以成立，但原文还有it，不能填got it to表达本人成功。", "make it to表示成功到达，made it to the top为跻身上层。", "manage to do需要不定式动词，此处是it to the top。"]],
  [10, 9, ["ever", "never", "either", "neither"], "B", "按作者写作时点，前句never made it to the top在领导人姓名上举例。", ["ever常见于问句或条件句，不能表达这里的从未。", "never否定过去截至文章时点的经历，呼应普通人身份。", "either表示也时常用于否定句尾，不能在此代替never。", "neither表示两者都不，后面不是两个对等选择的主语。"]],
  [11, 10, ["disguised", "disturbed", "disputed", "distinguished"], "D", "本段承接普通军人的历史贡献，评价其军旅生涯。", ["disguised指伪装，不等于卓越。", "disturbed指被打扰或不安，文中无此评价。", "disputed为有争议的，下文没有争论其生涯真伪。", "distinguished表示卓越、杰出的，符合正面评价。"]],
  [12, 11, ["company", "community", "collection", "colony"], "C", "or重述a character为多种American personalities的综合。", ["company为公司、陪伴或一群人，不是性格特征的综合体。", "community强调共同生活的群体，电影角色不是社区。", "a collection of为一系列的集合，指多种美国人性格集于一身。", "colony为殖民地或生物群落，不表达角色集合。"]],
  [13, 12, ["employed", "appointed", "interviewed", "questioned"], "C", "上句明确Pyle是war correspondent，军人后来在电影中演自己。", ["employ指雇用，没有记者雇用士兵的依据。", "appoint为任命，派尔不是在给士兵任职。", "interview为记者采访，符合其身份与报道活动。", "question可指询问或审问，但采访报道的职业语境以interview最准确。"]],
  [14, 13, ["human", "military", "political", "ethical"], "A", "writing about ... soldiers与not how many miles、what towns对比报道重心。", ["human为人的一面，关注士兵日常苦难和感受。", "military着重军事方面，恰是后面被排除的战绩数字。", "political为政治的，文中未谈政权或政策报道。", "ethical为伦理道德的，不能等同描写普通人的处境。"]],
  [15, 13, ["ruined", "commuted", "patrolled", "gained"], "D", "与城镇被占领、解放并列的是战线推进的距离。", ["ruin为毁坏，不能用多少英里被毁表达战线进展。", "commute为通勤或减刑，不合战场语境。", "patrol为巡逻，尽管可以巡行某片区域，但此处对照战果而非巡逻路线。", "gain在这里是取得推进距离，配合miles表示战线推进。"]],
  [16, 14, ["paralleled", "counteracted", "duplicated", "contradicted"], "A", "下句Both men概括记者与画家共同关注的内容。", ["parallel作动词为相似、相呼应，下句正解释其共同点。", "counteract是抵消作用，二人的作品不是相互抵消。", "duplicate是复制，题中只有关注相似，未说抄袭或重制。", "contradict是相矛盾，和Both men的相同关注不符。"]],
  [17, 15, ["neglected", "emphasized", "avoided", "admired"], "B", "前文famous for covering说明二人重点呈现士兵真实生活。", ["neglect为忽略，与特意描写日常艰辛相反。", "emphasize为强调、突出呈现，符合报道与漫画的共同特点。", "avoid为回避，原文列出的正是他们书写的内容。", "admire为赞赏，呈现战争疲惫不等于欣赏其苦难。"]],
  [18, 15, ["stages", "illusions", "fragments", "advances"], "C", "冒号后是咖啡、烟草、住处等战争间隙的日常文明生活。", ["stages为发展阶段，几种生活物品并非历史分期。", "illusions为幻觉，士兵分享的物品和住处真实存在。", "fragments为碎片或片段，比喻战争中残存的正常生活。", "advances为进步，所列事物并未说明文明的进步过程。"]],
  [19, 16, ["With", "To", "Among", "Beyond"], "B", "主句说美国兵对这些国家民众的意义，需要评价视角。", ["with为伴随或拥有，不直接引出对谁而言。", "to为对……来说，国家借指其人民。", "among为在一群之中，句子并非给国家内部位置分类。", "beyond为超出，文中不表范围之外。"]],
  [20, 16, ["on the contrary", "by this means", "from the outset", "at that point"], "D", "最重要的人是特定战争历史时刻的评价，而非永远的身份。", ["on the contrary表示恰恰相反，与前句无此矛盾。", "by this means是通过这种方式，前面未给方法。", "from the outset表示从一开始，文中未讨论起始阶段。", "at that point为在那个时候，限定士兵的重要性。"]],
];
export const cloze2012Questions: Question[] = questionRows.map(([number, sentenceNumber, options, answer, locating, reasons]) => ({
  id: 201200 + number, number, sentenceId: `2012-cloze-s${sentenceNumber}`, prompt: `第${number}空`, answer, locating,
  options: options.map((text, index) => ({ key: "ABCD"[index] as Question["answer"], text })),
  explanations: { A: reasons[0], B: reasons[1], C: reasons[2], D: reasons[3] },
}));
for (const item of cloze2012Sentences) {
  let testText = item.text;
  const questions = cloze2012Questions.filter(question => question.sentenceId === item.id);
  item.answerWords = questions.map(question => question.options.find(option => option.key === question.answer)!.text);
  for (const question of questions) {
    const answer = question.options.find(option => option.key === question.answer)!.text;
    const source = question.number === 19 ? "To" : answer;
    const start = question.number === 5 ? testText.indexOf("but an average") : testText.indexOf(source);
    testText = testText.slice(0, start) + `___(${question.number})` + testText.slice(start + source.length);
  }
  if (questions.length) item.testText = testText;
}
