import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";
const rows: LexiconRow[] = [
  ["universal", "", "adj.", "世界范围的；全人类的", "修饰history，强调人类历史总体。", "universal history（世界通史）", "universal也可指普遍适用；不是单指宇宙天体史。"],
  ["accomplish", "accomplishes accomplished accomplishing", "v.", "完成；成就", "what为其宾语，指人类所做成的事情。", "accomplish a task（完成任务）", "achieve强调取得目标或成果，accomplish强调做成任务。"],
  ["here", "", "adv.", "在这里；在这世上", "回指this world，修饰have worked。", "work here（在此有所作为）", "不是特指作者正在写作的房间。"],
  ["write", "writes wrote written writing", "v.", "写道；撰写", "wrote用于引语报道及创作著作。", "write a biography（写传记）", "write过去式wrote，分词written；名词writing单独按语境处理。"],
  ["writing", "writings", "n.", "写作；著作", "the writing of history是活动，his rambling writing是作品。", "the writing of history（历史写作）", "不把名词writing一概计入动词write词位。"],
  ["victorian", "", "adj.", "维多利亚时代的", "修饰sage和author，标示所述人物所处时代。", "a Victorian author（维多利亚时代作家）", "不是victory胜利的词形。"],
  ["sage", "sages", "n.", "智者；思想家", "修饰同位人名Thomas Carlyle的身份名词。", "a Victorian sage（维多利亚时代思想家）", "另可指鼠尾草，但本句为人而非植物。"],
  ["thomas", "", "proper n.", "托马斯", "Thomas Carlyle的名字，与姓氏共同定位思想家。", "Thomas Carlyle（托马斯·卡莱尔）", "专名，不按普通名词构词推断。"],
  ["carlyle", "", "proper n.", "卡莱尔", "本文伟人史观代表人物，44题对应难以效仿的时代英雄。", "Thomas Carlyle（托马斯·卡莱尔）", "与Smiles普通职业榜样观区分。"],
  ["great", "greater greatest", "adj.", "伟大的；卓越的", "great men为杰出历史人物，不是更大的男性。", "great men（伟人）", "great也可表示数量大或程度高，此处评价成就。"],
  ["work", "works worked working", "v. / n.", "有所作为；工作；创作", "首句worked指人的活动，work on为着手创作。", "work on a book（撰写一本书）", "本文不是药物奏效或市场起作用。"],
  ["well", "", "discourse marker", "不过；那么", "第二句开头缓和并引出反驳。", "Well, not any more（不过，现在不再如此）", "此处不是副词好地、可能性加强词或水井名词。"],
  ["suddenly", "", "adv.", "突然间", "修饰对英国史学偏好变化的观察。", "suddenly change（突然改变）", "suddenly着重出乎意料或突发，gradually为渐进。"],
  ["historical", "", "adj.", "历史的；有关历史的", "historical form在此指历史写作形式。", "a historical form（历史书写形式）", "historic指具有重大历史意义，不等于historical。"],
  ["pass", "passes passed passing", "v.", "过去；消逝", "passing在craze前作分词定语，指短暂的。", "a passing craze（一时热潮）", "本句不是通过考试或免交作业。"],
  ["craze", "crazes", "n.", "一时的狂热；风潮", "a passing literary craze为短暂文学风尚。", "a literary craze（文学热潮）", "trend可以长期持续，craze强调短期追逐。"],
  ["broad", "broader broadest", "adj.", "广泛的；深广的", "broader修饰truth，把解释从风尚扩大到史观。", "a broader truth（更广泛的事实）", "比较级broader，不是泛指物理更宽。"],
  ["truth", "truths", "n.", "事实；真相", "about后的从句说明事实涉及看待过去的方式。", "a broader truth（更普遍的事实）", "truth可作事实可数，也可指真实性不可数。"],
  ["approach", "approaches approached approaching", "v.", "看待；处理", "approach the past为以某种方式理解历史。", "approach the past（看待历史）", "此处是及物动词，不需再加to；名词an approach to才用to。"],
  ["concern", "concerns concerned concerning", "v.", "使关注；关涉", "concerned with说明关心什么，而非焦虑某种危险。", "be concerned with learning（关注学习）", "concerned about偏担心，concerned with偏涉及或关注。"],
  ["interest", "interests interested interesting", "v. / n.", "使感兴趣；兴趣", "interested in接动名词feeling，表兴趣所在。", "be interested in history（对历史感兴趣）", "不是金融利息或利益集团。"],
  ["forefather", "forefathers", "n.", "祖先；先辈", "指生活于过去、可供后人理解学习的人。", "learn from our forefathers（向先辈学习）", "不局限于自己的直系父系祖先。"],
  ["pain", "pains", "n.", "痛苦；苦难", "their pain指先人所经历的痛苦。", "feel their pain（体会他们的痛苦）", "take pains为费心，不能把复数习语义套入本句。"],
  ["empathy", "", "n.", "共情；感同身受", "与inspiration形成文章主题对照。", "feel empathy（产生共情）", "sympathy侧重同情，empathy强调设身处地理解感受。"],
  ["inspiration", "inspirations", "n.", "鼓舞；激励", "此处为从伟人事迹得到精神激励，不是创作灵感。", "a source of inspiration（激励的来源）", "也可指灵感；与empathy理解他人感受不同。"],
  ["renaissance", "", "proper n.", "文艺复兴", "the Renaissance为所追溯的历史时期。", "the Renaissance（文艺复兴）", "小写renaissance也可表示复兴，本文是专名。"],
  ["recount", "recounts recounted recounting", "v.", "叙述；讲述", "mean后动名词，宾语为伟人生平。", "recount a life（叙述生平）", "讲述义不同于重新计票的recount用法。"],
  ["exemplary", "", "adj.", "典范的；值得效法的", "修饰lives，含道德或行为榜样评价。", "an exemplary life（堪为典范的人生）", "example是例子名词，不是exemplary的屈折形式。"],
  ["life", "lives", "n.", "人生；生平", "伟人及职业人物的经历为传记内容。", "the lives of great men（伟人的生平）", "lives在本文为life的复数，不是live的第三人称动词。"],
  ["petrarch", "", "proper n.", "彼特拉克", "41题人物，创作古典英雄传记并赞颂美德。", "Petrarch's writing（彼特拉克的作品）", "不与Machiavelli的权谋成功论混淆。"],
  ["rambling", "", "adj.", "散漫冗长的；漫无章法的", "修饰writing，描述著作铺陈特点。", "rambling writing（铺陈散漫的作品）", "不是在此描述人物步行漫游。"],
  ["de", "", "Latin title element", "关于", "拉丁书名De Viris Illustribus的首词，对应英文译名On。", "De Viris Illustribus（《名人传》）", "按完整书名理解，不当英语普通介词统计词性。"],
  ["viris", "", "Latin title element", "人物；人们", "拉丁书名组成部分，英文标题对应Men。", "De Viris Illustribus（《名人传》）", "保留拉丁拼写，不误作virus病毒。"],
  ["illustribus", "", "Latin title element", "杰出的；著名的", "书名中与Viris搭配，英文标题对应Famous。", "De Viris Illustribus（《名人传》）", "非英语illustrations的屈折词形。"],
  ["highlight", "highlights highlighted highlighting", "v.", "突出；强调", "正文突出美德，选项B突出荣耀但属于错误归属。", "highlight virtue（强调美德）", "emphasize同样强调，不等于high light两个独立词。"],
  ["virtus", "", "Latin n.", "美德；德性", "原文立即用or virtue释义，指英雄值得赞颂的品格。", "the virtus of heroes（英雄的美德）", "按本文括号释义理解，不扩展为未经本文讨论的哲学体系。"],
  ["virtue", "virtues", "n.", "美德；德性", "Petrarch赞颂，Machiavelli未把它列为成功领袖必要技能。", "classical virtue（古典美德）", "也可指优点、长处；by virtue of意为由于、凭借。"],
  ["classical", "", "adj.", "古典的；古希腊罗马的", "修饰heroes，限定传记描绘的传统对象。", "classical heroes（古典英雄）", "classic可指经典或典型，不与classical所有语境互换。"],
  ["hero", "heroes", "n.", "英雄", "复数heroes指传记中的杰出人物。", "classical heroes（古典英雄）", "hero也指故事男主角；本文侧重被赞颂的人物。"],
  ["celebrate", "celebrates celebrated celebrating", "v.", "赞颂；颂扬", "宾语greatness，评价战胜命运的英雄。", "celebrate greatness（颂扬伟大）", "也可庆祝节日，但本句不指举办活动。"],
  ["greatness", "", "n.", "伟大；卓越", "先指英雄成就，后指各时代衡量伟大的标准。", "attributes of greatness（伟大的特质）", "great是形容词，greatness为派生名词须独立词位。"],
  ["conquer", "conquers conquered conquering", "v.", "战胜；征服", "conquering fortune意为战胜命运际遇。", "conquer fortune（战胜命运）", "不是掠夺钱财；conquer也可用于征服领土。"],
  ["fortune", "fortunes", "n.", "命运；际遇", "作为conquering宾语，强调克服命运。", "conquer fortune（战胜命运）", "另可指运气和大笔财富，如make a fortune发财。"],
  ["biographical", "", "adj.", "传记的", "修饰tradition，指记录人物生平的写作传统。", "biographical tradition（传记传统）", "biography是传记名词，不并入该形容词屈折统计。"],
  ["niccolò", "niccol", "proper n.", "尼科洛", "Niccolò Machiavelli的名字；按原卷保留重音符号。", "Niccolò Machiavelli（尼科洛·马基雅维利）", "界面ASCII词片Niccol映射完整名字，非另一个人物。"],
  ["machiavelli", "", "proper n.", "马基雅维利", "《君主论》作者，42题观点归属。", "Niccolò Machiavelli（马基雅维利）", "与颂扬古典美德的Petrarch相对照。"],
  ["prince", "princes", "n.", "君主；王子", "The Prince为本文所引书名《君主论》。", "The Prince（《君主论》）", "在书名中指统治者，不宜按现代皇子故事理解。"],
  ["champion", "champions championed championing", "v.", "推崇；大力支持", "championed三种政治技能，as说明其作为成功条件的作用。", "champion boldness（推崇果敢）", "也可作冠军名词，本句位置为谓语动词。"],
  ["cunning", "", "n.", "狡黠；权谋", "与ruthlessness、boldness并列作宾语。", "political cunning（政治权谋）", "cleverness聪明较中性，cunning常含狡诈色彩。"],
  ["ruthlessness", "", "n.", "无情；冷酷", "与美德仁慈形成价值标准对比。", "cunning and ruthlessness（权谋与冷酷）", "ruthless为形容词，-ness形成抽象名词。"],
  ["boldness", "", "n.", "果敢；胆识", "领袖成功所推崇的能力之一。", "a leader's boldness（领导者的胆识）", "不把果敢等同没有判断的鲁莽。"],
  ["mercy", "", "n.", "仁慈；宽恕", "rather than后的传统德性之一。", "show mercy（表现仁慈）", "at the mercy of为任凭摆布，不能套回本句。"],
  ["justice", "", "n.", "正义；公正", "与virtue和mercy并列为传统价值。", "virtue and justice（美德与正义）", "不是法官称谓Justice或某一司法机构。"],
  ["skill", "skills", "n.", "技能；本领", "as the skills把前述品质视为成功领导能力。", "leadership skills（领导技能）", "skill可学习培养，不等于道德评价virtue。"],
  ["attribute", "attributes", "n.", "特质；属性", "主语attributes of greatness指伟大所含的标准。", "attributes of greatness（伟大的特质）", "动词attribute A to B为把A归因于B，本文不是动词。"],
  ["romantic", "romantics", "n.", "浪漫主义者", "大写The Romantics指浪漫主义思潮中的作家艺术家。", "the Romantics（浪漫主义者）", "不按日常浪漫的恋人义理解。"],
  ["commemorate", "commemorates commemorated commemorating", "v.", "纪念；颂念", "以书写生平纪念当代杰出艺术家。", "commemorate leading artists（纪念杰出艺术家）", "celebrate侧重赞颂，commemorate强调纪念。"],
  ["leading", "", "adj.", "杰出的；主要的", "leading painters and authors为最重要的一批艺术家。", "leading painters（杰出的画家）", "不是lead to导致的现在分词，不与动词词形强并。"],
  ["painter", "painters", "n.", "画家", "与authors并列，为Romantics所纪念的人。", "leading painters（杰出画家）", "可指油漆工，但艺术家语境明确为画家。"],
  ["stress", "stresses stressed stressing", "v.", "强调", "分词stressing说明纪念时着重个人经历。", "stress uniqueness（强调独特性）", "不是精神压力名词，也非使人焦虑的用法。"],
  ["uniqueness", "", "n.", "独特性", "强调个人经历不可替代的特点。", "the uniqueness of experience（经历的独特性）", "unique是形容词，uniqueness为派生名词。"],
  ["artist", "artists artist's", "n.", "艺术家", "artist's是所有格，personal experience为其经历。", "an artist's experience（艺术家的经历）", "所有格不等于第三人称动词或is缩写。"],
  ["glory", "glories", "n.", "荣耀；荣光", "public glory为在公众中的荣耀，原句将其排除。", "public glory（公众中的荣耀）", "不能因highlighted选项就反转rather than的否定对照。"],
  ["self-help", "", "n.", "自助；自立", "首处为斯迈尔斯著作《自助》，后指靠自己努力的力量。", "the power of self-help（自助的力量）", "不是外部慈善救助，连字符保留为整体。"],
  ["catalogue", "catalogues", "n.", "汇录；目录", "as a catalogue说明该书汇集典范人生。", "a catalogue of lives（生平汇录）", "此处不是商品购物目录；catalog美式拼写另见通用资料。"],
  ["engineer", "engineers", "n.", "工程师", "与industrialists、explorers并列，属Smiles传记对象。", "the lives of engineers（工程师的生平）", "动词engineer可指策划，但本文为职业名称。"],
  ["industrialist", "industrialists", "n.", "实业家；工业家", "指经营工业事业的人，非产业工人。", "engineers and industrialists（工程师与实业家）", "industrial工业的与industrialist实业家不可混同。"],
  ["explorer", "explorers", "n.", "探险家", "Smiles书中值得称道的人物类别之一。", "the lives of explorers（探险家的生平）", "不是互联网浏览器名称或抽象探索行为。"],
  ["valuable", "", "adj.", "有价值的；宝贵的", "评价这些实例对读者有借鉴价值。", "valuable examples（宝贵的实例）", "不只指价格昂贵。"],
  ["furnish", "furnishes furnished furnishing", "v.", "提供", "which是提供的实例，they为三类人物。", "furnish examples（提供实例）", "furnish也可为房间配家具；本句非该义。"],
  ["patient", "", "adj.", "耐心的；持之以恒的", "修饰purpose，强调长久坚持的目标。", "patient purpose（持之以恒的志向）", "不是patient患者名词，不应显示就医语境。"],
  ["purpose", "purposes", "n.", "志向；目标", "patient purpose指持久坚定的目标。", "patient purpose（持之以恒的志向）", "purpose也可用途，此处描述人的志向。"],
  ["resolute", "", "adj.", "坚决的；坚定的", "resolute working为坚定不懈的努力。", "resolute working（坚定不懈的努力）", "resolution为决心名词，不是屈折词形。"],
  ["steadfast", "", "adj.", "坚定不移的；始终如一的", "修饰integrity，表示一直保持正直。", "steadfast integrity（始终正直）", "steady可平稳持续，steadfast强调信念坚定。"],
  ["integrity", "", "n.", "正直；诚实", "指自助榜样人物的道德品格。", "steadfast integrity（坚定的正直品格）", "另可完整性，如data integrity数据完整性。"],
  ["issue", "issues issued issuing", "v.", "导致；产生结果", "issue in接formation，表示造就高尚品格。", "issue in success（以成功告终）", "不同于issue发布、发行或名词议题。"],
  ["formation", "formations", "n.", "形成；塑造", "formation of character为人格的形成。", "the formation of character（品格的形成）", "不是鸟群编队或军事队形。"],
  ["noble", "nobler noblest", "adj.", "高尚的", "与manly并列评价character。", "noble character（高尚品格）", "noble也可贵族的，本文评价道德而非血统。"],
  ["manly", "", "adj.", "刚毅的；有男子气概的", "为历史引语对character的赞词，译出勇毅色彩。", "manly character（刚毅的品格）", "属于原文时代话语，不扩展为所有性别都必须遵从的标准。"],
  ["exhibit", "exhibits exhibited exhibiting", "v.", "展示；表明", "远隔长修饰与主语examples相连，宾语为what从句。", "exhibit the power of self-help（展现自助的力量）", "名词exhibit可为展品，此处为谓语。"],
  ["biography", "biographies", "n.", "传记", "of后列出传主，His指传记作者Smiles。", "a biography of Watt（瓦特传）", "autobiography为自传；biographical为派生形容词。"],
  ["hold", "holds held holding", "v.", "树为榜样；持有观点", "hold up as在正文为树为明灯，选项held that为认为。", "hold up as a beacon（树为指路明灯）", "hold up也可耽搁或抢劫，不能套入传记语境。"],
  ["beacon", "beacons", "n.", "灯塔；指路明灯", "比喻传记为劳动者提供人生方向。", "a beacon of hope（希望的灯塔）", "不应只显示实物航标而漏掉榜样比喻。"],
  ["guide", "guides guided guiding", "v.", "引导；指引", "to guide说明传记作为明灯的作用。", "guide somebody through life（引导某人度过人生）", "guide也可导游或指南名词，本句是不定式动词。"],
  ["bit", "bits", "n.", "一点；少量", "a bit修饰bourgeois，缓和批评程度。", "a bit bourgeois（有点市民气）", "不是计算机比特或整块物体。"],
  ["bourgeois", "", "adj.", "资产阶级的；带市民气的", "Carlyle认为前述职业成功榜样有些庸常市民气。", "a bit bourgeois（有点市民气）", "本文是Carlyle评价，不代表作者统一赞成这种贬评。"],
  ["heroic", "", "adj.", "英雄式的；英勇非凡的", "修饰lives，说明Carlyle关注超凡英雄。", "heroic lives（英雄式的人生）", "hero为名词，heroic是派生形容词，统计分开。"],
  ["epochal", "", "adj.", "划时代的；影响时代的", "修饰figures，与时代影响力相关。", "epochal figures（划时代人物）", "epoch是时代名词，不是epochal的同一原形。"],
  ["represent", "represents represented representing", "v.", "体现；代表", "人物体现一种难以效仿的人生。", "represent heroic lives（体现英雄式人生）", "不是represent a client代理客户的法律义。"],
  ["acknowledge", "acknowledges acknowledged acknowledging", "v.", "承认；认可", "被动不定式后as说明认可其权威地位。", "acknowledge authority（承认权威）", "recognize可认可，acknowledge强调承认事实或地位。"],
  ["possess", "possesses possessed possessing", "v.", "拥有；具有", "possessing authority为具有权威，possessed wealth为拥有财富。", "possess authority（具有权威）", "不是possessed被鬼附体的形容词意义。"],
  ["high", "higher highest", "adj.", "高的；更高层级的", "higher authority比较英雄与普通人的权威。", "higher authority（更高的权威）", "比较级higher，不等于highly副词。"],
  ["mere", "", "adj.", "仅仅的；普通的", "mere mortals把英雄之外的人称为凡人。", "mere mortals（普通凡人）", "mere在名词前，merely为副词不能原位互换。"],
  ["mortal", "mortals", "n.", "凡人；会死的人", "与被赋予超凡权威的英雄对照。", "mere mortals（普通人）", "也可形容词致命的或终有一死的，本文为复数名词。"],
  ["convince", "convinces convinced convincing", "v.", "说服；使信服", "was convinced为被动，Not everyone限制认同范围。", "be convinced by an argument（被论证说服）", "persuade常强调劝某人行动，convince侧重信念。"],
  ["bombast", "", "n.", "夸夸其谈；浮夸言辞", "批评给英雄超凡权威的论调。", "such bombast（这种夸大言辞）", "不是bomb炸弹，不能按词形想象暴力。"],
  ["hitherto", "", "adv.", "迄今；到那时为止", "修饰existing，属于所引历史文本的时间视角。", "hitherto existing society（迄今存在的社会）", "不把引语时间自动更新为网站浏览时点。"],
  ["exist", "exists existed existing", "v.", "存在", "existing在society前作分词定语。", "existing society（现存社会）", "不及物动词，不直接带被存在的宾语。"],
  ["class", "classes", "n.", "阶级", "class struggles为阶级斗争。", "class struggles（阶级斗争）", "不是班级、课程或分类动词。"],
  ["struggle", "struggles struggled struggling", "n. / v.", "斗争；抗争", "本篇两处名词说明社会阶级和民众的抗争。", "a record of struggle（抗争的记录）", "不只指个人事业艰辛，也不必每次理解为武装战争。"],
  ["communist", "communists", "adj. / n.", "共产主义的；共产主义者", "The Communist Manifesto书名中为形容词。", "The Communist Manifesto（《共产党宣言》）", "本文用于著作名称，不是新增对群体的评价。"],
  ["manifesto", "manifestos manifestoes", "n.", "宣言", "指系统陈述政治主张的文本，此处为书名。", "a political manifesto（政治宣言）", "与manual操作手册的文体不同。"],
  ["immense", "", "adj.", "巨大的", "修饰wealth，no否定抽象历史拥有财富。", "immense wealth（巨额财富）", "程度强于普通large，但不提供任何精确数额。"],
  ["wage", "wages waged waging", "v.", "发动；进行", "wage battles为进行战斗，nor承接否定。", "wage a battle（进行战斗）", "名词wage为工资；本句在谓语位为动词。"],
  ["real", "", "adj.", "真实的；现实存在的", "与living共同强调行动主体是真实的人。", "real, living man（现实中活生生的人）", "不是reality名词，派生词分别统计。"],
  ["mass", "masses", "n.", "民众；大众", "the masses整体表示普通民众。", "the masses（广大民众）", "mass也可质量、一团、大量；这里不是物理质量。"],
  ["reality", "realities", "n.", "现实情况", "复数economic realities为各时代具体经济现实。", "economic realities（经济现实）", "real为形容词，不合并为同一屈折词位。"],
  ["context", "contexts", "n.", "背景；环境", "social contexts为事件所处社会环境。", "social contexts（社会背景）", "不只指一句话附近的语境。"],
  ["relation", "relations", "n.", "关系", "power relations为社会中权力配置关系。", "power relations（权力关系）", "relation也可亲属，此处非家庭称谓。"],
  ["epoch", "epochs", "n.", "时代；历史时期", "each epoch为社会条件中的时代单位。", "each epoch（每个时代）", "era也表时代，epoch常强调历史特征。"],
  ["stand", "stands stood standing", "v.", "处于；并立", "stood用于时代处境及两类史学并存。", "stand alongside（与……并存）", "stand过去式和分词均stood；本篇非单纯身体站立。"],
  ["please", "pleases pleased pleasing", "v.", "愿意；选择", "as they please为按照自己的意愿，无宾语。", "as you please（随你所愿）", "不是礼貌用语请，也非使某人高兴的及物用法。"],
  ["circumstance", "circumstances", "n.", "条件；环境", "under circumstances说明创造历史时的客观条件。", "under given circumstances（在既定条件下）", "复数常表环境，不是某一孤立意外事件。"],
  ["transmit", "transmits transmitted transmitting", "v.", "传承；传递", "过去分词修饰circumstances，表示由过去传下的条件。", "transmit from the past（从过去传承下来）", "过去式双写t；本文不是疾病传播的特定语境。"],
  ["revolutionise", "revolutionises revolutionised revolutionising", "v.", "彻底改变；革新", "宾语为人们对历史的认识。", "revolutionise understanding（彻底改变认识）", "保留原卷英式拼写，不机械译为发动政治革命。"],
  ["nurture", "nurtures nurtured nurturing", "v.", "培养；孕育", "英国学术环境培养了一批新史家。", "nurture historians（培养历史学家）", "既可养育儿童也可培养才能，本文为后者。"],
  ["alongside", "", "prep.", "与……并列；在……旁边", "stood alongside比喻两种史学写作并存。", "alongside biographies（与传记并列）", "并存不代表取代后彻底消灭旧传统。"],
  ["realm", "realms", "n.", "领域", "realms of understanding为新的认识或研究领域。", "new realms of understanding（新的认识领域）", "realm还可王国，本文不指行政领土。"],
  ["understanding", "understandings", "n.", "理解；认识", "of understanding限定研究领域性质。", "realms of understanding（认识领域）", "本处为名词，不强并understand的所有动词次数。"],
  ["cultural", "", "adj.", "文化的", "修饰studies，表示文化研究领域。", "cultural studies（文化研究）", "culture名词与cultural派生形容词分开计数。"],
  ["open", "opens opened opening", "v.", "开拓；打开", "were opened up为被动，指研究领域被开辟。", "open up new realms（开辟新领域）", "open up在此不是开商店营业或向人吐露心声。"],
  ["scholar", "scholars", "n.", "学者", "as从句主语，研究过去社会的人。", "historical scholars（历史研究学者）", "school学校与scholar学者不是相同词位。"],
  ["unpick", "unpicks unpicked unpicking", "v.", "细致剖析；梳理", "宾语为过去社会的多样性，使用拆线的比喻。", "unpick social complexity（剖析社会复杂性）", "本义拆开缝线，本文不作挑选的反义词硬译。"],
  ["multiplicity", "multiplicities", "n.", "多样性；众多", "描述已经消逝的社会形态之复杂多样。", "a multiplicity of societies（多样的社会形态）", "不是multiplication乘法计算。"],
  ["downstairs", "", "adv. / n.", "楼下；下层民众的生活", "被名词化作主语，与upstairs形成阶层隐喻。", "history downstairs（下层民众的历史）", "这里不能只按建筑空间而不解释阶层暗示。"],
  ["upstairs", "", "adv. / n.", "楼上；上层人物的生活", "与downstairs比较其引人关注程度。", "life upstairs（上层人物的生活）", "不代表所有时代楼层与身份都固定对应。"],
  ["fascinating", "", "adj.", "引人入胜的；极有吸引力的", "as...as比较两类人的生活被关注的程度。", "fascinating history（引人入胜的历史）", "fascinated为人感到着迷，fascinating为事物令人着迷。"],
  ["emphasize", "emphasizes emphasized emphasizing", "v.", "强调", "选项A对应原文highlighting virtue。", "emphasize virtue（强调美德）", "与highlight为近义，不表示美德是所有段落共同主张。"],
  ["dismiss", "dismisses dismissed dismissing", "v.", "不予考虑；摒弃", "dismiss A as B表示因将A视为B而不采纳。", "dismiss virtue as unnecessary（认为美德非必要而不采纳）", "也可解雇或驳回诉讼，本文选项非这两义。"],
  ["unnecessary", "", "adj.", "不必要的", "选项F限定为成功领袖的条件，不泛指一切道德。", "unnecessary for success（成功并不需要的）", "unnecessary是不必要，不是impossible不可能。"],
  ["depict", "depicts depicted depicting", "v.", "描绘；描述", "选项G概括Smiles汇录三类人生。", "depict worthy lives（描写值得效法的人生）", "既可文字描述，也可图像描绘，本文为传记写作。"],
  ["samuel","","proper n.","塞缪尔","43题传记作家斯迈尔斯的名字","Samuel Smiles（塞缪尔，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["smiles","","proper n.","斯迈尔斯","《自助》作者的姓，不是smile微笑的复数","Samuel Smiles（斯迈尔斯，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["james","","proper n.","詹姆斯","斯迈尔斯传记中的瓦特的名字","James Watt（詹姆斯，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["watt","","proper n.","瓦特","传主瓦特的姓，不是功率单位瓦特","James Watt（瓦特，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["richard","","proper n.","理查德","阿克赖特的名字，非其他篇同名学者","Richard Arkwright（理查德，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["arkwright","","proper n.","阿克赖特","斯迈尔斯所写传主的姓","Richard Arkwright（阿克赖特，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["josiah","","proper n.","乔赛亚","韦奇伍德的名字","Josiah Wedgwood（乔赛亚，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["wedgwood","","proper n.","韦奇伍德","斯迈尔斯传记中的人物姓氏","Josiah Wedgwood（韦奇伍德，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["martin","","proper n.","马丁","卡莱尔笔下路德的名字","Martin Luther（马丁，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["luther","","proper n.","路德","卡莱尔笔下英雄之一的姓氏","Martin Luther（路德，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["oliver","","proper n.","奥利弗","克伦威尔的名字，非2011篇厨师姓氏","Oliver Cromwell（奥利弗，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["cromwell","","proper n.","克伦威尔","卡莱尔描写的英雄人物之一","Oliver Cromwell（克伦威尔，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["napoleon","","proper n.","拿破仑","卡莱尔描写的英雄人物名字","Napoleon Bonaparte（拿破仑，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["bonaparte","","proper n.","波拿巴","拿破仑的姓氏","Napoleon Bonaparte（波拿巴，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["marx","","proper n.","马克思","本文阶级斗争与民众史观的提出者之一","Marx and Engels（马克思，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["engels","","proper n.","恩格斯","与马克思共同署名的思想家","Marx and Engels（恩格斯，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["christopher","","proper n.","克里斯托弗","英国社会史学者希尔的名字","Christopher Hill（克里斯托弗，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["hill","","proper n.","希尔","史家姓氏，非hill小山名词","Christopher Hill（希尔，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["ep","","proper n.","E.P.（姓名缩写）","按原卷保留没有句点的名字缩写","EP Thompson（E.P.（姓名缩写），本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["thompson","","proper n.","汤普森","英国新史学代表人物姓氏","EP Thompson（汤普森，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["eric","","proper n.","埃里克","霍布斯鲍姆的名字","Eric Hobsbawm（埃里克，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
  ["hobsbawm","","proper n.","霍布斯鲍姆","末段新史学代表人物姓氏","Eric Hobsbawm（霍布斯鲍姆，本文人物姓名）","专名按人物定位，不从相似普通词推断其历史主张。"],
];
const reviewed = reviewedLexicon(rows);
export const passage2012P5Lexicon = reviewed.entries;
export const passage2012P5LemmaAliases = reviewed.aliases;
export const passage2012P5CollocationGlosses = reviewed.glosses;
export const passage2012P5FormPartOfSpeech: Record<string, string> = { writing: "n.", working: "v.-ing / n.", lives: "n.", leading: "adj.", interested: "adj.（分词）", concerned: "adj.（分词）", patient: "adj.", attributes: "n.", sage: "n.", masses: "n.", struggles: "n.", held: "v.-ed", living: "adj.（分词）", studies: "n.", found: "v.-ed（分词定语）", given: "v.-ed（分词定语）", passing: "adj.（分词）", power: "n.", class: "n.", worth: "n." };
Object.assign(passage2012P5LemmaAliases, { leading: "leading", writing: "writing", understanding: "understanding", fascinating: "fascinating", smiles: "smiles", rambling: "rambling" });
passage2012P5Lexicon.fortune.otherMeanings = ["运气、命运：good fortune好运。", "巨额财富：make a fortune发财；cost a fortune花费很多钱。"];
passage2012P5Lexicon.issue.otherMeanings = ["n. 问题、议题；刊物的一期；发行。", "v. 发布命令或声明；发行书刊、证券；issue from源自。"];
passage2012P5Lexicon.hold.otherMeanings = ["握住；容纳；举办；维持；持有观点。hold that认为，hold a meeting开会。", "hold up耽搁、抢劫或树为榜样；hold on坚持、稍等。"];
passage2012P5Lexicon.mass.otherMeanings = ["质量；一团或一堆；大量。a mass of evidence大量证据。", "adj. 大规模的、大众的，如mass production大规模生产。"];
passage2012P5Lexicon.champion.otherMeanings = ["n. 冠军；斗士、捍卫者。a champion of reform改革的支持者。"];
passage2012P5Lexicon.furnish.otherMeanings = ["为房屋配备家具；furnish somebody with something向某人提供某物。"];
passage2012P5Lexicon.integrity.otherMeanings = ["完整性；完好。data integrity数据完整性，territorial integrity领土完整。"];
passage2012P5Lexicon.dismiss.otherMeanings = ["解雇；让某人离开、解散；驳回诉讼或请求；不予理会。"];

export const passage2012P5SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2012-p5-s1": { bottom: { contextualMeaning: "根本；实质", use: "at bottom整体修饰is判断，不是最低位置。" }, man: { contextualMeaning: "人类", use: "单数类指全人类，不限定男性。" } },
  "2012-p5-s3": { fall: { contextualMeaning: "与……闹翻；不再青睐", use: "fallen out with历史写作形式是比喻，非跌落。" } },
  "2012-p5-s4": { point: { contextualMeaning: "表明；指向", use: "point to引事实结论，不是point out指出的原样替换。" }, it: { contextualMeaning: "史学偏好变化这一现象", use: "承接This，与历史形式本身区分。" } },
  "2012-p5-s6": { day: { contextualMeaning: "时期；时代", use: "earliest days指文艺复兴早期，不指某几日。" }, writing: { contextualMeaning: "历史写作活动", use: "the writing of history为名词化主语。" } },
  "2012-p5-s7": { highlight: { contextualSubstitutions: [{ label: "emphasizing", chinese: "强调", fit: "direct", rewrittenSentence: "In 1337, Petrarch began work on his rambling writing De Viris Illustribus – On Famous Men, emphasizing the virtus (or virtue) of classical heroes.", nuance: "highlight强调突出某一特征，emphasize强调给予该特征较大重视；此处均保留对古典英雄美德的重视。", target: "word:emphasize" }] }, writing: { contextualMeaning: "著作；作品", use: "his rambling writing特指De Viris Illustribus。" }, or: { contextualMeaning: "也就是；换言之", use: "括号用virtue解释拉丁词virtus，不是给出互斥选择。" } },
  "2012-p5-s8": { their: { contextualMeaning: "古典英雄们", use: "若以规范代词显示，回指前句classical heroes。" }, rise: { contextualMeaning: "攀上巅峰；取得成功", use: "rising to the top与conquering fortune并列。" } },
  "2012-p5-s9": { turn: { contextualMeaning: "彻底颠覆", use: "turned...on its head中which为前置宾语，its指传统。" }, head: { contextualMeaning: "颠倒习语中的头部意象", use: "turn something on its head整体为颠覆，不是人物的头脑。" } },
  "2012-p5-s11": { over: { contextualMeaning: "随着……推移", use: "over time为时间渐变，不是关于某个争论。" }, time: { contextualMeaning: "时间；时代演进", use: "over time指跨时代的变化，不是倍数。" } },
  "2012-p5-s12": { day: { contextualMeaning: "所处时代", use: "of their day限定画家作家的时代。" }, their: { contextualMeaning: "浪漫主义者", use: "规范代词回指The Romantics。" } },
  "2012-p5-s13": { worthy: { contextualMeaning: "值得尊敬、效法的", use: "修饰lives，对三类人物生平作价值评价。" } },
  "2012-p5-s14": { work: { contextualMeaning: "坚定不懈的努力", use: "resolute working为名词化工作活动，与志向和正直并列。", partOfSpeech: "n.（动名词）" }, power: { contextualMeaning: "力量；能力", use: "前处为自助等品质的力量，后处in the power of each指每个人的能力范围。" }, they: { contextualMeaning: "上述工程师、实业家和探险家", use: "they furnish examples说明这些人物提供榜样。" }, each: { contextualMeaning: "每个人", use: "each独立使用，for himself与之照应。" }, it: { contextualMeaning: "形式主语", use: "真实内容为to accomplish，不作强调句it。" } },
  "2012-p5-s15": { work: { contextualMeaning: "劳动；工作", use: "working在working man中修饰人，指劳动者。", partOfSpeech: "adj.（分词）" } },
  "2012-p5-s17": { authority: { contextualMeaning: "权威；号召力", use: "higher authority与普通人相比，非政府当局复数。" }, figure: { contextualMeaning: "人物", use: "epochal figures回指路德等英雄，非数字。" } },
  "2012-p5-s19": { exist: { contextualMeaning: "现存的", use: "hitherto existing限定society。" } },
  "2012-p5-s20": { they: { contextualMeaning: "马克思与恩格斯", use: "For them明确观点归属。" }, for: { contextualMeaning: "在……看来", use: "For them标记观察立场，非原因连词。" }, that: { contextualMeaning: "前述一切行动", use: "all that为代词宾语，不引导从句。" }, live: { contextualMeaning: "活生生的", use: "living修饰man，突出实际行动主体。", partOfSpeech: "adj.（分词）" } },
  "2012-p5-s21": { record: { contextualMeaning: "记录", use: "their record of struggle指民众斗争的记录，非最高纪录。", partOfSpeech: "n." } },
  "2012-p5-s22": { appreciate: { contextualMeaning: "充分理解；考察", use: "认识历史所处条件，不是感谢或币值上升。" }, power: { contextualMeaning: "权力", use: "power relations指社会权力关系，不是个人自助能力。" }, stand: { contextualMeaning: "处于", use: "in which each epoch stood指时代所处的环境。" } },
  "2012-p5-s23": { for: { contextualMeaning: "因为", use: "For引出解释前句的理由，保留原卷冒号。" }, make: { contextualMeaning: "创造", use: "make history以历史为宾语，不是使某人变成。" }, themselves: { contextualMeaning: "人们自己", use: "chosen by themselves指自行选择条件，并非其他篇迁移运动。" }, find: { contextualMeaning: "遇到；面对", use: "found为分词，修饰直接遇到的历史条件。" }, give: { contextualMeaning: "既定的；已给定的", use: "given为分词定语，修饰circumstances。" } },
  "2012-p5-s24": { appreciation: { contextualMeaning: "理解；认识", use: "appreciation of the past为理解历史，不是感激。" }, this: { contextualMeaning: "民众史及社会条件史观", use: "回指Marx和Engels展开的思想，不回指Carlyle。" } },
  "2012-p5-s26": { below: { contextualMeaning: "社会下层；民众视角", use: "from below为历史研究视角的比喻，非垂直方位。" }, stand: { contextualMeaning: "并立；并存", use: "stood alongside表示两类写史方式并存。" } },
  "2012-p5-s27": { lose: { contextualMeaning: "已消逝的", use: "lost societies是已经不复存在的社会形态，非迷路社团。" }, study: { contextualMeaning: "研究", use: "cultural studies为研究领域名称，studies为名词。", partOfSpeech: "n." }, as: { contextualMeaning: "随着", use: "伴随学者深入研究，新的领域被开辟。" } },
  "2012-p5-s28": { just: { contextualMeaning: "恰恰；同样地", use: "just加强as...as的同等程度，而非仅仅。" } },
};
