import type { PracticeTask, GrammarConceptId, ErrorCategory } from "./learning-model";
type Hints = Pick<PracticeTask, "hintWords" | "mapRevealsAnswer" | "leaksToTaskIds" | "leaksToTasks">;
const range = (id: string, prompt: string, answer: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, hints: Hints): PracticeTask => ({ id, revision: 1, kind: "range", prompt, options: [], answer, evidence: answer, feedback, conceptId, errorType, ...hints });
const choice = (id: string, prompt: string, options: string[], answer: number, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, hints: Hints): PracticeTask => ({ id, revision: 1, kind: "choice", prompt, options, answer: options[answer], evidence, feedback, conceptId, errorType, ...hints });
const link = (id: string, prompt: string, pairs: Array<[string,string]>, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, hints: Hints): PracticeTask => ({ id, revision: 1, kind: "link", prompt, options: pairs.map(pair => pair[1]), answer: JSON.stringify(pairs.map(pair => pair[1])), links: pairs.map(([source,target]) => ({ source,target })), evidence, feedback, conceptId, errorType, ...hints });
const order = (id: string, prompt: string, answer: string[], extras: string[], evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, hints: Hints): PracticeTask => ({ id, revision: 1, kind: "order", prompt, options: [...answer,...extras], answer: JSON.stringify(answer), evidence, feedback, conceptId, errorType, ...hints });
const s = (n: number) => `2012-p1-s${n}`;

export const passage2012P1Practice: Record<string, PracticeTask[]> = {
  [s(1)]: [
    link("two-been", "把两处has been分别连到实际结构。", [["has never been ... popular", "系表：受欢迎程度"], ["has been ... scorned", "被动：受到轻视"]], "has never been terribly popular with students and even many parents, but in recent years it has been particularly scorned", "popular是形容词，scorned是动作分词；相同的has been不代表相同的语法关系。", "basic-svc", "predicate", { hintWords: ["popular", "scorned", "been", "has"] }),
    choice("attitude-shift", "but连接的态度变化是什么？", ["从不很受欢迎发展到近年尤其受轻视", "从被鄙视变成备受欢迎", "从少量作业变成没有任何作业"], 0, "but in recent years it has been particularly scorned", "but不是把评价变好；scorned比不受欢迎更强烈。只描述态度变化，没有断言作业被取消。", "negation-contrast", "passage-logic", { hintWords: ["but", "never", "particularly", "scorned"], mapRevealsAnswer: true }),
  ],
  [s(2)]: [order("district-subject", "拿掉插入举例和修饰，重建主谓宾。", ["School districts", "are revising", "their thinking"], ["Los Angeles Unified", "most recently"], "School districts across the country, most recently Los Angeles Unified, are revising their thinking", "两逗号之间是最新一例，复数are对应School districts；不是把Los Angeles Unified改成整个主语。", "subject-head", "subject", { hintWords: ["districts", "are", "revising", "thinking"] })],
  [s(3)]: [
    range("policy-relative", "划出完整的which定语从句，包含政策具体规定。", "which mandates that with the exception of some advanced courses, homework may no longer count for more than 10% of a student's academic grade", "which说明policy；其中that是mandates所接规定内容，不能在mandates之后就停止。", "clause-relative", "clause-boundary", { hintWords: ["which", "mandates", "that"], leaksToTaskIds: ["nested-policy"] }),
    link("nested-policy", "把两层关系词连到它的作用。", [["which", "回指policy，作mandates主语"], ["that", "引出mandates的规定内容，不作内部主宾语"]], "which mandates that with the exception of some advanced courses", "先是政策规定，再是规定的完整命题；which有句法成分，内容that只连接。", "clause-object", "clause-boundary", { hintWords: ["which", "that", "mandates"], leaksToTaskIds: ["policy-relative"] }),
    choice("weight-exception", "10%与advanced courses分别限定什么？", ["成绩权重上限；不受该上限约束的部分课程", "作业总量；完全不布置作业的课程", "考试及格线；没有考试的课程"], 0, "with the exception of some advanced courses, homework may no longer count for more than 10%", "count for接academic grade百分比，是分数权重；例外也只针对这个规定。不得把它换成作业量或免做作业。", "comparison-scope", "option-logic", { hintWords: ["exception", "count", "grade", "with the exception of", "count for more than 10%"], mapRevealsAnswer: true, leaksToTasks: [{ sentenceId: "2012-p1-map", taskId: "policy-target" }] }),
  ],
  [s(4)]: [
    range("difficulty-relative", "划出修饰difficulty的完整定语从句。", "that students from impoverished or chaotic homes might have in completing their homework", "that代回difficulty作have宾语；from短语只修饰students，in completing说明困难领域。", "clause-relative", "clause-boundary", { hintWords: ["that", "difficulty", "have", "difficulty that students from impoverished or chaotic homes might have in completing their homework"] }),
    choice("purpose-only", "is meant to说明什么？", ["规则的设计意图", "规则已经实现的成效", "学生必须逐字背诵的定义"], 0, "This rule is meant to address the difficulty", "承认帮助困难学生的初衷，不等于确认这一办法有效；But下一句开始评价缺陷。", "author-voice", "passage-logic", { hintWords: ["meant", "is meant to address"], mapRevealsAnswer: true }),
  ],
  [s(5)]: [choice("policy-complement", "unclear and contradictory在句中是什么？", ["policy的两个并列表语", "is的两个直接宾语", "说明学生做作业方式的状语"], 0, "the policy is unclear and contradictory", "形容词经is说明policy的性质，没有动作接收者，所以不叫宾语。", "basic-svc", "predicate", { hintWords: ["is", "unclear", "contradictory"] })],
  [s(6)]: [
    range("restricted-homework", "划出共同限定homework的两条定语从句。", "that students cannot complete on their own or that they cannot do without expensive equipment", "两个that从句虽放在谓语后，仍共同回答哪类作业；or列出两种不适宜的任务。", "clause-relative", "clause-boundary", { hintWords: ["that", "own", "without", "on their own", "cannot do without expensive equipment"], leaksToTaskIds: ["no-scope"] }),
    choice("no-scope", "no homework应怎样确定否定范围？", ["结合后置定语：禁止那两类不适当作业", "单独读取：作者要求取消所有作业", "只否定学生：教师无需考虑作业条件"], 0, "no homework should be assigned that students cannot complete on their own", "no否定的是带限定的完整名词范围；删掉定语会把合理限制扩大成全面取消。", "negation-contrast", "option-logic", { hintWords: ["no", "that", "without"], mapRevealsAnswer: true }),
  ],
  [s(7)]: [
    range("district-condition", "划出完整if条件，不包含主句it is going。", "if the district is essentially giving a pass to students who do not do their homework because of complicated family lives", "who从句嵌在条件的students内部；because of接名词短语，没有额外独立谓语。", "clause-condition", "clause-boundary", { hintWords: ["if", "who", "because", "giving a pass to students", "because of complicated family lives"] }),
    link("three-layers", "把三层从句连到各自作用。", [["if the district ...", "限定作者批评的政策情形"], ["who do not do ...", "限定哪些students"], ["that standards need ...", "说明implication的内容"]], "the implication that standards need to be lowered for poor children", "降低标准处在被警惕的暗示内部；不是作者无条件主张降低标准。关系层级先于术语。", "apposition", "attachment", { hintWords: ["if", "who", "that", "implication"], mapRevealsAnswer: true }),
  ],
  [s(8)]: [
    link("quantity-references", "匹配比较结构中的指代。", [["it", "家庭作业homework"], ["they", "教师teachers"]], "teachers are allowed to assign as much of it as they want", "as much用于不可数作业量；as they want按教师意愿定数量，不能让they回指管理者。", "reference-pronoun", "reference", { hintWords: ["it", "they", "much", "as much of it as they want"], mapRevealsAnswer: true }),
    choice("speaker-boundary", "homework will still be a part of schooling是谁提出的说法？", ["学区管理者", "作者已证明的研究结论", "所有学生的一致请求"], 0, "District administrators say that homework will still be a part of schooling", "say明确标出管理者说法；下一句But将检验其实际效果，不能因转述就认定作者赞成。", "author-voice", "passage-logic", { hintWords: ["administrators", "say"], mapRevealsAnswer: true }),
  ],
  [s(9)]: [
    link("finite-and-with", "把三个动作接回它们的主语及语法层。", [["counting", "with内部的homework，非谓语"], ["skip", "主句students，受can支配"], ["see", "与skip并列，共享students和can"]], "with homework counting for no more than 10% of their grades, students can easily skip half their homework and see", "先分离with背景结构，再找students之后的并列谓语；counting没有与skip平列。", "nonfinite-subject", "predicate", { hintWords: ["with", "counting", "can", "skip", "see"] }),
    choice("incentive-not-indifference", "分数差别很小说明的直接后果是什么？", ["少做作业的成绩代价很小，完成动力可能下降", "学生必然不再关心成绩单", "州统考已经失去公信力"], 0, "skip half their homework and see very little difference on their report cards", "作者把作业权重与完成激励相连；不在乎成绩单和考试权威下降都不是这个因果链。", "paragraph-role", "option-logic", { hintWords: ["skip", "half", "little", "difference", "report cards"], mapRevealsAnswer: true }),
  ],
  [s(10)]: [range("second-group", "只划出限定后一组students的完整who从句。", "who performed well on the tests and did their homework", "同一who统领performed和did，要求考好且做作业。前面的some和might则限制第一种情形，不能用少数情况证明作业对所有人无用。", "clause-relative", "clause-boundary", { hintWords: ["who", "performed", "did", "well"] })],
  [s(11)]: [choice("possible-claim", "本句可以支持哪种表述？", ["作业很可能帮助了这些学生", "作业已被严格证明是好成绩的唯一原因", "It指所有不做作业的学生"], 0, "It is quite possible that the homework helped", "It是形式主语，that命题是真正主语；quite加强可能，不取消possible的不确定性。", "clause-subject", "option-logic", { hintWords: ["It", "possible", "quite", "helped"], mapRevealsAnswer: true })],
  [s(12)]: [
    range("find-object", "划出find的完整宾语从句。", "what works best for their students", "what既连接又作works主语，整体指最有效的做法；不是直接提出问题。", "clause-object", "clause-boundary", { hintWords: ["what", "works", "best", "what works best for their students"] }),
    link("empower-actors", "把授权结构中的角色匹配起来。", [["the policy", "本可赋权、实际强推规则的制度安排"], ["teachers", "empowering宾语与to find的逻辑主语"]], "rather than empowering teachers to find", "empower somebody to do中somebody执行后面的动作；rather than排除这种方式，主句强调统一强推。", "nonfinite-subject", "attachment", { hintWords: ["empowering", "teachers", "find", "rather than empowering teachers"], mapRevealsAnswer: true }),
  ],
  [s(13)]: [choice("none-negation", "addresses none of ...怎样连起来理解？", ["一个也没有处理", "已经处理了全部", "只有少数问题还没处理"], 0, "addresses none of the truly thorny questions about homework", "否定放在宾语none上；不能因谓语是肯定形式addresses就漏掉否定。", "negation-contrast", "translation", { hintWords: ["none", "addresses", "thorny"] })],
  [s(14)]: [
    range("value-condition", "划出完整的If条件，保留宾语及宾补。", "If the district finds homework to be unimportant to its students' academic achievement", "finds A to be B在条件内评价作业有无益处；后面的减量或取消只是这一前提成立时的建议。", "clause-condition", "clause-boundary", { hintWords: ["If", "finds", "unimportant", "finds homework to be unimportant"], mapRevealsAnswer: true }),
    link("make-complement", "把make结构的宾语与补足动作配对。", [["them", "宾语：前面的assignments"], ["count for almost nothing", "宾补：作业计分权重近乎零"]], "not make them count for almost nothing", "make后用不带to的不定式；them是作业，不是学生。否定排除的是保留任务却让它几乎不计分的做法。", "object-complement", "reference", { hintWords: ["them", "make", "count", "count for almost nothing"], mapRevealsAnswer: true }),
  ],
  [s(15)]: [choice("value-before-weight", "与上句相对，if homework matters先假设什么？", ["作业有教育价值", "作业已经占总成绩的大多数", "作业中的事情很多"], 0, "if homework matters, it should account for a significant portion of the grade", "matters是动词重要；教育价值为前提，较大计分份额是结果，不可倒换。", "clause-condition", "passage-logic", { hintWords: ["matters", "Conversely", "account", "account for a significant portion"], mapRevealsAnswer: true, leaksToTasks: [{ sentenceId: "2012-p1-map", taskId: "value-first" }] })],
  [s(16)]: [
    range("first-ensure", "划出ensure的第一个完整that宾语从句，在逗号前停止。", "that the homework students receive is meaningful or appropriate to their age and the subject", "students receive是homework内部定语；is与homework构成外层主系表。第二个or that才开启并列的另一保障内容。", "clause-object", "clause-boundary", { hintWords: ["that", "is", "receive", "meaningful", "appropriate"] }),
    link("nested-subjects", "分别匹配三个谓语的实际主语。", [["receive", "students"], ["is meaningful", "the homework students receive"], ["are willing", "they，指teachers"]], "the homework students receive is meaningful or appropriate to their age and the subject, or that teachers are not assigning more than they are willing", "距离最近的名词不一定是主语；第一层the homework is，定语students receive，后层they are willing。their age的their另指学生。", "subject-head", "subject", { hintWords: ["receive", "is", "they", "their", "willing"] }),
    choice("ensure-limits", "does nothing to ensure说明什么？", ["政策没有采取保障措施，不能据此断言坏结果已全部发生", "政策已确保所有作业都不适当", "教师已经被证明没有批改能力"], 0, "does nothing to ensure", "缺乏保障不等于反面情况全部发生；willing说愿意检查批改，不是能够与否。", "negation-contrast", "option-logic", { hintWords: ["nothing", "ensure", "willing", "does nothing to ensure"], mapRevealsAnswer: true }),
  ],
  [s(17)]: [
    range("board-time", "划出完整while时间从句，包括董事会职责的插入说明。", "while the school board, which is responsible for setting educational policy, looks into the matter and conducts public hearings", "while从句中school board共享looks into和conducts，which从句嵌入主语之后；暂缓期间调查听证。", "clause-time", "clause-boundary", { hintWords: ["while", "which", "looks", "conducts", "is responsible for setting educational policy"] }),
    choice("hold-not-cancel", "put on hold在这里意味着什么？", ["暂缓执行，等待调查与听证", "立即永久取消所有作业", "把作业交由学生保管"], 0, "The homework rules should be put on hold", "on hold是暂停，不是永久取消；暂停对象为rules，调查对象为政策。", "lexical-context", "passage-logic", { hintWords: ["hold", "put", "be put on hold"], mapRevealsAnswer: true }),
  ],
  [s(18)]: [link("closing-infinitive", "把结句中的成分接到正确作用。", [["It", "形式主语，先占位置"], ["for L.A. Unified", "不定式的执行者"], ["right", "修饰do的副词：妥当地"]], "It is not too late for L.A. Unified to do homework right", "真正被评价的是学区把作业问题做好这件事；not too late说明仍可补救，right不是权利名词。", "nonfinite-subject", "attachment", { hintWords: ["It", "for", "right", "not too late", "do homework right"], mapRevealsAnswer: true })],
};
