import type { SentenceWordContext } from "./contextual-vocabulary";
type ReviewedContext=SentenceWordContext&{pattern:string;patternMeaning:string};
const w=(partOfSpeech:string,contextualMeaning:string,use:string,pattern:string,patternMeaning:string):ReviewedContext=>({partOfSpeech,contextualMeaning,use,pattern,patternMeaning,preferredCollocations:[pattern]});
const s=(n:number)=>`2012-p2-s${n}`;
const q=(n:number,key="prompt")=>`question-2012${n}-${key==="prompt"?"prompt":`option-${key}`}`;
export const passage2012P2ReviewedContexts:Record<string,Record<string,ReviewedContext>>={
[s(1)]:{
adult:w("adj.","成年的","adult作定语修饰women，与后面的young girls构成代际对比。","adult women","成年女性"),
remember:w("v.","记得；回忆起","remember接being动名词，回忆曾经存在的状态；不是remember to do记得去做。","remember being so obsessed with the colour","记得曾如此痴迷这种颜色"),
being:w("v.-ing（系动词的动名词形式）","处于；是","being引出obsessed状态，整体作remember宾语，不是独立的正在进行动作。","being so obsessed with the colour","如此痴迷这种颜色"),
obsess:w("adj.（过去分词性）","痴迷的","obsessed在being后说明女性的状态，with引痴迷对象。","being so obsessed with the colour","如此痴迷这种颜色"),
with:w("prep.","对；对于","with在obsessed with中引出痴迷对象，不是with独立结构。","obsessed with the colour","痴迷这种颜色"),
yet:w("conj.","然而；可是","连接成人回忆与当前女孩生活的反差，不表示尚未。","yet it is pervasive","然而它无处不在"),
it:w("pron.","它","it指pink及其文化呈现，作is主语，不是形式主语。","it is pervasive in our young girls' lives","它遍布我们年幼女孩的生活"),
young:w("adj.","年幼的","young直接限定girls，和adult women对照。","our young girls' lives","我们年幼女孩的生活"),
life:w("n.（复数）","生活","lives为life复数，指女孩各自的生活，不是live的三单动词。","our young girls' lives","我们年幼女孩的生活"),
do:w("aux.","用于构成否定","do not remember中do支撑一般现在时否定，主要动作是remember。","do not remember","不记得"),
},
[s(2)]:{
it:w("pron.（结构成分/实指代词）","它；结构占位词","句首It构成It is not that；but后的it与though后的it及fuses前it均指粉色。需按各自位置区分。","It is not that pink is intrinsically bad","并不是说粉色本身不好"),
that:w("conj.","引出内容判断","that pink is intrinsically bad是It is not that结构的内容，并非指示词那个。","that pink is intrinsically bad","粉色本身不好这一判断"),
such:w("det.","如此的；这样的","such a tiny slice中such加强后面名词短语的程度，不是such as举例。","such a tiny slice of the rainbow","彩虹中如此微小的一部分"),
slice:w("n.","一小片；一部分","a tiny slice以彩虹整体为参照，批评单一颜色对女孩形象的代表范围太窄。","a tiny slice of the rainbow","彩虹中的极小一片"),
though:w("conj.","虽然；尽管","引出让步：承认一种可能正面作用，主句仍批评身份与外貌绑定。","though it may celebrate girlhood in one way","尽管它或许以一种方式赞美女孩时期"),
may:w("modal v.","可能；或许","may celebrate表达可能性，不表示许可，也不把让步内容当作绝对结论。","may celebrate girlhood","或许赞美女孩时期"),
one:w("num./det.","一个；一种","one限定way，表示一种方式，不是代回前面名词的one。","in one way","以一种方式"),
identity:w("n.","身份；自我认同","girls' identity为fuses的宾语，被绑定的对象为appearance；不指身份证件。","fuses girls' identity to appearance","把女孩的身份绑定到外貌"),
to:w("prep.","与；到","fuse A to B中to引绑定目标appearance，并非不定式标记。","fuses girls' identity to appearance","把女孩身份同外貌紧密绑定"),
},
[s(3)]:{
it:w("pron.","它","指前句粉色及其文化呈现，作presents主语。","it presents that connection","它呈现那种联系"),
that:w("demonstrative det.","那种","限定connection，回指前句身份与外貌的绑定，不引从句。","that connection","那种联系"),
connection:w("n.","联系；连接","回指girls' identity to appearance所述联系，只采用可确认回指。","that connection","前句所说的那种联系"),
between:w("prep.","在……之间","此处between girls缺少完整的另一关系端点；只确认其介词形式，不补造缺失对象。","between girls","原文未完整展开的关系片段"),
only:w("adv.","仅仅","not only ... but ...构成递进，由无害推进为纯真的证据，不是only if条件。","not only innocent but as evidence of innocence","不仅无害，而且被当作纯真证据"),
as:w("prep.","作为；被当作","在present ... as ...中引出呈现的评价身份，后面从innocent推进到evidence。","as evidence of innocence","作为纯真的证据"),
old:w("adj.（复合名词组成）","岁的","界面将two-year-olds的后半显示为olds；须合回整个复数复合名词，指两岁儿童，而非年长者。","two-year-olds","两岁的儿童"),
},
[s(4)]:{
look:w("v.-ing（分词）","看；观察","Looking around作状语，逻辑主语为I，即作者。","Looking around","环顾四周"),
lack:w("n.","缺乏；不足","at后的名词中心为lack，of imagination说明缺少想象，about说明想象对象。","the singular lack of imagination","极为突出的想象贫乏"),
about:w("prep.","关于","about girls' lives and interests限定imagination的内容，不把缺乏想象归为女孩个人特征。","imagination about girls' lives and interests","对女孩生活与兴趣的想象"),
life:w("n.（复数）","生活","lives与interests并列，指女孩可以过的生活，不是多个生命或live动词。","girls' lives and interests","女孩的生活和兴趣"),
},
[s(5)]:{
attraction:w("n.","喜爱；偏好","attraction to pink表示女孩对粉色的偏好；to引被喜爱对象。","Girls' attraction to pink","女孩对粉色的喜爱"),
it:w("pron.","它；这种偏好","it回指Girls' attraction to pink；is not省略前面不可避免/写进DNA的表语，而非否认偏好现象存在。","it is not","它并非如此"),
associate:w("adj.（职级定语）","副的","修饰professor，整体为副教授；单词本身不承担完整的教授名词意义。","an associate professor of American Studies","一位美国研究副教授"),
american:w("adj.","美国的","American Studies是美国研究这一学术领域，不能把American单独作美国人名词。","American Studies","美国研究"),
study:w("n.（复数）","研究","Studies属于学科名称American Studies，不是studies的三单动词。","American Studies","美国研究这一学科"),
encode:w("v.-ed（分词）","编码；写入","encoded in DNA补充看似天生的印象，随后is not否定；勿把编码本身读成已证事实。","encoded in their DNA","被写进她们的DNA"),
to:w("prep.","对；根据结构的组成","attraction to中引偏好对象，according to中引信息来源；两处后接名词，不是不定式。","Girls' attraction to pink","女孩对粉色的喜爱"),
},
[s(6)]:{
white:w("n.（颜色名词）","白色；白色衣物","作wore宾语，表示婴儿穿的白色衣服；颜色选择由洗涤实际条件解释。","all babies wore white","所有婴儿都穿白色衣物"),
wear:w("v.（过去式）","穿；穿着","wore为wear不规则过去式，宾语white表示白色衣物。","all babies wore white","所有婴儿都穿白色衣物"),
get:w("v.-ing（动名词）","使；让","getting clothes clean中clothes为宾语，clean为宾补；使衣服变干净。","getting clothes clean","把衣服洗干净"),
clean:w("adj.","干净的","作clothes的宾语补足语，表示洗后的状态，不是另一个清扫动作。","getting clothes clean","使衣服变干净"),
since:w("conj.","因为","since意为因为，从句解释穿白衣的实际理由；不是自从某时。","since the only way of getting clothes clean was to boil them","因为清洁衣物的唯一办法是煮洗"),
they:w("pron.（宾格them）","它们","boil them中的them指clothes；被煮洗的是衣服。","to boil them","煮洗这些衣服"),
only:w("adj./det.","唯一的","only直接限定way，是当时唯一清洁办法；不是only if条件结构。","the only way of getting clothes clean","把衣服洗干净的唯一办法"),
before:w("prep.","在……之前","before后接domestic washing machines名词短语，表示家用洗衣机出现前的时代。","the era before domestic washing machines","家用洗衣机出现前的时代"),
all:w("adv./det.","完全；所有","at all在否定句中加强否定；all babies中的all则限定所有婴儿，两处功能不同。","not colour-coded at all","完全没有按颜色分类"),
matter:w("n.","事情；情况","as a practical matter整体表示出于实际考虑；matter是名词，不作重要或有关系的动词。","as a practical matter","出于实际考虑"),
},
[s(7)]:{
what:w("pron.（融合关系结构）","所……的东西","what were thought of...整体作wore宾语，what又作were thought主语；句首What's more则是补充说明固定表达，不与此混同。","what were thought of as gender-neutral dresses","被认为不分性别的裙装"),
more:w("adv.（固定表达成分）","更；另外","What's more整体表示此外，用于补充另一历史事实，非the more...the more比较结构。","What's more","此外"),
wear:w("v.（过去式）","穿；穿着","wore后接what名词性从句作宾语，衣物是不分性别的裙装。","wore what were thought of as gender-neutral dresses","穿着被视为性别中性的裙装"),
thought:w("v.-ed（被动分词）","认为；视为","were thought of as中thought为think过去分词，of/as共同构成视为结构。","thought of as gender-neutral dresses","被视为不分性别的裙装"),
as:w("prep.","作为；视为","thought of as B中as引出被认定的类别B。","as gender-neutral dresses","作为不分性别的裙装"),
},
[s(8)]:{
when:w("conj.","当……时","引出育儿配色开始采用的时间状语从句，不修饰某个先行名词。","When nursery colours were introduced","当婴幼儿配色被引入时"),
consider:w("v.-ed（被动分词）","被认为；被视为","pink为被动主语，the more masculine colour补足其被认定的身份。","pink was actually considered the more masculine colour","粉色实际上被认为是更男性化的颜色"),
more:w("adv.（比较级标记）","更","修饰形容词masculine，比较男性化程度，并非数量更多的名词定语。","the more masculine colour","更男性化的颜色"),
associate:w("v.-ed（被动分词）","联系；关联","was associated with说明红色与力量之间的文化联想。","was associated with strength","与力量联系在一起"),
which:w("relative pron.","关系代词，回指红色","非限制性定语从句主语，回指紧邻的red，描述其力量联想。","which was associated with strength","红色与力量有关"),
with:w("prep.","与","associated with中引出关联对象strength，不是with复合结构。","associated with strength","与力量相关联"),
red:w("n.","红色","of red中作介词宾语，指粉色所源出的深色，不是单独修饰名词的形容词。","a pastel version of red","红色的一种柔淡版本"),
},
[s(9)]:{
with:w("prep.","带有；具有","插入短语补充Blue的宗教和品格联想，后面无独立主谓结构。","with its intimations of the Virgin Mary, constancy and faithfulness","带有圣母玛利亚、坚定与忠贞的联想"),
its:w("possessive det.","它的","its回指Blue；intimations属于蓝色唤起的文化联想。","its intimations","它带来的联想"),
blue:w("n.","蓝色","Blue作symbolised主语，以颜色为名词谈文化象征。","Blue, with its intimations","蓝色以及它所引发的联想"),
},
[s(10)]:{
it:w("pron.（强调结构/实指）","它；强调结构成分","句首It构成It was not until...that时间强调；when it began中的it才回指pink。","It was not until the mid-1980s","直到1980年代中期才"),
that:w("强调结构连接成分","用于引出被强调时间对应的主句","It was not until ... that ...中that不代替任何实体，也不作pink句的主语。","that pink fully came into its own","粉色才真正兴盛"),
when:w("relative adv.","在那时","两处when补充mid-1980s/粉色兴盛时的营销与表象；第二处所述吸引力由seem限定。","when amplifying age and sex differences became a dominant children's marketing strategy","当放大年龄性别差异成为主导营销策略时"),
what:w("pron.（融合关系结构）","所……的东西","what defined them as female在of后作名词性从句，what兼作defined主语。","what defined them as female","界定她们为女性的事物"),
they:w("pron.（宾格them）","她们","defined them中的them指girls，as female说明分类身份。","defined them as female","把她们界定为女性"),
come:w("v.（过去式）","进入；来到","came into its own整体是走向兴盛、发挥自身作用；came为come过去式。","came into its own","真正兴盛起来"),
into:w("prep.（习语成分）","进入","与came及its own构成习语，不解释成具体空间进入。","came into its own","真正兴盛起来"),
own:w("pron.（习语成分）","自身应有的地位或作用","come into one's own整体读，own并不是另一个拥有动作。","came into its own","真正兴盛起来"),
its:w("possessive det.","它的","its在习语中指pink，保持第三人称所属。","came into its own","粉色真正兴盛起来"),
age:w("n.","年龄","与sex并列修饰differences，指年龄差异，不是历史时代。","age and sex differences","年龄与性别差异"),
sex:w("n.","性别","与age并列，构成市场细分的维度。","age and sex differences","年龄和性别差异"),
few:w("det.","几个；少数几个","the first few years表示最初几个年份，不是few单独表示几乎没有的强否定。","the first few critical years","最初几个关键年份"),
least:w("adv.（固定表达成分）","至少","at least表示保守下限，并未给出确切截止年龄。","at least for the first few critical years","至少在最初几个关键年份"),
for:w("prep.","在……期间","for引持续时间，和at least一起限定相关印象的年龄范围，不表示原因。","for the first few critical years","在最初几个关键年份"),
part:w("n.","部分","part of what...是对粉色作为女孩身份构成部分的补充说明。","part of what defined them as female","界定她们为女性的因素之一"),
},
[s(11)]:{
have:w("aux.（过去式had）","构成过去完成时","had not realised回顾作者在认识营销影响之前未意识到的状态；不译为拥有。","had not realised","此前没有意识到"),
how:w("adv.（内容从句连接成分）","多么；程度如何","how profoundly修饰dictated，整个内容从句作realised宾语。","how profoundly marketing trends dictated our perception","营销趋势多么深刻地左右我们的认知"),
what:w("pron.（融合关系结构）","所……的事物","what is natural to kids整体作of宾语，what又作is主语。","what is natural to kids","对孩子而言自然的事物"),
to:w("prep.","对……而言","natural to kids中to后接kids，说明何人觉得自然，不是不定式。","natural to kids","对孩子而言自然的"),
include:w("prep.","包括","including引出被营销左右的认知所包含的一项，非独立有限谓语。","including our core beliefs","包括我们的核心信念"),
core:w("adj.（定语）","核心的；基本的","修饰beliefs，指关于儿童心理发展的基本信念。","our core beliefs","我们的核心信念"),
development:w("n.","发展；成长过程","psychological development指儿童心理发展；被影响的直接宾语是对此的信念。","their psychological development","他们的心理发展"),
},
[s(13)]:{
that:w("demonstrative det.","那个","that限定phase组成内容从句主语，assumed后的连接词实际上省略；不能把that从phase剥离。","that phase","那个阶段"),
assume:w("v.（过去式）","以为；假定","assumed后接省略连接词的宾语从句，原先假设被wrong纠正。","I assumed that phase was something","我原以为那个阶段是某种东西"),
phase:w("n.","阶段","回指toddler概念；不是时尚phase或实验相位。","that phase","那个幼儿阶段"),
wrong:w("adj.","错误的","冒号后的省略评语否定作者此前的假设，不评价儿童行为对错。","wrong","这个设想错了"),
into:w("prep.","针对；关于","research into引出研究对象children's behaviour，不是进入某空间。","research into children's behaviour","针对儿童行为的研究"),
},
[s(14)]:{
cook:w("proper n.","库克（姓氏）","Daniel Cook是儿童消费史学者姓名；Cook此处为姓氏。","Daniel Cook","丹尼尔·库克"),
it:w("pron.","它；这一概念","指toddler术语/分类概念，作was popularised主语，不指具体孩子。","it was popularised as a marketing trick","该概念作为营销花招被推广"),
turn:w("v.（第三人称单数）","结果是；结果发现","Turns out是省略的引出结构，揭示与上一句假设相反的事实。","Turns out","结果发现"),
out:w("adv.（短语动词成分）","结果；显露出来","与Turns组成turn out，表示后来发现结果，不是向外走。","Turns out","结果发现"),
by:w("prep.","由","引出被动动作popularised的实际施事clothing manufacturers。","by clothing manufacturers","由服装制造商"),
},
[s(15)]:{
that:w("conj.","引出建议内容","that从句说明刊物劝商店做什么；中间目的短语是插入成分。","that, in order to increase sales, they should create","为了增销，商店应当创造这一建议"),
they:w("pron.","它们；这些商店","they指department stores，是should create的主语。","they should create","这些商店应当创造"),
order:w("n.（目的表达组成）","用于in order to表达目的","此处in order to后接increase，整体为为了增销，并非订单名词独立用法。","in order to increase sales","为了增加销售"),
sale:w("n.（复数sales）","销售；销售额","increase sales是提高销售额，尚未扣除成本，需与profits利润区别。","increase sales","增加销售额"),
should:w("modal v.","应该；应当","属于刊物对商店的建议，后接create原形，不是回顾过去的should have done。","they should create","商店应当创建"),
third:w("ordinal number（定语）","第三的","修饰stepping stone，比喻婴儿装与大童装之间新增的一层。",'a "third stepping stone"',"一个第三层过渡类别"),
stepping:w("v.-ing（复合名词组成）","踩踏；跨步（合成词成分）","stepping stone整体为踏脚石/跳板，本句借指第三消费层级。",'a "third stepping stone"',"一个第三层过渡类别"),
wear:w("n.","服装","infant wear指婴儿装，wear作名词，与clothes组成两端。","between infant wear and older kids' clothes","在婴儿装与大童服装之间"),
department:w("n.（复合名词成分）","部门；商品部类","department store整体为百货商店，本句商店是被建议者。","department stores","百货商店"),
},
[s(16)]:{
it:w("pron.（强调结构/实指）","它；强调结构成分","句首It属于It was only after...that强调结构；evolved前it才回指toddler术语。","it evolved into a broadly accepted developmental stage","该概念演变成广泛认可的发展阶段"),
that:w("强调结构连接成分","引出强调时间对应的主句","与It was only after配合，强调先成为购物术语，再成为普遍认可的发展阶段。","that it evolved into a broadly accepted developmental stage","它才演变成广泛认可的发展阶段"),
only:w("adv.","只有；仅在","only限定after时间条件，强调顺序，后接的并不是if从句。",'only after "toddler" became a common shoppers\' term',"只有在幼儿成为购物常用术语之后"),
into:w("prep.","成为；进入某种状态","evolved into后面为演变结果a...stage，不是具体空间地点。","evolved into a broadly accepted developmental stage","演变为广泛认可的发展阶段"),
accept:w("adj.（过去分词性）","被认可的；被接受的","broadly accepted作前置定语修饰stage，表示社会广泛接受，不代表已作科学验证。","a broadly accepted developmental stage","一个被广泛认可的发展阶段"),
},
[s(17)]:{
split:w("v.-ing（动名词）","划分；分开","Splitting kids, or adults, into ...整体作has proved主语，kids/adults是其内部宾语。","Splitting kids, or adults, into ever-tinier categories","把孩子或成人划成越来越细的类别"),
adult:w("n.（复数）","成年人","or adults补充同样可细分的另一群体，作Splitting宾语。","kids, or adults","孩子，或成年人"),
prove:w("linking v.（完成时分词）","结果表明是；证明是","has proved后接名词表语a sure-fire way，说明分类行为的性质。","has proved a sure-fire way","已经表明是一个可靠办法"),
have:w("aux.（第三人称单数has）","构成现在完成时","has与proved构成完成时，主语中心是整个Splitting行为，不随categories复数变化。","has proved","已证明是"),
into:w("prep.","分成；归入","split A into B中into引分类结果，而非移动进入。","into ever-tinier categories","分成越来越细小的类别"),
},
[s(18)]:{
one:w("pron./num.","一个；其中之一","one of the easiest ways主语中心为one，因此谓语用is而非are。","one of the easiest ways","最容易的办法之一"),
where:w("conj./relative adv.（状语连接）","在……地方或情形中","where从句限定invent的情形，前面无名词先行词；they指gender differences。","where they did not previously exist","在这些差异原本不存在的情形中"),
they:w("pron.（主格/宾格）","它们","invent them的宾格them与where they...的主格they都指gender differences。","invent them where they did not previously exist","在原本没有这些差异的情形中制造它们"),
do:w("aux.（过去式did）","构成一般过去时否定","did not与exist组成否定谓语；did不承担做这一独立动作。","did not previously exist","此前并不存在"),
},
[q(26)]:{
means:w("v.（第三人称单数）","意指；表示","the author means中means是mean的三单谓语，后接pink内容从句。","the author means pink","作者意在表达粉色（后接选项）"),
it:w("pron.","它","题干所引it is...the rainbow的it对应原文pink，不是形式主语。",'"it is… the rainbow"',"它是……彩虹（原题省略引文）"),
by:w("prep.","通过","By saying给表达含义的方式，后接动名词。",'By saying "it is… the rainbow"',"通过说它是……彩虹"),
},
[q(26,"B")]:{
associate:w("v.-ed（被动分词）","联系；关联","should not be associated否定应有的关联，with引girls' innocence。","be associated with girls' innocence","与女孩的纯真联系起来"),
should:w("modal v.","应该","should not be associated给出不应有关联的规范判断。","should not be associated","不应被联系起来"),
},
[q(26,"C")]:{should:w("modal v.","应该","should not be the sole representation否定唯一代表性，未否定任何代表作用。","should not be the sole representation","不应成为唯一代表")},
[q(27)]:{
which:w("interrogative pron.","哪一个","which of the following是疑问主语，问下列选项中哪项成立，不是定语从句关系词。","which of the following","下列各项中的哪一个"),
follow:w("adj.（分词性）","下面的；随后列出的","the following名词化指随后列出的选项，不是跟随某人的动作。","the following","下面列出的内容"),
},
[q(27,"B")]:{use:w("semi-modal construction","曾经","used to be regarded说过去曾被看作，不能按使用或习惯于解释。","used to be regarded as the colour for girls","过去被视为女孩的颜色")},
[q(27,"C")]:{white:w("n.（颜色名词）","白色","White为被动句主语，选项主张婴儿偏爱白色；是否符合证据另行判断。","White is preferred by babies","白色被婴儿偏爱")},
[q(27,"D")]:{use:w("semi-modal construction","曾经","used to be讲过去的状态，不是使用或be used to doing。","used to be a neutral colour","曾是一种中性颜色"),neutral:w("adj.","中性的；不分性别的","neutral修饰colour，范围由in symbolising genders限定，不是政治中立。","a neutral colour in symbolising genders","象征性别时中性的颜色")},
[q(28)]:{
that:w("conj.","引出内容","that从句作suggests宾语，主语为our perception。","that our perception of children's psychological development","我们对儿童心理发展的认知这一命题"),
much:w("adv.","很大程度地","修饰was influenced的程度，不是在限定名词数量。","was much influenced","受到很大影响"),
development:w("n.","发展；成长过程","psychological development为心理发展，直接被影响的主语却是our perception。","children's psychological development","儿童的心理发展"),
},
[q(28,"C")]:{into:w("prep.","针对；关于","researches into后接研究对象，researches是原卷名词复数。","researches into children's behaviour","对儿童行为的研究")},
[q(28,"D")]:{consumption:w("n.","消费","childhood consumption指儿童时期的消费行为，作为studies的研究主题。","studies of childhood consumption","儿童消费研究")},
[q(29)]:{
learn:w("v.","得知；推知","may learn from Paragraph 4要求从第四段获取推断，不是学习技能。","learn from Paragraph 4","从第四段得知"),
that:w("conj.","引出得知的内容","that department stores were advised...为learn宾语从句。","that department stores were advised","百货商店被建议这一内容"),
department:w("n.（复合名词成分）","部门；商品部类","department stores整体为百货商店，是were advised的被动主语。","department stores","百货商店"),
},
[q(29,"A")]:{into:w("prep.","分成","classify consumers into smaller groups给分类结果。","into smaller groups","分成更小的群体")},
[q(29,"B")]:{equal:w("adj.","同等的","equal修饰importance，表示重视程度相同，不是名词地位平等者。","equal importance","同等的重要性"),to:w("prep.","对；于","attach importance to中的to引重视对象different genders，非不定式。","to different genders","对不同性别")},
[q(29,"C")]:{wear:w("n.","服装","infant wear为婴儿服装，与older kids' clothes并列，作on宾语。","infant wear and older kids' clothes","婴儿装和大童服装")},
[q(30)]:{
it:w("pron.（形式主语）","形式主语","It对应后置that命题，不指粉色实体；can be concluded说明可以推知。","It can be concluded","可以得出结论"),
that:w("conj.","引出结论内容","that girls' attraction...为后置主语从句，对应形式主语It。","that girls' attraction to pink seems to be","女孩对粉色的喜爱似乎（后接选项）"),
},
[q(30,"B")]:{explain:w("v.-ed（被动分词）","解释","explained承接题干be组成被动，by引所声称的解释依据。","explained by their inborn tendency","由她们的天生倾向解释"),their:w("possessive det.","她们的","their回指girls，限定女孩的inborn tendency。","their inborn tendency","她们的天生倾向")},
[q(30,"D")]:{well:w("adv.","充分地；妥当地","修饰interpreted说明解释程度/质量，不是健康形容词。","well interpreted","得到充分解释")},
};
const additional:Record<string,Record<string,ReviewedContext>>={
[s(2)]:{of:w("prep.","……中的","slice of the rainbow给部分所属的整体；本句不是效果或制成材料关系。","a tiny slice of the rainbow","彩虹中极小的一片")},
[s(3)]:{of:w("prep.","……的","evidence of innocence给证据所证明的性质。","evidence of innocence","纯真的证据")},
[s(4)]:{of:w("prep.","……的","lack of imagination给缺少的内容imagination。","lack of imagination","想象力的缺乏")},
[s(5)]:{of:w("prep.","……领域的","professor of American Studies说明教授所属学术领域。","professor of American Studies","美国研究教授")},
[s(6)]:{
early:w("adj.","早期的；初期的","修饰20th century，指20世纪初期；时间相对于原文历史叙述。","the early 20th century","20世纪初期"),
as:w("prep.","就……而言；从……考虑","as a practical matter是评注介词表达，用实际洗涤条件解释穿白衣。","as a practical matter","出于实际考虑"),
of:w("prep.","……的","way of doing中of后接动名词说明办法的具体任务。","of getting clothes clean","把衣服洗干净这一事项"),
to:w("infinitive marker","不定式标记","to boil them整体作was表语，说明清洁衣物的方法。","to boil them","将衣物煮洗"),
},
[s(7)]:{of:w("prep.（短语动词成分）","用于think of，表示看待","thought of as共同构成被视为，of不连接数量或材料。","thought of as gender-neutral dresses","被视为不分性别的裙装")},
[s(8)]:{introduce:w("v.-ed（被动分词）","引入；开始采用","were introduced说婴幼儿颜色分类开始被采用，被动主语是nursery colours。","nursery colours were introduced","开始采用婴幼儿配色"),of:w("prep.","……的一种","version of red指以红色为基础的一种柔淡版本。","a pastel version of red","红色的一种柔淡版本")},
[s(9)]:{of:w("prep.","关于；涉及","intimations of给出联想内容，后面三项共同受of支配。","intimations of the Virgin Mary, constancy and faithfulness","对圣母玛利亚、坚定和忠贞的联想")},
[s(10)]:{as:w("prep.","作为；为","define them as female中as引分类身份female，不是时间连词。","defined them as female","将她们界定为女性"),of:w("prep.","……中的","part of what...给整体范围，what名词性从句作of宾语。","part of what defined them as female","界定她们为女性的事物的一部分"),to:w("infinitive marker / prep.","不定式标记；对","began to seem中的to引不定式，attractive to girls中的to引吸引对象，分别辨认。","began to seem inherently attractive to girls","开始显得天生吸引女孩")},
[s(11)]:{of:w("prep.","关于；对于","perception of引认知对象，后接what名词性从句。","perception of what is natural to kids","对孩子何为自然的认知")},
[s(13)]:{of:w("prep.","……的","years of research把多年时间与研究活动联系起来。","years of research into children's behaviour","对儿童行为的多年研究")},
[s(14)]:{as:w("prep.","作为","as a marketing trick说明推广概念的方式或身份，而非时间状语。","as a marketing trick","作为营销花招"),of:w("prep.","……领域的","historian of childhood consumerism限定历史学家的研究领域。","a historian of childhood consumerism","一位儿童消费主义史学家"),to:w("prep.（固定表达成分）","根据；按","according to后接Daniel Cook，说明信息来源，不是不定式。","according to Daniel Cook","根据丹尼尔·库克的说法")},
[s(15)]:{to:w("infinitive marker","不定式标记","in order to increase整体为目的表达，to后接increase原形。","in order to increase sales","为了增加销售额")},
[s(17)]:{to:w("infinitive marker","不定式标记","to boost profits修饰way，说明这一办法用来达成的目的。","a sure-fire way to boost profits","提高利润的一种可靠办法")},
[s(18)]:{of:w("prep.","……之中的","one of后接复数名词短语，表示其中一个；主语仍以one为中心。","one of the easiest ways","最容易的办法之一"),to:w("infinitive marker","不定式标记","to segment修饰ways，to magnify作is表语；or invent共用第二个to。","to magnify gender differences","放大性别差异")},
[q(26,"A")]:{of:w("prep.","……的","lack of imagination说明缺少的内容；girls'则限定缺少者。","girls' lack of imagination","女孩缺乏想象力")},
[q(26,"B")]:{with:w("prep.","与","associated with后接关联对象girls' innocence，无独立主谓搭配。","with girls' innocence","与女孩的纯真")},
[q(26,"C")]:{of:w("prep.","……的","representation of girlhood给被代表对象。","representation of girlhood","女孩时期的代表")},
[q(27)]:{to:w("prep.（固定表达成分）","根据；按照","According to Paragraph 2给证据出处，后接名词，不引不定式。","According to Paragraph 2","根据第二段"),of:w("prep.","……中的；对于","which of the following从后列选项中选择，true of colours说明适用主题。","which of the following","下列选项中的哪项")},
[q(27,"B")]:{as:w("prep.","作为；被视为","regarded as后接被认定身份the colour for girls，不是时间连词。","as the colour for girls","作为女孩的颜色"),to:w("semi-modal construction component","用于used to，表示过去曾经","used to be regarded构成过去曾被看作的陈述，to后接be原形。","used to be regarded","过去曾被视为")},
[q(27,"D")]:{to:w("semi-modal construction component","用于used to，表示过去曾经","used to be后接过去被认为成立的表语，不表示习惯于。","used to be a neutral colour","过去曾是一种中性颜色")},
[q(28)]:{of:w("prep.","关于；对于","perception of后接被认知对象children's psychological development。","our perception of children's psychological development","我们对儿童心理发展的认知")},
[q(28,"A")]:{of:w("prep.","对于；针对","observation of后接观察对象children's nature。","the observation of children's nature","对儿童天性的观察")},
[q(28,"B")]:{of:w("prep.","关于；对于","marketing of products表示营销的对象为产品，for children再限定产品受众。","the marketing of products for children","儿童产品营销")},
[q(28,"D")]:{of:w("prep.","关于；针对","studies of给研究主题，而非研究实际造成的影响。","studies of childhood consumption","对儿童消费的研究")},
[q(29)]:{to:w("infinitive marker","不定式标记","were advised to后由选项动词补足建议行动，执行者为department stores。","were advised to","被建议去做（选项动作）")},
[q(30)]:{to:w("prep. / infinitive marker","对；不定式标记","attraction to pink中的to引偏好对象；seems to be中的to引内容补足不定式。","girls' attraction to pink","女孩对粉色的偏好")},
};
for(const [sourceId,rows] of Object.entries(additional))passage2012P2ReviewedContexts[sourceId]={...passage2012P2ReviewedContexts[sourceId],...rows};
export const passage2012P2ContextGlosses:Record<string,{meaning:string;note?:string}>=Object.fromEntries(Object.values(passage2012P2ReviewedContexts).flatMap(rows=>Object.values(rows).map(row=>[row.pattern.toLowerCase(),{meaning:row.patternMeaning,note:row.use}])));
