import type {SentenceWordContext} from "./contextual-vocabulary";
type C=SentenceWordContext&{pattern:string;patternMeaning:string};
const w=(partOfSpeech:string,contextualMeaning:string,use:string,pattern:string,patternMeaning:string):C=>({partOfSpeech,contextualMeaning,use,pattern,patternMeaning,preferredCollocations:[pattern]});
const s=(n:number)=>`2012-p3-s${n}`,q=(n:number,k="prompt")=>`question-2012${n}-${k==="prompt"?k:`option-${k}`}`;
export const passage2012P3ReviewedContexts:Record<string,Record<string,C>>={
[s(1)]:{
industry:w("n.","产业；行业","biotech industry是受到裁决震动的领域，非个人勤劳品质。","America's biotech industry","美国生物技术产业"),
its:w("possessive det.","它的","its指受影响的biotech industry，core是其根基的比喻。","to its core","直至产业根基"),
to:w("prep.","到；达到","to its core加强shook的程度，不接动词原形。","shook America's biotech industry to its core","深刻震动美国生物技术产业"),
},
[s(2)]:{
have:w("aux.（had）","构成过去完成时","had won说明2010裁决以前数十年取得专利的背景，had不单独表示拥有。","had won patents","此前已取得专利"),
for:w("prep.","关于；持续","for isolated DNA给专利对象，for decades给持续时间；按后接成分分辨。","patents for isolated DNA for decades","数十年来取得分离DNA专利"),
by:w("prep.","截至；到……时","by 2005为历史统计截止，非被动施事。","by 2005","截至2005年"),
some:w("adv.","大约","位于20%之前表示约数，不是某些20%。","some 20% of human genes","约20%的人类基因"),
patent:w("n. / v.-ed（被动）","专利；授予专利","won patents中的patents为名词，were patented中的patented为被动分词；同句词形决定词性。","human genes were patented","人类基因被授予专利"),
},
[s(3)]:{that:w("conj.","引出裁定内容","that genes were unpatentable作ruled宾语，that不作从句成分。","that genes were unpatentable","基因不具备可专利性这一裁定")},
[s(4)]:{agitate:w("adj.（分词性）","不安的；焦躁的","agitated在were后描述高管心理状态；violently表示强烈程度。","were violently agitated","极度焦躁不安")},
[s(5)]:{
industry:w("n.（专名组成）","产业；行业","Industry在行业组织全称中限定所属领域。","Biotechnology Industry Organisation","生物技术产业组织"),
that:w("conj.","引出保证内容","assured members that...先接被安抚的人，再给保证命题。",'that this was just a "preliminary step"',"这不过是初步一步这一保证"),
this:w("demonstrative pron.","这；此次裁决","回指2010年3月不利判决，是was主语。",'this was just a "preliminary step"',"此次判决只是初步一步"),
battle:w("n.（比喻）","较量；斗争","longer battle比喻后续围绕基因专利的法律争取，不指实体战争。","in a longer battle","在更长期的较量中"),
},
[s(6)]:{
they:w("pron.","他们","回指前文因不利裁决而不安的企业高管和行业方。","they were relieved","他们松了口气"),
relieve:w("adj.（分词性）","宽慰的；安心的","relieved为情绪状态，at least temporarily限制宽慰仅至少暂时存在。","were relieved, at least temporarily","至少暂时感到宽慰"),
least:w("adv.（固定表达成分）","至少","at least temporarily确认最低限度的暂时宽慰，不表示永久结果。","at least temporarily","至少暂时如此"),
on:w("prep.","在（某日）","On July 29th给具体月日，原文未在此标年份。","On July 29th","在7月29日"),
},
[s(7)]:{
appeal:w("n.（复数定语）","上诉","appeals修饰court，整体为上诉法院，不作动词呼吁。","A federal appeals court","一家联邦上诉法院"),
rule:w("v.-ing（分词）","裁定；判决","ruling与overturned共用法院施事，后接that宾语从句。","ruling that Myriad Genetics could indeed hold patents","裁定Myriad确实可以持有专利"),
that:w("conj. / relative pron.","内容连接词；关系代词","第一个that引ruling内容，不作内部主语；第二个that代two genes作help主语。","that help forecast a woman's risk of breast cancer","有助于预测女性乳腺癌风险的（基因）"),
can:w("modal v.（could）","可以；获准","could hold表达所报道裁决的许可，不是公司能力强弱或假想推测。","could indeed hold patents to two genes","确实可以持有两个基因的专利"),
hold:w("v.","持有；拥有","hold patents指拥有专利权，并非举办或拿在手上。","hold patents to two genes","持有两个基因的专利"),
to:w("prep.","关于；对于","patents to two genes中to后接名词，给专利对象。","patents to two genes","两个基因的专利"),
help:w("v.","帮助；有助于","help后接省to的forecast，基因有助于预测风险，不直接确诊。","help forecast a woman's risk of breast cancer","有助于预测女性患乳腺癌的风险"),
},
[s(8)]:{
chief:w("adj.","首席的；最高的","chief修饰executive构成最高经营负责人职位，不是独立名词首领。","The chief executive of Myriad","Myriad的首席执行官"),
ruling:w("n.","裁决；判决","the ruling为said内容从句的主语，与前句分词ruling功能不同。","the ruling was a blessing","裁决是福音"),
to:w("prep.","对；对于","blessing to引被认为受益的两类对象firms and patients。","a blessing to firms and patients alike","对企业和患者同样是福音"),
patient:w("n.（复数）","患者","patients与firms并列作to宾语，不是耐心的形容词。","firms and patients alike","企业和患者双方"),
alike:w("adv.","同样地；都","后置修饰两项并列对象，将企业和患者都纳入高管评价。","firms and patients alike","企业与患者同样如此"),
},
[s(9)]:{
as:w("conj.","随着","as companies continue...引时间发展背景，不是as名词身份结构。","as companies continue their attempts at personalised medicine","随着企业继续探索个性化医疗"),
rather:w("adv.","相当","直接修饰busy的程度，此处不与than组合。","rather busy","相当忙碌"),
remain:w("linking v.","仍然；保持","will remain接busy形容词表语，说明法院仍然繁忙。","will remain rather busy","仍将相当忙碌"),
at:w("prep.","针对；在……方面","attempts at引尝试领域personalised medicine，不是时刻。","attempts at personalised medicine","个性化医疗方面的尝试"),
},
[s(10)]:{over:w("adj./predicative adv.","结束的","作is后表语，not over为未结束，probably又限制确定性。","is probably not over","很可能还没结束")},
[s(11)]:{
make:w("v.","提出","make arguments为提出论点，arguments为宾语，非使役make A do。","make three main arguments","提出三个主要论点"),
against:w("prep.","反对","限定arguments所反对的对象gene patents，不是保险防范。","arguments against gene patents","反对基因专利的论点"),
it:w("pron.","它","第一处it代gene作may not be patented主语；第二处代innovation作reward宾语。","rather than reward it","而非奖励创新"),
may:w("modal v.","可以；获准","may not be patented在批评者理由中为不得授专利，不是概率上可能没申请。","may not be patented","不得被授予专利"),
so:w("conj./adv.（结果连接）","所以；因此","连接自然属性与不得授专利的推论，这条因果属于批评者。","so it may not be patented","所以不得为它授予专利"),
product:w("n.","产物","a product of nature表示自然产物，不限于工业商品。","a product of nature","自然产物"),
as:w("prep.（举例结构成分）","例如；像","such as Myriad's举检测例子，Myriad's后省略tests；不引时间从句。","such as Myriad's","例如Myriad公司的检测"),
to:w("prep.","对；获得……的","access to genetic tests给可获得服务，后接名词，非不定式。","access to genetic tests","获得基因检测服务的机会"),
rather:w("adv.（对照结构成分）","而非","rather than reward it与suppress对照，it指innovation。","rather than reward it","而不是奖励创新"),
than:w("conj./prep.（对照结构成分）","而不是","与rather组成取舍对照，不表示数量比较。","rather than reward it","而非奖励创新"),
},
[s(12)]:{
number:w("n.（数量表达中心）","人数；一批人","A growing number省略people，谓语seem按复数群体理解；并未限定具体职业。","A growing number seem to agree","越来越多的人似乎认同"),
agree:w("v.","认同；赞同","承前认同批评者的论点，seem保留看来如此，不是签署正式协议。","seem to agree","似乎表示认同"),
},
[s(13)]:{
last:w("adj.（时间限定）","上一个的","Last year指文章写作时点的前一年，不是末日或持续动词。","Last year","去年（相对文章时点）"),
reform:w("n.","改革","urged的宾语，报告工作组呼吁改革，不表示已经实施。","urged reform","敦促改革"),
relate:w("v.-ed（分词）","相关的；有关联的","related to后置修饰patents，没有独立限定时态。","patents related to genetic tests","与基因检测相关的专利"),
to:w("prep.","与；同","related to引关系对象genetic tests，并非不定式。","related to genetic tests","与基因检测相关"),
},
[s(14)]:{
file:w("v.（过去式）","提交","filed a brief为向法院正式提交书面意见，不是申请专利。","filed a brief","提交法律书面意见"),
brief:w("n.","法律书面意见；诉讼文书","a brief作filed宾语，arguing后给内容；并非简短形容词。","filed a brief in the Myriad case","在Myriad案中提交法律书面意见"),
argue:w("v.-ing（分词）","主张；论证","arguing与filed共用司法部作逻辑施事，说明书面意见内容。","arguing that an isolated DNA molecule","主张一个分离出的DNA分子（后接内容）"),
that:w("conj. / relative pron.","内容连接词；关系代词","第一that引arguing内容；最后that回指cotton fibres，作have been separated主语。","that have been separated from cotton seeds","已从棉籽中分离出来的（纤维）"),
less:w("adv.（比较结构）","更少；较低程度","no less ... than否定较低自然属性，在此类比为DNA与棉纤维同样是自然产物。","no less a product of nature…than are cotton fibres","与棉纤维同样是自然产物"),
than:w("conj.","与……相比","引比较标准分句，are倒装在长主语cotton fibres之前。","than are cotton fibres that have been separated from cotton seeds","与从棉籽中分离出的棉纤维相比"),
have:w("aux.","构成完成时","have been separated为现在完成时被动，have不是实义拥有。","have been separated from cotton seeds","已从棉籽分离"),
nature:w("n.","自然界","product of nature给自然来源，不是人的性格。","a product of nature","自然产物"),
product:w("n.","产物","DNA与棉纤维被作为自然产物比较，而非工业商品。","a product of nature","自然产物"),
},
[s(15)]:{remain:w("linking v.","仍然；保持","remain unanswered为系表，说明问题尚未得到回答，不是身体残骸名词。","remain unanswered","仍未得到回答")},
[s(16)]:{
it:w("pron.（形式主语/实指）","它；形式主语","句首it对应whether整个命题；within it中的it指a whole genome，需按位置区分。","it is unclear whether","是否如此尚不清楚"),
whether:w("conj.","是否","引后置主语从句，对应形式it；不是假设条件如果。","whether the sequencing of a whole genome violates","整个基因组测序是否侵犯（后接对象）"),
individual:w("adj.","单个的；个别的","修饰genes，与whole genome整体范围对照，不是个人名词。","individual genes within it","该基因组内部的单个基因"),
within:w("prep.","在……内部","within it说明genes位于整个基因组内部，不是未来时间界限。","within it","在该基因组内部"),
for:w("prep.（举例表达组成）","用于for example举例","For example连接前句未解问题与具体测序疑问，不表示原因或目的。","For example","例如"),
},
[s(17)]:{
may:w("modal v.","可能","may yet reach表示从文中时点看后续可能到达最高法院，非报告已完成。","may yet reach the Supreme Court","今后仍可能进入最高法院"),
yet:w("adv.","仍；以后还可能","与may同用保留后续发生的可能，不是转折连词。","may yet reach","仍可能到达"),
},
[s(18)]:{
as:w("conj.","随着","As the industry advances是时间发展背景从句，industry为主语。","As the industry advances","随着产业发展"),
have:w("v.","产生；具有","have an impact表示产生影响，为实义动词，不是完成时助动词。","have an even greater impact","产生更大的影响"),
great:w("adj.（比较级greater）","更大的","greater修饰impact程度，不预设影响一定更好或更坏。","an even greater impact","更大的影响"),
even:w("adv.","甚至；还","加强greater比较级，说明其他案件影响可能还更大。","even greater","甚至更大的"),
},
[s(19)]:{
file:w("v.","提出申请","file patents是提出专利申请的压缩表达，不等于已经获批。","file many more patents","大量提出新的专利申请"),
most:w("pron.","大多数","回指human DNA molecules，而非企业；后面给两种已有状态。","most are already patented or in the public domain","大多数分子已经有专利或处于公有领域"),
more:w("det.（比较级）","更多的；额外的","many more patents为大量额外专利，unlikely不等于绝无新的申请。","many more patents","大量新增专利"),
public:w("adj.","公有的","public domain为公有领域，和patented并列形成不同状态。","in the public domain","处于公有领域"),
},
[s(20)]:{
how:w("adv.（内容从句连接）","如何；怎样","how genes interact作studying宾语，how给互动方式，没有how adjective程度结构。","how genes interact","基因如何相互作用"),
that:w("relative pron.","关系代词，回指关联","that修饰correlations，又作might be used被动主语。","that might be used to determine the causes of disease or predict a drug's efficacy","可能用于查明病因或预测药效的（关联）"),
may:w("modal v.（might）","可能","might限制关联的潜在用途，不表过去的获准，也不保证可证因果。","might be used","可能被用于"),
use:w("v.-ed（被动分词）","使用；利用","might be used to do表示可能被用于达成用途，非used to do过去常常。","be used to determine the causes of disease","被用于查明病因"),
determine:w("v.","查明；确定","这里determine以causes为对象是查明病因；另一句determined by suit则为决定成败。","determine the causes of disease","查明疾病的原因"),
for:w("prep.（短语动词成分）","寻找的对象标记","looking for correlations整体为寻找关联，不解释成持续时间。","looking for correlations","寻找相关关系"),
},
[s(21)]:{
for:w("prep.","关于；为……服务","patents for引专利对象，lawyer for BIO说明为机构服务，两处不是原因。",'patents for "connecting the dots',"将串联线索作为对象的专利"),
win:w("v.","取得；赢得","to win patents说明企业渴望的目标，并不宣告已获批准。",'win patents for "connecting the dots',"为串联线索取得专利"),
explain:w("v.（第三人称单数）","解释；说明","explains Hans Sauer为报道分句主谓倒装，Hans是主语。","explains Hans Sauer","Hans Sauer解释说"),
},
[s(22)]:{
their:w("possessive det.","它们的","指希望取得关联专利的企业，success为其申请成败。","Their success","企业的成功"),
determine:w("v.-ed（被动分词）","决定；影响成败","may be determined by suit表示诉讼可能决定成功，不是查明病因。","may be determined by a suit","可能由一项诉讼决定"),
bring:w("v.-ed（分词）","提起（诉讼）","brought by...后置修饰suit，说明提起案件的主体为诊所。","brought by the Mayo Clinic","由梅奥诊所提起"),
which:w("relative pron.","关系代词，指诉讼","which作hear的宾语，先行词为suit；Mayo Clinic是提起者，不能按距离误判。","which the Supreme Court will hear in its next term","最高法院将在下一审期审理的案件"),
its:w("possessive det.","它的","its回指Supreme Court，next term为该法院下一审期。","in its next term","在该法院下一审期"),
this:w("demonstrative det.","这个；这一","this限定issue，承前关于为基因互动关联获得专利的议题。","related to this issue","与这一议题相关"),
to:w("prep.","与；同","related to引关联议题，不是不定式标记。","related to this issue","与这一议题有关"),
},
[s(23)]:{
hold:w("v.（过去式）","举办；召开","held a convention为举办大会，和hold patents的持有权利区分。","held a convention","举办了一次大会"),
which:w("relative pron.","关系代词，指大会","which回指convention，作included主语。","which included sessions","包含专题场次的大会"),
on:w("prep.","关于；就……内容","coach lawyers on给培训主题the shifting landscape for patents。","on the shifting landscape for patents","关于变化中的专利形势"),
},
[s(24)]:{pack:w("adj.（分词性）","挤满人的；满座的","packed在was后描写会议人数，非打包物件。原有crowded替换保留人多但程度略弱。","Each meeting was packed","每场会议都座无虚席")},
[q(31)]:{
it:w("pron.（形式主语）","形式主语","It对应后置that内容，不指公司或基因。","It can be learned from Paragraph 1","可从第一段得知"),
learn:w("v.-ed（被动分词）","得知；推知","can be learned from要求从段落证据推出企业期望，并非学会技能。","can be learned from Paragraph 1","可从第一段得知"),
will:w("modal v.（would）","用于would like表达愿望","would like表示企业希望怎样，不是过去视角未来。","would like","希望；想要"),
like:w("v.","希望；想要","would like后由选项补对象＋不定式，like并非比较介词像。","would like","希望"),
that:w("conj.","引出推知内容","that从句对应形式主语It，主语companies，谓语would like。","that the biotech companies would like","企业希望（后接选项）这一命题"),
},
[q(31,"B")]:{issue:w("v.","发布；发出","to issue a warning中issue为动词原形，不是议题名词。","to issue a warning","发布一项警告")},
[q(31,"C")]:{their:w("possessive det.","它们的","their指题干biotech companies，限定企业自己的高管。","their executives","它们的高管")},
[q(31,"D")]:{rule:w("v.（短语动词组成）","排除；不予考虑","rule out整体为排除基因专利，并非rule that裁定后接命题。","rule out gene patenting","排除基因授专利"),out:w("particle","用于rule out，表示排除","与rule构成整体，gene patenting为被排除对象。","rule out gene patenting","排除基因授专利")},
[q(32)]:{
who:w("relative pron.","关系代词，指反对者","who修饰Those并作are主语，不是疑问词谁。","who are against gene patents","反对基因专利的（人）"),
against:w("prep.","反对","are against为反对立场，against短语作表语。","against gene patents","反对基因专利"),
that:w("conj.","引出相信的内容","believe that之后由四个完整命题选项补足，不是指示词那个。","believe that","认为（后接选项）"),
},
[q(32,"B")]:{only:w("adv.（范围限定）","只有；仅有","only限定man-made products作为可专利对象的必要条件，不能反推所有人造产品均能获专利。","only man-made products are patentable","只有人造产品才具备可专利的可能")},
[q(32,"C")]:{much:w("adv.","很大程度地","much修饰depend的程度，而非某名词的数量。","depend much on innovation","很大程度取决于创新"),on:w("prep.","关于；取决于的对象标记","patents on genes给专利对象；depend on innovation给依赖因素，两处分别辨认。","depend much on innovation","很大程度取决于创新")},
[q(32,"D")]:{should:w("modal v.","应该；应当","should restrict提出规范建议，不是评价过去的should have done。","courts should restrict access","法院应当限制可及机会"),to:w("prep.","对；获得……的","access to后接服务genetic tests，非不定式。","access to genetic tests","获得基因检测的机会")},
[q(33)]:{to:w("prep. / infinitive marker","根据的组成；不定式标记","According to后接信息来源Hans Sauer；eager to win的to引愿望内容，两处功能不同。","According to Hans Sauer","根据Hans Sauer的说法"),for:w("prep.","关于；就……对象","patents for后的选项动名词给希望取得专利的成果，不引原因从句。","win patents for","为……取得专利")},
[q(33,"A")]:{discover:w("v.-ing（动名词）","发现","discovering为题干for后的动名词，宾语gene interactions保留基因互动对象。","discovering gene interactions","发现基因互动")},
[q(33,"B")]:{establish:w("v.-ing（动名词）","确立；建立","establishing为题干for后的动名词，宾语限定为疾病关联。","establishing disease correlations","确立疾病关联")},
[q(33,"C")]:{draw:w("v.-ing（动名词）","画；绘制","drawing pictures为字面绘图，整体接题干for；不是得出结论。","drawing pictures of genes","绘制基因图像")},
[q(33,"D")]:{identify:w("v.-ing（动名词）","识别；鉴定","identifying在for后名词化该动作，宾语human DNA并未表达互动关系。","identifying human DNA","鉴定人类DNA")},
[q(34)]:{mean:w("v.（第三人称单数）","意指；表示","the author means that询问句子在段落中的深层意思。","the author means that","作者意在说明"),that:w("conj.","引出意思内容","作means内容连接词，后面四选项为完整命题。","means that","意味着（后接命题）"),by:w("prep.","通过","By saying后接被引句，表示以该细节表达含义的方式。",'By saying "Each meeting was packed"',"通过说每场会议都满座")},
[q(34,"C")]:{great:w("adj.","重大的；重要的","great修饰concern，不是比较级greater；说明关切程度。","a great concern","一个重大关切")},
[q(35)]:{toward:w("prep.","对于；针对","attitude toward引态度对象gene patenting，不是空间朝向。","attitude toward gene patenting","对基因专利的态度"),speak:w("v.-ing（固定评注成分）","说；而言","Generally speaking整体为总体而言，限定全文概括角度。","Generally speaking","总体而言")},
[q(35,"A")]:{critical:w("adj.","批评的","在态度选项中为持批评态度，不是关键阶段的critical。","critical","批评的")},
};
export const passage2012P3ContextGlosses:Record<string,{meaning:string;note?:string}>=Object.fromEntries(Object.values(passage2012P3ReviewedContexts).flatMap(rows=>Object.values(rows).map(row=>[row.pattern.toLowerCase(),{meaning:row.patternMeaning,note:row.use}])));
