import { passage2012P3ReviewedContexts } from "./2012-passage-3-contexts";
import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";
const rows: LexiconRow[] = [
  ["march", "", "proper n.", "三月", "March 2010为原文判决的时间，不是行军动词。", "in March 2010（在2010年3月）", "月份首字母大写，普通march还可指行进、游行。"],
  ["member", "members", "n.", "成员；会员", "BIO向行业组织会员保证争议还会继续。", "members of a trade group（行业团体会员）", "member是组织成员，不等同公司的所有员工。"],
  ["indeed", "", "adv.", "确实；的确", "强化上诉裁决允许持有专利的说法，不表示作者赞同制度本身。", "could indeed hold patents（确实可以持有专利）", "indeed确认命题，instead表示替代，拼写近但不同。"],
  ["risk", "risks risked risking", "n.", "风险；可能性", "a woman's risk of breast cancer为女性患乳腺癌风险。", "the risk of disease（患病风险）", "风险高低不等于已经确诊，原文仅讲预测用途。"],
  ["firm", "firms", "n.", "企业；公司", "与companies同指从事生物技术研发的企业。", "biotech firms（生物技术企业）", "firm作形容词还可坚定、坚实，本文为组织名词。"],
  ["attempt", "attempts attempted attempting", "n.", "尝试；努力", "attempts at personalised medicine表示仍在探索的方向。", "an attempt at reform（改革尝试）", "尝试不保证取得预期结果。"],
  ["itself", "", "reflexive pron.", "它本身", "强调Myriad case本身仍可能未结束，不另指其他案件。", "the case itself（该案本身）", "反身代词此处为同位强调，不是谓语宾语。"],
  ["argument", "arguments", "n.", "论点；理由", "three main arguments后面列出三项反对理由。", "arguments against patents（反对专利的论点）", "argument还可为争吵，本文是可论证的理由。"],
  ["despite", "", "prep.", "尽管；虽然", "后接appeals court's decision名词短语表达让步。", "despite a decision（尽管已有裁决）", "despite后不直接接完整从句；although是连词。"],
  ["question", "questions", "n.", "问题；疑问", "big questions remain unanswered说明重大问题未明。", "unanswered questions（未解问题）", "questions为可数名词复数，表示有待澄清的疑问。"],
  ["advance", "advances advanced advancing", "v.", "发展；推进", "industry advances为产业不断发展，不是名词复数。", "the industry advances（产业发展）", "advance在完形选项为进步名词，在此由主语加谓语结构判为动词。"],
  ["unlikely", "", "adj.", "不大可能的", "unlikely to file many more是不大可能大量新增，并非绝不申请。", "be unlikely to happen（不大可能发生）", "unlikely为概率较低，impossible为不可能，力度不同。"],
  ["study", "studies studied studying", "v.", "研究", "studying后接how genes interact名词性从句。", "study gene interactions（研究基因互动）", "study也可为研究名词，本句为进行时动词。"],
  ["look", "looks looked looking", "v.", "寻找（look for）", "looking for correlations为寻找有用关联，不是调查人物。", "look for correlations（寻找关联）", "look into是调查，look for是寻找，两种介词结构不能混同。"],
  ["predict", "predicts predicted predicting", "v.", "预测", "与determine并列，表示关联研究可能用于预测药效。", "predict efficacy（预测疗效）", "预测并非证实，might进一步限定潜在用途。"],
  ["drug", "drugs", "n.", "药物", "a drug's efficacy为药物疗效，不是违禁毒品语境。", "a drug's efficacy（一种药物的疗效）", "drug可有毒品义，本句医疗研究语境取治疗药物。"],
  ["connect", "connects connected connecting", "v.", "联系；连接", "connecting the dots比喻把线索联系起来发现关系。", "connect the dots（把线索串联）", "本文不是画图或物理接线，须联系genes interact。"],
  ["explain", "explains explained explaining", "v.", "解释；说明", "explains Hans Sauer为报道分句倒装，律师为发言人。", "explain an issue（解释一个问题）", "explain something to someone才向某人说明，不写explain someone something。"],
  ["determine", "determines determined determining", "v.", "查明；决定", "20句为查明病因，22句为诉讼决定申请成败，两种语境区分。", "determine the causes（查明原因）", "determine既可查明未知事实，也可决定后果，不全译决心。"],
  ["shift", "shifts shifted shifting", "v.", "变化；转变", "shifting修饰landscape，指专利环境不断变化。", "a shifting landscape（变化中的形势）", "不是轮班名词，也不是搬运实体景观。"],
  ["active", "", "adj.", "积极的；活跃的", "31题干扰项误把高管agitated的焦躁当作积极。", "active executives（活跃的高管）", "agitated是激动不安，active是活跃，不应互译。"],
  ["discover", "discovers discovered discovering", "v.", "发现", "33题discovering gene interactions对应研究基因如何互动。", "discover interactions（发现相互作用）", "discover发现已有关系，不等于invent创造新关系。"],
  ["establish", "establishes established establishing", "v.", "确立；建立", "33题选项把研究对象换成疾病关联，不是原文基因互动。", "establish a correlation（确立一种关联）", "关联研究的应用于病因，不等于研究疾病之间的关系。"],
  ["draw", "draws drew drawn drawing", "v.", "绘画；画出", "33题干扰项把connecting the dots误解成画图。", "draw a picture（画一幅图）", "draw a conclusion为得出结论，draw pictures在选项为字面绘图。"],
  ["picture", "pictures", "n.", "图画；图片", "33题干扰项，并非本文想获得专利的成果。", "pictures of genes（基因图像）", "联系基因相互作用不是绘制基因图片。"],
  ["identify", "identifies identified identifying", "v.", "识别；鉴定", "33题干扰项泛指识别人类DNA，遗漏新研究的互动关系。", "identify human DNA（鉴定人类DNA）", "identify单个对象不等于discover interactions发现相互作用。"],
  ["attend", "attends attended attending", "v.", "参加；出席", "34题D泛称热衷大会，原文重点为专利议题受关注。", "attend a convention（出席大会）", "attend一般直接接会议宾语，不加to；attend to是处理照料。"],
  ["speak", "speaks spoke spoken speaking", "v.", "说；表达", "Generally speaking为一般而言、总体说来，框定态度判断。", "generally speaking（一般而言）", "此处为固定评注短语，不是作者在做现场演讲。"],
  ["meeting", "meetings", "n.", "会议；专题场次", "Each meeting为末句主语，不能归meet满足的动词义。", "a packed meeting（满座的会议）", "meeting派生名词与meet的进行式同形，本文为可数事件名词。"],
  ["mean", "means meant meaning", "v.", "意指；意思是", "34题the author means that询问句子深层含义，不是名词手段。", "mean that ...（意思是……）", "means在by this means中才是名词手段；本题为动词三单。"],
  ["concern", "concerns concerned concerning", "n.", "关注；关切", "a great concern说明基因专利为受关注的议题。", "a great concern（重要关切）", "concern也可作动词涉及或使担心，本选项为名词。"],
  ["case", "cases", "n.", "案件；诉讼案", "Myriad case贯穿历史基因专利争议，不是实验案例泛称。", "a patent case（专利案件）", "case也可情况、盒子或病例，此处由法院语境定为案件。"],
  ["crowded", "", "adj.", "拥挤的；挤满人的", "可替换packed描写会议参加者多，程度略弱。", "a crowded meeting（拥挤的会议）", "packed往往表示满得很，crowded只强调人多拥挤。"],
  ["federal", "", "adj.", "联邦的", "限定法官、上诉法院或工作组所处的国家层级。", "a federal court（联邦法院）", "联邦与州级机构不同，不以当前案例替换历史原文。"],
  ["judge", "judges judged judging", "n.", "法官", "文中先后出现一审法官和上诉法院，职责层级需区分。", "a federal judge（一位联邦法官）", "judgment为判决或判断，judge本句指人。"],
  ["shake", "shook shaken shakes shaking", "v.", "震动；撼动", "shook ... to its core比喻裁决给行业重大冲击。", "shake an industry to its core（从根本上震动一个行业）", "震动为比喻，不是产业发生物理摇晃。"],
  ["biotech", "", "adj. / n.", "生物技术的；生物技术", "biotechnology的简略形式，修饰industry或companies。", "the biotech industry（生物技术产业）", "本文讨论行业专利争议，不是医疗诊疗建议。"],
  ["core", "cores", "n.", "核心；根本", "to its core强调震动程度深至根本。", "to its core（从根本上；深深地）", "core可指物体中心，此处为产业基础的比喻。"],
  ["patent", "patents patented patenting", "n. / v.", "专利；授予专利", "名词指排他性权利，were patented中为动词被动。", "hold a patent（持有专利）", "patent不等于论文发表；本文描述历史争议而非现行授权标准。"],
  ["isolate", "isolates isolated isolating", "v.", "分离；使隔离", "isolated DNA指经分离的DNA，不是人为创造的全新基因。", "isolate a molecule（分离一个分子）", "分离与发明不是同一动作，正是文中争议。"],
  ["dna", "", "abbreviation n.", "DNA；脱氧核糖核酸", "本文以DNA分子作为历史专利讨论对象。", "human DNA（人类DNA）", "gene是基因，genome是基因组，不能与DNA一律互译。"],
  ["gene", "genes", "n.", "基因", "gene patents为基因相关专利，two genes说明案件中两个对象。", "gene interactions（基因相互作用）", "genome是整体基因组，gene是其中基因，范围不同。"],
  ["patentable", "", "adj.", "可以获得专利的", "31题企业希望基因具备可专利性。", "be patentable（具有可专利性）", "patented为已经获得专利，patentable为能否获专利，不能混淆。"],
  ["unpatentable", "", "adj.", "不能获得专利的", "2010年3月裁决的核心判断，un-否定可专利性。", "be unpatentable（不具备可专利性）", "不具备资格不等于只是还没申请；仅报道原文判决。"],
  ["executive", "executives", "n.", "企业高管", "复数指行业高管，chief executive为公司最高经营负责人。", "a chief executive（首席执行官）", "executive也可为行政的形容词，本篇主要指管理人员。"],
  ["violently", "", "adv.", "强烈地；极度地", "violently agitated是情绪强度，非高管实施暴力。", "violently agitated（极度不安）", "violently也可为暴力地，必须由动词与语境判断。"],
  ["agitate", "agitated agitates agitating", "v.", "使不安；使激动", "were agitated描述企业高管听到不利判决的心理状态。", "be agitated by news（因消息而不安）", "active为积极活跃，agitated为焦躁不安，不是同义词。"],
  ["biotechnology", "", "n.", "生物技术", "行业组织全称中的领域名称。", "Biotechnology Industry Organisation（生物技术产业组织）", "biotech为常见缩略表达；统计不强并两个独立词形。"],
  ["organisation", "organisations", "n.", "组织；机构", "保留原卷英式拼法，指BIO行业组织。", "an industry organisation（行业组织）", "organization为美式拼法；本篇不静默改原文拼写。"],
  ["bio", "bio's", "abbreviation n.", "生物技术产业组织（BIO）", "与全称同指，负责安抚会员并举办会议。", "a lawyer for the BIO（BIO的律师）", "此处不是词缀bio-生物的独立知识词。"],
  ["trade", "trades", "n. used attributively", "行业", "a trade group为行业团体，而非一笔商品交易。", "a trade group（行业团体）", "trade可指贸易，本句按职业产业群体理解。"],
  ["assure", "assures assured assuring", "v.", "向……保证；使放心", "assure members that后接受事者和保证内容。", "assure somebody that ...（向某人保证……）", "ensure后直接接要保证的结果；assure一般先接人。"],
  ["preliminary", "", "adj.", "初步的；预备的", "preliminary step是组织对败诉阶段性的描述。", "a preliminary step（初步步骤）", "final为最终，preliminary不意味着争议已经解决。"],
  ["relieve", "relieved relieves relieving", "v.", "使宽慰；缓解", "were relieved为松了一口气，时限被temporarily限定。", "feel relieved（感到宽慰）", "relieve pain可缓解疼痛，relieve someone of duty为解除职务；本文均非后两义。"],
  ["temporarily", "", "adv.", "暂时地", "限制行业人士安心的持续时间，后文仍有法律疑问。", "temporarily relieved（暂时宽慰）", "permanently为永久，temporarily为暂时，不可漏译。"],
  ["appeal", "appeals appealed appealing", "n. / v.", "上诉", "appeals court为上诉法院，负责复审先前判决。", "an appeals court（上诉法院）", "appeal还可指呼吁、吸引力，此处司法上下文为上诉。"],
  ["overturn", "overturned overturns overturning", "v.", "推翻；撤销", "overturn the prior decision表示上诉法院改变原判。", "overturn a decision（推翻判决）", "confirm为维持或确认，overturn方向相反。"],
  ["prior", "", "adj.", "先前的", "prior decision回指不允许基因专利的一审裁决。", "a prior decision（先前裁决）", "prior to为在……之前，本句prior直接修饰名词。"],
  ["ruling", "rulings", "n.", "裁决；判决", "the ruling在8句为名词；7句ruling为rule动词分词，另用句子词位映射。", "a court ruling（法院裁决）", "名词ruling与动词rule的分词同形，须按句区分。"],
  ["rule", "rules ruled", "v.", "裁定；判决", "ruled that和ruling that后接法院判决内容。", "rule that ...（裁定……）", "rule out才是排除，不可把ruled that也译成排除。"],
  ["myriad", "myriad's", "proper n.", "Myriad公司", "公司名中的Myriad，Genetics为全称另一部分。", "Myriad Genetics（Myriad基因公司）", "普通词myriad可指大量，但本篇为专名。"],
  ["genetics", "", "proper n. component", "Genetics（公司名称组成部分）", "Myriad Genetics为公司全称，不能把该公司当学科作为诉讼当事方。", "Myriad Genetics（Myriad基因公司）", "genetics作一般名词时为遗传学，本句用于专名。"],
  ["forecast", "forecasts forecasted forecasting", "v.", "预测", "forecast risk表示预测风险，不是确诊疾病。", "forecast a risk（预测一种风险）", "predict也为预测；forecast过去式可同形或forecasted。"],
  ["breast", "breasts", "n. used attributively", "乳房；乳腺的", "breast cancer整体为乳腺癌。", "breast cancer（乳腺癌）", "原文仅说明相关检测用途，不据此给出个人诊断。"],
  ["cancer", "cancers", "n.", "癌症", "risk of breast cancer指未来患病风险，而非确定已患病。", "the risk of cancer（患癌风险）", "risk风险与diagnosis诊断不可混同。"],
  ["utah", "", "proper n.", "犹他州", "a company in Utah为公司所在地信息。", "a company in Utah（一家位于犹他州的公司）", "地名并非药物名称。"],
  ["blessing", "blessings", "n.", "福音；有益的事", "企业高管称判决为双方福音，需保留发言来源。", "a blessing to patients（对患者有益的事）", "此处为好事的比喻，不特指宗教祝福。"],
  ["alike", "", "adv.", "同样地；两者都", "firms and patients alike把企业与患者一并包括。", "young and old alike（老少都一样）", "alike常后置，不等于like介词后再接对象。"],
  ["personalised", "", "adj.", "个性化的；针对个体的", "修饰medicine，保留原卷英式拼法。", "personalised medicine（个性化医疗）", "personal个人的未必包含按个体差异定制之意。"],
  ["medicine", "medicines", "n.", "医学；医疗", "personalised medicine指医疗方式，不仅是一种药品。", "personalised medicine（个性化医疗）", "drug为具体药物；medicine可指学科、医疗或药品。"],
  ["critic", "critics", "n.", "批评者；反对者", "第11句三个论点的提出者，不能当成作者自己。", "critics of gene patents（基因专利的反对者）", "critical为批评的形容词，critic为人。"],
  ["suppress", "suppresses suppressed suppressing", "v.", "抑制；压制", "批评者称专利压制创新，与reward对照。", "suppress innovation（抑制创新）", "stimulate促进与suppress抑制方向相反。"],
  ["innovation", "innovations", "n.", "创新", "专利本应激励创新，而批评者认为其作用相反。", "reward innovation（奖励创新）", "invention为具体发明，innovation更广包括新方法和改进。"],
  ["reward", "rewards rewarded rewarding", "v.", "奖励；回报", "rather than reward it中it指创新。", "reward innovation（奖励创新）", "suppress与reward为相反作用，不是同义替换。"],
  ["monopoly", "monopolies", "n.", "垄断；独占", "patents' monopolies为专利带来的排他性控制。", "patent monopolies（专利垄断）", "这里不是普通的高市场份额数据，而是批评者对排他权的描述。"],
  ["access", "accesses accessed accessing", "n.", "获得或使用的机会", "access to tests为获得检测服务的可及性，不是测试入口网址。", "access to genetic tests（获得基因检测的机会）", "access后通常用to，不把该to当不定式标记。"],
  ["genetic", "", "adj.", "遗传的；基因的", "genetic tests指基因检测，和gene名词不合并原形。", "genetic tests（基因检测）", "genetic形容词、genetics学科名词、gene基因名词须区分。"],
  ["test", "tests tested testing", "n.", "检测；检验", "本篇为基因医学检测，讨论检测服务及其可及性。", "genetic tests（基因检测）", "test可为考试，本文需用生物医学检测语境。"],
  ["task-force", "task-forces", "n.", "专项工作组", "a federal task-force指为特定任务设立的联邦工作组。", "a federal task-force（联邦专项工作组）", "不把task-force拆成普通任务和物理力量。"],
  ["urge", "urges urged urging", "v.", "敦促；呼吁", "urge reform是提出改革要求，非宣布改革已完成。", "urge reform（敦促改革）", "urge语气强于suggest，但仍不等于实施。"],
  ["department", "departments", "n.", "部门；部", "Department of Justice整体为美国司法部。", "the Department of Justice（司法部）", "department也可指大学系，本文为政府部门。"],
  ["justice", "", "n.", "司法；公正", "Department of Justice为部门名称，不能作法官个人。", "the Department of Justice（司法部）", "justice还可称高级法院法官，此处机构名语境不同。"],
  ["file", "files filed filing", "v.", "提交；提出申请", "file a brief为提交书面法律意见；file patents为提出专利申请。", "file a brief（提交法律书面意见）", "file也可为文件名词或归档动词，本句强调正式提交。"],
  ["brief", "briefs", "n.", "法律书面意见；诉讼文书", "司法部向法院提交的材料，arguing引具体论点。", "file a legal brief（提交法律书面意见）", "brief形容词为简短的，本文是专门法律名词。"],
  ["molecule", "molecules", "n.", "分子", "DNA molecule与棉纤维被用作自然产物的类比。", "a DNA molecule（一个DNA分子）", "molecule不等于gene；全文在不同层面讨论对象。"],
  ["cotton", "", "n. used attributively", "棉；棉花的", "修饰fibres和seeds，构成自然产物类比。", "cotton fibres（棉纤维）", "cotton fibre与cotton seed分别为纤维和种子。"],
  ["fibre", "fibres", "n.", "纤维", "原卷英式fibres保留；例证为从棉籽分离的棉纤维。", "cotton fibres（棉纤维）", "fiber为美式拼法，不静默改用户文本。"],
  ["separate", "separates separated separating", "v.", "分离；分开", "have been separated是完成时被动，强调经过分离。", "separate fibres from seeds（把纤维与种子分离）", "isolate也可分离，separate from明确原来相连的对象。"],
  ["seed", "seeds", "n.", "种子；籽", "cotton seeds为棉籽，是纤维分离的来源。", "cotton seeds（棉籽）", "不是药物种类或生物学基因，类比层次须保持。"],
  ["sequencing", "", "n.", "测序；确定序列的过程", "the sequencing of a whole genome作whether从句主语。", "genome sequencing（基因组测序）", "sequence可为序列；sequencing这里作为过程名词独立处理。"],
  ["genome", "genomes", "n.", "基因组", "a whole genome为测序整体，其中含individual genes。", "a whole genome（整个基因组）", "gene为基因，genome为整体基因组，不能互换范围。"],
  ["violate", "violates violated violating", "v.", "侵犯；违反", "violates patents提出是否侵权的疑问，不是已认定违法。", "violate a patent（侵犯专利权）", "violate law可违反法律，此处宾语为专利权。"],
  ["supreme", "", "adj.", "最高的", "Supreme Court为最高法院专名。", "the Supreme Court（最高法院）", "原卷选项小写supreme保留；不因此另建词位。"],
  ["suit", "suits", "n.", "诉讼；案件", "other suits和a suit均为法院诉讼，不是服装或适合动词。", "bring a suit（提起诉讼）", "sue为起诉动词，是相关词而非suit的屈折；不将sued合并进suit计数。"],
  ["domain", "domains", "n.", "领域；范围", "public domain指公有领域，不是互联网域名。", "in the public domain（处于公有领域）", "受专利保护与公有领域在文中是两种不同状态。"],
  ["interact", "interacts interacted interacting", "v.", "相互作用；互动", "how genes interact说明基因之间如何关联和影响。", "genes interact（基因相互作用）", "interact不是识别一个孤立基因，核心在多个对象的关系。"],
  ["correlation", "correlations", "n.", "相关关系；关联", "寻找可能帮助查明病因或预测疗效的基因关联。", "gene correlations（基因关联）", "correlation相关性不等于causation因果性，本文只说可能用途。"],
  ["efficacy", "", "n.", "效力；疗效", "a drug's efficacy指药物产生预期效果的能力。", "a drug's efficacy（药物疗效）", "efficiency为效率，efficacy为有效性或疗效。"],
  ["eager", "", "adj.", "渴望的；急切的", "be eager to win patents说明企业申请意愿。", "be eager to do（急于做）", "eager强调想做，不保证法律上能够成功。"],
  ["dot", "dots", "n.", "点；线索点", "connect the dots为把分散线索联系起来的比喻。", "connect the dots（把线索串联起来）", "不能据此选画基因图片的字面选项。"],
  ["hans", "", "proper n.", "汉斯（人名）", "Hans Sauer为BIO律师全名。", "Hans Sauer（汉斯·绍尔）", "原文人物姓名不是研究项目缩写。"],
  ["sauer", "", "proper n.", "绍尔（姓氏）", "为原文律师姓氏，是33题观点来源。", "Hans Sauer（汉斯·绍尔）", "专名不编造词根或同义词。"],
  ["lawyer", "lawyers", "n.", "律师", "BIO律师解释申请趋势，会议另向律师介绍变化环境。", "a lawyer for the BIO（BIO的律师）", "judge为裁判者，lawyer为法律专业代理或顾问，身份不同。"],
  ["mayo", "", "proper n.", "梅奥（机构名组成）", "Mayo Clinic为提起相关诉讼的机构。", "the Mayo Clinic（梅奥诊所）", "不按口语mayo蛋黄酱义理解。"],
  ["clinic", "clinics", "n.", "诊所；医疗机构", "Mayo Clinic为机构专名，不是该案疾病名称。", "the Mayo Clinic（梅奥诊所）", "hospital通常为医院，Clinic在本句专名依约定译名。"],
  ["term", "terms", "n.", "审期；开庭期", "its next term指最高法院下一审期。", "the Court's next term（法院下一审期）", "term还可指学期、任期、术语、条款，此处不是医学术语。"],
  ["hear", "heard hears hearing", "v.", "审理；听取", "法院hear a suit为审理案件，而非偶然听见消息。", "hear a case（审理案件）", "listen为主动听，hear在司法搭配里有专门审理义。"],
  ["convention", "conventions", "n.", "大会；会议", "BIO组织的行业大会，包含多个专题场次。", "hold a convention（举办大会）", "convention也可指惯例、公约；本文与held、sessions搭配选大会。"],
  ["session", "sessions", "n.", "会议场次；专题讨论", "大会中为律师培训的各专题场次。", "training sessions（培训场次）", "session为一次时段或场次，convention为整体大会。"],
  ["coach", "coaches coached coaching", "v.", "培训；指导", "coach lawyers on后接培训主题，非运动员教练职位。", "coach lawyers on patent issues（就专利问题培训律师）", "coach作名词还可指教练或长途客车，本句为动词。"],
  ["landscape", "landscapes", "n.", "格局；形势", "shifting landscape for patents比喻不断变化的专利环境。", "the changing legal landscape（变化中的法律格局）", "landscape通常指风景，此处并无自然景色描写。"],
  ["pack", "packs packed packing", "v.", "挤满；装满", "was packed形容每场会议满座，体现关注度。", "a packed meeting（座无虚席的会议）", "pack行李为打包；会议语境为挤满人。"],
  ["man-made", "", "adj.", "人工制造的；人造的", "32题对比自然产物，只是概括批评者立场，不声称充分授权条件。", "man-made products（人造产品）", "人工创造与仅从自然物分离不是同一操作。"],
  ["interaction", "interactions", "n.", "相互作用；互动", "33题gene interactions对应how genes interact。", "gene interactions（基因相互作用）", "interact为动词、interaction为派生名词，不能合并原形次数。"],
  ["authoritative", "", "adj.", "有权威的", "34题干扰项，满席不能直接推出法院权威。", "an authoritative source（权威来源）", "authoritarian为专制的，与authoritative权威的不同。"],
  ["keen", "keener keenest", "adj.", "热衷的；渴望的", "34题干扰项把对具体议题关注泛化为爱参会。", "be keen to attend（热衷参加）", "本句不能以出席旺盛就推断律师爱所有会议。"],
  ["objective", "", "adj.", "客观的", "35题评价作者平衡呈现不同立场与不确定性。", "an objective account（客观的叙述）", "objective作名词为目标，本题是态度形容词。"],
  ["supportive", "", "adj.", "支持的", "35题干扰项，企业赞成不等于作者表示支持。", "a supportive attitude（支持态度）", "报告支持者观点不等于作者本人的supportive立场。"],
  ["scornful", "", "adj.", "轻蔑的；鄙视的", "35题不符合中性报道争议的行文方式。", "a scornful tone（轻蔑的语气）", "critical可理性批评，scornful语气更强而含鄙视。"],
];
const reviewed = reviewedLexicon(rows);
export const passage2012P3Lexicon = reviewed.entries;
export const passage2012P3LemmaAliases: Record<string, string> = { ...reviewed.aliases, ...Object.fromEntries(rows.map(([headword]) => [headword, headword])), "woman's": "woman", "drug's": "drug", "court's": "court", "patents'": "patent" };
export const passage2012P3CollocationGlosses = reviewed.glosses;
export const passage2012P3FormPartOfSpeech: Record<string, string> = { isolated: "v.-ed（分词定语）", patented: "v.-ed（被动）", patenting: "gerund", ruling: "n. / v.-ing", prior: "adj.", growing: "v.-ing（定语）", shifting: "v.-ing（定语）", packed: "adj.（分词形容词）", relieved: "adj.（分词形容词）", genetic: "adj.", filing: "gerund" };
passage2012P3Lexicon.appeal.otherMeanings = ["呼吁（appeal for help）；吸引力（have wide appeal）；v. appeal to有吸引力。"];
passage2012P3Lexicon.brief.otherMeanings = ["adj. 简短的；短暂的。v. 向……介绍基本情况。n. 任务说明。in brief简言之。"];
passage2012P3Lexicon.file.otherMeanings = ["n. 文件、卷宗、档案；锉刀。v. 归档；排成纵队行进；锉平。"];
passage2012P3Lexicon.suit.otherMeanings = ["n. 一套衣服；v. 适合、使满意（suit one's needs满足需要）。"];
passage2012P3Lexicon.term.otherMeanings = ["术语；学期；任期；期限；复数terms条款、关系；in terms of就……而言。"];
passage2012P3Lexicon.convention.otherMeanings = ["惯例、习俗（social conventions社会习俗）；公约、协定（an international convention国际公约）。"];
passage2012P3Lexicon.coach.otherMeanings = ["n. 教练；长途客车；旅客车厢。v. 辅导、训练，不限运动领域。"];
export const passage2012P3SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2012-p3-s1": { its: { contextualMeaning: "美国生物技术产业的", use: "core为其根本，不是法官身体的核心。" } },
  "2012-p3-s2": { some: { contextualMeaning: "大约", use: "some在20%前表示约数，不能译成某一些20%。" }, win: { contextualMeaning: "取得；赢得", use: "had won patents表示先前已取得专利。" } },
  "2012-p3-s3": { rule: { contextualMeaning: "裁定", use: "ruled that说明法官作出不可专利的判决。", partOfSpeech: "v." } },
  "2012-p3-s5": { this: { contextualMeaning: "2010年3月的不利判决", use: "组织将它称为长久法律争斗的初步阶段。" }, just: { contextualMeaning: "仅仅；不过", use: "强调不是终局，以安抚会员。" } },
  "2012-p3-s6": { they: { contextualMeaning: "行业高管及企业人士", use: "回指前段因不利判决而不安的一方。" } },
  "2012-p3-s7": { rule: { contextualMeaning: "裁定；判决", use: "现在分词补充上诉法院判决内容，that后接宾语。", partOfSpeech: "v.-ing" }, hold: { contextualMeaning: "持有；拥有", use: "hold patents表示依法持有专利，非举办会议。" } },
  "2012-p3-s8": { ruling: { contextualMeaning: "裁决；判决", use: "the ruling是said宾语从句的主语，明确为名词。", partOfSpeech: "n." } },
  "2012-p3-s9": { as: { contextualMeaning: "随着", use: "引产业探索持续的时间背景，不单独断言因果。" }, rather: { contextualMeaning: "相当", use: "程度副词修饰busy，非rather than取舍。" } },
  "2012-p3-s10": { over: { contextualMeaning: "结束", use: "not over为尚未终结，非空间上方。" }, itself: { contextualMeaning: "案件本身", use: "对case加以强调，不为反身动作宾语。" } },
  "2012-p3-s11": { it: { contextualMeaning: "先指基因，后指创新", use: "may not be patented的it指gene；reward it的it指innovation，按各分句区分。" }, nature: { contextualMeaning: "自然界", use: "a product of nature为天然产物，非人的性格。" } },
  "2012-p3-s12": { number: { contextualMeaning: "人数；一批人", use: "A growing number省略people，不是单纯数学数字。" }, agree: { contextualMeaning: "认同批评者的观点", use: "省略前文已给出的反对基因专利的具体论点。" } },
  "2012-p3-s14": { less: { contextualMeaning: "较少；no less ... than整体为同样是", use: "否定较低程度，因此不是DNA的自然性更弱。" } },
  "2012-p3-s16": { it: { contextualMeaning: "前者为形式主语，后者指整个基因组", use: "it is unclear后接真正主语whether从句；within it中的it回指whole genome。" } },
  "2012-p3-s17": { yet: { contextualMeaning: "仍有可能；以后还可能", use: "may yet强调后续到最高法院的可能性，而非转折连词。" } },
  "2012-p3-s18": { advance: { contextualMeaning: "发展；向前推进", use: "产业作为主语，advances为动词，不是复数名词进步。", partOfSpeech: "v." }, even: { contextualMeaning: "甚至；更", use: "even加强greater比较级，表示其他诉讼的潜在影响还更大。" } },
  "2012-p3-s19": { file: { contextualMeaning: "提出专利申请", use: "file patents是申请专利的压缩说法，不是已经获得。" }, most: { contextualMeaning: "多数人类DNA分子", use: "回指前面的human DNA molecules，谓语为两类状态。" }, public: { contextualMeaning: "公有的；公众可使用的", use: "public domain为公有领域，非对外展示但仍有专利的状态。" } },
  "2012-p3-s20": { drug: { contextualMeaning: "药物", use: "drug's efficacy是治疗药物疗效，非毒品效力。" }, cause: { contextualMeaning: "病因；原因", use: "the causes of disease为疾病原因，不是公益事业。" } },
  "2012-p3-s21": { connect: { contextualMeaning: "把……联系起来", use: "connect the dots比喻发现线索之间的联系。" } },
  "2012-p3-s22": { determine: { contextualMeaning: "决定；影响成败", use: "may be determined by说明诉讼可能决定企业申请成败，非查明病因。" }, their: { contextualMeaning: "企业的", use: "Their success指企业获得新型基因关联专利的成功。" }, bring: { contextualMeaning: "提起（诉讼）", use: "brought by the Mayo Clinic说明起诉者，不是把物件拿到法院。" }, which: { contextualMeaning: "关系代词，指这项诉讼", use: "在定语从句作hear宾语，不能就近指Mayo Clinic。" } },
  "2012-p3-s23": { hold: { contextualMeaning: "举办；召开", use: "held a convention与第7句持有专利义不同。" }, on: { contextualMeaning: "关于；就……内容", use: "coach lawyers on后接培训话题。" } },
  "2012-p3-s24": { pack: { contextualSubstitutions: [{ label: "crowded", chinese: "挤满人的", fit: "direct", rewrittenSentence: "Each meeting was crowded.", nuance: "crowded保留人多拥挤的意思，但packed更强调座无虚席的程度。", target: "word:crowded" }] } },
};

for(const [sourceId,contexts] of Object.entries(passage2012P3ReviewedContexts)){
  const target=passage2012P3SentenceContexts[sourceId]??={};
  for(const [headword,context] of Object.entries(contexts))target[headword]={...target[headword],...context};
}
