import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, type LexiconRow } from "./2011-content-helpers";

const rows: LexiconRow[] = [
  ["pretty", "prettier prettiest", "adj.", "漂亮的；这里题目式地指粉红审美", "Pretty in pink 是文章标题式开场，带评论色彩。", "pretty in pink（粉红装扮得很漂亮）", "pretty 可作副词“相当”，此处是形容词，不能把标题只译成“相当”。"],
  ["adult", "adults", "n./adj.", "成年人；成年的", "adult women 指成年女性；第4段 adults 指成人消费者。", "adult women（成年女性）", "adult 既可作名词也可作定语，需看后面是否接名词。"],
  ["woman", "women", "n.", "女性；妇女", "adult women 与 young girls 构成代际对照。", "adult women（成年女性）", "woman 单数，women 复数；不能与 man / men 的形式混淆。"],
  ["obsess", "obsessed obsesses obsessing", "v.", "使着迷；使痴迷", "be obsessed with the colour 表示对这种颜色痴迷。", "be obsessed with（痴迷于）", "obsessed 是过去分词形容词；interested 是感兴趣，obsessed 程度强得多。"],
  ["colour", "colours", "n.", "颜色；色彩", "本文讨论颜色被赋予的性别象征，并非纯视觉色相。", "nursery colours（婴幼儿用品颜色）", "colour 是英式拼写；美式常写 color。"],
  ["colour-code", "colour-coded colour-coding", "v.", "按颜色编码；用颜色分类", "Children were not colour-coded at all 说明儿童过去没有用颜色区分性别。", "be colour-coded（按颜色分类）", "colour-code 是英式拼写；本文是社会分类方式，不是给颜色本身命名。"],
  ["pervasive", "", "adj.", "无处不在的；渗透各处的", "pervasive in girls' lives 说明粉色文化广泛渗透。", "be pervasive in（遍布于）", "popular 只是受欢迎，pervasive 强调覆盖范围广。"],
  ["pink", "", "n./adj.", "粉色；粉色的", "文章的中心对象，被讨论为被营销塑造的女孩标记。", "pink culture（粉色文化）", "pink 可作名词或形容词；本文不把颜色本身简单判为坏。"],
  ["intrinsically", "", "adv.", "本质上；天生地", "pink is not intrinsically bad 排除“粉色本身有害”的误解。", "intrinsically bad（本质上坏的）", "intrinsic 是内在本质；inborn 更专指先天形成。"],
  ["slice", "slices", "n.", "薄片；一小部分", "a tiny slice of the rainbow 比喻粉色只是彩虹中的极小部分。", "a slice of（……的一小部分）", "slice 是可切下的一片，也可比喻整体的一小部分。"],
  ["rainbow", "rainbows", "n.", "彩虹；多种色彩的整体", "rainbow 用整体色谱反衬粉色不应垄断女孩形象。", "the rainbow（彩虹/色彩全谱）", "不能因彩虹比喻而把本句误作天气描写。"],
  ["celebrate", "celebrates celebrated celebrating", "v.", "赞美；颂扬；庆祝", "may celebrate girlhood 承认粉色可能表达一种女孩时期的美好。", "celebrate girlhood（颂扬女孩时期）", "celebrate 在此不是举行节日活动，而是正面呈现。"],
  ["girlhood", "", "n.", "女孩时期；少女身份", "第1段批评把 girlhood 缩减为单一粉色形象。", "representation of girlhood（女孩时期的代表）", "girlhood 是时期/身份抽象名词，不是复数 girls 的同义替换。"],
  ["firmly", "", "adv.", "牢固地；坚定地", "firmly 与 repeatedly 共同修饰 fuses，强调绑定既反复又牢固。", "firmly fuse A to B（牢固地把 A 绑定到 B）", "firmly 可修饰立场或物理固定，本文为文化联系的牢固程度。"],
  ["fuse", "fuses fused fusing", "v.", "把……熔合；紧密绑定", "fuses girls' identity to appearance 批评把身份与外表强行捆绑。", "fuse A to B（把 A 与 B 紧密连在一起）", "link 可泛指联系，fuse 比 link 更强调难以分开的结合。"],
  ["identity", "identities", "n.", "身份；自我认同", "girls' identity 指被社会建构的“女孩是谁”的认同。", "identity to appearance（身份与外表的绑定）", "identity 不只是身份证明，也可指群体或个人认同。"],
  ["appearance", "appearances", "n.", "外表；外貌", "to appearance 说明被绑定的是外观，而非能力或兴趣。", "fuse identity to appearance（把身份绑到外表）", "appearance 还可指出现、表象，本文是外表形象。"],
  ["present", "presents presented presenting", "v.", "把……呈现为", "presents that connection as innocent 表示把某种联系包装成无害。", "present A as B（把 A 呈现为 B）", "present 作名词是礼物，作形容词是当前；本文为动词。"],
  ["connection", "connections", "n.", "联系；关联", "that connection 回指女孩身份与外表的捆绑。", "a connection between（……之间的联系）", "connection 可指交通换乘或人脉，本文为观念上的联系。"],
  ["innocent", "", "adj.", "无害的；纯真的", "not only innocent but as evidence of innocence 是作者批评的包装方式。", "evidence of innocence（纯真的证据）", "innocent 可指无罪或天真，本文接近“无害/纯真”。"],
  ["evidence", "", "n.", "证据；迹象", "as evidence of innocence 指被当作证明纯真的证据。", "evidence of（……的证据）", "evidence 通常不可数；不能与 prove 混为同一词性。"],
  ["innocence", "", "n.", "纯真；无害状态", "文章质疑营销把粉色联系包装成 innocence 的证据。", "evidence of innocence（纯真的证据）", "innocence 为 innocent 的名词，亦可指法律上的清白。"],
  ["despair", "despaired despairs despairing", "v./n.", "绝望；深感失望", "despaired at the lack of imagination 表示作者强烈失望。", "despair at sth（对某事深感绝望）", "despair at 后接令人失望的对象；不是普通的 dislike。"],
  ["singular", "", "adj.", "异常突出的；极其的", "the singular lack 指极其明显的贫乏。", "a singular lack of（异常突出的缺乏）", "singular 还可指单数，本文不能按语法术语解释。"],
  ["imagination", "", "n.", "想象力；想象空间", "lack of imagination about girls' lives 批评社会想象过于单一。", "lack of imagination（缺乏想象力）", "imagination 不等同 intelligence，重点是可设想的生活与兴趣范围。"],
  ["attraction", "attractions", "n.", "吸引；喜爱", "girls' attraction to pink 指女孩对粉色的吸引/偏好。", "attraction to（对……的吸引/喜爱）", "attractive 是有吸引力的，attraction 是名词。"],
  ["unavoidable", "", "adj.", "不可避免的", "may seem unavoidable 是表面印象，随即被研究者否定。", "seem unavoidable（看似不可避免）", "inevitable 同义较正式；本文有 may seem 的保留语气。"],
  ["encode", "encoded encodes encoding", "v.", "编码；写入", "encoded in their DNA 比喻性说法指仿佛先天写入基因。", "be encoded in DNA（被编码进 DNA）", "encode 可指信息编码；本文不把这一比喻当成科学定论。"],
  ["DNA", "", "n.", "DNA；脱氧核糖核酸", "in their DNA 代表“天生的、遗传的”解释。", "be in one's DNA（仿佛天生如此）", "日常英语常比喻天性，不能据此推成实际基因研究结论。"],
  ["associate", "associate associated associates associating", "v./n.", "副教授；使联系", "an associate professor 是副教授；was associated with 为与……相联系。", "an associate professor（副教授）", "associate 既是职称名词，也可作动词；需按结构辨别。"],
  ["colour-code", "colour-coded colour-coding", "v.", "按颜色编码；用颜色分类", "Children were not colour-coded 指儿童尚未用颜色区分性别。", "be colour-coded（按颜色分类）", "code 还可指密码代码，本文特指用颜色作社会分类。"],
  ["era", "eras", "n.", "时代；时期", "the era before domestic washing machines 限定历史生活条件。", "the era before（……之前的时代）", "era 比 period 更常指较长、有特征的历史阶段。"],
  ["domestic", "", "adj.", "家用的；家庭的", "domestic washing machines 指家用洗衣机。", "domestic washing machine（家用洗衣机）", "domestic 也可指国内的、家庭内部的，本文不是“本国的”。"],
  ["practical", "", "adj.", "实际的；实用的", "as a practical matter 解释婴儿穿白色出于洗衣便利。", "as a practical matter（出于实际考虑）", "practical 是实际可行，practicable 是可实行，二者不可混同。"],
  ["boil", "boils boiled boiling", "v.", "煮沸；用沸水煮", "the only way ... was to boil them 指用煮沸的方式洗净衣服。", "boil clothes clean（煮洗干净衣物）", "boil 还可指水沸腾；本文为及物动词，them 指 clothes。"],
  ["gender-neutral", "", "adj.", "不分性别的；性别中性的", "gender-neutral dresses 指未以男孩/女孩区分的衣服。", "gender-neutral dresses（不分性别的连衣裙）", "neutral 还可指中立，本文讨论性别标记而非政治立场。"],
  ["nursery", "nurseries", "n./adj.", "婴幼儿房；婴幼儿用品的", "nursery colours 是给婴幼儿用品使用的颜色。", "nursery colours（婴幼儿用品颜色）", "nursery 不是植物苗圃的唯一含义，本文不指园艺。"],
  ["masculine", "", "adj.", "男性化的", "pink was considered the more masculine colour 说明粉色一度较男性化。", "the more masculine colour（更男性化的颜色）", "masculine 与 male 的关系类似 femininity 与 female，注意词性不同。"],
  ["pastel", "pastels", "adj./n.", "柔和的浅色；粉彩色", "a pastel version of red 把粉色说成红色的柔和浅淡版本。", "a pastel version of red（红色的浅色版本）", "pastel 不等于所有浅色，只强调柔和、粉彩式色调。"],
  ["version", "versions", "n.", "版本；变体", "a pastel version of red 指红色的一种浅色变体。", "a version of（……的一种版本）", "version 不等于 exact copy，强调同一事物的变形或不同版本。"],
  ["intimation", "intimations", "n.", "暗示；联想", "intimations of the Virgin Mary 是蓝色引起的文化联想。", "intimations of（对……的暗示/联想）", "intimation 比 direct statement 更含蓄，不是亲密 intimacy。"],
  ["constancy", "", "n.", "坚定；始终如一", "constancy 与 faithfulness 并列，是蓝色的文化联想。", "constancy and faithfulness（坚定与忠贞）", "constant 是形容词，constancy 是抽象名词。"],
  ["faithfulness", "", "n.", "忠贞；忠实", "faithfulness 是蓝色过去象征女性气质的联想之一。", "faithfulness to（对……忠贞）", "faithfulness 不只是宗教信仰，也可指忠诚可靠。"],
  ["symbolise", "symbolised symbolises symbolising", "v.", "象征", "Blue symbolised femininity 说明过去色彩象征的方向。", "symbolise femininity（象征女性气质）", "symbolise 表文化代表，不是“证明某人的真实性别”。"],
  ["femininity", "", "n.", "女性气质", "symbolised femininity 指被文化上赋予女性象征。", "symbolise femininity（象征女性气质）", "female 是性别形容词/名词，femininity 是抽象气质名词。"],
  ["amplify", "amplifies amplified amplifying", "v.", "放大；夸大", "amplifying age and sex differences 是儿童营销策略的核心。", "amplify differences（放大差异）", "amplify 可指声音放大；本文为社会差异的夸张强化。"],
  ["dominant", "", "adj.", "占主导地位的", "a dominant children's marketing strategy 指当时主导的营销办法。", "a dominant strategy（主导策略）", "dominant 不等于 only，主导不表示唯一存在。"],
  ["marketing", "", "n.", "营销；市场推广", "marketing trends / strategy 是全文解释粉色偏好的关键机制。", "children's marketing strategy（儿童市场营销策略）", "marketing 不是 market 的地点义，而是促进销售的活动。"],
  ["strategy", "strategies", "n.", "策略", "marketing strategy 指有目的地利用年龄、性别差异的销售策略。", "marketing strategy（营销策略）", "strategy 强调有计划的长期办法，不同于单次 trick。"],
  ["come", "came comes coming", "v.", "来到；出现；在习语中真正兴盛", "come into its own 表示粉色真正发挥影响、变得流行。", "come into one's own（真正兴盛/充分发挥）", "come into its own 不是进入自己的物品，须整体理解。"],
  ["inherently", "", "adv.", "天生地；固有地", "seem inherently attractive 表示“看起来天生有吸引力”，保留 seem 的不确定。", "inherently attractive（天生有吸引力的）", "intrinsically 与 inherently 近义，本文二者都用来质疑“天生”叙事。"],
  ["attractive", "", "adj.", "有吸引力的", "attractive to girls 指粉色看起来吸引女孩。", "be attractive to（对……有吸引力）", "attraction 是名词，attractive 是形容词，不能直接互换位置。"],
  ["define", "defined defines defining", "v.", "界定；定义", "what defined them as female 指被当作界定女孩为女性的部分。", "define A as B（把 A 界定为 B）", "define 不只是字典下定义，也可指社会如何塑造身份。"],
  ["critical", "", "adj.", "关键的；至关重要的", "the first few critical years 指最初几个关键年份。", "critical years（关键岁月）", "critical 还可指批评的，本文为关键的。"],
  ["profoundly", "", "adv.", "深刻地；极大地", "how profoundly marketing trends dictated... 强调影响程度。", "profoundly influence（深刻影响）", "profoundly 比 deeply 更正式，常修饰影响或理解。"],
  ["trend", "trends", "n.", "趋势；潮流", "marketing trends 指营销中的变化潮流。", "marketing trends（营销趋势）", "trend 是一段时期的走向，不等于一次广告活动。"],
  ["dictate", "dictated dictates dictating", "v.", "强力左右；决定", "dictated our perception 指营销趋势左右我们的看法。", "dictate perception（左右看法）", "dictate 也可指口述，不是本文的词义。"],
  ["perception", "perceptions", "n.", "看法；感知方式", "our perception of what is natural to kids 指我们如何理解儿童天性。", "perception of（对……的看法）", "perception 可指感官知觉，本文为社会观念。"],
  ["psychological", "", "adj.", "心理的", "psychological development 指儿童心理发展。", "psychological development（心理发展）", "psychological 不等于 physical，本文不是身体成长。"],
  ["toddler", "toddlers", "n.", "幼儿；学步儿童", "toddler 是被营销推广后才成为常用购物术语的称谓。", "a toddler（幼儿）", "本文重点是这一标签的市场来源，不把它误当自然不变的科学阶段。"],
  ["assume", "assumed assumes assuming", "v.", "假定；想当然认为", "I assumed... 后被 wrong 推翻，表示作者此前未经证实的看法。", "assume that（假定……）", "assume 不等于 prove；后接从句时常表达暂定判断。"],
  ["phase", "phases", "n.", "阶段", "that phase 回指 toddler 所对应的发展阶段概念。", "a developmental phase（发展阶段）", "phase 可指月相或项目阶段，本文指儿童成长标签。"],
  ["research", "researches researched researching", "n./v.", "研究", "years of research into children's behaviour 是作者原先的错误设想。", "research into（对……的研究）", "research 通常不可数；researches 作复数或动词需依句法判断。"],
  ["behaviour", "behaviours", "n.", "行为", "children's behaviour 是研究对象，不是文章认定的发展阶段来源。", "children's behaviour（儿童行为）", "behaviour 是英式拼写；美式为 behavior。"],
  ["turn", "turns turned turning", "v.", "结果是；变得（turn out）", "Turns out 省略 that，表示后来发现实际情况。", "turn out（结果发现）", "turn 可指转弯；turn out 在本文需整体理解。"],
  ["historian", "historians", "n.", "历史学家", "a historian of childhood consumerism 是 Daniel Cook 的身份。", "a historian of（……史研究者）", "historian 研究历史，不能误为 history 课程。"],
  ["consumerism", "", "n.", "消费主义；消费文化", "childhood consumerism 指儿童生活被消费市场塑造的现象。", "childhood consumerism（儿童消费文化）", "consumerism 不只是 consumer 的复数，强调社会消费逻辑。"],
  ["popularise", "popularised popularises popularising", "v.", "使流行；推广", "it was popularised as a marketing trick 指该称谓被营销推广。", "be popularised as（作为……被推广）", "popularise 是使某物流行；be popular 是某物本身受欢迎。"],
  ["trick", "tricks", "n.", "花招；策略", "a marketing trick 指为销售设计的营销花招。", "a marketing trick（营销花招）", "trick 也可指魔术或欺骗，本文强调带目的的商业策略。"],
  ["manufacturer", "manufacturers", "n.", "制造商", "clothing manufacturers 被写为推广 toddler 术语的商业施事。", "clothing manufacturer（服装制造商）", "manufacturer 是生产者，retailer 是零售者，本文二者不能混同。"],
  ["trade", "", "n./adj.", "行业；贸易的", "trade publications 指面向行业从业者的刊物。", "trade publications（行业刊物）", "trade 还可作交易动词，本文作定语限定 publications。"],
  ["publication", "publications", "n.", "出版物；刊物", "Trade publications counselled department stores 指行业刊物提出建议。", "trade publication（行业刊物）", "publication 指出版物，不等于出版行为本身。"],
  ["counsel", "counselled counsels counselling", "v./n.", "劝告；建议", "counselled department stores that... 指向百货商店建议。", "counsel somebody that（建议某人……）", "英式拼写 counselled/counselling 双写 l；counsel 也可作法律顾问名词。"],
  ["department", "departments", "n.", "部门；百货商店的专柜", "department stores 是百货商店这一整体名词。", "department store（百货商店）", "不能逐字理解成“部门的商店”。"],
  ["stepping stone", "stepping-stone", "n.", "垫脚石；通往下一阶段的跳板", "third stepping stone 比喻人为增加的市场过渡层。", "a stepping stone between A and B（A 与 B 间的过渡跳板）", "不是实际石头；本句指婴儿装与大童装之间的新消费类别。"],
  ["infant", "infants", "n./adj.", "婴儿；婴儿的", "infant wear 是婴儿服装。", "infant wear（婴儿服装）", "infant 比 toddler 年龄更小，本文二者构成市场层级。"],
  ["wear", "wore worn wearing", "n./v.", "穿着；服装", "infant wear 为服装名词；wore white 为 wear 的过去式。", "infant wear（婴儿服装）", "wear 可为动词“穿”，也可为名词“服装”；原文两处词性不同。"],
  ["shopper", "shoppers", "n.", "购物者；消费者", "a common shoppers' term 是购物者普遍使用的术语。", "shoppers' term（购物者常用术语）", "shoppers' 为复数所有格，term 的中心含义是术语。"],
  ["term", "terms", "n.", "术语；说法", "toddler became a common shoppers' term 指它先成为购物分类用语。", "a common term（常用术语）", "term 还可指学期、条件，本文为名词术语。"],
  ["evolve", "evolved evolves evolving", "v.", "逐渐演变", "it evolved into a developmental stage 指称谓逐渐变成社会认可阶段。", "evolve into（演变成）", "evolve 强调渐变；develop 可为发展或开发，不能完全替代。"],
  ["developmental", "", "adj.", "发展的；发育阶段的", "a developmental stage 是被广泛接受的成长阶段。", "developmental stage（发展阶段）", "developmental 是形容词，development 是名词。"],
  ["split", "splitting splits", "v.", "划分；分割", "Splitting kids or adults into categories 指按市场类别细分人群。", "split A into B（把 A 分成 B）", "split 不只指裂开，也可指人为分类；本文主语为动名词 splitting。"],
  ["ever-tinier", "", "adj.", "越来越小的；越来越细的", "ever-tinier categories 指不断细分的类别。", "ever-tinier categories（越来越细的类别）", "ever 加比较级表示变化持续加强，不等同 once。"],
  ["category", "categories", "n.", "类别；分类", "把人群分为更小类别以提高利润。", "into categories（分成类别）", "category 指分类框，不是具体某件商品。"],
  ["sure-fire", "", "adj.", "几乎必定奏效的", "a sure-fire way to boost profits 形容商业上可靠的增利办法。", "a sure-fire way（万全办法）", "本义与射击命中有关，本文为比喻性“十拿九稳”。"],
  ["boost", "boosts boosted boosting", "v./n.", "提升；促进", "boost profits 指提高利润。", "boost profits（提高利润）", "boost 强调推动上升，increase 是较中性的增加。"],
  ["profit", "profits", "n.", "利润", "boost profits 是全文对市场细分动机的直接说明。", "boost profits（增加利润）", "profit 与 sales 不同：销售额高不必然等于利润高。"],
  ["segment", "segments segmented segmenting", "v./n.", "细分；市场细分", "segment a market 指按消费特征切分市场。", "segment a market（细分市场）", "segment 不只是几何线段，本文为营销动词。"],
  ["magnify", "magnifies magnified magnifying", "v.", "放大；夸大", "magnify gender differences 指把性别差异刻意放大。", "magnify differences（夸大差异）", "magnify 可指放大镜，本文为社会差异的夸张化。"],
  ["gender", "genders", "n.", "性别（社会性别维度）", "gender differences 是营销细分的维度。", "gender differences（性别差异）", "gender 在此与 sex 并列出现，文章讨论市场化的性别标记。"],
  ["invent", "invented invents inventing", "v.", "发明；凭空制造", "invent them where they did not exist 指在没有差异处制造差异。", "invent differences（制造差异）", "invent 不是发现已有事实，正是作者批评的强词。"],
  ["previously", "", "adv.", "先前；此前", "did not previously exist 表原先不存在。", "previously exist（此前存在）", "previously 标记时间先后，不能当作“可能地”。"],
  ["sole", "", "adj.", "唯一的；仅有的", "sole representation of girlhood 是 26 题正确项的核心限制。", "the sole representation of（唯一代表）", "sole 还可指鞋底，本文为“唯一的”。"],
  ["representation", "representations", "n.", "代表；呈现方式", "representation of girlhood 指对女孩时期的单一呈现。", "representation of（对……的呈现）", "representation 不等于 legal representative，本文讨论文化形象。"],
  ["classify", "classifies classified classifying", "v.", "分类", "29题 classify consumers into smaller groups 概括原文细分市场逻辑。", "classify A into groups（把 A 分为群体）", "classify 是按标准归类，segment 更侧重营销市场细分。"],
  ["consumer", "consumers", "n.", "消费者", "29题 consumers 对应原文的 kids or adults 作为被细分的市场群体。", "consumer groups（消费者群体）", "consumerism 为消费主义；consumer 是具体消费者。"],
  ["inborn", "", "adj.", "天生的；先天的", "30题 inborn tendency 是被全文否定的解释。", "an inborn tendency（先天倾向）", "inborn 与 encoded in DNA 同属天生论，原文以营销史反驳。"],
  ["tendency", "tendencies", "n.", "倾向", "inborn tendency 指先天偏好倾向。", "a tendency to（做……的倾向）", "tendency 是可能性/倾向，不是确定事实。"],
  ["impose", "imposed imposes imposing", "v.", "强加；施加", "30题 imposed by profit-driven businessmen 概括逐利营销对偏好的塑造。", "impose A on B（把 A 强加给 B）", "impose 指外部强加；不是自然形成的 attract。"],
  ["profit-driven", "", "adj.", "逐利驱动的", "profit-driven businessmen 对应全文 boost profits 的商业动机。", "profit-driven business（逐利经营）", "profit-driven 说明动机，不等于所有商家都已完全理解心理机制。"],
  ["businessman", "businessmen", "n.", "商人；经营者", "30题 businessman 概括服装制造商、百货商店等逐利主体。", "profit-driven businessmen（逐利商人）", "businessman 为男性称谓；原文实体具体为 manufacturers 与 stores。"],
  ["tiny", "tinier tiniest", "adj.", "极小的；微小的", "such a tiny slice of the rainbow 强调粉色只是完整色谱中的很小一部分。", "a tiny slice of（极小的一部分）", "tiny 比 small 更强调尺寸或份额极小；此处不能推成粉色没有影响。"],
  ["repeatedly", "", "adv.", "反复地；一再地", "repeatedly and firmly 修饰 fuses，强调这种身份绑定不断被重复。", "repeatedly do sth.（反复做某事）", "repeatedly 强调次数，firmly 强调力度；两者不能互相替代。"],
  ["two-year-old", "two-year-olds", "n./adj.", "两岁的孩子；两岁的", "even among two-year-olds 指这种文化呈现甚至延伸到两岁儿童。", "a two-year-old（一个两岁的孩子）", "复数为 two-year-olds；作前置定语时通常写 a two-year-old child。"],
  ["interest", "interests", "n.", "兴趣；关注的事物", "girls' lives and interests 指女孩能过怎样的生活、能喜欢什么。", "have an interest in（对……感兴趣）", "interest 可指兴趣、利益或利息；本文为兴趣与关注领域。"],
  ["somehow", "", "adv.", "不知怎的；以某种方式", "somehow encoded in their DNA 表示“仿佛不知怎么地被写进基因”，随后被否定。", "somehow seem to（不知怎的似乎）", "somehow 带不确定性，不等于 clearly 或 certainly。"],
  ["jo", "", "n.（专名）", "乔（Jo Paoletti 的名）", "Jo 与 Paoletti 共同构成研究者姓名。", "Jo Paoletti（乔·保莱蒂）", "人名应整体识别，不把 Jo 当普通词义翻译。"],
  ["paoletti", "", "n.（专名）", "保莱蒂（研究者姓氏）", "Jo Paoletti 是文中被引用的美国研究者。", "according to Jo Paoletti（按乔·保莱蒂的说法）", "姓氏用于来源归属，不是可按字面拆开的普通名词。"],
  ["dress", "dresses dressed dressing", "n./v.", "连衣裙；衣服", "gender-neutral dresses 指不按男孩女孩区分的连衣裙。", "a gender-neutral dress（不分性别的连衣裙）", "dress 作名词是连衣裙，作动词是给……穿衣；本句为复数名词。"],
  ["blue", "", "n./adj.", "蓝色；蓝色的", "Blue symbolised femininity 说明蓝色曾被赋予女性气质的文化象征。", "blue symbolised femininity（蓝色象征女性气质）", "本文讲历史符号，不把颜色同性别的关系说成天生事实。"],
  ["virgin", "", "n.（专名组成）", "圣母（Virgin Mary 中的 Virgin）", "the Virgin Mary 是圣母玛丽亚这一专有称谓。", "the Virgin Mary（圣母玛丽亚）", "此处不取普通名词“处女”义，须与 Mary 合并识别为专名。"],
  ["mary", "", "n.（专名）", "玛丽（Virgin Mary 中的 Mary）", "Mary 与 Virgin 连用构成宗教专名。", "the Virgin Mary（圣母玛丽亚）", "此处为专有名词，不按普通词义或人称代词处理。"],
  ["realise", "realises realised realising", "v.", "意识到；认识到", "I had not realised 表示作者此前没有意识到营销趋势的深刻影响。", "realise how ...（意识到多么……）", "realise 是英式拼写；美式常写 realize。"],
  ["daniel", "", "n.（专名）", "丹尼尔（Daniel Cook 的名）", "Daniel Cook 被介绍为儿童消费主义历史学家。", "Daniel Cook（丹尼尔·库克）", "人名用于标示信息来源，不把 Daniel 当普通名词处理。"],
  ["childhood", "", "n.", "童年；儿童时期", "a historian of childhood consumerism 研究儿童生活中的消费文化。", "childhood consumerism（儿童消费文化）", "childhood 指儿童时期，不能与 child 的单个孩子含义混同。"],
  ["clothing", "", "n.", "衣物；服装", "clothing manufacturers 指推广 toddler 概念的服装制造商。", "clothing manufacturers（服装制造商）", "clothing 通常不可数；不是 cloth 的单纯复数。"],
  ["store", "stores", "n.", "商店；百货商店", "department stores 是行业刊物提出营销建议的对象。", "department store（百货商店）", "store 可指储存或商店；本文为零售百货商店。"],
  ["stone", "stones", "n.", "石头；踏脚石", "third stepping stone 中 stone 是比喻性过渡层的一部分。", "a stepping stone（过渡跳板）", "stepping stone 是固定比喻，不能按实际石头理解。"],
  ["stepping", "stepped stepping", "v.-ing（定语）", "踏步的；起过渡作用的", "third stepping stone 中 stepping 修饰 stone，表示通往下一阶段的过渡。", "a stepping stone（过渡跳板）", "不要把 stepping 单独误作实际走路；在固定搭配中强调阶段间的过渡功能。"],
  ["old", "older oldest", "adj.", "年长的；较大的", "older kids' clothes 指较大孩子穿的衣服。", "older kids（年龄较大的孩子）", "older 是 old 的比较级；本文比较年龄，不表示陈旧。"],
  ["broadly", "", "adv.", "广泛地；大体上", "broadly accepted 表示被社会广泛接受。", "broadly accepted（被广泛接受）", "broadly 修饰 accepted 的接受范围，不等于完全没有争议。"],
  ["accept", "accepts accepted accepting", "v.", "接受；认可", "accepted developmental stage 指被广泛认可的发展阶段概念。", "accept A as B（接受 A 为 B）", "accept 可指收到或同意；本文为社会层面的认可。"],
  ["prefer", "prefers preferred preferring", "v.", "更喜欢；偏好", "White is preferred by babies 是原卷错误选项，把清洗便利误说成婴儿偏好。", "prefer A to B（比起 B 更喜欢 A）", "prefer 表比较性的偏好；原文没有说婴儿主动偏爱白色。"],
  ["advise", "advises advised advising", "v.", "建议；劝告", "were advised to 概括行业刊物给百货商店的建议。", "advise sb. to do sth.（建议某人做某事）", "advise 后可接人和不定式；不能只根据题干把建议对象误作消费者。"],
  ["conclude", "concludes concluded concluding", "v.", "得出结论；推断", "It can be concluded that ... 要求根据全文营销史作归纳。", "conclude that ...（得出……的结论）", "conclude 是基于证据的归纳，不等于随意猜测。"],
  ["understand", "understands understood understanding", "v.", "理解；弄清", "fully understood by clothing manufacturers 是第30题干扰项，全文并未说制造商完全理解偏好机制。", "fully understand（完全理解）", "understood 为过去分词；fully understood 不能从“会营销”推出来。"],
  ["interpret", "interprets interpreted interpreting", "v.", "解释；阐释", "well interpreted by psychological experts 是第30题干扰项，作者用 wrong 否定专家研究的原先假设。", "interpret A as B（把 A 解释为 B）", "interpret 是解释，不能误作专家已经给出完整正确说明。"],
  ["look", "looks looked looking", "v.", "看；查看", "Looking around 作分词状语，表示作者环顾周围后产生失望。", "look around（环顾四周）", "look 可作看、显得等义；本文为主动观察，不是系动词“看起来”。"],
];

const reviewed = reviewedLexicon(rows);

export const passage2012P2Lexicon = reviewed.entries;
export const passage2012P2LemmaAliases: Record<string, string> = {
  ...reviewed.aliases,
  ...Object.fromEntries(rows.map(([headword]) => [headword, headword])),
  "girls'": "girl",
  "kids'": "kid",
  "shoppers'": "shopper",
  "children's": "child",
  "women's": "woman",
  "what's": "what",
  "two-year-olds": "two-year-old",
  "two-year": "two-year-old",
  olds: "old",
  "1930s": "1930s",
  "20th": "20th",
  "mid-1980s": "mid-1980s",
};
export const passage2012P2CollocationGlosses = reviewed.glosses;
export const passage2012P2FormPartOfSpeech: Record<string, string> = {
  pretty: "adj.", women: "n.（复数）", obsessed: "adj.（过去分词）", pervasive: "adj.", pink: "n.", intrinsically: "adv.", tiny: "adj.", girlhood: "n.", repeatedly: "adv.", firmly: "adv.", girls: "n.（复数）", identity: "n.", appearance: "n.", presents: "v.（第三人称单数）", 'two-year-olds': "n.（复数）", innocent: "adj.", evidence: "n.", innocence: "n.", singular: "adj.", lives: "n.（复数）", interests: "n.（复数）", unavoidable: "adj.", somehow: "adv.", encoded: "v.-ed（过去分词）", DNA: "n.", associate: "n.", professor: "n.", American: "adj.", 'colour-coded': "v.-ed（被动）", early: "adj.", '20th': "num.", domestic: "adj.", washing: "n.（定语）", machines: "n.（复数）", babies: "n.（复数）", white: "adj.", practical: "adj.", getting: "v.-ing", clean: "adj.", boiling: "v.", both: "det.", boys: "n.（复数）", wore: "v.-ed", thought: "v.-ed（被动）", 'gender-neutral': "adj.", dresses: "n.（复数）", nursery: "adj.", colours: "n.（复数）", introduced: "v.-ed（被动）", actually: "adv.", considered: "v.-ed（被动）", more: "adj.（比较级）", masculine: "adj.", pastel: "adj.", red: "n.", associated: "v.-ed（被动）", strength: "n.", Blue: "n.", intimations: "n.（复数）", Virgin: "n.（专名）", Mary: "n.（专名）", constancy: "n.", faithfulness: "n.", symbolised: "v.-ed", femininity: "n.", 'mid-1980s': "n.", amplifying: "v.-ing", age: "n.", sex: "n.", differences: "n.（复数）", dominant: "adj.", "children's": "n.（所有格定语）", marketing: "n.", strategy: "n.", fully: "adv.", came: "v.-ed", own: "pron.", began: "v.-ed", inherently: "adv.", attractive: "adj.", them: "pron.", female: "adj.", least: "adv.", critical: "adj.", years: "n.（复数）", realised: "v.-ed", profoundly: "adv.", trends: "n.（复数）", dictated: "v.-ed", perception: "n.", natural: "adj.", kids: "n.（复数）", including: "prep.", core: "adj.", beliefs: "n.（复数）", psychological: "adj.", development: "n.", Take: "v.", toddler: "n.", assumed: "v.-ed", phase: "n.", experts: "n.（复数）", developed: "v.-ed", research: "n.", behaviour: "n.", wrong: "adj.", Turns: "v.", out: "adv.", Daniel: "n.（专名）", Cook: "n.（专名）", historian: "n.", childhood: "n.", consumerism: "n.", popularised: "v.-ed（被动）", trick: "n.", clothing: "n.（定语）", manufacturers: "n.（复数）", trade: "adj.", publications: "n.（复数）", counselled: "v.-ed", department: "n.", stores: "n.（复数）", order: "n.", increase: "v.", sales: "n.（复数）", should: "modal v.", create: "v.", third: "num.", stepping: "v.-ing（定语）", stone: "n.", infant: "adj.", wear: "n.", older: "adj.（比较级）", clothes: "n.（复数）", shoppers: "n.（复数）", term: "n.", evolved: "v.-ed", broadly: "adv.", accepted: "adj.（过去分词）", developmental: "adj.", stage: "n.", Splitting: "v.-ing", adults: "n.（复数）", 'ever-tinier': "adj.", categories: "n.（复数）", proved: "v.-ed", 'sure-fire': "adj.", boost: "v.", profits: "n.（复数）", easiest: "adj.（最高级）", ways: "n.（复数）", segment: "v.", market: "n.", magnify: "v.", gender: "n.", invent: "v.", previously: "adv.", exist: "v.", sole: "adj.", representation: "n.", influence: "v.", preferred: "v.-ed（被动）", neutral: "adj.", symbolising: "v.-ing", observation: "n.", nature: "n.", researches: "n.（复数）", studies: "n.（复数）", advised: "v.-ed（被动）", classify: "v.", consumers: "n.（复数）", attach: "v.", equal: "adj.", importance: "n.", focus: "v.", common: "adj.", concluded: "v.-ed（被动）", understood: "v.-ed（被动）", clearly: "adv.", inborn: "adj.", tendency: "n.", mainly: "adv.", imposed: "v.-ed（被动）", 'profit-driven': "adj.", businessmen: "n.（复数）", interpreted: "v.-ed（被动）",
};

passage2012P2Lexicon.present.otherMeanings = ["n. 礼物；adj. 在场的、目前的；v. 提交、颁发。present A as B 在本文为“把 A 呈现为 B”。"];
passage2012P2Lexicon.matter = { partOfSpeech: "n.", contextualMeaning: "事情；实际问题（as a practical matter）", use: "as a practical matter 中 matter 是事情、情况；不是第1段质问的动词 matter。", specialForms: ["matter 可作名词或动词；本句为名词。"], collocations: ["as a practical matter"], examSynonyms: ["issue 指议题；matter 在此指实际情况。"] };
passage2012P2Lexicon.take = { partOfSpeech: "v.", contextualMeaning: "拿……作为例子", use: "Take the toddler. 是祈使式举例，省略主语 you。", specialForms: ["take / takes / took / taken / taking。"], collocations: ["take + noun as an example"], examSynonyms: ["use 可作一般使用；take 在此为口语化“以……为例”。"] };
passage2012P2Lexicon.term.otherMeanings = ["n. 学期；期限；条件；v. 把……称为。本文为购物者使用的术语。"];
passage2012P2Lexicon.wear.otherMeanings = ["v. 穿；磨损；n. 服装、衣着。正文既有 wore white 的动词义，也有 infant wear 的服装名词义。"];

export const passage2012P2SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2012-p2-s1": { it: { contextualMeaning: "粉色文化/粉色在女孩生活中的普遍存在", use: "yet 后 it 指上一分句谈到的粉色现象，不指 adult women。" }, young: { contextualMeaning: "年幼的", use: "young girls 与 adult women 形成代际对照，不是“年轻女子”的泛称。" } },
  "2012-p2-s2": { it: { contextualMeaning: "粉色", use: "两处 it 均指 pink；后一句说明粉色把女孩身份绑定到外表。" }, slice: { contextualMeaning: "彩虹中的一小片；比喻女孩形象中很小的一部分", use: "a tiny slice of the rainbow 不说物理切片，而是批评粉色占据过度代表性。" }, identity: { contextualMeaning: "女孩被塑造的身份认同", use: "girls' identity 是被营销叙事塑造的“女孩是谁”，不是身份证件。" } },
  "2012-p2-s3": { it: { contextualMeaning: "粉色文化/其营销呈现", use: "Then it presents 中 it 继续指前句的 pink 及其文化呈现。" }, connection: { contextualMeaning: "女孩身份与外表之间的既有连接", use: "that connection 回指上一句 fuses girls' identity to appearance。" }, between: { contextualMeaning: "原卷中保留的 between girls as... 片段", use: "用户原卷与多个公开真题转录均为该形式，搭配不完整；不擅自补词，语义按前句 connection 回指理解。" } },
  "2012-p2-s4": { look: { contextualMeaning: "环顾；观察", use: "Looking around 作分词状语，逻辑主语为 I。" }, singular: { contextualMeaning: "异常突出的；极其的", use: "singular lack 不是语法上的单数，而是强调缺乏程度。" }, life: { contextualMeaning: "生活方式和人生可能", use: "girls' lives 不是生命次数，而是女孩能过怎样的生活。" } },
  "2012-p2-s5": { attraction: { contextualMeaning: "对粉色的吸引/偏好", use: "Girls' attraction to pink 中 to 引所指对象。" }, encode: { contextualMeaning: "仿佛被先天写入", use: "somehow encoded in DNA 是“似乎天生”的说法，随后被否定。" }, it: { contextualMeaning: "女孩爱粉色是不可避免/天生的判断", use: "it is not 省略前面 unavoidable/encoded in DNA 的补语。" } },
  "2012-p2-s6": { "colour-code": { contextualMeaning: "按颜色标记；按颜色区分性别", use: "were not colour-coded at all 表过去儿童完全没有按颜色做性别分类；连字符连接 colour 和 coded，应整体点击理解。" }, wear: { contextualMeaning: "穿着", use: "all babies wore white 中 wore 是 wear 的过去式；与 infant wear 的名词义不同。" }, matter: { contextualMeaning: "实际考虑", use: "as a practical matter 表穿白色出于洗衣便利。" }, they: { contextualMeaning: "衣服", use: "boil them 的 them 回指 clothes。" } },
  "2012-p2-s7": { what: { contextualMeaning: "被认为是中性连衣裙的东西", use: "what 引导名词性从句，整体作 wore 的宾语。" }, thought: { contextualMeaning: "被认为", use: "were thought of as 为被动的“被看作”，不指思考动作。" } },
  "2012-p2-s8": { nursery: { contextualMeaning: "婴幼儿用品的", use: "nursery colours 指婴幼儿房间或用品中使用的颜色。" }, consider: { contextualMeaning: "被认为是", use: "pink was considered the more masculine colour 是被动宾补结构。" }, which: { contextualMeaning: "红色", use: "which was associated with strength 回指 red，不是整个句子。" } },
  "2012-p2-s9": { intimation: { contextualMeaning: "文化暗示与联想", use: "with its intimations of... 是蓝色所带的宗教和品格联想。" }, symbolise: { contextualMeaning: "象征", use: "Blue symbolised femininity 描述历史文化符号，不作今日事实。" } },
  "2012-p2-s10": { it: { contextualMeaning: "粉色", use: "pink fully came into its own 后 when it began... 的 it 指 pink。" }, own: { contextualMeaning: "自身应有的位置/作用", use: "come into its own 为习语，own 不是所有格代词的普通“自己的”。" }, they: { contextualMeaning: "女孩", use: "defined them as female 的 them 回指 girls。" }, critical: { contextualMeaning: "关键的", use: "the first few critical years 指人生最初几个关键年份。" } },
  "2012-p2-s11": { dictate: { contextualMeaning: "强力左右；决定", use: "marketing trends dictated our perception 不是口述文字，而是左右观念。" }, natural: { contextualMeaning: "对儿童而言自然的", use: "what is natural to kids 是被营销影响的社会判断。" }, their: { contextualMeaning: "儿童的", use: "their psychological development 中 their 指 kids。" } },
  "2012-p2-s12": { take: { contextualMeaning: "以……为例", use: "Take the toddler. 是祈使式举例，不是让读者把孩子带走。" } },
  "2012-p2-s13": { phase: { contextualMeaning: "toddler 被认定的发展阶段", use: "that phase 回指上一句 toddler。" }, wrong: { contextualMeaning: "这个假设错了", use: "冒号后 wrong 省略 That assumption was，推翻作者原先看法。" } },
  "2012-p2-s14": { turn: { contextualMeaning: "结果发现（turns out）", use: "Turns out 省略 that，引出与上一句相反的事实。" }, it: { contextualMeaning: "toddler 这一称谓/阶段概念", use: "was popularised 的 it 回指 toddler。" }, trick: { contextualMeaning: "营销花招", use: "marketing trick 带批评色彩，说明有意推动消费。" } },
  "2012-p2-s15": { trade: { contextualMeaning: "行业的", use: "trade publications 指服务行业从业者的刊物。" }, counsel: { contextualMeaning: "建议；劝告", use: "counselled department stores that... 表刊物向百货商店建议。" }, they: { contextualMeaning: "百货商店", use: "they should create 的 they 指 department stores。" }, stepping: { contextualMeaning: "通向下一阶段的跳板", use: "third stepping stone 是市场分层的比喻，不是实物石头。" }, wear: { contextualMeaning: "服装", use: "infant wear 中 wear 为服装名词，与 wore white 的动词义分开。" } },
  "2012-p2-s16": { it: { contextualMeaning: "toddler 这个购物术语", use: "it evolved into... 回指 toddler 这个称谓，而非某个孩子。" }, term: { contextualMeaning: "购物者常用的术语", use: "shoppers' term 指购买服装时使用的分类说法。" }, stage: { contextualMeaning: "发展阶段", use: "developmental stage 是后来被广泛接受的儿童成长阶段概念。" } },
  "2012-p2-s17": { split: { contextualMeaning: "把人群分开分类", use: "动名词 Splitting kids, or adults 作整句主语。" }, "ever-tinier": { contextualMeaning: "越来越细小的", use: "ever 加比较级 tinier 表不断细分。" }, prove: { contextualMeaning: "已经证明是", use: "has proved 表经验上显示为有效做法。" }, "sure-fire": { contextualMeaning: "几乎必定奏效的", use: "sure-fire way 是提高利润的万全办法的比喻说法。" } },
  "2012-p2-s18": { segment: { contextualMeaning: "细分", use: "segment a market 指按特征切分消费者市场。" }, magnify: { contextualMeaning: "夸大；强化", use: "magnify gender differences 指有意放大性别差异。" }, they: { contextualMeaning: "性别差异", use: "invent them 的 them 回指 gender differences。" }, where: { contextualMeaning: "在原先不存在这些差异的情形中", use: "where 引出情形性定语从句，不是具体地理地点。" } },
};
