import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, reviewedPhrases, type LexiconRow, type PhraseRow, type ReviewedEntry } from "./2011-content-helpers";

const rows: LexiconRow[] = [
  ["adam", "", "proper n.", "亚当（人名）", "Adam Davidson 是本文引用文章的作者，只需识别。", "Adam Davidson（亚当·戴维森）", "专有名词不作为普通词义迁移。"],
  ["davidson", "davidson's", "proper n.", "戴维森（姓氏）", "Adam Davidson 是作者姓名；所有格 Davidson's 修饰 article。", "Adam Davidson（亚当·戴维森）", "专有名词只需识别，不拆成普通构词。"],
  ["relate", "relates related relating", "v.", "讲述；叙述", "relates a joke 表示把一个笑话讲给读者，不是把两件事建立联系。", "relate a story（讲述故事）", "tell 更普通；relate 在书面语中可表示较完整地叙述。"],
  ["joke", "jokes joked joking", "n.", "笑话", "开篇笑话用夸张方式说明现代纺织厂的自动化程度。", "tell a joke（讲笑话）", "joke 是笑话；anecdote 是轶事，不一定有笑点。"],
  ["mill", "mills", "n.", "工厂；纺织厂", "textile mill 指纺织厂，不是磨坊这一历史义。", "a textile mill（纺织厂）", "factory 是泛称；mill 常见于纺织、钢铁、造纸等加工厂。"],
  ["automate", "automates automated automating", "v.", "使自动化", "has been automated 是现在完成时被动，说明生产过程已高度自动化。", "automate production（使生产自动化）", "mechanize 强调机械化；automate 强调由自动系统完成。"],
  ["employee", "employees", "n.", "雇员；员工", "only two employees 是笑话中的用工人数，不等于工厂数量。", "hire an employee（雇用员工）", "employee 是受雇者；employer 是雇主。"],
  ["dog", "dogs", "n.", "狗", "笑话中狗的任务是阻止人接近机器。", "keep the dog away（让狗远离）", "此处为字面动物，不是贬义称呼。"],
  ["yes", "", "interj.", "是的；确实", "段首 Yes 承认技术一直会减少一些岗位，再由 but 转向变化已经加速。", "Yes, but ...（是的，不过……）", "先承认前一句，再读转折后的重点。"],
  ["stubbornly", "", "adv.", "顽固地；难以下降地", "stubbornly high 修饰失业率，表示长期处在高位且难以改善。", "remain stubbornly high（持续居高不下）", "persistently 侧重持续；stubbornly 还带难以改变之意。"],
  ["middle-class", "", "adj.", "中产阶级的", "middle-class incomes 指中产阶级群体的收入。", "middle-class incomes（中产阶级收入）", "middle class 作名词；连字符形式在名词前作定语。"],
  ["advance", "advances advanced advancing", "n.", "进步；发展", "advances in globalization and technology 指这些领域的发展，不是预付款。", "advances in technology（技术进步）", "advance 作动词可表示推进；本文复数名词表示进展。"],
  ["globalization", "", "n.", "全球化", "与信息技术进步并列，说明劳动力替代的结构性原因。", "economic globalization（经济全球化）", "internationalization 侧重跨国扩展；globalization 强调全球范围的整合。"],
  ["technology", "technologies", "n.", "技术；科技", "information technology revolution 是信息技术革命；new technology 指新技术总体。", "information technology（信息技术）", "technique 多指具体方法技巧；technology 指技术体系。"],
  ["replace", "replaces replaced replacing", "v.", "取代；替换", "replace labor with machines 中 labor 是被替代者，machines 是替代来源。", "replace A with B（用B取代A）", "substitute B for A 方向相同，但介词结构不同。"],
  ["skill", "skills skilled", "n.", "技能；本领", "workers with average skills 指技能水平一般的劳动者。", "job skills（职业技能）", "ability 更宽泛；skill 通常可通过学习和练习获得。"],
  ["officially", "", "adv.", "正式地；确实地", "average is officially over 中起强调作用：只靠普通水平的时代确实结束了，不指政府公告。", "be officially over（正式结束）", "formally 偏程序正式；此处 officially 具有修辞强调。"],
  ["employer", "employers", "n.", "雇主；用人单位", "雇主能获得更多廉价替代资源，是普通劳动者压力增加的原因。", "potential employers（潜在雇主）", "employer 雇主；employee 雇员；employment 就业。"],
  ["robotics", "", "n.", "机器人技术", "cheap robotics 指成本较低的机器人技术或设备能力。", "advances in robotics（机器人技术进步）", "robot 是具体机器人；robotics 是学科或技术领域，通常用单数形式。"],
  ["software", "", "n.", "软件", "与机器人、自动化并列，是雇主可低成本获得的资源。", "software development（软件开发）", "software 通常不可数，不说 a software。"],
  ["automation", "", "n.", "自动化", "cheap automation 指成本较低的自动化方案。", "industrial automation（工业自动化）", "automation 是过程或体系；automated 是已自动化的。"],
  ["genius", "geniuses", "n.", "天才；高水平人才", "cheap geniuses 夸张地指雇主能以较低成本获得的优秀人才。", "a technical genius（技术天才）", "genius 复数是 geniuses；本文不是精灵义。"],
  ["sure", "", "adj./adv.", "确定的；肯定", "know for sure 整体表示可以确定地知道。", "know for sure（确知）", "在 for sure 中按整体副词作用理解。"],
  ["unique", "", "adj.", "独特的；独一无二的", "unique value contribution 是能让个人脱颖而出的独特价值贡献。", "a unique contribution（独特贡献）", "special 可表示特别；unique 更强调与其他人不同。"],
  ["contribution", "contributions", "n.", "贡献", "本文指个人为工作提供的独特价值，不是捐款。", "make a contribution（作出贡献）", "contribution 可指捐献；本句由 value 和 employment 限定为工作价值。"],
  ["field", "fields", "n.", "领域；行业", "field of employment 指个人从事工作的领域，不是田地。", "a field of work（工作领域）", "area 可泛指范围；field 常指专业或职业领域。"],
  ["employment", "", "n.", "就业；工作", "field of employment 是就业领域；support employment 是促进就业。", "employment opportunities（就业机会）", "job 是具体职位；employment 是就业状态或总体用工。"],
  ["acceleration", "accelerations", "n.", "加速；加快", "there's been an acceleration 承接技术吞噬岗位，表示这一过程已经加快。", "an acceleration in change（变化加快）", "acceleration 是速度增加；speed 只是速度本身。"],
  ["factory", "factories", "n.", "工厂", "U.S. factories 是裁员动作的主体。", "factory workers（工厂工人）", "mill 是特定加工厂；factory 是一般工业生产场所。"],
  ["shed", "sheds shedding", "v.", "裁掉；减少", "factories shed workers 指工厂裁员；shed 的过去式仍是 shed。", "shed jobs（削减岗位）", "lay off workers 更直接说裁员；shed 强调去除、减少。"],
  ["erase", "erases erased erasing", "v.", "抹去；抵消", "裁员几乎抵消此前七十年的岗位增长，不是把技术成果删除。", "erase previous gains（抵消此前增长）", "wipe out 语气更强；erase 在此为比喻义。"],
  ["previous", "", "adj.", "先前的；此前的", "the previous 70 years 是所述十年之前的七十年。", "the previous decade（此前十年）", "last 可指最近一个；previous 强调相对于参照点更早。"],
  ["total", "totals totaled totalling", "n./adj.", "总数；总计的", "in total 把消失岗位合计为约六百万。", "in total（总计）", "total 作形容词也可表示全部的；本搭配作总计。"],
  ["disappear", "disappears disappeared disappearing", "v.", "消失；不复存在", "制造业岗位消失，表示岗位不再存在。", "jobs disappear（岗位消失）", "vanish 更突然；disappear 中性描述不再出现。"],
  ["ensure", "ensures ensured ensuring", "v.", "确保；保障", "法案要确保每个美国人都有接受高中后教育的机会。", "ensure access to education（确保教育机会）", "insure 常指投保；assure 常接人；ensure 接要保证的结果。"],
  ["illustrate", "illustrates illustrated illustrating", "v.", "说明；阐明", "题目问笑话用于说明哪种影响，不是问插图。", "illustrate a point（说明观点）", "demonstrate 可强调证明；illustrate 常用例子解释。"],
  ["alleviation", "", "n.", "缓解；减轻", "alleviation of job pressure 意为就业压力的减轻，是第21题反向干扰。", "the alleviation of pressure（压力缓解）", "relief 更常用；alleviation 较正式。"],
  ["shrinkage", "", "n.", "缩小；萎缩", "the shrinkage of textile mills 指工厂本身规模或数量萎缩，原文只说雇员少。", "market shrinkage（市场萎缩）", "reduction 泛指减少；shrinkage 强调整体缩小。"],
  ["salary", "salaries", "n.", "薪水；薪金", "moderate salary 是第22题干扰项，正文没有要求雇员降低薪资诉求。", "earn a salary（领取薪水）", "wage 常按小时或周支付；salary 常按月或年固定支付。"],
  ["quotation", "quotations", "n.", "引文；引用的话", "第23题指第四段戴维森引述的工厂岗位数据。", "a direct quotation（直接引文）", "quote 可作动词或较口语的名词；quotation 是完整引文。"],
  ["explain", "explains explained explaining", "v.", "说明；解释", "题目问引文说明了什么现象。", "explain why（解释为什么）", "describe 是描述；explain 强调说清原因或含义。"],
  ["offer", "offers offered offering", "v.", "提供", "new jobs and services have been offered 是第23题时间与段落错位的干扰项。", "offer a service（提供服务）", "provide 更中性；offer 常带主动拿出、可供选择之意。"],
  ["accelerate", "accelerates accelerated accelerating", "v.", "使加速；加快", "第24题把加快技术革命错误地当作减少失业的措施。", "accelerate change（加速变化）", "speed up 更口语；accelerate 更正式。"],
  ["bill", "bills", "n.", "法案", "G. I. Bill 是法案名称；作者强调法案的教育目标，不是法案数量。", "pass a bill（通过法案）", "bill 还可指账单或钞票；本句由 pass 和政策语境确定为法案。"],
  ["post-high", "", "adj.", "高中后的", "post-high school education 整体指高中毕业后的继续教育。", "post-high school education（高中后教育）", "post- 表示在……之后。"],
  ["i.t.", "", "abbr.", "信息技术", "I.T. 是 information technology 的缩写。", "the I.T. revolution（信息技术革命）", "只需识别缩写，不拆成代词 I。"],
  ["t", "", "abbr. component", "信息技术缩写的一部分", "原卷将 I. T. 分开书写；T 是 technology 的首字母。", "I. T.（信息技术）", "与否定缩写中的 n't 无关。"],
];
const reviewed = reviewedLexicon(rows);
export const passage2013P1Lexicon: Record<string, ReviewedEntry> = reviewed.entries;
export const passage2013P1LemmaAliases: Record<string, string> = { ...reviewed.aliases, "davidson's": "davidson", "won't": "will", "there's": "there", "post-high": "post-high", "goes": "go", "notes": "note", "gains": "gain", "pieces": "piece", "ending": "end" };
export const passage2013P1FormPartOfSpeech: Record<string, string> = Object.fromEntries(rows.flatMap(([headword, forms, pos]) => [[headword, pos], ...forms.split(" ").filter(Boolean).map(form => [form, pos])]));

export const passage2013P1SentenceContexts: Record<string, Record<string, SentenceWordContext>> = {
  "2013-p1-s1": {
    textile: { partOfSpeech: "adj.", contextualMeaning: "纺织业的", use: "textile 修饰 mill，说明这是一家纺织厂。", preferredCollocations: ["textile mill（纺织厂）"] },
    entitle: { partOfSpeech: "v.-ed", contextualMeaning: "题为；名为", use: "entitled \"Making It in America\" 后置修饰 essay，说明文章标题。" },
    make: { partOfSpeech: "v.（标题中的动名词形式）", contextualMeaning: "取得成功；立足", use: "篇名 Making It in America 中 make it 整体指在美国取得成功。" },
    country: { partOfSpeech: "n.", contextualMeaning: "地区；乡间", use: "cotton country 指产棉区，不是一个国家。" },
    average: { partOfSpeech: "adj.", contextualMeaning: "普通的；一般的", use: "the average mill 指普通、典型的纺织厂，不是在计算算术平均数。" },
  },
  "2013-p1-s3": {
    article: { partOfSpeech: "n.", contextualMeaning: "文章", use: "Davidson's article 指戴维森写的文章，不是物品或法律条款。" },
    piece: { partOfSpeech: "n.", contextualMeaning: "文章；作品", use: "pieces 与 article 同类，指最近发表的多篇文章。" },
    make: { partOfSpeech: "v.-ing", contextualMeaning: "提出；表达", use: "making the point 说明这些文章共同提出一个观点。" },
    point: { partOfSpeech: "n.", contextualMeaning: "观点；要点", use: "the point 后接 that 同位语从句，展开观点内容。" },
    reason: { partOfSpeech: "n.", contextualMeaning: "原因", use: "the reason ... is because of ... 解释失业和收入下降的原因。" },
    decline: { partOfSpeech: "v.-ing/adj.", contextualMeaning: "下降的；减少的", use: "declining middle-class incomes 与 high unemployment 并列。" },
    demand: { partOfSpeech: "n.", contextualMeaning: "需求", use: "drop in demand 指经济衰退造成的总需求下降。" },
    revolution: { partOfSpeech: "n.", contextualMeaning: "革命；重大变革", use: "information technology revolution 指信息技术带来的重大变革。" },
    labor: { partOfSpeech: "n.", contextualMeaning: "劳动力；人工", use: "replace labor with machines 中 labor 是被替代对象。" },
  },
  "2013-p1-s5": { average: { partOfSpeech: "n./adj. used substantively", contextualMeaning: "普通水平；一般水准", use: "average is officially over 是中心判断：只达到普通水平已不够。" }, over: { partOfSpeech: "adj.", contextualMeaning: "结束的；不再适用的", use: "is over 作表语，表示靠一般水准即可的时代结束。" } },
  "2013-p1-s4": { average: { partOfSpeech: "adj.", contextualMeaning: "普通的；一般水平的", use: "三处 average 都说一般技能、一般工作与一般生活，不是数学平均值。" } },
  "2013-p1-s6": { being: { partOfSpeech: "gerund", contextualMeaning: "处于……状态", use: "Being average 整体作主语，指仅达到普通水平。" }, average: { partOfSpeech: "adj.", contextualMeaning: "普通水平的", use: "作 Being 的表语。" }, use: { partOfSpeech: "semi-modal", contextualMeaning: "过去常常；过去能", use: "what it used to 后省略 earn you，需从前文补回。" } },
  "2013-p1-s7": { access: { partOfSpeech: "n.", contextualMeaning: "获得、使用的机会", use: "have access to 后接雇主可用的劳动力与技术资源。" }, above: { partOfSpeech: "prep./adj.", contextualMeaning: "高于", use: "above average 修饰 foreign labor，表示水平高于一般。" }, average: { partOfSpeech: "n.", contextualMeaning: "普通水平；平均水准", use: "above average 作为整体表示高于普通水平。" }, labor: { partOfSpeech: "n.", contextualMeaning: "劳动力；人工", use: "foreign labor 指可供雇主选择的外国劳动力。" }, cheap: { partOfSpeech: "adj.", contextualMeaning: "成本低的；价格低廉的", use: "重复修饰劳动力、机器人、软件、自动化和人才，强调替代资源成本低。" } },
  "2013-p1-s8": { extra: { partOfSpeech: "n.", contextualMeaning: "额外优势；超出一般之处", use: "破折号后的 unique value contribution 解释 extra。" }, value: { partOfSpeech: "n. used attributively", contextualMeaning: "价值", use: "value contribution 整体指能为工作提供的价值贡献。" }, stand: { partOfSpeech: "v.", contextualMeaning: "显得突出", use: "stand out 是整体搭配，表示脱颖而出。" }, out: { partOfSpeech: "particle", contextualMeaning: "突出（短语成分）", use: "与 stand 构成 stand out，不单独按外面翻译。" } },
  "2013-p1-s9": { eat: { partOfSpeech: "v.-ing", contextualMeaning: "吞噬；不断挤掉", use: "eating jobs 是比喻，指技术持续减少就业岗位。" }, will: { partOfSpeech: "modal v.", contextualMeaning: "将会", use: "always will 后省略 be eating jobs，表示未来仍会如此。" } },
  "2013-p1-s10": { there: { partOfSpeech: "existential marker", contextualMeaning: "存在；发生", use: "there's been 表示已经出现了加速。" } },
  "2013-p1-s11": { note: { partOfSpeech: "v.", contextualMeaning: "指出；提到", use: "As Davidson notes 交代引文来源，不是做笔记。" }, end: { partOfSpeech: "v.-ing", contextualMeaning: "截止；结束于", use: "the 10 years ending in 2009 指截至2009年的十年。" }, gain: { partOfSpeech: "n.", contextualMeaning: "增长；新增成果", use: "结合 workers/jobs，gains 指此前七十年积累的就业岗位增长。" }, one: { partOfSpeech: "pron./number", contextualMeaning: "一个；三分之一中的一份", use: "one out of every three 表示每三个中一个。" }, total: { partOfSpeech: "n.", contextualMeaning: "总计", use: "in total 说明消失岗位合计约六百万。" } },
  "2013-p1-s13": { advance: { partOfSpeech: "n.", contextualMeaning: "进步；发展", use: "with each advance 表示每一次发展。" }, best: { partOfSpeech: "adj. superlative", contextualMeaning: "最好的；优质的", use: "the best jobs 指条件较好的工作岗位。" }, require: { partOfSpeech: "v.", contextualMeaning: "要求；需要", use: "require workers to have 表示岗位要求劳动者具备更多教育。" }, education: { partOfSpeech: "n.", contextualMeaning: "教育；受教育程度", use: "more and better education 同时说数量和质量。" }, average: { partOfSpeech: "n.", contextualMeaning: "普通水平", use: "above average 表示超出普通水平。" } },
  "2013-p1-s14": { average: { partOfSpeech: "n./adj. used substantively", contextualMeaning: "普通水平", use: "回扣全文中心：一般水准已经不够。" }, support: { partOfSpeech: "v.", contextualMeaning: "促进；支持", use: "support employment 指采取措施促进就业。" }, pass: { partOfSpeech: "gerund", contextualMeaning: "通过（法案）", use: "passing some kind of Bill 作 than 后的比较对象，说明最重要的措施。" }, access: { partOfSpeech: "n.", contextualMeaning: "接受教育的机会", use: "has access to education 不是物理入口，而是有机会接受教育。" }, education: { partOfSpeech: "n.", contextualMeaning: "高中后教育", use: "post-high school education 包括高中毕业后的继续教育。" },
  },
  "question-201321-prompt": { illustrate: { partOfSpeech: "v.", contextualMeaning: "说明；阐明", use: "问笑话在论证中用来说明什么。" } },
  "question-201321-option-C": { textile: { partOfSpeech: "adj.", contextualMeaning: "纺织业的", use: "textile 修饰 mills，说明选项讨论的是纺织厂。", preferredCollocations: ["textile mills（纺织厂）"] } },
  "question-201321-option-A": { impact: { partOfSpeech: "n.", contextualMeaning: "影响", use: "the impact of technological advances 指技术进步对用工的影响。" }, advance: { partOfSpeech: "n.", contextualMeaning: "进步；发展", use: "technological advances 与正文自动化和信息技术进步对应。" } },
  "question-201322-option-D": { contribute: { partOfSpeech: "v.", contextualMeaning: "贡献；提供价值", use: "contribute something unique 是 unique value contribution 的词性转换。" } },
  "question-201322-option-C": { average: { partOfSpeech: "adj.", contextualMeaning: "普通的；一般水平的", use: "average lifestyle 回指过去一般技能可获得的普通生活。" } },
  "question-201323-option-A": { gain: { partOfSpeech: "n.", contextualMeaning: "成果；增长", use: "选项故意写 technology gains；原文 gains 实际由岗位语境限定。" } },
  "question-201323-option-B": { opportunity: { partOfSpeech: "n.", contextualMeaning: "机会；岗位机会", use: "job opportunities 与原文 manufacturing jobs 对应。" }, speed: { partOfSpeech: "n.", contextualMeaning: "速度", use: "at a high speed 对应原文 so fast 和 acceleration。" } },
  "question-201324-option-D": { bill: { partOfSpeech: "n.", contextualMeaning: "法案", use: "more bills 偷换原文法案必须保证教育机会的内容。" } },
  "question-201324-option-C": { advance: { partOfSpeech: "v.", contextualMeaning: "推进；促进", use: "选项把推进全球化误写成减少失业的措施。" } },
  "question-201325-option-A": { law: { partOfSpeech: "n.", contextualMeaning: "法律", use: "New Law Takes Effect 暗示已有新法生效，而正文只是提出政策建议。" }, effect: { partOfSpeech: "n.", contextualMeaning: "效力；实施", use: "take effect 整体表示生效。" } },
  "question-201325-option-C": { average: { partOfSpeech: "n./adj. used substantively", contextualMeaning: "普通水平", use: "标题概括仅靠一般水平已经不够。" } },
};

const phraseRows: PhraseRow[] = [
  ["in-the-past", "In the past", "in the past", "时间搭配", "过去；从前", "作时间状语，与今天的情况形成对照。", "In the past, average skills were enough.", "过去，一般技能就够了。", "不是在过去某个物体内部。"],
  ["keep-away-from", "keep the man away from", "keep A away from B", "使役距离搭配", "使A远离B", "keep 后接宾语A，away from B说明不让A接近的对象。", "Keep children away from the machines.", "让孩子远离机器。", "不是让机器远离人，方向由宾语和from后对象决定。"],
  ["make-the-point", "making the point", "make the point that + clause", "观点表达搭配", "提出、强调某一观点", "point 后可接 that 从句展开观点内容。", "The report makes the point that skills matter.", "报告强调技能很重要。", "不是制作一个点。"],
  ["because-of", "because of", "because of + noun/doing", "原因介词结构", "因为；由于", "后接名词性成分；because 后接完整从句。", "Demand fell because of the recession.", "需求因经济衰退而下降。", "不要把 because of 后直接接完整谓语从句。"],
  ["replace-a-with-b", "replacing labor with machines or foreign workers", "replace A with B", "替代结构", "用B取代A", "A 是被替代者，B 是进入其位置的替代来源。", "Firms replaced routine labor with software.", "企业用软件取代重复劳动。", "方向不能读反。"],
  ["used-to", "used to", "used to + verb", "过去习惯或状态", "过去常常；过去曾经", "表示过去成立而现在通常不再成立；本文动词内容由上文省略。", "Average skills used to be enough.", "普通技能过去曾经够用。", "be used to doing 是习惯于，结构不同。"],
  ["access-to", "access to", "access to + noun", "机会与资源搭配", "获得、使用……的机会", "to 是介词，后接名词；语境决定是资源使用权还是教育机会。", "Workers need access to education.", "劳动者需要接受教育的机会。", "不能把 access 一律译成网络接入。"],
  ["stand-out", "stand out", "stand out in/from + group", "短语动词", "脱颖而出；显得突出", "out 表示从背景中突出，可接领域或群体。", "Her skills make her stand out.", "她的技能使她脱颖而出。", "不是站在外面。"],
  ["one-out-of-every", "one out of every three", "one out of every + number", "比例结构", "每……个中有一个", "分子为 one，every 后的数量给出分母。", "One out of every four jobs changed.", "每四个岗位中有一个发生变化。", "不要误读成只剩一个岗位。"],
  ["in-total", "in total", "in total", "合计搭配", "总计；合计", "用于把前述项目或比例换算为总数。", "Six million jobs disappeared in total.", "总计六百万个岗位消失。", "不表示每一年都六百万。"],
  ["for-sure", "for sure", "know for sure", "确定性搭配", "确定地；肯定", "修饰 know，表示作者认为这一点可以确定。", "We know for sure that requirements changed.", "我们可以确定要求发生了变化。", "不能把 sure 单独挂到 jobs。"],
  ["require-somebody-to", "require workers to have", "require somebody to do", "动词复合结构", "要求某人做某事", "somebody 是不定式动作的执行者。", "Good jobs require workers to learn.", "好工作要求劳动者学习。", "require doing 可表示某事需要被做，结构不同。"],
  ["have-access-to", "has access to", "have access to + noun", "机会搭配", "有机会获得或使用", "主语是拥有机会的人，to 后接资源或教育。", "Everyone should have access to education.", "每个人都应有接受教育的机会。", "不等于已经完成这项教育。"],
  ["post-high-school-education", "post-high school education", "post-high school education", "复合定语搭配", "高中后的继续教育", "post- 表示之后，整个复合定语限定 education。", "Post-high school education can include vocational training.", "高中后教育可包括职业培训。", "不能拆成“职位高的学校教育”。"],
  ["at-high-speed", "at a high speed", "at a high speed", "速度搭配", "以很快的速度", "在第23题中概括 so fast 和 acceleration。", "Jobs were disappearing at a high speed.", "岗位正迅速消失。", "只说明速度，不自动扩大到所有行业。"],
];
const phrases = reviewedPhrases(phraseRows);
export const passage2013P1PhraseGuides = phrases.guides;
export const passage2013P1PhraseAliases = phrases.aliases;
export const passage2013P1PhraseGlosses = phrases.glosses;
