import { reviewedLexicon, type LexiconRow, type ReviewedEntry } from "./2011-content-helpers";

const rows: LexiconRow[] = [
  ["advantage", "advantages", "n.", "优势；有利条件", "advantages of electronic money 指电子货币相对纸质支付的优势。", "an advantage of something（某事物的优势）", "benefit 侧重带来的好处；advantage 还含相对有利地位。"],
  ["prediction", "predictions", "n.", "预测；预言", "predictions have been around 表示有关无现金社会的预测存在已久。", "make a prediction（作出预测）", "forecast 常用于天气或数据趋势；prediction 范围更广。"],
  ["slow", "slower slowest", "adj.", "缓慢的；迟来的", "slow in coming 表示迟迟没有到来。", "be slow in coming（迟迟到来）", "late 强调超过预定时间；slow 强调过程进展缓慢。"],
  ["telecommunications", "", "n. used attributively", "电信；远程通信", "telecommunications networks 指支持电子支付的数据通信网络。", "telecommunications networks（通信网络）", "communication 更宽泛；telecommunications 特指远距离电子通信。"],
  ["network", "networks", "n.", "网络；系统", "本句指连接计算机与读卡器的通信网络。", "a computer network（计算机网络）", "web 多指万维网；network 可指设备、人员或组织连接体系。"],
  ["receipt", "receipts", "n.", "收据；付款凭证", "纸质支票能提供可保存的付款凭证。", "provide a receipt（提供收据）", "bill 是应付账单；receipt 证明已经收到款项。"],
  ["unwilling", "", "adj.", "不愿意的", "be unwilling to give up 表示消费者不愿放弃收据优势。", "be unwilling to do（不愿做）", "reluctant 也表示不情愿，常强调勉强与犹豫。"],
  ["float", "floats floated floating", "n.", "浮存期；扣款前的时间差", "支票语境中的 float 是开票后到实际扣款之间的几天。", "check float（支票浮存期）", "此处不是漂浮动作，也不是饮料上的冰淇淋。"],
  ["meantime", "", "n.", "期间；与此同时", "in the meantime 指支票兑现前的几天中。", "in the meantime（在此期间）", "meanwhile 可作副词；meantime 常用于固定介词短语。"],
  ["fourth", "", "ordinal/adv.", "第四；第四点", "Fourth 引出安全与隐私这一最后一类原因。", "First ... Fourth ...（第一……第四……）", "four 是基数四；fourth 表示顺序第四。"],
  ["uncommon", "", "adj.", "不常见的；罕见的", "not uncommon 是双重否定，表示并不少见。", "not uncommon（并不少见）", "rare 直接表示稀少；not uncommon 语气更委婉。"],
  ["fraud", "frauds", "n.", "欺诈；诈骗", "this type of fraud 指非法进入电子账户并盗取资金。", "prevent fraud（防止欺诈）", "cheating 更口语且范围广；fraud 常指经济或身份欺诈。"],
  ["field", "fields", "n.", "领域；学科分支", "a new field of computer science 指计算机科学的新研究领域。", "a field of study（研究领域）", "本文不是田地或运动场。"],
  ["cope", "copes coped coping", "v.", "应对；处理", "cope with security issues 表示设法处理安全问题。", "cope with a problem（应对问题）", "solve 强调解决完成；cope with 强调应付和处理。"],
  ["trail", "trails trailed trailing", "n.", "轨迹；可追踪记录", "electronic trail 指支付活动留下的电子记录链。", "leave an electronic trail（留下电子轨迹）", "path 是一般路径；trail 更强调沿途留下的痕迹。"],
  ["contain", "contains contained containing", "v.", "包含；容纳", "that contains ... data 说明电子轨迹中保存个人数据。", "contain personal data（包含个人数据）", "include 常列举部分；contain 可说明内部容纳内容。"],
  ["employer", "employers", "n.", "雇主；用人单位", "雇主是可能访问个人支付数据的主体之一。", "employers and marketers（雇主和营销人员）", "employee 是雇员，不能混用。"],
  ["marketer", "marketers", "n.", "营销人员；营销机构", "marketers 可能利用个人支付数据进行营销。", "online marketers（网络营销人员）", "market 作动词是推销；marketer 指从事营销的人或机构。"],
  ["thereby", "", "adv.", "从而；由此", "thereby violating privacy 表示访问数据可能造成的结果。", "thereby doing（从而做）", "therefore 引完整结果判断；thereby 常直接接分词。"],
  ["resist", "resists resisted resisting", "v.", "抵抗；抗拒", "本题为 reverse 的干扰项，resist itself 不能表示杂志后来改口。", "resist change（抵制变化）", "reverse 是反转立场；resist 是阻止外来作用。"],
  ["resume", "resumes resumed resuming", "v.", "恢复；继续", "本题为 reverse 的干扰项，未说明杂志恢复原预测。", "resume work（恢复工作）", "continue 是持续不停；resume 指中断后重新开始。"],
  ["silent", "", "adj.", "沉默的；无声的", "silent in coming 不能表达进程迟缓，是第5题干扰项。", "remain silent（保持沉默）", "quiet 表示安静；silent 更强调没有声音或不发言。"],
  ["sudden", "", "adj.", "突然的", "与预测二十年仍未实现的语境相反。", "a sudden change（突然变化）", "rapid 强调速度快；sudden 强调发生意外而突然。"],
  ["steady", "steadier steadiest", "adj.", "稳定的；持续的", "steady in coming 不能突出无现金社会迟迟未到。", "steady growth（稳定增长）", "stable 偏状态稳定；steady 还可指持续均匀。"],
  ["temporary", "", "adj.", "临时的；暂时的", "电子货币的目标是成为 dominant 而非 temporary 支付形式。", "a temporary measure（临时措施）", "permanent 与之相反；dominant 强调主导地位。"],
  ["collect", "collects collected collecting", "v.", "收集；领取", "collect receipts 是收集收据，不是支票自身提供收据。", "collect receipts（收集收据）", "provide 是提供；collect 是把已有物品收集起来。"],
  ["copy", "copies copied copying", "v.", "复制；抄写", "copy receipts 需要已有原件，不符合支票提供凭证的逻辑。", "copy a document（复制文件）", "print 是打印；copy 强调制作副本。"],
  ["print", "prints printed printing", "v.", "打印；印刷", "本题中支票的优势是提供收据，不要求现场打印。", "print a receipt（打印收据）", "provide 侧重给予；print 只说明制作方式。"],
  ["unsafe", "", "adj.", "不安全的", "not unsafe 表示并非不安全，不能说明事件发生频率。", "an unsafe system（不安全的系统）", "insecure 也可指系统不安全；unsafe 范围更广。"],
  ["adapt", "adapts adapted adapting", "v.", "适应；调整", "adapt to security issues 只表示适应，弱于主动应对风险。", "adapt to change（适应变化）", "cope with 强调应付困难；adapt to 强调改变自己以适应。"],
  ["chunk", "chunks", "n.", "大块；一段数据", "chunk 不强调支付活动留下的可追踪记录。", "a chunk of data（一块数据）", "trail 是连续痕迹；chunk 是相对独立的一块。"],
  ["chip", "chips", "n.", "芯片；小片", "电子支付留下的是数据轨迹，不是实体芯片。", "a computer chip（计算机芯片）", "chip 是硬件元件；trail 是可追踪记录。"],
  ["cashless", "", "adj.", "无现金的", "cashless society 指所有支付以电子方式完成的社会。", "a cashless society（无现金社会）", "cash-free 含义相近；cashless 更常用于支付体系。"],
  ["fruition", "", "n.", "实现；成果", "come to fruition 表示计划或预测成为现实。", "come to fruition（成为现实）", "result 是一般结果；fruition 强调努力或设想最终实现。"],
  ["revolutionize", "revolutionizes revolutionized revolutionizing", "v.", "彻底改变；使发生革命性变化", "引文说电子支付会彻底改变货币概念。", "revolutionize a system（彻底改变一个体系）", "reform 偏改革改良；revolutionize 语气更强。"],
  ["cash", "cashes cashed cashing", "v.", "兑现（支票）", "a check is cashed 表示支票被兑现。", "cash a check（兑现支票）", "withdraw 是从账户取款；cash 特指把票据换成可用资金。"],
  ["issuer", "issuers issuer's", "n.", "出票人；发行方", "issuer's account 指开出支票者的账户。", "the issuer's account（出票人账户）", "recipient 是收款人；issuer 是签发票据的一方。"],
  ["immediate", "", "adj.", "即时的；立刻发生的", "electronic payments are immediate 指支付和扣款立即发生。", "an immediate payment（即时支付）", "important 是重要的，与 immediate 不同。"],
  ["unauthorized", "", "adj.", "未经授权的", "an unauthorized hacker 指没有合法访问权限的黑客。", "unauthorized access（未授权访问）", "illegal 强调违法；unauthorized 强调未获许可。"],
  ["alter", "alters altered altering", "v.", "改动；篡改", "黑客 alter information 指擅自改变数据库信息。", "alter information（篡改信息）", "change 中性；alter 在安全语境可突出未经许可的修改。"],
  ["store", "stores stored storing", "v.", "存储；保存", "information stored there 是存放在数据库中的信息。", "store data（存储数据）", "save 也可保存；store 强调长期放置和保管。"],
  ["occurrence", "occurrences", "n.", "事件；发生的事情", "not an uncommon occurrence 表示这类入侵并不少见。", "a common occurrence（常见事件）", "event 可指安排好的大事；occurrence 强调发生的事情。"],
  ["steal", "steals stole stolen stealing", "v.", "偷窃；盗取", "steal from someone else's account 表示从他人账户盗取资金。", "steal from an account（从账户盗取）", "rob 通常以人或地点作宾语；steal 常以物作宾语或接from。"],
  ["else", "else's", "adj./adv.", "别的；其他人的", "someone else's accounts 表示其他人的账户。", "someone else's account（别人的账户）", "other 通常修饰名词；else 跟在不定代词后。"],
  ["prevention", "", "n.", "预防；防止", "the prevention of fraud 指防止电子账户欺诈。", "the prevention of fraud（防止欺诈）", "protection 是保护；prevention 强调使事情不发生。"],
  ["moreover", "", "adv.", "此外；而且", "第1题干扰项，不能连接前后相反判断。", "Moreover, ...（此外……）", "however 表转折；moreover 表同向递进。"],
  ["imaginative", "", "adj.", "富有想象力的", "不能说明建设电子支付网络的成本，是第7题干扰项。", "an imaginative idea（富有想象力的想法）", "imaginary 是想象出来的；imaginative 形容富有创意。"],
  ["sensitive", "", "adj.", "敏感的；灵敏的", "原文谈网络建设成本，并非设备是否灵敏。", "sensitive information（敏感信息）", "sensible 是明智的，不能混淆。"],
  ["productive", "", "adj.", "有成效的；多产的", "不能解释基础设施成为无现金化阻碍。", "a productive system（高效产出的系统）", "efficient 侧重投入产出效率；productive 侧重产出多。"],
  ["original", "", "adj.", "最初的；原创的", "电子货币不是要成为最初的支付形式，是第8题干扰项。", "the original form（最初形式）", "dominant 指主导；original 指时间或来源上的最初。"],
  ["borrow", "borrows borrowed borrowing", "v.", "借入；借用", "funds are borrowed 表示资金被借入，不符合出票人账户扣款。", "borrow money（借钱）", "lend 是借出，方向相反。"],
  ["analyze", "analyzes analyzed analyzing", "v.", "分析", "information analyzed there 只说明分析，不能概括信息存储状态。", "analyze data（分析数据）", "store 是保存；analyze 是研究内容。"],
  ["display", "displays displayed displaying", "v.", "显示；展示", "displayed 不能保证信息被数据库长期存储。", "display information（显示信息）", "show 更普通；display 常指在屏幕或公开场合呈现。"],
  ["unnatural", "", "adj.", "不自然的；反常的", "not unnatural 不说明黑客事件发生频率。", "an unnatural reaction（反常反应）", "uncommon 指不常见，属于频率判断。"],
  ["manipulation", "manipulations", "n.", "操纵；篡改", "欺诈的操纵行为不是防范欺诈这一任务。", "data manipulation（数据操纵）", "prevention 是阻止；manipulation 是控制或改动。"],
  ["justification", "justifications", "n.", "正当理由；辩解", "fraud 的 justification 不能表达治理任务。", "provide a justification（给出理由）", "explanation 解释原因；justification 强调证明合理。"],
  ["path", "paths", "n.", "道路；路径", "path 缺少电子活动留下可追踪痕迹的含义。", "follow a path（沿路径前进）", "trail 可指路径，也强调沿途留下的痕迹。"],
];

const reviewed = reviewedLexicon(rows);
export const cloze2013Lexicon: Record<string, ReviewedEntry> = reviewed.entries;
export const cloze2013LemmaAliases: Record<string, string> = { ...reviewed.aliases };
export const cloze2013FormPartOfSpeech: Record<string, string> = Object.fromEntries(rows.flatMap(([headword, forms, pos]) => [[headword, pos], ...forms.split(" ").filter(Boolean).map(form => [form, pos])]));
