import type { SentenceWordContext } from "./contextual-vocabulary";
import { reviewedLexicon, reviewedPhrases, type LexiconRow, type PhraseRow } from "./2011-content-helpers";
const rows: LexiconRow[] = [
 ["accommodate","accommodates accommodated accommodating","v.","适应；容纳","接纳人员流动的新现实，需要争论双方改变态度。","accommodate change（适应变化）","adapt强调自身调整；accommodate也强调为多样情况留出空间。"],
 ["adapt","adapts adapted adapting","v.","适应；调整","第27题被动式should be adapted表示制度应调整。","adapt to change（适应变化）","adapt调整以适应；adopt是采用。"],
 ["affectionate","","adj.","亲切的；充满感情的","修饰nickname，说明候鸟绰号带亲切色彩。","an affectionate nickname（亲切的绰号）","affection是感情；affected可指做作的，不能混同。"],
 ["aide","aides","n.","助手；护理员","home health-care aides是提供居家护理的工作人员。","a health-care aide（护理员）","aide指人，aid可指帮助本身。"],
 ["alien","aliens","n.","外国人","被贴上应驱逐者的身份标签，不是外星人。","an alien resident（外籍居民）","此处alien带划分内外身份的色彩；foreigner更一般。"],
 ["american","americans","n.","美国人","in the making说正在成为美国人的过程。","an American citizen（美国公民）","American也可作形容词；本句复数形式为人。"],
 ["atlantic","","proper n.","大西洋","across the Atlantic说明跨大西洋来到美国的路线。","the Atlantic Ocean（大西洋）","大洋名称通常与the连用；只需识别地点。"],
 ["battle","battles","n.","争论；斗争","immigration battle指移民政策之争，不是实际战争。","a political battle（政治争论）","debate侧重讨论，battle比喻双方激烈对立。"],
 ["brand","brands branded branding","v.","给……贴标签；把……称为","brand them as aliens表示给移民贴上排斥性的身份标签。","brand A as B（把A称作B）","brand作名词是品牌；此处作动词常带贬义评价。"],
 ["broken","","adj.","失灵的；有问题的","broken immigration system指运作不良的制度，不是物体破碎。","a broken system（失灵的制度）","broken在此为形容词状态；修复对象是制度。"],
 ["challenge","challenges challenged challenging","n.","挑战；难题","immigration challenges指需要解决的移民管理难题。","meet a challenge（应对挑战）","challenge既可指挑战也可作质疑动词；本处为复数名词。"],
 ["commit","commits committed committing","v.","承诺；使承担义务","commit themselves to staying表示承诺留下；without否定这个承诺。","commit oneself to doing（承诺做某事）","to是介词，后接doing；不等于commit a crime的犯下义。"],
 ["construction","constructions","n.","建筑；建造","construction workers指建筑工人，不是法律解释。","construction workers（建筑工人）","construct建造；construction还可指句法结构，须按名词搭配区分。"],
 ["contribute","contributes contributed contributing","v.","促成；有助于","contributed to连接僵化框架与制度失灵，含不良结果。","contribute to a problem（促成问题）","contribute to不保证结果有益，不能一律译为积极贡献。"],
 ["crop","crops","n.","农作物","crop pickers是采摘农作物的人。","crop production（农作物生产）","本处名词作定语；crop up才是突然出现。"],
 ["definition","definitions","n.","定义；判定标准","strict definitions指对合法和非法的严格界定。","a strict definition（严格的定义）","definition是界定内容，category是类别。"],
 ["di","","外语介词","意大利语中的“的”","uccelli di passaggio是完整绰号，后面的birds of passage给出英文解释。","uccelli di passaggio（候鸟）","仅识别这段意大利语，不作为普通英语词义背诵。"],
 ["divide","divides divided dividing","v.","划分；分成","divide newcomers into two categories表示按两类划分。","divide A into B（把A分成B）","divide作名词可指分歧；本句是动词。"],
 ["ease","","n.","轻松；自如","with ease整体作方式状语，说明跨越边界得心应手。","with ease（轻松地）","ease作动词可指减轻，此处介词后为名词。"],
 ["energetic","","adj.","精力充沛的；积极的","energetic participants表示积极参与经济的人。","an energetic participant（积极的参与者）","energetic说活力；energy是名词。"],
 ["engineer","engineers engineered engineering","n.","工程师","职业列举中的工程师。","a software engineer（软件工程师）","engineer也可作策划动词，此处复数名词指人。"],
 ["entrepreneur","entrepreneurs","n.","企业家；创业者","移民职业清单包括创业经营者。","a successful entrepreneur（成功的企业家）","entrepreneur强调创办经营企业，不等于普通雇员。"],
 ["exist","exists existed existing","v.","存在","existing修饰system，指现行制度。","the existing system（现行制度）","existing表示当前存在，不能从中推断制度合理。"],
 ["faithful","","adj.","忠诚的；忠实的","faithful partners是第29题增加的关系判断。","a faithful partner（忠诚的伙伴）","honorably表示正当地，不自动等于faithful。"],
 ["favor","favors favored favoring","n.","优待；好处","economic favors指额外经济利益，原文未提出。","economic favors（经济优待）","favor作动词可指支持；本选项是复数名词。"],
 ["fix","fixes fixed fixing","v.","修复；解决","fix it中的it指失灵的移民制度。","fix a problem（解决问题）","fix有固定和确定义，此处对应broken，取修复义。"],
 ["flow","flows flowed flowing","n.","流动","工作、资金、思想的跨地流动推动全球经济。","the flow of money（资金流动）","flow可指连续流动，不只指水流或气流。"],
 ["folk","folks","n.","人们","many folks是许多普通人，较口语。","ordinary folks（普通人）","folk也可作民间的；folks在此是人们。"],
 ["framework","frameworks","n.","框架；思维体系","That framework回指合法/非法和好/坏的二分方式。","a conceptual framework（概念框架）","framework在此是抽象思维结构，不是实体支架。"],
 ["gray","","adj.","灰色的；界限不清的","gray areas比喻难以按两类清楚划定的地带。","gray areas（灰色地带）","gray和grey是两种拼写；此处不是实际颜色。"],
 ["ground","grounds","n.","立场；共同基础","middle ground是极端立场之间可协调的空间。","middle ground（中间立场）","ground也可指地面；此处和middle组成比喻搭配。"],
 ["hail","hails hailed hailing","v.","称赞；赞扬","hail them as Americans表示欢迎并称他们为未来美国人。","hail A as B（称赞A为B）","praise强调称赞；hail常带公开、热烈认可的语气。"],
 ["health-care","","adj.","医疗保健的","home health-care aides指提供居家保健护理的人员。","health-care services（医疗保健服务）","health care名词短语加连字符后可整体修饰名词。"],
 ["honorably","","adv.","正当地；光明正大地","说明双重国家归属可以是正当而不羞耻的。","act honorably（光明正大地行事）","不是仅仅得到名声，而是行为或身份具有正当性。"],
 ["identity","identities","n.","身份","跨越不同国家和法律环境中的身份边界。","national identity（国家身份认同）","identity可指身份或认同，不能一律译成身份证件。"],
 ["immigrant","immigrants","n.","移民","本文指从别国来到美国的人，包含长期定居和暂住者。","immigrant communities（移民群体）","immigrant从迁入国角度说；emigrant从迁出国角度说。"],
 ["immigrate","immigrates immigrated immigrating","v.","移居入境","第26题说跨大西洋迁入，但这不足以定义候鸟式移民。","immigrate to a country（移居某国）","emigrate from从某国移出；介词与观察方向不同。"],
 ["incentive","incentives","n.","激励；刺激因素","financial incentives是金钱方面的激励，并非原文所说的自由去留。","financial incentives（经济激励）","opportunity是机会，incentive是促使行动的诱因。"],
 ["intention","intentions","n.","意图；打算","no intention to stay明确没有长期留下的打算。","have no intention to do（无意做某事）","intention说意图，不等于已经发生的结果。"],
 ["italian","italians","adj.","意大利的","Italian immigrants是来自意大利的移民。","Italian immigrants（意大利移民）","国籍形容词在英文中需大写。"],
 ["italy","","proper n.","意大利","移民最终返回的祖国。","return to Italy（回到意大利）","国家专名，仅需识别地点。"],
 ["jurisdiction","jurisdictions","n.","司法管辖权；管辖区","与laws和identities并列，指跨国流动涉及的不同管辖范围。","under a jurisdiction（在某管辖权下）","jurisdiction是权限或管辖范围，不等同于一条具体法律。"],
 ["kick","kicks kicked kicking","v.","踢；驱逐","kick out整体意为赶出去；be kicked out是被驱逐。","kick somebody out（把某人赶出去）","不可把字面踢腿动作当成本句主旨，应整体识别kick out。"],
 ["logic","","n.","逻辑；思维方式","right or wrong的逻辑指非对即错的二分判断。","the logic of an argument（论证的逻辑）","logical是形容词，logic是名词。"],
 ["look","looks looked looking","v.","看待；考虑","look beyond表示看问题时超越既有限制。","look beyond appearances（超越表象看问题）","本处不是系动词look加形容词的看起来。"],
 ["loosen","loosens loosened loosening","v.","放松；松开","loosened control是第27题没有原文依据的管控变化。","loosen control（放松控制）","loosen是动词；loose是松的，lose是失去。"],
 ["mightily","","adv.","极大地；强有力地","修饰contributed，强调僵化框架的显著负面影响。","contribute mightily（起很大作用）","much more普通；mightily强调程度或力量。"],
 ["mighty","mightier mightiest","adj.","强大的；有力的","mighty rivals是强劲对手，非作者对移民的定位。","a mighty rival（强劲对手）","mighty为形容词，mightily为副词。"],
 ["mistake","mistakes mistook mistaken","n.","错误","标题说Big Mistake是在批评二分思维。","make a mistake（犯错误）","mistake也可作误认动词；本文标题使用名词。"],
 ["motion","motions","n.","运动；流动","people in motion指不断迁移流动的人。","in motion（在运动中）","motion此处不是议会动议。"],
 ["nation","nations","n.","国家；民族","two nations说明可能同时具有两个国家的归属。","belong to two nations（归属于两个国家）","nation重国家或民族共同体，national为形容词。"],
 ["newcomer","newcomers","n.","新来者","本文特指新迁入的人。","welcome newcomers（欢迎新来者）","newcomer不限移民，具体范围由本文语境决定。"],
 ["nickname","nicknames nicknamed nicknaming","n.","绰号；昵称","候鸟是暂居移民的亲切绰号。","an affectionate nickname（亲切的绰号）","nickname与正式姓名不同。"],
 ["open","opens opened opening","v.","开拓；打开","opening up the middle ground是打开两极之间的讨论空间。","open up possibilities（开辟可能性）","open up可为抽象开放，不只开门。"],
 ["outcome","outcomes","n.","结果","multiple outcomes与multiple paths并列，说明不能只有一种定居结局。","possible outcomes（可能的结果）","path是路径，outcome是结果，不能混成两个同义词。"],
 ["paralysis","","n.","瘫痪；僵局","political paralysis比喻政治上无法推进解决方案。","political paralysis（政治僵局）","并非医学瘫痪，而是借指行动能力受阻。"],
 ["participant","participants","n.","参与者","这些移民积极参与全球经济。","active participants（积极参与者）","participate为动词；participant为参与的人。"],
 ["passage","passages","n.","迁移；通过","birds of passage整体比喻迁徙的候鸟，本文指暂住再回流的移民。","birds of passage（候鸟；流动移民）","passage在题型标题里可指文章，本搭配中不是段落。"],
 ["passaggio","","外语名词","意大利语中的“通行；迁移”","uccelli di passaggio在此由birds of passage解释。","uccelli di passaggio（候鸟）","原文意大利语只需识别，不并作英语passage的屈折变化。"],
 ["path","paths","n.","途径；道路","multiple paths指管理移民的多种途径。","multiple paths（多种途径）","途径是实现方式，不是最终结果outcome。"],
 ["permanent","","adj.","永久的；长期的","与sojourner和temporarily对照；permanent home是长期安家。","a permanent home（永久的家）","permanent长期稳定，temporary暂时。"],
 ["permission","","n.","许可；允许","With or without permission说明可能获得或未获制度许可。","with permission（经许可）","permission通常不可数；不等于获得全球认可recognition。"],
 ["physicist","physicists","n.","物理学家","列举候鸟式移民中的科研职业。","a theoretical physicist（理论物理学家）","physicist物理学家，physician医生。"],
 ["picker","pickers","n.","采摘工；采摘者","crop pickers是从事农作物采摘的工人。","crop pickers（农作物采摘工）","pick为动作，picker为实施者；不合并为一个原形。"],
 ["productive","","adj.","有生产力的；能有所贡献的","短期在美国工作也可以创造价值，不必永久留下。","productive work（有成效的工作）","productive说明能产生成果，不是被生产出来的produced。"],
 ["recognition","","n.","认可；承认","global recognition出现在干扰项中，原文没有把它列为诉求。","gain recognition（获得认可）","recognition还可指辨认，本选项指认可。"],
 ["refer","refers referred referring","v.","指的是；提到","refers to询问birds of passage的所指。","refer to（指的是）","本题不是把某人转介到别处。"],
 ["regular","","adj.","固定的；常规的","regular jobs把工作限定为固定工作，是选项添加的限制。","a regular job（固定工作）","regular有定期或普通义，具体由所修饰名词决定。"],
 ["return","returns returned returning","v.","返回；回到","returned to Italy说明永久返回祖国，而非永久离开。","return to a country（返回某国）","return本身已有回的方向，不必再加back。"],
 ["rival","rivals rivaled rivalling","n.","竞争对手","mighty rivals是强劲竞争者，不是作者要求对待移民的方式。","a political rival（政治对手）","partner伙伴与rival对手角色不同。"],
 ["settler","settlers","n.","定居者","与暂居者sojourners并列，说明移民去留方式不同。","permanent settlers（永久定居者）","settle定居；settler指人；sojourner暂居者。"],
 ["side","sides","n.","一方；一边","both sides指移民争论的双方，不仅是国境两侧。","both sides of a debate（争论双方）","side可指阵营或立场，不必是空间左右。"],
 ["sojourner","sojourners","n.","暂居者","只打算住一段时间，赚钱后回家的移民。","a temporary sojourner（暂居者）","与settler长期定居形成对照；属于识别即可的低频词。"],
 ["stay","stays stayed staying","v.","停留；留下","是否永远stay决定定居与暂居的区别。","stay temporarily（暂时停留）","stay保留居留状态，leave是离开。"],
 ["straddle","straddles straddled straddling","v.","跨越；横跨","跨越不同法律、管辖权和身份边界。","straddle borders（跨越边界）","本处由骑跨的字面义引申为同时处于不同领域。"],
 ["thrive","thrives thrived thriving","v.","兴旺；发展良好","living and thriving表示不仅生存，还能发展。","thrive in a new environment（在新环境中发展良好）","survive强调活下来，thrive强调发展好。"],
 ["today","today's","adv./n.","今天；当今","today's作所有格限定birds of passage，表示当代的。","today's immigrants（当今的移民）","此处与一个世纪前比较，today指当代，不限当天。"],
 ["uccelli","","外语名词","意大利语中的“鸟”","完整表达uccelli di passaggio紧接英文birds of passage。","uccelli di passaggio（候鸟）","只作原文外语绰号识别，不与bird原形合并计数。"],
 ["us","","国名缩写","美国","第27题in the US中的US是United States，不是we的宾格。","in the US（在美国）","US国名缩写与小写us代词必须按来源区分。"],
 ["violinist","violinists","n.","小提琴手","与农工、工程师等并列，体现流动者职业多样。","a professional violinist（职业小提琴手）","violin为乐器，violinist为演奏者。"],
 ["good","better best","adj.","好的；良好的","good or bad表示把移民按道德好坏分类。","good or bad（好或坏）","for good整体表示永久，不能逐词套好的。"],
 ["get","gets got gotten getting","v.","获得；取得","get regular jobs指取得固定工作。","get a job（找到工作）","get有多义，get over才是克服；这里直接接job。"],
 ["leave","leaves left leaving","v.","离开","leave their home countries指离开祖国，与stay对照。","leave a country（离开某国）","此处不表示留下某物；宾语是离开的地点。"],
 ["work","works worked working","n.","工作；劳动","flow of work是工作和劳动机会的流动。","the flow of work（工作的流动）","本句与money/ideas并列，不能用动词起作用解释。"],
 ["understand","understands understood understanding","v.","理解；认识","understanding后接that从句，理解移民管理需要多样路径。","understand a problem（理解问题）","understanding在此为动名词，仍保留宾语从句。"],
 ["mean","means meant meaning","v.","意味着；表示","末句means连接一种观念改变及其含义。","mean doing（意味着做某事）","mean to do是打算做；means名词才是手段。"],
];
const lex=reviewedLexicon(rows);
export const passage2013P2Lexicon=lex.entries;
export const passage2013P2LemmaAliases:Record<string,string>={...lex.aliases,us:"us",means:"means"};
export const passage2013P2SentenceContexts:Record<string,Record<string,SentenceWordContext>>={
 "2013-p2-s1":{immigrant:{partOfSpeech:"n.",contextualMeaning:"移民",use:"包含settlers和sojourners两类移居者。"}},
 "2013-p2-s2":{along:{partOfSpeech:"固定搭配成分",contextualMeaning:"构成along with，表示伴随",use:"along with引出与暂居者一起到来的定居者。"},with:{partOfSpeech:"prep.",contextualMeaning:"与……一起；伴随着",use:"沿用along with整体的伴随关系，后面不是came的主语。"},look:{partOfSpeech:"v.",contextualMeaning:"寻求；打算",use:"looking to make a permanent home表示希望长期安家。"},make:{partOfSpeech:"v.",contextualMeaning:"建立；赚取",use:"make a home指安家；同句make some money则为赚钱，两个make保持各自搭配。"}},
 "2013-p2-s4":{good:{partOfSpeech:"固定搭配成分",contextualMeaning:"构成for good，表示永久",use:"for good整体修饰returned，不把good另造为单词的永久义。"}},
 "2013-p2-s8":{make:{partOfSpeech:"n.",contextualMeaning:"形成；发展过程",use:"in the making指尚在形成中，说明可能成为美国人。"},as:{partOfSpeech:"prep.",contextualMeaning:"作为；被视为",use:"hail/brand them as后接所赋予的身份。"}},
 "2013-p2-s10":{change:{partOfSpeech:"v.",contextualMeaning:"改变",use:"change的宾语是思考分类的方式，不是增加类别。"}},
 "2013-p2-s14":{home:{partOfSpeech:"n.作定语",contextualMeaning:"家；家庭",use:"home修饰health-care，说明居家提供护理。"}},
 "2013-p2-s15":{drive:{partOfSpeech:"v.",contextualMeaning:"推动；驱动",use:"driven by作后置定语，说明全球经济的推动来源。"}},
 "2013-p2-s16":{call:{partOfSpeech:"v.",contextualMeaning:"召唤；吸引",use:"把机会拟人化为召唤他们的人，表示随工作机会往返。"},as:{partOfSpeech:"conj.",contextualMeaning:"随着；当……时",use:"机会到来时决定去留，连接行动与机会。"}},
 "2013-p2-s17":{place:{partOfSpeech:"n.",contextualMeaning:"地方；位置",use:"工作与家庭可以分处两地。"},manage:{partOfSpeech:"v.",contextualMeaning:"设法做到",use:"manage to have表示能够安排异地工作与家庭。"},one:{partOfSpeech:"num.",contextualMeaning:"一；一个",use:"one place与another相对，表示两处不同地方。"}},
 "2013-p2-s19":{place:{partOfSpeech:"n.",contextualMeaning:"地方；位置",use:"把美国看作可以暂时参与生产的地方。"},while:{partOfSpeech:"n.",contextualMeaning:"一段时间",use:"for a while整体表示暂时，while在介词后为名词。"},themselves:{partOfSpeech:"reflexive pron.",contextualMeaning:"他们自己",use:"回指them所指的候鸟式移民，是作出居留承诺的人。"}},
 "2013-p2-s20":{home:{partOfSpeech:"n.",contextualMeaning:"家；家庭",use:"home作从句主语，说明家的归属可以同时在两地。"},here:{partOfSpeech:"adv.",contextualMeaning:"在这里",use:"这里指美国，与there所指的另一祖国并列。"},there:{partOfSpeech:"adv.",contextualMeaning:"在那里",use:"here and there指美国与另一个祖国，不是there be存在句。"}},
 "2013-p2-s22":{mean:{partOfSpeech:"v.",contextualMeaning:"意味着；表示",use:"means的主语是Looking beyond整组，后接两个并列动名词宾语。"},manage:{partOfSpeech:"v.",contextualMeaning:"管理",use:"managing immigration整组作从句主语。"},right:{partOfSpeech:"adj.",contextualMeaning:"正确的",use:"right or wrong是对错二分，不是权利。"}},
 "question-201327-prompt":{us:{partOfSpeech:"proper n.",contextualMeaning:"美国",use:"US是United States的缩写，不是我们宾格us。"}},
 "question-201327-option-D":{means:{partOfSpeech:"n.",contextualMeaning:"手段；方法",use:"political means指政治手段，不是末句means的意味着动词。"}},
 "question-201330-option-B":{great:{partOfSpeech:"adj.",contextualMeaning:"巨大的；程度大的",use:"Great Risk是巨大风险，不是比较级更大。"}},
 "question-201330-option-C":{great:{partOfSpeech:"adj.",contextualMeaning:"巨大的；程度大的",use:"Great Risk是选项添加的巨大风险评价。"}},
 "question-201326-option-B":{good:{partOfSpeech:"固定搭配成分",contextualMeaning:"构成for good，表示永久",use:"该搭配在选项中修饰leave，和原文修饰returned的方向相反。"}},
 "question-201329-prompt":{suggest:{partOfSpeech:"v.",contextualMeaning:"建议；提议",use:"suggests that...should be treated问作者的建议，不是客观现象暗示。"}},
};
const phraseRows:PhraseRow[]=[
 ["along-with","Along with","along with + noun","伴随介词结构","与……一起","后接伴随对象，不自动成为主句主语。","Along with the workers came their families.","工人到来的同时，他们的家人也来了。","主谓一致看真正主语，不看with后的近处名词。"],
 ["no-intention","had no intention to stay","have no intention to do","意图结构","无意做某事","no否定intention，to do说明所谈的行为。","They had no intention to stay.","他们无意留下。","没有打算不等于客观上绝无可能。"],
 ["for-good","for good","for good","固定副词搭配","永久地","整体修饰离开、返回等动作，方向由动词决定。","She returned home for good.","她永久回到家乡定居。","不能译成为了好处。"],
 ["birds-of-passage","birds of passage","birds of passage","比喻名词搭配","候鸟；暂居的流动者","本篇比喻会迁来又返回的人。","These workers are birds of passage.","这些工人像候鸟一样来去。","不是所有移民都属于此类。"],
 ["divide-into","divide newcomers into two categories","divide A into B","分类结构","把A分成B","A是被分类对象，into后是分成的类别。","Divide the items into two groups.","把这些项目分为两组。","divide by常见于除法，不能与into混用。"],
 ["in-the-making","in the making","in the making","固定介词搭配","正在形成中","放在名词后说明其尚在发展形成。","She is a leader in the making.","她是正在成长中的领导者。","不等于已经成为。"],
 ["kick-out","kicked out","kick somebody out","短语动词","赶走；驱逐","out强调让某人离开；被动为be kicked out。","They were kicked out.","他们被赶了出去。","代词宾语在kick和out中间。"],
 ["look-beyond","look beyond","look beyond + noun","动词介词搭配","超越……来看问题","不要把判断局限在某一表面或现有框架。","Look beyond strict categories.","不要局限于严格的类别来看问题。","超越框架不等于否认一切规则。"],
 ["gray-areas","gray areas","gray areas","比喻名词搭配","灰色地带；模糊领域","指边界不清、难简单二分的情况。","The rule leaves gray areas.","这条规则留下了模糊地带。","不是实际颜色，也不自动断言全部违法。"],
 ["come-and-go","come and go","come and go","并列动词搭配","来来去去；往返","保留进入与离开两个方向。","They come and go with the seasons.","他们随季节往返。","不能只译成永久迁入。"],
 ["with-or-without","With or without","with or without + noun","并列介词结构","有无……都","同一个名词同时受with与without支配。","With or without permission, he left.","不论是否获准，他都离开了。","这是描述条件两面，不是给行为合法性背书。"],
 ["with-ease","with ease","with ease","方式搭配","轻松地；自如地","介词加名词整体作方式状语。","She solved the problem with ease.","她轻松解决了问题。","ease在此是名词，不是减轻的动词。"],
 ["2010-p1-for-a-while","for a while","for + duration","时间搭配","一段时间；暂时","for后名词while表示持续一段时间。","He stayed for a while.","他待了一阵子。","此处while不是而或当……时的连词。"],
 ["commit-to","committing themselves to staying","commit oneself to doing","承诺结构","承诺做某事","to是介词，后接doing；oneself回指承诺者。","They committed themselves to staying.","他们承诺留下。","不要把to当不定式标记而写to stay。"],
 ["belong-to","belong to","belong to + noun","归属搭配","属于；归属于","后接所属的人、群体或国家。","She belongs to two communities.","她归属于两个群体。","belong通常不用于被动语态。"],
 ["in-motion","in motion","in motion","状态搭配","在运动中；处于流动中","本文说人员跨地流动。","The population is in motion.","人口正在流动。","不是制定政治动议。"],
 ["open-up","opening up","open up + noun","短语动词","开辟；打开","可以指打开讨论和可能性空间。","The debate opened up new possibilities.","讨论开辟了新的可能。","抽象空间不需按实体门解释。"],
 ["middle-ground","middle ground","middle ground","比喻名词搭配","中间立场；折中空间","非黑即白两极之间可协调的立场。","They found middle ground.","他们找到了可协调的中间立场。","不是地理上的中间土地。"],
];
const phr=reviewedPhrases(phraseRows);
export const passage2013P2PhraseGuides=phr.guides;
export const passage2013P2PhraseAliases=phr.aliases;
export const passage2013P2PhraseGlosses={...lex.glosses,...phr.glosses};
