import type {ArticleGuide} from './article-teaching';
import {createV2Sentence,type QuickReading} from './article-v2/model';
import {reviewedBlocks} from './2013-reading-helpers';
import {texts,paragraphNumbers} from './2014-passage-3-source';
const rows:Array<[string,string,string,string[],QuickReading['keyReasons'],string[]]>=[
['人与机器对抗的观念至少和工业革命一样古老，但这种现象往往在经济衰退和脆弱复苏期间感受得最为强烈。','as old as比较历史；most acutely felt是被动，说明人们对冲突的感受更强，不是冲突首次出现。','提出人机竞争的长期背景及经济低迷时的突出表现。',['but this phenomenon'],['answer-evidence','main-line'],['at least as old as']],
['然而，如果以为我们眼下只是在经历繁荣与萧条周期中痛苦的一面，那就错了。','it是形式主语，真正主语是to think；simply限制为“仅仅”。','转折指出问题不只是普通经济周期。',['to think','simply experiencing'],['paragraph-turn','reference-or-scope'],['a boom and bust cycle']],
['有些工作已经永远消失，被机器淘汰了。','for good表示永久；outmoded by machines是过去分词补充消失原因。','说明技术带来的岗位消失具有永久性。',['outmoded'],['answer-evidence','misreading'],['for good']],
['由于技术对吞噬人类工作岗位有着永不满足的胃口，这种现象将继续以我们无法立即预见的方式重塑经济。','Since引出原因；ways后省略关系词that/in which，we cannot foresee修饰ways。','预测技术会持续改变就业和经济结构。',['this phenomenon','in ways'],['answer-evidence','nested-clause'],['an insatiable appetite for','eating up']],
['当技术的价格和性能迅速改善时，那些一度被认为不会受到自动化影响的工作，会突然面临威胁。','price improvement指成本更有利；that定语从句中的were thought被动，to be immune作主语补足语。','解释原本安全的岗位为何也会受到自动化冲击。',['jobs that','suddenly become'],['answer-evidence','nested-clause'],['be immune from']],
['这一论点因埃里克·布林约尔松和安德鲁·麦卡菲合著的《与机器赛跑》一书大获成功而受到广泛关注；两位作者都来自麻省理工学院数字商业中心。','via说明获得关注的途径；by短语说明作者；who回指两位作者。','交代该观点及其代表性著作。',['via the success','by Erik','who both'],['attachment'],['attracted a lot of attention','hail from']],
['这是一个有力的论点，也是一个令人害怕的论点。','one代替argument，避免重复；scary说明这一判断令人担忧。','承认“机器取代岗位”观点的力量和冲击。',[],[],[]],
['然而，《拉力》及其他著作的作者约翰·哈格尔说，布林约尔松和麦卡菲没有抓住这些工作最初为何如此容易受技术冲击的原因。','author of...是同位语；why从句修饰reason；in the first place追问根本原因。','转入Hagel的反驳：岗位设计才是脆弱性的原因。',['says Brynjolfsson','why these jobs'],['paragraph-turn','answer-evidence','nested-clause'],['in the first place']],
['哈格尔说，我们在美国设计出的工作往往是“严格照脚本执行”和“高度标准化”的那一类，不给“个人主动性或创造力”留下空间。','that tend...修饰ones，而ones指jobs；leave no room for明确排除主动性和创造力。','指出美国岗位设计抑制人的主动性与创造力。',['that tend','ones that'],['answer-evidence','nested-clause'],['leave no room for']],
['简言之，这些工作正是机器比人类做得好得多的类型。','that定语从句修饰jobs；perform much better at省略重复的performing these jobs。','说明标准化岗位天然适合机器。',['that machines'],['answer-evidence','misreading'],['In short']],
['哈格尔说，我们正是这样在美国工人背上放了一个巨大的靶标。','That回指把岗位设计得脚本化、标准化；target sign比喻工人易被机器取代。','用比喻总结这种岗位设计让工人成为替代目标。',['Hagel says'],['reference-or-scope','misreading'],['put a giant target sign on the backs of']],
['哈格尔说，我们仍依赖一种非常典型的20世纪工作观念，因此现在该重新设计工作如何开展的模式了。','It is time to...表示该做某事；how从句修饰formula；since引出必须改革的原因。','提出重新设计工作方式的主张。',['since we','Hagel says'],['main-line','nested-clause'],["It's time to",'relying on']],
['在快速变化的经济中，我们比以往任何时候都更需要这样的职场员工：他们能发挥主动性和想象力，“应对意外事件”。','more than ever修饰need；who定语从句说明people所需能力；to respond说明运用想象力的目的。','提出人类在未来工作中的独特价值。',['who can','"to respond'],['answer-evidence','attachment'],['take initiative','exercise their imagination','respond to']],
['这并不是机器擅长的事情。','That回指运用主动性和想象力应对意外事件；be good at后接擅长对象。','明确人类优势不在机器能力范围内。',[],['answer-evidence','reference-or-scope'],['machines are good at']],
['机器被设计用来执行非常可预测的活动。','被动are designed强调机器的设计用途；predictable与unexpected形成对比。','解释机器适合标准化任务的原因。',[],['answer-evidence'],['are designed to']],
['正如哈格尔所指出的，布林约尔松和麦卡菲在书中确实谈到了这一点。','As引出观点来源；this point回指机器应增强人类而不是简单替代的讨论方向。','承认前述作者也涉及了人机协作。',['Brynjolfsson'],['answer-evidence','reference-or-scope'],['touched on']],
['我们需要把“与机器对抗的竞赛”重新表述为“同机器协作的竞赛”。','reframe A as B表示重新界定；against与with形成核心对比。','提出全文解决方向：从对抗转向协作。',[],['main-line','answer-evidence'],['reframe race against the machine as race with the machine']],
['换句话说，我们需要研究机器能够增强而不是取代人类劳动的方式。','in which修饰ways；rather than连接augment和replace，保持动作对象human labor相同。','具体解释“与机器协作”的含义。',['in which','rather than'],['answer-evidence','nested-clause'],['In other words','rather than']],
['那么，问题其实并不在技术本身，而在于“我们该如何创新制度和工作实践？”','not...but rather...纠正问题焦点；引号内how疑问句提出制度改革任务。','以制度与工作实践创新收束全文。',['but rather'],['paragraph-turn','main-line'],['not really about technology, but rather']],
];
export const sentences=texts.map((text,i)=>{const[natural,obstacle,logic,starts,keyReasons,phrases]=rows[i];return createV2Sentence({id:`2014-p3-s${i+1}`,number:i+1,text,natural,logic,phrases,quickReading:{blocks:reviewedBlocks(text,starts),obstacle,keyReasons}});});
sentences[4].grammarPatches=[{explanation:'先读“工作受到威胁”，再把中间的过去看法补完整：这些工作曾被认为不会受自动化影响。',relation:'that修饰jobs；were once thought to be immune中to be immune是对jobs的补充判断。',term:'定语从句内的被动补足结构',transferRule:'名词后出现that + be thought/believed + to do时，先确定that回指的名词，再还原“人们认为该名词会……”的关系。'}];
sentences[8].grammarPatches=[{explanation:'ones不是新的一类对象，而是代替前面的jobs；两个that分别说明这些工作是什么样、造成什么后果。',relation:'第一个that修饰ones并连接tend，第二个that也修饰ones并连接leave。',term:'替代词与并列定语从句',transferRule:'one/ones代替前文名词时，用前文名词补回再读；相邻that从句要分别找先行词和谓语。'}];
sentences[17].grammarPatches=[{explanation:'作者要寻找的是机器如何帮助人类劳动的方式，后面再用rather than排除“取代”。',relation:'in which修饰ways；augment与replace并列，共同以human labor为宾语。',term:'介词加关系代词与并列谓语',transferRule:'ways in which可理解为“做某事的方式”；rather than连接同级动作时，共享成分只需补回一次。'}];
export const paragraphs=paragraphNumbers.map((ns,i)=>({id:`2014-p3-para${i+1}`,sentenceIds:ns.map(n=>`2014-p3-s${n}`)}));
export const guide:ArticleGuide={mainIdea:'自动化会淘汰标准化岗位，但根本问题在于岗位和制度设计；未来应让机器增强人的主动性与创造力，并改革工作实践。',route:['经济低迷凸显岗位威胁','自动化波及原本安全的工作','Hagel追问岗位脆弱的原因','标准化工作压制人的创造力','重新设计工作以发挥人类优势','从与机器对抗转向同机器协作'],paragraphs:[['技术冲击超越经济周期','有些岗位永久消失，技术将持续重塑经济。','提出问题。'],['自动化范围扩大','技术性价比改善使原本安全的岗位受威胁。','补充机制和观点来源。'],['转向岗位设计','Hagel认为流行论点没有触及岗位为何脆弱。','提出反方解释。'],['脚本化岗位成为靶标','缺少个人主动性和创造力的工作更适合机器。','解释根本原因。'],['重塑工作模式','人类应发挥主动性和想象力应对意外。','提出人的比较优势。'],['与机器协作','机器应增强人类劳动，制度与工作实践需要创新。','给出解决方向。']].map(([title,summary,relation],i)=>({paragraphId:paragraphs[i].id,title,summary,relation})),references:[{sentenceId:'2014-p3-s2',expression:'it',referent:'to think we are right now simply experiencing the painful side of a boom and bust cycle',targetSentenceIds:['2014-p3-s2'],explanation:'it是形式主语，真正被评价为错误的是后面的想法。'},{sentenceId:'2014-p3-s11',expression:'That',referent:'把工作设计成严格照脚本执行、高度标准化且不留主动性和创造力空间',targetSentenceIds:['2014-p3-s9','2014-p3-s10'],explanation:'这种设计让工人成为机器替代的目标。'},{sentenceId:'2014-p3-s14',expression:'That',referent:'员工运用主动性和想象力应对意外事件',targetSentenceIds:['2014-p3-s13'],explanation:'机器不擅长的是应对意外所需的创造性活动。'},{sentenceId:'2014-p3-s16',expression:'this point',referent:'机器与人应形成增强关系，而不只是替代关系',targetSentenceIds:['2014-p3-s17','2014-p3-s18'],explanation:'下两句把这一点明确表述为race with the machine和augment human labor。'}],timeline:[],sentenceRoles:Object.fromEntries(sentences.map(s=>[s.id,s.logic]))};
