import {
  passage1FamilyAliases,
  passage1FormPartOfSpeech,
  passage1LemmaAliases,
  passage1Lexicon,
} from "./passage-1-lexicon";

export type LexicalGuide = {
  headword: string;
  partOfSpeech: string;
  contextualMeaning?: string;
  use?: string;
  specialForms: string[];
  examSynonyms: string[];
  collocations?: string[];
  otherMeanings?: string[];
  wordFamily?: string[];
  confusions?: string[];
};

export const lemmaAliases: Record<string, string> = {
  are: "be",
  is: "be",
  cannot: "can",
  wishes: "wish",
  consuming: "consume",
  produces: "produce",
  effects: "effect",
  ways: "way",
  sowing: "sow",
  channels: "channel",
  fertilizers: "fertilizer",
  implements: "implement",
  funds: "fund",
  loans: "loan",
  paths: "path",
  routes: "route",
  vessels: "vessel",
  doing: "do",
  succeeded: "succeed",
  succeeds: "succeed",
  succeeding: "succeed",
};

export const familyAliases: Record<string, string> = {
  consumption: "consume",
  production: "produce",
  obtainable: "obtain",
  agricultural: "agriculture",
  irrigation: "irrigate",
  farmer: "farm",
  frequently: "frequent",
  naturally: "natural",
  immediately: "immediate",
  unpredictable: "predict",
  himself: "he",
  his: "he",
  wishes: "wish",
};

const partOfSpeech: Record<string, string> = {
  a: "art.（不定冠词）",
  against: "prep.",
  agricultural: "adj.",
  all: "det./pron./adv.",
  also: "adv.",
  an: "art.（不定冠词）",
  and: "conj.",
  as: "prep./conj./adv.",
  at: "prep.",
  available: "adj.",
  bad: "adj.",
  be: "v.（系动词/助动词）",
  before: "prep./conj./adv.",
  between: "prep.",
  borrow: "v.",
  but: "conj./prep./adv.",
  can: "modal v.",
  channel: "n./v.",
  chemical: "adj./n.",
  commodity: "n.",
  construct: "v./n.",
  consume: "v.",
  consumption: "n.",
  continue: "v.",
  desire: "v./n.",
  difference: "n.",
  disparity: "n.",
  dispose: "v.",
  do: "v./aux.",
  effect: "n./v.",
  either: "det./pron./adv./conj.",
  enhance: "v.",
  ever: "adv.",
  excess: "n./adj.",
  expect: "v.",
  extra: "adj./n./adv.",
  family: "n./adj.",
  farm: "n./v.",
  farmer: "n.",
  feed: "v./n.",
  fertilizer: "n.",
  for: "prep./conj.",
  form: "n./v.",
  frequently: "adv.",
  fund: "n./v.",
  gap: "n.",
  genuinely: "adv.",
  grain: "n.",
  he: "pron.",
  himself: "reflexive pron.",
  his: "possessive det./pron.",
  hope: "v./n.",
  if: "conj.",
  immediately: "adv.",
  implement: "n./v.",
  improve: "v.",
  in: "prep./adv.",
  instead: "adv.",
  insurance: "n.",
  interest: "n./v.",
  irrigation: "n.",
  keep: "v./n.",
  kind: "n./adj.",
  large: "adj.",
  loan: "n./v.",
  long: "adj./adv./v.",
  low: "adj./adv./n.",
  may: "modal v.",
  mix: "v./n.",
  money: "n.",
  more: "det./pron./adv.",
  much: "det./pron./adv.",
  must: "modal v./n.",
  naturally: "adv.",
  need: "v./n./modal v.",
  no: "det./adv./n.",
  not: "adv.",
  obtain: "v.",
  obtainable: "adj.",
  obviously: "adv.",
  of: "prep.",
  offer: "v./n.",
  old: "adj.",
  only: "adv./adj./conj.",
  or: "conj.",
  order: "n./v.",
  other: "adj./pron.",
  path: "n.",
  percentage: "n.",
  presumably: "adv.",
  produce: "v./n.",
  production: "n.",
  property: "n.",
  proportion: "n.",
  purchase: "v./n.",
  quantity: "n.",
  raise: "v./n.",
  rate: "n./v.",
  ratio: "n.",
  replace: "v.",
  route: "n./v.",
  save: "v./prep./conj./n.",
  search: "v./n.",
  seed: "n./v.",
  seek: "v.",
  "self-confident": "adj.",
  "self-restrained": "adj.",
  "self-satisfied": "adj.",
  "self-sufficient": "adj.",
  sell: "v./n.",
  since: "prep./conj./adv.",
  soil: "n./v.",
  some: "det./pron./adv.",
  sow: "v.",
  store: "v./n.",
  succeed: "v.",
  success: "n.",
  successful: "adj.",
  successfully: "adv.",
  supplement: "n./v.",
  support: "v./n.",
  surplus: "n./adj.",
  than: "conj./prep.",
  the: "art.（定冠词）",
  this: "det./pron.",
  three: "numeral",
  to: "prep./不定式标记",
  towards: "prep.",
  try: "v./n.",
  unpredictable: "adj.",
  use: "v./n.",
  vessel: "n.",
  want: "v./n.",
  way: "n.",
  weather: "n./v.",
  well: "adv./adj./n./interj.",
  which: "pron./det.",
  wide: "adj./adv.",
  will: "modal v./n./v.",
  wish: "v./n.",
};

const formPartOfSpeech: Record<string, string> = {
  are: "v.（be 的现在时复数）",
  cannot: "modal v.（can 的否定形式）",
  channels: "n.（复数）",
  consuming: "v.（-ing/动名词形式）",
  effects: "n.（复数）",
  fertilizers: "n.（复数）",
  funds: "n.（复数，资金）",
  implements: "n.（复数，工具）",
  is: "v.（be 的第三人称单数现在时）",
  loans: "n.（复数）",
  paths: "n.（复数）",
  produces: "v.（第三人称单数）",
  routes: "n.（复数）",
  sowing: "v.-ing / gerund（播种）",
  vessels: "n.（复数）",
  ways: "n.（复数）",
  wishes: "v.（第三人称单数）",
};

Object.assign(lemmaAliases, passage1LemmaAliases);
Object.assign(familyAliases, passage1FamilyAliases);
Object.assign(formPartOfSpeech, passage1FormPartOfSpeech);

const specialForms: Record<string, string[]> = {
  bad: ["bad（原级）", "worse（比较级）", "worst（最高级）"],
  be: ["am / is / are（现在时）", "was / were（过去时）", "been（过去分词）", "being（-ing）"],
  can: ["can（现在式）", "could（过去式/较委婉形式）", "cannot / can't（否定）"],
  channel: ["channel（单数/原形）", "channels（复数/第三人称单数）", "channelled / channeled（过去式）"],
  consume: ["consume（原形）", "consumes（第三人称单数）", "consumed（过去式/过去分词）", "consuming（-ing，去 e）"],
  continue: ["continue（原形）", "continues（第三人称单数）", "continued（过去式/过去分词）", "continuing（-ing，去 e）"],
  do: ["do（原形）", "does（第三人称单数）", "did（过去式）", "done（过去分词）", "doing（-ing）"],
  effect: ["effect（单数/原形）", "effects（复数/第三人称单数）", "effected（动词过去式）"],
  family: ["family（单数）", "families（复数，y → ies）"],
  feed: ["feed（原形）", "feeds（第三人称单数）", "fed（过去式/过去分词）", "feeding（-ing）"],
  fertilizer: ["fertilizer（单数）", "fertilizers（复数）"],
  fund: ["fund（单数/原形）", "funds（复数/第三人称单数）", "funded（过去式/过去分词）"],
  hope: ["hope（原形）", "hopes（第三人称单数）", "hoped（过去式/过去分词）", "hoping（-ing，去 e）"],
  implement: ["implement（单数/原形）", "implements（复数/第三人称单数）", "implemented（过去式/过去分词）"],
  keep: ["keep（原形）", "keeps（第三人称单数）", "kept（过去式/过去分词）", "keeping（-ing）"],
  large: ["large（原级）", "larger（比较级）", "largest（最高级）"],
  loan: ["loan（单数/原形）", "loans（复数/第三人称单数）", "loaned（过去式/过去分词）"],
  low: ["low（原级）", "lower（比较级）", "lowest（最高级）"],
  may: ["may（现在式）", "might（过去式/可能性更弱或更委婉）"],
  money: ["money（通常不可数）", "monies / moneys（不同笔款项，正式且少见）"],
  obtain: ["obtain（原形）", "obtains（第三人称单数）", "obtained（过去式/过去分词）", "obtaining（-ing）"],
  old: ["old（原级）", "older / elder（比较级）", "oldest / eldest（最高级）"],
  produce: ["produce（原形）", "produces（第三人称单数）", "produced（过去式/过去分词）", "producing（-ing，去 e）"],
  property: ["property（单数/不可数“财产”）", "properties（多处房产/多种性质）"],
  quantity: ["quantity（单数）", "quantities（复数，y → ies）"],
  seek: ["seek（原形）", "seeks（第三人称单数）", "sought（过去式/过去分词）", "seeking（-ing）"],
  sell: ["sell（原形）", "sells（第三人称单数）", "sold（过去式/过去分词）", "selling（-ing）"],
  sow: ["sow（原形）", "sows（第三人称单数）", "sowed（过去式）", "sown / sowed（过去分词）", "sowing（-ing）"],
  succeed: ["succeed（原形）", "succeeds（第三人称单数）", "succeeded（过去式/过去分词）", "succeeding（-ing）"],
  success: ["success（通常不可数：成功）", "successes（可数：成功的人或事）"],
  try: ["try（原形）", "tries（第三人称单数，y → ies）", "tried（过去式/过去分词）", "trying（-ing）"],
  use: ["use（原形/名词）", "uses（第三人称单数/复数）", "used（过去式/过去分词）", "using（-ing，去 e）"],
  wide: ["wide（原级）", "wider（比较级）", "widest（最高级）"],
  will: ["will（现在式）", "would（过去式/假设或委婉形式）"],
  wish: ["wish（原形）", "wishes（第三人称单数，-sh + es）", "wished（过去式/过去分词）", "wishing（-ing）"],
};

const contextualMeaning: Record<string, string> = {
  between: "在……之间；原句构成 between his consumption and his production",
  before: "在……之前；原选项 long before 表“早在……之前”",
  desire: "渴望；愿望（语气通常比 hope / wish 更强、更正式）",
  difference: "差别；差异",
  disparity: "明显差距；不平等",
  ever: "曾经；在任何时候；原选项 ever since 表“自从……以来”",
  excess: "过量；过剩；超出所需的部分",
  expect: "预料；期待某事很可能发生",
  hope: "希望某件可能实现的事发生",
  long: "很久；长的；原选项 long before 中作副词",
  more: "更多；原选项 more than 表“超过；不仅仅”",
  much: "很多；原选项 much as 表“尽管”",
  since: "自从；因为；从……以后",
  success: "成功；成功的结果或事物",
  successful: "成功的；达到预期结果的",
  successfully: "成功地；顺利地",
  than: "比；用于比较结构",
  want: "想要；需要（最普通、直接）",
  well: "好地；原选项 as well as 表“也；以及”",
  wish: "希望；原句 wishes to succeed 表较正式地“想要成功”",
};

const usage: Record<string, string> = {
  against: "against + 风险/损失可表示“防范、抵御”；insurance against sth 是固定搭配。",
  agricultural: "只作定语较常见：agricultural production / implements；不要与 agriculture n. 混用。",
  available: "be available to sb / for sth；既可指物“可获得”，也可指人“有空”。",
  before: "before + 名词/时间点，或 before + 从句；long before 强调“早在……之前”。",
  between: "核心结构是 between A and B，A、B 应保持语法平行；也可接复数名词，表示若干彼此区分的对象之间。",
  borrow: "borrow sth from sb 表“从某人处借入”；与 lend sth to sb 的方向相反。",
  channel: "irrigation channel 指灌溉渠；作动词 channel sth into... 表把资源导向某处。",
  chemical: "chemical fertilizers 中 chemical 作形容词；作名词时表示化学品。",
  construct: "construct + 建筑/系统/论证；比 build 更正式，也可指构建抽象事物。",
  consume: "consume food/energy/resources；原文 consuming 是介词 of 后的动名词。",
  continue: "continue to do 与 continue doing 多数情况下都表示继续做；continue with + 名词。",
  desire: "desire to do / desire sth；正式且语气较强，不等同于普通的 want。",
  dispose: "dispose of sth 才表示“处理掉”；dispose 不能在本题中直接接 old implements。",
  effect: "have an effect on；the effects of sth。注意 affect 通常是动词“影响”。",
  either: "either A or B 连接同级成分；单独作限定词时表示“两者任一”。",
  enhance: "enhance quality/value/ability，强调提升已有的质量或价值；不说 enhance the soil 表施肥。",
  ever: "ever since + 起点，主句常用现在完成时；不要只按“曾经”硬译。",
  excess: "an excess of + 名词表示“过量的……”；excess + 名词作定语，如 excess demand。与 surplus 相比，excess 更强调超过需要或限度。",
  expect: "expect sth / expect to do / expect sb to do；强调判断某事很可能发生。",
  extra: "extra funds / time / cost；表示在原有之外再增加的。",
  family: "support a family 表“养家”；family 作集合名词时单复数取决于强调整体还是成员。",
  farmer: "可数名词；farmer 强调经营或耕作的人，farm 是农场/经营农场。",
  feed: "feed sb/sth；feed A with B；feed the soil 是给土壤补充养分的拟人化搭配。",
  for: "insurance for + 人/物；insurance against + 风险。此题不能用 for 替代 against。",
  frequently: "频率副词，通常置于实义动词前、be 动词后；not frequently 是“不常”，不是“从不”。",
  hope: "hope to do / hope that...，用于说话者认为仍可能实现的愿望；不能说 hope sb to do。",
  if: "if 引导条件；only if 是“只有……才”，if only 是“要是……就好了”。",
  immediately: "可修饰动作，也可作连词表示“一……就……”；原句修饰 consuming。",
  improve: "improve sth 或 sth improves；improve on/upon sth 表在原有基础上做得更好。",
  irrigation: "irrigation channel/system；由 irrigate v.（灌溉）派生。",
  keep: "keep + 宾语 + 补足语表示“使……保持”；keep doing 表持续做；原句 keep a gap 是维持差额。",
  kind: "a kind of + 名词；of this kind 后置修饰 loans。kind 作形容词另表示“友善的”。",
  long: "long before / long after 中作副词；before long 则是“不久以后”，顺序不同含义相反。",
  may: "此处表示现实可能性“可能需要”，不是请求许可。may have done 表对过去的推测。",
  mix: "mix A with B；mix sth up。mix the soil 只是翻动/混合土壤，不等于施肥。",
  more: "more than + 数量表示“超过”；more than + 名词/形容词还可表示“不仅仅/非常”。",
  much: "much as 可引导让步，意为“尽管”；much 主要修饰不可数名词或比较级。",
  need: "need sth / need to do；need doing 可用主动形式表达被动含义，如 needs repairing。",
  obtain: "obtain sth from...，较正式，强调通过努力取得；不直接接双宾语。",
  obtainable: "be obtainable from；强调“能否取得”，available 还可表示“现成可用/有空”。",
  offer: "offer sb sth / offer sth to sb 表主动提供；原题农民是资金需求方，不能用 offer。",
  order: "in order to + 动词原形只表示目的；order 本身还可表示顺序、命令或订购。",
  path: "path 指小路或抽象途径；灌溉输水设施应用 channel。",
  percentage: "percentage of + 整体；具体百分数可用 a high percentage，但 interest rate 不能换成 percentage of interest。",
  presumably: "句子副词，表示根据已知情况推测“大概”；不表示频率。",
  produce: "produce a surplus / result；作名词时重音变化，表示农产品。",
  proportion: "the proportion of A to B 或 a proportion of the whole；强调部分占整体的份额。",
  purchase: "purchase sth 比 buy 正式；purchase old implements 会变成“购买旧农具”，不合本题逻辑。",
  raise: "raise + 宾语：提高、筹集、养育；是不及物 rise 的对应及物动词。",
  ratio: "the ratio of A to B；强调两个量的数值之比，不表示利率。",
  replace: "replace A with/by B；replace old equipment 表更换旧设备。",
  route: "route 指路线或途径；channel 强调可输送水、信息等的通道。",
  save: "save money 可表示储蓄或节省；seek funds 是寻求资金，二者方向不同。",
  search: "search a place/person 或 search for sth；不能直接说 search funds 表“寻求资金”。",
  seed: "seed for sowing；作动词可表示播种或为比赛设种子选手。",
  sell: "sell sth to sb / sell sth for a price；sell well 是“畅销”，主动形式表被动意义。",
  since: "ever since + 时间起点，常与完成时连用；since 也可引导原因从句。",
  sow: "sow seed / sow a field with seed；过去分词常用 sown。",
  supplement: "supplement A with B 表用 B 补充 A；不能直接表达把旧农具换掉。",
  support: "support oneself/a family 是“养活”；support an idea/person 才是支持观点或人。",
  success: "success 通常作不可数名词表示“成功”；a success 可指一个成功的人、事或成果。不能直接作谓语。",
  successful: "be successful in (doing) sth 表示“在某事上成功”；successful 是形容词，需要与 be 等系动词连用。",
  successfully: "副词，修饰动词、形容词或整句，如 successfully complete the task。",
  than: "用于比较结构 more than / rather than / other than；不同结构不能按单个 than 推义。",
  towards: "表示方向、接近或态度；不与 insurance 构成“防范风险”的搭配。",
  use: "use A as B / use A for doing；原句 use surplus in three ways。",
  vessel: "可指船、容器或血管；不能表示灌溉渠。",
  want: "want sth / want to do / want sb to do；语气直接、日常，不含 wish 的虚拟意味。",
  way: "in this/three ways；a way to do / a way of doing。",
  weather: "不可数名词；weather 是短期天气，climate 是长期气候。",
  well: "as well as 表“也、以及”，连接并列项；谓语单复数通常由前面的主语决定。",
  a: "不定冠词，放在辅音音素开头的单数可数名词前，表示“一个”或泛指一类；不能修饰复数或不可数名词。",
  all: "all + 复数可数名词或不可数名词；all his grain 中 all 位于物主限定词 his 之前。",
  also: "表示“也、还”，通常放在实义动词前、be 动词或第一个助动词后；原句位于 may 与 need 之间。",
  an: "不定冠词，放在元音音素开头的单数可数名词前；判断依据是发音而非首字母。",
  and: "并列连词，连接语法上平行的词、短语或分句；阅读时应核对 and 两侧是否同级。",
  at: "可表示精确地点、时间点、价格、速度或比率；at a low rate 中表示“以某种比率”。",
  bad: "可作定语或表语；bad weather 是“恶劣天气”。比较级和最高级是不规则的 worse、worst。",
  be: "系动词后接名词、形容词或介词短语说明身份和状态；也可与分词构成被动语态或进行时。",
  but: "并列连词，连接语法同级而意义转折的成分或分句；原句从“想借低息贷款”转向“并不易获得”。",
  can: "情态动词，后接动词原形；可表示能力、客观可能性或许可。否定形式 cannot / can't。",
  farm: "作名词表示农场；作动词表示务农或经营农场。improve his farm 中为名词。",
  form: "in the form of 表“以……形式”；作动词时表示形成、组成。不要在固定结构中把 form 单独译成“表格”。",
  genuinely: "副词，表示“真正地、真诚地”；修饰形容词或动词。与 obviously（显然地）表达的判断依据不同。",
  he: "第三人称男性主格代词，在句中作主语；宾格为 him，物主限定词为 his，反身代词为 himself。",
  himself: "反身代词，主语和宾语指同一男性时使用；support himself 是“养活他自己”，不能换成 him。",
  his: "物主限定词，放在名词前表示“他的”，如 his production；也可单独作物主代词。",
  in: "介词，常表示在某范围、时间或状态内，也可说明方式；in three ways 表“以三种方式”。",
  interest: "rate of interest / interest rate 中表示“利息、利率”；另可表示兴趣或利益，需由搭配判断。",
  large: "常修饰数量、规模或体积；a large quantity of 是“大量的”，比 big 更适合正式数量表达。",
  low: "可表示位置低、数量少或比率低；a low rate of interest 是“低利率”，比较级为 lower。",
  money: "表示“钱、资金”时通常不可数，不能直接说 a money 或 many money；可用 a sum of money。",
  naturally: "既可表示“自然地”，也可作句子副词表示“当然、可以预料地”；原句属于后者。",
  no: "限定词，直接放在名词前表示“没有任何……”，通常等于 not any；no surplus 比 not a surplus 更自然。",
  not: "否定副词，否定其后的词或谓语；not frequently 只否定频率，表示“不常”，不等于 never。",
  obviously: "句子副词，表示结论从证据看“显然”；比 presumably（推测地）把握更强。",
  old: "作定语或表语；old implements 指旧农具。older / oldest 是普通比较级、最高级。",
  or: "并列连词，表示选择、替代或解释；either A or B 中与 either 呼应，A、B 应保持结构平行。",
  other: "other + 复数或不可数名词表示“其他的”；another 接单数可数名词，the other 常指两者中的另一个。",
  "self-confident": "形容词，表示“自信的”；描述心理状态，不能替换 self-sufficient（自给自足的）。",
  "self-restrained": "形容词，表示“克制的、自我约束的”；不表示经济上的自给自足。",
  "self-satisfied": "形容词，表示“自满的、沾沾自喜的”；通常带贬义，不等于 self-sufficient。",
  soil: "表示土壤时通常不可数；feed / enrich / improve the soil 可表示给土壤补充养分或改善土质。",
  some: "可修饰复数可数名词或不可数名词；some of + 限定词/代词，如 some of his property。",
  the: "定冠词，标明双方已知、前文提到或语境中唯一的对象；不表示数量。",
  this: "可作限定词或代词，指靠近说话者或前文刚提到的单数事物；this surplus 回指前面的 surplus。",
  three: "基数词，直接修饰复数可数名词；in three ways 中 ways 必须用复数。",
  try: "try to do 表示努力、设法做；try doing 表示试着用某种办法，两者含义不同。",
  unpredictable: "由 un- + predict + -able 构成，表示“无法预料的”；常修饰 effects、weather、outcome 等。",
  wide: "可表示物理宽度或抽象差距大；a wide gap 是“很大的差距”，不要机械译成“宽的缝隙”。",
  which: "关系代词 which 指物，在定语从句中可作主语或宾语；原句指代 commodity。",
  will: "此处表示将来或自然倾向；will 也可表示意愿，would 可用于过去将来/假设/委婉。",
  wish: "原句是 wish to do sth（较正式地“想要做某事”）。wish + that 从句常表示与事实相反或难实现的愿望；还可用 wish sb sth。",
};

const collocations: Record<string, string[]> = {
  between: ["between A and B", "the difference between A and B", "choose between A and B", "between the ages of A and B"],
  excess: ["an excess of", "in excess of", "excess demand", "excess baggage"],
  wish: ["wish to do sth", "wish sb to do sth", "wish + that 从句", "wish sb sth"],
  hope: ["hope to do sth", "hope that...", "hope for sth", "in the hope of doing"],
  want: ["want to do sth", "want sb to do sth", "want sth done"],
  desire: ["desire to do sth", "a desire for sth"],
  expect: ["expect to do sth", "expect sb to do sth", "be expected to do"],
  success: ["achieve success", "a great success", "success in doing"],
  successful: ["be successful in doing", "a successful attempt", "highly successful"],
  successfully: ["successfully complete", "successfully apply"],
};

const examSynonyms: Record<string, string[]> = {
  available: ["obtainable（能够取得的）", "accessible（可接近/可使用的）"],
  bad: ["poor（质量差）", "adverse（不利的）", "harmful（有害的）"],
  borrow: ["obtain on loan（借入）"],
  channel: ["canal（水渠）", "passage（通道）"],
  commodity: ["goods（货物）", "merchandise（商品）", "product（产品）"],
  construct: ["build（建造）", "establish（建立）", "form（构建）"],
  consume: ["use up（耗尽）", "expend（消耗）"],
  consumption: ["use（使用/消耗）", "expenditure（支出/消耗量）", "intake（摄入量）"],
  continue: ["persist（坚持继续）", "proceed（继续进行）", "remain（仍然）"],
  effect: ["impact（影响）", "result（结果）", "consequence（后果）"],
  excess: ["surplus（超过需要的剩余）", "overabundance（过多）", "overflow（溢出量）"],
  enhance: ["improve（改善）", "strengthen（加强）", "boost（提升）"],
  extra: ["additional（附加的）", "further（更多的）", "supplementary（补充的）"],
  family: ["household（家庭单位）", "relatives（亲属）"],
  farmer: ["grower（种植者）", "agricultural producer（农业生产者）"],
  feed: ["nourish（滋养）", "supply（供给）"],
  frequently: ["often（经常）", "regularly（有规律地）", "repeatedly（反复地）"],
  fund: ["money（资金）", "capital（资本）", "finance（资金/融资）"],
  gap: ["difference（差异）", "disparity（明显差距）", "interval（间隔）"],
  hope: ["wish（愿望；常含不现实/正式色彩）", "expect（预计很可能发生）", "desire（强烈愿望）"],
  improve: ["enhance（提升）", "promote（促进）", "refine（改进完善）"],
  implement: ["tool（工具，名词义）", "carry out（实施，动词义）", "execute（执行，动词义）"],
  insurance: ["protection（保护）", "safeguard（保障措施）"],
  keep: ["maintain（维持）", "retain（保留）", "preserve（保存）"],
  large: ["substantial（大量的）", "considerable（相当大的）", "extensive（广泛的）"],
  loan: ["credit（信贷）", "advance（预付款/贷款）"],
  low: ["reduced（降低的）", "modest（不高的）", "small（小的）"],
  money: ["funds（资金）", "capital（资本）", "finance（财力）"],
  obtain: ["acquire（获得）", "gain（取得）", "secure（设法得到）"],
  obtainable: ["available（可获得/可用的）", "accessible（可取得/可接近的）", "attainable（可达到的）"],
  offer: ["provide（提供）", "propose（提出）", "present（呈上）"],
  produce: ["generate（产生）", "create（创造）", "manufacture（制造）"],
  production: ["output（产出）", "manufacture（制造）"],
  property: ["possession（所有物）", "asset（资产）", "real estate（房地产）"],
  purchase: ["buy（购买）", "acquire（购得）"],
  quantity: ["amount（不可数事物的量）", "number（可数事物的数量）", "volume（总量）"],
  rate: ["pace（速度）", "level（比率水平）", "charge（费率）"],
  replace: ["substitute（替代）", "renew（更新）"],
  search: ["look for（寻找）", "seek（寻求）"],
  seek: ["look for（寻找）", "pursue（追求）", "request（寻求/请求）"],
  sell: ["trade（交易）", "market（推销）"],
  store: ["save（储存）", "preserve（保存）", "stockpile（大量储备）"],
  succeed: ["prosper（兴旺）", "achieve（达到目标，及物）", "accomplish（完成，及物）"],
  success: ["achievement（成就）", "accomplishment（完成的成果）"],
  successful: ["effective（有效的）", "prosperous（繁荣的）"],
  support: ["maintain（供养/维持）", "sustain（维持）", "back（支持）"],
  surplus: ["excess（过剩）", "remainder（剩余部分）"],
  unpredictable: ["uncertain（不确定的）", "unforeseeable（无法预见的）"],
  vessel: ["ship（船）", "container（容器）"],
  want: ["wish（希望）", "desire（渴望）", "need（需要；部分语境）"],
  weather: ["climate（气候；不是同义词，时间尺度不同）"],
  wide: ["broad（宽广的）", "extensive（广泛的）"],
  wish: ["hope（希望可能实现的事）", "want（普通直接地想要）", "desire（较强烈、正式地渴望）"],
};

const confusions: Record<string, string[]> = {
  between: ["between A and B 强调可区分的对象；among 常指未逐一区分的一群人或物。", "不能说 between A to B。"],
  excess: ["surplus 是需求满足后的剩余或盈余，语气可中性；excess 强调超过需要、限度或正常量，常带负面意味。"],
  hope: ["hope to do：希望做可能实现的事；不能说 hope sb to do。", "wish that... 常接虚拟语气；hope that... 通常谈仍可能发生的事。"],
  wish: ["wish to do 较正式，接近 want to do；hope to do 更强调对未来可能结果的期待。", "wish sb to do 可以；hope sb to do 不可以。", "wish sb sth 可以说 wish you success；hope 不接双宾语。"],
  success: ["success 是名词；succeed 是动词；successful 是形容词；successfully 是副词。"],
  successful: ["successful 是形容词，不能单独作谓语；应说 be successful。"],
};

const wordFamily: Record<string, string[]> = {
  excess: ["excessive adj. 过度的", "excessively adv. 过度地"],
  hope: ["hopeful adj. 有希望的", "hopeless adj. 无望的", "hopefully adv. 有希望地/但愿"],
  wish: ["wish n. 愿望/祝愿", "wishful adj. 一厢情愿的", "wishfully adv. 一厢情愿地"],
  success: ["succeed v. 成功", "successful adj. 成功的", "successfully adv. 成功地"],
  successful: ["succeed v. 成功", "success n. 成功", "successfully adv. 成功地"],
};

const otherMeanings: Record<string, string[]> = {
  excess: ["adj. 超额的；额外的，如 excess baggage", "in excess of：超过……"],
  hope: ["n. 希望；期望", "有希望的人或事物"],
  wish: ["n. 愿望；祝愿", "wish that...：对现实相反或难实现情况的愿望"],
  success: ["a success：成功的人或事", "可数复数 successes：多次成功 / 成功案例"],
};

function inferPartOfSpeech(headword: string) {
  if (/ly$/.test(headword)) return "adv.";
  if (/(tion|sion|ment|ness|ity|ism|ance|ence|er|or)$/.test(headword)) return "n.";
  if (/(able|ible|ful|less|ive|ous|al|ic|ed)$/.test(headword)) return "adj.";
  if (/(ize|ise|ify|ate)$/.test(headword)) return "v.";
  return "word（需结合来源词条判断词性）";
}

export function canonicalLemma(token: string) {
  const normalized = token.trim().toLowerCase();
  return lemmaAliases[normalized] ?? normalized;
}

export function getLexicalGuide(token: string): LexicalGuide {
  const normalized = token.trim().toLowerCase();
  const headword = canonicalLemma(normalized);
  const passageEntry = passage1Lexicon[headword];
  const pos = formPartOfSpeech[normalized] ?? passageEntry?.partOfSpeech ?? partOfSpeech[headword] ?? inferPartOfSpeech(headword);
  const isStructureWord = /art\.|prep\.|conj\.|pron\.|det\.|modal/.test(pos);
  const mergedCollocations = Array.from(new Set([...(collocations[headword] ?? []), ...(passageEntry?.collocations ?? [])]));
  const mergedMeanings = Array.from(new Set([...(otherMeanings[headword] ?? []), ...(passageEntry?.otherMeanings ?? [])]));
  const mergedFamily = Array.from(new Set([...(wordFamily[headword] ?? []), ...(passageEntry?.wordFamily ?? [])]));
  const mergedConfusions = Array.from(new Set([...(confusions[headword] ?? []), ...(passageEntry?.confusions ?? [])]));
  return {
    headword,
    partOfSpeech: pos,
    contextualMeaning: passageEntry?.contextualMeaning ?? contextualMeaning[headword],
    use: passageEntry?.use ?? usage[headword],
    specialForms: passageEntry?.specialForms ?? specialForms[headword] ?? [isStructureWord ? "结构词：无普通词形变化，重点看句法位置" : "无需要单独记忆的不规则变形"],
    examSynonyms: passageEntry?.examSynonyms ?? examSynonyms[headword] ?? [isStructureWord ? "结构词通常不能脱离句型直接替换" : "本词暂无需要成组强记的考研近义词"],
    collocations: mergedCollocations,
    otherMeanings: mergedMeanings,
    wordFamily: mergedFamily,
    confusions: mergedConfusions,
  };
}
