import type { BeginnerClauseDetail, BeginnerSyntaxComponent, Question, QuestionAnalysis, SentenceAnalysis, SyntaxVisualRole } from "./data";
import { withReviewedSyntax } from "./reviewed-syntax";
const c=(text:string,form:string,fn:string,modifies:string,explanation:string,children?:BeginnerSyntaxComponent[]):BeginnerSyntaxComponent=>({text,form,function:fn,modifies,explanation,children});
const cl=(text:string,type:string,marker:string,role:string,subject:string,predicate:string,details:Array<[string,string]>):BeginnerClauseDetail=>({text,type,marker,role,subject,predicate,predicateDetails:details.map(([functionName,text])=>({function:functionName,text})),translationOrder:"先找本层实际主谓，再读补足；原题的未完成位置由选项补齐。"});
const make=(base:SentenceAnalysis,components:BeginnerSyntaxComponent[],colors:SyntaxVisualRole[],trunk:string,focus:string,clauses:BeginnerClauseDetail[]=[],phrase=false):SentenceAnalysis=>withReviewedSyntax({...base,trunk,textKind:phrase?"phrase":"sentence",beginnerSyntax:{components,clauses},layers:[{label:"语言关系",text:focus}],grammar:[focus],logic:"先理解本项文字实际表达的关系，再由正文证据判断。"},colors);
const sub=(t:string,p:string,e:string)=>c(t,"名词性成分","主语",p,e),pred=(t:string,s:string,e:string)=>c(t,"有限谓语","谓语",s,e),obj=(t:string,p:string,e:string,ch?:BeginnerSyntaxComponent[])=>c(t,"名词性成分","宾语",p,e,ch),comp=(t:string,p:string,e:string)=>c(t,"表语成分","表语",p,e),mod=(t:string,p:string,e:string,ch?:BeginnerSyntaxComponent[])=>c(t,"修饰或补足成分","修饰或补足",p,e,ch);
const infinitive=(t:string,p:string,e:string,ch?:BeginnerSyntaxComponent[])=>c(t,"不定式结构","非谓语补足",p,e,ch);
export function passage5QuestionAnalysis(question:Question):QuestionAnalysis {
 const old=question.analysis!,o=old.options!;let prompt:SentenceAnalysis,answer:SentenceAnalysis;const options:Record<string,SentenceAnalysis>={};
 if(question.id===27){
  const inside=[sub("ambition","may be well regarded","抱负是被评价对象。"),pred("may be well regarded","ambition","情态被动，well修饰认可程度。"),c("if","条件连接词","待补条件标记","may be well regarded","题干只写if，没有条件内部主谓，不虚构完整条件从句。")];
  prompt=make(old.prompt!,[sub("It","is generally believed","形式主语，对应后置that内容。"),pred("is generally believed","It","被动报告，generally限定一般看法。"),c("that ambition may be well regarded if","that内容结构","后置主语从句","It","给被普遍相信的内容，其中if所需条件尚待选项补足。",[c("that","连接词","内容标记","后置主语内容","不在内部作成分。"),...inside])],["subject","predicate","subject"],"It is generally believed that ambition may be well regarded if","形式主语与后置内容分开，if仍在等待条件；不能替选项补写正文。",[cl("that ambition may be well regarded if","主语从句（条件待补）","that","对应形式主语It","ambition","may be well regarded",[])]);
  options.A=make(o.A!,[sub("its returns","compensate","its指抱负，returns为回报复数。"),pred("well compensate","its returns","well表示补偿得充分。"),mod("for the sacrifices","compensate","compensate for接所抵偿的牺牲。")],["subject","predicate","modifier"],"its returns well compensate for the sacrifices","returns不是返回的动词；compensate for把回报与付出建立平衡关系。");
  options.B=make(o.B!,[sub("it","is rewarded","it承接ambition。"),pred("is rewarded","it","被动：得到某种回报。"),mod("with money, fame and power","rewarded","with列回报内容，非worthy of的价值比较。")],["subject","predicate","modifier"],"it is rewarded with money, fame and power","money、fame、power是并列回报项；语法上未给回报是否值得牺牲这一关系。");
  options.C=make(o.C!,[sub("its goals","are","goals复数主语。"),pred("are","its goals","连接目标属性。"),comp("spiritual rather than material","are","rather than在两个形容词间作取舍，选精神而非物质。")],["subject","predicate","complement"],"its goals are spiritual rather than material","rather than连接表语属性，不是比较目标数量的than从句。");
  options.D=make(o.D!,[sub("it","is shared","被共同认可的是抱负。"),pred("is shared","it","被动谓语。"),mod("by the rich and the famous","shared","两个the加形容词的名词化人群并列作施事。")],["subject","predicate","modifier"],"it is shared by the rich and the famous","rich、famous在the后指人群，不能直接等同受敬仰者。");
  answer=make(old.answer!,[sub("Ambition","may be well regarded","主句主语。"),pred("may be well regarded","Ambition","情态被动。"),c("if its returns well compensate for the sacrifices","if条件从句","条件状语","may be well regarded","本补全示例现在具有真实条件主谓。",[c("if","条件连接词","条件标记","从句","引出认可条件。"),...options.A.beginnerSyntax!.components])],["subject","predicate","modifier"],"Ambition may be well regarded if its returns well compensate for the sacrifices","补全后if从句中returns是主语，compensate是谓语。",[cl("if its returns well compensate for the sacrifices","条件状语从句","if","限定认可条件","its returns","well compensate",[])]);
 }else if(question.id===28){
  prompt=make(old.prompt!,[sub("The last sentence of the first paragraph","implies","sentence为中心，两个序数限定定位。"),pred("most probably implies","The last sentence","probably保留推断强度；most加强可能程度。"),c("that it is","待补内容从句","宾语从句","implies","it是形式主语，表语和真正内容由选项补足。",[c("that","连接词","内容标记","implies","引出暗示内容。"),sub("it","is","形式主语框架。"),pred("is","it","表语尚未提供。")])],["subject","predicate","object"],"The last sentence most probably implies that it is","题干已有that内容的it is框架，但没有完整评价补足。",[cl("that it is","宾语从句（表语待补）","that","作implies的内容","it","is",[])]);
  options.A=make(o.A!,[comp("customary","题干is","表示习惯性的，等待承接题干。"),mod("of the educated","customary","原选项用of指涉及的受教育者，保留原措辞。"),infinitive("to discard ambition in words","题干it","不定式给被评价的行为，in words限定在口头上。",[c("discard","不定式动词","非谓语中心","to discard","舍弃。"),obj("ambition","discard","被舍弃对象。"),mod("in words","discard","只是口头上的行为。")])],["complement","modifier","subject"],"customary of the educated to discard ambition in words","这是形容词和不定式补足片段，没有独立有限谓语；保留原文customary of。",[],true);
  options.B=make(o.B!,[comp("too late","题干is","too说明晚到影响可行性的程度。"),infinitive("to check ambition","late","check为遏制，不是检查答案。"),c("once it has been let out","时间从句","时间或条件限定","check ambition","一旦抱负被释放后。",[c("once","连接词","时机标记","has been let out","引出已释放条件。"),sub("it","has been let out","it指ambition。"),pred("has been let out","it","完成被动；let的分词仍为let。")])],["complement","modifier","modifier"],"too late to check ambition once it has been let out","整体为待补表语片段，内部once确有完整主谓，不能把整个选项都当无从句短语。",[cl("once it has been let out","时间状语从句","once","限定遏制的时机","it","has been let out",[])],true);
  options.C=make(o.C!,[comp("dishonest","题干is","作道德评价表语。"),infinitive("to deny ambition after the fulfillment of the goal","题干it","不定式给被评价行为，after后是名词短语，不是从句。",[c("deny","不定式动词","非谓语中心","to deny","否认。"),obj("ambition","deny","被否认的抱负。"),mod("after the fulfillment of the goal","deny","after介词接实现目标这一名词化事件。")])],["complement","subject"],"dishonest to deny ambition after the fulfillment of the goal","dishonest评价受益后否认这一行为；after这里没有有限主谓。",[],true);
  options.D=make(o.D!,[comp("impractical","题干is","表示不切实际。"),mod("for the educated","to enjoy","for引出不定式逻辑主语。"),infinitive("to enjoy benefits from ambition","题干it","enjoy支配benefits，from说明好处来源。")],["complement","modifier","subject"],"impractical for the educated to enjoy benefits from ambition","for the educated说明谁享受好处；选项判断享受本身不切实际。",[],true);
  answer=make(old.answer!,[sub("It","is","形式主语，后置to结构给真实内容。"),pred("is","It","系动词。"),...options.C.beginnerSyntax!.components],["subject","predicate","complement","subject"],"It is dishonest to deny ambition after the fulfillment of the goal","to deny...作真正主语，dishonest为表语；after接名词短语。");
 }else if(question.id===29){
  prompt=make(old.prompt!,[sub("Some people","do not openly admit","不定数量人群，非所有人。"),pred("do not openly admit","Some people","否定公开承认，不否定拥有抱负。"),c("they have ambition","省略that的内容从句","宾语从句","admit","真实拥有的内容。",[sub("they","have","回指Some people。"),pred("have","they","拥有。"),obj("ambition","have","所拥有内容。")]),c("because","原因连接词","待补原因标记","do not openly admit","原题只有because，原因主体由选项补足。")],["subject","predicate","object","connector"],"Some people do not openly admit they have ambition because","admit后宾语从句省略that，because只给下一层连接，不虚构原因。",[cl("they have ambition","宾语从句","that（省略）","作admit内容","they","have",[["宾语","ambition"]])]);
  options.A=make(o.A!,[sub("they","think","主语指那些人。"),pred("think","they","think of...as把对象归类。"),mod("of it","think","of的宾语it指抱负。"),c("as immoral","形容词补足","对象评价补足","it","说明他们自己给抱负的道德判断。")],["subject","predicate","modifier","complement"],"they think of it as immoral","think of A as B中as补充对A的看法，不能混同被别人认为如何。");
  options.B=make(o.B!,[sub("their pursuits","are not","复数名词主语，指追求对象。"),pred("are not","their pursuits","否定系词判断。"),comp("fame or wealth","are not","or连接两个名词表语，否定两类追求。")],["subject","predicate","complement"],"their pursuits are not fame or wealth","pursuits是名词而非pursue谓语；句意是否认追求名利。");
  options.C=make(o.C!,[sub("ambition","is not","抱负作主语。"),pred("is not","ambition","否定系词判断。"),comp("closely related","is not","related为关系状态，closely给关联程度。"),mod("to material benefits","related","to介词接关联对象，不是不定式。")],["subject","predicate","complement","modifier"],"ambition is not closely related to material benefits","be related to为状态结构，否定密切相关，不表示抱负不存在。");
  const wanting=(initial:string)=>[sub(initial,"do not want","指不坦承者。"),pred("do not want",initial,"否定所希望的外在形象。"),infinitive("to appear greedy and contemptible","want","appear为系动词性不定式，两个形容词作内部表语。",[c("appear","不定式系动词","非谓语中心","to appear","显得，谈他人眼中的形象。"),comp("greedy and contemptible","appear","贪婪而可鄙，两者并列。")])];
  options.D=make(o.D!,wanting("they"),["subject","predicate","object"],"they do not want to appear greedy and contemptible","want后的不定式保留appear显得，不能直接译为他们本质如何。");
  answer=make(old.answer!,wanting("They"),["subject","predicate","object"],"They do not want to appear greedy and contemptible","to appear说明所不愿呈现的形象，两形容词是appear的表语。");
 }else{
  const inner=[sub("ambition","should be maintained","被维护的对象。"),pred("should be maintained","ambition","情态被动，should表应然。")];
  prompt=make(old.prompt!,[mod("From the last paragraph","can be drawn","限定推论依据为最后一段。"),sub("the conclusion","can be drawn","结论是被推出的对象。"),pred("can be drawn","the conclusion","情态被动，draw a conclusion的被动式。"),c("that ambition should be maintained","that内容从句","同位语从句","the conclusion","内容解释conclusion，因较长放在谓语之后。",[c("that","连接词","内容标记","conclusion","非结果so...that，也不在内部作成分。"),...inner])],["modifier","subject","predicate","modifier"],"the conclusion can be drawn that ambition should be maintained","that解释结论内容，是后置同位语从句；方式由选项补足。",[cl("that ambition should be maintained","同位语从句","that","解释conclusion","ambition","should be maintained",[])]);
  const pairs:Record<string,[string,string,string]>={A:["secretly","and vigorously","秘密而有力地"],B:["openly","and enthusiastically","公开而热情地"],C:["easily","and momentarily","轻易而短暂地"],D:["verbally","and spiritually","口头而精神层面地"]};
  for(const [key,[first,second,meaning]] of Object.entries(pairs)) options[key]=make(o[key as "A"|"B"|"C"|"D"]!,[c(first,"副词","方式状语","maintained",`${meaning}的第一项方式。`),c(second,"并列连接及副词","并列方式状语","maintained","and连接第二种方式，不构成新谓语。")],["modifier","modifier"],`${first} ${second}`,"两个副词并列修饰被动维护的方式，整个选项无独立主谓。",[],true);
  answer=make(old.answer!,[sub("Ambition","should be maintained","抱负为被维护者。"),pred("should be maintained","Ambition","情态被动。"),...options.B.beginnerSyntax!.components],["subject","predicate","modifier","modifier"],"Ambition should be maintained openly and enthusiastically","两个并列副词修饰维护方式；应然结论需由最后一段立场推出。");
 }
 return {prompt,options,answer};
}
