import type { PhraseKnowledge, WordKnowledge } from "./knowledge-base";

type Structure = PhraseKnowledge["structures"][number];

function guide(
  key: string,
  canonical: string,
  type: string,
  meaning: string,
  summary: string,
  grammarRole: string,
  rule = summary,
  examples?: Structure["examples"],
  pitfalls?: string[],
): PhraseKnowledge {
  return {
    key,
    canonical,
    type,
    meaning,
    summary,
    grammarRole,
    structures: [{ pattern: canonical, meaning, rule, examples }],
    pitfalls,
  };
}

export const passage1PhraseGuides: Record<string, PhraseKnowledge> = {
  "history-of-success": guide("history-of-success", "a history of + n.", "名词结构", "一段……的历史 / 长期经历", "history 在此指长期积累的经历，of 后说明经历的内容。", "主语中心名词短语", "of 后接名词或动名词；long、effortless 等形容词修饰 success。", [{ english: "The firm has a long history of innovation.", chinese: "这家公司有悠久的创新历史。" }]),
  "dreadful-handicap": guide("dreadful-handicap", "a dreadful handicap", "名词搭配", "一种严重而可怕的障碍", "handicap 指妨碍继续发展的不利条件；dreadful 强调严重程度。", "系动词后的名词表语", "形容词 dreadful 前置修饰中心名词 handicap。"),
  "if-past-participle": guide("if-past-participle", "if + past participle", "状语从句省略", "如果被……", "当条件从句主语与主句指代一致，且从句含 be 时，可省略主语和 be。", "条件状语", "完整形式为 if + 主语 + be + 过去分词；只有省略后不会造成主语歧义时才使用。", [{ english: "If properly managed, the problem can become an opportunity.", chinese: "如果处理得当，这个问题可以转化为机会。" }]),
  "driving-force": guide("driving-force", "a driving force", "名词搭配", "推动力；驱动力", "指促使某种发展、变化或行动发生的主要力量。", "名词表语", "driving 作形容词，force 为中心名词；常与 behind 搭配说明推动对象。", [{ english: "Competition can be a driving force behind innovation.", chinese: "竞争可以成为创新背后的推动力。" }]),
  "enter-period": guide("enter-period", "enter + a period / stage", "动词搭配", "进入某个时期 / 阶段", "enter 是及物动词，直接接 period，不需要 into。", "时间从句中的谓语宾语结构", "表示进入具体时期时通常用 enter sth；enter into 多用于协议、讨论或关系。"),
  "after-end-of": guide("after-end-of", "after the end of + event", "时间结构", "在某事件结束之后", "after 引出时间，the end of 说明哪一事件的结束。", "时间状语", "event 使用名词；专有历史事件如 the Second World War 保留冠词和大写。"),
  "times-comparative": guide("times-comparative", "A + be + times + comparative + than B", "倍数比较", "A 比 B 大 / 多若干倍", "先找倍数，再找比较级及 than 后的比较对象。", "后置比较成分", "A、B 必须具有可比性；原文 competitor 代指 competitor's market。", [{ english: "Its market is three times larger than its rival's.", chinese: "它的市场比竞争对手的大三倍。" }], ["不要把 than 后对象误读为 A 自身过去的规模。"]),
  "participle-result": guide("participle-result", "clause, giving + object + complement", "现在分词结构", "前述情况由此给……带来……", "giving 的逻辑主语是前面整件事，表示自然结果。", "现在分词结果状语", "若分词表示结果，其逻辑主语通常是前面主句内容，而非紧邻名词。"),
  "worlds-best": guide("worlds-best", "the world's best", "所有格与最高级", "世界上最优秀的人或事物", "world's 用名词所有格限定范围，best 名词化表示最优秀者。", "系动词表语", "最高级前通常用 the；best 后省略了可由上下文恢复的名词。"),
  "most-skilled": guide("most-skilled", "the most + adjective", "最高级结构", "最……的", "the most skilled 与前面的 the world's best 平行；原句省略重复的 were。", "省略分句中的表语", "多音节形容词用 most 构成最高级，并通常加 the。"),
  "beyond-dreams": guide("beyond-dreams", "beyond the dreams of sb", "程度搭配", "超出某人的想象", "beyond 表示程度越过想象边界，修饰 prosperous。", "程度状语", "of 后接产生想象的人；不要逐字译为“在梦想之外”。"),
  "whose-clause": guide("whose-clause", "noun + whose + noun + clause", "定语从句", "……的某人 / 某物，其……", "whose 引导定语从句并表示所属；whose + noun 在从句中充当成分。", "后置定语", "先找 whose 的先行词，再判断 whose 后名词在从句中的句法位置。", [{ english: "The countries whose economies were damaged recovered slowly.", chinese: "经济遭受破坏的国家复苏缓慢。" }]),
  "it-inevitable-that": guide("it-inevitable-that", "It is/was inevitable that + clause", "形式主语结构", "……是不可避免的", "it 是形式主语，that 从句是真正主语。", "主句 + 真正主语从句", "that 通常不能换成 which；从句内容承担被评价的事件。"),
  "should-have-narrowed": guide("should-have-narrowed", "evaluative adjective + that + should have done", "评价性 should", "某事竟会 / 必然已经发生", "inevitable 后的 should 带有说话者评价语气，本句不表示义务。", "主语从句谓语", "should have done 指向已经发生或从过去视角看必然的变化；需结合评价词翻译。"),
  "as-change": guide("as-change", "as + clause", "状语从句", "随着……；因为……", "本句 as 同时呈现时间推进和原因：其他国家变富，美国优势随之收窄。", "时间兼原因状语", "as 的逻辑要依上下文确定，不能一律译为“当”。"),
  "sentence-adverb": guide("sentence-adverb", "sentence adverb + clause", "句子副词", "同样不可避免地……", "Just as inevitably 承接上一句的 inevitable，评价整个后续分句。", "连接性句子状语", "句子副词修饰整个判断，通常用逗号与主干隔开。"),
  "retreat-from": guide("retreat-from", "the retreat from + position / dominance", "名词搭配", "从某地位退却；失去优势地位", "from 引出退出的原有位置。", "主语名词短语", "retreat 可作名词或动词；名词后常接 from。"),
  "prove-adjective": guide("prove-adjective", "prove + adjective", "系表结构", "结果是 / 被证明是……", "prove 在此是系动词，painful 为表语，不是“证明某物”的及物用法。", "谓语 + 表语", "prove 后直接接形容词时常译为“结果表明是”。"),
  "by-mid-1980s": guide("by-mid-1980s", "by + past time", "时间结构", "到过去某时为止", "by 设置过去时间界限，常与过去完成时搭配。", "时间状语", "by 表截止点；in 只表示发生于某时期，不能表达“到……为止”。"),
  "find-oneself-loss": guide("find-oneself-loss", "find oneself at a loss over sth", "动词搭配", "发现自己对某事感到困惑 / 不知所措", "oneself 是宾语，at a loss 是宾补，over 引出困惑对象。", "谓语 + 宾语 + 宾补 + 对象", "at a loss 此处不是“亏损”；over 后接造成困惑的问题。", [{ english: "Many firms found themselves at a loss over the new rules.", chinese: "许多企业面对新规则不知所措。" }]),
  "fading-competitiveness": guide("fading-competitiveness", "fading + competitiveness", "名词短语", "不断减弱的竞争力", "fading 是现在分词形容词，强调竞争力正在逐渐消退。", "介词宾语中的名词短语", "competitiveness 通常为不可数名词；fading 表持续变化。"),
  "such-as": guide("such-as", "such as + examples", "举例结构", "例如；诸如", "such as 后列举前一类别的实例。", "插入举例成分", "列举项应属于前面概括词的范围；不要与表示结果的 so that 混淆。"),
  "had-shrunk-vanished": guide("had-shrunk-vanished", "had + past participle A or B", "过去完成时并列", "已经A或B", "shrunk 与 vanished 共用助动词 had，表示到过去时间点之前已发生。", "并列谓语", "并列过去分词必须与共同的 had 在时态和语态上匹配。"),
  "in-face-of": guide("in-face-of", "in the face of + difficulty / pressure", "介词习语", "面对困难、压力或竞争", "表示在不利情形面前发生某动作或结果。", "情境 / 原因状语", "the 通常不能省略；of 后接名词或动名词。"),
  "there-be-left": guide("there-be-left", "there be + number + noun + left", "存在句", "还剩下若干……", "left 是 leave 的过去分词作后置定语，真正主语位于 be 后。", "存在句主干", "be 的单复数通常与后面名词一致；left 不是“左边的”。"),
  "there-be-none": guide("there-be-none", "there be + none", "存在句", "一个也没有", "none 代替前文已经明确的复数或不可数对象。", "括号补充句主干", "none 可按所指对象理解为单数或复数；本句用 there is none。"),
  "passive-buy-by": guide("passive-buy-by", "company A + be bought by company B", "被动语态", "A公司被B公司收购", "buy 在企业语境中表示收购；by 引出收购方。", "被动谓语 + 施事者", "不要只按日常“购买商品”理解 buy。"),
  "foreign-made": guide("foreign-made", "foreign-made + product", "复合形容词", "外国制造的产品", "foreign-made 整体前置修饰商品名词。", "主语名词短语中的定语", "复合形容词置于名词前通常保留连字符。"),
  "sweep-into": guide("sweep-into", "sweep into + market / place", "动词搭配", "大举涌入；席卷进入", "用动态比喻表示大量产品迅速进入并占领市场。", "进行时谓语", "语气强于普通 enter，包含数量大、速度快的含义。"),
  "domestic-market": guide("domestic-market", "the domestic market", "经济搭配", "国内市场；本国市场", "domestic 根据 market 译为“国内的”，而非“家庭的”。", "介词 into 的宾语", "需结合中心名词判断 domestic 的具体中文义。"),
  "machine-tool-industry": guide("machine-tool-industry", "machine-tool industry", "复合名词", "机床行业", "machine tool 作前置定语修饰 industry；定语形式常带连字符。", "主语名词短语", "不要把 machine 和 tool 分别修饰 industry。"),
  "on-ropes": guide("on-ropes", "be on the ropes", "习语", "处境危急；濒临失败", "源于拳击选手被逼到围绳边，但尚未等于彻底倒闭。", "系动词表语", "不能按字面译为“在绳子上”，也不能夸大为已经 collapse。", [{ english: "The old company was on the ropes but had not collapsed.", chinese: "这家老公司岌岌可危，但尚未倒闭。" }]),
  "for-a-while": guide("for-a-while", "for a while", "时间短语", "一段时间；一度", "表示某种判断或状态持续了一段有限时间。", "时间状语", "while 在这里是名词；与引导对比从句的 while 不同。"),
  "look-as-though": guide("look-as-though", "it look(s) as though + clause", "表象判断结构", "看起来仿佛……", "it 是形式主语，as though 从句承载看起来可能发生的内容。", "主句 + 表语从句", "陈述有现实迹象的判断时不必机械使用虚拟语气。"),
  "making-of": guide("making-of", "the making of + product", "名词化结构", "……的制造；……制造业", "making 是动名词名词化，of 后接被制造的产品。", "as though 从句主语", "根据语境可译为制造过程或制造业。"),
  "heart-of": guide("heart-of", "be / sit at the heart of sth", "介词习语", "处于……的核心", "heart 比喻事物最关键的位置。", "定语从句谓语补足", "通常与 at 和 of 连用，不能只记单个 heart。"),
  "going-to-casualty": guide("going-to-casualty", "be going to be the next casualty", "将来与比喻", "看起来将成为下一个受害者 / 牺牲品", "be going to 基于当时迹象预测；casualty 比喻可能衰落的行业。", "as though 从句谓语", "表示当时预测，不等于事情已经发生。"),
  "all-of-this": guide("all-of-this", "all of this", "总括指代", "所有这一切", "总括回指前文列举的多个工业衰退现象。", "主语", "this 指一个整体局势，不要只回指紧邻的单句。"),
  "crisis-confidence": guide("crisis-confidence", "a crisis of confidence", "名词搭配", "信心危机", "of 引出危机的具体内容。", "cause 的宾语", "confidence 在此是社会和经济信心，不只是个人自信。"),
  "stop-take-granted": guide("stop-take-granted", "stop taking A for granted", "动词搭配", "不再把A视为理所当然", "stop doing 表停止原有行为；take A for granted 必须整体识别。", "谓语 + 动名词宾语", "stop to do 是停下去做另一事，与 stop doing 不同。", [{ english: "People stopped taking growth for granted.", chinese: "人们不再把增长视为理所当然。" }]),
  "way-of-doing": guide("way-of-doing", "one's way of doing sth", "名词结构", "某人做某事的方式", "of doing 后置修饰 way，说明具体做事方式。", "宾语从句主语", "of 是介词，后接 doing；也可用 way to do，但侧重点略有不同。"),
  "be-failing": guide("be-failing", "be failing", "进行时状态", "正在失效 / 走向失败", "进行时强调经营方式逐渐显露失败迹象。", "宾语从句谓语", "fail 可表示人失败、系统失灵或方法无效；需按主语判断。"),
  "would-begin-fall": guide("would-begin-fall", "would therefore shortly begin to fall", "过去将来与因果", "因此不久将开始下降", "would 是过去视角中的将来，therefore 表因果，shortly 表时间很近。", "第二个宾语从句谓语", "副词位置可调整，但逻辑依次为“因此—不久—开始下降”。"),
  "as-well": guide("as-well", "as well", "句末副词短语", "也；同样", "放在肯定句或陈述句末补充同类信息。", "句末补充状语", "不要与 as well as 混淆；后者可连接名词或结构。"),
  "one-after-another": guide("one-after-another", "one + singular noun + after another", "反复结构", "一个接一个；接连不断", "用单数名词表示同类事件连续发生。", "bring 的宾语", "another 前通常不再重复名词；若改用复数可说 one after the other。"),
  "inquiry-series-into": guide("inquiry-series-into", "one inquiry after another into + issue / cause", "反复调查结构", "接连对某问题 / 原因展开调查", "one inquiry after another 表示调查接连发生，into 引出每次调查深入考察的对象。", "bring 的宾语及其后置介词补足语", "先识别 one...after another 的反复关系，再把 into 后内容连回 inquiry；不要把 into 误连到 another。"),
  "inquiry-into": guide("inquiry-into", "inquiry into + issue / cause", "名词搭配", "对某问题 / 原因的调查", "into 引出深入调查的对象。", "后置介词补足语", "不能用 inquiry of 表同样的调查对象关系。"),
  "industrial-decline": guide("industrial-decline", "industrial decline", "经济搭配", "工业衰退", "industrial 修饰 decline，指产业竞争力、产能或市场地位下降。", "of 后的名词短语", "decline 是过程性下降，不一定等于 collapse。"),
  "sensational-findings": guide("sensational-findings", "sometimes sensational findings", "名词短语", "有时颇为耸动的调查结论", "sometimes 只修饰 sensational；findings 指调查所得结论。", "主语", "finding 在研究语境中不是“寻找”，而是可数的发现/结论。"),
  "filled-warnings": guide("filled-warnings", "be filled with warnings about sth", "被动搭配", "充满对某事的警告", "with 引出内容，about 引出警告对象。", "被动谓语 + 内容补足", "不要漏掉两个介词各自不同的功能。"),
  "competition-overseas": guide("competition-overseas", "competition from overseas", "经济搭配", "来自海外的竞争", "from 引出竞争来源，growing 强调程度不断增强。", "about 的宾语", "overseas 在此是副词，不需要再加 countries。"),
  "how-exclamation": guide("how-exclamation", "How + subject + verb!", "感叹句", "……发生了多么大的变化！", "How 修饰隐含的变化程度，后面保持陈述语序。", "段落转折感叹句", "不是疑问句，不倒装，也不要求回答方式。"),
  "look-back-on": guide("look-back-on", "look back on + period / experience", "动词短语", "回顾某段时期 / 经历", "on 后接回顾对象。", "谓语动词短语", "look back 单独表示回头看；加 on 后常指回顾过去。"),
  "years-solid-growth": guide("years-solid-growth", "a period / years of solid growth", "经济搭配", "一段时期的稳定增长", "of 后说明这段时间所经历的经济状态。", "look back on 的宾语", "solid 在此是“稳健、实在”，不是“固体的”。"),
  "while-contrast-progressive": guide("while-contrast-progressive", "while + contrasting clause", "对比从句", "而……；与此相反……", "while 对照美国增长与日本持续挣扎。", "对比状语从句", "此处不是单纯“当……时”；完成进行时强调状态持续至参照时间。"),
  "attribute-to": guide("attribute-to", "attribute A (solely) to B", "归因结构", "把A（完全）归因于B", "A 是结果，to 后的 B 是被认为的原因。", "谓语 + 宾语 + 原因补足", "to 是介词，后接名词或 doing；不要把因果方向写反。", [{ english: "Few observers attribute the recovery solely to luck.", chinese: "很少有观察者把复苏完全归因于运气。" }]),
  "such-noun-as": guide("such-noun-as", "such + noun + as A or B", "举例结构", "诸如A或B这样的……", "such 限定类别名词，as 引出具体例子。", "to 后的原因名词短语", "注意 as 前必须有被举例的类别中心词。"),
  "devalued-dollar": guide("devalued-dollar", "a devalued currency", "经济搭配", "贬值的货币", "devalued 是过去分词形容词，说明货币对外价值已降低。", "as 后列举的原因", "devalue 常指官方或市场导致货币价值下降，与 depreciation 语境需区分。"),
  "business-cycle-turn": guide("business-cycle-turn", "the turning of the business cycle", "经济结构", "经济周期的转向", "turning 指经济由一个周期阶段转入另一个阶段。", "as 后列举的原因", "business cycle 是整体术语，不能把 business 单独译为一家企业。"),
  "self-doubt-noun": guide("self-doubt-noun", "self-doubt", "复合名词", "自我怀疑", "self- 与 doubt 构成不可数抽象名词。", "主语", "通常不加冠词；与 confidence、pride 等心理状态词对照。"),
  "yield-to": guide("yield-to", "A yield to B", "动词搭配", "A让位于B；A被B取代", "to 是介词，B 为后来占据主导的状态。", "现在完成时谓语", "也可表示向压力屈服；本句强调状态替代。"),
  "change-structure": guide("change-structure", "change one's / its structure", "动词搭配", "改变自身结构；进行结构调整", "change 直接接 structure 作宾语。", "引语中的并列谓语", "这是受访者对复苏原因的解释，不自动代表作者立场。"),
  "go-on-diet": guide("go-on-diet", "go on a diet", "习语 / 比喻", "开始节食；比喻精简机构和成本", "文中把美国工业拟人化，表示削减冗余、提高效率。", "引语中的并列谓语", "商业语境应译出比喻含义，不能只译“节食”。"),
  "learn-be-adjective": guide("learn-be-adjective", "learn to be + adjective", "不定式搭配", "逐渐学会变得……", "to be 后接形容词表语，说明通过学习获得的新特征。", "引语中的并列谓语", "learn 后的不定式表示习得结果；quick-witted 不能拆成两个独立修饰词。"),
  "according-to-person": guide("according-to-person", "according to + person / source", "引述结构", "据某人 / 某资料所说", "明确标注观点来源，使其与作者立场区分。", "引语来源状语", "通常不用 according to me 表“我认为”；表达本人意见更常用 in my opinion。"),
  "make-proud": guide("make-proud", "make sb proud to do / of sth", "使役结构", "使某人因……感到自豪", "sb 是宾语，proud 是宾补；to do 或 of sth 说明自豪的原因。", "引语主干", "make 后宾补形容词前不加 to be。"),
  "see-how-clause": guide("see-how-clause", "see how + subject + verb", "宾语从句", "看到……如何 / 多么……", "how 从句作 see 的宾语，并保持陈述语序。", "原因不定式中的宾语从句", "how 可能强调方式或程度，需结合谓语和上下文。"),
  "think-tank-apposition": guide("think-tank-apposition", "institution, a think-tank in place", "同位语结构", "某机构，即位于某地的一家智库", "逗号后的名词短语补充解释前面的机构。", "非限制性同位语", "think-tank 为可数复合名词，通常保留连字符。"),
  "look-back-as": guide("look-back-as", "look back on A as B", "评价结构", "回顾A并将其视为B", "on 后接回顾对象 A，as 后接后来给出的评价 B。", "believe 的宾语从句谓语", "不要把 as 错连到 period 内部；它引出对该时期的评价。"),
  "golden-age": guide("golden-age", "a golden age of + field", "名词搭配", "某领域的黄金时代", "指某领域最繁荣、成就最突出的时期。", "as 后的宾语补足", "golden 为比喻义，不表示材料真由黄金制成。"),
  "computer-age": guide("computer-age", "the computer age", "时代搭配", "计算机时代", "指计算机技术成为社会和产业核心的时代。", "of 后名词短语中的中心表达", "computer 作前置定语修饰 age。"),
};

export const passage1PhraseAliases: Record<string, string> = {
  "a history of long and effortless success": "history-of-success",
  "a dreadful handicap": "dreadful-handicap",
  "if properly handled": "if-past-participle",
  "a driving force": "driving-force",
  "entered just such a glowing period": "enter-period",
  "after the end of the second world war": "after-end-of",
  "eight times larger than any competitor": "times-comparative",
  "giving its industries unparalleled economies of scale": "participle-result",
  "unparalleled economies of scale": "participle-result",
  "the world's best": "worlds-best",
  "the most skilled": "most-skilled",
  "prosperous beyond the dreams of": "beyond-dreams",
  "whose economies the war had destroyed": "whose-clause",
  "it was inevitable that": "it-inevitable-that",
  "this primacy should have narrowed": "should-have-narrowed",
  "as other countries grew richer": "as-change",
  "just as inevitably": "sentence-adverb",
  "the retreat from predominance": "retreat-from",
  "proved painful": "prove-adjective",
  "by the mid-1980s": "by-mid-1980s",
  "found themselves at a loss over": "find-oneself-loss",
  "fading industrial competitiveness": "fading-competitiveness",
  "such as consumer electronics": "such-as",
  "had shrunk or vanished": "had-shrunk-vanished",
  "in the face of foreign competition": "in-face-of",
  "there was only one american television maker left": "there-be-left",
  "there is none": "there-be-none",
  "was bought by south korea's lg electronics": "passive-buy-by",
  "foreign-made cars and textiles": "foreign-made",
  "were sweeping into": "sweep-into",
  "the domestic market": "domestic-market",
  "machine-tool industry": "machine-tool-industry",
  "on the ropes": "on-ropes",
  "for a while": "for-a-while",
  "it looked as though": "look-as-though",
  "the making of semiconductors": "making-of",
  "sat at the heart of": "heart-of",
  "was going to be the next casualty": "going-to-casualty",
  "all of this": "all-of-this",
  "a crisis of confidence": "crisis-confidence",
  "stopped taking prosperity for granted": "stop-take-granted",
  "their way of doing business": "way-of-doing",
  "was failing": "be-failing",
  "would therefore shortly begin to fall": "would-begin-fall",
  "as well": "as-well",
  "one inquiry after another": "one-after-another",
  "one inquiry after another into the causes of": "inquiry-series-into",
  "inquiry into the causes of": "inquiry-into",
  "america's industrial decline": "industrial-decline",
  "sometimes sensational findings": "sensational-findings",
  "were filled with warnings about": "filled-warnings",
  "the growing competition from overseas": "competition-overseas",
  "how things have changed": "how-exclamation",
  "look back on": "look-back-on",
  "five years of solid growth": "years-solid-growth",
  "while japan has been struggling": "while-contrast-progressive",
  "attribute this solely to": "attribute-to",
  "such obvious causes as": "such-noun-as",
  "a devalued dollar": "devalued-dollar",
  "the turning of the business cycle": "business-cycle-turn",
  "self-doubt": "self-doubt-noun",
  "yielded to blind pride": "yield-to",
  "has changed its structure": "change-structure",
  "has gone on a diet": "go-on-diet",
  "has learnt to be more quick-witted": "learn-be-adjective",
  "according to richard cavanaugh": "according-to-person",
  "makes me proud to be an american": "make-proud",
  "see how our businesses are improving their productivity": "see-how-clause",
  "a think-tank in washington, dc": "think-tank-apposition",
  "look back on this period as": "look-back-as",
  "a golden age of business management": "golden-age",
  "the new computer age": "computer-age",
};

export const passage1CollocationGlosses: Record<string, { meaning: string; note?: string }> = Object.fromEntries(
  Object.entries(passage1PhraseAliases).map(([source, key]) => {
    const entry = passage1PhraseGuides[key];
    return [source, { meaning: entry.meaning, note: entry.summary }];
  }),
);

export const passage1FamilyGlosses: Record<string, string> = {
  accomplishment: "成就；完成的任务",
  american: "美国人；美国的",
  america: "美国",
  attain: "达到；获得",
  compete: "竞争",
  competition: "竞争",
  competitor: "竞争者",
  competitive: "有竞争力的",
  competitiveness: "竞争力",
  consume: "消费；消耗",
  consumption: "消费；消耗量",
  cooperate: "合作",
  cooperative: "合作的；合作社",
  devaluation: "贬值",
  develop: "发展；开发",
  developed: "发达的；已发展的",
  developing: "发展中的",
  economic: "经济的",
  economy: "经济；规模经济",
  economical: "节约的；经济实惠的",
  economist: "经济学家",
  educate: "教育",
  educational: "教育的",
  effort: "努力",
  effortlessly: "毫不费力地",
  industrial: "工业的",
  industry: "工业；行业",
  industrialization: "工业化",
  industrialize: "使工业化",
  invention: "发明",
  inventor: "发明者",
  inventive: "有创造力的",
  make: "制造；使得",
  manage: "管理；设法做到",
  manager: "管理者",
  managerial: "管理的",
  predominant: "占主导地位的",
  predominate: "占优势",
  pride: "自豪；自负",
  proudly: "自豪地",
  produce: "生产",
  product: "产品",
  productive: "高产的；富有成效的",
  productivity: "生产率",
  proper: "恰当的",
  property: "财产；性质",
  prosper: "繁荣",
  prosperity: "繁荣",
  prosperous: "繁荣的",
  science: "科学",
  scientific: "科学的",
  sole: "唯一的",
  solely: "仅仅",
  structure: "结构；组织",
  grow: "增长；逐渐变得",
  succeed: "成功",
  restructuring: "重组",
  revive: "复苏；使恢复",
  unite: "联合；团结",
  unity: "团结；统一",
  govern: "治理；统治",
  governmental: "政府的",
  warn: "警告",
  work: "工作",
  workforce: "劳动力队伍",
};

export const passage1WordKnowledge: Record<string, WordKnowledge> = {
  few: {
    grammarRole: "限定词；修饰可数名词复数，带否定倾向",
    grammarSummary: "few 表示“几乎没有”；a few 表示“有一些”。第21句 Few Americans 是作者分析立场的关键范围限制。",
    structures: [{ pattern: "few + plural countable noun", meaning: "几乎没有……", rule: "不带 a 时语义偏否定；只能修饰可数名词复数。" }],
    pitfalls: ["不要把 few 误读成 a few。"],
  },
  whose: {
    grammarRole: "关系代词；在定语从句中表示所属",
    grammarSummary: "whose 可指人或物，后接名词；whose + noun 在从句中整体充当成分。",
    structures: passage1PhraseGuides["whose-clause"].structures,
  },
  while: {
    grammarRole: "从属连词；本句表示两种情况的对比",
    grammarSummary: "while 可表示“当……时”或“而/然而”；美国增长与日本挣扎并置时应判断为对比。",
    structures: passage1PhraseGuides["while-contrast-progressive"].structures,
  },
  should: {
    grammarRole: "情态动词；在评价性结构中表达预期或必然语气",
    grammarSummary: "inevitable that... should have done 中 should 不表示义务，应结合 inevitable 译为“必然会/竟会”。",
    structures: passage1PhraseGuides["should-have-narrowed"].structures,
  },
  there: {
    grammarRole: "存在句引导词；真正主语位于 be 后",
    grammarSummary: "there be 不按地点副词“那里”理解；be 的形式与后置主语和时态相配。",
    structures: passage1PhraseGuides["there-be-left"].structures,
  },
  attribute: {
    grammarRole: "及物动词；后接结果宾语与 to 原因补足语",
    grammarSummary: "attribute A to B 把A归因于B；因果方向不可倒置。",
    structures: passage1PhraseGuides["attribute-to"].structures,
  },
};
