import type { Question, SentenceAnalysis } from "./data";

export const passage1Sentences: SentenceAnalysis[] = [
  {
    id: "p1-s1",
    number: 1,
    text: "A history of long and effortless success can be a dreadful handicap, but, if properly handled, it may become a driving force.",
    chunks: [
      { text: "A history of long and effortless success", role: "subject" },
      { text: " can be", role: "predicate" },
      { text: " a dreadful handicap, ", role: "object" },
      { text: "but, ", role: "connector" },
      { text: "if properly handled, ", role: "condition" },
      { text: "it", role: "subject" },
      { text: " may become", role: "predicate" },
      { text: " a driving force.", role: "object" },
    ],
    trunk: "A history of success can be a handicap, but it may become a driving force.",
    layers: [
      { label: "并列主干", text: "A history ... can be a handicap, but it may become a driving force：成功史可能成为障碍，却也可能转化为动力" },
      { label: "省略条件", text: "if properly handled = if it is properly handled；省略了与主句相同的主语 it 和 be 动词" },
      { label: "指代关系", text: "it 回指前面的 a history of long and effortless success" },
    ],
    grammar: [
      "but 连接两个意义相反的判断，构成全文的核心转折：成功既可能是障碍，也可能是动力。",
      "if + 过去分词是状语从句省略，完整形式为 if it is properly handled。",
      "become 是系动词，后接名词短语 a driving force 作表语。",
    ],
    literal: "一段长期而不费力的成功历史可能是一种可怕的障碍，但是，如果被妥善处理，它也可能成为一种推动力量。",
    natural: "长期轻易获得成功的经历可能成为可怕的包袱；但若应对得当，它也能转化为前进的动力。",
    logic: "全文总论点。先提出“成功史的双重作用”，后文用美国经济由盛转衰再复苏的过程加以说明。",
    phrases: [
      "A history of long and effortless success",
      "a dreadful handicap",
      "if properly handled",
      "a driving force",
    ],
  },
  {
    id: "p1-s2",
    number: 2,
    text: "When the United States entered just such a glowing period after the end of the Second World War, it had a market eight times larger than any competitor, giving its industries unparalleled economies of scale.",
    chunks: [
      { text: "When the United States entered just such a glowing period after the end of the Second World War, ", role: "condition" },
      { text: "it", role: "subject" },
      { text: " had", role: "predicate" },
      { text: " a market eight times larger than any competitor, ", role: "object" },
      { text: "giving its industries unparalleled economies of scale.", role: "modifier" },
    ],
    trunk: "it had a market",
    layers: [
      { label: "时间从句", text: "When the United States entered ... period：当美国进入这样一个辉煌时期时" },
      { label: "倍数比较", text: "eight times larger than any competitor 后置修饰 market，比较的是美国市场与任何竞争者的市场" },
      { label: "结果分词", text: "giving ... 是现在分词结果状语，说明巨大市场由此给工业带来的规模经济优势" },
    ],
    grammar: [
      "such 回指上一句的 long and effortless success，just such 意为“正是这样的”。",
      "倍数表达为 A + be + 倍数 + 比较级 + than B；competitor 在此用其市场代替竞争者所拥有的市场。",
      "giving 的逻辑主语是前面整件事，而不是紧邻的 competitor。",
    ],
    literal: "第二次世界大战结束后，当美国进入正是这样一个辉煌时期时，它拥有一个比任何竞争者大八倍的市场，这给它的工业带来了无与伦比的规模经济。",
    natural: "二战结束后，美国进入了这样一个繁荣时期：其市场规模是任何竞争对手的八倍，使美国工业获得了无可比拟的规模经济优势。",
    logic: "开始列举美国战后几乎不费力便取得经济优势的客观条件。",
    phrases: [
      "entered just such a glowing period",
      "after the end of the Second World War",
      "eight times larger than any competitor",
      "giving its industries unparalleled economies of scale",
    ],
  },
  {
    id: "p1-s3",
    number: 3,
    text: "Its scientists were the world's best; its workers the most skilled.",
    chunks: [
      { text: "Its scientists", role: "subject" },
      { text: " were", role: "predicate" },
      { text: " the world's best; ", role: "object" },
      { text: "its workers", role: "subject" },
      { text: " the most skilled.", role: "object" },
    ],
    trunk: "Its scientists were the world's best; its workers (were) the most skilled.",
    layers: [
      { label: "前一分句", text: "Its scientists were the world's best：美国的科学家是世界上最优秀的" },
      { label: "平行省略", text: "its workers the most skilled = its workers were the most skilled；后半句省略了重复的 were" },
    ],
    grammar: [
      "分号连接两个关系紧密、结构平行的独立分句。",
      "第二个分句为避免重复省略 were；理解时必须把系动词补回。",
      "best 与 most skilled 都是最高级，the 不能随意省略。",
    ],
    literal: "它的科学家是世界上最优秀的；它的工人是技术最熟练的。",
    natural: "美国拥有世界一流的科学家和技术最娴熟的工人。",
    logic: "继续补充美国战后的科技与劳动力优势。",
    phrases: ["the world's best", "the most skilled"],
  },
  {
    id: "p1-s4",
    number: 4,
    text: "America and Americans were prosperous beyond the dreams of the Europeans and Asians whose economies the war had destroyed.",
    chunks: [
      { text: "America and Americans", role: "subject" },
      { text: " were", role: "predicate" },
      { text: " prosperous", role: "object" },
      { text: " beyond the dreams of the Europeans and Asians", role: "modifier" },
      { text: " whose economies the war had destroyed.", role: "modifier" },
    ],
    trunk: "America and Americans were prosperous.",
    layers: [
      { label: "程度修饰", text: "beyond the dreams of ... 修饰 prosperous，意为富裕程度超出欧亚人民的想象" },
      { label: "定语从句", text: "whose economies the war had destroyed 修饰 Europeans and Asians；whose economies 在从句中作 destroyed 的宾语" },
      { label: "时态先后", text: "had destroyed 表示经济遭战争摧毁发生在美国当时繁荣之前" },
    ],
    grammar: [
      "whose 可指人也可指物，表示所属关系；此处相当于 the economies of the Europeans and Asians。",
      "过去完成时 had destroyed 表示“过去的过去”。",
      "beyond one's dreams 是“超出某人的想象”，不能机械译成“在梦想之外”。",
    ],
    literal: "美国和美国人繁荣到了欧洲人和亚洲人梦想之外的程度，而战争已经摧毁了这些欧洲人和亚洲人的经济。",
    natural: "美国及其民众富裕得令经济遭战争摧毁的欧洲人和亚洲人难以想象。",
    logic: "以欧亚经济被毁作对照，点明美国战后优势很大程度来自竞争者受损；这是第11题的核心依据。",
    phrases: ["prosperous beyond the dreams of", "whose economies the war had destroyed"],
  },
  {
    id: "p1-s5",
    number: 5,
    text: "It was inevitable that this primacy should have narrowed as other countries grew richer.",
    chunks: [
      { text: "It", role: "subject" },
      { text: " was", role: "predicate" },
      { text: " inevitable", role: "object" },
      { text: " that this primacy should have narrowed", role: "object" },
      { text: " as other countries grew richer.", role: "condition" },
    ],
    trunk: "It was inevitable that this primacy should have narrowed.",
    layers: [
      { label: "形式主语", text: "It 是形式主语，真正主语是 that this primacy should have narrowed" },
      { label: "时间兼原因", text: "as other countries grew richer 表示随着其他国家日益富裕，也暗含优势缩小的原因" },
    ],
    grammar: [
      "It is/was inevitable that... 表示“……是不可避免的”。",
      "should have narrowed 在 inevitable 后带有“本来就必然如此”的语气，不译为“应该”。",
      "grow + 形容词比较级表示逐渐变得更……。",
    ],
    literal: "随着其他国家变得更加富裕，这种首要地位会缩小是不可避免的。",
    natural: "随着其他国家日益富裕，美国的领先优势必然会逐渐缩小。",
    logic: "从战后绝对优势转向优势收窄，开启第二段的衰退过程。",
    phrases: ["It was inevitable that", "this primacy should have narrowed", "as other countries grew richer"],
  },
  {
    id: "p1-s6",
    number: 6,
    text: "Just as inevitably, the retreat from predominance proved painful.",
    chunks: [
      { text: "Just as inevitably, ", role: "connector" },
      { text: "the retreat from predominance", role: "subject" },
      { text: " proved", role: "predicate" },
      { text: " painful.", role: "object" },
    ],
    trunk: "the retreat proved painful",
    layers: [
      { label: "承接副词", text: "Just as inevitably 承接上句：优势收窄不可避免，退出霸主地位带来的痛苦也同样不可避免" },
      { label: "系动词", text: "proved 在此不是“证明”，而是系动词“结果表明是”" },
    ],
    grammar: [
      "prove + adjective 可作系表结构，表示“结果是/被证明是……”。",
      "retreat from + 地位/立场表示从某种位置后退或退出。",
    ],
    literal: "同样不可避免的是，从主导地位的退却被证明是痛苦的。",
    natural: "同样不可避免的是，失去霸主地位的过程十分痛苦。",
    logic: "以概括句引出美国工业在20世纪80年代遭遇的具体困境。",
    phrases: ["Just as inevitably", "the retreat from predominance", "proved painful"],
  },
  {
    id: "p1-s7",
    number: 7,
    text: "By the mid-1980s Americans had found themselves at a loss over their fading industrial competitiveness.",
    chunks: [
      { text: "By the mid-1980s ", role: "modifier" },
      { text: "Americans", role: "subject" },
      { text: " had found", role: "predicate" },
      { text: " themselves", role: "object" },
      { text: " at a loss", role: "object" },
      { text: " over their fading industrial competitiveness.", role: "modifier" },
    ],
    trunk: "Americans had found themselves at a loss.",
    layers: [
      { label: "时间界限", text: "By the mid-1980s 与过去完成时 had found 搭配，表示到80年代中期为止已经形成的状态" },
      { label: "宾补结构", text: "find oneself + 状态：发现自己处于某种状态；at a loss 作宾语补足语" },
      { label: "原因对象", text: "over their fading industrial competitiveness 说明美国人因什么而茫然" },
    ],
    grammar: [
      "find oneself + 介词短语/形容词表示“不知不觉发现自己处于……”。",
      "at a loss 可表示困惑、不知所措，也可表示亏损；此处是前者。",
      "fading 是现在分词形容词，表示竞争力正在逐渐减弱。",
    ],
    literal: "到20世纪80年代中期，美国人已经发现自己面对正在减弱的工业竞争力而不知所措。",
    natural: "到20世纪80年代中期，面对不断下降的工业竞争力，美国人已感到茫然无措。",
    logic: "从国家地位转到民众心理，为第三段的信心危机埋下伏笔。",
    phrases: ["By the mid-1980s", "found themselves at a loss over", "fading industrial competitiveness"],
  },
  {
    id: "p1-s8",
    number: 8,
    text: "Some huge American industries, such as consumer electronics, had shrunk or vanished in the face of foreign competition.",
    chunks: [
      { text: "Some huge American industries, ", role: "subject" },
      { text: "such as consumer electronics, ", role: "modifier" },
      { text: "had shrunk or vanished", role: "predicate" },
      { text: " in the face of foreign competition.", role: "modifier" },
    ],
    trunk: "Some industries had shrunk or vanished.",
    layers: [
      { label: "举例插入", text: "such as consumer electronics 举例说明 huge American industries" },
      { label: "谓语并列", text: "had shrunk or vanished：已经萎缩或消失；两个过去分词共用 had" },
      { label: "情境原因", text: "in the face of foreign competition 表示面对国外竞争时发生的结果" },
    ],
    grammar: [
      "such as 用于列举同类实例，不等于表示假设的 such...as...。",
      "shrink–shrank–shrunk 是不规则变化；此处 shrunk 为过去分词。",
      "in the face of 常表示“面对困难/压力”。",
    ],
    literal: "一些大型美国工业，例如消费电子业，在国外竞争面前已经萎缩或消失。",
    natural: "面对外国竞争，美国一些大型产业——如消费电子业——已经萎缩甚至消失。",
    logic: "给出美国工业竞争力衰退的第一组事实证据。",
    phrases: ["such as consumer electronics", "had shrunk or vanished", "in the face of foreign competition"],
  },
  {
    id: "p1-s9",
    number: 9,
    text: "By 1987 there was only one American television maker left, Zenith.",
    chunks: [
      { text: "By 1987 ", role: "modifier" },
      { text: "there was", role: "predicate" },
      { text: " only one American television maker left, ", role: "subject" },
      { text: "Zenith.", role: "modifier" },
    ],
    trunk: "there was only one maker left",
    layers: [
      { label: "存在句", text: "there was ... left 表示“还剩下……”；真正主语是 one American television maker" },
      { label: "同位语", text: "Zenith 与 one American television maker 指同一对象，补充说明仅存厂商的名称" },
    ],
    grammar: [
      "there be + 名词 + left 是表示“剩余”的常见结构。",
      "left 在此是 leave 的过去分词作后置定语，意为“剩下的”，不是“左边的”。",
    ],
    literal: "到1987年，只剩下一家美国电视机制造商，即Zenith。",
    natural: "到1987年，美国电视机制造商只剩下Zenith一家。",
    logic: "用电视产业几乎消失的具体数字强化衰退程度。",
    phrases: ["there was only one American television maker left"],
  },
  {
    id: "p1-s10",
    number: 10,
    text: "(Now there is none: Zenith was bought by South Korea's LG Electronics in July.)",
    chunks: [
      { text: "(Now ", role: "modifier" },
      { text: "there is", role: "predicate" },
      { text: " none: ", role: "subject" },
      { text: "Zenith", role: "subject" },
      { text: " was bought", role: "predicate" },
      { text: " by South Korea's LG Electronics", role: "modifier" },
      { text: " in July.)", role: "modifier" },
    ],
    trunk: "there is none: Zenith was bought by LG Electronics.",
    layers: [
      { label: "冒号解释", text: "Now there is none 先给结果，冒号后说明原因：Zenith 已被韩国LG电子收购" },
      { label: "被动语态", text: "was bought by：被……收购；by 引出动作执行者" },
    ],
    grammar: [
      "none 代替 no American television maker，避免重复。",
      "buy 在企业语境中可表示“收购”，不是普通的购买商品。",
      "括号表示作者补充的较新信息，不改变主线。",
    ],
    literal: "（现在一家也没有了：Zenith在7月被韩国的LG电子收购。）",
    natural: "（如今连一家也不剩了：Zenith已于7月被韩国LG电子收购。）",
    logic: "补充说明美国电视制造业已从“仅剩一家”进一步变为“一家不剩”。",
    phrases: ["there is none", "was bought by South Korea's LG Electronics"],
  },
  {
    id: "p1-s11",
    number: 11,
    text: "Foreign-made cars and textiles were sweeping into the domestic market.",
    chunks: [
      { text: "Foreign-made cars and textiles", role: "subject" },
      { text: " were sweeping into", role: "predicate" },
      { text: " the domestic market.", role: "object" },
    ],
    trunk: "cars and textiles were sweeping into the market",
    layers: [
      { label: "复合形容词", text: "Foreign-made = made in foreign countries，作定语修饰 cars and textiles" },
      { label: "动态比喻", text: "sweep into 本义是席卷而入，这里形象表示大量快速进入并占领市场" },
    ],
    grammar: [
      "foreign-made 是“副词/形容词 + 过去分词”构成的复合形容词。",
      "过去进行时 were sweeping 强调当时持续发生并不断扩大的趋势。",
      "domestic 在此是“国内的”，不是“家庭的”。",
    ],
    literal: "外国制造的汽车和纺织品正在席卷进入国内市场。",
    natural: "外国汽车和纺织品正大举涌入美国国内市场。",
    logic: "直接证明美国汽车业失去了部分国内市场，是第12题D项的定位句。",
    phrases: ["Foreign-made cars and textiles", "were sweeping into", "the domestic market"],
  },
  {
    id: "p1-s12",
    number: 12,
    text: "America's machine-tool industry was on the ropes.",
    chunks: [
      { text: "America's machine-tool industry", role: "subject" },
      { text: " was", role: "predicate" },
      { text: " on the ropes.", role: "object" },
    ],
    trunk: "America's industry was on the ropes.",
    layers: [
      { label: "复合名词", text: "machine-tool industry 以 machine tool 作前置定语，指机床行业" },
      { label: "习语表语", text: "on the ropes 源于拳击，表示处境危急、濒临失败，但尚未彻底倒闭" },
    ],
    grammar: [
      "be on the ropes 是固定习语，不能按“在绳子上”直译。",
      "machine-tool 使用连字符构成复合定语。",
    ],
    literal: "美国的机床行业正处在拳击台围绳边的危急状态。",
    natural: "美国的机床行业也已岌岌可危。",
    logic: "继续列举衰退产业；“危急但未倒闭”用于排除第12题C项的 collapsed。",
    phrases: ["machine-tool industry", "on the ropes"],
  },
  {
    id: "p1-s13",
    number: 13,
    text: "For a while it looked as though the making of semiconductors, which America had invented and which sat at the heart of the new computer age, was going to be the next casualty.",
    chunks: [
      { text: "For a while ", role: "modifier" },
      { text: "it", role: "subject" },
      { text: " looked", role: "predicate" },
      { text: " as though the making of semiconductors, ", role: "object" },
      { text: "which America had invented and which sat at the heart of the new computer age, ", role: "modifier" },
      { text: "was going to be", role: "predicate" },
      { text: " the next casualty.", role: "object" },
    ],
    trunk: "it looked as though the making of semiconductors was going to be the next casualty.",
    layers: [
      { label: "主句框架", text: "it looked as though...：看起来仿佛……；it 是形式主语，as though 从句承载判断内容" },
      { label: "从句主干", text: "the making of semiconductors was going to be the next casualty：半导体制造业似乎将成为下一个受害者" },
      { label: "双重定语", text: "which America had invented 与 which sat at the heart... 并列修饰 semiconductors" },
      { label: "中心习语", text: "sit at the heart of 表示处于……的核心；casualty 比喻在竞争中受损或消失的产业" },
    ],
    grammar: [
      "look as though + 从句表示“看起来仿佛……”，此处陈述当时迹象，不必机械理解为虚拟语气。",
      "两个 which 定语从句共用先行词 semiconductors，and 连接平行结构。",
      "be going to 表示根据当时迹象判断即将发生，而本文并没有说半导体业已经被接管。",
    ],
    literal: "有一阵子，看起来仿佛半导体的制造——半导体由美国发明并位于新计算机时代的核心——将成为下一个受害者。",
    natural: "一度看来，连美国发明、又处于新计算机时代核心的半导体制造业，也将成为下一个牺牲品。",
    logic: "把工业危机推至高潮，同时用“看起来将会”而非既成事实排除第12题B项。",
    phrases: ["For a while", "it looked as though", "the making of semiconductors", "sat at the heart of", "was going to be the next casualty"],
  },
  {
    id: "p1-s14",
    number: 14,
    text: "All of this caused a crisis of confidence.",
    chunks: [
      { text: "All of this", role: "subject" },
      { text: " caused", role: "predicate" },
      { text: " a crisis of confidence.", role: "object" },
    ],
    trunk: "All of this caused a crisis.",
    layers: [
      { label: "总括指代", text: "All of this 回指上一段列举的工业衰退与外国竞争" },
      { label: "因果结论", text: "caused 明确建立产业困境与信心危机之间的因果关系" },
    ],
    grammar: [
      "all of + 指示代词构成主语时，此处按 this 所指的整体情况使用单数概念。",
      "a crisis of confidence 表示“信心危机”，of 说明危机的内容。",
    ],
    literal: "所有这些造成了一场信心的危机。",
    natural: "这一切引发了美国人的信心危机。",
    logic: "第三段首句总结前段后果，并转入美国人的反思。",
    phrases: ["All of this", "a crisis of confidence"],
  },
  {
    id: "p1-s15",
    number: 15,
    text: "Americans stopped taking prosperity for granted.",
    chunks: [
      { text: "Americans", role: "subject" },
      { text: " stopped taking", role: "predicate" },
      { text: " prosperity", role: "object" },
      { text: " for granted.", role: "modifier" },
    ],
    trunk: "Americans stopped taking prosperity for granted.",
    layers: [
      { label: "停止行为", text: "stop doing 表示停止原来一直在做的事；不是 stop to do“停下来去做另一件事”" },
      { label: "固定结构", text: "take A for granted：想当然地认为A理所应当存在" },
    ],
    grammar: [
      "take sth for granted 必须整体识别，不能把 granted 单独译成“被批准的”。",
      "prosperity 是抽象不可数名词，指经济繁荣状态。",
    ],
    literal: "美国人停止把繁荣当作理所当然。",
    natural: "美国人不再认为繁荣是理所当然、会永远持续的。",
    logic: "说明竞争压力打破了美国人的安逸心态，开始产生反省。",
    phrases: ["stopped taking prosperity for granted"],
  },
  {
    id: "p1-s16",
    number: 16,
    text: "They began to believe that their way of doing business was failing, and that their incomes would therefore shortly begin to fall as well.",
    chunks: [
      { text: "They", role: "subject" },
      { text: " began to believe", role: "predicate" },
      { text: " that their way of doing business was failing, ", role: "object" },
      { text: "and", role: "connector" },
      { text: " that their incomes would therefore shortly begin to fall as well.", role: "object" },
    ],
    trunk: "They began to believe that..., and that....",
    layers: [
      { label: "双宾语从句", text: "believe 后接两个由 and 连接的 that 从句：经营方式正在失败；收入也很快会下降" },
      { label: "方式结构", text: "their way of doing business：他们经营商业的方式；of doing 后置修饰 way" },
      { label: "因果副词", text: "therefore 把前一判断“经营失败”与后一预测“收入下降”连接起来" },
    ],
    grammar: [
      "两个 that 都引导 believe 的宾语从句；第二个 that 保留可清楚标出并列层级。",
      "would 是过去视角中的将来，即“他们当时认为收入随后会下降”。",
      "as well 位于句末表示“也”，对应前一个负面判断。",
    ],
    literal: "他们开始相信，他们做生意的方式正在失败，并且因此他们的收入不久也将开始下降。",
    natural: "他们开始认为，美国的经营方式出了问题，因此个人收入很快也会随之下降。",
    logic: "将信心危机具体化为对商业模式和未来收入的双重怀疑。",
    phrases: ["their way of doing business", "was failing", "would therefore shortly begin to fall", "as well"],
  },
  {
    id: "p1-s17",
    number: 17,
    text: "The mid-1980s brought one inquiry after another into the causes of America's industrial decline.",
    chunks: [
      { text: "The mid-1980s", role: "subject" },
      { text: " brought", role: "predicate" },
      { text: " one inquiry after another", role: "object" },
      { text: " into the causes of America's industrial decline.", role: "modifier" },
    ],
    trunk: "The mid-1980s brought inquiries.",
    layers: [
      { label: "时间拟人主语", text: "The mid-1980s brought... 不是年代主动做事，而是表示该时期出现了……" },
      { label: "反复结构", text: "one inquiry after another 表示调查接连不断" },
      { label: "调查对象", text: "inquiry into + 名词表示对某问题的调查；这里调查工业衰退的原因" },
    ],
    grammar: [
      "one + 单数名词 + after another 表示“一个接一个”。",
      "inquiry into 是固定搭配；into 说明深入调查的对象。",
      "decline 在此是名词，of America's industrial decline 修饰 causes。",
    ],
    literal: "20世纪80年代中期带来了一次又一次对美国工业衰退原因的调查。",
    natural: "20世纪80年代中期，人们接连调查美国工业衰退的原因。",
    logic: "说明信心危机并未只停留在情绪层面，而是推动了系统反思。",
    phrases: ["one inquiry after another", "one inquiry after another into the causes of", "America's industrial decline"],
  },
  {
    id: "p1-s18",
    number: 18,
    text: "Their sometimes sensational findings were filled with warnings about the growing competition from overseas.",
    chunks: [
      { text: "Their sometimes sensational findings", role: "subject" },
      { text: " were filled", role: "predicate" },
      { text: " with warnings", role: "object" },
      { text: " about the growing competition from overseas.", role: "modifier" },
    ],
    trunk: "Their findings were filled with warnings.",
    layers: [
      { label: "程度插入", text: "sometimes 修饰 sensational：调查结论有时具有耸动性" },
      { label: "被动搭配", text: "be filled with 表示充满；with 后接内容 warnings" },
      { label: "警告内容", text: "warnings about... 说明警告针对日益加剧的海外竞争" },
    ],
    grammar: [
      "finding 作可数名词常表示调查或研究得出的“发现/结论”。",
      "growing 是现在分词形容词，表示竞争在增强，而不是“种植竞争”。",
      "from overseas 中 overseas 为副词，表示竞争来自海外。",
    ],
    literal: "这些有时耸人听闻的调查结果充满了关于来自海外且日益增长的竞争的警告。",
    natural: "这些调查的结论有时颇为耸动，其中充斥着对海外竞争不断加剧的警告。",
    logic: "点出外部竞争形成压力，是“竞争推动反思与进步”这一隐含因果链的一环。",
    phrases: ["sometimes sensational findings", "were filled with warnings about", "the growing competition from overseas"],
  },
  {
    id: "p1-s19",
    number: 19,
    text: "How things have changed!",
    chunks: [
      { text: "How", role: "modifier" },
      { text: " things", role: "subject" },
      { text: " have changed!", role: "predicate" },
    ],
    trunk: "things have changed",
    layers: [
      { label: "感叹句", text: "How + 主语 + 谓语表示对变化程度的感叹，相当于“情况变化多大啊”" },
    ],
    grammar: [
      "这是 How 引导的感叹句，不是询问“怎样变化”的疑问句。",
      "现在完成时 have changed 强调过去变化造成的当前局面。",
    ],
    literal: "事情已经发生了多么大的变化！",
    natural: "情况已经大不一样了！",
    logic: "强烈转折标志，切换到20世纪90年代美国经济复苏。",
    phrases: ["How things have changed"],
  },
  {
    id: "p1-s20",
    number: 20,
    text: "In 1995 the United States can look back on five years of solid growth while Japan has been struggling.",
    chunks: [
      { text: "In 1995 ", role: "modifier" },
      { text: "the United States", role: "subject" },
      { text: " can look back on", role: "predicate" },
      { text: " five years of solid growth", role: "object" },
      { text: " while Japan has been struggling.", role: "condition" },
    ],
    trunk: "the United States can look back on growth while Japan has been struggling.",
    layers: [
      { label: "美国主句", text: "look back on five years of solid growth：回顾连续五年的稳定增长" },
      { label: "对比从句", text: "while Japan has been struggling：而日本一直举步维艰；while 表对比" },
    ],
    grammar: [
      "look back on + 过去经历表示“回顾”。",
      "while 在此不是单纯的“当……时”，而是连接美国增长与日本挣扎的鲜明对比。",
      "has been struggling 是现在完成进行时，强调从过去持续到1995年的艰难状态。",
    ],
    literal: "在1995年，美国可以回顾五年的稳定增长，而日本一直在艰难挣扎。",
    natural: "到1995年，美国已连续五年稳步增长，日本却仍在苦苦挣扎。",
    logic: "用美日对比呈现经济局势逆转，为后面的“盲目自豪”提供背景。",
    phrases: ["look back on", "five years of solid growth", "while Japan has been struggling"],
  },
  {
    id: "p1-s21",
    number: 21,
    text: "Few Americans attribute this solely to such obvious causes as a devalued dollar or the turning of the business cycle.",
    chunks: [
      { text: "Few Americans", role: "subject" },
      { text: " attribute", role: "predicate" },
      { text: " this", role: "object" },
      { text: " solely to such obvious causes as a devalued dollar or the turning of the business cycle.", role: "modifier" },
    ],
    trunk: "Few Americans attribute this solely to obvious causes.",
    layers: [
      { label: "核心搭配", text: "attribute A to B：把A归因于B；this 指美国连续五年的增长" },
      { label: "举例结构", text: "such causes as A or B：诸如A或B这样的原因" },
      { label: "作者距离", text: "Few Americans... 只报告美国人的归因；下一句称其为 blind pride，显示作者并不完全认同" },
    ],
    grammar: [
      "few + 可数名词复数表示“几乎没有”，带否定意味；不同于 a few“有一些”。",
      "attribute sth to sth 中 to 是介词，后接名词或 doing。",
      "devalued 是过去分词形容词，a devalued dollar 指贬值后的美元。",
    ],
    literal: "很少有美国人把这仅仅归因于诸如贬值的美元或商业周期的转折这类明显原因。",
    natural: "很少有美国人认为，这次复苏仅仅源于美元贬值或经济周期转向等显而易见的因素。",
    logic: "区分“美国人的自我解释”与“作者的隐含判断”；结合下一句的批评语气，是第14题选择A的关键。",
    phrases: ["attribute this solely to", "such obvious causes as", "a devalued dollar", "the turning of the business cycle"],
  },
  {
    id: "p1-s22",
    number: 22,
    text: "Self-doubt has yielded to blind pride.",
    chunks: [
      { text: "Self-doubt", role: "subject" },
      { text: " has yielded", role: "predicate" },
      { text: " to blind pride.", role: "object" },
    ],
    trunk: "Self-doubt has yielded to blind pride.",
    layers: [
      { label: "状态替代", text: "A yield to B 表示A让位于B；过去的自我怀疑已被盲目自豪取代" },
      { label: "评价用词", text: "blind 带明确贬义，表明作者认为这种自豪缺乏理性依据" },
    ],
    grammar: [
      "yield to 在此是不及物短语“让步于/被……取代”，to 为介词。",
      "现在完成时 has yielded 强调心理变化已经发生并影响当前。",
    ],
    literal: "自我怀疑已经向盲目的骄傲让步。",
    natural: "昔日的自我怀疑如今已被盲目自负所取代。",
    logic: "作者用带批评色彩的概括否定美国人的过度自夸，为第14题排除受访者观点提供语气证据。",
    phrases: ["Self-doubt", "yielded to blind pride"],
  },
  {
    id: "p1-s23",
    number: 23,
    text: "\"American industry has changed its structure, has gone on a diet, has learnt to be more quick-witted,\" according to Richard Cavanaugh, executive dean of Harvard's Kennedy School of Government.",
    chunks: [
      { text: "\"American industry", role: "subject" },
      { text: " has changed", role: "predicate" },
      { text: " its structure, ", role: "object" },
      { text: "has gone on a diet, ", role: "predicate" },
      { text: "has learnt to be", role: "predicate" },
      { text: " more quick-witted,\" ", role: "object" },
      { text: "according to Richard Cavanaugh, ", role: "modifier" },
      { text: "executive dean of Harvard's Kennedy School of Government.", role: "modifier" },
    ],
    trunk: "American industry has changed..., has gone..., has learnt....",
    layers: [
      { label: "三项并列", text: "has changed / has gone / has learnt 三个现在完成时谓语共用主语 American industry" },
      { label: "比喻表达", text: "go on a diet 本指节食，此处比喻企业精简机构、削减成本" },
      { label: "引语来源", text: "according to... 说明这是Cavanaugh的观点；executive dean... 是同位语介绍其身份" },
    ],
    grammar: [
      "并列谓语重复 has，强化产业连续完成的三项改变。",
      "learn to do 表示通过学习逐渐具备做某事的能力；quick-witted 作 be 的表语。",
      "according to 引述他人看法，不能自动当作作者本人立场。",
    ],
    literal: "“美国工业已经改变了它的结构，已经开始节食，并已经学会变得更加机敏，”哈佛大学肯尼迪政府学院执行院长理查德·卡瓦诺说。",
    natural: "哈佛大学肯尼迪政府学院执行院长理查德·卡瓦诺认为：“美国工业完成了结构调整，精简了规模，也变得更加敏捷。”",
    logic: "列出美国人对复苏的内部改革解释，但属于被引述者观点，不等于作者最终认可。",
    phrases: ["has changed its structure", "has gone on a diet", "has learnt to be more quick-witted", "according to Richard Cavanaugh"],
  },
  {
    id: "p1-s24",
    number: 24,
    text: "\"It makes me proud to be an American just to see how our businesses are improving their productivity,\" says Stephen Moore of the Cato Institute, a think-tank in Washington, DC.",
    chunks: [
      { text: "\"It", role: "subject" },
      { text: " makes", role: "predicate" },
      { text: " me", role: "object" },
      { text: " proud to be an American", role: "object" },
      { text: " just to see how our businesses are improving their productivity,\" ", role: "condition" },
      { text: "says", role: "predicate" },
      { text: " Stephen Moore of the Cato Institute, ", role: "subject" },
      { text: "a think-tank in Washington, DC.", role: "modifier" },
    ],
    trunk: "It makes me proud to see how businesses are improving productivity.",
    layers: [
      { label: "使役结构", text: "make + me + proud：使我感到自豪；proud 是宾语补足语" },
      { label: "原因不定式", text: "just to see... 表示仅仅看到这一点就足以产生自豪感" },
      { label: "how从句", text: "how our businesses are improving... 作 see 的宾语，how 表示改善的方式或程度" },
      { label: "身份同位语", text: "a think-tank in Washington, DC 补充说明 Cato Institute 是华盛顿的一家智库" },
    ],
    grammar: [
      "make sb + adjective 是使役结构，意为“使某人处于某种状态”。",
      "see 后接 how 宾语从句，使用陈述语序。",
      "直接引语在前时，says Stephen Moore 使用谓语在前的引语倒装。",
    ],
    literal: "“仅仅看到我们的企业怎样正在提高它们的生产率，就使我为作为一个美国人而自豪，”华盛顿特区智库卡托研究所的斯蒂芬·摩尔说。",
    natural: "华盛顿智库卡托研究所的斯蒂芬·摩尔说：“看到美国企业不断提高生产率，我身为美国人深感自豪。”",
    logic: "继续展示美国人的自豪情绪；其强烈主观色彩与作者所说的 blind pride 相呼应。",
    phrases: ["makes me proud to be an American", "see how our businesses are improving their productivity", "a think-tank in Washington, DC"],
  },
  {
    id: "p1-s25",
    number: 25,
    text: "And William Sahlman of the Harvard Business School believes that people will look back on this period as \"a golden age of business management in the United States.\"",
    chunks: [
      { text: "And ", role: "connector" },
      { text: "William Sahlman of the Harvard Business School", role: "subject" },
      { text: " believes", role: "predicate" },
      { text: " that people will look back on this period as \"a golden age of business management in the United States.\"", role: "object" },
    ],
    trunk: "William Sahlman believes that people will look back on this period as a golden age.",
    layers: [
      { label: "宾语从句", text: "that people will... 是 believes 的宾语，说明Sahlman的判断" },
      { label: "评价结构", text: "look back on A as B：回顾A并把它视为B" },
      { label: "名词层级", text: "a golden age of business management in the United States：美国企业管理的黄金时代" },
    ],
    grammar: [
      "look back on sth as... 表示回顾过去并将其评价为……。",
      "will 是从当前视角对未来回顾行为的预测。",
      "句首 And 承接前两位受访者的乐观评价，形成列举。",
    ],
    literal: "而哈佛商学院的威廉·萨尔曼相信，人们将回顾这一时期，把它看作“美国企业管理的一个黄金时代”。",
    natural: "哈佛商学院的威廉·萨尔曼甚至认为，后人会把这一时期视为“美国企业管理的黄金时代”。",
    logic: "以第三个乐观引语收束全文，完整呈现从危机反思到盲目自豪的心理摆动。",
    phrases: ["look back on this period as", "a golden age of business management"],
  },
];

export const passage1Questions: Question[] = [
  {
    id: 11,
    sentenceId: "p1-s4",
    prompt: "The U.S. achieved its predominance after World War II because ____.",
    options: [
      { key: "A", text: "it had made painstaking efforts towards this goal" },
      { key: "B", text: "its domestic market was eight times larger than before" },
      { key: "C", text: "the war had destroyed the economies of most potential competitors" },
      { key: "D", text: "the unparalleled size of its workforce had given an impetus to its economy" },
    ],
    answer: "C",
    locating: "第2—4句列举战后美国的巨大市场、科技和技术优势；第4句进一步点明欧亚潜在竞争者的经济已被战争摧毁，因此C概括了美国轻易取得主导地位的关键外部条件。",
    explanations: {
      A: "原文首句明确说 long and effortless success，painstaking efforts“艰苦努力”与 effortless 相反。",
      B: "原文是美国市场比任何竞争者的市场大八倍，不是比美国自己战前的市场大八倍，比较对象被偷换。",
      C: "第4句 whose economies the war had destroyed 表明欧洲和亚洲潜在竞争者的经济遭战争摧毁，与美国的繁荣形成直接对照。",
      D: "原文说的是美国市场使其工业获得 unparalleled economies of scale，并未说美国劳动力“规模空前”；workers 只被描述为技术最熟练。",
    },
  },
  {
    id: 12,
    sentenceId: "p1-s11",
    prompt: "The loss of U.S. predominance in the world economy in the 1980s is manifested in the fact that the American ____.",
    options: [
      { key: "A", text: "TV industry had withdrawn to its domestic market" },
      { key: "B", text: "semiconductor industry had been taken over by foreign enterprises" },
      { key: "C", text: "machine-tool industry had collapsed after suicidal actions" },
      { key: "D", text: "auto industry had lost part of its domestic market" },
    ],
    answer: "D",
    locating: "第11句 Foreign-made cars ... were sweeping into the domestic market 说明外国汽车大量进入美国国内市场，因此美国汽车业失去了部分本土市场。",
    explanations: {
      A: "第9—10句说美国电视制造商从仅剩一家变为一家不剩，并非“退守并保住国内市场”。",
      B: "第13句只说半导体制造业一度看起来将成为下一个受害者，was going to be 是当时预测，并未说已经被外国企业接管。",
      C: "on the ropes 表示岌岌可危而非已经 collapsed；原文也没有 suicidal actions“自毁行为”。",
      D: "外国汽车席卷美国国内市场，直接意味着美国汽车业丧失了部分国内市场，属于原文事实的同义改写。",
    },
  },
  {
    id: 13,
    sentenceId: "p1-s18",
    prompt: "What can be inferred from the passage?",
    options: [
      { key: "A", text: "It is human nature to shift between self-doubt and blind pride" },
      { key: "B", text: "Intense competition may contribute to economic progress" },
      { key: "C", text: "The revival of the economy depends on international cooperation" },
      { key: "D", text: "A long history of success may pave the way for further development" },
    ],
    answer: "B",
    locating: "第8—18句构成“外国竞争加剧→美国工业受挫→产生信心危机→连续调查并反思”的链条，随后第20句出现五年稳定增长，因此可推断竞争压力可能促进经济改进。",
    explanations: {
      A: "文章只描述美国人在特定经济周期中的心理变化，不能把单一国家的现象扩大为普遍的 human nature。",
      B: "外部竞争促使美国停止把繁荣视为理所当然并调查衰退原因，之后经济恢复增长；这是跨段落隐含的因果关系。",
      C: "文中谈的是 foreign competition，而不是 international cooperation；“依赖国际合作”没有依据。",
      D: "首句说成功史可能成为 dreadful handicap，只有 properly handled 才可能转化为动力；D删掉关键条件并把“可能成为障碍”改成直接铺路。",
    },
  },
  {
    id: 14,
    sentenceId: "p1-s21",
    prompt: "The author seems to believe the revival of the U.S. economy in the 1990s can be attributed to the ____.",
    options: [
      { key: "A", text: "turning of the business cycle" },
      { key: "B", text: "restructuring of industry" },
      { key: "C", text: "improved business management" },
      { key: "D", text: "success in education" },
    ],
    answer: "A",
    locating: "第21句说很少有美国人把复苏仅归因于美元贬值或经济周期转向；第22句紧接着批评这种态度已变成 blind pride。作者借此与美国人的自我赞美拉开距离，暗示经济周期等客观因素仍是重要解释。",
    explanations: {
      A: "turning of the business cycle 是作者列出的 obvious cause；随后用 blind pride 批评美国人轻视这些客观因素，因此A最能体现作者隐含立场。",
      B: "产业重组来自Cavanaugh的直接引语，是受访者观点；according to 明确标出观点来源，不等于作者认定的原因。",
      C: "企业提高生产率及“管理黄金时代”来自Moore和Sahlman的自豪评价，同样处在作者所批评的 blind pride 语境中。",
      D: "全文没有把经济复苏归因于教育成功；哈佛等机构只用于说明被引述者身份。",
    },
  },
];
