import type { Question, SentenceAnalysis } from "./data";

export const passage2Sentences: SentenceAnalysis[] = [
  {
    id: "p2-s1",
    number: 1,
    text: "Being a man has always been dangerous.",
    chunks: [
      { text: "Being a man", role: "subject" },
      { text: " has always been", role: "predicate" },
      { text: " dangerous.", role: "modifier" },
    ],
    trunk: "Being a man has been dangerous",
    layers: [
      { label: "动名词短语主语", text: "Being a man：成为男性这件事" },
      { label: "谓语与表语", text: "has always been dangerous：一直处于危险状态" },
    ],
    grammar: [
      "Being a man 是动名词短语作主语，表示一个概括性的事实。",
      "has always been 是现在完成时，always 强调这种情况持续至今。",
      "be dangerous 是系表结构，dangerous 描述主语所处的状态。",
    ],
    literal: "成为男性一直是危险的。",
    natural: "当男性一直伴随着更高的生存风险。",
    logic: "开篇提出全文起点：男性过去更容易在生存竞争中受损。",
    phrases: [],
  },
  {
    id: "p2-s2",
    number: 2,
    text: "There are about 105 males born for every 100 females, but this ratio drops to near balance at the age of maturity, and among 70-year-olds there are twice as many women as men.",
    chunks: [
      { text: "There are about 105 males born for every 100 females, ", role: "predicate" },
      { text: "but this ratio drops to near balance at the age of maturity, ", role: "connector" },
      { text: "and among 70-year-olds there are twice as many women as men.", role: "modifier" },
    ],
    trunk: "There are more male births, but the ratio balances and later favors women",
    layers: [
      { label: "存在句", text: "There are about 105 males born for every 100 females：每出生100名女性就约有105名男性出生" },
      { label: "转折变化", text: "but this ratio drops to near balance：这一比例到成年时降至接近平衡" },
      { label: "高龄段比较", text: "among 70-year-olds there are twice as many women as men：在70岁人群中女性约为男性的两倍" },
    ],
    grammar: [
      "there are 引导存在句，born 是过去分词后置修饰 males。",
      "for every 100 females 表示每100名女性对应的数量基准。",
      "drop to 后接结果数值或状态；as many A as B 构成数量同等比较。",
    ],
    literal: "每100名女性出生时约有105名男性，但这一比例在成熟年龄降至接近平衡；在70岁人群中，女性数量是男性的两倍。",
    natural: "出生时男孩略多于女孩，但到成年男女数量已近乎相等；到了70岁，女性人数约为男性的两倍。",
    logic: "用人口比例的年龄变化说明男性从出生到老年始终承受更高的死亡风险。",
    phrases: ["for every", "drops to near balance", "at the age of maturity", "twice as many women as men"],
  },
  {
    id: "p2-s3",
    number: 3,
    text: "But the great universal of male mortality is being changed.",
    chunks: [
      { text: "But ", role: "connector" },
      { text: "the great universal of male mortality", role: "subject" },
      { text: " is being changed.", role: "predicate" },
    ],
    trunk: "the universal of male mortality is being changed",
    layers: [
      { label: "转折", text: "But：转入对传统规律的修正" },
      { label: "主语", text: "the great universal of male mortality：男性死亡率这一普遍规律" },
      { label: "被动进行时", text: "is being changed：正在被改变" },
    ],
    grammar: [
      "is being changed 是现在进行时的被动语态，强调变化正在发生。",
      "of male mortality 中 of 引出 universal 所涉及的领域。",
      "But 放在句首承接前句数据，提示下文将说明男性生存状况改善。",
    ],
    literal: "男性死亡率这一伟大普遍规律正在被改变。",
    natural: "男性死亡率长期高于女性这一普遍规律正在发生变化。",
    logic: "从历史规律转向现代变化，提出自然选择压力减弱的第一个证据。",
    phrases: ["male mortality"],
  },
  {
    id: "p2-s4",
    number: 4,
    text: "Now, boy babies survive almost as well as girls do.",
    chunks: [
      { text: "Now, ", role: "connector" },
      { text: "boy babies", role: "subject" },
      { text: " survive", role: "predicate" },
      { text: " almost as well as girls do.", role: "modifier" },
    ],
    trunk: "boy babies survive almost as well as girls",
    layers: [
      { label: "时间转折", text: "Now：把讨论焦点移到现在" },
      { label: "主句", text: "boy babies survive：男婴能够存活" },
      { label: "同级比较", text: "almost as well as girls do：存活状况几乎和女婴一样好" },
    ],
    grammar: [
      "as well as 连接两个生存状况的比较对象，第二个 do 代替 survive。",
      "almost 修饰整个同级比较，表示“几乎达到同样程度”。",
      "boy babies 与 girls 是泛指复数名词短语。",
    ],
    literal: "现在，男婴存活得几乎和女孩一样好。",
    natural: "如今男婴的存活率几乎已与女婴相同。",
    logic: "具体解释男性死亡率规律为何改变：出生后的性别生存差距缩小。",
    phrases: ["almost as well as"],
  },
  {
    id: "p2-s5",
    number: 5,
    text: "This means that, for the first time, there will be an excess of boys in those crucial years when they are searching for a mate.",
    chunks: [
      { text: "This", role: "subject" },
      { text: " means", role: "predicate" },
      { text: " that, for the first time, there will be an excess of boys", role: "object" },
      { text: " in those crucial years", role: "modifier" },
      { text: " when they are searching for a mate.", role: "modifier" },
    ],
    trunk: "This means that there will be an excess of boys",
    layers: [
      { label: "指代与主句", text: "This means：this 指代男婴存活率提高这一变化" },
      { label: "宾语从句", text: "there will be an excess of boys：将会出现男孩过多" },
      { label: "时间与定语", text: "in those crucial years when they are searching for a mate：在他们寻找配偶的关键年龄段" },
    ],
    grammar: [
      "means that 引导宾语从句，说明前面事实产生的结果。",
      "there will be 是将来时存在句，an excess of boys 是后置主语。",
      "when 引导定语从句修饰 years，they 指 boys。",
    ],
    literal: "这意味着，第一次在他们寻找配偶的那些关键年份里，男孩会出现过剩。",
    natural: "这意味着，男孩将在寻找配偶的关键年龄段首次出现人数过多的情况。",
    logic: "从生存率变化推导人口结构后果：择偶年龄段的男性供给会相对过剩。",
    phrases: ["for the first time", "an excess of", "searching for a mate"],
  },
  {
    id: "p2-s6",
    number: 6,
    text: "More important, another chance for natural selection has been removed.",
    chunks: [
      { text: "More important, ", role: "connector" },
      { text: "another chance for natural selection", role: "subject" },
      { text: " has been removed.", role: "predicate" },
    ],
    trunk: "another chance for natural selection has been removed",
    layers: [
      { label: "评价性连接语", text: "More important：进一步指出更重要的后果" },
      { label: "主语", text: "another chance for natural selection：自然选择的又一个机会" },
      { label: "现在完成时被动", text: "has been removed：已经被消除" },
    ],
    grammar: [
      "More important 是省略了 it is 的句首评价语。",
      "for natural selection 表示这个机会服务于或属于自然选择过程。",
      "has been removed 用现在完成时被动，强调结果已经形成。",
    ],
    literal: "更重要的是，自然选择的另一个机会已经被移除了。",
    natural: "更重要的是，自然选择又少了一个发挥作用的机会。",
    logic: "把人口比例变化提升到进化层面，转入第二个自然选择机会的消失。",
    phrases: ["natural selection"],
  },
  {
    id: "p2-s7",
    number: 7,
    text: "Fifty years ago, the chance of a baby (particularly a boy baby) surviving depended on its weight.",
    chunks: [
      { text: "Fifty years ago, ", role: "modifier" },
      { text: "the chance of a baby (particularly a boy baby) surviving", role: "subject" },
      { text: " depended", role: "predicate" },
      { text: " on its weight.", role: "modifier" },
    ],
    trunk: "the chance of a baby surviving depended on its weight",
    layers: [
      { label: "过去时间", text: "Fifty years ago：把论述置于五十年前" },
      { label: "主语中心", text: "the chance of ... surviving：婴儿存活的可能性" },
      { label: "插入强调", text: "particularly a boy baby：尤其是男婴" },
      { label: "决定因素", text: "depended on its weight：取决于体重" },
    ],
    grammar: [
      "of a baby surviving 是动名词复合结构，surviving 表示婴儿存活这一事件。",
      "particularly a boy baby 是括号插入语，缩小强调范围而不改变主干。",
      "depend on 是不及物动词短语，on 后接决定因素。",
    ],
    literal: "五十年前，婴儿（尤其是男婴）能否存活取决于它的体重。",
    natural: "五十年前，婴儿能不能活下来，尤其是男婴，很大程度取决于出生体重。",
    logic: "给出过去自然选择筛选婴儿的具体标准，为下一句的极端后果作铺垫。",
    phrases: ["the chance of a baby (particularly a boy baby) surviving", "depended on"],
  },
  {
    id: "p2-s8",
    number: 8,
    text: "A kilogram too light or too heavy meant almost certain death.",
    chunks: [
      { text: "A kilogram too light or too heavy", role: "subject" },
      { text: " meant", role: "predicate" },
      { text: " almost certain death.", role: "object" },
    ],
    trunk: "A kilogram too light or too heavy meant almost certain death",
    layers: [
      { label: "主语", text: "A kilogram too light or too heavy：轻一公斤或重一公斤" },
      { label: "结果谓语", text: "meant almost certain death：意味着几乎必死" },
    ],
    grammar: [
      "too + 形容词表示“过于……而不能达到要求”，too light 与 too heavy 对举。",
      "meant 在此不是“意味着某个词的意思”，而是引出后果。",
      "death 是抽象不可数名词，certain 前的 almost 表示接近确定。",
    ],
    literal: "轻一公斤或重一公斤意味着几乎确定的死亡。",
    natural: "体重偏轻或偏重一公斤，几乎都意味着死亡。",
    logic: "把体重差异造成的强烈生存筛选具体化，说明过去自然选择压力很大。",
    phrases: ["too light or too heavy", "almost certain death"],
  },
  {
    id: "p2-s9",
    number: 9,
    text: "Today it makes almost no difference.",
    chunks: [
      { text: "Today ", role: "modifier" },
      { text: "it", role: "subject" },
      { text: " makes", role: "predicate" },
      { text: " almost no difference.", role: "object" },
    ],
    trunk: "it makes almost no difference",
    layers: [
      { label: "时间对比", text: "Today：与五十年前形成对照" },
      { label: "代词指代", text: "it：指体重偏轻或偏重这一差异" },
      { label: "结果", text: "makes almost no difference：几乎不再造成差别" },
    ],
    grammar: [
      "make a difference 表示“产生影响或差别”，difference 是宾语。",
      "almost no 是“几乎没有”，比 no 更保留少量例外的可能。",
      "it 是指代前句体重偏差的代词，不是形式主语。",
    ],
    literal: "如今它几乎不造成任何差别。",
    natural: "如今体重差一公斤几乎不会影响存活。",
    logic: "用极短的句子对比过去与现在，明确说明筛选标准已失效。",
    phrases: ["makes almost no difference"],
  },
  {
    id: "p2-s10",
    number: 10,
    text: "Since much of the variation is due to genes, one more agent of evolution has gone.",
    chunks: [
      { text: "Since much of the variation is due to genes, ", role: "condition" },
      { text: "one more agent of evolution", role: "subject" },
      { text: " has gone.", role: "predicate" },
    ],
    trunk: "one more agent of evolution has gone",
    layers: [
      { label: "原因从句", text: "Since much of the variation is due to genes：既然许多差异由基因造成" },
      { label: "主句主语", text: "one more agent of evolution：进化的又一个作用因素" },
      { label: "主句谓语", text: "has gone：已经消失" },
    ],
    grammar: [
      "Since 在句首引导原因从句，不是“自从”时间义。",
      "be due to 表示“由……造成”，to 后接原因。",
      "has gone 是现在完成时，gone 在此表示消失而非离开某地。",
    ],
    literal: "既然许多变异由基因造成，进化的又一个作用因素已经消失。",
    natural: "既然许多体重差异源于基因，进化又失去了一个发挥筛选作用的因素。",
    logic: "完成第二层推理：体重不再影响生存，连同基因变异在内的进化筛选作用也被削弱。",
    phrases: ["is due to", "agent of evolution"],
  },
  {
    id: "p2-s11",
    number: 11,
    text: "There is another way to commit evolutionary suicide: stay alive, but have fewer children.",
    chunks: [
      { text: "There is another way", role: "predicate" },
      { text: " to commit evolutionary suicide", role: "modifier" },
      { text: ": stay alive, ", role: "connector" },
      { text: "but have fewer children.", role: "predicate" },
    ],
    trunk: "There is another way: stay alive but have fewer children",
    layers: [
      { label: "存在句", text: "There is another way：还有另一种方式" },
      { label: "不定式定语", text: "to commit evolutionary suicide：去实施进化意义上的自杀" },
      { label: "冒号解释", text: "stay alive, but have fewer children：活着却少生孩子" },
    ],
    grammar: [
      "there is 引出新的论点，to commit ... 修饰 way。",
      "冒号后的两个动词短语 stay alive 与 have fewer children 构成对照。",
      "but 连接让步式并列动作，表示虽然活着却减少繁殖。",
    ],
    literal: "还有另一种实施进化自杀的方式：活下来，但生更少的孩子。",
    natural: "还有一种进化意义上的“自杀”：人虽然活着，却生育更少。",
    logic: "论证从死亡筛选转向繁殖筛选，提出自然选择减弱的第三个途径。",
    phrases: ["commit evolutionary suicide", "stay alive", "have fewer children"],
  },
  {
    id: "p2-s12",
    number: 12,
    text: "Few people are as fertile as in the past.",
    chunks: [
      { text: "Few people", role: "subject" },
      { text: " are", role: "predicate" },
      { text: " as fertile as in the past.", role: "modifier" },
    ],
    trunk: "Few people are as fertile as in the past",
    layers: [
      { label: "主语范围", text: "Few people：几乎没有多少人" },
      { label: "比较结构", text: "as fertile as in the past：像过去那样有生育力" },
    ],
    grammar: [
      "few 修饰可数名词复数，带有“几乎没有”的否定倾向。",
      "as fertile as 是形容词原级比较，第二个 as 后省略了 people were。",
      "in the past 表示过去时期，和现在形成比较。",
    ],
    literal: "很少有人像过去那样多产。",
    natural: "如今几乎没有人像过去那样能生育很多孩子。",
    logic: "用总体趋势承接“少生孩子”，说明生育率平均化。",
    phrases: ["as fertile as"],
  },
  {
    id: "p2-s13",
    number: 13,
    text: "Except in some religious communities, very few women have 15 children.",
    chunks: [
      { text: "Except in some religious communities, ", role: "modifier" },
      { text: "very few women", role: "subject" },
      { text: " have", role: "predicate" },
      { text: " 15 children.", role: "object" },
    ],
    trunk: "very few women have 15 children",
    layers: [
      { label: "例外范围", text: "Except in some religious communities：除了一些宗教社群之外" },
      { label: "主语", text: "very few women：极少数女性" },
      { label: "谓语与宾语", text: "have 15 children：生育15个孩子" },
    ],
    grammar: [
      "except in + 地点或群体表示“除……之外”，限定主句适用范围。",
      "very few 比 few 语气更强，强调人数极少。",
      "have children 在这里是“生育孩子”，不是单纯“拥有”。",
    ],
    literal: "除了一些宗教社群之外，极少有女性生育15个孩子。",
    natural: "除了一些宗教团体外，如今几乎没有女性会生育15个孩子。",
    logic: "用具体数字证明高生育率已不再普遍，只有少数特殊群体例外。",
    phrases: ["except in", "very few women"],
  },
  {
    id: "p2-s14",
    number: 14,
    text: "Nowadays the number of births, like the age of death, has become average.",
    chunks: [
      { text: "Nowadays ", role: "modifier" },
      { text: "the number of births", role: "subject" },
      { text: ", like the age of death, ", role: "modifier" },
      { text: "has become", role: "predicate" },
      { text: " average.", role: "modifier" },
    ],
    trunk: "the number of births has become average",
    layers: [
      { label: "时间状语", text: "Nowadays：如今" },
      { label: "主语", text: "the number of births：出生数量" },
      { label: "插入比较", text: "like the age of death：像死亡年龄一样" },
      { label: "系表结构", text: "has become average：已经趋于平均" },
    ],
    grammar: [
      "the number of + 复数名词作主语时谓语用单数。",
      "like the age of death 是插入的介词短语，比较出生数量与死亡年龄的平均化。",
      "become 后接形容词 average 作表语，说明状态变化。",
    ],
    literal: "如今出生的数量，像死亡的年龄一样，已经变得平均。",
    natural: "如今出生人数和死亡年龄一样，都趋于平均化。",
    logic: "概括前两句，指出生育和死亡这两个进化筛选指标都不再有明显分化。",
    phrases: ["the number of", "like the age of death", "become average"],
  },
  {
    id: "p2-s15",
    number: 15,
    text: "Most of us have roughly the same number of offspring.",
    chunks: [
      { text: "Most of us", role: "subject" },
      { text: " have", role: "predicate" },
      { text: " roughly the same number of offspring.", role: "object" },
    ],
    trunk: "Most of us have roughly the same number of offspring",
    layers: [
      { label: "主语范围", text: "Most of us：我们中的大多数人" },
      { label: "数量比较", text: "roughly the same number of offspring：大致相同数量的后代" },
    ],
    grammar: [
      "most of + 代词宾格表示“……中的大多数”，谓语由 most 所指的人数决定。",
      "the same number of + 可数名词复数表示相同数量，而不是 same amount。",
      "roughly 修饰数量比较，表示大致而非绝对相等。",
    ],
    literal: "我们大多数人拥有大致相同数量的后代。",
    natural: "我们中的大多数人生育的子女数量大致相同。",
    logic: "把平均化趋势落到个人层面，直接说明繁殖差异正在减少。",
    phrases: ["roughly the same number of offspring"],
  },
  {
    id: "p2-s16",
    number: 16,
    text: "Again, differences between people and the opportunity for natural selection to take advantage of it have diminished.",
    chunks: [
      { text: "Again, ", role: "connector" },
      { text: "differences between people and the opportunity for natural selection to take advantage of it", role: "subject" },
      { text: " have diminished.", role: "predicate" },
    ],
    trunk: "differences and the opportunity for natural selection have diminished",
    layers: [
      { label: "递进连接", text: "Again：再次回到自然选择机会减少的结论" },
      { label: "并列主语", text: "differences between people and the opportunity ...：人与人之间的差异以及自然选择利用这些差异的机会" },
      { label: "不定式结构", text: "to take advantage of it：去利用这些差异，it 指 differences" },
    ],
    grammar: [
      "and 连接两个并列主语中心，谓语使用复数 have。",
      "opportunity for sb to do 是“某人做某事的机会”结构。",
      "take advantage of 后接代词 it，指前面的 differences，而非 opportunity。",
    ],
    literal: "人与人之间的差异以及自然选择利用这些差异的机会再次减少了。",
    natural: "同样，人与人之间的差异变小了，自然选择利用这些差异的机会也随之减少。",
    logic: "小结第二段前半部分，把生育平均化明确归结为自然选择作用减弱。",
    phrases: ["take advantage of"],
  },
  {
    id: "p2-s17",
    number: 17,
    text: "India shows what is happening.",
    chunks: [
      { text: "India", role: "subject" },
      { text: " shows", role: "predicate" },
      { text: " what is happening.", role: "object" },
    ],
    trunk: "India shows what is happening",
    layers: [
      { label: "主语", text: "India：印度这一国家案例" },
      { label: "宾语从句", text: "what is happening：正在发生的情况" },
    ],
    grammar: [
      "what is happening 是 what 引导的宾语从句，what 在从句中作主语。",
      "shows 后接事实内容，表示用印度案例来展示前文趋势。",
    ],
    literal: "印度展示了正在发生的事情。",
    natural: "印度正好说明了这种变化。",
    logic: "从抽象机制转入国家案例，为下一句的贫富对比和第16题提供依据。",
    phrases: [],
  },
  {
    id: "p2-s18",
    number: 18,
    text: "The country offers wealth for a few in the great cities and poverty for the remaining tribal peoples.",
    chunks: [
      { text: "The country", role: "subject" },
      { text: " offers", role: "predicate" },
      { text: " wealth for a few in the great cities", role: "object" },
      { text: " and ", role: "connector" },
      { text: "poverty for the remaining tribal peoples.", role: "object" },
    ],
    trunk: "The country offers wealth for a few and poverty for the remaining tribal peoples",
    layers: [
      { label: "主干", text: "The country offers A and B：印度同时呈现两种相反生活条件" },
      { label: "第一对象", text: "wealth for a few in the great cities：大城市中少数人的财富" },
      { label: "第二对象", text: "poverty for the remaining tribal peoples：其余部落民族的贫困" },
    ],
    grammar: [
      "offers 后并列两个宾语 wealth 与 poverty，for 短语分别说明受益或受影响群体。",
      "remaining 是现在分词形容词，表示“剩余的、其余的”。",
      "tribal 作前置定语修饰 peoples，说明群体属性。",
    ],
    literal: "这个国家给大城市中的少数人财富，却给剩余的部落民族贫困。",
    natural: "印度的大城市让少数人富裕，而广大部落民族仍然贫困。",
    logic: "具体呈现印度内部的阶层和群体差异，支撑“贫富群体生育差异”的例证。",
    phrases: [],
  },
  {
    id: "p2-s19",
    number: 19,
    text: "The grand mediocrity of today—everyone being the same in survival and number of offspring—means that natural selection has lost 80% of its power in upper-middle-class India compared to the tribes.",
    chunks: [
      { text: "The grand mediocrity of today—everyone being the same in survival and number of offspring—", role: "subject" },
      { text: "means", role: "predicate" },
      { text: " that natural selection has lost 80% of its power", role: "object" },
      { text: " in upper-middle-class India compared to the tribes.", role: "modifier" },
    ],
    trunk: "The grand mediocrity of today means natural selection has lost power",
    layers: [
      { label: "抽象主语", text: "The grand mediocrity of today：当今普遍的平庸化 / 平均化" },
      { label: "破折号插入说明", text: "everyone being the same in survival and number of offspring：每个人的生存和后代数量都相同" },
      { label: "宾语从句", text: "natural selection has lost 80% of its power：自然选择失去了80%的力量" },
      { label: "比较范围", text: "in upper-middle-class India compared to the tribes：在印度中上阶层，相对于部落群体而言" },
    ],
    grammar: [
      "破折号内是独立主格式的补充说明，everyone being the same 概括 mediocrity 的内容。",
      "means that 引导宾语从句，说明平均化带来的后果。",
      "compared to the tribes 是过去分词短语作比较状语，省略了与谁相比的完整结构。",
    ],
    literal: "当今这种人人在生存和后代数量上都相同的巨大平均化，意味着在印度中上阶层，自然选择相对于部落群体已失去80%的力量。",
    natural: "如今人人的生存机会和后代数量都趋于相同，因此在印度中上阶层，自然选择的作用比部落群体中弱了80%。",
    logic: "把印度案例上升为量化结论，说明社会条件如何替代自然选择并抹平差异。",
    phrases: ["the same in", "compared to"],
  },
  {
    id: "p2-s20",
    number: 20,
    text: "For us, this means that evolution is over; the biological Utopia has arrived.",
    chunks: [
      { text: "For us, ", role: "modifier" },
      { text: "this", role: "subject" },
      { text: " means that evolution is over; ", role: "predicate" },
      { text: "the biological Utopia has arrived.", role: "connector" },
    ],
    trunk: "this means evolution is over; biological Utopia has arrived",
    layers: [
      { label: "观点范围", text: "For us：对人类而言" },
      { label: "指代总结", text: "this means：this 指前文自然选择作用减弱的整体事实" },
      { label: "并列结论", text: "evolution is over; the biological Utopia has arrived：进化结束，生物学乌托邦到来" },
    ],
    grammar: [
      "For us 是介词短语作句首范围状语，不是原因。",
      "means that 后接宾语从句；分号连接两个语义相关的独立分句。",
      "Utopia 是专有名词，biological 作前置定语，整体带有反讽色彩。",
    ],
    literal: "对我们而言，这意味着进化结束了；生物学上的乌托邦已经到来。",
    natural: "对人类来说，这似乎意味着进化已经终结，生物学意义上的乌托邦到来了。",
    logic: "先提出带有讽刺意味的阶段性结论，为最后一段反转和限定作铺垫。",
    phrases: ["evolution is over"],
  },
  {
    id: "p2-s21",
    number: 21,
    text: "Strangely, it has involved little physical change.",
    chunks: [
      { text: "Strangely, ", role: "modifier" },
      { text: "it", role: "subject" },
      { text: " has involved", role: "predicate" },
      { text: " little physical change.", role: "object" },
    ],
    trunk: "it has involved little physical change",
    layers: [
      { label: "评价副词", text: "Strangely：出人意料地" },
      { label: "指代", text: "it：指所谓进化结束 / 生物学乌托邦的到来" },
      { label: "宾语", text: "little physical change：很少的身体变化" },
    ],
    grammar: [
      "has involved 是现在完成时，it 指代前句的整体结论。",
      "little 修饰不可数名词 change，表示“很少”，带有否定倾向。",
      "physical change 指身体层面的变化，与社会和技术变化形成对照。",
    ],
    literal: "奇怪的是，它只包含很少的身体变化。",
    natural: "奇怪的是，这一过程几乎没有带来身体上的改变。",
    logic: "开始修正“进化结束”的直觉理解，指出人类外形几乎没有同步改变。",
    phrases: [],
  },
  {
    id: "p2-s22",
    number: 22,
    text: "No other species fills so many places in nature.",
    chunks: [
      { text: "No other species", role: "subject" },
      { text: " fills", role: "predicate" },
      { text: " so many places in nature.", role: "object" },
    ],
    trunk: "No other species fills so many places in nature",
    layers: [
      { label: "否定比较", text: "No other species：没有任何其他物种" },
      { label: "范围宾语", text: "so many places in nature：自然界如此多的位置 / 生态位" },
    ],
    grammar: [
      "No other + 单数名词构成最高程度的否定比较，谓语用单数 fills。",
      "fill places 在此是比喻义，表示占据自然界中的多种生态位置。",
      "so many 修饰可数名词 places，强调数量之多。",
    ],
    literal: "没有其他物种在自然界占据如此多的位置。",
    natural: "没有别的物种像人类一样占据自然界如此多的生态位置。",
    logic: "补充人类特殊性：人类凭借社会组织和工具适应了多种环境。",
    phrases: [],
  },
  {
    id: "p2-s23",
    number: 23,
    text: "But in the past 100, 000 years—even the past 100 years—our lives have been transformed but our bodies have not.",
    chunks: [
      { text: "But in the past 100, 000 years—even the past 100 years—", role: "modifier" },
      { text: "our lives", role: "subject" },
      { text: " have been transformed", role: "predicate" },
      { text: " but ", role: "connector" },
      { text: "our bodies", role: "subject" },
      { text: " have not.", role: "predicate" },
    ],
    trunk: "our lives have been transformed but our bodies have not",
    layers: [
      { label: "时间范围", text: "in the past 100, 000 years—even the past 100 years：在过去十万年，甚至过去一百年里" },
      { label: "对比前半", text: "our lives have been transformed：我们的生活已经发生巨变" },
      { label: "对比后半", text: "our bodies have not：我们的身体却没有改变，not 后省略 transformed" },
    ],
    grammar: [
      "破折号内插入 even the past 100 years，进一步缩短时间范围以加强对比。",
      "have been transformed 是现在完成时被动，表示生活受到外部力量改造。",
      "but 后 have not 是省略结构，完整形式为 our bodies have not been transformed。",
    ],
    literal: "但是在过去100, 000年，甚至过去100年中，我们的生活已被改变，而身体没有。",
    natural: "然而，无论是过去十万年还是仅仅过去一百年，我们的生活已被彻底改变，身体却没有随之变化。",
    logic: "用时间跨度证明生活变化与生物变化脱钩，为下一句“机器和社会替我们进化”作引出。",
    phrases: ["in the past 100, 000 years", "have been transformed"],
  },
  {
    id: "p2-s24",
    number: 24,
    text: "We did not evolve, because machines and society did it for us.",
    chunks: [
      { text: "We", role: "subject" },
      { text: " did not evolve", role: "predicate" },
      { text: ", because machines and society did it for us.", role: "condition" },
    ],
    trunk: "We did not evolve because machines and society did it for us",
    layers: [
      { label: "主句", text: "We did not evolve：我们没有发生生物进化" },
      { label: "原因从句", text: "because machines and society did it for us：因为机器和社会替我们完成了这件事" },
      { label: "代词指代", text: "it：指 evolve / 适应环境这一过程" },
    ],
    grammar: [
      "did not evolve 使用一般过去时否定，陈述作者关于过去过程的判断。",
      "because 引导原因状语从句，machines and society 是并列主语。",
      "do it for us 是代动词结构，it 代替 evolve，for us 表替代受益关系。",
    ],
    literal: "我们没有进化，因为机器和社会替我们做了这件事。",
    natural: "我们之所以没有发生身体进化，是因为机器和社会替我们完成了适应环境的工作。",
    logic: "给出核心解释：技术和社会制度承担了适应功能，使身体不必再被自然选择塑造。",
    phrases: ["did it for us"],
  },
  {
    id: "p2-s25",
    number: 25,
    text: "Darwin had a phrase to describe those ignorant of evolution: they “look at an organic being as a savage looks at a ship, as at something wholly beyond his comprehension.”",
    chunks: [
      { text: "Darwin", role: "subject" },
      { text: " had", role: "predicate" },
      { text: " a phrase", role: "object" },
      { text: " to describe those ignorant of evolution: ", role: "modifier" },
      { text: "they “look at an organic being as a savage looks at a ship, as at something wholly beyond his comprehension.”", role: "object" },
    ],
    trunk: "Darwin had a phrase to describe the ignorant",
    layers: [
      { label: "主句", text: "Darwin had a phrase：达尔文有一句话" },
      { label: "不定式目的", text: "to describe those ignorant of evolution：用来描述不了解进化的人" },
      { label: "引语", text: "they “look at ...”：他们看待有机体，就像野蛮人看待船一样" },
      { label: "嵌套比较", text: "as a savage looks at a ship, as at something wholly beyond his comprehension：把船视为完全无法理解的事物" },
    ],
    grammar: [
      "to describe ... 是不定式作后置定语，说明 phrase 的用途。",
      "those ignorant of evolution 中 ignorant 是形容词，of 短语补充无知的对象。",
      "引语内部 look at A as B 表示把 A 看作 B；第二个 as 引出补充说明。",
      "引用中的一般现在时表达一种概括性的认识方式。",
    ],
    literal: "达尔文有一句话来描述那些不了解进化的人：他们“看待一个有机体，就像野蛮人看待一艘船，把它当成完全超出自己理解力的东西”。",
    natural: "达尔文曾用一句话形容不懂进化的人：他们看待有机体，就像野蛮人看待船一样，觉得那完全是自己无法理解的东西。",
    logic: "借达尔文的比喻说明后人可能同样难以理解我们这个时代的生活方式。",
    phrases: ["ignorant of", "look at an organic being as", "beyond his comprehension"],
  },
  {
    id: "p2-s26",
    number: 26,
    text: "No doubt we will remember a 20th century way of life beyond comprehension for its ugliness.",
    chunks: [
      { text: "No doubt ", role: "connector" },
      { text: "we", role: "subject" },
      { text: " will remember", role: "predicate" },
      { text: " a 20th century way of life beyond comprehension", role: "object" },
      { text: " for its ugliness.", role: "modifier" },
    ],
    trunk: "we will remember a way of life for its ugliness",
    layers: [
      { label: "确定语气", text: "No doubt：毫无疑问" },
      { label: "将来回顾", text: "we will remember：后人将会记得" },
      { label: "评价对象", text: "a 20th century way of life beyond comprehension for its ugliness：因丑陋而难以理解的20世纪生活方式" },
    ],
    grammar: [
      "No doubt 是句子副词，表示作者对判断的高度确信。",
      "beyond comprehension 后置修饰 way of life，说明其难以理解的程度。",
      "for its ugliness 表示记忆或评价的原因，its 指 way of life。",
    ],
    literal: "毫无疑问，我们会因其丑陋而记住一种超出理解的20世纪生活方式。",
    natural: "毫无疑问，后人会因为20世纪生活方式的丑陋而记住它，甚至觉得难以理解。",
    logic: "把达尔文的比喻转回当代，暗示作者并不把所谓“乌托邦”视为真正美好。",
    phrases: ["no doubt", "way of life", "beyond comprehension"],
  },
  {
    id: "p2-s27",
    number: 27,
    text: "But however amazed our descendants may be at how far from Utopia we were, they will look just like us.",
    chunks: [
      { text: "But ", role: "connector" },
      { text: "however amazed our descendants may be at how far from Utopia we were, ", role: "condition" },
      { text: "they", role: "subject" },
      { text: " will look", role: "predicate" },
      { text: " just like us.", role: "modifier" },
    ],
    trunk: "they will look just like us",
    layers: [
      { label: "让步从句", text: "however amazed our descendants may be ...：无论后代会多么惊讶" },
      { label: "从句内部", text: "at how far from Utopia we were：对于我们离乌托邦有多远" },
      { label: "主句", text: "they will look just like us：他们的外貌仍会和我们一样" },
    ],
    grammar: [
      "however + 形容词引导让步结构，may be 表示未来可能的评价。",
      "how far from Utopia we were 是介词 at 后的宾语从句，保持陈述语序。",
      "look just like 是系动词加介词短语表语，表示外貌相似。",
    ],
    literal: "但是，无论我们的后代对于我们离乌托邦有多远感到多么惊讶，他们看起来都会和我们一样。",
    natural: "然而，无论后人会多么惊讶于我们离乌托邦竟如此遥远，他们的外表仍将与我们一模一样。",
    logic: "结尾反转标题预期：社会可能变化得面目全非，但人的身体外形仍不会因这些变化而进化。",
    phrases: ["however amazed our descendants may be at", "far from", "look just like"],
  },
];

export const passage2Questions: Question[] = [
  {
    id: 15,
    sentenceId: "p2-s7",
    prompt: "What used to be the danger in being a man according to the first paragraph?",
    options: [
      { key: "A", text: "A lack of mates." },
      { key: "B", text: "A fierce competition." },
      { key: "C", text: "A lower survival rate." },
      { key: "D", text: "A defective gene." },
    ],
    answer: "C",
    locating: "第7—8句说明过去婴儿能否存活取决于体重，偏轻或偏重一公斤都几乎必死；第3—4句又指出男性婴儿过去的存活状况较差，因此 danger 指较低的生存率。",
    explanations: {
      A: "第一段提到男孩在寻找配偶的年龄段可能过多，这是现在生存率提高后的结果，不是过去的危险。",
      B: "原文没有把男性面临的危险定义为竞争激烈；竞争只是自然选择的背景。",
      C: "过去男婴尤其容易因体重偏差而死亡，较低的存活率正是第一段所说的危险。",
      D: "第10句说体重差异有相当部分由基因造成，但并未说男性危险来自某种缺陷基因。",
    },
  },
  {
    id: 16,
    sentenceId: "p2-s19",
    prompt: "What does the example of India illustrate?",
    options: [
      { key: "A", text: "Wealthy people tend to have fewer children than poor people." },
      { key: "B", text: "Natural selection hardly works among the rich and the poor." },
      { key: "C", text: "The middle class population is 80% smaller than that of the tribes." },
      { key: "D", text: "India is one of the countries with a very high birth rate." },
    ],
    answer: "B",
    locating: "第18—19句用印度的贫富群体作对照：中上阶层中的自然选择作用比部落群体低80%。例子直接说明现代生存率和后代数量日趋平均，使自然选择在不同阶层间都很难再充分发挥作用。",
    explanations: {
      A: "错误。原文比较的是自然选择作用的强弱，没有提供富人和穷人的具体生育数量；把阶层差异直接推成富人少生孩子属于过度推断。",
      B: "正确。natural selection has lost 80% of its power 概括了印度案例：现代社会使富裕阶层和贫困部落之间可供自然选择利用的差异大幅缩小。",
      C: "80%描述的是自然选择作用的损失，不是中产阶层人口规模比部落人口少80%。",
      D: "例子强调生育差异和社会阶层，不是在判断印度整体出生率是否很高。",
    },
  },
  {
    id: 17,
    sentenceId: "p2-s24",
    prompt: "The author argues that our bodies have stopped evolving because.",
    options: [
      { key: "A", text: "life has been improved by technological advance" },
      { key: "B", text: "the number of female babies has been declining" },
      { key: "C", text: "our species has reached the highest stage of evolution" },
      { key: "D", text: "the difference between wealth and poverty is disappearing" },
    ],
    answer: "A",
    locating: "第23—24句明确对比生活已被改变而身体没有，并给出 because machines and society did it for us；技术和社会替代了身体进化的适应功能。",
    explanations: {
      A: "机器和社会改善并重塑了人类生活，使人不必依靠身体变化来适应环境，正是作者给出的原因。",
      B: "第一段讨论男婴与女婴的存活比例，且男婴存活率提高，并非女性婴儿减少。",
      C: "文章没有说人类达到进化最高阶段；“生物学乌托邦”是带有反讽的暂时说法。",
      D: "印度段落说明贫富差异仍然存在，不能作为身体停止进化的原因。",
    },
  },
  {
    id: 18,
    sentenceId: "p2-s27",
    prompt: "Which of the following would be the best title for the passage?",
    options: [
      { key: "A", text: "Sex Ratio Changes in Human Evolution." },
      { key: "B", text: "Ways of Continuing Man’s Evolution." },
      { key: "C", text: "The Evolutionary Future of Nature." },
      { key: "D", text: "Human Evolution Going Nowhere." },
    ],
    answer: "D",
    locating: "全文先说明男性死亡率和生育差异减小，再说明社会与机器替代了自然选择，结尾指出后代外貌仍会像我们；中心是人类身体进化停滞，而非单一性别比例。",
    explanations: {
      A: "性别比例只是第一段的一个证据，不能概括后文关于生育、社会替代和身体不变的完整论证。",
      B: "文章没有提出继续人类进化的方法，反而强调自然选择机会减少。",
      C: "讨论对象是人类身体进化，不是自然界未来的一般演化。",
      D: "Going nowhere 概括了自然选择弱化、身体几乎不变以及结尾“look just like us”的主旨，覆盖全文范围最广。",
    },
  },
];
