import type { Question, SentenceAnalysis } from "./data";

export const passage4Sentences: SentenceAnalysis[] = [
  {
    id: "p4-s1",
    number: 1,
    text: "Aimlessness has hardly been typical of the postwar Japan whose productivity and social harmony are the envy of the United States and Europe.",
    chunks: [
      { text: "Aimlessness", role: "subject" },
      { text: " has hardly been typical", role: "predicate" },
      { text: " of the postwar Japan", role: "modifier" },
      { text: " whose productivity and social harmony are the envy of the United States and Europe.", role: "modifier" },
    ],
    trunk: "Aimlessness has hardly been typical of postwar Japan.",
    layers: [
      { label: "主语", text: "Aimlessness：无所事事、缺少目标的状态" },
      { label: "核心判断", text: "has hardly been typical of the postwar Japan：几乎不是战后日本的典型特征" },
      { label: "定语从句", text: "whose productivity and social harmony are the envy of the United States and Europe：其生产力与社会和谐令欧美羡慕" },
    ],
    grammar: [
      "has hardly been 是现在完成时系表结构，hardly 表示‘几乎不’，语气接近部分否定。",
      "typical of 表示‘是……的典型特征’，of 后接被描述的对象。",
      "whose 引导非限制性定语从句，whose 同时修饰 productivity 和 social harmony，说明战后日本的两项特征。",
      "the envy of 是名词搭配，意为‘令……羡慕的对象’，不是动词 envy 的简单过去式。",
    ],
    literal: "无所事事几乎不是那个战后日本的典型特征；它的生产力和社会和谐是美国和欧洲羡慕的对象。",
    natural: "战后日本一向并不缺少目标：它的生产力和社会和谐曾令美国和欧洲羡慕。",
    logic: "开篇先给出战后日本的正面背景，为后文说明传统工作伦理正在衰退形成反差。",
    phrases: ["has hardly been typical of", "the envy of", "postwar Japan"],
  },
  {
    id: "p4-s2",
    number: 2,
    text: "But increasingly the Japanese are seeing a decline of the traditional work-moral values.",
    chunks: [
      { text: "But increasingly", role: "connector" },
      { text: " the Japanese", role: "subject" },
      { text: " are seeing", role: "predicate" },
      { text: " a decline of the traditional work-moral values.", role: "object" },
    ],
    trunk: "The Japanese are increasingly seeing a decline of traditional work-moral values.",
    layers: [
      { label: "转折与趋势", text: "But increasingly：然而这种情况正在越来越明显" },
      { label: "主语与谓语", text: "the Japanese are seeing：日本人正在看到或感受到" },
      { label: "宾语", text: "a decline of the traditional work-moral values：传统工作道德价值的衰退" },
    ],
    grammar: [
      "But 连接前后相反的社会图景；increasingly 是频率和程度副词，表示趋势不断增强。",
      "the Japanese 是表示国民整体的复数名词，谓语使用 are。",
      "see a decline of 表示‘看到某事衰退’，decline 后的 of 引出衰退对象。",
      "work-moral 是原文的复合修饰语，和 values 一起指工作伦理价值。",
    ],
    literal: "但是，日本人越来越看到传统工作道德价值的衰退。",
    natural: "然而，日本人越来越感觉到，传统的工作伦理正在走下坡路。",
    logic: "由第一句的昔日优势转入文章核心问题：日本社会的工作道德正在减弱。",
    phrases: ["seeing a decline of", "traditional work-moral values"],
  },
  {
    id: "p4-s3",
    number: 3,
    text: "Ten years ago young people were hardworking and saw their jobs as their primary reason for being, but now Japan has largely fulfilled its economic needs, and young people don't know where they should go next.",
    chunks: [
      { text: "Ten years ago", role: "modifier" },
      { text: " young people", role: "subject" },
      { text: " were hardworking and saw their jobs as their primary reason for being, ", role: "predicate" },
      { text: "but now", role: "connector" },
      { text: " Japan has largely fulfilled its economic needs, ", role: "predicate" },
      { text: "and young people don't know where they should go next.", role: "predicate" },
    ],
    trunk: "Young people once treated work as their main purpose, but now they do not know what to do next.",
    layers: [
      { label: "过去对照", text: "Ten years ago young people were hardworking：十年前的年轻人很勤奋" },
      { label: "人生目标", text: "saw their jobs as their primary reason for being：把工作看作存在的首要理由" },
      { label: "现状原因", text: "now Japan has largely fulfilled its economic needs：日本已大体满足经济需要" },
      { label: "迷惘结果", text: "young people don't know where they should go next：年轻人不知道下一步方向" },
    ],
    grammar: [
      "Ten years ago 与 now 构成明确的时间对比；过去时 were、saw 描述旧状态。",
      "see A as B 表示把 A 看作 B，as 后接名词短语作宾语补足语。",
      "reason for being 是‘存在的理由’；being 是介词 for 的动名词宾语。",
      "where they should go next 是 know 的宾语从句，where 在从句中作地点副词；should 表示应当或合理方向。",
    ],
    literal: "十年前年轻人很勤奋，把他们的工作看作存在的首要理由；但现在日本大体满足了经济需要，年轻人不知道下一步该往哪里走。",
    natural: "十年前，年轻人勤奋工作，把职业当作人生首要目标；如今经济目标基本实现，他们反而不知道未来该何去何从。",
    logic: "用年轻人目标感的前后变化具体说明经济成功之后出现的方向危机。",
    phrases: ["Ten years ago", "saw their jobs as", "primary reason for being", "fulfilled its economic needs", "where they should go next"],
  },
  {
    id: "p4-s4",
    number: 4,
    text: "The coming of age of the postwar baby boom and an entry of women into the male-dominated job market have limited the opportunities of teen-agers who are already questioning the heavy personal sacrifices involved in climbing Japan's rigid social ladder to good schools and jobs.",
    chunks: [
      { text: "The coming of age of the postwar baby boom and an entry of women into the male-dominated job market", role: "subject" },
      { text: " have limited", role: "predicate" },
      { text: " the opportunities of teen-agers", role: "object" },
      { text: " who are already questioning the heavy personal sacrifices involved in climbing Japan's rigid social ladder to good schools and jobs.", role: "modifier" },
    ],
    trunk: "The baby boom and women's entry into the job market have limited teenagers' opportunities.",
    layers: [
      { label: "并列主语", text: "the coming of age of the postwar baby boom and an entry of women into the male-dominated job market：战后婴儿潮一代成年，以及女性进入男性主导的就业市场" },
      { label: "结果", text: "have limited the opportunities of teen-agers：限制了青少年的机会" },
      { label: "定语从句", text: "who are already questioning...：这些青少年已经开始质疑传统上升道路的代价" },
      { label: "分词后置修饰", text: "sacrifices involved in climbing...：攀登社会阶梯所涉及的巨大个人牺牲" },
    ],
    grammar: [
      "coming of age 是‘成年’的名词短语；它与 an entry of women 构成并列主语，因此谓语用 have。",
      "male-dominated 是过去分词构成的复合形容词，修饰 job market。",
      "who 引导定语从句修饰 teen-agers；question 后接名词，表示质疑某种做法或代价。",
      "involved in climbing... 是过去分词短语后置修饰 sacrifices，in 后接动名词；to good schools and jobs 表示通向好学校和工作的阶梯。",
    ],
    literal: "战后婴儿潮一代成年以及女性进入男性主导的就业市场，已经限制了青少年的机会；这些青少年正在质疑攀登日本僵硬社会阶梯、进入好学校和好工作所涉及的沉重个人牺牲。",
    natural: "随着婴儿潮一代成年、女性进入男性占主导的职场，青少年获得的机会减少了；他们也开始怀疑，为了好学校和好工作而攀爬僵化社会阶梯是否值得付出巨大牺牲。",
    logic: "解释年轻人为何迷惘：竞争者增多、就业结构变化，同时传统成功路径的代价越来越难以接受。",
    phrases: ["coming of age", "entry of women into", "male-dominated job market", "have limited the opportunities of", "questioning the heavy personal sacrifices involved in", "climbing Japan's rigid social ladder"],
  },
  {
    id: "p4-s5",
    number: 5,
    text: "In a recent survey, it was found that only 24.5 percent of Japanese students were fully satisfied with school life, compared with 67.2 percent of students in the United States.",
    chunks: [
      { text: "In a recent survey,", role: "modifier" },
      { text: " it", role: "subject" },
      { text: " was found", role: "predicate" },
      { text: " that only 24.5 percent of Japanese students were fully satisfied with school life,", role: "object" },
      { text: " compared with 67.2 percent of students in the United States.", role: "modifier" },
    ],
    trunk: "A recent survey found that few Japanese students were satisfied with school life.",
    layers: [
      { label: "调查背景", text: "In a recent survey：在最近的一项调查中" },
      { label: "被动报告", text: "it was found that...：调查发现……，it 是形式主语" },
      { label: "日本数据", text: "only 24.5 percent ... were fully satisfied：只有24.5%的日本学生完全满意" },
      { label: "对比数据", text: "compared with 67.2 percent ...：与美国学生的67.2%相比" },
    ],
    grammar: [
      "it was found that 是被动报告结构，it 为形式主语，that 从句是真正内容。",
      "percent of + 复数名词后谓语由名词决定；students 是复数，所以用 were。",
      "be satisfied with 表示‘对……满意’，with 不能改成 about 来表达同一固定结构。",
      "compared with 是过去分词短语作比较状语，省略了与前面数据相比较的主语。",
    ],
    literal: "在最近的一项调查中，发现只有24.5%的日本学生完全满意学校生活，相比之下美国学生为67.2%。",
    natural: "最近一项调查显示，只有24.5%的日本学生对学校生活完全满意，而美国学生的比例为67.2%。",
    logic: "用跨国数据证实日本学生对学校生活的满意度偏低，为教育制度导致的挫折感提供证据。",
    phrases: ["In a recent survey", "it was found that", "were fully satisfied with", "compared with"],
  },
  {
    id: "p4-s6",
    number: 6,
    text: "In addition, far more Japanese workers expressed dissatisfaction with their jobs than did their counterparts in the 10 other countries surveyed.",
    chunks: [
      { text: "In addition,", role: "connector" },
      { text: " far more Japanese workers", role: "subject" },
      { text: " expressed dissatisfaction with their jobs", role: "predicate" },
      { text: " than did their counterparts in the 10 other countries surveyed.", role: "modifier" },
    ],
    trunk: "More Japanese workers were dissatisfied with their jobs than workers in the other countries.",
    layers: [
      { label: "递进连接", text: "In addition：在学生数据之外再增加一项证据" },
      { label: "比较主体", text: "far more Japanese workers expressed dissatisfaction：多得多的日本工人表达不满" },
      { label: "比较省略", text: "than did their counterparts：than 后倒装，did 代替 expressed dissatisfaction" },
      { label: "比较范围", text: "in the 10 other countries surveyed：在被调查的另外10个国家中" },
    ],
    grammar: [
      "in addition 是递进副词短语，表示在前一事实之外再补充证据。",
      "far 修饰比较级 more，加强‘多得多’的程度；dissatisfaction 是不可数抽象名词。",
      "than did their counterparts 是比较结构中的部分倒装，did 代替前面的 expressed dissatisfaction。",
      "surveyed 是过去分词后置修饰 countries，表示‘接受调查的国家’。",
    ],
    literal: "此外，表达对自己工作不满的日本工人多得多，超过了被调查的另外10个国家中的对应工人。",
    natural: "此外，日本工人对工作表示不满的比例也远高于其他10个受调查国家的工人。",
    logic: "把不满从学校延伸到职场，说明问题不是学生个体，而是整个社会的工作与生活体验。",
    phrases: ["In addition", "far more", "expressed dissatisfaction with", "than did", "their counterparts in the 10 other countries surveyed"],
  },
  {
    id: "p4-s7",
    number: 7,
    text: "While often praised by foreigners for its emphasis on the basics, Japanese education tends to stress test taking and mechanical learning over creativity and self-expression.",
    chunks: [
      { text: "While often praised by foreigners for its emphasis on the basics,", role: "condition" },
      { text: " Japanese education", role: "subject" },
      { text: " tends to stress", role: "predicate" },
      { text: " test taking and mechanical learning", role: "object" },
      { text: " over creativity and self-expression.", role: "modifier" },
    ],
    trunk: "Japanese education tends to stress test taking and mechanical learning over creativity.",
    layers: [
      { label: "让步背景", text: "While often praised by foreigners：虽然常受到外国人称赞" },
      { label: "称赞原因", text: "for its emphasis on the basics：因为强调基础知识" },
      { label: "教育倾向", text: "tends to stress test taking and mechanical learning：倾向于强调应试和机械学习" },
      { label: "取舍对比", text: "over creativity and self-expression：而不是创造力和自我表达" },
    ],
    grammar: [
      "While 引导省略主语和 be 的让步状语，完整形式可理解为 while it is often praised。",
      "tend to do 表示‘往往倾向于做’，to 后接动词原形；stress A over B 表示更强调 A 而非 B。",
      "test taking 和 mechanical learning 是并列的动名词化名词短语。",
      "self-expression 是复合名词，表示自我表达；creativity 与它都是 over 的比较对象。",
    ],
    literal: "虽然日本教育常因强调基础而受到外国人称赞，但它倾向于把应试和机械学习置于创造力与自我表达之上。",
    natural: "外国人常称赞日本教育重视基础，但它往往过分强调应试和机械学习，压过了创造力与自我表达。",
    logic: "指出教育方式的核心矛盾：基础训练的优点伴随着对创造性和个性的压制。",
    phrases: ["praised by foreigners", "emphasis on the basics", "tends to stress", "test taking", "over creativity and self-expression"],
  },
  {
    id: "p4-s8",
    number: 8,
    text: "Those things that do not show up in the test scores—personality, ability, courage or humanity—are completely ignored, says Toshiki Kaifu, chairman of the ruling Liberal Democratic Party's education committee.",
    chunks: [
      { text: "Those things that do not show up in the test scores", role: "subject" },
      { text: "—personality, ability, courage or humanity—", role: "modifier" },
      { text: "are completely ignored,", role: "predicate" },
      { text: " says Toshiki Kaifu, chairman of the ruling Liberal Democratic Party's education committee.", role: "connector" },
    ],
    trunk: "Things not shown in test scores are completely ignored.",
    layers: [
      { label: "主语中心", text: "Those things：那些事项，指不能由分数体现的素质" },
      { label: "定语从句", text: "that do not show up in the test scores：不能出现在考试分数中的" },
      { label: "插入列举", text: "personality, ability, courage or humanity：人格、能力、勇气或人性" },
      { label: "引语来源", text: "says Toshiki Kaifu...：教育委员会主席海部俊树的判断" },
    ],
    grammar: [
      "Those things 是主语，that 引导限制性定语从句修饰 things；show up 表示‘显现出来’。",
      "破折号中的四个名词是同位语，具体列举 test scores 无法衡量的品质。",
      "are completely ignored 是被动语态，completely 强调完全被忽视。",
      "says Toshiki Kaifu 是置于句末的插入引语，chairman... 是同位语，补充说明身份。",
    ],
    literal: "那些不在考试分数中显现的东西——人格、能力、勇气或人性——都被完全忽视，统治自由民主党的教育委员会主席海部俊树说。",
    natural: "执政自民党教育委员会主席海部俊树说，考试分数无法体现的人格、能力、勇气和人性，全都被忽略了。",
    logic: "用权威引语具体说明教育评价体系遗漏了哪些人的品质，为学生挫折和暴力行为作因果铺垫。",
    phrases: ["show up in", "test scores", "are completely ignored", "chairman of", "the ruling Liberal Democratic Party's"],
  },
  {
    id: "p4-s9",
    number: 9,
    text: "Frustration against this kind of thing leads kids to drop out and run wild.",
    chunks: [
      { text: "Frustration against this kind of thing", role: "subject" },
      { text: " leads", role: "predicate" },
      { text: " kids to drop out and run wild.", role: "object" },
    ],
    trunk: "Frustration leads kids to drop out and run wild.",
    layers: [
      { label: "原因主语", text: "Frustration against this kind of thing：对这种教育方式的挫折感" },
      { label: "结果结构", text: "leads kids to...：导致孩子去做某事" },
      { label: "并列结果", text: "drop out and run wild：辍学并失去约束、胡闹" },
    ],
    grammar: [
      "frustration against 后接引起不满的对象；this kind of thing 指上一句所说的忽视。",
      "lead sb to do sth 是使役结果结构，to 后接不定式；主语 frustration 为不可数名词，谓语用 leads。",
      "drop out 是不及物短语动词，通常指退学或退出；run wild 表示行为失控。",
    ],
    literal: "对这种事情的挫折感导致孩子辍学并任意胡闹。",
    natural: "对这种教育方式的失望会让孩子辍学、放任自己失控。",
    logic: "把评价体系的缺陷连接到青少年行为后果，开始从教育问题转向社会暴力现象。",
    phrases: ["this kind of thing", "leads kids to", "drop out", "run wild"],
  },
  {
    id: "p4-s10",
    number: 10,
    text: "Last year Japan experienced 2,125 incidents of school violence, including 929 assaults on teachers.",
    chunks: [
      { text: "Last year", role: "modifier" },
      { text: " Japan", role: "subject" },
      { text: " experienced", role: "predicate" },
      { text: " 2,125 incidents of school violence,", role: "object" },
      { text: " including 929 assaults on teachers.", role: "modifier" },
    ],
    trunk: "Japan experienced many incidents of school violence, including assaults on teachers.",
    layers: [
      { label: "时间", text: "Last year：把统计限定在上一年度" },
      { label: "主谓宾", text: "Japan experienced 2,125 incidents：日本发生了2125起事件" },
      { label: "类别说明", text: "of school violence：说明事件属于校园暴力" },
      { label: "举例补充", text: "including 929 assaults on teachers：其中929起是袭击教师" },
    ],
    grammar: [
      "experience 在此是及物动词，表示经历或遭遇某种事件，不是‘体验快乐’的单一含义。",
      "incidents of + 名词表示某类事件的数量；school violence 是不可数类别名词。",
      "including 引出整体中的具体部分，929 assaults 是被包含的数量。",
      "assault on sb 表示对某人的攻击，on 不能省略或随意改为 at。",
    ],
    literal: "去年日本经历了2125起校园暴力事件，其中包括929起对教师的袭击。",
    natural: "去年日本发生了2125起校园暴力事件，其中929起是袭击教师。",
    logic: "以具体统计把前句的‘失控’从评价变成可核验的社会事实。",
    phrases: ["Last year", "incidents of", "school violence", "including 929 assaults on teachers", "assaults on teachers"],
  },
  {
    id: "p4-s11",
    number: 11,
    text: "Amid the outcry, many conservative leaders are seeking a return to the prewar emphasis on moral education.",
    chunks: [
      { text: "Amid the outcry,", role: "modifier" },
      { text: " many conservative leaders", role: "subject" },
      { text: " are seeking", role: "predicate" },
      { text: " a return to the prewar emphasis on moral education.", role: "object" },
    ],
    trunk: "Conservative leaders are seeking a return to prewar moral education.",
    layers: [
      { label: "社会反应", text: "Amid the outcry：在公众强烈抗议声中" },
      { label: "行动主体", text: "many conservative leaders are seeking：许多保守派领导人正在寻求" },
      { label: "目标", text: "a return to the prewar emphasis：回到战前的重视方式" },
      { label: "教育领域", text: "on moral education：重视道德教育" },
    ],
    grammar: [
      "amid 是介词，表示‘在……之中’；outcry 指公众因严重问题发出的强烈抗议。",
      "seek 后接名词或不定式；seek a return to 表示寻求恢复到某种状态。",
      "return to 与 emphasis on 分别表达回归对象和重视内容，两个介词不能混用。",
      "prewar 是复合形容词，指第二次世界大战前的时期。",
    ],
    literal: "在抗议声中，许多保守派领导人正在寻求回到战前重视道德教育的做法。",
    natural: "面对舆论哗然，许多保守派领导人要求恢复战前那种重视道德教育的传统。",
    logic: "呈现保守派提出的政策回应，但下一句将说明这种解释可能忽略了更深层的生活方式因素。",
    phrases: ["Amid the outcry", "are seeking a return to", "prewar emphasis on", "moral education"],
  },
  {
    id: "p4-s12",
    number: 12,
    text: "Last year Mitsuo Setoyama, who was then education minister, raised eyebrows when he argued that liberal reforms introduced by the American occupation authorities after World War II had weakened the \"Japanese morality of respect for parents.\"",
    chunks: [
      { text: "Last year Mitsuo Setoyama,", role: "subject" },
      { text: " who was then education minister,", role: "modifier" },
      { text: " raised eyebrows", role: "predicate" },
      { text: " when he argued that liberal reforms introduced by the American occupation authorities after World War II had weakened the \"Japanese morality of respect for parents.\"", role: "object" },
    ],
    trunk: "Setoyama caused surprise by arguing that postwar reforms weakened respect for parents.",
    layers: [
      { label: "人物与同位语", text: "Mitsuo Setoyama, who was then education minister：时任教育部长的濑户山三男" },
      { label: "反应表达", text: "raised eyebrows：引起惊讶或争议" },
      { label: "时间条件", text: "when he argued that...：当他提出某个论断时" },
      { label: "宾语从句", text: "liberal reforms ... had weakened...：自由改革削弱了尊重父母的日本道德" },
    ],
    grammar: [
      "who 引导非限制性定语从句，补充说明 Mitsuo Setoyama 当时的职务。",
      "raise eyebrows 是习语，表示引起惊讶、怀疑或非议，不是字面上的抬眉毛。",
      "when 引导时间状语从句，argued 后接 that 宾语从句；introduced by... 是 reforms 的后置修饰。",
      "had weakened 是过去完成时，表示在他发表观点时，削弱作用已被认为发生在更早的战后改革阶段。",
    ],
    literal: "去年，时任教育部长的濑户山三男在主张美国占领当局在二战后引入的自由改革削弱了‘日本尊重父母的道德’时，引起了惊讶。",
    natural: "去年，时任教育部长的濑户山三男认为，美国占领当局二战后推行的自由化改革削弱了日本尊重父母的道德观，这番话引起了争议。",
    logic: "具体举出保守派把道德下降归因于战后改革的观点，同时为下一段提出生活方式解释留下转折空间。",
    phrases: ["raised eyebrows", "he argued that", "introduced by", "after World War II", "respect for parents"],
  },
  {
    id: "p4-s13",
    number: 13,
    text: "But that may have more to do with Japanese life-styles.",
    chunks: [
      { text: "But", role: "connector" },
      { text: " that", role: "subject" },
      { text: " may have more to do with", role: "predicate" },
      { text: " Japanese life-styles.", role: "object" },
    ],
    trunk: "That may have more to do with Japanese life-styles.",
    layers: [
      { label: "转折指代", text: "But that：但前面所说的道德问题可能另有原因" },
      { label: "可能性", text: "may have more to do with：可能更多与……有关" },
      { label: "原因范围", text: "Japanese life-styles：日本人的生活方式" },
    ],
    grammar: [
      "that 是指示代词，回指前文关于道德下降的解释或现象。",
      "have to do with 表示‘与……有关’，more 修饰比较关系，暗示生活方式比战后改革更关键。",
      "may + 动词原形表示推测；have 在这里是实义动词，不是完成时助动词。",
      "life-styles 是原文复合名词复数，指一整套生活方式。",
    ],
    literal: "但那可能更多与日本的生活方式有关。",
    natural: "不过，问题或许更多源于日本人的生活方式。",
    logic: "短句承担全篇关键转折：作者不完全接受把道德问题归咎于教育改革的解释。",
    phrases: ["have more to do with", "Japanese life-styles"],
  },
  {
    id: "p4-s14",
    number: 14,
    text: "\"In Japan,\" says educator Yoko Muro, \"it's never a question of whether you enjoy your job and your life, but only how much you can endure.\"",
    chunks: [
      { text: "\"In Japan,\"", role: "modifier" },
      { text: " says educator Yoko Muro,", role: "connector" },
      { text: " \"it's never a question of whether you enjoy your job and your life,", role: "subject" },
      { text: " but only how much you can endure.\"", role: "predicate" },
    ],
    trunk: "In Japan, the issue is not whether people enjoy life but how much they can endure.",
    layers: [
      { label: "引语框架", text: "says educator Yoko Muro：教育家室町洋子转述日本社会的观念" },
      { label: "否定判断", text: "it's never a question of whether...：问题从来不是是否享受" },
      { label: "whether 从句", text: "whether you enjoy your job and your life：是否享受工作和生活" },
      { label: "真正标准", text: "but only how much you can endure：而只是能忍受多少" },
    ],
    grammar: [
      "it's a question of... 是固定结构，of 后可接名词或 whether/how 引导的从句。",
      "whether you enjoy... 与 how much you can endure 构成 not... but... 的平行比较。",
      "how much 引导宾语从句，much 修饰不可数概念 endurance；can 后接动词原形 endure。",
      "引语中的 it 是形式主语，真正讨论内容由 question of 后面的从句承担。",
    ],
    literal: "在日本，教育家室町洋子说，这从来不是你是否享受工作和生活的问题，而只是你能忍受多少的问题。",
    natural: "教育家室町洋子说，在日本，人们从不问工作和生活是否快乐，只问自己还能忍受多少。",
    logic: "用访谈式概括揭示生活方式的核心心态：忍耐取代了享受，解释了不满为何不断累积。",
    phrases: ["a question of whether", "enjoy your job and your life", "how much you can endure", "but only how much you can endure"],
  },
  {
    id: "p4-s15",
    number: 15,
    text: "With economic growth has come centralization; fully 76 percent of Japan's 119 million citizens live in cities where community and the extended family have been abandoned in favor of isolated, two-generation households.",
    chunks: [
      { text: "With economic growth has come centralization;", role: "connector" },
      { text: " fully 76 percent of Japan's 119 million citizens", role: "subject" },
      { text: " live", role: "predicate" },
      { text: " in cities where community and the extended family have been abandoned in favor of isolated, two-generation households.", role: "modifier" },
    ],
    trunk: "Economic growth has brought centralization, with most citizens living in isolated urban households.",
    layers: [
      { label: "倒装结果", text: "With economic growth has come centralization：经济增长伴随着集中化" },
      { label: "数量主语", text: "76 percent of Japan's 119 million citizens：日本1.19亿公民中的76%" },
      { label: "地点从句", text: "live in cities where...：居住在城市，而城市中的传统关系已被放弃" },
      { label: "取代关系", text: "in favor of isolated, two-generation households：转而选择孤立的两代家庭" },
    ],
    grammar: [
      "With + 名词置于句首时，has come centralization 是倒装结构，正常语序是 centralization has come with economic growth。",
      "percent of + citizens 作主语时谓语用复数 live；fully 修饰百分比，表示整整。",
      "where 引导定语从句修饰 cities；have been abandoned 是现在完成时被动，主语是 community and the extended family。",
      "in favor of 表示‘支持、选择……而不是……’，isolated 和 two-generation 都是 households 的前置修饰语。",
    ],
    literal: "随着经济增长，集中化也到来了；日本1.19亿公民中整整76%住在城市，在那里社区和大家庭已被抛弃，转而采用孤立的两代家庭。",
    natural: "经济增长带来了城市集中化：日本1.19亿人口中有76%住在城市，社区和大家庭被孤立的两代小家庭取代。",
    logic: "说明经济增长的空间代价：城市化削弱社区和扩展家庭，为下一句的通勤、拥挤和孤独埋下原因。",
    phrases: ["With economic growth", "has come centralization", "percent of", "live in cities", "in favor of", "two-generation households"],
  },
  {
    id: "p4-s16",
    number: 16,
    text: "Urban Japanese have long endured lengthy commutes (travels to and from work) and crowded living conditions, but as the old group and family values weaken, the discomfort is beginning to tell.",
    chunks: [
      { text: "Urban Japanese", role: "subject" },
      { text: " have long endured", role: "predicate" },
      { text: " lengthy commutes (travels to and from work) and crowded living conditions,", role: "object" },
      { text: " but as the old group and family values weaken,", role: "condition" },
      { text: " the discomfort", role: "subject" },
      { text: " is beginning to tell.", role: "predicate" },
    ],
    trunk: "Urban Japanese have endured crowded commutes, and the resulting discomfort is beginning to show.",
    layers: [
      { label: "城市群体", text: "Urban Japanese：城市中的日本人" },
      { label: "长期负担", text: "have long endured lengthy commutes and crowded living conditions：长期忍受漫长通勤和拥挤居住条件" },
      { label: "条件变化", text: "as the old group and family values weaken：随着旧有群体和家庭价值削弱" },
      { label: "显现后果", text: "the discomfort is beginning to tell：不适开始显现影响" },
    ],
    grammar: [
      "have long endured 是现在完成时，long 强调从过去延续到现在。",
      "commute 在名词中指上下班路程；括号中的 travels to and from work 是对 commutes 的解释。",
      "as 引导时间兼原因状语从句，weaken 为不及物动词，主语是并列的 values。",
      "begin to tell 是习语，表示某种压力开始产生明显后果；tell 不是‘讲述’。",
    ],
    literal: "城市日本人长期忍受漫长通勤（往返工作的旅程）和拥挤的生活条件，但随着旧有群体和家庭价值观削弱，不适开始产生影响。",
    natural: "城市居民早已习惯漫长通勤和拥挤居住；然而，随着传统群体和家庭价值观衰落，这些不适开始显出后果。",
    logic: "把上一句的结构变化落实为日常压力，并指出传统价值减弱后，长期忍耐终于转化为社会症状。",
    phrases: ["have long endured", "to and from work", "living conditions", "as the old group and family values weaken", "is beginning to tell"],
  },
  {
    id: "p4-s17",
    number: 17,
    text: "In the past decade, the Japanese divorce rate, while still well below that of the United States, has increased by more than 50 percent, and suicides have increased by nearly one-quarter.",
    chunks: [
      { text: "In the past decade,", role: "modifier" },
      { text: " the Japanese divorce rate,", role: "subject" },
      { text: " while still well below that of the United States,", role: "modifier" },
      { text: " has increased by more than 50 percent,", role: "predicate" },
      { text: " and suicides have increased by nearly one-quarter.", role: "connector" },
    ],
    trunk: "Over the past decade, divorce and suicide rates in Japan have risen sharply.",
    layers: [
      { label: "时间范围", text: "In the past decade：在过去十年中" },
      { label: "主句一", text: "the Japanese divorce rate has increased by more than 50 percent：日本离婚率上升超过50%" },
      { label: "让步比较", text: "while still well below that of the United States：虽然仍远低于美国的离婚率" },
      { label: "并列结果", text: "suicides have increased by nearly one-quarter：自杀人数也增加了近四分之一" },
    ],
    grammar: [
      "in the past decade 与现在完成时 has increased 搭配，表示截至现在的变化。",
      "while 引导省略主语和 be 的让步插入语；that 代替前面的 divorce rate，避免重复。",
      "increase by + 百分比表示增加的幅度，more than 50 percent 是超过原数的一半。",
      "one-quarter 是分数名词，nearly 修饰分数；and 连接第二个完整分句，所以用 have。",
    ],
    literal: "在过去十年中，日本的离婚率虽然仍远低于美国的离婚率，却增加了超过50%；自杀人数也增加了近四分之一。",
    natural: "过去十年，日本离婚率虽仍远低于美国，却上升了50%以上；自杀人数也增加了近四分之一。",
    logic: "以离婚和自杀两项硬指标收束全文，显示生活方式和价值瓦解已经造成严重社会后果。",
    phrases: ["In the past decade", "well below that of", "has increased by", "more than 50 percent", "by nearly one-quarter"],
  },
];

export const passage4Questions: Question[] = [
  {
    id: 23,
    sentenceId: "p4-s1",
    prompt: "In the Westerners' eyes, the postwar Japan was.",
    options: [
      { key: "A", text: "under aimless development" },
      { key: "B", text: "a positive example" },
      { key: "C", text: "a rival to the West" },
      { key: "D", text: "on the decline" },
    ],
    answer: "B",
    locating: "第1句说战后日本的生产力和社会和谐是美国和欧洲羡慕的对象，说明在西方人眼中它是正面范例。",
    explanations: {
      A: "错误。aimlessness 与第1句的 hardly been typical 相反，文章说无目标并非战后日本的典型。",
      B: "正确。productivity and social harmony are the envy of the United States and Europe 明确表达了西方对日本成就的羡慕。",
      C: "错误。文章没有说日本是西方的竞争对手，rival 偷换了 envy 的评价关系。",
      D: "错误。decline 是后文传统工作道德的衰退，不是西方对战后日本整体形象的判断。",
    },
    analysis: {
      prompt: questionAnalysis(
        "p4-q23-prompt",
        23,
        "In the Westerners' eyes, the postwar Japan was.",
        [
          { text: "In the Westerners' eyes,", role: "modifier" },
          { text: " the postwar Japan", role: "subject" },
          { text: " was.", role: "predicate" },
        ],
        "The postwar Japan was + a description",
        [
          { label: "评价来源", text: "In the Westerners' eyes：限定评价来自西方人" },
          { label: "评价对象", text: "the postwar Japan：指战后日本的整体形象" },
          { label: "待补表语", text: "was：系动词后由 A-D 选项补充评价" },
        ],
        [
          "in one's eyes 是介词短语，表示‘在某人看来’，限定观点来源。",
          "was 后需要名词短语或形容词短语作表语；主旨题要选择概括性评价。",
        ],
        "在西方人的眼中，战后日本是……",
        "西方人怎样评价战后日本？",
        "题干要求回到第1句的整体评价，不能把后文的道德衰退提前当成战后日本的总体形象。",
        ["In the Westerners' eyes", "postwar Japan"],
      ),
      options: {
        A: questionAnalysis("p4-q23-option-a", 23, "under aimless development", [{ text: "under", role: "modifier" }, { text: " aimless development", role: "object" }], "Japan was under aimless development", [{ label: "介词", text: "under：引出所处的状态" }, { label: "名词短语", text: "aimless development：无明确目标的发展" }], ["under 后接名词短语，结构本身成立。", "aimlessness 在原文中被 hardly 否定，不能改写成正面结论。"], "处于无目标的发展中", "发展缺乏明确方向", "与第1句‘无所事事并非典型’的明确否定相冲突。", ["under aimless development"]),
        B: questionAnalysis("p4-q23-option-b", 23, "a positive example", [{ text: "a positive", role: "subject" }, { text: " example", role: "predicate" }], "Japan was a positive example", [{ label: "表语", text: "a positive example：一个正面范例" }], ["a + adjective + noun 构成名词短语作表语。", "positive example 概括 productivity 和 social harmony 受到羡慕的评价。"], "一个正面范例", "一个值得肯定和借鉴的例子", "与 the envy of the United States and Europe 的正面评价一致。", ["positive example"]),
        C: questionAnalysis("p4-q23-option-c", 23, "a rival to the West", [{ text: "a rival", role: "subject" }, { text: " to the West", role: "modifier" }], "Japan was a rival to the West", [{ label: "中心名词", text: "a rival：竞争对手" }, { label: "对象介词", text: "to the West：对西方而言" }], ["rival to 后接竞争对象，to 不是方向移动。", "原文表达羡慕和社会成就，不等于政治或经济对抗。"], "西方的竞争对手", "一个与西方对抗的竞争者", "文章没有给出 rival 关系，选项改变了评价性质。", ["a rival to"]),
        D: questionAnalysis("p4-q23-option-d", 23, "on the decline", [{ text: "on", role: "modifier" }, { text: " the decline", role: "predicate" }], "Japan was on the decline", [{ label: "状态短语", text: "on the decline：处于衰退中" }], ["on the decline 是介词短语作表语，表示正在衰退。", "第2句的 decline 修饰传统工作道德价值，不能扩大为战后日本整体在西方眼中已衰退。"], "处于衰退中", "正在走下坡路", "把后文正在出现的道德问题错当成第1句所述的历史整体评价。", ["on the decline"]),
      },
      answer: questionAnalysis("p4-q23-answer", 23, "In the Westerners' eyes, the postwar Japan was a positive example.", [{ text: "In the Westerners' eyes,", role: "modifier" }, { text: " the postwar Japan", role: "subject" }, { text: " was", role: "predicate" }, { text: " a positive example.", role: "object" }], "The postwar Japan was a positive example in Westerners' eyes.", [{ label: "评价来源", text: "In the Westerners' eyes：表明评价者是西方人" }, { label: "主语", text: "the postwar Japan：被评价的战后日本" }, { label: "表语", text: "a positive example：正面范例" }], ["was 是系动词，a positive example 作主语补足语。", "positive example 概括 productivity and social harmony 令西方羡慕的事实。"], "在西方人的眼中，战后日本是一个正面范例。", "西方人曾把战后日本视为值得肯定的样板。", "组合句完整复述第1句的评价关系，为后文的今昔反差定下基调。", ["In the Westerners' eyes", "a positive example"]),
    },
  },
  {
    id: 24,
    sentenceId: "p4-s7",
    prompt: "According to the author, what may chiefly be responsible for the moral decline of Japanese society?",
    options: [
      { key: "A", text: "Women's participation in social activities is limited." },
      { key: "B", text: "More workers are dissatisfied with their jobs." },
      { key: "C", text: "Excessive emphasis has been placed on the basics." },
      { key: "D", text: "The life-style has been influenced by Western values." },
    ],
    answer: "D",
    locating: "第12句先引述教育部长把道德衰退归因于战后美国改革，第13句作者用 But that may have more to do with Japanese life-styles 转折，指出主要原因更在生活方式；后文的城市集中化和两代隔离家庭说明这种生活方式受西方化价值结构影响。",
    explanations: {
      A: "错误。原文说女性进入男性主导的职场限制了青少年机会，并非女性参与社会活动受到限制。",
      B: "错误。工人不满是社会问题的表现和旁证，不是作者归纳的道德衰退首要原因。",
      C: "错误。原文说教育在强调基础知识的同时忽视创造力，并没有说对 basics 的重视本身 excessive；该项把教育问题扩大为首要原因。",
      D: "正确。第13句用 more to do with 明确把主要原因转向 Japanese life-styles，后文的城市集中化、大家庭瓦解和两代家庭隔离体现了西方化价值结构对生活方式的影响。",
    },
    analysis: {
      prompt: questionAnalysis("p4-q24-prompt", 24, "According to the author, what may chiefly be responsible for the moral decline of Japanese society?", [{ text: "According to the author,", role: "modifier" }, { text: " what", role: "subject" }, { text: " may chiefly be responsible", role: "predicate" }, { text: " for the moral decline of Japanese society?", role: "object" }], "What may be chiefly responsible for the moral decline?", [{ label: "观点来源", text: "According to the author：要求依据作者而不是常识作答" }, { label: "责任主体", text: "what may chiefly be responsible：询问最主要的原因" }, { label: "结果对象", text: "the moral decline of Japanese society：日本社会的道德衰退" }], ["according to 后接名词表示信息来源。", "be responsible for 表示‘对……负责或是……的原因’，chiefly 修饰责任程度。"], "根据作者，什么可能是日本社会道德衰退的主要原因？", "作者认为日本社会为何出现道德下滑？", "题目要求寻找主要原因，不能把统计表现、背景条件或未被作者支持的西方影响当答案。", ["according to the author", "may chiefly be responsible for"]),
      options: {
        A: questionAnalysis("p4-q24-option-a", 24, "Women's participation in social activities is limited.", [{ text: "Women's participation in social activities", role: "subject" }, { text: " is limited.", role: "predicate" }], "Women's participation is limited", [{ label: "主语", text: "Women's participation in social activities：女性参与社会活动" }, { label: "被动谓语", text: "is limited：受到限制" }], ["participation in 后接活动领域，in 不表示时间。", "原文是 women entry into the job market，方向是进入职场，不是参与受到限制。"], "女性参与社会活动受到限制。", "女性无法充分参与社会生活。", "把原文‘女性进入职场’改成‘女性参与受限’，与事实方向相反。", ["participation in", "is limited"]),
        B: questionAnalysis("p4-q24-option-b", 24, "More workers are dissatisfied with their jobs.", [{ text: "More workers", role: "subject" }, { text: " are dissatisfied", role: "predicate" }, { text: " with their jobs.", role: "modifier" }], "More workers are dissatisfied with their jobs", [{ label: "比较数量", text: "More workers：更多工人" }, { label: "状态", text: "are dissatisfied with their jobs：对工作不满" }], ["be dissatisfied with 是形容词搭配，with 后接不满对象。", "第6句把工人不满作为社会不适的证据，并未说它是道德衰退的首要成因。"], "更多工人对工作不满。", "越来越多的工人觉得工作不如意。", "这是文章列举的表现，不是第7—9句所强调的教育机制。", ["are dissatisfied with"]),
        C: questionAnalysis("p4-q24-option-c", 24, "Excessive emphasis has been placed on the basics.", [{ text: "Excessive emphasis", role: "subject" }, { text: " has been placed", role: "predicate" }, { text: " on the basics.", role: "object" }], "Excessive emphasis has been placed on the basics", [{ label: "主语", text: "Excessive emphasis：过度的重视" }, { label: "被动结构", text: "has been placed on the basics：被放在基础知识上" }], ["place emphasis on 是固定搭配，被动式为 emphasis has been placed on。", "原文批评的是 stress test taking and mechanical learning over creativity，并未把 basics 本身定性为 excessive。"], "过多的重视被放在基础知识上。", "教育把基础知识看得过重。", "把‘强调基础却忽略创造力’偷换成‘过度强调基础’，且没有抓住第13句 more to do with 指出的主要原因。", ["emphasis has been placed on"]),
        D: questionAnalysis("p4-q24-option-d", 24, "The life-style has been influenced by Western values.", [{ text: "The life-style", role: "subject" }, { text: " has been influenced", role: "predicate" }, { text: " by Western values.", role: "modifier" }], "The life-style has been influenced by Western values", [{ label: "被动来源", text: "has been influenced by Western values：受到西方价值观影响" }], ["be influenced by 表示被动接受影响，by 后接来源。", "第13句的 more to do with Japanese life-styles 是主要原因信号，后文的城市化、大家庭瓦解和隔离式两代家庭具体说明这种改变。"], "这种生活方式受到西方价值观影响。", "日本人的生活方式受到了西方价值结构的影响。", "概括第13—17句的因果链：生活方式西方化改变家庭和社区结构，进而削弱传统道德约束。", ["has been influenced by", "Western values"]),
      },
      answer: questionAnalysis("p4-q24-answer", 24, "According to the author, the life-style has been influenced by Western values.", [{ text: "According to the author,", role: "modifier" }, { text: " the life-style", role: "subject" }, { text: " has been influenced", role: "predicate" }, { text: " by Western values.", role: "modifier" }], "The life-style has been influenced by Western values.", [{ label: "依据", text: "According to the author：把答案限定为作者的判断" }, { label: "核心主语", text: "the life-style：第13句转折后强调的日本生活方式" }, { label: "影响来源", text: "has been influenced by Western values：受到西方价值结构影响" }], ["be influenced by 是现在完成时的被动结构，by 引出影响来源。", "more to do with Japanese life-styles 是主因提示，后文以城市集中化、家庭隔离和传统群体价值瓦解展开说明。"], "根据作者，这种生活方式受到了西方价值观的影响。", "作者认为，道德衰退的主因是日本生活方式受到西方价值结构影响。", "组合句把题干的主要原因追问与第13—17句生活方式转折及后续证据接合。", ["according to the author", "has been influenced by", "Western values"]),
    },
  },
  {
    id: 25,
    sentenceId: "p4-s8",
    prompt: "Which of the following is true according to the author?",
    options: [
      { key: "A", text: "Japanese education is praised for helping the young climb the social ladder." },
      { key: "B", text: "Japanese education is characterized by mechanical learning as well as creativity." },
      { key: "C", text: "More stress should be placed on the cultivation of creativity." },
      { key: "D", text: "Dropping out leads to frustration against test taking." },
    ],
    answer: "C",
    locating: "第7句说日本教育把应试和机械学习置于创造力之上，第8句说人格、能力、勇气和人性被忽视，因此作者的方向是应更多培养创造力，C 正确。",
    explanations: {
      A: "错误。climbing the social ladder 是青少年为好学校和工作付出牺牲的背景，不是外国人称赞日本教育的内容。",
      B: "错误。原文说 mechanical learning over creativity，强调机械学习压过创造力，不是二者同等并列。",
      C: "正确。既然创造力和自我表达被应试教育压制，作者的批评隐含要求增加对创造力的重视。",
      D: "错误。原文是 frustration against this kind of thing leads kids to drop out，因果方向是挫折导致辍学，而非辍学导致挫折。",
    },
    analysis: {
      prompt: questionAnalysis("p4-q25-prompt", 25, "Which of the following is true according to the author?", [{ text: "Which of the following", role: "subject" }, { text: " is true", role: "predicate" }, { text: " according to the author?", role: "modifier" }], "Which statement is true according to the author?", [{ label: "选择范围", text: "Which of the following：从下面四项中选择" }, { label: "判断", text: "is true：寻找与文章一致的陈述" }, { label: "依据", text: "according to the author：必须回到作者原文" }], ["which 引导疑问限定词，following 在此作形容词表示‘下列的’。", "be true according to 是判断题常用框架，不能只凭选项语法正确作答。"], "下列哪一项根据作者是正确的？", "四个陈述中哪一个真正符合作者的观点？", "这是正误判断题，关键在核对原文的比较关系和因果方向。", ["according to the author"]),
      options: {
        A: questionAnalysis("p4-q25-option-a", 25, "Japanese education is praised for helping the young climb the social ladder.", [{ text: "Japanese education", role: "subject" }, { text: " is praised", role: "predicate" }, { text: " for helping the young climb the social ladder.", role: "object" }], "Japanese education is praised for helping the young climb the social ladder", [{ label: "被动评价", text: "is praised for：因某个原因受到称赞" }, { label: "动名词结构", text: "helping the young climb the social ladder：帮助年轻人攀登社会阶梯" }], ["praise sb/sth for doing 表示因某行为或作用而称赞。", "原文 praised by foreigners for emphasis on the basics，不是因为帮助年轻人爬社会阶梯。"], "日本教育因帮助年轻人攀登社会阶梯而受到称赞。", "有人称赞日本教育能帮助年轻人获得好学校和工作。", "偷换了原文的称赞理由；社会阶梯是青少年牺牲和质疑的对象。", ["is praised for", "helping the young climb the social ladder", "climb the social ladder"]),
        B: questionAnalysis("p4-q25-option-b", 25, "Japanese education is characterized by mechanical learning as well as creativity.", [{ text: "Japanese education", role: "subject" }, { text: " is characterized", role: "predicate" }, { text: " by mechanical learning as well as creativity.", role: "modifier" }], "Japanese education is characterized by mechanical learning rather than creativity", [{ label: "特征来源", text: "is characterized by：以某特征为特点" }, { label: "对比对象", text: "mechanical learning as well as creativity：机械学习以及创造力" }], ["be characterized by 后接特征，as well as 表示‘以及’。", "原文用 over 表示机械学习压过创造力，as well as 把不平等关系改成并列。"], "日本教育的特点是机械学习以及创造力。", "日本教育既重机械学习，也同样重视创造力。", "把作者批评的失衡关系改成平衡并列，违背第7句。", ["is characterized by", "as well as"]),
        C: questionAnalysis("p4-q25-option-c", 25, "More stress should be placed on the cultivation of creativity.", [{ text: "More stress", role: "subject" }, { text: " should be placed", role: "predicate" }, { text: " on the cultivation of creativity.", role: "object" }], "More stress should be placed on cultivating creativity", [{ label: "建议主语", text: "More stress：更多的重视" }, { label: "被动建议", text: "should be placed on：应该放在……上" }, { label: "对象", text: "the cultivation of creativity：创造力的培养" }], ["place stress on 与 place emphasis on 一样，on 引出重视对象。", "should be placed 是情态动词加被动语态，表达根据批评可推出的改进方向。"], "更多的重视应该被放在创造力的培养上。", "教育应该更多培养创造力。", "与第7句对 creativity 的压制、第8句对人格等分数外品质的批评一致。", ["should be placed on", "cultivation of creativity"]),
        D: questionAnalysis("p4-q25-option-d", 25, "Dropping out leads to frustration against test taking.", [{ text: "Dropping out", role: "subject" }, { text: " leads", role: "predicate" }, { text: " to frustration against test taking.", role: "object" }], "Dropping out leads to frustration", [{ label: "动名词主语", text: "Dropping out：辍学这一行为" }, { label: "结果", text: "leads to frustration：导致挫折感" }], ["lead to 后接名词或动名词，表示导致结果。", "原文因果链是 frustration leads kids to drop out，选项把原因和结果倒置。"], "辍学导致对考试的挫折感。", "把辍学说成挫折的原因。", "与第9句明确的因果方向相反，且原文的 frustration 针对教育方式而非辍学之后。", ["leads to"]),
      },
      answer: questionAnalysis("p4-q25-answer", 25, "According to the author, more stress should be placed on the cultivation of creativity.", [{ text: "According to the author,", role: "modifier" }, { text: " more stress", role: "subject" }, { text: " should be placed", role: "predicate" }, { text: " on the cultivation of creativity.", role: "object" }], "More stress should be placed on cultivating creativity.", [{ label: "观点来源", text: "According to the author：结论来自作者对教育的批评" }, { label: "改进重点", text: "more stress should be placed：应增加重视程度" }, { label: "培养对象", text: "the cultivation of creativity：创造力的培养" }], ["should be placed on 是被动建议结构，on 后接目标。", "cultivation of creativity 把第7句被压低的 creativity 转成改革重点。"], "根据作者，应该更多重视创造力的培养。", "作者认为教育需要把更多精力放在培养创造力上。", "组合句正确保留原文的比较方向和规范化建议。", ["according to the author", "should be placed on"]),
    },
  },
  {
    id: 26,
    sentenceId: "p4-s16",
    prompt: "The change in Japanese life-style is revealed in the fact that.",
    options: [
      { key: "A", text: "the young are less tolerant of discomforts in life" },
      { key: "B", text: "the divorce rate in Japan exceeds that in the U.S." },
      { key: "C", text: "the Japanese endure more than ever before" },
      { key: "D", text: "the Japanese appreciate their present life" },
    ],
    answer: "A",
    locating: "第13—17句说明日本人长期忍受通勤和拥挤，但传统价值削弱后不适开始显现，离婚和自杀上升；这表明年轻人对生活不适的容忍度下降，A 最符合。",
    explanations: {
      A: "正确。文章说旧群体和家庭价值减弱后，长期不适开始产生影响，反映出年轻人不再像过去那样能忍受生活压力。",
      B: "错误。第17句明确说日本离婚率仍 well below that of the United States，未超过美国。",
      C: "错误。文章说过去长期 endure，但现在 discomfort is beginning to tell，不能推出比以往更能忍受。",
      D: "错误。全文数据反映不满、离婚和自杀增加，说明并非更欣赏当前生活。",
    },
    analysis: {
      prompt: questionAnalysis("p4-q26-prompt", 26, "The change in Japanese life-style is revealed in the fact that.", [{ text: "The change in Japanese life-style", role: "subject" }, { text: " is revealed", role: "predicate" }, { text: " in the fact that.", role: "object" }], "The change is revealed in the fact that + clause", [{ label: "主语", text: "The change in Japanese life-style：日本生活方式的变化" }, { label: "被动框架", text: "is revealed in the fact that：通过某事实显现出来" }, { label: "待补事实", text: "that 后由选项补充具体表现" }], ["be revealed in the fact that 是被动表达，that 引导同位语从句说明事实内容。", "题干末尾句号表示选项要接在 that 后形成完整陈述。"], "日本生活方式的变化体现在这样一个事实上：……", "哪一项事实体现了日本生活方式的变化？", "需要选择与第16—17句社会后果一致的事实，而非与原文数字相反的比较。", ["is revealed in", "the fact that"]),
      options: {
        A: questionAnalysis("p4-q26-option-a", 26, "the young are less tolerant of discomforts in life", [{ text: "the young", role: "subject" }, { text: " are less tolerant", role: "predicate" }, { text: " of discomforts in life", role: "modifier" }], "The young are less tolerant of discomforts in life", [{ label: "主语", text: "the young：年轻人这一群体" }, { label: "比较状态", text: "are less tolerant of：对……的容忍度更低" }, { label: "对象", text: "discomforts in life：生活中的不适" }], ["the + 形容词表示一类人；be tolerant of 后接能够容忍的对象。", "less tolerant 与过去长期 endure、如今 discomfort tell 的对照相吻合。"], "年轻人对生活中的不适更不能容忍。", "年轻人忍受生活压力的能力下降了。", "准确概括传统价值削弱后长期压力开始显现的变化。", ["tolerant of", "less tolerant of"]),
        B: questionAnalysis("p4-q26-option-b", 26, "the divorce rate in Japan exceeds that in the U.S.", [{ text: "the divorce rate in Japan", role: "subject" }, { text: " exceeds", role: "predicate" }, { text: " that in the U.S.", role: "object" }], "The divorce rate in Japan exceeds that in the U.S.", [{ label: "比较主体", text: "the divorce rate in Japan：日本离婚率" }, { label: "比较动词", text: "exceeds：超过" }, { label: "替代代词", text: "that in the U.S.：that 代替美国的 divorce rate" }], ["exceed 是及物动词，that 是指示代词，代替前面重复的名词。", "第17句说日本离婚率 well below 美国，exceeds 与原文相反。"], "日本离婚率超过美国离婚率。", "日本的离婚率比美国还高。", "直接违背原文的 well below that of the United States。", ["exceeds that in"]),
        C: questionAnalysis("p4-q26-option-c", 26, "the Japanese endure more than ever before", [{ text: "the Japanese", role: "subject" }, { text: " endure", role: "predicate" }, { text: " more than ever before", role: "modifier" }], "The Japanese endure more than ever before", [{ label: "群体主语", text: "the Japanese：日本人整体" }, { label: "动作", text: "endure：忍受、承受" }, { label: "比较时间", text: "more than ever before：比过去任何时候更多" }], ["more than ever before 是比较程度状语，ever before 指此前任何时候。", "作者说旧价值削弱后不适开始显现，重点是忍耐机制失效而不是忍受更多。"], "日本人比以往任何时候都忍受得更多。", "日本人比过去更能承受生活压力。", "把‘不适开始产生影响’错误理解成忍耐能力增强。", ["more than ever before"]),
        D: questionAnalysis("p4-q26-option-d", 26, "the Japanese appreciate their present life", [{ text: "the Japanese", role: "subject" }, { text: " appreciate", role: "predicate" }, { text: " their present life", role: "object" }], "The Japanese appreciate their present life", [{ label: "主语", text: "the Japanese：日本人" }, { label: "谓语", text: "appreciate：欣赏、感激" }, { label: "宾语", text: "their present life：当前生活" }], ["appreciate 可接名词作宾语，表示欣赏或重视。", "文章数据呈现不满、离婚和自杀增加，不能推出对现状更欣赏。"], "日本人欣赏他们当前的生活。", "日本人更加认可现在的生活。", "与全文的 dissatisfaction、discomfort 和社会问题数据相反。", ["present life"]),
      },
      answer: questionAnalysis("p4-q26-answer", 26, "The change in Japanese life-style is revealed in the fact that the young are less tolerant of discomforts in life.", [{ text: "The change in Japanese life-style", role: "subject" }, { text: " is revealed", role: "predicate" }, { text: " in the fact that", role: "modifier" }, { text: " the young are less tolerant of discomforts in life.", role: "object" }], "The young are less tolerant of discomforts in life.", [{ label: "被动框架", text: "The change ... is revealed：变化通过某事实显现" }, { label: "事实从句", text: "the young are less tolerant：年轻人的容忍度下降" }, { label: "对象", text: "of discomforts in life：生活中的不适" }], ["fact that 后接完整陈述，the young 是群体名词，tolerant 后固定接 of。", "less tolerant 概括了旧价值减弱、长期不适开始显现及社会指标恶化。"], "日本生活方式的变化体现在：年轻人对生活中的不适更不能容忍。", "生活方式变化的一个迹象是，年轻人已经不愿像过去那样忍受不适。", "组合句把第16句的机制与第17句的后果概括为题目要求的事实。", ["is revealed in", "tolerant of"]),
    },
  },
];

function questionAnalysis(
  id: string,
  number: number,
  text: string,
  chunks: SentenceAnalysis["chunks"],
  trunk: string,
  layers: SentenceAnalysis["layers"],
  grammar: string[],
  literal: string,
  natural: string,
  logic: string,
  phrases: string[] = [],
): SentenceAnalysis {
  return { id, number, text, chunks, trunk, layers, grammar, literal, natural, logic, phrases };
}
