import type { WordKnowledge } from "./knowledge-base";
const k=(pattern:string,meaning:string,grammarRole:string,rule:string):WordKnowledge=>({grammarRole,grammarSummary:rule,structures:[{pattern,meaning,rule}]});
const source:Record<string,Record<string,WordKnowledge>>={
 "p5-s1":{deem:k("the rewards ... must be deemed worthy of the sacrifices","回报必须被认为值得付出","被动及主语补足","主动deem A worthy of B在本句被动中让A作主语，worthy保留为对A的性质补足。"),control:k("control over one's destiny","对自己命运的掌控","名词及介词补足","control与财富和声望并列，over接掌控对象，不是名词性从句。")},
 "p5-s2":{least:k("the educated not least among them","其中尤其包括受教育者","否定最低程度的强调","not least意味着受教育者尤其重要，不是at least的最低数量。"),who:k("people who are themselves admired","自身也受敬仰的人","关系代词作主语","who回指people，themselves为强调语，不能把它当admired宾语。")},
 "p5-s3":{it:k("it is the educated who have claimed ...","恰恰是受教育者声称……","强调句形式主语","焦点是the educated，it不指ambition，who接焦点相关动作。"),claim:k("have claimed to have given up on ambition","声称已经不再坚持抱负","完成时谓语与完成不定式","有限have claimed与非谓语to have given up分开；所称放弃早于声称，声称不保证事实。")},
 "p5-s4":{what:k("What is odd is that ...","奇怪的是……","主语从句的内部主语","What在is odd内部作主语；整个What is odd再作外层is主语。"),that:k("that they have ... / that of their parents and grandparents","所获益的内容／父辈的抱负","同句连接词与替代代词","前一个that仅连接表语内容，后一个that替代ambition，of限定抱负属于谁。")},
 "p5-s5":{note:k("a heavy note of hypocrisy","浓重的虚伪意味","存在句名词中心","note单词义为意味、色彩；heavy给程度，of hypocrisy给性质，不能把整组义全塞给note。"),ride:k("with the educated themselves riding on them","而受教育者自己正骑在那些马上","with复合结构的分词补足","the educated是riding的逻辑主语，them指horses；这种身份关系说明他们已在受益。")},
 "p5-s6":{less:k("do not seem less interested ... than formerly","看不出兴趣比过去减少","否定比较的范围","not less排除减少，不推出所有人显著增加；interested后的in给兴趣对象。")},
 "p5-s7":{decade:k("a decade or two years ago","原卷过去时间措辞有疑点","时间数量词及源文疑点","decade是十年，two years字面为两年；语境可能原想写十至二十年前，但无法确认，保留英文。"),name:k("place names and name brands","地名和名牌","复数中心名词与名词定语","names是place names中心；name在name brands前作名词定语，不是两个相同词序的结构。")},
 "p5-s8":{lest:k("lest they be thought pushing, acquisitive and vulgar","唯恐被看得咄咄逼人、贪得庸俗","消极目的或顾虑从句","lest后be为虚拟式被动；形容词说明主语被评价成什么，不能换成他们自己认为。"),once:k("as once they could","像他们曾经能做的那样","比较从句内时间副词","once在此为曾经，could省略confess fully to their dreams；不是once引导一旦从句。"),to:k("confess fully to their dreams","充分坦承自己的梦想","实义动词后的介词","to后是dreams名词，也可接doing；不能按to+原形的不定式处理。")},
 "p5-s9":{treat:k("we are treated to fine hypocritical spectacles","我们得以见识虚伪场面","带反讽的被动短语","treated to给一种体验，本句fine与hypocritical产生反讽；不是被物理治疗。"),whose:k("whose own children are enrolled in private schools","其自己的孩子入读私校","所属关系限定词","whose限定children并指journalist，whose own children整体为主语，are enrolled被动。"),advocate:k("the journalist advocating participatory democracy","倡导参与式民主的记者","现在分词后置定语","advocating修饰journalist，无独立有限时态，democracy为分词内部宾语。")},
 "p5-s10":{appear:k("avoid appearing ambitious","避免显得有抱负","动名词内部系表结构","appearing整体作avoid宾语，ambitious作appear的表语，不是avoid的宾语补足语。"),proper:k("For such people ... the proper formulation is ...","对这类人行为的恰当概括是……","讽刺描述的评价形容词","proper评价概括是否准确，不表示作者推荐所引的自我隐藏规则。")},
 "p5-s11":{where:k("where they are not extremely unattractive","即使还不至于极其令人反感的情况下","含让步意味的情境连接词","where限定评价适用情境，they指defenders；保留not和extremely范围，不当地点从句。")},
 "p5-s12":{it:k("lower than it has ever been","比这种支持以往的程度更低","比较从句中的回指","it指主语support，不指ambition或the young；has been后省略重复程度表语。"),fix:k("a quality to be admired and fixed in the mind of the young","应被赞赏并植入年轻人心中的品质","并列被动不定式后置修饰","admired和fixed共享to be，所修饰quality是被作用的对象。")},
 "p5-s13":{mean:k("does not mean that A, that B, but only that C","不意味着A或B，而只意味着C","内容补足的否定范围","前两个that属于not mean否定，第三个是but only下的肯定内容。"),less:k("it is less openly professed","它较少被公开宣称","被动谓语内的程度比较","less不等于no longer；插入的no longer honored不能移到professed前。")},
 "p5-s14":{which:k("some of which are that ...","这些后果中的一些就是……","部分数量关系结构","which指Consequences，some of which整体作are主语，that内容再作表语。"),make:k("ambition is driven underground, or made sly","抱负被迫隐蔽，或变得狡黠","并列被动与性质补足","made共用is，sly是形容词主语补足；underground是driven的方向副词。")},
 "p5-s15":{such:k("Such, then, is the way things stand","事情的状况就是如此","表语前置的完全倒装","Such为前置表语，the way things stand为后置主语；非Such作主语带宾语。"),stand:k("the way things stand","事情所处的状况","省略关系标记的定语从句","things stand修饰way，可理解为that或in which连接，不能写成the way how。"),try:k("people trying to get on in life","努力在生活中有所进展的人","分词修饰中的不定式补足","trying后置修饰people，to get on补努力的内容，没有be构成完整进行时。")},
 "question-27-option-A":{return:k("its returns well compensate for the sacrifices","回报足以抵偿牺牲","复数名词主语","returns指所得回报，well修饰compensate；for接所抵偿的牺牲。")},
 "question-28-option-B":{check:k("too late to check ambition once it has been let out","抱负一旦释放便来不及遏制","不定式动词及时间限定","check取遏制义，once在本选项是连接词，内部it has been let out为完成被动。"),once:k("once it has been let out","一旦它被释放","时间或条件从句连接词","这里once连接完整主谓，与正文as once they could的时间副词不同。")},
 "question-28-option-C":{after:k("after the fulfillment of the goal","在目标实现之后","介词接名词化事件","fulfillment是名词，故after不引导有限从句；to deny结构为被评价行为。")},
 "question-29-option-A":{think:k("they think of it as immoral","他们自己认为抱负不道德","主动观点归属","think of it as给他们本人的看法，正文be thought说怕被别人看成某种人，主体关系不同。")},
 "question-29-option-D":{appear:k("want to appear greedy and contemptible","想显得贪婪而可鄙","不定式系动词及表语","本选项整体do not want否定这种愿望；appear后两个形容词讲外观形象。")},
 "question-30-prompt":{that:k("the conclusion can be drawn that ambition should be maintained","可以得出应该维护抱负的结论","后置同位语从句","that说明conclusion的具体内容，不作draw的宾语；主句draw已为被动。")},
};
export function getPassage5WordKnowledge(headword:string,sourceId?:string){return sourceId?source[sourceId]?.[headword]:undefined;}
