import type { PracticeTask, GrammarConceptId, ErrorCategory } from "./learning-model";

const choice = (id: string, prompt: string, options: string[], correct: number, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "choice", prompt, options, answer: options[correct], evidence, feedback, conceptId, errorType, ...extra });
const range = (id: string, prompt: string, answer: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "range", prompt, options: [], answer, evidence: answer, feedback, conceptId, errorType, ...extra });
const link = (id: string, prompt: string, pairs: Array<[string, string]>, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "link", prompt, links: pairs.map(([source, target]) => ({ source, target })), options: [...new Set(pairs.map(([, target]) => target))], answer: JSON.stringify(pairs.map(([, target]) => target)), evidence, feedback, conceptId, errorType, ...extra });
const order = (id: string, prompt: string, blocks: string[], distractors: string[], evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "order", prompt, options: [...blocks, ...distractors], answer: JSON.stringify(blocks), evidence, feedback, conceptId, errorType, ...extra });

export const passage3Practice: Record<string, PracticeTask[]> = {
  "p3-s1": [
    range("aim-content", "划出find out后面的完整宾语从句，保留最后的介词。", "what its advocates are aiming at", "what既引出内容，又充当at的宾语；整个从句说明要弄清目标，不是要求立刻接受原则。", "clause-object", "clause-boundary", { hintWords: ["what", "aiming", "find out", "aiming at"] }),
    link("two-evaluation-times", "把两个时间范围连到各自限定的判断。", [["today", "may seem：今天看起来"], ["in years to come", "may be regarded：将来可能被看作"]], "however farfetched and unreasonable their principles may seem today, it is possible that in years to come they may be regarded as normal", "今天的观感和未来的可能不同；may两次保留可能语气。", "time-reference", "tense", { hintWords: ["today", "years", "in years to come"] }),
  ],
  "p3-s2": [
    link("concession-layers", "分清这三组话在作者判断中的位置。", [["whatever Futurist poetry may be", "无论是什么的让步背景"], ["even admitting that the theory ... may be right", "暂且承认理论可能正确"], ["it can hardly be classed as Literature", "作者保留的主要判断"]], "for whatever Futurist poetry may be—even admitting that the theory on which it is based may be right—it can hardly be classed as Literature", "两层让步都服务于主句近否定判断；不能把may be right读成作者已经肯定理论。", "negation-contrast", "clause-boundary", { hintWords: ["whatever", "admitting", "hardly", "can hardly be classed as Literature"], mapRevealsAnswer: true }),
    choice("theory-reference", "on which it is based中的it指什么？", ["Futurist poetry", "the theory", "普通读者"], 0, "the theory on which it is based", "which已经回指theory，it另指以该理论为基础的未来主义诗歌。", "reference-pronoun", "reference", { hintWords: ["it", "which", "on which it is based"] }),
  ],
  "p3-s3": [
    range("present-endpoint", "从till开始划出一直到句末的时间从句，不选句末标点。", "till now we live in a world of noise and violence and speed", "till后有we live这个主谓组合，不应只拿till now两个词当完整结构；它写出加速延续到如今的状态。", "clause-time", "clause-boundary", { hintWords: ["till", "now", "till now"] }),
    choice("futurist-voice", "冒号后的生活加速主张首先是谁的说法？", ["被转述的未来主义者", "已被作者无条件证实的结论", "注释中落水的军官"], 0, "what the Futurist says", "says明确标注来源；作者到末句仍会追问人是否发生本质变化。", "author-voice", "passage-logic", { hintWords: ["says", "Futurist"], mapRevealsAnswer: true }),
  ],
  "p3-s4": [choice("corresponding-reason", "corresponding把内心变化接回哪项内容？", ["未来主义者所说的生活加速", "作者已证明军官体重改变", "倡导者人数减少"], 0, "a corresponding change", "相应变化接回上句生活条件加速，仍在未来主义者的推理内；不能当成作者独立作出的事实证明。", "paragraph-role", "passage-logic", { hintWords: ["corresponding", "Consequently", "have undergone a corresponding change"], mapRevealsAnswer: true })],
  "p3-s5": [order("claim-trunk", "去掉观点来源插入语，按原文次序拼回主谓宾。", ["This speeding up of life", "requires", "a new form of expression"], ["says the Futurist"], "This speeding up of life, says the Futurist, requires a new form of expression", "says the Futurist只交代谁说；requires才是生活加速这一主语的谓语。", "basic-svo", "predicate", { hintWords: ["requires", "says", "speeding up of life", "a new form of expression"] })],
  "p3-s6": [
    range("if-clause", "划出完整条件从句，从if开始。", "if we want to interpret modern stress", "want是条件从句谓语，to interpret补足想做的事，stress是interpret的宾语。", "clause-condition", "clause-boundary", { hintWords: ["if", "want", "if we want to"] }),
    choice("interpret-not-relieve", "interpret modern stress表达的目标是什么？", ["表现、阐释现代压力", "用诗歌消除现代压力", "增加作品产量"], 0, "interpret modern stress", "interpret解释或表现一种状态，不等于relieve减轻压力；speed up也不等于提高文学产量。", "lexical-context", "option-logic", { hintWords: ["interpret", "stress", "interpret modern stress"], mapRevealsAnswer: true })],
  "p3-s7": [
    link("parallel-limits", "把三个限制形式分别连到它们的含义。", [["stops", "标点或停顿标记"], ["qualifying adjectives", "修饰性的形容词"], ["finite verbs", "有时态等限定形式的动词"]], "stops, or qualifying adjectives, or finite verbs", "三个名词组都是by的宾语；finite限定范围，不能扩成不用任何动词。", "lexical-context", "vocabulary", { hintWords: ["stops", "qualifying", "adjectives", "finite", "verbs", "unhampered by"] }),
    range("finite-pour", "只划出带情态动词的有限谓语，不包括宾语和分词补充。", "must pour out", "must带动词原形pour，out是小品词；unhampered只是补充不受限制的状态。", "finite-predicate", "predicate", { hintWords: ["must", "pour", "unhampered", "pour out"] })],
  "p3-s8": [
    link("sound-reference", "在words that imitate them中，分别确定that和them。", [["that", "words：模仿者"], ["them", "sounds：被模仿的对象"]], "Instead of describing sounds we must make up words that imitate them", "that作关系从句的主语，them作imitate的宾语；不要把两个代词接回同一名词。", "reference-pronoun", "reference", { hintWords: ["that", "them", "imitate", "imitate them"] }),
    order("shared-must", "从第二分句提取主语和三个动作，按原文顺序排列。", ["we", "must use", "and shorten or lengthen"], ["different colored inks", "on the same page"], "we must use many sizes of type and different colored inks on the same page, and shorten or lengthen words at will", "use与shorten or lengthen共用we must；inks是use的宾语，不是新主语。", "finite-predicate", "predicate", { hintWords: ["use", "shorten", "lengthen", "must"] })],
  "p3-s9": [choice("confused-complement", "confused在本句说明什么？", ["描写本身呈现混乱状态", "作者被军官欺骗", "战斗是are的动作宾语"], 0, "their descriptions of battles are confused", "主语中心descriptions是复数名词，are为系动词，confused是表语；of battles只说明描写对象。", "basic-svc", "predicate", { hintWords: ["confused", "descriptions", "descriptions of battles"], mapRevealsAnswer: true })],
  "p3-s10": [
    link("two-real-subjects", "区分两项读者体验与各自的信息内容。", [["to read in the explanatory notes that...", "读注释中的打斗故事"], ["and then to find that...", "再发现诗行只有声音和体重"]], "it is a little upsetting to read in the explanatory notes", "to read和to find并列充当后置真正主语，it先占位；不是第二个find藏在第一个that从句里。", "nonfinite-subject", "attachment", { hintWords: ["it", "upsetting", "find", "a little upsetting", "explanatory notes"], leaksToTaskIds: ["story-versus-line"] }),
    range("bridge-clause", "划出修饰bridge的完整定语从句，从介词off开始。", "off which they both fall into the river", "which指桥；off标起点、into标终点。they both是两名军官，不能把bridge或river当执行者。", "clause-relative", "clause-boundary", { hintWords: ["off", "which", "both", "off which", "fall into the river"] }),
    choice("story-versus-line", "作者指出的落差是哪一种？", ["注释有完整故事，诗行只有拟声与数字", "同一座桥有两种颜色", "诗行准确记录了每个人的生平"], 0, "the line consists of the noise of their falling and the weights of the officers", "举例用注释的故事与诗行实际内容对照，支撑作者对可理解性、文学性的批评；不补出原文没有的体重归属。", "paragraph-role", "passage-logic", { hintWords: ["notes", "line", "consists", "explanatory notes", "consists of", "the noise of their falling", "the weights of the officers"], mapRevealsAnswer: true })],
  "p3-s11": [order("concession-main-claim", "拿掉让步从句，按原文顺序保留主要判断。", ["This", "can hardly be classed", "as Literature"], ["though it fulfills", "the laws and requirements"], "This, though it fulfills the laws and requirements of Futurist poetry, can hardly be classed as Literature", "though承认符合流派规则，hardly仍否定把作品称为文学；二者不是互相抵消。", "negation-contrast", "predicate", { hintWords: ["though", "hardly", "can hardly be classed as Literature"], mapRevealsAnswer: true })],
  "p3-s12": [
    range("proposition-content", "划出解释proposition具体内容的完整从句，含that。", "that a great change in our emotional life calls for a change of expression", "that从句解释主张内容；that自身不充当从句成分，不能因为紧跟名词就当成定语从句。", "apposition", "clause-boundary", { hintWords: ["that", "proposition", "calls for a change of expression"] }),
    choice("principle-not-premise", "作者在这里接受的究竟是哪项？", ["情感巨大变化需要相应表达变化这一原则", "人类本质已经发生巨大变化的事实", "所有未来主义作品都是文学"], 0, "no thinking man can refuse to accept their first proposition", "认可一般原则不等于肯定变化已经发生；末句正追问有没有本质变化。", "author-voice", "passage-logic", { hintWords: ["no", "refuse", "proposition", "all the same", "refuse to accept"], mapRevealsAnswer: true })],
  "p3-s13": [order("direct-question", "保留原文直接疑问句的词序，不改成间接问句。", ["have", "we", "essentially", "changed"], ["whether", "did"], "have we essentially changed", "现在完成时疑问句把have放到we前；作者提出问题，不能把它当作已经改变的陈述事实。", "finite-predicate", "predicate", { hintWords: ["have", "essentially", "changed", "essentially changed"], mapRevealsAnswer: true })],
};
