import type { ContextualSubstitution } from "./contextual-vocabulary";

export type PassageLexiconEntry = {
  partOfSpeech: string;
  contextualMeaning: string;
  use: string;
  specialForms?: string[];
  examSynonyms?: string[];
  collocations?: string[];
  otherMeanings?: string[];
  wordFamily?: string[];
  confusions?: string[];
  contextualSubstitutions?: ContextualSubstitution[];
};

export const passage1LemmaAliases: Record<string, string> = {
  "u.s.": "united states",
  "america's": "america",
  "harvard's": "harvard",
  "korea's": "korea",
  "world's": "world",
  achieved: "achieve",
  actions: "action",
  americans: "american",
  asians: "asian",
  attributed: "attribute",
  became: "become",
  been: "be",
  began: "begin",
  believes: "believe",
  bought: "buy",
  brought: "bring",
  businesses: "business",
  cars: "car",
  causes: "cause",
  caused: "cause",
  changed: "change",
  collapsed: "collapse",
  competitors: "competitor",
  countries: "country",
  depends: "depend",
  devalued: "devalue",
  destroyed: "destroy",
  dreams: "dream",
  economies: "economy",
  efforts: "effort",
  entered: "enter",
  enterprises: "enterprise",
  europeans: "european",
  fading: "fade",
  failing: "fail",
  filled: "fill",
  findings: "finding",
  found: "find",
  given: "give",
  giving: "give",
  gone: "go",
  going: "go",
  granted: "grant",
  grew: "grow",
  growing: "grow",
  had: "have",
  handled: "handle",
  has: "have",
  incomes: "income",
  industries: "industry",
  learnt: "learn",
  left: "leave",
  lost: "lose",
  looked: "look",
  made: "make",
  makes: "make",
  making: "make",
  improving: "improve",
  improved: "improve",
  inferred: "infer",
  invented: "invent",
  larger: "large",
  manifested: "manifest",
  narrowed: "narrow",
  proved: "prove",
  richer: "rich",
  ropes: "rope",
  restructuring: "restructure",
  says: "say",
  scientists: "scientist",
  seems: "seem",
  semiconductors: "semiconductor",
  shrunk: "shrink",
  states: "state",
  stopped: "stop",
  struggling: "struggle",
  sweeping: "sweep",
  taken: "take",
  taking: "take",
  textiles: "textile",
  themselves: "they",
  things: "thing",
  times: "time",
  turning: "turn",
  warnings: "warning",
  was: "be",
  vanished: "vanish",
  were: "be",
  withdrawn: "withdraw",
  workers: "worker",
  would: "will",
  years: "year",
  yielded: "yield",
};

export const passage1FamilyAliases: Record<string, string> = {
  american: "america",
  competitiveness: "compete",
  competitor: "compete",
  competition: "compete",
  economic: "economy",
  industrial: "industry",
  productivity: "produce",
  prosperous: "prosper",
  prosperity: "prosper",
  sensational: "sense",
  solely: "sole",
};

const noIrregular = ["无需要单独记忆的不规则变形"];
const structureWord = ["结构词：无普通词形变化，重点看句法位置"];

export const passage1Lexicon: Record<string, PassageLexiconEntry> = {
  about: { partOfSpeech: "prep./adv.", contextualMeaning: "关于；围绕", use: "warnings about... 中 about 引出警告所针对的内容。", specialForms: structureWord },
  after: { partOfSpeech: "prep./conj./adv.", contextualMeaning: "在……之后", use: "after the end of... 引出二战结束后的时间背景；after 可接名词、动名词或从句。", collocations: ["after the end of the Second World War"], specialForms: structureWord },
  another: { partOfSpeech: "det./pron.", contextualMeaning: "另一个；又一个", use: "one inquiry after another 表示一个调查接着另一个调查，another 后省略重复的 inquiry。", collocations: ["one inquiry after another"], specialForms: structureWord },
  according: { partOfSpeech: "prep. phrase component", contextualMeaning: "按照；根据", use: "according to + 人/资料表示观点或信息来源；本句用于标明引语来自Cavanaugh。", collocations: ["according to Richard Cavanaugh"], specialForms: structureWord },
  achieve: { partOfSpeech: "v.", contextualMeaning: "取得；实现", use: "achieve predominance 表示取得主导地位；achieve 是及物动词，直接接目标。", specialForms: ["achieve—achieved—achieved—achieving"], examSynonyms: ["attain（达到；较正式）", "accomplish（完成任务）"] },
  action: { partOfSpeech: "n.", contextualMeaning: "行动；行为", use: "suicidal actions 指会导致自我毁灭的行为；为第12题干扰项用词。", specialForms: ["action—actions（复数）"], examSynonyms: ["act（具体行为）", "measure（为达目的采取的措施）"] },
  age: { partOfSpeech: "n./v.", contextualMeaning: "时代；年龄", use: "computer age 与 golden age 中均为名词“时代”。", collocations: ["the new computer age", "a golden age of business management"], specialForms: ["age—ages（复数）；aged—aging/ageing（动词形式）"] },
  america: { partOfSpeech: "proper n.", contextualMeaning: "美国", use: "文中作为国家名称；America's 是名词所有格，修饰 industrial decline 或 industry。", specialForms: ["America（专有名词）；America's（所有格）"], wordFamily: ["American n./adj. 美国人；美国的"] },
  american: { partOfSpeech: "n./adj.", contextualMeaning: "美国人；美国的", use: "Americans 作复数名词“美国人”；American industry 中作形容词“美国的”。", specialForms: ["American—Americans（名词复数）"], wordFamily: ["America n. 美国"] },
  any: { partOfSpeech: "det./pron./adv.", contextualMeaning: "任何一个", use: "any competitor 用于比较级中，表示任何一个竞争者。", specialForms: structureWord },
  asian: { partOfSpeech: "n./adj.", contextualMeaning: "亚洲人；亚洲的", use: "Asians 在原文作复数名词，与 Europeans 并列。", specialForms: ["Asian—Asians（名词复数）"] },
  attribute: { partOfSpeech: "v./n.", contextualMeaning: "把……归因于", use: "attribute A to B：把A归因于B；本句 A 是复苏，B 是美元贬值或经济周期转向。", collocations: ["attribute this solely to"], specialForms: ["attribute—attributed—attributed—attributing"], examSynonyms: ["ascribe（归因；较正式）", "credit（把功劳归于）"], confusions: ["作名词时重音前移，表示“属性”；本句是动词。"] },
  author: { partOfSpeech: "n./v.", contextualMeaning: "作者", use: "The author seems to believe... 要求区分作者隐含态度与文中被引述者观点。", specialForms: ["author—authors（复数）；author—authored—authored（动词）"] },
  auto: { partOfSpeech: "n./adj. component", contextualMeaning: "汽车（工业）", use: "auto industry 是 automobile industry 的简写，出现在第12题选项。", specialForms: ["auto—autos（名词复数）"] },
  back: { partOfSpeech: "adv./n./adj./v.", contextualMeaning: "向后；回顾", use: "look back on 中 back 是副词，整个短语表示“回顾”。", collocations: ["look back on"], specialForms: noIrregular },
  because: { partOfSpeech: "conj.", contextualMeaning: "因为", use: "第11题题干引导原因状语从句，要求从原文寻找美国取得优势的原因。", specialForms: structureWord },
  become: { partOfSpeech: "linking v.", contextualMeaning: "成为；变成", use: "become a driving force 为系表结构，名词短语作表语。", specialForms: ["become—became—become—becoming"] },
  begin: { partOfSpeech: "v.", contextualMeaning: "开始", use: "begin to believe / begin to fall 后接不定式，表示开始出现某动作或变化。", specialForms: ["begin—began—begun—beginning"], examSynonyms: ["start（开始；更常用）", "commence（开始；正式）"] },
  believe: { partOfSpeech: "v.", contextualMeaning: "相信；认为", use: "believe that... 后接宾语从句；文中并列两个 that 从句。", specialForms: ["believe—believed—believed—believing"], examSynonyms: ["think（认为；较中性）", "hold（持有某观点；正式）"] },
  best: { partOfSpeech: "adj./adv./n.（最高级）", contextualMeaning: "最优秀的", use: "the world's best 中 best 名词化，表示世界上最优秀的一批科学家。", specialForms: ["good/well—better—best"] },
  beyond: { partOfSpeech: "prep./adv.", contextualMeaning: "超出；超过", use: "beyond the dreams of 表示超出某人的想象。", collocations: ["prosperous beyond the dreams of"], specialForms: structureWord },
  blind: { partOfSpeech: "adj./v./n.", contextualMeaning: "盲目的；缺乏理性判断的", use: "blind pride 是作者带批评色彩的评价，说明这种自豪忽视了客观因素。", collocations: ["yielded to blind pride"], specialForms: ["blind—blinder—blindest（少用）；blind—blinded—blinded（动词）"], examSynonyms: ["uncritical（不加批判的）", "irrational（不理性的）"] },
  bring: { partOfSpeech: "v.", contextualMeaning: "带来；使出现", use: "年代作主语时 bring 表示某时期出现了某种现象。", specialForms: ["bring—brought—brought—bringing"] },
  business: { partOfSpeech: "n.", contextualMeaning: "商业；企业；经营活动", use: "do business 表示经营；businesses 为可数复数时指企业。", collocations: ["their way of doing business", "a golden age of business management"], specialForms: ["business—businesses（复数）"] },
  buy: { partOfSpeech: "v./n.", contextualMeaning: "收购；购买", use: "Zenith was bought by... 中 buy 指企业收购，使用被动语态。", specialForms: ["buy—bought—bought—buying"], examSynonyms: ["purchase（购买；较正式）", "acquire（购得/收购）"] },
  by: { partOfSpeech: "prep./adv.", contextualMeaning: "到……为止；被；由", use: "By 1987 表截止时间；was bought by 中 by 引出被动语态的动作执行者。", specialForms: structureWord },
  car: { partOfSpeech: "n.", contextualMeaning: "汽车", use: "Foreign-made cars 指外国制造的汽车，是第12题定位信息。", specialForms: ["car—cars（复数）"] },
  casualty: { partOfSpeech: "n.", contextualMeaning: "受害者；在竞争中受损或消失的产业", use: "next casualty 是比喻说法，把可能衰落的半导体业视为下一个“牺牲品”。", collocations: ["was going to be the next casualty"], specialForms: ["casualty—casualties（复数）"], examSynonyms: ["victim（受害者）", "loss（损失的人或物）"] },
  cato: { partOfSpeech: "proper n.", contextualMeaning: "卡托（研究所名称的一部分）", use: "the Cato Institute 是美国智库名称；与后面的同位语 a think-tank 对应。", specialForms: ["Cato（专有名词）"] },
  cause: { partOfSpeech: "n./v.", contextualMeaning: "原因；导致", use: "cause a crisis 中作动词；causes of decline 中作复数名词。", specialForms: ["cause—causes（复数）；cause—caused—caused（动词）"], examSynonyms: ["reason（理由/原因）", "factor（影响因素）"] },
  cavanaugh: { partOfSpeech: "proper n.", contextualMeaning: "卡瓦诺（人名）", use: "Richard Cavanaugh 是被引述者；其观点不能直接当作作者立场。", specialForms: ["Cavanaugh（专有名词）"] },
  change: { partOfSpeech: "v./n.", contextualMeaning: "改变；变化", use: "has changed its structure 为及物用法；things have changed 为不及物用法。", collocations: ["How things have changed", "has changed its structure"], specialForms: ["change—changed—changed—changing"] },
  collapse: { partOfSpeech: "v./n.", contextualMeaning: "倒闭；崩溃", use: "第12题C项说机床业 had collapsed，但原文只说 on the ropes，因此程度被夸大。", specialForms: ["collapse—collapsed—collapsed—collapsing"], examSynonyms: ["fail（失败）", "break down（垮掉；失灵）"] },
  competition: { partOfSpeech: "n.", contextualMeaning: "竞争", use: "foreign competition / competition from overseas 均指来自国外企业的市场竞争。", collocations: ["in the face of foreign competition", "the growing competition from overseas"], specialForms: ["competition—competitions（具体比赛时可数）"], wordFamily: ["compete v. 竞争", "competitor n. 竞争者", "competitive adj. 有竞争力的", "competitiveness n. 竞争力"] },
  computer: { partOfSpeech: "n.", contextualMeaning: "计算机；电脑", use: "the new computer age 中作前置定语，说明以计算机技术为核心的新时代。", specialForms: ["computer—computers（复数）"] },
  confidence: { partOfSpeech: "n.", contextualMeaning: "信心；信任", use: "a crisis of confidence 指对美国经济和经营方式失去信心。", collocations: ["a crisis of confidence"], specialForms: ["confidence（通常不可数）"], examSynonyms: ["trust（对人或制度的信任）", "assurance（自信/保证）"] },
  consumer: { partOfSpeech: "n./adj. component", contextualMeaning: "消费者；消费类的", use: "consumer electronics 中作前置定语，指面向个人消费者的电子产品。", collocations: ["such as consumer electronics"], specialForms: ["consumer—consumers（复数）"], wordFamily: ["consume v. 消费", "consumption n. 消费"] },
  cooperation: { partOfSpeech: "n.", contextualMeaning: "合作", use: "international cooperation 是第13题C项内容，但全文没有把经济复苏归因于国际合作。", specialForms: ["cooperation（通常不可数）"], wordFamily: ["cooperate v. 合作", "cooperative adj. 合作的"] },
  competitiveness: { partOfSpeech: "n.", contextualMeaning: "竞争力", use: "industrial competitiveness 指一个国家工业在市场竞争中的能力。", collocations: ["fading industrial competitiveness"], specialForms: ["competitiveness（不可数名词）"], wordFamily: ["compete v. 竞争", "competition n. 竞争", "competitive adj. 有竞争力的"] },
  competitor: { partOfSpeech: "n.", contextualMeaning: "竞争者；竞争对手", use: "any competitor 在倍数比较中实际省略了 competitor's market。", specialForms: ["competitor—competitors（复数）"], wordFamily: ["compete v. 竞争", "competition n. 竞争", "competitive adj. 有竞争力的"] },
  contribute: { partOfSpeech: "v.", contextualMeaning: "促成；有助于", use: "contribute to + 名词/doing 表示促进某结果；第13题B项表示竞争可能促进经济进步。", specialForms: ["contribute—contributed—contributed—contributing"], examSynonyms: ["promote（促进）", "facilitate（使更容易）"] },
  country: { partOfSpeech: "n.", contextualMeaning: "国家", use: "other countries 与美国对比，指战后逐渐富裕的其他国家。", specialForms: ["country—countries（复数）"] },
  crisis: { partOfSpeech: "n.", contextualMeaning: "危机", use: "a crisis of confidence 表示信心危机。", collocations: ["a crisis of confidence"], specialForms: ["crisis—crises（复数）"] },
  cycle: { partOfSpeech: "n./v.", contextualMeaning: "周期；循环", use: "business cycle 指经济活动扩张与收缩的周期。", collocations: ["the turning of the business cycle"], specialForms: ["cycle—cycles（复数）；cycle—cycled—cycled（动词）"] },
  dc: { partOfSpeech: "proper n. abbreviation", contextualMeaning: "哥伦比亚特区（Washington, DC）", use: "用于美国首都 Washington, DC 的正式地名。", specialForms: ["DC = District of Columbia"] },
  dean: { partOfSpeech: "n.", contextualMeaning: "院长", use: "executive dean 是同位语身份信息，介绍Cavanaugh的职务。", specialForms: ["dean—deans（复数）"] },
  decline: { partOfSpeech: "n./v.", contextualMeaning: "衰退；下降", use: "industrial decline 中作名词，指工业竞争力和产业规模的下降。", collocations: ["America's industrial decline"], specialForms: ["decline—declined—declined—declining（动词）"], examSynonyms: ["decrease（减少）", "deterioration（恶化）"] },
  depend: { partOfSpeech: "v.", contextualMeaning: "依赖；取决于", use: "depend on + 名词/doing；第13题C项声称复苏依赖国际合作，但原文无此依据。", specialForms: ["depend—depended—depended—depending"] },
  diet: { partOfSpeech: "n./v.", contextualMeaning: "节食；此处比喻企业精简", use: "go on a diet 本指开始节食，在企业语境中比喻削减成本和冗余。", collocations: ["has gone on a diet"], specialForms: ["diet—diets（复数）；diet—dieted—dieted（动词）"] },
  dollar: { partOfSpeech: "n.", contextualMeaning: "美元", use: "a devalued dollar 指对外价值下降的美元。", collocations: ["a devalued dollar"], specialForms: ["dollar—dollars（复数）"] },
  domestic: { partOfSpeech: "adj./n.", contextualMeaning: "国内的；本国的", use: "the domestic market 指美国本国市场；不是“家庭的”。", collocations: ["the domestic market"], specialForms: noIrregular, examSynonyms: ["internal（内部的）", "home（国内的；作定语）"], confusions: ["domestic 也可表示“家庭的”，需由 market 等中心词判断。"] },
  destroy: { partOfSpeech: "v.", contextualMeaning: "摧毁；毁坏", use: "the war had destroyed the economies... 使用过去完成时，说明战争破坏发生在美国战后繁荣之前。", collocations: ["whose economies the war had destroyed"], specialForms: ["destroy—destroyed—destroyed—destroying"], examSynonyms: ["ruin（毁坏）", "devastate（严重破坏）"] },
  devalue: { partOfSpeech: "v.", contextualMeaning: "使货币贬值；贬低", use: "a devalued dollar 中过去分词作定语，表示美元价值已经下降。", collocations: ["a devalued dollar"], specialForms: ["devalue—devalued—devalued—devaluing"], wordFamily: ["devaluation n. 贬值"] },
  development: { partOfSpeech: "n.", contextualMeaning: "发展", use: "further development 是第13题D项，指进一步发展。", specialForms: ["development—developments（具体进展时可数）"], wordFamily: ["develop v. 发展", "developed adj. 发达的", "developing adj. 发展中的"] },
  do: { partOfSpeech: "v./aux.", contextualMeaning: "做；经营", use: "way of doing business 中 doing 是动名词，表示经营商业这一活动。", collocations: ["their way of doing business"], specialForms: ["do—does—did—done—doing"] },
  dream: { partOfSpeech: "n./v.", contextualMeaning: "梦想；想象", use: "beyond the dreams of 表示富裕程度超出欧亚人民的想象。", collocations: ["prosperous beyond the dreams of"], specialForms: ["dream—dreamed/dreamt—dreamed/dreamt—dreaming"] },
  dreadful: { partOfSpeech: "adj.", contextualMeaning: "可怕的；糟糕的", use: "a dreadful handicap 强调长期轻易成功可能造成严重障碍。", collocations: ["a dreadful handicap"], specialForms: noIrregular, examSynonyms: ["terrible（可怕的；程度强）", "awful（很糟的）"] },
  driving: { partOfSpeech: "adj./v.-ing", contextualMeaning: "推动的；驱动的", use: "driving force 为固定名词搭配，指促使发展或行动的力量。", collocations: ["a driving force"], specialForms: ["drive—drove—driven—driving"] },
  economy: { partOfSpeech: "n.", contextualMeaning: "经济；节约；规模经济", use: "economies 被摧毁时指各国经济；economies of scale 中为复数固定术语“规模经济”。", collocations: ["unparalleled economies of scale"], specialForms: ["economy—economies（复数）"], wordFamily: ["economic adj. 经济的", "economical adj. 节约的", "economist n. 经济学家"] },
  economic: { partOfSpeech: "adj.", contextualMeaning: "经济的", use: "economic progress 指经济发展；不要与 economical“节约的”混淆。", specialForms: noIrregular, wordFamily: ["economy n. 经济", "economist n. 经济学家"] },
  effortless: { partOfSpeech: "adj.", contextualMeaning: "不费力的；轻易取得的", use: "修饰 success，说明美国长期成功并非来自艰苦努力。", collocations: ["A history of long and effortless success"], specialForms: noIrregular, examSynonyms: ["easy（容易的；范围更广）", "smooth（顺利的；强调过程）"], wordFamily: ["effort n. 努力", "effortlessly adv. 毫不费力地"] },
  effort: { partOfSpeech: "n.", contextualMeaning: "努力", use: "painstaking efforts 是第11题A项，和原文 effortless success 构成反义干扰。", specialForms: ["effort—efforts（复数）"], examSynonyms: ["attempt（尝试）", "endeavor（努力；正式）"] },
  electronics: { partOfSpeech: "n.（学科/产业名词）", contextualMeaning: "电子产品业；电子学", use: "consumer electronics 指面向消费者的电子产品及其产业。", collocations: ["such as consumer electronics"], specialForms: ["electronics 通常视为单数概念，无普通单数形式"] },
  education: { partOfSpeech: "n.", contextualMeaning: "教育", use: "success in education 是第14题D项，但原文提到学校名称只为交代受访者身份。", specialForms: ["education（通常不可数）"], wordFamily: ["educate v. 教育", "educational adj. 教育的"] },
  eight: { partOfSpeech: "numeral", contextualMeaning: "八；八倍结构中的基数", use: "eight times larger than 中 eight 限定倍数 times。", collocations: ["eight times larger than any competitor"], specialForms: ["eight（基数词）—eighth（序数词）"] },
  end: { partOfSpeech: "n./v.", contextualMeaning: "结束；末尾", use: "after the end of... 表示在某事件结束之后。", collocations: ["after the end of the Second World War"], specialForms: ["end—ended—ended—ending（动词）"] },
  enter: { partOfSpeech: "v.", contextualMeaning: "进入；步入", use: "enter a period 直接接宾语，表示进入某个时期，不加 into。", collocations: ["entered just such a glowing period"], specialForms: ["enter—entered—entered—entering"], confusions: ["enter the market/period 通常不加 into；enter into 常表示开始协议、讨论或关系。"] },
  enterprise: { partOfSpeech: "n.", contextualMeaning: "企业", use: "foreign enterprises 出现在第12题B项，指外国企业。", specialForms: ["enterprise—enterprises（复数）"], examSynonyms: ["company（公司）", "business（企业/商业）"] },
  executive: { partOfSpeech: "adj./n.", contextualMeaning: "行政的；执行院长", use: "executive dean 是职务名称，作同位语介绍Cavanaugh。", specialForms: ["executive—executives（名词复数）"] },
  european: { partOfSpeech: "n./adj.", contextualMeaning: "欧洲人；欧洲的", use: "Europeans 在原文作复数名词，与 Asians 并列。", specialForms: ["European—Europeans（名词复数）"] },
  face: { partOfSpeech: "n./v.", contextualMeaning: "面对；面前", use: "in the face of 表示面对困难、压力或竞争。", collocations: ["in the face of foreign competition"], specialForms: ["face—faced—faced—facing（动词）"] },
  fact: { partOfSpeech: "n.", contextualMeaning: "事实", use: "in the fact that... 表示体现在……这一事实中；用于第12题题干。", specialForms: ["fact—facts（复数）"] },
  fade: { partOfSpeech: "v.", contextualMeaning: "逐渐减弱；褪去", use: "fading industrial competitiveness 中现在分词作定语，强调竞争力正在减弱。", collocations: ["fading industrial competitiveness"], specialForms: ["fade—faded—faded—fading"], examSynonyms: ["decline（下降）", "diminish（逐渐减少）"] },
  fail: { partOfSpeech: "v.", contextualMeaning: "失败；失灵", use: "their way of doing business was failing 表示经营方式正在失效。", collocations: ["was failing"], specialForms: ["fail—failed—failed—failing"] },
  fall: { partOfSpeech: "v./n.", contextualMeaning: "下降；下跌", use: "incomes begin to fall 表示收入开始下降。", collocations: ["would therefore shortly begin to fall"], specialForms: ["fall—fell—fallen—falling"], examSynonyms: ["drop（下降；较突然）", "decline（逐渐下降）"] },
  few: { partOfSpeech: "det./pron./adj.", contextualMeaning: "几乎没有；很少", use: "few Americans 带否定意味；不同于 a few Americans“有一些美国人”。", specialForms: ["few—fewer—fewest"], confusions: ["few + 可数复数表示“几乎没有”；a few 表示“有几个”。"] },
  fill: { partOfSpeech: "v./n.", contextualMeaning: "使充满", use: "be filled with + 内容表示充满；本句为被动结构。", collocations: ["were filled with warnings about"], specialForms: ["fill—filled—filled—filling"] },
  finding: { partOfSpeech: "n.", contextualMeaning: "调查结论；研究发现", use: "findings 为可数复数，指多次调查得出的结论，而非寻找动作。", collocations: ["sometimes sensational findings"], specialForms: ["finding—findings（复数）"], examSynonyms: ["result（结果）", "conclusion（结论）"] },
  find: { partOfSpeech: "v.", contextualMeaning: "发现自己处于", use: "find oneself + 状态表示发现自己处于某种情况；文中宾补为 at a loss。", collocations: ["found themselves at a loss over"], specialForms: ["find—found—found—finding"] },
  force: { partOfSpeech: "n./v.", contextualMeaning: "力量；推动力", use: "a driving force 指推动变化或发展的力量。", collocations: ["a driving force"], specialForms: ["force—forces（复数）；force—forced—forced（动词）"], examSynonyms: ["power（力量/权力）", "impetus（推动力）"] },
  five: { partOfSpeech: "numeral", contextualMeaning: "五", use: "five years of solid growth 表示持续五年的稳定增长。", collocations: ["five years of solid growth"], specialForms: ["five（基数词）—fifth（序数词）"] },
  foreign: { partOfSpeech: "adj.", contextualMeaning: "外国的；国外的", use: "foreign competition 指外国企业带来的竞争。", collocations: ["in the face of foreign competition"], specialForms: noIrregular },
  further: { partOfSpeech: "adj./adv./v.", contextualMeaning: "进一步的；更远地", use: "further development 表示在现有基础上的进一步发展。", specialForms: ["far—farther/further—farthest/furthest"] },
  "foreign-made": { partOfSpeech: "adj.", contextualMeaning: "外国制造的", use: "复合形容词，整体作定语修饰 cars and textiles。", collocations: ["Foreign-made cars and textiles"], specialForms: ["foreign-made（复合形容词，无比较级）"] },
  from: { partOfSpeech: "prep.", contextualMeaning: "从；来自", use: "competition from overseas 表示竞争的来源；retreat from 表示退出某地位。", specialForms: structureWord },
  give: { partOfSpeech: "v.", contextualMeaning: "给予；带来", use: "giving its industries... 为现在分词结果状语，说明巨大市场带来的结果。", collocations: ["giving its industries unparalleled economies of scale"], specialForms: ["give—gave—given—giving"] },
  glowing: { partOfSpeech: "adj.", contextualMeaning: "辉煌的；光辉的", use: "a glowing period 指繁荣而令人赞叹的时期。", collocations: ["entered just such a glowing period"], specialForms: ["glow—glowed—glowed—glowing"], examSynonyms: ["brilliant（辉煌的）", "promising（有希望的）"] },
  go: { partOfSpeech: "v.", contextualMeaning: "进入某种状态；去", use: "go on a diet 是固定搭配；gone 为 go 的过去分词。", collocations: ["has gone on a diet"], specialForms: ["go—went—gone—going"] },
  golden: { partOfSpeech: "adj.", contextualMeaning: "黄金般的；最繁荣的", use: "a golden age 指某领域最兴盛、最成功的时期。", collocations: ["a golden age of business management"], specialForms: noIrregular },
  goal: { partOfSpeech: "n.", contextualMeaning: "目标", use: "towards this goal 出现在第11题A项，指取得经济主导地位这一目标。", specialForms: ["goal—goals（复数）"], examSynonyms: ["aim（目标；意图）", "objective（具体目标；正式）"] },
  grow: { partOfSpeech: "v.", contextualMeaning: "逐渐变得；增长", use: "grow richer 是系动词用法；growing competition 中现在分词作定语表示不断加剧。", collocations: ["as other countries grew richer", "the growing competition from overseas"], specialForms: ["grow—grew—grown—growing"] },
  growth: { partOfSpeech: "n.", contextualMeaning: "增长；发展", use: "five years of solid growth 指连续五年的稳定经济增长。", collocations: ["five years of solid growth"], specialForms: ["growth—growths（具体增长类型时可数）"], wordFamily: ["grow v. 增长；逐渐变得"] },
  government: { partOfSpeech: "n.", contextualMeaning: "政府；政府管理", use: "Kennedy School of Government 是学院名称，government 不构成经济复苏原因。", specialForms: ["government—governments（复数）"], wordFamily: ["govern v. 治理", "governmental adj. 政府的"] },
  grant: { partOfSpeech: "v./n.", contextualMeaning: "认为理所当然（固定结构中）", use: "take A for granted 表示不加思考地认为A理所当然；granted 不能在此单独译为“被批准”。", collocations: ["stopped taking prosperity for granted"], specialForms: ["grant—granted—granted—granting"] },
  handicap: { partOfSpeech: "n./v.", contextualMeaning: "障碍；不利条件", use: "成功史被比喻为会妨碍继续进步的 handicap。", collocations: ["a dreadful handicap"], specialForms: ["handicap—handicaps（复数）；handicap—handicapped—handicapped（动词）"], examSynonyms: ["obstacle（阻碍前进的障碍）", "disadvantage（不利条件）"] },
  handle: { partOfSpeech: "v./n.", contextualMeaning: "处理；应对", use: "if properly handled 是被动省略结构，表示成功史若被妥善处理。", collocations: ["if properly handled"], specialForms: ["handle—handled—handled—handling"] },
  harvard: { partOfSpeech: "proper n.", contextualMeaning: "哈佛大学", use: "用于 Harvard's Kennedy School 与 Harvard Business School 两个机构名称。", specialForms: ["Harvard（专有名词）；Harvard's（所有格）"] },
  have: { partOfSpeech: "v./aux.", contextualMeaning: "拥有；完成时助动词", use: "had a market 中为实义动词“拥有”；has changed 等结构中为完成时助动词。", specialForms: ["have/has—had—had—having"] },
  heart: { partOfSpeech: "n.", contextualMeaning: "核心；中心", use: "sit at the heart of 表示处于某事物的核心位置。", collocations: ["sat at the heart of"], specialForms: ["heart—hearts（复数）"] },
  history: { partOfSpeech: "n.", contextualMeaning: "历史；经历", use: "a history of success 指长期积累的成功经历，不是单纯的历史学。", collocations: ["A history of long and effortless success"], specialForms: ["history—histories（复数）"] },
  how: { partOfSpeech: "adv./conj.", contextualMeaning: "多么；怎样", use: "How things have changed 是感叹；see how... 中引导宾语从句。", collocations: ["How things have changed", "see how our businesses are improving their productivity"], specialForms: structureWord },
  huge: { partOfSpeech: "adj.", contextualMeaning: "巨大的；大型的", use: "huge American industries 指规模庞大的美国行业。", specialForms: ["huge—huger—hugest（少用，通常用 much larger）"], examSynonyms: ["enormous（巨大的）", "massive（大规模的）"] },
  human: { partOfSpeech: "adj./n.", contextualMeaning: "人的；人类的", use: "human nature 指人性，出现在第13题A项的过度概括。", specialForms: ["human—humans（名词复数）"] },
  ii: { partOfSpeech: "Roman numeral", contextualMeaning: "二；第二", use: "World War II 中表示第二次世界大战。", specialForms: ["II = two / the Second"] },
  impetus: { partOfSpeech: "n.", contextualMeaning: "推动力；促进", use: "give an impetus to 表示给……推动力；第11题D项错误地把推动力归给劳动力规模。", specialForms: ["impetus—impetuses/impetus（复数）"], examSynonyms: ["stimulus（刺激因素）", "momentum（势头）"] },
  income: { partOfSpeech: "n.", contextualMeaning: "收入", use: "their incomes 为可数复数，指许多美国人的各自收入。", specialForms: ["income—incomes（复数）"], examSynonyms: ["earnings（劳动所得）", "revenue（机构/政府收入）"] },
  industry: { partOfSpeech: "n.", contextualMeaning: "工业；行业", use: "可作不可数总称“工业”，也可作可数名词指具体产业；本文两种用法都有。", collocations: ["machine-tool industry", "America's industrial decline", "has changed its structure"], specialForms: ["industry—industries（复数）"], wordFamily: ["industrial adj. 工业的", "industrialize v. 使工业化", "industrialization n. 工业化"] },
  industrial: { partOfSpeech: "adj.", contextualMeaning: "工业的；产业的", use: "industrial competitiveness/decline 分别表示工业竞争力和工业衰退。", collocations: ["fading industrial competitiveness", "America's industrial decline"], specialForms: noIrregular, wordFamily: ["industry n. 工业；行业", "industrialize v. 使工业化"] },
  inevitable: { partOfSpeech: "adj.", contextualMeaning: "不可避免的；必然的", use: "It was inevitable that... 中作表语，对 that 从句所述变化作必然性评价。", collocations: ["It was inevitable that"], specialForms: noIrregular, examSynonyms: ["unavoidable（无法避免的）", "inescapable（不可逃避的）"] },
  inevitably: { partOfSpeech: "adv.", contextualMeaning: "不可避免地；必然地", use: "Just as inevitably 作句子副词，承接上一句并评价整个判断。", collocations: ["Just as inevitably"], specialForms: noIrregular },
  infer: { partOfSpeech: "v.", contextualMeaning: "推断；推知", use: "infer A from B 表示从证据B推出结论A；第13题询问从全文可推出什么。", specialForms: ["infer—inferred—inferred—inferring"], examSynonyms: ["deduce（演绎推断）", "conclude（得出结论）"] },
  invent: { partOfSpeech: "v.", contextualMeaning: "发明；创造", use: "America had invented semiconductors 使用过去完成时，说明发明早于当时产业危机。", specialForms: ["invent—invented—invented—inventing"], wordFamily: ["invention n. 发明", "inventor n. 发明者", "inventive adj. 有创造力的"] },
  inquiry: { partOfSpeech: "n.", contextualMeaning: "调查；探究", use: "inquiry into + 问题表示对某事的调查。", collocations: ["one inquiry after another", "inquiry into the causes of"], specialForms: ["inquiry—inquiries（复数）"], examSynonyms: ["investigation（正式调查）", "research（系统研究）"] },
  institute: { partOfSpeech: "n./v.", contextualMeaning: "研究所；机构", use: "the Cato Institute 是机构专名；本句中 institute 作名词。", specialForms: ["institute—institutes（复数）；institute—instituted—instituted（动词）"] },
  intense: { partOfSpeech: "adj.", contextualMeaning: "激烈的；强烈的", use: "intense competition 是第13题B项对文中 growing foreign competition 的概括。", specialForms: noIrregular, examSynonyms: ["fierce（激烈的；常修饰竞争）", "severe（严重的）"] },
  international: { partOfSpeech: "adj.", contextualMeaning: "国际的", use: "international cooperation 出现在第13题C项，但原文讨论国际竞争而非合作。", specialForms: noIrregular },
  into: { partOfSpeech: "prep.", contextualMeaning: "进入；针对（调查）", use: "sweep into 表示涌入；inquiry into 表示对某问题的调查。", specialForms: structureWord },
  it: { partOfSpeech: "pron.", contextualMeaning: "它；形式主语", use: "可回指 success history，也可在 It was inevitable / it looked as though 中作形式主语。", specialForms: structureWord },
  its: { partOfSpeech: "possessive det./pron.", contextualMeaning: "它的；其", use: "修饰 industries、workers、structure 等名词；its 不带撇号，it's 才是 it is/has 的缩写。", specialForms: ["it（主格/宾格）—its（物主）—itself（反身）"], confusions: ["its 是物主形式；it's = it is 或 it has。"] },
  japan: { partOfSpeech: "proper n.", contextualMeaning: "日本", use: "与美国形成对比，1995年日本经济仍在挣扎。", specialForms: ["Japan（专有名词）"] },
  july: { partOfSpeech: "proper n.", contextualMeaning: "七月", use: "in July 为月份时间状语；月份名称首字母大写。", specialForms: ["July（月份专名）"] },
  just: { partOfSpeech: "adv./adj.", contextualMeaning: "正是；仅仅", use: "just such 强调“正是这样的”；just to see 表“仅仅看到”。", specialForms: noIrregular },
  kennedy: { partOfSpeech: "proper n.", contextualMeaning: "肯尼迪（学院名称的一部分）", use: "Harvard's Kennedy School of Government 是机构全称。", specialForms: ["Kennedy（专有名词）"] },
  korea: { partOfSpeech: "proper n.", contextualMeaning: "韩国（South Korea）", use: "South Korea's 为国家名所有格，修饰 LG Electronics。", specialForms: ["Korea（专有名词）；Korea's（所有格）"] },
  learn: { partOfSpeech: "v.", contextualMeaning: "学会；逐渐掌握", use: "learn to be + 形容词表示逐渐学会变得更……。", collocations: ["has learnt to be more quick-witted"], specialForms: ["learn—learned/learnt—learned/learnt—learning"] },
  leave: { partOfSpeech: "v./n.", contextualMeaning: "剩下；留下", use: "one maker left 中 left 是过去分词作后置定语，表示“剩下的”。", collocations: ["there was only one American television maker left"], specialForms: ["leave—left—left—leaving"] },
  lg: { partOfSpeech: "proper n. abbreviation", contextualMeaning: "LG（韩国电子企业）", use: "LG Electronics 是收购Zenith的公司名称。", specialForms: ["LG（企业专名缩写）"] },
  look: { partOfSpeech: "v./n.", contextualMeaning: "看起来；回顾", use: "look as though 为系动词判断；look back on 表回顾。", collocations: ["it looked as though", "look back on"], specialForms: ["look—looked—looked—looking"] },
  lose: { partOfSpeech: "v.", contextualMeaning: "失去", use: "had lost part of its domestic market 是第12题D项，对外国汽车涌入的合理改写。", specialForms: ["lose—lost—lost—losing"], examSynonyms: ["forfeit（因过失而失去）", "surrender（放弃/交出）"] },
  loss: { partOfSpeech: "n.", contextualMeaning: "丧失；损失；困惑（at a loss）", use: "loss of predominance 表地位丧失；at a loss 是固定习语“困惑”。", collocations: ["found themselves at a loss over"], specialForms: ["loss—losses（复数）"] },
  "machine-tool": { partOfSpeech: "adj. compound/n.", contextualMeaning: "机床（行业）的", use: "machine-tool industry 为复合定语结构，表示机床行业。", collocations: ["machine-tool industry"], specialForms: ["machine tool—machine tools（名词）；machine-tool（定语形式）"] },
  make: { partOfSpeech: "v./n.", contextualMeaning: "制造；使；构成", use: "making of semiconductors 为名词化“制造”；make me proud 为使役结构。", collocations: ["the making of semiconductors", "makes me proud to be an American"], specialForms: ["make—made—made—making"] },
  maker: { partOfSpeech: "n.", contextualMeaning: "制造商；生产者", use: "American television maker 指美国电视机制造商。", collocations: ["there was only one American television maker left"], specialForms: ["maker—makers（复数）"], wordFamily: ["make v. 制造；使"] },
  management: { partOfSpeech: "n.", contextualMeaning: "管理；经营管理", use: "business management 指企业管理。", collocations: ["a golden age of business management"], specialForms: ["management（通常不可数）；managements（不同管理层时少用）"], wordFamily: ["manage v. 管理；设法做到", "manager n. 管理者", "managerial adj. 管理的"] },
  market: { partOfSpeech: "n./v.", contextualMeaning: "市场", use: "market 可指市场规模或国内市场；本篇用于比较美国与竞争者的市场。", collocations: ["the domestic market"], specialForms: ["market—markets（复数）；market—marketed—marketed（动词）"] },
  manifest: { partOfSpeech: "v./adj./n.", contextualMeaning: "表现；表明", use: "be manifested in the fact that... 表示某种抽象变化体现在某项事实中。", specialForms: ["manifest—manifested—manifested—manifesting"], examSynonyms: ["demonstrate（显示/证明）", "reveal（揭示）"] },
  me: { partOfSpeech: "pron.（宾格）", contextualMeaning: "我", use: "make me proud 中作 make 的宾语。", specialForms: ["I（主格）—me（宾格）—my（形容词性物主代词）—mine（名词性物主代词）"] },
  mid: { partOfSpeech: "adj./prefix", contextualMeaning: "中期的", use: "mid-1980s 表示20世纪80年代中期，通常带连字符。", collocations: ["By the mid-1980s"], specialForms: ["mid-（前缀，表示中间/中期）"] },
  moore: { partOfSpeech: "proper n.", contextualMeaning: "摩尔（人名）", use: "Stephen Moore 是被引述者，其观点不等同于作者观点。", specialForms: ["Moore（专有名词）"] },
  most: { partOfSpeech: "det./pron./adv.", contextualMeaning: "最；大多数", use: "the most skilled 构成最高级；most potential competitors 中表示大多数。", specialForms: ["many/much—more—most"] },
  nature: { partOfSpeech: "n.", contextualMeaning: "本性；自然", use: "human nature 指人性；第13题A把特定美国现象过度泛化为人性。", specialForms: ["nature—natures（不同本性时可数）"] },
  narrow: { partOfSpeech: "v./adj.", contextualMeaning: "缩小；变窄", use: "primacy should have narrowed 表示美国领先优势相对缩小。", collocations: ["this primacy should have narrowed"], specialForms: ["narrow—narrowed—narrowed—narrowing；narrow—narrower—narrowest"], examSynonyms: ["reduce（减少）", "diminish（逐渐缩小）"] },
  new: { partOfSpeech: "adj.", contextualMeaning: "新的", use: "the new computer age 指当时新兴的计算机时代。", specialForms: ["new—newer—newest"] },
  next: { partOfSpeech: "adj./adv./n.", contextualMeaning: "下一个", use: "the next casualty 表示下一个可能受损的产业。", collocations: ["was going to be the next casualty"], specialForms: noIrregular },
  none: { partOfSpeech: "pron.", contextualMeaning: "一个也没有", use: "there is none 中代替 no American television maker。", collocations: ["there is none"], specialForms: structureWord },
  now: { partOfSpeech: "adv./n./conj.", contextualMeaning: "现在；如今", use: "括号内用于更新前句“1987年仅剩一家”的后来情况。", specialForms: noIrregular },
  obvious: { partOfSpeech: "adj.", contextualMeaning: "明显的；显而易见的", use: "such obvious causes as... 表示作者认为美元贬值和经济周期转向是很直接的解释。", collocations: ["such obvious causes as"], specialForms: noIrregular, examSynonyms: ["apparent（明显的/表面看来）", "evident（有证据表明的）"] },
  on: { partOfSpeech: "prep./adv.", contextualMeaning: "在；关于", use: "on the ropes 与 look back on 中均属固定结构的一部分。", specialForms: structureWord },
  one: { partOfSpeech: "numeral/det./pron.", contextualMeaning: "一个；某一个", use: "only one maker 表数量；one inquiry after another 表一个接一个。", collocations: ["one inquiry after another"], specialForms: structureWord },
  our: { partOfSpeech: "possessive det.", contextualMeaning: "我们的", use: "our businesses 指说话者所属国家美国的企业。", specialForms: ["we（主格）—us（宾格）—our（形容词性物主代词）—ours（名词性物主代词）"] },
  over: { partOfSpeech: "prep./adv./adj./n.", contextualMeaning: "关于；因……；在……上方", use: "at a loss over sth 中 over 引出令人困惑的问题。", collocations: ["found themselves at a loss over"], specialForms: structureWord },
  overseas: { partOfSpeech: "adv./adj.", contextualMeaning: "来自海外；海外的", use: "competition from overseas 中作副词，表示竞争来自国外。", collocations: ["the growing competition from overseas"], specialForms: noIrregular },
  painful: { partOfSpeech: "adj.", contextualMeaning: "痛苦的；艰难的", use: "prove painful 是系表结构，表示失去主导地位的过程结果十分痛苦。", collocations: ["proved painful"], specialForms: noIrregular, examSynonyms: ["distressing（令人痛苦的）", "difficult（艰难的）"] },
  painstaking: { partOfSpeech: "adj.", contextualMeaning: "艰苦细致的；煞费苦心的", use: "painstaking efforts 是第11题A项，与原文 effortless success 直接相反。", specialForms: noIrregular, examSynonyms: ["diligent（勤勉的）", "meticulous（极其细致的）"] },
  part: { partOfSpeech: "n./v.", contextualMeaning: "一部分", use: "lost part of its domestic market 表示丧失部分国内市场。", specialForms: ["part—parts（复数）；part—parted—parted（动词）"] },
  passage: { partOfSpeech: "n.", contextualMeaning: "文章；段落", use: "What can be inferred from the passage? 是阅读题题干，要求依据全文推断。", specialForms: ["passage—passages（复数）"] },
  pave: { partOfSpeech: "v.", contextualMeaning: "铺平；为……创造条件", use: "pave the way for 是固定搭配；第13题D错误地删去了 success 转化为动力所需的条件。", specialForms: ["pave—paved—paved—paving"], examSynonyms: ["facilitate（促进）", "prepare（为……作准备）"] },
  people: { partOfSpeech: "n.（集合/复数）", contextualMeaning: "人们", use: "people will look back... 作复数主语；通常不说 peoples，除非表示不同民族。", specialForms: ["person—people（普通复数）；peoples（多个民族）"] },
  period: { partOfSpeech: "n.", contextualMeaning: "时期；一段时间", use: "glowing period / this period 均指经济发展阶段。", collocations: ["entered just such a glowing period", "look back on this period as"], specialForms: ["period—periods（复数）"] },
  potential: { partOfSpeech: "adj./n.", contextualMeaning: "潜在的；可能的", use: "potential competitors 指若未被战争重创便可能与美国竞争的国家。", specialForms: noIrregular },
  predominance: { partOfSpeech: "n.", contextualMeaning: "主导地位；优势地位", use: "retreat/loss from predominance 均指美国世界经济霸主地位的下降。", collocations: ["the retreat from predominance"], specialForms: ["predominance（通常不可数）"], examSynonyms: ["dominance（支配地位）", "primacy（首要地位）"], wordFamily: ["predominant adj. 占主导地位的", "predominate v. 占优势"] },
  pride: { partOfSpeech: "n./v.", contextualMeaning: "自豪；自负", use: "blind pride 带贬义，指缺少客观依据的自负。", collocations: ["yielded to blind pride"], specialForms: ["pride（通常不可数）；pride—prided—prided（动词）"], confusions: ["pride 可中性/褒义“自豪”，但 blind pride 明显贬义。"] },
  primacy: { partOfSpeech: "n.", contextualMeaning: "首要地位；领先优势", use: "this primacy 回指美国战后的世界经济领先地位。", collocations: ["this primacy should have narrowed"], specialForms: ["primacy（通常不可数）"], examSynonyms: ["predominance（主导地位）", "priority（优先性；不是霸主地位）"] },
  productivity: { partOfSpeech: "n.", contextualMeaning: "生产率；生产效率", use: "improve productivity 表示单位投入带来的产出提高。", collocations: ["see how our businesses are improving their productivity"], specialForms: ["productivity（通常不可数）"], wordFamily: ["produce v. 生产", "product n. 产品", "productive adj. 高产的"] },
  progress: { partOfSpeech: "n./v.", contextualMeaning: "进步；发展", use: "economic progress 是第13题B项，对美国复苏的概括。", specialForms: ["progress（名词通常不可数）；progress—progressed—progressed（动词）"] },
  properly: { partOfSpeech: "adv.", contextualMeaning: "恰当地；妥善地", use: "修饰 handled，说明成功史只有被妥善处理才可能转化为动力。", collocations: ["if properly handled"], specialForms: noIrregular, wordFamily: ["proper adj. 恰当的", "property n. 财产/性质（词形相近但词义不同）"] },
  prosperous: { partOfSpeech: "adj.", contextualMeaning: "繁荣的；富裕的", use: "作表语描述America and Americans 的经济富裕状态。", collocations: ["prosperous beyond the dreams of"], specialForms: noIrregular, examSynonyms: ["thriving（繁荣的；发展良好）", "affluent（富裕的；多指人/社会）"], wordFamily: ["prosper v. 繁荣", "prosperity n. 繁荣"] },
  prosperity: { partOfSpeech: "n.", contextualMeaning: "繁荣；富裕", use: "take prosperity for granted 中作宾语，指长期经济繁荣。", collocations: ["stopped taking prosperity for granted"], specialForms: ["prosperity（通常不可数）"], wordFamily: ["prosper v. 繁荣", "prosperous adj. 繁荣的"] },
  prove: { partOfSpeech: "v./linking v.", contextualMeaning: "结果表明是；证明", use: "prove painful 为系动词用法，后接形容词表语。", collocations: ["proved painful"], specialForms: ["prove—proved—proved/proven—proving"], confusions: ["prove + adj. 可译“结果是”，不一定有主动证明动作。"] },
  proud: { partOfSpeech: "adj.", contextualMeaning: "自豪的", use: "make me proud 中作宾补；proud to be... 说明自豪的身份原因。", collocations: ["makes me proud to be an American"], specialForms: ["proud—prouder—proudest"], wordFamily: ["pride n. 自豪/自负", "proudly adv. 自豪地"] },
  "quick-witted": { partOfSpeech: "adj.", contextualMeaning: "机敏的；反应快的", use: "be more quick-witted 作系动词表语，比喻美国工业决策和反应更敏捷。", collocations: ["has learnt to be more quick-witted"], specialForms: ["quick-witted—more quick-witted—most quick-witted"] },
  restructure: { partOfSpeech: "v.", contextualMeaning: "重组；调整结构", use: "restructuring of industry 是第14题B项，是受访者观点的概括。", specialForms: ["restructure—restructured—restructured—restructuring"], wordFamily: ["structure n./v. 结构；组织", "restructuring n. 重组"] },
  revival: { partOfSpeech: "n.", contextualMeaning: "复苏；复兴", use: "the revival of the U.S. economy 指20世纪90年代美国经济复苏。", specialForms: ["revival—revivals（复数）"], wordFamily: ["revive v. 复苏；使恢复"] },
  retreat: { partOfSpeech: "n./v.", contextualMeaning: "退却；退出", use: "the retreat from predominance 指从世界经济主导地位上退下来。", collocations: ["the retreat from predominance"], specialForms: ["retreat—retreated—retreated—retreating（动词）"], examSynonyms: ["withdrawal（撤退；退出）", "decline（下降）"] },
  rich: { partOfSpeech: "adj.", contextualMeaning: "富裕的", use: "grow richer 为系动词结构，比较级说明其他国家逐渐变得更富裕。", collocations: ["as other countries grew richer"], specialForms: ["rich—richer—richest"], examSynonyms: ["wealthy（富有的）", "affluent（富裕的；正式）"] },
  richard: { partOfSpeech: "proper n.", contextualMeaning: "理查德（人名）", use: "Richard Cavanaugh 的名字。", specialForms: ["Richard（专有名词）"] },
  rope: { partOfSpeech: "n./v.", contextualMeaning: "绳索；困境（习语中）", use: "on the ropes 源自拳击，表示濒临失败但尚未彻底垮掉。", collocations: ["on the ropes"], specialForms: ["rope—ropes（复数）；rope—roped—roped（动词）"] },
  sahlman: { partOfSpeech: "proper n.", contextualMeaning: "萨尔曼（人名）", use: "William Sahlman 是第三位被引述者。", specialForms: ["Sahlman（专有名词）"] },
  sat: { partOfSpeech: "v.（sit 的过去式/过去分词）", contextualMeaning: "处于；位于", use: "sat at the heart of 表示处于新计算机时代的核心。", collocations: ["sat at the heart of"], specialForms: ["sit—sat—sat—sitting"] },
  say: { partOfSpeech: "v./n.", contextualMeaning: "说；表示", use: "直接引语在前时使用 says Stephen Moore 的引语倒装。", specialForms: ["say—said—said—saying"] },
  scale: { partOfSpeech: "n./v.", contextualMeaning: "规模", use: "economies of scale 是经济学固定术语“规模经济”。", collocations: ["unparalleled economies of scale"], specialForms: ["scale—scales（复数）；scale—scaled—scaled（动词）"] },
  school: { partOfSpeech: "n./v.", contextualMeaning: "学院；学校", use: "Kennedy School 与 Business School 均为机构名称的一部分。", specialForms: ["school—schools（复数）"] },
  scientist: { partOfSpeech: "n.", contextualMeaning: "科学家", use: "Its scientists 作主语，与 workers 构成平行比较。", specialForms: ["scientist—scientists（复数）"], wordFamily: ["science n. 科学", "scientific adj. 科学的"] },
  sensational: { partOfSpeech: "adj.", contextualMeaning: "耸人听闻的；轰动性的", use: "sometimes sensational findings 表示部分调查结论语气夸张、引人震动。", collocations: ["sometimes sensational findings"], specialForms: noIrregular, examSynonyms: ["dramatic（引人注目的）", "startling（令人震惊的）"] },
  second: { partOfSpeech: "ordinal numeral/adj./n.", contextualMeaning: "第二", use: "the Second World War 为专有历史名称“第二次世界大战”。", collocations: ["after the end of the Second World War"], specialForms: ["two（基数词）—second（序数词）"] },
  see: { partOfSpeech: "v.", contextualMeaning: "看到；了解", use: "see how... 后接 how 宾语从句，表示看到企业怎样提高生产率。", collocations: ["see how our businesses are improving their productivity"], specialForms: ["see—saw—seen—seeing"] },
  seem: { partOfSpeech: "linking v.", contextualMeaning: "似乎；看来", use: "The author seems to believe 是题干谨慎表达，要求推断作者隐含立场。", specialForms: ["seem—seemed—seemed—seeming"] },
  "self-doubt": { partOfSpeech: "n.", contextualMeaning: "自我怀疑", use: "与 blind pride 构成前后心理状态对比。", collocations: ["yielded to blind pride"], specialForms: ["self-doubt（通常不可数）"] },
  semiconductor: { partOfSpeech: "n./adj.", contextualMeaning: "半导体；半导体的", use: "the making of semiconductors 指半导体制造业。", collocations: ["the making of semiconductors"], specialForms: ["semiconductor—semiconductors（复数）"] },
  shift: { partOfSpeech: "v./n.", contextualMeaning: "转变；在……之间转换", use: "shift between A and B 出现在第13题A项，声称人在自我怀疑与盲目自豪之间转换。", specialForms: ["shift—shifted—shifted—shifting"] },
  should: { partOfSpeech: "modal v.", contextualMeaning: "竟会；必然会（在 inevitable 后）", use: "inevitable that... should have narrowed 中 should 带评价语气，不表示道德义务。", specialForms: ["shall—should；should have done（对过去完成情况的表达）"], confusions: ["在 inevitable/strange 等词后的 that 从句中，should 常不译为“应该”。"] },
  shortly: { partOfSpeech: "adv.", contextualMeaning: "不久；很快", use: "修饰 begin to fall，表示收入下降预计很快开始。", collocations: ["would therefore shortly begin to fall"], specialForms: noIrregular },
  shrink: { partOfSpeech: "v.", contextualMeaning: "萎缩；缩小", use: "industries had shrunk 表示产业规模已经缩减。", collocations: ["had shrunk or vanished"], specialForms: ["shrink—shrank—shrunk—shrinking"], examSynonyms: ["contract（收缩）", "diminish（逐渐减少）"] },
  solid: { partOfSpeech: "adj./n.", contextualMeaning: "稳定可靠的；实实在在的", use: "solid growth 表示持续而稳健的增长。", collocations: ["five years of solid growth"], specialForms: noIrregular, examSynonyms: ["steady（稳定的）", "sound（稳健的）"] },
  size: { partOfSpeech: "n./v.", contextualMeaning: "规模；大小", use: "the unparalleled size of its workforce 是第11题D项，原文没有说劳动力规模空前。", specialForms: ["size—sizes（复数）；size—sized—sized（动词）"] },
  skilled: { partOfSpeech: "adj.", contextualMeaning: "熟练的；有技能的", use: "the most skilled 是最高级表语，后面省略了 workers 可由上下文恢复。", collocations: ["the most skilled"], specialForms: ["skilled—more skilled—most skilled"], examSynonyms: ["proficient（熟练的）", "competent（胜任的）"] },
  solely: { partOfSpeech: "adv.", contextualMeaning: "仅仅；完全只", use: "attribute this solely to 表示把复苏完全只归因于某些因素。", collocations: ["attribute this solely to"], specialForms: noIrregular, wordFamily: ["sole adj. 唯一的", "solely adv. 仅仅"] },
  sometimes: { partOfSpeech: "adv.", contextualMeaning: "有时", use: "修饰 sensational，表示调查结论并非全都耸动，只是有时如此。", collocations: ["sometimes sensational findings"], specialForms: noIrregular },
  south: { partOfSpeech: "proper-name component/n./adj./adv.", contextualMeaning: "南；南方的", use: "South Korea 是专有国名“韩国”。", specialForms: ["south（方位词，无普通比较级）"] },
  state: { partOfSpeech: "n./v.", contextualMeaning: "州；国家（United States组成词）", use: "the United States 是美国正式国名；单独 state 还可表示状态或州。", specialForms: ["state—states（复数）；state—stated—stated（动词）"] },
  stephen: { partOfSpeech: "proper n.", contextualMeaning: "斯蒂芬（人名）", use: "Stephen Moore 的名字。", specialForms: ["Stephen（专有名词）"] },
  stop: { partOfSpeech: "v./n.", contextualMeaning: "停止", use: "stop doing 表示停止原来在做的事；stopped taking... 即不再把繁荣视为理所当然。", collocations: ["stopped taking prosperity for granted"], specialForms: ["stop—stopped—stopped—stopping"], confusions: ["stop doing 是停止做；stop to do 是停下当前动作去做另一件事。"] },
  structure: { partOfSpeech: "n./v.", contextualMeaning: "结构；调整结构", use: "change its structure 表示改变产业结构。", collocations: ["has changed its structure"], specialForms: ["structure—structures（复数）；structure—structured—structured（动词）"] },
  success: { partOfSpeech: "n.", contextualMeaning: "成功；成功经历", use: "long and effortless success 中为抽象不可数名词；success in education 中也指成功结果。", collocations: ["A history of long and effortless success"], specialForms: ["success（抽象成功）；a success / successes（成功的人、事或案例）"], wordFamily: ["succeed v. 成功", "successful adj. 成功的", "successfully adv. 成功地"] },
  struggle: { partOfSpeech: "v./n.", contextualMeaning: "艰难挣扎；苦苦应对", use: "has been struggling 是现在完成进行时，表示日本持续面临经济困难。", collocations: ["while Japan has been struggling"], specialForms: ["struggle—struggled—struggled—struggling"] },
  such: { partOfSpeech: "det./pron.", contextualMeaning: "这样的；诸如", use: "just such 回指前文；such...as... 用于列举这类原因。", collocations: ["such obvious causes as"], specialForms: structureWord },
  suicidal: { partOfSpeech: "adj.", contextualMeaning: "自毁性的；自杀性的", use: "suicidal actions 是第12题C项添加的原文没有的信息。", specialForms: noIrregular },
  sweep: { partOfSpeech: "v./n.", contextualMeaning: "席卷；大举涌入", use: "sweep into the market 比喻外国产品大量快速进入并占领市场。", collocations: ["were sweeping into"], specialForms: ["sweep—swept—swept—sweeping"], examSynonyms: ["flood（大量涌入）", "surge（汹涌进入）"] },
  take: { partOfSpeech: "v./n.", contextualMeaning: "把……视为；接管", use: "take prosperity for granted 是固定结构；be taken over 表示被接管。", collocations: ["stopped taking prosperity for granted"], specialForms: ["take—took—taken—taking"] },
  television: { partOfSpeech: "n.", contextualMeaning: "电视机；电视业", use: "American television maker 指美国电视机制造商。", collocations: ["there was only one American television maker left"], specialForms: ["television—televisions（电视机复数）"] },
  textile: { partOfSpeech: "n./adj.", contextualMeaning: "纺织品；纺织业的", use: "textiles 为复数名词，与 cars 并列作主语。", collocations: ["Foreign-made cars and textiles"], specialForms: ["textile—textiles（复数）"] },
  that: { partOfSpeech: "conj./pron./det.", contextualMeaning: "引导从句；那个", use: "可引导真正主语从句或 believe 的宾语从句；需根据句法位置判断。", specialForms: structureWord },
  their: { partOfSpeech: "possessive det.", contextualMeaning: "他们的；它们的", use: "修饰 competitiveness、way、incomes、findings 等名词。", specialForms: ["they（主格）—them（宾格）—their（形容词性物主代词）—theirs（名词性物主代词）"] },
  they: { partOfSpeech: "pron.", contextualMeaning: "他们；它们", use: "They 回指 Americans；themselves 是其反身代词。", specialForms: ["they（主格）—them（宾格）—their/theirs（物主）—themselves（反身）"] },
  there: { partOfSpeech: "adv./existential marker", contextualMeaning: "有；存在句引导词", use: "there was/is 构成存在句，真正主语位于 be 后。", collocations: ["there was only one American television maker left", "there is none"], specialForms: structureWord },
  therefore: { partOfSpeech: "adv.", contextualMeaning: "因此", use: "连接“经营方式失败”与“收入将下降”的因果推断。", collocations: ["would therefore shortly begin to fall"], specialForms: noIrregular },
  thing: { partOfSpeech: "n.", contextualMeaning: "事情；情况", use: "How things have changed 中复数 things 泛指整体局势。", collocations: ["How things have changed"], specialForms: ["thing—things（复数）"] },
  "think-tank": { partOfSpeech: "n.", contextualMeaning: "智库；思想库", use: "作 Cato Institute 的同位语，说明其机构性质。", collocations: ["a think-tank in Washington, DC"], specialForms: ["think-tank—think-tanks（复数）"] },
  though: { partOfSpeech: "conj./adv.", contextualMeaning: "仿佛；尽管", use: "as though 引导表语内容，表示“看起来仿佛……”。", collocations: ["it looked as though"], specialForms: structureWord },
  time: { partOfSpeech: "n./v.", contextualMeaning: "倍；时间", use: "eight times larger 中 times 是倍数单位；for a while 表一段时间。", collocations: ["eight times larger than any competitor", "For a while"], specialForms: ["time—times（复数）；time—timed—timed（动词）"] },
  turn: { partOfSpeech: "v./n.", contextualMeaning: "转向；转折", use: "the turning of the business cycle 指经济周期由衰退转向复苏。", collocations: ["the turning of the business cycle"], specialForms: ["turn—turned—turned—turning"] },
  tv: { partOfSpeech: "n. abbreviation", contextualMeaning: "电视；电视产业", use: "TV industry 是 television industry 的缩写，见第12题A项。", specialForms: ["TV = television"] },
  united: { partOfSpeech: "adj./past participle", contextualMeaning: "联合的；United States国名组成词", use: "the United States 为美国正式国名；此处不单独按普通形容词翻译。", specialForms: ["unite—united—united—uniting"], wordFamily: ["unite v. 联合", "unity n. 团结；统一"] },
  "united states": { partOfSpeech: "proper n.", contextualMeaning: "美国", use: "the United States / the U.S. 均指美国，形式上通常带 the。", specialForms: ["the United States；the U.S.（缩写）"] },
  unparalleled: { partOfSpeech: "adj.", contextualMeaning: "无与伦比的；空前的", use: "unparalleled economies of scale 修饰美国工业获得的规模经济优势。", collocations: ["giving its industries unparalleled economies of scale"], specialForms: noIrregular, examSynonyms: ["unrivalled（无可匹敌的）", "unprecedented（前所未有的）"] },
  vanish: { partOfSpeech: "v.", contextualMeaning: "消失；不复存在", use: "industries had vanished 表示某些产业完全消失，程度强于 shrink。", collocations: ["had shrunk or vanished"], specialForms: ["vanish—vanished—vanished—vanishing"], examSynonyms: ["disappear（消失）", "fade（逐渐淡去）"] },
  war: { partOfSpeech: "n.", contextualMeaning: "战争", use: "the Second World War 指第二次世界大战；the war 回指该战争。", collocations: ["after the end of the Second World War", "whose economies the war had destroyed"], specialForms: ["war—wars（复数）"] },
  way: { partOfSpeech: "n.", contextualMeaning: "方式；方法", use: "their way of doing business 中 way 表示做事方式；of doing 后置说明这种方式的具体内容。", collocations: ["their way of doing business"], specialForms: ["way—ways（复数）"], examSynonyms: ["method（系统的方法）", "means（实现目的的手段；单复数同形）"] },
  warning: { partOfSpeech: "n.", contextualMeaning: "警告；警示", use: "warnings about + 问题表示针对某问题的警告。", collocations: ["were filled with warnings about"], specialForms: ["warning—warnings（复数）"], wordFamily: ["warn v. 警告"] },
  washington: { partOfSpeech: "proper n.", contextualMeaning: "华盛顿", use: "Washington, DC 指美国首都。", specialForms: ["Washington（专有名词）"] },
  what: { partOfSpeech: "pron./det.", contextualMeaning: "什么；所……的事", use: "What can be inferred...? 为特殊疑问词作主语，询问可推断出的结论。", specialForms: structureWord },
  when: { partOfSpeech: "conj./adv./pron.", contextualMeaning: "当……时", use: "引导时间状语从句，说明美国进入辉煌时期的时间背景。", specialForms: structureWord },
  while: { partOfSpeech: "conj./n./v.", contextualMeaning: "而；然而", use: "本句连接美国稳定增长与日本持续挣扎，表示对比而非单纯同时。", collocations: ["while Japan has been struggling"], specialForms: structureWord },
  whose: { partOfSpeech: "relative/possessive pron.", contextualMeaning: "其……的；……的", use: "引导定语从句并表示所属；whose economies 修饰 Europeans and Asians。", collocations: ["whose economies the war had destroyed"], specialForms: structureWord },
  william: { partOfSpeech: "proper n.", contextualMeaning: "威廉（人名）", use: "William Sahlman 的名字。", specialForms: ["William（专有名词）"] },
  with: { partOfSpeech: "prep.", contextualMeaning: "带有；充满", use: "be filled with 中引出所充满的内容。", collocations: ["were filled with warnings about"], specialForms: structureWord },
  withdraw: { partOfSpeech: "v.", contextualMeaning: "撤出；退回", use: "withdraw to its domestic market 是第12题A项，原文事实并非美国电视业成功退守国内市场。", specialForms: ["withdraw—withdrew—withdrawn—withdrawing"], examSynonyms: ["retreat（撤退）", "pull out（撤出）"] },
  worker: { partOfSpeech: "n.", contextualMeaning: "工人；劳动者", use: "its workers 与 its scientists 平行，后面省略 were。", specialForms: ["worker—workers（复数）"], wordFamily: ["work v./n. 工作", "workforce n. 劳动力队伍"] },
  workforce: { partOfSpeech: "n.", contextualMeaning: "劳动力；全体员工", use: "第11题D项称劳动力规模空前，但原文只说工人技术最熟练。", specialForms: ["workforce—workforces（复数）"] },
  world: { partOfSpeech: "n.", contextualMeaning: "世界", use: "the world's best 使用名词所有格，表示世界上最优秀的。", collocations: ["the world's best"], specialForms: ["world—worlds（复数）；world's（所有格）"] },
  year: { partOfSpeech: "n.", contextualMeaning: "年", use: "five years of solid growth 表示持续时间为五年。", collocations: ["five years of solid growth"], specialForms: ["year—years（复数）"] },
  yield: { partOfSpeech: "v./n.", contextualMeaning: "让位于；屈服于", use: "yield to blind pride 表示自我怀疑被盲目自豪取代。", collocations: ["yielded to blind pride"], specialForms: ["yield—yielded—yielded—yielding"], examSynonyms: ["give way（让步/让位）", "surrender（屈服）"] },
  zenith: { partOfSpeech: "proper n./n.", contextualMeaning: "Zenith公司；顶峰", use: "文中为美国电视制造商名称；普通名词 zenith 还可表示顶峰。", specialForms: ["Zenith（公司专名）；zenith—zeniths（普通名词复数）"] },
};

export const passage1FormPartOfSpeech: Record<string, string> = {
  achieved: "v.（过去式/过去分词）",
  actions: "n.（复数）",
  "america's": "proper n.（所有格）",
  americans: "n.（复数）",
  asians: "n.（复数）",
  attributed: "v.（过去分词）",
  been: "v.（be 的过去分词）",
  began: "v.（begin 的过去式）",
  believes: "v.（第三人称单数）",
  bought: "v.（buy 的过去式/过去分词）",
  brought: "v.（bring 的过去式/过去分词）",
  businesses: "n.（复数，企业）",
  cars: "n.（复数）",
  causes: "n.（复数）",
  caused: "v.（过去式）",
  changed: "v.（过去分词）",
  collapsed: "v.（过去分词）",
  competitors: "n.（复数）",
  countries: "n.（复数）",
  destroyed: "v.（过去分词）",
  devalued: "adj./v.（过去分词作定语）",
  dreams: "n.（复数）",
  economies: "n.（复数）",
  efforts: "n.（复数）",
  entered: "v.（过去式）",
  enterprises: "n.（复数）",
  europeans: "n.（复数）",
  fading: "adj./v.-ing（逐渐减弱的）",
  failing: "v.（过去进行时分词）",
  findings: "n.（复数，调查结论）",
  found: "v.（find 的过去分词）",
  given: "v.（give 的过去分词）",
  going: "v.-ing（be going to 结构）",
  granted: "v.（过去分词；固定搭配成分）",
  giving: "v.-ing（结果状语）",
  gone: "v.（go 的过去分词）",
  grew: "v.（grow 的过去式）",
  growing: "adj./v.-ing（不断增强的）",
  had: "v./aux.（have 的过去式）",
  handled: "v.（过去分词，被动意义）",
  "harvard's": "proper n.（所有格）",
  has: "aux.（第三人称单数）",
  improving: "v.（现在进行时分词）",
  incomes: "n.（复数）",
  inferred: "v.（过去分词）",
  industries: "n.（复数）",
  invented: "v.（过去分词）",
  learnt: "v.（learn 的过去分词）",
  larger: "adj.（比较级）",
  left: "v.（过去分词作后置定语）",
  "korea's": "proper n.（所有格）",
  lost: "v.（lose 的过去式/过去分词）",
  looked: "v.（过去式）",
  made: "v.（make 的过去分词）",
  makes: "v.（第三人称单数）",
  making: "n./gerund（制造）",
  manifested: "v.（过去分词，被动语态）",
  narrowed: "v.（过去分词）",
  richer: "adj.（比较级）",
  ropes: "n.（复数；习语组成）",
  restructuring: "n./v.-ing（重组）",
  says: "v.（第三人称单数）",
  scientists: "n.（复数）",
  semiconductors: "n.（复数）",
  shrunk: "v.（shrink 的过去分词）",
  stopped: "v.（过去式）",
  states: "n.（复数；专有国名组成）",
  struggling: "v.（现在完成进行时分词）",
  sweeping: "v.（过去进行时分词）",
  taken: "v.（take 的过去分词）",
  taking: "v.-ing/gerund",
  textiles: "n.（复数）",
  themselves: "reflexive pron.",
  things: "n.（复数）",
  times: "n.（复数，倍数）",
  turning: "n./gerund（转向）",
  united: "adj./v.（过去分词；专有国名组成）",
  warnings: "n.（复数）",
  was: "v.（be 的过去时单数）",
  were: "v.（be 的过去时复数）",
  withdrawn: "v.（withdraw 的过去分词）",
  workers: "n.（复数）",
  "world's": "n.（所有格）",
  would: "modal v.（过去视角中的将来）",
  years: "n.（复数）",
  yielded: "v.（过去分词）",
};
