import type { Question, SentenceAnalysis } from "./data";

export const passage3Sentences: SentenceAnalysis[] = [
  {
    id: "p3-s1",
    number: 1,
    text: "When a new movement in art attains a certain fashion, it is advisable to find out what its advocates are aiming at, for, however farfetched and unreasonable their principles may seem today, it is possible that in years to come they may be regarded as normal.",
    chunks: [
      { text: "When a new movement in art attains a certain fashion, ", role: "condition" },
      { text: "it", role: "subject" },
      { text: " is advisable", role: "predicate" },
      { text: " to find out what its advocates are aiming at, ", role: "object" },
      { text: "for, ", role: "connector" },
      { text: "however farfetched and unreasonable their principles may seem today, ", role: "condition" },
      { text: "it", role: "subject" },
      { text: " is possible", role: "predicate" },
      { text: " that in years to come they may be regarded as normal.", role: "object" },
    ],
    trunk: "It is advisable to find out what its advocates are aiming at; it is possible that their principles may later be regarded as normal.",
    layers: [
      { label: "时间条件", text: "When a new movement in art attains a certain fashion：当艺术中的新运动形成一定风尚时" },
      { label: "建议主句", text: "it is advisable to find out what its advocates are aiming at：最好弄清其拥护者的目标" },
      { label: "原因与让步", text: "for, however farfetched and unreasonable their principles may seem today：因为即使这些原则今天显得牵强而不合理" },
      { label: "可能结果", text: "it is possible that in years to come they may be regarded as normal：多年后它们可能被视为正常" },
    ],
    grammar: [
      "When 引导时间状语从句，attain 在这里表示达到某种风尚或流行程度。",
      "it is advisable to do 是形式主语结构，真正主语是不定式 to find out；what its advocates are aiming at 是 find out 的宾语从句。",
      "however + 形容词 + 主语 + may seem 构成让步结构；farfetched 与 unreasonable 并列作表语。",
      "it is possible that... 是形式主语结构，in years to come 表示将来的若干年后；may be regarded as 是情态动词加被动语态和 as 补足语。",
    ],
    literal: "当艺术中的一场新运动达到某种风尚时，最好弄清它的拥护者在追求什么，因为无论他们的原则今天看起来多么牵强和不合理，多年后它们都有可能被视为正常。",
    natural: "一种新的艺术运动形成风潮后，应该先弄清其拥护者究竟想达到什么目的；因为即使这些原则今天显得牵强荒谬，若干年后也可能被视为正常。",
    logic: "提出评价新艺术思潮的方法：先了解其目标，不要只凭当下观感否定它，为下文讨论未来主义诗歌作铺垫。",
    phrases: ["a new movement in art", "attains a certain fashion", "it is advisable to", "find out", "aiming at", "in years to come", "be regarded as normal"],
  },
  {
    id: "p3-s2",
    number: 2,
    text: "With regard to Futurist poetry, however, the case is rather difficult, for whatever Futurist poetry may be—even admitting that the theory on which it is based may be right—it can hardly be classed as Literature.",
    chunks: [
      { text: "With regard to Futurist poetry, however, ", role: "modifier" },
      { text: "the case", role: "subject" },
      { text: " is rather difficult, ", role: "predicate" },
      { text: "for ", role: "connector" },
      { text: "whatever Futurist poetry may be—even admitting that the theory on which it is based may be right—it", role: "condition" },
      { text: " can hardly be classed", role: "predicate" },
      { text: " as Literature.", role: "object" },
    ],
    trunk: "The case of Futurist poetry is difficult; it can hardly be classed as Literature.",
    layers: [
      { label: "话题限定", text: "With regard to Futurist poetry：就未来主义诗歌而言" },
      { label: "主句判断", text: "the case is rather difficult：情况相当棘手" },
      { label: "让步插入", text: "whatever Futurist poetry may be—even admitting that the theory ... may be right：不论未来主义诗歌是什么，即使承认其理论可能正确" },
      { label: "核心结论", text: "it can hardly be classed as Literature：它很难被归入文学" },
    ],
    grammar: [
      "With regard to 是介词短语，限定讨论对象；however 插入句中表示转折。",
      "whatever 引导让步表语从句；even admitting that... 是现在分词短语作让步补充，that 从句中 on which 引导定语从句修饰 theory。",
      "can hardly be classed as... 是情态动词、近否定副词、被动语态与 class A as B 结构的组合。",
    ],
    literal: "不过，就未来主义诗歌而言，情况相当困难，因为无论未来主义诗歌是什么——即使承认它所依据的理论可能是正确的——它也几乎不能被归为文学。",
    natural: "不过，未来主义诗歌的情况颇为棘手：即便承认它所依据的理论可能正确，这种诗歌也很难算作文学。",
    logic: "把第一句提出的普遍评价原则落实到具体对象，并先亮出作者的保留判断：理论或许有道理，但作品未必属于文学。",
    phrases: ["with regard to", "rather difficult", "on which it is based", "can hardly be classed as Literature"],
  },
  {
    id: "p3-s3",
    number: 3,
    text: "This, in brief, is what the Futurist says: for a century, past conditions of life have been conditionally speeding up, till now we live in a world of noise and violence and speed.",
    chunks: [
      { text: "This", role: "subject" },
      { text: ", in brief, ", role: "modifier" },
      { text: "is what the Futurist says: ", role: "predicate" },
      { text: "for a century, ", role: "condition" },
      { text: "past conditions of life", role: "subject" },
      { text: " have been conditionally speeding up, ", role: "predicate" },
      { text: "till now ", role: "condition" },
      { text: "we", role: "subject" },
      { text: " live", role: "predicate" },
      { text: " in a world of noise and violence and speed.", role: "modifier" },
    ],
    trunk: "This is what the Futurist says: conditions of life have been speeding up, and now we live in a world of noise, violence and speed.",
    layers: [
      { label: "概括引入", text: "This, in brief, is what the Futurist says：以下是未来主义者的简要说法" },
      { label: "时间持续", text: "for a century, past conditions of life have been conditionally speeding up：一个世纪以来，过去的生活条件一直在加速" },
      { label: "现在结果", text: "till now we live in a world of noise and violence and speed：直到如今我们生活在充满噪音、暴力和速度的世界里" },
    ],
    grammar: [
      "This is what... 是系表结构，what 引导表语从句；in brief 是插入的概括语。",
      "have been conditionally speeding up 是现在完成进行时，保留原文 conditionally，强调从过去持续到现在的加速过程。",
      "till now 引出截至现在的结果；a world of noise and violence and speed 中多个 of 短语并列修饰 world。",
    ],
    literal: "简言之，这就是未来主义者所说的：一个世纪以来，过去的生活条件一直在有条件地加速，直到现在我们生活在一个充满噪音、暴力和速度的世界里。",
    natural: "简要说，未来主义者认为：过去一个世纪里，生活节奏不断加快，如今我们已经置身于噪声、暴力和高速充斥的世界。",
    logic: "转述未来主义者的基本理论，把现代生活的加速作为其新诗歌形式主张的出发点。",
    phrases: ["in brief", "conditions of life", "speeding up", "till now", "a world of noise and violence and speed"],
  },
  {
    id: "p3-s4",
    number: 4,
    text: "Consequently, our feelings, thoughts and emotions have undergone a corresponding change.",
    chunks: [
      { text: "Consequently, ", role: "connector" },
      { text: "our feelings, thoughts and emotions", role: "subject" },
      { text: " have undergone", role: "predicate" },
      { text: " a corresponding change.", role: "object" },
    ],
    trunk: "Our feelings, thoughts and emotions have undergone a corresponding change.",
    layers: [
      { label: "因果连接", text: "Consequently：承接生活节奏加速，推出心理变化" },
      { label: "主语并列", text: "our feelings, thoughts and emotions：感情、思想和情绪三个并列抽象名词" },
      { label: "结果", text: "have undergone a corresponding change：已经发生相应变化" },
    ],
    grammar: [
      "Consequently 是句子副词，表示前句原因带来的结果。",
      "feelings、thoughts 和 emotions 是三个并列主语，共同使用复数现在完成时 have undergone。",
      "undergo 是及物动词，表示经历或承受变化；corresponding 修饰 change，指与生活加速相对应的变化。",
    ],
    literal: "因此，我们的感情、思想和情绪已经经历了相应的变化。",
    natural: "因此，人的情感、思想和情绪也随之发生了变化。",
    logic: "从外部生活节奏推导内部心理变化，为下一句提出表达方式必须更新作直接铺垫。",
    phrases: ["have undergone a corresponding change"],
  },
  {
    id: "p3-s5",
    number: 5,
    text: "This speeding up of life, says the Futurist, requires a new form of expression.",
    chunks: [
      { text: "This speeding up of life, ", role: "subject" },
      { text: "says the Futurist, ", role: "connector" },
      { text: "requires", role: "predicate" },
      { text: " a new form of expression.", role: "object" },
    ],
    trunk: "This speeding up of life requires a new form of expression.",
    layers: [
      { label: "主语名词化", text: "This speeding up of life：生活的这种加速" },
      { label: "插入引述", text: "says the Futurist：未来主义者说" },
      { label: "因果要求", text: "requires a new form of expression：要求一种新的表达形式" },
    ],
    grammar: [
      "speeding up of life 是动名词短语名词化作主语，of life 说明加速的对象。",
      "says the Futurist 是倒装的插入引语，主语 the Futurist 位于谓语之后。",
      "require + 名词表示‘需要某物’；a new form of expression 中 of expression 后置修饰 form。",
    ],
    literal: "未来主义者说，生活的这种加速需要一种新的表达形式。",
    natural: "未来主义者认为，生活节奏的加快要求我们采用新的表达方式。",
    logic: "明确提出理论结论：生活和情感改变后，文学表达也必须随之改变。",
    phrases: ["speeding up of life", "a new form of expression"],
  },
  {
    id: "p3-s6",
    number: 6,
    text: "We must speed up our literature too, if we want to interpret modern stress.",
    chunks: [
      { text: "We", role: "subject" },
      { text: " must speed up", role: "predicate" },
      { text: " our literature too, ", role: "object" },
      { text: "if we want to interpret modern stress.", role: "condition" },
    ],
    trunk: "We must speed up our literature if we want to interpret modern stress.",
    layers: [
      { label: "主句", text: "We must speed up our literature too：我们也必须加快文学的节奏" },
      { label: "条件", text: "if we want to interpret modern stress：如果我们想表现现代生活的紧张压力" },
    ],
    grammar: [
      "must + 动词原形表示说话者认为必要的行动；speed up 是及物短语，宾语是 our literature。",
      "too 放在句末表示‘也’，承接前句对新表达形式的要求。",
      "if 引导真实条件句；want to interpret 中 want 后接不定式，interpret 的宾语是 modern stress。",
    ],
    literal: "如果我们想解释现代的压力，我们也必须加快我们的文学。",
    natural: "如果要表现现代生活的紧张节奏，文学也必须加快步伐。",
    logic: "把抽象的‘新表达’转化为具体要求，说明未来主义者主张文学形式跟上现代压力。",
    phrases: ["speed up our literature", "if we want to", "interpret modern stress"],
  },
  {
    id: "p3-s7",
    number: 7,
    text: "We must pour out a large stream of essential words, unhampered by stops, or qualifying adjectives, or finite verbs.",
    chunks: [
      { text: "We", role: "subject" },
      { text: " must pour out", role: "predicate" },
      { text: " a large stream of essential words, ", role: "object" },
      { text: "unhampered by stops, or qualifying adjectives, or finite verbs.", role: "modifier" },
    ],
    trunk: "We must pour out a large stream of essential words.",
    layers: [
      { label: "主干", text: "We must pour out a large stream of essential words：必须倾泻出大量必要词语" },
      { label: "方式限制", text: "unhampered by stops, or qualifying adjectives, or finite verbs：不受句号、限定形容词或限定动词阻碍" },
      { label: "并列清单", text: "stops / qualifying adjectives / finite verbs：三个 or 连接的限制因素" },
    ],
    grammar: [
      "pour out 是动词短语，表示大量连续倾吐；a large stream of 后接不可数或集合意义的名词。",
      "unhampered by... 是过去分词短语作补充说明，表示‘不受……妨碍’；by 后接名词。",
      "三个 or 短语并列作 stops 的补充说明，阅读时要保持同一语法层级。",
    ],
    literal: "我们必须倾泻出一大股必要的词语，不受句号、限定形容词或限定动词的阻碍。",
    natural: "我们必须不受句号、修饰性形容词和限定动词束缚地连续倾吐大量关键语词。",
    logic: "进一步具体化未来主义写作规则，强调连续、压缩和不受传统语法形式限制的语言流动。",
    phrases: ["pour out", "a large stream of essential words", "unhampered by"],
  },
  {
    id: "p3-s8",
    number: 8,
    text: "Instead of describing sounds we must make up words that imitate them; we must use many sizes of type and different colored inks on the same page, and shorten or lengthen words at will.",
    chunks: [
      { text: "Instead of describing sounds ", role: "modifier" },
      { text: "we", role: "subject" },
      { text: " must make up", role: "predicate" },
      { text: " words that imitate them; ", role: "object" },
      { text: "we", role: "subject" },
      { text: " must use", role: "predicate" },
      { text: " many sizes of type and different colored inks", role: "object" },
      { text: " on the same page, and shorten or lengthen words at will.", role: "modifier" },
    ],
    trunk: "We must make up imitative words and use varied type and ink, changing word length at will.",
    layers: [
      { label: "替代方式", text: "Instead of describing sounds：不是描述声音，而是采取另一种表达方式" },
      { label: "第一组动作", text: "we must make up words that imitate them：创造模仿声音的词语" },
      { label: "第二组动作", text: "we must use many sizes of type and different colored inks：使用不同字号和颜色的墨水" },
      { label: "自由调整", text: "on the same page, and shorten or lengthen words at will：在同一页上随意缩短或拉长词语" },
    ],
    grammar: [
      "instead of 是介词结构，后接 describing 这一动名词；make up words 是‘创造词语’，不是‘化妆’。",
      "that imitate them 引导限制性定语从句修饰 words，them 指 sounds。",
      "分号连接两个完整分句；第二分句中 and shorten or lengthen 与 use 并列，共用 must。",
      "at will 是方式短语，表示按照意愿、随意地；shorten 与 lengthen 构成反义并列。",
    ],
    literal: "我们必须创造模仿声音的词语，而不是描述声音；我们必须在同一页上使用许多字号和不同颜色的墨水，并随意缩短或拉长词语。",
    natural: "与其描写声音，不如造出能模仿声音的词；还要在同一页上使用不同大小的字体和不同颜色的墨水，随意改变词语长短。",
    logic: "列举视觉和语言层面的具体实验手法，显示未来主义者如何把‘新表达形式’落实到文本排版和造词。",
    phrases: ["instead of describing", "make up words", "imitate them", "on the same page", "at will"],
  },
  {
    id: "p3-s9",
    number: 9,
    text: "Certainly their descriptions of battles are confused.",
    chunks: [
      { text: "Certainly ", role: "connector" },
      { text: "their descriptions of battles", role: "subject" },
      { text: " are confused.", role: "predicate" },
    ],
    trunk: "Their descriptions of battles are confused.",
    layers: [
      { label: "评价副词", text: "Certainly：明确承认一个可以观察到的事实" },
      { label: "主语", text: "their descriptions of battles：他们对战斗的描写" },
      { label: "系表结构", text: "are confused：显得混乱" },
    ],
    grammar: [
      "Certainly 是句子副词，表示作者承认下文批评对象确实存在某种问题。",
      "descriptions of battles 中 of 引出描写的对象；主语中心词 descriptions 为复数，所以用 are。",
      "confused 是过去分词形容词，描述文字呈现出的混乱状态。",
    ],
    literal: "当然，他们对战斗的描写是混乱的。",
    natural: "当然，他们描写战斗的文字确实很混乱。",
    logic: "先承认未来主义诗歌在表达实验上的一个明显问题，为下一句举例说明其难以阅读作引子。",
    phrases: ["descriptions of battles"],
  },
  {
    id: "p3-s10",
    number: 10,
    text: "But it is a little upsetting to read in the explanatory notes that a certain line describes a fight between a Turkish and a Bulgarian officer on a bridge off which they both fall into the river—and then to find that the line consists of the noise of their falling and the weights of the officers: “Pluff! Pluff! A hundred and eighty-five kilograms.”",
    chunks: [
      { text: "But ", role: "connector" },
      { text: "it", role: "subject" },
      { text: " is a little upsetting", role: "predicate" },
      { text: " to read in the explanatory notes that a certain line describes a fight between a Turkish and a Bulgarian officer on a bridge off which they both fall into the river—and then to find that the line consists of the noise of their falling and the weights of the officers: ", role: "object" },
      { text: "“Pluff! Pluff! A hundred and eighty-five kilograms.”", role: "object" },
    ],
    trunk: "It is upsetting to read that a line describing a fight consists only of falling noises and the officers' weights.",
    layers: [
      { label: "情绪主句", text: "But it is a little upsetting：但是这有点令人不安" },
      { label: "形式主语", text: "to read in the explanatory notes that...：真正主语是阅读说明中的事实" },
      { label: "定语与关系词", text: "a fight between a Turkish and a Bulgarian officer on a bridge off which they both fall into the river：off which 引导定语从句，which 指 bridge" },
      { label: "并列不定式", text: "and then to find that...：继而发现该诗行由坠落声和军官体重组成" },
      { label: "拟声结尾", text: "“Pluff! Pluff! A hundred and eighty-five kilograms.”：用拟声词和数字呈现所谓战斗描写" },
    ],
    grammar: [
      "it is + 形容词 + to do 是形式主语结构；a little 修饰 upsetting，语气表示‘有点令人不安’。",
      "that a certain line describes... 是 read 的宾语从句；between A and B 连接两个并列人物，off which 引导介词提前的定语从句。",
      "and then to find 与 to read 并列；find 后接 that 宾语从句，consist of 表示由……组成。",
      "their falling 中 falling 是动名词，the weights of the officers 中 of 表所属；引号内容是该诗行的原样拟声和数字。",
    ],
    literal: "但是，在说明中读到某一行描写一名土耳其军官和一名保加利亚军官在桥上打斗、两人从桥上掉进河里，然后又发现这一行由他们坠落的声音和军官们的体重组成，这有点令人不安：‘扑通！扑通！一百八十五公斤。’",
    natural: "但读到说明才知道：某行诗描写的是一名土耳其军官和一名保加利亚军官在桥上交战并双双坠河；再看诗行本身，却只有坠落的声音和军官的体重，这实在令人不适：‘扑通！扑通！一百八十五公斤。’",
    logic: "用具体而荒诞的说明与诗行对照，证明这种形式实验虽有理论依据，却牺牲了可理解性和文学表达。",
    phrases: ["a little upsetting", "explanatory notes", "a fight between a Turkish and a Bulgarian officer", "off which", "fall into the river", "consists of", "the noise of their falling", "the weights of the officers"],
  },
  {
    id: "p3-s11",
    number: 11,
    text: "This, though it fulfills the laws and requirements of Futurist poetry, can hardly be classed as Literature.",
    chunks: [
      { text: "This, ", role: "subject" },
      { text: "though it fulfills the laws and requirements of Futurist poetry, ", role: "condition" },
      { text: "can hardly be classed", role: "predicate" },
      { text: " as Literature.", role: "object" },
    ],
    trunk: "This can hardly be classed as Literature, although it fulfills Futurist requirements.",
    layers: [
      { label: "指代总结", text: "This：指上一句所举的诗行及其写法" },
      { label: "让步从句", text: "though it fulfills the laws and requirements of Futurist poetry：尽管它满足未来主义诗歌的规则和要求" },
      { label: "作者结论", text: "can hardly be classed as Literature：仍很难归入文学" },
    ],
    grammar: [
      "though 引导让步状语从句，fulfills 的宾语是并列名词 laws and requirements。",
      "the laws and requirements of... 中 of 说明这些规则和要求所属的体系。",
      "can hardly be classed as Literature 与第2句呼应，hardly 表示‘几乎不能’，被动结构强调分类结果。",
    ],
    literal: "尽管这满足未来主义诗歌的法律和要求，这几乎不能被归为文学。",
    natural: "尽管它符合未来主义诗歌的规则和要求，这样的作品却很难称得上文学。",
    logic: "作出阶段性评价：承认未来主义内部标准的有效性，但坚持文学判断不能只看是否符合其自定规则。",
    phrases: ["fulfills the laws and requirements of Futurist poetry", "can hardly be classed as Literature"],
  },
  {
    id: "p3-s12",
    number: 12,
    text: "All the same, no thinking man can refuse to accept their first proposition: that a great change in our emotional life calls for a change of expression.",
    chunks: [
      { text: "All the same, ", role: "connector" },
      { text: "no thinking man", role: "subject" },
      { text: " can refuse to accept", role: "predicate" },
      { text: " their first proposition: ", role: "object" },
      { text: "that a great change in our emotional life calls for a change of expression.", role: "object" },
    ],
    trunk: "No thinking man can refuse to accept their first proposition: a great emotional change calls for a change of expression.",
    layers: [
      { label: "让步转折", text: "All the same：尽管前面批评作品，仍承认其第一项主张" },
      { label: "主句", text: "no thinking man can refuse to accept their first proposition：有思考能力的人不能拒绝接受这一主张" },
      { label: "同位语从句", text: "that a great change in our emotional life calls for a change of expression：具体解释 proposition 的内容" },
    ],
    grammar: [
      "All the same 是让步转折副词短语，表示在前述情况不变时仍成立的判断。",
      "no + 单数可数名词表示‘没有任何……’，thinking 作前置定语；can refuse to accept 中 refuse 后接不定式。",
      "冒号后的 that 从句是 proposition 的同位语，call for 表示‘要求、需要’；a change in/of 分别说明变化涉及的领域和变化的对象。",
    ],
    literal: "尽管如此，没有一个有思想的人能够拒绝接受他们的第一个主张：我们情感生活的巨大变化要求表达方式发生变化。",
    natural: "不过，任何有思考能力的人都不能否认他们的第一项主张：情感生活发生巨大变化，就需要相应改变表达方式。",
    logic: "在批评未来主义诗歌的形式之后保留其合理内核，承认时代和情感变化确实会要求新的表达。",
    phrases: ["all the same", "refuse to accept", "a great change in our emotional life", "calls for a change of expression"],
  },
  {
    id: "p3-s13",
    number: 13,
    text: "The whole question is really this: have we essentially changed?",
    chunks: [
      { text: "The whole question", role: "subject" },
      { text: " is really", role: "predicate" },
      { text: " this: ", role: "object" },
      { text: "have we essentially changed?", role: "condition" },
    ],
    trunk: "The whole question is whether we have essentially changed.",
    layers: [
      { label: "总结主语", text: "The whole question：全文真正需要回答的问题" },
      { label: "系表结构", text: "is really this：实际上就是下面这一点" },
      { label: "冒号后问题", text: "have we essentially changed?：我们是否发生了根本变化" },
    ],
    grammar: [
      "the whole question is this 是系表结构，this 后用冒号引出具体内容。",
      "have we essentially changed? 是直接疑问句，完成时询问截至现在是否发生了根本改变。",
      "essentially 是程度副词，修饰 changed，强调‘本质上’而非表面变化。",
    ],
    literal: "整个问题实际上是这个：我们本质上改变了吗？",
    natural: "归根到底，问题在于：我们的本质是否真的发生了变化？",
    logic: "以开放式反问收束全文，把对未来主义诗歌的评价提升为对现代人是否真正改变、是否需要新表达的根本追问。",
    phrases: ["the whole question", "essentially changed"],
  },
];

export const passage3Questions: Question[] = [
  {
    id: 19,
    sentenceId: "p3-s11",
    prompt: "This passage is mainly.",
    options: [
      { key: "A", text: "a survey of new approaches to art" },
      { key: "B", text: "a review of Futurist poetry" },
      { key: "C", text: "about merits of the Futurist movement" },
      { key: "D", text: "about laws and requirements of literature" },
    ],
    answer: "B",
    locating: "全文围绕 Futurist poetry 展开：第2句提出评价难题，第3—8句转述其理论和写法，第9—11句以战斗诗行说明其局限，第12—13句保留其第一项合理主张并提出总结性追问。",
    explanations: {
      A: "文章没有调查多种艺术新方法，而是集中评述一种具体的未来主义诗歌。",
      B: "正确。文章既介绍未来主义诗歌的理论和形式，又用具体例子评价其可读性和文学性，属于对该诗歌的评论。",
      C: "作者并未笼统赞扬未来主义运动的优点，反而明确说其作品很难归入 Literature。",
      D: "法律和要求只是第11句中用于说明未来主义内部标准的局部信息，不能概括全文。",
    },
    analysis: {
      prompt: questionAnalysis(
        "p3-q19-prompt",
        19,
        "This passage is mainly.",
        [
          { text: "This passage", role: "subject" },
          { text: " is", role: "predicate" },
          { text: " mainly.", role: "modifier" },
        ],
        "This passage is mainly + 名词短语",
        [
          { label: "指代范围", text: "This passage：指题干所给的整篇文章，而不是某一个例句" },
          { label: "系表框架", text: "is mainly：系动词后等待一个概括文章性质的表语" },
          { label: "省略位置", text: "mainly 后的内容由 A-D 选项补足，判断重点是全文覆盖范围" },
        ],
        [
          "This passage is mainly... 是阅读主旨题常见的省略句，is 后应接名词短语或形容词短语作表语。",
          "mainly 表示‘主要地’，要求选择能够覆盖全文论证，而不是只对应一个局部细节的选项。",
        ],
        "这篇文章主要是……",
        "这篇文章主要是在评论什么内容？",
        "题干把任务限定为概括全文体裁和对象，答案必须同时涵盖理论介绍、例证批评和结尾保留判断。",
      ),
      options: {
        A: questionAnalysis(
          "p3-q19-option-a",
          19,
          "a survey of new approaches to art",
          [
            { text: "a survey", role: "subject" },
            { text: " of new approaches to art", role: "modifier" },
          ],
          "a survey of new approaches to art",
          [
            { label: "中心名词", text: "a survey：名词 survey 表示系统调查或概览" },
            { label: "范围修饰", text: "of new approaches to art：of 短语把调查对象扩展为艺术的新方法" },
          ],
          [
            "a survey of... 是名词短语，survey 表示系统调查；它需要多个对象或方法作为调查范围。",
            "approaches to art 中 to 引出所涉及的领域，不能据此把文章误判为多种方法的调查。",
          ],
          "对艺术新方法的调查",
          "对艺术新方法进行的调查",
          "该选项把文章对象扩大为多种艺术方法，未体现全文只围绕 Futurist poetry 展开。",
        ),
        B: questionAnalysis(
          "p3-q19-option-b",
          19,
          "a review of Futurist poetry",
          [
            { text: "a review", role: "subject" },
            { text: " of Futurist poetry", role: "modifier" },
          ],
          "a review of Futurist poetry",
          [
            { label: "中心名词", text: "a review：名词 review 表示评论、评述" },
            { label: "评论对象", text: "of Futurist poetry：of 短语限定评论对象为未来主义诗歌" },
          ],
          [
            "a review of + 对象是评论类名词短语，of 后接被评述的作品或主题。",
            "Futurist poetry 是不可数的流派名称，poetry 不需要复数词尾。",
          ],
          "对未来主义诗歌的评论",
          "一篇评述未来主义诗歌的文章",
          "该选项同时覆盖文章介绍的理论、展示的写法、作者的批评和保留意见，能概括全文。",
        ),
        C: questionAnalysis(
          "p3-q19-option-c",
          19,
          "about merits of the Futurist movement",
          [
            { text: "about merits", role: "modifier" },
            { text: " of the Futurist movement", role: "subject" },
          ],
          "about merits of the Futurist movement",
          [
            { label: "话题介词", text: "about merits：about 引出讨论主题，merits 表优点" },
            { label: "所属范围", text: "of the Futurist movement：of 说明这些优点属于未来主义运动" },
          ],
          [
            "about + 名词短语可引出话题，但 about merits 只承诺讨论优点。",
            "merits 是可数名词复数，the Futurist movement 是其所属范围；语法成立不代表主旨成立。",
          ],
          "关于未来主义运动的优点",
          "讨论未来主义运动有哪些优点",
          "作者不仅没有单向罗列优点，还明确质疑其作品的文学性，因此该选项评价方向过窄。",
        ),
        D: questionAnalysis(
          "p3-q19-option-d",
          19,
          "about laws and requirements of literature",
          [
            { text: "about laws and requirements", role: "modifier" },
            { text: " of literature", role: "subject" },
          ],
          "about laws and requirements of literature",
          [
            { label: "并列名词", text: "laws and requirements：and 连接两个并列名词，表示规则和要求" },
            { label: "所属范围", text: "of literature：of 把规则和要求归于文学这一领域" },
          ],
          [
            "laws and requirements of... 是名词并列结构，of 后说明所属领域。",
            "literature 通常作不可数名词，表示文学这一类别；该短语只对应第11句的局部讨论。",
          ],
          "关于文学的规则和要求",
          "讨论文学应遵守的规则和要求",
          "文章讨论的是未来主义诗歌及其表达实验，不是在系统说明文学的一般法律或要求。",
        ),
      },
      answer: questionAnalysis(
        "p3-q19-answer",
        19,
        "This passage is mainly a review of Futurist poetry.",
        [
          { text: "This passage", role: "subject" },
          { text: " is mainly", role: "predicate" },
          { text: " a review of Futurist poetry.", role: "object" },
        ],
        "This passage is mainly a review of Futurist poetry.",
        [
          { label: "主语", text: "This passage：指整篇阅读文章" },
          { label: "判断框架", text: "is mainly：系动词与程度副词构成主旨判断" },
          { label: "表语", text: "a review of Futurist poetry：名词短语说明文章的体裁和对象" },
        ],
        [
          "is 后接名词短语 a review of Futurist poetry 作表语，回答‘文章是什么’。",
          "of Futurist poetry 中 of 引出评论对象，Futurist 作专名形容词修饰 poetry。",
        ],
        "这篇文章主要是一篇对未来主义诗歌的评论。",
        "全文主要是在评述未来主义诗歌。",
        "组合句把题干的主旨框架和正确选项合并，完整对应全文从介绍到批评再到保留意见的推进。",
      ),
    },
  },
  {
    id: 20,
    sentenceId: "p3-s1",
    prompt: "When a novel literary idea appears, people should try to.",
    options: [
      { key: "A", text: "determine its purposes" },
      { key: "B", text: "ignore its flaws" },
      { key: "C", text: "follow the new fashions" },
      { key: "D", text: "accept the principles" },
    ],
    answer: "A",
    locating: "第1句明确说 it is advisable to find out what its advocates are aiming at，即新艺术运动出现时应先弄清其拥护者想达到什么目的。",
    explanations: {
      A: "正确。find out what its advocates are aiming at 与 determine its purposes 同义，都是先判断这种新观念的目标。",
      B: "原文只说不要因原则今天显得牵强就立即否定，并没有要求忽略其缺点。",
      C: "attains a certain fashion 只是出现的背景，不是人们应当盲目追随潮流的建议。",
      D: "作者建议了解目标，而不是未经判断就接受其原则；第1句还保留了对原则合理性的审慎态度。",
    },
    analysis: {
      prompt: questionAnalysis(
        "p3-q20-prompt",
        20,
        "When a novel literary idea appears, people should try to.",
        [
          { text: "When a novel literary idea appears, ", role: "condition" },
          { text: "people", role: "subject" },
          { text: " should try", role: "predicate" },
          { text: " to.", role: "modifier" },
        ],
        "When an idea appears, people should try to ...",
        [
          { label: "时间条件", text: "When a novel literary idea appears：当一种新颖的文学观念出现时" },
          { label: "主句主语", text: "people：泛指面对新观念的读者或公众" },
          { label: "建议框架", text: "should try to：should 表建议，try to 后等待选项补足动作" },
        ],
        [
          "When 引导时间状语从句，appears 是第三人称单数，主语是 a novel literary idea。",
          "should try to 是情态动词加不定式结构，to 后必须接动词原形；选项提供真正动作。",
        ],
        "当一种新颖的文学观念出现时，人们应该努力去……",
        "新颖的文学观念出现时，人们首先应该做什么？",
        "题干要求从第1句提取建议动作，不能把背景、评价或未经判断的接受当成结论。",
      ),
      options: {
        A: questionAnalysis(
          "p3-q20-option-a",
          20,
          "determine its purposes",
          [
            { text: "determine", role: "predicate" },
            { text: " its purposes", role: "object" },
          ],
          "determine its purposes",
          [
            { label: "动作", text: "determine：直接表示确定或查明" },
            { label: "宾语", text: "its purposes：its 指新观念，purposes 表其目标" },
          ],
          [
            "determine 是及物动词，可直接接名词复数 purposes 作宾语。",
            "its 是物主限定词，purposes 是复数，表示一个观念可能有多个目标。",
          ],
          "确定它的目标",
          "弄清这种新观念究竟想达到什么目的",
          "与原文 find out what its advocates are aiming at 的宾语和逻辑完全对应。",
        ),
        B: questionAnalysis(
          "p3-q20-option-b",
          20,
          "ignore its flaws",
          [
            { text: "ignore", role: "predicate" },
            { text: " its flaws", role: "object" },
          ],
          "ignore its flaws",
          [
            { label: "动作", text: "ignore：表示有意不理会" },
            { label: "宾语", text: "its flaws：its 指新观念，flaws 表缺点" },
          ],
          [
            "ignore 是及物动词，直接接名词短语 its flaws，不需要介词。",
            "flaws 是可数名词复数，表示多个可能的缺陷；该结构语法虽成立，逻辑却与原文不同。",
          ],
          "忽视它的缺点",
          "对这种新观念的缺点视而不见",
          "原文要求先查明目标，并未要求不理会缺点；该项把审慎理解偷换成盲目包容。",
        ),
        C: questionAnalysis(
          "p3-q20-option-c",
          20,
          "follow the new fashions",
          [
            { text: "follow", role: "predicate" },
            { text: " the new fashions", role: "object" },
          ],
          "follow the new fashions",
          [
            { label: "动作", text: "follow：表示跟随或追随" },
            { label: "宾语", text: "the new fashions：特指新出现的风尚" },
          ],
          [
            "follow 是及物动词，the new fashions 作宾语；the 表示语境中已知的风尚。",
            "attains a certain fashion 是文章背景，不等于 should follow fashions 的建议。",
          ],
          "追随新的风尚",
          "跟着新潮流走",
          "原文只把风尚作为新运动出现的背景，未主张人们盲目追随潮流。",
        ),
        D: questionAnalysis(
          "p3-q20-option-d",
          20,
          "accept the principles",
          [
            { text: "accept", role: "predicate" },
            { text: " the principles", role: "object" },
          ],
          "accept the principles",
          [
            { label: "动作", text: "accept：表示接受某个观点或原则" },
            { label: "宾语", text: "the principles：特指该运动提出的一套原则" },
          ],
          [
            "accept 是及物动词，the principles 作宾语；the 指前文已提到的原则。",
            "接受原则是比查明目标更强的结论，超出了第1句的审慎建议。",
          ],
          "接受这些原则",
          "未经判断就接受这套原则",
          "作者只要求了解倡导者的目标，并没有要求先验地接受其原则。",
        ),
      },
      answer: questionAnalysis(
        "p3-q20-answer",
        20,
        "When a novel literary idea appears, people should try to determine its purposes.",
        [
          { text: "When a novel literary idea appears, ", role: "condition" },
          { text: "people", role: "subject" },
          { text: " should try to determine", role: "predicate" },
          { text: " its purposes.", role: "object" },
        ],
        "people should try to determine its purposes",
        [
          { label: "条件从句", text: "When a novel literary idea appears：新观念出现的时间背景" },
          { label: "建议主句", text: "people should try to determine：人们应该努力查明" },
          { label: "宾语", text: "its purposes：查明该观念的目标" },
        ],
        [
          "should try to determine 中 should 后接动词原形，try to determine 表努力查明。",
          "determine 是及物动词，its purposes 是宾语；其意义对应原文 find out what... are aiming at。",
        ],
        "当一种新颖的文学观念出现时，人们应该努力确定它的目标。",
        "面对新颖的文学观念，先弄清它究竟要实现什么目的。",
        "组合句把第1句的时间背景、建议和目标补足为完整判断，正是题目要求的动作。",
      ),
    },
  },
  {
    id: 21,
    sentenceId: "p3-s5",
    prompt: "Futurists claim that we must.",
    options: [
      { key: "A", text: "increase the production of literature" },
      { key: "B", text: "use poetry to relieve modern stress" },
      { key: "C", text: "develop new modes of expression" },
      { key: "D", text: "avoid using adjectives and verbs" },
    ],
    answer: "C",
    locating: "第5句说 speeding up of life requires a new form of expression，第6—8句又具体说明要加快文学、造词并改变排版，因此核心是发展新的表达方式。",
    explanations: {
      A: "production 指产量，原文讨论的是表达形式和文学节奏，不是增加文学作品数量。",
      B: "现代压力是需要被 interpret 的对象，未来主义者没有说用诗歌去 relieve 或缓解压力。",
      C: "正确。a new form of expression 概括了新表达形式、造词、字号和颜色等主张。",
      D: "第7句说不受 qualifying adjectives or finite verbs 阻碍，重点是写作不受传统形式束缚，并非绝对禁止使用所有形容词和动词。",
    },
    analysis: {
      prompt: questionAnalysis(
        "p3-q21-prompt",
        21,
        "Futurists claim that we must.",
        [
          { text: "Futurists", role: "subject" },
          { text: " claim", role: "predicate" },
          { text: " that we must.", role: "object" },
        ],
        "Futurists claim that we must ...",
        [
          { label: "主语", text: "Futurists：未来主义者这一群体" },
          { label: "观点动词", text: "claim：声称或主张" },
          { label: "宾语从句框架", text: "that we must：that 引出必须做什么的内容，动作由选项补足" },
        ],
        [
          "claim that... 是动词加宾语从句，that 后用完整分句。",
          "must 后接动词原形，题干把真正动作留给选项；不能把 must 当作名词。",
        ],
        "未来主义者声称我们必须……",
        "未来主义者主张我们必须做什么？",
        "题干要求概括第5—8句的行动主张，答案应是改变文学表达方式，而非改变作品数量或缓解压力。",
      ),
      options: {
        A: questionAnalysis(
          "p3-q21-option-a",
          21,
          "increase the production of literature",
          [
            { text: "increase", role: "predicate" },
            { text: " the production of literature", role: "object" },
          ],
          "increase the production of literature",
          [
            { label: "动作", text: "increase：提高数量或程度" },
            { label: "宾语", text: "the production of literature：文学作品的产量" },
          ],
          [
            "increase + 名词表示提高数量；production of literature 中 production 是产量概念。",
            "原文的 speeding up 指表达节奏和形式，不是增加文学作品的生产数量。",
          ],
          "增加文学作品的产量",
          "让文学作品生产得更多",
          "该项把形式和节奏变化误读成数量增长，未对应 new form of expression。",
        ),
        B: questionAnalysis(
          "p3-q21-option-b",
          21,
          "use poetry to relieve modern stress",
          [
            { text: "use poetry", role: "predicate" },
            { text: " to relieve modern stress", role: "modifier" },
          ],
          "use poetry to relieve modern stress",
          [
            { label: "工具动作", text: "use poetry：把诗歌作为手段" },
            { label: "目的不定式", text: "to relieve modern stress：to do 表目的，relieve 表缓解" },
          ],
          [
            "use A to do B 表示用 A 做 B；to relieve 是目的不定式。",
            "原文说 interpret modern stress，interpret 是诠释，不是 relieve 的缓解；两个动词逻辑方向不同。",
          ],
          "用诗歌来缓解现代压力",
          "借诗歌减轻现代生活的压力",
          "该项把需要被表现的现代压力改成需要被消除的压力，改变了原文目的。",
        ),
        C: questionAnalysis(
          "p3-q21-option-c",
          21,
          "develop new modes of expression",
          [
            { text: "develop", role: "predicate" },
            { text: " new modes of expression", role: "object" },
          ],
          "develop new modes of expression",
          [
            { label: "动作", text: "develop：发展或形成" },
            { label: "宾语", text: "new modes of expression：新的表达方式" },
          ],
          [
            "develop + 名词表示发展或形成某种方法；modes 是可数名词复数。",
            "of expression 后置修饰 modes，说明这些 mode 服务于表达。",
          ],
          "发展新的表达方式",
          "形成新的表达模式",
          "与第5句 a new form of expression 及第6—8句的具体做法一致，概括层级恰当。",
        ),
        D: questionAnalysis(
          "p3-q21-option-d",
          21,
          "avoid using adjectives and verbs",
          [
            { text: "avoid", role: "predicate" },
            { text: " using adjectives and verbs", role: "object" },
          ],
          "avoid using adjectives and verbs",
          [
            { label: "动作", text: "avoid：避免做某事" },
            { label: "动名词宾语", text: "using adjectives and verbs：avoid 后接动名词，列举形容词和动词" },
          ],
          [
            "avoid 后接动名词 using，不能接动词原形；adjectives and verbs 是并列宾语。",
            "原文 unhampered by 表示不受传统形式阻碍，不等于绝对避免使用这些词类。",
          ],
          "避免使用形容词和动词",
          "完全不用形容词和动词",
          "该项把‘不受阻碍’夸大成‘完全不用’，与原文的限定语气不符。",
        ),
      },
      answer: questionAnalysis(
        "p3-q21-answer",
        21,
        "Futurists claim that we must develop new modes of expression.",
        [
          { text: "Futurists", role: "subject" },
          { text: " claim", role: "predicate" },
          { text: " that we must develop", role: "object" },
          { text: " new modes of expression.", role: "modifier" },
        ],
        "Futurists claim that we must develop new modes of expression.",
        [
          { label: "主句", text: "Futurists claim：未来主义者提出主张" },
          { label: "宾语从句", text: "that we must develop：that 引出必须采取的行动" },
          { label: "行动对象", text: "new modes of expression：发展的对象是新的表达方式" },
        ],
        [
          "claim that 后接完整宾语从句；must develop 中 must 后接动词原形。",
          "modes of expression 是名词短语，of expression 说明 mode 的用途或领域。",
        ],
        "未来主义者声称我们必须发展新的表达方式。",
        "未来主义者主张文学必须采用新的表达模式。",
        "组合句把第5句的总要求与第6—8句的具体手段压缩为题目所问的核心主张。",
      ),
    },
  },
  {
    id: 22,
    sentenceId: "p3-s11",
    prompt: "The author believes that Futurist poetry is.",
    options: [
      { key: "A", text: "based on reasonable principles" },
      { key: "B", text: "new and acceptable to ordinary people" },
      { key: "C", text: "indicative of a basic change in human nature" },
      { key: "D", text: "more of a transient phenomenon than literature" },
    ],
    answer: "D",
    locating: "第2句说即使其理论可能正确，未来主义诗歌也很难被归为 Literature；第9—11句以混乱的战斗描写具体证明这一判断。",
    explanations: {
      A: "作者只承认理论‘may be right’，这是让步假设，不等于认定原则本身合理。",
      B: "全文没有说普通人接受这种诗歌；相反，说明与诗行脱节的例子突出其难以理解。",
      C: "作者承认情感生活变化会要求表达变化，但没有说未来主义诗歌证明人性本质已经改变。",
      D: "正确。作者认为它可能是对时代变化的短暂回应，却因难以理解而不能算作真正的 Literature。",
    },
    analysis: {
      prompt: questionAnalysis(
        "p3-q22-prompt",
        22,
        "The author believes that Futurist poetry is.",
        [
          { text: "The author", role: "subject" },
          { text: " believes", role: "predicate" },
          { text: " that Futurist poetry is.", role: "object" },
        ],
        "The author believes that Futurist poetry is ...",
        [
          { label: "主语", text: "The author：文章作者，而非被引述的未来主义者" },
          { label: "观点动词", text: "believes：引出作者自己的判断" },
          { label: "宾语从句框架", text: "that Futurist poetry is：that 引出对诗歌性质的判断，表语由选项补足" },
        ],
        [
          "believe that... 后接宾语从句，that 从句中 Futurist poetry 作主语。",
          "is 后需要表语；四个选项都是形容词或名词短语，分别给出不同性质判断。",
        ],
        "作者认为未来主义诗歌是……",
        "作者认为未来主义诗歌究竟是什么性质？",
        "题目要求综合第2句、第9—12句和结尾的评价，区分作者承认的理论内核与否定的作品文学性。",
      ),
      options: {
        A: questionAnalysis(
          "p3-q22-option-a",
          22,
          "based on reasonable principles",
          [
            { text: "based", role: "predicate" },
            { text: " on reasonable principles", role: "modifier" },
          ],
          "be based on reasonable principles",
          [
            { label: "被动结构", text: "based on：过去分词后接 on，表示以……为依据" },
            { label: "依据内容", text: "reasonable principles：reasonable 修饰 principles，表示合理原则" },
          ],
          [
            "be based on + 名词表示‘以……为基础’，based 不能脱离 be 单独作完整谓语。",
            "reasonable principles 是介词 on 的宾语；作者只说 theory may be right，并未断言原则合理。",
          ],
          "建立在合理原则之上",
          "以合理的原则为基础",
          "该项把让步假设 may be right 提高为作者的确定判断，语气过强。",
        ),
        B: questionAnalysis(
          "p3-q22-option-b",
          22,
          "new and acceptable to ordinary people",
          [
            { text: "new and acceptable", role: "predicate" },
            { text: " to ordinary people", role: "modifier" },
          ],
          "be new and acceptable to ordinary people",
          [
            { label: "并列表语", text: "new and acceptable：and 连接‘新颖’与‘可接受’两个表语形容词" },
            { label: "对象介词", text: "to ordinary people：to 引出接受者，ordinary people 指普通人" },
          ],
          [
            "acceptable to + 人表示对某人可接受；to 在此引出评价对象而非方向终点。",
            "ordinary people 是泛指复数名词短语，原文没有提供普通人接受未来主义诗歌的证据。",
          ],
          "新颖且为普通人所接受",
          "既新颖又能被普通读者接受",
          "文章强调说明与诗行脱节、描写混乱，不能推出普通人普遍接受。",
        ),
        C: questionAnalysis(
          "p3-q22-option-c",
          22,
          "indicative of a basic change in human nature",
          [
            { text: "indicative", role: "predicate" },
            { text: " of a basic change in human nature", role: "modifier" },
          ],
          "be indicative of a basic change in human nature",
          [
            { label: "表语形容词", text: "indicative：表示‘表明……的’" },
            { label: "of 补足语", text: "of a basic change in human nature：说明被表明的内容是人性的根本变化" },
          ],
          [
            "indicative of + 名词表示‘表明……’，of 后接所指示的事实。",
            "human nature 指人性；作者结尾只是追问是否本质改变，并没有给出肯定结论。",
          ],
          "表明人性发生了根本变化",
          "说明人的本性已经发生根本改变",
          "该项把开放式追问和表达方式变化夸大为人性已改变的确定证据。",
        ),
        D: questionAnalysis(
          "p3-q22-option-d",
          22,
          "more of a transient phenomenon than literature",
          [
            { text: "more of a transient phenomenon", role: "predicate" },
            { text: " than literature", role: "modifier" },
          ],
          "be more of a transient phenomenon than literature",
          [
            { label: "比较分类", text: "more of A than B：与其说是 B，不如说更像 A" },
            { label: "A项内容", text: "a transient phenomenon：短暂现象；transient 表示不会长久" },
            { label: "B项参照", text: "than literature：than 引出与‘文学’这一类别的比较" },
          ],
          [
            "more of a/an + 名词 + than... 表示分类倾向，more 修饰 a transient phenomenon 而非比较数量。",
            "transient 是形容词，phenomenon 是可数名词；than 后 literature 作比较参照类别。",
          ],
          "与其说是文学，不如说更像一种短暂现象",
          "作者认为它只是短暂的文化现象，算不上真正的文学",
          "第2句的 hardly be classed as Literature 和第9—11句的混乱例子共同支持这一评价。",
        ),
      },
      answer: questionAnalysis(
        "p3-q22-answer",
        22,
        "The author believes that Futurist poetry is more of a transient phenomenon than literature.",
        [
          { text: "The author", role: "subject" },
          { text: " believes", role: "predicate" },
          { text: " that Futurist poetry is", role: "object" },
          { text: " more of a transient phenomenon than literature.", role: "modifier" },
        ],
        "The author believes that Futurist poetry is more of a transient phenomenon than literature.",
        [
          { label: "作者判断", text: "The author believes：主句明确标出这是作者的立场" },
          { label: "判断内容", text: "that Futurist poetry is：宾语从句的主语和系动词" },
          { label: "比较分类", text: "more of a transient phenomenon than literature：更像短暂现象，而非文学" },
        ],
        [
          "believes that 引出作者观点；is 后接 more of a transient phenomenon than literature 作表语。",
          "more of A than B 是比较分类结构，强调 A 的性质强于把对象归入 B。",
        ],
        "作者认为，未来主义诗歌与其说是文学，不如说更像一种短暂现象。",
        "在作者看来，未来主义诗歌更像短暂的文化现象，而很难称为文学。",
        "组合句同时保留作者的让步和批评：理论可能有合理处，但作品的短暂性和不可读性使其难称文学。",
      ),
    },
  },
];

function questionAnalysis(
  id: string,
  number: number,
  text: string,
  chunks: SentenceAnalysis["chunks"],
  trunk: string,
  layers: SentenceAnalysis["layers"],
  grammar: string[],
  literal: string,
  natural: string,
  logic: string,
  phrases: string[] = [],
): SentenceAnalysis {
  return { id, number, text, chunks, trunk, layers, grammar, literal, natural, logic, phrases };
}
