import type { PassageLexiconEntry } from "./passage-1-lexicon";

const structureForms = ["结构词：无普通词形变化，重点看句法位置"];

export const passage2LemmaAliases: Record<string, string> = {
  about: "about",
  amazed: "amaze",
  babies: "baby",
  being: "be",
  birth: "birth",
  births: "birth",
  bodies: "body",
  born: "born",
  boys: "boy",
  changed: "change",
  changes: "change",
  children: "child",
  cities: "city",
  compared: "compare",
  communities: "community",
  countries: "country",
  depended: "depend",
  differences: "difference",
  diminished: "diminish",
  disappearing: "disappear",
  declining: "decline",
  does: "do",
  drops: "drop",
  evolving: "evolve",
  females: "female",
  fills: "fill",
  following: "follow",
  genes: "gene",
  girls: "girl",
  going: "go",
  gone: "go",
  had: "have",
  happening: "happen",
  has: "have",
  improved: "improve",
  involved: "involve",
  is: "be",
  life: "life",
  lives: "life",
  looks: "look",
  lost: "lose",
  lower: "low",
  men: "man",
  makes: "make",
  male: "male",
  males: "male",
  man: "man",
  "man's": "man",
  "man’s": "man",
  mates: "mate",
  meant: "mean",
  means: "mean",
  offers: "offer",
  peoples: "people",
  reached: "reach",
  remaining: "remain",
  removed: "remove",
  searching: "search",
  shows: "show",
  smaller: "small",
  stopped: "stop",
  surviving: "survive",
  technological: "technological",
  transformed: "transform",
  tribes: "tribe",
  descendants: "descendant",
  places: "place",
  machines: "machine",
  argues: "argue",
  arrived: "arrive",
  did: "do",
  works: "work",
  continuing: "continue",
  us: "we",
  used: "use",
  were: "be",
  women: "woman",
  would: "will",
  "year-olds": "year-old",
  years: "year",
  "upper-middle": "upper-middle",
  "20th": "twentieth",
  s: "possessive-suffix",
  h: "ordinal-suffix",
};

export const passage2FamilyAliases: Record<string, string> = {
  amazed: "amaze",
  average: "average",
  biological: "biology",
  births: "birth",
  bodies: "body",
  born: "bear",
  changed: "change",
  children: "child",
  compared: "compare",
  defective: "defect",
  dangerous: "danger",
  differences: "difference",
  diminished: "diminish",
  disappearing: "disappear",
  evolving: "evolve",
  evolutionary: "evolution",
  female: "female",
  fertile: "fertility",
  improved: "improve",
  involved: "involve",
  mortality: "mortal",
  offspring: "offspring",
  population: "populate",
  poverty: "poor",
  survival: "survive",
  technological: "technology",
  transformed: "transform",
  ugliness: "ugly",
  variation: "vary",
  wealthy: "wealth",
};

export const passage2FormPartOfSpeech: Record<string, string> = {
  every: "det./pron.（每一个；每隔）",
  twice: "adv.（两倍；两次）",
  many: "det./pron.（许多；数量比较）",
  men: "n.（man 的不规则复数）",
  those: "det./pron.（那些；指示代词）",
  fifty: "numeral/adj.（五十；五十的）",
  ago: "adv.（以前；距今……前）",
  depended: "v.（depend 的过去式）",
  certain: "adj.（确定的）",
  agent: "n.（因素；代理人）",
  commit: "v.（实施；犯下）",
  suicide: "n.（自杀；自我毁灭）",
  stay: "v./n.（保持；停留）",
  fewer: "det./pron.（较少的，修饰可数名词复数）",
  except: "prep./conj.（除……之外）",
  very: "adv.（非常；很）",
  nowadays: "adv.（如今）",
  us: "pron.（we 的宾格）",
  same: "adj./pron.（相同的；同一个）",
  tribal: "adj.（部落的）",
  everyone: "pron.（每个人）",
  arrived: "v.-ed（arrive 的过去式/过去分词）",
  so: "adv./conj.（如此；因此）",
  places: "n.（复数）",
  even: "adv.（甚至；即使）",
  we: "pron.（第一人称复数主格）",
  did: "v./aux.（do 的过去式）",
  machines: "n.（复数）",
  phrase: "n.（短语；措辞）",
  something: "pron.（某事；某物）",
  wholly: "adv.（完全地）",
  however: "adv./conj.（然而；无论多么）",
  descendants: "n.（复数）",
  far: "adv./adj.（远；遥远的）",
  middle: "n./adj.（中间；中等的）",
  high: "adj./adv.（高的；高度地）",
  argues: "v.（第三人称单数）",
  technological: "adj.（技术的）",
  declining: "v.-ing/adj.（下降；正在减少的）",
  continuing: "v.-ing/adj.（继续；持续的）",
  amazed: "adj./v.-ed（感到惊讶的）",
  being: "v.-ing / gerund（be 的现在分词或动名词）",
  babies: "n.（复数）",
  births: "n.（复数）",
  bodies: "n.（复数）",
  born: "v.-ed/adj.（bear 的过去分词）",
  boys: "n.（复数）",
  changed: "v.-ed/adj.（过去式或过去分词）",
  changes: "n.（复数）/v.（第三人称单数）",
  children: "n.（复数）",
  cities: "n.（复数，y → ies）",
  compared: "v.-ed（过去分词）",
  communities: "n.（复数）",
  countries: "n.（复数，y → ies）",
  differences: "n.（复数）",
  diminished: "v.-ed（过去式或过去分词）",
  disappearing: "v.-ing（现在分词）",
  does: "v./aux.（do 的第三人称单数）",
  drops: "v.（第三人称单数）",
  evolving: "v.-ing（现在分词）",
  females: "n.（复数）",
  fills: "v.（第三人称单数）",
  following: "adj./v.-ing（后续的；跟随）",
  genes: "n.（复数）",
  girls: "n.（复数）",
  going: "v.-ing（现在分词）",
  gone: "v.-ed（go 的过去分词）",
  had: "v./aux.（have 的过去式）",
  happening: "v.-ing（现在分词）",
  has: "v./aux.（第三人称单数）",
  improved: "v.-ed/adj.（过去式、过去分词或形容词）",
  involved: "v.-ed（过去式或过去分词）",
  is: "v./aux.（be 的第三人称单数）",
  lives: "n.（复数）",
  looks: "v.（第三人称单数）",
  lost: "v.-ed（lose 的过去式或过去分词）",
  lower: "adj.（比较级）",
  makes: "v.（第三人称单数）",
  males: "n.（复数）",
  mates: "n.（复数）",
  meant: "v.（mean 的过去式或过去分词）",
  means: "v.（第三人称单数）",
  offers: "v.（第三人称单数）",
  peoples: "n.（复数，多个民族）",
  reached: "v.-ed（过去式或过去分词）",
  remaining: "adj./v.-ing（剩余的）",
  removed: "v.-ed（过去分词）",
  searching: "v.-ing（现在分词）",
  shows: "v.（第三人称单数）",
  smaller: "adj.（比较级）",
  stopped: "v.-ed（过去式或过去分词）",
  surviving: "v.-ing（动名词或现在分词）",
  transformed: "v.-ed（过去分词）",
  tribes: "n.（复数）",
  used: "v.-ed/adj.（过去式、过去分词或形容词）",
  were: "v./aux.（be 的过去时复数）",
  women: "n.（woman 的复数）",
  works: "v.（第三人称单数）",
  would: "modal v.（will 的过去式或委婉形式）",
  "year-olds": "n.（复合名词复数）",
  years: "n.（复数）",
  "man's": "n.（名词所有格）",
  "man’s": "n.（名词所有格）",
};

type Extra = Partial<Pick<PassageLexiconEntry, "specialForms" | "examSynonyms" | "collocations" | "otherMeanings" | "wordFamily" | "confusions">>;

const makeEntry = (
  headword: string,
  partOfSpeech: string,
  contextualMeaning: string,
  use: string,
  extra: Extra = {},
): PassageLexiconEntry => ({
  partOfSpeech,
  contextualMeaning,
  use,
  specialForms: extra.specialForms ?? [`${headword}（本句词形；按语境判断词性）`],
  examSynonyms: extra.examSynonyms ?? [`${headword} 的近义表达需根据本句语义选择`],
  collocations: extra.collocations ?? [],
  otherMeanings: extra.otherMeanings ?? [],
  wordFamily: extra.wordFamily ?? [],
  confusions: extra.confusions ?? [],
});

export const passage2Lexicon: Record<string, PassageLexiconEntry> = {
  about: makeEntry("about", "prep./adv.", "大约；关于", "about 105 males 表示数量约为105；about + 名词也可表示“关于”。", { specialForms: structureForms, examSynonyms: ["approximately（大约）", "concerning（关于）"] }),
  according: makeEntry("according", "prep. phrase component", "根据", "according to the first paragraph 引出信息来源。", { specialForms: structureForms, examSynonyms: ["based on（依据）"], collocations: ["according to"] }),
  advance: makeEntry("advance", "n./v.", "进步；推进", "technological advance 指技术进步，是题目选项中的原因。", { specialForms: ["advance—advances（名词复数）；advance—advanced—advanced（动词）"], examSynonyms: ["progress（进步）", "development（发展）"] }),
  advantage: makeEntry("advantage", "n.", "优势；有利条件", "take advantage of 表示利用机会或条件。", { specialForms: ["advantage—advantages（复数）"], examSynonyms: ["benefit（益处）", "benefit（使受益）"], collocations: ["take advantage of"] }),
  again: makeEntry("again", "adv.", "再次；重新", "Again 放在句首，表示回到前面已经提出的结论。", { specialForms: structureForms, examSynonyms: ["once more（再次）", "anew（重新）"] }),
  amaze: makeEntry("amaze", "v.", "使惊讶", "be amazed at 表示对某事感到惊讶；amazed 是过去分词形容词。", { specialForms: ["amaze—amazes—amazed—amazing"], examSynonyms: ["surprise（使惊讶）", "astonish（使震惊）"], collocations: ["however amazed our descendants may be at"] }),
  alive: makeEntry("alive", "adj.", "活着的", "stay alive 中 alive 作表语形容词。", { specialForms: ["alive（表语形容词，无普通比较级）"], examSynonyms: ["living（活着的）", "live（活的；直播的）"] }),
  almost: makeEntry("almost", "adv.", "几乎；差不多", "almost 修饰数量、程度或比较结构，如 almost no difference。", { specialForms: structureForms, examSynonyms: ["nearly（几乎）", "practically（几乎）"] }),
  always: makeEntry("always", "adv.", "总是；一直", "has always been 中 always 放在助动词 has 后，强调长期持续。", { specialForms: structureForms, examSynonyms: ["continually（持续地）", "consistently（始终如一地）"] }),
  among: makeEntry("among", "prep.", "在……之中", "among 70-year-olds 表示在这一群体内部进行比较。", { specialForms: structureForms, examSynonyms: ["amid（在……之中）", "in（在……中）"] }),
  argue: makeEntry("argue", "v.", "论证；主张", "The author argues that 引出作者明确提出的因果判断。", { specialForms: ["argue—argues—argued—arguing"], examSynonyms: ["claim（声称）", "maintain（坚持认为）"] }),
  arrive: makeEntry("arrive", "v.", "到达；到来", "has arrived 表示某种状态或时代已经到来。", { specialForms: ["arrive—arrives—arrived—arriving"], examSynonyms: ["reach（到达）", "come（到来）"] }),
  author: makeEntry("author", "n.", "作者", "题干中的 The author 指文章作者，而非文中被提到的人。", { specialForms: ["author—authors（复数）；author—authored—authored（动词）"], examSynonyms: ["writer（作者）", "proponent（主张者）"] }),
  average: makeEntry("average", "adj./n./v.", "平均的；平均数；使平均", "has become average 表示趋于平均化。", { specialForms: ["average—averages（复数/第三人称单数）；averaged—averaging"], examSynonyms: ["mean（平均的；平均数）", "ordinary（普通的）"] }),
  baby: makeEntry("baby", "n.", "婴儿", "boy baby / baby surviving 中 baby 是可数名词。", { specialForms: ["baby—babies（y → ies）"], examSynonyms: ["infant（婴儿；较正式）", "newborn（新生儿）"] }),
  balance: makeEntry("balance", "n./v.", "平衡；使平衡", "near balance 表示男女比例接近平衡状态。", { specialForms: ["balance—balances（复数/第三人称单数）；balanced—balancing"], examSynonyms: ["equilibrium（平衡）", "stability（稳定）"] }),
  biological: makeEntry("biological", "adj.", "生物学的", "biological Utopia 是带有反讽色彩的“生物学乌托邦”。", { specialForms: ["biological（形容词）"], examSynonyms: ["organic（生物的；有机的）", "life-science（生命科学的）"], wordFamily: ["biology n. 生物学", "biologist n. 生物学家"] }),
  birth: makeEntry("birth", "n.", "出生；出生事件", "births 与 death 并列，构成出生和死亡的统计对照。", { specialForms: ["birth—births（复数）"], examSynonyms: ["delivery（分娩；出生）", "origin（起源）"], collocations: ["birth rate"] }),
  body: makeEntry("body", "n.", "身体；主体", "our bodies 与 our lives 对比，强调身体没有随生活改变。", { specialForms: ["body—bodies（y → ies）"], examSynonyms: ["physique（体格）", "organism（有机体）"] }),
  born: makeEntry("born", "v.-ed/adj.", "出生的；诞生的", "males born for every 100 females 中 born 是后置分词，修饰 males。", { specialForms: ["bear—bore—born/borne—bearing"], examSynonyms: ["given birth（出生的）", "native（本土出生的）"] }),
  boy: makeEntry("boy", "n.", "男孩", "boy babies、excess of boys 指男婴或男孩群体。", { specialForms: ["boy—boys（复数）"], examSynonyms: ["male child（男孩）", "lad（男孩；口语）"] }),
  century: makeEntry("century", "n.", "世纪", "20th century 表示二十世纪。", { specialForms: ["century—centuries（y → ies）"], examSynonyms: ["hundred-year period（百年时期）"] }),
  chance: makeEntry("chance", "n./v.", "机会；可能性", "the chance of a baby surviving 表示婴儿存活的可能性。", { specialForms: ["chance—chances（复数）；chanced—chancing"], examSynonyms: ["possibility（可能性）", "opportunity（机会）"], collocations: ["the chance of a baby (particularly a boy baby) surviving"] }),
  change: makeEntry("change", "n./v.", "改变；变化", "is being changed、differences have changed 等结构中表示状态变化。", { specialForms: ["change—changes—changed—changing"], examSynonyms: ["alter（改变）", "modify（修改）"] }),
  child: makeEntry("child", "n.", "孩子", "children 是 child 的不规则复数；have children 在本篇表示生育。", { specialForms: ["child—children（不规则复数）"], examSynonyms: ["offspring（后代）", "youngster（孩子）"] }),
  city: makeEntry("city", "n.", "城市", "great cities 与 tribal peoples 构成社会阶层和地域对照。", { specialForms: ["city—cities（y → ies）"], examSynonyms: ["urban center（城市中心）", "town（城镇；规模较小）"] }),
  class: makeEntry("class", "n./v.", "阶层；类别；把……分类", "upper-middle-class 中 class 是社会阶层名词。", { specialForms: ["class—classes（复数）；classed—classing"], examSynonyms: ["social group（社会群体）", "category（类别）"] }),
  compare: makeEntry("compare", "v.", "比较", "compared to the tribes 是过去分词短语，说明比较基准。", { specialForms: ["compare—compares—compared—comparing"], examSynonyms: ["contrast（对比）", "liken（把……比作）"], collocations: ["compared to"] }),
  community: makeEntry("community", "n.", "社群；社区", "religious communities 指具有共同信仰的群体。", { specialForms: ["community—communities（y → ies）"], examSynonyms: ["group（群体）", "society（社会）"] }),
  competition: makeEntry("competition", "n.", "竞争；竞赛", "competition 是自然选择发生的背景，不是题15所问的具体危险。", { specialForms: ["competition（通常不可数；具体比赛可数）"], examSynonyms: ["rivalry（竞争）", "contest（竞赛）"] }),
  comprehension: makeEntry("comprehension", "n.", "理解；理解力", "beyond his comprehension 表示超出他的理解能力。", { specialForms: ["comprehension（通常不可数）"], examSynonyms: ["understanding（理解）", "grasp（理解力）"], collocations: ["beyond his comprehension", "beyond comprehension"] }),
  crucial: makeEntry("crucial", "adj.", "关键的", "crucial years 指寻找配偶的关键年龄段。", { specialForms: ["crucial—more crucial—most crucial"], examSynonyms: ["critical（关键的）", "vital（至关重要的）"] }),
  danger: makeEntry("danger", "n.", "危险", "题15问 danger，答案要回指过去男婴较低的存活率。", { specialForms: ["danger—dangers（复数）"], examSynonyms: ["risk（风险）", "hazard（危险因素）"] }),
  dangerous: makeEntry("dangerous", "adj.", "危险的", "Being a man has always been dangerous 中作表语。", { specialForms: ["dangerous—more dangerous—most dangerous"], examSynonyms: ["risky（有风险的）", "hazardous（危险的）"], wordFamily: ["danger n. 危险"] }),
  darwin: makeEntry("darwin", "proper n.", "达尔文", "Darwin 是提出进化论的科学家姓名。", { specialForms: ["Darwin（专有名词）"], examSynonyms: ["Charles Darwin（查尔斯·达尔文）"] }),
  death: makeEntry("death", "n.", "死亡", "almost certain death 表示几乎确定的死亡结果。", { specialForms: ["death（不可数抽象名词；具体死亡事件可数）"], examSynonyms: ["demise（死亡；正式）", "fatality（死亡事件）"] }),
  defective: makeEntry("defective", "adj.", "有缺陷的", "defective gene 是干扰项，原文只说基因造成体重差异，未说是缺陷基因。", { specialForms: ["defective（形容词）"], examSynonyms: ["faulty（有故障的）", "flawed（有缺陷的）"], wordFamily: ["defect n. 缺陷", "defect v. 背叛"] }),
  descendant: makeEntry("descendant", "n.", "后代；后裔", "descendants 指未来的人类后代。", { specialForms: ["descendant—descendants（复数）"], examSynonyms: ["offspring（后代）", "successor（继承者）"] }),
  describe: makeEntry("describe", "v.", "描述", "a phrase to describe those ignorant of evolution 中 describe 接宾语。", { specialForms: ["describe—describes—described—describing"], examSynonyms: ["portray（描绘）", "characterize（刻画）"] }),
  difference: makeEntry("difference", "n.", "差别；影响", "make almost no difference 表示几乎不造成影响；differences between people 指人与人之间的差异。", { specialForms: ["difference—differences（复数）"], examSynonyms: ["distinction（区别）", "impact（影响；make a difference 语境）"], collocations: ["makes almost no difference", "the same in"] }),
  diminish: makeEntry("diminish", "v.", "减少；减弱", "have diminished 表示自然选择机会已经减少。", { specialForms: ["diminish—diminishes—diminished—diminishing"], examSynonyms: ["decrease（减少）", "weaken（削弱）"] }),
  disappear: makeEntry("disappear", "v.", "消失", "disappearing 是题目选项中的现在分词，表示逐渐消失。", { specialForms: ["disappear—disappears—disappeared—disappearing"], examSynonyms: ["vanish（消失）", "die out（灭绝；消失）"] }),
  do: makeEntry("do", "v./aux.", "做；代替前面动词", "girls do 中 do 代替 survive；did it for us 中 did 代替 evolve。", { specialForms: ["do—does—did—done—doing"], examSynonyms: ["perform（做；执行）", "carry out（执行）"] }),
  doubt: makeEntry("doubt", "n./v.", "怀疑；疑问", "No doubt 是句子副词，表示毫无疑问。", { specialForms: ["doubt—doubts—doubted—doubting"], examSynonyms: ["uncertainty（不确定）", "question（怀疑；质疑）"], collocations: ["no doubt"] }),
  drop: makeEntry("drop", "v./n.", "下降；下降幅度", "drops to near balance 中 drop to 后接变化终点。", { specialForms: ["drop—drops—dropped—dropping"], examSynonyms: ["fall（下降）", "decline（下降；衰退）"], collocations: ["drops to near balance"] }),
  due: makeEntry("due", "adj.", "由于；预定的", "is due to genes 中 due to 引出原因。", { specialForms: ["due（形容词；比较级通常不用）"], examSynonyms: ["caused by（由……造成）", "attributable to（归因于）"], collocations: ["is due to"] }),
  evolution: makeEntry("evolution", "n.", "进化；演变", "natural selection、agent of evolution 和 evolution is over 构成全文核心概念链。", { specialForms: ["evolution（通常不可数）"], examSynonyms: ["development（发展）", "transformation（演变）"], wordFamily: ["evolve v. 进化", "evolutionary adj. 进化的"], collocations: ["agent of evolution", "evolution is over"] }),
  evolutionary: makeEntry("evolutionary", "adj.", "进化的", "evolutionary suicide 表示进化意义上的自我毁灭。", { specialForms: ["evolutionary（形容词）"], examSynonyms: ["evolutive（进化的；少用）", "developmental（发展的）"], wordFamily: ["evolution n. 进化", "evolve v. 进化"], collocations: ["commit evolutionary suicide"] }),
  evolve: makeEntry("evolve", "v.", "进化；逐渐发展", "did not evolve 中 evolve 是动词原形；evolving 是选项中的现在分词。", { specialForms: ["evolve—evolves—evolved—evolving"], examSynonyms: ["develop（发展）", "adapt（适应）"] }),
  example: makeEntry("example", "n.", "例子；实例", "the example of India 指印度这一具体案例。", { specialForms: ["example—examples（复数）"], examSynonyms: ["instance（例子）", "case（案例）"] }),
  excess: makeEntry("excess", "n./adj.", "过量；过剩", "an excess of boys 表示男孩数量过多。", { specialForms: ["excess—excesses（复数）；excessive（形容词）"], examSynonyms: ["surplus（盈余）", "overabundance（过多）"], collocations: ["an excess of"] }),
  female: makeEntry("female", "n./adj.", "女性；雌性的", "females 与 males 构成出生性别比例对照。", { specialForms: ["female—females（复数）"], examSynonyms: ["woman（成年女性）", "feminine（女性的）"] }),
  fertile: makeEntry("fertile", "adj.", "有生育力的；肥沃的", "as fertile as in the past 表示像过去一样具有生育力。", { specialForms: ["fertile—more fertile—most fertile"], examSynonyms: ["productive（多产的）", "fruitful（有成果的）"], collocations: ["as fertile as"] }),
  fierce: makeEntry("fierce", "adj.", "激烈的；凶猛的", "fierce competition 是题15的干扰项；原文没有把男性危险定义为竞争激烈。", { specialForms: ["fierce—fiercer—fiercest"], examSynonyms: ["intense（激烈的）", "violent（猛烈的）"] }),
  fill: makeEntry("fill", "v.", "填满；占据", "fills so many places in nature 表示占据自然界许多生态位置。", { specialForms: ["fill—fills—filled—filling"], examSynonyms: ["occupy（占据）", "complete（填满；完成）"] }),
  first: makeEntry("first", "adj./adv./n.", "第一的；首次", "for the first time 是固定时间短语。", { specialForms: ["first（序数词；无普通比较级）"], examSynonyms: ["initial（最初的）", "foremost（首要的；最重要的）"] }),
  follow: makeEntry("follow", "v./n.", "跟随；接着", "following 可作形容词，表示后续的；题目中的 following 指下列。", { specialForms: ["follow—follows—followed—following"], examSynonyms: ["succeed（接着发生）", "pursue（追随）"] }),
  for: makeEntry("for", "prep./conj.", "对于；为了；每……对应", "for every、for the first time、for us 等结构中含义不同，需看搭配。", { specialForms: structureForms, examSynonyms: ["in order to（为了）", "because（因为；部分语境）"], collocations: ["for every", "for the first time", "for us"] }),
  future: makeEntry("future", "n./adj.", "未来；未来的", "The evolutionary future 是选项标题中的未来概念。", { specialForms: ["future—futures（复数）；future（形容词）"], examSynonyms: ["coming time（未来）", "prospective（未来的）"] }),
  gene: makeEntry("gene", "n.", "基因", "genes 是 variation 的原因之一，影响体重等性状。", { specialForms: ["gene—genes（复数）"], examSynonyms: ["genetic unit（遗传单位）", "hereditary factor（遗传因素）"] }),
  girl: makeEntry("girl", "n.", "女孩", "girls do 中 girls 是比较对象，do 代替 survive。", { specialForms: ["girl—girls（复数）"], examSynonyms: ["female child（女孩）", "young woman（年轻女性）"] }),
  go: makeEntry("go", "v.", "走；消失；进行", "has gone 中 gone 表示作用因素已经消失，不是离开地点。", { specialForms: ["go—goes—went—gone—going"], examSynonyms: ["disappear（消失；语境义）", "proceed（进行）"] }),
  grand: makeEntry("grand", "adj.", "宏大的；总体的", "grand mediocrity 是作者对平均化现象的概括性命名。", { specialForms: ["grand—grander—grandest"], examSynonyms: ["overall（总体的）", "magnificent（宏大的）"] }),
  great: makeEntry("great", "adj.", "伟大的；巨大的", "the great universal 中 great 带有强调和概括色彩。", { specialForms: ["great—greater—greatest"], examSynonyms: ["major（重大的）", "large（大的）"] }),
  happen: makeEntry("happen", "v.", "发生", "what is happening 是 what 引导的宾语从句。", { specialForms: ["happen—happens—happened—happening"], examSynonyms: ["occur（发生；正式）", "take place（发生）"] }),
  hard: makeEntry("hard", "adv./adj.", "努力地；困难的；坚硬的", "hardly works 中 hardly 不是 hard 的普通比较形式，而是“几乎不”。", { specialForms: ["hard—harder—hardest；hardly（副词派生）"], examSynonyms: ["difficult（困难的）", "firm（坚硬的）"] }),
  hardly: makeEntry("hardly", "adv.", "几乎不", "hardly works 表示自然选择几乎不起作用。", { specialForms: structureForms, examSynonyms: ["scarcely（几乎不）", "barely（勉强；几乎不）"] }),
  heavy: makeEntry("heavy", "adj.", "重的；沉重的", "too heavy 表示体重超过适宜范围。", { specialForms: ["heavy—heavier—heaviest"], examSynonyms: ["weighty（重的）", "substantial（分量大的）"] }),
  highest: makeEntry("high", "adj./adv.", "最高的；高的", "highest stage 是题目选项中夸大的进化阶段说法。", { specialForms: ["high—higher—highest"], examSynonyms: ["top（最高的）", "greatest（最大的）"] }),
  human: makeEntry("human", "n./adj.", "人类；人的", "Human Evolution 是题目标题中的人类进化。", { specialForms: ["human—humans（复数）"], examSynonyms: ["humankind（人类）", "anthropological（人类学的）"] }),
  ignorant: makeEntry("ignorant", "adj.", "无知的；不了解的", "those ignorant of evolution 中 ignorant 后接 of 引出不了解的对象。", { specialForms: ["ignorant—more ignorant—most ignorant"], examSynonyms: ["unaware（不了解的）", "uninformed（信息不足的）"], collocations: ["ignorant of"] }),
  illustrate: makeEntry("illustrate", "v.", "说明；阐明", "What does the example of India illustrate? 问该例子说明什么。", { specialForms: ["illustrate—illustrates—illustrated—illustrating"], examSynonyms: ["demonstrate（说明）", "exemplify（举例说明）"] }),
  important: makeEntry("important", "adj.", "重要的", "More important 是句首评价语，指出下一个论点更关键。", { specialForms: ["important—more important—most important"], examSynonyms: ["significant（重要的）", "crucial（关键的）"] }),
  india: makeEntry("india", "proper n.", "印度", "India 段落用阶层和部落群体对比说明自然选择作用减弱。", { specialForms: ["India（专有名词）"], examSynonyms: ["the Republic of India（印度共和国）"] }),
  involve: makeEntry("involve", "v.", "涉及；包含", "has involved little physical change 表示只涉及很少身体变化。", { specialForms: ["involve—involves—involved—involving"], examSynonyms: ["include（包括）", "entail（意味着；需要）"] }),
  just: makeEntry("just", "adv./adj.", "正好；仅仅；完全", "look just like 中 just 加强相似程度。", { specialForms: ["just（副词/形容词）"], examSynonyms: ["exactly（正好）", "simply（仅仅）"], collocations: ["look just like"] }),
  kilogram: makeEntry("kilogram", "n.", "千克；公斤", "A kilogram too light or too heavy 用一公斤偏差说明过去的严格筛选。", { specialForms: ["kilogram—kilograms（复数）"], examSynonyms: ["kilo（公斤；口语）", "unit of mass（质量单位）"] }),
  lack: makeEntry("lack", "n./v.", "缺乏；不足", "A lack of mates 是题15选项，原文并未把男性危险归结为缺少配偶。", { specialForms: ["lack—lacks—lacked—lacking"], examSynonyms: ["shortage（缺乏）", "absence（缺少）"] }),
  life: makeEntry("life", "n.", "生命；生活", "our lives have been transformed 中 life 指生活方式和生活条件。", { specialForms: ["life—lives（不规则复数）"], examSynonyms: ["existence（生命；存在）", "lifestyle（生活方式）"], collocations: ["way of life"] }),
  light: makeEntry("light", "adj./n./v.", "轻的；光；点燃", "too light 与 too heavy 对举，指出生体重偏轻或偏重。", { specialForms: ["light—lighter—lightest；light—lit/lighted—lit/lighted"], examSynonyms: ["underweight（体重过轻的）", "bright（明亮的）"] }),
  like: makeEntry("like", "prep./conj./v.", "像；喜欢", "like the age of death 中 like 是介词；look just like 表示外貌相似。", { specialForms: ["like—likes—liked—liking"], examSynonyms: ["similar to（像）", "such as（例如；不同结构）"], collocations: ["look just like"] }),
  little: makeEntry("little", "det./adj./adv.", "少量的；小的", "little physical change 中 little 修饰不可数名词，表示很少。", { specialForms: ["little—less—least"], examSynonyms: ["small（小的）", "slight（轻微的）"] }),
  look: makeEntry("look", "v./n.", "看；看起来", "look at A as B 表示把 A 看作 B；look just like 表示看起来像。", { specialForms: ["look—looks—looked—looking"], examSynonyms: ["seem（看起来）", "regard（看待）"], collocations: ["look at", "look at an organic being as", "look just like"] }),
  lose: makeEntry("lose", "v.", "失去；丢失", "has lost 80% of its power 中 lost 表示能力减少。", { specialForms: ["lose—lost—lost—losing"], examSynonyms: ["forfeit（丧失）", "misplace（遗失具体物品）"] }),
  low: makeEntry("low", "adj./adv.", "低的", "lower survival rate 是比较级结构，表示存活率较低。", { specialForms: ["low—lower—lowest"], examSynonyms: ["reduced（降低的）", "small（低的；数量少）"] }),
  male: makeEntry("male", "n./adj.", "男性；雄性的", "male mortality、males born 与 female 形成性别对照。", { specialForms: ["male—males（复数）"], examSynonyms: ["man（成年男性）", "masculine（男性的）"], collocations: ["male mortality"] }),
  man: makeEntry("man", "n.", "男性；人类", "being a man 和 Man’s Evolution 中 man 分别指男性和人类整体。", { specialForms: ["man—men（不规则复数）；man's/man’s（所有格）"], examSynonyms: ["male（男性）", "human being（人类）"] }),
  mate: makeEntry("mate", "n./v.", "配偶；交配伙伴", "searching for a mate 指寻找配偶。", { specialForms: ["mate—mates（复数）；mated—mating"], examSynonyms: ["partner（伴侣）", "spouse（配偶；正式）"], collocations: ["searching for a mate"] }),
  maturity: makeEntry("maturity", "n.", "成熟；成熟年龄", "at the age of maturity 指达到成熟年龄。", { specialForms: ["maturity（通常不可数）"], examSynonyms: ["adulthood（成年）", "ripeness（成熟）"], collocations: ["at the age of maturity"] }),
  mean: makeEntry("mean", "v./adj./n.", "意味着；平均的；意思", "means that 引出结果；meant death 表示导致某后果。", { specialForms: ["mean—means—meant—meaning"], examSynonyms: ["signify（意味着）", "intend（意图）"] }),
  mediocrity: makeEntry("mediocrity", "n.", "平庸；平均化", "grand mediocrity 指人人在生存和后代数量上趋同的平均化。", { specialForms: ["mediocrity—mediocrities（复数）"], examSynonyms: ["averageness（平均状态）", "ordinariness（普通）"] }),
  mortality: makeEntry("mortality", "n.", "死亡率；死亡现象", "male mortality 是男性死亡率这一统计概念。", { specialForms: ["mortality（通常不可数）"], examSynonyms: ["death rate（死亡率）", "fatality（死亡率；死亡事件）"], collocations: ["male mortality"] }),
  natural: makeEntry("natural", "adj.", "自然的", "natural selection 指不依赖人为安排的选择过程。", { specialForms: ["natural—more natural—most natural"], examSynonyms: ["innate（先天的）", "organic（自然的；有机的）"], collocations: ["natural selection"] }),
  nature: makeEntry("nature", "n.", "自然；本性", "places in nature 指自然界中的生态位置。", { specialForms: ["nature（通常不可数；性质义可数）"], examSynonyms: ["the natural world（自然界）", "character（本性）"] }),
  near: makeEntry("near", "prep./adj./adv.", "接近；附近的", "near balance 表示接近平衡，而不是完全相等。", { specialForms: ["near—nearer—nearest"], examSynonyms: ["close to（接近）", "almost（几乎）"], collocations: ["drops to near balance"] }),
  nowhere: makeEntry("nowhere", "adv.", "无处；任何地方都不", "Human Evolution Going Nowhere 中 nowhere 是标题的比喻表达，指没有进展。", { specialForms: structureForms, examSynonyms: ["in no place（无处）", "without progress（没有进展）"] }),
  number: makeEntry("number", "n./v.", "数量；编号", "the number of births 作主语时谓语用单数。", { specialForms: ["number—numbers（复数）；numbered—numbering"], examSynonyms: ["quantity（数量）", "figure（数字）"], collocations: ["the number of", "roughly the same number of offspring"] }),
  offspring: makeEntry("offspring", "n.", "后代", "offspring 单复数同形，指一个或多个后代。", { specialForms: ["offspring（单复数同形）"], examSynonyms: ["children（孩子；后代）", "descendants（后代）"], collocations: ["roughly the same number of offspring"] }),
  opportunity: makeEntry("opportunity", "n.", "机会", "the opportunity for natural selection 表示自然选择发挥作用的机会。", { specialForms: ["opportunity—opportunities（y → ies）"], examSynonyms: ["chance（机会）", "opening（机会；空缺）"] }),
  organic: makeEntry("organic", "adj./n.", "有机的；有机体的", "an organic being 指有机体；不是食品标签语境中的“有机”。", { specialForms: ["organic—more organic—most organic"], examSynonyms: ["biological（生物的）", "living（有生命的）"] }),
  paragraph: makeEntry("paragraph", "n.", "段落", "according to the first paragraph 要求根据第一段寻找答案。", { specialForms: ["paragraph—paragraphs（复数）"], examSynonyms: ["section（部分）", "passage section（文章段落）"] }),
  particularly: makeEntry("particularly", "adv.", "尤其；特别", "particularly a boy baby 是插入语，强调男婴。", { specialForms: ["particularly（副词）"], examSynonyms: ["especially（尤其）", "specifically（具体地）"] }),
  passage: makeEntry("passage", "n.", "文章；段落；通道", "the passage 指整篇阅读文章，题目18询问最佳标题。", { specialForms: ["passage—passages（复数）"], examSynonyms: ["article（文章）", "text（文本）"] }),
  past: makeEntry("past", "n./adj./prep.", "过去；过去的；经过", "in the past 100, 000 years 表示过去的一段时间。", { specialForms: ["past（无普通变形）"], examSynonyms: ["former（过去的）", "previous（先前的）"], collocations: ["in the past 100, 000 years"] }),
  people: makeEntry("people", "n.", "人们；民族", "people 可指人们；peoples 指多个民族，需由语境区分。", { specialForms: ["person—people（不规则复数）；people—peoples（多个民族）"], examSynonyms: ["persons（人们；正式）", "population（人口）"] }),
  physical: makeEntry("physical", "adj.", "身体的；物理的", "physical change 指身体层面的变化。", { specialForms: ["physical—more physical—most physical"], examSynonyms: ["bodily（身体的）", "material（物质的）"] }),
  place: makeEntry("place", "n./v.", "地方；位置；放置", "places in nature 指生态位置或生态位。", { specialForms: ["place—places—placed—placing"], examSynonyms: ["location（地点）", "position（位置）"] }),
  poor: makeEntry("poor", "adj.", "贫穷的；差的", "poor people 与 wealthy people 构成题16选项对比。", { specialForms: ["poor—poorer—poorest"], examSynonyms: ["impoverished（贫困的）", "needy（贫困的）"] }),
  population: makeEntry("population", "n.", "人口；种群", "middle class population 是选项中的人口表达，但原文比较的是自然选择作用而非人口规模。", { specialForms: ["population—populations（复数）"], examSynonyms: ["inhabitants（居民）", "species group（种群）"] }),
  poverty: makeEntry("poverty", "n.", "贫困", "poverty for the remaining tribal peoples 与 wealth for a few 对举。", { specialForms: ["poverty（通常不可数）"], examSynonyms: ["indigence（贫困；正式）", "deprivation（匮乏）"] }),
  power: makeEntry("power", "n./v.", "力量；能力；供能", "natural selection has lost 80% of its power 指作用能力下降。", { specialForms: ["power—powers（复数）；powered—powering"], examSynonyms: ["strength（力量）", "capacity（能力）"] }),
  rate: makeEntry("rate", "n./v.", "比率；速度；评价", "survival rate 是存活率，题15答案 lower survival rate。", { specialForms: ["rate—rates—rated—rating"], examSynonyms: ["ratio（比率；侧重两量关系）", "level（水平）"] }),
  ratio: makeEntry("ratio", "n.", "比率；比例", "this ratio 指男性与女性出生人数的比例。", { specialForms: ["ratio—ratios（复数）"], examSynonyms: ["proportion（比例）", "relationship（关系）"] }),
  reach: makeEntry("reach", "v./n.", "达到；到达", "has reached the highest stage 是题目选项中的夸张说法。", { specialForms: ["reach—reaches—reached—reaching"], examSynonyms: ["attain（达到）", "arrive at（达到；到达）"] }),
  remain: makeEntry("remain", "v./n.", "仍然；留下", "remaining tribal peoples 中 remaining 表示剩余的部落民族。", { specialForms: ["remain—remains—remained—remaining"], examSynonyms: ["stay（保持）", "be left（剩下）"] }),
  remove: makeEntry("remove", "v.", "移除；消除", "has been removed 表示自然选择的机会已经消失。", { specialForms: ["remove—removes—removed—removing"], examSynonyms: ["eliminate（消除）", "take away（拿走）"] }),
  remember: makeEntry("remember", "v.", "记得；记住", "we will remember a way of life 表示后人会记住这一生活方式。", { specialForms: ["remember—remembers—remembered—remembering"], examSynonyms: ["recall（回忆）", "retain（记住；保留）"] }),
  religious: makeEntry("religious", "adj.", "宗教的", "religious communities 是高生育率例外群体。", { specialForms: ["religious—more religious—most religious"], examSynonyms: ["faith-based（以信仰为基础的）", "devout（虔诚的）"] }),
  rich: makeEntry("rich", "adj.", "富裕的；丰富的", "rich people 与 poor people 形成阶层对照。", { specialForms: ["rich—richer—richest"], examSynonyms: ["wealthy（富裕的）", "affluent（富裕的；正式）"] }),
  roughly: makeEntry("roughly", "adv.", "大致；粗略地", "roughly the same number 表示数量大致相同。", { specialForms: ["roughly（副词）"], examSynonyms: ["approximately（大约）", "about（大约）"], collocations: ["roughly the same number of offspring"] }),
  savage: makeEntry("savage", "n./adj.", "野蛮人；野蛮的", "a savage looks at a ship 是达尔文比喻中的比较对象。", { specialForms: ["savage—savages（复数）；savage—savaged—savaging"], examSynonyms: ["primitive person（原始人）", "brutal（野蛮的）"] }),
  search: makeEntry("search", "v./n.", "寻找；搜索", "searching for a mate 中 search for 后接寻找对象。", { specialForms: ["search—searches—searched—searching"], examSynonyms: ["seek（寻找）", "look for（寻找）"], collocations: ["searching for a mate"] }),
  selection: makeEntry("selection", "n.", "选择；筛选", "natural selection 是进化论中的筛选机制。", { specialForms: ["selection—selections（复数）"], examSynonyms: ["choice（选择）", "screening（筛选）"], collocations: ["natural selection"] }),
  sex: makeEntry("sex", "n./v.", "性别；性行为", "Sex Ratio Changes 是题目选项标题，sex 在此指生物性别。", { specialForms: ["sex—sexes（复数）；sexed—sexing"], examSynonyms: ["gender（性别；社会语境）", "biological sex（生物性别）"] }),
  ship: makeEntry("ship", "n./v.", "船；运输", "a savage looks at a ship 是达尔文比喻中的船。", { specialForms: ["ship—ships—shipped—shipping"], examSynonyms: ["vessel（船只）", "boat（船；较小）"] }),
  show: makeEntry("show", "v./n.", "显示；表明", "India shows what is happening 中 show 后接 what 宾语从句。", { specialForms: ["show—shows—showed—shown/showed—showing"], examSynonyms: ["demonstrate（表明）", "reveal（揭示）"] }),
  small: makeEntry("small", "adj.", "小的；少量的", "smaller than 表示数量或规模更小。", { specialForms: ["small—smaller—smallest"], examSynonyms: ["minor（较小的）", "limited（有限的）"] }),
  society: makeEntry("society", "n.", "社会；社团", "machines and society did it for us 中 society 与 machines 并列为外部力量。", { specialForms: ["society—societies（y → ies）"], examSynonyms: ["community（社会群体）", "social system（社会制度）"] }),
  species: makeEntry("species", "n.", "物种；种类", "species 单复数同形，No other species 指没有其他物种。", { specialForms: ["species（单复数同形）"], examSynonyms: ["organism group（生物种群）", "kind（种类）"] }),
  stage: makeEntry("stage", "n./v.", "阶段；上演", "highest stage of evolution 是题目干扰项。", { specialForms: ["stage—stages—staged—staging"], examSynonyms: ["phase（阶段）", "level（水平）"] }),
  stop: makeEntry("stop", "v./n.", "停止", "stopped evolving 是选项中的过去分词结构，需与原文观点核对。", { specialForms: ["stop—stops—stopped—stopping"], examSynonyms: ["cease（停止；正式）", "halt（停止）"] }),
  strangely: makeEntry("strangely", "adv.", "奇怪地；出人意料地", "Strangely 放在句首，提示生活变化大而身体变化小这一反差。", { specialForms: ["strangely（副词）"], examSynonyms: ["oddly（奇怪地）", "unexpectedly（出乎意料地）"] }),
  survive: makeEntry("survive", "v.", "生存；幸存", "survive almost as well as girls do、surviving depended on weight 都围绕存活能力。", { specialForms: ["survive—survives—survived—surviving"], examSynonyms: ["live through（熬过）", "outlive（比……活得久）"], collocations: ["almost as well as", "the chance of a baby (particularly a boy baby) surviving"] }),
  survival: makeEntry("survival", "n.", "生存；存活", "lower survival rate 是题15正确答案的核心名词短语。", { specialForms: ["survival（通常不可数）"], examSynonyms: ["continuance（持续生存）", "persistence（持续存在；延续）"], wordFamily: ["survive v. 生存", "survivor n. 幸存者"] }),
  technological: makeEntry("technological", "adj.", "技术的", "technological advance 指技术进步，解释机器替代身体适应。", { specialForms: ["technological（形容词）"], examSynonyms: ["technical（技术的）", "high-tech（高技术的）"], wordFamily: ["technology n. 技术", "technologist n. 技术专家"] }),
  tend: makeEntry("tend", "v.", "往往；倾向于", "wealthy people tend to have fewer children 中 tend to 表示普遍趋势。", { specialForms: ["tend—tends—tended—tending"], examSynonyms: ["be inclined to（倾向于）", "usually（通常；副词）"] }),
  title: makeEntry("title", "n./v.", "标题；题名", "Which ... best title 询问能够概括全文的标题。", { specialForms: ["title—titles—titled—titling"], examSynonyms: ["heading（标题）", "name（名称）"] }),
  today: makeEntry("today", "adv./n.", "今天；如今", "Today 与 Fifty years ago 对照，说明筛选压力的变化。", { specialForms: structureForms, examSynonyms: ["now（如今）", "at present（目前）"] }),
  too: makeEntry("too", "adv.", "太；也", "too light or too heavy 中 too 表示超过适宜范围。", { specialForms: structureForms, examSynonyms: ["overly（过度地）", "also（也；另一义）"] }),
  transform: makeEntry("transform", "v.", "彻底改变；转化", "have been transformed 是生活受到外部力量彻底改变的被动结构。", { specialForms: ["transform—transforms—transformed—transforming"], examSynonyms: ["convert（转变）", "reshape（重塑）"] }),
  tribe: makeEntry("tribe", "n.", "部落；部族", "tribal peoples、the tribes 指传统部落群体。", { specialForms: ["tribe—tribes（复数）"], examSynonyms: ["clan（部族）", "indigenous group（原住群体）"] }),
  ugliness: makeEntry("ugliness", "n.", "丑陋", "for its ugliness 表示因生活方式的丑陋而被记住。", { specialForms: ["ugliness（不可数抽象名词）"], examSynonyms: ["hideousness（丑陋）", "deformity（丑态；畸形）"], wordFamily: ["ugly adj. 丑陋的"] }),
  universal: makeEntry("universal", "n./adj.", "普遍规律；普遍的", "the universal of male mortality 指男性死亡率的普遍规律。", { specialForms: ["universal—universals（名词复数）；more universal—most universal"], examSynonyms: ["general rule（普遍规律）", "global（普遍的；全球的）"] }),
  utopia: makeEntry("utopia", "proper n./n.", "乌托邦；理想社会", "biological Utopia 是作者带反讽的理想状态，far from Utopia 表示离理想状态很远。", { specialForms: ["Utopia（专有名词）；utopia—utopias（普通名词复数）"], examSynonyms: ["ideal world（理想世界）", "paradise（乐园；理想状态）"], collocations: ["far from"] }),
  variation: makeEntry("variation", "n.", "变异；差异", "much of the variation is due to genes 中 variation 指个体间差异。", { specialForms: ["variation—variations（复数）"], examSynonyms: ["difference（差异）", "diversity（多样性）"] }),
  wealthy: makeEntry("wealthy", "adj.", "富裕的", "wealthy people tend to have fewer children 是题16正确选项。", { specialForms: ["wealthy—wealthier—wealthiest"], examSynonyms: ["rich（富裕的）", "affluent（富裕的；正式）"], wordFamily: ["wealth n. 财富"] }),
  wealth: makeEntry("wealth", "n.", "财富", "wealth for a few 与 poverty 对举，说明印度社会差异。", { specialForms: ["wealth（通常不可数）"], examSynonyms: ["riches（财富）", "prosperity（繁荣；富裕）"] }),
  weight: makeEntry("weight", "n./v.", "重量；体重", "surviving depended on its weight，过去体重直接影响存活。", { specialForms: ["weight—weights—weighted—weighting"], examSynonyms: ["mass（质量）", "heaviness（重量）"] }),
  woman: makeEntry("woman", "n.", "女性；妇女", "women 是 woman 的不规则复数，与 men 对照。", { specialForms: ["woman—women（不规则复数）"], examSynonyms: ["female（女性）", "lady（女士）"] }),
  every: makeEntry("every", "det./pron.", "每一个；每隔", "for every 100 females 中 every 建立比例基准，表示每一组相同数量的对象。", { specialForms: ["every + 单数名词；every + 数词 + 复数名词"], examSynonyms: ["each（每一个；逐个强调）", "per（每；用于比例表达）"], collocations: ["for every"] }),
  twice: makeEntry("twice", "adv.", "两倍；两次", "twice as many women as men 中 twice 修饰数量比较，说明女性人数约为男性两倍。", { specialForms: ["twice（倍数副词；无比较级）"], examSynonyms: ["two times（两倍；两次）", "double（两倍的；动词/形容词）"], collocations: ["twice as many women as men"] }),
  many: makeEntry("many", "det./pron.", "许多；数量多", "as many women as men 与 so many places 中 many 都修饰可数名词复数，分别构成比较和程度结构。", { specialForms: ["many—more—most；as many + 复数名词 + as"], examSynonyms: ["numerous（许多的）", "a large number of（大量的）"], collocations: ["twice as many women as men", "fill so many places in nature"] }),
  those: makeEntry("those", "det./pron.", "那些；那些人/事物", "those crucial years 中 those 指前文所说的特定年龄段；those ignorant of evolution 中 those 指那些不了解进化的人。", { specialForms: ["that—those（指示代词复数）"], examSynonyms: ["the ones（那些人/事物）", "such people（这类人）"] }),
  fifty: makeEntry("fifty", "numeral/adj.", "五十；五十的", "fifty years ago 把论述定位在距今五十年前。", { specialForms: ["fifty（基数词）；fiftieth（序数词）"], examSynonyms: ["50（数字写法）", "half a hundred（五十；释义表达）"], collocations: ["fifty years ago"] }),
  ago: makeEntry("ago", "adv.", "以前；距今……前", "years ago 以说话时为参照说明过去时间，不能单独作介词使用。", { specialForms: ["two years ago；long ago"], examSynonyms: ["previously（以前）", "in the past（过去）"], collocations: ["fifty years ago"] }),
  certain: makeEntry("certain", "adj.", "确定的；必然的", "almost certain death 中 certain 表示结果几乎不可避免。", { specialForms: ["certain—more certain—most certain；certainty n."], examSynonyms: ["sure（确定的）", "definite（明确的；确定的）"], collocations: ["almost certain death"] }),
  agent: makeEntry("agent", "n.", "作用因素；代理人", "agent of evolution 中 agent 指促成进化变化的作用因素，不是行政代理人。", { specialForms: ["agent—agents（复数）；agency n."], examSynonyms: ["factor（因素）", "representative（代理人；代表）"], collocations: ["agent of evolution"] }),
  commit: makeEntry("commit", "v.", "实施；犯下", "commit evolutionary suicide 中 commit 与抽象名词连用，表示实施或造成某种严重结果。", { specialForms: ["commit—commits—committed—committing"], examSynonyms: ["carry out（实施）", "perpetrate（犯下；正式）"], collocations: ["commit evolutionary suicide"] }),
  suicide: makeEntry("suicide", "n.", "自我毁灭；自杀", "evolutionary suicide 是比喻说法，指一个群体因繁殖过少而削弱自身延续。", { specialForms: ["suicide—suicides（复数）；suicidal adj."], examSynonyms: ["self-destruction（自我毁灭）", "self-killing（自杀；直译释义）"], collocations: ["commit evolutionary suicide"] }),
  stay: makeEntry("stay", "v./n.", "保持；停留", "stay alive 中 stay 是系动词，表示保持活着这一状态。", { specialForms: ["stay—stays—stayed—staying"], examSynonyms: ["remain（保持；仍然）", "continue（继续处于）"], collocations: ["stay alive"] }),
  fewer: makeEntry("fewer", "det./pron.", "较少的（修饰可数名词复数）", "have fewer children 中 fewer 是 few 的比较级，表示孩子数量比参照组少。", { specialForms: ["few—fewer—fewest；fewer + 复数可数名词"], examSynonyms: ["a smaller number of（较少数量的）", "not as many（没有那么多）"], collocations: ["have fewer children"] }),
  except: makeEntry("except", "prep./conj.", "除……之外", "except in some religious communities 排除特定群体，说明主句存在例外范围。", { specialForms: ["except + noun；except that + clause；except for + noun"], examSynonyms: ["excluding（排除）", "apart from（除……之外）"], collocations: ["except in"] }),
  very: makeEntry("very", "adv.", "非常；很；极其", "very few women 与 very high birth rate 中 very 分别加强数量和程度。", { specialForms: ["very + adjective/adverb；very few/little"], examSynonyms: ["extremely（极其）", "highly（高度地；非常）"], collocations: ["very few women"] }),
  nowadays: makeEntry("nowadays", "adv.", "如今；现今", "Nowadays 放在句首，与 Fifty years ago 对照，标记现代社会的统计趋势。", { specialForms: ["nowadays（时间副词；通常置于句首或句末）"], examSynonyms: ["today（如今）", "at present（目前）"] }),
  we: makeEntry("we", "pron.", "我们；我们这一群体", "Most of us、for us 和 we will remember 中，we 的宾格形式 us 指说话者及其所属群体。", { specialForms: ["we（主格）—us（宾格）—our（物主限定词）—ours（物主代词）"], examSynonyms: ["our group（我们这一群体）", "people like us（像我们这样的人）"], collocations: ["for us", "did it for us"] }),
  same: makeEntry("same", "adj./pron.", "相同的；同样的", "the same number of offspring 与 everyone being the same 表示数量或状态趋于相同。", { specialForms: ["same 通常与 the 连用；same—sameness（名词）"], examSynonyms: ["identical（完全相同的）", "equal（相等的）"], collocations: ["the same in", "roughly the same number of offspring"] }),
  tribal: makeEntry("tribal", "adj.", "部落的；部族的", "the remaining tribal peoples 中 tribal 修饰 peoples，指传统部落民族。", { specialForms: ["tribe n.；tribal adj.；tribally adv."], examSynonyms: ["indigenous（原住的）", "clan-based（以部族为基础的）"], collocations: ["the remaining tribal peoples", "tribal peoples"] }),
  everyone: makeEntry("everyone", "pron.", "每个人；人人", "everyone being the same 中 everyone 作独立主格结构的逻辑主语，概括所有人的生存和生育结果。", { specialForms: ["everyone（单数不定代词，谓语通常用单数）；everyone's（所有格）"], examSynonyms: ["everybody（每个人）", "all people（所有人）"] }),
  so: makeEntry("so", "adv./conj.", "如此；这么；因此", "so many places 中 so 修饰数量，表示程度之高；不要把这里的 so 解释为“因此”。", { specialForms: ["so + adjective/adverb；so many/much + noun；so...that..."], examSynonyms: ["thus（因此；另一义）", "to such an extent（达到如此程度）"], collocations: ["fill so many places in nature"] }),
  even: makeEntry("even", "adv.", "甚至；连……都", "even the past 100 years 用 even 加强时间范围，强调连最近的一百年也包括在内。", { specialForms: ["even（副词；置于被强调成分前）"], examSynonyms: ["including（包括；语境义）", "still（甚至；另一语境）"] }),
  machine: makeEntry("machine", "n.", "机器；机械装置", "machines and society did it for us 中 machine 指替人完成适应工作的技术设备。", { specialForms: ["machine—machines（复数）；machine-made adj."], examSynonyms: ["device（装置）", "mechanism（机制；机械装置）"], collocations: ["did it for us"] }),
  phrase: makeEntry("phrase", "n./v.", "短语；措辞；表达", "a phrase to describe those ignorant of evolution 中 phrase 指用来概括某类人的表达。", { specialForms: ["phrase—phrases（复数）；phrase—phrased—phrasing（动词）"], examSynonyms: ["expression（表达）", "wording（措辞）"], collocations: ["a phrase to describe"] }),
  something: makeEntry("something", "pron.", "某事；某物", "as at something wholly beyond his comprehension 中 something 指一个无法理解的对象。", { specialForms: ["something（不定代词，通常视为单数）；something's（所有格/缩写需辨析）"], examSynonyms: ["an object（某个对象）", "a thing（某事物）"] }),
  wholly: makeEntry("wholly", "adv.", "完全地；彻底地", "wholly beyond his comprehension 中 wholly 加强 beyond，表示完全超出理解范围。", { specialForms: ["whole adj./n.；wholly adv."], examSynonyms: ["completely（完全地）", "entirely（完全地）"] }),
  however: makeEntry("however", "adv./conj.", "无论多么；然而", "however amazed our descendants may be at 是让步结构，however 修饰 amazed 并引出让步条件。", { specialForms: ["however + adjective/adverb + subject + may；however, + clause"], examSynonyms: ["no matter how（无论多么）", "nevertheless（然而；转折副词）"], collocations: ["however amazed our descendants may be at"] }),
  far: makeEntry("far", "adv./adj.", "远；远非", "far from Utopia 表示与理想状态相距甚远，属于抽象评价而非空间距离。", { specialForms: ["far—farther/further—farthest/furthest"], examSynonyms: ["distant（遥远的）", "greatly（很大程度地；far 修饰比较级时）"], collocations: ["far from"] }),
  middle: makeEntry("middle", "n./adj.", "中间；中等；中产阶层的", "upper-middle-class 和 middle class population 中 middle 与 class 构成社会阶层复合表达。", { specialForms: ["middle—middles（名词复数）；middle-class（复合形容词）"], examSynonyms: ["central（中间的）", "intermediate（中等的；中间的）"], collocations: ["upper-middle-class", "middle class population"] }),
  high: makeEntry("high", "adj./adv.", "高的；程度高的", "very high birth rate 中 high 表示出生率数值高；highest stage 中是最高级形式。", { specialForms: ["high—higher—highest；highly（副词）"], examSynonyms: ["elevated（高的）", "great（程度高的；语境义）"], collocations: ["birth rate"] }),
  work: makeEntry("work", "v./n.", "起作用；工作；运转", "Natural selection hardly works 中 work 表示某种机制起作用，works 是第三人称单数。", { specialForms: ["work—works—worked—working"], examSynonyms: ["function（运转；起作用）", "operate（运作）"] }),
  year: makeEntry("year", "n.", "年；年份", "year-olds 与 years ago 分别表示年龄复合名词和过去时间。", { specialForms: ["year—years（复数）"], examSynonyms: ["12-month period（年度）", "age（年龄；部分语境）"] }),
  "year-old": makeEntry("year-old", "compound adj./n.", "……岁的；年龄为……岁的人", "70-year-olds 中 year-old 构成复合名词。", { specialForms: ["year-old（前置定语不加复数；名词复数为 year-olds）"], examSynonyms: ["aged ... years（……岁）"] }),
  "upper-middle": makeEntry("upper-middle", "compound adj.", "中上层的", "upper-middle-class India 指印度中上阶层。", { specialForms: ["upper-middle（复合形容词）"], examSynonyms: ["upper-middle-class（中上阶层的）", "relatively affluent（相对富裕的）"] }),
  "possessive-suffix": makeEntry("possessive-suffix", "grammar marker", "所有格词尾 s", "题目标题中的 Man’s 被测试分词规则拆为 man 与 s；s 表示名词所有格词尾。", { specialForms: structureForms, examSynonyms: ["of-phrase（of 所有格结构）"] }),
  "ordinal-suffix": makeEntry("ordinal-suffix", "grammar marker", "序数词词尾 h", "20th 在测试正则中留下 h；h 是序数词后缀片段，不是独立实义词。", { specialForms: structureForms, examSynonyms: ["ordinal ending（序数词词尾）"] }),
  twentieth: makeEntry("twentieth", "ordinal numeral", "第二十的", "20th century 的完整序数词形式是 twentieth。", { specialForms: ["twenty—twentieth"], examSynonyms: ["number 20 ordinal（第二十）"] }),
  s: makeEntry("possessive-suffix", "grammar marker", "所有格词尾 s", "题目中的 Man’s 经过词形扫描后会出现 s；它只承担所有格标记功能。", { specialForms: structureForms, examSynonyms: ["of-phrase（of 所有格）"] }),
  h: makeEntry("ordinal-suffix", "grammar marker", "序数词词尾 h", "题目中的 20th 经过词形扫描后会出现 h；它不是独立词汇。", { specialForms: structureForms, examSynonyms: ["ordinal ending（序数词词尾）"] }),
};
