import type { SentenceReadingGuide } from "./data";
const q=(question:string,evidence:string,answer:string)=>({question,evidence,answer});
export const passage5Reading:Record<string,SentenceReadingGuide>={
 "p5-s1":{focus:"评价抱负的关键是回报与牺牲是否相称，不是单独列出财富声望就足够。",questions:[q("哪组是主语，破折号三个名词起什么作用？","the rewards of ambition—wealth, distinction, control over one's destiny—must be deemed","主语中心是rewards，三个并列名词组解释具体回报；must be deemed才是主句谓语。"),q("worthy说明回报怎样，made修饰哪里？","worthy of the sacrifices made on ambition's behalf","worthy为被动后主语补足，说明回报值得牺牲；made后置修饰sacrifices，非新的有限谓语。") ]},
 "p5-s2":{focus:"抱负传统需要广泛认同，尤其需要受敬仰者认可，受教育者更是重点而非例外。",questions:[q("who回指谁，themselves是否是另一个主语？","people who are themselves admired","who指people作关系从句主语；themselves强调这些人本身也受敬仰，不是反身宾语。"),q("not least among them把受教育者排除了吗？","the educated not least among them","没有。not least强调受教育者在受敬仰者中尤其重要，不能译成至少包括或最不重要。") ]},
 "p5-s3":{focus:"强调的反差是恰恰受教育者声称放弃理想；claim不能自动等同实际放弃。",questions:[q("it is...who突出哪一部分？","it is the educated who have claimed","焦点是the educated。整个结构可理解为受教育者声称，但主干展示仍保留原句强调框架。"),q("两组have都构成有限完成时吗？","have claimed to have given up on ambition as an ideal","have claimed为有限谓语；to have given up是完成不定式，所称放弃早于声称，不单独再起时态主句。") ]},
 "p5-s4":{focus:"奇怪之处是口头放弃者反而可能获益最多；自己的与父辈的是两种抱负来源。",questions:[q("What和that在内层作用相同吗？","What is odd is that they have perhaps most benefited from ambition","What在主语从句内部作主语；that只引出表语内容，不承担内部主宾。they仍指受教育者。"),q("their own与that代什么？","if not always their own then that of their parents and grandparents","两者都补充ambition：自己的抱负，或父母祖父母的抱负；that不是父母、祖父母或财富。") ]},
 "p5-s5":{focus:"关门太晚还不是全部讽刺，骑在马上更说明他们自己享用了抱负的好处。",questions:[q("note单词本身是不是整句的虚伪判断？","a heavy note of hypocrisy","note仅是意味或色彩；heavy给浓重程度，of hypocrisy给虚伪性质。整组才译浓重的虚伪意味。"),q("with后谁在骑，them指谁？","with the educated themselves riding on them","受教育者是riding执行者，themselves强调本人；them指已经逃走的马。这层表明他们正是获益者，不只是迟做补救。") ]},
 "p5-s6":{focus:"not less是否定兴趣减弱，并非否定成功本身，过去时间只是比较基准。",questions:[q("这句话是否说大家现在都更有兴趣？","do not seem less interested in success and its signs now than formerly","它只说看不出兴趣比过去少，不能增加到每个人兴趣都显著提高；success和its signs为两个并列兴趣对象。") ]},
 "p5-s7":{focus:"名称地点或许改变，成功标志的需求没有减弱；具体过去时间的原卷措辞不能擅自改正。",questions:[q("such items回指什么，may change改变什么？","the locations, place names and name brands may change, but such items do not seem less in demand","地点、地名和品牌可能改变；such items回指度假屋、欧洲旅行、宝马等成功标志，需求未显减少。"),q("能否直接把时间译成十年或二十年前？","than a decade or two years ago","不能确认。原卷确是此措辞，字面可读十年或两年前，也可能想表达十至二十年前；需要公开标记疑点并保留英文，不擅改。") ]},
 "p5-s8":{focus:"变化在于不敢公开坦承梦想，原因是怕别人评价；lest后被动及三个形容词不能误作主动宾语。",questions:[q("as once they could省略什么，once是什么作用？","as easily and openly as once they could","as...as比较方式，could后省略坦承梦想这一动作，once表示从前，不是一次或一旦的条件。"),q("他们自己认定抱负不道德，还是怕别人怎样看？","lest they be thought pushing, acquisitive and vulgar","lest表示唯恐，被动be thought说明害怕被别人看成这三种样子，不能改成自己认定抱负不道德。be为虚拟式原形。") ]},
 "p5-s9":{focus:"冒号后是三个并列人物例项，各自话语主张与生活选择形成反差；不要把后两个定语从句连错人。",questions:[q("which、who、whose各回接哪里？","fine hypocritical spectacles, which now more than ever seem in ample supply","which补充spectacles；后面who只修饰publisher，whose只修饰journalist，不把三个例子合成一人。"),q("哪个只是分词定语，哪个是真从句？","the journalist advocating participatory democracy in all phases of life, whose own children are enrolled in private schools","advocating为journalist的分词后置定语，没有独立时态；whose children are enrolled为完整关系从句，有主语和被动谓语。") ]},
 "p5-s10":{focus:"成功不惜代价却避免显得有抱负，是作者对虚伪者的讽刺概括，不是作者的行动建议。",questions:[q("口号是谁的行为逻辑，作者赞同吗？","For such people and many more perhaps not so exceptional, the proper formulation is","For限定这类人的行为，formulation是作者对其矛盾的概括；承接前文hypocritical，不能当作作者赞同隐瞒。"),q("avoid直接带什么，ambitious是什么？","avoid appearing ambitious","avoid的宾语是appearing ambitious动名词短语，ambitious是appear的表语；不是avoid直接带形容词，也不是avoid to appear。") ]},
 "p5-s11":{focus:"攻击者多而辩护者少且乏善可陈；where是评价情境，保留not与extremely的范围。",questions:[q("where谈一个地方吗？","where they are not extremely unattractive","这里是说在辩护者还没到极其令人反感的情况下，也仍缺乏号召力；不是地理地点，不能去掉not改成全部极其反感。") ]},
 "p5-s12":{focus:"长主语中心是support，插入的quality及其不定式不改变主句，it也回指支持程度。",questions:[q("哪一个is才是主句谓语，quality是什么？","the support for ambition as a healthy impulse, a quality to be admired and fixed in the mind of the young, is probably lower","主语中心support，到is probably lower才出现谓语；quality补充抱负这一品质，to be admired and fixed修饰quality。"),q("than从句it代谁，probably能省略吗？","probably lower than it has ever been in the United States","it代support，比较其支持程度；probably保留可能性，不能写成作者已证明绝对历史最低。") ]},
 "p5-s13":{focus:"前两个that内容都被否定，but only后的第三个才被肯定；公开宣称减少不等于抱负消失。",questions:[q("哪两项不成立，哪项成立？","does not mean that ambition is at an end, that people no longer feel its stirrings and promptings, but only that","不成立的是抱负结束以及人们不再有内在冲动；成立的是它不再公开受尊崇、也较少公开被宣称。"),q("less openly能译成完全不再公开吗？","it is less openly professed","不能。less是程度比较，较少公开；no longer修饰的是插入部分honored，不能移到professed上。") ]},
 "p5-s14":{focus:"some of which带出后果，其中再有that表语从句；made与driven共用被动is，但补足性质不同。",questions:[q("some of which指其中谁，that做什么？","some of which are that ambition is driven underground, or made sly","which代Consequences，some of which整体作are主语；that从句作表语说明后果。"),q("sly是第二个动作吗？","ambition is driven underground, or made sly","动作中心为被动driven与made，后者共用is；underground说明转入隐蔽，sly是被变成的性状，不是动词。") ]},
 "p5-s15":{focus:"Such表语前置，冒号后列出三个方位人群；分词trying不应补成原文已有的有限谓语。",questions:[q("Such与the way谁作主语？","Such, then, is the way things stand","Such是前置表语，the way things stand为主语；things stand修饰way，可理解省略that或in which，不是the way how。"),q("中间群体的有限谓语写出来了吗？","the majority of earnest people trying to get on in life","没有。冒号后三个方位项都省略存在或系动词；trying是people的分词定语，to get on说明努力在生活中进步。") ]},
};
