export type PassageLexiconEntry = {
  partOfSpeech: string;
  contextualMeaning: string;
  use: string;
  specialForms?: string[];
  examSynonyms?: string[];
  collocations?: string[];
  otherMeanings?: string[];
  wordFamily?: string[];
  confusions?: string[];
};

const structureForms = ["结构词：无普通词形变化，重点看句法位置"];

const entry = (
  partOfSpeech: string,
  contextualMeaning: string,
  use: string,
  options: Omit<PassageLexiconEntry, "partOfSpeech" | "contextualMeaning" | "use"> = {},
): PassageLexiconEntry => ({
  partOfSpeech,
  contextualMeaning,
  use,
  specialForms: options.specialForms ?? (
    /^(art|prep|conj|pron|det|modal)/.test(partOfSpeech)
      ? structureForms
      : [`${partOfSpeech}：按本篇语境理解`]
  ),
  examSynonyms: options.examSynonyms ?? (/^(art|prep|conj|pron|det|modal)/.test(partOfSpeech) ? ["结构词不能脱离句型直接替换"] : ["同义词需结合本句语境判断"]),
  ...options,
});

export const passage3LemmaAliases: Record<string, string> = {
  attains: "attain",
  is: "be",
  are: "be",
  been: "be",
  advocates: "advocate",
  aiming: "aim",
  years: "year",
  principles: "principle",
  regarded: "regard",
  classed: "class",
  admitting: "admit",
  based: "base",
  says: "say",
  conditions: "condition",
  speeding: "speed",
  feelings: "feeling",
  thoughts: "thought",
  emotions: "emotion",
  undergone: "undergo",
  requires: "require",
  words: "word",
  unhampered: "unhampered",
  stops: "stop",
  qualifying: "qualify",
  adjectives: "adjective",
  verbs: "verb",
  describing: "describe",
  sounds: "sound",
  them: "they",
  sizes: "size",
  inks: "ink",
  colored: "color",
  descriptions: "description",
  battles: "battle",
  confused: "confuse",
  upsetting: "upset",
  notes: "note",
  describes: "describe",
  officers: "officer",
  both: "both",
  consists: "consist",
  falling: "fall",
  weights: "weight",
  kilograms: "kilogram",
  fulfills: "fulfill",
  laws: "law",
  requirements: "requirement",
  thinking: "think",
  calls: "call",
  changed: "change",
  mainly: "mainly",
  approaches: "approach",
  merits: "merit",
  appears: "appear",
  purposes: "purpose",
  flaws: "flaw",
  fashions: "fashion",
  futurists: "futurist",
  production: "production",
  modes: "mode",
  using: "use",
};

export const passage3FamilyAliases: Record<string, string> = {
  advisable: "advise",
  advocates: "advocate",
  aiming: "aim",
  attainable: "attain",
  regarded: "regard",
  unreasonable: "reason",
  conditionally: "condition",
  speeding: "speed",
  corresponding: "correspond",
  expression: "express",
  interpret: "interpret",
  explanatory: "explain",
  descriptions: "describe",
  confused: "confuse",
  emotional: "emotion",
  essentially: "essence",
  literary: "literature",
  production: "produce",
  acceptable: "accept",
  indicative: "indicate",
  reasonable: "reason",
  transient: "transit",
};

export const passage3FormPartOfSpeech: Record<string, string> = {
  attains: "v.（第三人称单数）",
  advocates: "n.（复数；拥护者）",
  aiming: "v.-ing（aim 的现在分词）",
  years: "n.（复数）",
  regarded: "v.-ed（过去分词；被动语态）",
  classed: "v.-ed（过去分词；被动语态）",
  admitting: "v.-ing（让步分词）",
  based: "v.-ed/adj.（过去分词；有基础的）",
  says: "v.（第三人称单数）",
  conditions: "n.（复数）",
  been: "v.-ed（be 的过去分词）",
  speeding: "v.-ing（speed 的现在分词）",
  feelings: "n.（复数）",
  thoughts: "n.（复数）",
  emotions: "n.（复数）",
  undergone: "v.-ed（undergo 的过去分词）",
  requires: "v.（第三人称单数）",
  words: "n.（复数）",
  stops: "n.（复数）",
  qualifying: "v.-ing/adj.（限定；修饰）",
  adjectives: "n.（复数）",
  verbs: "n.（复数）",
  describing: "v.-ing/gerund（描述）",
  sounds: "n.（复数）",
  sizes: "n.（复数）",
  inks: "n.（复数）",
  descriptions: "n.（复数）",
  battles: "n.（复数）",
  confused: "adj./v.-ed（混乱的）",
  upsetting: "adj./v.-ing（令人不安的）",
  notes: "n.（复数）",
  describes: "v.（第三人称单数）",
  officers: "n.（复数）",
  consists: "v.（第三人称单数）",
  falling: "v.-ing/gerund（坠落）",
  weights: "n.（复数）",
  kilograms: "n.（复数）",
  fulfills: "v.（第三人称单数）",
  laws: "n.（复数）",
  requirements: "n.（复数）",
  thinking: "adj./gerund（有思想的；思考）",
  calls: "v.（第三人称单数）",
  changed: "v.-ed/adj.（改变的）",
  approaches: "n./v.（复数；第三人称单数）",
  merits: "n.（复数）",
  appears: "v.（第三人称单数）",
  purposes: "n.（复数）",
  flaws: "n.（复数）",
  fashions: "n.（复数）",
  futurists: "n.（复数）",
  modes: "n.（复数）",
  using: "v.-ing/gerund（使用）",
  production: "n.（生产；产出）",
};

export const passage3Lexicon: Record<string, PassageLexiconEntry> = {
  a: entry("art.", "一个；泛指一类事物", "不定冠词置于辅音音素开头的单数可数名词前。"),
  an: entry("art.", "一个；用于元音音素前", "不定冠词依据发音选择 an，而不是只看首字母。"),
  and: entry("conj.", "和；并且", "连接词、短语或分句时，两侧通常保持语法平行。"),
  as: entry("prep./conj./adv.", "作为；被视为；像", "as + 名词表示身份或结果，as 从句还可表示时间、原因或让步。"),
  at: entry("prep.", "在；针对；以某种方式", "at 可引出地点、对象或状态；regarded as 中 as 才是分类补语。"),
  be: entry("v.（系动词/助动词）", "是；处于某种状态；被……", "be 可构成系表、进行时和被动语态；be regarded as 是被动分类结构。", { specialForms: ["be—am/is/are—was/were—been—being"], examSynonyms: ["remain（保持某状态）", "become（变成；语义不同）"] }),
  by: entry("prep.", "被；由；通过", "被动语态中 by 引出施事；unhampered by 后接造成阻碍的事物。"),
  for: entry("prep./conj.", "因为；对于；持续", "for 可引出原因、对象或时间；本篇 for a century 表持续时间。"),
  if: entry("conj.", "如果；若", "if 引导条件从句；if we want to 表真实条件，不是虚拟愿望。"),
  in: entry("prep./adv.", "在……中；在……方面；以……方式", "in brief、in years to come 和 in the explanatory notes 中分别表示概括、时间和范围。"),
  into: entry("prep.", "进入；到……里面", "fall into the river 中 into 表示运动终点，不能换成静态 in。"),
  no: entry("det./adv.", "没有任何；不", "no + 名词表示完全否定；no thinking man 等于 not any thinking man。"),
  of: entry("prep.", "……的；关于；由……构成", "of 连接所属、内容或组成关系，如 stream of words、noise of falling。"),
  off: entry("prep./adv.", "从……上离开；离开；在……旁边", "bridge off which... 中 off 与 which 前置，表示从桥上掉下去。"),
  on: entry("prep./adv.", "在……上；关于；依据", "on which 引导定语从句，介词提前时 which 指代 theory。"),
  or: entry("conj.", "或者；或是", "连接选择或并列成分；stops, or qualifying adjectives, or finite verbs 保持同级。"),
  than: entry("conj./prep.", "比；与……相比", "比较结构中 than 引出参照项；more of A than B 表示“与其说是 B 不如说是 A”。"),
  that: entry("conj./pron./det.", "那个；引导从句", "that 可引导宾语、同位语或定语从句，需根据位置判断功能。"),
  the: entry("art.", "这个；特指已知对象", "定冠词标明前文已知或语境唯一的对象，如 the Futurist、the river。"),
  them: entry("pron.", "他们；它们（宾格）", "them 作 imitate 的宾语，指代前面的 sounds；主格为 they。"),
  their: entry("possessive det.", "他们的；它们的", "their + 名词表示所属，如 their principles、their falling。"),
  they: entry("pron.", "他们；它们", "they 作主语，形式不随性别变化；与 them/their 区分。"),
  this: entry("det./pron.", "这；这一点", "this 可回指前一句所述事实，如 This... can hardly be classed。"),
  what: entry("pron./det.", "什么；……的事情", "what 引导名词性从句，what its advocates are aiming at 作 find out 的宾语。"),
  whatever: entry("pron./conj.", "无论什么；不管怎样", "whatever Futurist poetry may be 是让步表语从句，whatever 不等于 what。"),
  which: entry("relative pron.", "哪一个；关系代词", "which 指物并可与介词搭配，off which 中 which 指 bridge。"),
  whoever: entry("pron.", "无论谁", "本篇未作正文词义，但可作为 whatever 的同类让步代词理解。"),
  both: entry("det./pron.", "两者都；双方", "both fall into the river 中 both 作主语同位限定，指两名军官。"),
  all: entry("det./pron./adv.", "全部；所有", "all the same 是固定转折短语；all 也可作限定词。"),
  more: entry("det./pron./adv.", "更多；更大程度", "more of a transient phenomenon than literature 是比较和分类结构。"),
  many: entry("det./pron.", "许多；数量多", "many 修饰可数名词复数；本篇选项中 many 需结合名词判断。"),
  other: entry("det./pron./adj.", "其他的；另一个", "other + 复数名词表示其他对象；the other 指两者中的另一个。"),
  movement: entry("n.", "运动；（艺术）思潮", "a movement in art 指一种艺术思潮，movement 可数。", { specialForms: ["movement—movements（复数）"], examSynonyms: ["trend（趋势；思潮）", "school（流派）"] }),
  art: entry("n.", "艺术；艺术创作", "movement in art 中 art 为不可数领域名词，表示艺术整体。", { specialForms: ["art（通常不可数；具体作品可数）"], examSynonyms: ["fine art（美术）", "craft（技艺；语义较窄）"] }),
  attain: entry("v.", "达到（某种状态、水平或风尚）", "attain + 名词表示经过发展达到目标；attains 是第三人称单数。", { specialForms: ["attain—attains—attained—attaining"], examSynonyms: ["achieve（达到）", "reach（达到）"], collocations: ["attains a certain fashion"] }),
  certain: entry("adj.", "某一；确定的", "a certain + 单数名词表示某个特定但未明说的对象。", { specialForms: ["certain—more certain—most certain；certainty n."], examSynonyms: ["specific（特定的）", "sure（确定的）"] }),
  fashion: entry("n./v.", "风尚；流行形式；塑造", "attain a certain fashion 表形成某种风尚；fashion 还可作动词表示塑造。", { specialForms: ["fashion—fashions（复数）；fashioned—fashioning"], examSynonyms: ["style（风格）", "trend（趋势）"] }),
  advisable: entry("adj.", "可取的；明智的", "it is advisable to do 是形式主语结构，表示建议采取某行动。", { specialForms: ["advisable（形容词）；advise v."], examSynonyms: ["wise（明智的）", "recommended（推荐的）"], wordFamily: ["advise v. 建议", "advisability n. 可取性"] }),
  find: entry("v.", "发现；查明", "find out + 宾语从句表示查明事实；find 与 find out 不完全等同。", { specialForms: ["find—finds—found—finding"], examSynonyms: ["discover（发现）", "determine（查明）"], collocations: ["find out"] }),
  out: entry("adv./particle", "出来；彻底；结果", "find out 中 out 是动词短语小品词，整体表示查明而非空间“外面”。", { specialForms: structureForms, examSynonyms: ["discover（查明；整体义）"] }),
  advocate: entry("n./v.", "拥护者；倡导", "its advocates are aiming at 中 advocate 是主张某理论的人；也可作动词。", { specialForms: ["advocate—advocates—advocated—advocating"], examSynonyms: ["supporter（支持者）", "proponent（倡导者）"], collocations: ["its advocates"] }),
  aim: entry("v./n.", "旨在；目标", "aim at + 名词/动名词表示以……为目标；aiming at 是现在分词。", { specialForms: ["aim—aims—aimed—aiming"], examSynonyms: ["target（以……为目标）", "intend（打算）"], collocations: ["aiming at"] }),
  farfetched: entry("adj.", "牵强的；难以置信的", "与 unreasonable 并列作表语，评价原则显得不合常理。", { specialForms: ["far-fetched/farfetched（形容词）"], examSynonyms: ["implausible（难以置信的）", "unrealistic（不现实的）"] }),
  unreasonable: entry("adj.", "不合理的；不讲道理的", "however farfetched and unreasonable... 中与 farfetched 并列作表语。", { specialForms: ["unreasonable—more unreasonable—most unreasonable"], examSynonyms: ["illogical（不合逻辑的）", "unjustified（无正当理由的）"], wordFamily: ["reason n. 理由；理性", "reasonably adv. 合理地"] }),
  principle: entry("n.", "原则；基本主张", "principles may seem... 中 principle 指一套理论所依据的基本规则。", { specialForms: ["principle—principles（复数）"], examSynonyms: ["rule（规则）", "doctrine（学说；原则）"] }),
  may: entry("modal v.", "可能；也许", "may be regarded as 表可能性并构成被动语态；may 后接动词原形。", { specialForms: ["may—might（过去式/较弱可能）"], examSynonyms: ["might（可能；语气较弱）"] }),
  seem: entry("v.", "似乎；看起来", "seem + adjective 或 seem to do 表示呈现出的状态。", { specialForms: ["seem—seems—seemed—seeming"], examSynonyms: ["appear（似乎）", "look（看起来）"] }),
  today: entry("adv./n.", "今天；如今", "today 与 in years to come 对照，形成现在和未来的时间参照。", { specialForms: structureForms, examSynonyms: ["now（如今）", "at present（目前）"] }),
  possible: entry("adj.", "可能的；可行的", "it is possible that... 是形式主语结构，that 从句说明可能内容。", { specialForms: ["possible—more possible—most possible；possibility n."], examSynonyms: ["feasible（可行的）", "likely（可能的）"] }),
  come: entry("v.", "到来；出现", "in years to come 中过去分词/不定式意义表示将来的若干年。", { specialForms: ["come—comes—came—come—coming"], examSynonyms: ["arrive（到来）", "occur（发生）"] }),
  regard: entry("v./n.", "把……视为；看待；关心", "be regarded as + 名词/形容词表示被视为；regard A as B 是主动结构。", { specialForms: ["regard—regards—regarded—regarding"], examSynonyms: ["consider（认为）", "view（看待）"], collocations: ["be regarded as normal", "with regard to"] }),
  normal: entry("adj.", "正常的；通常的", "be regarded as normal 中 normal 作 as 的主语补足语。", { specialForms: ["normal—more normal—most normal；normally adv."], examSynonyms: ["usual（通常的）", "standard（标准的）"] }),
  futurist: entry("n./adj.", "未来主义者；未来主义的", "Futurist poetry 指未来主义诗歌；Futurist 作专门流派名称时首字母大写。", { specialForms: ["futurist—futurists（复数）；futuristic adj."], examSynonyms: ["modernist（现代主义者；相关流派）", "avant-garde（先锋派的）"] }),
  poetry: entry("n.", "诗歌；诗作总称", "poetry 通常不可数；Futurist poetry 是流派名称。", { specialForms: ["poetry（不可数）；poem—poems（具体诗作）"], examSynonyms: ["verse（诗；韵文）", "poems（诗作，具体可数）"] }),
  case: entry("n.", "情况；事例", "the case is difficult 中 case 指所讨论的情况，不是“箱子”。", { specialForms: ["case—cases（复数）"], examSynonyms: ["situation（情况）", "instance（事例）"] }),
  rather: entry("adv.", "相当；宁可；而不是", "rather difficult 中 rather 修饰形容词表示“相当”；rather than 另表选择。", { specialForms: structureForms, examSynonyms: ["quite（相当）", "fairly（相当）"] }),
  difficult: entry("adj.", "困难的；棘手的", "rather difficult 中作表语，说明评价未来主义诗歌的难点。", { specialForms: ["difficult—more difficult—most difficult"], examSynonyms: ["hard（困难的）", "challenging（有挑战的）"] }),
  even: entry("adv.", "甚至；即使", "even admitting that... 加强让步语气，表示即使承认理论正确。", { specialForms: structureForms, examSynonyms: ["although（虽然；语法功能不同）", "even if（即使）"] }),
  admit: entry("v.", "承认；允许进入", "even admitting that... 中 admitting 是分词，that 从句是承认的内容。", { specialForms: ["admit—admits—admitted—admitting"], examSynonyms: ["acknowledge（承认）", "confess（承认；常带过错）"] }),
  theory: entry("n.", "理论；学说", "the theory on which it is based 中 on which 引出理论所依据的关系。", { specialForms: ["theory—theories（y→ies）"], examSynonyms: ["idea（观点）", "hypothesis（假说）"] }),
  base: entry("v./n.", "以……为基础；基础", "be based on + 名词表示以某事为依据；based 是过去分词。", { specialForms: ["base—bases—based—basing"], examSynonyms: ["found（建立于）", "ground（使建立在；基础）"], collocations: ["is based on"] }),
  right: entry("adj./adv./n.", "正确的；恰当的", "may be right 中 right 作表语，表示理论可能正确。", { specialForms: ["right—righter/more right—rightest/most right"], examSynonyms: ["correct（正确的）", "proper（恰当的）"] }),
  class: entry("v./n.", "归类；类别；阶层", "class A as B 表示把 A 归为 B；be classed as 是被动结构。", { specialForms: ["class—classes—classed—classing"], examSynonyms: ["categorize（分类）", "group（归类）"] }),
  literature: entry("n.", "文学；文学作品总称", "as Literature 中 Literature 首字母大写是原文排版，仍指文学这一类别。", { specialForms: ["literature（通常不可数）；literary adj."], examSynonyms: ["writing（文学作品；泛称）", "letters（文学；正式用语）"], wordFamily: ["literary adj. 文学的", "literate adj. 有读写能力的"] }),
  brief: entry("adj./adv.", "简短的；简言之", "in brief 是句子副词短语，概括后面的理论说明。", { specialForms: ["brief—briefer—briefest；briefly adv."], examSynonyms: ["short（短的）", "in short（简言之）"], collocations: ["in brief"] }),
  say: entry("v.", "说；表明", "says the Futurist 是倒装插入引语；say 后可接 that 从句。", { specialForms: ["say—says—said—saying"], examSynonyms: ["state（陈述）", "argue（主张）"] }),
  century: entry("n.", "世纪；一百年", "for a century 表示持续一百年；century 是可数名词。", { specialForms: ["century—centuries（y→ies）"], examSynonyms: ["hundred years（百年）"] }),
  past: entry("adj./n./prep.", "过去的；过去", "past conditions of life 中 past 修饰 conditions，指先前的生活状况。", { specialForms: ["past（无规则变形）"], examSynonyms: ["former（以前的）", "previous（先前的）"] }),
  condition: entry("n./v.", "状况；条件；使适应", "conditions of life 指生活状况；condition 可数时表示具体条件。", { specialForms: ["condition—conditions—conditioned—conditioning"], examSynonyms: ["state（状态）", "circumstance（情况）"], collocations: ["conditions of life"] }),
  conditionally: entry("adv.", "有条件地；附带条件地", "原文 conditionally speeding up 保留副词，表示加速并非毫无限制或绝对线性。", { specialForms: ["conditional adj.；conditionally adv."], examSynonyms: ["with conditions（有条件地）", "provisionally（暂时地；语义不同）"] }),
  speed: entry("v./n.", "加速；速度", "speed up 可及物或不及物；speeding up of life 中是动名词名词化。", { specialForms: ["speed—speeds—sped/speeded—speeding"], examSynonyms: ["accelerate（加速）", "hasten（加快）"], collocations: ["speeding up", "speeding up of life", "speed up our literature"] }),
  up: entry("adv./particle", "向上；加快；完成", "speed up 中 up 改变动词意义，构成常见短语动词。", { specialForms: structureForms, examSynonyms: ["accelerate（加快；整体义）"] }),
  till: entry("prep./conj.", "直到；直至", "till now 表示截至现在；till 后可接时间点或从句。", { specialForms: structureForms, examSynonyms: ["until（直到）"] }),
  now: entry("adv./n.", "现在；如今", "till now 把持续过程的终点定位在现在。", { specialForms: structureForms, examSynonyms: ["at present（目前）", "currently（当前）"] }),
  live: entry("v./adj.", "生活；居住；活着", "we live in a world of... 中 live 是不及物动词，后接 in 地点/环境。", { specialForms: ["live—lives—lived—living"], examSynonyms: ["reside（居住；正式）", "exist（存在；活着）"] }),
  world: entry("n.", "世界；领域", "a world of noise... 中 world 后接 of 短语说明充满的内容。", { specialForms: ["world—worlds（复数）"], examSynonyms: ["globe（地球；世界）", "realm（领域）"] }),
  noise: entry("n./v.", "噪音；声响", "the noise of their falling 中 noise 是坠落动作产生的声音。", { specialForms: ["noise—noises（复数）；noised—noising"], examSynonyms: ["sound（声音；中性）", "din（喧闹声）"] }),
  violence: entry("n.", "暴力；剧烈冲突", "a world of noise and violence and speed 中 violence 与抽象名词并列。", { specialForms: ["violence（不可数）；violent adj."], examSynonyms: ["force（暴力；力量）", "brutality（残暴）"] }),
  consequently: entry("adv.", "因此；所以", "句首 consequently 表示前句生活加速导致后句心理变化。", { specialForms: ["consequent adj.；consequently adv."], examSynonyms: ["therefore（因此）", "as a result（结果）"] }),
  feeling: entry("n./v.", "感情；感觉", "feelings、thoughts and emotions 构成并列主语，说明内在心理层面。", { specialForms: ["feeling—feelings（复数）"], examSynonyms: ["emotion（情感）", "sentiment（情绪；观点）"] }),
  thought: entry("n./v.", "思想；想法；think 的过去式", "thoughts 与 feelings、emotions 并列作抽象名词。", { specialForms: ["think—thought—thought；thought—thoughts（名词）"], examSynonyms: ["idea（想法）", "notion（观念）"] }),
  emotion: entry("n.", "情绪；情感", "emotions 指人的情感反应；emotional life 是其复合表达。", { specialForms: ["emotion—emotions（复数）；emotional adj."], examSynonyms: ["feeling（感情）", "sentiment（情感态度）"], collocations: ["emotional life"] }),
  undergo: entry("v.", "经历；承受（变化）", "have undergone a corresponding change 是现在完成时，undergo 后直接接变化名词。", { specialForms: ["undergo—undergoes—underwent—undergone—undergoing"], examSynonyms: ["experience（经历）", "sustain（承受；遭受）"], collocations: ["have undergone a corresponding change"] }),
  corresponding: entry("adj.", "相应的；对应的", "corresponding change 指与前述外部变化相对应的心理变化。", { specialForms: ["correspond—corresponds—corresponded；corresponding adj."], examSynonyms: ["matching（相应的）", "equivalent（对应的）"] }),
  change: entry("n./v.", "变化；改变", "a change of expression 中 change 是名词；changed 也可作过去分词或形容词。", { specialForms: ["change—changes—changed—changing"], examSynonyms: ["alter（改变）", "shift（转变）"], collocations: ["a change of expression", "a great change in our emotional life"] }),
  require: entry("v.", "需要；要求", "require + 名词表示需要；requires 是第三人称单数。", { specialForms: ["require—requires—required—requiring"], examSynonyms: ["need（需要）", "demand（要求；需求更强）"] }),
  form: entry("n./v.", "形式；形态；形成", "a new form of expression 中 form 是表达形式；of expression 后置修饰 form。", { specialForms: ["form—forms—formed—forming"], examSynonyms: ["shape（形式）", "mode（方式）"], collocations: ["a new form of expression"] }),
  expression: entry("n.", "表达；表达方式", "form of expression 指表达思想或情感的方式，expression 也可指表情。", { specialForms: ["expression—expressions（复数）；express v."], examSynonyms: [" wording（措辞）", "statement（表达；陈述）"] }),
  must: entry("modal v./n.", "必须；必然", "must + 动词原形表示必要性；must speed up 强调未来主义者的要求。", { specialForms: ["must（无过去式；过去语境常用 had to）"], examSynonyms: ["have to（必须）"] }),
  too: entry("adv.", "也；还", "句末 too 表示“也”，承接前句的新表达要求。", { specialForms: structureForms, examSynonyms: ["also（也）", "as well（也）"] }),
  want: entry("v./n.", "想要；希望", "want to do 表示想做某事；if we want to interpret... 是条件从句。", { specialForms: ["want—wants—wanted—wanting"], examSynonyms: ["wish（希望；较正式）", "desire（渴望；较强）"] }),
  interpret: entry("v.", "解释；诠释；表现", "interpret modern stress 中 interpret 表现或诠释现代生活的压力。", { specialForms: ["interpret—interprets—interpreted—interpreting"], examSynonyms: ["explain（解释）", "represent（表现；代表）"], wordFamily: ["interpretation n. 解释", "interpreter n. 口译员"] }),
  modern: entry("adj.", "现代的；当代的", "modern stress 指现代生活特有的紧张和压力。", { specialForms: ["modern—more modern—most modern；modernize v."], examSynonyms: ["contemporary（当代的）", "present-day（现代的）"] }),
  stress: entry("n./v.", "压力；强调", "modern stress 中 stress 指现代生活造成的紧张压力，而非句子重音。", { specialForms: ["stress—stresses—stressed—stressing"], examSynonyms: ["pressure（压力）", "strain（紧张；负荷）"] }),
  pour: entry("v.", "倾泻；连续涌出", "pour out + 名词表示大量连续倾吐；pour 是及物短语动词。", { specialForms: ["pour—pours—poured—pouring"], examSynonyms: ["spill（倾倒；溢出）", "pour forth（涌出）"], collocations: ["pour out"] }),
  large: entry("adj.", "大的；大量的", "a large stream of essential words 中 large 修饰 stream，强调数量和规模。", { specialForms: ["large—larger—largest"], examSynonyms: ["great（大的）", "substantial（大量的）"], collocations: ["a large stream of essential words"] }),
  stream: entry("n./v.", "流；连续的一股", "a stream of words 是数量比喻，of 后接连续涌出的内容。", { specialForms: ["stream—streams—streamed—streaming"], examSynonyms: ["flow（流；流动）", "sequence（连续的一系列）"] }),
  essential: entry("adj./n.", "必要的；核心的", "essential words 指被认为不可省略的核心词语。", { specialForms: ["essential—more essential—most essential；essentially adv."], examSynonyms: ["necessary（必要的）", "fundamental（根本的）"] }),
  word: entry("n./v.", "词；词语；措辞", "a stream of essential words 中 word 是可数名词；make up words 表造词。", { specialForms: ["word—words（复数）；worded—wording"], examSynonyms: ["term（术语）", "expression（表达）"] }),
  unhampered: entry("adj.", "不受阻碍的；不受束缚的", "unhampered by + 名词表示不被某物妨碍；是过去分词形容词。", { specialForms: ["hamper—hampered—hampering；unhampered adj."], examSynonyms: ["unrestricted（不受限制的）", "free（自由的）"] }),
  stop: entry("n./v.", "句号；停止", "stops 在本篇指标点句号；unhampered by stops 表不受句号阻隔。", { specialForms: ["stop—stops—stopped—stopping"], examSynonyms: ["punctuation mark（标点符号）", "halt（停止）"] }),
  qualify: entry("v.", "限定；修饰；使具备资格", "qualifying adjectives 中 qualifying 作前置定语，表示限定名词范围的形容词。", { specialForms: ["qualify—qualifies—qualified—qualifying"], examSynonyms: ["modify（修饰）", "limit（限制）"] }),
  adjective: entry("n.", "形容词", "qualifying adjectives 与 finite verbs 并列，指传统句法成分。", { specialForms: ["adjective—adjectives（复数）"], examSynonyms: ["descriptive word（描述性词语）"] }),
  finite: entry("adj.", "限定的；有界限的", "finite verb 是有时态和人称变化的限定动词，与非谓语相对。", { specialForms: ["finite—more finite—most finite"], examSynonyms: ["tensed（有时态的）", "limited（有限的）"] }),
  verb: entry("n.", "动词", "finite verbs 在句中承担时态和人称功能；verb 是语法术语。", { specialForms: ["verb—verbs—verbed—verbing"], examSynonyms: ["action word（动作词；教学称呼）"] }),
  instead: entry("adv.", "代替；反而", "instead of + doing 表示取代；instead 单独使用时不带 of。", { specialForms: structureForms, examSynonyms: ["alternatively（作为替代）"] }),
  describe: entry("v.", "描述；说明", "descriptions of battles 和 a line describes a fight 中 describe 可接名词作宾语。", { specialForms: ["describe—describes—described—describing"], examSynonyms: ["depict（描绘）", "explain（说明）"], collocations: ["descriptions of battles"] }),
  sound: entry("n./v./adj.", "声音；听起来", "describing sounds 中 sound 是可数名词复数；imitate them 的 them 指声音。", { specialForms: ["sound—sounds—sounded—sounding"], examSynonyms: ["noise（噪声；语义较窄）", "tone（音调）"] }),
  imitate: entry("v.", "模仿", "imitate + 宾语表示模仿声音或对象；that imitate them 中为定语从句谓语。", { specialForms: ["imitate—imitates—imitated—imitating"], examSynonyms: ["mimic（模仿）", "copy（复制；模仿）"] }),
  use: entry("v./n.", "使用；用途", "use many sizes of type 中 use 是及物动词，宾语是排版和墨水。", { specialForms: ["use—uses—used—using"], examSynonyms: ["employ（使用）", "utilize（利用；正式）"] }),
  size: entry("n./v.", "大小；尺寸", "many sizes of type 中 size 表字号大小；size 可作动词表示按尺寸分类。", { specialForms: ["size—sizes—sized—sizing"], examSynonyms: ["dimension（尺寸）", "scale（规模；字号尺度）"] }),
  type: entry("n./v.", "字体；类型；打字", "sizes of type 指字体字号，不是动词“打字”。", { specialForms: ["type—types—typed—typing"], examSynonyms: ["font（字体）", "kind（类型）"] }),
  different: entry("adj.", "不同的；各种的", "different colored inks 中 different 修饰复数名词，表示多种颜色。", { specialForms: ["different—more different—most different；differ v."], examSynonyms: ["distinct（不同的）", "various（各种的）"] }),
  color: entry("n./v.", "颜色；给……着色", "different colored inks 中 colored 是 color 的过去分词形容词，作前置定语；保留原文美式拼写。", { specialForms: ["color—colors—colored—coloring；coloured（英式拼写）"], examSynonyms: ["hue（色调）", "dye（染色；语义更具体）"] }),
  ink: entry("n./v.", "墨水；用墨水书写", "colored inks 是不可数物质名词的复数类别用法，表示不同种类的墨水。", { specialForms: ["ink—inks—inked—inking"], examSynonyms: ["printing ink（印刷油墨）"] }),
  same: entry("adj./pron.", "相同的；同一的", "on the same page 中 same 与 the 连用，表示同一页。", { specialForms: ["same（通常与 the 连用）；sameness n."], examSynonyms: ["identical（完全相同的）", "equal（相等的）"] }),
  page: entry("n./v.", "页；页面", "on the same page 是地点介词短语，也可引申为在同一文本中。", { specialForms: ["page—pages—paged—paging"], examSynonyms: ["leaf（书页；正式）", "sheet（页；纸张）"], collocations: ["on the same page"] }),
  shorten: entry("v.", "缩短", "shorten or lengthen words 中与 lengthen 构成反义并列。", { specialForms: ["shorten—shortens—shortened—shortening"], examSynonyms: ["abridge（删节；缩短）", "reduce（减少）"] }),
  lengthen: entry("v.", "拉长；延长", "lengthen words at will 表示随意增加词语的视觉或书写长度。", { specialForms: ["lengthen—lengthens—lengthened—lengthening"], examSynonyms: ["extend（延长）", "elongate（拉长；正式）"] }),
  will: entry("modal v./n.", "将；意愿；随意", "at will 中 will 是名词，表示按照意愿；不是将来时助动词。", { specialForms: ["will—would（过去视角/假设）"], examSynonyms: ["intention（意愿；名词义）", "voluntarily（自愿地；语境义）"] }),
  certainly: entry("adv.", "当然；确实", "句首 certainly 承认未来主义描写确实混乱，随后转入例证。", { specialForms: structureForms, examSynonyms: ["definitely（确实）", "surely（当然）"] }),
  description: entry("n.", "描述；描写", "descriptions of battles 中 description 是可数名词，of 引出描写对象。", { specialForms: ["description—descriptions；describe v."], examSynonyms: ["account（叙述）", "depiction（描绘）"] }),
  battle: entry("n./v.", "战斗；交战", "descriptions of battles 指战斗场面的描写；battle 可作动词。", { specialForms: ["battle—battles—battled—battling"], examSynonyms: ["fight（战斗）", "combat（战斗；正式）"] }),
  confuse: entry("v.", "使混乱；使困惑", "are confused 中 confused 是 confuse 的过去分词形容词，描述文字呈现出的混乱，而非读者感到困惑。", { specialForms: ["confuse—confuses—confused—confusing"], examSynonyms: ["puzzle（使困惑）", "disorder（使杂乱；语义不同）"] }),
  but: entry("conj./prep.", "但是；然而", "but it is... 引出对未来主义诗歌的转折性批评。", { specialForms: structureForms, examSynonyms: ["however（然而）", "yet（然而）"] }),
  little: entry("det./adv./adj.", "一点；少量；稍微", "a little upsetting 中 a little 修饰形容词，表示程度轻微。", { specialForms: structureForms, examSynonyms: ["slightly（稍微）", "somewhat（有些）"] }),
  upset: entry("v./adj.", "使不安；令人不适的", "it is a little upsetting to read... 中 upsetting 是现在分词形容词，说明读者感受。", { specialForms: ["upset—upsets—upset—upsetting"], examSynonyms: ["disturb（使不安）", "troubling（令人烦恼的）"] }),
  read: entry("v.", "阅读；读到", "to read in the explanatory notes 后接 that 宾语从句；read 的过去式拼写不变。", { specialForms: ["read /riːd/—read /red/—read /red/—reading"], examSynonyms: ["study（阅读；研究）", "notice（读到并注意）"] }),
  explanatory: entry("adj.", "解释性的；说明用的", "explanatory notes 指解释诗行含义的注释。", { specialForms: ["explain v.；explanatory adj.；explanation n."], examSynonyms: ["interpretive（解释性的）", "informative（提供信息的）"] }),
  note: entry("n./v.", "注释；注意到", "in the explanatory notes 中 note 是说明性注释；note 也可作动词。", { specialForms: ["note—notes—noted—noting"], examSynonyms: ["annotation（注释）", "remark（评论；说明）"] }),
  line: entry("n./v.", "诗行；行；描述线条", "a certain line describes... 中 line 指一行诗，而非几何线。", { specialForms: ["line—lines—lined—lining"], examSynonyms: ["verse（诗行）", "sentence（句子；语境近似）"] }),
  fight: entry("n./v.", "打斗；战斗；斗争", "a fight between A and B 中 fight 是名词，between 引出双方。", { specialForms: ["fight—fights—fought—fighting"], examSynonyms: ["battle（战斗）", "struggle（斗争）"], collocations: ["a fight between a Turkish and a Bulgarian officer"] }),
  turkish: entry("proper adj./n.", "土耳其的；土耳其人/语", "Turkish officer 中作国籍形容词，专名首字母按原文大写。", { specialForms: ["Turkish（专有形容词；无普通比较级）"], examSynonyms: ["from Turkey（土耳其的；释义表达）"] }),
  bulgarian: entry("proper adj./n.", "保加利亚的；保加利亚人/语", "Bulgarian officer 中作国籍形容词，与 Turkish 并列。", { specialForms: ["Bulgarian（专有形容词；无普通比较级）"], examSynonyms: ["from Bulgaria（保加利亚的；释义表达）"] }),
  officer: entry("n.", "军官；官员", "a Turkish and a Bulgarian officer 中 officer 是可数名词，前有两个并列国籍修饰语。", { specialForms: ["officer—officers（复数）"], examSynonyms: ["official（官员）", "military officer（军官）"] }),
  bridge: entry("n./v.", "桥；连接", "on a bridge off which... 中 bridge 是定语从句先行词。", { specialForms: ["bridge—bridges—bridged—bridging"], examSynonyms: ["span（桥；跨越）", "overpass（立交桥）"] }),
  fall: entry("v./n.", "掉落；下降；坠落", "fall into the river 中 fall 是不及物动词；falling 是其动名词。", { specialForms: ["fall—falls—fell—fallen—falling"], examSynonyms: ["drop（掉落）", "descend（下降）"], collocations: ["fall into the river"] }),
  river: entry("n.", "河流", "the river 是双方已知的河流地点；river 是可数名词。", { specialForms: ["river—rivers（复数）"], examSynonyms: ["waterway（水道）", "stream（小河；规模较小）"] }),
  then: entry("adv.", "然后；接着", "and then to find... 连接两个并列不定式动作。", { specialForms: structureForms, examSynonyms: ["afterwards（随后）", "next（接着）"] }),
  consist: entry("v.", "由……组成", "consist of + 名词表示组成部分；不能使用被动形式 be consisted of。", { specialForms: ["consist—consists—consisted—consisting"], examSynonyms: ["be composed of（由……组成）", "comprise（包含；组成）"], collocations: ["consists of"] }),
  weight: entry("n./v.", "重量；体重；权重", "the weights of the officers 中 weight 指军官体重，of 引出所属。", { specialForms: ["weight—weights—weighted—weighting"], examSynonyms: ["mass（质量）", "heaviness（重量）"] }),
  pluff: entry("interj./onomatopoeia", "扑通（拟声词）", "Pluff! 模仿物体落水的声音；引号和感叹号是原文形式的一部分。", { specialForms: ["Pluff（拟声词；无词形变化）"], examSynonyms: ["splash（扑通声；语境近似）"] }),
  hundred: entry("numeral/n.", "一百；百", "a hundred and eighty-five kilograms 是完整数量表达，hundred 前有 a。", { specialForms: ["hundred；two hundred（数词后不加 s）"], examSynonyms: ["one hundred（一百）"] }),
  "eighty-five": entry("cardinal numeral", "八十五", "与 hundred and 连用组成 185 的英文数量；连字符保留在复合数词中。", { specialForms: ["eighty-five（基数词）；eighty-fifth（序数词）"], examSynonyms: ["85（数字写法）"] }),
  kilogram: entry("n.", "千克；公斤", "kilograms 是重量单位复数，数量表达中单位名词用复数。", { specialForms: ["kilogram—kilograms（复数）"], examSynonyms: ["kg（缩写）"] }),
  fulfill: entry("v.", "履行；符合；实现", "fulfills the laws and requirements 中 fulfill 直接接并列宾语。", { specialForms: ["fulfill—fulfills—fulfilled—fulfilling"], examSynonyms: ["satisfy（满足要求）", "meet（符合；满足）"] }),
  law: entry("n.", "规则；法律；定律", "laws and requirements of Futurist poetry 指该流派自定的规则和要求。", { specialForms: ["law—laws（复数）"], examSynonyms: ["rule（规则）", "requirement（要求；语义相关）"] }),
  requirement: entry("n.", "要求；必要条件", "requirement of... 中 of 引出要求所属的诗歌体系。", { specialForms: ["requirement—requirements；require v."], examSynonyms: ["demand（要求）", "condition（条件）"] }),
  though: entry("conj.", "虽然；尽管", "though it fulfills... 引导让步状语从句，主句结论不因此改变。", { specialForms: structureForms, examSynonyms: ["although（虽然）", "even though（即使）"] }),
  thinking: entry("adj./gerund", "有思考能力的；思考", "no thinking man 中 thinking 作前置定语，表示理性思考的人。", { specialForms: ["think—thought—thought—thinking；thinking adj."], examSynonyms: ["rational（理性的）", "reflective（善于思考的）"] }),
  think: entry("v.", "思考；认为", "thinking man 源于 think；think 可接 that 从句。", { specialForms: ["think—thinks—thought—thinking"], examSynonyms: ["consider（考虑；认为）", "reason（推理）"] }),
  man: entry("n.", "人；男子", "no thinking man 用单数 man 泛指有思考能力的人，no 决定否定范围。", { specialForms: ["man—men（不规则复数）"], examSynonyms: ["person（人）", "human（人类；语境不同）"] }),
  refuse: entry("v.", "拒绝", "refuse to do 表示拒绝做某事；不能接 refuse doing 表同义。", { specialForms: ["refuse—refuses—refused—refusing"], examSynonyms: ["decline（拒绝；正式）", "reject（拒绝接受）"], collocations: ["refuse to accept"] }),
  accept: entry("v.", "接受；承认", "accept + proposition 表接受主张；accept 与 except 拼写和意义不同。", { specialForms: ["accept—accepts—accepted—accepting"], examSynonyms: ["acknowledge（承认）", "receive（接受；收到）"] }),
  first: entry("adj./adv./n.", "第一的；首先", "their first proposition 中 first 修饰 proposition，标示第一项主张。", { specialForms: ["first（序数词；无比较级）"], examSynonyms: ["initial（最初的）", "primary（首要的）"] }),
  proposition: entry("n.", "主张；命题", "冒号后的 that 从句是 proposition 的同位语，具体说明主张内容。", { specialForms: ["proposition—propositions（复数）"], examSynonyms: ["claim（主张）", "statement（陈述）"] }),
  great: entry("adj.", "巨大的；重要的", "a great change 中 great 强调变化幅度和重要性。", { specialForms: ["great—greater—greatest"], examSynonyms: ["major（重大的）", "considerable（相当大的）"] }),
  emotional: entry("adj.", "情感的；情绪的", "emotional life 指人的情感生活；emotional 修饰 life。", { specialForms: ["emotion n.；emotional—more emotional—most emotional"], examSynonyms: ["affective（情感的；正式）", "sentimental（感伤的；语义不同）"] }),
  call: entry("v./n.", "要求；呼叫；称呼", "call for + 名词表示需要或要求；calls 是第三人称单数。", { specialForms: ["call—calls—called—calling"], examSynonyms: ["require（要求）", "demand（要求；更强）"], collocations: ["calls for a change of expression"] }),
  whole: entry("adj./n.", "整个的；整体", "the whole question 中 whole 修饰 question，强调问题的总体。", { specialForms: ["whole—wholes；wholly adv."], examSynonyms: ["entire（整个的）", "complete（完整的）"] }),
  question: entry("n./v.", "问题；疑问；质疑", "the whole question is... 中 question 指需要回答的核心问题。", { specialForms: ["question—questions—questioned—questioning"], examSynonyms: ["issue（问题；议题）", "problem（问题；难题）"] }),
  really: entry("adv.", "真正地；实际上", "is really this 中 really 加强系表判断，说明总结重点。", { specialForms: structureForms, examSynonyms: ["actually（实际上）", "indeed（确实）"] }),
  essentially: entry("adv.", "本质上；基本上", "essentially changed 询问是否发生根本变化，而非表面变化。", { specialForms: ["essential adj.；essentially adv."], examSynonyms: ["fundamentally（根本上）", "basically（基本上）"] }),
  passage: entry("n.", "文章；段落", "This passage is mainly... 是阅读理解题干，passage 指整篇文章。", { specialForms: ["passage—passages（复数）"], examSynonyms: ["article（文章）", "text（文本）"] }),
  mainly: entry("adv.", "主要地", "题干 mainly 询问全文主旨，不能只依据某个局部例子。", { specialForms: ["main adj.；mainly adv."], examSynonyms: ["primarily（主要地）", "chiefly（主要地）"] }),
  survey: entry("n./v.", "调查；概览", "a survey of new approaches 是干扰项，survey 在选项中指系统调查。", { specialForms: ["survey—surveys—surveyed—surveying"], examSynonyms: ["overview（概览）", "investigation（调查）"] }),
  approach: entry("n./v.", "方法；接近；处理", "new approaches to art 中 approach 指处理艺术问题的方法。", { specialForms: ["approach—approaches—approached—approaching"], examSynonyms: ["method（方法）", "way（方式）"] }),
  review: entry("n./v.", "评论；复习；评述", "a review of Futurist poetry 概括全文的文体是评论性评述。", { specialForms: ["review—reviews—reviewed—reviewing"], examSynonyms: ["critique（评论）", "assessment（评估）"] }),
  about: entry("prep./adv.", "关于；大约", "about merits of... 中 about 引出讨论主题。", { specialForms: structureForms, examSynonyms: ["concerning（关于）", "approximately（大约；另一义）"] }),
  merit: entry("n./v.", "优点；价值；值得", "merits of the Futurist movement 指该运动可能具有的优点，选项并未概括全文。", { specialForms: ["merit—merits—merited—meriting"], examSynonyms: ["value（价值）", "virtue（优点）"] }),
  novel: entry("adj./n.", "新颖的；小说", "novel literary idea 中 novel 作形容词，表示新颖而非小说。", { specialForms: ["novel—more novel—most novel；novel—novels（名词复数）"], examSynonyms: ["new（新的）", "original（新颖的）"] }),
  literary: entry("adj.", "文学的；文学性的", "novel literary idea 中 literary 修饰 idea，选项不是在讨论文学法律。", { specialForms: ["literature n.；literary—more literary—most literary"], examSynonyms: ["artistic（艺术的）", "written（书面的；语境近似）"] }),
  idea: entry("n.", "想法；观念", "a literary idea appears 中 idea 是出现的新观念。", { specialForms: ["idea—ideas（复数）"], examSynonyms: ["notion（观念）", "concept（概念）"] }),
  appear: entry("v.", "出现；似乎", "when a novel literary idea appears 中 appear 是不及物动词；appears 为第三人称单数。", { specialForms: ["appear—appears—appeared—appearing"], examSynonyms: ["emerge（出现）", "seem（似乎；另一义）"] }),
  people: entry("n.", "人们；人群", "people should try to... 中 people 作复数集合名词，泛指读者或公众。", { specialForms: ["person—people（不规则复数）；people—peoples（多个民族）"], examSynonyms: ["persons（人们；正式）", "public（公众）"] }),
  should: entry("modal v.", "应该；应当", "should try to determine... 表建议；should 后接动词原形。", { specialForms: ["should（无词形变化）"], examSynonyms: ["ought to（应该）", "be expected to（应当；语气不同）"] }),
  try: entry("v./n.", "努力；尝试", "try to determine 表努力查明；try doing 则表示尝试某方法。", { specialForms: ["try—tries—tried—trying"], examSynonyms: ["attempt（尝试）", "endeavor（努力；正式）"] }),
  determine: entry("v.", "确定；查明", "determine its purposes 与 find out what... 同义，determine 直接接宾语。", { specialForms: ["determine—determines—determined—determining"], examSynonyms: ["establish（确定）", "find out（查明）"] }),
  purpose: entry("n.", "目的；用途", "determine its purposes 中 purpose 指新艺术观念的目标。", { specialForms: ["purpose—purposes（复数）；purposeful adj."], examSynonyms: ["aim（目的）", "objective（目标）"] }),
  ignore: entry("v.", "忽视；不理会", "ignore its flaws 是干扰项；原文建议先了解目标而非忽视缺点。", { specialForms: ["ignore—ignores—ignored—ignoring"], examSynonyms: ["disregard（忽视）", "overlook（忽略）"] }),
  flaw: entry("n.", "缺点；瑕疵", "its flaws 指新观念或作品存在的缺陷。", { specialForms: ["flaw—flaws（复数）；flawed adj."], examSynonyms: ["defect（缺陷）", "weakness（弱点）"] }),
  claim: entry("v./n.", "声称；主张", "Futurists claim that... 中 claim 后接 that 宾语从句。", { specialForms: ["claim—claims—claimed—claiming"], examSynonyms: ["assert（断言）", "argue（主张）"] }),
  increase: entry("v./n.", "增加；提高", "increase the production of literature 是选项中的数量增加，不等同于改变表达方式。", { specialForms: ["increase— increases— increased— increasing"], examSynonyms: ["raise（提高）", "expand（扩大）"] }),
  production: entry("n.", "生产；产量", "increase the production of literature 把 production 理解为作品产量，原文并未提出这一目标。", { specialForms: ["produce v.；production—productions（具体制作/作品）"], examSynonyms: ["output（产出）", "manufacture（制造）"] }),
  relieve: entry("v.", "缓解；减轻", "use poetry to relieve modern stress 是干扰项；原文说 interpret stress 而非缓解。", { specialForms: ["relieve—relieves—relieved—relieving"], examSynonyms: ["ease（缓解）", "alleviate（减轻；正式）"] }),
  develop: entry("v.", "发展；开发", "develop new modes of expression 概括未来主义者提出新表达方式。", { specialForms: ["develop—develops—developed—developing"], examSynonyms: ["create（创造）", "cultivate（培养；发展）"] }),
  mode: entry("n.", "方式；模式", "modes of expression 指表达方式，mode 是可数名词。", { specialForms: ["mode—modes（复数）"], examSynonyms: ["method（方法）", "form（形式）"] }),
  avoid: entry("v.", "避免；避开", "avoid using adjectives and verbs 是干扰项；原文是不受其阻碍，不是绝对避免。", { specialForms: ["avoid—avoids—avoided—avoiding"], examSynonyms: ["evade（躲避）", "prevent（避免；阻止，语义不同）"] }),
  using: entry("v.-ing/gerund", "使用；利用", "avoid using 后接动名词，using 与 avoid 构成动词搭配。", { specialForms: ["use—uses—used—using"], examSynonyms: ["employing（使用）"] }),
  author: entry("n.", "作者", "The author believes that... 是题干句式，author 指文章作者。", { specialForms: ["author—authors（复数）；author—authored—authoring"], examSynonyms: ["writer（作者）", "the writer（文章作者）"] }),
  believe: entry("v.", "相信；认为", "The author believes that... 引出作者对未来主义诗歌的判断。", { specialForms: ["believe—believes—believed—believing"], examSynonyms: ["think（认为）", "hold（持有观点）"] }),
  reasonable: entry("adj.", "合理的；理性的", "based on reasonable principles 是干扰项；作者只说理论可能正确，并未断言原则合理。", { specialForms: ["reasonable—more reasonable—most reasonable"], examSynonyms: ["rational（理性的）", "sound（合理可靠的）"] }),
  acceptable: entry("adj.", "可接受的；合意的", "new and acceptable to ordinary people 是干扰项，原文没有普通人接受的证据。", { specialForms: ["accept v.；acceptable—more acceptable—most acceptable"], examSynonyms: ["satisfactory（令人满意的）", "tolerable（可容忍的）"] }),
  ordinary: entry("adj.", "普通的；平常的", "ordinary people 指普通大众；题干选项用来设置范围过窄的干扰。", { specialForms: ["ordinary—more ordinary—most ordinary"], examSynonyms: ["common（普通的）", "usual（通常的）"] }),
  indicative: entry("adj.", "表明……的；指示性的", "indicative of + 名词表示显示某种特征；选项把它错误地指向人性变化。", { specialForms: ["indicate v.；indicative adj."], examSynonyms: ["suggestive（暗示的）", "revealing（揭示的）"] }),
  basic: entry("adj.", "基本的；根本的", "a basic change in human nature 是选项中的夸张概括。", { specialForms: ["basic—more basic—most basic；basically adv."], examSynonyms: ["fundamental（根本的）", "essential（基本的）"] }),
  human: entry("adj./n.", "人类的；人", "human nature 指人性；human 作前置定语修饰 nature。", { specialForms: ["human—humans（名词复数）；humanity n."], examSynonyms: ["mankind（人类）", "people（人们；语境不同）"] }),
  nature: entry("n.", "本性；自然", "human nature 是固定名词短语，nature 在此指人的本质。", { specialForms: ["nature（通常不可数；具体自然特征可数）"], examSynonyms: ["character（本性）", "essence（本质）"] }),
  transient: entry("adj.", "短暂的；转瞬即逝的", "more of a transient phenomenon than literature 表示更像短暂现象而非文学。", { specialForms: ["transient—more transient—most transient"], examSynonyms: ["temporary（暂时的）", "short-lived（短命的）"] }),
  phenomenon: entry("n.", "现象；事件", "a transient phenomenon 中 phenomenon 是可数名词，说明未来主义诗歌可能只是短暂现象。", { specialForms: ["phenomenon—phenomena（常见学术复数）；phenomenon—phenomenons（少见）"], examSynonyms: ["occurrence（现象；事件）", "event（事件）"] }),
};
