import type { VocabEntry } from "./data";

type Structure = NonNullable<VocabEntry["structures"]>[number];

type Definition = {
  key: string;
  source: string;
  canonical: string;
  type: string;
  meaning: string;
  grammarRole: string;
  rule: string;
  english: string;
  chinese: string;
  pitfalls: string[];
};

const s = (
  pattern: string,
  meaning: string,
  rule: string,
  english: string,
  chinese: string,
): Structure => ({
  pattern,
  meaning,
  rule,
  examples: [{ english, chinese }],
});

const d = (
  key: string,
  source: string,
  canonical: string,
  type: string,
  meaning: string,
  grammarRole: string,
  rule: string,
  english: string,
  chinese: string,
  pitfalls: string[],
): Definition => ({ key, source, canonical, type, meaning, grammarRole, rule, english, chinese, pitfalls });

const definitions: Definition[] = [
  d("is-to-be-well-regarded", "is to be well regarded", "be well regarded", "被动评价结构", "受到良好评价；得到认可", "be to do 条件结构中的被动谓语", "be to do 表示预期状态，well regarded 是 regard 的过去分词短语，说明社会评价。", "A plan must be well regarded to gain support.", "一个计划必须得到认可才能获得支持。", ["regarded 后可接 as 表身份；不要把 be regarded 写成主动 regard。"]),
  d("worthy-of-the-sacrifices", "worthy of the sacrifices", "be worthy of + noun", "形容词介词结构", "值得这些牺牲", "形容词表语 + of 补足语", "worthy 后固定接 of，of 后说明值得的代价、尊重或注意。", "The result is worthy of the sacrifices.", "这个结果值得付出这些牺牲。", ["worthy of 不写成 *worthy to sacrifices；值得做某事可用 worthy of doing。"]),
  d("on-ambitions-behalf", "on ambition's behalf", "on behalf of + noun", "介词短语", "为了抱负；代表抱负", "方式/受益者状语", "on behalf of 后接代表或受益对象；原文所有格 ambition's 是 of ambition 的压缩形式。", "She spoke on behalf of the students.", "她代表学生发言。", ["on behalf of 不等于 because of；所有格不能改成 *on behalf ambition。"]),
  d("is-to-have-vitality", "is to have vitality", "be to have + noun", "be to 结构", "要保持活力；预期具有活力", "条件从句中的系动词结构", "be to do 可表示计划、命令或应达到的结果；vitality 是 have 的宾语。", "The tradition is to have vitality through practice.", "这一传统要通过实践保持活力。", ["be to do 不等于普通将来时 will；要结合上下文判断预期或安排。"]),
  d("widely-shared", "widely shared", "be widely shared", "被动结构", "被广泛分享或认同", "副词 + 过去分词", "widely 修饰 shared 的范围，主语是被公众共同持有的观念或传统。", "The value is widely shared across cultures.", "这种价值观在不同文化中被广泛认同。", ["shared 可表示‘分享’或‘共同拥有’，不能只译成物理分发。"]),
  d("highly-regarded-by", "highly regarded by", "be highly regarded by + person", "被动评价结构", "受到……高度评价", "过去分词 + by 施动者", "highly 修饰 regarded，by 引出评价者；评价对象作主语。", "The researcher is highly regarded by her peers.", "这位研究者受到同行高度评价。", ["by 后是评价者，for 后才是受称赞的原因。"]),
  d("not-least-among-them", "not least among them", "not least among + group", "插入强调语", "其中尤其是；绝非最不重要", "插入语", "not least 是部分否定式强调，表示该对象至少很重要，常用于列举后的补充。", "Many experts, not least among them teachers, support the plan.", "许多专家支持该计划，其中教师尤其如此。", ["not least 不是‘最不’；这里是强调重要性。"]),
  d("in-an-odd-way", "in an odd way", "in an odd way", "方式介词短语", "以一种奇怪的方式；奇怪的是", "句首方式状语", "in + way 表示方式，odd 修饰 way；在句首常带有作者的反常提示。", "In an odd way, the failure helped us.", "奇怪的是，这次失败反而帮助了我们。", ["odd way 不等于 odd number；这里强调反常或出人意料。"]),
  d("it-is-the-educated-who", "it is the educated who", "it is + focus + who + clause", "强调句", "正是受教育者……", "it is...who 强调主语", "who 从句补充被强调对象的动作；the educated 是形容词名词化，指受教育者群体。", "It is the experienced who notice the risk.", "正是有经验的人注意到了风险。", ["强调句去掉 it is...who 后仍应保留完整主句；educated 在此不是普通形容词定语。"]),
  d("given-up-on", "given up on", "give up on + noun", "短语动词", "放弃对……的希望；不再坚持", "完成不定式中的短语动词", "give up on 后接人、目标或观念，表示不再相信其能实现；on 不能省略。", "Do not give up on the project too soon.", "不要太早放弃这个项目。", ["give up doing 是停止做某事，give up on sth 是放弃希望，含义不同。"]),
  d("as-an-ideal", "as an ideal", "regard/treat A as an ideal", "介词补语", "作为一种理想", "as + 名词作身份/性质补语", "as 后接名词说明把 ambition 看作何种概念；冠词 an 与元音音素开头的 ideal 搭配。", "They present service as an ideal.", "他们把服务呈现为一种理想。", ["as 表‘作为’，like 表‘像’，不能在此随意互换。"]),
  d("what-is-odd-is-that", "what is odd is that", "what + clause + be + that-clause", "主语从句 + 表语从句", "奇怪的是……", "what 从句作主语，that 从句作表语", "what 在从句内充当成分，that 从句完整说明 odd 的内容。", "What is odd is that nobody complained.", "奇怪的是没有人抱怨。", ["what 从句不是疑问句；不要写成 *what odd is。"]),
  d("benefited-from-ambition", "benefited from ambition", "benefit from + source", "动词介词搭配", "从抱负中获益", "现在完成时谓语 + from 来源", "benefit from 后接带来好处的人、事或条件；have benefited 表过去至今的受益。", "Young researchers benefit from collaboration.", "年轻研究者从合作中获益。", ["benefit 是不及物用法时需要 from；不要写 *benefit ambition。"]),
  d("if-not-always-their-own", "if not always their own", "if not A, then B", "省略让步结构", "即使不总是自己的", "省略式让步状语", "if not A 暗含 then B，后文 that of... 补足比较对象；own 是物主代词后的替代词。", "If not always her own, the idea came from her mentor.", "即使不总是她自己的，这个想法也来自她的导师。", ["own 不能脱离所属关系单独误译为‘拥有’；省略结构要回看后文。"]),
  d("that-of-their-parents-and-grandparents", "that of their parents and grandparents", "that of + noun", "替代结构", "他们父母和祖父母的（抱负）", "that 替代前文同类名词", "that of 避免重复单数名词 ambition，of 后接所属者；that 不能改成 which。", "Her career followed that of her parents.", "她的职业道路沿袭了父母的道路。", ["that of 不是指示地点；代替的名词必须与前文同类。"]),
  d("a-heavy-note-of-hypocrisy", "a heavy note of hypocrisy", "a note of + abstract noun", "名词搭配", "浓重的虚伪意味", "存在句中的名词短语", "note 在此是‘意味、调子’，of hypocrisy 说明这种意味的内容，heavy 表程度。", "There was a note of irony in his reply.", "他的回答带有一丝讽刺意味。", ["note 不只表示笔记；a note of 与 a case of 的中心名词不同。"]),
  d("a-case-of", "a case of", "a case of + noun/doing", "名词介词结构", "一个……的事例；属于……的情况", "同位语说明", "of 后接名词或动名词，说明具体属于哪类情况。", "It was a case of poor planning.", "这属于计划不周的情况。", ["case of 后接 doing 时动作名词化；不要写成 *a case to doing。"]),
  d("closing-the-barn-door-after-the-horses-have-escaped", "closing the barn door after the horses have escaped", "close the barn door after the horses have escaped", "习语性动名词结构", "马跑掉后才关门；事后补救", "of 的动名词宾语 + after 从句", "after 从句表示先发生的事件，整句比喻行动太迟；closing 作动名词。", "Apologizing after the damage is closing the barn door after the horses have escaped.", "造成损失后道歉就像马跑掉后才关门。", ["不要按字面理解为真正的畜牧操作；after 从句先于 closing 发生。"]),
  d("riding-on-them", "riding on them", "ride on + object", "with 复合结构", "骑在它们上面；依靠其成果", "with + 名词 + -ing", "them 回指 horses；在比喻中 riding on 表示正在享受由抱负带来的成果。", "With the team riding on its success, criticism sounded hollow.", "团队正享受成功成果时，批评显得空洞。", ["ride on 既可表示骑乘也可表示依赖；代词指代要回看先行词。"]),
  d("less-interested-in", "less interested in", "be less interested in + noun", "比较级形容词搭配", "对……兴趣较少", "系动词 + 比较级表语", "interested in 描述人的感受，less 表示与过去或另一对象相比程度较低。", "Consumers are less interested in outdated models.", "消费者对过时型号的兴趣较低。", ["interested（感到兴趣的）与 interesting（令人感兴趣的）不能混用。"]),
  d("its-signs", "its signs", "the signs of + noun", "物主代词短语", "它的标志；成功的象征", "物主限定词 + 名词", "its 指前文 success，signs 表现某抽象事物的外在标志。", "Success has visible signs, but they are not everything.", "成功有外在标志，但并非全部。", ["its 是物主限定词，不要与 it's 混淆；sign 在此不是路牌。"]),
  d("than-formerly", "than formerly", "than formerly", "省略比较结构", "比从前", "比较基准状语", "formerly 是正式副词，than 后省略重复的谓语或形容词短语。", "People travel more than formerly.", "人们比从前更常旅行。", ["formerly 不能当作名词；省略比较结构仍要找到比较基准。"]),
  d("may-change", "may change", "may + verb", "情态动词结构", "可能改变", "情态动词 + 动词原形", "may 表示可能性，后接 change 原形；不能在 may 后使用第三人称形式。", "Plans may change after the meeting.", "计划可能在会议后改变。", ["may change 不表示必然改变；不要写 *may changes。"]),
  d("name-brands", "name brands", "name brand(s)", "名词复合结构", "知名品牌；名牌", "名词作前置修饰语", "name 修饰 brands，整体指有品牌辨识度的商品；brands 用复数泛指。", "Name brands are not always better.", "名牌不一定总是更好。", ["name brand 不是‘品牌的名字’；brand 作动词时词性不同。"]),
  d("less-in-demand", "less in demand", "be in demand", "介词短语作表语", "需求较低；不如以前受欢迎", "be + in demand + 比较级", "in demand 表示受欢迎或需求旺盛，less 比较的是需求程度。", "This skill is still in demand.", "这项技能仍然有需求。", ["in demand 不是‘在需求里面’；demand 作动词时句法不同。"]),
  d("a-decade-or-two-years-ago", "a decade or two years ago", "a decade or two years ago", "时间状语", "十年或二十年前", "ago 时间定位", "ago 放在时间段后表示距现在的过去时长，or 连接两种估计。", "The policy began a decade ago.", "这项政策始于十年前。", ["ago 通常与一般过去时连用；不要与现在完成时直接搭配同一时间点。"]),
  d("what-has-happened-is-that", "what has happened is that", "what + present perfect + be + that-clause", "主语从句 + 表语从句", "发生的变化是……", "what 从句作主语", "has happened 表示变化已经发生并与现在相关，that 从句说明结果。", "What has happened is that demand has shifted.", "发生的变化是需求转移了。", ["what 从句不是‘什么发生了’的独立问句；that 后用陈述语序。"]),
  d("confess-fully-to", "confess fully to", "confess to + noun/doing", "动词介词搭配", "完全承认；坦白……", "副词 + confess + to 宾语", "confess to 后接名词、动名词或某人的罪过；fully 修饰承认程度。", "He confessed to copying the answer.", "他承认抄了答案。", ["confess 后接 to doing，不写 *confess to do；confess to sb 表向某人承认。"]),
  d("as-easily-and-openly-as", "as easily and openly as", "as + adverb + as", "同级比较结构", "像……一样轻易而公开", "两个并列副词的同级比较", "as...as 两侧应保持同类成分，easily 与 openly 都修饰动作方式。", "She spoke as clearly as her teacher.", "她说得和老师一样清楚。", ["比较结构不能漏掉第二个 as；副词修饰动词而非名词。"]),
  d("lest-they-be-thought", "lest they be thought", "lest + subject + (should) + verb", "正式目的从句", "唯恐他们被认为……", "lest 引导预防性从句", "正式英语中 lest 后常用动词原形或 should；be thought 是被动结构。", "He whispered lest he be heard.", "他低声说话，唯恐被听见。", ["lest 本身已含否定意味，不再加 not；不要把 be 改成一般现在时第三人称。"]),
  d("are-treated-to", "are treated to", "be treated to + noun", "被动短语动词", "被安排享用或看到……", "be + treated + to 宾语", "treated to 表示被给予一种体验，to 是介词；语境可正面也可讽刺。", "Guests were treated to a concert.", "客人们欣赏了一场音乐会。", ["treated to 不等于被虐待；‘对待某人’通常是 treat sb as/like。"]),
  d("more-than-ever", "more than ever", "more than ever", "程度比较短语", "比以往任何时候都更……", "副词程度修饰", "ever 指此前任何时候，more than ever 比较当前程度与过去最高程度。", "The issue matters more than ever.", "这个问题比以往任何时候都重要。", ["more than ever 比较程度，不是简单的数量‘多于曾经’。"]),
  d("in-ample-supply", "in ample supply", "be in ample supply", "介词表语结构", "供应充足", "be + in supply", "in supply 表示可获得，ample 修饰 supply 的充足程度。", "Fresh water is not always in ample supply.", "淡水供应并不总是充足。", ["supply 作名词时与 in 搭配；不要写成 *in ample supplies 表单一总体。"]),
  d("the-critic-of-american-materialism", "the critic of American materialism", "the critic of + noun", "名词后置修饰", "美国物质主义的批评者", "of 短语作 critic 的后置定语", "of American materialism 说明批评对象，American 首字母大写表示美国的。", "The critic of consumerism bought a large house.", "批评消费主义的人买了一座大房子。", ["critic of 是‘批评……的人’，不是被批评者；materialism 不等于 material。"]),
  d("enrolled-in-private-schools", "enrolled in private schools", "be enrolled in + institution", "被动状态搭配", "就读于私立学校", "be + enrolled + in", "enroll in 表注册或入学，be enrolled in 是被动或状态表达；schools 用复数泛指。", "Her children are enrolled in local schools.", "她的孩子就读于当地学校。", ["enroll in 不用 enroll to；enrolled 是过去分词，不表示主动报名者。"]),
  d("for-such-people", "for such people", "for + such + plural noun", "介词对象短语", "对于这样的人", "句首适用范围状语", "such 放在限定词位置，后接复数名词 people；for 引出适用对象。", "For such people, privacy is essential.", "对这样的人来说，隐私至关重要。", ["such people 不写成 *such a people；单数应为 such a person。"]),
  d("at-all-costs", "at all costs", "at all costs", "固定介词短语", "不惜一切代价", "方式状语", "costs 用复数表示各种代价，all 强调无论代价多大。", "They want to win at all costs.", "他们不惜一切代价想赢。", ["at all cost 的单数形式不符合本固定搭配；不要误译为‘在所有成本处’。"]),
  d("succeed-at", "succeed at", "succeed at + noun / doing", "动词介词搭配", "在某事上成功；成功做到某事", "不及物动词 + at 介词补语", "succeed at 后接名词或动名词，说明取得成功的领域或活动；表示一般‘成功’时也可单独使用 succeed。", "She succeeded at solving the problem.", "她成功解决了这个问题。", ["succeed at 后不能接动词原形；表示成功做某事也常用 succeed in doing。", "不要把 succeed at 与 succeed to（继承职位或王位）混淆。"]),
  d("avoid-appearing-ambitious", "avoid appearing ambitious", "avoid + doing + adjective", "动词搭配", "避免显得有抱负", "avoid 的动名词宾语 + 宾补", "avoid 后接动名词，appearing 后接形容词 ambitious 作表语。", "She avoids appearing impatient.", "她避免显得不耐烦。", ["avoid 后不能直接接不定式；appear 后接形容词，不接副词作表语。"]),
  d("attacks-on-ambition", "attacks on ambition", "attack(s) on + noun", "名词介词搭配", "对抱负的攻击或抨击", "名词 + on 后置修饰", "on 引出攻击对象；attacks 是可数名词复数，ambition 是抽象名词。", "The article contains attacks on corruption.", "这篇文章包含对腐败的抨击。", ["attack on 不等于 attack someone；动词 attack 可直接接宾语。"]),
  d("come-from-various-angles", "come from various angles", "come from + source", "动词介词搭配", "来自不同角度", "不及物动词 + from 来源", "come from 引出来源，various 修饰复数 angles，表示观点来源多样。", "Questions came from various angles.", "问题从不同角度出现。", ["various 后接复数名词；come from 不表示物理移动时也可表示观点来源。"]),
  d("public-defenders", "public defenders", "public defender(s)", "名词复合结构", "公开辩护者；为某观点公开辩护的人", "形容词 + 名词复数", "public 修饰 defenders，强调公开身份或公共立场；具体含义由语境确定。", "Public defenders answered the criticism.", "公开辩护者回应了批评。", ["public defender 也可指公设辩护人；本文是观点辩护者，不能脱离语境硬套法律义。"]),
  d("where-they-are-not", "where they are not", "where + subject + be", "关系副词从句", "在并非如此的地方/情况下", "where 引导地点或情境从句", "where 后用陈述语序，they 指前文 defenders；not 否定其存在或身份。", "They speak where they are not directly involved.", "他们在并未直接参与的地方发言。", ["where 从句不倒装；需根据先行词判断是地点还是抽象情境。"]),
  d("as-a-result", "as a result", "as a result", "连接副词短语", "因此；结果", "因果连接", "as a result 可独立连接前后分句，后常接逗号；as a result of 后才接名词。", "The road was closed; as a result, we arrived late.", "道路封闭了，因此我们迟到了。", ["as a result 与 as a result of 句法不同；不要漏掉 of 后的名词结构。"]),
  d("a-healthy-impulse", "a healthy impulse", "a/an + adjective + noun", "名词短语", "一种健康的冲动", "名词作表语或宾语", "impulse 是可数名词，healthy 描述其正面性质；a 与辅音音素 impulse 搭配。", "Curiosity is a healthy impulse.", "好奇心是一种健康的冲动。", ["impulse 不等于 long-term plan；冠词不能省略。"]),
  d("to-be-admired", "to be admired", "be admired", "被动不定式", "值得被敬仰", "to + be + 过去分词", "to be admired 表示被动结果，to 由前面的 quality 等名词或形容词结构支配。", "She has qualities to be admired.", "她有值得敬佩的品质。", ["to be admired 不是主动 admire；不要漏掉 be。"]),
  d("fixed-in-the-mind-of", "fixed in the mind of", "fix A in the mind of B", "过去分词后置结构", "植入某人的头脑", "过去分词 + in 介词补语", "fixed 表示被牢牢记住，in the mind of 指记忆所在；of 后接人物。", "The rule was fixed in the minds of the students.", "这条规则深深印在学生们的脑海里。", ["fixed in 不是物理固定地点；mind 的单复数由受影响的人数决定。"]),
  d("lower-than-it-has-ever-been", "lower than it has ever been", "comparative + than + present perfect", "比较级从句", "低于以往任何时候", "比较级 + than 从句", "has ever been 把当前水平与过去所有时点比较，ever 加强最高范围。", "Trust is lower than it has ever been.", "信任度低于以往任何时候。", ["than 后要用完整或可恢复的比较对象；ever 不能单独表示‘永远’。"]),
  d("at-an-end", "at an end", "be at an end", "介词表语结构", "结束；告终", "be + at + 名词", "at an end 表示某过程已经结束，an 修饰可数名词 end。", "The discussion is at an end.", "讨论结束了。", ["at an end 与 in the end（最后）不同；不要漏掉冠词 an。"]),
  d("no-longer-feel", "no longer feel", "no longer + verb", "否定时间副词", "不再感到", "副词修饰谓语", "no longer 表示状态从过去持续到现在的终止，feel 后接感受对象。", "They no longer feel afraid.", "他们不再感到害怕。", ["no longer 已含否定，不再加 not；not longer 是另一种比较表达。"]),
  d("openly-honored", "openly honored", "be openly honored", "被动评价结构", "被公开尊崇", "副词 + 过去分词", "openly 修饰 honored，说明尊崇行为公开进行；主语是受尊崇对象。", "The tradition was openly honored.", "这一传统得到公开尊崇。", ["honored 可表示荣誉或履行承诺，需看宾语；不要误写成 honorably。"]),
  d("openly-professed", "openly professed", "be openly professed", "被动表达结构", "被公开宣称或承认", "副词 + 过去分词", "profess 表公开声称，openly 强调表达方式；与 honored 的被动结构并列。", "Her beliefs are openly professed.", "她公开宣称自己的信念。", ["profess 不等于 professional；professed 是过去分词。"]),
  d("follow-from-this", "follow from this", "follow from + cause", "动词介词搭配", "由此产生", "不及物动词 + from 原因", "follow from 表结果由原因推出，this 指代前文事实；不能理解成空间跟随。", "Several changes followed from the decision.", "这一决定带来了几项变化。", ["follow from 与 follow up on 不同；from 后接原因或前提。"]),
  d("some-of-which", "some of which", "some of which + clause", "非限制性关系结构", "其中一些……", "数量代词 + 关系代词", "which 指代前面的复数名词，some of which 在从句中作主语或宾语。", "The plan has risks, some of which are serious.", "这个计划有风险，其中一些很严重。", ["which 的先行词通常是物或前述事实；不要改成 who 指人。"]),
  d("driven-underground", "driven underground", "drive A underground", "被动使役结构", "被迫转入地下；被压制而不公开", "过去分词 + 补语", "drive A underground 是使役结构，underground 作结果补语，表示公开表达被压下去。", "The movement was driven underground.", "这场运动被迫转入地下。", ["underground 在此是状态补语，不是简单地点；drive 的过去分词是 driven。"]),
  d("made-sly", "made sly", "make A + adjective", "被动使役结构", "变得鬼祟；被迫采取狡黠方式", "make + 宾语 + 形容词补语", "made sly 省略并列被动中的 is，sly 是结果补语，说明表达方式变得隐秘。", "Pressure made his answers evasive.", "压力使他的回答变得闪烁其词。", ["make 后接形容词作补语，不要写成 *made slyly 表同一结构。"]),
  d("the-way-things-stand", "the way things stand", "the way + clause", "名词性方式结构", "事情目前的状况", "way 后接从句作后置说明", "things stand 在此是‘事情处于某状态’，整体作名词短语；可用于总结现状。", "We must accept the way things stand.", "我们必须接受目前的状况。", ["stand 不只是‘站立’；the way things stand 不是行走路线。"]),
  d("on-the-left", "on the left", "on the left", "位置介词短语", "在左边；左侧一方", "并列位置状语", "on + the + side 表示图示或抽象排列中的位置，常与 on the right 对举。", "The critics stood on the left.", "批评者站在左边。", ["left 在此是名词位置，不是 left 的过去式；通常保留定冠词 the。"]),
  d("on-the-right", "on the right", "on the right", "位置介词短语", "在右边；右侧一方", "并列位置状语", "on the right 与 on the left 构成位置对照，具体可指政治立场或空间位置。", "Supporters gathered on the right.", "支持者聚在右边。", ["right 也可表示正确；此处由 on the... 结构确定为位置。"]),
  d("in-the-middle", "in the middle", "in the middle", "位置介词短语", "在中间；处于两端之间", "并列位置状语", "in 表示处于范围内部，the middle 可指空间或两种立场之间的中间位置。", "Most people remain in the middle.", "大多数人仍处在中间位置。", ["in the middle of 后才接名词；不要把 middle 误作中等程度形容词。"]),
  d("get-on-in-life", "get on in life", "get on in life", "短语动词", "在生活中取得进展；谋求发展", "不及物短语动词 + in 领域", "get on 在英式英语中表示进展或生活状况改善，in life 指生活领域。", "Hard work helped him get on in life.", "努力工作帮助他在生活中取得进展。", ["get on 也可表示相处融洽；in life 使本句含义转为人生发展。"]),
  d("compensate-for", "compensate for", "compensate for + loss/cost", "动词介词搭配", "补偿；弥补", "及物动词 + for 宾语", "for 后接需要弥补的损失、代价或不足；well 可修饰补偿程度。", "The bonus compensates for the extra hours.", "奖金弥补了额外的工时。", ["compensate for 不等于 compensate somebody with；对象与补偿方式句法不同。"]),
  d("rewarded-with", "rewarded with", "be rewarded with + result", "被动搭配", "以……作为回报", "be + rewarded + with", "with 引出得到的回报，主语是获得奖励的人或行为；不要与 rewarded for 的原因混淆。", "The team was rewarded with a grant.", "团队获得了一笔拨款作为奖励。", ["rewarded with 是所得内容，rewarded for 是获奖原因。"]),
  d("rather-than", "rather than", "rather than + parallel element", "取舍连接结构", "而不是；宁愿……而不……", "并列连接", "rather than 两侧应保持词性或结构平行，表达选择或对比。", "She chose facts rather than rumors.", "她选择事实而不是传闻。", ["rather than 后接 doing 时两侧要保持动名词平行；不要混淆 whether。"]),
  d("the-rich", "the rich", "the + adjective", "形容词名词化", "富人群体", "the + 形容词指一类人", "the rich 表示富人整体，谓语通常按复数群体理解；不能再加复数词尾。", "The rich are not a single group.", "富人并不是单一群体。", ["the rich 不是‘丰富的东西’；指人时谓语通常用复数。"]),
  d("the-famous", "the famous", "the + adjective", "形容词名词化", "名人群体", "the + 形容词指一类人", "the famous 表示著名人物整体，famous 保持形容词形式。", "The famous are often watched closely.", "名人常被密切关注。", ["the famous 不是 famous people 的所有格；不要写 *famouses。"]),
  d("implies-that", "implies that", "imply that + clause", "动词宾语从句", "暗示……；意味着……", "及物动词 + that 从句", "that 从句完整说明 imply 的内容，第三人称单数主语使用 implies。", "The evidence implies that the policy failed.", "证据暗示该政策失败了。", ["imply 后可省略 that 但不能省略从句内容；不要与 infer 的主客体方向混淆。"]),
  d("in-words", "in words", "in words", "介词方式短语", "在言语上；口头表达", "方式状语", "in words 指通过说法或表述，常与 in practice 对比。", "In words, he supported the plan; in practice, he delayed it.", "口头上他支持该计划，实际上却拖延了。", ["in words 不等于 word by word；这里强调言语与行动的差距。"]),
  d("too-late-to", "too late to", "too + adjective + to do", "too...to...结构", "太迟而无法……", "程度形容词 + 不定式", "too late to do 表示时间过晚导致动作无法有效完成；to 后接动词原形。", "It is too late to change the record.", "现在改记录已经太迟了。", ["too...to...通常含结果否定；不要把 too late for 与 too late to 混为一谈。"]),
  d("once-it-has-been-let-out", "once it has been let out", "once + present perfect passive", "时间从句", "一旦它被放出", "once 引导时间条件从句", "once 后用完成时被动，表示放出先于主句动作；let 的三态同形。", "Once the secret has been let out, control is difficult.", "秘密一旦泄露，就很难控制。", ["let 的过去式和过去分词仍是 let；once 从句不用倒装。"]),
  d("dishonest-to", "dishonest to", "it is + adjective + to do", "形式主语结构", "做……是不诚实的", "it 作形式主语 + 不定式", "真正主语是不定式，形容词 dishonest 对该行为作评价。", "It is dishonest to hide the evidence.", "隐瞒证据是不诚实的。", ["不要把 dishonest to 当作介词搭配；it 后的 to do 才是被评价行为。"]),
  d("after-the-fulfillment-of", "after the fulfillment of", "after + noun", "时间介词结构", "在……实现之后", "介词 + 抽象名词", "after 后接名词 fulfillment，of 引出实现的目标；也可改写为 after the goal is fulfilled。", "After the fulfillment of the promise, trust grew.", "承诺兑现后，信任增加了。", ["fulfillment 是名词；不要在 after 后直接接动词原形。"]),
  d("deny-ambition", "deny ambition", "deny + noun/doing", "动词搭配", "否认抱负", "及物动词 + 宾语", "deny 直接接被否认的事实或 doing，不能用 deny to do 表同义。", "He denied copying the report.", "他否认抄袭了报告。", ["deny doing 与 refuse to do 不同；deny 后不能接 *deny to confess。"]),
  d("openly-admit", "openly admit", "admit + noun/that-clause", "副词 + 动词搭配", "公开承认", "副词修饰及物动词", "admit 后接名词、动名词或宾语从句，openly 说明承认方式。", "She openly admitted her mistake.", "她公开承认了错误。", ["admit doing 不写成 *admit to do；openly 修饰 admit，不修饰宾语。"]),
  d("think-of-it-as", "think of it as", "think of A as B", "动词 + 宾语补足语", "把它看作……", "think of + 宾语 + as 补语", "as 后接名词或形容词说明对 A 的判断；it 指代前文概念。", "Think of the task as practice.", "把这项任务看作练习。", ["think about 是‘考虑’，think of A as B 才是‘把 A 看作 B’。"]),
  d("fame-or-wealth", "fame or wealth", "A or B", "并列名词结构", "名望或财富", "or 连接并列宾语", "or 连接两个同类名词，表示二者之一或二者并列选择。", "Fame or wealth cannot replace trust.", "名望或财富不能取代信任。", ["or 两侧要保持平行；wealth 是不可数名词，通常不加复数。"]),
  d("related-to", "related to", "be related to + noun", "过去分词形容词搭配", "与……相关", "be + related + to", "related to 引出关联对象，closely 可修饰关联程度。", "The issue is related to public trust.", "这个问题与公众信任有关。", ["related to 不表示因果必然；不要把 to 改成 *related with 表本结构。"]),
  d("appear-greedy", "appear greedy", "appear + adjective", "系动词结构", "显得贪婪", "感官/系动词 + 形容词表语", "appear 后接形容词说明呈现出的状态，不能用副词直接作表语。", "He did not want to appear greedy.", "他不想显得贪婪。", ["appear to do 是另一结构；appear greedy 中 greedy 是表语形容词。"]),
  d("and-contemptible", "and contemptible", "adjective and adjective", "并列表语", "并且令人鄙视的", "and 连接并列形容词", "and 连接 greedy 与 contemptible 两个表语形容词，共同说明 appear 的状态。", "The plan seems risky and contemptible.", "这个计划既有风险又令人鄙视。", ["并列形容词要保持同一层级；contemptible 不等于 contemptuous（蔑视他人的）。"]),
  d("can-be-drawn", "can be drawn", "can be drawn from + evidence", "情态被动结构", "可以得出（结论）", "can + be + 过去分词", "draw a conclusion from evidence 的被动形式中，from 引出依据；can 表可能性。", "A clear conclusion can be drawn from the data.", "可以从数据中得出明确结论。", ["draw 在此不是画图；被动需要 be drawn，不能写 *can drawn。"]),
  d("should-be-maintained", "should be maintained", "should be maintained + adverb", "情态被动结构", "应当被保持", "should + be + 过去分词", "should 表建议或规范，maintained 的宾语是前文 ambition；方式副词可置于过去分词前后。", "The balance should be maintained carefully.", "应当谨慎保持这种平衡。", ["should 后必须用动词原形 be；maintain 与 remain 不能混淆。"]),
  d("secretly-and-vigorously", "secretly and vigorously", "adverb and adverb", "并列方式状语", "秘密而有力地", "and 连接两个副词", "两个副词共同修饰 maintained，语法并列但语义上体现‘地下化’与力度的组合。", "The group worked secretly and vigorously.", "该小组秘密而有力地开展工作。", ["vigorously 表力度，不表示公开；secretly 与 openly 是反义方式。"]),
  d("openly-and-enthusiastically", "openly and enthusiastically", "adverb and adverb", "并列方式状语", "公开而热情地", "and 连接两个副词", "openly 与 enthusiastically 共同说明维护方式，表达作者推断的正面方向。", "They discussed the issue openly and enthusiastically.", "他们公开而热烈地讨论了这个问题。", ["enthusiastically 修饰动作方式；不要误写成形容词 enthusiastic 直接作状语。"]),
  d("easily-and-momentarily", "easily and momentarily", "adverb and adverb", "并列方式状语", "轻易而短暂地", "and 连接两个副词", "两个副词并列修饰动作；momentarily 强调持续时间很短。", "The light flashed easily and momentarily in the test.", "灯光在测试中轻易而短暂地闪过。", ["momentarily 不等于 eventually；它强调短时间。"]),
  d("verbally-and-spiritually", "verbally and spiritually", "adverb and adverb", "并列方式状语", "口头上并在精神层面", "and 连接两个副词", "verbally 表达语言层面，spiritually 表达精神层面，二者并列修饰 maintained。", "The value was defended verbally and spiritually.", "这一价值在语言和精神层面都得到维护。", ["verbally 不等于 orally 的所有语境；spiritually 不表示物理空间。"]),
  d("maintained-openly", "maintained openly", "maintain + object + openly", "被动谓语 + 方式副词", "公开地保持", "过去分词后置方式状语", "openly 修饰 maintained，说明保持行为的公开程度；与 secretly 形成对比。", "The principle is maintained openly.", "这一原则得到公开维护。", ["openly 的位置可前可后，但不能改变被动结构；不要把 maintained 当作名词。"]),
];

const collocationKey = (source: string) =>
  `p5-collocation-${source.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`;

const c = (
  source: string,
  canonical: string,
  meaning: string,
  english: string,
  chinese: string,
  pitfall: string,
  grammarRole = "高频搭配或句法结构",
): Definition =>
  d(
    collocationKey(source),
    source,
    canonical,
    "常用搭配",
    meaning,
    grammarRole,
    `${canonical} 是可迁移的规范结构；按整体理解为“${meaning}”。`,
    english,
    chinese,
    [pitfall, "先按整体搭配理解，再根据上下文确定具体成分。"],
  );

const reusedPhraseAliases: Record<string, string> = {
  "on behalf of ambition": "on-ambitions-behalf",
  "worthy of": "worthy-of-the-sacrifices",
  "on behalf of": "on-ambitions-behalf",
  "benefit from": "benefited-from-ambition",
  "highly regarded": "highly-regarded-by",
  "not least": "not-least-among-them",
  "a note of hypocrisy": "a-heavy-note-of-hypocrisy",
  "interested in": "less-interested-in",
  "signs of": "its-signs",
  "in demand": "less-in-demand",
  "confess to": "confess-fully-to",
  "lest + clause": "lest-they-be-thought",
  "be treated to": "are-treated-to",
  "a quality to be admired": "to-be-admired",
  "fixed in one's mind": "fixed-in-the-mind-of",
  "in the mind of": "fixed-in-the-mind-of",
  "as a consequence": "as-a-result",
  "some of which": "some-of-which",
  "drive A underground": "driven-underground",
  "from various angles": "come-from-various-angles",
  "public defender": "public-defenders",
  "the way things stand": "the-way-things-stand",
  "on the left": "on-the-left",
  "on the right": "on-the-right",
  "in the middle": "in-the-middle",
  "get on in life": "get-on-in-life",
  "compensate for": "compensate-for",
  "the rich": "the-rich",
  "the famous": "the-famous",
  "imply that": "implies-that",
  "in words": "in-words",
  "too late to": "too-late-to",
  "after the fulfillment of": "after-the-fulfillment-of",
  "deny doing": "deny-ambition",
  "related to": "related-to",
  "appear greedy": "appear-greedy",
  "and contemptible": "and-contemptible",
  "can be drawn": "can-be-drawn",
  "should be maintained": "should-be-maintained",
  "secretly and vigorously": "secretly-and-vigorously",
  "openly and enthusiastically": "openly-and-enthusiastically",
  "easily and momentarily": "easily-and-momentarily",
  "verbally and spiritually": "verbally-and-spiritually",
  "maintained openly": "maintained-openly",
  "rather than": "rather-than",
  "fame or wealth": "fame-or-wealth",
  "think of it as": "think-of-it-as",
  "once it has been let out": "once-it-has-been-let-out",
  "dishonest to": "dishonest-to",
  "openly admit": "openly-admit",
  "as a result": "as-a-result",
  "in ample supply": "in-ample-supply",
  "in an odd way": "in-an-odd-way",
  "than formerly": "than-formerly",
  "succeed at": "succeed-at",
};

const extraCollocations: Definition[] = [
  c("ambition to do", "ambition to do sth", "做某事的抱负", "Her ambition to lead the project inspired the team.", "她领导这个项目的抱负鼓舞了团队。", "ambition 后接 to do，不要写成 *ambition for do。", "名词 + 不定式补语"),
  c("the rewards of", "the rewards of + noun", "……带来的回报", "The rewards of patience are often lasting.", "耐心带来的回报往往是持久的。", "of 后接回报的来源；不要把 rewards of 误解为奖励对象。", "名词 + of 补足语"),
  c("reward sb with sth", "reward sb with sth", "用某物奖励某人", "The school rewarded her with a scholarship.", "学校用奖学金奖励了她。", "with 后是得到的奖励，for 后才是获奖原因。", "及物动词 + 宾语 + with"),
  c("control over", "control over + noun", "对……的控制", "They want greater control over their schedule.", "他们希望更好地掌控自己的日程。", "control over 的 over 引出控制对象，不要写成 *control to。", "名词 + 介词补足语"),
  c("take control of", "take control of + noun", "控制；接管……", "The committee took control of the budget.", "委员会接管了预算。", "take control of 后直接接被控制对象，of 不能省略。", "动词短语"),
  c("deem A worthy of B", "deem A worthy of B", "认为 A 值得 B", "The judges deemed the work worthy of praise.", "评委认为这件作品值得称赞。", "deem 是正式动词，A 后用形容词补语，不要加多余的 as。", "动词 + 宾语 + 形容词补语"),
  c("be deemed", "be deemed + adjective/noun", "被认为是……", "The proposal was deemed impractical.", "这项提案被认为不切实际。", "被动结构需要 be + deemed；不要写 *be deem。", "被动评价结构"),
  c("worthy of doing", "be worthy of doing", "值得做某事", "The issue is worthy of discussing.", "这个问题值得讨论。", "of 是介词，后接动名词 doing，不接动词原形。", "形容词 + 介词 + 动名词"),
  c("tradition of", "tradition of + noun/doing", "……的传统", "The tradition of helping neighbors remains strong.", "帮助邻居的传统依然牢固。", "of 后可接名词或动名词说明传统内容。", "名词 + of 补足语"),
  c("a long tradition", "a long tradition of + noun", "悠久的……传统", "The town has a long tradition of music.", "这座城镇有悠久的音乐传统。", "单数可数名词 tradition 前要有 a；具体内容通常接 of。", "名词短语"),
  c("wide range", "a wide range of + plural noun", "广泛范围；各种各样的……", "The course offers a wide range of choices.", "这门课程提供了多种选择。", "range 前通常有 a，of 后接复数名词。", "数量名词结构"),
  c("share an ideal", "share an ideal", "共同拥有一种理想", "The two groups share an ideal of public service.", "这两个群体共同拥有服务公众的理想。", "share 直接接共同拥有的内容；ideal 是可数名词时要有冠词。", "及物动词 + 宾语"),
  c("highly valued", "be highly valued", "受到高度重视", "Honesty is highly valued in the profession.", "诚实在这个行业中受到高度重视。", "valued 是过去分词；highly 修饰评价程度，不是空间高度。", "副词 + 被动分词"),
  c("be admired by", "be admired by + person", "受到……钦佩", "The teacher is admired by her students.", "这位老师受到学生们的钦佩。", "by 后接钦佩者；for 后才说明钦佩原因。", "被动评价结构"),
  c("admire sb for sth", "admire sb for sth", "因某事钦佩某人", "I admire her for her persistence.", "我因她的坚持而钦佩她。", "admire 的人作宾语，for 引出钦佩原因。", "动词 + 宾语 + for"),
  c("the educated", "the + adjective", "受过教育的人群", "The educated are expected to serve society.", "受过教育的人被期待服务社会。", "the + 形容词表示一类人，谓语通常用复数。", "形容词名词化"),
  c("educated people", "educated people", "受过教育的人", "Educated people may question old assumptions.", "受过教育的人可能会质疑旧有假设。", "people 是复数中心词，educated 作前置定语。", "形容词 + 复数名词"),
  c("at least", "at least + noun/clause", "至少；起码", "At least three students volunteered.", "至少有三名学生报名参加。", "at least 表最低限度，不等于 not least 的强调用法。", "程度副词短语"),
  c("oddly enough", "oddly enough, + clause", "奇怪的是；说来也怪", "Oddly enough, the delay improved the result.", "奇怪的是，这次延误反而改善了结果。", "oddly enough 常作句子插入或句首状语，不要把 enough 当名词。", "句子副词短语"),
  c("claim to do", "claim to do sth", "声称做某事", "He claims to know the answer.", "他声称知道答案。", "claim 后接 to do；若主语不同，改用 claim that 从句。", "动词 + 不定式"),
  c("claim that", "claim that + clause", "声称……", "The report claims that the method is safe.", "报告声称这种方法是安全的。", "that 后用陈述语序，不要写成疑问倒装。", "动词 + 宾语从句"),
  c("ideal for", "be ideal for + noun/doing", "最适合……；对……理想", "This room is ideal for quiet study.", "这个房间非常适合安静学习。", "for 后接适用对象或活动，不能直接接动词原形。", "形容词 + 介词"),
  c("benefit sb", "benefit sb", "使某人受益", "Regular exercise benefits the heart.", "经常锻炼有益于心脏。", "benefit 作及物动词时直接接受益者；不要再加 from。", "及物动词"),
  c("one's own", "one's own + noun", "某人自己的……", "She made her own decision.", "她做出了自己的决定。", "own 通常放在物主限定词后修饰名词，不能脱离所属关系乱用。", "物主限定结构"),
  c("on one's own", "on one's own", "独自；靠自己", "He completed the task on his own.", "他独自完成了任务。", "on one's own 表独立状态，不等于 one's own + 名词。", "介词短语"),
  c("accuse sb of hypocrisy", "accuse sb of + noun/doing", "指责某人虚伪", "They accused him of hypocrisy.", "他们指责他虚伪。", "accuse 后接人，of 后接被指责的行为或性质。", "动词 + 宾语 + of"),
  c("close the door", "close the door", "关门；关闭入口", "Please close the door quietly.", "请安静地关门。", "close 是及物动词时直接接 door；不要在此处加介词 to。", "及物动词 + 宾语"),
  c("close after", "close after + time/event", "在……之后关闭", "The museum closes after the final tour.", "博物馆在最后一场参观后关闭。", "after 后接时间或事件，表示关闭发生的先后。", "动词 + 时间状语"),
  c("at the door", "at the door", "在门口", "Someone is waiting at the door.", "有人正在门口等候。", "at the door 表位置；表示进入方向时用 through/to the door。", "地点介词短语"),
  c("escape from", "escape from + place/danger", "从……逃脱", "The hikers escaped from the storm.", "徒步者躲过了暴风雨。", "from 引出逃离的地点或危险，不能写成 *escape to 表同一义。", "动词 + 介词"),
  c("escape notice", "escape notice", "未被注意到；逃过注意", "The small error escaped notice.", "这个小错误没有被注意到。", "notice 在此是名词，escape 直接接它，不要加 from。", "动词 + 名词"),
  c("ride on", "ride on + object", "骑在……上；依赖……", "The outcome rides on public support.", "结果取决于公众支持。", "ride on 可是字面骑乘，也可比喻依赖，需看宾语。", "短语动词"),
  c("go for a ride", "go for a ride", "去兜风；骑行", "We went for a ride after dinner.", "晚饭后我们去兜风了。", "ride 是可数名词，a 不能省略。", "动词短语"),
  c("take an interest in", "take an interest in + noun", "对……产生兴趣", "She took an interest in local history.", "她对地方历史产生了兴趣。", "interest 是可数名词时用 an；in 后接兴趣对象。", "动词 + 名词 + 介词"),
  c("a sign of success", "a sign of + noun", "成功的迹象", "A growing audience is a sign of success.", "观众增多是成功的迹象。", "sign 是可数名词，of 后说明所指示的内容。", "名词 + of 补足语"),
  c("summer home", "summer home", "避暑住宅；夏季住宅", "They spend July at their summer home.", "他们在避暑住宅度过七月。", "summer 作前置修饰语，home 在此是名词，不是副词。", "名词复合结构"),
  c("at home", "at home", "在家；在熟悉环境中", "The children are safe at home.", "孩子们在家很安全。", "at home 表位置或熟悉感，不要按 at + home 的动作方向理解。", "地点介词短语"),
  c("name brand", "name brand", "知名品牌；名牌", "Some shoppers prefer name brands.", "一些购物者更喜欢名牌。", "name 作前置修饰语表示知名，不是 brand 的名称。", "名词复合结构"),
  c("by name", "by name", "按名字；叫得出名字", "The receptionist knows every visitor by name.", "接待员知道每位访客的名字。", "by name 表识别方式；不要与 in the name of 的代表关系混淆。", "方式介词短语"),
  c("brand image", "brand image", "品牌形象", "A consistent logo strengthens the brand image.", "统一的标志能强化品牌形象。", "brand image 是名词复合结构，image 不是图像的唯一含义。", "名词复合结构"),
  c("demand for", "demand for + noun", "对……的需求", "Demand for clean energy is growing.", "对清洁能源的需求正在增长。", "demand 作名词时用 for 引出需求对象；作动词时可直接接宾语。", "名词 + 介词补足语"),
  c("openly profess", "openly profess + belief/ambition", "公开宣称……", "She openly professed her support for the reform.", "她公开宣称支持这项改革。", "profess 后接信念或立场；副词 openly 修饰宣称方式。", "副词 + 及物动词"),
  c("once again", "once again", "再次；又一次", "The committee met once again.", "委员会再次开会。", "once again 是副词短语，通常修饰动作，不要误写成 once and again 的时间从句。", "副词短语"),
  c("once + clause", "once + clause", "一旦……；当……之后", "Once the evidence is checked, we can decide.", "证据核查后我们就可以作决定。", "once 引导时间或条件从句，从句用陈述语序，主句再说明结果。", "从属连词 + 从句"),
  c("treat A as B", "treat A as B", "把 A 当作 B 对待", "We should treat criticism as useful advice.", "我们应把批评当作有用的建议。", "treat 后接宾语 A，as 后接身份或性质补语 B；不能漏掉 as。", "动词 + 宾语 + as 补语"),
  c("ample evidence", "ample evidence", "充分的证据", "There is ample evidence to support the claim.", "有充分证据支持这一说法。", "evidence 通常不可数，ample 修饰数量充足程度，不要随意加复数 -s。", "形容词 + 不可数名词"),
  c("in supply", "be in supply", "有供应；可获得", "Fresh water is limited in supply.", "淡水供应有限。", "in supply 表示可获得性，常与 ample、short、limited 等词连用。", "介词短语作表语"),
  c("supply sb with sth", "supply sb with sth", "向某人提供某物", "The program supplies schools with new materials.", "该项目向学校提供新材料。", "with 后接提供的物品；也可用 supply sth to sb，不能把两种结构混写。", "动词 + 间接宾语 + with"),
  c("critic of", "critic of + noun", "……的批评者", "He is a sharp critic of wasteful spending.", "他是浪费性支出的尖锐批评者。", "critic of 后接批评对象；critic 不是 criticism（批评行为）。", "名词 + of 后置定语"),
  c("harsh critic", "a harsh critic of + noun", "严厉的批评者", "She is a harsh critic of the policy.", "她严厉批评这项政策。", "critic 是可数名词，单数前需有 a；harsh 描述批评态度。", "形容词 + 可数名词"),
  c("take one's meals", "take one's meals", "用餐；进餐", "He takes his meals in the staff room.", "他在员工休息室用餐。", "take one's meals 是正式表达，one's 随主语变化；不要把 take 直译为‘拿走’。", "动词短语"),
  c("take action", "take action", "采取行动", "The agency must take action quickly.", "该机构必须迅速采取行动。", "action 在此通常不可数；不要在固定搭配中随意加 a。", "动词 + 名词"),
  c("advocate doing", "advocate doing sth", "提倡做某事", "Experts advocate reducing waste.", "专家提倡减少浪费。", "advocate 作动词时后接动名词或 that 从句，不接带 to 的不定式。", "动词 + 动名词"),
  c("advocate for", "advocate for + person/cause", "为……发声；支持……", "The group advocates for equal access.", "该团体为平等机会发声。", "advocate for 后接支持对象；英式正式用法也常直接用 advocate sth。", "动词 + 介词"),
  c("phase of life", "a phase of life", "人生阶段", "Retirement is a new phase of life.", "退休是人生的新阶段。", "phase of life 指阶段而非具体地点；phase 是可数名词，单数通常要有 a。", "名词 + of 短语"),
  c("in phases", "in phases", "分阶段地", "The repairs will be completed in phases.", "维修将分阶段完成。", "in phases 强调多个阶段，不能与表示一次完成的 at once 混用。", "方式介词短语"),
  c("enroll in", "enroll in + course/institution", "报名参加；注册进入", "She enrolled in an evening course.", "她报名参加了夜校课程。", "enroll in 后接课程或机构；不要写成 *enroll to。", "动词 + 介词"),
  c("be enrolled in", "be enrolled in + course/institution", "注册于；就读于", "The children are enrolled in local schools.", "这些孩子就读于当地学校。", "be enrolled in 可表示登记状态或被动入学，in 后接机构或项目。", "被动状态结构"),
  c("private school", "private school", "私立学校", "Their daughter attends a private school.", "他们的女儿就读于一所私立学校。", "private 修饰 school 表办学性质；泛指单数时要用 a。", "形容词 + 名词"),
  c("private life", "private life", "私人生活", "The actor keeps his private life out of the news.", "这位演员不让私人生活登上新闻。", "private life 与 public life 对比，private 不是‘秘密的’唯一译法。", "形容词 + 名词"),
  c("the cost of", "the cost of + noun/doing", "……的成本；代价", "We calculated the cost of replacing the equipment.", "我们计算了更换设备的成本。", "of 后接名词或动名词说明成本内容；cost 与 price 的含义不同。", "名词 + of 补足语"),
  c("appear ambitious", "appear + adjective", "显得有抱负", "She did not want to appear ambitious.", "她不想显得有抱负。", "appear 后接形容词作表语；不要用副词 ambitious 修饰 appear。", "系动词 + 形容词"),
  c("appear to do", "appear to do sth", "似乎做某事；显得……", "The figures appear to support the conclusion.", "这些数据似乎支持这一结论。", "appear 后接 to do 表推断；不要把 to 当介词而接名词。", "系动词 + 不定式"),
  c("ambitious plan", "an ambitious plan", "雄心勃勃的计划", "The city adopted an ambitious plan for transit.", "这座城市通过了一项雄心勃勃的交通计划。", "ambitious 修饰 plan，表示目标高或规模大，不等于一定可行。", "形容词 + 可数名词"),
  c("attack on", "attack on + noun", "对……的攻击；抨击", "The speech was an attack on corruption.", "这篇演讲是对腐败的抨击。", "attack 作名词时常用 on 引出对象；作动词时可直接接宾语。", "名词 + 介词补足语"),
  c("come under attack", "come under attack", "受到攻击或抨击", "The proposal came under attack from critics.", "这项提案受到批评者的抨击。", "under attack 表被攻击状态，不能写成 *under an attack 表一般意义。", "动词短语"),
  c("from an angle", "from an angle", "从某一角度", "The issue looks different from another angle.", "从另一个角度看，这个问题不同。", "angle 可表示分析角度或几何角度，要由语境判断；from 引出观察视角。", "介词短语"),
  c("public support", "public support for + noun", "公众支持", "The project needs public support.", "这个项目需要公众支持。", "support 在此通常是不可数名词；具体支持对象可接 for。", "名词短语"),
  c("defender of", "defender of + noun", "……的捍卫者", "She is a defender of free speech.", "她是言论自由的捍卫者。", "defender of 后接捍卫对象；不要与 defendant（被告）混淆。", "名词 + of 后置定语"),
  c("result from", "result from + cause", "由……导致；源于……", "The delay resulted from a power failure.", "延误是由停电造成的。", "result from 引出原因；result in 才引出结果。", "动词 + 介词"),
  c("support for", "support for + noun", "对……的支持", "Support for the measure remains strong.", "对这项措施的支持仍然很强。", "support 作名词时用 for 引出支持对象；不要与 support sb 混为同一结构。", "名词 + 介词补足语"),
  c("support an ambition", "support + ambition/goal", "支持某项抱负", "Her family supported her ambition to study abroad.", "她的家人支持她出国学习的抱负。", "support 作及物动词直接接 ambition；后面可用 to do 说明目标。", "及物动词 + 宾语"),
  c("quality of life", "quality of life", "生活质量", "Clean air improves quality of life.", "清洁空气能改善生活质量。", "quality of life 是固定名词短语，quality 表总体水平，不是单项‘质量’。", "名词 + of 短语"),
  c("fix a date", "fix a date", "确定日期；约定日期", "Let us fix a date for the meeting.", "我们确定一个开会日期吧。", "fix 在此表示确定，不是修理；date 前的冠词不能省略。", "动词 + 名词"),
  c("keep in mind", "keep sth in mind", "记住；牢记", "Keep the original purpose in mind.", "牢记最初的目的。", "keep 后可接宾语再接 in mind；不要写成 *keep on mind。", "动词短语"),
  c("formerly known as", "formerly known as + name", "以前称为……", "The town was formerly known as Eastport.", "这座城镇以前称为 Eastport。", "formerly 是副词，known as 是过去分词短语；不要误用 former 作副词。", "过去分词短语"),
  c("feel a need", "feel a need to do", "感到有必要做某事", "Many workers feel a need to retrain.", "许多工人感到有必要重新培训。", "need 是可数名词时用 a；to do 说明需要采取的行动。", "动词 + 名词 + 不定式"),
  c("feel that", "feel that + clause", "觉得；认为……", "I feel that the evidence is incomplete.", "我觉得证据并不完整。", "feel that 引导陈述从句；正式写作中不能把它当作表示触摸的 feel。", "动词 + 宾语从句"),
  c("be honored", "be honored to do", "荣幸做某事；受到尊重", "We are honored to welcome the guests.", "我们很荣幸欢迎各位来宾。", "be honored 可接 to do 表示荣幸，也可单独表示受到尊敬，需看语境。", "被动形容词结构"),
  c("honor a tradition", "honor + tradition", "遵循；尊重传统", "The ceremony honors an old tradition.", "这项仪式遵循一项古老传统。", "honor 作动词直接接 tradition；不要在动词后再加 for。", "及物动词 + 宾语"),
  c("profess a belief", "profess + belief", "公开宣称一种信念", "He professes a belief in equal treatment.", "他公开宣称相信平等对待。", "profess 比 believe 更正式且带‘公开表明’意味；belief 是名词。", "动词 + 名词"),
  c("consequence of", "consequence of + noun/doing", "……的后果", "The consequence of ignoring the warning was severe.", "忽视警告的后果很严重。", "of 后接原因或行为；consequence 常指结果，不等于 cause。", "名词 + of 补足语"),
  c("some people", "some people", "有些人；一些人", "Some people prefer working alone.", "有些人更喜欢独自工作。", "some 修饰复数可数名词 people，谓语通常用复数；不要与 someone 混用。", "限定词 + 复数名词"),
  c("drive sb to do", "drive sb to do sth", "迫使某人做某事", "Pressure drove him to leave the job.", "压力迫使他辞掉了工作。", "drive 后接人作宾语，to do 表被迫采取的行动；不要漏掉宾语。", "动词 + 宾语 + 不定式"),
  c("go underground", "go underground", "转入地下；秘密活动", "The movement went underground after the ban.", "禁令后该运动转入地下。", "underground 在此作副词或形容词，表示秘密状态，不一定是物理地下。", "动词短语"),
  c("drive underground", "drive sth underground", "使……转入地下", "The restrictions drove the organization underground.", "限制迫使该组织转入地下。", "drive underground 需要宾语说明被迫隐藏的对象；underground 不是直接宾语。", "动词 + 宾语 + 副词"),
  c("stand for", "stand for + noun", "代表；支持；意味着", "The letters stand for a longer name.", "stand for 的含义随语境可为‘代表’或‘支持’，不要与 stand by 混淆。", "短语动词"),
  c("as usual", "as usual", "像往常一样", "As usual, the train arrived early.", "像往常一样，火车提前到了。", "as usual 常作句首或句末状语，不能写成 *as usually。", "方式状语"),
  c("the usual", "the usual + noun", "通常的；惯常的事物", "He ordered the usual for breakfast.", "他早餐点了平常的那份。", "the usual 可省略后面的名词，具体指什么要由上下文恢复。", "the + 形容词名词化"),
  c("the majority of", "the majority of + plural noun", "大多数……", "The majority of voters supported the proposal.", "大多数选民支持这项提案。", "majority of 后接复数名词；谓语可按正式语体用单数或按成员意义用复数。", "数量短语"),
  c("majority opinion", "majority opinion", "多数意见", "The report reflects majority opinion.", "这份报告反映了多数意见。", "majority 作前置修饰语，opinion 可作不可数概念；不要误解为‘多数人的意见书’。", "名词复合结构"),
  c("try to do", "try to do sth", "努力做某事；试图做某事", "They tried to solve the problem.", "他们努力解决这个问题。", "try to do 强调努力达到目标；to 后接动词原形。", "动词 + 不定式"),
  c("try doing", "try doing sth", "尝试做某事（看是否有效）", "Try restarting the computer.", "试试重启电脑。", "try doing 强调把某方法作为试验；与 try to do 的目的侧重点不同。", "动词 + 动名词"),
  c("get on", "get on", "进展；相处；上车", "How are you getting on with the project?", "你的项目进展如何？", "get on 的含义要看宾语和语境；get on with 可表示继续或相处。", "短语动词"),
  c("probably + verb", "probably + verb", "很可能……", "They will probably agree.", "他们很可能会同意。", "probably 通常置于情态动词后、实义动词前；位置变化不能改变陈述语气。", "副词位置"),
  c("be probably + adjective", "be probably + adjective", "很可能是……的", "The result is probably accurate.", "结果很可能是准确的。", "系动词 be 后通常直接接 probably，再接形容词；不要写成 *probably is 在普通陈述中造成不自然语序。", "系动词 + 副词 + 形容词"),
  c("be believed to", "be believed to do", "被认为……", "The method is believed to reduce costs.", "这种方法被认为能降低成本。", "be believed to do 是被动报告结构；也可改写为 people believe that...。", "被动 + 不定式"),
  c("believe that", "believe that + clause", "相信；认为……", "Researchers believe that the trend will continue.", "研究人员认为这一趋势会继续。", "that 引导陈述从句，主句 believe 的主语是持有观点的人。", "动词 + 宾语从句"),
  c("returns on", "returns on + investment", "……的回报；收益率", "Investors compare returns on different funds.", "投资者比较不同基金的回报。", "on 后接投资或资产类别；returns 用复数表示收益，不能与 return to（返回）混淆。", "名词 + 介词补足语"),
  c("compensate sb for sth", "compensate sb for sth", "因某事补偿某人", "The airline compensated passengers for the delay.", "航空公司因延误赔偿乘客。", "compensate 后接被补偿者，for 后接原因或损失；不要把人和损失位置倒置。", "动词 + 宾语 + for"),
  c("achieve a goal", "achieve a goal", "实现目标", "She worked hard to achieve her goal.", "她努力实现自己的目标。", "achieve 是及物动词，直接接 goal；不要说 *achieve to do。", "及物动词 + 宾语"),
  c("goal of", "goal of + noun/doing", "……的目标", "The goal of the policy is to cut waste.", "这项政策的目标是减少浪费。", "of 后说明目标所属的计划或行动；表语不定式说明具体目标。", "名词 + of 补足语"),
  c("imply a meaning", "imply + meaning", "暗示一种含义", "The phrase may imply a different meaning here.", "这个短语在这里可能暗示不同含义。", "imply 是间接暗示，不等于明确说明；meaning 是被暗示的内容。", "及物动词 + 宾语"),
  c("check on", "check on + person/thing", "检查……的状况", "Please check on the children before bed.", "睡前请查看孩子们的情况。", "check on 强调确认状态；check sth 可表示核对内容，介词不能随意省略。", "短语动词"),
  c("keep in check", "keep sth in check", "抑制；控制在范围内", "The new rules keep prices in check.", "新规则把价格控制在合理范围内。", "in check 表受控状态；不要与 check in（办理登记）混淆。", "动词短语"),
  c("let out", "let out + secret/sound", "泄露；发出；放出", "He let out the secret by mistake.", "他无意中泄露了秘密。", "let out 可表示泄露信息、发出声音或放人出去，宾语决定具体义。", "短语动词"),
  c("let sb do", "let sb do sth", "让某人做某事", "The teacher let the students leave early.", "老师让学生们提前离开。", "let 后接宾语再接不带 to 的动词原形；不要写成 *let sb to do。", "使役结构"),
  c("immoral to do", "it is immoral to do sth", "做某事是不道德的", "It is immoral to exploit vulnerable people.", "剥削弱势群体是不道德的。", "immoral 常用于 it is + adjective + to do 结构；不要与 amoral（非道德判断）混淆。", "形容词 + 不定式"),
  c("immoral behavior", "immoral behavior", "不道德行为", "The law cannot excuse immoral behavior.", "法律不能为不道德行为开脱。", "behavior 通常不可数，immoral 作前置定语；不要误写为 *immorality behavior。", "形容词 + 不可数名词"),
  c("deny that", "deny that + clause", "否认……", "The company denied that it had hidden the data.", "公司否认曾隐藏数据。", "deny that 后接完整从句；deny doing 侧重否认做过某事，不能混淆时态关系。", "动词 + 宾语从句"),
  c("fulfillment of", "fulfillment of + noun", "……的实现；满足", "The fulfillment of the promise took years.", "这项承诺的实现花了多年时间。", "of 后接被实现的目标或承诺；fulfillment 也可指需求满足。", "名词 + of 补足语"),
  c("a sense of fulfillment", "a sense of fulfillment", "成就感；满足感", "Teaching gives her a sense of fulfillment.", "教学给她带来成就感。", "sense of fulfillment 是固定名词短语，a 不能省略；不要只译成一般‘感觉’。", "名词短语"),
  c("pursuit of", "pursuit of + noun", "对……的追求", "The pursuit of knowledge requires patience.", "追求知识需要耐心。", "pursuit 是名词，of 引出追求对象；不要与 pursue 的动词结构混用。", "名词 + of 补足语"),
  c("pursue a goal", "pursue a goal", "追求目标", "They pursue a common goal.", "他们追求共同目标。", "pursue 是及物动词直接接 goal，不需要加 after 或 to。", "及物动词 + 宾语"),
  c("be related to", "be related to + noun", "与……有关联", "The symptoms may be related to stress.", "这些症状可能与压力有关。", "related to 表关联而非必然因果；to 在此是介词，后接名词或动名词。", "被动形容词搭配"),
  c("relate A to B", "relate A to B", "把 A 与 B 联系起来", "The study relates sleep quality to memory.", "这项研究把睡眠质量与记忆联系起来。", "relate 后接 A，再用 to 引出 B；不要把 to 换成 for。", "动词 + 宾语 + to"),
  c("draw a conclusion", "draw a conclusion", "得出结论", "We can draw a conclusion from the evidence.", "我们可以从证据中得出结论。", "draw 在此表示得出，不是‘画’；结论来源通常用 from。", "动词 + 名词"),
  c("in conclusion", "in conclusion", "总之；最后", "In conclusion, the policy needs revision.", "总之，这项政策需要修改。", "in conclusion 是总结性插入语，后接完整句子；不要与 consequently 混作因果连接。", "句子副词短语"),
  c("draw from", "draw from + source", "从……汲取；依据……", "The author draws from historical records.", "作者借鉴历史记录。", "draw from 引出信息或灵感来源；draw on 也可表示利用资源，但语气和搭配范围略有不同。", "动词 + 介词"),
  c("maintain an ambition", "maintain an ambition", "保持抱负", "She maintained an ambition to improve public services.", "她一直保持改善公共服务的抱负。", "maintain 可表示持续保持，不是单纯拥有；ambition 后可接 to do 说明目标。", "及物动词 + 宾语"),
  c("be maintained", "be maintained", "得到保持；被维持", "The standard must be maintained.", "这一标准必须得到保持。", "be maintained 是被动结构，主语是被保持的对象；不要漏掉 be。", "被动语态"),
];

const uniqueDefinitions = Array.from(
  new Map([...definitions, ...extraCollocations].map((item) => [item.source.toLowerCase(), item])).values(),
);

export const passage5PhraseGuides = Object.fromEntries(
  uniqueDefinitions.map((item) => [
    item.key,
    {
      key: item.key,
      sourceExpression: item.source,
      canonical: item.canonical,
      type: item.type,
      meaning: item.meaning,
      summary: "原文表达“" + item.source + "”；规范结构为“" + item.canonical + "”。" + item.meaning,
      grammarRole: item.grammarRole,
      structures: [s(item.canonical, item.meaning, item.rule, item.english, item.chinese)],
      pitfalls: item.pitfalls,
    },
  ]),
);

export const passage5PhraseAliases: Record<string, string> = Object.fromEntries(
  uniqueDefinitions.map((item) => [item.source.toLowerCase(), item.key]),
);

Object.assign(passage5PhraseAliases, {
  ...reusedPhraseAliases,
  "fix in one's mind": "fixed-in-the-mind-of",
  "drive a underground": "driven-underground",
  "well regarded": "is-to-be-well-regarded",
  "the sacrifices": "worthy-of-the-sacrifices",
  "benefits from ambition": "benefited-from-ambition",
  "maintained openly": "maintained-openly",
});

export const passage5CollocationGlosses: Record<string, { meaning: string; note?: string }> = Object.fromEntries(
  uniqueDefinitions.map((item) => [item.source.toLowerCase(), { meaning: item.meaning, note: item.rule }]),
);

export const passage5FamilyGlosses: Record<string, string> = {
  ambition: "抱负；雄心",
  admire: "钦佩；赞赏",
  benefit: "受益；好处",
  educate: "教育；培养",
  honor: "尊敬；荣誉",
  maintain: "维持；坚持",
  profess: "公开宣称",
  regard: "看待；尊重",
  reward: "奖励；回报",
  sacrifice: "牺牲；献出",
  succeed: "成功；继承",
  support: "支持；供养",
  probable: "很可能的；大概的",
  probability: "可能性；概率",
};

export const passage5WordKnowledge = {
  ambition: {
    grammarRole: "抽象名词",
    grammarSummary: "ambition 可作不可数概念名词表示抱负，也可用 one's ambition 表个人目标；本文与 rewards、sacrifices 构成价值判断。",
    structures: [
      s("ambition to do sth", "做某事的抱负", "ambition 后可接不定式说明目标。", "Her ambition to teach inspired the class.", "她从事教学的抱负鼓舞了全班。"),
      s("on behalf of ambition", "为了抱负", "on behalf of 后接代表或受益对象。", "They acted on behalf of a shared ambition.", "他们为了共同的抱负而行动。"),
    ],
    pitfalls: ["ambition 是名词；ambitious 是形容词。", "抱负本身不等于 greed，需结合回报和社会评价判断。"],
  },
  benefit: {
    grammarRole: "动词/名词",
    grammarSummary: "benefit from 表示从某来源受益；benefit 作名词时可表示好处。",
    structures: [s("benefit from + source", "从……中受益", "from 后接带来好处的来源。", "Students benefit from feedback.", "学生从反馈中受益。")],
    pitfalls: ["benefit from 与 benefit somebody 的主客体方向不同。"],
  },
  regard: {
    grammarRole: "动词/名词",
    grammarSummary: "be regarded as 表示被看作；be well/highly regarded 表示受到评价。",
    structures: [s("be regarded as + noun", "被视为……", "as 后接身份或性质补语。", "The method is regarded as reliable.", "这种方法被视为可靠。")],
    pitfalls: ["regard A as B 不能漏掉 as；regard 作名词时还可表示尊重或方面。"],
  },
  confess: {
    grammarRole: "及物/不及物动词",
    grammarSummary: "confess to + 名词或 doing 表示承认；confess sth to sb 表向某人坦白某事。",
    structures: [s("confess to doing", "承认做过某事", "to 是介词，后接动名词。", "He confessed to hiding the file.", "他承认藏起了文件。")],
    pitfalls: ["不要写 confess to do；承认对象和承认对象的听者都要区分。"],
  },
  maintain: {
    grammarRole: "及物动词",
    grammarSummary: "maintain + 名词表示保持、维持或坚持观点；被动 should be maintained 表应当维持。",
    structures: [s("maintain + balance/standard", "维持平衡或标准", "maintain 直接接宾语。", "The team maintains high standards.", "团队保持高标准。")],
    pitfalls: ["maintain 不等于 merely keep 的所有语境；maintain an opinion 还可表示坚持观点。"],
  },
} satisfies Record<string, { grammarRole: string; grammarSummary: string; structures: Structure[]; pitfalls?: string[] }>;
