import type { PracticeTask, GrammarConceptId, ErrorCategory } from "./learning-model";
const choice = (id: string, prompt: string, options: string[], answer: number, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "choice", prompt, options, answer: options[answer], evidence, feedback, conceptId, errorType, ...extra });
const range = (id: string, prompt: string, answer: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "range", prompt, answer, evidence: answer, feedback, conceptId, errorType, ...extra });
const order = (id: string, prompt: string, blocks: string[], distractors: string[], evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "order", prompt, options: [...blocks, ...distractors], answer: JSON.stringify(blocks), evidence, feedback, conceptId, errorType, ...extra });
const link = (id: string, prompt: string, pairs: Array<[string, string]>, evidence: string, feedback: string, conceptId: GrammarConceptId, errorType: ErrorCategory, extra: Partial<PracticeTask> = {}): PracticeTask => ({ id, revision: 1, kind: "link", prompt, links: pairs.map(([source, target]) => ({ source, target })), options: pairs.map(([, target]) => target), answer: JSON.stringify(pairs.map(([, target]) => target)), evidence, feedback, conceptId, errorType, ...extra });
export const passage4Practice: Record<string, PracticeTask[]> = {
 "p4-s1": [choice("hardly-scope", "本句对缺乏目标作了哪种判断？", ["它几乎不是战后日本的典型特点", "它一向是战后日本的典型特点", "美国和欧洲都没有目标"], 0, "Aimlessness has hardly been typical", "hardly否定typical，不能漏掉近否定，把正面背景读反。", "negation-contrast", "option-logic", { hintWords: ["hardly", "Aimlessness", "has hardly been typical of"], mapRevealsAnswer: true }), link("envy-roles", "连清所属与羡慕的方向。", [["whose", "日本的：限定生产力与社会和谐"], ["the United States and Europe", "羡慕者"]], "whose productivity and social harmony are the envy of the United States and Europe", "whose表示所属，整个从句主语是日本的生产力和社会和谐；它们成为欧美羡慕的对象。", "reference-pronoun", "reference", { hintWords: ["whose", "envy", "the envy of"] })],
 "p4-s2": [order("seeing-decline", "删去句首连接与趋势状语，拼回主谓宾。", ["the Japanese", "are seeing", "a decline of the traditional work-moral values"], ["increasingly", "But"], "the Japanese are seeing a decline of the traditional work-moral values", "decline在这里是名词宾语，are seeing才是谓语。", "basic-svo", "predicate", { hintWords: ["seeing", "decline", "seeing a decline of"] })],
 "p4-s3": [link("past-now", "把时间与对应动词组相连。", [["Ten years ago", "were hardworking and saw their jobs as..."], ["now", "Japan has largely fulfilled... and young people don't know..."]], "Ten years ago young people were hardworking", "过去的勤奋和工作意义，与如今需求满足后的方向困惑形成对照。", "time-reference", "tense", { hintWords: ["ago", "now", "were", "has", "Ten years ago"] }), range("where-content", "划出know后的完整宾语从句。", "where they should go next", "间接疑问从句保持they should go的陈述语序，where问方向，next给下一步。", "clause-object", "clause-boundary", { hintWords: ["where", "should", "where they should go next"] })],
 "p4-s4": [range("two-events", "划出have limited之前的完整并列主语。", "The coming of age of the postwar baby boom and an entry of women into the male-dominated job market", "两个并列名词化事件共同作主语，所以用have；women只是entry的参与者。", "basic-svo", "predicate", { hintWords: ["coming", "entry", "have", "coming of age", "entry of women into"] }), link("nested-modifiers", "将两层后置说明接回各自的名词。", [["who are already questioning...", "teen-agers：正在质疑的青少年"], ["involved in climbing...", "sacrifices：攀爬阶梯所涉及的牺牲"]], "teen-agers who are already questioning the heavy personal sacrifices involved in climbing", "who从句修饰teen-agers，involved分词短语在该从句内部修饰sacrifices；层级不能并成一个长谓语。", "modifier-prepositional", "attachment", { hintWords: ["who", "questioning", "involved", "sacrifices"] })],
 "p4-s5": [range("reported-subject", "划出it was found对应的后置真正主语，不含比较补充。", "that only 24.5 percent of Japanese students were fully satisfied with school life", "that整组说明被发现的内容；it先占主语位置，compared with之后另补美国比例。", "clause-subject", "clause-boundary", { hintWords: ["it", "that", "found", "it was found that"] }), link("two-denominators", "把满意比例接回各自的统计群体。", [["24.5 percent", "日本学生"], ["67.2 percent", "美国学生"]], "compared with 67.2 percent of students in the United States", "两项都是各自国家学生满意学校生活的比例，不是增长幅度，也不共用两国学生总数。", "comparison-scope", "option-logic", { hintWords: ["percent", "only", "compared with"] })],
 "p4-s6": [choice("more-workers", "far more直接增加的是什么？", ["表达不满的日本工人的数量", "每名工人的不满程度", "工作本身的数量"], 0, "far more Japanese workers", "more限定workers，far加强比较差距；原文未给比例的分母，不能自行说不满比例。", "comparison-scope", "option-logic", { hintWords: ["far", "more", "workers", "far more"] }), choice("did-substitute", "than did their counterparts中的did起什么作用？", ["替代前面表达工作不满的动作", "表示做出了对照工人", "是调查国家的主语"], 0, "than did their counterparts in the 10 other countries surveyed", "did代替expressed dissatisfaction with their jobs；counterparts为倒装后置主语，surveyed修饰countries。", "finite-predicate", "predicate", { hintWords: ["did", "counterparts", "surveyed", "than did"] })],
 "p4-s7": [choice("reduced-while", "While often praised省略的共同主语是谁？", ["Japanese education", "foreigners", "creativity"], 0, "While often praised by foreigners", "被称赞的是日本教育；foreigners在by后表示称赞者。省略主语和be后，praised仍是被动分词。", "negation-contrast", "clause-boundary", { hintWords: ["While", "praised", "foreigners", "praised by foreigners"] }), link("stress-over", "区分教育倾向中被优先与被压低的两组。", [["test taking and mechanical learning", "更被重视的做法"], ["creativity and self-expression", "相对被轻视的素质"]], "stress test taking and mechanical learning over creativity and self-expression", "stress A over B表示重A轻B；不是把四项并列为同等重视。", "comparison-scope", "option-logic", { hintWords: ["stress", "over", "over creativity and self-expression"], mapRevealsAnswer: true })],
 "p4-s8": [order("ignored-trunk", "去掉主语后的定语、例项与报道语，拼回引语主干。", ["Those things", "are completely ignored"], ["personality, ability, courage or humanity", "says Toshiki Kaifu"], "Those things that do not show up in the test scores", "Those things是主语中心，are ignored是被动谓语；中间定语和例项都不能取代它们。", "passive-voice", "predicate", { hintWords: ["things", "ignored", "are completely ignored"] }), choice("kaifu-voice", "chairman of...补充谁的身份？", ["Toshiki Kaifu", "Those things", "Japanese students"], 0, "Toshiki Kaifu, chairman of the ruling Liberal Democratic Party's education committee", "chairman为人物同位语，says的后置主语是Toshiki Kaifu；不把职位并入被引判断。", "apposition", "attachment", { hintWords: ["chairman", "says", "chairman of"] })],
 "p4-s9": [order("causal-direction", "按原句因果方向排列主语、谓语、宾语与补足动作。", ["Frustration against this kind of thing", "leads", "kids", "to drop out and run wild"], ["test scores"], "Frustration against this kind of thing leads kids to drop out and run wild", "原因是对这种教育的挫败感，结果是辍学失控；题25D把因果倒转。", "object-complement", "passage-logic", { hintWords: ["Frustration", "leads", "drop out", "run wild", "leads kids to"], mapRevealsAnswer: true })],
 "p4-s10": [choice("including-subset", "包括929起袭击教师后，总校园暴力事件应怎样理解？", ["929起属于2125起中的一部分", "两组相加得到总数", "2125起只是袭击教师事件"], 0, "2,125 incidents of school violence, including 929 assaults on teachers", "including引出总数内的一个子类，on teachers说明袭击对象，不增加总数。", "comparison-scope", "option-logic", { hintWords: ["including", "incidents", "assaults", "including 929 assaults on teachers"] })],
 "p4-s11": [link("return-emphasis", "把两个介词关系接回中心词。", [["to the prewar emphasis...", "return：回归的目标"], ["on moral education", "emphasis：重视的对象"]], "a return to the prewar emphasis on moral education", "return是seeking的名词宾语，to与on各接一层，不能把它看成并列两个动词。", "modifier-prepositional", "attachment", { hintWords: ["return", "emphasis", "prewar emphasis on"] })],
 "p4-s12": [order("setoyama-trunk", "只保留部长引起反应的主句，去掉身份和时间从句。", ["Mitsuo Setoyama", "raised", "eyebrows"], ["who was then education minister", "when he argued"], "Mitsuo Setoyama, who was then education minister, raised eyebrows", "who只补身份，when解释引起惊讶时说了什么；主句谓语是raised，eyebrows为习语宾语。", "basic-svo", "predicate", { hintWords: ["who", "when", "raised", "eyebrows", "raised eyebrows"] }), choice("minister-claim", "改革削弱尊重父母道德的说法首先属于谁？", ["被引述的部长", "作者已经证实的唯一原因", "欧美学生"], 0, "he argued that liberal reforms", "he argued标明部长主张；下一句But会把作者解释转向日本生活方式，不能直接替换观点主体。", "author-voice", "passage-logic", { hintWords: ["argued", "he argued that"], mapRevealsAnswer: true })],
 "p4-s13": [choice("qualified-cause", "may have more to do with保留了哪一种判断强度？", ["可能与生活方式更加相关", "唯一确定原因就是西方教育改革", "完全与生活方式无关"], 0, "may have more to do with Japanese life-styles", "may表示可能，more给相对侧重；作者未在本句明确给出Western values或唯一因果。", "author-voice", "option-logic", { hintWords: ["may", "more", "have more to do with"], mapRevealsAnswer: true })],
 "p4-s14": [range("whether-content", "划出whether引出的完整间接疑问，不选but后的内容。", "whether you enjoy your job and your life", "这组作of的宾语，问是否快乐；whether不表示条件。", "clause-object", "clause-boundary", { hintWords: ["whether", "enjoy", "a question of whether"] }), choice("how-much-role", "how much在you can endure内补足什么？", ["endure的宾语：能忍受多少", "you的同位人名", "与工作并列的地点"], 0, "how much you can endure", "you是主语，can endure为谓语，how much作前置宾语；后半省去重复的a question of。", "clause-object", "predicate", { hintWords: ["how", "much", "endure", "how much you can endure"] })],
 "p4-s15": [choice("inverted-subject", "With economic growth has come centralization的主语是？", ["centralization", "economic growth", "With"], 0, "With economic growth has come centralization", "centralization是后置主语，has come为前置谓语；With引出的经济增长是背景。", "subject-head", "predicate", { hintWords: ["come", "centralization", "has come centralization"] }), link("replacement-direction", "把新旧社会形式连到各自的位置。", [["community and the extended family", "被舍弃的旧形式"], ["isolated, two-generation households", "转而选择的新形式"]], "community and the extended family have been abandoned in favor of isolated, two-generation households", "in favor of后是新选择；被动主语才是被舍弃的一方，不把取代方向倒过来。", "passive-voice", "reference", { hintWords: ["abandoned", "favor", "in favor of"], mapRevealsAnswer: true })],
 "p4-s16": [range("as-change", "划出解释价值观变化背景的完整从句。", "as the old group and family values weaken", "中心主语是values，weaken不及物；整组给不适显效提供伴随变化背景。", "clause-time", "clause-boundary", { hintWords: ["as", "values", "weaken", "as the old group and family values weaken"] }), choice("tell-effect", "to tell在本句表示什么？", ["产生影响、显出后果", "告诉别人一个故事", "确定他们已不再痛苦"], 0, "the discomfort is beginning to tell", "tell不带宾语，指不适开始显效；have endured只是长期忍受，没有说已经习惯。", "lexical-context", "vocabulary", { hintWords: ["tell", "discomfort", "is beginning to tell"], mapRevealsAnswer: true })],
 "p4-s17": [choice("level-growth", "日本离婚率仍低于美国，同时自身增长50%以上，这两点是否矛盾？", ["不矛盾：一个比国家间水平，一个比自身变化", "矛盾：增长50%就必定超过美国", "原文说日本没有增长"], 0, "while still well below that of the United States", "while给水平让步，by给自身增幅；日本仍低于美国，与它比以前增长可以同时成立。", "comparison-scope", "option-logic", { hintWords: ["while", "below", "by", "well below that of"], mapRevealsAnswer: true, leaksToTaskIds: ["by-increase"] }), link("by-increase", "把两个增幅接回统计对象。", [["more than 50 percent", "日本离婚率比先前的增幅"], ["nearly one-quarter", "自杀事件比先前的增幅"]], "has increased by more than 50 percent, and suicides have increased by nearly one-quarter", "by后写增加了多少；没有把suicides写成自杀率，也没有说离婚率达到50%。", "comparison-scope", "option-logic", { hintWords: ["by", "percent", "suicides", "by nearly one-quarter"] })],
};
