import type { BeginnerClauseDetail, BeginnerSyntaxComponent, Question, QuestionAnalysis, SentenceAnalysis, SyntaxVisualRole } from "./data";
import { withReviewedSyntax } from "./reviewed-syntax";
const c=(text:string,form:string,fn:string,modifies:string,explanation:string,children?:BeginnerSyntaxComponent[]):BeginnerSyntaxComponent=>({text,form,function:fn,modifies,explanation,children});
const cl=(text:string,type:string,marker:string,role:string,subject:string,predicate:string,details:Array<[string,string]>):BeginnerClauseDetail=>({text,type,marker,role,subject,predicate,predicateDetails:details.map(([fn,text])=>({function:fn,text})),translationOrder:"先读本组真实主谓，再接宾语、表语或补足；题干空缺由选项补全，不编造原文。"});
const make=(base:SentenceAnalysis,components:BeginnerSyntaxComponent[],colors:SyntaxVisualRole[],trunk:string,focus:string,clauses:BeginnerClauseDetail[]=[],phrase=false):SentenceAnalysis=>withReviewedSyntax({...base,trunk,textKind:phrase?"phrase":"sentence",beginnerSyntax:{components,clauses},layers:[{label:"语言关系",text:focus}],grammar:[focus],logic:"先理解本项实际文字；其是否成立另由题目证据判断。"},colors);
const sub=(t:string,p:string,e:string)=>c(t,"名词性成分","主语",p,e);
const pred=(t:string,s:string,e:string)=>c(t,"有限谓语","谓语",s,e);
const comp=(t:string,p:string,e:string,ch?:BeginnerSyntaxComponent[])=>c(t,"形容词或名词补足","表语",p,e,ch);
const mod=(t:string,p:string,e:string,ch?:BeginnerSyntaxComponent[])=>c(t,"介词或状语短语","限定或补足",p,e,ch);
const according=mod("According to the author","后面判断","限定观点属于文章作者，不替换成被引者。"), accordingLower=mod("according to the author","true","限定正确性依据。"), eyes=mod("In the Westerners' eyes","was","表评价来源，eyes不按视觉器官直译整组。"), lifeSubject=sub("The life-style","has been influenced","life-style为单数名词，题目将其作为受影响对象。");
const lifeParts=[lifeSubject,pred("has been influenced","The life-style","现在完成时被动；been与influenced共同构成语态。"),mod("by Western values","has been influenced","by引出施加影响的一方；Western修饰values。")];
const cultivate=(initial:string)=>[sub(initial,"should be placed","stress为不可数名词重视，more是数量限定。"),pred("should be placed",initial,"情态动词加被动，表示应给予重视。"),mod("on the cultivation of creativity","placed","on给重视对象，of说明所培养的是创造力。",[c("of creativity","介词短语","内容限定","cultivation","creativity是培养的对象。")])];
export function passage4QuestionAnalysis(question:Question):QuestionAnalysis {
 const old=question.analysis!,o=old.options!;let prompt:SentenceAnalysis,answer:SentenceAnalysis;const options:Record<string,SentenceAnalysis>={};
 if(question.id===23){
  const head=[eyes,sub("the postwar Japan","was","指战后日本，限定题问时间。"),pred("was","the postwar Japan","表语由选项补足，原题以句号结束。")];
  prompt=make(old.prompt!,head,["modifier","subject","predicate"],"the postwar Japan was","题干是待补表语的主系框架，评价来自西方人。不能添加原文没有的description词。");
  options.A=make(o.A!,[c("under","介词","介词中心","development","引出所处状态。"),c("aimless development","名词短语","介词宾语","under","aimless修饰development，表示缺乏目标的发展。")],["complement","object"],"under aimless development","under加名词构成状态短语，没有独立主谓。",[],true);
  options.B=make(o.B!,[c("a positive","冠词及形容词","前置限定","example","positive说明正面意义。"),c("example","名词","短语中心","题干was","作为范例这一身份。")],["modifier","complement"],"a positive example","整个名词短语作待补表语，不把positive当谓语。",[],true);
  options.C=make(o.C!,[c("a rival","名词短语","短语中心","题干was","指竞争对手。"),mod("to the West","rival","to是介词，指定竞争对方。")],["complement","modifier"],"a rival to the West","to the West修饰rival，非目的不定式。",[],true);
  options.D=make(o.D!,[c("on","介词","固定状态结构","decline","与the decline构成处于衰退中的含义。"),c("the decline","名词短语","介词宾语","on","decline是名词，不是下降的谓语。")],["complement","object"],"on the decline","on the decline为完整介词状态短语，可作was后的表语。",[],true);
  answer=make(old.answer!,[...head,comp("a positive example","was","给出正面典范的分类。")],["modifier","subject","predicate","complement"],"the postwar Japan was a positive example","本补全示例用名词短语作表语。");
 } else if(question.id===24){
  prompt=make(old.prompt!,[according,sub("what","may be","疑问代词直接充当主语。"),pred("may chiefly be","what","may给可能性，chiefly限定主要程度，be连接责任补足。"),comp("responsible","be","形容词表语，并非一个被动分词。"),mod("for the moral decline of Japanese society","responsible","for引出对哪种结果负责；of说明日本社会的衰退。")],["modifier","subject","predicate","complement","modifier"],"what may chiefly be responsible for the moral decline of Japanese society","what本身作疑问主语，后面无需再补一个倒装主语；responsible for是形容词结构。");
  options.A=make(o.A!,[sub("Women's participation in social activities","is limited","中心participation是单数，Women's为参与者，in说明参与领域。"),pred("is limited","participation","被限制的状态或被动判断；不把women当主语中心。")],["subject","predicate"],"Women's participation is limited","participation是名词主语，社会活动是in后的领域，并非participate的动词形式。");
  options.B=make(o.B!,[sub("More workers","are","more数量限定workers。"),pred("are","More workers","系动词，连接不满状态。"),comp("dissatisfied","are","形容词表语，not satisfied的词汇否定。"),mod("with their jobs","dissatisfied","with引出不满对象，their指workers。")],["subject","predicate","complement","modifier"],"More workers are dissatisfied with their jobs","more谈人数，不是dissatisfied程度比较。");
  options.C=make(o.C!,[sub("Excessive emphasis","has been placed","emphasis不可数，excessive说明过度。"),pred("has been placed","emphasis","现在完成时被动。"),mod("on the basics","placed","on给重视对象；basics为基础知识的名词化复数。")],["subject","predicate","modifier"],"Excessive emphasis has been placed on the basics","place emphasis on的被动将emphasis移为主语，不是on引出的宾语从句。");
  options.D=make(o.D!,lifeParts,["subject","predicate","modifier"],"The life-style has been influenced by Western values","by Western values表示影响来源；词义解释与该选项较间接的证据强度分开。");
  answer=make(old.answer!,[according,...lifeParts.map((p,i)=>i===0?{...p,text:"the life-style"}:p)],["modifier","subject","predicate","modifier"],"the life-style has been influenced by Western values","保留原补全语言示例；作者归因与Western values概括的边界另见证据说明。");
 } else if(question.id===25){
  prompt=make(old.prompt!,[sub("Which of the following","is","Which是疑问中心，of the following限定候选范围。"),pred("is","Which","询问哪一项成立。"),comp("true","is","形容词表语，表示符合事实或文意。"),accordingLower],["subject","predicate","complement","modifier"],"Which of the following is true","主语疑问句保持Which...is顺序，according to限定作者立场。");
  options.A=make(o.A!,[sub("Japanese education","is praised","被评价的是教育。"),pred("is praised","Japanese education","现在时被动，施事未明写。"),mod("for helping the young climb the social ladder","praised","for接动名词短语表示受赞原因。",[c("helping the young climb the social ladder","动名词及复合宾语","介词宾语","for","help后为the young宾语和climb补足动作。",[c("the young","名词化形容词","宾语兼climb执行者","helping","泛指年轻人。"),c("climb the social ladder","不带to的不定式","宾语补足语","the young","climb支配the social ladder，不是独立有限谓语。")])])],["subject","predicate","modifier"],"Japanese education is praised for helping the young climb the social ladder","help somebody do结构中climb省略to；整个helping短语作for的宾语，不编成that从句。");
  options.B=make(o.B!,[sub("Japanese education","is characterized","被描述的教育。"),pred("is characterized","Japanese education","被动，be characterized by表示以某特征为特点。"),mod("by mechanical learning as well as creativity","characterized","as well as连接机械学习和创造力，表示两者都包括。")],["subject","predicate","modifier"],"Japanese education is characterized by mechanical learning as well as creativity","as well as构成并列添加，不等于原文over的轻重取舍。");
  options.C=make(o.C!,cultivate("More stress"),["subject","predicate","modifier"],"More stress should be placed on the cultivation of creativity","stress是名词重视；more为数量限定；on的对象是创造力培养。");
  options.D=make(o.D!,[sub("Dropping out","leads","动名词化的辍学作单数主语。"),pred("leads","Dropping out","后接to介词表示导致。"),mod("to frustration against test taking","leads","to接frustration名词，不是不定式；against后为引起挫败的考试做法。")],["subject","predicate","modifier"],"Dropping out leads to frustration against test taking","lead to后接名词结果；本选项把辍学当原因，不能把语法解释改成原文相反方向。");
  answer=make(old.answer!,[according,...cultivate("more stress")],["modifier","subject","predicate","modifier"],"more stress should be placed on the cultivation of creativity","名词重视作主语，被动结构提出应加强创造力培养的建议。");
 } else {
  const main=[sub("The change in Japanese life-style","is revealed","中心change，in限定生活方式领域。"),pred("is revealed","The change","被动，指变化得以体现。")];
  prompt=make(old.prompt!,[...main,mod("in the fact","is revealed","in引出体现变化的事实。"),c("that","内容连接词","待补事实内容标记","fact","原题只给that，具体主谓由选项提供，不虚构空白内容从句。")],["subject","predicate","modifier","connector"],"The change in Japanese life-style is revealed in the fact that","that将引出fact的内容，目前只有连接词，没有可分析的从句主谓。");
  const young=[sub("the young","are","the加形容词表示年轻人群体，使用复数are。"),pred("are","the young","连接容忍状态。"),comp("less tolerant","are","less比较容忍程度，tolerant是形容词。"),mod("of discomforts in life","tolerant","of补足容忍对象；in life限定不适来自生活。")];
  options.A=make(o.A!,young,["subject","predicate","complement","modifier"],"the young are less tolerant of discomforts in life","be tolerant of为形容词补足结构，less说明容忍程度降低。");
  options.B=make(o.B!,[sub("the divorce rate in Japan","exceeds","中心rate是单数，in Japan限定国家。"),pred("exceeds","the divorce rate","及物动词超过，后面直接带比较对象。"),c("that in the U.S.","替代代词及国家限定","宾语","exceeds","that代divorce rate；in the U.S.限定美国对应指标。")],["subject","predicate","object"],"the divorce rate in Japan exceeds that in the U.S.","that不是引导从句，而是替代名词rate，U.S.保持原缩写形式。");
  options.C=make(o.C!,[sub("the Japanese","endure","名词化国籍形容词，表示日本人。"),pred("endure","the Japanese","承受、忍耐。"),c("more","比较数量成分","承受量比较","endure","这里表示承受更多，非比较人数。"),mod("than ever before","more","比较先前任何时候，不是额外完整主谓从句。")],["subject","predicate","object","modifier"],"the Japanese endure more than ever before","than ever before省略重复信息，不能凭此推出原文已有承受总量统计。");
  options.D=make(o.D!,[sub("the Japanese","appreciate","群体主语。"),pred("appreciate","the Japanese","欣赏、珍视。"),c("their present life","名词短语","宾语","appreciate","present是形容词当前的，修饰life。")],["subject","predicate","object"],"the Japanese appreciate their present life","present life表示当前生活，不是礼物，their回指日本人。");
  const full="that the young are less tolerant of discomforts in life";
  answer=make(old.answer!,[...main,mod(`in the fact ${full}`,"is revealed","fact后that说明其具体内容。",[c(full,"that内容从句","同位语从句","fact","内容为年轻人对生活不适的容忍程度较低。",young)])],["subject","predicate","modifier"],"The change in Japanese life-style is revealed in the fact that the young are less tolerant of discomforts in life","本补全示例的that从句解释fact；原题干只有that时不预造这一从句。",[cl(full,"同位语从句","that","解释fact的内容","the young","are",[["表语","less tolerant of discomforts in life"]])]);
 }
 if(question.id===26) options.C={...options.C!,natural:"日本人比以往任何时候承受得更多。"};
 return {prompt,options,answer};
}
