import type { PracticeTask,GrammarConceptId,ErrorCategory } from "./learning-model";
const choice=(id:string,prompt:string,options:string[],index:number,evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:"choice",prompt,options,answer:options[index],evidence,feedback,conceptId,errorType,...extra});
const range=(id:string,prompt:string,answer:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:"range",options:[],prompt,answer,evidence:answer,feedback,conceptId,errorType,...extra});
const link=(id:string,prompt:string,pairs:Array<[string,string]>,evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:"link",prompt,links:pairs.map(([source,target])=>({source,target})),options:pairs.map(([,t])=>t),answer:JSON.stringify(pairs.map(([,t])=>t)),evidence,feedback,conceptId,errorType,...extra});
const order=(id:string,prompt:string,blocks:string[],distractors:string[],evidence:string,feedback:string,conceptId:GrammarConceptId,errorType:ErrorCategory,extra:Partial<PracticeTask>={}):PracticeTask=>({id,revision:1,kind:"order",prompt,options:[...blocks,...distractors],answer:JSON.stringify(blocks),evidence,feedback,conceptId,errorType,...extra});
export const passage5Practice:Record<string,PracticeTask[]>={
 "p5-s1":[choice("reward-balance","作者所设的认可条件是什么？",["回报被认为值得相应牺牲","只要得到金钱就足够","只要目标完全无物质性"],0,"must be deemed worthy of the sacrifices made on ambition's behalf","worthy把回报与牺牲联系起来，不是单独出现wealth就达到条件。","comparison-scope","option-logic",{hintWords:["worthy","sacrifices","worthy of the sacrifices"],mapRevealsAnswer:true}),range("reward-subject","只划出主语中心短语，不包含破折号内的例项。","the rewards of ambition","rewards是主语，wealth等为同位列举；must be deemed在例项之后才开始。","subject-head","subject",{hintWords:["rewards","wealth","deemed"]})],
 "p5-s2":[choice("not-least","not least among them怎样定位受教育者？",["尤其包括他们，且他们是重要一类","将他们排除在外","说他们最不重要"],0,"the educated not least among them","not least用否定最低来强调重要性，不是至少包括的数量表达。","negation-contrast","vocabulary",{hintWords:["least","educated","not least among them"],mapRevealsAnswer:true}),link("two-admirations","把被认可对象接回各层。",[["it must be highly regarded","抱负传统受重视"],["who are themselves admired","认可者自身受敬仰"]],"it especially must be highly regarded by people who are themselves admired","两个被动句对应不同主语，who回指people，themselves只强调这些人本人。","reference-pronoun","reference",{hintWords:["it","who","themselves","admired","highly regarded by"]})],
 "p5-s3":[choice("cleft-focus","it is...who强调了谁？",["the educated","ambition","an ideal"],0,"it is the educated who have claimed","焦点是受教育者，强调他们本应认可却声称放弃的反差；it不指抱负。","basic-svc","subject",{hintWords:["it","who","educated","it is the educated who"]}),choice("perfect-infinitive","to have given up与have claimed是什么关系？",["完成不定式说明所称放弃先于声称","两个并列有限完成时","普通过去分词修饰ideal"],0,"have claimed to have given up on ambition as an ideal","have claimed是有限谓语，to have given up是claim后的完成不定式；不把声称当作事实已被作者核验。","nonfinite-infinitive","tense",{hintWords:["to","have","claimed","given","given up on"]})],
 "p5-s4":[link("what-that","把两个连接形式的内部作用连正确。",[["What","在What is odd内部作主语"],["that","只连接表语内容，不作内部成分"]],"What is odd is that they have perhaps most benefited from ambition","外层主语从句与表语从句分开；What自身有主语功能，that没有。","clause-predicative","clause-boundary",{hintWords:["What","that","what is odd is that"]}),choice("ambition-sources","their own与that of their parents...共同省略或替代哪一个名词？",["ambition","wealth","the educated"],0,"if not always their own then that of their parents and grandparents","比较自身与父辈的抱负来源，不是把that指成父母或财富。","reference-pronoun","reference",{hintWords:["own","that","that of their parents and grandparents"]})],
 "p5-s5":[link("horses-riders","把比喻里的角色接回对应关系。",[["them","已逃走的马"],["the educated themselves","骑在马上、已经获益的人"]],"with the educated themselves riding on them","骑马者正是受教育者，说明他们享受了抱负的好处后又声称放弃；them不指受教育者。","reference-pronoun","reference",{hintWords:["them","themselves","riding","riding on them"],mapRevealsAnswer:true}),range("after-clause","划出说明关门时机的完整时间从句。","after the horses have escaped","after有完整主谓the horses have escaped，先跑马再关门；closing自身仍为动名词。","clause-time","clause-boundary",{hintWords:["after","horses","escaped","closing the barn door after the horses have escaped"]})],
 "p5-s6":[choice("not-less-interest","do not seem less interested最稳妥地表示什么？",["看不出兴趣比过去减少","所有人的兴趣都明显增加","成功的标志已经完全消失"],0,"do not seem less interested in success and its signs now than formerly","not less排除减少，但不保证每个人都增加；formerly只提供比较过去。","negation-contrast","option-logic",{hintWords:["not","less","formerly","less interested in","than formerly"],mapRevealsAnswer:true})],
 "p5-s7":[choice("surface-demand","地点品牌改变，与需求之间是什么关系？",["外在标志可变，需求未显减少","名称变动证明需求完全消失","原句已经精确证明二十年增幅"],0,"the locations, place names and name brands may change, but such items do not seem less in demand","but对照表面变化与需求不减；过去时间措辞本身有疑点，不能编成精确增长统计。","paragraph-role","passage-logic",{hintWords:["change","demand","less in demand"],mapRevealsAnswer:true})],
 "p5-s8":[range("lest-worry","划出lest引出的完整顾虑从句。","lest they be thought pushing, acquisitive and vulgar","be thought是被动，三个形容词说明怕被别人评价成什么；不是自己认定抱负不道德。","clause-purpose","clause-boundary",{hintWords:["lest","be","thought","lest they be thought"],leaksToTaskIds:["appearance-motive"]}),choice("appearance-motive","人们不坦承梦想，主要怕的是什么？",["别人把自己看得贪婪庸俗","自己绝无物质梦想","抱负与成功完全无关"],0,"lest they be thought pushing, acquisitive and vulgar","被动thought标出对他人眼光的顾虑，不能偷换成内心毫无欲望。","author-voice","option-logic",{hintWords:["thought","pushing","acquisitive","vulgar"],mapRevealsAnswer:true})],
 "p5-s9":[link("three-attachments","把三个关系形式接回各自先行项。",[["which now more than ever seem...","hypocritical spectacles"],["who takes his meals...","the publisher"],["whose own children...","the journalist"]],"fine hypocritical spectacles, which now more than ever seem in ample supply","which说场面之多，who说出版商用餐，whose说记者孩子；不能把三例读成同一人。","clause-relative","attachment",{hintWords:["which","who","whose","publisher","journalist"]}),range("publisher-clause","只划出修饰出版商的完整定语从句。","who takes his meals in three-star restaurants","who回指publisher，takes是谓语，his meals是宾语，in短语给地点。","clause-relative","clause-boundary",{hintWords:["who","takes","meals","restaurants"]})],
 "p5-s10":[choice("ironic-rule","不惜代价成功却不显抱负的口号，作者在这里做什么？",["讽刺概括他人的矛盾行为","认真建议读者隐藏梦想","证明成功与抱负没有关系"],0,"the proper formulation is","承接hypocritical examples，作者概括这类人的行为逻辑；不能把被批评的口号当作者主张。","author-voice","passage-logic",{hintWords:["formulation","proper","ambitious","avoid appearing ambitious"],mapRevealsAnswer:true}),range("avoid-object","划出avoid的完整动名词宾语，不含avoid。","appearing ambitious","appearing为动名词，ambitious在内部作appear的表语；avoid不能在本结构直接接to appear。","nonfinite-gerund","predicate",{hintWords:["avoid","appearing","ambitious","avoid appearing ambitious"]})],
 "p5-s11":[choice("where-situation","where they are not extremely unattractive中的where表达什么？",["评价适用的情境：即使还不至于极其反感","辩护者居住的具体城市","已经确认全部辩护者都极其反感"],0,"where they are not extremely unattractive","where在这里不是地点，not仍否定极其反感这一程度；即使不到这一步，他们也缺乏号召力。","negation-contrast","clause-boundary",{hintWords:["where","not","extremely","where they are not"]})],
 "p5-s12":[order("support-trunk","去掉同位补充，按原文次序拼回主要判断。",["the support for ambition as a healthy impulse","is","probably","lower"],["a quality to be admired","the young"],"the support for ambition as a healthy impulse","主语中心support，quality是补充说明；probably保留可能性，lower比较社会支持程度。","basic-svc","subject",{hintWords:["support","quality","lower","probably"]}),choice("support-reference","than it has ever been中的it指什么？",["the support for ambition","the young","a healthy body"],0,"than it has ever been in the United States","比较的是支持程度的今昔，不是年轻人年龄或抱负是否存在。","reference-pronoun","reference",{hintWords:["it","support","lower than it has ever been"]})],
 "p5-s13":[link("three-contents","把三项内容放回否定或肯定范围。",[["ambition is at an end","作者否定这一解释"],["people no longer feel its stirrings and promptings","作者也否定这一解释"],["it is less openly professed","作者真正肯定的变化"]],"This does not mean that ambition is at an end","not mean管前两个that，but only转到第三个；变化是公开宣称较少，不是抱负消失。","negation-contrast","option-logic",{hintWords:["not","mean","but","only","less"],mapRevealsAnswer:true,leaksToTaskIds:["less-not-none"]}),choice("less-not-none","less openly professed能否译成完全不再公开承认？",["不能，只表示公开宣称较少","可以，less等于完全没有","可以，因为honored与professed同一个词"],0,"it is less openly professed","no longer只在插入的honored结构里，professed前是less，程度不能跨层替换。","comparison-scope","translation",{hintWords:["less","no","longer","openly professed"]})],
 "p5-s14":[choice("some-consequences","some of which中的which回指什么？",["Consequences","ambition","people"],0,"Consequences follow from this, of course, some of which","其中一些说的是后果，some of which整体作are主语，后面that再说明其内容。","reference-pronoun","reference",{hintWords:["Consequences","some","which","some of which"]}),link("two-results","区分两个结果补足的形式。",[["underground","转入隐蔽状态的方向副词"],["sly","被变成的性质形容词"]],"ambition is driven underground, or made sly","driven与made共用is，underground不是名词宾语，sly不是新的动词。","object-complement","predicate",{hintWords:["driven","underground","made","sly","driven underground","made sly"]})],
 "p5-s15":[choice("fronted-such","Such, then, is the way things stand中前置了什么？",["表语Such，主语是the way things stand","主语Such，后面是宾语","动词trying的宾语"],0,"Such, then, is the way things stand","Such表语前置，things stand修饰way；后面三个人群用省略结构平行排列。","basic-svc","subject",{hintWords:["Such","way","stand","the way things stand"]}),choice("trying-status","trying to get on in life怎样连接people？",["分词后置定语，说明他们在努力什么","原文独立的现在进行时谓语","说明批评者都已成功的完成时"],0,"the majority of earnest people trying to get on in life","trying没有be构成有限进行时；to get on补足努力做什么，get on在此是生活中取得进展。","nonfinite-participle","predicate",{hintWords:["trying","people","get on in life"]})],
};
