import type { ArticleGuide,PassageEvidence } from "./article-teaching";
const s=(n:number)=>`p5-s${n}`,e=(n:number,quote:string,role:string):PassageEvidence=>({sentenceId:s(n),quote,role});
export const passage5Paragraphs=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]].map((g,i)=>({id:`p5-paragraph-${i+1}`,sentenceIds:g.map(s)}));
export const passage5Guide:ArticleGuide={
 mainIdea:"作者主张正视抱负的健康价值，批评受教育者享受其回报却口头否认，也批评只求成功而隐藏抱负的虚伪。抱负并未消失，减少的是公开支持和承认；压抑它会令其转入隐蔽。结尾关注认真谋求生活进展的大多数人。",
 route:["认可抱负的条件与受教育者的反差","欲望未减，公开坦承却减少","公开支持困境与隐蔽化后果"],
 paragraphs:[{paragraphId:"p5-paragraph-1",title:"认可条件与否认的虚伪",summary:"回报应值得牺牲，传统需要广泛及受敬仰者认可；受教育者却声称放弃，而他们自己或家庭已经获益，作者用骑马者关门的比喻讽刺。",relation:"先给合理抱负的评价标准，再展示应当支持者的自相矛盾。"},{paragraphId:"p5-paragraph-2",title:"欲望与外表分离",summary:"成功和其标志的吸引力并未减弱；人们因担心他人眼光而不坦承梦想，三个生活例子与讽刺口号揭示表里不一。",relation:"解释为什么口头否认不等于真实欲望消失，并把虚伪具体化。"},{paragraphId:"p5-paragraph-3",title:"支持下降的真正后果",summary:"批评者多而公开辩护者少，健康抱负的支持降低；这不说明抱负终结，只是较少公开宣称，进而隐蔽化，结尾呈现两端喧嚣与中间努力生活者。",relation:"从个人言行反差推到社会氛围与后果，为公开、积极面对抱负提供方向。"}],
 sentenceRoles:Object.fromEntries(["建立回报值得牺牲才获认可的条件。","说明抱负传统需要广泛认同，尤其受教育者认可。","用强调句突出恰恰受教育者声称放弃的反差。","指出他们可能从自己或父辈抱负中获益最多。","用骑马者事后关门比喻评价其虚伪。","否定人们对成功及标志的兴趣已经减少。","区分物质标志外观变化与需求未减，时间措辞保留原卷疑点。","解释公开坦承减少源于对别人眼光的顾虑。","用三个并列人物主张与生活的反差展示虚伪。","用成功却不显抱负的口号讽刺概括行为。","对照批评者众多与辩护者少且乏善可陈。","指出把抱负当健康品质的社会支持可能降到很低。","用两个否定和一个肯定澄清真正变化。","说明公开承认减少导致抱负隐蔽化。","以三个方位人群收束，关注大多数认真谋生求进者。"].map((v,i)=>[s(i+1),v])),
 references:[{expression:"it",sentenceId:s(2),referent:"the tradition of ambition",targetSentenceIds:[s(2)],explanation:"两个must判断谈抱负传统。"},{expression:"them",sentenceId:s(2),referent:"people who are themselves admired",targetSentenceIds:[s(2)],explanation:"受教育者尤其包括在受敬仰者中。"},{expression:"they",sentenceId:s(4),referent:"the educated",targetSentenceIds:[s(3)],explanation:"获益者与声称放弃者为同一群体。"},{expression:"that of their parents and grandparents",sentenceId:s(4),referent:"父母和祖父母的抱负",targetSentenceIds:[s(4)],explanation:"that代ambition，非财富或人。"},{expression:"this",sentenceId:s(5),referent:"获益后又声称放弃抱负的做法",targetSentenceIds:[s(3),s(4)],explanation:"评价针对前两句的言行反差。"},{expression:"them",sentenceId:s(5),referent:"the horses",targetSentenceIds:[s(5)],explanation:"骑在马上者是受教育者，them是被骑的马。"},{expression:"such items",sentenceId:s(7),referent:"度假屋、欧洲旅行、宝马等成功标志",targetSentenceIds:[s(7)],explanation:"具体名字变化，仍谈这类需求。"},{expression:"which",sentenceId:s(9),referent:"fine hypocritical spectacles",targetSentenceIds:[s(9)],explanation:"第一关系从句补充整个场面；后面的who与whose各接一个人。"},{expression:"it",sentenceId:s(12),referent:"the support for ambition",targetSentenceIds:[s(12)],explanation:"比较社会支持的过去与当前程度。"},{expression:"This",sentenceId:s(13),referent:"健康抱负公开支持下降",targetSentenceIds:[s(11),s(12)],explanation:"由支持下降澄清它不意味着什么。"},{expression:"some of which",sentenceId:s(14),referent:"Consequences中的一些后果",targetSentenceIds:[s(14)],explanation:"整体为关系从句主语，嵌套that从句给内容。"}],
 timeline:[{label:"声称与所称放弃",event:"to have given up是完成不定式，所声称的放弃早于声称；不保证放弃真实发生。",evidence:[e(3,"have claimed to have given up","先后关系")]},{label:"马逃与关门",event:"比喻先马逃、后关门；骑马者自己已经得益，时间先后服务于讽刺。",evidence:[e(5,"after the horses have escaped","先发生事件"),e(5,"the educated themselves riding on them","受益者身份")]},{label:"当前与过去欲望",event:"现在兴趣和需求未显减少。第7句a decade or two years ago时间措辞有疑点，不转换为确定的二十年前。",evidence:[e(6,"now than formerly","相对比较"),e(7,"than a decade or two years ago","原卷异常时间短语")] }],
 voices:[{speaker:"受教育者所声称的立场",claim:"已经不再把抱负当理想。",boundary:"claimed只是声称；第4—5句以获益与比喻质疑其真诚。",evidence:[e(3,"have claimed to have given up on ambition as an ideal","声称内容")]},{speaker:"被讽刺人物的行为逻辑",claim:"成功可以不惜代价，但不要显得有抱负。",boundary:"这是作者讽刺性概括他人，并非作者给读者的建议。",evidence:[e(10,"For such people","适用对象"),e(10,"Succeed at all costs but avoid appearing ambitious","被概括口号")]},{speaker:"作者",claim:"抱负仍存在，减少的是公开支持与承认；将其逼入地下是负面后果，健康抱负值得正视。",boundary:"肯定健康抱负不等于赞成不择手段，也不能将not less说成所有人欲望暴增。",evidence:[e(12,"ambition as a healthy impulse","正面价值界定"),e(13,"it is less openly professed","变化范围"),e(14,"ambition is driven underground, or made sly","负面后果")] }],
 practice:[{id:"three-stage-route",revision:1,kind:"order",prompt:"按原卷三段顺序排列论证。",options:["评价条件与受益后否认的虚伪","欲望未减而坦承减少的实例","社会支持下降与隐蔽化后果"],answer:JSON.stringify(["评价条件与受益后否认的虚伪","欲望未减而坦承减少的实例","社会支持下降与隐蔽化后果"]),evidence:"This does not mean that ambition is at an end",feedback:"第一段先设标准再批评反差，第二段用需求与例子说明伪装，第三段澄清抱负仍在而公开支持变少。",conceptId:"passage-route",errorType:"passage-logic",mapRevealsAnswer:true,leaksToTaskIds:["real-change"]},{id:"real-change",revision:1,kind:"choice",prompt:"作者认为真正减少了什么？",options:["对抱负的公开支持和坦承","全部人的成功欲望","所有物质生活需求"],answer:"对抱负的公开支持和坦承",evidence:"it is less openly professed",feedback:"not mean排除抱负终结与冲动消失，but only肯定公开宣称较少；not less又说明成功兴趣未显减少。",conceptId:"negation-contrast",errorType:"passage-logic",mapRevealsAnswer:true,leaksToTasks:[{sentenceId:s(6),taskId:"not-less-interest"},{sentenceId:s(13),taskId:"three-contents"},{sentenceId:s(13),taskId:"less-not-none"}]},{id:"satire-boundary",revision:1,kind:"choice",prompt:"成功却不显抱负的口号如何进入作者论证？",options:["概括被批评者的虚伪，衬出应坦诚面对抱负","作者认可隐瞒抱负是唯一健康办法","证明受教育者从未从抱负获益"],answer:"概括被批评者的虚伪，衬出应坦诚面对抱负",evidence:"Succeed at all costs but avoid appearing ambitious",feedback:"三个生活例子先显示表里不一，口号随后讽刺其行为；作者批评公开否认造成的隐蔽化，不倡导隐瞒。",conceptId:"author-voice",errorType:"passage-logic",mapRevealsAnswer:true,leaksToTasks:[{sentenceId:s(10),taskId:"ironic-rule"}]}],
};
