/**
 * Reviewed equivalences in the imported corpus, scoped to a lemma and one POS.
 * These group wording variants, not the underlying articles or their exact glosses.
 * Mixed-POS and mixed-meaning dictionary summaries are intentionally not assigned
 * to a narrower sense. IDs describe meanings and do not depend on Chinese text.
 */
import { normalizeMeaning } from "./semantic-normalization";

type Alias = { id: string; pos: string; meaning: string };
type Group = readonly [term: string, id: string, pos: string, meaning: string, ...variants: string[]];

const groups: readonly Group[] = [
  ["create", "create", "v", "建立；创建；产生", "建立；创建", "培养；建立", "提供；建立", "培养", "形成；培养", "造成；产生", "造成；形成"],
  ["deliver", "convey", "v", "送达；输送", "提供；传递", "递送；交付"],
  ["spend", "expenditure", "n", "花费；支出", "花费；消费"],
  ["decline", "decrease", "n", "衰退；下降", "衰退", "下降"],
  ["develop", "develop", "v", "发展；形成", "发展", "发展；开发"],
  ["limit", "restriction", "n", "限制", "限制规定"],
  ["limit", "restrict", "v", "限制", "限制广告投放"],
  ["regard", "consider", "v", "看待；评价", "看作", "把……视为"],
  ["return", "go-back", "v", "返回", "恢复；回到"],
  ["bring", "bring", "v", "带来", "带来；使出现", "带来；此处bring back为带回"],
  ["course", "course", "n", "发展进程；走向", "轨迹；进程"],
  ["early", "early", "adv", "较早地", "早"],
  ["early", "early", "adj", "早期的；初期的", "早期的；较早地"],
  ["executive", "manager", "n", "企业高管", "经营管理人员；执行主管", "经营管理人员"],
  ["experience", "experience", "v", "经受；承受", "经历；发生", "经历；体验"],
  ["last", "previous", "adj", "上一个的", "上一的"],
  ["line", "text-line", "n", "行；文本行", "行", "诗行"],
  ["next", "next", "adj", "下一个的", "下一份的", "下一年的"],
  ["question", "question", "n", "问题；疑问", "问题；所考虑的事"],
  ["small", "small", "adj", "小的；少量的", "更小的", "小的；较小的", "小型的；人数少的", "更少的"],
  ["stop", "stop", "v", "停止", "停止；不再"],
  ["stress", "pressure", "n", "压力", "紧张压力"],
  ["stress", "emphasize", "v", "强调", "强调；重视"],
  ["struggle", "struggle", "v", "艰难挣扎；苦苦应对", "艰难努力"],
  ["success", "success", "n", "成功", "成功；成功的结果或事物", "成功；成功经历"],
  ["word", "word", "n", "词；词语；措辞", "词；单词", "词；用语", "言辞"],
  ["year", "year", "n", "年", "年；年度", "年；年份", "年；一年", "年龄段；年"],
  ["build", "build", "v", "建设；建造", "建造", "建造；修建"],
  ["hard", "difficult", "adj", "困难的", "更困难的"],
  ["impact", "effect", "n", "影响；冲击", "影响"],
  ["big", "large", "adj", "大的", "大型的", "大的；宽大的", "大型的；规模大的"],
  ["common", "usual", "adj", "普通的；常见的", "普遍的；常见的", "普遍存在的"],
  ["focus", "focus", "v", "集中；聚焦", "把关注重点放在", "着重于；集中于", "集中关注；焦点"],
  ["sale", "sales", "n", "销售；销售额", "销售；销售业绩", "销售；销量"],
  ["talk", "talk", "n", "谈话；交谈", "谈话（书名 Divorce Talk 的组成部分）", "会谈；讨论"],
  ["board", "committee", "n", "委员会；董事会", "董事会"],
  ["writing", "text", "n", "作文；所写文章", "作文；写作内容", "著作；作品"],
  ["approach", "method", "n", "方法；途径", "做法；方案", "办法；处理方式"],
  ["authority", "authority", "n", "权威；公信力", "权威；号召力"],
  ["back", "support", "v", "支持", "支持；支撑"],
  ["base", "basis", "v", "以……为基础", "以……为依据", "以……为基础；基础"],
  ["benefit", "benefit", "n", "好处；益处", "好处；收益"],
  ["buy", "buy", "v", "购买", "收购；购买"],
  ["claim", "assert", "v", "声称；宣称", "声称", "主张；声称"],
  ["compare", "compare", "v", "比较；相比", "比较", "相比"],
  ["divorce", "divorce", "n", "离婚", "离婚；离婚案例"],
  ["domestic", "household", "adj", "家用的；家庭的", "家庭的"],
  ["easy", "easy", "adj", "容易的；不费力的", "更容易的", "较容易的", "轻易获得的"],
  ["efficiency", "efficiency", "n", "效率", "效率；高效性", "效率；运行能效", "效率；效能"],
  ["endure", "tolerate", "v", "承受；忍受", "经历并忍受", "忍受"],
  ["example", "instance", "n", "例子；实例", "例子", "例子；做法"],
  ["fashion", "fashion", "n", "时尚；潮流", "风尚；流行", "风尚；潮流", "时尚；风尚"],
  ["history", "history", "n", "历史；发展历程", "历史", "历史；经历", "历史；过去情况"],
  ["human", "human", "adj", "人的；人类的", "人类的"],
  ["idea", "idea", "n", "想法；观念", "想法；看法", "思想；观念"],
  ["keep", "continue", "v", "使保持", "使持续", "留住；使继续留任"],
  ["know", "know", "v", "知道；了解", "知道"],
  ["lack", "lack", "n", "缺乏；不足", "缺乏"],
  ["late", "late-period", "adj", "末期的；后期的", "年代后期的"],
  ["lose", "lose", "v", "失去；丢失", "失去", "损失"],
  ["man", "male", "n", "男人；男子", "男性"],
  ["person", "person", "n", "人；个人", "人们", "人", "人；人员"],
  ["private", "non-state", "adj", "私营的；非政府的", "私营的"],
  ["proportion", "share", "n", "比例；所占份额", "广告收入占全部收入的比例"],
  ["proportion", "ratio", "n", "比例关系；尺度配比", "建筑的比例与尺度关系"],
  ["reason", "reason", "n", "理由；原因", "原因"],
  ["relate", "connect", "v", "相关的；有关联的", "有关联"],
  ["review", "critique", "n", "评论；评述", "评论；评测"],
  ["shift", "change", "v", "变化；转变", "转变；摇摆", "转移；改变"],
  ["sign", "sign", "v", "签名；署名", "签约；签字加入"],
  ["speed", "accelerate", "v", "加速", "加快"],
  ["store", "shop", "n", "商店", "商店；百货商店"],
  ["succeed", "succeed", "v", "成功", "成功；取得进展"],
  ["survive", "survive", "v", "存活", "留存", "存活；维持经营"],
  ["tend", "tendency", "v", "往往；倾向于", "往往", "倾向于"],
  ["try", "attempt", "v", "努力；尝试", "设法；努力", "尝试"],
  ["day", "day", "n", "天；日", "天"],
  ["day", "era", "n", "时期；时代", "所处时代"],
  ["letter", "correspondence", "n", "信；书信", "信件", "信；邮件书信文本"],
  ["professional", "professional", "adj", "专业的", "专业的；面向专业者的", "专业的；专业人士的"],
  ["publication", "publishing", "n", "公开发表；公布", "发表；公开"],
  ["select", "select", "v", "选择；挑选", "挑选；遴选", "挑选"],
  ["comment", "comment", "n", "评论；意见", "评论；发言"],
  ["design", "design", "n", "设计", "设计方案"],
  ["perform", "perform", "v", "表现", "表现；运行状况如何"],
  ["popular", "popular", "adj", "受欢迎的；流行的", "受欢迎的", "流行的；广为使用的", "流行的；普遍使用的"],
  ["associate", "connect", "v", "联系；关联", "联系；使有关联"],
  ["accept", "accept", "v", "接受", "接受；承认"],
  ["advance", "progress", "n", "进步；发展", "进步"],
  ["appear", "appear", "v", "出现", "出现；产生"],
  ["avoid", "avoid", "v", "避免", "避免；躲开", "避免；回避"],
  ["child", "child", "n", "孩子；儿童", "孩子", "儿童"],
  ["country", "country", "n", "国家", "国家；国家整体", "国家；全国"],
  ["danger", "danger", "n", "危险", "危险；危害", "危险；威胁"],
  ["deny", "withhold", "v", "剥夺；拒绝给予", "使无法获得；不予给予"],
  ["describe", "describe", "v", "描述", "描述；说明", "描述；称为"],
  ["drop", "withdraw", "v", "退出；中途离开", "中途退出"],
  ["education", "education", "n", "教育", "教育；教育制度", "教育；受教育程度"],
  ["enjoy", "enjoy", "v", "享受", "享受；喜欢"],
  ["essential", "essential", "adj", "必不可少的", "必不可少的；重要的"],
  ["fade", "fade", "v", "逐渐减弱", "逐渐减弱；褪去"],
  ["feel", "feel", "v", "感觉；感受", "感到", "感受；产生（需求）"],
  ["imply", "imply", "v", "意味着；暗示", "暗示", "意味着；暗含"],
  ["interpret", "interpret", "v", "解释；阐释", "解读；说明"],
  ["job", "employment", "n", "工作；职位", "工作", "岗位；职位"],
  ["kind", "type", "n", "种类；类别", "种类"],
  ["let", "allow", "v", "让；任由", "让；放任"],
  ["manifest", "show", "v", "显示；表明", "表现；表明", "显示；显露"],
  ["mass", "people", "n", "民众；大众", "大众；大批普通人"],
  ["means", "means", "n", "方式；手段", "手段；工具"],
  ["moral", "moral", "adj", "道德的", "道德方面的"],
  ["movement", "movement", "n", "运动；思潮", "运动；（艺术）思潮"],
  ["narrow", "narrow", "v", "缩小；变窄", "缩小"],
  ["near", "near", "adj", "临近的", "接近的"],
  ["period", "period", "n", "时期；一段时间", "时期；时段", "一段时期"],
  ["predominance", "predominance", "n", "主导地位；优势地位", "优势地位", "主导地位"],
  ["recent", "recent", "adj", "最近的", "近来的", "近期的"],
  ["reform", "reform", "n", "改革", "改革；改良"],
  ["relieve", "alleviate", "v", "缓解；减轻", "缓解；解除"],
  ["responsible", "cause", "adj", "负有责任的；造成某事的", "负有责任的；造成……的"],
  ["reveal", "reveal", "v", "揭示；显示", "揭示", "显现；体现"],
  ["reward", "reward", "v", "奖励；回报", "给予回报"],
  ["save", "rescue", "v", "挽救；使免于毁坏", "挽救；使免于衰亡"],
  ["society", "society", "n", "社会", "社会；社会群体"],
  ["stand", "state", "v", "处于某状况", "处于"],
  ["sweep", "sweep", "v", "席卷", "迅速席卷；蔓延", "席卷；大举涌入"],
  ["woman", "woman", "n", "女性；女人", "女性；妇女", "女性"],
  ["agree", "agree", "v", "同意；赞同", "认同；赞同", "同意"],
];


const aliases = new Map<string, Alias>();
for (const [term, id, pos, meaning, ...variants] of groups) {
  for (const variant of [meaning, ...variants]) {
    aliases.set(`${term}\u0000${pos}\u0000${normalizeMeaning(variant)}`, { id, pos, meaning });
  }
}

/** POS is the normalized single POS; no partial matching against mixed-POS rows. */
export function getContentSemanticAlias(termKey: string, pos: string, meaning: string): Alias | undefined {
  return aliases.get(`${termKey}\u0000${pos}\u0000${normalizeMeaning(meaning)}`);
}
